### ISSUE TITLE
Unfinished download always removed

### ISSUE THREAD

**Issue by Madaft** [TeamNewPipe/NewPipe#7254] opened 2021-10-15 08:29 UTC
### Checklist

- [x] I am using the latest version - 0.21.12 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Try to download something first (video/music/srt), and pause the download.
2. Close the app, and open it again.
3. Open downloads menu, it will needs some time to reload, then the notification 'app is not responding' appear, and then choose wait.
4. Your downloading list is gone, but file is still exist and can't be open because it's not fully download.

### Actual behavior
 The downloading list is gone, it's annoying because i need to retry from beginning everytime or you have to not close the app.

### Screenshots/Screen recordings

![Screenshot_2021-10-15-15-04-54-714_org schabi newpipe](https://user-images.githubusercontent.com/92572661/137456794-8524c4d2-7562-49ba-9fc3-998ae5043543.jpg)
![Screenshot_2021-10-15-15-06-12-793_org schabi newpipe](https://user-images.githubusercontent.com/92572661/137456808-406d6b98-10d9-4fa7-a58b-6caf0f678cc4.jpg)
![Screenshot_2021-10-15-15-05-20-522_org schabi newpipe](https://user-images.githubusercontent.com/92572661/137456819-91d23009-335e-47e3-92f1-9702dfd4c1d9.jpg)
the chronological is, I'm downloading something, pause it, close the app, open app again, go to downloads list, it goes blank for a second, notification 'app is not responding' appear, click wait, it goes normal, the downloading is gone.

PS. You can see at my screenshot, it shows that i only downloaded the Sustainable #1 videos. But actually, i am downloading the #234 too, and they're not finished yet. Now their download list are gone because Newpipe has bug that won't reload the unfinished download list on my device. But the #234 files are saved on my storage, and they can't be fully opened/ viewed.

### Device info

 - Android version/Custom ROM version:
 - Device model: Redmi Note 10 Pro
*I already make sure that the battery saver for Newpipe is no restrictions

**Comment by mhmdanas** [comment] 2021-10-16 08:34
Duplicate of #7059.

**Closed by mhmdanas** 2021-10-16 08:34 UTC
Labels: bug
