### ISSUE TITLE
Double subscription glitch.

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#2537] opened 2019-08-18 12:35 UTC
Connected to #2529, for some reason I have one channel twice. As this happened, selecting said channel from subscription tab failed so I subscribed from search again, and now both entries work. I can provide backup data for the app if requested.

**Comment by gkeegan** [comment] 2019-08-18 14:16
Duplicate of #2167

**Closed** 2019-08-18 15:06 UTC
