### ISSUE TITLE
Video doent play on other resolutions

### ISSUE THREAD

**Issue by aaazv** [TeamNewPipe/NewPipe#3140] opened 2020-02-25 04:13 UTC
https://gofile.io/?c=vvYhS7

Check this video I recorded for complete info. 
This happens a lot of times with many videos.

Made me think for a long time that newpipe doesnt work untill thought about changing the reso!

**Comment by Stypox** [comment] 2020-02-25 08:05
Duplicate of #2673 and others

**Closed** 2020-02-25 09:09 UTC
