### ISSUE TITLE
Feature Request: Block Channels

### ISSUE THREAD

**Issue by LordCorvin** [TeamNewPipe/NewPipe#2302] opened 2019-04-20 11:43 UTC
This is feature request which I beleive would improve the app. Channel blocking, there a bunch of clickbaiting channels which would be nice to block.

**Comment by Symbian9** [comment] 2019-04-21 15:39
You mean in search results? Think "Skip Channel in Search" or "Ignore Channel in Search" is better name for this option

**Comment by justanidea** [comment] 2019-04-21 16:07
Probably in suggestions too

**Comment by nostromov** [comment] 2019-04-22 04:11
Channel Blacklist doesn't exclude them? It should, it does, right? :o

**Comment by TobiGr** [comment] 2019-04-23 10:18
Duplicate of #1815

**Closed by TobiGr** 2019-04-23 10:18 UTC
Labels: duplicate
