### ISSUE TITLE
Notifications for New Videos

### ISSUE THREAD

**Issue by HonestAbe7** [TeamNewPipe/NewPipe#7241] opened 2021-10-13 22:12 UTC
I recently discovered that I can use the RSS feed to get notifications for new videos. This is so cool. Is there a way to get this feature inside the app instead of outside like YouTube does? I don't mind using an RSS reader to get new video posts but only if I need to.

**Comment by TiA4f8R** [comment] 2021-10-13 22:45
Please don't remove the template when opening an issue: there are good reasons to keep it, like to avoid creating issue duplicates.

Your issue is a duplicate of #1086. A PR which implemented this feature should be merged soon: see #2335.

Closing this issue.

**Closed by TiA4f8R** 2021-10-13 22:45 UTC
Labels: question
