### ISSUE TITLE
Long press on first video thumbnail should enable bulk selection

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5832] opened 2021-03-15 07:44 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Bulk selection is helpful for temporary enqeuing and downloading videos at once. Long press on thumbnail should enable bulk selection. 

More suggestions in #5657

Please be noted that "Long Press on first video thumbnail" will enable bulk selection. Single tap on next videos will select next videos. Long press once again on any video thumbnail will select that video as second video for bulk selection. But long press on title bar should show long press menu as usual as a user may change his mind. Single tap on title bar or thumbnail will play the video as the user may want to check his videos (for example, episode 65 and episode 66 are confusing). Cancel option suggestion in #5657.

**Comment by MD77MD** [comment] 2021-03-20 23:58
very true

**Comment by TippyLion28** [comment] 2022-07-06 09:56
Why was this closed as completed?

**Comment by opusforlife2** [comment] 2022-07-10 18:50
The feature wasn't introduced back then. It was just 'closed'.

It's actually a bit careless of GH to retrospectively mark all prior closed issues as 'completed'. That's misleading information.

**Comment by TippyLion28** [comment] 2022-07-10 20:17
Also a bit annoying that @SameenAhnaf made me close my issue as a duplicate of theirs only to close this issue too?? Wtf dude

**Comment by TippyLion28** [comment] 2022-07-11 05:12
Too late now I've already opened a new issue. Don't mess people around

**Comment by SameenAhnaf** [comment] 2022-07-11 07:43
@opusforlife2 Choose which one to close. 🙂

**Closed** 2022-07-12 11:41 UTC
Labels: enhancement

**Comment by opusforlife2** [comment] 2022-07-16 08:03
> Don't mess people around

🤣🤣🤣

**Comment by SameenAhnaf** [comment] 2022-07-16 11:17
> Don't mess people around

Oh no! Am I getting capital punishment? Please forgive me🙏🥺
