### ISSUE TITLE
Videos are not completely fullscreen (last issue was closed by mistake)

### ISSUE THREAD

**Issue by PrinceRaj53** [TeamNewPipe/NewPipe#8776] opened 2022-08-13 17:19 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1.Play any video
2.Switch to full screen
3.Touch the arrow on top right corner
4.Set the "zoom" option
5.You'll see that the video is still not completely full screen & there is still space left on the left side.

### Expected behavior

The videos should be played full screen.

### Actual behavior

The videos are not in fullscreen.

### Screenshots/Screen recordings

This is how it should've worked :

![Should be like this](https://user-images.githubusercontent.com/96355726/184504180-dcb40104-1fd4-4031-aed0-bfedfaa10ee0.jpg)

And this is how it looks right now :

![Not fullscreen](https://user-images.githubusercontent.com/96355726/184504200-696138bd-c06c-478e-9900-cb7daf51a6c6.jpg)

### Logs

None.

### Affected Android/Custom ROM version

Android 12

### Affected device model

Realme GT Neo 2(RMX3370)

### Additional information

The issue was present in the previous version as well as this version. Only in the debug apk that was provided just before 0.23.2 it actually shows the video in full screen, edge to edge, without any issues.

The debug apk I was talking about is this one : https://github.com/TeamNewPipe/NewPipeExtractor/pull/891 

This is the only one where the video was completely fullscreen.

**Comment by opusforlife2** [comment] 2022-08-13 18:15
Let's stay on #8774. No need for a new one. Marking as duplicate.

**Comment by opusforlife2** [comment] 2022-08-13 18:15
Duplicate of #8774

**Closed** 2022-08-13 18:15 UTC
Labels: bug, needs triage
