### ISSUE TITLE
Dont hide a whole page when an error occurs.

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#5938] opened 2021-03-28 10:39 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Lets say a network error occurs, we get this screen that masks out the video feed that has already been loaded, hiding information:

![kek](https://user-images.githubusercontent.com/74684948/112749442-8acc3c00-8fc2-11eb-871a-ade7d7c7f335.jpg)

I propose a solution could be something like this. The already loaded content is still visible:

![bruh](https://user-images.githubusercontent.com/74684948/112749472-a6cfdd80-8fc2-11eb-8f2c-c4828337ee99.jpg)

**Comment by Stypox** [comment] 2021-03-28 22:41
This shouldn't happen, it's a bug. The behaviour you described is exactly what should already happen. Could you provide some steps to reproduce?

**Comment by Hogerys** [comment] 2021-03-29 18:00
@Stypox wtf no this isnt a bug. This is how the whole thing is implemented. Read again please.

**Comment by Stypox** [comment] 2021-03-29 20:48
I implemented exactly what you proposed in the last version. The app should show the full error panel only if there are no items already being shown, and otherwise would show the Snackbar at the bottom, exactly as you are asking. If it doesn't work properly apparently that's a bug. Please provide steps to reproduce.

**Comment by Stypox** [comment] 2021-03-29 20:50
If this is strictly related to feed then duplicate of #5452

**Closed by Stypox** 2021-03-29 20:50 UTC
Labels: enhancement, feed

**Comment by Hogerys** [comment] 2021-04-02 13:32
How can i reopen?

**Comment by Hogerys** [comment] 2021-04-02 13:35
Steps: Request feed update.
If no internet whole page turns black instead of snackbar.

**Comment by Stypox** [comment] 2021-04-02 16:12
I said, duplicate of #5452

**Comment by Hogerys** [comment] 2021-04-04 00:06
Ok but how can i reopen the issue?

**Comment by Stypox** [comment] 2021-04-04 06:41
You shouldn't reopen the issue, as it is a duplicate

**Comment by Hogerys** [comment] 2021-04-13 14:20
I would like to reopen the issue.
