### ISSUE TITLE
Long standing bug : list in landscape mode

### ISSUE THREAD

**Issue by jediafr** [TeamNewPipe/NewPipe#2774] opened 2019-11-02 10:10 UTC
Didnt noticed this until i tried to use my tablet in lanscape.

How to reproduce : 
rotate screen and select list of feeds.
The list will stop after the 9th videos, the sandbox will spin forever.

Temporary solution : rotate in portrait.

- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment] 2019-11-05 13:57
Duplicate of #1974

**Closed by Stypox** 2019-11-05 13:57 UTC
