### ISSUE TITLE
Background music playback error

### ISSUE THREAD

**Issue by shotgun9076** [TeamNewPipe/NewPipe#2785] opened 2019-11-05 22:37 UTC
When looking up playlist(s) upon pressing background on my device to play music, it produces (error)-cannot play music. 
Also does this with videos. 

{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=JJZSszc-qF4",
   "content_language": "GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.17.4",
   "os": "Linux samsung\/beyond2qlteue\/beyond2q:9\/PPR1.180610.011\/G975U1UEU2BSGL:user\/release-keys 9 - 28",
   "time": "2019-11-05 22:45",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerConfig(YoutubeStreamExtractor.java:660)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:638)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAt

**Comment by shotgun9076** [comment] 2019-11-05 22:44
Have sent numerous crash reports via email

**Comment by Stypox** [comment] 2019-12-03 14:33
Duplicate of #2787

**Closed by Stypox** 2019-12-03 14:33 UTC
