### ISSUE TITLE
Suggestion: automatic play button in background player.

### ISSUE THREAD

**Issue by MarioMey** [TeamNewPipe/NewPipe#2890] opened 2019-12-24 16:33 UTC
I got confused some time ago when I didn't know how to make player to one song after the other... finally, I discovered that I had to touch the "Automatic play" swich... **before touching background play** (or whatever it is called... I use it in spanish ;) ).

Yesterday, my brother installed NP and he got confused in the same way.

Are my brother and I the problem...? Or that option is a bit confusing?

When I want to play something, I think in touch "play". The moment that I decide to listen more songs... could be after touching play. If this happens, there's no way to activate it.

**Comment by Stypox** [comment] 2020-01-02 21:14
Duplicate of #1761

**Closed by Stypox** 2020-01-02 21:14 UTC
