### ISSUE TITLE
Can't Play Videos on Sony Smart (BRAVIA Android TV)

### ISSUE THREAD

**Issue by TheFloatingBrain** [TeamNewPipe/NewPipe#8795] opened 2022-08-15 05:35 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Download NewPipe on Sony (Andriod 9) Smart TV (Bravia Android TV)
2. Try to play a video
3. Video will not load (see some icons appear then disappear), asks if you want to reload
4. Press reload, video still will not load
5. Repeat after attempting to turn off other things that are displayed (comments, description, etc under Settings -> Content)
 

### Expected behavior

Video play

### Actual behavior

Video will not load (neither will comments)

### Logs

{"user_action":"requested stream","request":"https://www.youtube.com/watch?v=s3L2rE39pCc","content_language":"en-US","content_country":"US","app_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.23.1","os":"Linux Android 9 - 28","time":"2022-08-15 01:01","exceptions":["org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)\n\tat org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)\n\tat org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\n"],"user_comment":""}

### Affected Android/Custom ROM version

Andriod 9 (Kernel Version 4.9.125 March 5th 2021) Build BRAVIA_ATV3_4k_UC-user 9 PTT1.190515.001.S43671651

### Affected device model

Sony Smart TV Bravia Android TV

### Additional information

I installed NewPipe over wifi using ADB, other apps seem to work with this. I played with it a bit, added a couple channels, etc. then set out to import my data, which took a while, as I had to dig into the NewPipe code to understand why it wouldn't use the file manager app I installed (Simple File Manager Pro from F-Droid) would not work (turns out it need an app that will recognize the .zip MIME type, "Material Files" (also from F-Droid) does the trick). I tried to play a video AFTER getting the data, and it would not load. The data was from the previous version of New Pipe so I cleared storage and tried again, both times I tried turning off comments, description, etc. (most/all of the stuff under Settings->Content). I then updated NewPipe on my other device, exported the data again, and tried again, nothing changed (did not expect it too). It was a bit of a pain trying to get the error log from the crash reporter, that alone took almost hour 😅

**Comment by TheFloatingBrain** [comment] 2022-08-15 05:46
[oops](https://github.com/TeamNewPipe/NewPipe/issues/8384)

**Comment by TheFloatingBrain** [comment] 2022-08-15 05:52
That one is about the video not playing after another video, however mine will not play at all, [I want to use NewPipe specifically because I dont have to sign in and I can take my data wherever I want to go so I am not interested in SmartTubeNext](https://github.com/TeamNewPipe/NewPipe/issues/8369)

**Comment by mhmdanas** [comment] 2022-08-15 07:45
Duplicate of #8760. 0.23.2 fixes this error.

**Closed by mhmdanas** 2022-08-15 07:45 UTC
Labels: bug, needs triage

**Comment by TheFloatingBrain** [comment] 2022-08-15 14:52
I am using 0.23.2, I also noticed its not working on my phone, I don't think its specific to my TV

**Comment by TheFloatingBrain** [comment] 2022-08-15 15:09
> Duplicate of #8760. 0.23.2 fixes this error.

Sorry, my bad, I thought I was on the latest version, updated and it works :)
