### ISSUE TITLE
Errors on refreshing what's new feed when you have subscribed to a terminated channel

### ISSUE THREAD

**Issue by nikhilCad** [TeamNewPipe/NewPipe#3602] opened 2020-05-17 04:11 UTC
### Version

-
0.19.3

### Steps to reproduce the bug

Subscribe to a channel that has high risk of being taken down due to copyrights(channel that post pirated TV shows). Once the account get suspended, you will get error each time when refreshing what's new

### Expected behavior

Newpipe handles it internally
### Actual behaviour

Some errors occured message shows at bottom
### Screenshots/Screen recordings

Now , sorry. I have unsubscribed to that channel and now can't reproduce the bug. Again, sorry

**Comment by B0pol** [comment] 2020-05-17 10:30
Duplicate of #3313

**Closed by B0pol** 2020-05-17 10:30 UTC
Labels: bug
