### ISSUE TITLE
Update alert downloads wrong version

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#3952] opened 2020-07-27 20:55 UTC
![Screenshot_20200727-225408_Samsung Internet](https://user-images.githubusercontent.com/26146502/88591148-2f753300-d05c-11ea-8f2b-8e7e55d37b05.jpg)
After clicking the popup with 0.19.7 update, it downloaded 0.19.6 apk (which was my current version).

**Comment by MD77MD** [comment] 2020-07-27 21:00
the same here!

**Comment by kubo6472** [comment] 2020-07-27 21:03
![Screenshot_20200727-230217_My Files](https://user-images.githubusercontent.com/26146502/88591816-3e101a00-d05d-11ea-8a89-07325333a453.jpg)
Proof, that it's not just named wrong, but actually, there's a size difference.

**Comment by MD77MD** [comment] 2020-07-27 21:16
yes.. it's the actual 19.6 apk

**Comment by FireMasterK** [comment] 2020-07-27 21:34
I can't replicate this, it downloaded 0.19.7 when I clicked on the notification.

**Comment by impti** [comment] 2020-07-27 21:35
I confirm this. Was suggested to update to 0.19.7 but the pop-up leads to the .6 version.

**Comment by MD77MD** [comment] 2020-07-27 21:36
> I can't replicate this, it downloaded 0.19.7 when I clicked on the notification.

Check newpipe version in about.

**Comment by FireMasterK** [comment] 2020-07-27 21:43
> > I can't replicate this, it downloaded 0.19.7 when I clicked on the notification.
> 
> Check newpipe version in about.

I did, it downloaded the right version for me.

Maybe this was caused by a caching issue so only selective people get affected.

**Comment by TobiGr** [comment] 2020-07-27 21:43
I cannot reproduce this, too.
Our API links to the correct APK: https://newpipe.schabi.org/api/data.json

**Comment by kubo6472** [comment] 2020-07-27 21:46
I have a theory that someone first updated the version code (which triggered the notification) then it updated the URL. Meaning all notifications that popped up were linking to the old version.

**Comment by TobiGr** [comment] 2020-07-27 21:59
@kubo6472 I updated the attached file, but why should GitHub link to an old release in this case? Anyway, I think we can close this.

**Closed by TobiGr** 2020-07-27 21:59 UTC
