### ISSUE TITLE
Rotation crash on „Video not available“ page

### ISSUE THREAD

**Issue by HugeFrog24** [TeamNewPipe/NewPipe#5941] opened 2021-03-28 12:40 UTC
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a video that's not available (invalid URL/private video/whatever)
2. Rotate the screen by 90°

### Actual behaviour

NewPipe throws an UI error

### Expected behavior

Just rotate the page by 90°

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/62775760/112752430-3c736900-8fd3-11eb-9de1-59a109b83e4e.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3792)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5957)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5863)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
	at org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:55)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:279)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:139)
	at android.app.Activity.performCreate(Activity.java:8198)
	at android.app.Activity.performCreate(Activity.java:8182)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
	... 13 more
Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.fragments.EmptyFragment.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
	... 37 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 11 R, Stock ROM
 - Device model: Samsung Galaxy Note 10+

**Comment by sauravrao637** [comment] 2021-04-04 20:49
I think this bug has been fixed and the thread can be closed because I followed the steps and on rotating it shows "Content Unavailable , report".

**Comment by peat80** [comment] 2021-04-07 08:47
It still crashes for me while using nightly build 141. Or is there a specific pr that is not merged yet that is supposed to fix this?

**Comment by sauravrao637** [comment] 2021-04-07 08:54
I am using 0.21.0 , @HugeFrog24 @peat80   can you please provide a link you are facing the crash with?

**Comment by peat80** [comment] 2021-04-07 09:23
> I am using 0.21.0 , @HugeFrog24 @peat80 can you please provide a link you are facing the crash with?

I tried premiere videos on my subscribed channels and they all fail. 

https://www.youtube.com/watch?v=PsIqN22cPuA

https://www.youtube.com/watch?v=gB_BrIE3kRE

**Comment by sauravrao637** [comment] 2021-04-07 09:26
yea , the bug is still there :(

**Comment by Nothing4You** [comment] 2021-04-21 22:07
I was seeing the same on 0.21.1 so I went to try out v0.21.2_RC2 from #6052 to see if this was resolved already but it looks like it got "worse", as it doesn't even open the builtin crash reporter for me, just closes the app.
Seeing this in the logs I'm wondering though if this may be intended behavior and the crash log is automatically submitted?
```
04-21 23:53:24.822 27150 29836 I ACRA    : Sending report /data/user/0/org.schabi.newpipe.debug.release0212/app_ACRA-approved/2021-04-21T23:53:24.736+02:00.stacktrace
```

I can reproduce it with multiple available videos, including https://youtu.be/dQw4w9WgXcQ, just by rotating before the video itself is loaded.

demo:

https://user-images.githubusercontent.com/3694534/115626661-1bfeac00-a2fe-11eb-9a4e-38bb657b4c8c.mp4

<details><summary><b>Crash log (from logcat)</b></summary><p>

```
04-21 23:53:24.691 29734 29734 D AndroidRuntime: Shutting down VM
04-21 23:53:24.693 29734 29734 E AndroidRuntime: FATAL EXCEPTION: main
04-21 23:53:24.693 29734 29734 E AndroidRuntime: Process: org.schabi.newpipe.debug.release0212, PID: 29734
04-21 23:53:24.693 29734 29734 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe.debug.release0212/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:55)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:279)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:141)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	... 13 more
04-21 23:53:24.693 29734 29734 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.fragments.EmptyFragment.<init> []
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at java.lang.Class.getConstructor0(Class.java:2332)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at java.lang.Class.getConstructor(Class.java:1728)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
04-21 23:53:24.693 29734 29734 E AndroidRuntime: 	... 37 more
04-21 23:53:24.694 29734 29734 E ACRA    : ACRA caught a RuntimeException for org.schabi.newpipe.debug.release0212
04-21 23:53:24.694 29734 29734 E ACRA    : java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe.debug.release0212/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.os.Looper.loop(Looper.java:223)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7660)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
04-21 23:53:24.694 29734 29734 E ACRA    : Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:55)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:279)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:141)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.Activity.performCreate(Activity.java:8000)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.Activity.performCreate(Activity.java:7984)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
04-21 23:53:24.694 29734 29734 E ACRA    : 	... 13 more
04-21 23:53:24.694 29734 29734 E ACRA    : Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.fragments.EmptyFragment.<init> []
04-21 23:53:24.694 29734 29734 E ACRA    : 	at java.lang.Class.getConstructor0(Class.java:2332)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at java.lang.Class.getConstructor(Class.java:1728)
04-21 23:53:24.694 29734 29734 E ACRA    : 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
04-21 23:53:24.694 29734 29734 E ACRA    : 	... 37 more
```
</details>
<hr>

**Comment by rancidfrog** [comment] 2021-04-26 17:13
This crash apparently also happens before a video loads.
1. Share video to newpipe video mode
2. Rotate device before video url is parsed completely and loaded
3. App crashes: 

________

Crash when rotate device before video loads when sharing
### Steps to reproduce the bug

1. Open youtube video in browser
2. Share video to newpipe video mode
3. Rotate device before video loads (Bad connection makes it worse as it takes longer to load video giving it more time to crash, as if the video loads before rotating app does not crash)
4. App crashes when you rotate device before newpipe   parses and loads youtube video




### Actual behaviour

App crashes


### Expected behavior

Switch to landscape mode without crashing


### Screenshots/Screen recordings






### Logs




## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ UM
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5279)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5187)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
	at org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:55)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:279)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:139)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 13 more
Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.fragments.EmptyFragment.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
	... 37 more

```
</details>
<hr>




### Device info

 - Android version/Custom ROM version: Android 10 | LineageOS

**Comment by SameenAhnaf** [comment] 2021-04-29 10:50
I am facing the same bug if all video tabs (description, comments and related stream) are disabled. It doesn't tend to appear if one or more tabs are enabled.

Also, facing following bugs.
1. App crashes without any error report.
2. Notification player continues streaming with no sound and ending.
3. Not possible to close the player by "Close" button on notification player. However, swiping or "Clear notification" works even while and after this strange streaming


https://user-images.githubusercontent.com/79245641/116539400-95079000-a90a-11eb-8812-fed7d364c444.mp4

**Closed** 2021-06-03 10:22 UTC
Labels: GUI, bug

**Comment by peat80** [comment] 2021-06-04 11:53
Nightly build 200 still crashes for me on rotation, but is supposed to have #6242 included. 🤔 
The debug apk of this pr works for me without crash. Very strange.
