### ISSUE TITLE
Can't download videos

### ISSUE THREAD

**Issue by rolandixor** [TeamNewPipe/NewPipe#6766] opened 2021-07-25 23:43 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux BLU/G90_PRO/G0370WW:10/QP1A.190711.020/1615211229:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4021)
	at android.app.ActivityThread.access$1700(ActivityThread.java:226)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1928)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4009)
	... 8 more

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-07-25 23:45
Duplicate of #6687.

**Closed by mhmdanas** 2021-07-25 23:45 UTC
