### ISSUE TITLE
2nd video in playlist does not play if they are the same video

### ISSUE THREAD

**Issue by thedancingtaco** [TeamNewPipe/NewPipe#5022] opened 2020-11-28 12:42 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Create a playlist
2. Put 2 of the same video in the playlist
3. Click play

### Actual behaviour
The video does not play after the 1st video

### Expected behavior
The video should play after the 1st video

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung Note 20

**Comment by kubo6472** [comment] 2020-11-29 00:00
> * [x]  I am using the latest version - x.xx.x

Is your version going to stay a secret?

**Comment by RickyM7** [comment] 2020-11-29 01:12
@thedancingtaco Duplicate of #4940

**Comment by thedancingtaco** [comment] 2020-11-29 05:04
> > * [x]   I am using the latest version - x.xx.x
> 
> Is your version going to stay a secret?

Sorry, it's 0.20.4

**Comment by opusforlife2** [comment] 2020-11-29 08:05
Closing as duplicate.

**Closed by opusforlife2** 2020-11-29 08:05 UTC
Labels: bug
