### ISSUE TITLE
Show time left for video to end in player [Option]

### ISSUE THREAD

**Issue by ask6155** [TeamNewPipe/NewPipe#3625] opened 2020-05-21 02:44 UTC
#### Describe the feature you want

Hey, It would be nice if there was a option to toggle between showing length of the video in the player (on the bottom right) and showing time left.
For example if the video is 30min and I've watched 5min then the right hand side should show -25:00 and be counting down.
#### Is your feature request related to a problem? Please describe it

Nah.
#### Additional context

This idea was a brainfart.
#### How will you/everyone benefit from this feature?

If my mom screams at me to stop watching Youtube, I could say to her, "Mom, only X minutes left!"

**Comment by SameenAhnaf** [comment] 2021-12-11 06:43
@litetex This issue should be closed as https://github.com/TeamNewPipe/NewPipe/issues/7207 has a better description.

**Comment by litetex** [comment] 2021-12-11 11:48
Duplicate of #3625

**Closed by litetex** 2021-12-11 11:48 UTC
Labels: enhancement, player, template-ignored

**Comment by opusforlife2** [comment] 2021-12-11 16:34
@litetex You marked this issue as a duplicate of itself. 😄

Also, this does actually follow the old template. It's changed since then.
