### ISSUE TITLE
Can't read comment section

### ISSUE THREAD

**Issue by NewPipeUser123** [TeamNewPipe/NewPipe#10983] opened 2024-04-17 18:06 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.26.1

### Steps to reproduce the bug

Every video loads with no viewable comments. All list as 0. Error pops up: "Sorry, something went wrong."

### Expected behavior

Being able to read comments.

### Actual behavior

Can't read comments

### Screenshots/Screen recordings

<img alt="Screenshot_20240417-110026" src="https://github.com/TeamNewPipe/NewPipe/assets/167349833/99f427c4-d14b-4b03-bb13-d8b6c2733269" width=263 />

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux lge/timelm/timelm:13/TKQ1.220829.002/231650224a5f6:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1809)
	at android.app.Activity.startActivityForResult(Activity.java:5492)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:5450)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:5948)
	at android.app.Activity.startActivity(Activity.java:5915)
	at org.schabi.newpipe.error.ErrorUtil$Companion.openActivity(ErrorUtil.kt:43)
	at org.schabi.newpipe.error.ErrorUtil$Companion.showSnackbar$lambda$0(ErrorUtil.kt:149)
	at org.schabi.newpipe.error.ErrorUtil$Companion.$r8$lambda$hbVLiP6-HtFc17h3_yyNDsmaIY8(ErrorUtil.kt:0)
	at org.schabi.newpipe.error.ErrorUtil$Companion$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar.$r8$lambda$4rINiMZz55Dc47hSTCuz-ALWyEw(Snackbar.java:0)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7516)
	at android.view.View.performClickInternal(View.java:7493)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29392)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8022)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.os.TransactionTooLargeException: data parcel size 1241992 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2227)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1803)
	... 25 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13

### Affected device model

LG

**Comment by OldGuyInTheClub** [comment] 2024-04-18 02:24
I've had this issue for about three weeks, as well.  I found a similar report a few days ago but can't locate it at the moment.  That issue was marked closed  but I don't think there was a fix.

**Comment by AudricV** [comment] 2024-04-18 04:20
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #10808. 
Please search (better, with different keywords?) for duplicates, **especially pinned ones**, the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-04-18 04:20 UTC
Labels: bug, needs triage
