### ISSUE TITLE
Download as MP3

### ISSUE THREAD

**Issue by gitdebpro** [TeamNewPipe/NewPipe#6586] opened 2021-06-29 07:50 UTC
Hi there is it possible to have an option to download audio only in mp3 format also to fetch cover from video thumbnail in 1:1 ratio like 500x500 or 900x900 something like that ?

Thanks for this magnificent piece of app

**Comment by SameenAhnaf** [comment] 2021-06-29 07:58
Duplicate of #507. Also, please fill in the template properly.

**Closed** 2021-06-29 09:19 UTC
