### ISSUE TITLE
Please re-add "Enqueue in Background" option back into the app

### ISSUE THREAD

**Issue by phenomenal11** [TeamNewPipe/NewPipe#5070] opened 2020-12-02 10:33 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Since version 0.25.3 the feature to "Enqueue in Background" has been removed from this application. Now the "Enqueue" option only pops up if another video is already playing.

**Why is this a problem?**

Previously i would go to my history and long press on a video and press "Enqueue in Background" and _only that_ video would be enqueued but now if i press "Start Playing in Background" it enqueues _every single_ video in my history. Same thing happens with my playlists. Sometimes i just want to play a single track which i cannot do now. 😢 

**Workaround**

The current workaround that i have is that i must open the video page and from there click the "Background" button. Only then it enqueues a singular video. Now this may not seem like a big deal but it has been my observation that sometimes video pages take a long time to load whereas if i want to just listen to the audio there is almost never any delay in playing. This is especially applicable to videos with lesser number of views. For someone like me who exclusively uses NewPipe to listen to _a lot_ of songs it is quite a pain in the bum. 

**Please help me**

I understand you may have done it to reduce the menu clutter in the app so might i suggest to give an option to the user to enable/disable these options from the settings instead. 
Please save me from having to open video pages one by one to listen to a song. I would be forever thankful to you O Mighty Devs. 😄

**Comment by nbmrjuhneibkr** [comment] 2020-12-03 08:18
All these attempts at further "unification" of the queues make https://github.com/TeamNewPipe/NewPipe/issues/4460 (which is the biggest fundamental issue in 0.20.x) even more unlikely to be fixed in the foreseeable future. It just keeps getting worse.

**Comment by phenomenal11** [comment] 2020-12-03 08:34
O man.. this is a lot bigger than i thought. I kept thinking why weren't more people talking about this.. lol.. i guess i wasn't alone 😄

**Comment by Stypox** [comment] 2020-12-04 16:55
Duplicate of #4805 and #4460

**Closed by Stypox** 2020-12-04 16:55 UTC
Labels: enhancement
