### ISSUE TITLE
[Enhancement] Sorting Options For Videos

### ISSUE THREAD

**Issue by newuser70** [TeamNewPipe/NewPipe#2402] opened 2019-06-14 19:36 UTC
Hello,

Can you please add an option to sort videos especially by date in channels and search results?

I think this will be very usefull on channels which has big amount of videos uploaded. If possible to group them (in collapsible way or similar to real/paper phonebooks)  by months or years.

Sorting videos by date in channels ,
Sorting videos by title in channels ,
Sorting by channel names in search tab
Custom input by user to narrow search results (search through results) ,
Other useful search parameters that you can have in your mind . 

Regards,

**Comment by Stypox** [comment] 2019-06-22 09:04
Duplicate of #110 (search filters) and #2414 (channel page)

**Closed by Stypox** 2019-06-22 09:04 UTC
