### ISSUE TITLE
Lock interface for pocket use

### ISSUE THREAD

**Issue by oborder** [TeamNewPipe/NewPipe#1734] opened 2018-09-20 05:00 UTC
I often listen to videos while commuting, doing shopping and similar. If I use main player touch events are often registered in my pocket. I would like to be able to use main player while the phone is in my pocket.

For listening to music background option is fine, but for some podcast and conference videos I sometimes want to look at the screen briefly. Transition between background and main player looses position, speed setting etc.

I think that adding lock option to the main player would be better option. 
- it would add lock/unlock icon to video actions
- unlock would show overlay over video asking for pattern (3x3 like android pattern lock)
- when locked it would still show video but no touch events would be acted upon

Really like the app, it makes watching presentations much nicer by controlling playback speed.
Thanks

**Comment by opusforlife2** [comment] 2020-01-11 14:51
This issue would be made redundant by #2907 since it would allow seamless switching between different playback modes.

> playback position is synchronized between players. Easy to switch from one to another

**Comment by B0pol** [comment] 2020-05-10 09:35
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1575

**Closed by B0pol** 2020-05-10 09:35 UTC
Labels: enhancement, player
