### ISSUE TITLE
Release v0.24.1 (PLEASE TEST!)

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#9292] opened 2022-11-04 12:10 UTC
# Download APK for testing

[NewPipe_0.24.1_RC2.zip](https://github.com/TeamNewPipe/NewPipe/files/9938718/NewPipe_0.24.1_RC2.zip) (reuploaded from [this CI artifact](https://github.com/TeamNewPipe/NewPipe/suites/9129095010/artifacts/424034330) coming from the corresponding release pull request, #9290)

**Report new issues / bugs here!** bugs which existed in previous versions must not be reported here.

## Known issues

- #9242 - probably fixed by #9109
- #9298
- ⚠️ [YouTube] Shorts and livestreams (including VODs) of most channels are not available in videos listed in channels, due to the separation of them into separate tabs. This issue could be solved **only when channel tabs will be implemented**.

  However, you can use workarounds for now:

  - For feeds, use the dedicated method to fetch them (a.k.a. RSS feeds);
  - For channels: you can use the uploads playlist of a channel to get all its public videos: take a channel ID (**not a username or a handle**), replace `UC` by `UU` at the beginning of the ID and use the resulting ID as a playlist ID (append this ID to a playlist URL like `https://www.youtube.com/playlist?list=` and then open this URL in NewPipe).

# Changelog

## App
<details><summary>read more</summary>

### New
- Add monochrome icon #8987
- Add link to FAQ in the app #9164
- Add an "Open in browser" button on error panel #9180
- Add option to display channel groups as list instead of grid #9207
- Long-click on stream segment to share timestamped URLs (for YouTube only) #9203
- Support YouTube handles #9291

### Improved
- Add play queue button to video details fragment #8946
- Show "Hold to enqueue" tip in local playlists #9196

### Fixed
- Fix potential cast exception in comments text #9065
- Fix `DownloadDialog` crash on screen rotation #9079
- Fix crash when clicking download and quitting the history fragment #9143
- Fix job for removing watched streams from playlist not executing only once #8706
- Fix duplicate videos in feed group "All" #9230

### Localization
- Add new localizations (Icelandic, Latvian, Malayalam) to language selector #9179
- Update translations #9092, #9179, #9256
- Remove empty localizations #9256

### Development
- Use `LinkifyCompat` #8934
- Utilize `useSimpleSummaryProvider` attribute #9011
- Improve `FeedGroupDialogViewModel` factory #8734
- Update Android Gradle Plugin to 7.3.0 #8986
- Use range-limiting methods in more places #8747
- Use Okio's `ByteString` for download checksums #8767
- Calculate search score using streams #8739
- Use `TextViewCompat.setCompoundDrawableTintList()` #8655
- Update AppCompat to 1.5.1 and compileSdk to 32 #8768
- Update PrettyTime from 5.0.3 to 5.0.6 to include new localizations made by NewPipe contributors #9272
- Update NewPipe Extractor #9291
</details>

## Extractor

<details><summary>read more</summary>

### New
- [YouTube] Add comment reply count support TeamNewPipe/NewPipeExtractor#936
- [YouTube] Add `uploaderUrl()` and `uploaderVerified()` to `PlaylistInfoItem` TeamNewPipe/NewPipeExtractor#959
- [YouTube] Support handles TeamNewPipe/NewPipeExtractor#964

### Improved
- [YouTube] Support new metadata format of playlists TeamNewPipe/NewPipeExtractor#958
- [YouTube] Add support for attributed text description TeamNewPipe/NewPipeExtractor#953

### Fixed
- [media.ccc.de] Avoid possible NullPointerException in `MediaCCCRecentKiosk` TeamNewPipe/NewPipeExtractor#930
- [SoundCloud] Fix `SoundcloudPlaylistExtractor`: tracks are in correct order TeamNewPipe/NewPipeExtractor#939
- [SoundCloud] Fix getting more comments TeamNewPipe/NewPipeExtractor#943
- [YouTube] Workaround 403 HTTP errors of ANDROID client streams TeamNewPipe/NewPipeExtractor#960
- [YouTube] Support richGridRenderer on channel page to fix extraction of videos in channels TeamNewPipe/NewPipeExtractor#944
- [YouTube] Support all channel usernames TeamNewPipe/NewPipeExtractor#964

### Development
- Bump junit-bom to 5.9.1 TeamNewPipe/NewPipeExtractor#931
- Bump spotbugs-annotations from 4.7.1 to 4.7.3 TeamNewPipe/NewPipeExtractor#924 TeamNewPipe/NewPipeExtractor#945
- Use `EnumMap` in `PatternsHolder` TeamNewPipe/NewPipeExtractor#888
</details>

**Comment by mirakernel** [comment] 2022-11-04 14:18
Updating subscriptions works, watching channels works:) Thank you so much!

**Comment by HTSamurai** [comment] 2022-11-04 15:03
Works great, cant see any new bugs

**Comment by rcboy43** [comment] 2022-11-04 15:22
No seeing any errors while testing.

**Comment by mwang99** [comment] 2022-11-04 15:24
Seems to work 👍

**Comment by Nizami20052022** [comment] 2022-11-04 15:25
Where to download APK from?

**Comment by weole** [comment] 2022-11-04 15:26
I can't open it after I download it.

**Comment by bvanseg** [comment] 2022-11-04 15:39
Works great on Galaxy S10e 👍🏻

**Comment by KiYugadgeter** [comment] 2022-11-04 15:40
There is no any regression.
Thank you.

Pixel6

**Comment by Jean-BaptisteC** [comment] 2022-11-04 17:20
Channel group doesn't keep layout grid when you leave app
Pixel 6 - Android 13

**Comment by opusforlife2** [comment] 2022-11-04 17:23
It follows the List/Grid setting under Appearance. Check that.

**Comment by Stypox** [comment] 2022-11-04 17:26
@SameenAhnaf could you test [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9940733/app-debug.zip)? From #9298

**Comment by IMMalebolgia** [comment] 2022-11-04 18:05
This release fixes the issue where the "What's New"  tab was no longer updating as well as the empty channel video lists in the "Subscriptions" tab.

It does not change the automatic fullscreen issue on the FireTV 4k Max but no regressions seen on the non-Max 4k FireTV.

**Comment by opusforlife2** [comment] 2022-11-04 18:07
If that issue was fixed it would be closed.

**Comment by Nizami20052022** [comment] 2022-11-04 18:08
Application performance has decreased. The application opens late and runs hard.

**Comment by Stypox** [comment] 2022-11-04 18:14
That's normal, it's just a debug APK. It won't be this way in a release APK.

**Comment by IMMalebolgia** [comment] 2022-11-04 18:18
> If that issue was fixed it would be closed.

I didn't expect it to be fixed as it was not mentioned but there are several debug releases I am testing so just wanted to be thorough in case it mattered.

**Comment by Nizami20052022** [comment] 2022-11-04 18:19
This is a minor update.

**Comment by brunocalmon** [comment] 2022-11-04 20:47
Works fine on my pixel 5, stock ROM.
The current 0.24.0v is not working not my phone or TV.

When will it be available on F-Droid?

**Comment by ubrt** [comment] 2022-11-04 21:03
Works fine on my Pixel 4a 5G. Subscriptions are getting updated now, great job!

**Comment by GabiK65** [comment] 2022-11-04 21:57
Works great on my Redmi Note 8 running LineageOS 18 with microg

**Comment by nwrkbiz** [comment] 2022-11-04 22:19
Works for me aswell

**Comment by razbone** [comment] 2022-11-05 00:27
forecast when the full screen videos will work again ?

**Comment by peat80** [comment] 2022-11-05 00:27
> @SameenAhnaf could you test [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9940733/app-debug.zip)? From #9298

I can reproduce this. Sadly also with apk from 9298.

**Comment by peat80** [comment] 2022-11-05 00:34
> > @SameenAhnaf could you test [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9940733/app-debug.zip)? From #9298
> 
> I can reproduce this. Sadly also with apk from 9298.

It happens every time when you scroll down so that channel groups are out of sight, then open any channel, press back & then scroll up to channel groups. Goes back to normal after closing the app.

**Comment by DavidC-DFFF** [comment] 2022-11-05 01:09
Seems to work like a charm.

**Comment by WorkHard4470** [comment] 2022-11-05 01:37
I expect and suggest to remove ability to report errors if app crashed. If the app crashed, no error reporting are shown. It'll be available once @TobiGr will improve this soon.

**Comment by Noobydoobie** [comment] 2022-11-05 05:55
Installed NewPipe_0.24.1_RC2.zip on:
Samsung Galaxy Note10+ Android 12
Amazon Firestick 4k plus
Everything worked. Content in my subscription channels is back and my subscriptions downloaded seamlessly on both devices.
I have a Samsung Note 5 (Android 7) which I also tried. I kept getting an error saying my subscriptions couldn't be imported but when I manually typed the channel name into search, went to the channel and clicked on the subscribe button and then went to newpipes subscription tab the content loaded correctly for any subscription channel I subscribed to manually. Happy to provide more detail if anyone needs it.
Thank you to all who worked on fixing this issue I am extremely grateful to you all.

**Comment by Xglk** [comment] 2022-11-05 07:41
Hi all,
It's better but not Perfect. 
Some list are not complete. By example the chanel Thinkerview: we only see video that are 5 month old and more...
Thank you for your work

**Comment by hubertm600** [comment] 2022-11-05 08:56
it seem working fine! the channel are not loading problem is fixed

**Comment by asap2Go** [comment] 2022-11-05 09:25
APP works fine again, thanks!

**Comment by NewNewPipe** [comment] 2022-11-05 10:12
Xglk exactly.

Compare the list of videos from NP version 0.24.1 vs. the official YT application or YT via WWW. NP is missing videos from the channel's video list.

**Comment by NewNewPipe** [comment] 2022-11-05 10:47
Differences between main, video, live tabs.

**Comment by janTaja** [comment] 2022-11-05 11:02
i have the subscriptions tab as default and it takes a second for the subscription list to load and another second for channel groups to show up. idk if that’s a part of a debug apk being slow, but if not, maybe channel groups should load first? visually, at least. it’s disturbing when the page content changes twice

**Comment by CorentinBrule** [comment] 2022-11-05 13:43
Tested on Galaxy M32, Android 12 . I think everything is going as you expected : "videos" appeares in chanel, not Shorts and VODs. Videos ans VODs appeares in research, not the Shorts. For now open url like https://m.youtube.com/c/chanelname/streams in Newpipe redirect to /videos

**Comment by drdewes** [comment] 2022-11-05 15:34
It's pretty crazy. Problem with Wlan on Glaxy S5  and Goolge Pixel 6. The problem also existed with 0.24.0 . No videos or downloads possible. This problem only occurs with a 1GB WIFI. Fritz box 6660 cable. YoutubeApp and Libretube without any problems. There are no problems with LTE or any other WLAN. DNS exchanged several times. problem remains the same. may i could help you. I hope I could help. Thanks for the wonderful work!

**Comment by uxweb** [comment] 2022-11-05 15:50
Thanks for all your hard work on this! I love NewPipe! 

I have found these issues testing the 0.24.1 in a Pixel 6a:

### Group channels & bookmarked playlists are not restored when importing from a previous local file backup
![Screenshot_20221105-092430](https://user-images.githubusercontent.com/5134732/200128312-a4e39902-c4c5-4c51-bbff-23bbccc82c82.png)
![Screenshot_20221105-093313](https://user-images.githubusercontent.com/5134732/200128332-756dda25-bd6c-4cb4-a1c9-1f63db145462.png)

### Toast messages not visible when using dark theme but light
![Screenshot_20221105-092925](https://user-images.githubusercontent.com/5134732/200128364-791d470d-60d2-4b44-b234-455d2ba0abd3.png)
![Screenshot_20221105-092834](https://user-images.githubusercontent.com/5134732/200128369-956ff286-c6cf-4b78-af79-2f64c5f185cf.png)

**Comment by Markel** [comment] 2022-11-05 18:07
> Channel groups & bookmarked playlists are not restored when importing from a previous local file backup

Not happening on Poco F1 (LineageOS 16 - Android 9)

**Comment by Stypox** [comment] 2022-11-05 18:44
> Channel groups & bookmarked playlists are not restored when importing from a previous local file backup

Nothing has changed about backups in between releases I think. Could you try to see what happens when importing data into an older APK, such as [this one](https://github.com/TeamNewPipe/NewPipe-nightly/releases/tag/nightly-2)? Also, could you try to clean that app's data and try importing the database again, just to see if maybe this was a one-time problem caused by something we can't control?

> Toast messages not visible when using dark theme but light

Could you provide more information, such as which Android version you are on? Does this happen on older NewPipe versions, too? Do other toasts work fine (i.e. toasts which are not about restarting to change language), such as the "Playlisted" toast that comes up after adding a video to a playlist?

**Comment by Stypox** [comment] 2022-11-05 19:09
@SameenAhnaf actually there was an even simpler way to reproduce: just setting grid view, then scrolling down until only channels are visible, then opening a channel and going back would reproduce the bug consistently for me. Anyway the problem was a stupid mistake of mine. Could you test the new APK from #9298? [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9944546/app-debug.zip)

**Comment by Stypox** [comment] 2022-11-05 19:23
> When will it be available on F-Droid?

@brunocalmon We are doing the release really soon: once that is done the GitHub APK will be available, and also the release on our own F-Droid repo will be. The official F-Droid repo will take a few days to update though.

> forecast when the full screen videos will work again ?

@razbone We are working on it, but since we have no way to reproduce (nobody of us has an Android TV and the emulator has no issues), debugging is really really slow.

**Comment by peat80** [comment] 2022-11-05 20:07
> @peat80 @SameenAhnaf actually there was an even simpler way to reproduce: just setting grid view, then scrolling down until only channels are visible, then opening a channel and going back would reproduce the bug consistently for me (actually that's what @peat80 said, sorry). Anyway the problem was a stupid mistake of mine solved by [fc06159](https://github.com/TeamNewPipe/NewPipe/commit/fc061599f8906755762f4041e2073080b941cf54). Could you test the new APK from #9298? [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9944546/app-debug.zip)

This debug apk solves the issue. 😎👍

**Closed** 2022-11-05 22:22 UTC

**Comment by jaseg** [comment] 2022-11-06 10:56
Works great, what's new feed and channel page issues both resolved. Device: Samsung A51 w/ stock OS.

**Comment by moriel5** [comment] 2022-11-06 13:02
A shame that it had to happen in such a disruptive way, however channel tabs is a feature that I have been waiting for for a very long time, so I am glad to see it finally be implemented.
