### ISSUE TITLE
NewPipe doesn't remember the video viewed  path when back button is clicked

### ISSUE THREAD

**Issue by fightthepower** [TeamNewPipe/NewPipe#2358] opened 2019-05-23 11:58 UTC
**How to reproduce**
1.  Open any video page in newpipe (v 0.16.1)

2.  From that video page select any  recommended  video and go to its page

3.  Repeat the step 2 as many times as you like

**Problem**
Lets say I go from a video page A to video E in this path A->B->C->D->E. When back button is clicked in Eth page I should have gone to Dth page and then back button gets to Cth page similar to this E->D->C->B->A. 

But in my newpipe when I click back button from Eth video page it goes directly to either trending or whats new page and skip all intermediate video pages. Similar thing exist if we go to a channel page also.

- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.
- [ x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment] 2019-05-23 12:09
I think this will be fixed as soon as #2286 will be merged.

**Comment by TobiGr** [comment] 2019-05-23 17:34
There are two back buttons. When using the hardware back button, you should go back one page. But using the back button in the app bar should bring you back to the first level in this case the trending page/home.

**Comment by yausername** [comment] 2019-05-23 21:43
I too found this non intuitive.
How about using the home icon instead?
![sc2(1)](https://user-images.githubusercontent.com/5203007/58288591-b9c76480-7dd1-11e9-973d-0ab7ce71a5f6.jpg) ![sc1(2)](https://user-images.githubusercontent.com/5203007/58288606-bfbd4580-7dd1-11e9-918a-ea2be6dcd003.jpg)

**Comment by fightthepower** [comment] 2019-05-24 05:33
@yausername I agree it should have been the home icon, I thought that the back arrow is for going back.
@TobiGr I didn't think of using hardware back button , thanks for letting me know. That said I personally prefer not to use the hardware button and instead I want to use inbuilt app back button or swiping to go  back to page. Please consider this as a feature request for that.

**Comment by cdwijs** [comment] 2019-12-28 17:20
I confirm that the hardware back button works as expected, the arrow in the top-left goes back too far.

Tested with this version:
NewPipe 0.17.4 (latest release)
Android 6.0.1
CyanogenMod 13.0-20161121-NIGHTLY-ks01lte
Samsung Galaxy S4

**Comment by opusforlife2** [comment] 2020-08-12 17:55
Close as intended behaviour? Device hard/soft back button for unwinding the backstack, and the app's back button to go up a level, as Mauricio explained?

**Comment by Stypox** [comment] 2020-08-12 18:42
Yes, the behaviour chosen in unified ui is there to stay

**Closed by Stypox** 2020-08-12 18:42 UTC
Labels: GUI, enhancement
