### ISSUE TITLE
Feature: Keep audio streamed in background

### ISSUE THREAD

**Issue by Shawn-Beltz** [TeamNewPipe/NewPipe#1991] opened 2019-01-08 23:59 UTC
- [x] I carefully read the [contribution guidelines] and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Add a toggle to the background player to keep a copy of each song streamed to completion.

This would be a convenient way to download playlists without wasting or abusing bandwidth.

**Comment by gkeegan** [comment] 2019-01-09 06:52
So basically caching (not sure if that would be the term) the audio file for a while, then if you select to download it or play it again later, the app will just play from the file?

**Comment by Stypox** [comment] 2019-09-17 04:34
Duplicate of #478 #1179

**Closed by Stypox** 2019-09-17 04:34 UTC
