### ISSUE TITLE
Progress bar does not complete after the video.

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#7174] opened 2021-09-26 11:02 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to newpipe
2. https://www.youtube.com/watch?v=F4yfSGI4SOc
3. See progress bar

### Actual behavior

There is some extra space after the endof the video

### Expected behavior

The progress bar completely cover the lower part

### Device info

 - Android version/Custom ROM version: android 7.1.1 nougat
 - Device model: Samsung Galaxy Tab A

**Comment by SameenAhnaf** [comment] 2021-09-26 11:22
Isn't this a duplicate of #6180?

**Comment by litetex** [comment] 2021-09-26 18:24
@Thewisem 

Seems like you don't remeber you own issues...

**Closed by litetex** 2021-09-26 18:24 UTC
Labels: bug

**Comment by Thewisem** [comment] 2021-09-26 19:31
Oops. Sorry
