### ISSUE TITLE
Some videos won't load at 720p

### ISSUE THREAD

**Issue by TheProgrammingDog** [TeamNewPipe/NewPipe#3998] opened 2020-07-28 21:18 UTC
### Version

- Newpipe - 0.19.8
- Android - 10 but it is reproducible on an android 8.1.0 phone

### Steps to reproduce the bug

1. Go to https://www.youtube.com/watch?v=xNQpKNOkvZA or https://www.youtube.com/watch?v=9iWvpTAgmY4
2. Play video at 720p

### Expected behavior
Video loads

### Actual behaviour
Video doesn't  load and a gray popup appears saying 'Could not play this stream'.

### Screenshots/Screen recordings
![Screenshot_20200728-221309_NewPipe](https://user-images.githubusercontent.com/68926464/88722750-ad4e4280-d11f-11ea-83ae-bf1669284e9f.jpg)

### Logs
No log

Sorry if anything is missing this is my first time using Github.

**Comment by FireMasterK** [comment] 2020-07-28 21:39
Can't replicate this, videos play perfectly fine on my end.

**Comment by wb9688** [comment] 2020-07-28 21:42
>Sorry if anything is missing this is my first time using Github.

Nope, you actually filled in the template, and provided enough information.

However those videos are recently ended livestreams/premieres, which aren't supported by NewPipe yet, but I'm not sure if there is an issue for it. After some time, they're properly processed by YouTube and thus playable in NewPipe.

**Comment by TheProgrammingDog** [comment] 2020-07-28 21:43
Just messed around some more, its only when playing MPEG 720p. I think its a duplicate of #2415 anyway. I should probably have checked the pinned issues...

**Comment by Stypox** [comment] 2020-07-29 07:46
Yeah, this is most probably duplicate of #2415

**Closed** 2020-07-29 07:45 UTC
Labels: bug
