### ISSUE TITLE
Error when searching on SoundCloud

### ISSUE THREAD

**Issue by divyansh10101** [TeamNewPipe/NewPipe#3469] opened 2020-04-22 05:11 UTC
### Version

- 0.19.2

### Steps to reproduce the bug
Select SoundCloud before mainscreen loads 
try searching something and error will show up 
you can search before loading mainscreen by slowing your internet

### Expected behavior

it should show up your searched songs

### Actual behaviour

it shows error

### Logs

<img src="https://user-images.githubusercontent.com/64121209/79943154-cc389b00-8485-11ea-9d10-c11ade4fb37d.png" width="200">

**Comment by gkeegan** [comment] 2020-04-22 07:05
Please have a concise issue title and put the information into the issue body under the correct headings.

Follow the template as it tells you!

**Comment by surrodox2001** [comment] 2020-04-22 07:15
Maybe you can shrink your title here? Perhaps a tagging bug.

**Comment by B0pol** [comment] 2020-04-22 08:42
Please use [Crash report to Markdown](https://teamnewpipe.github.io/CrashReportToMarkdown/):
When you have the error, share to clipboard, paste on [Crash report to Markdown](https://teamnewpipe.github.io/CrashReportToMarkdown/), click transform and paste the transformed bug report here on github @divyansh10101

**Comment by tatami4** [comment] 2020-04-22 18:17
Probably a duplicate of #2915.

**Closed** 2020-04-22 18:54 UTC
Labels: bug
