### ISSUE TITLE
Some Changes To Back Up Option

### ISSUE THREAD

**Issue by IamJithendra** [TeamNewPipe/NewPipe#1331] opened 2018-04-18 15:18 UTC
On Back Up  Please Do Override The Last Back Up Data And Automatically Backup once In A Week and Save It as Json Instead of Zip

**Comment by theScrabi** [comment] 2018-04-21 17:33
This would require some more work.

**Comment by theScrabi** [comment] 2018-05-31 09:35
Please open another issue about this :)

**Comment by Stypox** [comment] 2019-07-21 10:04
Duplicate of #1163

**Closed by Stypox** 2019-07-21 10:04 UTC
