### ISSUE TITLE
Stream to external player temporarily

### ISSUE THREAD

**Issue by godzellax** [TeamNewPipe/NewPipe#7180] opened 2021-09-28 10:29 UTC
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

There's an option in settings to play a video in external player permanently but what if you want to lay on the built-in player and stream any video from there to external player by adding an option "stream to" then choose the app so will be more comfortable.

Can you please do that? Thank you so much.

**Comment by SameenAhnaf** [comment] 2021-09-28 11:58
Duplicate of #3642.

**Comment by godzellax** [comment] 2021-09-28 13:47
Oops sorry my bad

**Comment by godzellax** [comment] 2021-09-28 13:55
Will be added soon?

**Comment by mhmdanas** [comment] 2021-09-28 14:21
There is no timeline for when this will be implemented.

**Closed by mhmdanas** 2021-09-28 14:21 UTC
Labels: enhancement
