### ISSUE TITLE
Paused video starts itself when put into background

### ISSUE THREAD

**Issue by StefanBrand** [TeamNewPipe/NewPipe#3245] opened 2020-03-18 07:24 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

## Issue
When I pause a full-screen video and then put NewPipe into background (tabbing the circle button in Android), the pop-up player pops up and the video playback resumes.

The same behaviour can be observed, when the video is paused and then the screen turns off. The pop-up player appears *on the dark screen* (i.e. I cannot see it until I reactivate the screen) and video playback starts automatically.

## What I expect
A paused video should not start the pop-up player, or if it does so, it should not start playback on its own.

## Steps to reproduce
1. Play a video
2. Pause the video
3. Tab Android's circle button (navigation bar)
4. Pop-up player pops up and video playback start by itself

*or*

1. Play a video
2. Pause the video
3. Let screen go dark.
4. Pop-up player pops up (invisibly) and video playback start by itself

## Disclaimer
There might be some setting that I have set in my NewPipe preferences that makes the pop-up player appear when I leave the app. Still, automatic playback should not happen if the video is paused.

## System
- Fairphone 3
- Android 9
- NewPipe 0.18.2 from F-Droid

## Praise
I like NewPipe a lot and lately I'm especially interested in the new CCC Media channel. I use it for researching interesting topics in my field (geoinformatics).

**Comment by Stypox** [comment] 2020-03-18 11:28
Could you update to 0.18.6? Though this should not fix anything

**Comment by Stypox** [comment] 2020-03-18 11:35
Actually, I can't reproduce on 0.18.6. Could you check there? Recently a pr about this was merged

**Comment by Stypox** [comment] 2020-03-18 11:40
Fixed in 0.18.4+
- Fixed player starting again although it is paused when option "minimize on app switch" enabled and NewPipe is minimized #2917

**Closed by Stypox** 2020-03-18 11:40 UTC
Labels: bug, player

**Comment by StefanBrand** [comment] 2020-03-18 13:03
Okay, thanks! Seems that F-Droid ist pretty delayed... 😬
-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 18. März 2020 12:40:17 MEZ schrieb Stypox <notifications@github.com>:
>Closed #3245.
