### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by myrky** [TeamNewPipe/NewPipe#9446] opened 2022-11-22 15:36 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Make it possible to add channel groups to the home screen as playlists.

### Why do you want this feature?

To be able to view subscriptions by category

**Comment by opusforlife2** [comment] 2022-11-26 09:46
> as playlists

You mean in the Bookmarked playlists tab?

**Comment by myrky** [comment] 2022-11-28 15:14
> > as playlists
> 
> You mean in the Bookmarked playlists tab?

Section "content of main page"

**Comment by myrky** [comment] 2022-11-28 15:15
> Thanks for the issue. Please edit the title to `Shortcuts for Channel Groups`

How is it done? This is my first time here.

**Comment by opusforlife2** [comment] 2022-11-28 15:31
Duplicate of #3319

**Closed by opusforlife2** 2022-11-28 15:31 UTC
Labels: feature request, needs triage

**Comment by myrky** [comment] 2022-11-29 12:19
> Duplicate of #3319

Did you close the application? What I write is not what you show.

I'm talking about adding a group of channels that you create yourself, not individual channels.

How do you reopen the entry?

**Comment by opusforlife2** [comment] 2022-11-30 12:32
Needs some clarification, then. You said playlists. Playlists contain videos.

You're proposing being able to add a new type of tab to the main page, aren't you? What do you want to see in the new tab? Videos from channel groups? Channels from one channel group? All channel groups in a separate tab from Subscriptions?
