### ISSUE TITLE
Live streams play at highest quality. Default resolution settings don't apply to live streams, and no resolution selection menu is available.

### ISSUE THREAD

**Issue by Robby-** [TeamNewPipe/NewPipe#2137] opened 2019-02-19 19:46 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Live streams play at highest quality. The default resolution settings don't apply to live streams, there is also no resolution selection menu in the top left as there is on normal videos, to change this.

It would be great if support for this could be implemented, as this is a problem on low-bandwidth connections, or connections with data caps.

**Comment by Stypox** [comment] 2020-04-20 07:52
Duplicate of #1312

**Closed by Stypox** 2020-04-20 07:52 UTC
Labels: bug, player
