### ISSUE TITLE
Subscriptions refresh by pulling down. 

### ISSUE THREAD

**Issue by Poomex** [TeamNewPipe/NewPipe#3401] opened 2020-04-09 08:50 UTC
#### Describe the feature you want

It would be awesome to be able to pull down on the subscriptions page to reload it instead of touching the bar at the top. This is how it's done in most Material Design apps. 
#### Is your feature request related to a problem? Please describe it

Refreshing subscriptions is not as simple as it could be. 
#### How will you/everyone benefit from this feature?

I think this would make using NewPipe feel much more modern and well-designed and give the users a better experience

**Comment by wb9688** [comment] 2020-04-09 08:56
Duplicate of #3321

**Closed by wb9688** 2020-04-09 08:56 UTC
Labels: enhancement
