### ISSUE TITLE
Youtube Takeout

### ISSUE THREAD

**Issue by dwyjbksq** [TeamNewPipe/NewPipe#6959] opened 2021-08-23 16:37 UTC
Hello, today I installed your application and I wanted to import the scripts and when I chose the file with subscriptions, an error popped up

**Comment by SameenAhnaf** [comment] 2021-08-23 17:18
Please keep the discussion in #1751.

**Comment by litetex** [comment] 2021-08-23 19:06
@dwyjbksq 
Please fill out the issue according to the template.
If there was an error also copy that text and paste it into the template. 
Without the details it's impossible to tell what is going wrong.

**Comment by mhmdanas** [comment] 2021-08-23 22:35
Probably a duplicate of #6757. If you have any reason to think otherwise, please make a comment.

**Closed by mhmdanas** 2021-08-23 22:35 UTC
Labels: bug, user-ignored-template-instructions
