### ISSUE TITLE
[Feature request]Allow NewPipe to be selected as a default video player

### ISSUE THREAD

**Issue by slyscorpion** [TeamNewPipe/NewPipe#1216] opened 2018-03-25 19:37 UTC
Hi,

Would it be possible to have NewPipe show up in MIUI 9's default apps setting? I would like to have NewPipe show up as an option for a default video player for video links.

In this screenshot you can see that other apps can be set as a default video player https://i.imgur.com/6ObAYbD.jpg and this one https://i.imgur.com/aBFa4RK.jpg and I was hoping that the same could be done with NewPipe.

Let me know if you need any OS or device info to help with this issue.

**Comment by theScrabi** [comment] 2018-03-25 20:16
> video player 

I don't know how that works, but I would gues what they mean is the video player that can play local files. NewPipe can not do that.

**Comment by slyscorpion** [comment] 2018-03-25 20:21
Hi,

I meant that I would like to have NewPipe open up when I click on a video link in another application like the web browser or a Reddit app on my phone. You know how when you're browsing the net on your phone and you tap a video link and YouTube opens up? I was hoping something like that could be done for NewPipe.

**Comment by theScrabi** [comment] 2018-03-26 13:14
But NewPipe can do that. I think the feature to open links in other apps depends on your browser.
Which browser are you using?

**Comment by slyscorpion** [comment] 2018-03-26 14:13
@theScrabi I use Chrome and Xiaomi's own browser that I guess is just called "Browser" (I assume that this is the stock Android browser somewhat modified by Xiaomi somehow).

I also use a Reddit app called Joey for Reddit and I was hoping to have NewPipe open up when I click on a video link within that application.

Apologies if I am asking for too much ;)

**Comment by wb9688** [comment] 2018-03-26 15:41
@slyscorpion: It does that, but YouTube is by default set as don't ask or
something, so disable that in Settings > Apps > YouTube, and you should get
a choice between NewPipe, YouTube, Chrome and Browser next time.

**Comment by slyscorpion** [comment] 2018-03-26 16:15
@wb9688

This is how my defaults menu looks like currently with no video player set to default: https://i.imgur.com/ppmq0lR.jpg

So far, I have not received any option to play video content with NewPipe.

**Comment by wb9688** [comment] 2018-03-26 16:32
@slyscorpion: Not that menu, but the following: https://vgy.me/5gfGd6.png
https://vgy.me/tUfVEu.png https://vgy.me/F5WwID.png

**Comment by slyscorpion** [comment] 2018-03-26 16:46
@wb9688

This is all I get when I go into the YouTube app info: https://i.imgur.com/z6hkpSD.jpg

I am not running stock Android as you appear to be.

**Comment by slyscorpion** [comment] 2018-03-26 16:49
Oh and none of those menu items offer me the same choices as you have on your 3 screenshots @wb9688

**Comment by BezMan** [comment] 2018-06-27 07:47
I am new here and this feature is my 1st thing that's missing - this app should contain an Intent Filter to be able to handle and open popular video links (such as YouTube links).

**Comment by terrawarra** [comment] 2018-09-08 07:27
I'm new here too... so be gentle with me !
The easy way for me to make any app my preferred app is to install (yes, another app) a freebie known as "better open with".
so simple !
https://play.google.com/store/apps/details?id=com.aboutmycode.betteropenwith&hl=en_US

**Comment by gkeegan** [comment] 2018-09-08 20:15
What I did to have this work was go to the apps page, then click YouTube. Click "open by default" and set the "open links in this app" to disallow (or whatever your device calls it).
 
I then went back to apps and clicked newpipe. Went to the "open by default" settings, and clicked allow on the "open links in this app".

**Comment by vertigo220** [comment] 2018-10-08 19:31
I'm running stock 8.0.0 and regardless of how I change the defaults, including setting YouTube to never open links and NewPipe to always open them, they still keep opening in YouTube. The only way I've found to stop this is by disabling YouTube, which is fine by me. If Google wants to be a bunch of ****s about it, then I just won't use their app at all. Frankly, I'd disable all Google stuff if I could. Personally, I think the behavior I'm experiencing is intentional on Google's part, just like how M$ changed how default programs are set in W10 and made it significantly harder to change the default browser from Edge, and even then Edge is still sometimes used. I'm just waiting for both companies to be hit with antitrust suits, but sadly that doesn't seem likely.

Actually, I'm not sure why it worked before, but playing with it now NewPipe won't open even with YouTube disabled when clicking a link in Chrome. It works in other browser's, though. Just more antitrust crap. Oh well, NewPipe's much better anyway, and I guess that's just one more reason (as if I needed it) to quit using Chrome.

And Better Open With, as mentioned by @terrawarra, is great. I've been using it for years. So much better than Google's crappy implementation, and consistent unlike all their stuff that's constantly changing for no reason.

**Comment by terrawarra** [comment] 2018-10-08 22:54
You mentioned that when you click on a YouTube link in Chrome browser....that rang a warning bell with me !
  Bloody Google are in bed with Chrome !... enough said !
Try using "Brave" browser.... .it opens in newpipe when I open a YouTube link.
Give it a try..... you've got nothing to lose

**Comment by vertigo220** [comment] 2018-10-08 22:58
As I mentioned, it works in other broswers. It just so happens the other browser I tried was in fact Brave, which is one of two Chromium-based browsers I'll even use (ok, three if you count the fact I'm currently using Chrome on my phone, but that's apparently going to stop, and frankly should have long ago). Also, I assume you know that it's more than Google being in bed with Chrome, but that Chrome is a Google product. Anyways, still waiting for that antitrust suit...

**Comment by Stypox** [comment] 2019-07-19 12:22
Duplicate of #1052

**Closed by Stypox** 2019-07-19 12:22 UTC
