### ISSUE TITLE
export /impart groups

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#4068] opened 2020-08-03 22:53 UTC
#### Describe the feature you want

the ability to export /impart groups separate from settings. 

#### Is your feature request related to a problem? Please describe it

I have multiple devices with different settings depending on their usage (phone settings are different than TV settings) but all of them share the same subscriptions and groups. subscriptions are easily exported and imported. however groups can only be imported/exported with settings.
#### Additional context

I would suggest subscriptions and groups are exported and imported together (one file for both or two files separated)
#### How will you/everyone benefit from this feature?

it would make exporting and importing subscriptions and groups between multiple devices a lot easier for everyone. and eliminate the need to redo settings on each device every time groups are updated

 this is also useful for testing newPipe builds that might have new orconflicting options in settings

**Comment by MD77MD** [comment] 2020-08-04 12:39
after thinking about it, I have even a better idea. there could be a master export/import file, then we can control what is exported/imported via checkboxes. 
checkbox for:
- subscriptions
- home tabs
- playlists
- subscriptions groups
- history and watch position
- search history
- settings

**Comment by opusforlife2** [comment] 2020-08-04 13:02
Duplicate of #3505.

**Closed by opusforlife2** 2020-08-04 13:02 UTC
Labels: enhancement
