### ISSUE TITLE
Is there a way to queue a background video from outside newpipe?

### ISSUE THREAD

**Issue by chris47368** [TeamNewPipe/NewPipe#2604] opened 2019-09-07 13:54 UTC
Is there a way to toggle the newpipe video action menu so that rather than stopping an already playing background video and playing the newly shared video instead it just queues that video to the end of the queue?

This just to clarify is the menu you get when you share a video from a different external app such as the YouTube app and not the internal dialog menus you get within the newpipe app itself.

Thank you newpipe developers :)

**Comment by Stypox** [comment] 2019-10-02 14:05
Duplicate of #1487

**Closed by Stypox** 2019-10-02 14:05 UTC
