### ISSUE TITLE
Adding metadata to downloads

### ISSUE THREAD

**Issue by FirstWithThisName** [TeamNewPipe/NewPipe#2910] opened 2019-12-30 19:06 UTC
The possibility to set meta data for downloaded files.
So the artist and the title are readable for players like Kodi, VLC etc. this and makes it possible to add this information in the download menu.

This option could be maybe enabled in the app settings.

**Comment by TobiGr** [comment] 2019-12-30 22:56
Duplicate of #183

**Closed by TobiGr** 2019-12-30 22:56 UTC
