### ISSUE TITLE
"Copy URL" function no longer available in 0.11 share menu

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#847] opened 2017-11-14 08:58 UTC
It would be nice to be able to just copy a video's URL from the share menu easily instead of having to open another app to get the link. 

Putting "copy URL" in the 3 dot menu on a video page would also be fine. 

And please just preserve the full URL instead of using truncated URLS.

**Comment by theScrabi** [comment] 2017-11-14 10:32
You could use [this app](Share to Clipboard (Copy to clipboard from the Share menu) - https://f-droid.org/app/com.tengu.sharetoclipboard) for that.

**Comment by wb9688** [comment] 2017-11-14 11:06
Isn't that built-in Android?

**Comment by Cormak** [comment] 2017-11-14 16:43
@wb9688 It shows up on every app except Newpipe now.

@theScrabi Yes, but why remove it? It was useful when it was there and it's not bloat.

**Comment by theScrabi** [comment] 2017-11-15 09:41
I can't remember we where adding nor removing that feature. Intact I didn't know about it at all. Maybe we might need to figure out why it disappeared in the first place.

**Comment by Cormak** [comment] 2017-11-15 11:11
Thanks for re-opening it. It was definitely removed within the last 2 versions. I use it all the time to paste the same Youtube link to multiple people on multiple apps. Much faster than using the share button, which is why I was so disappointed to see it gone.

**Comment by drcouzelis** [comment] 2018-01-25 22:29
As recommended above, I use the "Share to Clipboard" app to copy links, then paste them in Termux to use the "youtube-dl" downloader (available in PyPi, allows for resume).

Unfortunately, this has now been made more cumbersome with the recent addition of the title of the video appended to the link that is sent to the share menu.

What do you recommend for copying just the URL? Adding a "Copy link" entry to the three-dot menu seems simplest to me (but I am not an Android developer). :)

**Comment by B0pol** [comment] 2020-05-10 09:20
duplicate of #621

**Closed by B0pol** 2020-05-10 09:20 UTC
Labels: enhancement, good first issue
