### ISSUE TITLE
When press on background play - song start from 0:00 sec

### ISSUE THREAD

**Issue by dhananroy** [TeamNewPipe/NewPipe#8173] opened 2022-04-11 06:57 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

When press on background play - song start from 0:00 sec.

### Screenshots/Screen recordings

<img alt="Screenshot_2022-04-11-12-26-36-573_org schabi newpipe" src="https://user-images.githubusercontent.com/71282375/162681747-76c14a5b-d926-4415-91ea-d0169847c4e3.jpg" height=600 />
<img alt="Screenshot_2022-04-11-12-26-42-171_org schabi newpipe" src="https://user-images.githubusercontent.com/71282375/162681763-f299b7b5-b42d-4cc4-ba03-323b6b4782ad.jpg" height=600 />
<img alt="Screenshot_2022-04-11-12-26-45-645_org schabi newpipe" src="https://user-images.githubusercontent.com/71282375/162681766-478ccfe0-02fd-41b1-9b48-222b5b8955f2.jpg" height=600 />

### Affected Android/Custom ROM version

Android 11

### Affected device model

Poco x2

**Comment by opusforlife2** [comment] 2022-04-13 18:38
Duplicate of #7427

**Closed by opusforlife2** 2022-04-13 18:38 UTC
Labels: bug
