### ISSUE TITLE
Make Soundcloud UI have more of an audio UI than a repurposed Youtube UI

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1068] opened 2018-02-05 01:47 UTC
Trying out the 0.11.6 beta and the Soundcloud functionality is a nice bonus. However, it feels too much like an orange Youtube rather than its own service. Since Soundcloud is an audio service, can we have a proper audio-focused UI for the Soundcloud section of Newpipe? Perhaps make it feel more like Spotify than Youtube? It would be useful to have separate audio and video UIs for future service support.

**Comment by JeffRockatansky** [comment] 2019-10-28 09:44
0.17.3, issue still relevant.

**Comment by opusforlife2** [comment] 2020-08-04 03:50
Duplicate of #2610.

**Closed** 2020-08-04 13:30 UTC
Labels: GUI, enhancement, soundcloud
