### ISSUE TITLE
Youtube comments

### ISSUE THREAD

**Issue by kgoerbig** [TeamNewPipe/NewPipe#1624] opened 2018-08-23 12:52 UTC
Is there a way you could add a way to view (read-only) comments on individual youtube videos in NewPipe?  It would be nice feature, and would enhance NewPipe nicely if this could be implemented.

**Comment by TobiGr** [comment] 2018-08-23 13:52
Yes, it is planned to add comment support. At the moment, there is an open pull request to add comment support to the backend (TeamNewPipe/NewPipeExtractor#101). Comments will be read-only of course.

Duplicate of #579

**Closed by TobiGr** 2018-08-23 13:52 UTC
