### ISSUE TITLE
The feature of blacklist for videos and channels

### ISSUE THREAD

**Issue by Kristal9** [TeamNewPipe/NewPipe#8505] opened 2022-06-12 11:07 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I think what would be great if NewPipe app would have of blacklist of videos and channels. So user would has opportunity to add any YouTube video or YouTube channel to this blacklist and every time when they would search videos to watch these videos from blacklist or videos from channels from blacklist would not be in the search results or recommendations.

### Why do you want this feature?

I and a lot of people have channels which we hate and don't wanna watch, and every time when we swipe them in search results or recommendations we waste a lot of time.

**Comment by SameenAhnaf** [comment] 2022-06-12 12:49
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1815

**Closed** 2022-06-12 21:01 UTC
Labels: enhancement
