### ISSUE TITLE
Can We See Subscriptions from Current Group Feed?

### ISSUE THREAD

**Issue by denemier** [TeamNewPipe/NewPipe#3423] opened 2020-04-13 00:23 UTC
its nice feature to have multiple feeds but can we see subscriptions on top of the current feeds screen or at least you can add a simple button to popup only groups subscriptions, if we would click the channel than go to channel.

**Comment by Stypox** [comment] 2020-04-15 18:08
Duplicate of #3388 
*Also, please **follow the issue template** when creating an issue next time, don't just delete everything!*.

**Closed by Stypox** 2020-04-15 18:08 UTC
Labels: enhancement

**Comment by denemier** [comment] 2020-04-17 18:05
sorry thanks

**Comment by MD77MD** [comment] 2020-04-24 23:30
#3315 

although the new feed UI has been a long awaited feature.. old feed UI definitely had its uses... combining both would be really awesome
I would suggest to add swipe left and right (like the one used between comments and related videos) to switch between two panels
-the first panel is used for listing feeds by upload time (new feed UI)
-the second panel will show latest video from each channel (old feed UI).. i would also like the ability added to go to any channel from here directly.. maybe by adding channel icon next to its related video or by an option in video menu.

if the swiping solution is not easy.. maybe a tab next to feed refresh bar would do the trick... or maybe make to tabs above the feed refresh bar, one called (new videos) and another called (channels).

also maybe you can make it an option to have it in settings... same as comments
