### ISSUE TITLE
error while downloading audio

### ISSUE THREAD

**Issue by SNvMK** [TeamNewPipe/NewPipe#7127] opened 2021-09-20 09:57 UTC
i got this when wanted to download m4a audio of Stereo Madness soundtrack. idk why this happens
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
	at android.app.Activity.startActivityForResult(Activity.java:5320)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at org.schabi.newpipe.download.DownloadDialog.launchDirectoryPicker(DownloadDialog.java:690)
	at org.schabi.newpipe.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:747)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1(DownloadDialog.java:359)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1$DownloadDialog(Unknown Source:0)
	at org.schabi.newpipe.download.-$$Lambda$DownloadDialog$QfMS-FoXWFjSoHiNV7JREecQBWg.onMenuItemClick(Unknown Source:2)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

# Version
0.21.9, from F-Droid repo

**Comment by litetex** [comment] 2021-09-21 20:24
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6729

**Closed** 2021-09-21 20:25 UTC

**Comment by SNvMK** [comment] 2021-09-22 09:48
@litetex Yes, i have Material Files

**Comment by tsiflimagas** [comment] 2021-09-22 10:12
@SNvMK have you removed system's one?

**Comment by SNvMK** [comment] 2021-09-22 10:31
@tsiflimagas DocumentsUI? yes

**Comment by tsiflimagas** [comment] 2021-09-22 11:35
The that's ui, most probably. Restore that app (dirty flash your rom I'd say) and better don't remove it again, it's necessary for SAF as it's the onyo SAF provider. Idk if it's possible for a user app to serve as a SAF provider.

**Comment by SNvMK** [comment] 2021-09-22 14:08
@tsiflimagas okay, i think i will just find this app and put to /system/priv-app. also i tried putting material files as DocumentsUI, didnt worked

**Comment by litetex** [comment] 2021-09-22 18:28
@SNvMK 
You can also disable SAF in the settings 😉 
Maybe this helps 😄
