### ISSUE TITLE
pick the quality for livestreams

### ISSUE THREAD

**Issue by Omar-tamer** [TeamNewPipe/NewPipe#7088] opened 2021-09-10 23:31 UTC
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I was just thinking that it would be really nice for people with slow internet speeds and limited bandwidth to be able to pick the quality of livestreams 

#### Is your feature request related to a problem? Please describe it
Whenever a livestream is working for me the quality starts at 144pand then it starts pumping up the quality and then the stream starts lagging then buffers for a sec and finally ends with failed to play stream.
Its pretty annoying having to use my browser for livestreams ngl

#### How will you/everyone benefit from this feature?

This feature will make streams playable for people using mobile data as they wont have to worry about their limited bandwidth when watching a stream.
If GOOGLE CAN DO IT WE CAN DO IT BETTER!!!!!!!!!!!

**Comment by SameenAhnaf** [comment] 2021-09-11 00:55
Duplicate of #1239.

**Comment by opusforlife2** [comment] 2021-09-11 06:40
Like I said in your other issue - and as you can see, the need has been proven here - the checklist isn't optional. Closing as duplicate.

**Closed by opusforlife2** 2021-09-11 06:40 UTC
Labels: enhancement
