### ISSUE TITLE
crash when going back to history

### ISSUE THREAD

**Issue by pokegamer5547** [TeamNewPipe/NewPipe#7486] opened 2021-12-03 07:55 UTC
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to history, scroll down and select any video.
2. open the video in full screen and after it plays, exit the full screen.
3. go back to history and scroll all the way to top.

### Actual behavior

it will show the background, popup, and playall button even tho page is not at top yet, and once you scroll up to top, newpipe crashes. also like to mention that the report button shown often in screen record doesn't do anything when pressing it.

### Ex pected behavior

report button should work and also those three buttons shouldn't appear unless user scrolls to the top and  yeah shouldn't crash.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/65234485/144565197-111fb5cf-68ee-435a-b329-9db11b363306.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7080)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Crdroid 7.12 Android 11
 - Device model: poco m2 pro

**Comment by defini-tiv** [comment] 2021-12-04 08:14
I can confirm that.

LineageOS 18.1 (Android 11)
Fairphone 3

**Comment by litetex** [comment] 2021-12-07 21:03
Duplicate of #4475

**Closed** 2021-12-07 21:03 UTC
Labels: bug, duplicate
