### ISSUE TITLE
Time ticker to the left of seekbar glitches when the timestamp ends in an 8

### ISSUE THREAD

**Issue by eternaltyro** [TeamNewPipe/NewPipe#6902] opened 2021-08-11 09:52 UTC
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Long-press Youtube video and select Start Playing in Background
2. Enqueue another video just in case
3. Swipe down and click on the NewPipe notification to view the play Queue
4. Observe the timestamp to the left of the Seekbar

### Actual behavior

When the timestamp ends in `8` the timestamp is displayed in two lines. You can even drag across the seekbar and see the timestamp glitch.

### Expected behavior
Consistent one-line timestamp

### Screenshots/Screen recordings

![Screenshot_20210811-150844_NewPipe](https://user-images.githubusercontent.com/230743/129008803-4b5d33e4-bf76-42f9-b829-57c33f383f73.jpg)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung M30s

**Comment by SameenAhnaf** [comment] 2021-08-11 11:15
Duplicate of #6567.

**Closed** 2021-08-11 13:01 UTC
Labels: bug
