### ISSUE TITLE
UI CRASH V 20 

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#4520] opened 2020-10-15 18:16 UTC
I started playing normally, then I was switching to full screen and trying to increase brightness. 

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.20.0
* __OS:__ Linux Android 7.1.2 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList androidx.core.app.NotificationCompat$Builder.mActions' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.shouldUpdateBufferingSlot(NotificationUtil.java:151)
	at org.schabi.newpipe.player.VideoPlayerImpl.onBuffering(VideoPlayerImpl.java:1121)
	at org.schabi.newpipe.player.BasePlayer.changeState(BasePlayer.java:583)
	at org.schabi.newpipe.player.VideoPlayerImpl.changeState(VideoPlayerImpl.java:1102)
	at org.schabi.newpipe.player.BasePlayer.onPlayerStateChanged(BasePlayer.java:798)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:828)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$AYkTJomZb3BnUDA59u8cvRVoKcM.invokeListener(lambda)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:826)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

```
</details>
<hr>

**Comment by xibr** [comment] 2020-10-15 21:45
look like a duplicate of #4390

**Comment by opusforlife2** [comment] 2020-10-16 09:11
See if you can reproduce it with the brightness gesture, otherwise it's fairly certain this is caused by the double tap gesture when paused.

**Closed by opusforlife2** 2020-10-16 09:11 UTC
Labels: bug
