### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by saintsorro** [TeamNewPipe/NewPipe#2699] opened 2019-10-07 16:37 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Exported database does not export subs and playlists. @yausername submitted an apk that worked perfectly, please look into what files that apk is backing up.

**Comment by Stypox** [comment] 2019-10-10 12:21
Duplicate of #2508

**Closed by Stypox** 2019-10-10 12:21 UTC
