### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [TeamNewPipe/NewPipe#5289] opened 2020-12-27 08:13 UTC
### Checklist

- [√] I am using the latest version - x.xx.x 
- [√] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [√] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [√] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to first page
2. See the bug

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box overlap with each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103166637-136dfb80-485f-11eb-84a2-f2663285b222.png)
App version is 0.20.1, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="445" alt="bug-newpipe_955" src="https://user-images.githubusercontent.com/18572115/103166563-42d03880-485e-11eb-9eaf-4866b33398fb.png">

### Actual behaviour

use the largest **_font_** and **_display_**.

### Expected behavior

Hope to solve the problem of overlap

### Screenshots/Screen recordings

<img width="445" alt="bug-newpipe_955" src="https://user-images.githubusercontent.com/18572115/103166568-58456280-485e-11eb-826e-fadd4bb26909.png">

### Device info

 - Android version/Custom ROM version: Android 8.0
 - Device model: Google nexus 6

**Comment by mhmdanas** [comment] 2020-12-27 10:21
This would be a duplicate of #5096.

By the way, you are using an outdated version of NewPipe (0.20.1), probably because you are getting it from the official F-Droid repo. We are having issues publishing our updates there, and so NewPipe there is many versions behind (the current version is 0.20.7). See https://github.com/TeamNewPipe/NewPipe#updates on how to update to the latest version.

**Closed by mhmdanas** 2020-12-27 10:21 UTC
Labels: bug

**Comment by franklinbill** [comment] 2020-12-30 09:15
OK, Thank you!
