### ISSUE TITLE
Show release date of scheduled Videos/Streams

### ISSUE THREAD

**Issue by zolagonano** [TeamNewPipe/NewPipe#8283] opened 2022-04-23 15:05 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Currently, When playing a scheduled Video/Stream, NewPipe says that the content is unavailable, but the scheduled date can be extracted and shown there instead.

### Why do you want this feature?

"Content unavailable" is a little bit confusing because it might mean that the video got taken down or it's private

**Comment by opusforlife2** [comment] 2022-04-23 16:28
Duplicate of #5192

**Closed by opusforlife2** 2022-04-23 16:28 UTC
Labels: enhancement
