### ISSUE TITLE
Add Some Features to Download 

### ISSUE THREAD

**Issue by IamJithendra** [TeamNewPipe/NewPipe#1062] opened 2018-02-02 17:08 UTC
Add A Feature to share the downloaded video URL

Change the Notification on The Notification Bar To the Downloading File Name And % Completed

Add Thumpnail Seeing Feature Of Downloaded  Video

**Comment by theScrabi** [comment] 2018-02-04 11:28
Well this would require that we wrote the download manager from the ground up. You bring up some cool ideas but this was a loot of work for us right now.

**Comment by Stypox** [comment] 2019-07-01 03:56
The notification has been brought about in #962

**Comment by opusforlife2** [comment] 2020-08-04 03:48
Partially done + partially duplicate of #3332.

**Closed** 2020-08-04 06:31 UTC
Labels: downloader, enhancement
