### ISSUE TITLE
New Bug. Can't play any videos. Get a blank screen with a rotating white circle that keeps rotating indefinitely. Downloaded the latest version 4 days ago and it seemed fine until today. 

### ISSUE THREAD

**Issue by veryjolly** [TeamNewPipe/NewPipe#4048] opened 2020-08-02 07:47 UTC
### Version

-

**Comment by wb9688** [comment] 2020-08-02 09:36
Duplicate of #2415

**Closed by wb9688** 2020-08-02 09:36 UTC
Labels: bug
