### ISSUE TITLE
rotating screen does not always scale the video to fit the screen

### ISSUE THREAD

**Issue by teridon** [TeamNewPipe/NewPipe#7594] opened 2021-12-28 15:58 UTC
### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1.  While in portrait mode, open a video and start it playing 
2.  Rotate the phone to landscape mode

### Actual behavior

Newpipe fills the entire screen.  However, approximately 40% of the time, the video does not scale to fit the entire screen.  Instead, it stays the same relative size as it was in portrait mode.  In addition, when you rotate the phone back to portrait, for a split-second it finally scales the video to fit the screen, before returning to the normal portrait view.  

AFAICT, this problem never occurs if the video is *paused* when you rotate the screen.  i.e. a workaround to this bug is to pause the video, rotate to landscape, then resume the video.  

### Expected behavior

Newpipe should fill the screen and scale the video to fit.

### Screenshots/Screen recordings

Video of this occurring:
https://youtu.be/jRj7oGCVFkg

### Logs

There's no error; would be happy to install a debug build if that's what it takes to get a log.

### Device info

 - Android version/Custom ROM version:   12
 - Device model:  Pixel 3 XL

**Comment by litetex** [comment] 2021-12-29 14:58
Duplicate of #7262

**Closed by litetex** 2021-12-29 14:58 UTC
Labels: bug
