### ISSUE TITLE
Playlist download (Batch downloading)

### ISSUE THREAD

**Issue by f4m4z** [TeamNewPipe/NewPipe#6171] opened 2021-04-25 15:53 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it

Often time, i like to listen to entire playlists in Youtube, usually videogame/anime OSTs or song compilations (usually exclusive to Youtube)

Despite there being an option to download individual songs/videos by clicking on their names and downloading them separately/one-by-one, there is no way to download the entire playlist (Batch downloading)

It would be a handy feature to add and would save us alot of hassle.

#### Additional context

![Screenshot_2021-04-25-21-48-15-504_org schabi newpipe](https://user-images.githubusercontent.com/65540671/116000066-8d956d80-a610-11eb-92c9-0609560ffe32.jpg)

**Comment by mhmdanas** [comment] 2021-04-25 16:26
Duplicate of #2380.

**Closed by mhmdanas** 2021-04-25 16:26 UTC
Labels: enhancement
