### ISSUE TITLE
please add two features in newpipe app, one is to play all feed page video in auto-play and second isan  option to add channel shortcut to the home screen.

### ISSUE THREAD

**Issue by komals1** [TeamNewPipe/NewPipe#8256] opened 2022-04-19 05:25 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

while playing videos from feed i have to go back to feed page to each time to select another video for play, it would be wonderful if all feed items can be played one after another .

secondly option is simply to create shortcut option for channels on home screen

### Why do you want this feature?

the first request i like to use is to listen to news, as older videos automatically showed in auto-play, but after setting feed fetch limit to one day older i can catch with daily news more easily.

second, is also to make channels more easily accessible.

### Additional information

nothing

**Comment by SameenAhnaf** [comment] 2022-04-19 06:13
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5741 and https://github.com/TeamNewPipe/NewPipe/issues/8044 respectively

**Closed** 2022-04-19 09:21 UTC
Labels: enhancement
