### ISSUE TITLE
Swiping doesn't add additional search results in landscape mode

### ISSUE THREAD

**Issue by wiggisser** [TeamNewPipe/NewPipe#7671] opened 2022-01-18 21:36 UTC
### Checklist

- [x] I am using the latest version - 0.21.15
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Rotate your tablet into landscape mode
2. Do a search
3. Try to swipe to get more results

### Actual behavior

On a tablet that is big enough to display a 7 x 3 search results grid, the last cell in the grid is empty because initially only the first 20 results are shown. So swiping doesn't work and won't add the next results. If you rotate to portrait and swipe to add additional results and then rotate back to landscape, swiping also works in landscape mode and adds additional results.

### Expected behavior

Swiping should load additional results if available, even if not all cells in the grid are filled. Or load enough results to fully fill the grid.

### Screenshots/Screen recordings

![Screenshot_20220118-223357_NewPipe.jpg](https://user-images.githubusercontent.com/3647678/150022324-2a705474-019f-4651-9c90-9eaebbcd8219.jpg)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung Galaxy Tab A7

**Comment by litetex** [comment] 2022-01-19 18:52
Duplicate of #1974
A fix is available with #7659

**Closed by litetex** 2022-01-19 18:53 UTC
Labels: bug
