### ISSUE TITLE
ReCaptcha

### ISSUE THREAD

**Issue by LargePrime** [TeamNewPipe/NewPipe#3272] opened 2020-03-25 16:39 UTC
Continous recaptcha requests with 18.7 and 19rc2
Does not seem to be a done button
Screenshots attached
![Screenshot_20200325-093759](https://user-images.githubusercontent.com/3808065/77562215-f8f49500-6e7c-11ea-90d9-3f9091f3fa37.jpg)
![Screenshot_20200325-093523](https://user-images.githubusercontent.com/3808065/77562240-03169380-6e7d-11ea-9491-b0b9bd896b7f.jpg)
![Screenshot_20200325-093449](https://user-images.githubusercontent.com/3808065/77562261-0873de00-6e7d-11ea-880d-026ce28e4877.jpg)

**Comment by TobiGr** [comment] 2020-03-25 17:20
Please stick to the issue template. We put there for a reason. I now have to ask multiple questions, which you could/should have answered by filling in the template...

It looks like you are using a VPN, is that correct? If yes, that should be the reason why you get reCaptcha's at all.
> Does not seem to be a done button

Did you press on the checkmark at the top right or the green one in the reCAPTCHA field? Which button do you mean?

@Stypox You have had an APK for debugging the reCHAPTCHA coockie, can you post it here?

**Comment by Stypox** [comment] 2020-03-25 21:38
Could you test this APK (from #3035)? It does not fix the bug, but enables me to gather more information. When you press :heavy_check_mark (after solving) it throws an error on purpose (so that I can see the content of cookies): please paste the bug report content here.
[app-debug_2.zip](https://github.com/TeamNewPipe/NewPipe/files/4142983/app-debug_2.zip)

**Comment by LargePrime** [comment] 2020-03-26 02:09
Tested apk Stypox suggested. No issue.

**Comment by Stypox** [comment] 2020-03-26 08:47
Strange, there should be ReCaptchas as before... didn't you get any? That's a problem, because the purpose of that apk is to capture more information about captchas and then raise an error... It does not fix anything ;-)

**Comment by TobiGr** [comment] 2020-03-26 09:59
Did you still you the VPN?

**Comment by LargePrime** [comment] 2020-03-26 16:39
Yes I use a vpn. Always

**Comment by tusch001** [comment] 2020-04-05 16:48
Version 19.2 on Stock Android 6.0.1:

When using Orbot (not as VPN but Newpipe data is sent to orbot in my firewall) I have the same problem while updating the channels. My guess is it is connected the specified URL. Is it necessary to use search_query=test&pbj=1? Because this could trigger youtube when too many people update / open the app within a short time. Maybe also reason for issue #3310?

**Comment by B0pol** [comment] 2020-04-06 12:26
> Version 19.2 on Stock Android 6.0.1:
> 
> When using Orbot (not as VPN but Newpipe data is sent to orbot in my firewall) I have the same problem while updating the channels. My guess is it is connected the specified URL. Is it necessary to use search_query=test&pbj=1? Because this could trigger youtube when too many people update / open the app within a short time. Maybe also reason for issue #3310?

This was the reason why if I remember https://github.com/TeamNewPipe/NewPipeExtractor/pull/262#issuecomment-592730187
Ping @wb9688

**Comment by wb9688** [comment] 2020-04-06 12:33
@B0pol: That "test" search is used to check whether the hardcoded client version is still valid.

**Comment by Stypox** [comment] 2020-04-10 07:29
Duplicate of #3134

**Closed by Stypox** 2020-04-10 07:29 UTC
Labels: bug
