### ISSUE TITLE
Error Downloading WebM Format

### ISSUE THREAD

**Issue by mjusuf** [TeamNewPipe/NewPipe#2321] opened 2019-05-04 18:06 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

when I download webm format, I get this error
Initially, from 0% to 49,9% nothing problem
but, when come to 50%, the progress downloading will stuck for a while, and after that, post processing will run without downloading the remaining 50%

if I play a video file, the image will be damaged, and the seek bar cannot be used

sorry for my bad english
for more details, please see my recording video
https://youtu.be/gLLnOavaLKA

**Comment by kapodamy** [comment] 2019-06-21 19:53
duplicate of #2291, also, this is fixed in the next version

**Closed** 2019-09-29 12:56 UTC
