### ISSUE TITLE
NewPipe repeatedly opening to the point where I have to quickly uninstall it

### ISSUE THREAD

**Issue by throwawaynewpipe** [TeamNewPipe/NewPipe#6470] opened 2021-06-10 17:33 UTC
### Checklist

- [x] I am using the latest version - 0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

NewPipe repeatedly opening to the point where I have to quickly uninstall it. It doesn't happen while using actively the app. Sorry, I have no idea why it happens. 

### Logs

{"user_action":"ui error","request":"ACRA report","content_language":"en-US","content_country":"US","app_language":"en_US","service":"none","package":"org.schabi.newpipe","version":"0.21.4","os":"Linux Android 11 - 30","time":"2021-06-10 07:14","exceptions":("java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.getIndex()' on a null object reference\n\tat org.schabi.newpipe.player.Player.onCompleted(Player.java:2177)\n\tat org.schabi.newpipe.player.Player.changeState(Player.java:2016)\n\tat org.schabi.newpipe.player.Player.onPlayerStateChanged(Player.java:1936)\n\tat com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$6(ExoPlayerImpl.java:1443)\n\tat com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$6$ExoPlayerImpl$PlaybackInfoUpdate(Unknown Source:0)\n\tat com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$b8AtGdawGxQCz-_rX1H1__vkxF4.invokeListener(Unknown Source:2)\n\tat com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)\n\tat com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1498)\n\tat com.google.android.exoplayer2.ExoPlayerImpl.access$100(ExoPlayerImpl.java:56)\n\tat com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:1440)\n\tat com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1328)\n\tat com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:956)\n\tat com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:320)\n\tat com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1402)\n\tat com.google.android.exoplayer2.DefaultControlDispatcher.dispatchPrepare(DefaultControlDispatcher.java:57)\n\tat com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onPlay(MediaSessionConnector.java:1151)\n\tat android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onPlay(MediaSessionCompat.java:1614)\n\tat android.media.session.MediaSession$Callback.onMediaButtonEvent(MediaSession.java:928)\n\tat android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onMediaButtonEvent(MediaSessionCompat.java:1604)\n\tat android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1566)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:246)\n\tat android.app.ActivityThread.main(ActivityThread.java:8506)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)\n"],"user_comment":""}

### Device info

 - Android version/Custom ROM version: Android Version 11 
 - Device model: Samsung Galaxy M21

**Comment by mhmdanas** [comment] 2021-06-10 18:21
Duplicate of #6233.

**Closed by mhmdanas** 2021-06-10 18:21 UTC
Labels: bug
