### ISSUE TITLE
Captcha "solve" issue

### ISSUE THREAD

**Issue by Xakepka** [TeamNewPipe/NewPipe#6655] opened 2021-07-13 08:16 UTC
This happens every time I try to play a video from YT.

It the restarts the app with the following code:
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.3
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: reasonPhrase can't be empty.
	at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
	at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
	at xf.a(SourceFile:315)
	at afs.handleMessage(SourceFile:67)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-07-13 17:02
Duplicate of #6519. See if updating the webview fixes this issue. Also, please update to the latest NewPipe version, as it includes bug fixes and new features.

**Closed by mhmdanas** 2021-07-13 17:02 UTC
