### ISSUE TITLE
Android 12 Popup bug

### ISSUE THREAD

**Issue by Jigsaw88** [TeamNewPipe/NewPipe#8097] opened 2022-03-24 00:14 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1.Open a Video
2.Press the popup Button

### Expected behavior

The popup should be moveable but the rest of the phone should still be useable

### Actual behavior

The popup work, but after pressing the button the only thing you can do is moving the popup, you cant do anything with the phone until you close the popup

### Screenshots/Screen recordings

https://streamable.com/1dfzmo

### Affected Android/Custom ROM version

Latest Version of GrapheneOS (Android 12) 

### Affected device model

Google pixel 6

**Comment by SameenAhnaf** [comment] 2022-03-24 00:42
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6770. Please check for duplicates properly from repo or at least from first page of issues and pinned ones.

**Closed** 2022-03-24 03:34 UTC
Labels: bug
