### ISSUE TITLE
NewPipe desktop version

### ISSUE THREAD

**Issue by D-Ermis** [TeamNewPipe/NewPipe#1198] opened 2018-03-22 09:16 UTC
Hi -- Do you think it's feasible to have a desktop version of NewPipe?

I love NewPipe and I use it daily on my Android device. I'd like to do the same on my personal computer.
Thanks a lot and keep up the good work! Waiting for #1044 to be available, this will be a game changer.

**Comment by wb9688** [comment] 2018-03-22 09:17
Duplicate of #1051

**Closed** 2018-03-22 09:17 UTC
