### ISSUE TITLE
Music Album Matching

### ISSUE THREAD

**Issue by woorst** [TeamNewPipe/NewPipe#2071] opened 2019-01-29 01:11 UTC
Search by album title then have newpipe create a playlist automatically populated with tracks in the album à la [mps-youtube](https://github.com/mps-youtube/mps-youtube/blob/0d21ac37fe9f676b4cfb21a2f12e982baa770b3c/README.rst#music-album-matching).

**Comment by opusforlife2** [comment] 2020-08-04 07:21
Fixed? Youtube Music search has an Album option.

**Comment by Stypox** [comment] 2020-08-04 13:45
@opusforlife2 also, this would be out of scope for newpipe

**Closed** 2020-08-04 13:44 UTC
Labels: enhancement

**Comment by opusforlife2** [comment] 2020-08-04 13:46
Oh. Then I probably misunderstood what the issue is about.
