### ISSUE TITLE
sub-playlists/playlists inside playlists

### ISSUE THREAD

**Issue by phly95** [TeamNewPipe/NewPipe#1790] opened 2018-10-04 03:35 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I often like finding albums in playlist form, but if I want to add it to my albums playlist, it becomes problematic since it's a bunch of individual videos. It would be awesome if you could place playlists inside playlists, and when queued you can skip to the next song or the next album.

**Comment by Stypox** [comment] 2019-08-28 17:01
Duplicate of #1313

**Closed by Stypox** 2019-08-28 17:01 UTC
