### ISSUE TITLE
UI-Redesign

### ISSUE THREAD

**Issue by newhinton** [TeamNewPipe/NewPipe#7047] opened 2021-09-03 11:36 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
There are some things in the user interface that could be improved, and i want feedback so that i could implement some of them if wanted.

1. What's new:
a) Remove the feedupdate-bar when the feed was updated recently. (Threshhold needs to be carefully chosen)
b) Dont replace the feed with a loading symbol, just update when loading is done.
c) Refresh when app was opened
d) Maybe jump to top after refresh instead of "staying"
e) Is the feed-loading warning really necessary? I feel this adresses an issue that should be somewhere in a setting, not prominently in the main view

2. Subscriptions:
a) Remove channel groups when only the "all" group exists. Add a three-dot menu with an button that adds a new group, and then show the bar again.
b) Completely remove Subscription-Header-Dropdown. Import&Export should be either in a Settings-Menu, or a three dot menu. 

3. History:
a) Move everything that is not a video to the three dot menu. 
b) Create a completely new view for  'Most Played'.

#### Is your feature request related to a problem? Please describe it

1) Every point is basically a cleanup. There is no reason other than to reduce cluttering and making it easier to concentrate on actual content without having unnecessary information.

2 a) This is only useful when groups are set. Alternatively this could be switched to a dropdown similar to the Subscription-Header-Dropdown, but generally i think we should not scatter buttons&features all over the place in hundreds of submenus that are different. There is place in the tree-dot menu, so why not use it?

2b) Those features are not used regularly. (Probably why there is a dropdown for it in the first place) The three-dot menu is perfect for that, and if every view uses it, the user can always easily find cool features there!

3a) Same as 2b. (Probably more frequently used, but they still belong in a menu)

3b) A statistics View would be a great addition. Alternatively, this button could be moved to the three dot menu aswell.

#### How will you/everyone benefit from this feature?

Overall, this would result in a more streamlined and polished experience. While everything would "move", new users would not be overwhelmed by many features and things that are not useful on the first steps with newpipe. Also it would get more consistent, since everything uses the same ui-behaviour instead of introducing new and sometimes unusual ui-elements.

Let me now what you think!

**Comment by litetex** [comment] 2021-09-03 20:50
1d) will be addressed with #7050

**Comment by castrik** [comment] 2021-09-04 04:18
1c) I'd recommend to have an option for refresh subs using RSS feed when opening the app so it loads up latest stuff quickly and we don't have to wait for minutes (I have many subscriptions and I have to wait, RSS loads up quickly) and we can still do a manual refresh using default mode to load up everything in detail if we want

**Comment by SameenAhnaf** [comment] 2021-09-05 05:29
Some abbreviations: SP: Short press
LP: Long press
OB: Open in browser


Also, I suggested three `Top bar options on right` for maintaining symmetry throughout the UI. Please include 'Search' as the fourth option too as it was a highly requested feature. (More details: H. 'Search'). 


<details><summary> A. Bottom bar </summary>


Related issues: #2438, #3319, #3732, #7022
Possibly solves: #4405, #6395, #3825, #1070 and #5701


My primary concept is that drawer items should be replaced into a bottom bar and main page items into drawer. Bottom bar options should be alike YouTube which are not configurable.
Bottom bar options: Explore, Subscriptions, What's New, Profiles, Downloads, Watched


'Content on main page' should be replaced by 'Content on Drawer'. The only new option is feed group as suggested in #3319.
Drawer tabs should always look for new videos and include the number on right. from, they should be static regardless of profiles (More details: B. Profile manager)
Drawer:
Top: Newpipe red top
Middle: '+ Add tab'
Bottom: Drawer tabs
Tabs arrangement:
Left: Position holder
Middle: 1. Feed icon (If possible, add #2438) (SP: Enable bulk selection and turn '+ Add feed' into 'Remove' suggested in #3732, Long press can't be added as #7022 was suggested)
2. Feed name
Right: New video number (SP: automatically play new videos on last player)


<details><summary> Why this switch </summary>
1. Less hassle as drawer items are configurable right on the front instead of settings.
2. Drawer items should accessible throughout all profiles. This will let users to have access to any item in an easier way (More details: Profile manager section)
3. Such an awkward placement of buttons of channel tab on main page will be gone. Especially, the 'Search' button is confusing as if it suggests to search within the channel although it doesn't.
![IMG_20210905_095052](https://user-images.githubusercontent.com/79245641/132116266-1a784c6e-673d-488f-928b-ce3ed7edc29e.jpg)



</details>
</details>


<details><summary>B. Profile manager </summary>


Related issues: #5654, #5809, #650


Multiple profiles (like multiple YouTube accounts) should be added where you can configure everything seperately suggested in #5654.


Note that each service should have seperate profiles. #5809 and #650 suggested this differenciation. For example, Newpipe has support for YouTube, Bandcamp and SoundCloud. Now, by default, there should be profiles like `YouTube 1`, `Bandcamp 1` and SoundCloud 1.


Users should be able to have seperate profiles under the service and rename them later. For example, under YouTube, I should be able to have 'Fun', 'Tech' and 'Motivation' profiles, 'Music' and 'Podcasts' under SoundCloud and 'Classic' under Bandcamp etc.


Ticking a profile should make new profiles to have the same settings as the ticked one by default. They should be later configurable. The new profiles will only have the settings applied. If no profile is ticked, factory settings for new profiles will be applied by default.


As of now, the whole database gets overlapped completely. This shouldn't happen if multiple profiles are introduced as old database can be optionally kept. Also, make sure to keep these options at the bottom of profile manager as they are common in the app.
1. Import
2. Export
3. About
These database related issues should be solved alongside: #6551, #1348, #4076, #5949 and #1751. They focus mainly on importing database from Google Takeout and optionally select options for backup file.


</details>

<details><summary> C. Explore </summary>
Top bar options on right: `Country`, `OB`, `Share`
Related issues: #6626, #1805, #1088


Explore tab should include all kiosks like YouTube Trending (more Trending sections in #1805 & #1088), SoundCloud Top 50 etc like following image. Also, #6626 asks to include `country` selection on top bar.
![IMG_20210905_061021](https://user-images.githubusercontent.com/79245641/132116306-5a822270-65dd-4eea-bf1a-39fb3a21cc3f.jpg)



Kiosks could also show items like in grid to match YouTube app and it feels great!
</details>


<details><summary> D. Subscriptions and Playlists (Main Page Tab) </summary>
Top bar options on right: `Notifications`, `Grid`, `Sort`

Related issues: #3353, #5592, #6704, #3417, #5615, #3301, #3525

Possibly solve: #6372, #5615, #5836, #3388
 
`Notifications`: New stream notifications should be easily manageable. Although #2335 suggested the management to keep in settings, I'd recommend you to keep them in a top bar icon instead of settings.


Grouping and similar layout for playlists were suggested in #3525, #5681 and #5783. Unlike #5783, I'd recommend you to keep similar layout for both channel and playlist groups.


`Grid`: It'd be nice to customize the view as a lot of channels can fit into grid view ensuring easier access and list view is better for advanced operations.
Channel and Playlists list view:
1. Left: Channel or playlist icon (SP: Enable bulk selection with a bottom menu of options: `Select/Deselect all`, `Unsubscribe`, `Add to group, `Move to group`, `Remove from current groups`)
2. Middle: Channel or playlist icon
3. Group number: (SP: Checklist for groups and Unsubscribe button)
![IMG_20210905_055920](https://user-images.githubusercontent.com/79245641/132116314-eeca5d1e-bac3-4819-82a7-400343f04268.jpg)



Following layout could be added to solve #6372 as well.
![Document 3_1](https://user-images.githubusercontent.com/79245641/132116327-3f2ad31e-fe88-4f00-b227-b370592e27df.jpg)

1.  Position holder
2. Group icon (SP: Enable multi selection for groups) (Details: Last para of this section)
3. Group name (SP: Access feed as usual)
4. New video number (#1448, #6879) (SP: Auto-play only new videos on last player of channel group)
Note that last player should be remembered seperately for each group. New video number should only load if auto-feed load is enabled as asked in #4967.


`Sort`: Sort subscriptions and playlists by last update was requested in #3812 and #3870. The 'Sort' button would just interchange into two conditions 'By last update' and 'By alphabetical order'. No advanced option is required here.


When multi selection is enabled by SP on group icons, following options should be changed.
1. `+ Add`: `X Remove` (Remove only groups themselves but keep channels and playlists subscribed)
2. `All`: `Unsubscribe` (remove all the groups and unsubscribe channels/ playlists as well)
3. `Ungrouped`: `Edit` (Works only if one channel group is selected. As 'Remove' already added outside the editor, 'Add profile' should be added to move or copy channel or playlist group to another profiles)
#5615 suggested to show channel groups following certain conditions and divide them into sections. Most users have no idea about sets and I'm in favor of following management.
1. Common: Show channels/playlists common within the groups
2. More in the groups: All channels/playlists within the groups other than common ones.
3. Others: All channels/playlists not included into the selected groups


</details>


<details><summary> E. Channel and Playlist Page </summary>
Top bar options on right: (for Channel) `Blacklist/Whitelist`, `Share` (LP: Copy link), `OB` (LP: RSS)


Top bar options on right: (for Playlist) `Sub/Unsub/Edit`, `Share` (LP: Copy link), `OB` (LP: RSS or import from RSS)


</details>


<details><summary> F. What's New Feed  </summary>
Top bar options on right: `Hide Watched`, `Feed settings`, `Reload/Cancel/Header`
Related issues: #4334, #3525, #6996, #6703


`Feed settings`: Suggested in https://github.com/TeamNewPipe/NewPipe/issues/3192#issuecomment-706617110


Although #5007 asks to keep pull to refresh optional, both gesture and update line should be completely ditched. `Reload/Cancel/Header` button is a better solution, I think.
`Reload`: It will be shown by default.
`Cancel`: When the feed is being updated.
`Header`: Remain for 10 seconds after each feed update.
Toasts are a little complicated to access on Android TV. So, I'd prefer button instead.


</details>


<details><summary> G. Downloads </summary>


Top bar options on right: `Settings`, `Playlists`, `Trash` 
Related issues: #1387, #4341, #6162, #3188, #5687
Possibly solve: #6496


#1387 asks for multiple options. Anyway, I am summarizing all of them.
1. Prevent accidental deletion: #6162 also says that current deletion process is awkward. In my opinion, 'Bulk selection for files by SP on video thumbnail' could be added. BS menu options could be: `Select/Deselect all`, `Delete`, `Clear` (Delete history only), `Add to playlist` (asked in #3188)
2. Album cover: Also asked in #4341
3. Search bar (More details: H. Search)
4. Download error can't be resolved: Download notification could play a major role in this case.


More details on download notification: By default, 'Pause all/Resume all' could be shown to pause or resume downloads easily. Swiping down the notification should show 'Pause/Resume/Queue' and 'Cancel' button for every single video. Completed and failed downloads should be shown in a separate notification with a similar layout just with 'Play' and 'Retry' buttons respectively instead of 'Pause/Resume'.


Downloader should automatically detect the best number of threads on the basis of connection speed instead of showing it as an option in download popup. 'Queue' option for downloads should be ditched for the same reason.


In my opinion, three dots menu (for every video) and grid button are useless as well. You may think of including #6496 throughout all pages.


#5687 asks to add `Trash` so that users don't have to worry about losing downloaded videos. I figured out a way to avoid losing other videos. But I'll discuss it later and 'Trash' should be exclusive for 'Downloads'.


</details>


<details><summary> F. Watched </summary>
Top bar options on right: `Pause`, `Clear`, `Sort`
Related issues: #5193, #3487, #2338


Current 'History and Cache' settings is really questionable. 'History' in drawer always gets hidden once watch history is disabled. In my opinion, 'History and Cache' settings should be completely ditched and an option to pause or resume history should be added within 'History'. 'History' could be renamed as `Watched` or `Watch history` as it only manages watch history. See: H. Search for pausing and managing search history.


As `Watched` will be a part of bottom bar options instead of drawer, it will be awesome to enable incognito mode by LP on it. Turning on 'Incognito mode' will disable search and watch history until it's turned off back.


`Pause`: Set a certain amount of time how long history will remain paused. 
![IMG_20210905_095758](https://user-images.githubusercontent.com/79245641/132116246-e9a79e2e-6fd6-4f03-9f6d-77c35efa9b7f.jpg)


`Clear`: #3487 asks to clear watch history or keep entries of a certain number or within a certain timeframe. The second option could be set automatic as well.


`Sort`: Replace 'Most played' or 'Last played' into an icon instead of a line.


#5193 asks to include 'Scroll down to last media'. In my opinion, all watched items should be pinned like YouTube Shorts on the top of channel page.
#6041 also asks to save views every time a video is clicked. I think, playback time should also be included to resume playback from the same last moment.
Video thumbnail (SP: Open video as usual).
Video title (SP: Scroll down to that media).
Playback time (SP: Auto-play video with the last player.)
![IMG_20210905_100948](https://user-images.githubusercontent.com/79245641/132116338-0d6f3bb5-1bd5-46d0-972e-5d7bf445aab0.jpg)



</details>


<details><summary> H. Search </summary> 
Top bar options on right: `Pause`, `Clear`, `X`, `Sort`
Related issues: #844, #6821, #2977, #4795, #5441, #3037


As I stated earlier in A section, 'Search' function of `Top bar options on right` will be the fourth option in all pages. However, search menu for every single page won't be the same as they are added to fulfill different requirements. Note that 'Web' option would work same as of now.
Explore, History, Channel and Playlist Page, What's New and subscription feeds: (#3037, #5127 and #5441):
1. Videos (within the page)
2. Web
Subscriptions and Playlists tab on bottom bar #4795:
1. Channels/Playlists
2. Web

`Pause`: Pause search history indefinitely or for a certain amount of time.
![IMG_20210905_095758](https://user-images.githubusercontent.com/79245641/132116348-e9a04a2a-f603-40a8-bfd9-dbc4ca2bec39.jpg)


`Clear`: Clear all search entries


`X`, `Sort`: Same as of now.


This icon on the left of searches is unnecessary. It could be replaced by 'Pin' option suggested in #844.
![IMG_20210905_055920](https://user-images.githubusercontent.com/79245641/132116426-204f44f4-30e3-4d32-a948-8bb8f2968908.jpg)



</details>


<details><summary> I. How 'Possibly Solve' works: </summary>

1. #4405 can be solved by introducing bottom bar as stated in https://github.com/TeamNewPipe/NewPipe/issues/4405#issuecomment-710785015.

2. Technically, YouTube webpage is same as PureTuber. So, #6395 is also solved. See: https://github.com/TeamNewPipe/NewPipe/issues/6395#issuecomment-860001508

3. #3825: Drawer items can be added or edited directly from drawer.

4. #1070: Implemented by multiple profiles

5. #5701: What's New will be a part of bottom bar. So, it will be done automatically.

6. #6372: Suggested design should make channel groups easier to access.

7. #5615: Set is quite an uncommon way to figure out groups. Bulk selection is a lot more easier to understand.

8. #3388, #4726, #5836: #3388 is a better solution, I think.

9. #6496: Should be included throughout the app.

</details>

**Comment by Thewisem** [comment] 2021-09-05 23:47
Hi! Just want to add my input on one UI design which would be helpful

Option to Bookmark videos shared to newpipe. Currently there are 4 options. I want a 5th option of bookmark so that I can bookmark it on watch later playlist.

**Comment by SameenAhnaf** [comment] 2021-09-06 00:16
@Thewisem #5858 also asks for this.

**Comment by Thewisem** [comment] 2021-09-06 00:29
Ok then the forward and back of videos. Not fast forward but moving between videos. The two buttons in left and right of the pause button in youtube app in which you can forward to a new video or go back to the previous video.

**Comment by SameenAhnaf** [comment] 2021-09-06 03:18
@Thewisem This is also implemented actually. The thing is that `Next` and `Previous` buttons works differently on Newpipe and YouTube app.

Previous/Next buttons show recommended videos on YouTube app (unless you are playing a playlist). But these buttons appear if a queue is in existence on Newpipe app.

Although YouTube app shows previous/next buttons regardless of turning auto-queue on or off. That is not the case with Newpipe app. However, I think we should have the discussion in #7065 if you want to have buttons regardless of turning auto-queue on or off.

1.Go to 'Settings'
2.Go to 'Video and Audio'
3.Enable "Auto-queue next stream" 
You will be able to following UI while playing videos. You will similar UI if you manually enqueue videos as well.


<details><summary> Video </summary>

https://user-images.githubusercontent.com/79245641/132152719-d1391c51-f363-43ce-b1d0-5ea3e7093ee6.mp4

</details>

**Comment by Thewisem** [comment] 2021-09-06 14:55
How about the fact that to read the comments you have to overshadow the video?

**Comment by Thewisem** [comment] 2021-09-06 14:57
It'd be nice for it to not go up and just stay put so hat I can watch the video as well as read comments

**Comment by Thewisem** [comment] 2021-09-06 15:02
I am sorry if I sound demanding.

**Comment by SameenAhnaf** [comment] 2021-09-06 15:17
@Thewisem #4484 is also there. 

>I am sorry if I sound demanding.

No problem at all. Mainly, this issue was intended how the features will be arranged. Because, scattered enhancements actually don't work out as many suggestions contradict with each other.

It'd have been great if you edited your comment once instead of making three consecutive comments. As nobody has responded yet, your comments wouldn't have noticed our attention.

@newhinton I'm not sure if we should discuss player UI changes here .You primarily focused on feed pages. My suggestions are already huge. So, I think, @Thewisem and I should keep player related discussion in #1317.

**Comment by Krelyshy** [comment] 2021-09-15 06:16
I am strictly against 1b), it would just cause confusion.

**Comment by newhinton** [comment] 2021-09-15 07:13
@Krelyshy Why would it create confusion? basically every app in existence uses a pull to refresh-flow and follows my improvement, why should we not do it in the same way?

**Comment by SameenAhnaf** [comment] 2021-09-15 10:17
@newhinton I believe, feed should be obviously accessible while loading. But there should be a clear indication of loading just like how we see on browser.
![IMG_20210915_161313](https://user-images.githubusercontent.com/79245641/133415576-e8f492a2-7610-439f-a096-4346740f8619.jpg)

Also, feed update bar should be completely gone and "Reload" button should be replaced into the top bar.
>Top bar options on right: Hide Watched, Feed settings, Reload/Cancel/Header
>
>both gesture and update line should be completely ditched. Reload/Cancel/Header button is a better solution, I think.
Reload: It will be shown by default.
Cancel: When the feed is being updated.
Header: Remain for 10 seconds after each feed update.

**Comment by newhinton** [comment] 2021-09-15 11:42
@SameenAhnaf You are right, and for that we should use this:

[Material.io - Swipe to Refresh](https://material.io/design/platform-guidance/android-swipe-to-refresh.html)
This is exactly what newpipe should use, instead of the current implementation. 

Where did you get that quote from? It seems it is not from this thread, and i'd like to read the context

**Comment by SameenAhnaf** [comment] 2021-09-15 12:32
>Where did you get that quote from? It seems it is not from this thread, and i'd like to read the context

It's already written mentioned in my first comment. See `F. What's New Feed` section of https://github.com/TeamNewPipe/NewPipe/issues/7047#issuecomment-913089778.

**Comment by Pranab009** [comment] 2022-02-13 14:22
Add download tab in main page.

![Screenshot_20220127-084858_1_1](https://user-images.githubusercontent.com/65340361/153757461-80a94db0-5e8a-448c-8e6f-094c652565c9.png)

**Comment by rahaaatul** [comment] 2022-03-23 09:59
- Add **Card View** in list view mode. Like one full grid, instead of 2.

- Add a Full Black theme with shades of black.

**Comment by madpipeline** [comment] 2022-04-20 21:39
Is there an dedicated issue open for 1b that I can subscribe to?

**Comment by opusforlife2** [comment] 2022-04-23 15:07
I'm closing this issue. Not a single PR came out of it.

Because of the multiple features it talks about, issues like this quickly become a mess of going nowhere fast.

@newhinton If you want to poll users for features, please open a separate issue for each item, so that it can be tracked individually.

Everyone else, if there is a feature discussed here that you want, please open a new issue after checking for duplicates.

**Closed by opusforlife2** 2022-04-23 15:07 UTC
Labels: enhancement, GUI, feed
