### ISSUE TITLE
Hide trending tab

### ISSUE THREAD

**Issue by a-kbd** [TeamNewPipe/NewPipe#8050] opened 2022-03-16 15:48 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When entering the hamburger menu you can find tabs such as "trending", "subscriptions" etc. It would be very nice if these tabs were customizable and one could e.g. remove the trending tab (just how you can remove video suggestions tab under the video or arrange comment, description etc tabs to your liking)

### Why do you want this feature?

A strength of NewPipe is ability to remove distractions such as video suggestions, the home page etc. What remains is the trending page. Being able to remove it would mean the ultimate distraction free mobile youtube experience 

### Additional information

The tabs I'm talking about:

<img src="https://i.imgur.com/Ja2G7s9.jpg" alt="drawing" width="150"/>

**Comment by ThisIsPaulDaily** [comment] 2022-03-16 16:31
What do you think about having the default page open to "What's New" instead of trending? 

I don't disagree with this enhancement, I'm more so commenting with the thought of "Yes, and..."

**Comment by a-kbd** [comment] 2022-03-16 18:53
@ThisIsPaulDaily yes I already have removed trending from the main app windows and have "whats new" open as default. The thing is just that if the procrastination brain knows trending is one click away, it will eventually find its way there (despite the utter low quality material found in trending) 

I'm (trying to) use youtube as a productivity tool (for tutorials and such) and NewPipe is the only option app that lets you remove video suggestions etc and customize the interface. Except for the links in the hamburger menu 

(I know you aren't disagreeing, just further strengthening the case)

**Comment by litetex** [comment] 2022-03-16 19:17
Duplicate of #4081

**Closed by litetex** 2022-03-16 19:17 UTC
Labels: enhancement
