### ISSUE TITLE
Worst when it comes to listening to music when exercising.

### ISSUE THREAD

**Issue by ZioZvevo** [TeamNewPipe/NewPipe#8296] opened 2022-04-26 17:32 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Latest- 0.22.2

### Steps to reproduce the bug

Press any video ._.

### Expected behavior

The video loads in a couple seconds, and it smooth without interruptions.

### Actual behavior

The video takes 15 seconds to load when clicked on. Then sometimes, it stops after 5 or so seconds it starts playing. In the worst of cases, it stops every ten seconds and makes the audio cut. 

### Screenshots/Screen recordings

NA, its just the videos not loading.

### Affected Android/Custom ROM version

Android 9 Pie

### Affected device model

LG G8 Thinq

### Additional information

This is not my problem. My network is perfect. I tried it with 5G, and with 5ghz wifi, and with normal 2.4 ghz wifi. This is a bummer. I wanted an app that was as good as vanced, and this, if it would work properly, could be even better. The loading times are dreadful. I find myself in the middle of the workout lifting weights and the music stops all of a sudden. I find my self stopping the workout and having to switch to Vanced. Please, this ruins the point, might as well have ads with these wait times, id probably wait even less watching ads in Youtube rather than waiting 30 seconds for the video to start.

**Comment by TiA4f8R** [comment] 2022-04-26 18:06
Read pinned issues and follow the next time the issue template, PLEASE!

I know that's this issue is really frustrating, but that's not a reason to open another duplicate of an **exisiting and known issue**. There are solutions in them, which work pretty fine.

Thank you.

Duplicate of #7630 and #6949.

**Closed by TiA4f8R** 2022-04-26 18:06 UTC
Labels: bug
