### ISSUE TITLE
Soundcloud sharing is not working

### ISSUE THREAD

**Issue by garawaa** [TeamNewPipe/NewPipe#6085] opened 2021-04-15 10:17 UTC
When sharing a song from soundcloud gives message like:

Could not recognize the URL. Open with another app

**Comment by mhmdanas** [comment] 2021-04-15 12:01
What version of NewPipe are you using?

**Comment by ShareASmile** [comment] 2021-04-15 16:56
@garawaa  Don't ignore Issue Template. Filling of Issue template is mandatory. Now we have to ask number of questions to find about the issue you faced.

**Comment by garawaa** [comment] 2021-04-20 13:34
> What version of NewPipe are you using?

last version 0.21.1

**Comment by TiA4f8R** [comment] 2021-04-20 14:54
I think that you are using the SoundCloud app. Duplicate of #5025 in this case.
Like @ShareASmile said, please follow the corresponding issue template next time.

**Closed by TiA4f8R** 2021-04-20 14:54 UTC
