### ISSUE TITLE
🔥 v0.16.1 Did not find balanced marker at 'class*=\"attribution\"

### ISSUE THREAD

**Issue by essare** [TeamNewPipe/NewPipe#2225] opened 2019-03-17 15:39 UTC
Every time i try to request a video the snackbar appears
PS: i've update this issue to use bugReportImporter.
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=nrKQz-ClwIc
* __Content Language:__ US
* __Service:__ YouTube
* __Version:__ 0.16.1
* __OS:__ Linux Android 7.0 - 24
undefined

<details><summary><b>Crash log</b></summary><p>

```
org.jsoup.select.Selector$SelectorParseException: Did not find balanced marker at 'class*="attribution"'
	at org.jsoup.select.QueryParser.parse(QueryParser.java:44)
	at org.jsoup.select.Selector.select(Selector.java:91)
	at org.jsoup.nodes.Element.select(Element.java:363)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$1.getUploaderName(YoutubeStreamExtractor.java:913)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:59)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:89)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getRelatedStreams(YoutubeStreamExtractor.java:526)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getRelatedVideosOrLogError(ExtractorHelper.java:33)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:267)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$jmGRDgN6SboJT_idOrZ-yShfxEY.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```
</p></details>
<hr>

**Comment by theScrabi** [comment] 2019-03-17 20:16
Can you please use the bugreport reporter for posting issues here. You should have read the open checkboxes wehen you opened an issue.

**Comment by Ess-Soft** [comment] 2019-03-17 21:22
I've update both issue #2224 and this one. sorry for that.

**Comment by theScrabi** [comment] 2019-03-18 00:05
I could not reproduce the issue. From which country are you trying to access?

**Comment by Stypox** [comment] 2020-02-19 16:22
Now fixed, or outdated bugreport anyway

**Closed by Stypox** 2020-02-19 16:22 UTC
Labels: bug, more info needed, requires extractor change
