### ISSUE TITLE
local playlist bugs: can't move or delete items

### ISSUE THREAD

**Issue by anpic** [TeamNewPipe/NewPipe#2292] opened 2019-04-17 09:34 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

videos in local playlists are not movable and not removable permanently

**Comment by Stypox** [comment] 2019-04-17 10:56
Youtube playlists can't be edited, because there is no Google login.
But it is possible both to move and remove videos on local playlists...

**Comment by anpic** [comment] 2019-04-17 11:33
> But it is possible both to move and remove videos on local playlists

bugs in local playlists

**Comment by Stypox** [comment] 2019-04-17 17:57
For me it works as expected (version 0.15.1, the latest)

**Comment by anpic** [comment] 2019-04-17 20:23
> For me it works as expected (version 0.15.1, the latest)

maybe in 0.15.1 it works but the latest version is 0.16.1

**Comment by Stypox** [comment] 2019-04-17 23:08
Sorry I meant to say 0.16.1

**Comment by anpic** [comment] 2019-04-18 08:05
I tested on Github and F-Droid versions both and Legacy version

**Comment by thiswillbeyourgithub** [comment] 2020-05-29 20:53
I have the same problem. It's really problematic for me as I use a local playlist as a kind of "watch later" playlist. It's the feature I use the most.

This happens like 9 times out of 10. I can't move videos around or delete them reliably.

The only workaround I found was to delete the app cache, then force newpipe to close, open it and delete as many videos as I can in a burst. Then press exit. I can then see if the playlist's length has dropped or not. It usually works but not even all the time.

**Comment by opusforlife2** [comment] 2020-10-10 17:09
Please try to reproduce on 0.20.0. Closing for now.

**Closed by opusforlife2** 2020-10-10 17:09 UTC
Labels: GUI, bug
