### ISSUE TITLE
Crash in multitasking

### ISSUE THREAD

**Issue by JVS-XII** [TeamNewPipe/NewPipe#6691] opened 2021-07-18 12:33 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Run content in the background or pop-up window.
2. Open playback queue via push-notification
3. Run in multitasking long press of recents button or button on the card in the recents menu

### Actual behavior

In the first case, crash when the application only starts to move to multitasking. In the second when app returns to full size.
If you add NewPipe the second application when enque is already open or enque opens after adding to multitasking, it's okay until the window size changes.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ BY
* __Content Language:__ ru-BY
* __App Language:__ ru
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux HUAWEI/PRA-LA1/HWPRA-H:8.0.0/HUAWEIPRA-LA1/368(C10):user/release-keys 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.PlaybackParameters org.schabi.newpipe.player.Player.getPlaybackParameters()' on a null object reference
	at org.schabi.newpipe.player.PlayQueueActivity.onCreateOptionsMenu(PlayQueueActivity.java:107)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3645)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:718)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: don't know ROM is - EMUI 8.0
 - Device model: Huawei P8 Lite 2017

**Comment by mhmdanas** [comment] 2021-07-18 16:41
Duplicate of #6078.

**Closed by mhmdanas** 2021-07-18 16:41 UTC
Labels: bug
