### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by memz13155n** [TeamNewPipe/NewPipe#9231] opened 2022-10-28 03:44 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Play a video in full screen till end from landscape mode. Press full screen to turn to portrait mode. Ui error

### Expected behavior

Expected to bring me back to portrait mode after playing a video in landscape mode

### Actual behavior

After exiting video, ui error occurred.

### Screenshots/Screen recordings

<img alt="Screenshot_20221027-224421" src="https://user-images.githubusercontent.com/98498676/198497674-077bb430-a83e-498b-9e43-3de44ba6d661.png" height=600 />

### Logs

-------------------------------------
java.lang.ClassCastException: android.text.SpannedString cannot be cast to android.text.Spannable
	at org.schabi.newpipe.util.CommentTextOnTouchListener.onTouch(CommentTextOnTouchListener.java:29)
	at android.view.View.dispatchTouchEvent(View.java:10020)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3105)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
	at android.view.View.dispatchPointerEvent(View.java:10244)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6252)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6226)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6187)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6355)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6132)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
-------------------------------------

**Comment by tsiflimagas** [comment] 2022-10-28 03:53
Your reproduction steps don't seem to be related to the stacktrace. It seems to be related to tapping on a comment, and a duplicate of #9052.

**Closed** 2022-10-28 04:00 UTC
Labels: bug, needs triage
