### ISSUE TITLE
Someone knows what happens, I already solved the captcha and it is not solved

### ISSUE THREAD

**Issue by Carlos502gt** [TeamNewPipe/NewPipe#6175] opened 2021-04-26 05:16 UTC
![Screenshot_20210425-231421_NewPipe.jpg](https://user-images.githubusercontent.com/81324987/116032043-309fb480-a61c-11eb-8171-f1d8bd6a21d4.jpg)

**Comment by TiA4f8R** [comment] 2021-04-26 09:17
Duplicate of #6055. Please don't remove the template next time, there are reasons to keep it.

**Closed by TiA4f8R** 2021-04-26 09:17 UTC
Labels: bug
