### ISSUE TITLE
Comments dont load from EU, but via US VPN

### ISSUE THREAD

**Issue by DancingBear1** [TeamNewPipe/NewPipe#6507] opened 2021-06-17 14:18 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

Error, no comments

It also fails when using a VPN via NL. When switching to US it works fine. After using US, it works without proxy for a while, but after clearing cache or a certain timeout it stops working again. That's why I suspect a cookie issue.

See #6506 

### Expected behavior

comments load

## Exception
* User Action: requested comments
* Request: Start loading: https://www.youtube.com/watch?v=msQPZuM0xlo
* Content Country: DE
* Content Language: de
* App Language: de_DE
* Service: YouTube
* Version: 0.21.5
* OS: Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "INNERTUBE_CONTEXT_CLIENT_NAME\":(.*?)[,}]"
 at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)
 at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:58)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.onFetchPage(YoutubeCommentsExtractor.java:137)
 at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
 at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:34)
 at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:154)
 at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)
 at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
 at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
 at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
 at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
 at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
 at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
 at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
 at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 at java.lang.Thread.run(Thread.java:764)

</details>
<hr>

**Comment by mhmdanas** [comment] 2021-06-17 18:43
Duplicate of #5977.

**Closed by mhmdanas** 2021-06-17 18:43 UTC
Labels: bug

**Comment by mhmdanas** [comment] 2021-06-17 19:09
Might also be a duplicate of #6016.
