### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mountaincastle47** [TeamNewPipe/NewPipe#6768] opened 2021-07-26 11:47 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ ko-KR
* __App Language:__ ko_KR
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux razer/cheryl2/aura:9/P-MR2-RC001-RZR-190914/3123:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3582)
	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6735)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3570)
	... 8 more

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-07-26 13:25
Duplicate of #6687.

**Closed by mhmdanas** 2021-07-26 13:25 UTC
