### ISSUE TITLE
Mini player should also get closed if notification player is closed

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6227] opened 2021-05-03 08:47 UTC
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start any video on any player
2. Close it from notification player
3. Notification player gets closed
4. Mini player still persists on the app inside even if I am using another app.

### Actual behaviour

It seems like that "Pause" and "Close" action button has the exact same purpose for now. 'Close' button just ditches the notification as well.

### Expected behavior

"Close" button should close both the notification and media completely.

### Device info

 - Android version/Custom ROM version: MIUI 12.0.7
 - Device model: Xiaomi Redmi Note 8 Pro

**Comment by Stypox** [comment] 2021-07-28 13:17
This is the expected behaviour

**Comment by SameenAhnaf** [comment] 2021-07-28 13:20
@Stypox Really 😒? There's neither any easy way to clear queue neither. Even if it's implemented under three dots menu, it will involve too many steps.

**Comment by SameenAhnaf** [comment] 2021-07-29 06:27
@Stypox #4335 is already requested. So, there should be an option to clear queue easily as well.

**Comment by Stypox** [comment] 2021-07-29 08:28
The X button clears the queue, doesn't it? How is this related to this issue? And how is #4335 related to this issue?

**Comment by SameenAhnaf** [comment] 2021-07-29 10:39
@Stypox Nope. Clearing notification was always the case once unified player was introduced.

Even if keeping the last media was the expected behavior, playback manager is not accessible and other videos on the queue are also remaining.

https://user-images.githubusercontent.com/79245641/127477635-da221014-4b2c-4d87-af9a-919437987e9b.mp4

>And how is #4335 related to this issue?

#4335 asks for an alternative for clearing notification. So, "X" button should clear queue in both mini player and notification player.

**Comment by Stypox** [comment] 2021-07-31 07:53
Oh ok, I see what you mean. Why is that video an issue?

**Comment by SameenAhnaf** [comment] 2021-08-05 07:34
@Stypox You forgot to reopen this issue.

>Why is that video an issue?

I don't follow you. But all of my devices have the same bug. So, maybe, it's something with settings.

**Comment by Stypox** [comment] 2021-08-05 09:13
Ok, I'm reopening this. But I still don't get why it is a problem that the mini player (along with its queue) is not closed.

**Comment by SameenAhnaf** [comment] 2021-08-05 12:59
Sorry for the inconveniences. The expected behavior of 'X' button is clearing notification as of now.

Unfortunately, that's neither the case. Playback manager can't be accessed from notification player by short press.

This is what I am calling playback manager.

<details><summary> Screenshot </summary>

<img src="https://user-images.githubusercontent.com/79245641/128353348-79ecf509-f4fe-484a-a0f0-664840551400.jpg" height="300px"/>

</details>

As far as I know, you don't like inconsistent behavior. This is the reason why you wanted to ditch 'Enqueue' feature completely 🙃.

X button in the media player clears queue. That's why, I think the same button in notification player should behave the same.

**Comment by Stypox** [comment] 2021-08-06 07:06
> Playback manager can't be accessed from notification player by short press.

That's because it can be accessed through the main player.

> This is the reason why you wanted to ditch 'Enqueue' feature completely :upside_down_face.

I never wanted to ditch 'Enqueue'

> X button in the media player clears queue. That's why, I think the same button in mini player should behave the same.

Ok, I get this, but what are the downsides of keeping the backstack of opened videos?

**Comment by SameenAhnaf** [comment] 2021-08-06 09:14
>That's because it can be accessed through the main player.

I didn't notice the behavior in the app. But why should it switch to main player? I didn't ask it to do so. There is 'Switch to main' option in playback manager. 

>I never wanted to ditch 'Enqueue'

See: https://github.com/TeamNewPipe/NewPipe/pull/5850#issuecomment-802903048.

Maybe, I misinterpreted the things though. Please rectify me if I am wrong.

>what are the downsides of keeping the backstack of opened videos?

There's no easy way to clear background or popup queue. These players are meant for multitasking.
1. Pull down notification panel
2. Short press on notification player
3. Access playback manager
4. Press 'Back'
5. Swipe down queue manager
6. Get back to the last app

It's still a hassle when accessed from recent apps.
1. Go to recent apps
2. Choose 'Newpipe'
3. Swipe down video info (if any video info is open)
4. Press 'Back'
5. Swipe down mini player
6. Get back to last app

Why can't I clear queue by just pulling down notification panel and tapping the X button?


Also, why should same button behave differently in notification and mini player? All other buttons like pause, next, previous etc behave the same all over the UI. 

Plus, an alternative of clearing notification is already suggested.

**Comment by Stypox** [comment] 2021-08-06 13:06
> See: #5850 (comment).

I was saying that having Enqueue change the player was bad UX, not that the enqueue option should be ditched completely... The current "Enqueue" option is perfect.

> Why can't I clear queue by just pulling down notification panel and tapping the X button?

That already happens!! If you close the notification with the X and then start another player the old videos will not be present! That's because X also clears the queue! The only thing that X doesn't currently do is clear the backstack of `VideoDetailFragment`s, and I think that's what you are asking for. But even then, why would you clear the backstack of opened videos when pressing the X in the notification? How is that related?

> There's no easy way to clear background or popup queue. 

Mmmh, let's see... Clicking the X in the notification does exactly that?

> Plus, an alternative of clearing notification is already suggested. Clearing queue is a basic task and it should be easily accessible.

Clearing the queue is (and should be) equivalent to closing the player, as a player cannot exist without a queue with at least one item. So why make them two different options, just to confuse all users?

**Comment by Stypox** [comment] 2021-08-06 13:13
Here is a demonstration that X clears the queue:
- start playing video 1 in any player type
- clear the notification with the X
- start playing video 2 in any player type
- tap on the notification to view the queue or access the queue from within the main player
- the queue only contains video 2 (and possibly an auto-enqueued one, but that's unrelated)

**Comment by SameenAhnaf** [comment] 2021-08-06 13:34
The situation isn't highly problematic for now. What if multiple queues are introduced? Avently himself opened an issue on this. See: #5940.

**Comment by Stypox** [comment] 2021-08-06 14:51
Yes, but multiple queues has nothing to do with this, hasn't it?

**Comment by SameenAhnaf** [comment] 2021-08-06 15:28
First of all, as there's a mini player for main player, it's expected that users may want to keep main queue as well. Plus, Will it be logical to turn background queue into main queue although I only asked only to clear the notification? It's normal that I won't like to mix up queues.

**Comment by Stypox** [comment] 2021-08-10 08:00
Oh, btw, this was already discussed: #4131

**Closed** 2021-08-10 08:17 UTC
Labels: bug
