### ISSUE TITLE
Download list disappearing after app exist 

### ISSUE THREAD

**Issue by shockergit** [TeamNewPipe/NewPipe#7794] opened 2022-02-04 02:12 UTC
I just downloaded a video 50% using public wifi. After reaching home and checked the apps download tab its gone. Now i have to download again. Please fix this
Also please add the resolution name also with file name so we can download multiple resolutions of video at the same time.

**Comment by brnwlshubh** [comment] 2022-02-04 05:06
Duplicate #7059

**Comment by shockergit** [comment] 2022-02-04 06:15
Also please add resume support for all files

**Comment by mhmdanas** [comment] 2022-02-04 08:51
Duplicate of #7059.

**Closed by mhmdanas** 2022-02-04 08:51 UTC
Labels: bug
