### ISSUE TITLE
Displaying Japanese instead of Russian.

### ISSUE THREAD

**Issue by Reyorconn** [TeamNewPipe/NewPipe#10513] opened 2023-10-25 22:38 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. open the side menu.
2. Go to the settings section
3. Open the content section.
3. Select the application section Russian.

### Expected behavior

Translation of the application into Russian. 

### Actual behavior

Translating the app into Japanese. 

### Screenshots/Screen recordings

<img alt="Screenshot_20231026_013104_NewPipe" src="https://github.com/TeamNewPipe/NewPipe/assets/49608705/6133a061-728d-41e1-8065-49c0ed1d2191" width=285 />

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung galaxy a53 5g(SM-A536E/DS)

**Comment by ShareASmile** [comment] 2023-10-26 03:34
This is fixed by PR #10406

For a workaround see (this comment)[https://github.com/TeamNewPipe/NewPipe/issues/10438#issuecomment-1729940790]

**Comment by AudricV** [comment] 2023-10-26 08:06
Closing as a duplicate of #10438. Like said below, this has been already fixed and will be a part of the next release.

**Closed by AudricV** 2023-10-26 08:06 UTC
Labels: bug, needs triage
