### ISSUE TITLE
Notification Bug

### ISSUE THREAD

**Issue by jewangyu** [TeamNewPipe/NewPipe#3582] opened 2020-05-13 10:25 UTC
-->
There is a notification bug where the notification sound keeps ringing. The only way to turn off the notification sound is to either close Newpipe entirely or turn off notifications for Newpipe.

### Version

-0.19.3
Android 10
Samsung S20 and S10
One UI 2.1

### Steps to reproduce the bug

I don't know how to reproduce the error. It just randomly appear as I listen to music.

One time I was listening to music which was connected to the car Bluetooth. Then I made a phone call. Then hung up. Then then notification sounds started.

**Comment by jewangyu** [comment] 2020-05-13 11:01
Turning off "Show Comments" fixed issue.

**Comment by Stypox** [comment] 2020-05-14 09:20
What? How is it possible that disabling an option having to do with comments fixes a problem with notifications?

**Comment by jewangyu** [comment] 2020-05-17 10:48
So turning off comments only fixed the issue for a short time. There is some other things happening.

**Comment by Stypox** [comment] 2020-05-17 11:08
I believe this is a duplicate of #1574

**Closed by Stypox** 2020-05-17 11:08 UTC
Labels: bug
