### ISSUE TITLE
Can't search videos by upload date

### ISSUE THREAD

**Issue by sliceanddice9** [TeamNewPipe/NewPipe#4184] opened 2020-08-24 23:18 UTC
I’m using version 0.19.5 and I can’t seem to find the option to search videos by upload date. I remember I used to be able to do this on NewPipe but not anymore. How can start doing this again?

**Comment by opusforlife2** [comment] 2020-08-25 14:15
This was never an option. Newpipe never had search filters. You might be remembering Vanced or another app.

Anyway, duplicate of #110.

**Closed by opusforlife2** 2020-08-25 14:15 UTC
