### ISSUE TITLE
[Feature Request] Optional sponsor skipping

### ISSUE THREAD

**Issue by faissaloo** [TeamNewPipe/NewPipe#2831] opened 2019-11-30 14:49 UTC
Like most people, I hate ads. SponsorBlock has both an API and downloadable database dump that could be used to skip ads embedded in YouTube videos:   https://github.com/ajayyy/SponsorBlock

**Comment by TemporaryAccount0x1** [comment] 2019-11-30 19:01
This is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2554. It seems like @polymorphicshade already started working on it (https://github.com/polymorphicshade/NewPipe/tree/sponsorblock)

**Closed** 2019-12-11 20:44 UTC
