### ISSUE TITLE
How to disable bandcamp

### ISSUE THREAD

**Issue by legacychimera247** [TeamNewPipe/NewPipe#8264] opened 2022-04-20 09:16 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Althought newpipe is a great app for youtube i would like to disable it for bandcamp, cause for example it's triggered for actions it don't support like viewing the cart, so would it be nice to have the ability to disable it...

**Comment by SameenAhnaf** [comment] 2022-04-20 10:58
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1116

**Comment by legacychimera247** [comment] 2022-04-20 11:26
oh thank you, didn't see that when searching...

**Closed** 2022-04-20 12:23 UTC
Labels: question
