### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by champion174** [TeamNewPipe/NewPipe#3017] opened 2020-01-27 10:04 UTC
Everything is fine, Can you Please add the playlists option in the channels view, as of now it's available in the search option only, it'll be Very helpful. Because we can't browse all videos know. I hope it'll be available in the next update.

**Comment by Stypox** [comment] 2020-01-27 15:48
Duplicate of #2414

**Closed by Stypox** 2020-01-27 15:48 UTC
