### ISSUE TITLE
Can't import subscriptions on Android Q Beta 5

### ISSUE THREAD

**Issue by 101118496** [TeamNewPipe/NewPipe#2491] opened 2019-08-05 11:44 UTC
Location defaults to storage/emulated/0 but all the directories are completely empty.
Best of luck, love your work :)

**Comment by 101118496** [comment] 2019-08-06 04:30
Thank you sorry about that!

**Comment by Stypox** [comment] 2019-08-11 18:13
Is this a duplicate of #2470 ?

**Comment by Stypox** [comment] 2020-07-30 06:31
This is old and was probably fixed in the meantime. Btw, could you try if #3777 works?

**Closed by Stypox** 2020-07-30 06:31 UTC
Labels: bug, device/software specific, more info needed
