### ISSUE TITLE
Add "upcoming" or "in <n> hours" to scheduled stream's thumbnail

### ISSUE THREAD

**Issue by Piruzzolo** [TeamNewPipe/NewPipe#5512] opened 2021-01-30 18:55 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
It would be nice to have a label over the thumbnail of and upcoming stream on YouTube, saying "upcoming" or similar, or the time to its start (e.g. "in 3 hours", "in 25 minutes")

#### How will you/everyone benefit from this feature?
It would make clearer that It's a future stream, not a regular video

**Comment by B0pol** [comment] 2021-02-11 15:23
duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5192

**Closed by B0pol** 2021-02-11 15:23 UTC
Labels: enhancement
