### ISSUE TITLE
[STOP CREATING DUPLICATES] [YouTube] Channel page doesn't contain any video/no new video when not using dedicated feed

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9223] opened 2022-10-27 14:47 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open any channel 
2. No videos appear in channel
3. Search for the same channel and some videos appear 
4. Videos appear in What's new feed as well

### Expected behavior

App should show me new uploads by the selected channel

### Actual behavior

Blank. Nothing shows up

### Screenshots/Screen recordings

For step 2

<img alt="Screenshot_2022-10-27-20-12-50-59_d7d328def685d290e891d05b54a6e164" src="https://user-images.githubusercontent.com/28833686/198321512-1a5e2281-1b6d-46d8-9e69-dc7e8fb2bc8d.png" height=600 />

For step 3

<img alt="Screenshot_2022-10-27-20-12-55-58_d7d328def685d290e891d05b54a6e164" src="https://user-images.githubusercontent.com/28833686/198321660-614069c1-ec15-4dd4-8dd2-d94b46a6e1d1.png" height=600 />

### Affected Android/Custom ROM version

Color OS v6.0(android 9)

### Affected device model

Oppo Realme 1 CPH1861

**Comment by opusforlife2** [comment] 2022-10-27 15:30
Known: see TeamNewPipe/NewPipeExtractor#944

**Comment by EthanZeigler** [comment] 2022-10-28 13:56
> Everything started working fine as of now  shall I close it? I heard YouTube is messing around with three tab layout maybe keep this open for future reference.

It's still broken on my end. Might be a rollout thing

**Comment by LittleVulpix** [comment] 2022-10-28 14:12
Yeah. Broken for me too (was working yesterday). Hoping this gets merged/fixed soon!

**Comment by kiralema** [comment] 2022-10-28 15:00
Same here. Just updated to 0.24.0 in hope the issue was fixed,  but half of my subscribed channels still show nothing... :(

**Comment by Software-Solutions-Australia** [comment] 2022-10-28 21:27
I just started to have this problem. I'm not sure if this is related or not but it started happening to me when I subscribed to a new channel, now some other channels I was already subscribed to and could see their videos are also showing as blank, could be a coincidence, just thought I'd mention it. I can't think of anything else that's changed on my end. 

![Screenshot_20221029-082550_NewPipe](https://user-images.githubusercontent.com/108548866/198735628-c9f246a5-6260-430e-a810-6366bea73867.png)

**Comment by Tvirin** [comment] 2022-10-29 00:40
Same here. 
Sometime Force Stop + Clear Cache help me but after a while videos don't appear again

**Comment by EthanZeigler** [comment] 2022-10-29 00:54
Please stop replying to this and instead thumbs up the original issue request. Just saying "this affects me too" makes it harder for the maintainers to communicate and causes a ton of unnecessary notifications.

**Comment by Tarpal** [comment] 2022-10-30 00:04
Restarting the app or mobile doesn't solve the issue.
As it is the Subscriptions List is merely a reminder note of the exact names of the subscribed channels. When manually doing a Search for a channel the screen gets as expected populated with the channel's entries. It's a workaround.

**Comment by gitdimas** [comment] 2022-10-30 05:55
setting - appearance - list view mode - change to grid or list (everytime you open the app) temporarily solve my problem

**Comment by WorkHard4470** [comment] 2022-10-30 06:15
> If any one is interested in a working fixed app here is a link
> 
> https://github.com/TeamNewPipe/NewPipe/files/9858627/app-debug3.zip
> 
> Just download and install this apk
> 
> Note: may still contain bugs experimental release

Looks like it has rotation lagging errors.

**Comment by NSTAdventure** [comment] 2022-10-31 02:58
> ### Checklist
> * [x]  I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
> * [x]  I made sure that there are _no existing issues_ - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
> * [x]  I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
> * [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
> * [x]  This issue contains only one bug.
> * [x]  I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).
> 
> ### Affected version
> 0.24.0
> 
> ### Steps to reproduce the bug
> 1. Open any channel
> 2. No videos appear in channel
> 3. Search for the same channel and some videos appear
> 4. Videos appear in What's new feed as well
> 
> ### Expected behavior
> App should show me new uploads by the selected channel
> 
> ### Actual behavior
> Blank. Nothing shows up
> 
> ### Screenshots/Screen recordings
> For step 2
> 
> <img alt="Screenshot_2022-10-27-20-12-50-59_d7d328def685d290e891d05b54a6e164" height="600" src="https://user-images.githubusercontent.com/28833686/198321512-1a5e2281-1b6d-46d8-9e69-dc7e8fb2bc8d.png">
> 
> For step 3
> 
> <img alt="Screenshot_2022-10-27-20-12-55-58_d7d328def685d290e891d05b54a6e164" height="600" src="https://user-images.githubusercontent.com/28833686/198321660-614069c1-ec15-4dd4-8dd2-d94b46a6e1d1.png">
> 
> ### Logs
> _No response_
> 
> ### Affected Android/Custom ROM version
> Color OS v6.0(android 9)
> 
> ### Affected device model
> Oppo Realme 1 CPH1861
> 
> ### Additional information
> _No response_

Bug are confirmed with same reproduce step above

Actually just visit any ch and if you unlucky the respective bug where video will not show up will triggered

Link ch:
https://m.youtube.com/channel/UCtvmZLhea1h9_0SbDdu_BoQ

Screenshot:
![Screenshot_2022-10-31-09-55-29-49](https://user-images.githubusercontent.com/50813528/198921852-03fe7448-e5b0-4b77-9b7c-43387cd58a72.jpg)

**Comment by Dhangofa** [comment] 2022-10-31 11:12
Same issue with me. Channel page doesn't contained any video. But search page showing videos of that channel.

App version - 0.24.0
Android version - 11
![IMG_20221031_162938](https://user-images.githubusercontent.com/117024745/198995170-035e56a5-465d-446b-b7cf-8eb855449e31.jpg)


![IMG_20221031_162950](https://user-images.githubusercontent.com/117024745/198995002-ff452f20-74bb-4124-abf6-93e490025f9c.jpg)

**Comment by acrodemocide** [comment] 2022-10-31 13:57
This is broken for me too. I have found that it changes. For example, I have channel A and channel B. When I first come in, channel A shows no videos, but channel B does videos and works as expected.

Then I'll check back later, and channel A lists videos and works as expected and channel B has no videos listed 

Then I'll check again, and both channels will have all the videos listed and work as expected.

It seems to be random. I'll open the app, and some channels work, and the rest do. Then I'll check back later and they work and others are broken. It some other combination.

**Comment by LittleVulpix** [comment] 2022-10-31 14:28
It might be worth locking comments for this issue only for contributors/maintainers. It is clear that the issue is related to change in youtube layout which will (likely) be resolved in linked patch. Until then no workarounds/further comments are going to be relevant because in the end the layout has changed and so must the relevant code.

**Comment by opusforlife2** [comment] 2022-10-31 15:58
People often need a place to vent. The more common and critical the issue, the more venting there is. Better to let it all out in the most relevant issue, because there is a tendency among some users to find other places to make their voices heard, despite the fact that the fix is known.

**Comment by danielzgtg** [comment] 2022-11-01 03:53
Locking comments will cause us to lose the ability to use thumbs up.

**Comment by weole** [comment] 2022-11-01 04:32
It used to be only with some channels, but now all of my subscribed channels show no videos.

**Comment by ivorget** [comment] 2022-11-01 11:35
A workaround while waiting an official fix: clicking on the RSS feed icon (the one between the channel name and the share icon) will ask to add it to your podcaster app, e.g. AntennaPod.
When you then open a video item from the list in the podcast app, there isn't a media link, but AntennaPod at least offers a "visit website" link which will take you straight into the relevant video in NewPipe.

**Comment by aleksfadini** [comment] 2022-11-01 14:49
> A workaround while waiting an official fix: clicking on the RSS feed icon (the one between the channel name and the share icon) will ask to add it to your podcaster app, e.g. AntennaPod. When you then open a video item from the list in the podcast app, there isn't a media link, but AntennaPod at least offers a "visit website" link which will take you straight into the relevant video in NewPipe.

This somehow worked for me in the meantime!

**Comment by nikhilCad** [comment] 2022-11-01 18:01
Go to what's New Tab > Three dots > Help > Enable fast mode as a temporary workaround to load feed

**Comment by Tarpal** [comment] 2022-11-01 20:28
> 
That Fast Mode work around doesn't work here.
Enabled it. Restarted the app. Nope.

It's a strange matter: earlier today the content of a subscribed channel showed up. Now it's blank again.

**Comment by Racer159** [comment] 2022-11-01 21:08
> > 
> 
> That Fast Mode work around doesn't work here. Thank you for sharing anyway. Enabled Fast Mode. Restarted the app. Nope.
> 
> It's a strange matter: earlier today the content of a subscribed channel showed up. Now it's blank again.

Fast Mode worked for me as a workaround though I had to wait for the refresh timeout to pass (NewPipe won't refresh channels again if it has been refreshed too recently)

**Comment by EverCpp** [comment] 2022-11-01 21:15
I can confirm the issue- I cannnot see content in any channel with lastest version 2.4. Also I can't see a lot of recent videos at my feed that I think is a related problem. Thanks

![bug1](https://user-images.githubusercontent.com/19392892/199343081-ae43c289-2d5a-438e-8150-e389cb2ade7c.png)

**Closed** 2022-11-02 23:10 UTC
Labels: bug, ASAP, youtube, requires extractor change, channel
