### ISSUE TITLE
Add download option in long-press menu

### ISSUE THREAD

**Issue by nadiration** [TeamNewPipe/NewPipe#6340] opened 2021-05-21 12:59 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The ability to download videos without playing by long pressing the video thumbnail and then choosing download from the list of options

#### How will you/everyone benefit from this feature?

Sometimes you need to download videos before playing so it would be useful to just long press video thumbnail and download.

**Comment by mhmdanas** [comment] 2021-05-21 13:38
Duplicate of #5782.

**Comment by mhmdanas** [comment] 2021-05-21 13:38
Sorry, #2171.

**Closed by mhmdanas** 2021-05-21 13:38 UTC
Labels: enhancement
