### ISSUE TITLE
Download function disappeared. Tried installing latest APK but still no download option anymore

### ISSUE THREAD

**Issue by HendonRunner** [TeamNewPipe/NewPipe#4406] opened 2020-10-05 12:51 UTC
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

**Comment by vkay94** [comment] 2020-10-05 12:58
Please give more information by filling at least the steps and behaviors points of the bug report template. Otherwise we can't help you.

**Comment by HendonRunner** [comment] 2020-10-05 13:02
I have reguarly been using the download feature.  No Android updates since last successful use.  The download option has simply disappeared.

**Comment by vkay94** [comment] 2020-10-05 13:18
I still don't understand which download function you refer to. 
Video downloads? What do you mean by "Android updates"? Which option has disappeared? Where has it been?

Give as much information as possible.

**Comment by Stypox** [comment] 2020-10-05 15:14
*Please **follow the issue template** when creating an issue, don't just ignore everything!* Now I have to ask questions you would have already answered: what are the exact steps to reproduce this? Which video(s) are you encountering this issue on?

**Comment by HendonRunner** [comment] 2020-10-05 15:40
Sorry to have ignored important parts of your process.  I have now identified that the loss of the audio download option  it is file specific to a single video so far:

https://youtu.be/PURErKL01bE

Unless I get I will close off this issue.

**Comment by wb9688** [comment] 2020-10-05 15:43
@HendonRunner: That's a live stream. Live streams can't be downloaded

**Comment by HendonRunner** [comment] 2020-10-05 15:46
Apologies for misunderstanding the criticalityof your system.  I have now identified that the issue is file specific, and do far to a single file 


Although a livestream, it was days after the event. And on previous editions of the same event, downloading worked after the event was finished.

**Comment by Stypox** [comment] 2020-10-05 16:14
@HendonRunner the same video can't be downloaded on pre-0.20.0 (I tested with 0.19.0, see apk in #3266), so this is not a regression from 0.20.0. I don't know if there is anything that can be done about this: YouTube provides the video in a live format, which could only be downloaded with special workarounds NewPipe is currently not willing to implement. @wb9688 am I right?

**Comment by opusforlife2** [comment] 2020-10-10 13:13
Closing since out of scope.

**Closed by opusforlife2** 2020-10-10 13:13 UTC
Labels: bug, more info needed
