### ISSUE TITLE
Zoom and Move options by 2 touch. feature.

### ISSUE THREAD

**Issue by DI555** [TeamNewPipe/NewPipe#3217] opened 2020-03-12 13:53 UTC
would be great to use zoom and move video functions - to zooming needed video field and moving it to needed focus view.  
-2 related moving touches to zoom in/out... and 2 freezed touches to moving the point of view. exactly like we doing with some maps ;) !!!

**Comment by Stypox** [comment] 2020-03-13 13:10
Related, but closed: #576

**Comment by DI555** [comment] 2020-03-13 16:36
what's the goals of this feature:
1. zooming in, - when you need to focus on the best video areas,- in sports vodeos or learning videos etc. ...

2. zooming out, - yes, if your display is hires., for example 2600*1600 or so..., - you will get very bad curved video picture on low then 1024 videos or even on 1024 :(!!! So will be great to zoom out video a little or more!!! this wiil be great for hires. and big size devices !!!

**Comment by DI555** [comment] 2020-03-22 00:18
imo the best place to turn on/off the feature is a button in the upper drop-down bar by pressed the ''v'' button on the playing screen!

**Comment by Stypox** [comment] 2020-04-05 06:51
Duplicate of #1406

**Closed by Stypox** 2020-04-05 06:51 UTC
Labels: enhancement, player
