### ISSUE TITLE
"Lock screen" button in full screen mode

### ISSUE THREAD

**Issue by Liquid-Aristocracy** [TeamNewPipe/NewPipe#7116] opened 2021-09-16 08:40 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Add a button in full screen mode to toggle a mode in which playback, brightness, volume & other controls are disabled. In this mode, when swipe on the side of the screen nothing will happen, and after tap on the screen, the only remain control in the UI should be disable this mode.

Can add a switch in setting to enable / disable this button.

#### How will you/everyone benefit from this feature?

Sometimes when I playing video on my smartphone I may need to move around & do some other things, and I don't want to stop the video play. But when I take my phone in full screen mode I may potentially touch / swipe on the screen and interfere the video playback.

Also, if add it I can touch my (waterproof) phone with wet hand without worrying water drops messing up the touching screen.

**Comment by SameenAhnaf** [comment] 2021-09-16 11:35
Duplicate of #5740 and check the APK in #5799.

**Closed** 2021-09-16 13:51 UTC
Labels: enhancement
