### ISSUE TITLE
Get back to the top of feed

### ISSUE THREAD

**Issue by ourslfs** [TeamNewPipe/NewPipe#6350] opened 2021-05-22 15:02 UTC
At the moment, when you scrolled down far enough in the feed(and the channel overview), to get back to the top you have to manually scroll, which is quite inconvenient. Mayby adding additional ui element or by tapping on header.

**Comment by SameenAhnaf** [comment] 2021-07-08 13:26
@mhmdanas Isn't this a duplicate of #3633?

**Comment by litetex** [comment] 2021-11-01 21:35
Duplicate of #6650.
Will be fixed by #7050

**Closed by litetex** 2021-11-01 21:35 UTC
Labels: enhancement

**Comment by kputschko** [comment] 2023-08-16 17:33
This doesn't seem to work for me. I'm halfway down my feed and still have to manually scroll to the top.
