### ISSUE TITLE
video not scaling properly when entering full-screen mode

### ISSUE THREAD

**Issue by infinitytec** [TeamNewPipe/NewPipe#8007] opened 2022-03-10 03:25 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Go to a video
2. Start playing it in portrait
3. Rotate phone to landscape
4. If the issue does not appear, rotate phone back to portrait and then back to landscape. Repeat as needed.

### Expected behavior

Video should scale properly to the full screen consistently.

### Actual behavior

Video will sometimes stay at a smaller size while the rest of the player scales properly.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/13670462/157582489-2d9609cd-2a40-4cdb-a3d0-08fc3437bd8d.mp4

### Affected Android/Custom ROM version

Android 12, OneUI 4.1

### Affected device model

Galaxy S22 Ultra

**Comment by TiA4f8R** [comment] 2022-03-10 09:30
- [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

No, you don't, duplicate of #7262.

Please avoid opening issues next time before checking properly the existing ones first. Thank you.

**Closed by TiA4f8R** 2022-03-10 09:30 UTC
Labels: bug

**Comment by infinitytec** [comment] 2022-03-10 12:55
> * [x]  I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
> 
> 
> No, you don't, duplicate of #7262.
> 
> Please avoid opening issues next time before checking properly the existing ones first. Thank you.

Sorry. I was looking for one but I guess I failed to find it.
