### ISSUE TITLE
Show Info Remove Just Once & Always Buttons

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#2172] opened 2019-03-02 20:23 UTC
To my understanding the Perfer 'open' Action - Always Asks option is designed for when you share a youtube video to the NewPipe app it will open a menu asking how you want to view the YouTube content, weather you want to watch the video in full screen mode, popup window, background or show the video info. I find it irritating that I have to select an option and tap "Just Once". If I tap Always by accident then I have to go into the NewPipe setting and changfe the Perfer 'open' Action back to Always Ask.

I feel how Always Ask should work is when you share a video to the NewPipe app it will open a menu asking how you want to view the YouTube content, weather you want to watch the video in full screen mode, popup window, background or show the video info and which every one you select it will simply do. No need for Just Once or an Always button.

**Comment by Stypox** [comment] 2019-08-18 19:52
Duplicate of #1170

**Closed by Stypox** 2019-08-18 19:52 UTC
