### ISSUE TITLE
.MP3 Support

### ISSUE THREAD

**Issue by MACtr** [TeamNewPipe/NewPipe#3066] opened 2020-02-08 10:21 UTC
.MP3 I think it should have its format. The .m4a format, especially .Opus, is not supported on older devices.The device does not play when I download it to the device. I cannot install a different player because there is no space on the device. Please add the .mp3 format. I cannot help you because I do not know coding.Sorry.

**Comment by B0pol** [comment] 2020-02-08 10:40
Duplicate of #507. See it, there are explainations.

**Closed** 2020-02-08 11:01 UTC
Labels: duplicate
