### ISSUE TITLE
Hide comments icon in fullscreen

### ISSUE THREAD

**Issue by Davidozzoo** [TeamNewPipe/NewPipe#7676] opened 2022-01-21 18:00 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Hi all,
When i play a video in fullscreen on my tablet (Android 4.4.2, NewPipe 0.21.15) some icons about comments and desciption appear
at the bottom of the screen (as can be seen in the screenshots).
![Screenshot_2022-01-21-18-43-58~2](https://user-images.githubusercontent.com/63609944/150575835-cf412bdd-7210-4d36-a0b9-3792bf81e28f.png)
![Screenshot_2022-01-21-18-41-55](https://user-images.githubusercontent.com/63609944/150576863-6571357d-d96f-4ec3-97ca-93b045b84c08.png)
I have already tried to search in options a way to hide them, but i could't do it, neither disabling the tablet mode.
To hide them i have to slide that icon up and down, every time and that's quite boring.
When i do the same on my phone (Android 8.1, NewPipe 0.21.15) they don't appear.
Is there a way to disable it?
What does their presence depend on?

**Comment by SameenAhnaf** [comment] 2022-01-21 18:13
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6089

**Comment by litetex** [comment] 2022-01-21 19:48
Duplicate of #6089

**Closed by litetex** 2022-01-21 19:48 UTC
Labels: question
