### ISSUE TITLE
Not working landscape mobile position

### ISSUE THREAD

**Issue by RuthlessLinux** [TeamNewPipe/NewPipe#7899] opened 2022-02-19 10:49 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22 and olders

### Steps to reproduce the bug

1. Go to new pipe
2. Click on one video
3. Flip the smartphone.
4. New pipe error. Stop the video and go out.

### Actual behavior

Video error. New pipe shows the error report.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.16
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4180)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4198)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4472)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1472)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6111)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:658)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:255)
	at android.view.View.dispatchDetachedFromWindow(View.java:15461)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4756)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4730)
	at android.view.ViewGroup.removeView(ViewGroup.java:4661)
	at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.java:350)
	at androidx.fragment.app.SpecialEffectsController$Operation$State.applyState(SpecialEffectsController.java:452)
	at androidx.fragment.app.SpecialEffectsController$1.run(SpecialEffectsController.java:211)
	at androidx.fragment.app.SpecialEffectsController$Operation.complete(SpecialEffectsController.java:695)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:744)
	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:597)
	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:332)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3132)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:334)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:330)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:278)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:446)
	at android.app.Activity.performDestroy(Activity.java:7001)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4167)
	... 10 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

Lenovo p2 vibe

**Comment by mhmdanas** [comment] 2022-02-19 11:14
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7549.

**Closed by mhmdanas** 2022-02-19 11:14 UTC
Labels: bug
