### ISSUE TITLE
in-channel search

### ISSUE THREAD

**Issue by pendaar** [TeamNewPipe/NewPipe#4635] opened 2020-10-24 22:01 UTC
Hi
please add "in-channel search" feature.
like this attached screenshot.
![youtube](https://user-images.githubusercontent.com/49104183/97094409-a7ee8e80-1661-11eb-8696-15780fc7d3b3.png)

**Comment by opusforlife2** [comment] 2020-10-25 05:21
Don't delete the template. Duplicate of #2414.

**Closed by opusforlife2** 2020-10-25 05:21 UTC
Labels: enhancement
