### ISSUE TITLE
New pipe

### ISSUE THREAD

**Issue by DonJuan83** [TeamNewPipe/NewPipe#11124] opened 2024-06-01 02:29 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

Solo copie un vínculo 

### Expected behavior

Que enlazará al mismo

### Actual behavior

Envío informe de error
<img alt="Screenshot_2024-05-31-20-26-48-081_org schabi newpipe" src="https://github.com/TeamNewPipe/NewPipe/assets/107373848/e2edc0da-332d-44bf-be81-a4aa3e53f508" width=270 />

### Additional information

Los formatos en qué descarga la app, no son compatible con ningún medio de reproducción siempre marca error de formato no válido aún cuando solo requiero reenviar el archivo no me lo permite

**Comment by jbb101** [comment] 2024-06-13 17:47
This looks like a duplicate of #11136 based on the error message in the screenshot.

**Closed** 2024-06-16 00:15 UTC
Labels: bug, waiting for author, needs triage
