### ISSUE TITLE
Only buffers, NEVER plays

### ISSUE THREAD

**Issue by Psk666** [TeamNewPipe/NewPipe#6725] opened 2021-07-21 15:10 UTC
### Checklist

- [x] I am using the latest version - 0.21.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

Hi, I'm a newbie as i just got Newpipe about a week ago, v 0.21.5.

For the first 5 days or so, Newpipe was flawless. Issue started with videos no longer starting to play whatsoever. The only thing it shows is the loading/buffering screen. I've walked away, leaving my tablet for about 10 minutes and came back to see nothing changed. I updated a day ago when i saw the current version of 0.21.6 was available, hoping it would resolve the issue. It did not. I cleaned cache, cleaned data, forced-stop countless times, rebooted, uninstalled and reinstalled. Nothing helped.

### Expected behavior

I expect videos to play

### Device info

 - Android version/Custom ROM version: 7.1.1
 - Device model: SM-T350

**Comment by TiA4f8R** [comment] 2021-07-21 15:56
Duplicate of #6510.

**Closed by TiA4f8R** 2021-07-21 15:56 UTC
Labels: bug

**Comment by Psk666** [comment] 2021-07-21 16:31
I have previously read the OP for #6510. That user has videos "randomly" working. Mine do not work at all. Please read my post before being so quick to dismiss it.

**Comment by Psk666** [comment] 2021-07-21 19:34
Fuck you for being so fucking dismissive and useless
