### ISSUE TITLE
All downloads start as "Queued" 

### ISSUE THREAD

**Issue by Neodymium5312** [TeamNewPipe/NewPipe#2072] opened 2019-01-29 12:57 UTC
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.
- [ n/a] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

All downloads are added as queued when added from share menu or from main application, is this intended behavior? 
It always downloaded as soon as added in 0.14.
I'm assuming i'm not the only one having this issue

I add sometimes 20 to 30 or more videos to download at one time since i just go through my sub feed and download anything that interests me on my wifi, for later watching at work where i have 0 cell signal. Having to go into the newpipe application and manually start each download is a real pain. 

I've tried unchecking the "queued" checkbox and it doesn't seem to have any effect whether i do it on a single download or each one. New downloads always start as "queued" I was waiting for an update hoping it would be fixed but still have this issue with 0.15.1. An option in the settings at least would be nice since i understand why this would be default behavior in certain use cases, but having no way to undo or change this behavior is kinda counter intuitive.

Assuming this is somehow related to #457 but this behavior only started with 0.15 as a regression maybe?

**Comment by Neodymium5312** [comment] 2019-01-29 13:01
Was mentioned by another user in #2068 as well so obviously i'm not the only one

**Comment by theScrabi** [comment] 2019-01-29 13:59
> All downloads are added as queued when added from share menu or from main application, is this intended behavior?

Yes. As the downloader already works multithreaded you don't get any performance improvements if you start two downloads at the same time, instead you are making it worse. This is why we decided to make downloads queued.

**Comment by epitron** [comment] 2019-01-29 16:57
He wants one download to start at the same time... :) See here: "Having to go into the newpipe application and manually start each download is a real pain."

This is the same problem I'm having.

**Comment by Neodymium5312** [comment] 2019-01-29 17:00
I don't get any downloads starting at all. I have to manually open the application and start each one every single time. And if I forget and the download times out. Then I have to open the video again, add the download again, clear the old download, and then start the new download. This is untenable. It's insane, and an awful UX. I don't understand why I have to go through all this trouble. Point out the code I need to change and I will build the apk myself. I've already tried but I couldn't figure out what needed to be changed as I don't code in this language

**Comment by Neodymium5312** [comment] 2019-01-29 17:02
I just want it to work the way it did before where each download would start up and the next would queue until the first was done. I don't need multithreading, I don't need more than one download at a time. I just want it to fricken work without having to babysit over 200 downloads every single day.

**Comment by Symbian9** [comment] 2019-02-01 13:56
> so obviously i'm not the only one

I also don't like new hard-coded "queue instead of multiple downloads"!

Please, add check-box option "Mulitply downloads" into "Settings > Download", so users could switch to previous "multiple downloads" behavior!

**Comment by Neodymium5312** [comment] 2019-02-01 14:11
@theScrabi misread my issue and closed it without understanding that something is broken for me since downloads don't start on their own at all. Whatever, guess ill just switch over to another application and reinstall newpipe once this is fixed. @epitron knows what issue i'm explaining but i guess the dev didn't understand what i was trying to explain. I'm not holding out hope this will be fixed anytime soon, so I'll just go back to 0.14 and figure out a way to port the api changes to get it working properly

**Comment by TobiGr** [comment] 2019-02-01 14:41
Which Android version / ROM and device are you using? I wasn't able to reproduce your problem at all.

**Comment by Neodymium5312** [comment] 2019-02-01 14:43
I'm on the Moto z3, stock rom with magisk. Android 8.1 with Sept 1 patch. Nothing special

**Comment by Neodymium5312** [comment] 2019-02-01 14:45
Xt1929-4 retus Moto Z3 play

**Comment by epitron** [comment] 2019-02-01 21:39
I'm using a Galaxy S7 w/ stock ROM

**Comment by Neodymium5312** [comment] 2019-02-03 23:53
So I just figure out that they start as normal using mobile data. Seems this only happens on Wi-Fi for some reason. I never use my data to download videos since I pay per GB. Can anyone else confirm this @epitron

**Comment by epitron** [comment] 2019-02-04 03:45
They don't start for me in both cases: WiFi and mobile. I tried changing the "pause downloads when on mobile" setting in both scenarios, and it didn't make a difference.

**Comment by Neodymium5312** [comment] 2019-02-04 03:50
And now I can't get it working again. I don't understand what I did but it's stopped working again for me. It worked for that one video and now it still is making all videos queued when adding them. I even tried adding the same video again with no dice.

**Comment by Neodymium5312** [comment] 2019-02-04 04:07
@epitron try rebooting it downloads the video once I reboot. I assuming 5his has something to do with the applications background or downloader service being shut down possibly?

**Comment by Neodymium5312** [comment] 2019-02-04 04:11
Are you running dns66? I think it might have something to do with it. I forced closed newpipe still works. I've closed and opened it multiple times and also used the share function form YouTube application no changes. But once I open dns66 it stops working

**Comment by Neodymium5312** [comment] 2019-02-04 04:38
Okay it's definitely dns66 causing the issue know my end. Stopping the VPN or even force stopping the application doesn't unbreakable newpipe either. A full reboot is required to make downloads act as expected. @epitron

**Comment by Neodymium5312** [comment] 2019-02-04 04:46
@symbian9 would this be enough information to repro on your side?

**Comment by Symbian9** [comment] 2019-02-04 20:04
> would this be enough information to repro on your side?

I use *NetGuard* as firewall on my Android 5.1 device & will newer dissable it while phone connected to network — so I can't reproduce steps above.

Anyway, I has NO such issues with *NewPipe* 14.1 (and older) on my device with *NetGuard* enabled — when I add new download it started immediatly.

So, I just want an option in *NewPipe* 15.x "Download" settings:

- [x] Old download method

**Comment by epitron** [comment] 2019-02-04 20:07
Ah, that explains it! I'm using NetGuard as well. I guess NewPipe is refusing to start downloading unless it thinks it's connected to the internet, and the VPN is confusing its detection code.

**Comment by Symbian9** [comment] 2019-02-04 20:10
> They just need to fix the queueing code when a VPN is active.

Agreed.

**Comment by 2137mail** [comment] 2019-02-13 10:19
My problem is different, I think. Downloads NEVER start, stuck in queue. I have tried to disconnect my VPN (AirVPN), no difference. Cleared cache, cleared data, installed, re-installed. Nothing. Can anyone help, please?

**Comment by Symbian9** [comment] 2019-02-13 11:44
> My problem is different, I think. Downloads NEVER start, stuck in queue.

I has same behavior.

**Comment by 2137mail** [comment] 2019-02-14 18:09
who can help with the issue?Philippe Margery




13 Feb 2019, 12:44 by notifications@github.com:

**Comment by kptkill** [comment] 2019-02-20 22:10
I am seeing the issue as well, though downloads sit in queued even if I turn off DNS66 prior to attempting a download.  I've also force quit new pipe after stopping DNS66.  Manually starting downloads in the queue works fine.  Android 8.0 LG G5 on wifi and mobile networks.

**Comment by kapodamy** [comment] 2019-02-24 01:14
this happens with any vpn/proxy app? my phone is too old for dns66 and airvpn (android 4.4)

**Comment by Neodymium5312** [comment] 2019-02-24 01:17
It's any vpn at all on my device. I'm using pia VPN now with the same issue. I believe if s vpn is selected at all within the Android settings it prevents downloads from starting

**Comment by 2137mail** [comment] 2019-02-24 10:42
I only tried with airvpn switched and then switched off. Same in both cases 



24 févr. 2019 à 02:14 de notifications@github.com:

**Comment by Neodymium5312** [comment] 2019-02-24 10:58
If you switch it off completely and then reboot without the VPN set to
start at boot then newpipe will behave normally. This is the only way I've
found that works to fix this. Something is getting cached once the VPN is
started and a reboot seems to clear whatever it is.

**Comment by 2137mail** [comment] 2019-02-24 13:12
So this worked when I downloaded without the vpn (after reboot). When I then switched on the vpn again it failed to download. Then I switched off the vpn without rebooting and it still didn't download. 
Is this being seen by the developers? Are you in the dev team or just a kind user helping out? :) 
24 févr. 2019 à 11:58 de notifications@github.com:

> If you switch it off completely and then reboot without the VPN set to
>  start at boot then newpipe will behave normally. This is the only way I've
>  found that works to fix this. Something is getting cached once the VPN is
>  started and a reboot seems to clear whatever it is.
>

**Comment by Neodymium5312** [comment] 2019-02-25 00:12
I'm just the one started the thread. There's a pull request that hopefully fixes this issue. But we'll have to wait for a merge and release to see if it helps or not.

**Comment by epitron** [comment] 2019-02-25 03:37
It doesn't look like this is addressed in the pull request yet...

**Comment by Neodymium5312** [comment] 2019-02-25 04:00
I was reading the closing comments for  https://github.com/TeamNewPipe/NewPipe/issues/2149
And it says that it possibly closes #2072 but I'm not sure if that's correct since I can't verify

**Comment by litlmike** [comment] 2019-03-05 23:59
I have this same issue.  No downloads start.  I like the downloads being queued, but I do not like that NO downloads begin, unless I manually tell it to download each download.

**Comment by epitron** [comment] 2019-03-06 02:53
@Neodymium5312 The latest update didn't fix the issue. :\

**Comment by Symbian9** [comment] 2019-03-06 08:03
> The latest update didn't fix the issue. :\

I still has this issue with *NewPipe* `0.16.0` too

**Comment by Flashwalker** [comment] 2019-03-15 20:09
Just updated to 0.16 and got same shit:  
> All downloads start as "Queued" 
> I don't get any downloads starting at all. I have to manually open the application and start each one every single time...

**Comment by tusch001** [comment] 2019-06-12 17:24
Reactivating this issue
16.2
still no automatic start of download when vpn is active (and thereafter)
all android versions (stock 6.0, lineageos 14.1, 15.0, 16.0) on different phones / tablets
all rooted either VPN by Orbot or VPN for Android. Also Stock Android 7.1 - non-rooted with Netguard.
Can I help testing?

**Comment by mouarfff** [comment] 2019-07-02 12:40
if i can help too, just this week ...

**Comment by cuilean** [comment] 2019-07-10 16:04
i also have a problem when the videos actually download. the video goes in my gallery but it has no sound. however, when i transferred the video to my PC, the sound works. weird...

**Comment by Stypox** [comment] 2019-07-10 16:43
@cuilean #1372 may be the problem you are encountering. If it is not, please open a stand-alone issue.

**Comment by tusch001** [comment] 2019-08-06 13:31
VPN issue seems to be fixed in 17.0.RC2 (at least for me). Thanks

**Comment by mouarfff** [comment] 2019-08-10 09:45
good :)

so where can i download this version ? need to wait for realease ?

**Comment by gkeegan** [comment] 2019-08-10 10:05
@mouarfff #2483 is where you can find some apks for it.

**Comment by mouarfff** [comment] 2019-08-10 10:35
thx :)

i have no issue now ;)

**Closed** 2019-08-18 19:27 UTC
