### ISSUE TITLE
Could not load decryption code, with the latest version... since last days.

### ISSUE THREAD

**Issue by m00x-pixel** [TeamNewPipe/NewPipe#4280] opened 2020-09-14 21:16 UTC
Hi,

i use newpipe since an long time include the latest 0.19.8 (Github version) on two different mobile phones. 

But since last week on one phone the app show only the error message below, on every video i try to load. First i though it is an general issue so i tried it on the second phone too. But here the videos play without any problem.

What i did already: delete the app and download the apk and install it again, but it stay the same. 

Can someone give some hint what could cause this?

Error: 

## Exception
* User Action: requested stream
* Request: https://www.youtube.com/watch?v=R-Yq1AlIwsc
* Content Country: DE
* Content Language: de
* App Language: de_DE
* Service: YouTube
* Version: 0.19.8
* OS: Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

org.schabi.newpipe.extractor.exceptions.ParsingException: Could not load decryption code for the Youtube service.
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerUrl(YoutubeStreamExtractor.java:706)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:656)
 at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
 at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
 at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
 at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
 at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
 at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
 at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
 at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerUrl(YoutubeStreamExtractor.java:701)
 ... 30 more

</details>
<hr>

Sample Video but all my tries are the same, so it seems not be specific to an special video: 
YouTube (https://www.youtube.com/watch?v=R-Yq1AlIwsc)

**Comment by opusforlife2** [comment] 2020-09-14 21:18
Duplicate of #3753. Always check before opening.

**Closed by opusforlife2** 2020-09-14 21:18 UTC
Labels: bug
