### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by qg0** [TeamNewPipe/NewPipe#6938] opened 2021-08-17 22:23 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ none
* __Version:__ 0.21.8
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment VideoDetailFragment{4fce7b4} (cc1d7f2c-8606-43ca-888d-95c0de3a04dd) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at org.schabi.newpipe.error.ErrorActivity.reportErrorInSnackbar(ErrorActivity.java:98)
	at org.schabi.newpipe.fragments.BaseStateFragment.showSnackBarError(BaseStateFragment.java:211)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$2.onLoadingFailed(VideoDetailFragment.java:690)
	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask$2.run(LoadAndDisplayImageTask.java:360)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```
</details>
<hr>

**Comment by litetex** [comment] 2021-08-18 17:48
Duplicate of #5998

Also please fill out the template accordingly.

The problem originates from the ImageLoader who will be replaced with #5928

**Closed** 2021-08-24 08:52 UTC
Labels: bug, user-ignored-template-instructions
