### ISSUE TITLE
Video not resizing when switching from portrait to landscape.

### ISSUE THREAD

**Issue by Elmoww** [TeamNewPipe/NewPipe#7333] opened 2021-10-30 06:00 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior
When pressing the fullscreen button on the player the video stays the same size in landscape mode as it was on portrait mode. When Automatic Switching is turn on,  it scales fine.

### Expected behavior
Fullscreen playback.

### Screenshots/Screen recordings
![Screenshot_20211030-075221](https://user-images.githubusercontent.com/93420401/139522129-91021c4b-0e24-4e0b-a2e1-f212d81d0534.png)

### Device info

 - Android 12
 - Pixel 3a

**Comment by Kr1sh1** [comment] 2021-10-31 15:15
Can confirm.

Version 0.21.13
Pixel 6
Android 12

Although moving back to portrait, then to landscape again usually works.

**Comment by litetex** [comment] 2021-11-01 21:52
Duplicate of #7262

**Closed by litetex** 2021-11-01 21:52 UTC
Labels: bug, player
