### ISSUE TITLE
Video Restarts when copying the link to the clipboard

### ISSUE THREAD

**Issue by Darkshine0** [TeamNewPipe/NewPipe#3453] opened 2020-04-18 13:45 UTC
When watching a video if you try to copy the link to the clipboard, the video itself actually restarts and instead of resuming from where you left it goes back to the very beginning of the video

### Version

-0.19.2

### Steps to reproduce the bug

Play a video. Pause it. Try sharing it by copying it trough the clipboard.

### Expected behavior

The video should've resumed from the point I was watching. 
### Actual behaviour

The video came back to the start. 
### Logs

.

**Comment by XiangRongLin** [comment] 2020-04-18 16:04
Duplicate of #3268

**Closed** 2020-04-18 16:10 UTC
Labels: bug
