### ISSUE TITLE
Show Channel's Curated Playlists

### ISSUE THREAD

**Issue by ieredcat** [TeamNewPipe/NewPipe#3489] opened 2020-04-25 22:29 UTC
#### Describe the feature you want

I think it would be great if Channel Curated Playlists were shown and not just a list of all the videos.

#### Is your feature request related to a problem? Please describe it

How does the 'auto' option work for the 'list' and 'grid' options? No matter how I orientate my device it only shows list unless I choose 'grid' manually. I don't know if this is a bug or if it depends on the type of device I have (I use a Samsung Galaxy S8; SM-G95OU and it's fully updated).

#### How will you/everyone benefit from this feature?

I think this feature should be added so us users don't have to scroll indefinitely until we find videos that interests us on a certain channel. Channels group related videos together so viewers can find what they need faster and more efficiently.

Even though the 'grid' option for orientation makes scrolling through the feed more bearable, having related videos pre-grouped together by the channel creators themselves makes the process quicker, especially if the channel has a lot of videos curated in one playlist.

**Comment by wb9688** [comment] 2020-04-26 05:47
You mean like I was working on in #3201? If so, I'm closing this as a duplicate of #2414. Please look of your issue already exists next time. I think grid is only enabled by default on tablets.

**Closed by wb9688** 2020-04-26 05:47 UTC
Labels: enhancement
