### ISSUE TITLE
System UI broke (Popup Player)

### ISSUE THREAD

**Issue by cebeyip876** [TeamNewPipe/NewPipe#7331] opened 2021-10-30 03:56 UTC
### Checklist

- [x] I am using the latest version - Newpipe Stable Channel (FDroid)
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

When Launching Popup window and navigating to Home screen System Ui is unresponsive With Display over other apps in off system Ui is fine

### Expected behavior
play videos with ui responsive

### Device info

 - Android version/Custom ROM version:Graphene Os An12
 - Device model: Pixel 3

**Comment by graingert** [comment] 2021-10-30 12:35
Seems a dupe of https://github.com/TeamNewPipe/NewPipe/issues/7321

**Comment by mhmdanas** [comment] 2021-10-30 13:22
Duplicate of #6770.

**Closed by mhmdanas** 2021-10-30 13:22 UTC
Labels: bug
