### ISSUE TITLE
Donate-Button crashes App on Android TV

### ISSUE THREAD

**Issue by LiPoPower** [TeamNewPipe/NewPipe#7249] opened 2021-10-14 15:33 UTC
### Checklist

- [x] I am using the latest version - 0.21.10 
- [ X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Info' in mainMenü'
2. Press on 'Give Back/Donate Button'

### Actual behavior
The App crashes.

### Expected behavior
Display Infos how to donate to the project

### Screenshots/Screen recordings

No Screenshots available, NewPipe running on an Android TV Philips 55PUS7305

### Logs

Sorry, can not paste the crash report, because i can't navigate to the mentioned "Copy formatted report"-Button with my remote.

### Device info

 - Android version/Custom ROM version: 9 (?), Sorry can't figure out the precise Android version
 - Device model: Philips 55PUS7305 Android TV

**Comment by mhmdanas** [comment] 2021-10-15 04:37
> Sorry, can not paste the crash report, because i can't navigate to the mentioned "Copy formatted report"-Button with my remote.

Hmm, maybe this should be fixed?

Anyway, I don't have NewPipe on my hand, so I can't really attempt to reproduce this. Could you at least send a screenshot or a picture of the log (I usually loath pictures of errors, but they're better than nothing at least)?

**Comment by LiPoPower** [comment] 2021-10-15 05:38
yes, shure.
Here is the link to google fotos:
[https://photos.app.goo.gl/Rf45jsZowxdTt3gt8](url)

**Comment by peat80** [comment] 2021-10-15 15:57
Probably device / firmware related. On shield tv it opens the links on the about tab in installed browser as expected (or shows a toast if no browser is installed).

**Comment by litetex** [comment] 2021-10-16 23:29
The error says ``Permission Denial: Starting intent ...``.
Looks like NewPipe has no permission to open the browser...

@LiPoPower 
Can you check if the permissions for the app are set correctly (if there are any)?
Also does e.g. sharing a video to a browser work?

**Closed** 2021-10-30 00:06 UTC
Labels: bug, Android TV, waiting-for-author
