### ISSUE TITLE
Duplicate check on playlists.

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#5643] opened 2021-02-19 19:17 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

If i were to add a video to a playlist when its already in there a duplicate is made. Imo. this is a bit counterintuitive. There could be a warning, when adding the video with confirmations, maybe a popup saying its already in there and not adding a video. Or alternatively moving the video to the end of the playlist.

#### Is your feature request related to a problem? Please describe it

no

#### How will you/everyone benefit from this feature?

Easier playlist management for people who use it as a database

**Comment by mhmdanas** [comment] 2021-02-20 13:46
I believe is a duplicate of #4186.

**Closed by mhmdanas** 2021-02-20 13:46 UTC
Labels: enhancement
