### ISSUE TITLE
Feature Request: Dynamic zoom in / zoom out while watching videos to be able to see details on small screens

### ISSUE THREAD

**Issue by ondernuray** [TeamNewPipe/NewPipe#3364] opened 2020-04-04 21:05 UTC
Dynamic Zoom in / Zoom out while watching videos. It is useful while learning programming languages on Youtube via small screen mobile phone.

Thanks
Onder

**Comment by Stypox** [comment] 2020-04-05 06:50
Duplicate of #3217

**Comment by Stypox** [comment] 2020-04-05 06:50
Also duplicate of #1406

**Closed by Stypox** 2020-04-05 06:50 UTC
