### ISSUE TITLE
Soundcloud "double subscribe"

### ISSUE THREAD

**Issue by pr0gr8mm3r** [TeamNewPipe/NewPipe#1237] opened 2018-04-01 09:40 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

# Steps to reproduce
1. Subscribe to a Soundcloud channel
2. Go to Subscriptions tab and click on the channel
3. Press the subscribe button again
4. Channel appears two times in Subscriptions Tab
5. If I click on any of the two the button says "Subscribed"
6. If I unsubscribe the channel only appears once

**Version 0.13.0**

**Comment by pr0gr8mm3r** [comment] 2018-04-01 10:35
I recently tested it on another device (emulator API 27) and I was not able to reproduce the issue.

**Comment by theScrabi** [comment] 2018-04-01 13:41
I was not able to reproduce that bug. Did you subscribe to a specific channel?

**Comment by pr0gr8mm3r** [comment] 2018-04-01 21:03
Yes, it is called 'Jogeir'. On the emulator i tried a different channel (Adele), which also works correctly on my phone.

**Comment by Stypox** [comment] 2019-07-19 12:56
Closing in favour of #2167 
The issue is not soundcloud specific

**Closed by Stypox** 2019-07-19 12:56 UTC
Labels: soundcloud
