### ISSUE TITLE
[0.21.2] Searching anything fails

### ISSUE THREAD

**Issue by JulienGn** [TeamNewPipe/NewPipe#6327] opened 2021-05-18 08:06 UTC
Checklist

 I am using the latest version - 0.21.2

 I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

 I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

 This issue contains only one bug. I will open one issue for every bug report I want to file.

Steps to reproduce the bug

- Open the New pipe client
- Search anything
- Fail

Actual behaviour
Search fail, and says the website cannot be analyzed

Expected behavior
Should display my search videos

Device info
Android version/Custom ROM version: Linux Android 9 - 28
Device model: Xiaomi Note 9 Pro

Note: the frontpage suggestions videos are still working through.

**Comment by e-aleixandre** [comment] 2021-05-18 19:36
Installing v0.21.1 (previous version) solved it for me. I guess we need to wait for the next one ;)

**Comment by JulienGn** [comment] 2021-05-19 08:12
Yes, I confirm rollbacking to version 0.21.1 search function does work currently.

This might help the dev team to fix this issue quicker.

**Comment by bberry259** [comment] 2021-05-20 05:22
I've been struggling with the same issue for some time on 0.21.2 (Graphene OS ). I've tried reinstalls, clearing cache etc.
Reverting to 0.21.1 worked for me. Search has returned as have comments (which also weren't working).

**Comment by Disqu3-mirOir-qt** [comment] 2021-05-21 14:09
im my side seem fixed by himself , maybe google do change

**Comment by chwallen** [comment] 2021-05-29 09:32
I still have this issue in 0.21.3.

**Comment by TiA4f8R** [comment] 2021-05-29 11:54
What crash report do you get?

**Comment by JulienGn** [comment] 2021-05-29 12:44
-------------------------------------
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:279)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:297)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:375)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:234)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:60)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:80)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$qyxpuXgomWa-cbONQns-pd7zxm0.call(Unknown Source:8)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "var\s*ytInitialData\s*=\s*(\{.*?\});"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:54)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:275)
	... 20 more
-------------------------------------

**Comment by TiA4f8R** [comment] 2021-05-29 15:52
So it's a duplicate of #5977. Closing. Please search better for duplicates next time (try using the message of stacktraces if you can't find anything)!

**Closed by TiA4f8R** 2021-05-29 15:52 UTC
Labels: bug, more info needed
