### ISSUE TITLE
add "play in reverse order" button or option

### ISSUE THREAD

**Issue by joshatt** [TeamNewPipe/NewPipe#5490] opened 2021-01-26 03:43 UTC
#### How will you/everyone benefit from this feature?

"play in reverse order", this will be wonderful for audiobook, podcast or lectures.
And, "sorting playlist" is not enough, audiobook podcast or lectures are not limited to playlist format, it'll be better if channels are also covered. Either channel or playlist, when new video added it gets complicated, so, a simple "play in reverse order" button or option will cover all situations.
Please consider in future version.

**Comment by mhmdanas** [comment] 2021-01-26 05:20
Duplicate of #3815. Also, please don't remove the checklist, as it's necessary.

**Closed by mhmdanas** 2021-01-26 05:20 UTC
Labels: enhancement
