### ISSUE TITLE
Failing to download videos.

### ISSUE THREAD

**Issue by Sky-Drifter** [TeamNewPipe/NewPipe#2367] opened 2019-05-28 23:55 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

 This happened a few hours ago, i tried to download a video, but it didn't "fetch" the info about the video (size, etc).
 The video "card" was stuck at  --.-%.
 I managed to download said video by restarting my device, but it gone straight to "queue" first, then i manually started the download.
My device is a Galaxy J6 running on stock android 8.0 using the latest version "0.16.1". Thanks.

**Comment by Sky-Drifter** [comment] 2019-05-29 00:25
It's seems to be related to the "No root Firewall" app, after uninstalling said app, Newpipe downloaded the video just fine.
 I didn't updated or downloaded any app, not even the firewall app. Thanks.

**Comment by gkeegan** [comment] 2019-05-29 00:56
was the firewall on

**Comment by gkeegan** [comment] 2019-05-29 00:57
Also, I believe this is unrelated to the firewall, as I have had the same issue.

**Comment by gkeegan** [comment] 2019-05-29 00:58
#2360

**Comment by Sky-Drifter** [comment] 2019-05-29 01:41
I checked #2360, it didn't even "downloaded" without showing any progress, even after trying to pause and start the download, it didn't work, the moment i turned the firewall off, some 5 or 6 secs later the download started normally.
 I even tried using Netguard firewall, to no avail, it's the same thing.
 Reinstalling Newpipe didn't helped either.
 Unlike #2360, Newpipe didn't crashed. Thanks

**Comment by Sky-Drifter** [comment] 2019-05-29 01:53
I almost forgot, @gkeegan could you try to download a video, but before you click on the download button, see if it shows the video size, i'm quite sure this is related to this issue. Thank you.

**Comment by Sky-Drifter** [comment] 2019-05-29 02:09
I forget to add, watching without downloading didn't worked either, it connected to the usual urls but it didn't downloaded the required files, etc. Thanks.

**Comment by gkeegan** [comment] 2019-05-29 02:44
About the video not showing a download size, was this a very recently released video?

**Comment by Sky-Drifter** [comment] 2019-05-29 02:58
Nope, the video was released some 6 months ago.

**Comment by puppykickr** [comment] 2019-06-05 06:14
This cannot be related to NoRoot Firewall.
I use that app, both on my 7.1.1 and my 8.1.0 without any difficulty downloading.

And it is the same with NetGuard.

The only way that either would interfere is if it was set to block NewPipe or any domain that NewPipe needs to access in order to perform the download.

That being said, I have been experiencing download problems as well.

What fixed the issue for me was to revert back to the default download destination folders.

Whenever I select my prefered destination folders, the file gets queued until I go into the settings, select downloads, and then manually start the download.

Very annoying, so I gave up and just use the default download folders.

**Comment by kapodamy** [comment] 2019-06-21 19:26
duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2072

**Closed** 2019-08-18 19:29 UTC
