### ISSUE TITLE
Feature request: Option to add channel name to download name...

### ISSUE THREAD

**Issue by paulescobar** [TeamNewPipe/NewPipe#2709] opened 2019-10-10 10:48 UTC
Currently, all downloads get thrown into a single directory. After a time, it becomes very hard to identify or organize videos from a specific source.

That's why it would be very helpful to have an option that lets us add the channel name to the start of the video title. That way we could know the video's author, and sort similar videos together in file managers.

**Comment by Stypox** [comment] 2019-10-10 12:26
Duplicate of #2282

**Closed by Stypox** 2019-10-10 12:26 UTC
