### ISSUE TITLE
NewPipe can't handle upcoming live stream links

### ISSUE THREAD

**Issue by nadiration** [TeamNewPipe/NewPipe#6101] opened 2021-04-17 16:40 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Go to any upcoming YouTube stream link for example https://youtu.be/5J3peD8LZ5o

### Actual behaviour

It says item not available

### Expected behavior

The stream link to load and show the thumbnail and people waiting to watch

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment] 2021-04-17 18:29
Duplicate of #5192.

**Closed by mhmdanas** 2021-04-17 18:29 UTC
Labels: bug
