### ISSUE TITLE
With Autoplay disabled, I cannot select the video quality or interact with other controls before/without playing it

### ISSUE THREAD

**Issue by shadow00** [TeamNewPipe/NewPipe#4458] opened 2020-10-09 08:25 UTC
### Checklist

- [x] I am using the latest version. 

- [x] I checked, but didn't find any duplicates of this issue in the repo. 

- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Disable Autoplay in the app settings

2. Open any Youtube video

### Actual behaviour

The playback settings (video quality, playback speed, screen fit, and the arrow that shows the mute and share buttons) cannot be used without playing the video.

### Expected behavior

I used to be able to interact with those settings before playing a video. The current interface breaks two usage scenarios:

1. I keep the default quality to the highest possible, but when I know that I'm in a place with bad/slow networking I want to manually lower the video quality before pressing play. Instead, I now have to press play and _then_ set the lower quality, and then wait for the player to get stuck while it's switching to the lower quality video.

2. Sometimes I want to share a video from its info screen, while I have a different video playing in the background. This is currently impossible, as I would have to press play first, thus blocking whatever I have playing in the background.  
There is a workaround (add the video to queue, open queue, long-press and share, then remove it from queue), but it's extremely impractical.   

### Screenshots/Screen recordings

![](https://i.imgur.com/6adDJsd.jpg)

**Comment by nbmrjuhneibkr** [comment] 2020-10-09 09:59
Same problem.  
If I already know that I want to open a video in an external app, why would I want to start playing it in NewPipe first?  
Same goes for the video quality: if I know that I want to play a video in a quality that is different from the default, why would I want to start playing it in the default quality first?  
Combined with https://github.com/TeamNewPipe/NewPipe/issues/4460 this also means that I can't share a video or open it in a different app without wiping my background queue.

This is terrible design and a clear step backwards from v0.18. These options should be re-implemented.

**Comment by opusforlife2** [comment] 2020-10-09 13:28
Duplicate of #4039.

**Closed by opusforlife2** 2020-10-09 13:28 UTC

**Comment by avently** [comment] 2020-10-09 14:28
@opusforlife2 if I remember correctly, it was you who asked to add autoplay disabled, right? Before that I didn't even have a setting for that so autoplay was always on :)

**Comment by opusforlife2** [comment] 2020-10-09 14:31
I don't remember if it was me or someone else, but I was sure glad when that setting was introduced. 🤭

**Comment by opusforlife2** [comment] 2020-10-10 14:07
Added these proposed buttons to #4039.

**Comment by ThomasLeigh** [comment] 2020-12-27 23:07
I have the impression that some time ago the following things were possible in *NewPipe* - **once You’ve opened a video page (in a vertical view, no full-screen) but not started playing the video yet:**

1. You could swipe alongside left or right side of a video to adjust brightness or volume.
2. You could set the quality of the video to be played.

Thanks to those things it had been very convenient to use *NewPipe*, especially given that I much like to set all those things **before** playing and that I use to watch some videos with different quality than others.

For some time now, however, to set all those things per video I need to play it first :( . Furthermore, in case of swipe gestures to adjust volume or brightness it seems to be possible only in full-screen mode :( .

Could the behavior described within the two points above be restored?
