### ISSUE TITLE
Possibility for duplicate subscriptions

### ISSUE THREAD

**Issue by gkeegan** [TeamNewPipe/NewPipe#2167] opened 2019-03-01 02:03 UTC
Currently there is a way to get infinite subscriptions to one channel.

Steps to reproduce:
1. Go to what's new page
2. Tap any video
3. Through the page for that video, visit the channel

The subscribe button doesn't show that you are subscribed, and if clicked will add the channel to your subscriptions, so that there are two of them shown.

This is present in release 0.16.0 and my build of dev branch from a little after 0.15.1. (And possibly a few more versions).

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

- [X] I checked if the issue/feature exists in the latest version.

**Comment by selurvedu** [comment] 2019-03-14 06:55
Same here.

**Comment by Stypox** [comment] 2019-05-04 19:05
I can't reproduce this (v0.16.1)

**Comment by gkeegan** [comment] 2019-05-04 20:47
Odd. I still can. I don't see how this could be a device specific issue though.

**Comment by Stypox** [comment] 2019-05-04 21:41
Am I doing something wrong?
![SVID_20190504_232040_1](https://user-images.githubusercontent.com/36421898/57185124-0b14c000-6ec6-11e9-9014-a8ad7860fdec.gif)

**Comment by gkeegan** [comment] 2019-05-05 01:08
Hm. That's odd. I found another way that activates it on my end. In search, search any channel. Ex: NASA. Click the channel, then hit subscribe. Now from that page, click a video. From the video page, click on the channel. It will show that you are not subscribed. Tapping it again will add the duplicate.

@Stypox if this doesn't cause the bug then I believe we may have to do some deeper digging.

**Comment by hp8wvvvgnj6asjm7** [comment] 2019-05-18 03:26
I have the same issue, and also I can't unsubscribe some channels, they show as not subscribed but still show up in my feed

**Comment by gkeegan** [comment] 2019-05-18 20:49
@hp8wvvvgnj6asjm7 I'm going to wait until the next release, as it seems like it will change a bunch of things related to subscriptions and feeds. Hopefully it will fix your issue.

**Comment by Stypox** [comment] 2019-08-12 08:12
It happened to me today. It seems to be a problem with only some channels. [Jim Yosef](https://invidio.us/channel/Jimboows) is one of them. NewPipe checks whether a subscription already exists by looking for its url in the database, so I suppose this problem is caused by different urls for the same channel. This should probably be fixed in the extractor, so that it always produces the same link for the same channel.

**Comment by Stypox** [comment] 2019-08-12 08:21
After logging the channel info I see the difference:
- the url in the database is `https://www.youtube.com/user/Jimboows`
- the url from the video is `https://www.youtube.com/channel/UCf5q0cbFOLbphljteZ9d4Pw`

**Closed** 2019-08-17 22:42 UTC
