### ISSUE TITLE
Crash after long press

### ISSUE THREAD

**Issue by Feuerswut** [TeamNewPipe/NewPipe#7470] opened 2021-11-30 18:10 UTC
### Checklist

- [x] I am using the latest version - F-Droid 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to Video selection (and have autoplay on click disabled)
2. Press on the video
3. Press on play in the bottom right corner
4. Immediately: long press on another video in the feed
5. CRASH - null object reference (the queue size has not yet been set by NewPipe.

I'd suggest setting the queue size to 0 or 1 before requesting the video contents and then setting the queue size, just to avoid the bug OR try catching the null object and doing nothing (the user will just be irritated, but the app wont crash)

### Actual behavior

The app crashes after long click has been performed

### Expected behavior

The app brings up the content (video options) menu for the appropriate video

### Screenshots/Screen recordings

[![Crash Video](https://gcdn.pbrd.co/images/sgR6MeKJpK1L.png)](https://www.youtube.com/watch?v=sgXgQ56qnpY)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.size()' on a null object reference
	at org.schabi.newpipe.player.helper.PlayerHolder.getQueueSize(PlayerHolder.java:74)
	at org.schabi.newpipe.local.feed.FeedFragment.showStreamDialog(FeedFragment.kt:331)
	at org.schabi.newpipe.local.feed.FeedFragment.access$showStreamDialog(FeedFragment.kt:80)
	at org.schabi.newpipe.local.feed.FeedFragment$listenerStreamItem$1.onItemLongClick(FeedFragment.kt:390)
	at com.xwray.groupie.GroupieViewHolder$2.onLongClick(GroupieViewHolder.java:32)
	at android.view.View.performLongClickInternal(View.java:7521)
	at android.view.View.performLongClick(View.java:7479)
	at android.view.View.performLongClick(View.java:7497)
	at android.view.View$CheckForLongPress.run(View.java:28634)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>
<hr>

### Device info

 - Android version: And. 12 Patch Nov. (1), stock
 - Device model: Pixel 6

**Comment by Feuerswut** [comment] 2021-11-30 18:10
Uploading newpipe exception 7184.mp4…

**Comment by Feuerswut** [comment] 2021-11-30 18:25
info: click on the image to open video.

**Comment by litetex** [comment] 2021-11-30 18:27
Duplicate of #7305.
You may give that issue an upvote 😉 

Btw: I'm currently waiting for your reply in #7414

**Closed by litetex** 2021-11-30 18:27 UTC
Labels: bug, template-ignored

**Comment by Stypox** [comment] 2022-01-25 16:44
Could you test if #7704 solves the issue?

**Comment by litetex** [comment] 2022-01-25 18:16
@Stypox
Could you please not repost the above line under every duplicated issue of #7305 in the future?
We want to keep the discussion inside #7305.

**Comment by Stypox** [comment] 2022-01-26 08:42
Sorry, I just wanted to get all users to test, next time I'll ping in the main issue
