### ISSUE TITLE
Playlist video count messed up

### ISSUE THREAD

**Issue by Whitespace-code** [TeamNewPipe/NewPipe#6804] opened 2021-07-29 22:51 UTC
### Checklist

- [x] I am using the latest version - 0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Look (not from the search menu) at this playlist: `https://www.youtube.com/playlist?list=PL8dPuuaLjXtNlUrzyH5r6jN9ulIgZBpdo`

You should see a video count of above 10000000.

### Actual behavior

The Video count shows as more than 10 million. In the bookmarked playlist tab, the number isn't even shown completely.

### Expected behavior

It should have shown 41 videos.

### Screenshots/Screen recordings

![20210730_003644](https://user-images.githubusercontent.com/76942454/127574920-5aa5d0a9-537f-4c95-938e-7fc58eefe677.png)
![Screenshot_20210730-003523](https://user-images.githubusercontent.com/76942454/127574975-6d7ac46b-2e15-440a-9881-a7f144e5e778.png)

### Device info

 - Android version/Custom ROM version: Android 6 (Samsung)
 - Device model: Samsung Galaxy J5
 - Unrooted

**Comment by mhmdanas** [comment] 2021-07-30 01:12
Duplicate of #5004.

**Closed by mhmdanas** 2021-07-30 01:12 UTC
Labels: bug
