### ISSUE TITLE
Newsfeed play all in a row

### ISSUE THREAD

**Issue by vozer** [TeamNewPipe/NewPipe#7988] opened 2022-03-04 19:49 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When I am watching my feed I would like be able to click on video and select "play list from here", then x number of videos should be queued as a play list and played after each other. 

### Why do you want this feature?

To watch my feed I always have to click the video, click out, select the next etc. Especially with short videos this is time consuming and irritating.

**Comment by SameenAhnaf** [comment] 2022-03-04 23:29
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3362

**Closed** 2022-03-06 14:06 UTC
Labels: enhancement, duplicate
