### ISSUE TITLE
[Feature request] Add a setting that the video is always start in fullscreen

### ISSUE THREAD

**Issue by ovz93br43v7** [TeamNewPipe/NewPipe#5281] opened 2020-12-26 11:28 UTC
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I would like to have a setting to define that every video I click on is then started in fullscreen and that disable the minimized videos.

#### Is your feature request related to a problem? Please describe it
On my FireTv stick with remote it is hard to reach the button for fullscreen. So it would make my life easier when I could select the above described setting.

#### How will you/everyone benefit from this feature?
Improved usability on FireTV stick ;-)

**Comment by mhmdanas** [comment] 2020-12-26 18:42
Thanks for opening an issue! Could you please not make the headers (the things that start with `####`) bold? It's ruining the formatting. :)

**Comment by ovz93br43v7** [comment] 2020-12-26 20:39
I removed the "**" but it is still bold o.O

**Comment by mhmdanas** [comment] 2020-12-26 20:41
Well, to be more specific, I wanted you to remove the `**`. Headers are usually rendered as bold.

**Comment by mhmdanas** [comment] 2021-01-19 12:32
Closing as a duplicate of #4387. If I misunderstood something and it's not actually a duplicate, feel free to write a comment.

**Closed by mhmdanas** 2021-01-19 12:32 UTC
Labels: enhancement
