### ISSUE TITLE
Newpipe

### ISSUE THREAD

**Issue by codycox24** [TeamNewPipe/NewPipe#6218] opened 2021-05-02 03:44 UTC
Download track issue

**Comment by fynngodau** [comment] 2021-05-02 08:16
Could you please be more specific what the issue is, when it happens, and whether there are any errors shown to you? Please also use the [issue template](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md).

Since your report is currently not helpful for solving your problem, I will now close this issue.

**Closed by fynngodau** 2021-05-02 08:16 UTC
Labels: doesn't-follow-template
