### ISSUE TITLE
constant video jerking, buffering problem.

### ISSUE THREAD

**Issue by retropassion** [TeamNewPipe/NewPipe#6611] opened 2021-07-05 08:26 UTC
Hello, 

For some time I have been experiencing a rather annoying problem (version 21.5 on Android)
All videos (Youtube) are not played correctly, it makes jerks every second. There is a problem of cache and buffering of the videos. 
I must admit that it is very problematic (Same problem with 4G or WIFI)

Can you report this problem to the developers ? 

Thank you very much for this application and your work !

**Comment by Doctor-blob** [comment] 2021-07-05 09:18
Same Problem here

**Comment by Disqu3-mirOir-qt** [comment] 2021-07-05 11:05
same for me need clear cache every time after 2-3 video see

**Comment by botistreamer** [comment] 2021-07-05 11:40
Duplicate of #6510.

Atleast check the pinned issues before making a new issue.

**Closed** 2021-07-05 12:33 UTC
Labels: bug

**Comment by TiA4f8R** [comment] 2021-07-05 12:41
Also, don't remove the issue template when opening an issue.
