### ISSUE TITLE
Recommended videos

### ISSUE THREAD

**Issue by xDevoidx** [TeamNewPipe/NewPipe#8466] opened 2022-06-01 20:13 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Adding a recommended videos page to the start site, just like YT.

### Why do you want this feature?

It would be nice seeing recommended videos because the trends aren't always the best and often you click on videos on those recommended pages you didn't even knew of

**Comment by SameenAhnaf** [comment] 2022-06-01 21:51
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2256

**Closed** 2022-06-11 18:37 UTC
Labels: enhancement
