### ISSUE TITLE
Allow moving backwards/forwards by clicking on time stamps in comments

### ISSUE THREAD

**Issue by nicolasmaia** [TeamNewPipe/NewPipe#2851] opened 2019-12-09 05:28 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

It's common for YouTube video descriptions or comments to feature certain timestamps indicating when a given song or segment starts. As of now, clicking on them opens yet another instance of NewPipe. Ideally, it would only work on the now-being-played-video.

**Comment by SameenAhnaf** [comment] 2021-09-03 11:06
@Stypox Isn't this a duplicate of #4241?

**Comment by Anon1444** [comment] 2021-09-12 04:09
Please do something regarding this.

**Comment by Stypox** [comment] 2021-09-27 09:25
#4241

**Closed by Stypox** 2021-09-27 09:25 UTC
Labels: enhancement, player
