### ISSUE TITLE
Video interface improvement

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1117] opened 2018-02-16 21:36 UTC
I have some ideas to improve the video +popup interface
      -   First, make possible to see the video while reading the description for example, without using the "switch to popup" button (because its not handy) You could make a button which appears when your phone is horizontal to switch quilckly:
http://i65.tinypic.com/21lo9z9.png
        
   - then the popup should be deletable more easily, for instance as the messenger app (an area who deletes the popup):
http://i65.tinypic.com/200com0.png

   - Finally the ability to resize and replace the popup when you go to another Newpipe page (as the subscription page), like the YouTube app do :
http://i68.tinypic.com/4u8g01.png

The most important would be that all this functionalities could be enabled or disabled by the user, to make newpipe as customizable as possible :)

**Comment by justanidea** [comment] 2018-02-17 11:10
Any suggestions?

**Comment by speednroll** [comment] 2018-02-17 17:07
I do not know, I like Newpipe as such with the options it already has...

**Comment by theScrabi** [comment] 2018-02-17 17:42
These are some coll suggestions, but for us now are just other things more important. However a helping hand is always wellcome ;D

**Comment by justanidea** [comment] 2018-02-17 18:32
I would like to help... but i havent the knowledge :')

**Comment by Stypox** [comment] 2019-07-18 14:21
Please change this issue to only include the third suggestion, since the first one is on #1126 and the second one has already been implemented.

**Comment by Stypox** [comment] 2020-03-08 09:33
1. Duplicate of #1126
2. Implemented
3. Duplicate of #1200

**Closed by Stypox** 2020-03-08 09:33 UTC
Labels: GUI, enhancement
