### ISSUE TITLE
[feature request] save the last used Playback speed setting. 

### ISSUE THREAD

**Issue by Samyak039** [TeamNewPipe/NewPipe#3212] opened 2020-03-11 14:29 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

now in the app the default speed is 1x but I like to watch at 1.5x so now I have to adjust it in the beginning of every video to the desired speed. 

it would be nice if the app remembers the last used speed setting and uses the same for every video untill I manually changes the setting.

**Comment by XiangRongLin** [comment] 2020-03-11 17:04
This should be pretty easy to implement.
If someone new wants to try they could look at how #3043 is implemented.

Otherwise i would do it.

**Comment by Samyak039** [comment] 2020-03-12 16:05
@XiangRongLin sorry, I am noob to this so I won't be able to do this

**Comment by Stypox** [comment] 2020-03-13 13:08
Duplicate of #735

**Closed by Stypox** 2020-03-13 13:08 UTC
