### ISSUE TITLE
version 530f745 2020-09-08 crush when i click on video

### ISSUE THREAD

**Issue by Domiuns** [TeamNewPipe/NewPipe#4267] opened 2020-09-10 20:16 UTC
### Version

-

### Logs

I have test apk on android 4.4 and apk version 530f745 2020-09-08 block my phone when crash
Demostration video https://streamable.com/e/ygkbwt

**Comment by opusforlife2** [comment] 2020-09-10 20:26
Does it happen with the 2020-09-06 version?

**Comment by avently** [comment] 2020-09-10 20:42
Yes, please, test previous versions too which will help to find the cause. And say which one started to do this crash first. Even better would be to receive logs from `adb logcat` if you know how to get them.

**Comment by Domiuns** [comment] 2020-09-10 22:42
@opusforlife2 version a801d09 2020-09-06 not have this problem work normal

**Comment by opusforlife2** [comment] 2020-09-11 09:46
@Stypox Could have been caused by #3909, then?

**Comment by Stypox** [comment] 2020-09-11 12:01
@opusforlife2 by #3909 or by #4154. We would need to do a `git bisect` until we find the specific commit causing the issue, but it is complicated to do this without instant feedback. Let me try anyway based on some guesses:
- apk before fixing intrusive deprecations: ba6c7de35a87c92f65a3b5d9f0f65d3c0aaa22c7 [ba6c7de35a87c92f65a3b5d9f0f65d3c0aaa22c7.zip](https://github.com/TeamNewPipe/NewPipe/files/5208732/ba6c7de35a87c92f65a3b5d9f0f65d3c0aaa22c7.zip)
- apk after fixing intrusive deprecations: a4feb3fc09b734d4365bc498ed0289c7dc3558cf [a4feb3fc09b734d4365bc498ed0289c7dc3558cf.zip](https://github.com/TeamNewPipe/NewPipe/files/5208742/a4feb3fc09b734d4365bc498ed0289c7dc3558cf.zip)
- apk just after #4154's merge, before #3909: 14486782dcfb3ac99965b995c1e45c6368c05ce5 [14486782dcfb3ac99965b995c1e45c6368c05ce5.zip](https://github.com/TeamNewPipe/NewPipe/files/5208731/14486782dcfb3ac99965b995c1e45c6368c05ce5.zip)

@Domiuns could you try the apks above? Thank you in advance for you patience. By the way, since the apks above are in chronological order, if already the second one does not work, you don't have to test the third one, as that would obviously not work.

**Comment by avently** [comment] 2020-09-11 12:20
@Stypox why it keeps crashing without showing error activity? What's s way the user can use to send us logs (without obvious `adb logcat`)?

**Comment by Stypox** [comment] 2020-09-11 12:29
> @Stypox why it keeps crashing without showing error activity?

I don't know, but it seems like the crash is so severe not even ACRA is able to catch it... and this is really strange. We would need an `adb logcat` to be sure though, maybe this is an issue with ACRA.

**Comment by opusforlife2** [comment] 2020-09-11 12:32
What if debug versions of Newpipe have logging functionality added? A user could install a debug APK, enable logging from the Debug menu, reproduce a crash, and send the log.

**Comment by wb9688** [comment] 2020-09-11 12:33
@avently: Our ACRA implementation doesn't handle multidex or big crash logs properly.

**Comment by avently** [comment] 2020-09-11 15:37
https://developer.android.com/studio/releases/platform-tools

Download file for your OS, open cmd/terminal, drag and drop adb onto cmd/terminal,  type after adb path : ` logcat`
So you'll see something like:
`pathdoadb\adb.exe logcat`
and press enter

**Comment by Domiuns** [comment] 2020-09-11 15:41
I have make this file
[logcat.txt](https://github.com/TeamNewPipe/NewPipe/files/5210081/logcat.txt)

**Comment by opusforlife2** [comment] 2020-09-11 16:04
@Domiuns Stypox gave you 3 apks. Which one did you try?

**Comment by avently** [comment] 2020-09-11 16:08
`java.lang.NoClassDefFoundError: android.view.accessibility.CaptioningManager`

The code from stacktrace says that Android can't find CaptioningManager which is available on API 19 and later (you have API 19 if your Android is 4.4.4, right?) https://developer.android.com/reference/android/view/accessibility/CaptioningManager


The code from that shown in stack trace:
```
E/ACRA    ( 4202): java.lang.NoClassDefFoundError: android.view.accessibility.CaptioningManager

E/ACRA    ( 4202): 	at org.schabi.newpipe.player.helper.PlayerHelper.getCaptionScale(PlayerHelper.java:330)

E/ACRA    ( 4202): 	at org.schabi.newpipe.player.VideoPlayer.initViews(VideoPlayer.java:204)

E/ACRA    ( 4202): 	at org.schabi.newpipe.player.VideoPlayerImpl.initViews(VideoPlayerImpl.java:279)

E/ACRA    ( 4202): 	at org.schabi.newpipe.player.VideoPlayer.setup(VideoPlayer.java:180)

E/ACRA    ( 4202): 	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:128)

E/ACRA    ( 4202): 	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:121)

E/ACRA    ( 4202): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2671)

E/ACRA    ( 4202): 	at android.app.ActivityThread.access$1600(ActivityThread.java:156)

E/ACRA    ( 4202): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)

E/ACRA    ( 4202): 	at android.os.Handler.dispatchMessage(Handler.java:99)

E/ACRA    ( 4202): 	at android.os.Looper.loop(Looper.java:153)

E/ACRA    ( 4202): 	at android.app.ActivityThread.main(ActivityThread.java:5297)

E/ACRA    ( 4202): 	at java.lang.reflect.Method.invokeNative(Native Method)

E/ACRA    ( 4202): 	at java.lang.reflect.Method.invoke(Method.java:511)

E/ACRA    ( 4202): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)

E/ACRA    ( 4202): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)

E/ACRA    ( 4202): 	at dalvik.system.NativeStart.main(Native Method)

```

This is the link for the cause of crash:
https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java#L330

This is when the code was changed:
https://github.com/TeamNewPipe/NewPipe/commit/06d54ef77ea33117237cd89aa5fc10fc4d2a0e23#diff-d9a56593590a61716be0fc107ac247f7


Looks like your code @TacoTheDank causes the crash but the problem is that the code is fine:) Either @Domiuns device is not KitKat (or Android API is less than 19 for some reason), either device's developers have removed the class for some reason in him's device.

**Comment by wb9688** [comment] 2020-09-11 16:10
@avently: He's running some weird Android 4.4 ROM on his device that came with an older Android version…

**Comment by avently** [comment] 2020-09-11 16:16
I'm 100% sure that this issue https://github.com/TeamNewPipe/NewPipe/issues/4179 is related to the same problem. 
So I recommend you, @Domiuns, to update your ROM to a normal version if possible or to buy another phone. It will save your time in trying to fix the errors that come from here and there.

**Comment by Domiuns** [comment] 2020-09-11 16:24
I have install ROM android 4.4.4 to my phone (buyed on 2014) i think at this point is time to change device or rom

**Comment by TacoTheDank** [comment] 2020-09-12 00:49
@avently Interesting... 🤔

**Comment by TacoTheDank** [comment] 2020-09-12 00:52
@Domiuns You could also use the legacy version for now: https://github.com/TeamNewPipe/NewPipe-legacy/releases

**Comment by opusforlife2** [comment] 2020-10-17 19:33
Oh. Forgot to close this.

**Closed by opusforlife2** 2020-10-17 19:33 UTC
Labels: bug
