### ISSUE TITLE
Newpipe app isn't opening.

### ISSUE THREAD

**Issue by mrpr3s** [TeamNewPipe/NewPipe#4055] opened 2020-08-02 13:50 UTC
i am facing issue with newpipe app. It crashes automatically when i click on it. Currently i am using github release of the app & version is 0.19.8.
This all happens suddenly. All is working good a momemt ago the app just suddenly start behaving like this. I tried clearing app cache force closing it. I haven't cleared the app data yet as all my subscription & playlists gone if i do.

Here are the crash logs: https://del.dog/phigurrulo

**Comment by opusforlife2** [comment] 2020-08-02 18:56
At the very least, make a backup of the app data. If you have root, use OAndBackupX, if not, then adb backup to a computer.

**Comment by TobiGr** [comment] 2020-08-02 19:33
What a beautiful stack trace :heart: Our bug reporter is crashing :facepalm: 
That was hopefully fixed by #3982

**Comment by mrpr3s** [comment] 2020-08-03 01:32
@opusforlife2 
seems like i am stucked. I have root access & i taken backup of its app data, but when i restore data it again started crashing.
I think there is No way to get my subsciptions & playlists data back 😢

**Comment by wb9688** [comment] 2020-08-03 05:20
@mrpr3s: Take the newpipe.db file from your back-up, clear NewPipe's data, make an export in Settings -> Content, replace the newpipe.db in the resulting .zip, then import that .zip and it should work (just your settings and NewPipe's knowledge of what you've downloaded will be gone).

**Comment by Stypox** [comment] 2020-08-04 13:14
I'm closing this until further information is available, and also because it is a duplicate of #3995. @mrpr3s thank you for taking the time to get the crash report; unfortunately it does not contain anything useful due to an issue with the bug reporter. Follow the steps provided by wb9688 to restore your data ;-)

**Closed** 2020-08-04 13:14 UTC
Labels: bug
