### ISSUE TITLE
Unable to open downloads

### ISSUE THREAD

**Issue by Praveen0899** [TeamNewPipe/NewPipe#1423] opened 2018-05-26 07:53 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

Unable to open downloads in 0.13.4

**Comment by Praveen0899** [comment] 2018-05-26 07:53
It's in 0.13.4

**Comment by theScrabi** [comment] 2018-05-26 12:38
You aren't able to open downloads in v0.13.4. Can you please describe it further. Do you get a stracktrace, if so please send it.

**Comment by Praveen0899** [comment] 2018-05-29 12:28
When I click the downloads it's not opening and showing the UI  failure. I sent the UI failure to the mail (    crashreport@newpipe.schabi.org    ).can you check the mail and see the problem

**Comment by rainecheck** [comment] 2018-05-30 10:07
I'm getting this too, though on 0.13.3. It might be something to do with bad data in the downloads folder, as the problem went away after I cleared out files and data, but returned after I downloaded some other files (one of which also failed to download).
Stacktrace:
```
{
"user_action": "ui error",
"request": "App crash, UI failure",
"content_language": "GB",
"service": "none",
"package": "org.schabi.newpipe",
"version": "0.13.3",
"os": "Linux Android 8.1.0 - 27",
"time": "2018-05-30 10:04",
"exceptions": [
"java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference\n\tat us.shandian.giga.get.DownloadMission.addListener(DownloadMission.java:234)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:115)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:40)\n\tat android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)\n\tat android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)\n\tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)\n\tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)\n\tat android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)\n\tat android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)\n\tat android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)\n\tat android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)\n\tat android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)\n\tat android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)\n\tat android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)\n\tat android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat com.android.internal.policy.DecorView.onLayout(DecorView.java:761)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:723)\n\tat android.view.Choreographer.doFrame(Choreographer.java:658)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)\n\tat android.os.Handler.handleCallback(Handler.java:790)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6494)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)\n"
],
"user_comment": ""
}
```

**Comment by colaas** [comment] 2018-05-31 02:07
I can't access the downloads window either. This was on 0.13.3 and still can't on 0.13.4. Opening from the app or the notification makes it crash every time.
Trace:

{
"user_action": "ui error",
"request": "App crash, UI failure",
"content_language": "GB",
"service": "none",
"package": "org.schabi.newpipe",
"version": "0.13.4",
"os": "Linux Android 8.0.0 - 26",
"time": "2018-05-31 01:58",
"exceptions": [
"java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference\n\tat us.shandian.giga.get.DownloadMission.addListener(DownloadMission.java:235)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:119)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:44)\n\tat android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)\n\tat android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)\n\tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)\n\tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)\n\tat android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)\n\tat android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)\n\tat android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)\n\tat android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)\n\tat android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)\n\tat android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)\n\tat android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)\n\tat android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)\n\tat android.view.View.layout(View.java:19612)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6055)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19612)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6055)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:19612)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6055)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19612)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6055)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:19612)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6055)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19612)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6055)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:19612)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6055)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19612)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6055)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat com.android.internal.policy.DecorView.onLayout(DecorView.java:761)\n\tat android.view.View.layout(View.java:19612)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6055)\n\tat android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2509)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2225)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1411)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6785)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:968)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:780)\n\tat android.view.Choreographer.doFrame(Choreographer.java:715)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)\n\tat android.os.Handler.handleCallback(Handler.java:789)\n\tat android.os.Handler.dispatchMessage(Handler.java:98)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6665)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)\n"
],
"user_comment": "I can't open the downloads menu, it crashes every time."
}

**Comment by theScrabi** [comment] 2018-05-31 08:35
I see. I thought that this was fixed before. A fix for this should be provided soon.

**Comment by acrosca** [comment] 2018-05-31 16:45
The crash log is clear, a NPE check would fix the crash.
All my attempts to replicate the issue have failed. 

To understand what is really occurring and not just prevent the crash, it might help if the people that experience the issue go the download folder and retrieve the .giga files

**Comment by DafabHoid** [comment] 2018-06-01 12:36
This is exactly the crash which #1407 fixes. And it indeed does, but as I noticed now: **Only in debug builds**.
It seems that for release builds, Proguard removes the method `DownloadMission.readObject`, because it is never called in the code (it's called by the Virtual Machine, but Proguard does not know). I'm preparing a fix.

**Comment by theScrabi** [comment] 2018-06-01 14:11
Nice thx

**Comment by max421** [comment] 2018-06-01 18:08
I can confirm the problem, too. Everytime i want to download something the app crash after a few second and make a restart. 
I test it on the internal memory and on the sd sd card. I'm using version 0.13.4.

**Comment by theScrabi** [comment] 2018-06-01 19:51
Lets see if @DafabHoid fix works. I want to release this weekend :)

**Comment by max421** [comment] 2018-06-01 20:31
thx

**Comment by max421** [comment] 2018-06-04 19:19
I still have the mentioned bug (can't download videos; app crashes completly). I get UI error.
I'm on the version 0.13.5

I take a quick look in the details and in on some lines the app says: 

java.io.IOException: Permission denied at us.shandian.giga.get.DownloadManagerImp....
caused by: java.io.IOException: Permission denied at java.io.UnixFileSystem.createFile....

I checked my AppOps Permissions and XPrivacy settings for the App and i don't block any file system access.

**Comment by theScrabi** [comment] 2018-06-04 20:45
thats something differet. you try to access external storrage. thats not possible

**Closed by theScrabi** 2018-06-04 20:45 UTC
Labels: ASAP, bug
