### ISSUE TITLE
Polishing UI to Material 3 OR Flutter.

### ISSUE THREAD

**Issue by 1YuvrajS** [TeamNewPipe/NewPipe#10910] opened 2024-03-27 17:25 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

1. Current UI is still good but Red Nav bar doesn't look quite good.
2. When I using Newpipe app Google TV, but Red bar are bright but isn't good for my eye when looking at it.
3. Updating tp new UI to Material 3 that give more adaptive Colour.
4. Update logo of an app.
5. In Playing Video, Subtitle is hard to navigate.

### Why do you want this feature?

Same as above.

**Comment by AudricV** [comment] 2024-03-27 18:28
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

You did not, duplicate of #7595. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

Also, Flutter has nothing to do with design, it's a technology to build apps.

**Closed by AudricV** 2024-03-27 18:28 UTC
Labels: feature request, needs triage
