### ISSUE TITLE
Every video says there is an error, but the video plays fine. Log says "Parsing Error: Could not get Like Count"

### ISSUE THREAD

**Issue by joshuabengal** [TeamNewPipe/NewPipe#10639] opened 2023-12-08 00:56 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

Play a video

### Expected behavior

Video plays

### Actual behavior

An error message appears "Sorry something went wrong" but the video plays just fine

### Affected Android/Custom ROM version

Stock Android 12

### Affected device model

TCL A30

### Additional information

Report says "Guru Meditation" and it says What happened: could not parse website" below that. However other than the error message showing, everything works fine. Looking at the error it says there was a parsing exception: Could not get Like count

**Comment by AudricV** [comment] 2023-12-08 07:12
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #10624. Please search (better, with different keywords?) for duplicates, especially pinned ones, and fill in the template properly the next time you want to open an issue. Thank you.

**Closed by AudricV** 2023-12-08 07:12 UTC
Labels: bug, needs triage
