### ISSUE TITLE
Release 0.21.11

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#7193] opened 2021-10-02 16:52 UTC
# Testing APK
[NewPipe_v0.21.11_RC1.zip](https://github.com/TeamNewPipe/NewPipe/files/7271845/NewPipe_v0.21.11_RC1.zip)
Corresponding PR #7192 

# Changelog

### New
3 - Add a play next button to the long press menu #6872 
11 -  Add YouTube shorts path prefix to intent filter #7181 

### Improved
17 - Swap seekbar position with player buttons in Queue screen #6824 
4 - Make all buttons in player have selectable item background borderless #7042 
13 - Expand minimized player buttons clickable area #7177 
15 - Search for updates immediately when enabling automatic update checks on GitHub builds #6980 

### Fixed
8 - Fixed Settings import #7169
9 - Various fixes related to MediasessionManager #7166 
10-  Disabled media tunneling on RealtekATV #7178 
16 -  Fixed seekbar not completed after video end #7176 

### Development
1 - Updated Android Gradle Plugin to version 7.0.2 #6974 ⚠️ Now requires Java 11 to build
2 - Allow passing in package name suffix through CLI #6420 
5 - Extracted repeated variable to a constant #7132
6 - Removed deprecated preferenceTheme style attribute #7156 
7 - Regenerated some drawables to their latest design #7152
12 - Updated Groupie library to 2.9.0 #7150
14 -  Fixed typos in READMEs #7184 

### New
- Added support for extracting comment replies continuation TeamNewPipe/NewPipeExtractor#703 

### Improved
- [SoundCloud] Updated client id TeamNewPipe/NewPipeExtractor@d8ec3ce3708cae511d5df65622aa9c4fde56b2a7

### Development
-  Bump jsoup from 1.14.2 to 1.14.3 TeamNewPipe/NewPipeExtractor#734

**Comment by tsiflimagas** [comment] 2021-10-02 17:12
There are two issues which were introduced after 0.2.10 was merged into dev (at least as far as I noticed), and were present only in dev by then (they're not present in 0.2.10 release).
1) Tapping on timestamps in comments, starts the video in paused popup player, though it should continue playing right away.
2) Partially watched videos never start from the point where they were left at, they always start from the beginning.

**Comment by CloverBadland** [comment] 2021-10-02 18:10
My English is in progress, so I'm not sure, but wouldn't it be better if in the long press menu the "Enqueue next" was "Enqueue as next"

To me "Enqueue next" would mean to queue the next video, which makes no sense.

![enqueue](https://user-images.githubusercontent.com/86160566/135727469-c69ef5fe-6505-416d-a25e-b62aac0f4117.png)

**Comment by mhmdanas** [comment] 2021-10-02 19:01
@CloverBadland "Enqueue next" is entirely valid and idiomatic English as far as I know. Here "next" is used as an adverb.

**Comment by litetex** [comment] 2021-10-03 20:05
Somehow the tag in ``NavigationHelper`` (used for logging) is the wrong one.
Opened a PR: #7196

**Comment by Redirion** [comment] 2021-10-05 15:45
>     2. Partially watched videos never start from the point where they were left at, they always start from the beginning.

could this be a regression from #7176?

**Comment by TobiGr** [comment] 2021-10-05 16:46
@Redirion yes, we should also check whether the duration and current position are different by less than 1 second before setting the current position to the duration

**Comment by tsiflimagas** [comment] 2021-10-05 17:10
Both of the mentioned regressions were introduced a bit earlier than 0.2.10 release, but I couldn't notice which was the commit which did any of the two, since I only noticed them after 0.2.10 branch was merged in dev. #7176 is newer than that. The regression may lies to the code there, but I think it's not related to this commit.

**Comment by Mhowser** [comment] 2021-10-08 07:56
I'm not sure how to view the comment replies on Youtube, or is that not implemented in the frontend yet?

**Comment by K3XRad** [comment] 2021-10-09 12:54
> @Mhowser indeed, that hasn't been implemented in the app yet. PRs welcome!

I'm sorry for offtop, just one question.

@FireMasterK Maybe you planned to add comment replies in the frontend (app)? Or someone else should do that? Just for the information. Thanks in advance for the answer!

**Comment by TobiGr** [comment] 2021-10-10 18:40
> > ```
> > 2. Partially watched videos never start from the point where they were left at, they always start from the beginning.
> > ```
> 
> could this be a regression from #7176?

I just checked this. This bug also exists in the current release. So this is not a blocker.

**Closed** 2021-10-11 14:36 UTC

**Comment by tsiflimagas** [comment] 2021-10-13 01:40
@TobiGr hmm weird, I can't reproduce it on v0.20.10. Anyway, I guess I'll open issues for each of the mentioned problems, so they can be tracked down.

**Comment by tsiflimagas** [comment] 2021-10-13 03:35
@Redirion I found the source of both the regressions I mentioned. It's the changes made by #6872
