### ISSUE TITLE
Can't Download anything or open Downloads it crashes the app instantly 

### ISSUE THREAD

**Issue by hysteriabox** [TeamNewPipe/NewPipe#6823] opened 2021-08-01 20:42 UTC
{"user_action":"ui error","request":"ACRA report","content_language":"en-US","content_country":"US","app_language":"en_US","service":"none","package":"org.schabi.newpipe","version":"0.21.7","os":"Linux samsung/beyond0qltesq/beyond0q:11/RP1A.200720.012/G970USQU5GUE2:user/release-keys 11 - 30","time":"2021-08-01 13:31","exceptions":["java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:4619)\n\tat android.app.ActivityThread.access$1700(ActivityThread.java:301)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2167)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:246)\n\tat android.app.ActivityThread.main(ActivityThread.java:8512)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference\n\tat us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)\n\tat us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)\n\tat us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:4607)\n\t... 8 more\n"],"user_comment":""}

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux samsung/beyond0qltesq/beyond0q:11/RP1A.200720.012/G970USQU5GUE2:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4619)
	at android.app.ActivityThread.access$1700(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4607)
	... 8 more

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-08-01 22:02
Duplicate of #6687. Also, please don't remove the template when opening an issue.

**Closed by mhmdanas** 2021-08-01 22:02 UTC
Labels: bug
