### ISSUE TITLE
Playback speed gesture

### ISSUE THREAD

**Issue by Donkey-Doug** [TeamNewPipe/NewPipe#3309] opened 2020-03-30 19:18 UTC
Use a gesture, similar to the gesture to change brightness and volume, to change the video playback speed. Perhaps allow customizable gestures (and preferably more than 2 if desired)

**Comment by Stypox** [comment] 2020-03-30 19:58
Duplicate of #1823

**Closed by Stypox** 2020-03-30 19:58 UTC
