### ISSUE TITLE
Subscription count sometimes doesn't load

### ISSUE THREAD

**Issue by foxjaw** [TeamNewPipe/NewPipe#10990] opened 2024-04-22 06:12 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1 and 0.27.0_RC2

### Steps to reproduce the bug

It's random. The subscribers count sometimes won't load at all. When it doesn't, I have to reopen the channel page again and again to resolve this issue.

### Screenshots/Screen recordings

<img alt="Screenshot" src="https://github.com/TeamNewPipe/NewPipe/assets/150133625/4eb778bd-5ca2-43c9-a4b6-f111f7904929" width=270 />

**Comment by AudricV** [comment] 2024-04-22 11:28
> - [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #10826. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-04-22 11:28 UTC
Labels: bug, needs triage
