### ISSUE TITLE
An adaptive icon for Android 13

### ISSUE THREAD

**Issue by SpicyPTV** [TeamNewPipe/NewPipe#9141] opened 2022-10-16 22:43 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

An icon that Android 13 can use it's Material You design language on so that the colours change to match the wallpaper

### Why do you want this feature?

It is a new feature on Android 13 that will soon be a standard for most apps, NewPipe should get this so it doesn't fall behind.

### Additional information

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by tsiflimagas** [comment] 2022-10-17 03:01
Duplicate of #9007 and solved in #8987.

**Closed** 2022-10-17 07:58 UTC
Labels: feature request, needs triage
