### ISSUE TITLE
Decryption of video URL

### ISSUE THREAD

**Issue by champion174** [TeamNewPipe/NewPipe#2987] opened 2020-01-24 05:55 UTC
This is the best Application I've ever seen.
It works well yesterday but now I can't able to play any of the videos in that. 
It's showing the error; could not decrypt the video URL signature.
Hope it'll be fixed soon

**Comment by gkeegan** [comment] 2020-01-24 06:01
Duplicate of #2981.

Download the new release from GitHub. See instructions here: https://github.com/TeamNewPipe/NewPipe/blob/dev/README.md#Updates.

**Comment by tianxuefeng** [comment] 2020-01-24 06:25
implementation 'com.github.TeamNewPipe:NewPipeExtractor:ff61e284'
Hi, use this!

**Closed** 2020-01-24 11:29 UTC

**Comment by champion174** [comment] 2020-01-24 14:04
thank you, got it
