### ISSUE TITLE
Newpipe hates random videos

### ISSUE THREAD

**Issue by derpendary** [TeamNewPipe/NewPipe#8851] opened 2022-08-21 13:43 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2`

### Steps to reproduce the bug

1. Go to search.
2. Search for any topic.
3. There should be a video with a very blurry thumbnail.
4. If selected, the video will play buffer every few seconds.

### Expected behavior

There wouldn't be any blurry thumbnails on videos that would constantly buffer.

### Actual behavior

One of the hundreds of videos presented will have a blurry thumbnail and would constantly buffer.

### Additional information

I apologize for the informal title, but it is honestly funny enough that I had to eschew with the formality and tell it exactly how it is. Also, yes, I checked to see if it was my Internet. The blurred video takes ~5-10 seconds to start playing, and all the surrounding videos take ~2-3 seconds, and don't buffer at all.

**Comment by SameenAhnaf** [comment] 2022-08-21 13:53
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/8839 and https://github.com/TeamNewPipe/NewPipeExtractor/issues/763

**Comment by derpendary** [comment] 2022-08-21 14:11
> Duplicate of #8839 and [TeamNewPipe/NewPipeExtractor#763](https://github.com/TeamNewPipe/NewPipeExtractor/issues/763)

I've already seen that bug and I feel that this one is different.

**Closed** 2022-08-22 06:27 UTC
Labels: bug, needs triage
