### ISSUE TITLE
Not Show Size And Not Download Youtube Video

### ISSUE THREAD

**Issue by ucmatestudio** [TeamNewPipe/NewPipe#2648] opened 2019-09-18 20:23 UTC
* Downloading not work on your app newpipe app, not show size.
* Not work.
![Screenshot_2019-09-19-01-53-09-989_com google android gm](https://user-images.githubusercontent.com/54525530/65183060-42a09500-da80-11e9-88f6-30c7a4e59d71.png)

**Comment by kapodamy** [comment] 2019-10-01 17:16
beacuse takes a while

**Comment by Stypox** [comment] 2019-10-03 05:21
@ucmatestudio this is probably a duplicate of #2647 and others

**Closed by Stypox** 2019-10-03 05:21 UTC
