### ISSUE TITLE
[bug] Deletes videos from playlist only from second time

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#2355] opened 2019-05-22 16:28 UTC
Press "delete" from context menu of playlist.
Exit the app.
Restart the app.
Go to the playlist and you'll see deleted video there which will be deleted only from the second time.

**Comment by teod0r** [comment] 2019-05-22 16:29
I mean bookmarked (saved) playlists

**Comment by teod0r** [comment] 2019-08-21 09:06
actualy it deletes a video from playlist only after I press hw BACK button hiding the application. if I long press hw BACK button for CLOSING the app after deleting a video, video stays undeleted.

**Comment by Stypox** [comment] 2019-09-29 13:39
Duplicate of #2088

**Closed by Stypox** 2019-09-29 13:39 UTC
