### ISSUE TITLE
Failed to play this stream

### ISSUE THREAD

**Issue by tro69** [TeamNewPipe/NewPipe#883] opened 2017-11-30 15:41 UTC
When I try to watch this [video](https://www.youtube.com/watch?v=4LfJnj66HVQ) I get this error message: "Failed to play this stream".
I also tried to play video with all video resolutions and to play in background (only audio) but I got same error message.
I'm running NewPipe 0.11.0 on Android 7.1.2

**Comment by theScrabi** [comment] 2017-11-30 15:44
Confirmed.

**Comment by voidpublic** [comment] 2017-12-01 18:40
can confirm as well.Seems to be happen randomly. Killing the app completely and restarting it seems to fix it temporarily

**Comment by tro69** [comment] 2017-12-02 15:12
I tried many times to kill the app completely and restart it but it doesn't work anyway.

**Comment by SudoLinux** [comment] 2017-12-04 06:53
@tro69 I think @voidpublic means that you need to kill via setting menu and not the app switcher... :)

**Comment by v0idst4r** [comment] 2017-12-05 16:52
@SudoLinux I think he knew what he meant. This video still doesn't play when force closing (for me).

**Comment by v0idst4r** [comment] 2017-12-05 16:53
I know other videos this happens to. I remember them working on old versions of newpipe though.

**Comment by v0idst4r** [comment] 2017-12-05 16:53
Could it be DRM related?

**Comment by voidpublic** [comment] 2017-12-05 16:55
Yeah can confirm, been seeing it now as well. 

This video for example: https://www.youtube.com/watch?v=lvs68OKOquM

It does work when killing them app, sometimes for a long time (have been going for 3 weeks without that issue). Recently (like last 2 days) I've had it happen multiple times a day. Exact same video. Happens to background/fullplay and popout. 


If you can let me know how to enable debugging i'm happy to provide logs.

**Comment by sensiblepuffin** [comment] 2018-01-05 19:11
This happened to me last night, so I tried logging with VLC to try and figure out what was going on. (Settings -> Advanced -> Debug logs)

Log: https://pastebin.com/t6N6T4DP

It looks like it's getting a 403 Forbidden in response to its GET. However, I was using a VPN when the error occurred, so this might have been the endpoint getting blocked for making requests too often. By the time I realized this, however, I stopped getting the error.

Can someone else try to replicate what I see while not using a VPN?

**Closed** 2018-01-24 23:41 UTC
Labels: bug

**Comment by TippyLion28** [comment] 2019-05-11 12:21
I think this has something to do with DRM. It's happening to me mainly with music videos.

https://youtu.be/YSWKtuaV2fY
