### ISSUE TITLE
[Feature request] Add import subscription from youtube

### ISSUE THREAD

**Issue by YouROK** [TeamNewPipe/NewPipe#823] opened 2017-11-08 19:42 UTC
Please make import subscriptions.
This can be done using a rss file from "https://www.youtube.com/subscription_manager", from the bottom of the page. 
I represent it as follows: I download a file from youtube and import the file into the program.
It will be easier than looking at the site and search into the program.

My rss with subscription in attach:
[subscription_manager.txt](https://github.com/TeamNewPipe/NewPipe/files/1455177/subscription_manager.txt)

**Comment by TobiGr** [comment] 2017-11-08 19:49
Work in progress: #774 
Duplicate of #698

**Closed** 2017-11-09 01:45 UTC
Labels: duplicate
