### ISSUE TITLE
Audio skips/interrupts shortly whenever the app transitions from background to foreground

### ISSUE THREAD

**Issue by FTC55** [TeamNewPipe/NewPipe#6375] opened 2021-05-26 18:04 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play any video
2. Lock the phone or send the app to background
3. Reopen the app

### Actual behaviour
Whenever the app is minimized, the audio is interrupted shortly and then resumes, whenever it's maximized, the player displays the buffering animation and the audio is interrupted again (for a slightly longer time) and then resumes.

### Expected behavior
The audio shouldn't be interrupted but instead it should continue playing smoothly.

### Device info

 - Android version/Custom ROM version: 11
 - Device model: Samsung Galaxy S20+

**Comment by mhmdanas** [comment] 2021-05-26 21:05
Duplicate of #5016.

**Closed by mhmdanas** 2021-05-26 21:05 UTC
Labels: bug
