### ISSUE TITLE
v0.17.0 is really slow to go back from a channel page

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2513] opened 2019-08-13 20:03 UTC
I grabbed the v0.17.0 apk while it was up. When you are viewing a channel and press back to view your subscriptions, the app seemingly hangs for a second. This bug is not present on v0.16.2.

Steps to reproduce: 

Goto subscriptions, select a channel, then press back. The app will hang a bit both ways, but most notably when going back to subscriptions.

**Comment by Stypox** [comment] 2019-08-13 21:13
Duplicate of #2507

**Comment by Gymcap** [comment] 2019-08-18 01:55
This bug is still present as of [#2531](https://github.com/TeamNewPipe/NewPipe/issues/2531). 

To clarify, I am referencing the fact that it takes about a second for the subscriptions activity to show when pressing back from a channel activity. This was near/instant in v0.16.2 and previous.

**Comment by Stypox** [comment] 2019-08-18 05:12
You are right. I'll take a look at this

**Comment by Stypox** [comment] 2019-08-18 06:22
I am not able to find the cause of this slowdown. I can't find any relationship between the latest changes in ChannelFragment and the slowdown... the problem probably has to do with other files used by ChannelFragment.
Anyway I noticed that the slowdown happens anytime "back" is pressed in a channel, independently from the previous fragment.

**Comment by Isayso** [comment] 2019-08-22 14:18
I tested the dev branch yesterday and started a bigger download (and cannot scroll resolution in portrait mode). After I opened the download page and pressed "back", download still running, the app froze. Could leave app with home button. After some minutes I got a Shutdown or wait message from Android. 
No such behavior with 16.x
Hope this helps.

**Comment by TobiGr** [comment] 2019-08-22 15:18
Could you please try to disable 'Position in lists' in the history and cache settings and tell us whether the problems still exist.

**Comment by Isayso** [comment] 2019-08-22 19:30
I switched "Position in lists off", no change, App stops when I try to go back from download fragment.

**Comment by opusforlife2** [comment] 2019-09-10 04:16
@Stypox Is this bug present in 0.17.1? I haven't faced it so far.

**Comment by Stypox** [comment] 2019-10-02 12:22
@opusforlife2 we should probably ask @Gymcap as I could only reproduce "roughly" (i.e. my phone is probably fast enough to prevent slowdowns)

**Comment by opusforlife2** [comment] 2020-02-22 16:18
@Stypox Close?

**Comment by Stypox** [comment] 2020-02-22 17:52
This still happens on really slow devices, I think @opusforlife2

**Comment by opusforlife2** [comment] 2020-10-10 17:27
@Gymcap @Isayso Is this still an issue in 0.20.0?

**Closed by opusforlife2** 2020-10-10 17:27 UTC
Labels: GUI, bug, device/software specific
