### ISSUE TITLE
Feature Request: Newest videos within <x> timespan from Subscriptions.

### ISSUE THREAD

**Issue by JYNxYoshii** [TeamNewPipe/NewPipe#3138] opened 2020-02-24 02:05 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

While I know this has been brought up before, I'm rather surprised that there is not a function which pulls videos, sorted chronologically, from your Subscriptions. Have it as another page (a la Trending, Subscriptions, Playlists, etc.) with a button on the top, maybe a dropdown or something to select a pull range (max of 1 week or 1 month, something like that). This would go through the channels of your selected platform, or all of them once enabled in Settings, and scrub them for the newest videos posted within your selected range. Maybe have a setting that will auto-pull every <x> amount of time, over wi-fi or all networks, etc. For each channel in Subscriptions, have them labeled or classed based on platform for greater control?

Just throwing out random ideas. Point is, if such a feature existed, this app would be a legitimate replacement for YouTube, since commenting is usually worthless and comments themselves can already be viewed.

**Comment by Stypox** [comment] 2020-02-25 09:17
Duplicate of #739 and #822
Fixed by #2309

**Closed by Stypox** 2020-02-25 09:17 UTC
