### ISSUE TITLE
Tor/proxy support

### ISSUE THREAD

**Issue by cs-nero** [TeamNewPipe/NewPipe#3077] opened 2020-02-11 07:40 UTC
Hey,
I would appreciate if NewPipe would add a support for proxys (Type, Host, Port).
I think it is a feature which many users would like, because NewPipe is important for privacy.

Please let me know what you think about that and sorry for my bad english.

**Comment by OffifialMITX** [comment] 2020-02-12 13:43
As it is right now, you can use Orbot's "VPN" mode to force NP to use Tor. Generally it does not cause issues.

**Comment by Stypox** [comment] 2020-02-12 14:05
Duplicate of #1129

**Closed by Stypox** 2020-02-12 14:05 UTC

**Comment by Ryu945** [comment] 2021-04-28 15:54
> 
> 
> As it is right now, you can use Orbot's "VPN" mode to force NP to use Tor. Generally it does not cause issues.
That has an issue though.   You generally use a regular VPN as the system wide VPN and then connect to Tor through that.   If you use Orbot, you have to turn off your system wide VPN.

**Comment by cs-nero** [comment] 2021-05-12 10:55
I am not using Orbot, I have a server for that and I wanna use that.

**Comment by Ryu945** [comment] 2021-05-14 19:01
> 
> 
> I am not using Orbot, I have a server for that and I wanna use that.

That is why I would like New Pipe to have built in Tor connection.  You can't always rely on having that server.
