### ISSUE TITLE
Bookmark option on links shared

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6389] opened 2021-05-28 17:16 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I would like for you to add the option to bookmark videos when shared to newpipe so that I can watch later rather than watch it then. It would help in making it easier for me to bookmark good videos as well. Now I have to share the link to newpipe, open newpipe and then click save rather than having a save for later or bookmark option. It would really help

#### Is your feature request related to a problem? Please describe it

I want to watch videos shared on social media later but due to the runaround I have to do it takes a lot of time.

#### How will you/everyone benefit from this feature?

This feature will help busy people to hsve option to watch later so that they can continue their activities and then watch it later

**Comment by mhmdanas** [comment] 2021-05-28 17:57
Duplicate of #5775.

**Closed by mhmdanas** 2021-05-28 17:57 UTC
Labels: enhancement
