### ISSUE TITLE
0.8.9 UI crashes when going to Downloads

### ISSUE THREAD

**Issue by tzenrick** [TeamNewPipe/NewPipe#447] opened 2017-02-06 11:48 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

App UI crashes when selecting downloads from the menu, or from the notification.  Same behavior with Lollipop and CyanogenMod KitKat.  Same behavior whether actively downloading, or not.
```
{
   "user_action": "ui error",
   "exceptions": [
      "java.lang.NullPointerException\n\tat us.shandian.giga.ui.adapter.MissionAdapter.<init>(MissionAdapter.java:59)\n\tat us.shandian.giga.ui.fragment.MissionsFragment.updateList(MissionsFragment.java:116)\n\tat us.shandian.giga.ui.fragment.MissionsFragment.access$200(MissionsFragment.java:30)\n\tat us.shandian.giga.ui.fragment.MissionsFragment$1.onServiceConnected(MissionsFragment.java:51)\n\tat android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1108)\n\tat android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1125)\n\tat android.os.Handler.handleCallback(Handler.java:733)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:136)\n\tat android.app.ActivityThread.main(ActivityThread.java:5146)\n\tat java.lang.reflect.Method.invokeNative(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:515)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)\n\tat de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)\n\tat dalvik.system.NativeStart.main(Native Method)\n"
   ],
   "os": "Linux Android 4.4.4 - 19",
   "time": "2017-02-06 11:39",
   "ip_range": "107.181.0.0",
   "request": "App crash, UI failure",
   "package": "org.schabi.newpipe",
   "service": "none",
   "content_language": "en",
   "user_comment": ".",
   "version": "0.8.9"
}
```

**Comment by OffifialMITX** [comment] 2017-02-09 18:14
Same thing on Stock 5.1.1 API 22.

**Comment by OffifialMITX** [comment] 2017-02-09 18:16
Also nothing can be downloaded, no matter how long I wait.

**Comment by turboteckel** [comment] 2017-02-09 18:28
Same on 4.3

{
    "user_action": "ui error",
    "exceptions": [
       "java.lang.NullPointerException\n\tat us.shandian.giga.ui.adapter.MissionAdapter.<init>(MissionAdapter.java:59)\n\tat us.shandian.giga.ui.fragment.MissionsFragment.updateList(MissionsFragment.java:116)\n\tat us.shandian.giga.ui.fragment.MissionsFragment.access$200(MissionsFragment.java:30)\n\tat us.shandian.giga.ui.fragment.MissionsFragment$1.onServiceConnected(MissionsFragment.java:51)\n\tat android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1111)\n\tat android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1128)\n\tat android.os.Handler.handleCallback(Handler.java:730)\n\tat android.os.Handler.dispatchMessage(Handler.java:92)\n\tat android.os.Looper.loop(Looper.java:176)\n\tat android.app.ActivityThread.main(ActivityThread.java:5419)\n\tat java.lang.reflect.Method.invokeNative(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:525)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)\n\tat dalvik.system.NativeStart.main(Native Method)\n"
    ],
    "os": "Linux Android 4.3 - 18",
    "time": "2017-02-09 18:24",
    "request": "App crash, UI failure",
    "package": "org.schabi.newpipe",
    "service": "none",
    "content_language": "en",
    "user_comment": "",
    "version": "0.8.9"
 }

**Comment by Spielmops** [comment] 2017-02-18 09:56
The same happens on my 3 different devices with Android 5.1. Downloads are possible and Ok but the call of the page "Downloads" crashes the app. It was definitly possible before version 0.8.9.

Spielmops

**Comment by StefanBrand** [comment] 2017-02-28 00:25
I think you received numerous logs about it via email... :D

**Comment by StefanBrand** [comment] 2017-02-28 11:10
Seems to be fixed in 0.8.10 :) Can others confirm?

**Comment by Spielmops** [comment] 2017-02-28 11:13
I can confirm that: fixed! Thanks a lot!

**Comment by TobiGr** [comment] 2017-02-28 12:17
Yes. It seems to be fixed. Thanks

**Comment by OffifialMITX** [comment] 2017-02-28 13:56
Yes, works fine, thanks.

**Comment by theScrabi** [comment] 2017-02-28 15:26
Lol I didn't even touch anything there xD

**Closed** 2017-02-28 15:27 UTC
