### ISSUE TITLE
Unable to parse one specific video

### ISSUE THREAD

**Issue by REmerald** [TeamNewPipe/NewPipe#10457] opened 2023-09-29 18:02 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

0. "Show restricted content" is on.
1. Go to the link in the logs.
2. "Could not parse website" on trying to watch or download.

### Expected behavior

I should be able to view and download the video.

### Actual behavior

Throws the error on attempting to load the video.

### Screenshots/Screen recordings

<img alt="IMG_20230929_203344" src="https://github.com/TeamNewPipe/NewPipe/assets/55359236/ed76968a-3ca1-418a-9763-d6796093de1e" width=392 />
<img alt="IMG_20230929_205533" src="https://github.com/TeamNewPipe/NewPipe/assets/55359236/7ff663bc-0408-4798-9dfa-1838aa20a6d3" width=286 />

## Exception
* __User Action:__ requested stream
* __Request:__ Loading stream info: https://www.youtube.com/watch?v=iH3FPrI_Cuw
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:119)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

### Affected Android/Custom ROM version

MIUI by xiaomi.eu 12.5.4.0 Android 10

### Affected device model

Redmi Note 7 Pro

### Additional information

Other age restricted videos load and download fine, even the ones with the blurred thumbnails.
E.g. reactions and reuploads of "vomit cake".
Only this video doesn't work.

Tried to change multiple settings, didn't work.
Clearing all data didn't help either.

NewPipe is able to display the comments while it tries to load the video, but that's it. You can scroll the comments indefinitely until the error screen removes them.
Subsequent attempts don't show the comments until the app is restarted.

SkyTube can't play/download the video either, but it doesn't throw any error, it's just stuck and doesn't do anything.
Youtube Revanced 18.23.35 plays the video fine.

**Comment by AudricV** [comment] 2023-09-29 18:15
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #10347. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2023-09-29 18:15 UTC
Labels: bug, needs triage
