### ISSUE TITLE
treating extractor Code as data?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#8926] opened 2022-09-03 05:59 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my question isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

* As the youtube always keep on changing something (i guess) 
* which makes the newpipe app's yt instance to break (i.e. not play), 
* and that requires extractor updates, and hence corresponding hotfix releases 
* which take anywhere from some hours to a few days.

So, considering all this, it will be nice if 
* the newpipe extractor logic - at least for youtube, could somehow be deployed in a "code as data" method; 
* meaning that the updated extractor logic could be loaded on the go by the newpipe app 
* and it can continue to work as intended.

**Comment by yashpalgoyal1304** [comment] 2022-09-09 02:21
the problem to be addressed is same, the suggested solution is slightly
different.

but yeah, i'll paste the difference over there when i'll have time.

u can close this one in the meantime :thumbsup:

Frivolous2 wrote:

> This appears to be a duplicate of #5915
> <https://github.com/TeamNewPipe/NewPipe/issues/5915>.
>

**Comment by Frivolous2** [comment] 2022-09-09 15:47
I'm afraid I can't close it as I'm just a regular user like yourself, and don't have the needed privileges. 😅 Could you close it instead?

**Comment by yashpalgoyal1304** [comment] 2022-09-09 17:18
aah, 'kayh. nice.

github doesnt provide any actions via email and i dont have access to a
github logged in device atm. so, i wont be able to close it for some days.

Frivolous2 wrote:

> ... as I'm just a regular user ...
>

**Comment by AudricV** [comment] 2022-09-09 18:04
Closing as a duplicate of #5915. Even if ideas proposed are not the same, they concern the same topic (and issue).

Make sure to avoid this type of duplicates in the future. Thank you.

**Closed by AudricV** 2022-09-09 18:04 UTC
Labels: question, needs triage
