### ISSUE TITLE
[YouTube] [Channel search results] Wrong stream count and subscriber count unknown

### ISSUE THREAD

**Issue by Monstanner** [TeamNewPipe/NewPipe#9442] opened 2022-11-20 13:35 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Open NewPipe.
2. Search for a channel.
3. Tap the search and search again. (Doesn't happen all the time and doesn't happen with every channel)

### Expected behavior

NewPipe should not display the alias numbers as subscribers and the actual subscribers as videos.

### Actual behavior

NewPipe messes up the channel info because of the new alias feature. It depends on how many subscribers the channel has and whether Has a number at the end of the alias. As an example, I have attached two screenshots of the channel Bippty. In the first screenshot everything is still correct. However, in the second, NewPipe takes the number from the alias as the subscriber count (his YouTube alias is (at)bippty1442) and the old subscriber number is now the new video number.

### Screenshots/Screen recordings

<img alt="alias1" src="https://user-images.githubusercontent.com/45621250/202902178-654e2743-7ef6-4caa-8837-b3a0b1bd7c11.png" height=600 />
<img alt="alias2" src="https://user-images.githubusercontent.com/45621250/202902187-faee4c17-db29-40d0-96f1-f20110a73b4a.png" height=600 />

## Exception
* __User Action:__ searched
* __Request:__ gronkh
* __Content Language:__ de
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux Nokia/Plate2_00WW/PL2_sprout:10/QKQ1.190828.002/00WW_4_16B:user/release-keys 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get subscriber count
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:84)
	at org.schabi.newpipe.extractor.channel.ChannelInfoItemsCollector.extract(ChannelInfoItemsCollector.java:40)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:84)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:48)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:104)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectStreamsFrom(YoutubeSearchExtractor.java:226)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:162)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:21)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:69)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:37)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:82)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$qyxpuXgomWa-cbONQns-pd7zxm0(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:8)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: Failed to find pattern "([\d]+([\.,][\d]+)?)" inside of "@gronkh"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:78)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
	at org.schabi.newpipe.extractor.utils.Utils.mixedNumberWordToLong(Utils.java:79)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:81)
	... 23 more

```
</p></details>
<hr>

### Affected Android/Custom ROM version

Android 10 Vanilla

### Affected device model

Nokia 6.1

### Additional information

I also noticed that if you search for the channel Linus Tech Tips, everything is normal, even after multiple searches. Here the alias is (at)LinusTechTips. At Gronkh's channel, on the other hand, there are problems with displaying the number of subscribers. There is no number of subscribers at all. Just a video number, which are the subscribers. In addition, there is an apology that something went wrong and NewPipe gives me a bug report, which I have inserted in the log section. On a second or even third search, everything is back to normal. His alias is (at)gronkh. If I then search again then everything is okay again. If it did not go out of the described or shown. I'm just looking for the names without an @ in front of it.

**Comment by AudricV** [comment] 2022-11-20 14:34
See TeamNewPipe/NewPipeExtractor#976.

**Comment by Monstanner** [comment] 2022-11-20 14:45
> See [TeamNewPipe/NewPipeExtractor#976](https://github.com/TeamNewPipe/NewPipeExtractor/issues/976).

Thanks for the link. Sorry for the duplicate. I will then close this issue.

**Comment by AudricV** [comment] 2022-11-22 16:30
Thanks for your attitude! We get rarely such reactions.

That's not a duplicate of an existing issue in the app repo, but in the extractor, so I am reopening this one, which is the first report of this YouTube change. It would give more visibility to the issue and *may* prevent duplicates.

**Closed** 2022-12-05 16:52 UTC
Labels: bug, youtube, requires extractor change
