### ISSUE TITLE
Playlist sort order

### ISSUE THREAD

**Issue by ggdorman** [TeamNewPipe/NewPipe#5237] opened 2020-12-20 17:47 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be nice to have a simple "sort order" setting at the top of a playlist. This could have options such as "Date added" and "Date uploaded" with ascending/descending order.

#### Is your feature request related to a problem? Please describe it

My issue is that I usually want to see the newly added videos first.

#### How will you/everyone benefit from this feature?

Well, it would help people wanting playlist sorting. I think it's a pretty useful feature and I know I'm not the only one wanting it. See related:  #3486 #5197

**Comment by denthebro** [comment] 2021-07-03 03:30
Please add this! It was a very convenient feature on the official youtube app

**Comment by litetex** [comment] 2022-02-15 18:53
Duplicate of #3263

**Closed by litetex** 2022-02-15 18:53 UTC
Labels: enhancement
