### ISSUE TITLE
RYD Integration

### ISSUE THREAD

**Issue by nin0-dev** [TeamNewPipe/NewPipe#8037] opened 2022-03-14 20:56 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

It would be cool to have the dislike count shown right after the like count. 

Dislike data would be fetched from Return YouTube Dislike.

### Why do you want this feature?

We can know which videos are blatant trolls or bad just by checking the dislike count, which isn't possible yet.

**Comment by TiA4f8R** [comment] 2022-03-14 20:59
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

You didn't: duplicate of #7469. Please avoid opening duplicates of exisiting issues next time. Thank you.

**Closed by TiA4f8R** 2022-03-14 20:59 UTC
Labels: enhancement
