### ISSUE TITLE
Add option of automatic Invidious redirection

### ISSUE THREAD

**Issue by danialbehzadi** [TeamNewPipe/NewPipe#3001] opened 2020-01-24 20:22 UTC
It's not a bug, but an enhancement recommendation.

As Newpipe already supports invidious, please add an option to automatically fetch youtube videos from selected Invidious instance. Not only this helps users to increase the privacy, but also helps people with censored Internet to access youtube videos cached in invidious servers.

Edit: This might be a fix/workaroud for annoying #2981 bug too!

**Comment by prp-e** [comment] 2020-01-24 20:28
I support this. A free worldwide network is a right for all people.

**Comment by erfanoabdi** [comment] 2020-01-25 03:53
+1

**Comment by Stypox** [comment] 2020-01-27 19:01
Duplicate of #2621

**Closed by Stypox** 2020-01-27 19:01 UTC
