### ISSUE TITLE
Download option for the video pop-up

### ISSUE THREAD

**Issue by Berndion** [TeamNewPipe/NewPipe#7875] opened 2022-02-14 22:06 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When you hold your finger on a video a pop-up opens, giving you various options (play, share, open in browser, channel details etc.)
Add to that another option for downloading either a video or audio of the video.

### Why do you want this feature?

At the moment you have to open every single video which you plan to download the video or audio from.
This obviously leads to a lot of clicking, waiting and back and forth.
The feature would simplify this process a lot.

### Additional information

I am sorry English not my native language, in case I have expressed myself unclearly.

**Comment by brnwlshubh** [comment] 2022-02-14 22:28
#7771

**Comment by Berndion** [comment] 2022-02-14 22:38
@brnwlshubh
Does that imply the same feature? Because when I hold on a video I get 9 and not 6 options.
The only 6 "buttons" I can see are in a video.
Namely add, background, pop-up, download, share, open in browser.

That's not what I meant.

**Comment by CyberaxAnnon** [comment] 2022-02-15 02:52
Agreed, I would like to add a video that I would like to watch without needing to go to the video to download.

**Comment by litetex** [comment] 2022-02-15 18:46
Duplicate of #2171 / #7771

**Closed by litetex** 2022-02-15 18:46 UTC
Labels: enhancement
