### ISSUE TITLE
Differnet launages in video

### ISSUE THREAD

**Issue by sho-blackz** [TeamNewPipe/NewPipe#8939] opened 2022-09-06 08:43 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

lastest 0.23.3

### Steps to reproduce the bug

new newpipe and arch for mr beast channel.
Open channel page and click on the video title 'I Survived A Plane Crash '
video play in a differnt audio than english.

if i open the same video on browser from newpipe 
it plays in english

### Screenshots/Screen recordings

https://photos.app.goo.gl/kq5ogQf5sH81dNbt9

**Comment by SameenAhnaf** [comment] 2022-09-06 14:36
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5854

**Closed** 2022-09-07 20:46 UTC
Labels: bug, needs triage
