### ISSUE TITLE
Newpipe not working

### ISSUE THREAD

**Issue by Tier5Laughsuk** [TeamNewPipe/NewPipe#8253] opened 2022-04-18 03:00 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Version 3.0

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=VvLxB1jvb7k
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 3.0
* __OS:__ Linux samsung/r8seea/r8s:12/SP1A.210812.016/G780FXXU8DVB2:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected device model

Galaxy s20

### Additional information

It was working until a couple of days ago..

**Comment by georgesuba** [comment] 2022-04-18 03:19
I have same problem with v0.22.1 and also with v0.22.2, channels are loaded it wont play anything. It was working about two weeks ago, then I noticed that loading videos was starting taking few seconds, and 3 or 4 days back loading times was like 20-30 seconds and then it stop completely. Since then I've updated to 0.22.2 but still same problem.

**Comment by MDP43140** [comment] 2022-04-18 03:50
> Crash log
> ```
> org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
> 	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
> 	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
> 	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
> 	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
> 	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
> 	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
> 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
> 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
> 	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
> 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
> 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
> 	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
> 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
> 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
> 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
> 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
> 	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
> 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
> 	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
> 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
> 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
> 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
> 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
> 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
> 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:920)
> ```
Looks like duplicate of #8202.

**Comment by RobertBalogh** [comment] 2022-04-18 06:27
I experienced the same issues. Nothing is can be played. 
Hope this can be sorted out somehow.

**Comment by RobertBalogh** [comment] 2022-04-18 06:30
Tried the Legacy version which plays the videos, can download but no menus or setting are available.

**Comment by llcool** [comment] 2022-04-18 08:06
Uninstalling then re-installing v0.22.2 worked for me. :)

**Comment by benzbee** [comment] 2022-04-18 08:11
Same issue  videos won't play 😫

**Comment by RobertBalogh** [comment] 2022-04-18 08:39
Tried the Legacy version which plays the videos, can download but no menus or setting are available.

**Comment by TiA4f8R** [comment] 2022-04-18 09:08
> Version 3.0

@Tier5Laughsuk Where did you download the app?

**Comment by benzbee** [comment] 2022-04-18 09:40
I download it on F-droid.

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by TiA4f8R** [comment] 2022-04-18 09:42
Then why your app version is `3.0`? The latest version is 0.22.2.

**Comment by apollo79** [comment] 2022-04-18 10:57
Same issue here. 

Log:

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=HjsMshhJ7zc
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

**Comment by georgesuba** [comment] 2022-04-18 11:37
@llcool 

> Uninstalling then re-installing v0.22.2 worked for me. :)

Hi, I can confirm that this solution worked for me too. Don't know why updating app did not worked but uninstall and then do fresh install of 0.22.2 worked for me as well

**Comment by benzbee** [comment] 2022-04-18 11:40
Ok thank you George Suba much appreciate it🤗

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by litetex** [comment] 2022-04-18 13:18
Guy, open your eyes and read the checklist:
> I made sure that there are no existing issues

![grafik](https://user-images.githubusercontent.com/40789489/163813750-2ad26f94-f592-4674-838b-7ceb4fdb2db6.png)

**Closed by litetex** 2022-04-18 13:18 UTC
Labels: bug

**Comment by RobertBalogh** [comment] 2022-04-18 13:54
Uninstalled, reinstalled via F-droid. 

Still not working.

![IMG_20220418_145258.jpg](https://user-images.githubusercontent.com/44980423/163818302-7adb5cd7-42bf-4a63-902f-6a0ccbb725ec.jpg)

![IMG_20220418_145241.jpg](https://user-images.githubusercontent.com/44980423/163818337-ed123ce9-43b9-4829-b11d-cc7622392ba9.jpg)

**Comment by RobertBalogh** [comment] 2022-04-18 14:00
Ok it was my fault. I downloaded the 0.22.1 instead of 0.22.2.

But F-droid still have the 0.22.1 which is not working. 
They should update their system.

**Comment by litetex** [comment] 2022-04-18 15:24
> But F-droid still have the 0.22.1 which is not working.

F-Droid usually takes some days to recognize the changes:

https://github.com/TeamNewPipe/NewPipe#installation-and-updates
> Update via F-Droid. This is the slowest method of getting updates, as F-Droid must recognize changes, build the APK itself, sign it, then push the update to users.

**Comment by benzbee** [comment] 2022-10-11 08:59
My app is version is this not 3.0

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by opusforlife2** [comment] 2022-10-12 17:57
@benzbee What?
