### ISSUE TITLE
Please 

### ISSUE THREAD

**Issue by KalpanaChetan** [TeamNewPipe/NewPipe#8908] opened 2022-08-29 15:16 UTC
### Checklist

- [ ] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [ ] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [ ] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [ ] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [ ] This issue contains only one feature request.
- [ ] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

English is not my language .There can be a lot of mistakes in typing
1.Scheduler like 1DM
https://play.google.com/store/apps/details?id=idm.internet.download.manager

2. Pin  a bookmark in bookmarked playlists
3. Playlist downloader
4. Indicates new pipe if a video file is already downloaded.  But  ask where to download option is on new pipe never indicates
5. To download a video,  new pipe create a folder automatically( channel  name )and download the video
6. Show both format MPEG-4 and WebM during download 

### Why do you want this feature?

I want to make the new pipe the most powerful

**Comment by SameenAhnaf** [comment] 2022-08-29 18:27
1. Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4183
2. https://github.com/TeamNewPipe/NewPipe/issues/7870 gets the job done.
3. Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5482

**Comment by opusforlife2** [comment] 2022-08-31 19:59
@KalpanaChetan [CLICK](https://simplytranslate.org/?engine=google&text=%23%23%23%20Checklist%0D%0A%0D%0A-%20%5B%20%5D%20I%20made%20sure%20that%20there%20are%20%2Ano%20existing%20issues%2A%20-%20%5Bopen%5D%28https%3A//github.com/TeamNewPipe/NewPipe/issues%29%20or%20%5Bclosed%5D%28https%3A//github.com/TeamNewPipe/NewPipe/issues%3Fq%3Dis%253Aissue%2Bis%253Aclosed%29%20-%20which%20I%20could%20contribute%20my%20information%20to.%0D%0A-%20%5B%20%5D%20I%20have%20read%20the%20%5BFAQ%5D%28https%3A//newpipe.net/FAQ/%29%20and%20my%20problem%20isn%27t%20listed.%0D%0A-%20%5B%20%5D%20I%27m%20aware%20that%20this%20is%20a%20request%20for%20NewPipe%20itself%20and%20that%20requests%20for%20adding%20a%20new%20service%20need%20to%20be%20made%20at%20%5BNewPipeExtractor%5D%28https%3A//github.com/TeamNewPipe/NewPipeExtractor/issues%29.%0D%0A-%20%5B%20%5D%20I%20have%20taken%20the%20time%20to%20fill%20in%20all%20the%20required%20details.%20I%20understand%20that%20the%20feature%20request%20will%20be%20dismissed%20otherwise.%0D%0A-%20%5B%20%5D%20This%20issue%20contains%20only%20one%20feature%20request.%0D%0A-%20%5B%20%5D%20I%20have%20read%20and%20understood%20the%20%5Bcontribution%20guidelines%5D%28https%3A//github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md%29.%0D%0A%0D%0A%23%23%23%20Feature%20description%0D%0A%0D%0A%23%23%23%20Why%20do%20you%20want%20this%20feature%3F%0D%0A%0D%0A%23%23%23%20Additional%20information&sl=en&tl=hi)

**Closed by opusforlife2** 2022-08-31 19:59 UTC
Labels: enhancement, needs triage
