### ISSUE TITLE
Screen rotation glitch

### ISSUE THREAD

**Issue by 83317** [TeamNewPipe/NewPipe#7683] opened 2022-01-22 17:26 UTC
![Screenshot_20220117-154716](https://user-images.githubusercontent.com/93091272/149835345-cb6a6116-7dfa-4891-b064-b05cab3d70a7.png)
![Screenshot_20220117-154737](https://user-images.githubusercontent.com/93091272/149835351-c47af1a9-9f82-44a8-b321-85920e47d91a.png)

The scale of the video is inconsistent, sometimes I get a black box when I try to go full screen.

Using pixel 4a on GrapheneOS stable channel. This wasn't an issue before graphene updated the GUI on the 4a.

**Comment by SameenAhnaf** [comment] 2022-01-24 01:29
@litetex Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7262

**Comment by litetex** [comment] 2022-01-24 19:24
→ https://github.com/TeamNewPipe/NewPipe/issues/7683#issuecomment-1019632009

**Closed by litetex** 2022-01-24 19:24 UTC
Labels: bug, template-missing
