### ISSUE TITLE
Order Subscription videos by date not one per Channel

### ISSUE THREAD

**Issue by JustMeErazem** [TeamNewPipe/NewPipe#1190] opened 2018-03-15 22:18 UTC
Can you order videos by release date, so that there can be more videos by the same channel if they were released one after another (like in normal Youtube or SkyTube). Now there is only one video per channel and some channels haven't posted in months, so it's confusing.

**Comment by theScrabi** [comment] 2018-03-15 23:19
This got requested multible times. We might have to add a something to the database that remebers which vidos of a channel you've already seen.

**Comment by JustMeErazem** [comment] 2018-03-17 19:28
Maybe you can see how [SkyTube](https://github.com/ram-on/SkyTube/) does it.

**Comment by andrewferguson** [comment] 2018-03-19 19:43
I don't particularly see why it is necessary to remember which videos in the subscription feed have already been watched - at least at this stage. (Although is this information not already stored in the database because it will be in the watch history?)

A good fix in the interim I think would be to show the first 15 or 20 most recent videos from subscribed channels, with the option to view more older videos if desired.

(I don't know how you feel about this, however several channels I subscribe to update very infrequently when compared to others, so I find the subscription feed in it's current state quite confusing).

**Comment by JustMeErazem** [comment] 2018-03-19 19:48
@andrewferguson I didn't mention remembering already watched videos, as I also find that not as useful. But your 2nd argument is what I proposed. Latest 20-30 videos released by subscribed channels in order of release. I think the dev understood what I meant.

**Comment by mauriciocolli** [comment] 2018-03-19 21:37
Duplicate of #822.

**Closed by mauriciocolli** 2018-03-19 21:37 UTC
Labels: duplicate
