### ISSUE TITLE
[Feature Request] Scheduled Backup + Import Monitoring

### ISSUE THREAD

**Issue by grravity** [TeamNewPipe/NewPipe#3798] opened 2020-06-20 05:40 UTC
It would be very nice to offer a scheduled export of Newpipe data, this would allow the ability to Rsync to another device and sync all your data. The second part going alongside my suggestion to have the ability to have Newpipe monitor a folder for data changes to read new data from the sync.

**Comment by B0pol** [comment] 2020-06-21 15:03
Duplicate of #3558 for the first part. Open a new issue **and follow the template** for the second part if you want it

**Closed by B0pol** 2020-06-21 15:03 UTC
