### ISSUE TITLE
Release v0.25.0 (please TEST!)

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#9712] opened 2023-01-22 08:07 UTC
## Testing for regressions
Debug APK (built by @Stypox): [NewPipe_v0.25.0_RC2_debug.zip](https://github.com/TeamNewPipe/NewPipe/files/10529530/NewPipe_v0.25.0_RC2_debug.zip)
Release APK (built and signed by @Stypox): [NewPipe_v0.25.0_RC2_release.zip](https://github.com/TeamNewPipe/NewPipe/files/10529519/NewPipe_v0.25.0_RC2_release.zip)
Please report **only regressions** (i.e. new issues) here, not issues that were already present in previous releases!

## TODO

- [x] https://github.com/orgs/TeamNewPipe/projects/12
- [ ] Merge weblate
- [x] https://github.com/TeamNewPipe/NewPipe/pull/9553#issuecomment-1398217296, see #9742

## NewPipeExtractor version

This version of NewPipe will ship with [NewPipeExtractor version v0.22.5](https://github.com/TeamNewPipe/NewPipeExtractor/releases/tag/v0.22.5) (still WIP)

<details><summary><h2>App changelog </h2></summary><p>

### New
- Show toast when no updates are available #8668
- Show subscriber count on video details page #9173
- Download items from the queue #9502
- Allow permanently setting a playlist thumbnail #9523
- Add long press action on hashtags and web links in descriptions #7725
- Full width thumbnails aka card view mode #9310

### Improved
- Remove the redundant/overlapping toast "Copied to clipboard" for Android 13+ #8961
- Make mini-player close button area larger #8743
- Use smoother bitmap downscaling for thumbnails #8686 #9479
- Rename "Help" to "Fast mode" #9500
- Add hint to improve discoverability of subscription import #9501
- Disable night theme selection if auto theme is not used #9488
- Set `compileSdk` and `targetSdk` to 33 (Android 13) #9306 #9671 #9696
- Seeking no longer pauses the played stream #9496
- Added icon for "Play All" #9568
- Add language suffix to downloaded subtitle filenames #9499
- Check availability of Samsung DeX only on Samsung devices #9619
- Add "What's New" to the default main page tabs #9664
- Change "What's New" icon #9678
- Made channel images in grid lists bigger #9555
- Change "Chapters" icon #9691

### Fixed
- Fix persistent hover overlay when in desktop/DeX mode or using a mouse/non-touch input #8316
- Only show "Enqueue next" when in the middle of the queue #8883
-  [PeerTube] Remove dead Privacy Tools instance #9504
- Crash fix when click "Add to playlist" while the current list is still loading #9521
- Allow using background player when there are no separate audio streams #9562
- Improve screen rotation handling in Open action menu #9135
- Ask for permission when enqueuing in a popup #9653
- Fix removing watched videos from playlist includes currently playing #9445
- Fix displaying multiple empty playlists #9642
- Fix background player stops working when enqueueing playlist at different index #9706 
- Fix link clicking and ellipsizing of comments #9631 

### Localization
- Update translations 1d53389ca9a2cdf3eff152d7118bc8152e25aaac, #9522, #9596, #9688
-  Added Odia language to language selector #9651

### Development
- Make `PendingIntent`s immutable on Android 6.0 and later #9333
- Use `Locale.forLanguageTag()` #8870
- Forbid wrong `@Nullable` and `@NotNull` annotation imports #9474
- Set image-minimizer to specify image width #9471
- Update Sonarqube to 3.5 #9480
- Use `Math.floorDiv()` #8810
- Use `SparseArrayCompat` #8895
- Update LeakCanary to 2.9.1 #9306
- Update Desugaring to 1.1.8, ACRA to 5.9.7 and Android Gradle Plugin to 7.3.1 #9481
- Refactor `VideoDetailFragment` #8847
- Refactor `VideoPlayerUi` #9159
- Update RxJava to 3.1.5 and RxAndroid to 3.0.2 #9520
- Use `ListAdapter` in `NotificationModeConfigAdapter` #8841
- Use new NPE UTF8 Utils methods #8769
- Update ExoPlayer to 2.18.2 #9553
- Clean up `Optional`-related code #9285 #9663
- Remove Runnable variables for Handlers #8886
- Use `WindowCompat` #8894
  - If you encounter any issue with system UI not behaving properly, this PR will be reverted
- Update `desugar_jdk_libs` to 2.0.0 and Android Gradle Plugin to 7.4.0 (which requires Android Studio Electric Eel) #9686 

</details>

**Comment by tsiflimagas** [comment] 2023-01-22 09:32
Confirmation from others might be needed, but when I resize the popup player, its size jumps around for a moment, something like flashing, and after that it ends up away from one of the fingers, making swiping-adjusting uncomfortable.

**Comment by peat80** [comment] 2023-01-22 12:16
Not really an problem, more an cosmetical issue:

Since the introduction of the new card view and raising the item size on tv (previously 5, now 3 items per row) the resolution of the thumbnails is way too low. They look blurry and show artifacts. People may be complaining about that. 🙄🤭

So wouldit be possible to get

https://github.com/TeamNewPipe/NewPipeExtractor/pull/889

Completed and merged before releasing 0.25?
Not necessary ofc, but the new release would look more polished with better tumbs. 😎

Anyways, great job so far. 😁👍

**Comment by moriel5** [comment] 2023-01-23 17:21
@peat80 I something similar on my Razer Phone 2.

While the items per row under the subscription tab remained the same (4), they are now much larger and very blurry.

Personally, I would have preferred for them to remain the same size, but to reduce the amount of space between them by fitting 5 items (I have the space for that, since I set everything to be at the smallest size in the system settings).

**Comment by theScrabi** [comment] 2023-01-24 08:23
Some search strings leed to a subscriber count parsing exception:

## Exception
* __User Action:__ searched
* __Request:__ whattefück
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ YouTube
* __Version:__ 0.25.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Exceptions (2)</b></summary><p>
<details><summary><b>Crash log 1</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get subscriber count
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:84)
	at org.schabi.newpipe.extractor.channel.ChannelInfoItemsCollector.extract(ChannelInfoItemsCollector.java:40)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:84)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:48)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:104)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectStreamsFrom(YoutubeSearchExtractor.java:226)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:162)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:21)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:69)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:37)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:82)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$qyxpuXgomWa-cbONQns-pd7zxm0(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: Failed to find pattern "([\d]+([\.,][\d]+)?)" inside of "@GamingFrag"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:75)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:60)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:49)
	at org.schabi.newpipe.extractor.utils.Utils.mixedNumberWordToLong(Utils.java:98)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:81)
	... 23 more

```
</details>
<details><summary><b>Crash log 2</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get subscriber count
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:84)
	at org.schabi.newpipe.extractor.channel.ChannelInfoItemsCollector.extract(ChannelInfoItemsCollector.java:40)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:84)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:48)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:104)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectStreamsFrom(YoutubeSearchExtractor.java:226)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:162)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:21)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:69)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:37)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:82)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$qyxpuXgomWa-cbONQns-pd7zxm0(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: Failed to find pattern "([\d]+([\.,][\d]+)?)" inside of "@kucibieber"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:75)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:60)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:49)
	at org.schabi.newpipe.extractor.utils.Utils.mixedNumberWordToLong(Utils.java:98)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:81)
	... 23 more

```
</details>
</p></details>
<hr>

**Comment by Jean-BaptisteC** [comment] 2023-01-24 12:44
> Clicking on `Open In Browser` shows a toast _No app on your device can open this_

Check this https://github.com/TeamNewPipe/NewPipe/issues/9615

**Comment by Jean-BaptisteC** [comment] 2023-01-24 13:18
This bug is specific to Android 13 :)

**Comment by Monstanner** [comment] 2023-01-25 14:28
There is a known issue with the new [ExoPlayer version](https://github.com/google/ExoPlayer/issues/10808)  on certain Android versions/devices. This makes the video stutter at a certain resolution. I have tested the new version of NewPipe on my Device (Nokia 6.1 Android 10 Vanilla) and from a resolution of 720p60fps and higher, the problem is present. [Zapp](https://github.com/mediathekview/zapp/issues/350)  also has the problem and is waiting for an update of ExoPlayer which may fix the problem. [Xtra](https://github.com/crackededed/Xtra/issues/197)  has/had the problem too, but was able to solve it with a hadware decoder.

**Comment by yashpalgoyal1304** [comment] 2023-01-26 17:04
_self hiding as offtopic_

----
that is neat, saw this in gitlab first; didn;t know gh has such thing too.
https://github.com/orgs/TeamNewPipe/projects/12

**Comment by js290** [comment] 2023-01-27 15:19
Would [adding nightly builds](https://github.com/TeamNewPipe/NewPipe-nightly/issues/2) to the f-droid repo help recruit more testers?

**Comment by hamzaarbeed** [comment] 2023-01-29 05:51
This release doesn't have feeds from live tab. When opening channels. There is no live or shorts tabs.

**Comment by Stypox** [comment] 2023-01-29 10:18
I published Release Candidate 2, which includes these changes:
- Update NewPipeExtractor, which fixes multiple changes introduced by YouTube and other services that could generate stacktraces #9631 #9725
- Fix background player stops working when enqueueing playlist at different index #9706

**Comment by Stypox** [comment] 2023-01-29 10:22
> So would it be possible to get https://github.com/TeamNewPipe/NewPipeExtractor/pull/889 completed and merged before releasing 0.25?

@peat80 Definitely not, unfortunately. It will take a while ;-)

> Clicking twice is now required for showing video interface. First one for showing soft buttons, second one for video interface. This should not be the case as swiping from soft buttons' edge shows soft buttons.

@SameenAhnaf This is likely caused by #8894. @Isira-Seneviratne could you look into it?

**Comment by Isira-Seneviratne** [comment] 2023-01-29 10:24
> > So would it be possible to get https://github.com/TeamNewPipe/NewPipeExtractor/pull/889 completed and merged before releasing 0.25?
> 
> @peat80 Definitely not, unfortunately. It will take a while ;-)
> 
> > Clicking twice is now required for showing video interface. First one for showing soft buttons, second one for video interface. This should not be the case as swiping from soft buttons' edge shows soft buttons.
> 
> @SameenAhnaf This is likely caused by #8894. @Isira-Seneviratne could you look into it?
> 
> 

Sure, I'll take a look when I get home.

**Comment by Isira-Seneviratne** [comment] 2023-01-29 12:18
@SameenAhnaf On which Android version(s) did you get this issue?

**Comment by JozKov** [comment] 2023-02-03 10:53
Hi, NewPipe v0.22. - v0.25 are not work on Xiaomi Mi TV Stick 4K. Fullscreen stops the video and than is not possible plays another video.

**Comment by Isira-Seneviratne** [comment] 2023-02-03 14:06
@SameenAhnaf I checked on a device running Android 11, and the system bars displayed fine when tapping the video player once.

**Comment by Stypox** [comment] 2023-02-07 20:05
I tried once again to reproduce the two issues that SameenAhnaf is having on MIUI, but since I have no such device myself, I couldn't reproduce. So for now I'm publishing this release, then we'll see if someone is able to fix those issues in the next release.

**Comment by peat80** [comment] 2023-02-07 23:44
NewPipe #9615
seems to affect android tv too (latest nightlys and release candidates of 0.25).
Version 0.24.1 opens installed browser (tv bro) fine.

**Closed** 2023-02-08 21:46 UTC

**Comment by Wazhai** [comment] 2023-02-09 08:57
0.25 isn't on your F-Droid repo yet
https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

**Comment by TobiGr** [comment] 2023-02-09 11:46
Sorry for the delay. The update is available trough our F-Droid repo now.
