### ISSUE TITLE
Can't download/play all songs/ error 403 v0.16.1

### ISSUE THREAD

**Issue by ime90** [TeamNewPipe/NewPipe#2384] opened 2019-06-05 18:32 UTC
As the title says, certain songs can't be played or downloaded. I would say that the ratio is 50% songs are playable/DLable while 50% aren't.

Examples:
Works:
https://www.youtube.com/watch?v=Ohuf1yRror0
https://www.youtube.com/watch?v=4o3s51RJgoA

Does not work:
https://www.youtube.com/watch?v=PmvT7B3u7II
https://www.youtube.com/watch?v=KRhyb2RRRb8
https://www.youtube.com/watch?v=rfijEEhLzJQ

Error message:
HTTP 403

How the error "looks". When I press background, the player in the top is set to 00:00/00:00 and doesn't start. When I press download, it just says error.

Version:
V0.16.1

Phone:
Huawei mate20 pro

Android version:
9
Emui version: 9.0.0

**Comment by gkeegan** [comment] 2019-06-05 18:51
Could you please try to turn off battery optimization for NewPipe? Especially since Emui is tricky with that.

Anyways, these videos play fine for me.

**Comment by ime90** [comment] 2019-06-05 18:58
I did, and after a quick phone restart it works.

Thank you very much :)

**Comment by ime90** [comment] 2019-06-06 14:46
So after a force restart + clear cache it seems to work.

After that I can watch videos in background but only till they reach like 2.5MGB of cache memory. Then I have to do the same. Pretty weird.

Dunno if it qualifies as a bug or not.

**Comment by gkeegan** [comment] 2019-06-06 17:22
2.5MB or GB? 

Also, I would say this classifies as a bug, the cache for those videos should be getting cleared once they finish playing.

**Comment by ime90** [comment] 2019-06-06 17:25
MB. It doesn't even come close to going over. But the force stop + clear cache does enable playing previously unplayable videos

**Comment by gkeegan** [comment] 2019-06-06 18:05
Could you try to update to 0.16.2 and see if the issue is fixed?

**Comment by InconsolableCellist** [comment] 2019-06-06 19:31
I have this problem too. 403 when I try to download, and when I try to watch a video it just spins. 0.16.2, just updated

**Comment by gkeegan** [comment] 2019-06-06 21:13
Are these videos recently uploaded?

**Comment by InconsolableCellist** [comment] 2019-06-06 21:17
Here are the videos:

https://www.youtube.com/watch?v=oF68P5N1RJM (2009)

https://www.youtube.com/watch?v=orwgEEaJln0 (2014)

Curiously both videos now play, a few hours after I noticed the error, but the top video still throws a 403 when trying to download (audio only, 128 kbps, 3 threads), but the bottom one does download.

**Comment by InconsolableCellist** [comment] 2019-06-06 23:33
It's happening with this video now https://www.youtube.com/watch?v=pkox8x1LxQ4 (2015), download works but not playing it, it just spins.

I've tried three networks (two different WiFi networks and one 4G)

**Comment by gkeegan** [comment] 2019-06-07 00:36
Try switching resolution when playing it.

**Comment by ime90** [comment] 2019-06-07 06:44
After the new update (16.02) everything seems to work fine.

Newpipe bestpipe!

**Comment by puppykickr** [comment] 2019-06-08 05:08
I am getting the 403 error on two different devices, 7.1.1 and 8.1.0

When I attempt to download, it always goes into queue, and then when I start I get the error.

I thought that I had solved the queue issue by reverting back to the default location, even though I would much prefer the downloads to go into the Downloads folder instead of two  folders inside two different NewPipe folders.

Going back to default helped for about a week, now it is doing it all over again.

NewPipe Legacy has the same problems.

**Comment by TobiGr** [comment] 2019-06-08 07:32
@puppykickr Legacy is still based on 0.16.1. On which NewPipe versions do you get the error? As said above, this should be fixed in 0.16.2.

**Comment by puppykickr** [comment] 2019-06-08 22:49
All available versions.
Also, I have multiple apps for this purpose, and all are doing the same thing.

Only Music Downloader (F-Droid) seems to be working at the moment.

I also find that the videos/music that will not download will often not play.

YouTube is returning error messages to the requests.

I even tried my old standby, FVD Tube, to no avail.

This is common across two devices, running 7.1.1 and 8.1.0

Only Music Downloader, with the lastest update, can download some selected music.

**Comment by gkeegan** [comment] 2019-06-09 00:00
What area are you in physically? Perhaps it is blocked videos causing the issue?

**Comment by puppykickr** [comment] 2019-06-10 22:08
I am in Indiana, USA.
I recently updated to 16.2, but I haven't had a chance to test anything
with it yet.

Grant Ryan Swan
(puppykicker)

**Comment by Rei1226** [comment] 2019-06-11 00:55
I have also been having similar issues. Around half the songs of my Playlists don't even play anymore, they just get stuck loading at the beginning.

**Comment by gkeegan** [comment] 2019-06-11 02:26
@tobigr this seems like it might be an issue with YouTube again (albeit on a much smaller scale than the usual changes).

**Comment by Metalmacher** [comment] 2019-06-11 10:24
Updating to 16.2 resolved the issue for me. Check the version inside the 'About' page, maybe you're using an older build.

**Comment by erindalc** [comment] 2019-06-13 06:44
I updated but had to clear cache and restart the download from the video to get some music to download.

**Comment by TobiGr** [comment] 2019-06-13 21:29
Is there anyone left who uses 0.16.2 and experiences this problem? I took a look at youtube-dl and the fix they implemented is included in the extractor through https://github.com/TeamNewPipe/NewPipeExtractor/pull/163 which is part of 0.16.2.

**Comment by gkeegan** [comment] 2019-06-14 01:45
@tobigr I still get the problem on 0.16.2.

**Comment by puppykickr** [comment] 2019-06-14 09:08
So far, it seems to work on my 8.1.0 and it even accepted the subscription
download as it came from YouTube.

But, the issues remain on my 7.1.1.

Grant Ryan Swan
(puppykicker)

**Comment by TobiGr** [comment] 2019-06-14 13:34
okay, that's bad.
I can't reproduce with VPN to USA. Does cleaning the cache resolves the problem?
The videos in the first post work for me. Can someone give me a link to a video which causes problems on 0.16.2 and not 0.16.1 please?

**Comment by puppykickr** [comment] 2019-06-15 05:24
I will attempt to try it on the 7.1.1 again soon.

**Comment by butchleitz** [comment] 2019-06-16 19:09
Updated to 16.2, downloading 5 files,  audio only,  all get 403 errors. Forced stop, cleared cache,  shut off battery optimization,  everything i read here to try, still does it.

**Comment by balibebas** [comment] 2019-06-19 10:52
Stopped seeing 403s on 0.16.2 after syncing F-Droid repo and updating from Aurora Droid [installed from APK](@cheatandroid). Did end up exporting and re-importing content settings for good measure. Tested on Mullvad HK server using WireGuard.

**Comment by balibebas** [comment] 2019-06-19 10:55
Stopped seeing 403s on 0.16.2 after syncing F-Droid repo and updating from Aurora Droid [installed from APK](https://t.me/cheatandroid). Did end up exporting and re-importing content settings for good measure, and reinstalling the app. Tested on Mullvad HK server using WireGuard.

**Comment by c272** [comment] 2019-06-20 06:45
On 8.1.0 running 0.16.2, currently all downloads are failing and throwing 403, so definitely not unique to older versions.

I'm in the UK, if it helps.

**Comment by puppykickr** [comment] 2019-06-21 19:50
Just tried new version, 16.2 on my 8.1.0

Downloaded one typical video, one 'official' music video, and the audio of
the same music video.

All were successful, and my personal download locations worked just fine:

Download/NewPipe/videos
Download/NewPipe/music

I have not yet attempted with my 7.1.1

Grant Ryan Swan
(puppykicker)

**Comment by puppykickr** [comment] 2019-06-24 06:41
I just tried it with the 7.1.1 and the download feature is now working
fine, and files are successfully going into my preferred locations.

There are some playback issues on some files, but testing shows that I can
download a file that won't play and then watch it.

What I found was that the player must be set for a format that the
video/audio is available on.

I had the player default set for 480p, but when I checked the download
screen only 360p and 720p were showing up.

A quick change of the default solved this issue.

Grant Ryan Swan
(puppykicker)

**Closed** 2019-09-29 13:59 UTC

**Comment by NicolasJons** [comment] 2024-08-13 11:26
It looks like you're running into issues with downloading or playing songs in v0.16.1. If you're open to trying an alternative, I recommend checking out the YMusic app. It allows you to stream and download music seamlessly, often with fewer errors. It's been a great solution for me, especially when other apps have trouble. Hope this helps!
