### ISSUE TITLE
Crash occurs when attempting to download a video

### ISSUE THREAD

**Issue by dmack6464** [TeamNewPipe/NewPipe#6899] opened 2021-08-11 05:57 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Download a video.

### Actual behavior

A crash occurs.

### Expected behavior

A video of my choosing should be downloaded.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ AU
* __Content Language:__ en-AU
* __App Language:__ en_AU
* __Service:__ none
* __Version:__ 0.21.8
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2018)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
	at android.app.Activity.startActivityForResult(Activity.java:4688)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:208)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:166)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at org.schabi.newpipe.download.DownloadDialog.launchDirectoryPicker(DownloadDialog.java:690)
	at org.schabi.newpipe.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:749)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1(DownloadDialog.java:359)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1$DownloadDialog(Unknown Source:0)
	at org.schabi.newpipe.download.-$$Lambda$DownloadDialog$QfMS-FoXWFjSoHiNV7JREecQBWg.onMenuItemClick(Unknown Source:2)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:7333)
	at android.widget.TextView.performClick(TextView.java:14160)
	at android.view.View.performClickInternal(View.java:7299)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27773)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6986)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by Speziax** [comment] 2021-08-11 11:26
I have had this exact same issue, immediately after downloading the latest update (0.21.8).  I believe it's related to another issue with the latest update, which is that when I attempt to view the "downloads queue," where download progress is shown, the app also crashes in a way that matches what is described above.  It flashes a bunch of times, then closes.  Not sure whether I should revert back for the time being.

**Comment by mhmdanas** [comment] 2021-08-11 13:00
Duplicate of #6729. You need to have an external file manager installed (see https://github.com/TeamNewPipe/NewPipe/issues/6729#issuecomment-886230249).

**Closed by mhmdanas** 2021-08-11 13:00 UTC
Labels: bug

**Comment by tsiflimagas** [comment] 2021-08-11 14:04
@Speziax have you removed your system file manager? If so, there's no file manager capable of also being a SAF provider.

**Comment by Speziax** [comment] 2021-08-11 14:21
> @Speziax have you removed your system file manager? If so, there's no file manager capable of also being a SAF provider.

Thank you for the reply,
I have not removed my system file manager, but I do use a third-party manager called "FX File Explorer."  It's interfaced perfectly fine with all previous versions of NewPipe I've used before, including the one I had earlier today.  Maybe there's a tweak that needs to be made regarding access on either of our sides?

NewPipe DOES have "storage" permission on my phone, and I even tried disabling and then re-enabling it after the initial incident.

**Comment by mhmdanas** [comment] 2021-08-11 14:55
> NewPipe DOES have "storage" permission on my phone, and I even tried disabling and then re-enabling it after the initial incident.

To be clear, when SAF is enabled, you do _not_ need to give NewPipe the storage permission.

In addition, there is another, unrelated bug with downloading videos: #6687. Maybe it's affecting you too?

In any case, please give the 0.21.9 release candidate a try and see if you still face the issue: #6841
