### ISSUE TITLE
data folder and synchronization

### ISSUE THREAD

**Issue by safkhet** [TeamNewPipe/NewPipe#1861] opened 2018-10-31 20:04 UTC
The most important missing feature for me to ditch YouTube is playlist, subscription and history synchronization, preferably using something simple, like syncthing.

Where does NewPipe keeps this data (which folder)? And is it possible to synchronize it?

Thanks for this great app

- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [x ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by theScrabi** [comment] 2018-11-05 15:13
It keeps is data to its own folder. Its not possible to sychronize atm.

**Comment by trymeouteh** [comment] 2019-03-02 20:00
First off. Great job on the new v0.16.0 release. What a great release with great new features such as comments, update notification and mediaCCC.

I know there are a few requests on data syncing NewPipe such as cloud storage syncing, syncing data folders but I thought of a few different approaches which can allow the user to sync their data in a safe, secure and private matter.

1. Built-In P2P Sync
Why not add a feature within the NewPipe app where a you can sync two or more devices together with a QR Code. How it can work is you have a your master device (Such as your phone) and you have your slave devices (Such as your tablets). Your scan the QR Code on your master device with your slave device. Then it will know it sync the data between the two devices. Every time you add/remove a subscription, add/remove a bookmark or create/delete a playlist it will sync the change to the other devices.

Settings can be added on weather data syncing is allowed on mobile data. When the data is transferred between the devices the data should be encrypted.


2. Automatic File Export & Automatic File Import
Every time the user adds or removes a subscription, add or removes a bookmark, adds or removes a playlist it will export a a backup file in a certain folder and it will have the name of NewPipe_Automatic_Backup. If NewPipe detects the NewPipe_Automatic_Backup file last modified date to be greater then the last time it had an automatic export NewPipe will automatically import the file. All that is needed not to make the syncing work is for the user to use Syncthing or some cloud storage feature to sync the data between the devices. But an option to be able to encryption this data should be added to allow security and privacy. 

3. Folders & Files
The NewPipe data will be saved in a folder on your device. It will contain a folder called history, search history, subscriptions, bookmarks, etc? In the history folder it will have a files named the video url and the file data will contain when the video was watched. In the subscription folder it will have files named after channel urls. All that is needed not to make the syncing work is for the user to use Syncthing or some cloud storage feature to sync the data between the devices. But an option to be able to encryption this data should be added to allow security and privacy.

**Comment by trymeouteh** [comment] 2019-04-03 20:35
I just found out a cool tool called DecSync. This allows you to sync data between apps by storing the data into a file and then the user can use Syncthing for example to sync the data between devices. It allows users to choose how their data is synced or backed up. I hope NewPipe checks this out and implements this!

**Comment by Stypox** [comment] 2019-08-28 20:44
Duplicate of #1163

**Closed by Stypox** 2019-08-28 20:44 UTC
