### ISSUE TITLE
casting function

### ISSUE THREAD

**Issue by monjanse** [TeamNewPipe/NewPipe#5185] opened 2020-12-15 18:55 UTC
i wish that newpipe could have chromecast function. 

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by c-shubh** [comment] 2020-12-16 14:09
Duplicate of #668

**Closed** 2020-12-17 05:23 UTC
Labels: enhancement
