### ISSUE TITLE
Only Youtube and Peertube work rest show that there was a network error

### ISSUE THREAD

**Issue by Manav2007** [TeamNewPipe/NewPipe#6391] opened 2021-05-29 03:49 UTC
Hey! Recently found a bug when I try to open SoundCloud, media.ccc.de, Bandcamp they open perfectly fine but it then shows a network error occurred even If I have full Internet access. How do I fix this?

Regards
Manav Harsana

**Comment by TiA4f8R** [comment] 2021-05-29 11:52
Please don't remove the template when opening an issue.

Can you share the formatted crash report when you press the `Report` button or just say if you got `No adress associated with hostname` in the top of the crash report? Thank you in advance.

**Comment by TippyLion28** [comment] 2021-08-03 16:51
Sorry to hijack this issue, but I believe it's the same one I'm having.

Soundcloud is completely broken for me. Can't search, can't go directly to a track. It's just borked. Here's what I get when searching:

```
{"user_action":"searched","request":"used","content_language":"en-GB","content_country":"GB","app_language":"en_GB","service":"SoundCloud","package":"org.schabi.newpipe","version":"0.21.7","os":"Linux Android 11 - 30","time":"2021-08-03 17:49","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response\n\tat org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSearchExtractor.onFetchPage(SoundcloudSearchExtractor.java:89)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)\n\tat org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:29)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:81)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$qyxpuXgomWa-cbONQns-pd7zxm0.call(Unknown Source:8)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:923)\nCaused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0\n\tat com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonParser.currentValue(Unknown Source:31)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:4)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)\n\tat org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSearchExtractor.onFetchPage(SoundcloudSearchExtractor.java:87)\n\t... 15 more\n"],"user_comment":""}
```

**Comment by TippyLion28** [comment] 2021-08-03 16:52
From the hot page:

`{"user_action":"requested kiosk","request":"Start loading: https://soundcloud.com/charts/new","content_language":"en-GB","content_country":"GB","app_language":"en_GB","service":"SoundCloud","package":"org.schabi.newpipe","version":"0.21.7","os":"Linux Android 11 - 30","time":"2021-08-03 17:52","exceptions":["java.io.IOException: Could not get streams from API, HTTP 401\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.getStreamsFromApi(SoundcloudParsingHelper.java:283)\n\tat org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudChartsExtractor.getInitialPage(SoundcloudChartsExtractor.java:81)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)\n\tat org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:72)\n\tat org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:58)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:184)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$NbG7JFGg0N9HK-3exJNRB9r_hYY.call(Unknown Source:4)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:923)\n"],"user_comment":""} `

**Comment by TippyLion28** [comment] 2021-08-03 16:54
Going directly to a track:
`{"user_action":"requested stream","request":"https://m.soundcloud.com/usedmusicbe/flume-rushing-back-feat-vera-blue-used-bootleg","content_language":"en-GB","content_country":"GB","app_language":"en_GB","service":"SoundCloud","package":"org.schabi.newpipe","version":"0.21.7","os":"Linux Android 11 - 30","time":"2021-08-03 17:53","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse JSON response\n\tat org.schabi.newpipe.extractor.services.soundcloud.linkHandler.SoundcloudStreamLinkHandlerFactory.getId(SoundcloudStreamLinkHandlerFactory.java:39)\n\tat org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:77)\n\tat org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:58)\n\tat org.schabi.newpipe.extractor.StreamingService.getStreamExtractor(StreamingService.java:262)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:923)\nCaused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse JSON response\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveIdWithWidgetApi(SoundcloudParsingHelper.java:181)\n\tat org.schabi.newpipe.extractor.services.soundcloud.linkHandler.SoundcloudStreamLinkHandlerFactory.getId(SoundcloudStreamLinkHandlerFactory.java:37)\n\t... 30 more\nCaused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0\n\tat com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonParser.currentValue(Unknown Source:31)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:4)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveIdWithWidgetApi(SoundcloudParsingHelper.java:178)\n\t... 31 more\n"],"user_comment":""} `

**Comment by TiA4f8R** [comment] 2021-08-04 11:17
@TippyLion28 @Manav2007 Does the issue still persists with the 0.21.8 version?

**Comment by TippyLion28** [comment] 2021-08-04 11:23
Works perfectly for me now. Thanks :)

**Comment by litetex** [comment] 2021-08-18 19:26
Closing this because the issue seems to be fixed

**Closed by litetex** 2021-08-18 19:26 UTC
Labels: bug, more info needed, user-ignored-template-instructions
