### ISSUE TITLE
Downloader crashing

### ISSUE THREAD

**Issue by rajarshikhatua100** [TeamNewPipe/NewPipe#8411] opened 2022-05-17 20:59 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. download 4-5 videos
2. go to download 
3. press pause

### Expected behavior

Pause downloads

### Actual behavior

App crushing

### Logs

FATAL EXCEPTION: main
Process: org.schabi.newpipe, PID: 9428
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Thread.isAlive()' on a null object reference
	at us.shandian.giga.get.DownloadMission.joinForThreads(DownloadMission.java:817)
	at us.shandian.giga.get.DownloadMission.pauseThreads(DownloadMission.java:521)
	at us.shandian.giga.get.DownloadMission.pause(DownloadMission.java:516)
	at us.shandian.giga.service.DownloadManager.pauseAllMissions(DownloadManager.java:400)
	at us.shandian.giga.ui.fragment.MissionsFragment.onOptionsItemSelected(MissionsFragment.java:201)
	at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3122)
	at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3226)
	at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:416)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:358)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:7792)
	at android.widget.TextView.performClick(TextView.java:16112)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung galaxy m31

**Comment by NewNewPipe** [comment] 2022-05-18 22:02
The problem with the downloader has been around for a long time. There are topics about it.

**Comment by litetex** [comment] 2022-05-22 13:19
Duplicate of #4008. You may give that issue a upvote ;)

**Closed by litetex** 2022-05-22 13:19 UTC
Labels: bug, downloader
