### ISSUE TITLE
opening links from browser UX improvement 

### ISSUE THREAD

**Issue by LargePrime** [TeamNewPipe/NewPipe#2352] opened 2019-05-21 20:05 UTC
If one opens newpipe from a browser link, the vid plays fine. 
But there is no way to goto the vids channel, or save the vid, or subscribe, from that interface. Back takes you back to what you were watching last time you used newpipe. 

- [ X ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ X ] I checked if the issue/feature exists in the latest version.
- [N/A] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment] 2019-05-21 20:23
This is a duplicate of #2186, I think

**Closed** 2019-09-29 13:38 UTC
