### ISSUE TITLE
Need Live videos section(and other sections like shorts, community posts) for channels 

### ISSUE THREAD

**Issue by VGumbakis** [TeamNewPipe/NewPipe#9834] opened 2023-02-18 17:38 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Users need live section, and shorts or even comumity section.

### Why do you want this feature?

Because i can only find live videos if i copy link from web and put in newpipes search bar.

**Comment by AudricV** [comment] 2023-02-18 17:44
> Need Live videos section(and other sections like shorts, community posts) for channels

You need to follow a template when opening an issue: duplicate of #2414. Please search (better, with different keywords?) for duplicates the next time you want to open an issue.

Thank you.

**Closed by AudricV** 2023-02-18 17:44 UTC
Labels: feature request, needs triage
