### ISSUE TITLE
[PERFORMANCE PROBLEM] Videos take longer to start on NewPipe 0.23.0 compared to NewPipe 0.22.2

### ISSUE THREAD

**Issue by CHECK-1234** [TeamNewPipe/NewPipe#8400] opened 2022-05-14 18:00 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Install NewPipe 0.22.2
2. Enter someones YouTube channel
3. Press on a video
4. Play the video
5. Repeat steps 3 & 4 while going down the list videos of videos on a YouTube channel
6. Notce how fast the video starts when clicking to play a video

7. Update to NewPipe 0.23.0
8. Clear cache
9. Enters someones YouTube channel
10. Press on a video
11. Play the video
12. Repeat steps 10 & 11 while going down the list videos of videos on a YouTube channel
13. You should notice that videos take longer to start on NewPipe 0.23.0 when clicking to play a video compared to NewPipe 0.22.2
14.  Delete NewPipe 0.23.0 and repeat steps 1-13 to test again and you should be able to notice how much more faster NewPipe 0.22.2 starts a videos compared to NewPipe 0.23.0

### Expected behavior

Expected videos to start fast in NewPipe 0.23.0 like in NewPipe 0.22.2

### Actual behavior

Videos taking long to start on NewPipe 0.23.0 compared to NewPipe 0.22.2

### Affected Android/Custom ROM version

PHH AOSP Android 12

### Affected device model

LG V40

**Comment by TiA4f8R** [comment] 2022-05-14 18:08
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

No, you didn't, duplicate of #8345. Please search (better, with different keywords?) for duplicates the next time you want to open an issue.

**Closed by TiA4f8R** 2022-05-14 18:08 UTC
Labels: bug
