### ISSUE TITLE
Player crashes after 3 minutes while screen off (fixed through Samsung Device Care)

### ISSUE THREAD

**Issue by 1Olegna** [TeamNewPipe/NewPipe#8664] opened 2022-07-20 13:06 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Play video/audio with screen off.
2. After 3 minutes the video crashes forcing me to unlock screen in order for video/music to start playing again.

### Expected behavior

Video continues to play while screen is off.

### Actual behavior

Video crashes after 3 minutes while screen if off. While screen is on there's no issue.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=d5nJqUlvzmE
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to rr1---sn-vgqsknse.googlevideo.com/2607:f8b0:4009:d::6 (port 443) from /fc00:bbbb:bbbb:bb01::2c:4026 (port 48808) after 8000ms
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.net.SocketTimeoutException: failed to connect to rr1---sn-vgqsknse.googlevideo.com/2607:f8b0:4009:d::6 (port 443) from /fc00:bbbb:bbbb:bb01::2c:4026 (port 48808) after 8000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
	at libcore.io.IoBridge.connect(IoBridge.java:180)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
	... 10 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12/4.1 One UI

### Affected device model

Samsung S10 plus

### Additional information

Works fine on galaxy s9 plus, android 10/ 2.5 One UI

**Comment by SavageTheUnicorn** [comment] 2022-07-21 14:58
Are battery optimizations disabled for the Newpipe app? If this doesn't help then it's a problem with the application itself.

**Comment by lawson85** [comment] 2022-07-21 22:33
Follow steps at dontkillmyapp.com

**Comment by 1Olegna** [comment] 2022-07-22 03:33
I replied back via email, but I don't see the replies. Changed settings and rebooted phone. Will follow up later today. Appreciate the help

**Comment by 1Olegna** [comment] 2022-07-23 02:06
Same issue after changes were made...

**Comment by yalexwander** [comment] 2022-08-16 21:30
Confirming the bug. But not sure if it was the same as in start post. I had stable crash after few minutes after video playback. Independently on screen turned on or off.

Soultion worked for me on android 4.4 : Settings -> Screen -> Sleep time => set to 30 secs(was 5 mins in my case).

**Comment by developedby** [comment] 2023-06-01 21:53
> Follow steps at dontkillmyapp.com

According to this website, on Samsung phones, even disabling battery optimizations the phone may still decide to kill the running service.  
I tried it on my phone (Samsung Galaxy A53, running OneUI 5.1, Android 13) and even with all battery optimizations disabled I still get a "Network Error" every 2-3 minutes.

I wonder if there's anything NewPipe could do to bypass that

**Comment by ebberx** [comment] 2023-06-20 00:56
I believe I have the same issue. Happens when switching context away from newpipe. Fails after 1 min exactly. 

When pressing play in the background, the app seems to be suspended right away and is reloaded upon reopening.

Crash report from when switching context, after 1 min:
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=Toq9YLl49KM
* __Content Country:__ DK
* __Content Language:__ da-DK
* __App Language:__ da_DK
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux samsung/beyond0lteeea/beyond0:12/SP1A.210812.016/G970FXXUGHVJ5:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to rr2---sn-uqj-55gz.googlevideo.com/95.166.96.13 (port 443) from /192.168.1.98 (port 58462) after 8000ms
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.net.SocketTimeoutException: failed to connect to rr2---sn-uqj-55gz.googlevideo.com/95.166.96.13 (port 443) from /192.168.1.98 (port 58462) after 8000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
	at libcore.io.IoBridge.connect(IoBridge.java:180)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
	... 10 more

```
</details>
<hr>

**Comment by PaperOrb** [comment] 2023-08-28 04:20
Just adding my voice to the mix since this doesn't seem to be getting any traction. In my particular case on lineageOS 20 with battery set to unrestricted, I get these network error messages with the screen off, but the app doesn't crash like it used to when I was on an older version of android--it just won't let me play any videos, requiring me to restart newpipe altogether. Switching to a different app for the time being since this has wasted close to a dozen hours within the last year for me and still isn't fixed or addressed.

**Comment by Timothy099qw** [comment] 2023-10-09 01:21
I am interested in fixing this issue, is it possible that this issue can be assigned to me? It seems to be related to the background process. This can possibly be achieved by adding a separate task that always refreshes and shows notification in the menu so that user can confirm its background playing or enable a hidden mini player.

**Comment by eddieofny** [comment] 2023-11-04 19:31
Adding my voice to the mix as well. LG K20 running stock firmware. For me, any video I watch automatically pauses whenever I lock the screen. Ignoring battery optimizations didn't fix it.

**Comment by foxjaw** [comment] 2023-11-07 13:26
I guess this is OneUI issue. I was on Lineage, Graphene & now on A14 GSI. Crash never occured while background play.

**Comment by senescence01** [comment] 2023-11-20 10:22
Anyone with this issue using Rethink DNS or similiar blocker? I noticed that removing it resolves the NewPipe background play interruption.

**Comment by senescence01** [comment] 2023-11-21 15:53
Might be, but also could be my specific filter combination avalible from Rethink app. I didn't go too deep, just noticed it worked since uninstaling Rethink (I switched to Mullvad dns).

**Comment by invinciblevenom** [comment] 2023-11-21 18:27
I have been using NewPipe on my Samsung M21 since OneUI 2.5 to OneUI 4.1 Android 12(Same as OP) now. I always use background play but never faced any issues like this. Even without removing Background restrictions and with apps like SaverTuner, the app never gave any network error.

**Comment by invinciblevenom** [comment] 2023-11-21 18:28
> I guess this is OneUI issue. I was on Lineage, Graphene & now on A14 GSI. Background play never stopped on mine.

It's definitely not a OneUI issue else more users would have reported same.

**Comment by invinciblevenom** [comment] 2023-11-21 18:36
Try disabling Adaptive battery from Device Care @1Olegna @developedby @eldahl

**Comment by eldahl** [comment] 2024-10-19 11:13
Yes, for me it does. Here is a fresh crash log:

{"user_action":"play stream","request":"Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=E7EOjkGVmyo","content_language":"da-DK","content_country":"DK","app_language":"da_DK","service":"YouTube","package":"org.schabi.newpipe","version":"0.27.2","os":"Linux samsung/beyond0lteeea/beyond0:12/SP1A.210812.016/G970FXXUGHVJ5:user/release-keys 12 - 31","time":"2024-10-19 13:11","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: Source error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to rr1---sn-uqj-caad.googlevideo.com/95.166.96.76 (port 443) from /192.168.1.98 (port 35552) after 8000ms\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)\n\tat com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)\n\tat com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)\n\tat com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)\n\tat com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)\n\tat com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:920)\nCaused by: java.net.SocketTimeoutException: failed to connect to rr1---sn-uqj-caad.googlevideo.com/95.166.96.76 (port 443) from /192.168.1.98 (port 35552) after 8000ms\n\tat libcore.io.IoBridge.connectErrno(IoBridge.java:236)\n\tat libcore.io.IoBridge.connect(IoBridge.java:180)\n\tat java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)\n\tat java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)\n\tat java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)\n\tat java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)\n\tat java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)\n\tat java.net.Socket.connect(Socket.java:621)\n\tat com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)\n\tat com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)\n\tat com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)\n\tat com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)\n\tat com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)\n\tat com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)\n\tat com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)\n\tat com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)\n\tat com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)\n\tat com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)\n\t... 10 more\n"],"user_comment":""}

**Comment by eldahl** [comment] 2024-10-19 11:15
Yes for me it does. Here is a fresh crash log:

{"user_action":"play stream","request":"Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=E7EOjkGVmyo","content_language":"da-DK","content_country":"DK","app_language":"da_DK","service":"YouTube","package":"org.schabi.newpipe","version":"0.27.2","os":"Linux samsung/beyond0lteeea/beyond0:12/SP1A.210812.016/G970FXXUGHVJ5:user/release-keys 12 - 31","time":"2024-10-19 13:11","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: Source error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to rr1---sn-uqj-caad.googlevideo.com/95.166.96.76 (port 443) from /192.168.1.98 (port 35552) after 8000ms\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)\n\tat com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)\n\tat com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)\n\tat com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)\n\tat com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)\n\tat com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:920)\nCaused by: java.net.SocketTimeoutException: failed to connect to rr1---sn-uqj-caad.googlevideo.com/95.166.96.76 (port 443) from /192.168.1.98 (port 35552) after 8000ms\n\tat libcore.io.IoBridge.connectErrno(IoBridge.java:236)\n\tat libcore.io.IoBridge.connect(IoBridge.java:180)\n\tat java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)\n\tat java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)\n\tat java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)\n\tat java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)\n\tat java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)\n\tat java.net.Socket.connect(Socket.java:621)\n\tat com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)\n\tat com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)\n\tat com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)\n\tat com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)\n\tat com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)\n\tat com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)\n\tat com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)\n\tat com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)\n\tat com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)\n\tat com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)\n\tat com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)\n\t... 10 more\n"],"user_comment":""}

**Comment by eldahl** [comment] 2024-10-19 11:48
@invinciblevenom 
> Try disabling Adaptive battery from Device Care @1Olegna @developedby @eldahl

Adding NewPipe as an app that never sleeps within Device Care fixes the issue.
Definitely an Android battery optimization/app suspend issue.

**Closed as completed** 2024-10-19 11:54 UTC
Labels: question, device/software specific

**Comment by invinciblevenom** [comment] 2024-11-02 08:32
> @invinciblevenom
> 
> > Try disabling Adaptive battery from Device Care @1Olegna @developedby @eldahl
> 
> Adding NewPipe as an app that never sleeps within Device Care fixes the issue. Definitely an Android battery optimization/app suspend issue.

It's still weird for me as I have been using Extreme Battery Saver profile on my device still never faced any issue with playback
