### ISSUE TITLE
NewPipe UI gets messed if device font size is non default

### ISSUE THREAD

**Issue by silasdb** [TeamNewPipe/NewPipe#2893] opened 2019-12-26 01:45 UTC
- [x] I carefully read the [contribution
guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md)
and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown
converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug
reports.

When changing default device Font Size, NewPipe UI don't adjust (Samsung
Galaxy A10). Language: pt_br. See attached screenshots.

![IMG-20191225-WA0005](https://user-images.githubusercontent.com/105259/71453033-0c05a500-2768-11ea-956d-b4242732f481.jpg)
![IMG-20191225-WA0006](https://user-images.githubusercontent.com/105259/71453034-0c05a500-2768-11ea-9978-45e4d215699a.jpg)

**Comment by gkeegan** [comment] 2019-12-26 02:22
Confirmed.

**Comment by TobiGr** [comment] 2019-12-26 10:59
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1008 and https://github.com/TeamNewPipe/NewPipe/issues/1292

**Closed by TobiGr** 2019-12-26 10:59 UTC
