### ISSUE TITLE
Feature request: Playlists in "What's New"

### ISSUE THREAD

**Issue by oliverpink** [TeamNewPipe/NewPipe#2686] opened 2019-10-04 16:48 UTC
I have a lot of channels I check from time to time, and it would be great to sort them by category. For example, user can create a category like "Music", "Productivity", "Fun", or whatever else and then add some channel in that category. And every time user opens that category it will show the latest video from added channels. 

I think that there are a lot of people for whom this feature would be useful.

**Comment by IT-Tool** [comment] 2019-10-04 18:28
Just today also wanted to create such issue :)

On the tab “What's new” add the ability to choose the channels that will be displayed.
  Now the formation of this list seems more random fixed (channels are fixed and do not move depending on updates)! It's not very convenient.
•  I would like to choose the channels update from which I am interested to receive.
•  Choose how to sort them, by the date of the new video on the channel or by manual sorting.

**Comment by TemporaryAccount0x1** [comment] 2019-10-05 10:32
@mauriciocolli was working on this as part of https://github.com/TeamNewPipe/NewPipe/pull/2309

**Comment by darkwarrior3** [comment] 2019-10-05 10:48
Or randomly would be also okay.

** It would be best if you put new videos in order of date. Latest videos according to time and date would be on top. **

I have so many subscriptions. I have to scroll to bottom each time to search new videos.

**Comment by TemporaryAccount0x1** [comment] 2019-10-05 13:10
@darkwarrior3 this is being worked on in https://github.com/TeamNewPipe/NewPipe/pull/2547 it should be merged soon.

**Comment by Stypox** [comment] 2019-10-06 06:40
Duplicate of #565

**Closed by Stypox** 2019-10-06 06:40 UTC
