### ISSUE TITLE
Subscribers count not showing when searching for a youtube channel

### ISSUE THREAD

**Issue by tadekdudek** [TeamNewPipe/NewPipe#9533] opened 2022-12-11 11:37 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Go to Home screen
2. Search for any youtube channel

### Expected behavior

The channel search result should contain a subscribers count information.

### Actual behavior

There is no subscribers count in the channel search result and the error message appears. Maybe nobody looks at this information, but the error message is so annoying.

### Screenshots/Screen recordings

<img alt="err" src="https://user-images.githubusercontent.com/99012892/206901264-6de5991f-700c-4e3f-96e3-7d757a2feba4.jpg" width=277 />

## Exception
* __User Action:__ searched
* __Request:__ zelent
* __Content Country:__ PL
* __Content Language:__ pl-PL
* __App Language:__ pl_PL
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get subscriber count
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:84)
	at org.schabi.newpipe.extractor.channel.ChannelInfoItemsCollector.extract(ChannelInfoItemsCollector.java:40)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:84)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:48)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:104)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectStreamsFrom(YoutubeSearchExtractor.java:226)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:162)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:21)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:69)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:37)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:82)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$qyxpuXgomWa-cbONQns-pd7zxm0(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:8)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: Failed to find pattern "([\d]+([\.,][\d]+)?)" inside of "@Pasjainformatyki"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:78)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
	at org.schabi.newpipe.extractor.utils.Utils.mixedNumberWordToLong(Utils.java:79)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelInfoItemExtractor.getSubscriberCount(YoutubeChannelInfoItemExtractor.java:81)
	... 23 more

```
</details>
<hr>

### Affected Android/Custom ROM version

LineageOS 18.1

### Affected device model

Redmi Note 7

**Comment by AudricV** [comment] 2022-12-11 14:33
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #9442 and already fixed in the extractor development branch. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2022-12-11 14:33 UTC
Labels: bug, needs triage
