### ISSUE TITLE
Can't translate local language

### ISSUE THREAD

**Issue by tee4341** [TeamNewPipe/NewPipe#8403] opened 2022-05-16 04:10 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

translate to local language
![16-05-2022_10-04-10](https://user-images.githubusercontent.com/48321898/168517857-484a245a-213d-4d97-91a4-755011917f03.png)

YouTube forces you to manually change the language for every clip.

![Episode 1_ What is OpenCL™_ - YouTube - Google Chrome 5_16_2022 10_24_45 AM](https://user-images.githubusercontent.com/48321898/168517884-ac8f8842-1137-4242-a730-ca046c00efdf.png)
and need force translate to local language
![Episode 1_ What is OpenCL™_ - YouTube - Google Chrome 5_16_2022 10_24_58 AM](https://user-images.githubusercontent.com/48321898/168517891-57d7d4cd-1de5-4fed-abc9-c7c5bec0d26b.png)
.

### Why do you want this feature?

I really like America's content and want to keep watching. 
but not all translations can be correct.

### Additional information
now can show  English language  only
![16-05-2022_10-01-40](https://user-images.githubusercontent.com/48321898/168517682-9cf3f52f-67be-4364-b43f-c921171b37a7.gif)
now can show  English language  only
![16-05-2022_10-00-46](https://user-images.githubusercontent.com/48321898/168517705-eb64fb34-ac2c-43a1-ae01-fbb4d2534e8e.gif)

**Comment by SameenAhnaf** [comment] 2022-05-16 04:32
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/8023

**Closed** 2022-05-16 07:16 UTC
Labels: enhancement
