### ISSUE TITLE
v21.0 causing infinite Guru Meditation crash loop

### ISSUE THREAD

**Issue by OldGuyInTheClub** [TeamNewPipe/NewPipe#6012] opened 2021-04-06 01:34 UTC
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Newpipe'
2. Press on 'Any video or videos'
3. Wait 1-10 minutes for instability

### Actual behaviour

LG V20: Android 8.0.0

Updated Newpipe per a Newpipe notification about ten days ago.  System has been unstable ever since.

After a few minutes of use, I will get the "Guru Meditation" error page for ~2 seconds, it will disappear, and then reappear in an endless loop on top of any other applications.  The only solution is a full reboot of the phone.  I can try it again and the error will come back but the time to get to the error will vary from one to many minutes.

### Expected behavior

Newpipe has been very stable up to this point and I simply accept new updates.   But, upon checking it seems 21.0 is in beta?  
https://newpipe.net/blog/pinned/release/newpipe-0.21.0-released/ indicates it is a full release but
https://github.com/TeamNewPipe/NewPipe says the latest is still in beta and to file a bug report if there are problems, hence this message.

Additional observations:
The Newpipe icon will blink on the top icon panel of the phone as the error comes and goes.  

On the lock screen, the Newpipe ribbon is gray and the hourglass indication appears.

I no longer have a Trending icon as shown in
https://github.com/TeamNewPipe/NewPipe/blob/dev/fastlane/metadata/android/en-US/images/phoneScreenshots/shot_01.png
- I only have the Channel groups (TV) and Bookmarked Playlists icons
- I can get Trending through Hamburger -> Trending
- I don't need or use Trending, just noting a discrepancy between what I have and the documentation

I can't find any way to break out of the loop other than rebooting the phone.  e.g. Closing all running apps does not stop the Newpipe error loop

Steps I have taken:
1) Checked the Issues list prior to posting
2) Reproduced the error per above
3) Downgraded to 20.9 - Seems to fix the crashing but some features like YT comments don't work and I frequently get "Something went wrong" messages but without the crash loop
4) Reinstalled 21.0 and confirmed the problem

I can downgrade to any recommended version.  So long as I can watch videos and access playlists, I can live without comments and other features.  

Thanks, 

The Old Guy in the Club

### Screenshots/Screen recordings

Can't capture anything due to infinite Guru Meditation loop.

### Logs

Don't see any applicable logs but I don't know where to look, either.  Again, infinite loop makes this hard to pin down.

### Device info

 - Android version/Custom ROM version: 8.0.0/nothing custom
 - Device model: LG V20

**Comment by mhmdanas** [comment] 2021-04-06 06:35
> I no longer have a Trending icon

It should be present by default; the only thing that could possibly have caused it to not be shown on your device is if somebody messed with NewPipe's settings on your phones. It's possible to add it again by going to "Settings > Content > Content of main page," pressing on the plus button, and choosing "Default Kiosk."

Regarding the infinite loop, this could be related to #5977; do you live in the EU? If so, can you see if the problem is fixed in the APK provided [here](https://github.com/TeamNewPipe/NewPipe/issues/5977#issuecomment-812728868)?

Also, can you try downgrading to 0.20.11 and see if the issue is present there?

**Comment by mhmdanas** [comment] 2021-04-06 06:37
Also, to clear up a misunderstanding you seem to have, 0.21 is indeed a beta release, but so is every previous single release of NewPipe. That's why it's 0.21 with a zero.

**Comment by OldGuyInTheClub** [comment] 2021-04-06 06:47
Ok, re: Beta.  I was not aware of the numbering convention.  

**Trending:** I am the only user of my phone so I don't think anyone changed my settings but it is definitely possible that I changed something without realizing it.

**EU:** No, I am not in the EU but now that you mention it I do use a VPN and use EU servers as part of my "rotation".  I am pretty sure I have had the problem while using non-EU servers (Canada, US, etc.) but will need to investigate this.   It didn't occur to me that this could be a problem so I did not try disabling the VPN.

I will also downgrade to 0.20.11 as you suggested and test it in conjunction with the VPN tests.

Thanks for the suggestions.  I will report what I find.

**Comment by TiA4f8R** [comment] 2021-04-06 08:06
@OldGuyInTheClub Can you also capture logs with a computer with ADB and developer options in your phone settings?
If you don't know how to do, check my comment in [this issue](https://github.com/TeamNewPipe/NewPipe/issues/5155#issuecomment-748531502) and let me know if something went wrong when you try to capture logs.

**Comment by OldGuyInTheClub** [comment] 2021-04-06 08:24
Thanks for the step-by-step instructions.  If the problem persists after the prior tips on location/downgrading, etc. I will see if I can capture some logs.

**Comment by TiA4f8R** [comment] 2021-04-06 08:37
@OldGuyInTheClub Please try to capture logs from 0.21.0 version.

**Comment by OldGuyInTheClub** [comment] 2021-04-09 04:14
**Update:**
**v21.0:** Disabled VPN yet this version continued to crash.

Completely uninstalled v21.0 via help from the IRC channel.

**Installed v20.11:** No crashes over the past couple of days.  Works with the VPN reenabled, as well and I have access to comments and other features.

I use Newpipe intensively mostly on weekends so these are preliminary observations.  If v20.11 continues like this, I am in good shape.

**Comment by OldGuyInTheClub** [comment] 2021-04-17 16:46
V.20.11 has worked well for me.  This solves my problem.

**Comment by mhmdanas** [comment] 2021-04-17 18:28
Even if 0.20.11 works, changes in YouTube will eventually break it and you will have to update to a later version, so I believe this issue should stay open.

**Comment by OldGuyInTheClub** [comment] 2021-04-17 19:08
Ok.  I'll try the latest version and see if any of the prior troubleshooting steps like full deleting/installing make a difference.  Always a chance something is amiss with my phone.

**Comment by OldGuyInTheClub** [comment] 2021-04-18 17:15
For reference, v21.1 has the same issue on my phone:
- Installed over v20.11 and it went into the crash loop within 10 minutes
- Deleted and installed fresh.  It was stable for over 12 hours, then crashed

Both times I was not  actively using the app but had it open in the background. When I went into the app, it crashed and required reboot.  Force Stop did not work.

**Comment by TiA4f8R** [comment] 2021-04-18 17:37
We cannot solve this issue until you can capture logs and send the logs. Can you please try to get logs? Thanks!

**Comment by OldGuyInTheClub** [comment] 2021-04-18 18:20
I'll try to implement ADB and report back.

**Comment by OldGuyInTheClub** [comment] 2021-04-18 18:39
Unfortunately, adb devices returns a blank line. 

 Additionally, my phone goes into an infinite "USB debugging connected: Tap to turn off in settings" and "File transfer: Tap to change USB options" loop.  Keeps beeping and putting up notifications.  Maybe this is related to the underlying problem with Newpipe v21.x.  Probably something wrong with my phone and not Newpipe.

**Comment by TiA4f8R** [comment] 2021-04-18 22:22
You can have some problem with drivers on your computer, especially on Windows (I had this problem). If you are on this system, try opening the Device Manager (right-click on the Start menu). If there is a problem with an unknown USB Driver which isn't another driver than what you think be your phone, try updating the non-working driver with the USB MTP Device (you need to search in the list of drivers, USB drivers). You can find more on the Internet.

**Comment by OldGuyInTheClub** [comment] 2021-04-19 00:05
I am on a Mac.  I found some threads and got drivers/software from LG's site but the software requires Catalina (10.15) and I am on Mojave (10.14.6).   Sorry but this is at the limits of my abilities.  I'll use v20.11 as long as it lasts and hope for the best with future Newpipe releases.  Thank you for the help.

**Comment by TiA4f8R** [comment] 2021-04-19 10:20
Oh ok, I'm sorry. However, can you reproduce the bug with the 0.21.2 version in development (#6052)?

**Comment by OldGuyInTheClub** [comment] 2021-04-21 04:05
v0.21.2 development also crashed but I think I may be seeing a pattern for at least _some_ of the crashes.  Cellular reception in/near my house isn't great although I am supposedly in a strong coverage area.  I use wifi in the house but when I leave, there can be a  gap between when wifi cuts off and the cellular data network cuts in.  On some of those occasions (but not all), I've noticed Newpipe v0.21.x crashing.  

Again, it doesn't happen all of the time which makes systematic checking difficult.  I can't guarantee that this is the cause of all the crashes, either but there is a correlation worth noting.

Because of spotty cellular data service (US Sprint in limbo to T-Mobile but still a Sprint SIM card), I keep "Cellular data always active" enabled in Developer Options, otherwise I can be without cellular data for long stretches when wifi disconnects.  Even then I periodically need to go in and out of airplane mode to force reconnection.  Could this flaky connection be an issue with v0.21.x but not with earlier versions?  

I will try disabling "Cellular data always active" and see what happens but wanted to mention the possibility.

**Comment by OldGuyInTheClub** [comment] 2021-08-15 00:54
A couple of weeks ago my cell ISP pushed an update that improved a lot of connection problems with their data network.  This is across all applications, not just NewPipe.

I tried v21.8 and it has been stable for over a week.  Per a prior comment, I think this issue is phone related due to the unstable connection and not a problem with the NewPipe app.

**Comment by litetex** [comment] 2021-08-25 15:12
Great that you found out the problem 👍 

I think we can close the issue if there are no further problems regarding this topic.

**Closed** 2021-08-25 16:20 UTC
Labels: bug, more info needed

**Comment by WaleedaliAjeebi** [comment] 2022-12-30 11:09
> ما كان يجب أن يحدث. Guru Meditation.

ما حدث :

تم تحطم App/UI

المعلومات :

UI Error

Application crash

۱۱:۰۸۳۰-۱۲-۲۰۲۲

What:

Request: GMT Time:

nVersion: Version:

Device:

Device:

nModel:

nModel:

com.transsion.filemanagerx

9999000.6.7

Linux Android 12-31

2036

V2035

2036C

التعقيب الخاص بك (باللغة الانجليزية) :

التفاصيل :

java.lang.RuntimeException: Unable

to

Strongly consider using FLAG_IMMUTABLE

at android.app.ActivityThread.handleS

at android.app.ActivityThread.access$ at android.app.ActivityThread$H.handl

at android.os.Handler.dispatchMessage at android.os.Looper.loopOnce (Looper.j

at android.os.Looper.loop(Looper.java at android.app.ActivityThread.main(Aci

at java.lang.reflect.Method.invoke(Na at com.android.internal.os.RuntimeIni1
