### ISSUE TITLE
Send link from SoundCloud app to NewPipe

### ISSUE THREAD

**Issue by VasilisKos** [TeamNewPipe/NewPipe#7775] opened 2022-02-02 07:08 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Trying to send a soundcloud link (song) from the official Soundcloud app, through the share button, gives the message that the url is not supported, and the option to open the link in the internet browser. Doing so, loops back to the soundcloud app, and asks which app I want to open the link with. Choosing NewPipe then works properly.

### Expected behavior

The soundcloud link should be recognised in the first place, and not making that loop behaviour.

### Device info

 - Android version/Custom ROM version: 10
 - Device model: Nokia 6.2

**Comment by mhmdanas** [comment] 2022-02-03 09:08
Could you please post the URL here?

**Comment by VasilisKos** [comment] 2022-02-03 09:26
> Could you please post the URL here?

e.g. https://soundcloud.app.goo.gl/tSrUa

**Comment by mhmdanas** [comment] 2022-02-03 09:48
Duplicate of #5025.

**Closed by mhmdanas** 2022-02-03 09:48 UTC
Labels: bug
