### ISSUE TITLE
Full screen not working properly

### ISSUE THREAD

**Issue by danilo-alm** [TeamNewPipe/NewPipe#8374] opened 2022-05-08 22:34 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Open any video
2. Click on the full screen button

### Expected behavior

Video occupies the whole screen

### Actual behavior

Video occupies 1/4 of the screen

### Screenshots/Screen recordings

![Screenshot_20220508-192456_NewPipe](https://user-images.githubusercontent.com/88722240/167318440-352c843d-69cf-4913-9de6-c2ff33154636.jpg)

### Affected Android/Custom ROM version

Android 12 - One UI 4.1

### Affected device model

Galaxy Note 10 Lite

### Additional information

The bug occurs randomly. When it happens I just keep exiting and coming back to full screen mode until it stops

**Comment by SameenAhnaf** [comment] 2022-05-08 22:48
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7262

**Closed** 2022-05-08 23:10 UTC
Labels: bug
