### ISSUE TITLE
Ui crash on videos which have comments

### ISSUE THREAD

**Issue by djubre7** [TeamNewPipe/NewPipe#10973] opened 2024-04-14 13:30 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

27.0

### Steps to reproduce the bug

Load subscribed json, watch video without comments - plays, watch video with comments - ui crash

### Expected behavior

Watch video regardless of comments

### Logs

{"user_action":"ui error","request":"ACRA report","content_language":"en-US","content_country":"US","app_language":"en_US","service":"none","package":"org.schabi.newpipe.nightly","version":"0.26.1","os":"Linux Android 13 - 33","time":"2024-04-14 15:27","exceptions":["java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.extractor.stream.Description.getType()' on a null object reference\n\tat org.schabi.newpipe.util.text.TextLinkifier.fromDescription(TextLinkifier.java:70)\n\tat org.schabi.newpipe.util.text.TextEllipsizer.linkifyContentView(TextEllipsizer.java:166)\n\tat org.schabi.newpipe.util.text.TextEllipsizer.setContent(TextEllipsizer.java:62)\n\tat org.schabi.newpipe.info_list.holder.CommentInfoItemHolder.updateFromItem(CommentInfoItemHolder.java:127)\n\tat org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:337)\n\tat androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)\n\tat androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)\n\tat androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)\n\tat androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)\n\tat androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)\n\tat androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)\n\tat androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)\n\tat androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)\n\tat androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)\n\tat androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)\n\tat com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)\n\tat com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2381)\n\tat androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:270)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:270)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)\n\tat androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)\n\tat com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:576)\n\tat androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:270)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1582)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:270)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1582)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:270)\n\tat com.android.internal.policy.DecorView.onLayout(DecorView.java:1427)\n\tat android.view.View.layout(View.java:24969)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6784)\n\tat android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4917)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4240)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:923)\n\tat android.view.Choreographer.doFrame(Choreographer.java:852)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)\n\tat android.os.Handler.handleCallback(Handler.java:942)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.app.ActivityThread.main(ActivityThread.java:8757)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)\n"],"user_comment":""}

### Affected device model

Samsung s22 ultra

**Comment by mwang99** [comment] 2024-04-16 03:49
Also experiencing this bug.

**Comment by djubre7** [comment] 2024-04-18 16:47
> Doesn't happen to regular videos?

No, I just rechecked. Videos without comments load normally, with comments I get UI crash...

**Comment by djubre7** [comment] 2024-04-18 20:56
Same behavior even with the non-subscribed videos. I did managed to open one video with comments, but as soon as I tried to play it, it crashed. Afterwards I couldn't open it again.

**Comment by ITILLI** [comment] 2024-04-22 05:02
same issue even non-subscribed
## log
comment is missing
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1722)
	at android.app.Activity.startActivityForResult(Activity.java:5258)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:5203)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:5587)
	at android.app.Activity.startActivity(Activity.java:5555)
	at org.schabi.newpipe.error.ErrorUtil$Companion.openActivity(ErrorUtil.kt:43)
	at org.schabi.newpipe.error.ErrorUtil$Companion.showSnackbar$lambda$0(ErrorUtil.kt:149)
	at org.schabi.newpipe.error.ErrorUtil$Companion.$r8$lambda$hbVLiP6-HtFc17h3_yyNDsmaIY8(ErrorUtil.kt:0)
	at org.schabi.newpipe.error.ErrorUtil$Companion$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar.$r8$lambda$4rINiMZz55Dc47hSTCuz-ALWyEw(Snackbar.java:0)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7869)
	at android.widget.TextView.performClick(TextView.java:15003)
	at android.view.View.performClickInternal(View.java:7838)
	at android.view.View.access$3600(View.java:886)
	at android.view.View$PerformClick.run(View.java:29362)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8129)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: android.os.TransactionTooLargeException: data parcel size 1241828 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:575)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4433)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	... 25 more

```
</details>
<hr>

**Comment by djubre7** [comment] 2024-04-22 09:11
> Alright. Mind updating the description then?
> 
> Also, when you say "without comments", do you mean you turn comments off, or videos that actually have zero comments?

Videos that actually have zero comments.

**Comment by AudricV** [comment] 2024-04-22 11:23
> - [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #10888. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-04-22 11:23 UTC
Labels: bug, needs triage
