### ISSUE TITLE
Duplicated videos in a playlist don't load after the 1st one.

### ISSUE THREAD

**Issue by sqtvrnqliq** [TeamNewPipe/NewPipe#5255] opened 2020-12-23 03:18 UTC
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any playlist with a duplicated video that plays after the original.
2. Press on the background play option or play all.
3. Wait until the original video is done or fast forward; then comes the infinite buffering.

### Actual behaviour

After the og video, the duplicate will be stuck buffering in timelessness.

### Expected behavior

The duplicate video loads as normal without an issue.

### Logs

Because of this issue, I had to switch to the pre-unified 0.19.8 version which loaded the playlist as normal but buffered a little after some time and then went back to playing the expected video. I have no idea at all what's causing this issue in the newer builds but it's most probably youtube's doing. I do hope you at least try to fix this because there's no other ad free app I can listen to my long playlists on.
 
Thank you.

### Device info

 - Android version/Custom ROM version: 9
 - Device model: Samsung J5 (2017 Build)

**Comment by RickyM7** [comment] 2020-12-23 08:24
Duplicate of #4940.

**Closed** 2020-12-23 11:37 UTC
Labels: bug
