### ISSUE TITLE
Custom Sites

### ISSUE THREAD

**Issue by maxxxed69** [TeamNewPipe/NewPipe#7596] opened 2021-12-29 15:16 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

To be able to add custom sites/ urls would be incredibly liberating.

#### Why do you want this feature?

For as much as I support NewPipes' support for YouTube, Soundcloud, and other peer video site. I think, if it is feasible, but has yet to be added, that the team is doing a huge disservice to the app itself and it's users and contributors. 

I plan to continue using newpipe, and I hope this will be seriously considered.

**Comment by litetex** [comment] 2021-12-29 17:40
Duplicate of #7456

**Closed** 2021-12-29 17:40 UTC
Labels: enhancement, template-ignored
