### ISSUE TITLE
Crash after trying to delete a video from a playlist

### ISSUE THREAD

**Issue by d4f5409d** [TeamNewPipe/NewPipe#6124] opened 2021-04-20 20:22 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to playlist page
2. Press on a playlist
3. Try to remove a video

It happens randomly, but today it did happen 2 times. I deleted a video from my playlist, watched another, and I've tried to delete that one and NewPipe got crashed.

### Actual behaviour

When I try to delete it, ut crashes. I open the app again, and I can delete it.

### Expected behavior

Deleting a video from a playlist

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ UK
* __Content Language:__ en
* __App Language:__ en_UK
* __Service:__ none
* __Version:__ 0.21.1
* __OS:__ Linux Samsung Android 9
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=37; index=-1
	at java.util.ArrayList.remove(ArrayList.java:506)
	at org.schabi.newpipe.local.LocalItemListAdapter.removeItem(LocalItemListAdapter.java:129)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.deleteItem(LocalPlaylistFragment.java:602)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$23(LocalPlaylistFragment.java:780)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$23$LocalPlaylistFragment(Unknown Source:0)
	at org.schabi.newpipe.local.playlist.-$$Lambda$LocalPlaylistFragment$mqVZbx-Y0Wr3WWOrkG9BVt02WwI.onClick(Unknown Source:4)
	at org.schabi.newpipe.util.StreamDialogEntry.clickOn(StreamDialogEntry.java:144)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$24(LocalPlaylistFragment.java:783)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$24$LocalPlaylistFragment(Unknown Source:0)
	at org.schabi.newpipe.local.playlist.-$$Lambda$LocalPlaylistFragment$DKJcisObqgB6j43xoqruTCAJLOE.onClick(Unknown Source:4)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1299)
	at android.widget.AdapterView.performItemClick(AdapterView.java:362)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
	at android.widget.AbsListView$7.run(AbsListView.java:6612)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-04-21 10:07
Duplicate of #3891.

**Closed by mhmdanas** 2021-04-21 10:07 UTC
Labels: bug
