### ISSUE TITLE
Player don't jump to specific time after clicking timestamp link in comment

### ISSUE THREAD

**Issue by libkoi** [TeamNewPipe/NewPipe#5231] opened 2020-12-20 07:47 UTC
### Checklist
- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Enable "Picture in Picture" function for NewPipe
2. Open a YouTube video that contains a timestamp link in its comment section
3. Click that timestamp link

### Actual behaviour
A new Picture-in-Picture window is created.

### Expected behavior
The main player jumps to the timestamp specified by that link, no new window is created.

### Screenshots/Screen recordings
![Screenshot_20201220-153148_NewPipe](https://user-images.githubusercontent.com/18418456/102707902-f161ff80-42d9-11eb-86a9-2939f0c6e671.png)
Tooltip text: "Play in picture-in-picture" mode

### Device info

 - Android version/Custom ROM version: 9
 - Device model: Xiaomi MI 6

**Comment by mhmdanas** [comment] 2020-12-20 12:07
Duplicate of #4241.

**Closed by mhmdanas** 2020-12-20 12:07 UTC
Labels: bug
