### ISSUE TITLE
Video always goes to Zoom mode as default - Kind of 'forgets' the preference

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#5786] opened 2021-03-07 10:41 UTC
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play any video.
2. Goes to zoom mode on its own.
3. Forgets settings anything besides zoom mode.

### Actual behaviour

Video plays in zoom mode every time. Ignores user selected options for viewing mode.

### Expected behavior

Should remember the view mode selection by user.

### Screenshots/Screen recordings

![IMG_0007](https://user-images.githubusercontent.com/55331939/110237297-3984db80-7f33-11eb-90b3-a14b469f540b.gif)

### Device info

 - Android version/Custom ROM version: Android 10 Stock
 - Device model: OnePlus

**Comment by desmonk** [comment] 2021-03-07 10:43
This has been going on since many weeks now and not a recent update could have caused this. Either my phone is doing this or the app or some settings that I might have messed up. But there is no settings for this in the Settings menu so I am not sure.

**Comment by furquan-lp** [comment] 2021-03-07 12:13
> This has been going on since many weeks now and not a recent update could have caused this. Either my phone is doing this or the app or some settings that I might have messed up. But there is no settings for this in the Settings menu so I am not sure.

It's probably not your phone because I'm facing the same problem across two different phones. I figured it'd have been fixed in 0.20.11 but the issue remains after the update on both devices.

**Comment by mhmdanas** [comment] 2021-03-07 12:17
Duplicate of #5613.

**Closed by mhmdanas** 2021-03-07 12:17 UTC
Labels: bug
