### ISSUE TITLE
Can't Able to Play any YouTube Video

### ISSUE THREAD

**Issue by AsVeganOk** [TeamNewPipe/NewPipe#7815] opened 2022-02-05 11:15 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.schabi.newpipe.extractor.stream.StreamInfo org.schabi.newpipe.player.resolver.MediaSourceTag.getMetadata()' on a null object reference
	at org.schabi.newpipe.player.Player.onPlayerError(Player.java:2526)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$10(ExoPlayerImpl.java:1269)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$-K5msfvAakBrxKAsG9AjoK30L1g(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda7.invoke(Unknown Source:4)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283)
	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
	at com.google.android.exoplayer2.util.ListenerSet.$r8$lambda$NbKDn9xtItiyMgYZmjIx_Sv1FFQ(Unknown Source:0)
	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1340)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1175)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1(ExoPlayerImpl.java:216)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$nOBJYkeEQ2uz3sBKLToLWmzrgZk(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda22.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8246)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: 11/ Funtouch    #@@OS_10.5
 - Device model: vivo 1919

**Comment by mhmdanas** [comment] 2022-02-05 11:41
Duplicate of #7734. Update to 0.21.16. If you're using the official F-Droid repository, it may take some time to publish the update. In case you don't want to wait, follow the instructions in https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/, and don't forget to export your database before uninstalling NewPipe, or you will lose all your NewPipe data.

**Closed by mhmdanas** 2022-02-05 11:41 UTC
Labels: bug

**Comment by TiA4f8R** [comment] 2022-02-05 11:48
> - [x] I am using the latest version - x.xx.x

You need to fill in the version you are using. And also template sections.

> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

Really? There are 28 duplicates of a pinned issue (excluding this one)!

So please really search instead of probably ticking a checkbox by lazyness (or use better search keywords, I don't know!)

Like mhmdanas said, update to version 0.21.16 to fix this issue. If you are using F-Droid official repo to get NewPipe updates, don't forget that it takes more time to be available on F-Droid because it recompiles the app from the source.

It is [available on it since yesterday](https://f-droid.org/en/packages/org.schabi.newpipe/#latest) so you may need to update your repositories to get it.

Thank you.
