### ISSUE TITLE
Feature request: Deduplication of list items

### ISSUE THREAD

**Issue by JeffRockatansky** [TeamNewPipe/NewPipe#5027] opened 2020-11-28 23:00 UTC
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at [CONTRIBUTING.md](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
An option to automatically find and remove and/or disallow duplicate list items (for Youtube it would be videos in playlists).

#### Is your feature request related to a problem? Please describe it
I'm creating multiple lists by categories as I plan something to watch later. Sometimes the playlist accumulates quite a lot of videos so I don't remember if a video is already in a list or not.

#### Additional context
Duplicate Tabs Closer Firefox Extension is nice)

#### How will you/everyone benefit from this feature?
It will be much more convenient to use playlists.

**Comment by RickyM7** [comment] 2020-11-29 01:19
I think it's a duplicate of the #4186.

**Comment by mhmdanas** [comment] 2020-11-29 06:30
To be more precise, it's a duplicate of #1473, which was closed in favor of #4186.

**Closed by mhmdanas** 2020-11-29 06:30 UTC
Labels: enhancement
