### ISSUE TITLE
Could not parse website | ParsingException: Could not get comment id

### ISSUE THREAD

**Issue by Iodine98** [TeamNewPipe/NewPipe#10968] opened 2024-04-12 09:23 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Open the `NewPipe` app on phone (Oneplus Nord AC2003)
2. Go to this YouTube video: [https://www.youtube.com/watch?v=rdBMmOaAbQk](https://www.youtube.com/watch?v=rdBMmOaAbQk)
3. The result is as shown in the screenshot

### Expected behavior

I expect to see the comments under that video. See the below screenshot of the Desktop browser version:
![image](https://github.com/TeamNewPipe/NewPipe/assets/12817322/2a8603ec-08a3-4af7-97e2-4ca2ef4b5070)

### Actual behavior

I only see empty profile icons with the thumbs up button without any text and a toast with _Something went wrong REPORT_

### Screenshots/Screen recordings

<img alt="WhatsApp Image 2024-04-12 at 11 13 32_830a53f3" src="https://github.com/TeamNewPipe/NewPipe/assets/12817322/37e20fde-be75-49ff-acfd-80109c87f83e" width=283 />

### Logs

{"user_action":"requested comments","request":"Start loading: https://www.youtube.com/watch?v=rdBMmOaAbQk","content_language":"en-US","content_country":"US","app_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.26.1","os":"Linux OnePlus/Nord_EEA/Nord:12/RKQ1.211119.001/Q.202211241830:user/release-keys 12 - 31","time":"2024-04-12 11:15","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get comment id\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentId(YoutubeCommentsInfoItemExtractor.java:212)\n\tat org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:24)\n\tat org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:124)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)\n\tat j$.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source:2)\n\tat j$.util.stream.ReferencePipeline$3$1.accept(Unknown Source:10)\n\tat j$.util.stream.ReferencePipeline$3$1.accept(Unknown Source:10)\n\tat j$.util.stream.ReferencePipeline$2$1.accept(Unknown Source:12)\n\tat j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source:19)\n\tat j$.util.stream.AbstractPipeline.copyInto(Unknown Source:22)\n\tat j$.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source:10)\n\tat j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source:0)\n\tat j$.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source:0)\n\tat j$.util.stream.AbstractPipeline.evaluate(Unknown Source:34)\n\tat j$.util.stream.ReferencePipeline.forEach(Unknown Source:5)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:263)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.extractComments(YoutubeCommentsExtractor.java:206)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:58)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:21)\n\tat org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:48)\n\tat org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:29)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:153)\n\tat org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$60N_-UL7E5eaxFaFO1bZZmnfwM8(ExtractorHelper.java:0)\n\tat org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda4.call(R8$$SyntheticClass:0)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)

### Affected Android/Custom ROM version

Android 12 / OxygenOS 12.1

### Affected device model

Oneplus Nord (Build no: Build no: AC2003_11_F_23)

### Additional information

Using my home's WiFi connection

**Comment by AudricV** [comment] 2024-04-12 09:33
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #10808. Please search (better, with different keywords?) for duplicates, **especially pinned issues**, the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-04-12 09:33 UTC
Labels: bug, needs triage
