### ISSUE TITLE
guru meditation error

### ISSUE THREAD

**Issue by Gogutzel** [TeamNewPipe/NewPipe#8507] opened 2022-06-12 16:44 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

f0.23.0

### Steps to reproduce the bug

While playing something and click to play other on the list in the right, it appears always sorry....guru meditation and a report, this is on Android tv 8.0,. That red page let me to copy format error on the screen but i cannot copy there. ## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@fe7e845 with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.createNotification(NotificationUtil.java:92)
	at org.schabi.newpipe.player.NotificationUtil.createNotificationAndStartForeground(NotificationUtil.java:179)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:126)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
	... 8 more

```
</details>   

### Expected behavior

I expect you to fix that, is to good project to go anywhere else. Thank you!

### Actual behavior

,,need to restart apk and go to history to see what was playing before and start again to play....

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@fe7e845 with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.createNotification(NotificationUtil.java:92)
	at org.schabi.newpipe.player.NotificationUtil.createNotificationAndStartForeground(NotificationUtil.java:179)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:126)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
	... 8 more

```
</details>
<hr>

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@fe7e845 with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
	at android.app.ActivityThread.-wrap20(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.createNotification(NotificationUtil.java:92)
	at org.schabi.newpipe.player.NotificationUtil.createNotificationAndStartForeground(NotificationUtil.java:179)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:126)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
	... 8 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 8.0 Android TV Tesla globe

### Affected device model

Tesla TV globe 

### Additional information

hanimations off, no matterfs if standard limit or no backround processes ckecked in the developer oprions

**Comment by TiA4f8R** [comment] 2022-06-12 18:25
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #8384.

**Closed by TiA4f8R** 2022-06-12 18:25 UTC
Labels: bug
