### ISSUE TITLE
UI overlay stays when unpausing from bluetooth.

### ISSUE THREAD

**Issue by EvilGremlin** [TeamNewPipe/NewPipe#6282] opened 2021-05-13 20:07 UTC
Well, that. Any android version (6,7,9), any BT device, any NewPipe version of last year or so.

**Comment by mhmdanas** [comment] 2021-05-14 22:04
Can you clarify what an "overlay" is? Also, please don't remove the template when opening an issue.

**Comment by EvilGremlin** [comment] 2021-05-15 09:25
UI overlay is all controls etc.
Issue is waaay too simple and easily reproduceable to warrant lengthy template imo.

**Comment by mhmdanas** [comment] 2021-05-15 10:58
Duplicate of #3403.

**Closed by mhmdanas** 2021-05-15 10:58 UTC
Labels: bug, user-ignored-template-instructions

**Comment by EvilGremlin** [comment] 2021-05-15 11:20
Ahaha, so i just serched for wrong words. Again.
