### ISSUE TITLE
Update to v0.21.6 removed "Play to Kodi" from channel groups video list

### ISSUE THREAD

**Issue by lameventanas** [TeamNewPipe/NewPipe#6681] opened 2021-07-16 09:54 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Click on any channel group (or "All")
2. Long-press any video

### Actual behavior

"Play to Kodi" menu entry isn't in the context menu
Doing the same thing from the video's channel (instead of channel group) does show the menu entry

### Expected behavior

"Play to Kodi" menu entry should be there.
"Queue in Kodi" would be the great (see #6181).

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by thegergo02** [comment] 2021-07-20 11:44
You need to enable it in "Settings/Video and audio"

**Comment by lameventanas** [comment] 2021-07-20 12:35
Of course it is enabled in the settings.
"Play to Kodi" shows up in the context menu of channel video lists, but not of channel group video lists.
In previous versions it showed up in both.

**Comment by thegergo02** [comment] 2021-07-20 14:28
Oh I see, I can confirm this too.

**Comment by C-O-D** [comment] 2021-08-28 07:43
Yes, the Kodi entry in the context menu is gone since 0.21.9 - but I really like to have it there.
Too many clicks necessary otherwise to get there, not convenient - can we please get this back?

**Comment by AudricV** [comment] 2024-02-10 23:04
I see this option, when the option to show this menu item is enabled, on stream items in the `All` channel groups on the 0.26.1 version. Therefore I am closing this issue as fixed, but if it is not, please comment and I will reopen this issue. Thank you.

**Closed by AudricV** 2024-02-10 23:04 UTC
Labels: bug
