### ISSUE TITLE
Mismatch between shown video and playing video

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#6822] opened 2021-08-01 13:21 UTC
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Search for something
2. Open a video and click play
3. Swipe down to minimize it while its playing
4. Click on another video
5. The newly-clicked video's title is shown, but the previous video is sometimes loaded into the main player where it keeps playing, thus giving the appearance of a wrongly-titled video

### Actual behavior

The newly chosen video is not pre-loaded and the previous video is now playing in the main player with the newly-clicked video's info below it - note this only happens sometimes

### Expected behavior

The previous video should EITHER stop playing AND the newly chosen video should load OR the previous video should continue playing in its minimized state while the user sees the newly-clicked video's info and thumbnail loaded into the main player's view

### Device info

 - Android version/Custom ROM version: 8.0
 - Device model: Samsung Galaxy S7 Edge

*Not sure if it's relevant or not, but I currently have 'Show comments' and 'Show description' disabled.

**Comment by ThisIsPaulDaily** [comment] 2021-08-02 11:07
I believe this is expected behavior and should remain as is. 
Especially because the enque in pop-up fix feature branch hasn't been merged. If that branch merged, I think your issue would be less of an issue.

**Comment by infinitewaveparticle** [comment] 2021-08-02 14:21
@ThisIsPaulDaily There's no way this is a feature. Perhaps I didn't make it clear enough, but playing a video (not in pop-up, but the regular GUI player) with a different video's title where its title should be can't possibly be a feature (I have screenshots, just no browser on this device that allows me to upload them).

This has nothing to do with queuing another video or playing it in the pop-up function. I am simply trying to load a new video and play it now (which should stop the current one from playing, but doesn't).

If I were trying to add it to a queue (which I am not - I never use that feature), then I'd expect both the title and the video to load after the current one ends, but in my case the title for the newly-clicked video loads where the current one was as the current one keeps playing.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2021-08-02 14:24
p.s. The minimized video that is playing becomes un-minimized; the title for the one I just clicked replaces its title, but the video for the one I just clicked does not load... So I'm left with a mismatched title/video. I hope this all makes it clear now.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by chrstfer** [comment] 2021-08-03 04:05
Nah this is definitely the expected behavior. The player is decoupled from the info beneath it. I realize coming from the main youtube app this is a bit unusual, but its whats supposed to happen and its honestly a better experience imo. If you want to play it, you can use the context/long-press menu or just click the button corresponding to the player you want to play the video in.

**Comment by infinitewaveparticle** [comment] 2021-08-03 15:03
@Chris well if you're correct, then either it's a terrible "feature" or you don't understand what I'm saying. BTW, I have never used the main YouTube app. I'm just saying that these things shouldn't be like this. The title of the video should always match the video that's loaded/playing in the main player (I'm not using the popup). Please tell me how mislabeling a video is a better experience for you.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ThisIsPaulDaily** [comment] 2021-08-04 01:26
It's not "mislabeled" it's working as expected. If I want to know the description of a video I can read it ahead of playback. If I decide to play the video, I can long press and play it. 

It may be good to annotate some screenshots. Maybe you could be correct and I'm just the user with the weird workflow :D https://xkcd.com/1172/

**Comment by infinitewaveparticle** [comment] 2021-08-06 17:47
@ThisIsPaulDaily

I'll definitely upload a screenshot of what I mean sometime this weekend. I just need to use my other device to do it. Sorry for the late reply. Life got in the way.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2021-08-07 15:11
The first screenshot shows a video playing with its correct title directly underneath it:
![NewPipe wrong-title bug1_2021-08-01_07-57-45](https://user-images.githubusercontent.com/29090831/128604733-dfd4d549-595c-4c96-b2bb-26e8b5d50927.jpg)
The second screenshot shows what I saw when I did the steps listed above. Note that the title is of the video I clicked to load/play, but the video playing is still the one from the screenshot above. This doesn't happen every time I take these steps, but it does happen sometimes.
![NewPipe wrong-title bug2_2021-08-01_07-57-22](https://user-images.githubusercontent.com/29090831/128604746-06851ef2-3d11-45fc-aef3-5217c9c5302b.jpg)

**Comment by chrstfer** [comment] 2021-08-11 18:09
See the buttons under the title? Those are used to play the video in the player. 

Being able to browse video descriptions while another video is playing is an objectively preferable experience to not being able to. Its exceedingly frustrating to need to save your current video somewhere (there's no easy way to stash queues either, making this even worse) when you just want to, for instance, grab a link from the description of another video. 

Forcing the lower panel to be tied to the currently playing video is not gonna happen, the player was designed the way it is now for a reason. This isnt a bug its an excellent feature, and im not sure what bothers you about it quite honestly. If you wanted to request that an option be created to force the panel and the player to be linked, please create a new feature/enhancement request issue.

**Comment by infinitewaveparticle** [comment] 2021-08-12 21:28
Chris -

I don't mind seeing descriptions of other videos when a video is playing, but a title? That seems dumb. It would be better to reserve that for when the current video is playing in the popup player or is minimized and still playing. Also, why does this only happen sometimes? Most of the time it works the way I want it to - the title and the video both change when I click on a new video. So if this happens every time for you, then we have different experiences with the app.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2021-08-12 21:36
Also, I have ADD pretty badly so watching a video while reading a description just isn't possible. I can't multitask like that. My attention stream is limited to one thing at a time or else I completely miss out on both... So as I've mentioned before I'd love to be able to customize every single nuance of the app... And it would also be great to have different apks based on device and OS and different preset settings based on device settings. Perhaps this issue title should be changed to "happens sometimes" and it could be fixed to be a setting that we all can set as we desire.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2021-09-27 20:17
To all in this thread: I finally understand where I was failing to describe this issue correctly. I have edited the title and the description of the issue accordingly. I hope this makes it much more clear. I now understand what you were pointing out. The problem seems to be that the minimized video currently playing should remain minimized while it continues to play, but it doesn't always do so.

**Comment by opusforlife2** [comment] 2021-10-02 06:51
Try to use simple titles, my dude.

**Comment by ShareASmile** [comment] 2024-02-17 19:19
Is it still an issue on 0.26.1?

**Closed** 2024-03-06 00:12 UTC
Labels: bug, GUI, player, waiting for author
