### ISSUE TITLE
Export / Backup Playlist

### ISSUE THREAD

**Issue by zaheernathani** [TeamNewPipe/NewPipe#4123] opened 2020-08-13 03:27 UTC
**In addition to export option of subscription we should have Export / Backup _Playlist_ option as well.**

**Comment by zaheernathani** [comment] 2020-08-13 13:42
I need to use Syncthing to keep kt synchronised

**Comment by opusforlife2** [comment] 2020-08-13 15:24
Duplicate of #4076. Always search before creating a new issue.

**Closed by opusforlife2** 2020-08-13 15:24 UTC
Labels: enhancement
