### ISSUE TITLE
support showing contents from multiple countries

### ISSUE THREAD

**Issue by chlxt** [TeamNewPipe/NewPipe#6608] opened 2021-07-04 11:47 UTC
#### Describe the feature you want

add support for show content  from multiple countries simultaneously in `Trending` tab, currently newpie can only show one default country content.

I think NewPie team may change selection option from radio button to checkbox to support contents from multiple countries.

#### How will you/everyone benefit from this feature?

This feature will let us see latest trending content from multiple countries without having to manually change the default content county option and restart the app.

**Comment by SameenAhnaf** [comment] 2021-07-04 12:50
Duplicate of #5496. Also, fill in the template properly. You are not supposed to remove it.

**Closed** 2021-07-04 16:12 UTC
Labels: enhancement
