### ISSUE TITLE
Crash on pressing Download button or Download tab

### ISSUE THREAD

**Issue by k-slava** [TeamNewPipe/NewPipe#6775] opened 2021-07-27 07:13 UTC
### Logs

Crash of the app on pressing Download button or Download tab.
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3582)
	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3570)
	... 8 more

```
</details>
<hr>

### Checklist

- [x] I am using the latest version - 0.21.7
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Way 1

1. Go to video
2. Press on download
3. Crash

Way 2

1. Swipe to menu
2. Press on downloads
3. Crash

### When it started

It started from the previos version of the app. I waited for the new version but it didn't fix the bug.

**Comment by bew** [comment] 2021-07-27 07:45
Duplicate of #6687

**Closed** 2021-07-27 09:40 UTC
Labels: bug
