### ISSUE TITLE
Tap-through area below Report button on Video Details Page

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#6406] opened 2021-05-31 18:29 UTC
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open the link given in #6403.
2. See the "age-restricted" error and a Report button.
3. Tap the area below the Report button (except the area where the bottom tabs are supposed to be).

### Actual behaviour

Tapping in that area actually taps on whatever is below the fragment: search results page, any feed (such as What's New), the Subscriptions tab, the Bookmarked Playlists tab, etc.

Also, tapping on the area where the video title should be (which expands the action buttons) also generates a ripple, though it can't do anything else.

### Expected behavior

The areas mentioned should not be tappable.

### Device info

 - Android version/Custom ROM version: Android 10 (LOS 17.1)

**Comment by TiA4f8R** [comment] 2021-06-01 10:19
Duplicate of #5600.

**Closed** 2021-06-01 10:19 UTC
Labels: user-ignored-template-instructions

**Comment by opusforlife2** [comment] 2021-06-01 14:21
I _did_ search for duplicates, but you managed to describe the problem without using the word 'report' anywhere in that issue! (╯°□°）╯︵ ┻━┻
