### ISSUE TITLE
Allow adding subscription to multiple feeds at once from channel view

### ISSUE THREAD

**Issue by gqqjhffr** [TeamNewPipe/NewPipe#8784] opened 2022-08-14 01:53 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Title says it all. Refer to the Fritter client for Twitter, itself inspired by NewPipe, for how this could work.

### Why do you want this feature?

I have many specific feeds for many specific purposes, many of which overlap. It is tedious and memory-taxing adding channels to feeds from the feed view, as opposed to picking appropriate feeds for a channel from the channel view.

**Comment by SameenAhnaf** [comment] 2022-08-14 08:35
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5836

**Closed** 2022-08-14 14:42 UTC
Labels: enhancement, needs triage
