### ISSUE TITLE
Please Add Playlist Organizer/sub folder

### ISSUE THREAD

**Issue by Pranab009** [TeamNewPipe/NewPipe#7936] opened 2022-02-23 14:42 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Please Add Playlist Organizer (File inside Folder)

If you have too many playlist then it is difficult to find correct playlist quickly.
Ex.
You have different song playlists like
Bollywood Songs
Bengali Songs
Dance Songs
Hollywood Songs
Instrumental Songs
Flock Songs
Romantic Songs
Sad Songs
Tollywood Songs
Melodic Songs
Ringtones

If this all songs playlists are shown in one place then it can be find quickly. Otherwise it all Store according A to Z. It take lot more time for find songs

Sol.
Add a Folder type or Add Sort by own.

Bollywood Songs
Bengali Songs
Dance Songs
Hollywood Songs
Instrumental Songs
Flock Songs
Romantic Songs
Sad Songs
Tollywood Songs
Melodic Songs
Ringtones

If this all saved in music folder then you can find music playlists fast and easily.

Or sort by own is possible then try to add this.

### Additional information

<img alt="Screenshot_20220223-194516_1" src="https://user-images.githubusercontent.com/65340361/155341491-a101233e-8eac-42af-8baa-816d6bb7baba.png" height=600 />

**Comment by SameenAhnaf** [comment] 2022-02-23 16:47
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1313

**Comment by Pranab009** [comment] 2022-02-23 17:03
When this feature implemented??
Please try to implemented this feature as soon as possible.

**Comment by tsiflimagas** [comment] 2022-02-23 18:30
It's a project on which people work in their free time. Requesting things in this manner sounds impolite and annoying.

**Closed** 2022-02-23 19:06 UTC
Labels: question
