### ISSUE TITLE
Fullscreening from miniplayer restarts entire video

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#7200] opened 2021-10-05 09:46 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

The video restarts itself no matter long the video has gone.

### Expected behavior

Go back into fullscreen mode, remembering the video's progress.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Galaxy S10

**Comment by mhmdanas** [comment] 2021-10-05 14:58
Duplicate of #6472.

**Closed by mhmdanas** 2021-10-05 14:58 UTC
Labels: bug
