### ISSUE TITLE
Audio/Video Desync

### ISSUE THREAD

**Issue by Raul1198** [TeamNewPipe/NewPipe#3796] opened 2020-06-19 12:47 UTC
### Version

- 0.19.5
- Pocophone Poco F1 , Android 10 , AOSP Extended (AEX)

### Steps to reproduce the bug

1. Open any video. I tested with different videos from different channels, all of them with this issue.

### Expected behavior

 The video playing nomal with the audio in sync with the video

### Actual behaviour

The video plays normally, but looking carefully, the video and audio began to go out of sync slowly (with video first). The audio is few seconds ahead of the video.

### Screenshots/Screen recordings

NA.
### Logs

 NA.

**Comment by wb9688** [comment] 2020-06-19 12:52
Duplicate of #3550

**Closed by wb9688** 2020-06-19 12:52 UTC
Labels: bug
