### ISSUE TITLE
Adding a search function to history tab

### ISSUE THREAD

**Issue by ekjames** [TeamNewPipe/NewPipe#3705] opened 2020-05-31 13:15 UTC
I was wondering if there will be the ability to search for previously watched videos is the history tab? This feature would help with the thousands of videos me and others have watched throughout the years without scrolling for a long time to find a specific video we watched years ago.

**Comment by androidSwDev099** [comment] 2020-05-31 14:22
I would find this very useful too. If it could include searching a playlist list or background player, that would be very helpful for me too.

**Comment by B0pol** [comment] 2020-05-31 14:31
Duplicate of #2977

**Closed by B0pol** 2020-05-31 14:31 UTC
Labels: enhancement
