### ISSUE TITLE
Some videos won't play, missing codec?

### ISSUE THREAD

**Issue by ravilov** [TeamNewPipe/NewPipe#2228] opened 2019-03-18 06:33 UTC
It gets as far as showing the thumbnail/description/comments screen. But when I tap on the video, it just shows the loading spinner forever. This happens consistently on Android 4.4 but seems to work on Android 7.1. Maybe a missing system codec on older Android versions? Any way to remedy this, or at least detect this condition and show a warning?

**Examples:**
- <https://www.youtube.com/watch?v=_p1wmOIPNfg>
- almost all videos from <https://www.youtube.com/channel/UCYgagfPRvQo4sQUAm4SLAnA>

--------

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by theScrabi** [comment] 2019-03-18 07:29
Can't be, the video would fail to be displayed and end up with an exception if no supported codec was supplied.

**Comment by ravilov** [comment] 2019-03-18 07:40
Any other ideas for this strange behavior? Is it perhaps possible an exception does indeed happen but ends up suppressed (via an empty `catch` block or similar), or just sent to logcat, or otherwise kept from reaching the player?

**Comment by theScrabi** [comment] 2019-03-18 09:06
It could be your android system.

**Comment by mozbugbox** [comment] 2019-03-18 13:06
It could be the hardware video decoder that cannot handle the video steam properly. Particularly when playing the `webm` format.

Try test it by setup `NewPipe` to `play with external player` and has the external player (VLC, MX player) plays online stream videos using **soft video decoder**.

**Comment by ravilov** [comment] 2019-03-19 04:47
Made some interesting discoveries.

I installed MX Player as suggested and set NewPipe to use external player. Videos that work normally in NP work just fine in MX as well, and videos that don't work in NP don't work in MX either. MX just goes through available codec categories (SW, HW, HW+) and finally displays "Cannot play this link".

Then I thought of something. My default resolution in NP is set to 480p. Just for testing I changed it to 720p. Suddenly all the videos work, both in NP and MX.

Not sure what to make of that. Still think there must be a better way to handle not being able to play a video instead of just showing the loading spinner forever. I'm leaving my default at 720p for now at least.

**Comment by theScrabi** [comment] 2019-03-19 16:06
Ah that was the missing part. Yes 420p also failes on my device.

**Comment by kuesji** [comment] 2019-03-31 09:28
same problem.
 when i select 480p as quality it is loading take too much time . at the this point 720p loading in shorter time than 480p. my network easily play 720p videos, so it's not network problem

**Comment by alexandrezia** [comment] 2019-06-18 02:31
Have this issue too, android 4.4 (honda civic head unity)

**Comment by Stypox** [comment] 2019-09-27 05:47
#2415 is probably related

**Comment by Stypox** [comment] 2020-04-27 07:17
Duplicate of #2415

**Closed by Stypox** 2020-04-27 07:17 UTC
Labels: bug, requires extractor change
