### ISSUE TITLE
Subscription Order

### ISSUE THREAD

**Issue by fnkwuweh** [TeamNewPipe/NewPipe#739] opened 2017-09-25 20:31 UTC
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=49721213)](https://www.bountysource.com/issues/49721213-subscription-order?utm_source=49721213&utm_medium=shield&utm_campaign=ISSUE_BADGE)

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Love the new Local Subscriptions feature. However, the "what's new" feed does not display videos in chronological order and random reorganises the feed on restarting the app.

**Comment by mauriciocolli** [comment] 2017-09-25 20:53
Try to open the /videos page of any channel, you'll notice that YouTube doesn't show the date on those, only an approximation of it, that's the most "complicated" part to make it work (which is not that hard).

If we base the information on those, it'll not be order by the exact time of upload, but when you enter a video, it will be the exact date (because then, YouTube give us). Do you find this acceptable? (or even just better than now?)

##### At the moment, we are working on some high-priority features (like playlists), but I think someone will work on it soon.

**Comment by SweepJegus** [comment] 2017-09-26 00:45
I think a good solution would be to replace showing individual videos with groups by channel in alphabetical/anti-alphabetical order showing the several most recent videos of the channel, which YouTube does show you on their channel page.

**Comment by Lionirdeadman** [comment] 2017-10-04 18:52
Shouldn't we use the RSS feeds to determine the date and order the videos should be in? Take all the RSS feeds from the subscriptions and just put them there. Wouldn't that make it much easier and allow more control?

**Comment by tkosamja** [comment] 2017-10-09 21:35
Is anyone working on this? It would be really useful and I've been excited about a subscription feed.

**Comment by theScrabi** [comment] 2017-10-10 07:33
The problem is that rss only works on users not on channles. So rss is not a solution we can generally relay on.

**Comment by stemy2** [comment] 2017-11-23 18:02
I know this is technically possible. The SkyTube app does it very well, you can have the videos of your subscriptions chronologically sorted. Maybe you should study its method to do the same.

**Comment by theScrabi** [comment] 2017-11-23 19:37
In my opinion that subscription thing should be reworked anyway.  So it behaves more like a rss feed reader.

**Comment by avently** [comment] 2017-12-01 16:38
@mauriciocolli seems like you can get time from rss even for channels
Example https://www.youtube.com/feeds/videos.xml?channel_id=UCz9iqx91UzlKg-WbBnlOR2g

**Comment by theScrabi** [comment] 2018-06-03 20:02
I'm going to mark this as duplicate in favour of https://github.com/TeamNewPipe/NewPipe/issues/1448. I'll keep it open for the bounty tho. However please put any discussion to #1448.

**Comment by krmax44** [comment] 2018-09-16 09:47
> The problem is that rss only works on users not on channles. So rss is not a solution we can generally relay on.

It's easy to get a user's channel id though. For example: https://youtube.com/user/krmax44 has the channel id available in multiple locations:

```html
<link rel="canonical" href="https://www.youtube.com/channel/UC8wnw_JpwQhBHwEGv-bLZSA">
<meta property="og:url" content="https://www.youtube.com/channel/UC8wnw_JpwQhBHwEGv-bLZSA">
```
It would be very easy to parse these and to then use the rss feeds that include the exact timestamps.

**Comment by theScrabi** [comment] 2018-09-18 16:58
Yes but there are channels for which no iser exists like dong.

**Comment by krmax44** [comment] 2018-09-19 13:44
> 
> 
> Yes but there are channels for which no iser exists like dong.

Do you mean this channel? https://www.youtube.com/channel/UClq42foiSgl7sSpLupnugGA

**Comment by PureTryOut** [comment] 2018-12-01 12:18
Well, closing this would be wrong, as this is still a severely wanted feature.

**Comment by infinitytec** [comment] 2019-03-06 22:57
This would be useful for me.

**Comment by MajdA1** [comment] 2019-07-18 20:58
Any updates on this? This is the only feature that's stopping me from switching all together

**Comment by nkvname** [comment] 2019-10-15 08:30
Hmmm... someone started already on this issue, but it's still in progress? https://www.bountysource.com/issues/49721213-subscription-order?utm_source=49721213&utm_medium=shield&utm_campaign=ISSUE_BADGE

**Comment by TobiGr** [comment] 2019-10-15 10:12
@MajdA1 See my https://github.com/TeamNewPipe/NewPipe/issues/2715#issuecomment-541343034. #2309 is under active development, review and testing.

**Closed** 2020-03-14 17:15 UTC
Labels: bounty, duplicate, enhancement
