### ISSUE TITLE
Video full screen 30% of the time bugging

### ISSUE THREAD

**Issue by Vizznet** [TeamNewPipe/NewPipe#8912] opened 2022-08-30 21:11 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Click on a video
2. Go in full screen

### Expected behavior

The screen being filled up

### Actual behavior

30% of the time only a quarter of the screen is filled up with video. To fix it I have to go out of full screen mode and go back into it everytime it happens.

### Screenshots/Screen recordings

![Screenshot_20220830-230716_NewPipe](https://user-images.githubusercontent.com/71229122/187543497-ee8788df-e7e2-4f2e-ad12-9b5e2f6faa74.jpg)

### Logs

-

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung galaxy s10e

### Additional information

-

**Comment by AudricV** [comment] 2022-08-30 21:24
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #7262. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2022-08-30 21:24 UTC
Labels: bug, needs triage
