### ISSUE TITLE
Enqueueing Videos from a Playlist enqueues the whole playlist

### ISSUE THREAD

**Issue by AnonymousSeal** [TeamNewPipe/NewPipe#7235] opened 2021-10-12 22:12 UTC
### Checklist

- [x] I am using the latest version - 0.21.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to your Playlists
2. Open one
3. Select a video (long press)
4. Click Start Playing in background
5. Now enter the player queue through the notification

### Actual behavior

The whole playlist is enqueued.

### Expected behavior

Only this one video should be enqueued

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by SameenAhnaf** [comment] 2021-10-13 00:30
Duplicate of #5677.

**Closed** 2021-10-13 06:57 UTC
