### ISSUE TITLE
WIP

### ISSUE THREAD

**Issue by Djfe** [TeamNewPipe/NewPipe#1233] opened 2018-03-31 17:43 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [] I checked if the issue/feature exists in the latest version.

This is my feedback for now, just some ideas on how this app could be improved :)
I used it for one day and I like it already.
This issue is **WIP** for now, because I'm out of time. (just some notes)
I plan on separating it into small issues later today (and search whether such issues exist already).
I promise this will look prettier soon ^^ (my apology for ignoring the guidelines for now)

The feed is not very useful (especially) after importing my youtube subscriptions, it only displays the last video of an account and it does that even for 3 year old videos.
It should be sorted somehow as well.

The search should be sortable (upload date and all the other options available on youtube)

The player should remember, where you left off (for like a week or so).

It should remember your queue even when you restart the app.

It should stop you from adding something to a playlist if it's already part of that playlist (opt-in?)

You should be able to switch from background player to main player (with video).
(same for pop-up player)
Maybe with a button in the gui or in the notification bar.
Since background player and the foreground player don't share the same queue that might get difficult to achieve atm.
Both queues should be included in the bookmarks page.

It would be nice to set a playlist to auto-download, so it's always available offline.
(in addition to choosing audio only or with video)

The app should allow us to see reposts of tracks (soundcloud) of an artist/reposts of videos of an account on youtube. (also likes/following of soundcloud accounts)
Same goes for playlists/albums.

Playlists/albums adding to queue/app playlist.
view playlists/uploads/likes/following etc. from your own youtube/soundcloud account

If you are on the details page of a youtube video: show playlists below of that account, that contain this video (maybe with limits) -> could be useful for let's play playlists or music albums

german translation: "seeking" is "spulen" not "suchen" (I'll take a look at weblate soon)

Why does the background player have two buttons both for playback speed?

Display account description of the youtube/soundcloud account and maybe when the account was created

display links to other accounts of that account (facebook, twitter etc.)

remember download settings so that one button press is enough

define how many downloads at the same time (for example max. 1)
pause whole download queue at once button

maybe also:
other channels of that account/other channels that the account recommends
The community tab
Display thumbnail/cover on home screen when background player is active.

**Comment by karyogamy** [comment] 2018-03-31 19:51
I'll cover some of the points, but for many of the issues, the answer is simply that we don't have enough people and resources to work on them. Also, this issue will likely just get closed since we expect only one issue per problem and many of the issues pointed out here have already been mentioned.

> The feed is not very useful

This is being worked on #1044

> The search should be sortable (upload date and all the other options available on youtube)

See #110

> The player should remember, where you left off (for like a week or so).

This is already implemented, someone just has to add a confirmation UI to let users make the decision to seek.

> It should remember your queue even when you restart the app.

Noted. Though right now it isn't very clear on how the behavior should be, since we can have multiple players (background/fullscreen/popup) simultaneously, how should the queue for each players be remembered? Maybe we will come back to this after having consolidated the players into a single one.

> It should stop you from adding something to a playlist if it's already part of that playlist (opt-in?)

Discussed in #1004. 

> You should be able to switch from background player to main player (with video).

Start a background stream. Click on the notification to open the play queue. Click on the three dots on top right. Switch to main player.

> It would be nice to set a playlist to auto-download, so it's always available offline.

See #1161 #1180 

> The app should allow us to see reposts of tracks (soundcloud) of an artist/reposts of videos of an account on youtube. (also likes/following of soundcloud accounts)

Not sure what you mean by this, can you please clarify?

> Playlists/albums adding to queue/app playlist.

This can be done but can have unexpected behavior when the 

> view playlists/uploads/likes/following etc. from your own youtube/soundcloud account

I don't think we will be supporting sign on anytime soon. See #329

> Why does the background player have two buttons both for playback speed?

Left is for tempo and right is for pitch. Speed changing UI will be more fleshed out in the new release.

**Comment by theScrabi** [comment] 2018-03-31 20:42
Hello @Djfe .You did some work here which is great, but aome of the issues you listed here are already known to us and are duplicates. Also we have the rulw here that qe creafe one issue at a time in order to be able to track and discuss that issue better. Im therfore closing this one here. However you brought some good points so if you find time again it was awesome if you opened those issues :)

**Closed** 2018-03-31 20:42 UTC
