### ISSUE TITLE
NullPointerException / org.schabi.newpipe.player.playqueue.PlayQueue.getIndex()

### ISSUE THREAD

**Issue by Massedil** [TeamNewPipe/NewPipe#6230] opened 2021-05-03 20:17 UTC
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Don't know how to reproduce.

### Actual behaviour

Crash of the app.

### Expected behavior

No crash.

### Logs

```
{"user_action":"ui error","request":"ACRA report","content_language":"fr","content_country":"FR","app_language":"fr_FR","service":"none","package":"org.schabi.newpipe","version":"0.21.2","os":"Linux Android 10 - 29","time":"2021-05-03 17:26","exceptions":["java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.getIndex()' on a null object reference\n\tat org.schabi.newpipe.player.Player.onCompleted(Player.java:2154)\n\tat org.schabi.newpipe.player.Player.changeState(Player.java:1993)\n\tat org.schabi.newpipe.player.Player.onPlayerStateChanged(Player.java:1913)\n\tat com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$13(ExoPlayerImpl.java:1052)\n\tat com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$eAKzukwdd6P91AoYEF8JC1HDnJ4.invoke(Unknown Source:4)\n\tat com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:297)\n\tat com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:184)\n\tat com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)\n\tat com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:205)\n\tat com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1101)\n\tat com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:333)\n\tat com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1268)\n\tat com.google.android.exoplayer2.DefaultControlDispatcher.dispatchPrepare(DefaultControlDispatcher.java:57)\n\tat com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onPlay(MediaSessionConnector.java:1156)\n\tat android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onPlay(MediaSessionCompat.java:1614)\n\tat android.media.session.MediaSession$Callback.onMediaButtonEvent(MediaSession.java:920)\n\tat android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onMediaButtonEvent(MediaSessionCompat.java:1604)\n\tat android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1578)\n\tat android.os.Handler.dispatchMessage(Handler.java:107)\n\tat android.os.Looper.loop(Looper.java:214)\n\tat android.app.ActivityThread.main(ActivityThread.java:7356)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)\n"],"user_comment":""}
```

### Device info

 - Android version/Custom ROM version: LineageOS 17.1 / Android 10
 - Device model: Samsung Galaxy S5

**Comment by TiA4f8R** [comment] 2021-05-05 16:12
By looking at the stack trace, I think you can reproduce the crash by following the steps described in #6233. Closing as a duplicate of it, because it has more informations than your issue.

**Closed by TiA4f8R** 2021-05-05 16:12 UTC
Labels: bug
