### ISSUE TITLE
Support links to /hashtag youtube URLs

### ISSUE THREAD

**Issue by Vrihub** [TeamNewPipe/NewPipe#10948] opened 2024-04-05 15:17 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

Links to YouTube /hashtag URLs in video descriptions should be supported.

Example video: https://www.youtube.com/watch?v=Ok05GFoESGE

See at the end of the video description the #LATITY link leading to: https://www.youtube.com/hashtag/latity

### Expected behavior

Such links should be opened in newpipe, like regular "tags" already do

### Actual behavior

Links are opened via the default web browser

**Comment by AudricV** [comment] 2024-04-05 16:47
It's not a bug, it's a feature request which requires extractor support. Closing as a duplicate of #10549.

**Closed by AudricV** 2024-04-05 16:47 UTC
Labels: bug, needs triage
