### ISSUE TITLE
Videos zoomed in by default now (20.10).

### ISSUE THREAD

**Issue by imfinnanut** [TeamNewPipe/NewPipe#5633] opened 2021-02-18 17:50 UTC
Videos now appear zoomed in rather than fill by default now. I really dislike this change. I do not like using the zoom option because it crops part of the video. Now I have to undo this every time I watch a video.

Could we please change this back or at least have an option to choose your default viewing experience?

**Comment by litetex** [comment] 2021-02-18 18:45
Looks like a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5613

**Comment by mhmdanas** [comment] 2021-02-19 07:31
This seems like a duplicate of #5613, as @litetex suggests.

**Closed by mhmdanas** 2021-02-19 07:31 UTC
