### ISSUE TITLE
A random bug report, Idrk how it happened 

### ISSUE THREAD

**Issue by d4f5409d** [TeamNewPipe/NewPipe#6658] opened 2021-07-14 07:44 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ 
* __Content Language:__ 
* __App Language:__ 
* __Service:__ none
* __Version:__ 0.21.5
* __OS:__ Linux Android 11
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7080)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-07-14 11:13
Duplicate of #4475. Please fill in the template when opening an issue.

**Closed by mhmdanas** 2021-07-14 11:13 UTC
Labels: bug

**Comment by d4f5409d** [comment] 2021-07-14 11:25
I did not know how it happened sorry
