### ISSUE TITLE
Error Peertube

### ISSUE THREAD

**Issue by ICantInstall** [TeamNewPipe/NewPipe#8395] opened 2022-05-13 16:24 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

It just crashed and I wanna dump it here

### Expected behavior

Play Video in peertube

### Actual behavior

The APP crashes

### Logs

{"user_action":"ui error","request":"ACRA report","content_language":"en-US","content_country":"US","app_language":"en_US","service":"none","package":"org.polymorphicshade.newpipe","version":"0.23.0","os":"Linux Android 12 - 31","time":"2022-05-13 18:18","exceptions":["java.lang.NumberFormatException: For input string: \"\"\n\tat java.lang.Integer.parseInt(Integer.java:627)\n\tat java.lang.Integer.parseInt(Integer.java:650)\n\tat org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:502)\n\tat org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:517)\n\tat org.schabi.newpipe.util.ListHelper.$r8$lambda$UGNhfSv5KuYwsqrcThyeG189sI0(Unknown Source:0)\n\tat org.schabi.newpipe.util.ListHelper$$ExternalSyntheticLambda2.compare(Unknown Source:4)\n\tat java.util.Collections$ReverseComparator2.compare(Collections.java:5235)\n\tat java.util.TimSort.binarySort(TimSort.java:296)\n\tat java.util.TimSort.sort(TimSort.java:221)\n\tat java.util.Arrays.sort(Arrays.java:1492)\n\tat java.util.ArrayList.sort(ArrayList.java:1470)\n\tat java.util.Collections.sort(Collections.java:206)\n\tat org.schabi.newpipe.util.ListHelper.sortStreamList(ListHelper.java:279)\n\tat org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:253)\n\tat org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:140)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1638)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6(VideoDetailFragment.java:926)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$X-UcNln23jPsop2TvHe2VPTu0NQ(Unknown Source:0)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda12.accept(Unknown Source:8)\n\tat io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)\n\tat io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)\n\tat android.os.Handler.handleCallback(Unknown Source:2)\n\tat android.os.Handler.dispatchMessage(Unknown Source:4)\n\tat android.os.Looper.loopOnce(Unknown Source:176)\n\tat android.os.Looper.loop(Unknown Source:76)\n\tat android.app.ActivityThread.main(Unknown Source:138)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)\n\tat com.android.internal.os.ZygoteInit.main(Unknown Source:306)\n"],"user_comment":""}

### Affected Android/Custom ROM version

Android 12/ Xiaomi.eu 13.0.5

### Affected device model

Xiaomi Mi 11 Ultra

**Comment by TiA4f8R** [comment] 2022-05-13 19:21
> ### Affected version
> 
> 0.23.1

You're seeing in future :o. The latest version is 0.23.0, as you can see in the crash report the app generated.

> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

You didn't, please search (better, with different keywords maybe?) the next time you want to open an issue, because it's a duplicate of #6860. A fix is already available in the pull request linked in the issue.

Thank you.

**Closed by TiA4f8R** 2022-05-13 19:21 UTC
Labels: bug
