### ISSUE TITLE
endless loop trying to report for something get wrong

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#5040] opened 2020-11-30 05:38 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Ttry to reproduce  #5039
2. Press Report

### Actual behaviour

endless loop

### Expected behavior

no error

### Screenshots/Screen recordings

![ScreenRecord-2020-11-30-08-36-52](https://user-images.githubusercontent.com/14617699/100572800-6cda1d80-32e7-11eb-9add-ba915e1eec60.gif)

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment] 2020-11-30 06:47
Duplicate of #5017. 

Also, please follow the template's instructions when opening issues. This is your second issue that is a duplicate and you also didn't specify your device info.

**Closed by mhmdanas** 2020-11-30 06:47 UTC
Labels: bug

**Comment by 532910** [comment] 2020-11-30 14:32
> follow the template's

Have you ever filled this over-bloated template from mobile browser?

> your second issue that is a duplicate

0. It doesn't mean that I have NOT checked. I HAVE checked but didn't find any duplicates. There is no contradiction here.
1. I believe the dup is better than nothing.
2. If you require users to follow the template, you should follow it yourself. https://github.com/TeamNewPipe/NewPipe/issues/created_by/Stypox

**Comment by mhmdanas** [comment] 2020-11-30 14:45
> Have you ever filled this over-bloated template from mobile browser?

Is it that difficult to revise your issue so that you didn't forget to fill something? Also, it is "over-bloated" because we need it to contain as much relevant information and context as possible.

> It doesn't mean that I have NOT checked. I HAVE checked but didn't find any duplicates. There is no contradiction here.

Then put in some more effort please.

> I believe the dup is better than nothing.

Duplicates bloat the issue tracker and take up triagers' time. They are actually worse than nothing.

> If you require users to follow the template, you should follow it yourself. https://github.com/TeamNewPipe/NewPipe/issues/created_by/Stypox

Every single issue @Stypox opened that didn't follow the template was opened before the template was introduced.

**Comment by 532910** [comment] 2020-11-30 14:58
> Is it that difficult

Yes. It is difficult to revise it due to a lot of text that doesn't fit mobile screen! It's difficult to erase space in `[ ]` to put `x` there. It's difficult to read useless sentences like "Oh no, a bug! It happens. Thanks for reporting an issue with NewPipe." for example.

> only recently started to strictly enforce the policy of following the template

This is not true: https://github.com/TeamNewPipe/NewPipe/issues/4931

**Comment by mhmdanas** [comment] 2020-11-30 15:00
> Yes. It is difficult to revise it due to a lot of text that doesn't fit mobile screen! It's difficult to erase space in [ ] to put x there. It's difficult to read useless sentences like "Oh no, a bug! It happens. Thanks for reporting an issue with NewPipe." for example.

Maybe you could open an issue from a computer instead then? Then it will be easier for both of us.

> This is not true: #4931

That one appears to have slipped through the cracks. I'll close it.

**Comment by 532910** [comment] 2020-11-30 15:06
> from a computer

Please, don't tell people to use desktop instead of mobile and they will love you.

**Comment by mhmdanas** [comment] 2020-11-30 15:06
I'm only making a suggestion. You can user whatever you want.

**Comment by TheAssassin** [comment] 2020-11-30 16:34
This issue has been closed rightfully, in accordance to our guidelines. If you want it to be reopened, fill in the template, then post a follow-up comment.

> This is not true: #4931

"But the maintainers don't follow the template either!!!!111!!1" Well, great argument! It makes a lot of sense to compare your annoyingly information-free report to one single issue written by a maintainer who's anyway going to work on it. Really proves you are the good guy, and the devs are the bad ones!

> Have you ever filled this over-bloated template from mobile browser?

"Over-bloated"? Really? It just asks for the minimum information required to work on your issue. It's very arrogant from you to expect devs to figure out what goes wrong in your case (might be very hard to reproduce even!). It's really your job to provide sufficient information.

Just fill in the template. If you can't do it on mobile, do it on a computer. If you are not willing to invest the time necessary to provide a meaningful, useful bug report, then consider *not* creating further of these. You can hardly blame the maintainers for requiring standards to be followed, given the huge amount of issues they have to handle.

> It doesn't mean that I have NOT checked. I HAVE checked but didn't find any duplicates. There is no contradiction here.

If it takes a dev not even 1 minute to find a duplicate, the question is why it is so hard for you? You can't decline that it does indeed sound like you didn't have a look at all, especially since this is the second time it occurs.

> I believe the dup is better than nothing.

One could see it like this, too: nothing is better since it reduces the workload. A normal issue increases the workload, a duplicate increases it even further.

Seriously, just try to be more helpful. Otherwise, you will not be taken seriously.
