### ISSUE TITLE
Short press on thumbnail without opening the video should directly enter full screen

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6211] opened 2021-05-01 04:19 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Full screen is the most natural way for playing videos. Playing video on full screen is kinda a hassle at least for now. In many (not all) cases, video is the only thing I need. That's why, single tap on thumbnail should be added for entering full screen even without opening the video.

#### How will you/everyone benefit from this feature?

There are many users who only needs the video. Personally, I hardly require description or other stuff and getting directly into full screen is a hassle at least for now. A direct gesture would tremendously help us.

Yes, there's a #5459 on this topic. But you need to double tap (First on title bar, second on thumbnail, plus the buffering lag ugh!) unnecessarily for most videos. If someone needs main player, he can do so by clicking on title bar. As I stated earlier, I need main player only when required.

**Comment by SameenAhnaf** [comment] 2021-05-08 07:52
@SameenAhnaf

**Comment by mhmdanas** [comment] 2021-07-31 11:52
Duplicate of #4152.

**Closed by mhmdanas** 2021-07-31 11:52 UTC
Labels: GUI, enhancement
