### ISSUE TITLE
Repeatedly crashing with specific app data stored (IllegalArgumentException)

### ISSUE THREAD

**Issue by unresolvedsymbol** [TeamNewPipe/NewPipe#6797] opened 2021-07-29 05:54 UTC
### Checklist

- [x] I am using the latest version - 0.21.7 (build 973) 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
See video: https://files.catbox.moe/kraxe3.mp4
Have successfully reproduced this multiple times, seems to be along the lines of enqueuing a video then scrubbing to the end, beginning, and pausing.

### Resolve bug
Done by deleting files under shared_prefs (root required)

Stacktrace:
```
FATAL EXCEPTION: Thread-4
Process: org.schabi.newpipe, PID: 28929
java.lang.IllegalArgumentException: No such service ComponentInfo{org.schabi.newpipe/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.java:62)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.java:66)
	at org.acra.startup.StartupProcessorExecutor.lambda$null$0(StartupProcessorExecutor.java:86)
	at org.acra.startup.StartupProcessorExecutor.lambda$null$0$StartupProcessorExecutor(Unknown Source:0)
	at org.acra.startup.-$$Lambda$StartupProcessorExecutor$vr-B3Kby1WTBs7c-61N3dOEKizo.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

```

### Device info

 - Android version/Custom ROM version: crDroid 7.8 (A11)
 - Device model: OnePlus 7 Pro (SD855)

**Comment by mhmdanas** [comment] 2021-07-29 12:45
Do you perhaps have NewPipe installed on an external storage card?

> More information can not be obtained at the moment as I'd rather not loose my data.

You can back up all your data by pressing Settings > Content > Export database. You can then import it back by pressing Settings > Content > Import database.

**Comment by unresolvedsymbol** [comment] 2021-07-29 18:08
@mhmdanas It's on unencrypted internal storage. I cannot access settings. I have root though, how might I go about generating newpipe.settings from the xml in the app data?

**Comment by unresolvedsymbol** [comment] 2021-08-04 19:00
Turns out the crash is not caused by anything in newpipe.db, I tested this by extracting newpipe.db and manually creating a backup zip after reproducing the crash then clearing data and importing it to no avail.
@mhmdanas I've determined the data causing the crash is actually stored in the shared preference XML, deleting these files after reproducing the crash resolves the persistent crashing but backing up the "broken" files and putting them back does not recreate it. Reproduction video with clean data: https://files.catbox.moe/kraxe3.mp4 Excuse the absolute shit compression that Android 11's internal screen recorder did.

**Comment by hagen-tronje** [comment] 2021-08-08 20:40
-I use A11 on standard Samsung A71, langruage english, 0.21.8,
The crash happens  since 0.21.6.
0.21.5 worked
Once I hit the download button this chash report shows.
-------------------------------
---
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4619)
	at android.app.ActivityThread.access$1600(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4607)
	... 8 more
-------------------------------------

**Comment by mhmdanas** [comment] 2021-08-08 21:20
@hagen-tronje see #6687. The issue should be fixed in 0.21.9.

**Comment by r3muxd** [comment] 2021-11-12 04:53
still not fixed, happening to me on a11

**Comment by unresolvedsymbol** [comment] 2021-11-12 22:52
> still not fixed, happening to me on a11

Sorry I have not determined what tag in shared_perfs is causing the bug but deleting it seems to fix it for now at the loss of settings.  At least history and subs aren't deleted.

**Comment by randoentity** [comment] 2023-08-12 06:49
I don't know if this is the same issue as I'm having, namely the app crashing on startup until the app data is deleted, but based on the above I found an alternative fix, albeit a bit of a buckshot at the moment. 
I first tried starting with airplane mode on, but that didn't help. Then I tried starting activities directly with io.github.muntashirakon.AppManager (available through F-Droid) and got the standard error report activities. I allowed trackers just in case and then I turned off a bunch switches in app ops and user permission. Not the most scientific method, but I'll narrow it down next time it happens.

**Comment by ShareASmile** [comment] 2024-02-17 19:25
Is it still an issue on 0.26.1?

**Comment by randoentity** [comment] 2024-02-18 15:31
I had it a couple of weeks ago. All I had to do was use AppManager to launch an activity (just the main activity IIRC) and it worked normally again. I get that this information isn't very useful. I'll try to report it here next time it happens.

**Closed** 2024-03-06 00:12 UTC
Labels: bug, waiting for author
