### ISSUE TITLE
No result for search YouTube Music

### ISSUE THREAD

**Issue by reno-a** [TeamNewPipe/NewPipe#6810] opened 2021-07-30 20:55 UTC
_Version NewPipe 2.21.7 / F-Droid_

The search works by default.
The same goes for the Video search.
But, searching by the YouTube Music item does not give any result.

**Comment by botistreamer** [comment] 2021-07-31 04:15
Fill the bug reporting template properly

**Comment by reno-a** [comment] 2021-07-31 05:40
Bug repport is difficult, english ils not my language.I'm sorry. Best regard.---R. AIGOINLe 31 juil. 2021 06:15, botistreamer ***@***.***> a écrit :
Fill the bug reporting template properly

**Comment by PerryLiu4427** [comment] 2021-07-31 07:55
I have the same problem tooಠ_ಠ

**Comment by TiA4f8R** [comment] 2021-07-31 14:29
@reno-a Il n'y a aucun problème, je comprends tout à fait cette difficulté. N'hésitez pas à traduire le modèle en français la prochaine fois que vous ouvrez un ticket.

English version: @reno-a No problem, I fully understand this difficulty. Don't hesitate to translate the template in French the next time you open an issue.

We are aware of the issue and a PR has been opened to fix the bug: TeamNewPipe/NewPipeExtractor#699

**Comment by TiA4f8R** [comment] 2021-08-04 10:25
Can you confirm that the issue is fixed with the 0.21.8 version?

**Comment by PerryLiu4427** [comment] 2021-08-04 11:08
Yes, it's fixed in newest version, thanks for help!

TiA4f8R ***@***.***> 於 2021年8月4日 週三 下午6:25 寫道：

**Comment by TiA4f8R** [comment] 2021-08-04 11:10
Thanks for confirming @PerryLiu4427! The issue is also solved for me, so I am closing this issue.

**Closed by TiA4f8R** 2021-08-04 11:10 UTC
Labels: bug, requires extractor change, youtube

**Comment by reno-a** [comment] 2021-08-04 11:12
Yes, the  0.21.8 version solve the problem.
Thank-you. Best.
--
R. AIGOIN

**Comment by reno-a** [comment] 2021-08-04 11:14
> Can you confirm that the issue is fixed with the 0.21.8 version?

Yes, the  0.21.8 version solve the problem.
Thank-you. Best.
