### ISSUE TITLE
Crash when resolution set to best possible on certain vids.

### ISSUE THREAD

**Issue by SlavTiger** [TeamNewPipe/NewPipe#4348] opened 2020-09-29 05:36 UTC
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux motorola/james_a/james:8.0.0/OCP27.91-157-28/2:user/release-keys 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4500)
	at org.schabi.newpipe.player.helper.PlayerHelper.autoQueueOf(PlayerHelper.java:165)
	at org.schabi.newpipe.player.BasePlayer.maybeAutoQueueNextStream(BasePlayer.java:1336)
	at org.schabi.newpipe.player.BasePlayer.maybeUpdateCurrentMetadata(BasePlayer.java:1320)
	at org.schabi.newpipe.player.BasePlayer.onTimelineChanged(BasePlayer.java:677)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$0$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:804)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$N_S5kRfhaRTAkH28P5luFgKnFjQ.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:802)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6797)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)

```
</details>
<hr>

**Comment by opusforlife2** [comment] 2020-09-29 05:41
Can you give examples of such videos so we can try them?

**Comment by opusforlife2** [comment] 2020-09-29 05:43
Also, can you confirm that your issue is not a duplicate of #4112?

**Comment by SlavTiger** [comment] 2020-09-29 05:47
I hate to put you through this but the earrape video "scotland forever" by youtuber glitchy1 crashes the app entirely on two different android phones I have tried. Again I'm not putting that to be funny but it legitimately crashes the app for some reason after changing resolution settings. Enabling external video player will prevent the crash but remove audio. I was playing random stuff trying out the app when I ran into this.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by SlavTiger** [comment] 2020-09-29 05:48
So far "scotland forever" is the only video to consistently crash the app on both a j327 and a moto e5 cruize.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by opusforlife2** [comment] 2020-09-29 06:10
Tested. Duplicate of #4112.

**Closed by opusforlife2** 2020-09-29 06:10 UTC
Labels: bug

**Comment by SlavTiger** [comment] 2020-09-29 06:16
Wasn't sure. Thanks for verifying.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
