### ISSUE TITLE
Automatic video quality setter

### ISSUE THREAD

**Issue by MatsG23** [TeamNewPipe/NewPipe#8923] opened 2022-09-02 18:52 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I think of NewPipe adapting to the available network speed by automatically setting a higher or lower video quality (like in the official YT app).

### Why do you want this feature?

In some networks, videos often stop to load the next bits. You have to play around with the video quality and find a one that can be played without stuttering.

**Comment by SameenAhnaf** [comment] 2022-09-03 02:09
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5323

**Closed** 2022-09-03 16:21 UTC
Labels: enhancement, needs triage
