### ISSUE TITLE
Playback Speed Goes Back to Default Speed - User Needs to Change it Everytime

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#2843] opened 2019-12-05 13:57 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

First, thank you very much for supporting the app. I mean what an awesome work you have done that I am eternally grateful. I just have one request here.

Speed settings of a video gets reset to default unlike the ability to have a user selected resolution for each video. For example, a customized speed of 1.25x gets changed into 1x automatically.

Hope this gets soon implemented. Again, thank you for the efforts you have put in!

**Comment by Stypox** [comment] 2019-12-08 19:56
Duplicate of #1536

**Closed by Stypox** 2019-12-08 19:56 UTC
