### ISSUE TITLE
Video sort by

### ISSUE THREAD

**Issue by lawson85** [TeamNewPipe/NewPipe#4449] opened 2020-10-08 14:04 UTC
### Checklist

- [ ] I checked, but didn't find any duplicates of this issue in the repo. I have seriously checked
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request. Yes

#### Describe the feature you want

I want to be able to show search results in order of most recently uploaded

#### How will you/everyone benefit from this feature?

Everybody will benefit because they will not have to waide through all the obsolete rubbish

**Comment by Stypox** [comment] 2020-10-08 14:09
This is a duplicate of an issue you would have found if you searched for it

**Closed by Stypox** 2020-10-08 14:09 UTC
Labels: enhancement

**Comment by opusforlife2** [comment] 2020-10-08 14:21
The checklist is meant for you to go through and do. It's not decoration, mate. xD
