### ISSUE TITLE
Brightness Gesture doesn't follow device brightness

### ISSUE THREAD

**Issue by DanGLES3** [TeamNewPipe/NewPipe#1838] opened 2018-10-23 01:48 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

If i change brightness with gestures the brightness starts all the way down instead of following the device brightness set prior to watching the video

**Comment by micrus** [comment] 2018-10-27 15:40
Same here, every videos start with brighteness alla the way down and there is no way to bright it up. Any workaraound?

**Comment by epitron** [comment] 2018-10-28 20:14
I've noticed this as well. If it's hard to get the device's brightness, a better starting value would be 50%, rather than 0%.

**Comment by Stypox** [comment] 2019-08-28 18:17
Duplicate of #1456

**Closed by Stypox** 2019-08-28 18:17 UTC
