### ISSUE TITLE
filter by days and year in youtube search  result excite in m.youtube.com websites.

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#3125] opened 2020-02-22 05:21 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
![Screenshot_20200222-103143_Chrome](https://user-images.githubusercontent.com/46952207/75086915-da3e6e00-555f-11ea-9e61-bb751da8af21.jpg)
![Screenshot_20200222-103150_Chrome](https://user-images.githubusercontent.com/46952207/75086917-e1fe1280-555f-11ea-948c-540e2e1e9de6.jpg)

also filter in youtube.com site filters by date and years like these image's.. ^^^

**Comment by Stypox** [comment] 2020-02-22 08:56
Duplicate of #110 and #2251

**Closed by Stypox** 2020-02-22 08:56 UTC
