### ISSUE TITLE
Release 0.22.0

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#7857] opened 2022-02-11 14:39 UTC
# APKs for testing

[NewPipe_v0.22.0_RC4.zip](https://github.com/TeamNewPipe/NewPipe/files/8100964/NewPipe_v0.22.0_RC4.zip)

## ONLY REPORT NEW BUGS IN THIS ISSUE!
Corresponding PR: #7858
# Known Issues / ToDo:
- [x] (minor) fast forward / rewind text in player not centered vertically #7731

# Changelog
### New
35 - New Fast Forward/Rewind behavior #4833
36 - Searchable Preferences / Settings #7586 
13 - Highlight pinned comments as such #7577
2 - Add FSFE-Tube PeerTube instance #7481

### Improved
5 - Unify error reporting and add error notification #7482
6 - Show an alert dialog when no appropriate file manager was found #7452
19 - Do not repeatedly say "Video preview thumbnail" when in reader mode #7619 
37 - Increase playlist stuck target duration coefficient and catch `BehindLiveWindowExceptions` properly #7661 

### Fixed
4 - Fix order of local search results #7491 
8 - Respect cutouts when playing in MultiWindow #7451 
10 - Fixes hashtags that use non-English characters. #7556 
11 - Fix readme link #6855 
15 - Fixes view of sub-channel icon when not in use #7582 
17 - Fixed search not accepting key input after closing player overlay #7607
18 - Load full stream info before using a stream, fixing empty fields in play queue #7036
22 - Fix crash when sharing a playlist which is loading #7662 
23 - Workaround: Set recovery before switching player #7668
28 - Add app icon to fastlane metadata #7672 
29 - Always show playing in background/popup toast #7614, reverting #7224 and #7568
32 - Fix first item always played in the play queue when reloading play queue manager #7693 
33 - Load uploader url when showing channel details from play queue #7538 
41 - Fix crash when long-pressing stream while player is starting #7704 

### Development
1 - Update/Fix "Get it on F-Droid" #7498 
3 - Bump ktlint, Checkstyle, Java version #7500 ⚠️ The app requires now Java 11 to be built
7 - Update a bunch of libraries #7499 
9 -  Readd sonar CI job #7552 
12 - Small improvements to code quality and readability #7562 
14 - Update NewPipeExtractor #7589 
20 - CI: Upload test-report when an error occurs #7636 
21 - Replace JUnit asserts with AssertJ in HistoryRecordManagerTest #7654 
24 - Fix false warning #7648
25 - Add traditional Chinese README #7618
26 - Some untranslatable string improvements #7317 
27 - Ensure order of search history entries in tests #7670 
30 - Sync weblate #7689 
31 - Fix some gradle deprecations #7678 
34 - Improve HistoryRecordManager tests #7700
38 - Move translated READMEs to subfolder #7784
39 - Update FUNDING.yml #7682
40 - Small changes to license section of README #7710
42 - Add some stuff to paths-ignore #7803 

### Fixed
2- Disabled ``SoundcloudStreamExtractorTest#SoundcloudGeoRestrictedTrack#testRelatedItems`` as it's unreliable TeamNewPipe/NewPipeExtractor#761
4 - [YouTube] parse timestamps with >3 digits correctly TeamNewPipe/NewPipeExtractor#775 

### Development
1 - Bump spotbugs-annotations from 4.5.0 to 4.5.3 TeamNewPipe/NewPipeExtractor#759 TeamNewPipe/NewPipeExtractor#764 TeamNewPipe/NewPipeExtractor#772 
3 - Cleanup: Remove old ways of getting YT dis/likes and more TeamNewPipe/NewPipeExtractor#755
5 - Convert tests to JUnit 5 TeamNewPipe/NewPipeExtractor#768

**Comment by Stypox** [comment] 2022-02-11 20:34
I pressed X on the player notification and the player closed correctly but the notification # remained there (though it could be swiped). I only encountered this issue once, so it might not be a regression but just bad luck (i.e. the issue might have been there in the previois version). But when testing the apk look out for it :-)

**Comment by TobiGr** [comment] 2022-02-11 20:57
RC2 brings a some small changes: [NewPipe_v0.22.0_RC2_debug.zip](https://github.com/TeamNewPipe/NewPipe/files/8051588/NewPipe_v0.22.0_RC2_debug.zip)
-  #7860
- #7852
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/798
 - translation updates

**Comment by SameenAhnaf** [comment] 2022-02-12 04:52
While searching preferences, only setting option and path should be bold. The option details should be a little vague as it is now in settings. As setting option and path use seperate font size, it won't be hard to differenciate.

**Comment by opusforlife2** [comment] 2022-02-12 12:57
@SameenAhnaf This issue only cares about regressions. Open a new issue after this version is released.

**Comment by ImDeadGuy** [comment] 2022-02-12 14:32
Happy to see the Main<->Pop-up and Main<->Background player transitions now keep playback position, that issue's been an annoyance for a few builds now. Good job so far, guys!

Meanwhile, this issue's fix still not merged into the build apparently :(
https://github.com/TeamNewPipe/NewPipe/pull/7341
Is this really such a difficult issue to integrate, or does no one else use bluetooth headphones?

**Comment by TobiGr** [comment] 2022-02-18 23:16
[NewPipe_v0.22.0_RC4.zip](https://github.com/TeamNewPipe/NewPipe/files/8100964/NewPipe_v0.22.0_RC4.zip) fixes
- #7731

**Comment by degarb** [comment] 2022-02-19 15:35
Rc 24 does not work for me. Rc22 works fine. 

I am thrilled that the Rc22 does not loose its position when switching between player, popup and background, as in the main apk.  This fix allows me to use it as a lecture and sleep device for when in bed.  I had to abandon yt altogether for old Art Bell episodes, since every time I needed to check a text message, etc. I would loose the player position.  The main Yt app jars me awake with nerve jarring ads.  Plus, I get drowsy faster at 2.65 speed than trying to follow a less challenging 2x speed.  

Good job to the developers.  But I don't know why rc4 doesn't work, I tried clearing cache.  Both rc2 and rc4 side load along with the official version. But rc4 will start up, but seems to not find anything to play, and sharing list or video to the video player, just stares at me with the circular arrow.   Rc2 works and behaves fine.  Still locked into the platform curated by the advertiser- big pharma, etc. Whom ever writes them the biggest checks, controls the dialog.  But this is largely circumvented, because people are smarter than bots, and Yt is a virtual monopoly anyway.

**Comment by Stypox** [comment] 2022-02-19 15:48
@degarb could you provide more *relevant* information about what you are experiencing? The changes that happened between RC2 and RC4 (RC stands for Relase Candidate) are just an error fixed in the extractor, a bugfix for the player and updated translations. So there is nothing that could cause the app to load indefinitely. Could you test again, making sure there are no internet connection issues and/or other device problems? Also, what do you mean by "seems to not find anything to play", what have you tried? Could you provide us with a screenshot? Are you sure that under the same exact conditions (i.e. after a clean install) RC2 works but RC4 doesn't?

**Comment by litetex** [comment] 2022-02-21 19:59
@TobiGr can we close this?

**Closed** 2022-02-21 20:01 UTC
