### ISSUE TITLE
Back button behaviour

### ISSUE THREAD

**Issue by mihirrai** [TeamNewPipe/NewPipe#548] opened 2017-05-10 10:50 UTC
When opening YouTube links, for example from reddit sync, the back button does not go back to reddit sync directly. Instead the back button has to pressed repeatedly until newpipe is exited. Hope one back button press to return to previous application can be implemented.

**Comment by theScrabi** [comment] 2017-05-10 21:33
Yea, but thats a duplicate.

**Comment by mauriciocolli** [comment] 2017-05-16 01:50
Actually, the behavior that @mihirrai said is the preferred.

Also, I didn't found a duplicate of this issue specifically.

**Comment by tgp1994** [comment] 2017-05-17 05:18
I noticed this had changed several versions ago, are there plans to go back to the old way?

**Comment by theScrabi** [comment] 2017-05-17 07:41
Yes

**Comment by teod0r** [comment] 2017-06-03 14:19
Also the icon of search should be changed to eyeglass. And icon of back should be changed to an arrow.

**Comment by wb9688** [comment] 2017-06-03 14:59
@teod0r: Isn't that already?

**Comment by teod0r** [comment] 2017-06-04 07:46
@wb9688, now if you click the button with arrow, it openes home page, and you have to click the button with eyeglass second time to go to search. I suggest to have separate eyeglass button, which is always on the panel.

**Closed** 2017-06-11 12:14 UTC
Labels: enhancement
