### ISSUE TITLE
Locked player during scrolling

### ISSUE THREAD

**Issue by 9Orlaf2** [TeamNewPipe/NewPipe#7461] opened 2021-11-28 17:48 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Leave the video player visible during scrolling through video details, comments or recommended content. Like on the YouTube client developed by Google.

#### Why do you want this feature?

To be able to view more things at the same time, without having to choose whether to see the video or read the comments (for example).

**Comment by mhmdanas** [comment] 2021-11-28 17:51
Duplicate of #4484.

**Closed by mhmdanas** 2021-11-28 17:51 UTC
Labels: enhancement
