### ISSUE TITLE
Video playing in highest quality while watching premiere

### ISSUE THREAD

**Issue by SudipRajbanshi** [TeamNewPipe/NewPipe#10443] opened 2023-09-23 15:59 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

Play a premiere video and it'll start playing at the highest quality, no matter what you set in the default resolution. "Default resolution" setting is available in settings>video and audio>default resolution 

### Expected behavior

Premiere videos should play at "default resolution "

### Actual behavior

Premiere video is playing at highest resolution.

### Affected Android/Custom ROM version

Android 13, Official paranoid Android topaz 2, September security patch

### Affected device model

Poco X2, codename is phoenixin

**Comment by AudricV** [comment] 2023-09-23 16:16
A YouTube premiere is delivered as a livestream, so your issue is a duplicate of #1239.

**Closed by AudricV** 2023-09-23 16:16 UTC
Labels: bug, needs triage
