### ISSUE TITLE
Swipe left/right controls for the feed

### ISSUE THREAD

**Issue by tomose** [TeamNewPipe/NewPipe#8101] opened 2022-03-24 18:53 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add "swipe left/right" functionality for videos in the feed. Default it to something like swipe left = mark as watched, swipe right = enqueue. Add option to set left/right to most functions found in the long press menu (share, add to playlist).

That option alone will probably save a lot of people time when trying to hide watched videos, or queue up a bunch for background play.

### Why do you want this feature?

Swipe left/right speeds up UI interaction when performing tasks on many videos in the feed.

### Additional information

n/a

**Comment by tomose** [comment] 2022-03-24 18:54
If you need an example of similar swipe left/right, look at GMAIL. That's basically what Newpipe needs. And then the ability to customize the action of the swipe.

**Comment by SameenAhnaf** [comment] 2022-03-24 21:22
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2306 and rejected as mentioned in https://github.com/TeamNewPipe/NewPipe/issues/6187#issuecomment-904445140

**Comment by opusforlife2** [comment] 2022-03-25 19:48
From that comment:

> We are staying with the long press menu, and there are plans to improve it.

Just FYI, this isn't true anymore. That PR was closed.

**Comment by ggdorman** [comment] 2022-04-01 19:55
Genuinely the only feature I wish to see added. It would be amazing if I could swipe one way to add to a playlist (Watch Later) and and the other way to mark as watched (to hide it permanently from feed).

**Comment by Stypox** [comment] 2022-04-30 14:59
> Just FYI, this isn't true anymore. That PR was closed.

Wdym? We still plan on improving the long press menu. In the last few versions a few more entries have been added and there are still plans to create a better layout (though nobody worked on this yet).

So I will close this issue for the same reasons as https://github.com/TeamNewPipe/NewPipe/issues/6187#issuecomment-904445140

**Closed by Stypox** 2022-04-30 14:59 UTC
Labels: enhancement

**Comment by tomose** [comment] 2022-06-20 18:34
> > Just FYI, this isn't true anymore. That PR was closed.
> 
> Wdym? We still plan on improving the long press menu. In the last few versions a few more entries have been added and there are still plans to create a better layout (though nobody worked on this yet).
> 
> So I will close this issue for the same reasons as [#6187 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/6187#issuecomment-904445140)

"they would conflict with other gestures" There are no other gestures available in the feed list. No conflict.

"they would only allow adding at most two actions" And? Given that that area is where a lot of user interaction happens, why not add gestures when it improves user experience? Because we all know how much we LOVE to queue up videos by long pressing each, and, every, one. It simply is the best user experience. (sarcasm)

"it would be difficult to choose two actions without getting users complaining" So no actions is better than two predefined actions? This is why you offer a settings option for users to customize the actions.

"adding a setting page to customize swipe actions for every possible view would be really really complicated and would probably introduce bugs" Very complicated? Really? Come on now. Implementing the gesture itself would be more complicated than a settings option that dictates what the gesture does.

You're free to do as you wish, it's your project. But your given reasoning is weak. "Nah, don't feel like it" would've sufficed instead of weak reasons from a year ago. :)

**Comment by Stypox** [comment] 2022-06-21 07:59
I don't think those are weak reasons:
- 1. when the feed page is in the main page tab, the horizontal scroll is already used for scrolling between tabs
- 2. and 3. if we find a solution we need to find a final one, which does solve the issue for everyone. Only adding two options would only open up more issues about users saying "I want this other one"...
- 4. adding new settings is in general a bad thing because:
  - only tech-savy users will find them
  - it introduces complex behaviors into the app which are difficult to test and make sure they work correctly

So implementing this would not really solve the problem in general, and would also introduce more complexity into the app and more places where bugs can originate. I also would love if there were faster options than the long-press menu, and tried myself to find some designs (e.g. #2583), but I still haven't found something that satisfies the points above.

**Comment by opusforlife2** [comment] 2022-06-25 20:57
> when the feed page is in the main page tab

As far as I know, that was just a PR.

**Comment by Stypox** [comment] 2022-06-26 08:10
I am currently using it, and I've been using it from the start
![Screenshot_20220626-100308_NewPipe_1](https://user-images.githubusercontent.com/36421898/175805547-80b4b4d0-0e74-4a21-9b8a-75252d1facac.png)

**Comment by opusforlife2** [comment] 2022-06-26 15:37
Oh. That's just the What's New feed. When you wrote "feed page" I thought you were talking about custom feed tabs. 👍
