### ISSUE TITLE
crash on scrolling to top of list after deleting item

### ISSUE THREAD

**Issue by smellymoo** [TeamNewPipe/NewPipe#10050] opened 2023-04-28 16:37 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1: goto a playlist
2: delete an item
3: scroll to top of playlist

### Expected behavior

not crash

### Actual behavior

crash

### Logs

java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
 at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder([RecyclerView.java:7297](https://recyclerview.java:7297/))
 at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline([RecyclerView.java:6416](https://recyclerview.java:6416/))
 at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline([GapWorker.java:288](https://gapworker.java:288/))
 at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline([GapWorker.java:345](https://gapworker.java:345/))
 at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline([GapWorker.java:361](https://gapworker.java:361/))
 at androidx.recyclerview.widget.GapWorker.prefetch([GapWorker.java:368](https://gapworker.java:368/))
 at [androidx.recyclerview.widget.GapWorker.run](https://androidx.recyclerview.widget.gapworker.run/)([GapWorker.java:399](https://gapworker.java:399/))
 at android.os.Handler.handleCallback([Handler.java:942](https://handler.java:942/))
 at android.os.Handler.dispatchMessage([Handler.java:99](https://handler.java:99/))
 at android.os.Looper.loopOnce([Looper.java:226](https://looper.java:226/))
 at android.os.Looper.loop([Looper.java:313](https://looper.java:313/))
 at android.app.ActivityThread.main([ActivityThread.java:8741](https://activitythread.java:8741/))
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$[MethodAndArgsCaller.run](https://methodandargscaller.run/)([RuntimeInit.java:571](https://runtimeinit.java:571/))
 at com.android.internal.os.ZygoteInit.main([ZygoteInit.java:1067](https://zygoteinit.java:1067/))
-------------------------------------

**Comment by AudricV** [comment] 2023-04-29 08:48
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

You did not: duplicate of #4475. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2023-04-29 08:48 UTC
Labels: bug, GUI, playlist

**Comment by smellymoo** [comment] 2023-04-29 08:58
I tried. There are 1000+ open issues. That's a lot!

Maybe close some? I know it's annoying to deal with users, I spent a day to write a bot so I didn't need to deal with mine, I get it. 

But it's not the users fault they can't find the issues, there is too many open issues.
