### ISSUE TITLE
SoundCloud Tracks Result in Error

### ISSUE THREAD

**Issue by nahteyamashita** [TeamNewPipe/NewPipe#2823] opened 2019-11-25 22:28 UTC
As says in the title, SoundCloud tracks are no longer playing. This is the error text on the Guru Meditation popup.

## Exception
* __User Action:__ requested stream
* __Request:__ https://soundcloud.com/louisvsfrostsc/sans-why-are-you-in-my-gameboy
* __Content Language:__ US
* __Service:__ SoundCloud
* __Version:__ 0.17.4
* __OS:__ Linux Android 9 - 28
undefined

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:187)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

**Comment by fisian** [comment] 2019-11-26 20:58
I get the same error. Seems like Soundcloud changed something on their website again.

**Comment by AmbientCyan** [comment] 2019-11-27 18:22
I can confirm that not only can I not view soundcloud pages in-app but when I start typing in the search bar while in "SoundCloud mode" I get a nice exception:

```json
{
   "user_action": "get suggestions",
   "request": "",
   "content_language": "US",
   "service": "SoundCloud",
   "package": "org.schabi.newpipe",
   "version": "0.17.4",
   "os": "Linux Android 9 - 28",
   "time": "2019-11-27 18:19",
   "exceptions": [
      "org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:47)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:105)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$kAwiU5Tjeit-NCwHTWhD3V6UHS8.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\n\tat io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\n\tat io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)\n\tat io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\n\tat io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)\n\tat io.reactivex.Observable.subscribe(Observable.java:12090)\n\tat io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)\n\tat io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)\n\tat io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)\n\tat io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: com.grack.nanojson.JsonParserException: Expected JSON value, got EOF on line 1, char 0\n\tat com.grack.nanojson.JsonParser.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonParser.currentValue(Unknown Source:30)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:3)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:15)\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:40)\n\t... 26 more\n"
   ],
   "user_comment": ""
}
```

**Comment by beered239** [comment] 2019-11-28 02:19
Yeah SoundCloud isn't working anymore, same thing happened to me just now

**Comment by pihug12** [comment] 2019-11-28 21:49
On Youtube-DL, they changed the CLIENT_ID : https://github.com/ytdl-org/youtube-dl/commit/cf3c9eafad5e6b83788e15a605aa6804b1ab307c

(ping @mauriciocolli)

**Comment by TobiGr** [comment] 2019-11-28 22:04
Updating the client_id solves some of the problems. It seems like soundcloud moved the JSON where it was extracted from again^^. I'll investigate further to provide a full fix asap

**Comment by TobiGr** [comment] 2019-11-28 23:28
@AmbientCyan Your problem will be solved by #217 and further client_id changes handled properly by the app (no more crashing, but fetching the new one).
@nahteyamashita However there is still an auth problem to get the tracks. I'll take a look at it at the weekend if no one else is doing it before me.

**Comment by genevera** [comment] 2019-12-07 16:51
Is there any ETA on this fix?  The app is more or less unusable for me since it doesn't stream anything from SC.

PS thank you for all the hours that y'all have put into this! Only asking because I really like this app

**Comment by Stypox** [comment] 2019-12-09 20:06
TeamNewPipe/NewPipeExtractor#217 fixes this issue, it should be merged in a few days @genevera

**Comment by TobiGr** [comment] 2019-12-12 21:21
One half of the problem is solved. We can access SoundCloud again. However, it is not possible to get any streams which makes sc quite useless :( 
I think we need help.

**Comment by TobiGr** [comment] 2019-12-19 03:23
I managed to get the stream urls. See [this method](https://github.com/TeamNewPipe/NewPipeExtractor/blob/fix/SC_stream/extractor/src/main/java/org/schabi/newpipe/extractor/services/soundcloud/SoundcloudStreamExtractor.java#L143) for more info. However, I still cannot play them. I can generate a `m3u` url for each audio format, but exoplayer has problems with playing them. Can someone with more knowledge of the player help me out?
CC @theScrabi @Stypox @Redirion @yausername @mauriciocolli @karyogamy

**Comment by Stypox** [comment] 2019-12-19 11:47
Is this exoplayer issue helpful or related? https://github.com/google/ExoPlayer/issues/3722

**Comment by pihug12** [comment] 2019-12-21 22:41
I saw this fail in the https://github.com/TeamNewPipe/NewPipeExtractor/pull/217 Travis CI log:
```
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.soundcloud.com/i1/tracks/276206960/streams?client_id=bkcJLoXNaiFlsLaKBQXOxO5FhW0NJVnu
```

Here are the stream URLs for this track:
* Info API: https://api-v2.soundcloud.com/tracks/276206960?client_id=bkcJLoXNaiFlsLaKBQXOxO5FhW0NJVnu
* Stream 1 (playlist.m3u8): https://api-v2.soundcloud.com/media/soundcloud:tracks:276206960/6f584a2d-87c2-451b-90df-158efcc42680/stream/hls?client_id=bkcJLoXNaiFlsLaKBQXOxO5FhW0NJVnu
* Stream 2 (direct MP3?): https://api-v2.soundcloud.com/media/soundcloud:tracks:276206960/6f584a2d-87c2-451b-90df-158efcc42680/stream/progressive?client_id=bkcJLoXNaiFlsLaKBQXOxO5FhW0NJVnu

https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/soundcloud.py helped me a bit. I used `youtube-dl -s -v --print-traffic https://soundcloud.com/liluzivert/do-what-i-want-produced-by-maaly-raw-don-cannon` to see the requests done.

I don't know if these are the one you are not able to play with ExoPlayer.

**Comment by TobiGr** [comment] 2019-12-21 22:44
Ha perfect ❤️ we need to choose the last one.

**Closed** 2019-12-21 23:42 UTC
Labels: bug, requires extractor change, soundcloud
