### ISSUE TITLE
Newpipe crashed on pluging in the charger.

### ISSUE THREAD

**Issue by ashjas** [TeamNewPipe/NewPipe#7357] opened 2021-11-04 12:00 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.schabi.newpipe/.CheckForNewAppVersion }: app is in background uid UidRecord{da93235 u0a225 CAC  bg:+1h11m5s675ms idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1715)
	at android.app.ContextImpl.startService(ContextImpl.java:1670)
	at android.content.ContextWrapper.startService(ContextWrapper.java:720)
	at org.schabi.newpipe.CheckForNewAppVersion.startNewVersionCheckService(CheckForNewAppVersion.java:258)
	at org.schabi.newpipe.MainActivity.onPostCreate(MainActivity.java:175)
	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1383)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3484)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:58)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5415)
	at android.app.ActivityThread.access$3300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2076)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by litetex** [comment] 2021-11-12 19:46
Duplicate of #7397 (has better description)

**Closed by litetex** 2021-11-12 19:46 UTC
Labels: bug, template-missing
