### ISSUE TITLE
Video on top when scrolling comments

### ISSUE THREAD

**Issue by Wouter997** [TeamNewPipe/NewPipe#7356] opened 2021-11-04 06:31 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

I would like the video to stay on top/in view when scrolling the comments.

#### Why do you want this feature?

I always activate the pop up feature to achieve the above but it would be more elegant if the video remains in view as standard (like it does in the youtube app).

**Comment by mhmdanas** [comment] 2021-11-04 09:38
Duplicate of #4484.

**Closed by mhmdanas** 2021-11-04 09:38 UTC
Labels: enhancement
