### ISSUE TITLE
constant guru

### ISSUE THREAD

**Issue by ChaliKaki** [TeamNewPipe/NewPipe#8681] opened 2022-07-22 16:44 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

23.1

### Steps to reproduce the bug

select video
select second video
guru

### Expected behavior

see second video

### Actual behavior

guru

### Logs

[x.txt](https://github.com/TeamNewPipe/NewPipe/files/9169382/x.txt)

### Affected Android/Custom ROM version

android 9

### Affected device model

vontar box

**Comment by AudricV** [comment] 2022-07-22 17:23
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #8384. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2022-07-22 17:23 UTC
Labels: bug
