### ISSUE TITLE
Big Kang Warning

### ISSUE THREAD

**Issue by 4PERTURE** [TeamNewPipe/NewPipe#1767] opened 2018-09-29 15:06 UTC
I found this on XDA:
https://labs.xda-developers.com/store/app/com.gomezgutierrezd.alejandra.mini

This app violates the GPL license and there is no mention of NewPipe or the license anywhere in the app.

**Comment by comradekingu** [comment] 2018-10-02 21:03
@4PERTURE Such issues are discussed in #539 :)

**Comment by comradekingu** [comment] 2018-10-04 10:29
@theScrabi Here https://www.xda-developers.com/contact/#legal

**Comment by B0pol** [comment] 2020-05-10 09:46
Duplicate of #539

**Closed by B0pol** 2020-05-10 09:46 UTC
Labels: meta
