### ISSUE TITLE
Delete history older than x days

### ISSUE THREAD

**Issue by Donkey-Doug** [TeamNewPipe/NewPipe#7080] opened 2021-09-08 22:27 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it is a good idea to add an option to delete watch history older than x days. This makes it possible for me to still find a video I watched recently, but is also less invasive to my privacy. If I hand over my phone to someone else, they do not have access to every video I ever watched.

**Comment by SameenAhnaf** [comment] 2021-09-09 02:58
Duplicate of #3487.

**Closed** 2021-09-09 18:20 UTC
Labels: enhancement
