### ISSUE TITLE
ReCaptcha error

### ISSUE THREAD

**Issue by KrisKamweru** [TeamNewPipe/NewPipe#2795] opened 2019-11-10 17:48 UTC
- [✅] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [✅] I checked if the issue/feature exists in the latest version.
- [ ✅ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

## Exception
* __User Action:__ requested stream
* __Request:__ https://youtu.be/4G9h8ULBh_g
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.17.4
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerConfig(YoutubeStreamExtractor.java:660)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:638)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

Happens every time I open a video from anywhere (in app, share link, etc)

**Comment by molikuner** [comment] 2019-11-11 19:18
Actually I had the same issue, but only while being in a public Hotspot. At home it worked again.

**Comment by Z3ROGRAV1TYx** [comment] 2019-11-15 14:33
Same issue,  at home

**Comment by MuntashirAkon** [comment] 2019-11-22 16:21
[YMusic](https://ymusic.io) solved this problem (still buggy there as well) by prompting user to solve the captcha challenge. I wonder if similar can be implemented here as well.

A question: Are you spoofing user agent or anything like this? It seems my device has been blacklisted by Youtube which wasn't the case before I used this app (YMusic doesn't have this problem). When I use a browser app in the same device, I get a captcha followed by the following message:
> You are seeing this message because your current network has been identified as using non-authorized applications to access YouTube. Non-authorized apps can expose you to a number of risks including malware, unauthorized access to your data and excessive battery drain
>
> Please use the official YouTube Android, YouTube iOS or YouTube Go apps; and consider uninstalling any non-verified apps.
>
> To continue with your YouTube experience, please fill out the form below.

_How do I know that only my device has been blacklisted?_ This network has many users and none of them (including my computer) are blacklisted and works just fine even without having to logging in to an account.

**Comment by Stypox** [comment] 2019-12-03 14:31
Duplicate of #2787

**Closed by Stypox** 2019-12-03 14:31 UTC
