### ISSUE TITLE
App Crash, UI Failure

### ISSUE THREAD

**Issue by FreedomIsAChoice** [TeamNewPipe/NewPipe#5849] opened 2021-03-17 20:19 UTC
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ DE
* __Content Language:__ de
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux samsung/starltexx/starlte:10/QP1A.190711.020/G960FXXUAETG3:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.view.InflateException: Binary XML file line #31: Error inflating class (not found)org.schabi.newpipe.settings.custom.NotificationActionsPreference
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:287)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:344)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
	at androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:361)
	at org.schabi.newpipelegacy.settings.NotificationSettingsFragment.onCreatePreferences(NotificationSettingsFragment.kt:10)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at org.schabi.newpipelegacy.settings.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:24)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8125)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.ClassNotFoundException: org.schabi.newpipe.settings.custom.NotificationActionsPreference
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:214)
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:277)
	... 26 more
Caused by: java.lang.ClassNotFoundException: org.schabi.newpipe.settings.custom.NotificationActionsPreference
	... 30 more

```
</details>
<hr>

**Comment by TiA4f8R** [comment] 2021-03-18 11:50
You posted this crash on the wrong repo. Duplicate of TeamNewPipe/NewPipe-legacy#67.
Also please follow the template next time.

**Closed by TiA4f8R** 2021-03-18 11:50 UTC
Labels: bug
