### ISSUE TITLE
Playlists on channel pages

### ISSUE THREAD

**Issue by Dre-OS** [TeamNewPipe/NewPipe#4146] opened 2020-08-17 03:24 UTC
#### Describe the feature you want

It's nice to have the playlists created by a channel in a tab on a channel page like on YouTube
#### Is your feature request related to a problem? Please describe it

It's hard to find playlists, you have to search for the channel name in order for playlists to show up, but then you still have to find the specific playlist which is usually hidden between other videos which is inconvenient.
#### How will you/everyone benefit from this feature?

It would be a convenient way to find specific playlists for the binge watchers out there that follows a specific channel with a lot of video series but they don't want their playlist bookmarks to be crowded or for the average user that just wants playlists to be organized in one channel.

**Comment by opusforlife2** [comment] 2020-08-17 08:50
It'll come with the tabs PR: #3201.

Anyway, search before opening issues. Duplicate of #2414.

**Closed by opusforlife2** 2020-08-17 08:50 UTC
Labels: enhancement
