### ISSUE TITLE
 Dont replace the feed with a loading symbol when updating

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#8525] opened 2022-06-19 14:11 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

From https://github.com/TeamNewPipe/NewPipe/issues/7047:
* Dont replace the feed with a loading symbol, just update when loading is done.

### Why do you want this feature?

Users with a lot of subscriptions are primarily affected due to the long loading time.
Non-blocking UI → Users can browse the feed while loading.

### Additional information

See also #8511

**Comment by opusforlife2** [comment] 2022-06-19 22:39
Especially when updating through an Invidious instance. The feed loading time becomes an order of magnitude slower.

**Comment by SameenAhnaf** [comment] 2022-06-26 00:03
Duplicate of #4952

**Comment by opusforlife2** [comment] 2022-06-26 15:22
With its overly generic title, it's not surprising we missed it.

**Closed by opusforlife2** 2022-06-26 15:22 UTC
Labels: enhancement, GUI, feed
