### ISSUE TITLE
Multiple streams on multiple forms of player

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#4509] opened 2020-10-14 18:27 UTC
Before the unified player I could've kept two, sometimes even three videos ready to switch between them like browser tabs on PC. One on the main player, one on background (paused one) and sometimes even that paused popup. This isn't available anymore. Could you make a one/two feed(s) toggle in the settings?

**Comment by opusforlife2** [comment] 2020-10-14 18:31
Always fill the template. Duplicate of #4460.

**Closed by opusforlife2** 2020-10-14 18:31 UTC
