### ISSUE TITLE
[feature request] Add an option "Don't automaticaly select video without audio"

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#754] opened 2017-10-05 09:58 UTC
Could you please add an opportunity not to automaticaly preselect video resolution, that does not contains audio, but select best resolution with audio?
Have to manualy select quality, that contains audio for playing.

**Comment by theScrabi** [comment] 2017-10-05 12:05
What do you mean by that? Do you use the external player?

**Comment by teod0r** [comment] 2017-10-05 16:11
I use external player, I don't like buil-in. I mean 480p that have separate audio.

**Comment by theScrabi** [comment] 2017-10-07 00:00
I see. Well yea I guess that makes a valid issue.

**Comment by litetex** [comment] 2022-02-15 18:39
Duplicate of #1474

**Closed by litetex** 2022-02-15 18:39 UTC
Labels: enhancement
