### ISSUE TITLE
Enable Material You icon theme support on android 12

### ISSUE THREAD

**Issue by commit-ezza** [TeamNewPipe/NewPipe#8425] opened 2022-05-21 10:31 UTC
### Checklist

- [ ] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [ ] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [ ] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When Enabling Themed icon on android 12, NewPipe Sponsorblock support the themed icon and matching the users' theme.

### Why do you want this feature?

Regular NewPipe app has support for Material You icon theme-- this might be insignificant but nice to have on pixel devices.

**Comment by SameenAhnaf** [comment] 2022-05-21 11:19
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7595

**Closed** 2022-05-21 12:37 UTC
Labels: enhancement
