### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by Siorr** [TeamNewPipe/NewPipe#3346] opened 2020-04-03 17:33 UTC
I've been having issues with videos loading I thought it was my WiFi or mobile data but I think that it is within the app like the video will take a while to load or not even load at all.

**Comment by opusforlife2** [comment] 2020-04-03 17:40
Use the template. It is there for a reason. Open New Issue, copy the bug report template from there, paste it in this comment, and fill it out.

**Comment by gkeegan** [comment] 2020-04-03 18:00
Change quality to 720p. Does it load better now?

**Comment by Stypox** [comment] 2020-04-27 07:13
Duplicate of #2415

**Closed by Stypox** 2020-04-27 07:13 UTC
