### ISSUE TITLE
Popup player breaks interaction with the phone's UI (cannot use phone anymore)

### ISSUE THREAD

**Issue by OlivierGagnon** [TeamNewPipe/NewPipe#8032] opened 2022-03-14 17:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

* Play a video
* Toggle popup mode

* The popup window CAN be interacted with. Resized, moved.
* The entire phone UI, desktop, icons, other apps, are NO Longer able to be interacted/clicked on. It's like the popup player has put a layer on top of the entire screen, preventing clicking anything other than the popup player

* If you press Full Screen on the popup player and exit NewPipe, the phone UI is still unable to be interacted with. Needs to fully restart phone to use it again

### Expected behavior

Popup player should work properly

### Actual behavior

* The entire phone UI, desktop, icons, other apps, are NO Longer able to be interacted/clicked on. It's like the popup player has put a layer on top of the entire screen, preventing clicking anything other than the popup player

* If you press Full Screen on the popup player and exit NewPipe, the phone UI is still unable to be interacted with. Needs to fully restart phone to use it again

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 6

**Comment by mhmdanas** [comment] 2022-03-14 17:25
Duplicate of #6770.

**Comment by litetex** [comment] 2022-03-14 17:26
![grafik](https://user-images.githubusercontent.com/40789489/158227101-154230c5-1ee0-4f14-809f-f9eddb66435b.png)

Closing as duplicate

**Closed by mhmdanas** 2022-03-14 17:25 UTC
Labels: bug

**Comment by OlivierGagnon** [comment] 2022-03-14 17:57
Sorry guys!!
