### ISSUE TITLE
Audio freezes when turning monitor off, switching in/out of fullscreen etc.

### ISSUE THREAD

**Issue by eyalroz** [TeamNewPipe/NewPipe#7715] opened 2022-01-29 15:54 UTC
### Checklist

- [x] I am using the latest version - 0.21.15
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Start playing any video on YouTube (not an extremely short one)
2. Press the phone's power key, for a short time; in most smartphones, this will turn off the display, while running apps will continue running in some kind of background mode.
3. Listen for the continuity of video's sound

### Actual behavior
Sound stops for a few seconds, then resumes.

### Expected behavior
Sound should not stop at all: The hardware supports continued playback, and other apps ocntinue playtcoo fo

### Device info

 - Android version/Custom ROM version: MIUI Global 12.5.1
 - Device model: Xiaomi Mi 9 SE

### Other notes

* This has always been NewPipe's behavior - it's not anything new. It is also consistent - this _always_ happens.
* There are definitely apps which don't behave this way: Specifically, I use an app which streams Israeli radio stations with which playback is smooth while you turn your monitor on or off - whether the app is in the background or not. ... and of course - audio is smooth for phone conversations :-)

**Comment by mhmdanas** [comment] 2022-01-30 13:36
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5016.

**Closed by mhmdanas** 2022-01-30 13:36 UTC
Labels: bug

**Comment by eyalroz** [comment] 2022-01-30 17:52
@mhmdanas : Where can I get builds with this PR integrated? I'm not an Android dev myself.

**Comment by opusforlife2** [comment] 2022-01-30 18:07
@eyalroz The instructions are in the PR's description. Make sure you're signed in before trying to download the APK (Github limitation).
