### ISSUE TITLE
NewPipe is always starting when a bluetooth-device is connecting to smartphone

### ISSUE THREAD

**Issue by RichardBeisser** [TeamNewPipe/NewPipe#5778] opened 2021-03-06 22:18 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

When my headphones or my car-radio or my phoneheadset is connecting to my smartphone, newpipe always starts without doing something

### Expected behavior

newpipe should not start automatically

### Device info

 - Android version/Custom ROM version: Android 7.0
 - Device model: ulefone s8pro

**Comment by TobiGr** [comment] 2021-03-06 23:35
What do you mean by starting? Does the app launch and do you see the main tabs or do you get an empty NewPipe notification?

**Comment by Ammako** [comment] 2021-03-07 03:08
Empty notification

**Comment by RichardBeisser** [comment] 2021-03-07 10:36
> 
> 
> What do you mean by starting? Does the app launch and do you see the main tabs or do you get an empty NewPipe notification?

see this Screenshots:
[Pic1](https://abload.de/img/screenshot_20210307-144j7j.png)
[Pic2](https://abload.de/img/screenshot_20210307-1azkl4.png)

After a bluetooth-connection ist established, NewPipe is starting automatically

**Comment by opusforlife2** [comment] 2021-03-13 03:54
It's an Android issue. Nothing Newpipe can do here: https://github.com/TeamNewPipe/NewPipe/issues/3903#issuecomment-660667854

**Comment by Ammako** [comment] 2021-03-13 04:04
Could just have an option in NewPipe to ignore the intent. Just because it's an intentional Android feature doesn't mean an app can't be designed around that.

https://www.xda-developers.com/google-play-music-stop-automatic-playback/

**Comment by opusforlife2** [comment] 2021-03-13 04:07
Nice! I didn't know that was possible. Reopening because a fix is possible.

**Comment by mhmdanas** [comment] 2021-04-25 18:27
Duplicate of #5122.

**Closed by mhmdanas** 2021-04-25 18:27 UTC
Labels: bug
