### ISSUE TITLE
Shuffle playlist

### ISSUE THREAD

**Issue by Imany42** [TeamNewPipe/NewPipe#7354] opened 2021-11-03 18:40 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
The playlist has options such as background, play all and popup, but there is no option to shuffle the list.  Please add shuffle to the playlist. Thanks.
Also, this is my first time posting on github.  I'm so sorry if I made a mistake in the templates

#### Why do you want this feature?
 I want the music in my playlist to be shuffled.

**Comment by SameenAhnaf** [comment] 2021-11-04 03:25
Duplicate of #6625.

**Comment by litetex** [comment] 2021-11-04 12:58
Duplicate of #6625

**Closed by litetex** 2021-11-04 12:58 UTC
Labels: enhancement

**Comment by HiVaLiKi** [comment] 2021-11-13 21:22
I support
