### ISSUE TITLE
permanently store unlink pitch and tempo flag

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#1994] opened 2019-01-10 06:12 UTC
I'd like to always scale only tempo and never touch pitch.
But I need to set unlink checkmark every time.

For example VLC has separate setting for this.

**Comment by JoeTvx** [comment] 2019-01-22 12:08
+1
Having the unlink checked as default would be the use case for 99.9% of users, I would imagine, and would also solve this issue.

**Comment by Stypox** [comment] 2019-09-17 04:39
Duplicate of #735

**Closed by Stypox** 2019-09-17 04:39 UTC
