### ISSUE TITLE
Crash loop when starting a download

### ISSUE THREAD

**Issue by kurros** [TeamNewPipe/NewPipe#8748] opened 2022-08-08 02:48 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Navigate to a YT video
2. Click download
3. Click OK on name/quality popup.

### Expected behavior

A sucessful download

### Actual behavior

A 0 byte file is created in configured (via SAF) download location, and then NewPipe goes into a crash loop.

### Logs

Initial crash is:
```
FATAL EXCEPTION: main
Process: org.schabi.newpipe, PID: 31259
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
	at org.schabi.newpipe.streams.io.StoredFileHelper.<init>(StoredFileHelper.java:131)
	at us.shandian.giga.service.DownloadManagerService.startMission(DownloadManagerService.java:426)
	at us.shandian.giga.service.DownloadManagerService.lambda$onStartCommand$0(DownloadManagerService.java:213)
	at us.shandian.giga.service.DownloadManagerService.$r8$lambda$WuT9vKbg0muVO8HCiHnX-vu0d7I(Unknown Source:0)
	at us.shandian.giga.service.DownloadManagerService$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

followed by a loop of NewPipe restarting and crashing:
```
FATAL EXCEPTION: main
Process: org.schabi.newpipe, PID: 30907
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.error.ErrorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.schabi.newpipe.error.UserAction org.schabi.newpipe.error.ErrorInfo.getUserAction()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2805)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2883)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.schabi.newpipe.error.UserAction org.schabi.newpipe.error.ErrorInfo.getUserAction()' on a null object reference
	at org.schabi.newpipe.error.ErrorActivity.buildInfo(ErrorActivity.java:220)
	at org.schabi.newpipe.error.ErrorActivity.onCreate(ErrorActivity.java:123)
	at android.app.Activity.performCreate(Activity.java:7023)
	at android.app.Activity.performCreate(Activity.java:7014)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2758)
	... 9 more
```
### Affected Android/Custom ROM version

Android 8.1.0

### Affected device model

Generic Chinese tablet

### Additional information

I couldn't find any NewPipe generated debug logs or a way to enable them.

**Comment by smellymoo** [comment] 2022-08-14 19:11
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.23.2
* __OS:__ Linux samsung/xcoverproeea/xcoverpro:12/SP1A.210812.016/G715FNXXUADVF1:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.download.DownloadDialog: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.download.DownloadDialog: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:143)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
	... 12 more
Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.download.DownloadDialog.<init> []
	at java.lang.Class.getConstructor0(Class.java:2363)
	at java.lang.Class.getConstructor(Class.java:1759)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 26 more

```
</details>
<hr>

**Comment by coderkei** [comment] 2022-10-09 13:43
Happens to me too except, I can't download anything, it keeps force closing on the download box every time.

**Comment by opusforlife2** [comment] 2022-10-09 14:35
> Generic Chinese tablet

Try it on a different OS.

> mobile GUI 

Seal from F-Droid?

**Comment by coderkei** [comment] 2022-10-09 15:04
@opusforlife2 Just to add on, I get the same type of Crash on an Oppo Reno (1st Gen Model) running Android 11.

Using the latest version from the Newpipe upstream F-Droid repo.

**Comment by opusforlife2** [comment] 2022-10-09 15:07
Things to check:
- App has the correct permissions?
- Video and audio download folders are set properly?
- OS has at least one working and enabled SAF provider?

**Comment by coderkei** [comment] 2022-10-09 15:16
Hi @opusforlife2 

1) Yep, all permissions allowed:

2) SAF Provider is DocumentUI, seems to be working for other apps.

3) Paths are set as follows. They were set with the DocumentUI activity:

![](https://i.ibb.co/nMFKPSN/Screenshot-2022-10-09-16-10-52-89-ee8807d2de22f1831269d80920e33a3b.jpg)

Here is a video that causes the crash for me:
[https://www.youtube.com/watch?v=dp5aGjt2xok](https://www.youtube.com/watch?v=dp5aGjt2xok)

The video can be played but upon tapping "Download", the box shows up but a filesize does not show up, and it force closes after about 10 seconds. A crash log is not generated.

I am not sure if the process is being killed due to ANR or not but that seems to be the behavior visibly.

This was hard to reproduce in older versions but I can now reliably reproduce it on my device.

Is there anything else I can do to help with diagnosing the issue?

**Comment by opusforlife2** [comment] 2022-10-09 15:18
@coderkei What you describe is not the same bug then. You don't even get to start the download before you get the crash. See if there is another issue that describes your exact problem.

**Closed** 2022-10-24 00:22 UTC
Labels: bug, downloader, waiting for author
