### ISSUE TITLE
Seekbar in  the notification does not progress as video is playing in the background

### ISSUE THREAD

**Issue by eternal-sorrow** [TeamNewPipe/NewPipe#6909] opened 2021-08-12 06:38 UTC
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Start playing any video in the background
2. Swipe down to open the notification drawer

### Actual behavior

Seekbar in the notification stays at 0:00 as video playback progresses

### Expected behavior

Seekbar progresses with video playback

### Screenshots/Screen recordings

![photo_2021-08-12_16-35-40](https://user-images.githubusercontent.com/4847726/129149278-0095cd33-2939-42b3-8824-a45a2c9a71ec.jpg)

### Device info

 - Android version/Custom ROM version: Android 10/Lineage OS 17.1
 - Device model: Sony Xperia XA2 Dual H4133 pioneer

**Comment by SameenAhnaf** [comment] 2021-08-12 10:44
Duplicate of #4590.

**Closed** 2021-08-12 10:50 UTC
Labels: bug
