### ISSUE TITLE
Playlist download

### ISSUE THREAD

**Issue by CarterSnich** [TeamNewPipe/NewPipe#7258] opened 2021-10-16 04:22 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Allow NewPipe to download playlists, or at least add option to download video when you tap-and-hold a video.

Sample playlist
![Screenshot_2021-10-16-12-17-28-00_ee8807d2de22f1831269d80920e33a3b.jpg](https://user-images.githubusercontent.com/52433531/137573604-52a5546a-f004-443e-b4d8-b8c2c3fd3117.jpg)

Video options
![Screenshot_2021-10-16-12-17-33-06_ee8807d2de22f1831269d80920e33a3b.jpg](https://user-images.githubusercontent.com/52433531/137573617-69b035e3-0239-444a-8826-b4273ed40c17.jpg)

#### Why do you want this feature?

It's more convenient to download a playlists that way, instead of playing each video and clicking the Download button.

Thanks!

**Comment by SameenAhnaf** [comment] 2021-10-16 05:49
Duplicate of #5782.

**Comment by SameenAhnaf** [comment] 2021-10-16 06:47
Duplicate of #1236.

**Closed** 2021-10-16 08:33 UTC
Labels: enhancement
