### ISSUE TITLE
menu to order your channel list

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#970] opened 2018-01-06 17:50 UTC
add an option to sort by time of seniority or by alphabet the list of channels to which you subscribed

**Comment by tetris4** [comment] 2018-01-11 10:30
Manual ordering would also be useful, so one can group channels by topic (e.g. music, vlogs, comedy, sport highlights etc)

**Comment by theScrabi** [comment] 2018-01-11 11:46
Yes true.

**Comment by Tajnymag** [comment] 2019-01-28 18:11
Bump

**Comment by nekobit1** [comment] 2019-01-28 21:32
theScrabi mentioned before that his focus is bug fixes lately, not feature requests, so your bump isn't much help, but yeah, we should see this again too

**Comment by Tajnymag** [comment] 2019-01-28 21:35
@nekobit1 I respect that. The only reason for my "bump" was so the issue doesn't get closed by the stale[bot]

**Comment by Stypox** [comment] 2019-07-18 06:26
This problem will probably be solved by #2309

**Comment by opusforlife2** [comment] 2020-08-04 03:31
So it is solved now.

**Comment by wb9688** [comment] 2020-08-04 06:30
@opusforlife2: I don't think it's possible to see channels in a group (well, except when editing it) in a way that you could open the channels (which isn't possible when editing)

**Comment by opusforlife2** [comment] 2020-08-04 06:34
Then it's a duplicate of other open issues (can't remember the numbers right now, one of them is my own.)

**Closed** 2020-08-04 13:34 UTC
Labels: enhancement
