### ISSUE TITLE
Suggestions / recommendation tab (like YouTube)

### ISSUE THREAD

**Issue by HellxDo** [TeamNewPipe/NewPipe#4235] opened 2020-09-05 01:43 UTC
#### Describe the feature you want

I've recently been noticing how the recommendation tab really impacted what I watch.. specially because personally I discover slot of interesting music because of my search and video history. Sometimes in new pipe I lack the recommendation tab, usually hoping to listen to a new type of music, not the ones I know because of name.. this feature wouldn't violate the privacy of the user at all, it would simply find similar videos shown on search and users history tab, and display them in the home screen, similarly to the Queue System.
#### How will you/everyone benefit from this feature?

This feature will actually make us spend more time on NewPipe! Let's say someone goes there to find memes, to download, the suggestion page would find similar memes that the user seen, and they would stay there looking through all the memes and downloading. For Music Listeners (like me) new music of the same genre and taste.

**Comment by opusforlife2** [comment] 2020-09-05 07:33
We already do have a setting called 'Show Next and Similar videos', though?

**Comment by Stypox** [comment] 2020-09-06 13:15
This is a duplicate of an open issue, which I can't currently find, and #2227 is related

**Comment by opusforlife2** [comment] 2020-09-11 09:54
Found the original: #2256.

@HellxDo please post your suggestion as a comment on that issue.

**Closed by opusforlife2** 2020-09-11 09:54 UTC
Labels: enhancement, more info needed
