### ISSUE TITLE
After v0.24.0 update newpipe often crashes (screenshot included)

### ISSUE THREAD

**Issue by itsme24082004** [TeamNewPipe/NewPipe#9041] opened 2022-09-29 01:16 UTC
<img alt="Screenshot_2022-09-29-11-53-27-244_org schabi newpipe" src="https://user-images.githubusercontent.com/91739986/193456122-369c6a66-8f5d-4857-8149-39f9f3f0ef4e.jpg" height=600 />
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.0 

### Steps to reproduce the bug

1) Open newpipe latest version
2) Play any video
3)Popup message saying newpipe isnt responding comes or the entire app gets crashed.

### Expected behavior

1) To play video smoothly without getting crashed .

### Actual behavior

1) The app gets crashed or popup message saying newpipe isnt responding comesup.

### Affected Android/Custom ROM version

Android 10 / miui 12.5

### Affected device model

Redmi 8 a dual

### Additional information

I saw this kind of problem when i used debug app that one of the contributor gave when newpipe isnt working that time.

**Comment by itsme24082004** [comment] 2022-09-29 06:24
![Screenshot_2022-09-29-11-53-27-244_org schabi newpipe](https://user-images.githubusercontent.com/91739986/192954769-1a8af260-6983-44db-bcdf-c320498026b1.jpg)


Proof

**Comment by spectrejs** [comment] 2022-09-30 22:06
same problem here...

**Comment by Hypnoticbat9555** [comment] 2022-10-02 10:56
I have the same problem on my s20fe (snapdragon) running Android 12. Android keeps telling me the app is not responding, although the video keeps playing.

**Comment by itsme24082004** [comment] 2022-10-02 13:06
> 

Yes the exact problem is also there for me

**Comment by itsme24082004** [comment] 2022-10-02 13:07
@Hypnoticbat9555  yes this exact issue is also there for me bro

**Comment by opusforlife2** [comment] 2022-10-02 16:44
We'll need crash logs. If the app itself doesn't give you logs, try using a logcat app, or better yet, Scoop from F-Droid. If you don't have root, you'll have to provide it permissions using adb.

**Comment by Elanngo-Madheswaran** [comment] 2022-10-02 16:46
> We'll need crash logs. If the app itself doesn't give you logs, try using a logcat app, or better yet, Scoop from F-Droid. If you don't have root, you'll have to provide it permissions using adb.

The app doesnt give me logs but , i cant use adb as i dont have system with me so is there anyother way i can give you logs

**Comment by opusforlife2** [comment] 2022-10-02 16:48
That's okay. We can wait for others in this thread.

**Comment by Elanngo-Madheswaran** [comment] 2022-10-02 16:48
Hmm ok sir

**Comment by itsme24082004** [comment] 2022-10-02 17:05
@opusforlife2 bro @GlitzSmarter gave a crash log is this usefull

**Comment by opusforlife2** [comment] 2022-10-02 17:11
I know... I got the notification.

**Comment by itsme24082004** [comment] 2022-10-02 17:13
> I know... I got the notification.

Ooh sorry for the disturbance i am new

**Comment by opusforlife2** [comment] 2022-10-02 17:15
No problem.

**Comment by opusforlife2** [comment] 2022-10-02 17:32
Right. Seeing the logs and the steps taken, this is a duplicate of #9030.

**Closed by opusforlife2** 2022-10-02 17:32 UTC
Labels: bug, needs triage

**Comment by itsme24082004** [comment] 2022-10-02 17:37
Sorry as i dont know technicaly about this problem i started this issue  ,
i didnt intensionally start a duplicate issue . And i am sorry for the
disturbances

**Comment by opusforlife2** [comment] 2022-10-02 17:38
No problem. If we felt like you ignored the template on purpose, we would have used that specific label.

**Comment by Elanngo-Madheswaran** [comment] 2022-10-02 17:40
Ok thanks is there any way that problem getting solved

**Comment by opusforlife2** [comment] 2022-10-02 17:43
Patience.

**Comment by Elanngo-Madheswaran** [comment] 2022-10-02 17:45
Thank you!
