### ISSUE TITLE
Please add a download option after long-clicking on the video. 

### ISSUE THREAD

**Issue by cdwijs** [TeamNewPipe/NewPipe#2850] opened 2019-12-08 21:55 UTC
Summary: Please add a download option after long-clicking on the video. 

Usecase:
I don't have mobile data, and I would like to listen to YouTube on the go. Therefore I would like to quickly download multiple video's of a channel. 

Steps I now have to take to download 3 video's from a channel:
Start NewPipe
Click on a video
Click on the channel name
Click on a the first video
click download and OK
Click back
Click on the second video
click download and OK
Click back
Clink on the third video
click download and OK

It would be nice if it could be done like this:
Start NewPipe
Click on a video
Click on the channel name
Long-click on the first video. 
Select the -non existent- Download option, and press OK
Long-click on the second video. 
Select the -non existent- Download option, and press OK
Long-click on the third video. 
Select the -non existent- Download option, and press OK

My versions:
NewPipe 0.17.4 (latest release)
Android 6.0.1
CyanogenMod 13.0-20161121-NIGHTLY-ks01lte
Samsung Galaxy S4

**Comment by Stypox** [comment] 2019-12-09 20:12
Would #2583 suit your needs? Could you provide some feedback there?

**Comment by Stypox** [comment] 2019-12-11 20:40
@cdwijs

**Comment by Stypox** [comment] 2019-12-11 20:42
Duplicate of #2171

**Closed by Stypox** 2019-12-11 20:42 UTC
Labels: GUI, enhancement
