### ISSUE TITLE
add enqueue option from outside newpipe whe video already playing

### ISSUE THREAD

**Issue by dasapa4746** [TeamNewPipe/NewPipe#8446] opened 2022-05-27 21:11 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

when youre sharing a video to newpipe and youre already playing a video on it, add an option to queue it

### Why do you want this feature?

I mostly use newpipe on pop up mode and find myself constantly wanting to play multiple videos on it from external sources (browser, other new pipe instances, other apps, etc) when i find another video to play and have one playing already (background or pop up) I have to wait for it to be over so I can send the next one, I would like to be able to enqueue videos from sources outside the newpipe app

### Additional information

here is a mockup of what it could look like (the sharing option from the browser while I have a pop up playing)
<img alt="Screenshot_20220527-180239" src="https://user-images.githubusercontent.com/106407544/170789829-8c74ba25-1657-4225-a292-ab4c1c854f7f.png" height=600 />

**Comment by SameenAhnaf** [comment] 2022-05-27 21:58
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4779

**Closed** 2022-05-28 18:37 UTC
Labels: enhancement
