### ISSUE TITLE
Network error damn near always

### ISSUE THREAD

**Issue by Zen378** [TeamNewPipe/NewPipe#11312] opened 2024-07-18 15:45 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.1

### Steps to reproduce the bug

1. Play a video
2. Shut off the phone or use the background play feature
3. Wait 30 sec
4. Video shuts off and I get network error

### Expected behavior

Play the damn music as intended

### Actual behavior

Stopping my music consistently 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=fi7U24itRaQ
* __Content Country:__ SE
* __Content Language:__ sv-SE
* __App Language:__ sv_SE
* __Service:__ YouTube
* __Version:__ 0.27.1
* __OS:__ Linux samsung/a52sxqeea/a52sxq:14/UP1A.231005.007/A528BXXU7GXDC:user/release-keys 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Linux Samsung/a52sxqeea

### Affected device model

Samsung Galaxy A52S

**Comment by lmsalustri** [comment] 2024-07-18 16:15
Duplicate of #11191

**Closed as completed** 2024-07-18 16:47 UTC
Labels: template ignored, duplicate

**Comment by Zen378** [comment] 2024-07-18 17:09
Not a duplicate of #11191 since it occurs at random time stamps and only when playing in the background, not when app is open. Seems to somewhat work, atleast a little bit better when clearing cache through phones settings, not in app settings though. Also not the same version. 0.27.0 didn't even work for me, but 0.27.1 works partially except this bug, so there is a difference between the versions as well.
