### ISSUE TITLE
Video doesn't autoplay if shared to Newpipe

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#4071] opened 2020-08-04 07:37 UTC
### Version

- dev branch after 2907

### Steps to reproduce the bug

1. Turn on Autoplay (on Wi-Fi or Always).
2. Swipe Newpipe away from Recents.
3. Share a link to Newpipe.

### Expected behavior

Video details open up and video starts playing automatically.
### Actual behaviour

Video details open up, but that's it. That's the same behaviour as if autoplay was off.

Found while investigating #2232.

**Comment by ingingin** [comment] 2020-08-04 19:56
Do you mean the video should start or autoplay doesn't work properly. That title is messy

**Comment by opusforlife2** [comment] 2020-08-04 20:00
@ingingin You're thinking of auto-**queuing** of the next stream, which is an option in settings and also a toggle on the video details page. It's incorrectly named, especially now that it conflicts with the new setting added by the unified player PR.

**Comment by opusforlife2** [comment] 2020-08-20 08:23
I think the toggle should be renamed to "Auto-play Next" or "Auto-play Next Stream". What do you think, @B0pol, @Stypox?

**Comment by avently** [comment] 2020-09-03 18:34
Actually the issue is a little bit wrong and here is why. There are couple of choices you can use right now when you share a video to NewPipe: Show Info, Video player, Popup Player, Background Player, Download. 
First option (show info) just do what it should do: it just shows the info. Auto play is not working here which is expected.
Video player option will autoplay the video if auto play is enabled globally in the app which is expected too.
Popup and background player will always play automatically which is how they should work too.

In order to enable auto play for `show info` this line should be added before this line: https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/RouterActivity.java#L459 

```java
intent.putExtra(VideoDetailFragment.AUTO_PLAY, true);
```

But it's not logical choice at all based on how options are named.

**Comment by opusforlife2** [comment] 2020-09-03 18:39
Well, yeah. Show info is incorrect if autoplay is on. I think the visibility of the Show Info option should change based on if autoplay is on or off.

With autoplay off it can continue to be:
> Show Info, Video player, Popup Player, Background Player, Download.

But with autoplay on it should be:

> Video player, Popup Player, Background Player, Download.

**Comment by opusforlife2** [comment] 2020-09-03 20:27
Ok, wait, I just tested with the Always Ask option in the latest debug apk. Both Show Info and Video Player have the exact same behaviour for autoplay off: they open the video details but don't play it. For autoplay on, both open video details, and the video additionally plays if Video Player was selected.

Now, I think a better solution than my comment above is to tweak the behaviour in this way: 
- if autoplay is off, the app should show Show Info as an option, but hide Video Player.
- if autoplay is on, the app should show Video Player as an option, but hide Show Info.

This ^ is for the Always Ask dialog when opened externally, and for the Preferred open action dialog in Settings. Moreover if Video Player is selected as the preferred open action, then turning autoplay off should replace it with Show Info, but keep that option selected, and vice versa.

I think this set of behaviours will be the most intuitive.

**Comment by avently** [comment] 2020-09-03 20:53
@opusforlife2 sounds good actually. Make this happen:)

**Comment by opusforlife2** [comment] 2020-09-03 20:56
You hurt me right in my nascent coding skills.

**Comment by TobiGr** [comment] 2020-09-09 19:46
> 
> -    if autoplay is off, the app should show Show Info as an option, but hide Video Player. (or grey it out)
> -    if autoplay is on, the app should show Video Player as an option, but hide Show Info. (or grey it out)

Do you mean the auto-play toggle in terms of auto-queue or auto-play in terms of play video automatically when detail page oepened?
I'd prefer to check for the second one.

**Comment by opusforlife2** [comment] 2020-09-09 19:47
The second one. I normally refer to auto-queue as auto-queue only.

**Comment by opusforlife2** [comment] 2020-09-09 19:47
Also, auto-queue is not related to this at all. 😆

**Comment by avently** [comment] 2020-09-10 20:35
This issue should be closed once #4259 be merged, am I right? Or you see another ways to do some things?

**Comment by opusforlife2** [comment] 2020-09-10 20:38
Apparently, we blindsided TobiGr with this because #4070 was about the same problem. 🤭 And it was your investigation which showed this was the same issue.

I don't know what he intends to do with this for now. But yes, that PR will close both this and 4070 if it is merged.

**Closed** 2020-09-27 09:20 UTC
Labels: bug
