### ISSUE TITLE
Links in description can't be copied

### ISSUE THREAD

**Issue by AnXh3L0** [TeamNewPipe/NewPipe#3253] opened 2020-03-21 16:18 UTC
### Version

- 0.18.7, latest from F-Droid

### Steps to reproduce the bug

1. Go to any video which has long links in the description.
2. Links can be clicked on and will open correctly on the browser.
3. Try to copy the link(s) and paste somewhere else.

### Expected behavior
The full link will be copied.

### Actual behaviour
A clipped version of the link is copied.

### Screenshots/Screen records
Can't provide screenshots right now.

### Logs
Not a crash, just a bug, so no logs can be provided.

**Comment by wb9688** [comment] 2020-03-21 16:27
That's because you're just copying the text, so that's not a bug. I think we should show some pop-up when you hold a link though where you could copy it (or open it or share it).

**Comment by TobiGr** [comment] 2020-03-21 16:28
@wb9688 I was about to propose the same :D

**Comment by opusforlife2** [comment] 2020-03-21 17:30
> or open it

I'd like to point out an annoying behaviour regarding this. Newpipe treats these links as 3rd party app links. You get the option to choose the app if you have multiple versions of Newpipe installed. If you open that link, your backstack is gone, it's like a new instance of Newpipe has opened.

Ideally it should just open that link if it can and add it to the backstack.

**Comment by AnXh3L0** [comment] 2020-03-21 18:12
@wb9688 in versions prior to 0.18.5 (afaik) there was no link clipping so one could copy it directly, but the pop-up option seems like a good solution for everyone.

**Comment by angriness-sleek** [comment] 2020-03-21 20:33
> That's because you're just copying the text, so that's not a bug. I think we should show some pop-up when you hold a link though where you could copy it (or open it or share it).

When there are multiple links in a video you want to copy, for example take this https://www.youtube.com/watch?v=-jBvF4zrI50, having to take a popup for every link isn't feasible

**Comment by illustribe** [comment] 2021-01-14 13:25
Why can't it just work as usual android way of long tapping onto the link and having the standard little prompt of "open/copy/share" kind of thing?
It's extremely annoying not to be able to copy the links in the description, and not even being able to read them fully -in case I'd like to type em myself. And one more thing, it's not even working as it should when one clicks on a link, cause it doesn't open the usual "select the app to open with" prompt, at least in the case of a pdf link, it takes my straight to Google drive's app, even when I do have many pdf apps installed... :/
Cheers! 🙏

**Comment by yashpalgoyal1304** [comment] 2022-01-27 10:13
i think this issue can be very well closed now, 'cz the story has long been diverged.

i would have mentioned the relevant link for where it did, but i dont remember the specifics.

**Comment by illustribe** [comment] 2022-01-27 10:28
Yes, it's actually solved anyway since the select-all button was added 👍

**Comment by yashpalgoyal1304** [comment] 2022-01-27 10:59
> select-all button

yeah, i meant that itself, but dont remember the corresponding version. if you do, then please mention it here :)

**Comment by opusforlife2** [comment] 2022-01-29 18:35
Closing as solved, then.

**Comment by yashpalgoyal1304** [comment] 2022-01-29 18:39
hi @opusforlife2 do you remember in which version that select all button was introduced?

**Comment by opusforlife2** [comment] 2022-01-29 19:03
PR: #5946.

Commit: bc3e43a

**Comment by TiA4f8R** [comment] 2022-01-29 19:13
Reopening as we are not able to copy full links on YouTube. I will open a PR which will add this ability soon.

**Closed** 2023-01-15 13:06 UTC
Labels: feature request

**Comment by yashpalgoyal1304** [comment] 2023-01-22 21:49
> Reopening as we are not able to copy full links on YouTube.

I have pasted my input regarding this over there.... umh, i just want to know which problem was fixed, as it seems all working to me
