### ISSUE TITLE
Automatic video quality

### ISSUE THREAD

**Issue by Legoks** [TeamNewPipe/NewPipe#8444] opened 2022-05-27 18:57 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

This speeds up the video opening!

### Why do you want this feature?

I'm tired of manually adjusting the quality of the video. The video is often broken!

**Comment by SameenAhnaf** [comment] 2022-05-27 19:14
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5323

**Comment by Legoks** [comment] 2022-05-27 19:15
Will you solve?

**Closed** 2022-05-27 19:50 UTC
Labels: enhancement
