### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by muhendis46** [TeamNewPipe/NewPipe#4302] opened 2020-09-21 15:38 UTC
problem of changing the tone when accelerating the sound
audio download options no mp3 format

**Comment by Stypox** [comment] 2020-09-21 16:26
Duplicate of #507; won't fix because adding an mp3 converter would greatly increase the app's size. Please use a third party converter instead

**Closed by Stypox** 2020-09-21 16:26 UTC
Labels: bug

**Comment by opusforlife2** [comment] 2020-09-21 16:42
> problem of changing the tone when accelerating the sound

Make sure the "Unhook" box is selected, and the Pitch remains at 100% no matter what the Tempo is.
