### ISSUE TITLE
Dont show video content

### ISSUE THREAD

**Issue by DwarapudiDurgasaikumar** [TeamNewPipe/NewPipe#7755] opened 2022-02-01 12:58 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment] 2022-02-01 12:59
Almost certainly a duplicate of #7734, but I can't say for sure since you did not give us any real info. Please share the error you're having, or if not, a screen recording would be helpful.

**Comment by xMxster** [comment] 2022-02-01 14:30
Yeah. Seems like something broke for all of us.

I advice you to close this, and wait for the update.

I suggest you to download F-Droid and use NewPipe Legacy meanwhile.

**Closed** 2022-02-03 08:58 UTC
Labels: bug, template-ignored, waiting-for-author
