### ISSUE TITLE
Crash after importing Youtube subscriptions

### ISSUE THREAD

**Issue by Stig124** [TeamNewPipe/NewPipe#3147] opened 2020-02-27 00:31 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ en_GB
* __Service:__ none
* __Version:__ 0.18.5
* __OS:__ Linux samsung/beyond2lteeea/beyond2:10/QP1A.190711.020/G975FXXU3BSKO:user/release-keys 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
	at org.schabi.newpipe.local.subscription.SubscriptionFragment.lambda$getSubscriptionItems$7(SubscriptionFragment.java:541)
	at org.schabi.newpipe.local.subscription.-$$Lambda$SubscriptionFragment$eFd3y39Ymdl4aGqv994n0BdEByk.compare(Unknown Source:4)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:239)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at org.schabi.newpipe.local.subscription.SubscriptionFragment.getSubscriptionItems(SubscriptionFragment.java:539)
	at org.schabi.newpipe.local.subscription.SubscriptionFragment.handleResult(SubscriptionFragment.java:522)
	at org.schabi.newpipe.local.subscription.SubscriptionFragment$4.onNext(SubscriptionFragment.java:498)
	at org.schabi.newpipe.local.subscription.SubscriptionFragment$4.onNext(SubscriptionFragment.java:489)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

```
</p></details>
<hr> 
This crash happens when you're importing Youtube subsciption list and leaving the page with the youtube link using the back key, It crashes and never opens again

**Comment by Stypox** [comment] 2020-02-27 13:37
Could you provide the subscriptions file (only if you don't think this does violates your privacy)?

**Comment by Stypox** [comment] 2020-03-08 09:42
Duplicate of #2784

**Closed by Stypox** 2020-03-08 09:42 UTC
Labels: bug, more info needed
