### ISSUE TITLE
No Next Songs Recommendations on Background Player

### ISSUE THREAD

**Issue by goxr3plus** [TeamNewPipe/NewPipe#1688] opened 2018-09-09 10:11 UTC
In the previous versions of NewPipe when streaming a song in the background player i had recommendations for next audios but now nothing... only the main audio.

 I installed NewPipe 14.1 apk from latest release on github :) 

![](https://i.imgur.com/BXf7Ccy.png)

![](https://i.imgur.com/RBaE8qI.png)

_Sent from my Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ReekyMarko** [comment] 2018-09-09 11:10
Duplicate of #1678

**Closed** 2018-09-09 17:09 UTC
