### ISSUE TITLE
option to remember playback speed

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#1995] opened 2019-01-10 06:14 UTC
Please add an option to remember playback speed.

**Comment by Tikotik** [comment] 2019-03-21 03:56
Duplicate of #1924

**Comment by 532910** [comment] 2019-03-21 07:35
It's not exactly "duplicate".

**Comment by Stypox** [comment] 2019-08-28 21:15
Duplicate of #735

**Closed by Stypox** 2019-08-28 21:15 UTC

**Comment by 532910** [comment] 2019-08-28 21:36
It's no a duplicate of #735, but another setting.

**Comment by Stypox** [comment] 2019-08-28 21:41
As theScrabi said there, there will be no new setting, at least not in the settings screen. Also the discussion is in #735, and even though the request is different the base problem is the same, so only one way to do this will be chosen.
