### ISSUE TITLE
Strange behavior when connected to car bluetooth

### ISSUE THREAD

**Issue by nate2014jatc** [TeamNewPipe/NewPipe#1619] opened 2018-08-22 15:01 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [?] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

HI,
Whenever my phone connects to my car's Bluetooth, newpipe spawns a player on its own, that tries to play literally nothing. I can't pause the "playback" and when I kill the player notification, it immediately comes back until I disconnect my phone from my car manually.

**Comment by ReekyMarko** [comment] 2018-08-28 07:14
Do you by chance have a Xiaomi Roidmi bluetooth adapter? I had this same problem and after I removed the Roidmi app, this bevaviour disappeared.

**Comment by nate2014jatc** [comment] 2018-08-28 15:36
I do not have a Xiaomi Roidmi Bluetooth device.
I'll look into it and see if I have anything similar though. 

On August 28, 2018 1:14:22 AM MDT, Marko Korhonen <notifications@github.com> wrote:
>Do you by chance have a Xiaomi Roidmi bluetooth adapter? I had this
>same problem and after I removed the Roidmi app, this bevaviour
>disappeared.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TeamNewPipe/NewPipe/issues/1619#issuecomment-416476387

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brimston3** [comment] 2018-09-05 22:06
I get this behavior as well, but it's probably not a NewPipe issue per se. On connect, the last media player I had playing is launched and audio is started from that software (eg, vlc, pocketcasts resumes playback). In the case of NewPipe, the background player launches, but it shows "unknown" as the track info. Mine, on the other hand, does not try to relaunch if I close the newpipe notification -- my guess at @nate2014jatc's issue is buggy AVRCP behavior by the bluetooth sink.

**Comment by nate2014jatc** [comment] 2018-09-07 01:05
What's really strange in my case is that it's almost always Newpipe, regardless of what I was using before. It's even overridden Spotify (the grabbiest music player I could think of). 

On September 5, 2018 4:06:15 PM MDT, brimston3 <notifications@github.com> wrote:
>I get this behavior as well, but it's probably not a NewPipe issue per
>se. On connect, the last media player I had playing is launched and
>audio is started from that software (eg, vlc, pocketcasts resumes
>playback). In the case of NewPipe, the background player launches, but
>it shows "unknown" as the track info. Mine, on the other hand, does not
>try to relaunch if I close the newpipe notification -- my guess at
>@nate2014jatc's issue is buggy AVRCP behavior by the bluetooth sink.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/TeamNewPipe/NewPipe/issues/1619#issuecomment-418897040

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by theScrabi** [comment] 2018-09-07 10:39
Noticed this as well. We need to fix it.

**Comment by theScrabi** [comment] 2018-09-08 14:02
Its propably newpipe itself.

**Comment by theScrabi** [comment] 2018-09-20 16:10
But stearing and brakes still work? 🤔

**Comment by NeoFromMatrix** [comment] 2018-12-28 02:41
same behavior with moto g5 android 8.1

**Comment by skontar** [comment] 2019-11-12 07:50
I have the same problem with Samsung A40 and Samsung S10e when they connect to my car Bluetooth. Does not happen with other Bluetooth devices (and any other players for that matter). Anything I can help with?

**Comment by Liknus** [comment] 2020-03-10 12:27
Same problem: as soon as my OnePlus 6 connect to the Sync2 of my Ford I get an empty notification.. 
Newpipe v.0.18.4 on Android 10..

**Comment by Offerel** [comment] 2020-04-29 18:34
I can confirm that behavior on a Galaxy S9 with Android 10. The last audio app is Media Monkey. But when it connected to the car BT, always NewPipe take control. It would be nice, if we could get an option, where we could disable automatic react to BT connects. I have no other idea if there is a workaround

**Comment by wb9688** [comment] 2020-04-29 18:39
@Offerel: Could you test whether #3178 fixes it by any chance?

**Comment by Offerel** [comment] 2020-05-01 19:02
@wb9688 i have re-tested it today with the actual release version an the commit from above. I cant reproduce it either. The issue seems to be gone, after i removed the default associations from all involved apps. After that, i re-added the associations, but the problem seems to be disappeared.

**Comment by Stypox** [comment] 2020-05-17 11:07
Duplicate of #1574

**Closed by Stypox** 2020-05-17 11:07 UTC
Labels: bug

**Comment by amosnet** [comment] 2020-12-30 14:07
> I have the same problem with Samsung A40 and Samsung S10e when they connect to my car Bluetooth. Does not happen with other Bluetooth devices (and any other players for that matter). Anything I can help with?

It's been more than a year and the same thing is still there with my Samsung S10, only when it connects to the car, pretty weird.

Not sure if it is affected only to Samsungs when they connect to cars.
