### ISSUE TITLE
Download queue deletion bug

### ISSUE THREAD

**Issue by Tini4** [TeamNewPipe/NewPipe#7140] opened 2021-09-21 18:19 UTC
### Checklist

- [x] I am using the latest version - 0.21.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Queue up some downloads.
2. Before they are finished, disconnect the internet.
3. The queued downloads disappear.

### Actual behavior

The queued downloads disappear.

### Expected behavior

This did not happen in the previous versions. Before, the downloads waited for you to get back online, where you could resume them. Sometimes the one that is in the middle of being downloaded is broken, and you have to go and overwrite it, but that is ok since you know which one it is. Now everything disappears, and you have to search for all the videos to download again.

### Device info

 - Android version/Custom ROM version: 11, August 5, 2021
 - Device model: realme 7 Pro

**Comment by mhmdanas** [comment] 2021-09-22 19:16
Duplicate of #7059.

**Closed by mhmdanas** 2021-09-22 19:16 UTC
Labels: bug
