### ISSUE TITLE
[Feature request] Bookmarking, pop out video to youtube video page and other UI improvements in full screen?

### ISSUE THREAD

**Issue by fightthepower** [TeamNewPipe/NewPipe#2186] opened 2019-03-06 07:05 UTC
I use New Pipe as the default player in my phone. So whenever I click a youtube link in a third party app the video open as full screen in New Pipe

Problem
- Can't pop out to the running videos youtube page so cant read comments, see recommended pages , subscribe to that channel or add the video to playlist/bookmarking

Recommendation.
- New Pipe's UI in full screen should be something similar to that of [SkyTube's](https://github.com/ram-on/SkyTube)
- Swipe up,down,left and right border to get video description, Current behaviour, recommended videos, comments respectively

The **current biggest problem** is when we pop out the video it should directly go to the videos page instead of current behaviour

**Comment by yausername** [comment] 2019-03-06 07:14
Well, you can set your preferred way of opening links settings.
Settings->Video&Audio->Preferred 'open' action->Show info

**Comment by fightthepower** [comment] 2019-03-06 08:29
Still it doesn't solve the main problem. Can't go to the running videos video page or add the video to playlist or subscirbe to the channel

**Comment by yausername** [comment] 2019-03-06 08:40
You can do all of those in pop up mode.

**Comment by fightthepower** [comment] 2019-03-06 09:33
@yausername  I am either miscommunicating or  facing a new pipe bug. Either way I will explain the problem step wise

- Make New Pipe as the default video player app for your device
- Assume that in here Settings->Video&Audio->Preferred 'open' action-> we selected pop up or full screen it doesn't matter and completely close the new pipe app.
- Now open a **third pary** app (not the new pipe app) in which we have selected new pipe as the default video player and  and open a youtube link from this third party app
- A video starts playing in pop up, background, full screen depending upon our New pipe settings.

Here comes the problem.
- From here we can't go to the playing video's home page or do these things
> Can't go to the running videos page or add the video to playlist or subscirbe to the channel or view comments or view recommended videos.

I tried many times it doesn't work. If it helps I reported another bug I am facing with new pipe https://github.com/TeamNewPipe/NewPipe/issues/2125

**Comment by yausername** [comment] 2019-03-06 09:41
When you use the setting Show info
Settings->Video&Audio->Preferred 'open' action->Show info
It will open the video detail page when you navigate via third party apps.
You can then choose pop up from there.

**Comment by fightthepower** [comment] 2019-03-06 09:48
Thank you I misunderstood `show info`  I thought it shows some basic info of the video like description. But again it would be nice if we can go to the  videos page from popup and full screen. I have to do additional clicks to play the video according to the suggestion. 

Any way this partially solved my problem but I think I should not close this issue/feature request. What do you think?

**Comment by yausername** [comment] 2019-03-06 17:33
I think it would be nice to have this feature.

**Comment by burneracc69** [comment] 2019-03-19 07:29
#1975

**Comment by theScrabi** [comment] 2019-03-19 16:09
Uff honestly my guess is that this would add big changes for little advantage. I'm not a fan of also showing the commends/description during the playtime of a video.

**Comment by fightthepower** [comment] 2019-03-20 03:16
@theScrabi The comments/description will be hidden in the full screen unless we swipe to unhide it. Basically in skytube we can swipe to hide and unhide comments in fullscreen.

**Comment by ildar** [comment] 2019-05-22 03:45
what about: tap on newpipe in notifications, you get the play list, there you long-tap on the video.
?

**Comment by Stypox** [comment] 2019-09-27 05:20
Duplicate of #1873

**Closed by Stypox** 2019-09-27 05:20 UTC
