### ISSUE TITLE
Guru Meditation when you delete videos one at a time

### ISSUE THREAD

**Issue by Diamond-Back** [TeamNewPipe/NewPipe#6035] opened 2021-04-09 17:21 UTC
Never-ending severe instability. Always when you delete videos one at a time. I don't know how many updates it has been, but this bug persists the majority of the time.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux motorola/ali_amz/ali:8.0.0/OPS27.104-92/100:user/release-keys 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.remove(ArrayList.java:506)
	at org.schabi.newpipe.local.LocalItemListAdapter.removeItem(LocalItemListAdapter.java:129)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.deleteItem(LocalPlaylistFragment.java:602)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$23(LocalPlaylistFragment.java:780)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$23$LocalPlaylistFragment(Unknown Source:0)
	at org.schabi.newpipe.local.playlist.-$$Lambda$LocalPlaylistFragment$mqVZbx-Y0Wr3WWOrkG9BVt02WwI.onClick(Unknown Source:4)
	at org.schabi.newpipe.util.StreamDialogEntry.clickOn(StreamDialogEntry.java:144)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$24(LocalPlaylistFragment.java:783)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$24$LocalPlaylistFragment(Unknown Source:0)
	at org.schabi.newpipe.local.playlist.-$$Lambda$LocalPlaylistFragment$DKJcisObqgB6j43xoqruTCAJLOE.onClick(Unknown Source:4)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1142)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3160)
	at android.widget.AbsListView$3.run(AbsListView.java:4075)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6694)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-04-10 07:34
Duplicate of #3891.

**Closed by mhmdanas** 2021-04-10 07:34 UTC
