### ISSUE TITLE
More options on creator pages

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#5498] opened 2021-01-27 16:39 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I would enjoy more features on channel pages. There are currently tab options in newpipe such as 'listen in background', 'play all,' and 'popup', and i would imagine a solution using these same tabs like in regular youtube.

I would like the layout as the following:

1: VIDEOS - all the videos with the recently uploaded ones. (Basically what it looks like now) could have sorting options in a drop down menu like Oldest, Recent, Most viewed (e.i: Popular) etc.

2: PLAYLIST - Lists all the playlists of the channel (additional playlist support?)

3: CHANNELS - Lists all subscriptions and and connected channels

3: ABOUT - Could list all the properties the channel has: description, creation date, views, other social media

#### Is your feature request related to a problem? Please describe it

No.

#### Additional context

![IMG_20210127_173642](https://user-images.githubusercontent.com/74684948/106022562-460d4d00-60c6-11eb-8090-6ca0ee36bbed.jpg)

#### How will you/everyone benefit from this feature?

More versatile channel navigation and options.

**Comment by shivasagarrao** [comment] 2021-01-28 11:28
Duplicate of [#2414](https://github.com/TeamNewPipe/NewPipe/issues/2414)

**Comment by mhmdanas** [comment] 2021-02-10 08:40
@Hogerys mind opening separate issues for the channels and about tabs? There's already #5203 for playlists. Thanks in advance!

**Closed by mhmdanas** 2021-02-10 08:40 UTC
Labels: enhancement
