### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Shiryu862** [TeamNewPipe/NewPipe#7345] opened 2021-11-01 21:47 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ PeerTube
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:488)
	at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:503)
	at org.schabi.newpipe.util.ListHelper.$r8$lambda$UGNhfSv5KuYwsqrcThyeG189sI0(Unknown Source:0)
	at org.schabi.newpipe.util.ListHelper$$ExternalSyntheticLambda0.compare(Unknown Source:4)
	at java.util.Collections$ReverseComparator2.compare(Collections.java:5235)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at org.schabi.newpipe.util.ListHelper.sortStreamList(ListHelper.java:269)
	at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:243)
	at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:130)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1579)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6(VideoDetailFragment.java:890)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$X-UcNln23jPsop2TvHe2VPTu0NQ(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda10.accept(Unknown Source:8)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8577)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

**Comment by litetex** [comment] 2021-11-01 22:30
Duplicate of #6860

**Closed by litetex** 2021-11-01 22:30 UTC
Labels: bug, template-missing
