### ISSUE TITLE
Sort By Date Feature

### ISSUE THREAD

**Issue by mehedihasanziku** [TeamNewPipe/NewPipe#3257] opened 2020-03-22 16:09 UTC
I would like to see this feature in newpipe, it will help us to find latest videos faster instead of scrolling.

![IMG_20200322_220456_884](https://user-images.githubusercontent.com/48652123/77254176-ac953380-6c89-11ea-974a-25f2d55050ec.JPG)

Hope Team NewPipe will implement this feature very soon.

**Comment by Stypox** [comment] 2020-03-22 16:44
Closed in #2309

**Closed by Stypox** 2020-03-22 16:44 UTC
Labels: enhancement

**Comment by Stypox** [comment] 2020-03-22 16:55
Oh and if this is about search it is a duplicate of #2251

**Comment by mehedihasanziku** [comment] 2020-03-22 17:22
Yes, it was about search filter.

**Comment by rithans** [comment] 2020-04-16 09:53
additional sorting option will be also useful to everyone to sort playlist  by alphabetically and by last played.

**Comment by mehedihasanziku** [comment] 2020-04-16 09:56
recent filter really required....
