### ISSUE TITLE
Recaptcha failure

### ISSUE THREAD

**Issue by Bigdave290** [TeamNewPipe/NewPipe#8184] opened 2022-04-12 19:28 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Click Solve
405 error occurs

### Expected behavior

Allow captcha generation

### Actual behavior

Google gives this warning:
405. That’s an error.

The request method GET is inappropriate for the URL /youtubei/v1/guide. That’s all we know.

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Note 20

**Comment by delthas** [comment] 2022-04-12 19:29
Duplicate of #8183 .

**Closed** 2022-04-12 19:35 UTC
Labels: bug
