### ISSUE TITLE
zoom in feature

### ISSUE THREAD

**Issue by Nit-nit** [TeamNewPipe/NewPipe#8341] opened 2022-05-02 21:26 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

can i request for a zoom in feature, because as a mobile developer, i need to see code in a popup video and it is really small, in this case, i want to zoom the video to make it bigger while using the popup
<img alt="Screenshot_2022-05-03-02-50-22-241_com rhmsoft edit" src="https://user-images.githubusercontent.com/94877880/166330173-fd0747d4-8523-450b-927b-a2ce59e68965.jpg" height=600 />

### Why do you want this feature?

because i want to multitask, i needed an application who could show me code through a floating window while im coding on mobile

### Additional information

bring back youtube dislikes lol, change app theme to totally black instead of having red headers, we need an illustration instead of a sad face when something goes wrong because its better.

**Comment by pc00per** [comment] 2022-05-02 21:41
Duplicate of #7179
Also as per #7469, RYD project was never approved by the NewPipe team.
And the red header you asking to make it pitch black, it's NewPipe's trade theme & I guess it can't be changed.

**Comment by SameenAhnaf** [comment] 2022-05-02 23:35
#7179 is actually about adjusting aspect ratio intended to remove marjins and customizing length and width of the video. This is actually a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1406 which asks to zoom in any specific part of the video.

**Closed** 2022-05-03 15:48 UTC
Labels: enhancement

**Comment by Nit-nit** [comment] 2022-05-09 05:42
anyways i found the solution, opening split screen and zooming in youtube.com is better![Screenshot_2022-05-09-11-10-58-297_com.rhmsoft.edit.jpg](https://user-images.githubusercontent.com/94877880/167347472-590d0a7d-9d4e-430e-b192-f320896dede3.jpg)
