### ISSUE TITLE
string ioob error when typing in search bar

### ISSUE THREAD

**Issue by castropointer** [TeamNewPipe/NewPipe#7018] opened 2021-08-29 21:47 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.21.3
* __OS:__ Linux HUAWEI/AMN-L29EEA/HWAMN-M:9/HUAWEIAMN-LX9/9.1.0.300C431:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.StringIndexOutOfBoundsException: length=9; index=10
	at java.lang.String.substring(String.java:2032)
	at java.lang.String.subSequence(String.java:2079)
	at android.widget.TextView.onProvideAutoStructureForAssistOrAutofill(TextView.java:11006)
	at android.widget.TextView.onProvideStructure(TextView.java:10909)
	at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8718)
	at android.view.View.dispatchProvideStructure(View.java:8666)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
	at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:519)
	at android.app.assist.AssistStructure.<init>(AssistStructure.java:2047)
	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3794)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-08-30 02:47
Duplicate of #5382. Please try again on the latest version (0.21.9 at the time) and if you get the same error, please make a new issue that follows the template properly.

**Closed by mhmdanas** 2021-08-30 02:47 UTC
Labels: bug
