### ISSUE TITLE
Add a button, to switch from hover player to fullscreen 

### ISSUE THREAD

**Issue by JPluess** [TeamNewPipe/NewPipe#6663] opened 2021-07-14 21:58 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Please add a back to fullscreen button in the hover player see image below. 

#### Is your feature request related to a problem? Please describe it

No, just more convenient and easy to implement 

#### Additional context

Pls see image

![20210714_234014](https://user-images.githubusercontent.com/7995240/125698345-759c6d7c-0cfd-4bc5-b65e-8d6bf8cefb43.jpg)

#### How will you/everyone benefit from this feature?

Faster, direct, more convenient.

**Comment by JPluess** [comment] 2021-07-14 22:03
![20210714_235940](https://user-images.githubusercontent.com/7995240/125698956-3a2ad06f-bd48-42fb-8df2-b342c5c07e5a.jpg)

**Comment by SameenAhnaf** [comment] 2021-07-14 22:42
You may keep the discussion in #1832 to discuss how the buttons may be placed.

**Comment by mhmdanas** [comment] 2021-07-15 09:54
Closing as duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5845 and #1832.

**Closed by mhmdanas** 2021-07-15 09:54 UTC
Labels: enhancement
