### ISSUE TITLE
Unable to view live streams on YouTube shortly after airing

### ISSUE THREAD

**Issue by Flat** [TeamNewPipe/NewPipe#3088] opened 2020-02-12 17:44 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When trying to view a video such as https://youtu.be/I7_t4e-QTGw NewPipe will load comments and nothing else.
![Screenshot_20200212-084029_NewPipe](https://user-images.githubusercontent.com/2048861/74361433-e757a200-4d94-11ea-9c3a-e4161ddf430d.png)

After around 5 hours since the end of the broadcast NewPipe will correctly load the video. The video loads fine in browser and official app. As a side note youtube-dl seems to have some erroneous output when trying to download the video such as the total file size changing often. This makes me believe it may be a DASH or video format issue.

I will try to reproduce in an emulator later to see if I may be able to find more information regarding this.

Edit: Stack trace of error when trying to play video https://gist.github.com/Flat/e3b39559718742e02232f1958851e755

For some reason the video initially loads fine in my emulator, but is unable to play. Whereas on my actual device (Galaxy Note10+ Snapdragon) it fails to load anything but the comments as shown in the screenshot above.

**Comment by opusforlife2** [comment] 2020-08-15 07:59
Duplicate of #3336.

**Closed by opusforlife2** 2020-08-15 07:59 UTC
Labels: bug, youtube
