### ISSUE TITLE
Thumbnail size

### ISSUE THREAD

**Issue by NAVY7771** [TeamNewPipe/NewPipe#8439] opened 2022-05-26 11:28 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Go to settings and apperance.
2. Change the List view mode to GRID.
3. The thumbnail size does not take the entire size horizontally accross the screen in portrait mode of phone.

Don't know if this is a bug or it is meant to be but it would be better if the thumbnail acts like it does in the YouTube app.

### Screenshots/Screen recordings

<img alt="Screenshot_2022-05-26-16-49-44-96_ee8807d2de22f1831269d80920e33a3b" src="https://user-images.githubusercontent.com/94772802/170479121-61192bc0-4435-4bc7-b8a3-976dc98eca35.jpg" height=600 />

### Affected Android/Custom ROM version

Android 11

**Comment by SameenAhnaf** [comment] 2022-05-26 15:02
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6087

**Closed** 2022-05-27 20:57 UTC
Labels: bug
