### ISSUE TITLE
Add "save playlist as txt file" and "upload playlist as txt file" 

### ISSUE THREAD

**Issue by Nuktos** [TeamNewPipe/NewPipe#7037] opened 2021-09-01 14:24 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Hi! So, the title says it all, I just would like to be able to prepare a playlist from somewhere else, like on my computer, and simply inject it in NewPipe. I'm not a programmer but it seems fairly easy to implement, I suppose? The .txt format isn't necessary, but just a format that is easy to use for anyone. 
Thank you! 

#### How will you/everyone benefit from this feature?

I think it would be a nice feature to make playlists easily, faster and share them between different users. It could be cool to share them in one click without having to make a public playlist on a YouTube account.

**Comment by SameenAhnaf** [comment] 2021-09-01 16:40
Duplicate of #1788.

**Closed** 2021-09-02 11:03 UTC
Labels: enhancement
