### ISSUE TITLE
Better Playlist Management

### ISSUE THREAD

**Issue by voiceofvraja** [TeamNewPipe/NewPipe#5327] opened 2021-01-01 06:45 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Ability to sort playlists (referring to #5202)

**Comment by mhmdanas** [comment] 2021-01-01 10:45
Duplicate of #5237.

**Closed by mhmdanas** 2021-01-01 10:45 UTC
Labels: enhancement
