### ISSUE TITLE
Crash during share from Downloads inside app

### ISSUE THREAD

**Issue by Suncatcher** [TeamNewPipe/NewPipe#3105] opened 2020-02-17 07:53 UTC
![photo_2020-02-17_09-45-34](https://user-images.githubusercontent.com/6388034/74633427-4ee16900-516a-11ea-8878-5b6e34b7cb0e.jpg)

Steps to reproduce:

1. Go to Downloads folder inside app via three-dot button
2. Click Share on any video
![Inkedphoto_2020-02-17_09-49-18_LI](https://user-images.githubusercontent.com/6388034/74633726-f52d6e80-516a-11ea-8cac-b6353a6373d5.jpg)
3. Crash!

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ v0.18.3
* __OS:__ Linux xiaomi/onc/onc:9/PKQ1.181021.001/V11.0.2.0.PFLMIXM:user/release-keys 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
android.os.FileUriExposedException: file:///storage/emulated/0/Movies/NewPipe/%D0%9D%D1%83%20%D0%B7%D0%B0%D1%87%D0%B5%D0%BC%20%D1%82%D1%8B%20%D0%BD%D0%B0%20%D0%BD%D0%BE%D1%87%D1%8C%20%D0%B6%D1%80%D0%B5%D1%88%D1%8C%20_.mp4 exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
	at android.net.Uri.checkFileUriExposed(Uri.java:2371)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:963)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10252)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10258)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10237)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
	at android.app.Activity.startActivityForResult(Activity.java:4651)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at android.app.Activity.startActivityForResult(Activity.java:4609)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
	at android.app.Activity.startActivity(Activity.java:4970)
	at android.app.Activity.startActivity(Activity.java:4938)
	at us.shandian.giga.ui.adapter.MissionAdapter.shareFile(MissionAdapter.java:384)
	at us.shandian.giga.ui.adapter.MissionAdapter.handlePopupItem(MissionAdapter.java:661)
	at us.shandian.giga.ui.adapter.MissionAdapter.access$200(MissionAdapter.java:85)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$buildPopup$3$MissionAdapter$ViewHolderItem(MissionAdapter.java:934)
	at us.shandian.giga.ui.adapter.-$$Lambda$MissionAdapter$ViewHolderItem$RgJD8t6gH83XiFLVb3LGB9-h96A.onMenuItemClick(Unknown Source:2)
	at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1198)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3178)
	at android.widget.AbsListView$3.run(AbsListView.java:4132)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

```
</p></details>
<hr>
`

**Comment by XiangRongLin** [comment] 2020-02-17 20:30
Duplicate of #3045

**Closed** 2020-02-17 20:49 UTC
Labels: bug, downloader
