### ISSUE TITLE
"Install missing kore app" message is shown when attempting to play a youtube video to kodi, even though the kodi app is installed (NewPipe legacy works without a problem)

### ISSUE THREAD

**Issue by ivanr3** [TeamNewPipe/NewPipe#5920] opened 2021-03-27 09:35 UTC
"Install missing kore app" message is shown when attempting to play a youtube video to kodi, even though the kodi app is installed (NewPipe legacy works without a problem).

**Comment by mhmdanas** [comment] 2021-03-27 09:54
Duplicate of #5599.

**Closed by mhmdanas** 2021-03-27 09:54 UTC
