### ISSUE TITLE
Smartphone Video Orientation 

### ISSUE THREAD

**Issue by angelopouloschristos** [TeamNewPipe/NewPipe#8778] opened 2022-08-13 19:18 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1) Open the app (hold the phone portrait mode)
2) Go to "New Video's" -> in french "nouveautés" 
3 AND 4) Choose a video AND ...
3 AND 4) While the video loads, turn the smartphone landscape (horizontal)

### Expected behavior

The video should be full screen in landscape mode (horizontal).

### Actual behavior

The video is actualy NOT in full screen. Its in minimized/reduced on the top left corner, 1/4 of the actual full screen with black screen all around it.

### Screenshots/Screen recordings

![photo_2022-08-13_21-12-47](https://user-images.githubusercontent.com/80044056/184507625-1bd02c34-0d8b-47c7-b25d-462bcdb66d1e.jpg)
![photo_2022-08-13_21-03-57 (3)](https://user-images.githubusercontent.com/80044056/184507631-7031012d-b879-4da1-bb85-768e5e8acd80.jpg)

### Affected Android/Custom ROM version

Android 12 / Version One UI 4.1 (last update 1 August 2022) 

### Affected device model

Samsung Galaxy S21 Ultra

### Additional information

There is 2 ways to fix it WITHOUT changing something in the code.

1) First solution  : 
turn back the phone portrait (vertical), stop the video, turn the phone landscape(horizontal) , continue the video and it will display full screen no problem.

2) Second solution : 
keep turning your phone from landscape mode (horizontal) to portrait (vertical) without stopping the video, after (random times but more than 10) it works.

**Comment by AudricV** [comment] 2022-08-13 20:43
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #7262. Please search (better, with different keywords?) for duplicates the next time you want to open an issue.

This should be fixed in the next regular update. (You can already try the fix by using an APK of the dev branch).

Thank you.

**Closed by AudricV** 2022-08-13 20:43 UTC
Labels: bug, needs triage
