### ISSUE TITLE
Sleep timer feature request...

### ISSUE THREAD

**Issue by lemniscated** [TeamNewPipe/NewPipe#7622] opened 2022-01-06 22:02 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

I would like to request for a feature (which most you must be aware of...if not I'll be explaning it.) known as sleep timer....
With its help we can set timer for songs...i.e. after the timer ends the music will stop by itself...thereby saving resources...like battery and data charges...

#### Why do you want this feature?

It can help save battery and data charges.....plz add two options for the timer...
First can be for a set period of time....i.e. newpipe will stop it's stream or the video after streaming for the time set by user....

Second can be for a set number of videos....i.e. newpipe will stop it's stream or the video after playing a certain number of videos set by the user.....

Thank u very much for considering these...

**Comment by tsiflimagas** [comment] 2022-01-06 22:08
Duplicate of #2830. A Foss alternative was suggested there.

**Comment by lemniscated** [comment] 2022-01-06 22:15
> Duplicate of #2830. A Foss alternative was suggested
Can you plz attach a hyperlink to #2830...?!

**Comment by lemniscated** [comment] 2022-01-06 22:22
> Duplicate of #2830. A Foss alternative was suggested there.

Ok so...I checked it.....but still....isn't it great to have this feature as its native one rather than installing another app from somewhere else.....
I would request the developers to please acknowledge this....
I'm hoping to see this feature in the upcoming update....

**Comment by MD77MD** [comment] 2022-01-06 23:08
this would be a great thing to add.. and it's easy too I would guess

**Comment by litetex** [comment] 2022-01-07 13:29
Duplicate of #2830

**Closed by litetex** 2022-01-07 13:29 UTC
Labels: enhancement
