### ISSUE TITLE
Android buttons don't show (white on white?) in light mode

### ISSUE THREAD

**Issue by johanw666** [TeamNewPipe/NewPipe#5248] opened 2020-12-22 10:53 UTC
### Checklist

- [x] I am using the latest version - 0.20..6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Select light mode
2. In some screens the Android buttons (back, home, apps) don't show. They do work if you press the location where they should be so I assume it is just white text on a white background.
3. This is not happening on all devices: on Android 4, 5 and 6 this worled OK (the screen area where the buttons where located was black, even in light mode). But on this device (Android 10, Samsung A50) that areea is white too.

### Screenshots/Screen recordings
![Screenshot_20201222-114605_NewPipe](https://user-images.githubusercontent.com/8427572/102880858-432a9700-444c-11eb-8352-f1c7694a236c.jpg)

### Device info

 - Android version/Custom ROM version: 10, stock ROM.
 - Device model: Samsung A50

Edit: now I see the scrteenshot on a large screen I do notice the buttons, but very faint against the background. On my phone I can't see them.

**Comment by mhmdanas** [comment] 2020-12-26 18:45
Thanks for opening an issue! I can't see this bug in the screenshot. Could you take a screenshot that actually showcases the bug?

**Comment by johanw666** [comment] 2020-12-26 23:56
The back, home and app list buttons do show on the screenshot but with a very poor contrast. I can see them when I watch on my laptop but not on my phone. Don't you see the 3 buttons in the bottom of the screenshot or don't you think this is an issue?

**Comment by amir0159** [comment] 2020-12-27 00:38
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=ZMZ541mwdfY
* __Content Country:__ IR
* __Content Language:__ fa-IR
* __App Language:__ fa_IR
* __Service:__ YouTube
* __Version:__ 0.20.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: YouTube did not
provide player config even after three attempts
 at
org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:664)
 at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
 at
org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
 at
org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
 at
org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
 at
org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown
Source:4)
 at
io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at
io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at
io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at
io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
 at
io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
 at
io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
 at
io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at
io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at
io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at
io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
 at
io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 at
io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>


در تاریخ شنبه ۲۶ دسامبر ۲۰۲۰،‏ ۲۲:۱۶ Mohammed Anas <notifications@github.com>
نوشت:

**Comment by mhmdanas** [comment] 2020-12-27 07:00
@amir0159 upgrade to 0.20.7 to fix that (https://github.com/TeamNewPipe/NewPipe#updates).

@johanw666 oh, sorry, I just got what you meant. I thought you were talking about the buttons at the top of the screen and was a bit confused.

**Comment by amir0159** [comment] 2020-12-27 12:44
hi mohamad

Well, I was giving this error
message at the same time, I thought it was some kind of bug. It appeared
regularly, especially in older versions. This error was common when
searching and loading pages with high data volumes. I just installed the
new version 0.20.7 and I do not have experience with it yet, but I assure
you that I will send you the first error and bug message. Anyway, I will
send you another copy of that error in another format, maybe it will help
your work. Another issue is what is the difference between niwpipe and
niwpipe legacy, and I read somewhere that niwpipe has a released version of
peertub that also has a complete library of PeerTube examples. Is there
such a version ??
Thanks for the tips on peertube. If I have a problem, I will consult with
you.
------------------------------------

**Comment by mhmdanas** [comment] 2020-12-27 12:49
@amir0159 There's no need to send me the error; it's fixed for sure.

As for the difference between NewPipe and NewPipe Legacy, NewPipe Legacy is for older versions of Android. NewPipe supports 4.4+, while NewPipe Legacy supports 4.1+.

Regarding PeerTube, no, we don't run a PeerTube instance. NewPipe just act as a frontend for PeerTube, which isn't different from YouTube and the other services in this regard.

**Comment by Stypox** [comment] 2021-01-15 15:13
This is an issue with the ROM and can't be fixed by us. Also, this is a duplicate of something

**Closed by Stypox** 2021-01-15 15:13 UTC
Labels: GUI, bug

**Comment by amir0159** [comment] 2021-01-21 17:45
hi I'm proud to have friends like you

For guidance, I really thank this is your
credit. New Pipe has a Multiple versions. I try to get used to one because
some versions do not support the other version's data. If you know a
version that has a better prize Introduce . I wanted another subject in
another email, but I summarize in an email. 1 (This app:
https://ucmate.info/?Ref=appse does it communicate to New Piper? I know
that the NewPayp is open source, and the reason for my choice is its open
source because it is more reliable and its components are quite clear. If
anyone knows, please I received this program from one of my friends

در تاریخ یکشنبه ۲۷ دسامبر ۲۰۲۰،‏ ۱۶:۱۹ Mohammed Anas <
notifications@github.com> نوشت:

**Comment by mhmdanas** [comment] 2021-01-21 20:08
@amir0159 that is the first time I see that app. Taking a look at their screenshots, it does indeed look like that app is based on NewPipe. However, the website itself is extremely suspicious. I don't see a link to the app's source code anywhere in the website too. With that being said, I would advise against installing it.

**Comment by amir0159** [comment] 2021-01-27 17:10
Hello, thank you for your attention. I do not understand what you mean. You
say that the website of this app has a problem? I still have it installed
and I use it for Spotify. If there is a problem, I will delete it faster.
Honestly, this is the second app I see made in terms of user interface
similar to newpipe.

To make this app too:


https://www.vanced.pro/


در تاریخ پنجشنبه ۲۱ ژانویهٔ ۲۰۲۱،‏ ۲۳:۳۸ Mohammed Anas <
notifications@github.com> نوشت:

**Comment by amir0159** [comment] 2021-03-12 07:25
I had seen a few with the incorrect use of the Newpiap source, but this app
level up and apparently from advertising revenue. I am the user and can not
bear. the friends who tried and coded for this app and try to improve it,
and monitor how they can ignore such a false use of their orientation.
Useed for personal benefits from NewPayp and Logo Videoder

**Comment by amir0159** [comment] 2021-03-12 07:29
---------- Forwarded message ---------
فرستنده: amir gh ***@***.***>
‪Date: جمعه ۱۲ مارس ۲۰۲۱،‏ ۱۰:۵۵‬
Subject: [TeamNewPipe/NewPipe] Android
To: TeamNewPipe/NewPipe <
***@***.***>


I had seen a few with the incorrect use of the Newpiap source, but this app
level up and apparently from advertising revenue. I am the user and can not
bear. the friends who tried and coded for this app and try to improve it,
and monitor how they can ignore such a false use of their orientation.
Useed for personal benefits from NewPayp and Logo Videoder
