### ISSUE TITLE
Comments on comments are not shown.

### ISSUE THREAD

**Issue by TontyTon** [TeamNewPipe/NewPipe#4473] opened 2020-10-09 21:08 UTC
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any popular video
2. Open the video in official app or website to check if there are comments on comments. If yes continue, else find another video.
3. Check comments section in NewPipe.

### Actual behaviour

Comments on comments are not shown.

### Expected behavior

There should be a way to see comments on comments.

**Comment by opusforlife2** [comment] 2020-10-09 21:10
Duplicate of #2277.

**Closed by opusforlife2** 2020-10-09 21:10 UTC
Labels: bug

**Comment by TontyTon** [comment] 2020-10-09 21:14
Oh sorry, didn't checked so old issue.
