### ISSUE TITLE
Physical Mouse: remove the white overlay on mousover from the videoplayer window

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#4357] opened 2020-09-30 11:39 UTC
#### Version

- 0.20.0 RC

#### Describe the feature you want

It would be nice if you disable the selection feedback for the video window. At least in full screen.
#### Is your feature request related to a problem? Please describe it

When using a mouse with android there is this problem that the mouse keeps selecting the video window on mouse-over. This causes a white haze in front of the video, messing up the colours. _The big problem is: this also happens in fullscreen._

After 15 whole seconds the mouse fades, but the issue persists because the mouse seems to be there still.
#### Additional context

It looks like looking at the video through a tinted glass pane.

Clicking the video and holding seems to alleviate the problem. Except, then the controls pop up again.

This only happens in the RC build #4333. (edited: I think I saw it happen in 19.8, but no matter what I try cannot reproduce it in that version.)

#### How will you/everyone benefit from this feature?

People using a mouse can view the video in full glory, not through some selection feedback filter.

**Comment by opusforlife2** [comment] 2020-09-30 12:07
Ayyy, what a unique problem you have brought up. I like it.

Why did you choose feature request, though? This is a bug.

When you say "also happens in RC" you mean you encountered it in 0.19.8?

**Comment by UIZUI** [comment] 2020-09-30 13:02
>Ayyy, what a unique problem you have brought up. I like it.

 :)
> Why did you choose feature request, though? This is a bug.

I'm sorry but the bug form was a bit daunting with the pictures and logs (I dont think those make sense for this type of bug). And, for me it was not a clear cut bug, but more of a result from a design choice made for finger users. Perhaps an "totally impossible to avoid oversight".
>When you say "also happens in RC" you mean you encountered it in 0.19.8?

That was what I meant, but I can not reproduce it, so it is probably my faulty memory. It seems to work correctly in 0.19.8, sorry.

**Comment by avently** [comment] 2020-09-30 13:32
Show a screenrecord, please

**Comment by Stypox** [comment] 2020-09-30 13:57
@avently the user does not exist anymore. @opusforlife2 we can probably close the issue right away because we won't get any information from a deleted user.

**Comment by TobiGr** [comment] 2020-09-30 14:02
correct

**Comment by opusforlife2** [comment] 2020-09-30 14:13
Wow that was fast.

**Comment by UIZUI** [comment] 2020-09-30 16:11
This is a interactable CSS example http://jsfiddle.net/6nkh3u7k/5/ (codesharing side). The button lights up when you are on top of it with your mouse.

What happends to the button, happends to the player window both in information mode and in fullscreen.

The same happends to the "related videos", but thats actually nice. The problem is in Fullscreen playback having this on mouseover lightening.

I see this has been closed already, which I understand. Just a FYI as to what this problem is about.

**Comment by opusforlife2** [comment] 2020-09-30 16:20
It was closed because you deleted your account and vanished.

**Comment by UIZUI** [comment] 2020-09-30 18:43
I am very sorry. Please close this if you want. I dont have interest in this bugfix anymore.

Sorry for the time wasted.

**Comment by opusforlife2** [comment] 2020-09-30 18:45
Are you alright in real life, buddy?

**Comment by cbiere** [comment] 2020-10-24 16:09
This issue still exists in 0.20.1:

As soon as the cursor it moved, the video gets bright/milky which seems to be caused by a semi-transparent overlay:
https://www.sendspace.com/file/u8vojb
The workaround that works for me: move the cursor to the play/pause icon in the center and toggle it without moving the cursor.

**Comment by opusforlife2** [comment] 2020-10-24 18:27
@cbiere We were just waiting for a user to talk to about it, as the original reporter deleted their account. Thank you for the report!

**Comment by cbiere** [comment] 2020-10-28 17:20
Would you be so kind and reopen this issue? It's still present in 0.20.2.

**Comment by avently** [comment] 2020-10-28 17:35
@opusforlife2 there is a guy who talk about it with details already

**Comment by avently** [comment] 2020-10-28 17:38
@Alexander-- take a look. Looks like a white overlay causes such problem

**Comment by opusforlife2** [comment] 2020-10-28 19:49
Oh. Oops.

**Comment by s2r** [comment] 2021-06-02 21:18
I have the same issue, not exactly with a mouse, but when i go full screen it opens fine and runs fine, but if i press the screen again the white overlay and controls come up (that is fine and expected), but then the controls go away but the overlay stays up i have to press again the screen twice for the overlay to go away.

**Comment by krzsiek** [comment] 2021-11-01 15:57
0.21.13 This same problem all the time. With the mouse and video on fullscren, the cursor is always present on the entire screen and causes the screen to light up, just as it highlights other text, miniatures etc fields when it is not fullscreen. The problem persists and causes the video image to be brightened all the time with this highlight. (all the blacks turn gray, the picture is ugly)

**Comment by pat277** [comment] 2022-04-05 17:14
This problem still occurs, and also applies to when selected by keyboard arrow keys

**Comment by Andronx** [comment] 2022-09-27 17:37
This problem still occurs in 0.24.0, I had to report new bug but I found that opened already.
I use mouse a lot on android device and I'm sure some people also.
When mouse is connected, during video in full screen view,  whole screen is one big touch button, the problem is - when mouse cursor will be moved even one pixel, whole video screen change state to focused and that increase brightness of whole video.
I know that whole screen button is needed to work, because touch screen is necessary even if mouse is connected, but maybe there is a chance to remove focus effect on that specific button or solve that issue in different way.
That would be great to fix that issue. Thank You.

**Closed** 2022-11-09 16:10 UTC
Labels: bug, GUI, player, device/software specific

**Comment by han-sz** [comment] 2022-11-10 04:41
@Andronx The fix for this issue has just recently been merged, please test it with the next version of NewPipe once it's released (or build from source)

**Comment by Andronx** [comment] 2022-11-10 06:14
@han-sz I follow that topic and I'm happy that things are moving forward. I already builded apk and tested your changes and works corectly for me. Thank you to everyone involved for your work. I will also test the new version when it is released and let you know.

**Comment by ShareASmile** [comment] 2022-11-10 14:54
NewPipe nightly is released a few hours after a PR is meged into dev branch and updated code is  included in NewPipe Nightly latest Release as is reflected in nighly14 which includes above bug fix PR #8316:
https://github.com/TeamNewPipe/NewPipe-nightly/releases
