### ISSUE TITLE
[feature request] audio tag editing

### ISSUE THREAD

**Issue by chillsuw13** [TeamNewPipe/NewPipe#2123] opened 2019-02-15 04:18 UTC
option to edit audio tags before audio download

**Comment by magi44ken** [comment] 2019-04-12 23:01
I agree. There are times that I download music and would like to be able to edit the metadata before download.

Going further is to automatically enter the value for the common tag fields like:

Title: (This will be video title)
Artist: (This will be channel name. If not the correct one, the user can also edit it before download)

**Comment by Stypox** [comment] 2019-04-13 10:32
There should also be a button to extract song title and author from the video title, in case of songs.

I could implement this issue, but it would take me some time since I'd first have to completely understand how the download dialog works.

**Comment by magi44ken** [comment] 2019-04-13 17:27
That's a nice suggestion. As long as there is a way copy those info and can manually change before download to avoid switching to the browser to copy and then switch back to new pipe to paste.

Take your time and look forward to it

**Comment by Stypox** [comment] 2019-04-13 22:00
Oh, by the way, issue #2005 is similar

**Comment by Stypox** [comment] 2019-06-23 13:49
Duplicate of #183

**Closed by Stypox** 2019-06-23 13:49 UTC
