### ISSUE TITLE
Buffering on even fast internet. Have to wipe cache metadeta every other day

### ISSUE THREAD

**Issue by WilliamShockleyfake** [TeamNewPipe/NewPipe#6520] opened 2021-06-19 03:55 UTC
Add feature to wipe meta data on exit i.e. app close

**Comment by mhmdanas** [comment] 2021-06-19 10:17
Duplicate of #6510.

**Closed by mhmdanas** 2021-06-19 10:17 UTC

**Comment by Ammako** [comment] 2021-08-21 00:47
I'd probably revisit this one. Given that the other issue was closed as not being related to the cache/metadata problem... that, and whatever problem was being covered by the other issue might not necessarily have been fixed for everyone.

As per https://github.com/TeamNewPipe/NewPipe/issues/6510#issuecomment-898877815

> My buffering & 70kb/s speed issues seem to be solved with the latest update.

And yet I'm still getting this anyway on 0.21.8, so that would already indicate that whatever fix has been made didn't solve it for everyone.

Also: https://github.com/TeamNewPipe/NewPipe/issues/5516#issuecomment-901382592

> Currently the minimum buffer time is 25s the optimal 50s.

25 seconds minimum buffer time? Well clearly the app is failing to enforce this, otherwise the constant half-second buffering every second wouldn't be happening.

**Comment by mhmdanas** [comment] 2021-08-21 00:54
Feel free to open a new issue then (following the template properly please).
