### ISSUE TITLE
The app crash after launching the video on YouTube.

### ISSUE THREAD

**Issue by s3tnex** [TeamNewPipe/NewPipe#3955] opened 2020-07-27 21:22 UTC
Hello. The latest version at the moment (0.19.7) crashes when opening any video on YouTube. Everything is fine with the other services. It was checked personally.

> ## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=J5gpiWts5wE
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ YouTube
* __Version:__ 0.19.7
* __OS:__ Linux ¨xiaomi/cactus/cactus:9/PPR1.180610.011/V11.0.4.0.PCBMIXM:user/release-keys¨ 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function 
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(Unknown Source:189)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(Unknown Source:221)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Unknown Source:7)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(Unknown Source:0)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(Unknown Source:4)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(Unknown Source:4)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(Unknown Source:16)
	at io.reactivex.Single.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(Unknown Source:7)
	at io.reactivex.Single.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(Unknown Source:7)
	at io.reactivex.Maybe.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(Unknown Source:90)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(Unknown Source:11)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(Unknown Source:20)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(Unknown Source:7)
	at io.reactivex.Flowable.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(Unknown Source:9)
	at io.reactivex.Maybe.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(Unknown Source:9)
	at io.reactivex.Single.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source:2)
	at io.reactivex.Scheduler$DisposeTask.run(Unknown Source:9)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern ";([A-Za-z0-9_\$]{2})\...\( inside of var iea=function(a){a=a.split("");var b=[-1215677809,null,-1744521562,833462946,694270393,function(c,d){d=(d%c.length+c.length)%c.length;c.splice(d,1)};"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Unknown Source:84)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Unknown Source:4)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Unknown Source:1)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(Unknown Source:101)
	... 30 more

```
</details>
<hr>

**Comment by wb9688** [comment] 2020-07-27 21:24
Duplicate of #3951

**Comment by Kusurisan** [comment] 2020-07-27 21:24
it's not just the last version, it affects currently all users of NewPipe. Youtube changed something that broke NewPipe.

**Closed by wb9688** 2020-07-27 21:24 UTC
Labels: bug

**Comment by NabilAKROUD** [comment] 2020-07-27 21:33
Can't play any video, no way to use it.
I wiped all data, updated to the last version. 
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=2lAe1cqCOXo
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.19.7
* __OS:__ Linux samsung/j7y17ltexx/j7y17lte:9/PPR1.180610.011/J730FXXU6CSK6:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function 
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:786)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:670)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern ";([A-Za-z0-9_\$]{2})\...\( inside of var iea=function(a){a=a.split("");var b=[-1215677809,null,-1744521562,833462946,694270393,function(c,d){d=(d%c.length+c.length)%c.length;c.splice(d,1)};"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:773)
	... 30 more

```
</details>
<hr>
