### ISSUE TITLE
sepiasearch

### ISSUE THREAD

**Issue by emilasdf** [TeamNewPipe/NewPipe#5492] opened 2021-01-26 13:46 UTC
I think it would be nice if you add sepiasearch which makes it easyer to navigate a cross different peertube instaces. (https://sepiasearch.org)

If someone wants to search viedos on peertube one has to add a lot of instances and search them individuelly for just one viedo.

With sepia one can search 642 peertube instaces.

I like the uncommertial decentrliced aspect of peertube, but one of the problems using it on new pipe is that ts hard to find stuff.

**Comment by mhmdanas** [comment] 2021-01-26 15:15
Duplicate of #4461. Note that this feature is coming in 0.20.9. You can test it by installing the APK from #5455. Also, please don't remove the template when opening an issue. Thanks!

**Closed by mhmdanas** 2021-01-26 15:15 UTC
Labels: enhancement
