### ISSUE TITLE
When using back button it goes to the previously watched video, not the channel

### ISSUE THREAD

**Issue by Multipanda** [TeamNewPipe/NewPipe#5724] opened 2021-02-28 15:33 UTC
### Checklist
- [x] I am using the latest version - v0.20.10
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.
### Steps to reproduce the bug
anytime the app is open and I've played a previous video. Happens with any version of newpipe since the popup player was added and minimised play always run automatically when going back.
### Actual behaviour
When I use the back button on my tablet to go back to a channel after watching a video, it goes first to a previous video and I have to push a second time to get to the channel

Seems it's a problem with the minimized player, I also don't like that it still plays when going back, an easy solution is to turn off the minimized player, or at least add an option in the settings menu to that effect for those who don't want it.

### Expected behaviour
For the back button to actually get me directly back to the channel or playlist.

### Device info

 - Android version/Custom ROM version: Android 7.1.2 (LineageOS 14.1)
 - Device model: Samsung Galaxy Tab S (T800)

**Comment by moriel5** [comment] 2021-02-28 21:52
I was wondering myself whether this was a bug or intended behaviour.
It certainly wastes time for me when I need to go quickly between videos.

**Comment by Multipanda** [comment] 2021-03-01 17:09
Well, if it isn't a bug, then it's a pretty nonsensical UI decision. :-)

**Comment by ResuUman** [comment] 2021-03-02 08:57
It seams that this is closely related to:
https://github.com/TeamNewPipe/NewPipe/issues/5268#issue-774543973

**Comment by DanieLoche** [comment] 2021-03-04 16:08
I have this issue too.

This is even more problematic when you had a playlist, wants to see the details of the current video played, and then just want to go back to previous page (could be the channel, the playlist...) : Instead NewPipe being us to the previously  foreground watched video and the whole playlist is erased by it. (Probably due to the autoplay option?)

**Comment by Stypox** [comment] 2021-03-25 20:06
Closing in favour of #4479 as there is more discussion there

**Closed by Stypox** 2021-03-25 20:06 UTC
Labels: GUI, bug

**Comment by Multipanda** [comment] 2021-03-25 23:20
> 
> 
> Closing in favour of #4479 as there is more discussion there

 #4479 is labelled incorrectly though since it IS a bug, but it's not labelled as such. And I don't think more discussion is needed, it's easy enough to reproduce, and there are multiple ways it can be fixed.

**Comment by nbmrjuhneibkr** [comment] 2021-03-26 05:09
> #4479 is labelled incorrectly though since it IS a bug, but it's not labelled as such
I actually submitted it as a bug at first https://github.com/TeamNewPipe/NewPipe/issues/4462 (this new behavior is so confusing that I genuinely assumed that it was unintentional), but it was instantly closed. So I had to submit it as a feature request instead.

**Comment by moriel5** [comment] 2021-03-26 05:43
I agree, that #4479 is not the best place for this, though not because of its label, which I actually think is correct, but rather because what is requested there is more like a band-aid over incorrect behaviour, that should be fixed, hence this bug report, which looks at the issue as it truly is.

**Comment by Multipanda** [comment] 2021-06-06 17:58
This has now become worse, rather than having to click back a few times, if I've watched a bunch of videos through the suggestion feed i know have to click back through **every single one** making the app bordeline useless if I want to get back to the app's start screen.
