### ISSUE TITLE
On the tab “Trends”, add the ability to block channels.

### ISSUE THREAD

**Issue by IT-Tool** [TeamNewPipe/NewPipe#2688] opened 2019-10-04 18:37 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

  To prevent the trend tab from turning into garbage, it would be nice to block channels that you are not interested in (so that in the future you no longer receive content from them).

**Comment by Stypox** [comment] 2019-10-06 06:42
Duplicate of #1815

**Closed by Stypox** 2019-10-06 06:42 UTC
