### ISSUE TITLE
Download on mp3

### ISSUE THREAD

**Issue by China-nee** [TeamNewPipe/NewPipe#8368] opened 2022-05-08 00:56 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Download music on m4a it's okay but it will be better if I can dowload it also on mp3.

### Why do you want this feature?

Because on that way it will be easier.

**Comment by SameenAhnaf** [comment] 2022-05-08 01:58
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/507

**Comment by TiA4f8R** [comment] 2022-05-08 09:13
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

The template instructions are compulsory: you have to search (better?) for issue duplicates when you open an issue.

Closing as a duplicate of #507.

Thank you.

**Closed by TiA4f8R** 2022-05-08 09:13 UTC
Labels: enhancement
