### ISSUE TITLE
App crashes in history tab

### ISSUE THREAD

**Issue by malisipi** [TeamNewPipe/NewPipe#10404] opened 2023-09-07 18:31 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Open history page from side panel
2. Open a video from history page

<img src="https://github.com/TeamNewPipe/NewPipe/assets/87281783/7ea80d8f-a17b-4c00-b326-741cd4d8716a" width=400 />

3. Play the video

<img src="https://github.com/TeamNewPipe/NewPipe/assets/87281783/48fcaf48-6b8d-462e-959c-5595008f6ef6" width=400 />

4. Open a deleted/private video that placed in history

<img src="https://github.com/TeamNewPipe/NewPipe/assets/87281783/24453391-46b4-4b3e-9f00-dfca22e294de" width=400 />

<img src="https://github.com/TeamNewPipe/NewPipe/assets/87281783/b2f359d3-7916-4203-8a3b-a5fc985f932c" width=400 />

5. Enter fullscreen

<img src="https://github.com/TeamNewPipe/NewPipe/assets/87281783/95e9c681-3d92-4ef9-8bbe-c149c184fb7f" width=400 />

6. Leave fullscreen

<img src="https://github.com/TeamNewPipe/NewPipe/assets/87281783/b73655c3-4300-4712-8742-bce195784c1e" width=400 />

7. You will see the control buttons that placed in top, in background

<img src="https://github.com/TeamNewPipe/NewPipe/assets/87281783/8db7ddd5-140c-4a79-97dd-73e24eb9fad4" width=400 />

8. When you scroll to top, the application will crash.

### Expected behavior

It shouldn't crash and the control buttons shouldn't showed in background.

### Logs

-------------------------------------
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
-------------------------------------

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy A11

### Additional information

It's similar to https://github.com/TeamNewPipe/NewPipe/issues/8970 . However the bug is showing at different way.

**Comment by AudricV** [comment] 2023-09-07 19:08
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

You didn't, duplicate of #4475 like for the similar issue. Please search better (with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2023-09-07 19:08 UTC
Labels: bug, needs triage

**Comment by malisipi** [comment] 2023-09-07 19:26
Oh. I'm missed the issue. It's my bad. I was thoke it was related with only history tab. I will search better in next time. I'm glad to hear you're working on the issue. Thank you for making NewPipe better. Have a good day.
