### ISSUE TITLE
Age-Gated Videos not playing

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#4161] opened 2020-08-19 04:23 UTC
This issue was initially referenced in #890 and I cannot seem to be able to reopen the issue myself.

Nevertheless, videos such as https://www.youtube.com/watch?v=u9sO2c0Ml34 result in a crash when trying to view them.

Thank you for your time and consideration.

**Comment by opusforlife2** [comment] 2020-08-19 09:47
If a maintainer closes an issue only a maintainer can reopen it. Anyway, that issue is an old one, so let's keep this one open.

Can you please fill in the template? Like which version? I tried your link in 0.19.8 and it works. No error.

**Comment by justanidea** [comment] 2020-08-19 18:08
I does crash for me too and im in 0.19.8

**Comment by opusforlife2** [comment] 2020-08-19 18:21
@justanidea You didn't link the video.

**Comment by johnth3doe** [comment] 2020-08-19 19:12
Apologies for the late response @opusforlife2  and for not posting according to the guidelines, sincerely.

Firstly, I tried the same video once again since you claimed to be able to view it. As it were this is suddenly the case for me as well, it didn't instantly crash and allowed me to view it. 

By that principle I believe that this issue should be closed, that being said, user @justanidea seems to claim this issue is identical to them; therefore I shall ask what the correct etiquette/protocol is in this case?

I shall close the issue for the reason stated above until directed otherwise or due to circumstances (like a possible reemergence)

**Comment by johnth3doe** [comment] 2020-08-19 19:21
In a (possibly) related issue, when initially viewing this link: https://www.youtube.com/watch?v=zwT6DZCQi9k, I had a crash; but revisiting the video a second time didn't cause any issues. 

The log (I remembered this time): 
[NP Crash Log.txt](https://github.com/TeamNewPipe/NewPipe/files/5098776/NP.Crash.Log.txt)

Thank you once again for your time and consideration.

**Comment by justanidea** [comment] 2020-08-20 06:34
@opusforlife2 bcs its the one provided by @johnth3doe  :) Sorry for not clarifying, i thought it would make sense

**Comment by opusforlife2** [comment] 2020-08-20 08:03
@johnth3doe No problem. ✌️ 

@justanidea Yeah, I didn't realise you were talking about the video crashing specifically, and assumed you were talking about Newpipe crashing.

Since it's still crashing for justanidea, let's keep this open. We now have crash reports to show the devs as well.

**Comment by opusforlife2** [comment] 2020-08-20 08:05
@johnth3doe You can directly paste the contents of the crash report here, because Github renders the Markdown properly.

For example, here is the exact text of your crash report pasted below:

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=zwT6DZCQi9k
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.19.8
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not load decryption code for the Youtube service.
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerUrl(YoutubeStreamExtractor.java:706)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:656)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerUrl(YoutubeStreamExtractor.java:701)
	... 31 more

```
</details>
<hr>

**Comment by opusforlife2** [comment] 2020-08-20 08:10
> In a (possibly) related issue, when initially viewing this link: https://www.youtube.com/watch?v=zwT6DZCQi9k, I had a crash; but revisiting the video a second time didn't cause any issues.

Ah. I notice you got "Could not load decryption code for the Youtube service." in your crash message. I get this sometimes as well. This is caused by minor, temporary network issues, unless I'm mistaken. Everyone gets one of these every once in a while, if a video takes too long to load.

**Comment by Stypox** [comment] 2020-09-03 13:34
@justanidea @johnth3doe Could you install a debug apk (for example [the latest unified ui apk](https://github.com/TeamNewPipe/NewPipe/files/5168628/app-debug.zip)), connect your phone to your PC through USB, open Chrome, go to `chrome://inspect`, open that debug version of NewPipe on your phone, select that NewPipe instance in Chrome, go to the Network tab, try to reproduce the issue, and once you've successfully reproduced the issue, right-click in Chrome, select "Save as HAR with Content" and send me that HAR? Then we might be able to fix this issue.

**Comment by opusforlife2** [comment] 2020-11-08 06:15
Could you try the APK in https://github.com/TeamNewPipe/NewPipeExtractor/pull/447?

**Comment by opusforlife2** [comment] 2020-11-08 08:07
Closing until user replies.

**Closed by opusforlife2** 2020-11-08 08:07 UTC
Labels: bug, youtube

**Comment by johnth3doe** [comment] 2021-05-21 19:15
### Checklist


- [x] I am using version - 0.21.0 (Because I am avoiding upgrading as a result of #6179 [which I understand was introduced in 0.21.2]) 
- [x] I checked now, then realized that I had altogether forgot to reply when the issue was resolved (at that time). 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug






### Expected behaviour
Play all videos without error.


### Actual behavior
As explained above, and in the previous mentioned issue; any video (including the shown example)
results in a grey sad face.

### Screenshots/Screen recordings
N/A


### Logs

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=n79KoPVeCJg
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.21.0
* __OS:__ Linux Android 4.4.2
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:47)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchVideoInfoPage(YoutubeStreamExtractor.java:801)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:730)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(lambda)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

```
</details>
<hr>

### Additional Notes

1) I have made sure that 'restricted' settings are respectively set to allow viewing the content in question
2) The issue (in this instance) has surfaced since the last 1 to 2 days, before which it was working normally.


Thank you for your time, patience and consideration
___
PS. I would like it to be known that I am genuinely sorry to @opusforlife2 because, in lieu of their respectful patience, I showed bad etiquette in the absence of a response.
PPS. If possible, could someone please help me in re-opening this issue (since this satisfies the criteria of a response as per https://github.com/TeamNewPipe/NewPipe/issues/4161#issuecomment-723544041?
