### ISSUE TITLE
Network error on import youtube subscription

### ISSUE THREAD

**Issue by xdubx** [TeamNewPipe/NewPipe#2374] opened 2019-05-31 17:05 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Version: v0.16.1
Error as local notification: Network error.

If you have an empty entry in your subscription_manager.xml file in the attribute text. The import doesn't work anymore. I had a deleted account in my subscription list and it prevented that.

XML Entry:
```
 <outline text="" title="" type="rss" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCHdo1T6II2L5D4EpKemAjVA" />
```

Perhaps you could add a check if the fields are empty before trying to resolve the url.
With kind regards a lazy developer :)

**Comment by Stypox** [comment] 2019-05-31 17:52
This will be fixed in 0.16.2. The problem is that empty titles explicitely throw an error, even though there is no problem at all importing them: see TeamNewPipe/NewPipeExtractor#160

**Closed** 2019-09-29 13:55 UTC
