### ISSUE TITLE
SAF file open/close dialogues can't be confirmed on FireTV (FireOS bug)

### ISSUE THREAD

**Issue by k9janer** [TeamNewPipe/NewPipe#6455] opened 2021-06-08 17:24 UTC
### Checklist

- [x] I am using the latest version - v0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

So this isn't really a bug by NewPipe. In fact NewPipe doesn't do anything wrong but the new SAF dialogue triggers a long standing bug/limitation in FireOS used on some Amazon FireTV devices.

The issue is that Amazon forgot to modify the SAF file open/save dialogues to make them work with a remote. While you can navigate them, it's not possible to confirm any selection made in these menus unless you are using a separate input device like a mouse.

My Fire TV Stick 4K running the latest FireOS 6 (based on Android 7.1) is affected by this issue. I don't know if newer FireTV devices running FireOS 7 (based on Android 9) are still affected by this.

If possible, one solution would be to detect FireOS TV devices and disable SAF by default for the time being.

Do you think it's worth spending time working around an OS bug like this?

Edit: Of course this bug only applies to Fire TVs and TV boxes. The SAF dialogues can be navigated perfectly fine on my Fire HD 10 tablet with its touch screen.

### Steps to reproduce the bug

1. Install NewPipe on an up to date FireTV 4K Stick
2. Leave the settings on default (SAF is turned on by default)
3. Use any option that causes the SAF file open/save dialogue to appear - for example try downloading a video
4. The SAF file save dialogue will appear.
5. You will notice that it's not possible to confirm this dialogue. For example in the save dialogue you won't be able to choose a folder for the default download location as you can't reach "select".

### Device info

 - Android version/Custom ROM version: FireOS 6 based on Android 7.1
 - Device model: Fire TV Stick 4K

**Comment by Stypox** [comment] 2021-06-08 18:34
Oh no, device compatibility... Disabling SAF in the settings works, though, doesn't it? Anyway, a PR is needed.

**Comment by mhmdanas** [comment] 2021-06-08 19:41
I want to fix this. This line should be changed to have a check for FireTV:
https://github.com/TeamNewPipe/NewPipe/blob/56cd84c1fe4e9dce0d2003cdce0c6433dea1ff77/app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java#L68

I wonder though: should I create a new migration? I think not because no release with this change has been published.

**Comment by Stypox** [comment] 2021-06-09 10:55
No, there's no need for a new migration

**Comment by Stypox** [comment] 2021-06-09 10:57
No, there's no need for a new migration. But that's not the only thing that should be changed: the function NewPipeSettings.useStorageAccessFramework() should also be reworked.

**Comment by mhmdanas** [comment] 2021-06-18 12:07
How should I check if the device is a FireTV? `DeviceUtils.isTv()` check for TVs in general.

**Comment by TobiGr** [comment] 2021-06-18 12:24
You can extract this into a method: https://github.com/TeamNewPipe/NewPipe/blob/d6e0bd8c26af1b7818e025d8dcda2cb69f636fab/app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java#L48

**Comment by TobiGr** [comment] 2021-06-19 08:22
@k9janer Please test the APK in #6516 and tell us whether the problem is resolved.

**Comment by k9janer** [comment] 2021-06-19 10:53
I tried #6516 on 2 different FireTV 4K Sticks but unfortunately it doesn't work on both of them. SAF is still enabled by default.

**Comment by mhmdanas** [comment] 2021-06-19 10:56
Can you check that you have tried the latest APK right now? You may have tried the APK built before I committed e7a4976af0ed5ee181769f33854cc4569da86778.

**Comment by k9janer** [comment] 2021-06-19 11:14
Oh, yeah tried it with the older version before.

The new version now works as intended!

FireTV Stick 4K: SAF is disabled by default ✔️
Fire HD 10 Tablet (2019): SAF is still enabled by default ✔️

**Closed** 2021-06-20 19:01 UTC
Labels: bug, device/software specific
