### ISSUE TITLE
Share Playlist Option in Video Menu

### ISSUE THREAD

**Issue by 5lttrz** [TeamNewPipe/NewPipe#6668] opened 2021-07-15 13:11 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Adding a share playlist button in the quick playlist menu (in the video options).

#### Is your feature request related to a problem? Please describe it

Not related to any bug/problem, but it will be easier to share playlist if we close the original full playlist menu by accident and still can just open up the video menu and share the playlist.

#### Additional context

![Screenshot_20210715-183058.png](https://user-images.githubusercontent.com/75839799/125793570-a8fb4a9c-147a-4663-a3db-6f4face7dd81.png)

#### How will you/everyone benefit from this feature?

It will be easier to share playlists from within the video menu.

**Comment by SameenAhnaf** [comment] 2021-09-06 18:38
@opusforlife2 If I am not wrong, this is a duplicate of #1788.

**Comment by litetex** [comment] 2021-12-20 21:03
Consolidated into #1788

**Closed by litetex** 2021-12-20 21:03 UTC
Labels: enhancement, GUI
