### ISSUE TITLE
Approximate defaut video resolution when it's not available

### ISSUE THREAD

**Issue by nibley** [TeamNewPipe/NewPipe#6198] opened 2021-04-29 04:26 UTC
I use 144p as my default video resolution but I've noticed that some livestreams that streamed recently only have the three highest resolutions available (1080, 720, and 360)  

Because my preferred lower resolution is not available, NewPipe chooses 1080p. 

I'd suggest falling back to the resolution closest to the setting. Thanks.

**Comment by SameenAhnaf** [comment] 2021-04-29 04:38
Duplicate of #6084. Please avoid opening issues with already existing topics. When you are doing so, you are actually taking more time from devs which they could utilize for solving the problem.

**Closed** 2021-04-29 09:59 UTC
