### ISSUE TITLE
Unable to continue a paused video

### ISSUE THREAD

**Issue by Toasterbirb** [TeamNewPipe/NewPipe#8294] opened 2022-04-26 10:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Start playing any video
2. Let it play for a while
3. Pause the video
4. Try to continue the playback

### Expected behavior

The video should continue playback just fine

### Actual behavior

The continue button seems to get stuck and nothing happens when you press it.

### Affected Android/Custom ROM version

LineageOS 18.1

### Affected device model

Fairphone 3

### Additional information

This happens more often with videos played with autoplay.

I used to get around this by hitting the background playback button and immediately clicking on the video again to start playing it again and it would sometimes continue from the last position but usually it just starts from the beginning.

Sometimes when I try to perform this "workaround" though, if the video was a result of autoplay, it sometimes goes back to the first video I watched (selected from search results etc., the beginning of the autoplay queue), but this is probably a separate bug and not related. I'm not sure.

The bug is quite difficult to replicate with the first video in the autoplay queue (it hasn't gone to the next video yet), but I'm quite sure that that has also happened. The bug has occurred countless times, but when I tried to reproduce it for this bug report, I wasn't able to. It happened ealier today though with the same version, so it occurs quite randomly

**Comment by byteme-git** [comment] 2022-04-26 17:13
Same issue here. I have been experiencing the same bug constantly for multiple Versions now.

Version: 0.22.2 from F-Droid
Device: Poco F1
OS: Lineage 18.1 with Micro G

I can confirm that the issue also effects the first video, with or without other videos in the que. I also experience the same behavior of returning to the first Video. Using the back button twice and then pressing play or starting the video fron the feed again also works as workarounds to resume.

There seems to be a correlation to how much time passed after pausing, but its inconsistent and it also happens with a newly started video.

**Comment by Toasterbirb** [comment] 2022-04-26 18:07
Right, I forgot to mention it that I also have experiencced this for multiple versions. First I thought that it was just a one off thing and would go away in the next update but then just got used to it and just avoided pausing the video if I could.

I probably should have reported this earlier and not just hope that someone else would do it

**Comment by 2dvoid** [comment] 2022-04-28 22:49
I'm facing the same issue from a long time. Like @Toasterbirb I was also hoping someone to report.

Version: 0.22.2
Device: Redmi Note 5 AI (whyred)
OS: LineageOS for microg 18.1

**Comment by CyberaxAnnon** [comment] 2022-04-30 14:43
This happens to me either when I swap to another app for more than a few minutes or pause and turn off my screen. 
It does get annoying at times

**Comment by pc00per** [comment] 2022-05-03 16:46
I've encountered it recently. When you unlock your device with stream running in the background makes it pause & stops the buffer completely.

**Comment by simo1994** [comment] 2022-06-25 14:54
I've been experiencing this issue as well.
Paused videos become stuck if I wait some time (seconds or minutes), pressing play doesn't do anything.

In the past the New pipe notification stayed there even as the video was paused. Nowadays, it disappears after a short while. The app has all the OS "battery savings" settings disabled.

The problem happens especially when I start playing a video in another app, or answer a call.

**Comment by AlertSubject** [comment] 2022-06-26 11:06
I've only started getting this problem since I'm on Android 12

Here's how it happens most often

- play a video
- pause it
- either: minimize the app for a bit, click the rotate button the screen while paused, or just keep it paused for long enough even with the app opened
- result is that the video screen turns black and clicking the resume button won't start the video again. It also resets your view history progress for that video to 100% which is annoying because closing and reopening the video no longer gets me back to where I was

Sometimes the screen doesn't turn black but the pause frame stays as it should be. Everything else is the same (can't resume playback etc)
I think this mostly happens when I don't minimize the app and just keep it paused for a few minutes

**Comment by Toasterbirb** [comment] 2022-07-14 13:40
It looks like the pausing problem is gone, but instead the playback simply stops randomly with the interruptions increasing nearing the end of the video. Usually the video can just continue playing normally from the point it stopped at, but with longer videos sometimes nearing the end of the video it doesn't want to restart the video at all.

Here's one of the error reports that pop up from this issue to notifications
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED] occurred while playing https://www.youtube.com/watch?v=ILt1j3xEmw0
* __Content Country:__ JP
* __Content Language:__ fi-FI
* __App Language:__ fi_FI
* __Service:__ YouTube
* __Version:__ 0.23.1
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.UnknownHostException: Unable to resolve host "rr2---sn-4ox-ixal.googlevideo.com": No address associated with hostname
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.net.UnknownHostException: Unable to resolve host "rr2---sn-4ox-ixal.googlevideo.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
	... 10 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 28 more

```
</details>
<hr>

However as for the original issue, it seems to have been solved or I just haven't been unlucky enough to encounter it anymore. I'm not sure if these two are related in some way, but they are quite similar with the way they happen

**Comment by AlertSubject** [comment] 2022-07-14 19:54
> It looks like the pausing problem is gone,

Nope, definitely not
I still have it multiple times per day
But I haven't ever faced your issue

**Comment by Toasterbirb** [comment] 2022-07-15 00:41
Hmmh... Maybe it has something to do with the recent Android 12 (Lineage OS 19.1) update I had. The this timeline with the bug changing at least matches up

**Comment by AlertSubject** [comment] 2022-07-15 05:46
> Android 12

This issue started when I updated to Android 12 (together with the quarter screen playback issue)
I never had it on 11

OxygenOS Android 12

**Comment by Sinono3** [comment] 2022-08-28 16:38
This happens to me as well on Poco X3 NFC with LineageOS 18.1 with Android 11.

**Comment by byteme-git** [comment] 2022-08-29 07:37
I no longer experience the issue. Are you on the latest version?

**Comment by AlertSubject** [comment] 2022-08-29 07:57
I am on the latest version and still experience this issue

**Comment by opusforlife2** [comment] 2022-08-31 19:50
Could someone post a screenrecord, please?

**Comment by AlertSubject** [comment] 2022-09-01 20:42
> Could someone post a screenrecord, please?

https://transfer.sh/fbFvkJ/Record_2022-09-01-19-32-45.mp4

Sceen record available here

**Closed** 2022-09-15 00:16 UTC
Labels: bug, waiting for author

**Comment by eternal-sorrow** [comment] 2022-09-15 00:18
This is not fixed, reopen the issue please.

**Comment by AlertSubject** [comment] 2022-09-15 06:22
Sorry for the ping @opusforlife2, but could you please take a look at the provide video and remove the "waiting for author" label?

I believe the file upload is to expire soon and I don't have the original video anymore

**Comment by Toasterbirb** [comment] 2022-09-15 10:47
> This issue has been automatically closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.

I have not had this issue for a while now, but it seems to still persist for some users. My assumption has been that some Android update fixed the issue but I'm not certain. That would at least explain why it got fixed for some but not everyone

**Comment by opusforlife2** [comment] 2022-09-17 18:21
@AlertSubject Is there a video host that would keep your video permanently/for a long time? Also, the link isn't working for me. Could you check if it's still valid?

**Comment by AlertSubject** [comment] 2022-09-19 14:00
@opusforlife2 
The link has expired
I'll keep the file on my google drive for now 
https://drive.google.com/file/d/13QmebHjBPqyEmQECfeAMJlX7_5WEb6sm/view?usp=sharing
Should remain there for a few months until I delete my google account

**Comment by opusforlife2** [comment] 2022-09-20 07:30
Thanks, I hope it'll help debug the issue.

**Comment by AlertSubject** [comment] 2022-09-20 07:36
> Thanks, I hope it'll help debug the issue.

Let me know if you need more information
Happens to me a few times per day so I can reproduce it when needed

**Comment by mikeloeven** [comment] 2022-09-21 19:20
Issue still encountered on the most recent version of newpipe. Using an older model S5 Android 6.0.1 

Issue seems to at least in my situation triggered when the background player is paused long enough for the phone to doze. When attempting to resume playback the video will play a minute or two of video before freezing and displaying network error. I am unable get the video to restart and switching to the main player does not allow the video to buffer or resume either. Only workaround I have found so far is to Force Quit the main app an than re open the video from history which seems to resolve the problem

**Comment by AlertSubject** [comment] 2022-09-21 19:52
> Issue seems to at least in my situation triggered when the background player is paused long enough for the phone to doze. 


Completely different situation on my android 12 device
The trigger might be the same but somehow it can also trigger if I just shortly pause the video or pause and then exit full screen
Or even just minimizing the app to background when paused

After it has been triggered, the video more often than not gets replaced by a black screen and the rest can be seen on my video linked above
When the trigger is pausing and unpausing then the video won't turn black but instead keep the last frame frozen. (until I exit full screen and the video turns black again)

No network errors etc or any error notifications on my end

**Comment by ShareASmile** [comment] 2024-02-17 19:06
Is it still an issue on 0.26.1?

**Comment by mikeloeven** [comment] 2024-02-18 01:06
Issue is resolved for me although I def think it was to due with my old outdated android version. New phone is a Pixel 8 with Graphene OS and I cannot reproduce the issue on this system

**Comment by eternal-sorrow** [comment] 2024-02-20 23:16
Don't close so fast wait at least when 0.26.1 is published on f-droid.

**Comment by Toasterbirb** [comment] 2024-02-21 02:31
> Don't close so fast wait at least when 0.26.1 is published on f-droid.

I'm fairly certain this isn't a problem anymore, or if it is, it has to do with the Android version in some way or some other variable. I'm on version 0.25.2 and haven't had this problem for nearly two years at this point.

**Comment by eternal-sorrow** [comment] 2024-02-21 03:32
I'm on 0.25.2 still having this problem.

**Comment by eternal-sorrow** [comment] 2024-02-21 03:34
> it has to do with the Android version in some way or some other variable

That doesn't make it fixed, some people are stuck on the old Andoid version.

**Comment by eternal-sorrow** [comment] 2024-05-15 19:54
0.27.0 The issue is still there.
