### ISSUE TITLE
sometimes video in full screen shows in wrong size (android 12)

### ISSUE THREAD

**Issue by pokegamer5547** [TeamNewPipe/NewPipe#7896] opened 2022-02-19 06:33 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.21.16

### Steps to reproduce the bug

1. Open the video in full screen sometimes.

### Actual behavior

After upgrading to android 12, sometimes when trying to watch video (only in newpipe) in full screen it shows video in wrong size. It gets fixed after trying full screen again.

### Screenshots/Screen recordings
![Screenshot_20220219-115305_NewPipe](https://user-images.githubusercontent.com/65234485/154789599-604fefe6-1c63-4d83-9342-8748d6ee3161.png)

### Affected Android/Custom ROM version

android 12, crdroid 8.1 (based on lineage os 18.1)

### Affected device model

poco m2 pro (miatoll)

**Comment by SameenAhnaf** [comment] 2022-02-19 07:20
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7262

**Closed** 2022-02-19 09:41 UTC
Labels: bug
