### ISSUE TITLE
Phone restarts when I'm using newpipe 

### ISSUE THREAD

**Issue by vehosah** [TeamNewPipe/NewPipe#7276] opened 2021-10-18 22:22 UTC
### Checklist

- [x] I am using the latest version - x0.21.12
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Yesterday I used newpipe, the phone restarted, tonight I used it, the phone restarted again -->

### Device info

 - Android version/Custom ROM version:
 - Device model:Nokia 4.2 Android 11

**Comment by SameenAhnaf** [comment] 2021-10-18 22:30
You forgot to fill in the version.

> I am using the latest version - x.xx.x

**Comment by vehosah** [comment] 2021-10-18 22:43
> You forgot to fill in the version.
> 
> > I am using the latest version - x.xx.x

I filled it now

**Comment by litetex** [comment] 2021-10-20 18:27
Duplicate of #5961

Can't really tell what's happening with:
>Yesterday I used newpipe, the phone restarted, tonight I used it, the phone restarted again

Without further information (logs) we can't diagnose the problem further.

**Closed by litetex** 2021-10-20 18:27 UTC
Labels: bug, more info needed
