### ISSUE TITLE
YouTube filters (video duration, license, etc) are missing

### ISSUE THREAD

**Issue by prototyperspective** [TeamNewPipe/NewPipe#11648] opened 2024-10-26 14:48 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When searching on YouTube, one can click on "Filters" to see these filter options:

![2222](https://github.com/user-attachments/assets/4af2e65f-0ff7-4e6c-acd3-759f886824fc)

These are very useful for various purposes so please add them to NewPipe.

### Why do you want this feature?

In the Screenshot you can see how I use these filters to search for videos that are CCBY and can be uploaded to [Wikimedia Commons](https://commons.wikimedia.org/) (e.g. videos [about NewPipe](https://commons.wikimedia.org/wiki/Category:NewPipe) of that kind). Having these filters would also be useful on mobile.

There are also lots of other potential applications. For example, some search may show lots of long videos but you're only searching for a short video and could use the duration filter for that. Or some search shows many results but most of them have barely any views and I want to sort them by popularity. I could think of more ways these filters can be useful if that's important.

**Comment by AudricV** [comment] 2024-10-26 16:01
> - [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #2251. 
Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-10-26 16:01 UTC
Labels: feature request, needs triage
