### ISSUE TITLE
Can the comment loader code on skytube work on newpipe?

### ISSUE THREAD

**Issue by Ananas-Kuchen** [TeamNewPipe/NewPipe#6807] opened 2021-07-30 04:41 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Is it possible to use the code to load comments from skytube for newpipe, since both are the same as open source?

#### Is your feature request related to a problem? Please describe it

Since the newpipe comment field is problematic, if it is possible to implement something new it helps. maybe newpipe can show "reply" in each comment column. if possible

#### Additional context

![ss](https://user-images.githubusercontent.com/65159908/127600884-55f96204-453b-4a98-97f9-2036c3cb913f.png)

If the code for loading comments on skytube can be implemented/find another way for newpipe, that's great news. if you can't, that's okay

#### How will you/everyone benefit from this feature?

At least the user doesn't have to jump into the browser from newpipe every time he wants to see the reply

**Comment by mhmdanas** [comment] 2021-07-30 09:48
SkyTube and NewPipe share the same core, NewPipeExtractor, which is responsible for extracting everything. I'm not too familiar with SkyTube though, so it's possible that it uses a forked version of NewPipeExtractor or its own code for extracting comments.

It seems to me as if you are requesting comment replies (#2277). If that's the case, then this issue is a duplicate of #2277, but it's still not clear enough. Can you clarify?

**Comment by Ananas-Kuchen** [comment] 2021-07-30 13:34
> SkyTube and NewPipe share the same core, NewPipeExtractor, which is responsible for extracting everything. I'm not too familiar with SkyTube though, so it's possible that it uses a forked version of NewPipeExtractor or its own code for extracting comments.
> 
> It seems to me as if you are requesting comment replies (#2277). If that's the case, then this issue is a duplicate of #2277, but it's still not clear enough. Can you clarify?

Yes, someone did ask that. 

But i think it's the first time i'm mentioning the skytube code to load comments for newpipe

**Comment by mhmdanas** [comment] 2021-07-30 15:20
I checked, and it does seem like they got some code for this in their app: https://github.com/SkyTubeTeam/SkyTube/blob/1851b2aea1a67c42ca0396e8336ae472d7724bfc/app/src/main/java/free/rm/skytube/businessobjects/YouTube/GetCommentThreads.java

However, in any case, a PR on the extractor to extract comment replies for YouTube is already open (https://github.com/TeamNewPipe/NewPipeExtractor/pull/576). I'll be closing this issue in favor of #2277.

**Closed by mhmdanas** 2021-07-30 15:20 UTC
Labels: enhancement

**Comment by Ananas-Kuchen** [comment] 2021-07-31 01:40
> I checked, and it does seem like they got some code for this in their app: https://github.com/SkyTubeTeam/SkyTube/blob/1851b2aea1a67c42ca0396e8336ae472d7724bfc/app/src/main/java/free/rm/skytube/businessobjects/YouTube/GetCommentThreads.java
> 
> However, in any case, a PR on the extractor to extract comment replies for YouTube is already open ([TeamNewPipe/NewPipeExtractor#576](https://github.com/TeamNewPipe/NewPipeExtractor/pull/576)). I'll be closing this issue in favor of #2277.

ok
