### ISSUE TITLE
Make sharing possible without starting video.

### ISSUE THREAD

**Issue by Rowsinator** [TeamNewPipe/NewPipe#5024] opened 2020-11-28 17:47 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

While I love the new interface, one thing that has degraded is the ability to share videos without starting them.

Previously it was possible to share a video without starting it by using the drop down menu on the upper right hand side, and selecting share. Now I have to start the video first, which is a waste of data. What's worse is that it adds a time stamp, so if I do not immediately pause the video, the video I share won't start at the beginning if I don't modify the URL.

I am aware that you can press and hold on a video in the video listing to share videos that way, but this option is not available to me when I am sent a link by someone and want to share it with someone else.

Please add a button somewhere that allows me to share the video without having to start it. Perhaps next to the Download button, or maybe have the URL be copied when you press and hold the video play area.

#### Is your feature request related to a problem? Please describe it

This isn't so much related to a technical problem, more of a usability issue. Specifically, I use the share option to copy to the clipboard most of the time.

#### How will you/everyone benefit from this feature?

The less clicks the better. Here is a list of clicks that need to be done once the video page is on screen:

1. Click to play the video
2. Tap the video to get the menu to pop up
3. Pause the video
4. Tap the the drop down
5. Tap share
----------(after copying the url in the share menu and pasting it into a text field, this is not newpipe's problem)
6. delete time code after URL so video starts at the beginning.

The number of clicks could be drastically reduced by half by adding a button that is more accessible in the UI. I realize the UI is already pretty "cozy", but this is a function I use regularly, often a few times a day.

**Comment by mhmdanas** [comment] 2020-11-28 18:49
Duplicate of #4039.

**Closed** 2020-11-28 18:50 UTC
Labels: enhancement
