### ISSUE TITLE
Hamburger Menu Selection and Tab Order

### ISSUE THREAD

**Issue by voiceofvraja** [TeamNewPipe/NewPipe#5200] opened 2020-12-17 07:27 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Ability to edit order or remove tabs from the hamburger menu, for example let users select what they want there or just let them completely remove it and have only homepage

#### How will you/everyone benefit from this feature?

If someone just wants a more clear interface they can remove few options or the whole hamburger menu itself because all the options are already there to be used on the main page, the startup screen. It is more like it is doubled down so it would be nice to let users select what they want

**Comment by mhmdanas** [comment] 2020-12-17 07:40
Could you please change the titles of all your issues to be more descriptive? A title of "Feature request" is not useful at all.

**Comment by c-shubh** [comment] 2020-12-17 18:55
Duplicate of #4081

**Closed** 2020-12-18 10:08 UTC
Labels: enhancement
