### ISSUE TITLE
Like button is not working and the comment section are not loading

### ISSUE THREAD

**Issue by arjunmsujathan** [TeamNewPipe/NewPipe#6811] opened 2021-07-31 03:51 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by botistreamer** [comment] 2021-07-31 04:14
Duplicate of #6744 
check if the bug is already reported and fill the template properly

For the like button to work, we would have to log in. And that is not in the scope of the project. https://github.com/TeamNewPipe/NewPipe/issues/1322#issuecomment-381638887

**Closed** 2021-07-31 11:22 UTC
Labels: bug
