### ISSUE TITLE
[Legacy] Trending page remains empty

### ISSUE THREAD

**Issue by roytam1** [TeamNewPipe/NewPipe#6022] opened 2021-04-07 16:30 UTC
### Checklist

- [x] I am using the latest version - 0.20.8-legacy 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. install latest version of NewPipe Legacy
2. Launch it

### Actual behaviour

Circle keeps rotating and list remains empty.

### Expected behavior

Trending should be displayed.

### Device info

 - Android version/Custom ROM version: Android 4.1.2
 - Device model: SO-05D

**Comment by ShareASmile** [comment] 2021-04-08 10:36
Basically a duplicate of #5895 and fixed in Extractor v0.21.0 in https://github.com/TeamNewPipe/NewPipeExtractor/pull/582

Please Open Legacy Newpipe related issues in this dedicated repo.
https://github.com/TeamNewPipe/NewPipe-legacy

& ask for Legacy version update there (which has not been updated for a while, it looks).

**Comment by ShareASmile** [comment] 2021-04-08 10:48
You may also try legacy preunified (v19 UI) version having latest extractor from #4918  
Look for legacy version from given repo link given there.

**Comment by TiA4f8R** [comment] 2021-04-08 14:02
@ShareASmile is right. Closing of this issue with the above mentioned reasons.

**Closed by TiA4f8R** 2021-04-08 14:02 UTC
Labels: bug
