### ISSUE TITLE
Ability to show channel group as a tab on Main Page

### ISSUE THREAD

**Issue by Akv2021** [TeamNewPipe/NewPipe#8641] opened 2022-07-17 17:01 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Currently there is no option to set a particular channel group as a tab on main page. 
This tab would be similar to What's new tab but videos will only show videos from channels in that channel group instead of all subscribed channels.

### Why do you want this feature?

I can make channel group based on topics eg. Tech, Sports etc. but can not set a particular channel group as my default homepage/feed (by setting as first tab on main page). 

### Additional information

It can be set from Settings > Content > Contents of main page > Add button > Channel Group (similar to channel page options present currently) > Choose desired channel group.

**Comment by opusforlife2** [comment] 2022-07-17 17:52
Duplicate of #3319

**Closed** 2022-07-17 17:53 UTC
Labels: template ignored, duplicate
