### ISSUE TITLE
[FR] set name of artists in downloaded songs

### ISSUE THREAD

**Issue by ahmedzs** [TeamNewPipe/NewPipe#1241] opened 2018-04-01 22:05 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

naming artist field of downloaded songs to the name of channel, set album to 'name of channel - playlist name'

**Comment by Stypox** [comment] 2019-07-19 13:08
Duplicate of #183

**Closed by Stypox** 2019-07-19 13:08 UTC
