### ISSUE TITLE
21:9 Fullscreen support

### ISSUE THREAD

**Issue by developerfromjokela** [TeamNewPipe/NewPipe#2827] opened 2019-11-26 21:06 UTC
Hello,

(**This is a feature request** )

I'm using 21:9 phone, and watching 16:9 on 21:9 is little bit annoying. Google's YouTube app has that feature, so it will be nice one to have in NewPipe.

 
**update** 

I've found way to do it, it's the Fit button.
But for excellent UX, you can implement it like Google, just to do a zoom gesture, and done.

**Comment by B0pol** [comment] 2020-05-10 17:48
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3181

**Closed by B0pol** 2020-05-10 17:48 UTC
Labels: GUI, enhancement, player

**Comment by developerfromjokela** [comment] 2020-05-11 02:32
How is this a duplicate if I requested the feature way before him?

**Comment by Stypox** [comment] 2020-05-11 11:52
That's not the point. The point is that only one issue should stay open, and that other issue is a little bit more clear, and has already been pointed to by a pr

**Comment by developerfromjokela** [comment] 2020-05-18 17:22
Ok
