### ISSUE TITLE
Volume change on start or resume of playback

### ISSUE THREAD

**Issue by probotico** [TeamNewPipe/NewPipe#2833] opened 2019-12-01 13:11 UTC
- [v ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [v ] I checked if the issue/feature exists in the latest version.
- [x ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi, I'm encountering some issues on the audio playback, only tested on videos, mpeg m4a, when android media volume setting is on lowest possible (not muted).

Start video playback
Change to popup mode
Volume spikes then gets to correct value.

Resume video playback
Volume spikes 

Start video playback 
adjust volume to lowest setting 
Change to popup player
Volume spikes

From popup to player, also volume spikes

Hope you can reproduce bug on newpipe 17.4
Running android 7.1.2

Cheers

# -------------------

Another instance of this bug by @jmbreuer:
I sometimes have a network connection that even for just audio playback using the background player cannot keep up.

When the buffer empties, there's a gap of silence (obviously). When there's data coming in again, playback resumes with a spike of much louder volume, quickly (50-200ms at a guess) returning to the previous playback volume. Especially with headphones, those spikes can be quite painful.

(Conjecture: are 'empty' frames being fed to the decoder so it loses its playback gain tracking?)

Also, I had the impression that bits of audio (less then a second long) would repeat and stutter multiple times in that situation.

**Comment by XiangRongLin** [comment] 2019-12-13 18:30
I can reproduce it on my Android 7.1 device, but surprisingly it doesn't occur on my Android 10 one. Does someone else have a 8/9/10 device and could test it there.

**Comment by gillhash** [comment] 2020-01-31 02:31
Yes volume spikes on mine Samsung J2 Pro too.
Running android 6.0.1
Using Newpipe 18.2
@B0pol hopefully this issue be resolved bit early. Sadly can't find any related PR.

**Comment by mauriciocolli** [comment] 2020-03-07 18:32
Noticed this as well, debugged everything in the app and ended up in the only thing that made a difference in my device: the audio equalizer (in my case, the app to manage it was AudioFX).

@probotico @XiangRongLin @gillhash @jmbreuer Can you disable it and test if it still happens?

**Comment by XiangRongLin** [comment] 2020-03-07 18:40
@mauriciocolli 
can confirm it on my 7.1 device

**Comment by opusforlife2** [comment] 2020-05-02 15:19
I just recently created a new config in AudioFX to reduce volume, and I immediately noticed the volume spikes. I haven't tried it, but I'm sure that if you were to instead _increase_ the default volume in your config, you would notice volume _dips_ instead of spikes.

**Comment by opusforlife2** [comment] 2020-05-05 19:55
I was researching this a bit. It turns out that the guys at LineageOS tried to fix AudioFX: https://review.lineageos.org/c/LineageOS/android_frameworks_av/+/241472

but had to abandon it because of regressions: https://review.lineageos.org/c/LineageOS/android_frameworks_av/+/241802

and another attempt also didn't work out:
https://review.lineageos.org/c/LineageOS/android_frameworks_av/+/242705.

**Comment by opusforlife2** [comment] 2020-08-12 20:41
So... close as out of scope for Newpipe?

**Closed** 2020-08-12 20:58 UTC
Labels: bug, device/software specific, player
