### ISSUE TITLE
Automatic subscriptions refresh and (don't know if it's possible) video suggestions

### ISSUE THREAD

**Issue by Muda42** [TeamNewPipe/NewPipe#3549] opened 2020-05-07 09:34 UTC
It would be nice to have video suggestions and the ability to atomatically refresh the subscription feed

**Comment by Stypox** [comment] 2020-05-07 12:33
*Please **follow the issue template** when creating an issue, don't just delete everything!* Anyway, this is a duplicate of #2854, and auto subscription refresh has also already been proposed

**Closed by Stypox** 2020-05-07 12:33 UTC
Labels: enhancement
