### ISSUE TITLE
Regression - Share and other buttons in video details

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#4039] opened 2020-08-01 12:59 UTC
### Version

- 0.20.0

## Problem 
Now that the unified player PR is merged, let me be the first to add a bug to the Unified Player project (https://github.com/TeamNewPipe/NewPipe/projects/17).

We need to find a way to place the Share button back somewhere on the video details page.

Edit: List of buttons reported to be missing:
- Share
- Resolution selector
- Cast to Kodi

List of other possibly useful buttons:
- Play in external player
- Playback speed
- Fit/Fill/Zoom
- Captions
- Mute
- Open in browser

### Solution
~My suggestion was that it could be placed next to the Autoplay toggle.~

From the discussion below:

- How about a left to right swipeable list where the 4 action buttons are? The default visible actions would be the most used ones, and the lesser used ones could be swiped into view, 4 at a time.
- Better would be to allow to rearrange them via long tap and drag.
- I also think it should show as many buttons as possible on that device, e.g. a tablet in landscape will definitely be able to show more than 4 buttons I think.
- Actually, now that I think about it, that right arrow indicator should be present for all form factors, not just TV. We have to let the user know there is something new there, after all. A right arrow beside the download button would be obvious enough to be noticed. Otherwise mobile users would likely not know about this feature until they accidentally swipe sideways in just the right way or read about the feature online.
- Moreover, once the user has swiped left once to access the next 4 action buttons, we should also show a left arrow indicator next to the first action button, as well.

**Comment by avently** [comment] 2020-08-01 13:33
What do you call 
> Autoplay toggle.

?
And why don't you like current place of share button?

**Comment by opusforlife2** [comment] 2020-08-01 15:08
Same as I said here: https://github.com/TeamNewPipe/NewPipe/pull/2907#issuecomment-663261604

Basically, we currently have a Share button in the top bar (menu bar?) which is gone now, since the entire bar is gone after your PR. This contained the resolution selector and the share button. Resolution selector isn't that important because using it shows intent to play the video anyway, so you might as well change it after playing the video.

But not having a way to share the link without playing the video first, is a regression. So I suggested to put the Share button here:

![d172e35c-a6b4-4fe9-b7c7-ecb5c0c40d6d](https://user-images.githubusercontent.com/53176348/89104371-89814a00-d408-11ea-9d04-7c4ff15383d8.png)

I thought you didn't like the idea. Now I get the feeling it was just a communication gap between us. 😆

**Comment by avently** [comment] 2020-08-01 15:44
> I thought you didn't like the idea. Now I get the feeling it was just a communication gap between us.

I just didn't get in the PR thread what you mean by autoplay toggle:) I didn't even think about that area in the page because it's hidden all the time (comments is visible almost always)

> a communication gap between us

The issue with a share button is a gap between us. I use it a couple of times in my life and I don't think it should be visible on the page at. It's not useless but it's unused all the time. So I think the current position is good for an unused element.

Let's say someone will come here and say that he wants to see subtitles, or mute, or scale button near autoplay toggle, what will you say? You'll probably say that it's insane idea because these things are unused. This is how I feelling about share button.

**Comment by wb9688** [comment] 2020-08-01 15:54
@avently: I'd like to point out that there is a difference between the in-player share button and the share button that previously was at the top. The latter keeps the original URL, while the later first simplifies the URL and then adds the current timestamp (if possible for that service).

I do agree that next to the autoplay button isn't the right location for it imho.

**Comment by avently** [comment] 2020-08-01 16:05
> while the later first simplifies the URL and then adds the current timestamp (if possible for that service).

So is there situation when you need the first instead of the second? If so, it is possible to show an AlertDialog with both links. Isn't it the fix?

**Comment by opusforlife2** [comment] 2020-08-01 16:40
@avently
> subtitles, or mute, or scale button near autoplay toggle

They are in the same situation as the resolution selector. As I said above, you only need these once the video is _already_ playing. But that is not the case with sharing. Having to first play a video before being able to share it doesn't make sense. Here's how it would go:
1. You're on the video details page.
2. You tap on the video to play.
3. Tap again to show player controls UI.
4. Tap on the expansion arrow.

Now it's either:

5. Tap on Share.
6. Select an app to share to.
7. Scrub the timestamp from the URL manually.
8. Send the link.

or, if you implement an AlertDialog:

5. Tap on Share. AlertDialog opens.
6. Select the simple share option.
7. Select an app to share to.
8. Send the link.

Your solution is still the same number of steps, just like before. The only thing it is helping with is that the manual timestamp removal is gone.

On the current release, this is the how it goes:

1. You're on the video details page.
2. Tap on Share.
3. Select an app to share to.
4. Send the link.

See the difference?

As for a counter example, take the resolution selector.
In current release, you can:

1. Select resolution.
2. Play video.

After your PR:

1. Play video at default resolution.
2. Change resolution. Takes a few seconds to load the stream.

That's it. The only addition there is a few seconds. So I don't mind it much.

@wb9688
> I do agree that next to the autoplay button isn't the right location for it imho.

Yeah, it's just the first empty space I thought of that didn't seem problematic. Any ideas?

**Comment by avently** [comment] 2020-08-01 16:55
> Your solution is still the same number of steps

I'm not saying it's for effective than yours in terms of number of steps. But it's better logically (unused thing on unused place).

> Any ideas?

I see only only two solutions:
1. add a button on top of a thumbnail (like with three dots icon) in the right corner. So it will be visible only when there is thumbnail shown instead of a player. Not good solution and will not save you a one tap. Also this button can be shown in the bottom left corner after duration. 
2. Replace download buttons with something like "Actions" which will present bottom sheet dialog like Youtube do with many actions. This one is better since download button is often unused too.

I don't like both solutions but second one is probalby the way how it should work. Don't forget that there is a open in browser button which should be moved out of player too.

**Comment by opusforlife2** [comment] 2020-08-01 16:59
> Don't forget that there is a open in browser button which should be moved out of player too.

Actually, I'm not sure why that button exists. You can select your browser from the Share sheet directly.

**Comment by opusforlife2** [comment] 2020-08-01 17:06
> Replace download buttons with something like "Actions" which will present bottom sheet dialog like Youtube do with many actions. This one is better since download button is often unused too.

Hmm. How about a left to right swipeable list where the 4 action buttons are? The default visible actions would be the most used ones, and the lesser used ones could be swiped into view, 4 at a time. Maybe the buttons could change positions based on frequency of use.

If this is a viable solution, then I think swiping them to view 4 at a time would be better than a loose scrollable list, because tapping on the action buttons could become tedious.

**Comment by avently** [comment] 2020-08-01 17:19
> The default visible actions would be the most used ones, and the lesser used ones could be swiped into view

That's great solution! Not sure about frequency of use because buttons changing their place is kind of annoying and unexpected. Better would be to allow to rearrange them via long tap and drag. But scrollable list is useful. Not many buttons have to be there. Maybe someone will implement it, I hope so.

**Comment by opusforlife2** [comment] 2020-08-01 17:41
> Better would be to allow to rearrange them via long tap and drag. 

Yeah, that makes more sense.

**Comment by B0pol** [comment] 2020-08-01 17:47
Swipe doesn't work with Android TV

**Comment by opusforlife2** [comment] 2020-08-01 17:49
> Swipe doesn't work with Android TV

An arrow indicator at the right for TV, then? When you reach the rightmost action button, another right arrow command from the remote would scroll ahead.

**Comment by wb9688** [comment] 2020-08-01 19:20
@opusforlife2: I'm pretty sure it'll just go to the next button when you press right at the last visible button on TV in the kind of swiping thing you meant.

**Comment by opusforlife2** [comment] 2020-08-01 19:23
Oh. Then what about this? When the cursor (box) is on the rightmost action button, another right command would shift the cursor to the right arrow itself. Then it can be clicked on to do the swipe action.

**Comment by wb9688** [comment] 2020-08-01 19:25
@opusforlife2: I meant that your initial swiping idea should just work fine out of the box on Android TV, similar to how you could also e.g. just scroll in the search results (but horizontally instead of vertically obviously).

**Comment by opusforlife2** [comment] 2020-08-01 19:26
Oh. I thought you meant the cursor would shift to the suggested videos list on the right.

**Comment by opusforlife2** [comment] 2020-08-01 19:33
Actually, now that I think about it, that right arrow indicator should be present for _all_ form factors, not just TV. We have to let the user know there is _something new_ there, after all. A right arrow beside the download button would be obvious enough to be noticed. Otherwise mobile users would likely not know about this feature until they accidentally swipe sideways in just the right way or read about the feature online.

Moreover, once the user has swiped left once to access the next 4 action buttons, we should also show a left arrow indicator next to the first action button, as well.

**Comment by opusforlife2** [comment] 2020-09-09 12:49
Wow. @XiangRongLin already suggested a scrollable action bar months ago here: https://github.com/TeamNewPipe/NewPipe/issues/3583#issue-617583985

**Comment by Younes-L** [comment] 2020-10-05 07:07
Hello, I'd like to know why the action bar was removed :(
Thankfully the navigation drawer is finally accessible from the video info screen.

My suggestion is that these action buttons are way, way more important than comments or related videos.
Just push the comments down a 2nd row and put any missing button a 2nd row.
In this such a way there will be no need for additional taps and swipes and clues, as the buttons will be immediately visible.

@opusforlife2 I believe it is now master branch , 0.20.0

**Comment by opusforlife2** [comment] 2020-10-05 07:08
Changed. Thanks.

**Comment by sanityormadness** [comment] 2020-10-08 00:07
For the record, I use the Share button on the details page all the time after I've finished watching.

Know why? #2277

**Comment by MD77MD** [comment] 2020-10-08 01:18
not so related, but could anyone help me to understand what the three highlighted share buttons do or do differently (numbered in green).. examples/usages are much appreciated.

![Screenshot_20201008-040322](https://user-images.githubusercontent.com/63132171/95403881-2934ea00-091c-11eb-9007-fd64d184232d.jpg)
![Screenshot_20201008-040428](https://user-images.githubusercontent.com/63132171/95403900-3baf2380-091c-11eb-9f90-49f3a2644bc6.jpg)

**Comment by wb9688** [comment] 2020-10-08 07:09
@MD77MD: 1 opens the RSS feed, 2 is for sharing with friends, 3 opens it in your (default, if possible) browser

**Comment by WeAreJMJ** [comment] 2020-10-08 08:11
My suggestion would be to make the menu items always visible in the player window, ie, even before the playback is initiated. 

The items that wont work without loading (like captions) can be limited to defaults like auto-generated.

Resolution menu will be instantly available like prior to 0.20.0, while the share button will be need a click more. Open in browser will be require the same number of actions( pressing arrow instead of threedot menu)

**Comment by nbmrjuhneibkr** [comment] 2020-10-09 11:36
Why not just put the top menu bar back where it belongs? Why was it even necessary to remove it in the first place?

**Comment by nbmrjuhneibkr** [comment] 2020-10-09 13:33
Inaccessible Share option is just a part of the larger problem caused by the removal of the top bar.

1. If I already know that I want to open video in an external app, why would I want to start playing it in NewPipe first?
2. Same goes for the video quality: if I know that I want to play a video in a quality that is different from the default, why would I want to start playing it in the default quality first (wasting limited mobile data)?
3. Combined with #4460 this also means that I can't share a video or open it in a different app without wiping my background queue.

0.18: https://imgur.com/a/eIN92cj
0.20: https://imgur.com/a/8SFhoya

This is terrible design and a clear step backwards from v0.18. These options should be re-implemented.

**Comment by Stypox** [comment] 2020-10-11 13:59
I don't like the summary proposal on top by @opusforlife2, because most of the buttons would not be needed while the player is playing. Share, open in browser, playback speed, resolution, etc. are all accessible from within the player, so they shouldn't also be shown below. Instead, what about adding some buttons on top of the non-playing player? Something like this:

<img width="300px" src="https://user-images.githubusercontent.com/36421898/95680523-b6a56200-0bda-11eb-9ac7-7e1f68899e17.png"/>

**Comment by opusforlife2** [comment] 2020-10-11 14:16
Other people have presented their own use cases, but for me, personally, a non-timestamp Share button is absolutely a must to have without having to play the video. That is why I opened the issue. If there can be a Share button in an overlay on top of the thumbnail, I'll be happy.

But what would users with Autoplay turned on do, @Stypox? Your solution seems discriminatory against them, having useful buttons they will never get to access.

I still think the swipe-able list is a better UI.

**Comment by Stypox** [comment] 2020-10-11 14:24
> a non-timestamp Share button is absolutely a must to have without having to play the video

That's a different issue. The button inside the player should provide a way to share the video without a timestamp, too, and maybe in the same menu we should also show "open in browser" and "open in external player with specific resolution" and possibly more sharing options. Anyway yes, a share button would be there.

> having useful buttons they will never get to access.

All of the buttons shown there would also be accessible inside the player, as I said above: share, open in browser, playback speed, resolution, Fit/Fill/Zoom, etc.

**Comment by avently** [comment] 2020-10-11 14:29
@Stypox what about showing three dots button in place of your proposal instead of many buttons? One vs many

**Comment by opusforlife2** [comment] 2020-10-11 14:39
Yet another idea: Show "More Options" or something as an expandable header below the 4 button row, revealing all the extra options we want there to be, pushing down comments/related streams, just like expanding the video description pushes down comments/related streams.

**Comment by avently** [comment] 2020-10-11 14:43
@opusforlife2 that's nice! Instead of download button

**Comment by opusforlife2** [comment] 2020-10-11 15:03
Works for me.

This would become very similar to Quick Settings. Although instead of an Edit Menu where the buttons can only be dragged into the actual settings, this expandable menu would contain usable buttons. I suppose we could even have an actual Edit button to drag and drop the 3 most useful ones into the permanent row.

**Comment by WeAreJMJ** [comment] 2020-10-11 19:33
> that's nice! Instead of download button

Then that would need the capability to rearrange the buttons,since the download function already needs a few taps more than background play,etc.

Long pressing videos doesn't present a download option. So hiding it will mean permanently deprioratizing it...

**Comment by WeAreJMJ** [comment] 2020-10-11 19:38
> Instead, what about adding some buttons on top of the non-playing player

This would be better in my opinion #4444.

**Comment by nbmrjuhneibkr** [comment] 2020-10-15 20:25
Another use case in which current implementation of the "Share" feature is completely unusable: https://github.com/TeamNewPipe/NewPipe/issues/4519#issuecomment-709569012

**Comment by cyber199** [comment] 2020-10-16 11:36
Coming from my own (duplicate, oops) issue, may I make a suggestion regarding the four big action buttons?

I'm not a fan of gestural interfaces at all, and I'm not sure I like the idea of swiping left and right to access more buttons.  Since the four buttons always appear above the video description, why not show more buttons when the description is expanded?  They don't have to be as large as the current four, but it would have extra functions just one click away.  This would also be a good place for an Edit Layout button as proposed, which I could see myself making use of (I rarely if ever use the popup/floating player, for example, so would much like to replace it with another function without hiding the popup button altogether).

**Comment by rancidfrog** [comment] 2020-10-22 09:44
Took me a while to find share button.
Only issue is why is there no menu in pop-up player to share?
Full video player
![](https://i.imgur.com/Ce5GtPu.jpg)

vs
Pop-Up
![](https://i.imgur.com/7gDNEGu.jpg)

Is it not possible to have the same implementation in both?
That way there is continuance in design and users will not be confused where to find those buttons

**Comment by B0pol** [comment] 2020-10-22 17:14
No, because popup player has less free room for icon

**Comment by rancidfrog** [comment] 2020-10-22 18:27
@B0pol

Sorry, that makes no sense
Instead of the full screen icon, the arrow could be used moving full screen below, it takes the same amount of space as the other icons already displayed, it is even smaller.
Or it could be right beside 360p 1x as in first image above

The only issue is if the pop-up is too small, but then how are the other icons handled?

I do not understand what the issue is:
Full player:
![](https://i.imgur.com/FTR1IuS.png)

![](https://i.imgur.com/jx1UsLa.png)

Pop-Up player
![](https://i.imgur.com/ghnFZsV.png)
 
Clearly there are already icons on display in pop-up player
replacing full screen with arrow or keeping the arrow key in same position as full player - beside 360p 1x ^
should be possible too

**Comment by opusforlife2** [comment] 2020-10-22 18:51
@rancidfrog This is off-topic here. Could you open a new issue for this? Thanks.

**Comment by rancidfrog** [comment] 2020-10-23 04:43
@opusforlife2
Sure.
But is will just be another issue about share button?

**Comment by B0pol** [comment] 2020-10-23 05:35
There is no space here @rancidfrog 

<img src="https://i.ibb.co/jfQyg0B/Screenshot-20201023-073336-Firefox-Nightly.png" width="300">

And even if theorically there is space, popup player is supposed to be minimalistic and not bloated.

Android's picture in picture mode has only a play / pause button.

**Comment by rancidfrog** [comment] 2020-10-23 06:21
@B0pol

You were saying:
![](https://i.imgur.com/khCjC2V.png)

Just to bother you.
You see - if you replace full player mode with arrow icon then you can have the same expanding list with share|full screen|  etc.

And, this is the smallest pop-up player can go.
So, full-screen will need to be replaced with arrow icon which expands with list of options.

For future comments regarding this issue #4601
As @opusforlife2 suggested since this is his issue after all 

This might be a slight design change in regards to the implementation, but it is the same logic.
Since same arrow key will be used, just space issues firces list view

**Comment by poutnikl** [comment] 2020-10-29 08:56
I suppose many NP users frequently revisit NP for video they already know or have. They are not interested in watching, but in fetching a link to share. Having to watch it does not make much sense. Additionally, they may prefer external players.

**Comment by rancidfrog** [comment] 2020-10-30 13:14
@poutnikl
An easy way would be to go to history and long-press that video and select share.
But, this works well if you watched video and if it was recently watched.
Otherwise it would be a hassle to scroll through history to find the video.

**Comment by poutnikl** [comment] 2020-10-30 13:22
@rancidfrog It may work for video watching. But for many cases, I am only interested in downloading the audio part, and later eventually in sharing YT link for others to watch/listen.

**Comment by bunyevacz** [comment] 2020-10-31 19:16
One serious drawback for the current share button location, that you *need* to start (and also redownload!!) the video again to be able to access the functionality.

This is my workflow:
I download all the videos, which I want to listen/watch next day during my work on my home internet connection via wifi.

When I want to check the comments, I click on the video in my "downloaded" tab, and "show info". Then I need to start the video, but I'm not on my home internet connection rather on my mobile internet connection which is a scarce resource, and I really need to think twice if I want to view a video of that connection. 1 GiB data usage is not much for a whole month. (in my case).

I think the share button should be accessible withouz causing video download.

Sorry for the long explanation and thank you for your time and attention.

**Comment by Hund** [comment] 2020-11-16 05:16
Why is this taking so long to fix? It's super annoying that one of the most used feature was removed. :(

**Comment by nbmrjuhneibkr** [comment] 2020-11-16 13:51
Because someone has spent way too much time and effort removing lots of features from 0.20 release. Now someone else has to make a comparable effort to re-implement them.

**Comment by Hund** [comment] 2020-11-16 14:52
> Because someone has spent way too much time and effort removing lots of features from 0.20 release. Now someone else has to make a comparable effort to re-implement them.

Why do that with the stable branch though? :)

**Comment by opusforlife2** [comment] 2020-11-16 15:16
> Why is this taking so long to fix?

@Hund There is a PR linked which you can test and give feedback on.

> Why do that with the stable branch though? :)

There is no "stable branch". Newpipe has only one release track.

@nbmrjuhneibkr I'm minimising your comment because of its passive-aggressiveness.

**Comment by Stypox** [comment] 2020-12-09 13:18
Go cast your vote at https://github.com/TeamNewPipe/NewPipe/pull/4534#issuecomment-741700417

**Closed** 2021-01-17 19:02 UTC
Labels: GUI, bug

**Comment by opusforlife2** [comment] 2021-01-20 19:48
Woohoo! My Share button!
