### ISSUE TITLE
New Intent: Play audio in background

### ISSUE THREAD

**Issue by lightonflux** [TeamNewPipe/NewPipe#991] opened 2018-01-13 20:26 UTC
Currently NewPipe has a normal intent and one for the pop up mode. 

It would be very useful it it also had a intent to stream the audio in the background. 

This is extremely convenient when friends send you a yt music link and you don't want to see the video and save some bandwidth. Or when you find links to lecture or panel discussion on reddit. 

---
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

**Comment by speednroll** [comment] 2018-01-13 20:29
this is a joke? 😂 the background player has been implemented for a long time

**Comment by wb9688** [comment] 2018-01-13 20:34
@speednroll: He means when you click on a YouTube link, there's an "Open
with" menu from Android where you could choose between NewPipe, NewPipe
pop-up mode and Firefox (on my phone, others may have Chrome or also
YouTube or whatever). He wants an additional option to directly open
NewPipe background mode.

**Comment by speednroll** [comment] 2018-01-13 20:39
@wb9688 I understood it very late so I retract and delete the comment 😑

**Comment by mauriciocolli** [comment] 2018-01-13 20:40
Duplicate of #643

**Closed by mauriciocolli** 2018-01-13 20:40 UTC
Labels: duplicate
