### ISSUE TITLE
Play videos using url or file path of SD card

### ISSUE THREAD

**Issue by polaris0227** [TeamNewPipe/NewPipe#2602] opened 2019-09-05 06:00 UTC
How to play *.mp4 file using its file path or url?
I'd appreciate if anyone help me on this.
Its video player is perfect, but only plays the videos extracted by its extractor.
It would be great if it supports playing using url or path like other video apps.
Thanks.

**Comment by Stypox** [comment] 2019-09-05 06:14
Duplicate of #1052

**Closed** 2019-09-05 06:14 UTC
