### ISSUE TITLE
Request: Add time filter on searched result like in Youtube (Anytime, this week..)s 

### ISSUE THREAD

**Issue by s-amasha** [TeamNewPipe/NewPipe#6324] opened 2021-05-18 00:20 UTC
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I think it would be nice if you add time filter on the searched results which helps to check videos in certain time range.

Like in Youtube, after you make the search, you'll be able to filter search by specific time like :
Anytime (default)
Today
This week
This month
This year

I use this when I'm tracing some subject and want to see most recent videos of it.

Thanks.

**Comment by infinitewaveparticle** [comment] 2021-07-28 18:33
This is one of the most important features for youtube search. It would be awesome to be able to search for specific time ranges too (for example, only videos from 2011). This allows the user to find exactly what they're looking for with ease.

**Comment by infinitewaveparticle** [comment] 2021-07-28 18:57
I guess this is a duplicate of #110 ... may I make an off-topic suggestion that we make - and pin - a poll of about 20 feature requests and have all frequent lurkers and commenters here (basically NewPipe enthusiasts) rank them in the order of importance? Then perhaps the top 1 or 2 could have links to contribute to bounties? If everyone who could all pitched in $1 - $10 maybe we'd see some really old feature requests implemented. This one in particular would double the appeal of this app (at least in my opinion).

**Comment by opusforlife2** [comment] 2022-05-05 21:24
Should have been closed as duplicate of #2251. Doing that now.

**Closed by opusforlife2** 2022-05-05 21:24 UTC
Labels: enhancement
