### ISSUE TITLE
Playlist perpetually loads when 2nd video starts

### ISSUE THREAD

**Issue by reg0lith** [TeamNewPipe/NewPipe#6950] opened 2021-08-21 06:40 UTC
I have a custom playlist that I use at night for relaxation, and it is one 30-minute video that loops 2 or 3 times. As soon as it finishes the first time, it gets stuck perpetually loading the 2nd time.

**Comment by ktprograms** [comment] 2021-08-23 13:19
Seems like this would have been fixed in #6712. The fix is not in the current latest version (0.21.8), see https://github.com/TeamNewPipe/NewPipe/pull/6712#issuecomment-892162526 and https://github.com/TeamNewPipe/NewPipe/pull/6712#issuecomment-892426734.

**Comment by mhmdanas** [comment] 2021-08-23 22:36
It is as @ktprograms says. If you find the problem is not solved in 0.21.9, please make a comment.

**Closed by mhmdanas** 2021-08-23 22:36 UTC
Labels: bug, user-ignored-template-instructions
