### ISSUE TITLE
Dash Protocol Support

### ISSUE THREAD

**Issue by moriel5** [TeamNewPipe/NewPipe#2852] opened 2019-12-09 08:17 UTC
Is the Dash protocol supported? And if so, is it supported for downloads as well?

I'm saying this since on NewPipe I have less options (be it playback or downloads) when viewing the list of streams, with GetTube showing additional (Dash) streams.

This is with both video and audio (GetTube also allows you to choose from video+audio, video-only, and audio-only).

Currently, downloading videos is the only reason I still keep GetTube around (NewPipe fits my needs better), since usually the "Dash" mp4 and m4a streams shown on GetTube are lighter than their non-"Dash" variants.

**Comment by Stypox** [comment] 2019-12-09 20:20
As far as I know Dash playbacks are not supported as of now

**Comment by moriel5** [comment] 2019-12-10 06:50
Are there any plans for Dash playback support in the near future?

**Comment by B0pol** [comment] 2020-05-10 17:44
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2415

**Closed by B0pol** 2020-05-10 17:44 UTC
Labels: enhancement, requires extractor change, youtube
