### ISSUE TITLE
Add option on channel page to add in channel group

### ISSUE THREAD

**Issue by brnwlshubh** [TeamNewPipe/NewPipe#7962] opened 2022-02-27 16:55 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

While subscribing any YT channel page and again adding to channel group is much lengthy process.

### Why do you want this feature?

Add an option on channel page to add in channel group

### Additional information

Suggestion:- To add in 3 dot option inclusive of Settings & Open in Browser.

**Comment by SameenAhnaf** [comment] 2022-02-27 18:30
Duplicate of #5836

**Closed** 2022-02-28 02:17 UTC
Labels: enhancement
