### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by xTheDevilRazedMe-Tyler** [TeamNewPipe/NewPipe#9947] opened 2023-03-20 18:32 UTC
{"user_action":"ui error","request":"ACRA report","content_language":"en-US","content_country":"US","app_language":"en_US","service":"none","package":"org.schabi.newpipe","version":"0.25.0","os":"Linux lge/cv1_lao_com/cv1:8.1.0/OPM1.171019.019/192891358c1fc:user/release-keys 8.1.0 - 27","time":"2023-03-20 13:31","exceptions":["android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1790)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6651)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)\n"],"user_comment":""}

**Comment by AudricV** [comment] 2023-03-20 20:56
Duplicate of existing issues related to this stacktrace.

Please search (better, with different keywords?) for duplicates and use our issue templates from our GitHub repository the next time you want to open an issue.

Thank you.

**Closed by AudricV** 2023-03-20 20:56 UTC
