### ISSUE TITLE
[BUG] Only 99 first playlist elements read in background

### ISSUE THREAD

**Issue by difto** [TeamNewPipe/NewPipe#1943] opened 2018-12-13 06:14 UTC
Minor issue with the playlist management. If you open a playlist that has more than 99 elements and play it in the background, only the elements that were displayed at that time are actually read. If you want to read more than the 99 first elements, you have to scroll the list (so that it loads 99 next items and so on) and then press play.

**Comment by Stypox** [comment] 2019-08-28 21:33
Duplicate of #875

**Closed by Stypox** 2019-08-28 21:33 UTC
