### ISSUE TITLE
Sometime a specific quality will never load

### ISSUE THREAD

**Issue by TheFrenchGhosty** [TeamNewPipe/NewPipe#2683] opened 2019-10-03 09:53 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Sometimes a specific quality will be completely broken on a video and will never load. Every quality will load almost instantly but this one will not for minutes to hours.

Example: https://youtube.com/watch?v=L3oqktdx2a8 720p will never load (tested on 2 devices).

Recording of the issue: https://i.imgur.com/ndYkBKP.mp4

#2509 and #2674 might be related

**Comment by Pentaphon** [comment] 2019-10-07 00:01
I have the same exact issue. Switching to webm for audio and video made Newpipe 0.17.3 work perfectly again. The dev should tell people that with a sticky on top of this issue list.

**Comment by OffifialMITX** [comment] 2019-10-08 08:56
@Pentaphon For me, MPEG-4 works on most settings, but WebM is pretty broken.

**Comment by IT-Tool** [comment] 2019-10-08 23:54
thanks for the idea! in my case, WebM works much better than mp4 (after the last update). while waiting for fixes from developers.

**Comment by gillhash** [comment] 2020-02-23 09:13
Another example: 
https://youtu.be/Liw-n_L0RG8

(MPEG-4) 360p & 720p will never load keeps spinning with msg "could not play stream"
Webm 720p loads though alongwith lower formats. Interestingly no Webm 360p option shows after selecting Webm.

**Comment by Stypox** [comment] 2020-04-20 07:53
Duplicate of #2415

**Closed by Stypox** 2020-04-20 07:53 UTC
Labels: bug, requires extractor change, youtube
