### ISSUE TITLE
video resolution settings seem to be ignored

### ISSUE THREAD

**Issue by thx101** [TeamNewPipe/NewPipe#10291] opened 2023-08-02 17:27 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

set lowest resolution of 144p for defaults and limit (to save bandwidth).
play video

### Expected behavior

low res/bandwidth video

### Actual behavior

video is played at much higher resolution

### Affected Android/Custom ROM version

android 7

### Affected device model

nvidia shield tablet k1

### Additional information

I've tried this with a couple of live news channels (sky news was one). In libretube it works and the low resolution is very noticeable.

**Comment by TobiGr** [comment] 2023-08-02 18:25
I cannot reproduce the issue. Please do the following:
1. Go to settings > content  > export database
2. E-Mail the zip file with a reference to this issue to `team[at]newpipe.net`

**Comment by TobiGr** [comment] 2023-08-02 18:28
Duplicate of #1239

**Closed by TobiGr** 2023-08-02 18:28 UTC
Labels: duplicate
