### ISSUE TITLE
Search not working, subs not updating

### ISSUE THREAD

**Issue by Y-42** [TeamNewPipe/NewPipe#6090] opened 2021-04-15 15:44 UTC
Search has not been working for some weeks and the latest update did not fix it for me. There were rare instances were the search function has worked though.

The subscription update only works irregulary.

**Comment by AnonymousSeal** [comment] 2021-04-15 23:37
+1

subscription has worked mostly, but search is broken completely

**Comment by mhmdanas** [comment] 2021-04-16 11:36
@Y-42 @AnonymousSeal do you live in the EU or use a VPN that connects to an EU country? If so, it's almost certainly a duplicate of #5977.

**Comment by AnonymousSeal** [comment] 2021-04-16 12:13
I used my vpn to connect to a non-eu country and it worked, but then i connected to a eu country and it didn't work so I switch out of the eu again and then it had problems loading, but i guess thats more of an issue with my vpn or internet provider. So anyways I also believe this is a duplicate

**Comment by mhmdanas** [comment] 2021-04-24 10:48
I'll be closing this for now, but if this proves to be different from #5977, please open a new issue that follows the template properly.

**Closed by mhmdanas** 2021-04-24 10:48 UTC
Labels: bug, more info needed
