### ISSUE TITLE
Player sometimes doesn't stretch properly after rotation

### ISSUE THREAD

**Issue by AioiLight** [TeamNewPipe/NewPipe#7634] opened 2022-01-09 14:11 UTC
### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any video
2. Tap fullscreen button to rotate screen
3. Reproduce

### Actual behavior

Sometimes, player doesn't stretch properly size.

### Expected behavior

Always, screen stretches properly size.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/13918537/148685059-19964206-82da-4e75-8d90-9e799661ed6c.mp4

### Device info

 - Android version/Custom ROM version: 12 / OxygenOS 12 C.40
 - Device model: OnePlus 9

**Comment by litetex** [comment] 2022-01-09 16:44
Duplicate of #7262

**Closed by litetex** 2022-01-09 16:44 UTC
Labels: bug
