### ISSUE TITLE
Please add that when i slow the video and i download it download with the slowness

### ISSUE THREAD

**Issue by Danielking132** [TeamNewPipe/NewPipe#7337] opened 2021-10-30 23:23 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment] 2021-10-31 09:17
Did you mean "Show Download Speed" feature? Also, please give a detailed description by filling the description properly. Devs are unable to help with such a little amount of information.

**Comment by Survingo** [comment] 2021-10-31 11:35
I think OP's feature request is the ability to download video with a custom tempo and pitch, which would make it a duplicate of #7129.

Please correct me if I am wrong

**Comment by opusforlife2** [comment] 2021-11-01 16:07
Please fill the template properly.

**Closed** 2021-11-16 00:07 UTC
Labels: enhancement, template-ignored, waiting-for-author
