### ISSUE TITLE
Add subtitle translation

### ISSUE THREAD

**Issue by liltingle** [TeamNewPipe/NewPipe#6106] opened 2021-04-18 21:04 UTC
#### Describe the feature you want
I would like to translate the subtitles of the videos, a feature that I only see on YouTube web, not on the app or NewPipe.

#### How will you/everyone benefit from this feature?
This feature is ideal for many people, as they can upgrade to multi-language videos without language barriers, plus they would be the first to have this feature in mobile apps.

**Comment by SameenAhnaf** [comment] 2021-04-19 10:20
Duplicate of #5656. Also, please don't remove the template. You are supposed to put an 'x' (letter exe) between third brackets to check s checkbox.

**Comment by liltingle** [comment] 2021-04-19 12:38
> Duplicate of #5656. Also, please don't remove the template. You are supposed to put an 'x' (letter exe) between third brackets to check s checkbox.

Of course yes, I mean automatic translation, which is not implemented in any app, the only viable option for this is to download the subtitles in text and translate it. Which is very time consuming.

**Comment by mhmdanas** [comment] 2021-04-21 15:38
See https://github.com/TeamNewPipe/NewPipe/issues/5338#issuecomment-761543751.

**Closed by mhmdanas** 2021-04-21 15:38 UTC
Labels: enhancement
