### ISSUE TITLE
"Sorry, something went wrong. REPORT"

### ISSUE THREAD

**Issue by phind431** [TeamNewPipe/NewPipe#5103] opened 2020-12-05 19:03 UTC
- [x] I am using the latest version - 0.20.5 
- [ x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Press the play button on any video

"Sorry, something went wrong. REPORT" is overlayed on screen at bottom.
This is apparently a comment bug. I had checked to SHOW comments and was getting them, or so I thought. After unchecking the box for comments and then rechecking it and reopening ap, comments have effectively ceased to exist.
The REPORT button does nothing as ap does not crash. Everything works but the ability to show, or not, comments. I was getting comments, but now I see this is most likely the actual "something's wrong..." message. In any case this message should be in notifications and not in my face as an overlay blocking normal controls.

### Expected behavior

I read the comments as they are half the content utube offers. Newpipe's ability to load comments is broken.

### Device info

 - Android version/Custom ROM version:
Android9 / lineage-16.0-20201107-UNOFFICIAL-microG-signed-oneplus3
 - Device model: Oneplus 3T global, rooted, fakestore etc.

**Comment by phind431** [comment] 2020-12-05 19:08
A closed issue would be one that no longer exists.
I was reading comments just yesterday so the error is one that comes and goes. After unchecking the 'show comments, restarting ap, rechecking 'show comments', comments literally have ceased to exist.

**Comment by xibr** [comment] 2020-12-05 20:58
Does your issue have anything to do with this TeamNewPipe/NewPipeExtractor#455

**Comment by mhmdanas** [comment] 2020-12-06 09:02
It is probably a duplicate of TeamNewPipe/NewPipeExtractor#455 like @xibr says. If it is not, please ping me and I'll re-open this issue. Thanks!

**Closed by mhmdanas** 2020-12-06 09:02 UTC
Labels: bug
