### ISSUE TITLE
Youtube no longer offers subscription list download

### ISSUE THREAD

**Issue by QL568A6** [TeamNewPipe/NewPipe#4775] opened 2020-11-02 15:47 UTC
I followed the link in the [NewPipe FAQ page](https://newpipe.schabi.org/FAQ/tutorials/import-export-data/#import-youtube): https://www.youtube.com/subscription_manager?action_takeout=1

This causes a redirect to: https://www.youtube.com/feed/channels

The download doesn't start and there is no link/button/etc to download the list. I can't find anything in the settings, either.

I have tried this on Opera, Firefox, Seamonkey, and Edge.

I suspect that Youtube has removed the feature altogether to prevent exactly this sort of use.

Thus, NewPipe probably needs to find another way to import subscriptions.

**Comment by RickyM7** [comment] 2020-11-02 15:52
Have you tried to access the site in Desktop mode? It is that I also had problem with this and entering the site in desktop mode solved the problem.

**Comment by opusforlife2** [comment] 2020-11-02 15:56
Duplicate of #4720. Next time, fill the template given here: https://github.com/TeamNewPipe/NewPipe/issues/new/choose

**Closed by opusforlife2** 2020-11-02 15:56 UTC
