### ISSUE TITLE
[Android TV] Crash/NPE when launching a 2nd video from search

### ISSUE THREAD

**Issue by pihug12** [TeamNewPipe/NewPipe#8602] opened 2022-07-10 13:35 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.23.1

### Steps to reproduce the bug

Play a video. Search a 2nd video and start it while the 1st one is still playing.

### Expected behavior

The 2nd video should start.

### Actual behavior

It crashes.

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer [...]
  at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3724)
  [...]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Conte..'
  at org.schabi.newpipe.player.NotificationUtil.createNotification(NotificationUtil.java:92)
  [...]
```

### Screenshots/Screen recordings

![20220710_150447_cr](https://user-images.githubusercontent.com/678038/178146910-f9aa6a92-5134-4fb0-8ddc-4404f1aa3272.jpg)
![20220710_150507_cr](https://user-images.githubusercontent.com/678038/178146915-f39593a3-70f0-4222-91f0-f78e0dfaedd5.jpg)

### Affected Android/Custom ROM version

Android TV 9

### Affected device model

TV Box of a French ISP

**Comment by AudricV** [comment] 2022-07-11 17:09
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #8384. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2022-07-11 17:09 UTC
Labels: bug, Android TV
