### ISSUE TITLE
Text size ignores accessibility settings

### ISSUE THREAD

**Issue by gargargarrick** [TeamNewPipe/NewPipe#2786] opened 2019-11-06 07:24 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Up through version 0.17.3, NewPipe scaled text according to the size set in devices' accessibility settings. However, as of 0.17.4, it ignores this entirely. Even though I have set the base size to "huge", text is now rendered based on the "normal" size instead, which makes some items too small for me to read comfortably. I've attached a screenshot comparing the text sizes before (left) and after (right) updating. (The text running together is a separate issue and I don't particularly mind it.) The devices I tested this on were a Samsung Galaxy On5 with Android 6.0.1 and an Amazon Kindle Fire HD 8.

![Text sizes in v.0.17.3 vs. 0.17.4](https://user-images.githubusercontent.com/11541883/68276521-33c76f00-003b-11ea-816a-ca32ca4f878f.png)

**Comment by testuser51** [comment] 2020-05-07 10:39
I am able to reproduce this.

NewPipe 0.19.2
Android: 10
Device: Redmi Note 7

I hope someone will fix this bug

**Comment by janTaja** [comment] 2021-08-18 19:20
Oh, so this is a bug. I almost asked for increasing font size as a feature.

Still the same in 0.21.8, my device is Samsung A3 (2017) with Android 8.

I really hope this will be fixed soon because right now the text is tiny and hard to read and the app is hard to use because of that.

**Comment by mhmdanas** [comment] 2022-05-22 11:21
Cannot reproduce with NewPipe 0.23.0 on Android 12. I'm closing this, but if you're still facing this issue, please leave a comment.

**Closed by mhmdanas** 2022-05-22 11:21 UTC
Labels: bug, GUI
