### ISSUE TITLE
Download queue can't download more than a video at a time

### ISSUE THREAD

**Issue by ballo** [TeamNewPipe/NewPipe#6565] opened 2021-06-23 22:57 UTC
If I want to download a bunch of videos quickly, I have to manage the download queue manually so I'm downloading two or three videos at once. The number of simultaneous downloads should be an option.

**Comment by SameenAhnaf** [comment] 2021-06-24 03:02
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/746. Also, please fill in the template properly.

**Closed** 2021-06-25 18:51 UTC
Labels: enhancement
