### ISSUE TITLE
Popout seems to die when re-opening the main app (or resuming playback)

### ISSUE THREAD

**Issue by cyphar** [TeamNewPipe/NewPipe#2493] opened 2019-08-05 17:13 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

This has been an issue in NewPipe for a couple of years, but I never got around to sending a bug report (since there was no real "crash" to paste in an issue). Effectively, the issue is that (seemingly randomly) when you have a popout video playing the popout will die when you re-open the main app. This also happens sometimes when you try to resume a paused video some time after you paused it.

I can try to rustle up a video of it (if I can get a useful reproducer), but I'm opening this issue for visibility to hopefully get some sort of resolution. I've had this issue on a Pixel 3 XL, Pixel 3a, OnePlus 1, OnePlus 5T, and I've seen other people hit this issue as well after I recommended they use NewPipe.

**Comment by TobiGr** [comment] 2019-08-05 17:54
> Effectively, the issue is that (seemingly randomly) when you have a popout video playing the popout will die when you re-open the main app.

Does this happen when you open NewPipe or when you start playing a new video?

> This also happens sometimes when you try to resume a paused video some time after you paused it.

This can be caused by an expired stream link.

**Comment by cyphar** [comment] 2019-08-05 23:45
> Does this happen when you open NewPipe or when you start playing a new video?

When you re-open NewPipe. Effectively the reproducer is something like:

1. Start playing an hour-long video on popout.
2. Switch to another app.
3. Do other actions, lock our phone, etc.
4. Go back to NewPipe, and the popout dies.

**Comment by opusforlife2** [comment] 2020-08-12 18:36
Fixed by #2907. The notification is always there if a video is paused, making it possible to resume.

**Closed by opusforlife2** 2020-08-12 18:36 UTC
Labels: bug, player
