### ISSUE TITLE
Takes time for transitions

### ISSUE THREAD

**Issue by Soumik0007** [TeamNewPipe/NewPipe#5272] opened 2020-12-25 11:25 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

It takes time for transition.For example if I am switching for a popup view the sound will get stopped and it will take some time to come in a popup view.

### Expected behavior
I want the transitions to be smooth as well as fast.

### Device info

 - Android version/Custom ROM version:4.4.4 KitKat
 - Device model:Samsung Galaxy Grand Prime

**Comment by mhmdanas** [comment] 2020-12-25 11:54
Duplicate of #5016.

**Closed by mhmdanas** 2020-12-25 11:54 UTC
Labels: bug
