### ISSUE TITLE
NewPipe opened itself and tried to play a blank video?

### ISSUE THREAD

**Issue by xxxxme** [TeamNewPipe/NewPipe#6167] opened 2021-04-25 12:24 UTC
### Checklist

- [x] I am using the latest version - 0.21.1 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.  (I don't know what non-vague key words to search with.) 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

I have downloaded and watched videos in the past, but I haven't opened NewPipe since rebooting my phone. There are no partially- or fully-downloaded videos in downloads.

### Actual behaviour

Twice now, I have found a notification from NewPipe on my phone which looks like it's playing a video, but the background is grey, and there's the buffering hourglass instead of the pause/play button. Once this happened while my phone was sitting out of sight with the screen off, once while I was holding it with the screen on in a sports tracker app (no Internet access, no urls displayed, no videos, etc.), my phone buzzed and the NewPipe notification appeared.

### Expected behavior

NewPipe wouldn't start itself with a null video, or whatever is happening.

### Logs

Log activity (matlog): This is the first instance of NewPipe in the log. I believe this begins around the time it started itself. I then 1) closed the notification 2) force killed it from app info in settings 3) re-opened it and looked at downloads 4) closed it normally

04-25 07:30:14.724 I/ActivityManager(2275): Start proc 14072:org.schabi.newpipe/u0a264 for broadcast org.schabi.newpipe/androidx.media.session.MediaButtonReceiver
04-25 07:41:30.383 I/ActivityManager(2275): START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:org.schabi.newpipe flg=0x10008000 cmp=com.android.settings/.applications.InstalledAppDetails bnds=[492,1505][1152,1673]} from uid 10143
04-25 07:41:39.078 I/ActivityManager(2275): Force stopping org.schabi.newpipe appid=10264 user=0: from pid 14338
04-25 07:41:39.081 I/ActivityManager(2275): Killing 14072:org.schabi.newpipe/u0a264 (adj 900): stop org.schabi.newpipe
04-25 07:41:39.279 W/BroadcastQueue(2275): Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_RESTARTED dat=package:org.schabi.newpipe flg=0x10 (has extras) } to com.google.android.gms/org.microg.nlp.PackageReceiver
04-25 07:42:02.273 I/ActivityManager(2275): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.schabi.newpipe/.MainActivity bnds=[960,1812][1200,2160]} from uid 10143
04-25 07:42:02.598 I/ActivityManager(2275): Start proc 14409:org.schabi.newpipe/u0a264 for activity org.schabi.newpipe/.MainActivity
04-25 07:42:20.466 I/ActivityManager(2275): START u0 {cmp=org.schabi.newpipe/.download.DownloadActivity} from uid 10264
04-25 07:42:32.988 I/ActivityManager(2275): Killing 14409:org.schabi.newpipe/u0a264 (adj 1001): remove task
04-25 07:42:33.061 W/ActivityManager(2275): Scheduling restart of crashed service org.schabi.newpipe/us.shandian.giga.service.DownloadManagerService in 1000ms
04-25 07:42:34.104 I/ActivityManager(2275): Start proc 14481:org.schabi.newpipe/u0a264 for service org.schabi.newpipe/us.shandian.giga.service.DownloadManagerService

### Device info

 - Android version/Custom ROM version: LineageOS 16.0
 - Device model: LG v30 H932

**Comment by mhmdanas** [comment] 2021-04-25 13:12
Looks like a duplicate of #5122. This line in the log practically confirms it:
```
04-25 07:30:14.724 I/ActivityManager(2275): Start proc 14072:org.schabi.newpipe/u0a264 for broadcast org.schabi.newpipe/androidx.media.session.MediaButtonReceiver
```

**Closed by mhmdanas** 2021-04-25 13:12 UTC
Labels: bug
