### ISSUE TITLE
Cannot play WebM 2160p60 on any device on any network

### ISSUE THREAD

**Issue by 24RJ6** [TeamNewPipe/NewPipe#1388] opened 2018-05-09 11:58 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

I tried this on a couple of top end devices: Note 8, S8, S9+. The first two also both with Nougat and Oreo firmware. I checked the option to always use the highest available resolution and for some reason always end up with WebM 2160p60 even when searching for 8k videos on YouTube. It doesn't seem like an issue with decoding speed, it always plays for like 1-2 seconds and then I get the loading/buffering circle for 1-2 seconds. I tried multiple networks and get about 100-200 Mbit downstream via the phones Wifi. It seems it can't get the data fast enough despite the bandwidth being available on the network level.

The videos play fine when downloaded in MX Player or VLC. These phones also play the [400 Mbit jellyfish stress file](http://jell.yfish.us/media/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv) smooth in MX Player with HW+ decoder. So there should be more than enough decoding power.

**Comment by theScrabi** [comment] 2018-05-10 09:10
@karyogamy we have to do something about the buffering. It's not the first time something like this happens. You said you changed some parameters there recently. Could we roll them back for the next release?

**Comment by karyogamy** [comment] 2018-05-10 13:53
@theScrabi 
Yes, let's do that. I'll create a fix PR soon.

@24RJ6 
> The videos play fine when downloaded in MX Player or VLC.

Did you download the files before playing them in external players? If so, can you please check if the video streams better on-demand (by enabling "Use external video player" option in the "Video & Audio" settings)?

If possible, can you please also use a network monitoring tool, such as [this](https://play.google.com/store/apps/details?id=com.internet.speed.meter.lite&hl=en), to see if the extracted stream url is rate-limited during on-demand?

**Comment by theScrabi** [comment] 2018-05-12 11:56
@24RJ6 I've created a test build with the changes made in https://github.com/TeamNewPipe/NewPipe/pull/1389. Please tell me if it works:
https://cloud.damken.com/index.php/s/wSyRd2yC15x2ZwT
passwort is: buffertest

**Comment by 24RJ6** [comment] 2018-05-16 15:54
OK, I think I figured why MX is choppy and VLC has issues, they play the 8k version and not the 2160. Let me see if I can get them to play the 2160 one as NewPipe claims to play.

**Comment by 24RJ6** [comment] 2018-05-16 16:00
Yes, 4k60p plays fine when using MX with HW+ as external player. No buffering or stuttering. Same fails with heavy buffering with embedded player. It's this movie:

https://www.youtube.com/watch?v=1La4QzGeaaQ

**Comment by 24RJ6** [comment] 2018-05-17 07:33
> @24RJ6 How did you get the link to stream 8k(4320p) on VLC or MX? NewPipe currently only support stream url extraction up to 4k60fps(2160p).

NewPipe hands an URI to MX/VLC that returns an 8k stream. I would even guess that NewPipe gets an 8k stream in it's internal player without knowing it. I can't answer why that happens, but here are the steps to reproduce:

1.) Set all options to highest resolution in NewPipe and configure external player
2.) Open https://www.youtube.com/watch?v=ChOhcHD8fBA in NewPipe and click play
3.) Click play and check the stream properties in MX/VLC

![screenshot_20180517-090814](https://user-images.githubusercontent.com/39123484/40162652-ed7016f2-59b4-11e8-9c5b-b10d8dd204f9.jpg)

> If you are using the app I referred to for getting this stat, then the connection is about 2.6 megabits per second, which may not be enough to smoothly stream 4K content.

It's MegaBytes per second. I checked both using the build in speed meter of my ROM as well as the bandwidth graph of my OpenWRT/LEDE router. Also MX has no buffering issues (it displays the progress in the seek bar), just stutters a bit with the 8k content.

**Comment by karyogamy** [comment] 2018-05-17 20:52
> NewPipe hands an URI to MX/VLC that returns an 8k stream. I would even guess that NewPipe gets an 8k stream in it's internal player without knowing it.

Ah, you are right. Youtube seems to use the same tag (itag 272) for multiple resolutions (4K and 8K), as seen [here](https://github.com/rg3/youtube-dl/blob/7550ea501a94ed9060220cf4c8f696e514862c1a/youtube_dl/extractor/youtube.py#L447), which the extractor currently has no way to differentiate. I'm not sure this will be fixed any time soon though, since this is an edge case we don't see too often in typical usage.

> 8K
> It's only NewPipe that fails at the buffering part.

This is likely because MX is rolling their own video renderer while we are using ExoPlayer's default renderer, which has the codec capping at certain maximum resolution. This number might be different depending on the device, though on my device with 1080p screen, the codec (OMX-VDEC-1080P) caps at 4096 x 4096.

As for the constant buffering, I think the culprit might be caching after all. With caching on, the player tries to read the cache instead of directly reading from the upstream data source, which can cause a delay or buffer depending on how fast your device writes. Since I can't fully test the difference out as my connection drops to below 1M/s after a while, which causes buffering on both the built-in player and MX, here's a [debug apk](https://github.com/TeamNewPipe/NewPipe/files/2014688/app-debug.zip) with caching disabled to test this out with.

**Comment by 24RJ6** [comment] 2018-05-17 21:06
The debug build is better, but still neither 4k60p nor 8k30p is playable more than a few seconds without buffering. There must be something else :(

Thanks for you dedication to track that down.

**Comment by karyogamy** [comment] 2018-05-17 21:13
Did you have debug builds already installed? Maybe the exisiting cache is interfering with the playback, and clearing the cache may help with that. Otherwise, I don't think there is much can be done at the moment, as I can't really reproduce smooth playback on MX :/

**Comment by Stypox** [comment] 2019-07-21 09:31
This is a duplicate of #1294, see my comment there. I'm leaving this open anyway since there is some useful information.

**Comment by Stypox** [comment] 2020-04-27 07:18
Duplicate of #2415

**Closed by Stypox** 2020-04-27 07:18 UTC
Labels: bug, duplicate, player
