### ISSUE TITLE
some videos doesn't start

### ISSUE THREAD

**Issue by KonoromiHimaries** [TeamNewPipe/NewPipe#3228] opened 2020-03-14 16:39 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Test https://www.youtube.com/channel/UCZNJmdsIDwtnS-oEZBuymAw

To reproduce
- example video that does not start https://www.youtube.com/watch?v=xlNp86uMBwk
- open video in pip mode

**Comment by wb9688** [comment] 2020-03-14 16:42
At what resolution? I can't reproduce it

**Comment by KonoromiHimaries** [comment] 2020-03-14 17:06
![Screenshot_2020-03-14 schabi newpipe](https://user-images.githubusercontent.com/5884000/76686800-779c3780-661e-11ea-9353-428c3bd68835.jpg)

**Comment by Stypox** [comment] 2020-03-14 17:15
Duplicate of #2647

**Closed by Stypox** 2020-03-14 17:15 UTC
