### ISSUE TITLE
To use newpipe player for play local video 

### ISSUE THREAD

**Issue by shubh200-codesh** [TeamNewPipe/NewPipe#7054] opened 2021-09-04 05:08 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?
As newpipe has speed upto 3x also volume and brightness control and built in captions support so I don't want any other video player to download and decrease my phone storage. Please consider this

**Comment by SameenAhnaf** [comment] 2021-09-04 05:22
Duplicate of #478.

**Closed** 2021-09-04 06:03 UTC
Labels: enhancement
