### ISSUE TITLE
New searches appearing at the bottom of the recent search list

### ISSUE THREAD

**Issue by e-xception** [TeamNewPipe/NewPipe#7440] opened 2021-11-25 07:18 UTC
Whenever making a new search as of the latest update 0.21.13, the search no longer appears at the top of the recent searches list, but at or near the bottom. The recents are not in chronological order as well. This occurred on Android 11 and remained on Android 12 after I updated. 

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to search
2. Type anything and press enter
3. Go back to search after searching, the thing you searched will not be at the top. 

### Actual behavior

The most recent search appears at or close to the bottom of the recent searches, not at the top. None of the searches are in chronological order either. The searches were not in alphabetical order or anything such so I am assuming they are randomly placed.

### Expected behavior
The most recent search is expected to appear at the top of the recent searches, followed by the one before it, etc, in chronological order. 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/95016103/143397393-361935ba-f501-4417-913b-644b1ebb3217.mp4

### Device info

 - Android version/Custom ROM version: 12 (also occurs on 11)
 - Device model: SM-G998B

**Comment by mhmdanas** [comment] 2021-11-26 07:16
Duplicate of #6763.

**Closed by mhmdanas** 2021-11-26 07:16 UTC
Labels: bug

**Comment by e-xception** [comment] 2021-11-26 08:32
This isn't a feature request though. It used to be like this but as of the new update it no longer happens. It's a bug.

**Comment by mhmdanas** [comment] 2021-11-26 08:37
Either way, the requested change is the same thing; I don't think such a minor thing warrants keeping two essentially identical issues.
