### ISSUE TITLE
Thumbnail don't load bug

### ISSUE THREAD

**Issue by WorkHard4470** [TeamNewPipe/NewPipe#8951] opened 2022-09-10 08:42 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

Try to click https://www.youtube.com/watch?v=_AugF0k-coE&t=8 to view it but does not load thumbnails properly.

### Expected behavior

Thumbnails will be loaded fine without experiencing network problems.

### Actual behavior

Thumbnails cannot load for this video and looks like SquareUp Picasso will throw out error logs and network problems. Hoping the developer will make a new bugfix.

### Screenshots/Screen recordings

<img alt="Screenshot_2022-09-10-16-40-08-64_ee8807d2de22f1831269d80920e33a3b" src="https://user-images.githubusercontent.com/111160004/189475816-c5699032-c603-459c-8676-a959ce42f591.jpg" height=600 />

## Exception
* __User Action:__ load image
* __Request:__ https://i.ytimg.com/vi_webp/_AugF0k-coE/maxresdefault.webp
* __Content Country:__ PH
* __Content Language:__ en-PH
* __App Language:__ en_PH
* __Service:__ YouTube
* __Version:__ 0.23.3
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 404
	at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 [Global India ROM, realme UI 3.0]

### Affected device model

realme 8 4G

**Comment by AudricV** [comment] 2022-09-10 10:44
This issue also happen on YouTube, so that's not really an issue from our side but an issue from their side which they should fix (because there is no thumbnail shown on the website when you try to load the video you reported, as you can see in the following screenshot):

<img src="https://user-images.githubusercontent.com/74829229/189479428-7794b2d8-e075-44ec-85aa-82a13e11a1ad.png" width="500px" alt="404_maxres_yt_AugF0k-coE">

> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #7416. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2022-09-10 10:44 UTC
Labels: bug, needs triage
