### ISSUE TITLE
Android TV - Next video starts as a black screen.

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#4842] opened 2020-11-08 15:14 UTC
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Watch a video on Android TV
2. Next video starts as a black screen. No video but voice.
3. See the picture in the attachment.

### Actual behaviour

Next video starts as a black screen. No video but voice.

### Expected behavior

Next video should start normally.

### Screenshots/Screen recordings

![IMG_20201108_120033](https://user-images.githubusercontent.com/46603635/98468252-b9e83980-21ea-11eb-93ce-0b18eb38d4b2.jpg)

### Device info

 - Android version/Custom ROM version: Android TV 8.0
 - Device model: Philips PUS550112 55" Android TV

**Comment by zubayy** [comment] 2021-08-31 15:05
This might be related but on Android TV theres always a black screen (which shows for approx 5 seconds), when trying to load a video. Strangely the video doesn't actually buffer when playing as of 0.21.9 but only in the beginning when clicking on and opening a video.

Just as a meta thing can we please request more users to join as Android TV testers as it's kinda only B0pol and I.

**Comment by mihaiolimpiu** [comment] 2021-12-31 21:04
Hi, I can help here, I'm using a Philips 49PUS6482 and I experience the same bug, error on the latest build.
Android TV 8

**Comment by marcbuddemeyer** [comment] 2022-02-04 15:23
Hi, I'm using also a Philips OLED935 from 2020. Same behaviour also with 0.21.9 version.

**Comment by litetex** [comment] 2022-02-07 19:20
@mihaiolimpiu 


Use [logcat](https://developer.android.com/studio/command-line/logcat) which is shipped with [ADB](https://developer.android.com/studio/command-line/adb)

There are a bunch of manuals available online (searching for [``android get logs``](https://google.com/search?q=android+get+logs) returns some good results), e.g:
* https://android.stackexchange.com/a/14431 (recommended)
* https://wiki.lineageos.org/how-to/logcat#with-a-computer
* https://stackoverflow.com/a/2888222

**Comment by mihaiolimpiu** [comment] 2022-04-29 18:59
First of all sorry for the very late response with the current sitiuation this was the last thing on my mind, but here goes:
`adb logcat | findstr org.schabi.newpipe`
[findstr org.schabi.newpipe.txt](https://github.com/TeamNewPipe/NewPipe/files/8593086/findstr.org.schabi.newpipe.txt)

As aditional info:
If you stay on same automated queue screen as OP posted and you you play with forward, back commands, next videos are playing ok.
Whole thing starts over after leaving the queue screen.

**Comment by mihaiolimpiu** [comment] 2022-08-28 09:19
I followed the instructions in #8829 and used the debug builds from #8839 to disable media tunneling, in the debug settings as per @AudricV mentioned.
Yes, I can confirm that everything is working as expected with 0.23.3 Debug build with Media Tunneling disabled.

**Comment by eladkarako** [comment] 2022-08-29 15:39
> Use [logcat](https://developer.android.com/studio/command-line/logcat) which is shipped with [ADB](https://developer.android.com/studio/command-line/adb)
> 
> There are a bunch of manuals available online (searching for [`android get logs`](https://google.com/search?q=android+get+logs) returns some good results), e.g:

I also find it useful to run `tcpdump` on a device,  
then analyse the file with something like [burp](https://portswigger.net/burp/).  

if you have a hacked device,  
I would advise switching burp to proxy mode, trusting burp ca-certificate on the device and setting the wifi proxy settings to the computer running burp on your home network. 
then watch traffic as it happens. very convenient.

I suspect most of the issues in the last few weeks are related to download rate throttling, and plain connection closing due to invalid js player signature decrypting (you get as low as 3kbps or immediate connection close in some cases).

**Comment by mihaiolimpiu** [comment] 2022-08-29 19:34
Maybe it's important to mention that after the video turns black, selecting another video from the queue crashes the app with this log (app provided).
[log.txt](https://github.com/TeamNewPipe/NewPipe/files/9447474/log.txt)

**Comment by opusforlife2** [comment] 2022-08-31 20:04
@mihaiolimpiu Could you please open a new issue with all these details? I'm closing this one since OP is a ghost.

**Closed by opusforlife2** 2022-08-31 20:04 UTC
Labels: bug, player, device/software specific, Android TV
