### ISSUE TITLE
Comments no longer showing on any videos

### ISSUE THREAD

**Issue by Ferrero11** [TeamNewPipe/NewPipe#5733] opened 2021-03-02 16:26 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open any video in the app
2. Go to the comments tab at the bottom
3. Screen will show no comments

### Actual behaviour
Comments section is empty and it just says no comments 

### Expected behavior
Great youtube comments everyone loves reading are supposed to be in this tab

### Screenshots/Screen recordings
![Screenshot_20210302-101958_NewPipe](https://user-images.githubusercontent.com/72403056/109679841-90f50700-7b41-11eb-83cc-dcfb899289ca.png)

### Device Info

 - Android version/Custom ROM version: LineageOS 18.1 January 25 Update
 - Device model: Realme X2 Pro RMX1931

**Comment by NewNewPipe** [comment] 2021-03-02 21:04
Confirmed.

**Comment by azat11** [comment] 2021-03-02 21:33
Was waiting for someone to post this, so I won't have to.)

It started for me while I was still using 0.20.9, updating to 0.20.10 didn't change anything. The same "no comments".

**Comment by mhmdanas** [comment] 2021-03-03 05:21
Duplicate of #5585.

**Closed by mhmdanas** 2021-03-03 05:21 UTC
Labels: bug
