### ISSUE TITLE
Built-in Audio conversion

### ISSUE THREAD

**Issue by killk4809** [TeamNewPipe/NewPipe#3427] opened 2020-04-13 08:59 UTC
Not every phone can play opus audio files, some can't even play m4a audio files. So built-in Audio conversation would be much appreciated.

**Comment by mittorn** [comment] 2020-04-13 11:17
install vlc

**Comment by PeterHindes** [comment] 2020-04-14 06:15
There is a setting to choose your preferred codec. Real-time conversion would use too much battery.

**Comment by Stypox** [comment] 2020-04-15 18:24
> Real-time conversion would use too much battery

That's would only be an issue for the user: here the real problem is that it would drastically increase apk size to include `ffmpeg`. Also, this is a duplicate of #507

**Closed by Stypox** 2020-04-15 18:24 UTC
