### ISSUE TITLE
Android 12: popup player prevents user interaction with screen/apps, worked on Android 11

### ISSUE THREAD

**Issue by firefoxlover** [TeamNewPipe/NewPipe#8169] opened 2022-04-09 01:43 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Newpipe Sponsorblock 0.22.1

### Steps to reproduce the bug

1. Play a video in background OR as popup (permissions granted to do so)
2. try to interact with the screen, it doesnt even work using the background player
3. stop the video
4. interaction still doesnt work
5. close the video
6. interaction works again

### Expected behavior

Like on Android 11, the popup player shouldn't interfere with the screen.

### Actual behavior

The popup AND background player block the rest of the screen. Quicksettings and control buttons still work. The other parts of the screen don't react to any touch.

### Affected Android/Custom ROM version

LineageOS 19.1 unofficial

### Affected device model

Nokia 7+

### Additional information

- not foldable or TV
- I disabled all animations in developer options
- network connection enabled
- using Nova Launcher newest version
- all permissions granted (show above other apps)
- "picture in picture" isn't requested and not granted

**Comment by Nickoriginal** [comment] 2022-04-09 03:36
> - [x]  I made sure that there are _no existing issues_ - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6770. It is pinned. Please, before submitting the issue, check at least pinned issues.

**Closed** 2022-04-09 10:36 UTC
Labels: bug
