### ISSUE TITLE
Recaptcha challenge

### ISSUE THREAD

**Issue by mehedihasanziku** [TeamNewPipe/NewPipe#2924] opened 2020-01-05 10:31 UTC
![Screenshot_2020-01-05-16-28-51](https://user-images.githubusercontent.com/48652123/71778477-a079ce00-2fd8-11ea-9048-5542a18668d7.png)

When i go to play any video i am getting this issue on latest version, before this was something like extract issue.

**Comment by Stypox** [comment] 2020-01-05 12:15
Please explain further what you mean by `this issue` and `extract issue`.
Anyway this is most probably duplicate of #2896

**Comment by mehedihasanziku** [comment] 2020-01-05 12:19
> Please explain further what you mean by `this issue` and `extract issue`.
> Anyway this is most probably duplicate of #2896

Before when i go to play video i got this issue #2737,

But after update now i am facing above issue.....now i reverted back to older one, atleast now i can play video.

**Comment by abbluiz** [comment] 2020-01-16 03:19
I am having the same issue with latest F-Droid version. Any video opens a recaptcha challenge. When I hit submit, the video opens in a webview, like an embedded browser. There seems to be no other way of watching videos right now, which is bad. I can't go in full screen mode or even change the orientation without the recaptcha reloading.

**Comment by abbluiz** [comment] 2020-01-16 03:23
![Screenshot_20200115-222037](https://user-images.githubusercontent.com/19765082/72490565-84024080-37e5-11ea-9f06-d1bed1f6df2d.png)

![Screenshot_20200115-222055](https://user-images.githubusercontent.com/19765082/72490536-72b93400-37e5-11ea-903f-d1dab2e8882d.png)

**Comment by Stypox** [comment] 2020-01-16 06:28
What happens if you tap on the back button? @abbluiz

**Comment by abbluiz** [comment] 2020-01-16 21:16
> What happens if you tap on the back button? 

This happens. @Stypox 

![Screenshot_20200116-121848](https://user-images.githubusercontent.com/19765082/72563342-73040e80-387b-11ea-8cfc-67a62f80df9a.png)

**Comment by abbluiz** [comment] 2020-01-16 21:18
I have found the reason why the recaptcha challenges are being triggered here. It is the VPN server I am using. If I change it or disable it, the recaptcha stops. But I still consider it a problem, cause the app can't handle the challenges properly when they do happen.

**Comment by mehedihasanziku** [comment] 2020-01-16 21:21
It's not a vpn issue, i use this app without vpn, official app/website working perfectly, but this app not performing well sometime, i don't have an idea why it's started behaving like that

**Comment by Stypox** [comment] 2020-01-17 06:30
If I find some time I will look into this, though I don't know if I will be able to find anything since I can't reproduce ReCaptchas

**Comment by mehedihasanziku** [comment] 2020-01-17 06:33
I hope it can be fixed, and then maybe this issue will be cleared automatically

![ScreenShot01252](https://user-images.githubusercontent.com/48652123/72589462-7fdd3c80-3925-11ea-9bd6-07ecb7853f1b.jpg)

**Comment by Stypox** [comment] 2020-01-17 07:49
The Recaptcha will appear anyway (there is nothing that can be done to prevent it), but the resolution will work

**Comment by omarroth** [comment] 2020-01-20 21:22
FWIW, it should be possible to completely bypass this type of CAPTCHA using [QUIC](https://developer.android.com/guide/topics/connectivity/cronet/), although I'm not in a position to say how much work it would require to switch the NewPipe over to a new networking stack.

See also my comment in omarroth/invidious#957.

**Comment by ChairmanMkay** [comment] 2020-01-27 02:26
Is this an issue of ip address _reputation_ , shared address, user agent, or access pattern?

I'm leery to suggest but there are "free", low quota, "privacy" vpn services. I won't name any. (XPrivacy reveals harvesting problems with certain provider apps.) This should allow exploration of reputation issue or shared address issue.  DNSBL might provide the distinction. 

I also use an adblocking DNS. This might be a factor, but I'm not ever not-filtering.

**Comment by Stypox** [comment] 2020-01-27 21:10
Could you test this apk? The reCAPTCHA activity is shown, the user can resolve the reCAPTCHA (or follow the instructions, or do whatever they want), and then press back or "Done" to exit.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4119347/app-debug.zip)
@ChairmanMkay @mehedihasanziku @abbluiz

**Comment by Stypox** [comment] 2020-01-28 14:46
Here is a direct apk download (the other was .zip): [app-debug.apk](https://github.com/Stypox/NewPipe/releases/download/untagged-e35050f79c5922b192d5/app-debug.apk)

**Closed** 2020-02-02 21:16 UTC
Labels: bug, youtube
