### ISSUE TITLE
0.19.2 Error - Opening video

### ISSUE THREAD

**Issue by jniniinoinoino** [TeamNewPipe/NewPipe#3396] opened 2020-04-08 20:15 UTC
### Version

- 0.19.2

### Steps to reproduce the bug
1. Don't know what happened, I tried to open a video.

### Expected behavior
Go straight to video

### Actual behaviour
Crashed/Error

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=eNOl3sLzakM
* __Content Language:__ US
* __Service:__ YouTube
* __Version:__ 0.19.2
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not load decrypt function
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:757)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:643)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:65)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:61)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:120)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.ConnectException: Failed to connect to youtube.com/2a00:1450:400f:80b::200e:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:249)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:159)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:70)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:42)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:737)
	... 30 more
Caused by: java.net.ConnectException: failed to connect to youtube.com/2a00:1450:400f:80b::200e (port 443) from /fd00:1:fd00:1:fd00:1:fd00:1 (port 49343) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:278)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:187)
	at libcore.io.IoBridge.connect(IoBridge.java:129)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	... 51 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:267)
	... 61 more

```
</p></details>
<hr>

**Comment by justanidea** [comment] 2020-04-08 20:35
Im getting the same error on any. Only audio streaming works fine at least, but i guess youtube changed again... Probably, be ready for a fload of crash reports  haha sadly
Version 0.19.2, and any since 0.18.x at least

**Comment by wb9688** [comment] 2020-04-08 20:43
Are you using a proxy of any kind? If so, could you try disabling that? If not, it looks like this issue happens only for IPv6, which I don't have at home, so I couldn't test it.

If you don't mind us knowing your IP address, which you already gave anyway, could you open a browser on your PC, press F12, open the network tab, go to the URL in your issue report, play the video, copy the response of the get_video_info request, paste it here and also copy the URL of the video_playback request and paste that here as well? Thanks in advance.

**Comment by justanidea** [comment] 2020-04-09 06:15
@wb9688 okay. In fact i dont think my error is related to this one since i couldnt get the crash log, but only a toast saying: "trying to fix the error for the player" in loop

I realized that it was also happening when i was using instagram, so i just restarted my phone (something that i didnt do for at least two weeks...) and now everything works fine

Sorry, so at the end all what i said was unrelated with this issue.

**Comment by jniniinoinoino** [comment] 2020-04-09 18:44
> Are you using a proxy of any kind? If so, could you try disabling that?

Yes I am using a proxy. But the thing is, I always use a proxy(Tor) but just this time in forever have I gotten this error.

**Comment by Stypox** [comment] 2020-04-10 10:06
This is a network issue and probably is unrelated from newpipe

**Comment by jniniinoinoino** [comment] 2020-04-11 08:03
Well, I did get an error from it. Probably related to NewPipe and it's ability to deliver. Crashing doesn't happen if it isn't a concern to the app itself. Maybe this is because of the slow network speeds Tor delivers and as a compensation it crashes. But why should it crash with relation to Tor when normal people with slow wifi speeds doesn't get the same error.

It could be because of the constant reCAPTCHA that gets delivered to me every 5 min. So I gotta quit the app, change Tor identity and then open it again, hopefully it works, 90% of the time it does. Otherwise I gotta rechange my identity over and over until it works again.
I should open an issue for that: #3418

But I don't really know much myself, so you can close this issue if you feel like it :)

**Comment by Nico207** [comment] 2020-04-11 23:13
I also have the same problem ("Trying to fix the error from the player") with all videos, with Wifi, or cellular network, and with or without VPN.(no crash)

**Comment by Stypox** [comment] 2020-05-07 06:21
@jniniinoinoino is the experience a little bit better, now that recaptcha fixes have been released? Also, I don't think this can be fixed in any way, because it is caused by a network error.

**Comment by jniniinoinoino** [comment] 2020-05-08 13:24
hi @Stypox. I can't tell a difference. I don't think anything has improved. But what do I know... I usually never finish the reCAPTCHAS anyway. I just do the same thing I told you about in my previous comment over and over. I get the same amount of captchas in the same amount of time :(

**Comment by Stypox** [comment] 2020-05-08 13:55
Why are you not solving them?

**Comment by jniniinoinoino** [comment] 2020-05-08 14:13
I don't solve them because of the Google tracking and in learning they get from it. Also I find them annoying as fk, so annoying I never ever wanna have to deal with them. Everytime I do one. They either tell me its an incorrect captcha. Which it isn't. Or they will continue to give me street walks and traffic lights images over and over again til I sit there completing them min after min waiting for Google to accept my IP. So instead of waiting 5 minutes to complete it. I can rather just press one button. Change IP, restart NewPipe and I'm back in business.

**Comment by Stypox** [comment] 2020-05-08 15:04
Ok, so I guess this is not really something that can be fixed in NewPipe. The reported bug is a network issue supposedly unrelated  from NewPipe

**Closed** 2020-05-08 15:04 UTC
Labels: bug, more info needed, requires extractor change, youtube
