### ISSUE TITLE
(Feature Request) Option to download multiple videos simultaneously

### ISSUE THREAD

**Issue by shouyou10** [TeamNewPipe/NewPipe#6621] opened 2021-07-08 02:41 UTC
Newpipe is itself such a featureful app that I do not think I have used it all. But one of the features that would have helped me a lot is downloading multiple videos simultaneously.
''Play All'' feature is really handy one to watch or listen to a playlist just by a single tap. But I wish if there were a similar ''Download All'' option or something along that line.
Thank you for your great works on this project. Would love to see Newpipe improve as time passes by.

**Comment by SameenAhnaf** [comment] 2021-07-08 02:53
Duplicate of #746. Also, fill in the template properly. You are not supposed to remove it.

**Comment by mhmdanas** [comment] 2021-07-08 19:57
@SameenAhnaf correct, but the user has not seen the template, as it can only be seen from the GitHub website, not from third-party client.

**Closed by mhmdanas** 2021-07-08 19:57 UTC
