### ISSUE TITLE
hitbox of timestamp on comments is too large

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#7052] opened 2021-09-04 05:03 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

clicking anywhere in the line in which timestamp is present, opens the video 
what I'm asking for is that, timestamp should only be activated if the actual timestamp is clicked, not anywhere in the whole line

#### Is your feature request related to a problem? Please describe it

too many misclicks

**Comment by mhmdanas** [comment] 2021-09-04 06:05
Duplicate of #4838. Please search the issues more more diligently next time.

**Closed by mhmdanas** 2021-09-04 06:05 UTC
Labels: enhancement

**Comment by castrik** [comment] 2021-09-04 20:46
oh yeah, I searched only by 'comment' and that issue didn't show up
