### ISSUE TITLE
Small text on Android TV in grid view mode

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#3221] opened 2020-03-12 21:11 UTC
I use android TV ,in Newpipe grid mode there are many videos in the screen even I can't read texts unlike the official version of youtube and youtube TV.
I suggest to cahnge grid layout to have 6 videos similar to youtube version.

![IMG_20200312_212453](https://user-images.githubusercontent.com/11852634/76566660-87483e80-64ad-11ea-9e55-5c86f56c7f78.jpg)
![IMG_20200312_212535](https://user-images.githubusercontent.com/11852634/76566883-ff166900-64ad-11ea-937e-266b0998881f.jpg)

![IMG_20200312_212630](https://user-images.githubusercontent.com/11852634/76566663-89aa9880-64ad-11ea-8d5a-4e880d68ce6d.jpg)

**Comment by Stypox** [comment] 2020-03-13 13:49
@Alexander-- could #2806 fix this issue?
@TobiGr I think we will need a new "Android TV" label in the future

**Comment by Alexander--** [comment] 2020-03-14 00:44
@Stypox

No. In #2806 I focused on other issues: broken player controls, broken lists, and broken video descriptions.

**Comment by TobiGr** [comment] 2020-03-14 11:37
>  I think we will need a new "Android TV" label in the future

Done

**Comment by sorryusernameisalreadytaken** [comment] 2020-03-21 15:51
>  I suggest to cahnge grid layout to have 6 videos similar to youtube version.

Oh jeah I agree with that suggestion too. Would be awesome.

**Comment by allendema** [comment] 2020-08-06 18:41
Related #2347

**Comment by opusforlife2** [comment] 2020-08-15 09:19
Duplicate of #3139.

**Closed by opusforlife2** 2020-08-15 09:19 UTC
Labels: Android TV, GUI, bug, device/software specific
