### ISSUE TITLE
Some videos don't play in specific resolution

### ISSUE THREAD

**Issue by Nextross** [TeamNewPipe/NewPipe#4298] opened 2020-09-20 16:05 UTC
### Version

I'm using NewPipe version 0.19.8 on android 9. My phone is Huawei Nova 3.

### Steps to reproduce the bug

This bug seems to happen randomly across any video. When I open a video I want to play, the window is stuck in loading screen and I need to lower the resolution to get it load (usually to 360p). I don't think it's my internet connection as other videos work on the highest resolution.

### Expected behavior

I expect to play a video in the highest resolution possible.

### Actual behaviour

The player is stuck on loading screen.

### Screenshots/Screen recordings

[Example.zip](https://github.com/TeamNewPipe/NewPipe/files/5252028/Example.zip)

**Comment by opusforlife2** [comment] 2020-09-20 16:07
This is a duplicate of a pinned issue, mate. #2415. Check a little more thoroughly next time.

**Closed by opusforlife2** 2020-09-20 16:07 UTC
Labels: bug
