### ISSUE TITLE
Number of Videos in Playlist Incorrect

### ISSUE THREAD

**Issue by sasukeiscool** [TeamNewPipe/NewPipe#5877] opened 2021-03-22 10:02 UTC
![Screenshot_20210322-184812_NewPipe](https://user-images.githubusercontent.com/73827127/111971709-f8e6ae00-8b3f-11eb-9169-d3294ebba327.jpg)
![Screenshot_20210322-184747_NewPipe](https://user-images.githubusercontent.com/73827127/111971714-fa17db00-8b3f-11eb-874e-740ecb840a35.jpg)

### Checklist

- [x] I am using the latest version - 20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Go to 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtNCG9Vq7vdvJytS-F-xGi7_' (underscore is part of link)

### Actual behaviour
Number of videos in playlist shows up as 7,618,291. 

### Expected behavior
The number should be 42.

### Device info

 - Android version/Custom ROM version: 11
 - Device model: Galaxy S20

**Comment by mhmdanas** [comment] 2021-03-22 12:09
I think this is a duplicate of #5004.

**Closed by mhmdanas** 2021-03-22 12:09 UTC
Labels: bug
