### ISSUE TITLE
Exiting the app with the popup player active makes the touch screen unresponsive

### ISSUE THREAD

**Issue by Nannose** [TeamNewPipe/NewPipe#7695] opened 2022-01-24 11:38 UTC
App version: 0.21.15
Device: Samsung Galaxy S20 FE
Android version: 12, One UI 4.0

Within the app everything works fine, but if I try to exit and keep the popup player active I can not navigate the phone at all, except for the back/home/recent apps buttons. Only manipulating the popup player works, and getting rid of it lets me use the rest of the phone again.

[Here is a video showing the problem](https://files.catbox.moe/vh9bla.mp4)

**Comment by TiA4f8R** [comment] 2022-01-24 12:56
Duplicate of #6770. Please follow the template the next time you open an issue. Thank you.

**Closed by TiA4f8R** 2022-01-24 12:56 UTC
Labels: template-missing
