### ISSUE TITLE
[bug] Strange scrolling

### ISSUE THREAD

**Issue by teod0r** [TeamNewPipe/NewPipe#2196] opened 2019-03-08 14:57 UTC
1. Open the description of a video. Probably it shoud be a long description, I don't know.
2. Scroll it down unteel black screen (black theme). BUT it shoud be fast scrolling, NOT SLOW.
3. Try to scroll up to the contents. It never happens! Always black screen.
P.S. comments are disabled.

**Comment by yausername** [comment] 2019-03-08 19:29
Duplicate of #2174

**Closed** 2019-03-09 12:37 UTC
Labels: duplicate
