### ISSUE TITLE
Pressing the mini player option opens another notification bar.

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#3231] opened 2020-03-15 15:09 UTC
When im in full screen & go PiP mode it creates 2 notification bars, one paused and the actual one thats supposed to stay.

**Comment by Stypox** [comment] 2020-03-15 15:38
I can't reproduce. Could you check if #3178 fixes your issue?

**Comment by Stypox** [comment] 2020-04-27 07:35
Closing since no more information has been provided and this will be fixed by #2907

**Closed by Stypox** 2020-04-27 07:35 UTC
