### ISSUE TITLE
Playback speed UI does not adjust until the video is unpaused

### ISSUE THREAD

**Issue by andrewferguson** [TeamNewPipe/NewPipe#3416] opened 2020-04-11 00:13 UTC
### Version

- 0.19.1, since 0.19.2 isn't yet in F-Droid - this issue has been present in all recent (2019+) versions of NewPipe, and there is no merged PR for it, so I'm 99% sure it's still an issue.

### Steps to reproduce the bug
1. Open any video in the default video player.
2. Pause the video.
3. Press the _1x_ button at the top-right to open the _Playback Speed Controls_ pop-up.
4. Change the _tempo_ of the video to anything other than the default (_1x_). (Using either the slider control or the _+_ / _-_ buttons - both cause the bug to occur).
5. Close the _Playback Speed Controls_ pop-up by pressing the _OK_ button.
6. Observe that the speed indicator in the top-right still says _1x_, and not the new speed.
7. Play the video.
8. Observe that the speed indicator immediately changes to the newly-changed speed, and the video begins playing at that speed.

#### Additional sub-issue
The following steps continue from step 6 in the above _Steps to reproduce the bug_:

7. Open the _Playback Speed Controls_ again.
8. Observe that the _Playback Speed Controls_ pop-up also displays the old speed.
9. Close the _Playback Speed Controls_.
10. Play the video.
11. Observe that the video is playing at the original (_1x_) speed.

### Expected behaviour
When changing the video speed when the video is paused, the speed indicator in the top-right should update immediately after the speed has been changed, regardless if the video is paused, and not wait until the video begins playing to show the updated speed.

### Actual behaviour

If the video is paused, changing the video speed through the _Playback Speed Controls_ will not update the speed indicator when the _Playback Speed Controls_ pop-up is closed.

(Additional sub-issue): When a video is paused, adjusting the playback speed through the _Playback Speed Controls_, closing the pop-up, then re-opening the _Playback Speed Controls_ will reset the playback speed to whatever it was before the speed was adjusted.

### Additional notes
After typing up the above report, I have realised that the same issue affects the _Pitch_ as well as the _Tempo_. It's less visible, because only the _Tempo_ is shown on the main UI, but the inherent issue still exists (as noted in _Additional sub-issue_, opening the _Playback Speed Controls_ a second time when a video is paused will reset the tempo to it's previous value. This also affects the tempo as well).

**Comment by opusforlife2** [comment] 2020-09-06 18:40
In testing #4239, I can see that the UI updates on taking any of these actions: play, pause, forward, and rewind.

Basically, the issue is that the UI isn't getting updated upon tapping OK. This is true even for the menu itself, in which case it somehow assumes the visible value (the old one) to be the new value and uses _that_ upon tapping OK.

**Comment by opusforlife2** [comment] 2020-09-10 17:50
Related:

From: https://github.com/TeamNewPipe/NewPipe/pull/3178#issuecomment-689294566
> Notification definitely looks great however the notification progress bar sometimes doesn't update at all when playing stuff in the background.

@Stypox says the cause of both problems is:
> The setting change does not trigger a player update

**Comment by opusforlife2** [comment] 2020-10-10 18:50
This was fixed by #4347.

**Closed** 2020-10-10 18:51 UTC
Labels: GUI, bug, player
