### ISSUE TITLE
NewPipe for desktop

### ISSUE THREAD

**Issue by letkan** [TeamNewPipe/NewPipe#7631] opened 2022-01-08 08:42 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Man, I've been using this app for years and it's the best in its class, it has all the features I would want from a music streamer, great work. The thing is, I couldn't find anything close to it for my Linux desktop. I was wondering if you guys might consider such an enterprise, maybe something based on Electron so that it could be platform independent. 

#### Why do you want this feature?

I listen to music on my phone only when I'm out of my house, I have a hard time with small screens due to my eyesight. Getting into Android emulators and stuff is besides the point.

**Comment by mhmdanas** [comment] 2022-01-08 10:27
Closing as duplicate of #1051, but to answer your questions:

We have no such plans at the moment. Apparently Windows 11 can run Android apps, though I don't know how well it would work with NewPIpe. There are also other open-source and privacy-oriented frontends for YouTube around:

- [FreeTube](https://github.com/FreeTubeApp/FreeTube): uses Electron; supports Windows, macOS, and Linux
- [Invidious](https://github.com/iv-org/invidious): this is actually a web frontend, not an app, but if you're fine with it it works well
- [Piped](https://github.com/TeamPiped/Piped): also a web frontend, uses the same core as NewPipe (https://github.com/TeamNewPipe/NewPipeExtractor)

**Closed by mhmdanas** 2022-01-08 10:27 UTC
Labels: enhancement

**Comment by letkan** [comment] 2022-01-08 12:53
Thanks for replying anyway. I wan't aware of Piped, with nativefier I made it my app.
