### ISSUE TITLE
[Feature] Categorized trending page

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5073] opened 2020-12-02 15:47 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
What I want is for the trending page, maybe as an option, to have categories such as music, gaming, sports and news.

#### Is your feature request related to a problem? Please describe it
When I look at trending, it shows what I'm not interested in. So if when i gon on the Trending page, I can pick what I wanna look at, it would make it better.

#### Additional context

*Mock up image made with icons*
![1606924012193](https://user-images.githubusercontent.com/71007160/100895625-b0828200-34b5-11eb-82ca-8836d4d18cd6.jpg)

#### How will you/everyone benefit from this feature?
It would help people find relevant videos to their liking.

**Comment by B0pol** [comment] 2020-12-03 09:31
Duplicate of #1805

**Closed by B0pol** 2020-12-03 09:31 UTC
Labels: enhancement
