### ISSUE TITLE
Videos Cannot be Downloaded

### ISSUE THREAD

**Issue by CharAznableLoNZ** [TeamNewPipe/NewPipe#2680] opened 2019-10-02 01:24 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When trying to download 720p video the download never starts.  The file is created as empty and the download says the error Not found.

An example video having the issue.
https://www.youtube.com/watch?v=Ms8gUQQJSBE

Some other videos do not have this problem. However it's seems at random which ones work and which ones don't.   Version 17.3 from F-Droid.

**Comment by CharAznableLoNZ** [comment] 2019-10-03 00:09
Another video this issue is occurring on.

https://www.youtube.com/watch?v=YilpC0gswSg

**Comment by jonvaldes** [comment] 2019-10-03 04:23
Looks like this issue is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2674

**Comment by Stypox** [comment] 2019-10-03 05:16
This issue is probably related to all of these, but I'll keep it open anyway since it contains useful information: #2509 #2525 #2673 #2415 #2600 #2647 #2674 #2680

**Comment by Stypox** [comment] 2020-04-27 07:14
Duplicate of #2415

**Closed by Stypox** 2020-04-27 07:14 UTC
Labels: bug, requires extractor change, youtube
