### ISSUE TITLE
re-captcha issue

### ISSUE THREAD

**Issue by Quingy** [TeamNewPipe/NewPipe#6249] opened 2021-05-06 09:10 UTC
Even after solving recaptcha it never disappears.

**Comment by TiA4f8R** [comment] 2021-05-06 15:32
Did you tried to delete reCaptcha cookies in the settings? If it doesn't work, export your database, clear the app data, open the app and import the database **without** settings. This should solve the problem without any data loss, except your settings. If the case where the deletion of the reCaptcha cookies doesn't work, a fix which has been merged should solve this problem: #5997.

Also, your client seems to not support issue templates. Can you follow the corresponding template the next time you open an issue? Thank you!

**Comment by Sonicghub456** [comment] 2021-05-07 03:50
> Did you tried to delete reCaptcha cookies in the settings? If it doesn't work, export your database, clear the app data, open the app and import the database **without** settings. This should solve the problem without any data loss, except your settings. If the case where the deletion of the reCaptcha cookies doesn't work, a fix which has been merged should solve this problem: #5997.
> 
> Also, your client seems to not support issue templates. Can you follow the corresponding template the next time you open an issue? Thank you!

Hey i tried that and it didn't work.

**Comment by Sonicghub456** [comment] 2021-05-07 03:51
I still see it and i did import the data

**Comment by hp8wvvvgnj6asjm7** [comment] 2021-05-08 11:00
I have this issue since weeks. Can't use this app anymore.

**Comment by boringhexi** [comment] 2021-05-09 22:49
I'm experiencing this as well. Clearing the reCAPTCHA cookie didn't work, nor did clearing app data and reimporting the database without settings. Solving the captcha makes the video play in the recaptcha browser popup, but not in NewPipe itself.

**Comment by Gymcap** [comment] 2021-05-11 21:44
I'm having a similar issue except that I can't even complete the captcha. Whenever I tap the solve caption button in the app, it shows the white screen waiting for the captcha, then crashes. Here is the formatted report I got.

https://pastebin.com/T5Nu4h4a

**Comment by boringhexi** [comment] 2021-05-12 02:32
@Gymcap That sounds like it would need its own bug report, otherwise it'll get overlooked

**Comment by TiA4f8R** [comment] 2021-05-12 14:03
Closing as a duplicate of #6055.

**Closed by TiA4f8R** 2021-05-12 14:03 UTC
Labels: doesn't-follow-template
