### ISSUE TITLE
NewPipe Version in F-Droid not usable since October 2020!

### ISSUE THREAD

**Issue by jwiesel** [TeamNewPipe/NewPipe#5311] opened 2020-12-30 09:43 UTC
### Checklist

- [x] I am using the latest version available in F-Droid store- 0.20.1
- [x] I checked, but and found several duplicate but closed bug reports of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
The issue has been reported numerous times already (see below).
My issue is, that the solution is not published in F-Droid. Hence, the app is still not usable at all for more than two months already for all normal users who simply want to have a functioning app via F-Droid:

https://github.com/TeamNewPipe/NewPipe/issues/5161
https://github.com/TeamNewPipe/NewPipe/issues/5074
https://github.com/TeamNewPipe/NewPipe/issues/4627
https://github.com/TeamNewPipe/NewPipe/issues/4572
https://github.com/TeamNewPipe/NewPipe/issues/4803
https://github.com/TeamNewPipe/NewPipe/issues/4684
https://github.com/TeamNewPipe/NewPipe/issues/4658
...

### Actual behaviour
NewPipe app gets updated regularly, but the version in F-Droid has not been updated since October, 19 2020.

### Expected behavior
Update NewPipe in F-Droid to make the app usable again for normal users (who don't search the internet for bug reports or want to install custom repositories in F-Droid, etc. but simply will switch to a different app, if NewPipe is not working for them)

### Device info

 - Android version/Custom ROM version: 9
 - Device model: Huawei P20 Lite
 - NewPipe Version: 0.20.1

**Comment by mhmdanas** [comment] 2020-12-30 10:41
Thanks for opening an issue! This is a duplicate of #5069. Rest assured, we are in contact with the great folk over at F-Droid and are trying to fix this.

**Closed by mhmdanas** 2020-12-30 10:41 UTC
Labels: bug
