### ISSUE TITLE
Add pages option in setting as infinite swipe scrolling down alternative

### ISSUE THREAD

**Issue by bungadrum** [TeamNewPipe/NewPipe#6156] opened 2021-04-24 11:30 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
When you are searching videos in search results instead of swiping down all the time can you add a pages option. When you scroll to the bottom a bit you will reach the end and there you will see boxes that say 2, 3, 4 and so on similar how old YT layout looked. When you tap on them it will take you to a new page.

#### Additional context
Here is a example how it looked before and when you reach the bottom
![20210424_131713395~01.jpg](https://user-images.githubusercontent.com/75974100/115956989-3011fb80-a500-11eb-8184-e7e2d8d26c28.jpg)
![20210424_132045288~01.jpg](https://user-images.githubusercontent.com/75974100/115956996-3b652700-a500-11eb-8751-8905a27017b0.jpg)

#### How will you/everyone benefit from this feature? 
It would make searching for content alot easier compared to before. With unlimited scroll swiping down it's easy to get lost if you are searching for something specific and can't find it. On pages you can memories where things are located easy and go back anytime you want. The unlimited scroll swipe doesn't give you a sense that you reached the end and the content can't be organized.

**Comment by mhmdanas** [comment] 2021-05-29 20:15
Closing as duplicate of #2134.

**Closed by mhmdanas** 2021-05-29 20:15 UTC
Labels: enhancement
