### ISSUE TITLE
every video fails playback

### ISSUE THREAD

**Issue by dgerving** [TeamNewPipe/NewPipe#7797] opened 2022-02-04 07:21 UTC

**Comment by mhmdanas** [comment] 2022-02-04 08:51
Duplicate of #7734. You can either wait for 0.21.16 to come to the official F-Droid repo, or follow the instructions in https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/ (don't forget to export your database before uninstalling NewPipe).

**Closed by mhmdanas** 2022-02-04 08:51 UTC
