### ISSUE TITLE
Search functionality within a youtube channel

### ISSUE THREAD

**Issue by Ronkn** [TeamNewPipe/NewPipe#11233] opened 2024-07-03 01:50 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Search functionality within a youtube channels page similar to how YouTube has it. 
<img alt="Screenshot_20240702-214713_1" src="https://github.com/TeamNewPipe/NewPipe/assets/32688058/8b241246-2cef-4b95-91e5-454e5459011e" width=277 />

### Why do you want this feature?

Useful for finding a specific list of keyword related videos, from one channel. Searching globally with the channel name is hit or miss.

**Comment by ShareASmile** [comment] 2024-07-03 03:30
> - [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #5441 , Please search (better, with different keywords?) for duplicates the next time you want to open an issue and fill in the issue form properly. Thank you.

**Closed** 2024-07-03 03:31 UTC
Labels: template ignored, duplicate
