### ISSUE TITLE
[Feature Request] Set Default Video Playback Speed

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1924] opened 2018-12-03 21:42 UTC
On NewPipe I am currently unable to set a default playback speed for all videos I watch in the app. I often find when I begin watching a video I waste 10 seconds just trying to fiddle with the speed controls. If there was some way to set a default speed that played on all videos that would be great!

Similar to this it would be helpful if there was some way to unlink playback controls for all videos in settings (unlink tempo and pitch).

**Comment by farverio** [comment] 2018-12-17 03:30
Came to note this same FR. Additionally, I don't believea linear slide is ideal for selecting the speed (the value of playing at 1.63x for instance is quite limited). I believea more robust Newpipe might have increments of .5x speed and add a default speed under video and audio settings.

Lastly, I always unlink pitch and speed. Not sure the key merits there

**Comment by acid-clot** [comment] 2019-01-04 15:47
Totally! I don't feel any difference watching at 1.25x speed; and if it's going to save me a bit of time then why not let me configure that as the default?

You need to fiddle sometimes with the slide to get it to the perfect speed &/ pitch but I think the slider fulfills the purpose of getting you approximately to what you want really quickly.

And the app already has buttons that let you increase the speed and pitch in .25x increments and that doesn't seem so bad to me. 

The app warns that unlinking pitch and speed would cause distortions, but I've never experienced that.

**Comment by nikolayhg** [comment] 2019-07-07 07:10
+1

**Comment by Stypox** [comment] 2019-08-28 21:14
Duplicate of #735

**Closed by Stypox** 2019-08-28 21:14 UTC

**Comment by tweak42** [comment] 2020-03-30 21:33
Posting here requesting for ability to set a higher than 1x default speed.  I listen to practically all YT videos at 110% (sometimes higher) using Firefox desktop plugin.  Newpipe requires 4 extra clicks for *every single video* to do this.
