### ISSUE TITLE
Add an auto-play option, it's a BASIC feature!

### ISSUE THREAD

**Issue by jjgh** [TeamNewPipe/NewPipe#751] opened 2017-10-01 11:38 UTC
Playing a video should automatically enqueue other videos and play them in order.
I am using NewPipe since 3/4 months and I can't believe this has not been dealt accordingly to how important and basic this feature is.

**Comment by coffeemakr** [comment] 2017-10-01 12:37
Duplicate of #165

**Closed** 2017-10-01 22:50 UTC

**Comment by theScrabi** [comment] 2017-10-01 22:57
> I am using NewPipe since 3/4 months and I can't believe...

Well because it's basically not that easy to implement that BASIC feature so fast. You are using NewPipe since 3/4 months and I can't believe why you still write on github instead of helping us implement this BASIC feature :*

**Comment by jjgh** [comment] 2017-10-02 03:04
@theScrabi I apologise :)
