### ISSUE TITLE
channel tabs `shorts`, `playlist`, `channels`, `info`

### ISSUE THREAD

**Issue by asklow** [TeamNewPipe/NewPipe#10179] opened 2023-06-22 06:59 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

YouTube channel page have separated tabs such as Videos, Shorts, Playlists, Channels, Info.
It is possible to interface them via YouTube API.

[PipePipe](https://f-droid.org/en/packages/InfinityLoop1309.NewPipeEnhanced/) already does this

![Screenshot_20230622](https://github.com/TeamNewPipe/NewPipe/assets/117489882/af3d147f-8311-47d5-92fa-4abe8f9db304)

### Why do you want this feature?

More enhanced channel view

**Comment by yoshimo** [comment] 2023-06-22 07:30
I'd say duplicate of #https://github.com/TeamNewPipe/NewPipeExtractor/pull/951

**Comment by AudricV** [comment] 2023-06-22 10:46
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #2414. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2023-06-22 10:46 UTC
Labels: feature request, needs triage
