### ISSUE TITLE
Contols overlay don't hide when unpausing from bluetooth

### ISSUE THREAD

**Issue by EvilGremlin** [TeamNewPipe/NewPipe#5728] opened 2021-03-02 04:30 UTC
Well, that. Android 9.0, any headset/dedicated remote, any version of NewPipe.

By the way, it didn't show me template somehow? Probably because i first pressed "new issue" and only then logged in...

**Comment by mhmdanas** [comment] 2021-03-03 05:37
Thanks for opening an issue! This issue is a duplicate of #3403.

Regarding the template, can you see again if the templates are shown now? Also, just to be sure, are you using the GitHub website or a third-party client?

**Closed by mhmdanas** 2021-03-03 05:37 UTC

**Comment by EvilGremlin** [comment] 2021-03-03 05:42
Soooo old and still no fix...
Yep, website, template appears when i create isuue while already logged in.

**Comment by mhmdanas** [comment] 2021-03-03 05:46
No, there _is_ a fix, but it still hasn't been merged. See #3547. I'll try to get the PR merged soon.
