### ISSUE TITLE
[BUG] Videos Do Not Play

### ISSUE THREAD

**Issue by RuthlessRuler** [TeamNewPipe/NewPipe#1547] opened 2018-07-24 16:23 UTC
After playing 2 videos, when i click the third video, the app will go for infinite loading and i even checked and saw that no data is being received or sent.
This is a continous issue and persists and to solve it, i have to close and open the app. It would be nice if this feature is fixed.

**Comment by theScrabi** [comment] 2018-07-25 15:07
Which android version do you use?

**Comment by RuthlessRuler** [comment] 2018-07-26 11:40
Cosmic OS v5.1 based on Android Jelly Bean.
Also, Can you please send the email address where the bug reports are sent, cause my device dont have any client so i will mail it via PC.

**Comment by theScrabi** [comment] 2018-07-27 08:15
It be better if you posed your issue here directly using [The incredible bug report converter](https://teamnewpipe.github.io/CrashReportToMarkdown/).

**Comment by RuthlessRuler** [comment] 2018-07-27 14:40
The Bug reporter isnt converting, plus there is a speeling error(her --> here)
Here is the bug report directly:
{
   "user_action": "ui error",
   "exceptions": [
      "java.lang.OutOfMemoryError\n\tat android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)\n\tat android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:636)\n\tat android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:484)\n\tat android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:813)\n\tat android.content.res.Resources.loadDrawable(Resources.java:2822)\n\tat android.content.res.TypedArray.getDrawable(TypedArray.java:602)\n\tat android.content.res.XResources$XTypedArray.getDrawable(XResources.java:965)\n\tat android.widget.ImageView.<init>(ImageView.java:126)\n\tat android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:71)\n\tat android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:67)\n\tat android.support.v7.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:181)\n\tat android.support.v7.app.AppCompatViewInflater.cr

**Comment by theScrabi** [comment] 2018-07-27 15:24
Its not converting because this is not the full report.

**Comment by RuthlessRuler** [comment] 2018-07-28 11:22
ahh! Finally:
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.13.7
* __OS:__ Linux Android 5.1 - 16

```
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:636)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:484)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:813)
	at android.content.res.Resources.loadDrawable(Resources.java:2822)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:965)
	at android.widget.ImageView.(ImageView.java:126)
	at android.support.v7.widget.AppCompatImageView.(AppCompatImageView.java:71)
	at android.support.v7.widget.AppCompatImageView.(AppCompatImageView.java:67)
	at android.support.v7.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:181)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:105)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1035)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1092)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:681)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.getListHeader(ChannelFragment.java:137)
	at org.schabi.newpipe.fragments.list.BaseListFragment.initViews(BaseListFragment.java:130)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.initViews(BaseListInfoFragment.java:41)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:54)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:59)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4960)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

-------------------

```

**Comment by RuthlessRuler** [comment] 2018-07-29 07:03
Oh No, Its is Jelly Bean but themed to look like lollipop. I cant play JB compatible games on this Device.
And RAm can be an issue as it has only 1 gig of it.(But injected Youtube works fine)

**Comment by karyogamy** [comment] 2018-07-29 21:10
I also have this problem with bitmaps when using an older device with less than 1GB of memory. Can you disable the thumbnail loading in the options (Content -> Load thumbnails) and see if the problem still persists?

**Comment by RuthlessRuler** [comment] 2018-08-01 07:42
Okay, the error has been fixed by above method but the OG problem of videos not loading after viewing two videos still persist.
(Also if possible do something that can fix the issue and i dont have to turn off thumbnails.)

**Comment by Stypox** [comment] 2020-04-27 07:20
Duplicate of #2415

**Closed by Stypox** 2020-04-27 07:20 UTC
Labels: GUI, bug
