### ISSUE TITLE
Suggestion: Add bandwidth limiter for downloads

### ISSUE THREAD

**Issue by Pass1Vlax** [TeamNewPipe/NewPipe#7817] opened 2022-02-05 13:48 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

I think it would be nice to add bandwidth limiter for downloads (either in downloads page for quick access, or in download settings or in both)

#### Why do you want this feature?

I usually download large files and it takes up all my bandwidth so all the other people in the house have problems. Even Netflix previous won't load while I download something (30mbps line)

**Comment by SameenAhnaf** [comment] 2022-02-05 16:04
Duplicate of #2515

**Closed** 2022-02-05 18:29 UTC
Labels: enhancement
