### ISSUE TITLE
Built in offline Player for videos and music

### ISSUE THREAD

**Issue by dondiscaya0531** [TeamNewPipe/NewPipe#6554] opened 2021-06-22 23:11 UTC
it would be nice if theres a feature wherein you can play downloaded music or video in app, and toggle for offline and online mode.

**Comment by mhmdanas** [comment] 2021-06-22 23:26
Duplicate of #478. Also, please don't remove the template when opening an issue.

**Closed by mhmdanas** 2021-06-22 23:26 UTC
Labels: enhancement
