### ISSUE TITLE
Unable to import newpipe backup

### ISSUE THREAD

**Issue by PrinceRaj53** [TeamNewPipe/NewPipe#7550] opened 2021-12-18 21:39 UTC
### Checklist

- [x] I am using the latest version - 0.21.14 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to Settings
2. Go to content
3. Press on "import database"

### Actual behavior

When I try to import newpipebackup.zip file by clicking import database, the app just crashes without any warning. On 2nd or third crash, it displays a crash log given below.

### Expected behavior
The settings, history, playlists & subs contained in the backup should have been restored.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.14
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/zip flg=0x43 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2073)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1729)
	at android.app.Activity.startActivityForResult(Activity.java:5430)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at org.schabi.newpipe.settings.ContentSettingsFragment.lambda$onCreatePreferences$0(ContentSettingsFragment.java:76)
	at org.schabi.newpipe.settings.ContentSettingsFragment.$r8$lambda$IJ0-sY_2nFZ8j0D13C6AQ28cAn0(Unknown Source:0)
	at org.schabi.newpipe.settings.ContentSettingsFragment$$ExternalSyntheticLambda7.onPreferenceClick(Unknown Source:2)
	at androidx.preference.Preference.performClick(Preference.java:1184)
	at androidx.preference.Preference.performClick(Preference.java:1166)
	at androidx.preference.Preference$1.onClick(Preference.java:181)
	at android.view.View.performClick(View.java:7570)
	at android.view.View.performClickInternal(View.java:7525)
	at android.view.View.access$3900(View.java:836)
	at android.view.View$PerformClick.run(View.java:28680)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:260)
	at android.app.ActivityThread.main(ActivityThread.java:8260)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: 11 (not using any custom rom)

**Comment by litetex** [comment] 2021-12-18 21:49
Duplicate of #7113

Install a SAF compatible filemanager.

**Closed by litetex** 2021-12-18 21:50 UTC
Labels: bug
