### ISSUE TITLE
Unrecoverable Player Error on changing playback speed

### ISSUE THREAD

**Issue by iamkroot** [TeamNewPipe/NewPipe#6392] opened 2021-05-29 04:44 UTC
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open any video from Youtube
2. Press on playback speed to open popup menu
3. Try to increase the Tempo *over 1x*:
	* it works fine when decreasing speed from 1x to 0.75x, or even increasing from 0.75x to 1x.
	* Just doesn't seem to handle anything above 1x.
	* Changing pitch doesn't cause error.
	* Changing the step doesn't help  
	* And the crash happens _before_ pressing "ok" on the popup menu, as soon as I press the increase button and it goes over 1x.

### Actual behaviour

* Player crashes.
* Get a toast showing "Unrecoverable Player Error occurred"
* The playback speed is saved, and on restarting/resuming playback, it remembers the modified speed.

### Expected behavior
* Should not crash when going above 1x tempo

### Logs

Did not get any Error Report page.

### Device info

 - Android version/Custom ROM version: Android 11, Custom ROM: [Nusantara 2.9](https://nusantaraproject.my.id/)
 - Device model: Realme 3 Pro (RMX1851)
 - The bug's been present for a few weeks now, not sure when it started.

**Comment by homocomputeris** [comment] 2021-08-22 21:07
I have the same issue with 0.21.8

**Comment by litetex** [comment] 2021-09-12 18:58
Is this fixed now?

**Comment by homocomputeris** [comment] 2021-09-13 20:58
In my case, I still encounter the error with any codec.

**Comment by litetex** [comment] 2021-09-14 18:13
@iamkroot
Stated earlier:
> For me, it got fixed when I moved to a different custom ROM (SparkOS). So probably some codec error?

Looks like a OS problem. I don't think we can do much on app side here...

**Comment by litetex** [comment] 2021-09-14 18:24
> I thought the codecs are supposed to be shipped with NewPipe

No.
These are shipped with the device / OS: 
https://developer.android.com/guide/topics/media/media-formats

Also take a look at the exoplayer requirements:
* https://exoplayer.dev/supported-formats.html
* https://exoplayer.dev/supported-devices.html

If those are conditions are not met then we can't guarantee anything from the app side.

**Comment by homocomputeris** [comment] 2021-09-14 18:56
Well, some LineageOS bug, probably.

How can I get any logs for "Unrecoverable Player Error occurred", so that I can report codecs issues to LOS?

**Comment by litetex** [comment] 2021-09-14 19:06
People are asking so much for that I now create a Gist for it 😆 

> Use [logcat](https://developer.android.com/studio/command-line/logcat) which is shipped with  [ADB](https://developer.android.com/studio/command-line/adb)
> 
> There are a [bunch of manual online available](https://www.google.com/search?q=android+get+logs), e.g:
> * https://android.stackexchange.com/a/14431 (recommended)
> * https://wiki.lineageos.org/how-to/logcat#with-a-computer
> * https://stackoverflow.com/a/2888222

https://gist.github.com/litetex/ab061f158aeba824713e9a558e8e98ff

**Comment by homocomputeris** [comment] 2021-09-16 21:19
Thanks. I'm more or less familiar with logcat, the problem is it generates like 100 events per second. Any hint what I should look for in logcat? Searching for `newpipe` in logcat just doesn't return any results.

**Comment by litetex** [comment] 2021-09-18 14:12
Hmm I usually - when a problem occurs - I checkout the NewPipe repo (in Android studio) and debug the app via the integrated emulator/on my real device (via USB) as it's much easier to debug 😄 
So I don't know the pure commandline tool relatively good.

Maybe the documentation helps: 
https://developer.android.com/studio/command-line/logcat#filteringOutput

Note also that release builds are usually minimized. 
I think stuff like debug logging is disabled there.

**Comment by opusforlife2** [comment] 2021-09-19 07:36
> Note also that release builds are usually minimized.
I think stuff like debug logging is disabled there.

Indeed. @homocomputeris Please check the logs of the RC in the pinned issue and see if you get any useful information.

**Comment by tsiflimagas** [comment] 2021-09-19 09:33
@homocomputeris try filtering logs by pid. Do like `logcat --pid=$(pgrep -f org.schabi.newpipe)`

**Closed** 2021-09-27 00:06 UTC
Labels: bug, player, waiting-for-author
