### ISSUE TITLE
Android 12 popup mode bug

### ISSUE THREAD

**Issue by cehnemdark** [TeamNewPipe/NewPipe#7385] opened 2021-11-09 20:50 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Play any video from within the application in popup mode and go to the main menu.

### Actual behavior
 Touches will not be detected when you touch anywhere on the screen.

### Expected behavior

Must detect external touches while navigating the interface while the video is playing in popup mode

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/49096330/141002317-937ff18e-e3b1-462b-a9ab-77a87c5ac795.mp4

### Device info

 - Android version/Custom ROM version: Android 12 Arrow rom
 - Device model: Redmi note 9 pro

**Comment by tsiflimagas** [comment] 2021-11-09 20:51
Duplicate of #6770. Check out the workaround mentioned there.

**Comment by TiA4f8R** [comment] 2021-11-10 08:14
Please check better for duplicates before opening a new issue and fill the issue template properly next time (you need to fill the version you are using (replace `x.xx.x` in the first item of the checklist by the version). Thank you.
Closing as a duplicate of the issue mentioned above.

**Closed by TiA4f8R** 2021-11-10 08:14 UTC
Labels: bug
