### ISSUE TITLE
Support External Player for Live and Random Crash

### ISSUE THREAD

**Issue by RuthlessRuler** [TeamNewPipe/NewPipe#1745] opened 2018-09-21 17:49 UTC
So, yesterday i was unable to view the Live Event of GitLab cause MX Player just closed after some time without playing any clip. Though when i used the internal player it worked fine.

Also, its a very strange bug but rarely, when using internal player, My device will be stuck at total black screen. When i click power it locks device then again i click it, and unlock my device, and Open the app and start any video, my device automatically gets locked and unlocking will result in only a black screen!
Data of the app has to be cleared to fix this!

**Comment by RuthlessRuler** [comment] 2018-12-02 10:37
Also 480p Video have no sounds using External Players like MX Player.

**Comment by Stypox** [comment] 2019-08-28 06:37
Is this still an issue?

**Comment by B0pol** [comment] 2020-05-10 16:57
Yes it is @Stypox. But it's duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2415

**Closed by B0pol** 2020-05-10 16:57 UTC
Labels: bug, more info needed, player
