### ISSUE TITLE
Checklist style selection for batch operations

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9150] opened 2022-10-19 04:58 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Here is a visual example:

<img alt="Screenshot_2022-10-19-10-20-56-27" src="https://user-images.githubusercontent.com/28833686/196600562-33790d49-fe07-4fe7-815e-2c9f6b13faa2.png" height=600 />

To avoid conflict with long press options can use a selection mode button on the top right corner with select all check box somewhere. Once selected the long press on any selected video will    facilitate batch operations.

### Why do you want this feature?

It's too time consuming to do it otherwise I.e manually long pressing and selecting an option for each video. Also helpful for creating lengthy playlists

### Additional information

Will fix a lot of issues like batch downloading, adding marked as watched option for playlist or other similar open issues...

**Comment by tsiflimagas** [comment] 2022-10-22 14:10
Sounds like a duplicate of #5482, but this focuses on a specific solution for batch selection.

**Comment by opusforlife2** [comment] 2022-10-24 19:07
Duplicate of #8584, actually. I didn't use the correct keywords the last time.

**Closed by opusforlife2** 2022-10-24 19:07 UTC
Labels: feature request, GUI
