### ISSUE TITLE
[feature request] UI Language selection menu or "Force English" in settings

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#2162] opened 2019-02-27 21:17 UTC
I can not find a way to switch from one language to another, is there any?

**Comment by Stypox** [comment] 2019-02-27 21:20
Have you checked in Settings -> Content?

**Comment by eladkarako** [comment] 2019-02-27 23:56
Yes, 
Neither `Default content country` nor `Default content language` make any change to the UI of the program.

**Comment by DI555** [comment] 2019-02-28 12:51
Setting 'UI language' should be independent from 'Default content country' and 'Default content language' !
Yes, would be usefull to have independent option 'UI language'.

**Comment by eladkarako** [comment] 2019-02-28 23:35
I suggest using crowdin.
https://crowdin.com/page/open-source-project-setup-request

For a meanwhile I guess we can fork/compile with a translated xml (any idea where it is placed in the project?)

**Comment by eladkarako** [comment] 2019-12-16 18:41
Not related to https://github.com/TeamNewPipe/NewPipe/issues/68

**Comment by eladkarako** [comment] 2019-12-16 18:42
The version 18.x added a lot of translations, 
which is good (I guess), 
but I preferred English.

The thing is, once the language-resource exists under the <code>res/</code> folder, 
it becomes the program's UI language (if there isn't translation for the phone's native language yet, it will use the default one, <code>en-US</code> mostly).

Would be great to add a UI language-selection menu, 
or at least a checkbox to "Force English" as the language used, in the program settings.

as for now, 
I'm decompiling the APK with <a href="https://github.com/iBotPeaches/Apktool/">APKTool</a> deleting the languages under the <code>/res/</code> folder and recompiling/aligning/signing it to keep it use English... :)

This wasn't an issue to me up-until version 18.x where my phone-native language was added :|
https://github.com/TeamNewPipe/NewPipe/issues/2861#issuecomment-566184928

**Comment by Stypox** [comment] 2020-01-13 18:53
Duplicate of #2794

**Closed by Stypox** 2020-01-13 18:53 UTC

**Comment by eladkarako** [comment] 2020-01-13 21:29
@Stypox that bug report is:
1. using a very simplistic terminology and it is basically unreadable.
2. it talks about both UI and content. 
3. it is (for some reason) closed.

As this feature is not yet implemented, shouldn't you make sure there is at least one opened issue for UI language selection?

I suggest re-opening this one.
