### ISSUE TITLE
What's new section: upload date order

### ISSUE THREAD

**Issue by qowXp7GqsWx6VU** [TeamNewPipe/NewPipe#2783] opened 2019-11-05 13:44 UTC
Hello, I'd like to know if it would be possible to sort the videos of my subscriptions in the `What's New ` section. Today, they're "kinda" sorted, with the newest ones at the top of the list, but they're still not sortered correctly:

[See attached image](https://imgur.com/a/CjkW2ch)

Version: **0.17.4**

**Comment by Stypox** [comment] 2019-11-05 13:53
Duplicate of #822 #739 #1448
There are already some pull requests that aim to improve the feed order: #2309 #2547

**Closed by Stypox** 2019-11-05 13:53 UTC
