### ISSUE TITLE
related Videos doesnt seem to work

### ISSUE THREAD

**Issue by Telemakro** [TeamNewPipe/NewPipe#10813] opened 2024-02-01 13:20 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

NP 0.26.1

### Steps to reproduce the bug

Click on a video. And open related video feed.

### Expected behavior

When I finish watching a YT video. usually due to autoplay the next related video starts playing and I'm able to see a video feed.

### Actual behavior

After I watch a YT video auto play doesn't change to a related video and there is no 'related videos' feed displayed afterwards. The screen just goes black.

### Screenshots/Screen recordings

<img alt="Screenshot_20240201_141556_NewPipe" src="https://github.com/TeamNewPipe/NewPipe/assets/158475040/f70efad3-063e-4415-ad99-4f1cfc521559" width=284 />

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung galaxy S10+

**Comment by EthanZeigler** [comment] 2024-02-01 14:03
Duplicate of #10808

**Closed as completed** 2024-02-01 15:22 UTC
Labels: template ignored, duplicate

**Comment by Telemakro** [comment] 2024-02-01 17:42
Right because its the same malfunction
