### ISSUE TITLE
Mx Player missing as an External Video Player

### ISSUE THREAD

**Issue by mehedihasanziku** [TeamNewPipe/NewPipe#5975] opened 2021-03-31 20:13 UTC
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Settings > Video & Audio > Set Video External player.
Now back to video click On video, I don't see mx player as an external player.

![Screenshot_2021-04-01-01-55-24](https://user-images.githubusercontent.com/48652123/113204884-69ec3b00-928f-11eb-89c0-27ee6b1c661a.png)

### Device info

 - Android version/Custom ROM version: 6
 - Mx Player version 1.15.9 (Pro)

**Comment by sauravrao637** [comment] 2021-03-31 20:42
Hi,
I checked on this but could not reproduce the bug as you can see in below screenshot
![5975](https://user-images.githubusercontent.com/56369484/113208561-930ccb80-928f-11eb-9ed6-ea61c625392a.jpg)

**Comment by mehedihasanziku** [comment] 2021-03-31 21:01
> Hi,
> I checked on this but could not reproduce the bug as you can see in below screenshot
> ![5975](https://user-images.githubusercontent.com/56369484/113208561-930ccb80-928f-11eb-9ed6-ea61c625392a.jpg)

Hello.

Yes you are right, the issue seems to me happened if 1dm downloader installed, I freezed this app and got this 
![Screenshot_2021-04-01-02-51-00](https://user-images.githubusercontent.com/48652123/113210374-f8fc5180-9295-11eb-938f-ba8382c596ea.png)

Now I again unfreezed idm app to see.

Now I see

![Screenshot_2021-04-01-02-57-50](https://user-images.githubusercontent.com/48652123/113210513-2648ff80-9296-11eb-9d6c-f36c72725b8c.png)

Don't understand how some players missing after unfreezing 1DM. Not sure where to report. Let's wait for TeamNewPipe

And I don't see even on your screenshot always open with selected player, this was exist before two version ago as far as I remember.

**Comment by sauravrao637** [comment] 2021-03-31 21:04
AFAIK fetching the available players in the device is on android behalf and not on the app.
Let's wait and see what the team have to say :)

**Comment by TiA4f8R** [comment] 2021-04-01 10:53
Yes, @sauravrao637 is right. It's from Android (intents) and not the app. Closing as resolved.
@mehedihasanziku I removed the always option because the app is now using an ACTION_CHOOSER intent, which shows only all activities and doesn't have the ability to set an app to be a default for an intent, like it was on ACTION_VIEW intents. Maybe I will revert this for other actions than sharing or opening content in a browser, it was for always use the Android System Chooser instead of the Huawei Resolver and Chooser on EMUI devices.

**Closed by TiA4f8R** 2021-04-01 10:53 UTC
Labels: bug

**Comment by mehedihasanziku** [comment] 2021-04-01 14:14
Yes, Please revert. anyways i have another option in android to set in mx player to open supported links without ask.

But i know it's not relevant to this issue, but can you tell me why video resolution ask always when i set by default specific resoulation? is it an bug on something else?

Thanks

**Comment by TiA4f8R** [comment] 2021-04-01 15:37
It's not a bug because each quality has an unique stream URL so NewPipe let you choose a quality. Also, I think it is useful in order to reduce data and when the default quality isn't available in the streams of a content.

**Comment by mehedihasanziku** [comment] 2021-04-01 16:17
yes you are right. but i think there can be possible to add condition to display that asking feature if default specified resolution not available.  always selecting resolution looks very odd. i think it was fine before when there was control bar in top.

Let me know if something on your todo list.

Thanks.

**Comment by TiA4f8R** [comment] 2021-04-01 16:26
Free feel to open a new issue with the feature request template for this ;)

**Comment by TiA4f8R** [comment] 2021-04-10 20:25
> Yes, Please revert. anyways i have another option in android to set in mx player to open supported links without ask.

@mehedihasanziku Done in #5523.

**Comment by mehedihasanziku** [comment] 2021-06-18 16:57
> > Yes, Please revert. anyways i have another option in android to set in mx player to open supported links without ask.
> 
> @mehedihasanziku Done in #5523.

Still not reverted, I forgot to update you.
