### ISSUE TITLE
mp3 downloading feature

### ISSUE THREAD

**Issue by crisisdigital99** [TeamNewPipe/NewPipe#3706] opened 2020-05-31 14:31 UTC
#### Additional context

Need mp3 downloading capacity in newpipe. Often it has m4a and another format which is not even supported in my mobile. 
Please consider. I k its the only feature that is missing.

**Comment by B0pol** [comment] 2020-05-31 14:52
Duplicate of #507

**Closed by B0pol** 2020-05-31 14:52 UTC
Labels: enhancement

**Comment by wb9688** [comment] 2020-05-31 14:54
Properly fill in the issue template and look for duplicates first. NewPipe only downloads in the format that the service provides. Converting codecs is out of scope for NewPipe, just use another app for that.
