### ISSUE TITLE
[Feature request] Sharing playlist/multiple videos at once

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#2341] opened 2019-05-14 09:29 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

As the title says, would it be possible to add option to share multiple videos or even whole playlist at once? That'd be really great for sharing with Kodi.

**Comment by Stypox** [comment] 2019-09-29 13:02
Duplicate of #1788

**Closed by Stypox** 2019-09-29 13:02 UTC
