### ISSUE TITLE
Wrong title on "minimized" video (note: steps to reduce section isn't adding my steps; can't edit or add a comment with my browser; 1. play vid w autoplay on, 2. let next vid begin, 3. hit back to browse other vids)

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#5901] opened 2021-03-24 15:19 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

The title is the first video you clicked

### Expected behavior

The title should be the one that is currently playing

### Screenshots/Screen recordings

My browser isn't supported or I would add screenshots

### Device info

 - Android version/Custom ROM version: stock Android 8.0
 - Device model: Samsung Galaxy S7 Edge

**Comment by TiA4f8R** [comment] 2021-03-24 22:22
Duplicate of #5475. It has been fixed with #5820, which will be included in the next release.
Please search better next time for duplicates!

**Closed by TiA4f8R** 2021-03-24 22:22 UTC
Labels: bug

**Comment by infinitewaveparticle** [comment] 2021-04-09 20:18
I searched for Trending and didn't see it recently. This was a brand new problem for me so I expected to see the issue reported very recently.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2021-04-09 20:19
Sorry. Wrong thread with the last message of mine. Anyway, I tried searching for it, but I wasn't sure what to look for. I didn't look that far back.

Sent from ProtonMail mobile

-------- Original Message --------
