### ISSUE TITLE
Videos in the 'What's new' tab load indefinetly in landscape mode

### ISSUE THREAD

**Issue by fimark** [TeamNewPipe/NewPipe#2657] opened 2019-09-22 12:39 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

![recording_20190913_081141](https://user-images.githubusercontent.com/44549081/65387242-a4ddec00-dd45-11e9-8afd-90880b2acf09.gif)

This issue seems to happen only on my tablet ( SAMSUNG GALAXY TAB A 2016 T580 ) and only when you open the 'What's New' tab. This does not happen if you visit a channel in landascape mode, infact the videos load just fine.

I noticed that this also happens with my Firestick TV, maybe it has to do with the screen size of the device I'm using Newpipe on?

**Comment by Jamie-uni** [comment] 2019-09-25 07:15
I can confirm this on my Huawei MediaPad T5. Exactly the same bug in landscape

**Comment by fimark** [comment] 2019-09-25 10:49
Huawei MediaPad T5 has the same screen size and resolution of my tablet. (10.1" 1080p)
Maybe we should test if this happens with smaller tablets

**Comment by Jamie-uni** [comment] 2019-09-26 00:00
Yeah probably worth testing in the android emulator to easily change dpi/resolution. For what it's  worth, I tested on a 10.5-inch 2560x1600 tablet with identical results.

**Comment by Stypox** [comment] 2019-09-29 13:15
Duplicate of #1974

**Closed by Stypox** 2019-09-29 13:15 UTC
