### ISSUE TITLE
Video feed loads, cannot access any videos

### ISSUE THREAD

**Issue by M1N0RM1N3R** [TeamNewPipe/NewPipe#8877] opened 2022-08-25 01:00 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

2.23.2

### Steps to reproduce the bug

Try to access any video

### Expected behavior

Video content, description, etc. load.

### Actual behavior

Frowny-face error screen with option to retry or report.

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=NdChqjlJDeY
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.2
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not store JavaScript player
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1048)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.initStsFromPlayerJsIfNeeded(YoutubeStreamExtractor.java:1116)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:770)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:78)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get player js code from url: https://www.youtube.com/s/player/dc0c6770/player_ias.vflset/en_US/base.js
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.downloadJavaScriptCode(YoutubeJavaScriptExtractor.java:137)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:49)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:65)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1046)
	... 21 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 / One UI 4.1

### Affected device model

Samsung Galaxy A32 5G (SM-A326U)

**Comment by itsme24082004** [comment] 2022-08-25 01:05
I can confirm this issue 

Device : Redmi 8a dual
Android : 10

**Comment by teambvd** [comment] 2022-08-25 01:06
Same on android 9. Only started in the last 3 hours, verified YT standard app functions properly, and doesnt seem to be any others reporting issues with their service currently.

**Comment by 1Olegna** [comment] 2022-08-25 01:09
Ditto. Samsung s10+ started a few hours ago

**Comment by lbrunkho** [comment] 2022-08-25 01:23
Duplicate of #8876

**Comment by HUB1104** [comment] 2022-08-25 03:01
can't play any video

**Comment by Daniel666666666666666666666666** [comment] 2022-08-25 03:57
Confirm, Android 5.1.1

**Comment by gcandrade10** [comment] 2022-08-25 04:03
Same here

**Comment by marek22k** [comment] 2022-08-25 05:04
Same for me

**Comment by geekyjazzy** [comment] 2022-08-25 05:58
I observed this too on my Samsung a82018.

**Comment by Master2050** [comment] 2022-08-25 06:15
Having same issue, [debug build by @Theta-Dev](https://github.com/TeamNewPipe/NewPipe/files/9387795/app-debug.zip) in https://github.com/TeamNewPipe/NewPipe/issues/8839 seems to have fixed the issue.

**Comment by geekyjazzy** [comment] 2022-08-25 06:27
I tried this and it did indeed work! :) Thank you @Master2050 .

**Closed** 2022-08-25 06:40 UTC
Labels: bug, needs triage
