### ISSUE TITLE
Player screen

### ISSUE THREAD

**Issue by Barmarel** [TeamNewPipe/NewPipe#7827] opened 2022-02-06 08:18 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
Please add the ability to scroll through the comment list without hiding the video snippet. Like in the official app.

#### Why do you want this feature?
Because watching video and reading comments at the same time is very convenient. 
_I agree that you can open the playback in a floating window, but to do this every time is not very convenient._

**Comment by SameenAhnaf** [comment] 2022-02-06 09:14
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4484

**Closed** 2022-02-06 11:10 UTC
Labels: enhancement
