### ISSUE TITLE
Back button goes back too far from subscriptions-new-list of video's-video

### ISSUE THREAD

**Issue by cdwijs** [TeamNewPipe/NewPipe#2899] opened 2019-12-28 08:53 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Summary: Back button goes back too far from subscriptions-new-list of video's-video

Usecase:
I would like to download 3 adjacent video's in the subscription-new (Abonnementen-Nieuw) section. This takes more clicks than needed.

Workflow in the current version:
Start NewPipe
Click on subscriptions (Abonnementen)
Click on New (Nieuw)
Scroll to the video and click on it. 
Click download and OK
Click back
Click on New (Nieuw)
Scroll to the video and click on it. 
Click download and OK
Click back
Click on New (Nieuw)
Scroll to the video and click on it. 
Click download and OK

Proposed change:
When the user is at the list of video's of subscriptions-new (Abonnementen-Nieuw), and he has clicked on a video, the back button should return to the list of video's of subscriptions-new, instead of to the list of subscriptions

Workflow after the change:
Click on subscriptions (Abonnementen)
Click on New (Nieuw)
Scroll to the video and click on it.
Click download and OK
Click back
Arrive at the same position in the list of video's, and click on the next video
Click download and OK
Click back
Arrive at the same position in the list of video's, and click on the next video
Click download and OK

Tested with this version:
NewPipe 0.17.4 (latest release)
Android 6.0.1
CyanogenMod 13.0-20161121-NIGHTLY-ks01lte
Samsung Galaxy S4

**Comment by Stypox** [comment] 2019-12-28 17:16
Duplicate of #2358

**Closed by Stypox** 2019-12-28 17:16 UTC
