### ISSUE TITLE
Add a 'Open in Browser' button to the broken video page

### ISSUE THREAD

**Issue by astatine** [TeamNewPipe/NewPipe#8800] opened 2022-08-15 12:47 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Currently, NewPipe shows the 'Sorry, something went wrong' page with the big frowny face when the video hasn't premiered yet, and when NewPipe itself is broken. That page has `Report` and `Retry` buttons with expected functionality.

For both these cases, it would be great if a `Open in Browser` button is added to the page.

<img alt="Sorry, something went wrong." src="https://user-images.githubusercontent.com/1077402/184637375-a6e2670b-2b01-4779-a39c-9680ae2f3bd4.png" height=600 />

### Why do you want this feature?

This would enable the user to know when the video will premiere, and in the second case would enable the user to watch the video.

**Comment by SameenAhnaf** [comment] 2022-08-16 06:14
@mhmdanas Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6624

**Comment by mhmdanas** [comment] 2022-08-16 10:40
@SameenAhnaf no, this isn't a duplicate of #6624. This issue requests an "Open in browser" button when errors occur, while that issue asks for showing more information in case of errors.

**Comment by opusforlife2** [comment] 2022-08-16 17:59
Would really prefer it if the browser is sent a Piped/Invidious link instead of a YT one.

**Comment by mhmdanas** [comment] 2022-08-16 18:16
I suppose that could be added as a setting.

**Comment by opusforlife2** [comment] 2022-08-16 18:24
#2351 would be a prerequisite then.

**Comment by YonghaoDeng** [comment] 2022-10-18 06:47
Hey, could I work on this issue? :))

**Comment by opusforlife2** [comment] 2022-10-21 22:33
@YonghaoDeng Please give some idea of how you will implement this? A button under Report and Retry saying "Open in Browser"? Or something else?

**Comment by YonghaoDeng** [comment] 2022-10-21 23:57
> s

I will firstly add a button called "Open in Browser" in the error_panel.xml, then write code like adding onclicklistener in the ErrorPanelHelper.kt file  to enable clicking this button to open the browser. 
I also found a broken video page example in the NewPipe app, and I add the button like this:
![屏幕截图 2022-10-22 105608](https://user-images.githubusercontent.com/110881976/197306349-d51c1462-76e8-404a-b311-23fe16ee4dcf.png)

**Comment by YonghaoDeng** [comment] 2022-10-23 11:05
I have submitted the PR, can you review it? if it has some questions, you can talk to me. @opusforlife2

**Closed** 2022-10-27 12:38 UTC
Labels: feature request, GUI
