### ISSUE TITLE
Support opening SoundCloud’s soundcloud.com/name/____ URLs in playlist mode

### ISSUE THREAD

**Issue by superrpotion** [TeamNewPipe/NewPipe#10228] opened 2023-07-13 05:41 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Allow users to access and listen to soundcloud.com/name\/____ in playlist mode 

E.G. Sharing soundcloud.com/kencarson/likes to NewPipe should bring up all of the user’s liked tracks in playlist form.
Sharing soundcloud.com/kencarson/popular-tracks to NP should bring up the user’s popular tracks in playlist form. 
So on and so forth for “tracks”, “reposts”, “likes”, and “popular-tracks”. 
(If there are any more of these links, please leave it in the comments). 

### Why do you want this feature?

I use my SoundCloud “likes” and “reposts” as a catch-all playlist, and the official SoundCloud app will not let you log in if you have MicroG or no Google Play Services installed. 

NewPipe works perfectly on non-GPS devices, but I am unable to find my likes (or any other user’s likes) in the app, I am only allowed to view a user’s popular tracks. I can’t view their tracks in chronological order, their likes, or reposts, so I am unable to use NP and am forced to use the mobile site. 

### Additional information

All known URLs:
soundcloud.com/kencarson/popular-tracks
soundcloud.com/kencarson/tracks
soundcloud.com/kencarson/reposts
soundcloud.com/kencarson/likes

There’s also 
soundcloud.com/kencarson/albums 
&
soundcloud.com/kencarson/sets
Being able to browse all of a user’s public playlists or albums would be amazing, but that might be asking for too much.

**Comment by AudricV** [comment] 2023-07-13 07:28
For everything you ask except popular tracks, that's a duplicate of #2414. For popular tracks, this has probably the place in #7729. Closing as a duplicate of these issues.

Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2023-07-13 07:28 UTC
Labels: feature request, needs triage
