### ISSUE TITLE
Background music open newpipe background player bug

### ISSUE THREAD

**Issue by Domiuns** [TeamNewPipe/NewPipe#3323] opened 2020-04-01 10:16 UTC
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ it_IT
* __Service:__ none
* __Version:__ 0.19.1
* __OS:__ Linux Android 4.4.4 - 19

<details><summary><b>Crash log</b></summary><p>

```
android.content.res.Resources$NotFoundException: File res/drawable/ic_volume_up_white_24dp.xml from drawable resource ID #0x7f08015c. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
	at android.content.res.Resources.loadDrawable(Resources.java:1993)
	at android.content.res.Resources.getDrawable(Resources.java:673)
	at org.schabi.newpipe.player.ServicePlayerActivity.getThemedDrawable(ServicePlayerActivity.java:706)
	at org.schabi.newpipe.player.ServicePlayerActivity.onMaybeMuteChanged(ServicePlayerActivity.java:701)
	at org.schabi.newpipe.player.ServicePlayerActivity.onCreateOptionsMenu(ServicePlayerActivity.java:156)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2508)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:325)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2830)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
	at android.content.res.Resources.loadDrawable(Resources.java:1990)
	... 20 more
org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
	at android.content.res.Resources.loadDrawable(Resources.java:1990)
	at android.content.res.Resources.getDrawable(Resources.java:673)
	at org.schabi.newpipe.player.ServicePlayerActivity.getThemedDrawable(ServicePlayerActivity.java:706)
	at org.schabi.newpipe.player.ServicePlayerActivity.onMaybeMuteChanged(ServicePlayerActivity.java:701)
	at org.schabi.newpipe.player.ServicePlayerActivity.onCreateOptionsMenu(ServicePlayerActivity.java:156)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2508)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:325)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2830)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

```
</p></details>
<hr>
I found this bug, when I put the music or a video in the background and I press on the notification to open the player the app crash.

**Comment by Stypox** [comment] 2020-04-01 10:19
Duplicate of #3320, fixed in #3322, could you test the apk provided there?

**Closed** 2020-04-01 10:19 UTC
Labels: bug
