### ISSUE TITLE
Jump to last watched video in channel

### ISSUE THREAD

**Issue by atar-axis** [TeamNewPipe/NewPipe#7044] opened 2021-09-02 22:45 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
It would be great if you could add an option to jump to the last seen video in a channel. Some channels have hundreds of video and if you watch them one by one then you need to scroll down and down and down every time you want to watch the next one. 

#### Is your feature request related to a problem? Please describe it

Not really, it would just be great! 

#### Additional context

Here's a photo of my cat
![IMG-20210902-WA0031](https://user-images.githubusercontent.com/11148588/131925460-8c6a8a0a-ef8f-45c7-892a-056491acaa6a.jpg)

#### How will you/everyone benefit from this feature?

Really, I think this is totally self-explaining. If you ever wanted to watch videos one by one then you will understand. After some time newpipe just forgets where you scrolled to last time.

**Comment by Ammako** [comment] 2021-09-02 22:51
Alternatively, an option to add all of a channel's videos to a playlist, and then automatic sorting options for playlist so you could sort the playlist by chronological order, from oldest to newest. Then you can just play the list from the beginning, and remove videos from the list as you watch them, and the next unwatched one will always be at the top of the list.

**Comment by SameenAhnaf** [comment] 2021-09-03 03:34
Duplicate of #5193.

**Closed** 2021-09-03 05:08 UTC
Labels: enhancement
