### ISSUE TITLE
Bug when entering Full Screen mode

### ISSUE THREAD

**Issue by AppolyLPU** [TeamNewPipe/NewPipe#8303] opened 2022-04-28 14:59 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Click on a video
2. Enter fullscreen mode
3. The video is at visible just small in the left upper corner

### Expected behavior

The video at fullscreen mode should be in fullscreen.

### Actual behavior

The video is just visible in the left upper corner, the rest is black.

### Screenshots/Screen recordings

![Uploading Screenshot_NewPipe.jpg…]()

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S20

**Comment by SameenAhnaf** [comment] 2022-04-28 15:06
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7262

**Closed** 2022-04-28 18:31 UTC
Labels: bug
