### ISSUE TITLE
Videos in popup mode does not go fullscreen

### ISSUE THREAD

**Issue by shadowcyberdeck** [TeamNewPipe/NewPipe#6739] opened 2021-07-23 14:53 UTC
### Checklist

- [x] I am using the latest version - NewPipe yt_throttling 0.21.6 and NewPipe 0.21.7
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open any video and start playing it in horizontal full screen
1.a. I have screen rotate locked to vertical position
2. Switch to a different app to force the video into popup mode
3. Tap to make it full screen
4. In stead of reverting to horizontalfull screen it always ends up in vertical full screen
5. tapping the full screen icon in the lower right doesn't do anything
6. I end up having to force close the app and reopen to get back into horizontal full screen

### Expected behavior
Prior to both version 0.21.6 and 0.21.7 going from popup back to horizontal full screen worked flawlessly. 

### Screenshots/Screen recordings
Screen recording: https://mega.nz/file/MMh3RSxB#UPPZSO6n7fdom-XuMBXoT4NVcCJsCvgiXxMGxUP9Luc

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Samsung Galaxy Note 9

**Comment by mhmdanas** [comment] 2021-07-26 14:32
Duplicate of #5339. If you disagree, feel free to make a comment.

**Closed by mhmdanas** 2021-07-26 14:32 UTC
Labels: bug

**Comment by shadowcyberdeck** [comment] 2021-07-28 16:28
Checked #5339. And I have it set to open in popup player mode already.  It could be a specific device bug. If you need further logs please advise.
