### ISSUE TITLE
Subtitles cover the entire video. 

### ISSUE THREAD

**Issue by Riki432** [TeamNewPipe/NewPipe#4598] opened 2020-10-22 15:37 UTC
Well idk what more to say. 
![Screenshot_2020-10-22-21-02-55-866_org schabi newpipe](https://user-images.githubusercontent.com/44449105/96895729-54861000-14aa-11eb-9bd4-4fc627d6a12a.jpg)
![Screenshot_2020-10-22-21-03-04-587_org schabi newpipe](https://user-images.githubusercontent.com/44449105/96896073-ba729780-14aa-11eb-9d09-f64c6534c6eb.jpg)

Looks the same in popup video player. 
Haven't seen this happen to another video. 
Thanks for all the work ya'll do! 
Link to video: https://www.youtube.com/watch?v=lBmJ8-DsStE&t=2

**Comment by opusforlife2** [comment] 2020-10-22 16:40
@Stypox Seems like a duplicate of #4096.

**Comment by mhmdanas** [comment] 2021-04-15 20:56
I'll be closing this issue as a duplicate of #4096, but if you believe I'm wrong please write a comment.

**Closed by mhmdanas** 2021-04-15 20:56 UTC
Labels: bug
