### ISSUE TITLE
Quick Downloads from Titles

### ISSUE THREAD

**Issue by vrindavan** [TeamNewPipe/NewPipe#5227] opened 2020-12-19 19:05 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
If we have to download we have to click or play or open the video itself in order to download, it would be nice to have an ability to long press on videos and download then straight away from there, if any option is not important enough to be put there in the long press then it can be replaced with this one also or just simply added there.

**Comment by tkomianos** [comment] 2021-03-12 05:39
Is there anything new on this?

**Comment by mhmdanas** [comment] 2021-04-15 20:23
Duplicate of #2171.

**Closed by mhmdanas** 2021-04-15 20:23 UTC
Labels: GUI, enhancement
