### ISSUE TITLE
Error when change default folder

### ISSUE THREAD

**Issue by alabotski** [TeamNewPipe/NewPipe#7400] opened 2021-11-13 21:20 UTC
I have problems with NewPipe 0.21.13

My table - Mi Pad4
My firmware Carbon, Android 10 + Root - https://get.carbonrom.org/device-clover.html

When I try change default folder for Video & Music I have such error

`{"user_action":"ui error","request":"ACRA report","content_language":"ru-BY","content_country":"BY","app_language":"ru_BY","service":"none","package":"org.schabi.newpipe","version":"0.21.13","os":"Linux Android 10 - 29","time":"2021-11-12 22:54","exceptions":["android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }\n\tat android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)\n\tat android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)\n\tat android.app.Activity.startActivityForResult(Activity.java:5211)\n\tat androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)\n\tat androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)\n\tat androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)\n\tat androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)\n\tat androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)\n\tat androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)\n\tat org.schabi.newpipe.settings.DownloadSettingsFragment.launchDirectoryPicker(DownloadSettingsFragment.java:217)\n\tat org.schabi.newpipe.settings.DownloadSettingsFragment.onPreferenceTreeClick(DownloadSettingsFragment.java:208)\n\tat androidx.preference.Preference.performClick(Preference.java:1192)\n\tat androidx.preference.Preference.performClick(Preference.java:1166)\n\tat androidx.preference.Preference$1.onClick(Preference.java:181)\n\tat android.view.View.performClick(View.java:7259)\n\tat android.view.View.performClickInternal(View.java:7236)\n\tat android.view.View.access$3600(View.java:801)\n\tat android.view.View$PerformClick.run(View.java:27896)\n\tat android.os.Handler.handleCallback(Handler.java:883)\n\tat android.os.Handler.dispatchMessage(Handler.java:100)\n\tat android.os.Looper.loop(Looper.java:214)\n\tat android.app.ActivityThread.main(ActivityThread.java:7361)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)\n"],"user_comment":""}`

**Comment by litetex** [comment] 2021-11-14 11:37
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6729

> > ` No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }`
> 
> Looks like you have no file-manager...
> Can you check if you have one?

**Closed by litetex** 2021-11-14 11:37 UTC
Labels: bug, template-missing

**Comment by alabotski** [comment] 2021-11-14 17:14
@litetex 
Yes I deleted default file manager
But I have another - MiXplorer

**Comment by opusforlife2** [comment] 2021-11-14 17:31
@alabotski Use Material Files - https://f-droid.org/en/packages/me.zhanghai.android.files/
