### ISSUE TITLE
[Bug]: Playlist list is not complete when choosing to add a video to a playlist.

### ISSUE THREAD

**Issue by jehutyy** [TeamNewPipe/NewPipe#3919] opened 2020-07-21 14:38 UTC
When long pressing on a video to add to a playlist, it seems that only a subset of existing playlist is display on screen.

Example: 
If I have 
* a
* b
* c
* d
...
* n

Only playlist `a` to `d` will show on screen. Thus leading to being unable to add a video to playlist `n` as it doesn't show up.

I guess there's no issue when you doesn't have that much playlist.

Version : 0.19.5
Installed-from : F-Droid

**Comment by Stypox** [comment] 2020-07-24 16:08
I can't reproduce. Are you sure scrolling down does nothing?

**Comment by Kukulkan2019** [comment] 2020-07-26 13:27
Scrolling down stops at the forth row, persistently, I. e., twenty videos...

**Comment by opusforlife2** [comment] 2020-10-10 19:52
Closing until @jehutyy replies.

**Closed by opusforlife2** 2020-10-10 19:52 UTC
Labels: bug, more info needed

**Comment by jehutyy** [comment] 2020-10-20 08:51
Sorry I didn't see there was an update. 

I just tried and issue is still here. 

I can add some details however. It seems that I can only add track to playlist I created myself and not those I add by clicking on burger icon in the top right corner of the screen (those created by other maybe ?).

Can you confirm that adding a playlist already created by other to my `registered playlist` only make a reference to that playlist instead of creating a new playlist and adding elements from source playlist into it ?

**Comment by opusforlife2** [comment] 2020-10-20 10:44
Newpipe contains two kinds of playlists. The ones which you create yourself from within Newpipe (user playlists), and the ones which you add through bookmarking (service playlists). You can only modify user playlists, not service playlists.

**Comment by jehutyy** [comment] 2020-10-20 10:58
Ok I understand better. Is there a way to convert from one to another without having to add tracks one by one ?

**Comment by opusforlife2** [comment] 2020-10-20 11:01
Tap on Background play in the service playlist. It'll queue up all the streams. Open the Queue. You can see the Add to Playlist button there.

**Comment by jehutyy** [comment] 2020-10-20 11:13
Thank you very much I'll do that ;)
