### ISSUE TITLE
casting on a smart tv

### ISSUE THREAD

**Issue by hugeviking** [TeamNewPipe/NewPipe#3161] opened 2020-02-29 15:15 UTC
i'm using newpipe on a smart tv. is there a way to add the casting option from the phone like youtube app?

**Comment by wb9688** [comment] 2020-02-29 15:19
No, this issue is a duplicate of #668. Btw I'm working on PipeCast, which will initially support UPnP A/V and potentially also e.g. Cast v2 in the future.

**Closed by wb9688** 2020-02-29 15:19 UTC

**Comment by hugeviking** [comment] 2020-02-29 21:50
great ty
