### ISSUE TITLE
Show download progress and name of the video/audio file in notification while downloading

### ISSUE THREAD

**Issue by Simpath** [TeamNewPipe/NewPipe#8437] opened 2022-05-25 07:43 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I want newpipe's download notification to show download progress like how much it's been downloaded and how much is left both in a bar style and in xxMB/xxxMB style

And also show the name of the downloading file

Something like this:
<img alt="Screenshot_2022-05-25-13-01-55-358_org bromite bromite" src="https://user-images.githubusercontent.com/106220340/170206344-d6220dae-555e-4f11-8023-b1efdab4e10d.jpg" height=600 />

Currently it's like this
<img alt="Screenshot_2022-05-25-13-03-11-377_org schabi newpipe" src="https://user-images.githubusercontent.com/106220340/170206563-bd08d225-93a2-4a1f-9ec4-3c971d86012b.jpg" height=600 />

> 

### Why do you want this feature?

It would make it easy to track the download progress like
which videos have been downloaded
which ones are pending
Which are half download
Just by looking at the notification panel
Currently it takes us to download section for the same on tapping the notification but notification alone is not helpful

**Comment by SameenAhnaf** [comment] 2022-05-25 07:48
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3332

**Closed** 2022-05-25 07:49 UTC
Labels: enhancement

**Comment by Rishukumar-in** [comment] 2024-05-07 07:55
You mentioned it as not planned but atleast let it be open as feature request.Please do consider this in future.Thus feature will be very helpful.
