### ISSUE TITLE
Feature request: Recent by date

### ISSUE THREAD

**Issue by pmprog** [TeamNewPipe/NewPipe#2109] opened 2019-02-09 17:48 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
----------------------

I like the current "what's new" feed that shows the latest video/audio per subscription, but could we also have a "recent" list which shows all the uploaded items within a date range?

**Comment by TobiGr** [comment] 2019-02-10 11:42
Duplicate of #739

**Closed by TobiGr** 2019-02-10 11:42 UTC
