### ISSUE TITLE
Title text cutoff in beginning of feed

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6674] opened 2021-07-16 01:52 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to Newpipe
2. Check what new
3. Scroll up to reload what's new
4. Look at the text
5. See bug

### Actual behavior

Some text on The title gets cut off.

### Expected behavior

Title to be fully shown

### Screenshots/Screen recordings

![Screenshot_20210716-044847](https://user-images.githubusercontent.com/74511929/125879580-773272a3-6eb7-41c2-a509-7f24074f5128.jpg)

### Device info

 - Android version/Custom ROM version: version 7.1.1 Nougat
 - Device model: Samsung Galaxy Tab A

**Comment by SameenAhnaf** [comment] 2021-07-16 02:38
Grid view has been always like this. However, #6496 also suggests to solve the same bug.

**Comment by Thewisem** [comment] 2021-07-16 02:44
No That isn't the issue

**Comment by Thewisem** [comment] 2021-07-16 02:44
Ofc it wouldn't show full text

**Comment by Thewisem** [comment] 2021-07-16 02:45
But look at the beginning letter, of each of them or when the line starts

**Comment by Thewisem** [comment] 2021-07-16 02:46
There is a cutout over there which wasn't there in 0.21.5

**Comment by SameenAhnaf** [comment] 2021-07-16 02:52
It shows full text on my device on v0.21.5 neither. Did you change your device font size?
![IMG_20210716_085115](https://user-images.githubusercontent.com/79245641/125884375-f3f73110-5d40-48b0-84c1-d19dffe6f433.jpg)

**Comment by SameenAhnaf** [comment] 2021-07-16 02:54
Oh, yeah. Let's remove the off-topic comments please.

**Comment by Thewisem** [comment] 2021-07-16 03:03
Ok

**Comment by skyGtm** [comment] 2021-07-16 07:32
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6664
#6664 is talking about **Thumbnail** 
and this one is talking about **Title**.

**Comment by onkq** [comment] 2021-07-16 08:54
I mean both the thumbnail and the title

**Comment by mhmdanas** [comment] 2021-07-16 10:48
Duplicate of #6664.

**Closed by mhmdanas** 2021-07-16 10:48 UTC
Labels: bug
