### ISSUE TITLE
Broken timestamps in descriptions

### ISSUE THREAD

**Issue by brightentayle** [TeamNewPipe/NewPipe#2200] opened 2019-03-09 12:04 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

This issue actually was around since 0.15.1, but whenever a video with timestamps in the description shows up, NewPipe shows those as active links with hashtags on their end. The links lead to whatever YouTube player is set up by default, disregarding the timestamps.

![Screenshot_2019-03-09-13-45-23-547_org schabi newpipe](https://user-images.githubusercontent.com/38193034/54071318-95002e00-4273-11e9-8f1e-7fda18d52f3d.jpg)
![Screenshot_2019-03-09-13-47-11-448_com google android youtube](https://user-images.githubusercontent.com/38193034/54071319-95002e00-4273-11e9-8442-53f58b6d8fdb.jpg)

**Comment by TobiGr** [comment] 2019-03-09 12:31
Fixed in #2168 which will be included in version 0.16.1
Btw. 0.16.0 is the latest version

**Closed by TobiGr** 2019-03-09 12:31 UTC

**Comment by jimbo1qaz** [comment] 2019-07-15 21:10
Still broken in 0.16.2 from F-Droid.

**Comment by Stypox** [comment] 2019-07-16 07:41
Duplicate of #1025
