### ISSUE TITLE
Video plays in portait mode on tablet

### ISSUE THREAD

**Issue by sryze** [TeamNewPipe/NewPipe#3564] opened 2020-05-10 08:40 UTC
### Version
0.19.3
-

### Steps to reproduce the bug
1. Open a video
2. Press on play button

### Expected behavior
Video start playing in landscape mode, same as YouTube and other video apps

### Actual behaviour
Video is played in portait mode 

### More info
Auto-rotate is off.

When I turn auto-rotate on NewPipe plays videos in landscape mode as expected.

Device: Lenovo A7600-H Android KitKat 4.4

**Comment by B0pol** [comment] 2020-05-10 10:07
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3485

**Closed by B0pol** 2020-05-10 10:07 UTC
Labels: bug
