### ISSUE TITLE
Mix the fast and informative feed loader

### ISSUE THREAD

**Issue by dhuschde** [TeamNewPipe/NewPipe#8949] opened 2022-09-08 19:05 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The feed should be updated using the fast feed loader (which lacks information), but if it detects new Videos, it should use the Informative feed loader on only the updated channels.

This could be auto-enabled if the user has 50+ Subscriptions.

### Why do you want this feature?

This would speed up the Update process and still remain informative

**Comment by SameenAhnaf** [comment] 2022-09-08 19:31
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4934

**Closed as completed** 2022-09-08 19:45 UTC
Labels: duplicate
