### ISSUE TITLE
[feature request] Blacklist uploaders from appearing in search results

### ISSUE THREAD

**Issue by EmberHeartshine** [TeamNewPipe/NewPipe#2464] opened 2019-07-14 23:21 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports. (n/a)

When I'm searching for videos, I don't want BS "creators" with clickbait titles like Toms Mucenieks showing up in the search results. Could there be a feature that blacklists all videos from an uploader of my choice?

**Comment by Stypox** [comment] 2019-07-15 13:16
Duplicate of #1815

**Closed** 2019-07-15 15:07 UTC
