### ISSUE TITLE
v0.21.14 Playback gets stuck randomly

### ISSUE THREAD

**Issue by ToniMHeinonen** [TeamNewPipe/NewPipe#7574] opened 2021-12-24 06:40 UTC
### Checklist

- [x] I am using the latest version - 0.21.14 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open desired video
2. Click "Background"
3. Wait for 5-30 minutes
4. Hold down on other video and select "Enqueue" (I am not sure if this last step is required, but I always listen to multiple videos in a row using this method so it might be part of the reason the video gets stuck?)

### Actual behavior

Video stops playing randomly between 5 to 30 minutes of playback. The whole playback disappears from lock screen and when I swipe to show the top bar playback, there is a hourglass instead of play button.

This only happens in the newest version. I have used v0.21.13 for a long time and it never had this bug. I downgraded back to that version and playback is fully functional again.

### Expected behavior

Playback should not get stuck.

### Device info

 - Android version/Custom ROM version: 11
 - Device model: Moto G9 Plus

**Comment by TiA4f8R** [comment] 2021-12-24 09:57
> - [x] I am using the latest version - 0.21.14

This is not the latest version anymore. The latest version is 0.21.15 and this version fixes this issue.

> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

Duplicate of #7529. Like the template said, please check (better maybe?) for duplicates next time before you open an issue. Thank you!

**Closed by TiA4f8R** 2021-12-24 09:57 UTC
Labels: bug

**Comment by ToniMHeinonen** [comment] 2021-12-24 11:32
It is still the latest version in F-Droid. I was not aware, that F-Droid does not have the latest version, sorry for that. I did not check for duplicates so far away, since I remembered that the v.0.21.14 came couple of days ago. Sorry for the trouble.

**Comment by opusforlife2** [comment] 2021-12-25 19:48
@ToniMHeinonen https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/
