### ISSUE TITLE
Show replies to comments

### ISSUE THREAD

**Issue by Aga-C** [TeamNewPipe/NewPipe#6643] opened 2021-07-11 13:19 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I've encountered on YouTube that there are no replies to comments. It would be very nice to add this feature to be able to see whole conversations under video.

#### Is your feature request related to a problem? Please describe it

--

#### Additional context

In a web browser:
![image](https://user-images.githubusercontent.com/85929121/125196503-8b7b9c00-e25a-11eb-8e21-069a83b8f789.png)

The same in NewPipe:
![image](https://user-images.githubusercontent.com/85929121/125196630-e1504400-e25a-11eb-88c1-5b41564a5a1e.png)

#### How will you/everyone benefit from this feature?

Thanks to this feature, the app will show whole conversations in comments, so users won't miss anything if they like to read comments.

**Comment by ShareASmile** [comment] 2021-07-11 15:01
Duplicate of #2277 

Always check for duplicates first by searching issue tracker with relevant word before creating new issue, as per issue creation guidelines (checklist bullet point No. 1)

**Closed** 2021-07-11 15:31 UTC
Labels: enhancement
