### ISSUE TITLE
After update to latest version app crashes when shared link

### ISSUE THREAD

**Issue by rancidfrog** [TeamNewPipe/NewPipe#2407] opened 2019-06-18 14:04 UTC
App crashed on first launch after update,

```
   "user_action": "something",
   "request": "could not parse app update JSON data",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.16.2",
   "os": "Linux Android 7.1.1 - 25",
   "time": "2019-06-18 13:50",
   "exceptions": 


org.json.JSONException: Value <html><title>500 of type java.lang.String cannot be converted to JSONObject
at org.json.JSON.typeMismatch(JSON.java:111)
at org.json.JSONObject.<init>(JSONObject.java:160)
at org.json.JSONObject.<init>(JSONObject.java:173)
at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:108)
at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:48)
at android.os.AsyncTask.finish(AsyncTask.java:667)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6334)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
![](https://i.imgur.com/V2v729Q.png)

**Comment by Stypox** [comment] 2019-06-18 14:10
Duplicate of #2197

**Closed** 2019-06-18 16:50 UTC
