### ISSUE TITLE
Bug report - Unrecoverable error Surface Duo 

### ISSUE THREAD

**Issue by lico9182** [TeamNewPipe/NewPipe#8423] opened 2022-05-20 04:31 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

O.23.0

### Steps to reproduce the bug

Bug error happened in background, not sure if this happened while I was using the Newpipe app, or while the Newpipe app was running as a background task

### Expected behavior

Not applicable, as I had no knowledge this bug had happened until I swiped down to look at the Surface Duo's notifications. 

### Actual behavior

Did not perform any steps. This error seemed to happen at some point in the background 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=GVtTIHy8tC4
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4020, -1, null, [1280, 720, -1.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
	... 3 more
Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0
	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:99)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1177)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:794)
	... 5 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11

### Affected device model

Microsoft Surface Duo

### Additional information

Microsoft Surface Duo is a twin screen folding device, (and is not a single folding screen) it uses a custom version of the Microsoft Launcher which has been created and maintained by Microsoft specifically for the Duo device.

**Comment by mhmdanas** [comment] 2022-05-22 11:29
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/8016.

**Closed by mhmdanas** 2022-05-22 11:29 UTC
Labels: bug
