### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by AshishKumarSahu-1** [TeamNewPipe/NewPipe#11534] opened 2024-09-15 10:43 UTC
{"user_action":"ui error","request":"ACRA report","content_language":"en-IN","content_country":"IN","app_language":"en_IN","service":"none","package":"org.schabi.newpipe","version":"0.27.2","os":"Linux samsung/r11sxins/r11s:14/UP1A.231005.007/S711BXXU2CXCF:user/release-keys 14 - 34","time":"2024-09-15 16:12","exceptions":["android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)\n\tat android.os.Parcel.writeSerializable(Parcel.java:2809)\n\tat android.os.Parcel.writeValue(Parcel.java:2575)\n\tat android.os.Parcel.writeValue(Parcel.java:2374)\n\tat android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)\n\tat android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)\n\tat android.os.Bundle.writeToParcel(Bundle.java:1389)\n\tat android.os.Parcel.writeBundle(Parcel.java:1379)\n\tat android.os.Parcel.writeValue(Parcel.java:2491)\n\tat android.os.Parcel.writeValue(Parcel.java:2381)\n\tat android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)\n\tat android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)\n\tat android.os.Bundle.writeToParcel(Bundle.java:1389)\n\tat android.os.Parcel.writeBundle(Parcel.java:1379)\n\tat android.os.Parcel.writeValue(Parcel.java:2491)\n\tat android.os.Parcel.writeValue(Parcel.java:2381)\n\tat android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)\n\tat android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)\n\tat android.os.Bundle.writeToParcel(Bundle.java:1389)\n\tat android.os.Parcel.writeBundle(Parcel.java:1379)\n\tat android.os.Parcel.writeValue(Parcel.java:2491)\n\tat android.os.Parcel.writeValue(Parcel.java:2381)\n\tat android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)\n\tat android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)\n\tat android.os.Bundle.writeToParcel(Bundle.java:1389)\n\tat android.os.Parcel.writeBundle(Parcel.java:1379)\n\tat android.os.Parcel.writeValue(Parcel.java:2491)\n\tat android.os.Parcel.writeValue(Parcel.java:2381)\n\tat android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)\n\tat android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)\n\tat android.os.Bundle.writeToParcel(Bundle.java:1389)\n\tat android.os.Parcel.writeBundle(Parcel.java:1379)\n\tat android.os.Parcel.writeValue(Parcel.java:2491)\n\tat android.os.Parcel.writeValue(Parcel.java:2381)\n\tat android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)\n\tat android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)\n\tat android.os.Bundle.writeToParcel(Bundle.java:1389)\n\tat android.os.Parcel.writeBundle(Parcel.java:1379)\n\tat android.os.Parcel.writeValue(Parcel.java:2491)\n\tat android.os.Parcel.writeValue(Parcel.java:2381)\n\tat android.os.BaseBundle.dumpStats(BaseBundle.java:1917)\n\tat android.os.BaseBundle.dumpStats(BaseBundle.java:1954)\n\tat android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)\n\tat android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)\n\tat android.os.Handler.handleCallback(Handler.java:958)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:230)\n\tat android.os.Looper.loop(Looper.java:319)\n\tat android.app.ActivityThread.main(ActivityThread.java:8919)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)\nCaused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)\n\tat java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)\n\tat java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)\n\tat java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)\n\tat java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)\n\tat java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)\n\tat java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)\n\tat java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)\n\tat java.util.ArrayList.writeObject(ArrayList.java:873)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)\n\tat java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)\n\tat java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)\n\tat java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)\n\tat java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)\n\tat java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)\n\tat java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)\n\tat java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)\n\tat java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)\n\tat java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)\n\tat android.os.Parcel.writeSerializable(Parcel.java:2804)\n\t... 50 more\n"],"user_comment":""}

**Comment by AudricV** [comment] 2024-09-15 14:37
Please follow the issue forms available on GitHub's website when opening an issue. Duplicate of #11356.

**Closed by AudricV** 2024-09-15 14:37 UTC
