### ISSUE TITLE
Share from YouTube app to background player

### ISSUE THREAD

**Issue by SDB69100** [TeamNewPipe/NewPipe#1807] opened 2018-10-12 17:51 UTC
Share from YouTube app to background player : new video starts instead of being queued

Hi team, the issue is as described as in the title. It occurs when NewPipe is set to directly play yt audio in the background (no "ask first", I don't know if it happens when we prefer this option). When I use sharing with youtube, despite the fact that an info appears to indicate that this video has been enqueued, it stops the track I'm listening to and plays this new one instead.
Thanks for paying attention to the request.

**Comment by theScrabi** [comment] 2018-10-31 10:03
👍

**Comment by SDB69100** [comment] 2018-10-31 15:51
Thank you :)

**Comment by TobiGr** [comment] 2018-11-09 20:53
I'd suggest to add another setting, but make the enqueue option the default behaviour.

**Comment by Stypox** [comment] 2019-08-28 17:44
Duplicate of #1487

**Closed by Stypox** 2019-08-28 17:44 UTC
