### ISSUE TITLE
Randomly occured ui error

### ISSUE THREAD

**Issue by Serdna-Git** [TeamNewPipe/NewPipe#10373] opened 2023-08-24 13:35 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

25.2

### Steps to reproduce the bug

Randomly occuring error, see attachments.

### Logs

Sorry can't copy the log from my TV:

![Page1](https://github.com/TeamNewPipe/NewPipe/assets/143096691/b0171123-a861-4fb9-a6d7-7698a7af8a9f)

![Page2](https://github.com/TeamNewPipe/NewPipe/assets/143096691/4264db73-4e59-4db1-9c47-a7af772ef3ff)

**Comment by AudricV** [comment] 2023-08-24 14:55
Does the crash happen using the steps to reproduce of similar cases reported in the issue #8384? I believe your issue is a duplicate of this one.

Please try to give more information in the template the next time you want to open a bug report, especially for the `Steps to reproduce the bug` section.

**Comment by Serdna-Git** [comment] 2023-08-26 11:07
My apologies... you're absolutely right. So I can reproduce it. It's a duplicate. I haven't found that issue...

If you have a another second:  If I switch to full size also an error occurs (only frozen full size picture without sound) but there is no stack trace around. It is said: Look in the notifications but I can't found anything. Is the stack trace somewhere in the file system? Then I could send issues with text.
PS: I have to use an external video player (vlc) but with known sound issues at certain resolutions.

Thanks again!
________________________________

**Closed** 2023-09-15 19:48 UTC
Labels: duplicate
