### ISSUE TITLE
App/UI crashed

### ISSUE THREAD

**Issue by Speedmanasepsis** [TeamNewPipe/NewPipe#8317] opened 2022-04-30 20:23 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

Clicked on video on PeerTube
App/UI crashed

### Expected behavior

Video expected to play, not to cause app/UI to crash.

### Actual behavior

App/UI crashed

### Screenshots/Screen recordings

![Uploading Screenshot_20220430-161817.png…]()

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:502)
	at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:517)
	at org.schabi.newpipe.util.ListHelper.$r8$lambda$UGNhfSv5KuYwsqrcThyeG189sI0(Unknown Source:0)
	at org.schabi.newpipe.util.ListHelper$$ExternalSyntheticLambda2.compare(Unknown Source:4)
	at java.util.Collections$ReverseComparator2.compare(Collections.java:5235)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at org.schabi.newpipe.util.ListHelper.sortStreamList(ListHelper.java:279)
	at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:253)
	at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:140)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1616)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6(VideoDetailFragment.java:917)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$X-UcNln23jPsop2TvHe2VPTu0NQ(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda11.accept(Unknown Source:8)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Google Pixel 5

**Comment by TiA4f8R** [comment] 2022-04-30 21:13
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

No, duplicate of #6860.

**Closed by TiA4f8R** 2022-04-30 21:13 UTC
Labels: bug
