### ISSUE TITLE
Crash to lockscreen on opening a video

### ISSUE THREAD

**Issue by botistreamer** [TeamNewPipe/NewPipe#6497] opened 2021-06-16 09:56 UTC
### Checklist

- [x] I am using the latest version - 0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open [this video](https://www.youtube.com/watch?v=ybcribf3D3Y)
2. Let the video play, crash occurs.

Note: This has been occurring for many of the past versions on this particular device only (none of my other devices). It is very difficult to recreate this bug because it occurs very rarely.

### Actual behaviour

System UI crashes to lockscreen

### Expected behavior

Video should play normally.

### Screenshots/Screen recordings

[Imgur Link to screen recording](https://imgur.com/a/sAsLkLz)

### Logs
[Logs.txt from Matlog app](https://github.com/TeamNewPipe/NewPipe/files/6661991/Logs.txt)
Logs were taken when screen recording was **not** enabled.

### Device info

 - Android version/Custom ROM version: Android 10, Stock ROM
 - Device model: Asus Zenfone 5Z ZS620KL

**Comment by botistreamer** [comment] 2021-07-15 13:22
Still occurs on 0.21.6 on same device.

**Comment by TiA4f8R** [comment] 2021-07-15 17:03
Duplicate of #4638.

**Closed by TiA4f8R** 2021-07-15 17:03 UTC
Labels: bug
