### ISSUE TITLE
Syncing option

### ISSUE THREAD

**Issue by Rik44444** [TeamNewPipe/NewPipe#2762] opened 2019-10-25 23:20 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi, this app is so great! Many thanks for all the hours of development. I have a request: please add a login option, this would really be better than export (I just switched phones and forgot to export) 
Even better if this would sync to a web version of newpipe or alternative!

**Comment by lu4p** [comment] 2019-10-27 09:35
I don't like the idea of a central service like that. However a automatic periodical Database Dump to storage would enable you to sync this across all your devices via Sycthing etc.

**Comment by Rik44444** [comment] 2019-10-27 10:11
Yes automatic periodic dump would be an option. Central service also imo, even better, as long as it is optional! Then everyone can choose if they want it or not.

**Comment by TobiGr** [comment] 2019-10-28 00:23
Duplicate of a bunch of other tickets, e.g. #1163. However, you might be interested in #2668

**Closed by TobiGr** 2019-10-28 00:23 UTC
