### ISSUE TITLE
[Feature Request] Refresh channel items/video comments/...

### ISSUE THREAD

**Issue by 4goettma** [TeamNewPipe/NewPipe#3222] opened 2020-03-12 22:15 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Using the "Channel Page" view there is currently no way to update the channel listing except quitting and restarting the app manually. When I'm using the NewPipe, switching to another app (NewPipe remaining opened in the background) and returning several hours later, videos added in the meantime are still missing. It's totally fine not to auto-update in the background but there should be a possibility to manually refresh / automatically after x hours (whats about frequently updated news channels?).
https://github.com/TeamNewPipe/NewPipe/issues/264 tried to adress adding the ability to reload pages but combined several request in a single issue and lost focus on the reload aspect.
I would suggest adding a swipe-to-refresh gesture.

**Comment by Stypox** [comment] 2020-03-13 13:53
Duplicate of #740 and fixed by #2309

**Closed by Stypox** 2020-03-13 13:53 UTC
