### ISSUE TITLE
View replies to comments.

### ISSUE THREAD

**Issue by TheMystery28** [TeamNewPipe/NewPipe#7543] opened 2021-12-15 10:44 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

All is 
#### Why do you want this feature?

Hello

Everything is specified on the title. It is strange to only see the comments and not their answers. 

In any case, whether you do or not, thank you for the application.

**Comment by SameenAhnaf** [comment] 2021-12-15 12:54
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2277

**Closed** 2021-12-15 18:33 UTC
Labels: enhancement
