### ISSUE TITLE
Videos won't load while connected to mobile data

### ISSUE THREAD

**Issue by stuffsearcher** [TeamNewPipe/NewPipe#4342] opened 2020-09-28 20:18 UTC
### Version

-0.19.8

### Expected behavior

The video page will load normally.

### Actual behaviour

A ReCaptcha challenge is requested. Most of the time the ReCaptcha won't load (see image #1), if it does (see image #2) and you complete it, something like the YouTube mobile webpage will load instead of the normal UI (see image #3). If you click the checkmark it just closes the ReCaptcha challenge and the issue persists.

If you reconnect to Wi-Fi after encountering the issues they might still happen. The quick and reliable way to fix it is Force Stopping the app and opening it while connected to Wi-Fi.

### Screenshots/Screen recordings

Image #1: https://ibb.co/8DCK6yv
Image #2: https://ibb.co/6XLWV16
Image #3: https://ibb.co/zJ4sJ4R

### Logs

There is no Error Report page, but the issue seems similar to #4008.

**Comment by Stypox** [comment] 2020-09-29 05:35
Duplicate of #3714, I posted your comment there

**Closed** 2020-09-29 05:37 UTC
Labels: bug, youtube
