### ISSUE TITLE
Can we add multiple trending categories 

### ISSUE THREAD

**Issue by developersop** [TeamNewPipe/NewPipe#5139] opened 2020-12-10 15:10 UTC
Can we add multiple trending categories like this
![Screenshot_2020-12-10-20-33-14-478_com google android youtube](https://user-images.githubusercontent.com/73459162/101789915-dc41df80-3b27-11eb-9195-0b1cc303e24b.jpg)

**Comment by HTSamurai** [comment] 2020-12-10 17:43
This is a duplicate of #1805

**Closed** 2020-12-10 19:10 UTC
Labels: enhancement
