### ISSUE TITLE
[Suggestion] White Font On Light Theme

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#1278] opened 2018-04-07 02:03 UTC
When using the light theme I find its looks odd since the font of the symbols and text that has a red background to be black in color. I think if it was white instead it would look better and be easier to read for the light theme.

**Comment by theScrabi** [comment] 2018-04-07 10:37
Yea that was suggested before :D This is just there because of historical reasons. However we should think of fixing this.

**Comment by trymeouteh** [comment] 2018-12-21 03:09
https://github.com/TeamNewPipe/NewPipe/pull/1851

This new theme is not merging well with the new tweaks to NewPipe. Would it be possible to update how themes are made/managed and apply a way to customize the font colors on certain sections such as titles, search results, subs, etc?

I would imagine by doing this it will allow future themes to have more customization options and that way when with the next update you can roll out a better light theme, dark theme and a new hacking theme all working fully.

**Comment by beNitinhere** [comment] 2018-12-21 06:33
@trymeouteh well, this is cool theme customization allow user to set ui as per their comfort I'll try to make it possible for future builds. 

Thanks for your suggestion👍

**Comment by B0pol** [comment] 2020-05-13 15:15
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3042

**Closed by B0pol** 2020-05-13 15:15 UTC
Labels: GUI, enhancement
