### ISSUE TITLE
Keyboard doesn't appear on search sometimes

### ISSUE THREAD

**Issue by CrimsonFork** [TeamNewPipe/NewPipe#7490] opened 2021-12-04 03:46 UTC
Not original author but same issue, here's my report:

### Checklist
- [x] I am using the latest version - 0.21.13
- [x] I checked, did find a duplicate, #7089, but was told to open a new issue instead.
- [x] I have read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
- [x] This issue contains only one bug.

### Steps to reproduce the bug
1. Open app after it's been closed
2. Press the search button

### Actual behavior
The first time pressing the button, as well as the emerging text field does not call the software keyboard, closing the search and opening it again works as expected, unless the app has been unfocused, in which case the behavior is not consistent.

### Expected behavior
Keyboard being called every time the search bar is focused.

This bug is not present in Legacy 0.20.8

### Device info

 - Android version/Custom ROM version: Stock Rom 6 & 7, as well as LineageOS 17.1 (Android 11)
 - Device model: YT3-X50F, XT1771 and XT1604 respectively

I have a rooted device and can navigate ADB if that helps.

**Comment by opusforlife2** [comment] 2021-12-04 13:25
> but was told to open a new issue instead.

To be clear, this is because they didn't fill out the template properly. So for our purposes this issue will be the go to reference when discussion happens.

**Comment by CrimsonFork** [comment] 2021-12-04 14:28
I figured as much, just couldn't find any rule on closed unresolved issues, so wanted to be cautious.

**Comment by ggdorman** [comment] 2021-12-04 14:36
Please close #6790 in favour of this (seeing as this is the active thread). An important piece of info from that thread:
> The problem started when that new 'show played videos' button was added beside the search button

This should help pinpoint the version this bug first appeared in.

**Comment by ggdorman** [comment] 2021-12-04 14:38
In fact it would be better to close this thread as the older one has more infoand has been viewed by other maintainers.

**Comment by litetex** [comment] 2021-12-04 22:07
> Steps to reproduce the bug
> 1. Open app after it's been closed
> 2. Press the search button

I still can't reproduce it.
We (the devs) need a manual that also works on standard Android (the one use by the emulators) otherwise we are unable to locate the problem.

Maybe it's related to the keyboard apps?
What do you use?

**Comment by CHECK-1234** [comment] 2021-12-05 01:26
> > Steps to reproduce the bug
> > 
> > 1. Open app after it's been closed
> > 2. Press the search button
> 
> I still can't reproduce it. We (the devs) need a manual that also works on standard/stock Android (the one use by the emulators) otherwise we are unable to locate the problem.
> 
> Maybe it's related to the keyboard apps? What do you use?

Im having this same issue on 0.21.13. Im currently in PHH AOSP Android 12 GSI. Here is what I did to get this issue.

1. Open NewPipe app
2. Click on trendings page
3. Click on video
4. Swipe down on video
5. Click on search icon
6. The keyboard does not appear, until I press back and press search icon again

If swipe up on the video and then swipe down on the video again, and then press search icon, the keyboard does not appear again, until i press back and press search icon again.

The keyboard app that I am using is "Simple Keyboard".

**Comment by CrimsonFork** [comment] 2021-12-05 02:44
I have observed this behavior with Hacker's Keyboard and AOSP keyboard (LineageOS). Also for me it's literally just opening the app and tapping the search icon.

**Comment by lawson85** [comment] 2021-12-05 09:50
I have the same. It is well annoying!

**Comment by litetex** [comment] 2021-12-05 12:11
I can also reproduce the problem with SwiftKey or Android's default AOSP keyboard, however these keyboards don't vanish but simply stays open and don't relays inputs to the field anymore. I assume that the search field loses focus which shouldn't happen.
1. Search something
2. Open a video from that search
3. minimize the video (swipe down)
4. click the search bar → keyboard should show up
5. close the minimized video → search bar loses focuses but keyboard is still up; Trying to enter anything 

Demo:

https://user-images.githubusercontent.com/40789489/144745876-db1904a5-172c-421f-b007-3d4d65d51d6c.mp4

**Comment by CHECK-1234** [comment] 2021-12-05 15:08
> I can also reproduce the problem with SwiftKey or Android's default AOSP keyboard, however these keyboards don't vanish but simply stays open and don't relays inputs to the field anymore. I assume that the search field loses focus which shouldn't happen.
> 
> 1. Search something
> 2. Open a video from that search
> 3. minimize the video (swipe down)
> 4. click the search bar → keyboard should show up
> 5. close the minimized video → search bar loses focuses but keyboard is still up; Trying to enter anything
> 
> Demo:
> 
>  NPSearchLosesFocus.mp4

I confirm also having that issue happening on my device when I followed your steps.

Maybe my other issue with keyboard not popping up when sliding a video down and pressing search on icon on NewPipe home pages (bookmarks,subscriptions,trending pages) might be related to PHH AOSP Android 12 GSI.

**Closed** 2022-01-03 10:52 UTC
Labels: bug
