### ISSUE TITLE
Screen Cast Button (Kodi) quite hidden since version 20

### ISSUE THREAD

**Issue by MeCias** [TeamNewPipe/NewPipe#4382] opened 2020-10-04 15:12 UTC
Hi,

I noticed quite a inconvenience in the new version since I use new pipe mainly with my tablet as a remote to watch youtube on the big screen.

Before you could open the required video and hit the screen cast button. Also not ideal (to start it from the Whats new page would be perfect), but with two steps you could reach your goal.

With the new version (20) you need to open the requested video, start the video (if no autostart) and then open the menu to get to the screen cast button. Quite a lot of steps.

Would be nice to get via the sub menu (long press) of the Whats new page to the screen cast icon or maybe over the add to icon.

Thanks for the good work and for considering my request.

**Comment by opusforlife2** [comment] 2020-10-04 15:18
Duplicate of #4063. Always check for duplicates before opening issues.

**Closed by opusforlife2** 2020-10-04 15:18 UTC
