### ISSUE TITLE
Searchable history

### ISSUE THREAD

**Issue by lurlo** [TeamNewPipe/NewPipe#8019] opened 2022-03-12 16:21 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Searchable history with filters

Useful filters:
- date
- channel
- video duration
- percentage watched 
- times watched
- category

### Why do you want this feature?

With a large history, becomes almost impossiblr to find a specific video that I remembered or I want show to someone else.

### Additional information

That's it

**Comment by SameenAhnaf** [comment] 2022-03-12 17:32
Duplicate of #2977

**Closed** 2022-03-13 21:19 UTC
Labels: enhancement
