### ISSUE TITLE
Expose toggles/menus before playback starts

### ISSUE THREAD

**Issue by WeAreJMJ** [TeamNewPipe/NewPipe#4444] opened 2020-10-08 06:18 UTC
### Checklist

- [✓] I checked, but didn't find any duplicates of this issue in the repo. 
- [✓] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [✓] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Prior to 0.20.0, the video details screen presents video resolution and 'open in browser' menus. Now it has been shifted into the player window, but only shows up after initiating playback.

Request: Show all/most toggles/menus in video details screen (not just play button)  before playback

#### Is your feature request related to a problem? Please describe it

No.

#### Additional context

It would need a mock-up :/ But the player UI has enough space to show the options. Also virtue of being buttons, minimize gesture won't be affected by this feature

#### How will you/everyone benefit from this feature?

Less wasted bandwidth and fewer taps.

**Comment by opusforlife2** [comment] 2020-10-08 06:45
Duplicate of #4039. Check for duplicates a little more thoroughly?

**Closed by opusforlife2** 2020-10-08 06:45 UTC

**Comment by WeAreJMJ** [comment] 2020-10-08 08:11
Ok sure. Shared my suggestion there
