### ISSUE TITLE
Add thumbnail images

### ISSUE THREAD

**Issue by Pranab009** [TeamNewPipe/NewPipe#7868] opened 2022-02-13 12:52 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

Why music thumbnail image is not available?
Please add thumbnail images (music - m4a/mp3)

### Additional information

If anyone don't want this feature for its little much bigger size then atleast add this option inside setting.Where anyone can enable or disabled thumbnail picture.
Please add this feature.

Please see this screenshot
<img alt="Screenshot_20220201-144048_1" src="https://user-images.githubusercontent.com/65340361/153754002-fe7570e5-6df4-4309-a195-b5e94cdace72.png" height=600 />

**Comment by mhmdanas** [comment] 2022-02-13 12:58
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4341.

**Closed by mhmdanas** 2022-02-13 12:58 UTC
Labels: question
