### ISSUE TITLE
Popup feature makes phone unresponsive

### ISSUE THREAD

**Issue by GidCat** [TeamNewPipe/NewPipe#7587] opened 2021-12-26 22:20 UTC
### Checklist

- [x] I am using the latest version - v0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open any video.
2. Press the "popup" button.

### Actual behavior
The homescreen and other apps will be unresponsive. The only way to get the phone to be responsive again is by closing the video from the notifications menu or rebooting.

### Expected behavior

The homescreen and other apps should still be responsive once the popup feature is used.

### Screenshots/Screen recordings

[Video demonstration](https://www.dropbox.com/s/fmve2st91ms261q/NewPipe%20popup%20freeze.mp4?dl=0)

### Device info

 - Android version 12/Custom ROM version: GrapheneOS SQ1D.211205.017.2021122018
 - Device model: Google Pixel 6

**Comment by litetex** [comment] 2021-12-26 23:01
Duplicate of #6770

**Closed by litetex** 2021-12-26 23:01 UTC
Labels: bug
