### ISSUE TITLE
Add option to Show Channel Details for videos in Local Playlists

### ISSUE THREAD

**Issue by ktprograms** [TeamNewPipe/NewPipe#6889] opened 2021-08-10 08:46 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Add a `Show Channel Details` button when long pressing a video in a Local (Self created) Playlist.

#### Is your feature request related to a problem? Please describe it

This feature is currently only available with Remote Playlists.

#### Additional context

_**I have already implemented this and will make a PR if/when this change is wanted.**_

<img height=500 alt="device-2021-08-10-164151" src="https://user-images.githubusercontent.com/71804605/128836248-53d3051e-5a0e-4dcc-843f-245ded12d648.png" />

#### How will you/everyone benefit from this feature?

It allows you to go to the video's channel directly.

**Comment by mhmdanas** [comment] 2021-08-10 11:44
This is a duplicate of #6155.

> I have already implemented this and will make a PR if/when this change is wanted.

Do please publish a PR with a fix. Thanks in advance!

**Closed by mhmdanas** 2021-08-10 11:44 UTC
Labels: enhancement

**Comment by ktprograms** [comment] 2021-08-10 11:47
Whoops, not sure how I missed that duplicate.
