### ISSUE TITLE
Captions / Subtitles cause NPE Crash

### ISSUE THREAD

**Issue by WiiliamChik** [TeamNewPipe/NewPipe#2280] opened 2019-04-11 08:20 UTC
![Screenshot_20190411-161735](https://user-images.githubusercontent.com/6219285/55942418-ef2b4f00-5c76-11e9-8617-dced1a5874ca.jpg)

it is the last code, I am using ExoPlayer 2.9.6. 
When i try to switch captions, app crashes.
Here is the crash log. Please help. Thank you.

> 2019-04-11 16:19:10.236 26144-26144/? E/class org.schabi.newpipe.report.ErrorActivity: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
        at java.util.Locale.getISO3Language(Locale.java:1686)
        at com.google.android.exoplayer2.util.Util.normalizeLanguageCode(Util.java:417)
        at com.google.android.exoplayer2.trackselection.DefaultTrackSelector$Parameters.<init>(DefaultTrackSelector.java:749)
        at com.google.android.exoplayer2.trackselection.DefaultTrackSelector$ParametersBuilder.build(DefaultTrackSelector.java:540)
        at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.setParameters(DefaultTrackSelector.java:1157)
        at org.schabi.newpipe.player.VideoPlayer.lambda$buildCaptionMenu$2(VideoPlayer.java:308)
        at org.schabi.newpipe.player.-$$Lambda$VideoPlayer$yR0wbGD8IQocuwF19MgCUgLH9So.onMenuItemClick(Unknown Source:4)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:163)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:908)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:898)
        at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3166)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4131)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3878)
        at android.widget.DropDownListView.onTouchEvent(DropDownListView.java:116)
        at android.view.View.dispatchTouchEvent(View.java:11776)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2959)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
        at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2397)
        at android.view.View.dispatchPointerEvent(View.java:12015)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4866)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4644)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4175)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4228)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4194)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4321)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4202)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4378)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4175)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4228)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4194)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4202)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4175)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6754)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6728)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6674)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6857)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.

**Comment by TobiGr** [comment] 2019-04-14 10:30
Confirmed. This needs to be fixed before 0.16.2 is released.
CC @theScrabi

**Comment by TobiGr** [comment] 2019-04-27 20:29
This was caused by #2184. Maybe @Redirion can help as he/she dug into the changes of the new exoplayer version already.

**Comment by Redirion** [comment] 2019-04-27 20:47
oh, thanks for notifying me. That looks exactly like the cause for which the CustomTrackSelector that I have deleted, was added. I will try to reproduce it and check if it can be fixed without having to re add the CustomTrackSelector.

**Closed** 2019-04-28 00:29 UTC
Labels: bug
