### ISSUE TITLE
Channels  Playlists

### ISSUE THREAD

**Issue by sarmad84** [TeamNewPipe/NewPipe#6092] opened 2021-04-16 05:21 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?

*I think it would be nice if you add feature channels Playlists which makes it possible to focus on content that we need.*
![Screenshot_20210416-151256_SkyTube Extra](https://user-images.githubusercontent.com/25746389/114975155-1ac91b80-9ec7-11eb-8301-16295eb547c0.jpg)

**Comment by sauravrao637** [comment] 2021-04-16 06:51
Hi!
It will be great if you can elaborate the feature you need :)

**Comment by SameenAhnaf** [comment] 2021-04-16 07:11
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5203. Please avoid opening issues on existing topics.

**Closed** 2021-04-16 09:20 UTC
Labels: enhancement
