### ISSUE TITLE
Is the trending page supposed to look like this ?

### ISSUE THREAD

**Issue by cool-student** [TeamNewPipe/NewPipe#3145] opened 2020-02-26 16:06 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I'm on Android 10.

this is what it looks like **before** 0.18.5
![Screenshot_20200226-165908 small](https://user-images.githubusercontent.com/43842960/75363124-f886cf80-58b9-11ea-877b-893744acece9.jpg)

this is what it looks like in 0.18.5:
![Screenshot_20200226-165757_NewPipe small](https://user-images.githubusercontent.com/43842960/75363132-fb81c000-58b9-11ea-8cdb-26d67d73db88.jpg)

is this intentional ?

**Comment by wb9688** [comment] 2020-02-26 16:17
Could you tell me what countries/languages you've set in Settings->Content.

**Comment by wb9688** [comment] 2020-02-26 16:22
Never mind, this happens in the UK. This is semi-intentional, but should be fixed. It's caused by that "Munya Chawawa" thing you currently see on YouTube's new site.

**Comment by mauriciocolli** [comment] 2020-02-26 16:25
Saw this as well, don't know why an issue was not opened for this release (as usual), specially because it brings a big change.

Anyway, [here's why](https://github.com/TeamNewPipe/NewPipeExtractor/blob/02b59903fa5a3c8d0c83166862d12ecf5febf1ff/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeTrendingExtractor.java#L90-L94):


```java
[...]
@Nonnull
@Override
public InfoItemsPage<StreamInfoItem> getInitialPage() {
    StreamInfoItemsCollector collector = new StreamInfoItemsCollector(getServiceId());
    JsonArray firstPageElements = initialData.getObject("contents").getObject("twoColumnBrowseResultsRenderer")
            .getArray("tabs").getObject(0).getObject("tabRenderer").getObject("content")
            .getObject("sectionListRenderer").getArray("contents").getObject(0).getObject("itemSectionRenderer")
            .getArray("contents").getObject(0).getObject("shelfRenderer").getObject("content")
            .getObject("expandedShelfContentsRenderer").getArray("items");

[...]
```

There's more items within the `initialData`. A more efficient solution would be to traverse all the objects and get the `videoRenderer` ones.

Unfortunately I don't have the time to open a pull request right now, if nobody does this I'll try to do it later.

**Comment by wb9688** [comment] 2020-02-26 16:26
@mauriciocolli: I'll do it as part of TeamNewPipe/NewPipeExtractor#262.

**Comment by B0pol** [comment] 2020-02-26 19:39
I've noticed it doesn't happen with all countries (try china (hongkong))

**Comment by wb9688** [comment] 2020-02-26 19:41
@B0pol: That's true, else I would've caught it earlier. However I already fixed it now in https://github.com/TeamNewPipe/NewPipeExtractor/pull/262/commits/db305408e906614fbdff44d963fc94aed1363c9c.

**Closed** 2020-02-29 20:39 UTC
Labels: bug, pr open, youtube
