### ISSUE TITLE
Sorting Playlist via time added

### ISSUE THREAD

**Issue by chantisnake** [TeamNewPipe/NewPipe#3486] opened 2020-04-25 20:31 UTC
#### Describe the feature you want

Add a setting in each playlist to let it be sorted via time added. 
Or
Add a setting in each playlist such that we can control when a new video is added, it is added as the last element or the first element

#### Additional context

I always add videos to my watch later during my day, and watch all of them at night. This makes a incredibly large "watch later" playlist. Therefore, if all video is added as the last element, it will be painful to find it. For now, I can just delete my watch later playlist periodically. 

#### How will you/everyone benefit from this feature?

As stated above.

**Comment by wb9688** [comment] 2020-04-26 05:40
Is #3065 also a solution for your problem? If so, please try the RC of v0.19.3

**Comment by chantisnake** [comment] 2020-04-26 13:36
I don't think so, I don't typically watch all of them.

**Comment by tfga** [comment] 2020-07-09 16:23
Related: #3815

**Comment by litetex** [comment] 2022-02-15 18:52
Duplicate of #3263

**Closed by litetex** 2022-02-15 18:52 UTC
Labels: enhancement
