### ISSUE TITLE
Restricted Content Video 

### ISSUE THREAD

**Issue by Anti-God** [TeamNewPipe/NewPipe#6750] opened 2021-07-24 01:07 UTC
Dear NewPipe Team! I can't watch videos under 18 age. Although, I had enabled [ Show age restricted content ]. Thanks

**Comment by iiSnewoNL** [comment] 2021-07-24 08:44
+1

**Comment by Mrnobody1411** [comment] 2021-07-24 08:56
I have the same annoying problem with the site not being able to play age restricted videos, again, I'm really starting to lose my patience to be honest.

**Comment by iiSnewoNL** [comment] 2021-07-24 08:58
> I have the same annoying problem with the site not being able to play age restricted videos, again, I'm really starting to lose my patience to be honest. 

You can always uninstall the app and wait for an update if you want to, tho.

**Comment by Mhowser** [comment] 2021-07-25 07:45
I heard that this may be YouTube finally cracking down and not letting anybody view age-restricted content without signing in to a valid, age verified account.

**Comment by iiSnewoNL** [comment] 2021-07-25 09:05
> I heard that this may be YouTube finally cracking down and not letting anybody view age-restricted content without signing in to a valid, age verified account.

Ooooof, source?

**Comment by litetex** [comment] 2021-07-25 16:33
The problem is already known and tracked as #6726

Closing this as duplicate of #6726

**Closed by litetex** 2021-07-25 16:33 UTC

**Comment by Mrnobody1411** [comment] 2021-07-26 00:05
> > I have the same annoying problem with the site not being able to play age restricted videos, again, I'm really starting to lose my patience to be honest.
> 
> You can always uninstall the app and wait for an update if you want to, tho.

I might as well since the sites run by a bunch of fucking monkeys
