### ISSUE TITLE
Show something if there is a duplicate item to be added to a local playlist

### ISSUE THREAD

**Issue by ryota-hasegawa** [TeamNewPipe/NewPipe#4783] opened 2020-11-03 01:55 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Show something (eg. warning, checkbox) if there is a duplicate item to be added to a local playlist like the official YouTube or YT Music app

#### Is your feature request related to a problem? Please describe it

No

#### Additional context

Nothing especially

#### How will you/everyone benefit from this feature?

It will be convenient for everyone that creates playlists.

**Comment by opusforlife2** [comment] 2020-11-03 06:19
Duplicate of #4186.

**Closed by opusforlife2** 2020-11-03 06:19 UTC
Labels: enhancement

**Comment by ryota-hasegawa** [comment] 2020-11-03 07:28
Oh, I'm sorry
