### ISSUE TITLE
Crash when clicking channel

### ISSUE THREAD

**Issue by dimaspaf14** [TeamNewPipe/NewPipe#8553] opened 2022-06-26 14:27 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1.play random music in the background
2.search for random video
3.click the random video(dont play it)
4.click channel & it crash
After repeating for 3-4 times may fine

### Expected behavior

See a random clicked channel

### Actual behavior

Crash & switch to another app

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 6.0.1 - 23
<details><summary><b>Crash log </b></summary><p>

```
java.lang.OutOfMemoryError: Failed to allocate a 4355412 byte allocation with 3447104 free bytes and 3MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
	at android.content.res.Resources.createFromResourceStream(Resources.java:2988)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2708)
	at android.content.res.Resources.loadDrawable(Resources.java:2606)
	at android.content.res.VivoResources.loadDrawable(VivoResources.java:220)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
	at android.widget.ImageView.<init>(ImageView.java:152)
	at android.widget.ImageView.<init>(ImageView.java:140)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:74)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:69)
	at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:199)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:119)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1563)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1614)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:749)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:880)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:843)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:521)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
	at org.schabi.newpipe.databinding.ChannelHeaderBinding.inflate(ChannelHeaderBinding.java:90)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.getListHeaderSupplier(ChannelFragment.java:154)
	at org.schabi.newpipe.fragments.list.BaseListFragment.initViews(BaseListFragment.java:238)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.initViews(BaseListInfoFragment.java:51)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:67)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:42)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.onViewCreated(ChannelFragment.java:131)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5619)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 6.0.1

### Affected device model

Vivo y53 1606

**Comment by litetex** [comment] 2022-07-02 18:54
Duplicate of e.g. #8307

TL;DR
Your device runs out of memory.

**Closed by litetex** 2022-07-02 18:54 UTC
Labels: bug
