### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by haistakaavittukaikkisaatana** [TeamNewPipe/NewPipe#2541] opened 2019-08-18 21:46 UTC
I wish I could make the video to fill the entire screen by using zoom for example, right now it leaves the black bars on the both side of the video. This would be handy especially when watching 1440p or higher videos.

**Comment by Stypox** [comment] 2019-08-18 21:57
Duplicate of #1757

**Closed by Stypox** 2019-08-18 21:57 UTC
