### ISSUE TITLE
[Feature Request] Option to limit cache size

### ISSUE THREAD

**Issue by DanGLES3** [TeamNewPipe/NewPipe#1576] opened 2018-08-03 19:17 UTC
Some devices have very low storage and newpipe's cache can reach upwards of 100mb,it would be nice if we either could manually set cache size or atleast reduce the current cache size

**Comment by theScrabi** [comment] 2018-08-08 15:08
Yea sounds reasonable.

**Comment by mhmdanas** [comment] 2021-04-15 20:31
Duplicate of #697.

**Closed by mhmdanas** 2021-04-15 20:31 UTC
Labels: enhancement
