### ISSUE TITLE
socks5 proxy?

### ISSUE THREAD

**Issue by ydqsbfsyi** [TeamNewPipe/NewPipe#8625] opened 2022-07-14 08:20 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I know this request has been brought up several times, like #992, but that's long time ago and most of those topics had been closed. I'd like to bring it up again - there has been no such function in similar apps  (youtube related) before , until recently SmartTube Next added http/socks5 settings, which runs superb. Please consider this in future version.

### Why do you want this feature?

bypass blockage in some countries.

**Comment by mhmdanas** [comment] 2022-07-14 09:41
If you know that an existing issue is open for this, please don't open another one. Most of these topics have been closed precisely for the same reason this one will be closed, that it's a duplicate of #992.

> Please consider this in future version.

Everybody is welcome to submit a PR for this.

**Closed by mhmdanas** 2022-07-14 09:41 UTC
Labels: enhancement
