### ISSUE TITLE
Make full screen bottum

### ISSUE THREAD

**Issue by Wicoler** [TeamNewPipe/NewPipe#6159] opened 2021-04-24 17:28 UTC
Hi, i use newpipe a lot and youtube has full screen bottum that makes the video full screen

Newpipe dosent have that

Why it is good?
Some times the sensors dosent function as well and i cant full screen
Also there is this stuff called sensor off in android that stops it from full screen and this will really help me 

When the phone is on the floor or not picked up and your too lazy to flip it its good
Thx if u add it love ya newpipe thx.

**Comment by mhmdanas** [comment] 2021-04-24 17:30
Duplicate of #4478. Also, please don't remove the template when opening an issue.

**Closed by mhmdanas** 2021-04-24 17:30 UTC
Labels: enhancement

**Comment by Wicoler** [comment] 2021-04-25 13:26
Ok sorry i wont remove it anymore
