### ISSUE TITLE
stuck recaptcha after solving

### ISSUE THREAD

**Issue by baraa272** [TeamNewPipe/NewPipe#2896] opened 2019-12-27 19:49 UTC
- [✅] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ✅] I checked if the issue/feature exists in the latest version.
- [ ✅] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
Hi staff 
I would like to report a problem about the new version of newpipe 0.18 
Well after clicking at any video inside the app , recaptcha Window open , I check the captcha but after submitting I'm stuck at white screen without anything
If I go back I return to main screen of the app 
Here are screenshoot 
![Screenshot_20191227-214019](https://user-images.githubusercontent.com/32843097/71530484-ddabd500-28e1-11ea-9d61-e8c7dbef5e86.png)
My device is : sm-g935F galaxy s7 edge running nougat 7.0

**Comment by TobiGr** [comment] 2019-12-27 20:03
In case you run into this again, can you please record it and post the video here? I cannot reproduce this.

**Comment by baraa272** [comment] 2019-12-27 20:06
Will do just a minute

**Comment by baraa272** [comment] 2019-12-27 20:46
[2019_12_27_22_38_18.zip](https://github.com/TeamNewPipe/NewPipe/files/4006220/2019_12_27_22_38_18.zip)

**Comment by Stypox** [comment] 2020-01-05 12:17
@baraa272 what happens if you click "Submit"?

**Comment by Stypox** [comment] 2020-01-27 21:10
Could you test this apk? The reCAPTCHA activity is shown, the user can resolve the reCAPTCHA (or follow the instructions, or do whatever they want), and then press back or "Done" to exit.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4119347/app-debug.zip)
@baraa272

**Comment by Stypox** [comment] 2020-02-09 10:53
Fixed by #3035 (I accidentally mentioned #2986 instead of #2896)

**Closed by Stypox** 2020-02-09 10:53 UTC
Labels: bug, more info needed
