### ISSUE TITLE
Ability to download certain portions of a video

### ISSUE THREAD

**Issue by Lucipo** [TeamNewPipe/NewPipe#5693] opened 2021-02-23 22:03 UTC
It would definetly be a super useful feature to be able to basically trim/specify two points in a video to download audio from (like 0:05 to 1:30 in a song with 30 seconds of outro/silence)

Reason: NewPipe can download straight from YouTube, but if you were to download music it most often has intros, outros, long periods of silence, and sometimes anti-copyright-detection techniques. This would save a lot of time/using other applications to trim audio instead and it feels like something a YouTube Downloader would need.

**Comment by yoshimo** [comment] 2021-02-23 22:10
This would be nicely extended with splitting based on chapter marks and timestamps from the description.

**Comment by mhmdanas** [comment] 2021-02-24 05:00
Duplicate of #4122.

**Closed by mhmdanas** 2021-02-24 05:00 UTC
