### ISSUE TITLE
Chronological order for subscriptions tab

### ISSUE THREAD

**Issue by Tetsumaki** [TeamNewPipe/NewPipe#885] opened 2017-12-01 00:29 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

Hello,
The videos are not in chronological order in the subscriptions tab and news.
Example : https://i.imgur.com/tVKVGzV.png

**Comment by coffeemakr** [comment] 2017-12-01 10:14
Seems to be a duplicate of #739.

**Closed** 2017-12-01 15:00 UTC
