### ISSUE TITLE
App crashes when playing videos

### ISSUE THREAD

**Issue by teddong9281** [TeamNewPipe/NewPipe#2764] opened 2019-10-27 12:06 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I cannot play any video or audio as the app crashes. Moreover I have cleared data and cache and also uninstalled and reinstalled the apk but still I can't use newpipe. Its's not newpipe but other youtube alternatives are crashing. MAYBE, YouTube changed their setup.Please fix it as soon as you can. Currently I am using version 17.1 if this helps.

**Comment by Stypox** [comment] 2019-10-27 14:43
Thank you for the issue :-)

Please provide a bug report, so that we can analyze where the problem lies

**Comment by rhodwulf** [comment] 2019-10-27 15:47
Same problem, in my case show the next error:

{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=Ph83CpeYWlI",
   "content_language": "GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.17.3",
   "os": "Linux Android 6.0 - 23",
   "time": "2019-10-27 15:45",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getErrorMessage(YoutubeStreamExtractor.java:578)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerConfig(YoutubeStreamExtractor.java:666)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:645)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)\n\tat java.lang.Thread.run(Thread.java:833)\n"
   ],
   "user_comment": ""
}

**Comment by TobiGr** [comment] 2019-10-27 22:19
@teddong9281 please install 0.17.3 and tell us if the bus still exists

**Comment by fabiano-araujo** [comment] 2019-10-28 12:41
This problem seems to be with the newpipe extractor TeamNewPipe/NewPipeExtractor#208 is related to recaptcha

**Comment by rhodwulf** [comment] 2019-10-28 12:51
@TobiGr i have 0.17.3 and the problem persists.

**Comment by teddong9281** [comment] 2019-10-28 13:36
Installed version 17.4, the problem persists. And I have reported the bug through newpipe's bug report email and so i was not bothered to provide it here. But the problem is same for me as provided by @rhodwulf .

**Comment by rhodwulf** [comment] 2019-10-29 04:27
New Pipe is working again. Thanks!!!

**Comment by Stypox** [comment] 2019-10-29 06:18
@rhodwulf we didn't do anything...

**Comment by rhodwulf** [comment] 2019-10-29 12:49
hahahahaha, wth!?. What was the problem!?.

**Comment by teddong9281** [comment] 2019-10-29 12:55
Unfortunately the problem hasn't been solved for me. Though I have seen in the last issue that someone from Bangladesh is also suffering the same problem. Could this mean the problem is arisen regionally?

**Comment by teddong9281** [comment] 2019-10-29 13:12
Update: I can play video while using a vpn. It's nice that I can use newpipe but browsing using a vpn is a pain due to low speed. Would love if the problem is resolved.

**Comment by Stypox** [comment] 2019-11-01 11:46
Duplicate of #2737

**Closed by Stypox** 2019-11-01 11:46 UTC
