### ISSUE TITLE
Player also scrolling when we scroll comments

### ISSUE THREAD

**Issue by renjithrs123** [TeamNewPipe/NewPipe#6214] opened 2021-05-01 10:07 UTC
If we scroll the comments, or description or related videos, the played video also scrolling upwards and disappearing from the screen.
The original YouTube app or it's webpage don't arising this kind of situation. I love newPipe but I'm still not using the app due to this issue.
We cannot watch the video and read the comments simultaneously on our busy day to day life.

**Comment by mhmdanas** [comment] 2021-05-01 10:54
Duplicate of #4484. Also, please don't remove the template when opening an issue.

**Closed by mhmdanas** 2021-05-01 10:54 UTC
Labels: enhancement
