### ISSUE TITLE
[feature request] have a subscriptions folder / organization 

### ISSUE THREAD

**Issue by AwesomelyHumble** [TeamNewPipe/NewPipe#5592] opened 2021-02-15 09:52 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?

I know there is an organization for channel groups and it shows the latest videos from those channels, but I often like to go into a channel and watch older videos, or just browse. I have far too many subscriptions and it makes finding a specific channel difficult. 

I would like to request to have a similar format of organization that the channel groups has, but also for the subscriptions. I can click "all" to see all the channels I subscribe to, or click a custom subscription group / folder to see all channels within that folder, then I can click and browse a specific channel from there to see all their videos. Thank you!

**Comment by JCU0** [comment] 2021-02-15 10:24
It should be useful. When you enter a channel group, a list of channels (subscriptions) that are included into this group, may appear on top just before a currently implemented feed. A list of channels (maybe with collapse button), then a list of videos.

**Comment by litetex** [comment] 2022-03-23 19:21
Duplicate of #3388

**Closed by litetex** 2022-03-23 19:21 UTC
Labels: enhancement
