### ISSUE TITLE
Mute videos or at least the popup player

### ISSUE THREAD

**Issue by Offerel** [TeamNewPipe/NewPipe#2932] opened 2020-01-08 10:41 UTC
Is there a way/feature to mute either the whole NewPipe app (seperate from other apps) or at least the popup player? Reason for this question is, that i want to preview a video from other apps like reddit in NewPipe or its popup player but with muted sound, but i dont want to mute the media volume for all the other apps. Is that possible somehow?

**Comment by Stypox** [comment] 2020-01-08 14:31
Duplicate of #2876

**Closed by Stypox** 2020-01-08 14:31 UTC
