### ISSUE TITLE
Live quality selector still has problems

### ISSUE THREAD

**Issue by justanidea** [TeamNewPipe/NewPipe#1312] opened 2018-04-14 10:04 UTC
Since the last fix - that the quality chooser increase automatically the quality of the live if possible - its quite better (it works !) but I encountered a new issue :  the quality is set to maximum, so it pauses to load each half of second... So maybe choosing manually the quality could help, finally :)

**Comment by Stypox** [comment] 2020-04-20 07:53
Duplicate of #1239

**Closed by Stypox** 2020-04-20 07:53 UTC
Labels: enhancement
