### ISSUE TITLE
Add video playback does not play in full screen mode 

### ISSUE THREAD

**Issue by pizzaHar** [TeamNewPipe/NewPipe#2588] opened 2019-09-01 10:31 UTC
When a video is played, the fullscreen display comes immediately. But would like to play just like the original youtube app. You can also play video without the display doing anything. So you can read side comments.

**Comment by Stypox** [comment] 2019-09-01 10:41
Duplicate of #1200

**Closed by Stypox** 2019-09-01 10:41 UTC
