### ISSUE TITLE
can't open any video in new update

### ISSUE THREAD

**Issue by fdciabdul** [TeamNewPipe/NewPipe#2766] opened 2019-10-27 22:50 UTC
![Screenshot_2019-10-28-05-49-54-99](https://user-images.githubusercontent.com/31664438/67643161-d484a300-f946-11e9-99b4-a4ec2e99dba1.png)

**Comment by TobiGr** [comment] 2019-10-27 22:52
what country are you in?

**Comment by fdciabdul** [comment] 2019-10-27 23:52
Indonesia sir

**Comment by TobiGr** [comment] 2019-10-28 00:20
Okay, thanks. I cannot reproduce this. In this case, I need to see what YouTube content you receive. Please download, unzip and install this [app-debug.apk](khttps://github.com/TeamNewPipe/NewPipe/files/3692594/app-debug.apk.zip). When you run into this error again, please do not take a screenshot, but scroll down to the bottom, enable "append page content ..." and tap on the copy button. After that plese paste the text from your clipboard here.

**Comment by gkeegan** [comment] 2019-10-28 02:08
@TobiGr I think you forgot to add the apk? Or maybe it just isn't showing for me.

**Comment by TobiGr** [comment] 2019-10-28 07:16
Thanks for the heads up. There was a k before https:// which made GitHub not recognise the url.

**Comment by fabiano-araujo** [comment] 2019-10-28 12:39
This problem seems to be with the newpipe extractor https://github.com/TeamNewPipe/NewPipeExtractor/issues/208 is related to recaptcha

**Comment by fdciabdul** [comment] 2019-10-29 23:03
> Okay, thanks. I cannot reproduce this. In this case, I need to see what YouTube content you receive. Please download, unzip and install this [app-debug.apk](https://github.com/TeamNewPipe/NewPipe/files/3692594/app-debug.apk.zip). When you run into this error again, please do not take a screenshot, but scroll down to the bottom, enable "append page content ..." and tap on the copy button. After that plese paste the text from your clipboard here.

i was email you before , nothing response from you

**Comment by Stypox** [comment] 2019-11-01 11:50
Related / duplicate: #2737

**Comment by Stypox** [comment] 2020-01-27 21:12
Fixed in 0.18.2

**Comment by Stypox** [comment] 2020-01-27 21:13
@shafiusy about the reCAPTCHA: could you test this apk? The reCAPTCHA activity is shown, the user can resolve the reCAPTCHA (or follow the instructions, or do whatever they want), and then press back or "Done" to exit.
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4119347/app-debug.zip)

**Closed by Stypox** 2020-01-27 21:12 UTC
Labels: bug, requires extractor change, youtube
