### ISSUE TITLE
App crash while playing video

### ISSUE THREAD

**Issue by bloatware99** [TeamNewPipe/NewPipe#6368] opened 2021-05-25 05:18 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by TiA4f8R** [comment] 2021-05-25 16:16
We cannot help you with the information you provide. I think it can be a duplicate of #6342. Can you elaborate better and fill properly the bug report template, please? Thank you!

**Comment by mhmdanas** [comment] 2021-06-13 09:54
@bloatware99 we can't help you if you don't give us any info. I'm closing this issue for now, so please fill your template properly and make a comment when done so I can re-open this. Thanks!

**Closed by mhmdanas** 2021-06-13 09:54 UTC
Labels: bug, more info needed, user-ignored-template-instructions
