### ISSUE TITLE
[Feature request] View all Public playlists made by a YouTube channel while accessing that channel feed and show the playlists by categories.

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5629] opened 2021-02-18 10:03 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by mhmdanas** [comment] 2021-02-18 10:56
Duplicate of #5203. Also, please fill out the template properly when opening an issue.

**Closed by mhmdanas** 2021-02-18 10:56 UTC
Labels: enhancement
