### ISSUE TITLE
Add the option to download all videos of a Playlist 

### ISSUE THREAD

**Issue by AlertSubject** [TeamNewPipe/NewPipe#7270] opened 2021-10-17 19:09 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
Add an option to download all videos in a Playlist at once

#### Why do you want this feature?
I got Playlist with videos that I want to save but I definitely don't want to download every single video on its own.
A play all button already exists, so a download all button would be a nice addition

This also improves the user experience for people who keep music in playlists using newpipe

**Comment by SameenAhnaf** [comment] 2021-10-17 19:37
Duplicate of #1236.

**Closed** 2021-10-18 12:04 UTC
Labels: enhancement
