### ISSUE TITLE
Private Mode

### ISSUE THREAD

**Issue by mityax** [TeamNewPipe/NewPipe#4999] opened 2020-11-24 21:28 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I'd really appreciate a "private mode" feature in NewPipe, just like e.g. firefox has one. This feature should be easily toggleable (only one to two taps), so it can be used to temporarily disable recording of watch and search history.

#### How will you/everyone benefit from this feature?

This feature would be awesome as it gives more privacy at ease and eliminates the need of going to settings each time or deleting history manually.
Also, it should be really easy to implement, i think.

**Comment by HTSamurai** [comment] 2020-11-26 08:54
Hi, I know how to do this. First go to the NewPipe settings, then go to History and cache. Turn on or off watch/search history. It won't delete your history unless you clear your history.

**Comment by Lurux** [comment] 2020-11-26 12:04
> Hi, I know how to do this. First go to the NewPipe settings, then go to History and cache. Turn on or off watch/search history. It won't delete your history unless you clear your history.

True, but that's a bit cumbersome. Maybe a toggle in the overflow menu would do the trick ?

**Comment by mityax** [comment] 2020-11-27 08:42
> Hi, I know how to do this. First go to the NewPipe settings, then go to History and cache. Turn on or off watch/search history. It won't delete your history unless you clear your history.

Yeah, thats actually what I ment with "the need of going to settings each time". But just as @Lurux I think this is too much effort, making it really annoying if you just want to privately view one or two videos.

**Comment by Lurux** [comment] 2020-11-27 12:09
> Yeah, that's actually what I ment with "the need of going to settings each time". But just as @Lurux I think this is too much effort, making it really annoying if you just want to privately view one or two videos.

I would note though, since Newpipe is really privacy friendly I don't usually feel the need to disable this option. If I don't want a video in my history, I'll just delete it afterwards. I don't really know why I'd want to do that, though.

**Comment by Stypox** [comment] 2021-08-30 13:58
Duplicate of #2338

**Closed by Stypox** 2021-08-30 13:58 UTC
Labels: enhancement, privacy & data protection
