### ISSUE TITLE
Bug + fix : cannot save modifications to a playlist

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [TeamNewPipe/NewPipe#3434] opened 2020-04-14 09:38 UTC
Hi,
I send a bug report today but I figured I might as well post it here, especially because I found a quick workaround.

Basically : when editing a playlist (i e removing a video or reordering them), if I pressed the back arrow to go back to another menu the app would diplay an error and not save my changes.

I put the error log below.

what fixed it for me was to clear cache of the app.

`{
"user_action": "requested feed",
"request": "Loading feed",
"content_language": "FR",
"service": "none",
"package": "org.schabi.newpipe",
"version": "0.19.2",
"os": "Linux Android 9 - 28",
"time": "2020-04-14 07:31",
"exceptions": [
"org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https:\/\/www.youtube.com\/channel\/UC9ZMT1-Ka3d24dAYJzMcJBA\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:220)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:63)\n\tat io.reactivex.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:113)\n\tat io.reactivex.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)\n\tat io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeFeedExtractor.getId(YoutubeFeedExtractor.java:53)\n\tat org.schabi.newpipe.extractor.feed.FeedInfo.getInfo(FeedInfo.java:39)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getFeedInfoFallbackToChannelInfo$6(ExtractorHelper.java:149)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$ugdV6CfeDCyyO_ocIIpHyBlriuE.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle.subscribeActual(MaybeSwitchIfEmptySingle.java:45)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.Single.blockingGet(Single.java:2699)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:210)\n\t... 11 more\n"
],
"user_comment": "happens every time i delete a video from my playlist"
}`

**Comment by thiswillbeyourgithub** [comment] 2020-04-18 10:16
Well no it keeps happenning over and over, emptying cache seems to fix for less than 5 edition of the playlist.

**Comment by Stypox** [comment] 2020-04-20 07:37
*Please **follow the issue template** when creating an issue, don't just delete everything!* 
Use the [Incredible Error Report to Markdown Converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) before sending bug reports, as you should have been told when creating the issue.

This is a duplicate of #3313, to fix just unsubscribe from https://www.youtube.com/channel/UC9ZMT1-Ka3d24dAYJzMcJBA

**Closed by Stypox** 2020-04-20 07:37 UTC
Labels: bug
