### ISSUE TITLE
A video that is already on the list should not be added to the playlist

### ISSUE THREAD

**Issue by cehnemdark** [TeamNewPipe/NewPipe#5891] opened 2021-03-23 14:22 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Expected behavior

When we add a new video to the list, if there is a video, it should not be added, instead, "This video already exists, do you want to add it again?" can give a warning

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by SameenAhnaf** [comment] 2021-03-23 15:11
Duplicate of #5827. Please avoid opening issues over the problem over and over again. When you open more issues, you are taking more time from us which developers could use for further improvement.

**Comment by cehnemdark** [comment] 2021-03-23 15:13
> Duplicate of #5827. Please avoid opening issues over the problem over and over again. When you open more issues, you are taking more time from us which developers could use for further improvement.

No, not a copy or anything

**Comment by SameenAhnaf** [comment] 2021-03-23 15:29
Sorry, it is a copy of #4186.

**Comment by cehnemdark** [comment] 2021-03-23 15:39
> Sorry, it is a copy of #4186.

(I didn't have time to add the feature of "Remove Duplicated", sorry.)

^ That's really funny, well, I thought the developer knew software. I guess this will be my last post, let me see how to turn this off

**Comment by mhmdanas** [comment] 2021-03-23 15:49
@cehnemdark as @SameenAhnaf says, this is a duplicate of #4186 (this means that that issue requests the same thing, so one of the issues will have to be closed). A PR was already opened to add this feature: https://github.com/TeamNewPipe/NewPipe/pull/5334. Note that closing an issue doesn't mean a feature won't be added. 

@SameenAhnaf I think you can cut @cehnemdark some slack. If I recall correctly, they don't speak English, so they have to use a translator. I think that's enough to justify something like this.

**Closed by mhmdanas** 2021-03-23 15:49 UTC
Labels: bug

**Comment by mhmdanas** [comment] 2021-03-23 15:56
> The funny thing is that a few months have passed since he did not keep his promise, saying "I don't have time".

Please understand that all of us here are doing this work unpaid. Nobody is forced to work on anything or entitled to force others to do so.

**Comment by SameenAhnaf** [comment] 2021-03-23 16:24
@mhmdanas I never meant to hurt anyone. Anyway, thanks for your opinion. I will keep in mind from next time.

@cehnemdark Extremely sorry if you feel offended by any of my activities.

**Comment by cehnemdark** [comment] 2021-03-23 17:04
> @mhmdanas I never meant to hurt anyone. Anyway, thanks for your opinion. I will keep in mind from next time.
> 
> @cehnemdark Extremely sorry if you feel offended by any of my activities.

No, I was not disturbed, thanks to you, I learned a few more things.
