### ISSUE TITLE
When maximizing from mini player the video restarts

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#7527] opened 2021-12-12 06:40 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Find any video
2. Seek anywhere within the duration of said video
3. Go into mini player mode
4. Go back to fullscreen

### Actual behavior

The video restarts all over again no matter how far you are into the video.

### Expected behavior

To be able to resume back into the video seamlessly without any restarts

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung S10

**Comment by krtfwd** [comment] 2021-12-13 16:49
android 11 miui 12.5.3 and/or versions before it )
poco x3 nfc

Yes Same problem for some time / it started with one of the new ui/extractor updates ( i think several updates ago ) and has been broken/not fixed ever since

**Comment by Flam3z** [comment] 2021-12-14 20:04
Is there anyway this issue can be bumped or put on a higher priority as this has been happening for a few versions now and with this new version it has just gotten worse.

**Comment by TippyLion28** [comment] 2021-12-14 20:06
> Is there anyway this issue can be bumped or put on a higher priority as this has been happening for a few versions now and with this new version it has just gotten worse.

+1 for this. Latest version is unusable for playlists. Every time the app state changes it breaks playback, either starting from the beginning, starting from the wrong place or slipping to the wrong video.

**Comment by drewsat** [comment] 2021-12-15 02:01
I have this issue too

**Comment by mhmdanas** [comment] 2021-12-18 06:32
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7303.

**Closed by mhmdanas** 2021-12-18 06:32 UTC
Labels: bug
