### ISSUE TITLE
Option to add metadata to audio files

### ISSUE THREAD

**Issue by demonff1** [TeamNewPipe/NewPipe#5760] opened 2021-03-05 08:42 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I download my songs from YouTube (i.e. Newpipe). But newpipe audio files have blank metadata such as artist name, album, titles etc

#### Is your feature request related to a problem? Please describe it

It's hard to navigate my songs in my music player.

#### Additional context

It would be best if there was a option to add metadata to audio file when I was downloading a audio file. This could be implemented in this window.
![Screenshot_2021-03-05-14-36-50-043_org schabi newpipe](https://user-images.githubusercontent.com/68889858/110089462-59e05900-7dc0-11eb-9791-463a2d209523.jpg)

It's basically a mp3 editor that are available in play store.
#### How will you/everyone benefit from this feature?

•People will be benefitted who download songs from newpipe.
•Also, it would be nice if we can also edit local files as well
• People will see the uniqueness of newpipe and greater incentive to install newpipe than other competitors.

**Comment by mangoepic** [comment] 2021-03-06 10:29
Related Issues:
#4341 Add metadata while downloading files 
#5445 mp3/m4a cover pic feature request
#5736 Feature request - tagging

**Comment by mhmdanas** [comment] 2021-03-08 07:17
Duplicate of #4341. If you disagree, feel free to make a comment.

**Closed by mhmdanas** 2021-03-08 07:17 UTC
Labels: enhancement
