### ISSUE TITLE
[Suggestion] Be able to search only live streams

### ISSUE THREAD

**Issue by tuxayo** [TeamNewPipe/NewPipe#8725] opened 2022-08-02 00:15 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

In the menu to filter the search where there is "All, videos, Channels, Playlists, etc" there could be a lives/streams/live streams option.

### Why do you want this feature?

For example if searching for a group/category that does livestreams like "vtuber" "vtuber french" "hololive" "vshojo" "nijisanji"

It would make much easier to get the currents live streams of that group/category. Now it's just drowned in clips and streams archives.

### Additional information

<img src="https://user-images.githubusercontent.com/2678215/182264638-aa198510-eaf4-447a-9fcc-b7d4b9c97605.jpg" width="200" />

**Comment by opusforlife2** [comment] 2022-08-06 18:20
The "live" filter isn't in the same group as the "result type" filter (videos/channels/playlists). It's a video tag (like HD/3D/360). So this is a duplicate of #2251.

You can keep an eye on https://github.com/TeamNewPipe/NewPipeExtractor/pull/488 BTW.

**Closed by opusforlife2** 2022-08-06 18:20 UTC
Labels: enhancement
