### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lyloff** [TeamNewPipe/NewPipe#8600] opened 2022-07-10 12:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [ ] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Latest Version

### Steps to reproduce the bug

I just launched a video

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.23.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Thread.isAlive()' on a null object reference
	at us.shandian.giga.get.DownloadMission.joinForThreads(DownloadMission.java:817)
	at us.shandian.giga.get.DownloadMission.pauseThreads(DownloadMission.java:521)
	at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:363)
	at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:309)
	at us.shandian.giga.get.DownloadRunnable.run(DownloadRunnable.java:145)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Xiaomi Poco X3 Pro

**Comment by opusforlife2** [comment] 2022-07-10 19:12
Checklist isn't optional.

**Comment by litetex** [comment] 2022-07-12 17:56
Duplicate of #4008.

Please also fill out the issue properly next time.

**Closed by litetex** 2022-07-12 17:56 UTC
Labels: bug, waiting-for-author
