### ISSUE TITLE
Maximize button from popup player is not working

### ISSUE THREAD

**Issue by iamthesenate1** [TeamNewPipe/NewPipe#5797] opened 2021-03-08 21:11 UTC
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open a video.
2. Press the open in popup mode
3. Get out of the app
4. Press the maximize button.

### Actual behaviour

It doesn't do anything

### Expected behavior

It should get back to the app (main player)

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/77978836/110384072-d5aeff80-8065-11eb-843a-66e71ce19ecb.mp4

### Device info

 - Android version/Custom ROM version:7.1.2
 - Device model:Redmi Note 5A

**Comment by iamthesenate1** [comment] 2021-03-08 21:28
Alao I forgot to mention that it works only when inside the app

**Comment by mhmdanas** [comment] 2021-03-09 05:05
Duplicate of #5351.

**Closed by mhmdanas** 2021-03-09 05:05 UTC
Labels: bug
