### ISSUE TITLE
[Feature Request] Browser Extension for Sync

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [TeamNewPipe/NewPipe#2801] opened 2019-11-13 04:36 UTC
I am suggesting a browser plugin (Firefox and any other browsers of choice), which is 2way sync between newpipe and your browser, that will basically track progress, history, etc. While watching YouTube on the browser, Also allow inputting of playlists url's to sync to the NewPipe app. So it would be similar to signing into YouTube, but instead it is done through a browser plugin, requiring no need of a Google account/Sign in.

It would sync your progress of videos you are watching (How far in you are into a video)
sync watched history, search history etc.
Ability to build playlists (Add to "watch later", "add to playlist", "create new playlist", "copy playlist")
Sync subscriptions
and whatever else more.

This would be excellent for users who are constantly switching between devices, it could in theory be implemented with some kind of login feature, your something through newpipe I would assume. I'm not entirely sure the best way to do that. And then can be logged in on Newpipe on a tablet, as well as your phone, and the browser extension on your computer, and everything will be synced between one another. 

I genuinely think this would be AMAZING, for people trying to "Degoogle" (That don't want to eliminate Youtube) but enjoy newpipe, but dislike the idea of having to login to Google to sync stuff (Which Newpipe can't do anyways, also defeating the purpose of Newpipe). And allow more users into Newpipe.

**Comment by j0w0** [comment] 2019-11-19 19:54
This would be nice with [invidio.us](https://invidio.us) too, it already has a setting for importing newpipe data, it would just need to be automated

**Comment by Z3ROGRAV1TYx** [comment] 2019-11-19 20:15
@j0w0 i would prefer a plugin personally, and just let it work with both invidio.us and youtube

**Comment by Stypox** [comment] 2019-12-11 20:54
Related: #2278 #1236 #1163

**Comment by Stypox** [comment] 2019-12-11 20:56
Related: #2278 #1236 #1163
I'm closing this since it is a duplicate of #1163 and it would be better to keep all the discussion there. Please add a comment to that issue containing the same content of this one ;-)

**Closed by Stypox** 2019-12-11 20:56 UTC
