### ISSUE TITLE
Enqueueing videos from browser or youtube app resets the existing queue

### ISSUE THREAD

**Issue by altunyurt** [TeamNewPipe/NewPipe#4946] opened 2020-11-21 10:03 UTC
### Checklist

- [x] I am using the latest version - 0.20.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1 - Download and install v0.20.3
2 - Long press on some video on youtube app or browser or use share buttons
3 - Select open in external app 
4 - Select newpipe from menu 
5 - Video starts playing  (in my setup, all videos are forced to play in the background by default) 
6 - Repeat the steps 2 - 5 and the newly selected video takes over the existing queue and the player

### Actual behaviour

Enqueueing videous from browser or youtube app takes over the queue by resetting it to only the newly enqueued video. Even if there's a video already playing, the enqueued video takes over the player and the previous ones are discarded from the queue. No error or crash report is displayed. Open in newpipe popup does not contain enqueue option when the video is opened using "share button" on youtube web page  or youtube app.  

### Expected behavior

Prior versions allowed user to enqueue videos from browser or youtube app, extending the queue and they would play on their turn, without taking over the player. They did not contain enqueue option either, but  pressing "play in the background" would automatically enqueue the video by default, without disturbing the existing video play. 

### Device info

 - Android version/Custom ROM version: 7.1.1 
 - Device model: Lenovo Moto E4 plus

**Comment by vlad-mk** [comment] 2020-11-23 13:29
Same for me
- Android version: 5.5
- Device midel: Samung Tab Note 12.2

**Comment by rancidfrog** [comment] 2020-11-23 16:44
On 20.3, not yet updated to 20.4, 
this also occurs when sharing to pop-up player.

Previous versions would queue shared video, if you are watching something already; however, now it stops playing the cirrent pop-up video and plays recently shared video instead

**Comment by Pavlecom** [comment] 2020-11-26 05:30
Same for v.0.20.4 ... back to v.0.20.2 for 'fix' the problem.
'Previous versions would queue shared video.'

**Comment by shivasagarrao** [comment] 2020-11-26 18:12
When I open a video using **share** button on YouTube web page or YouTube app then if I press **back** button when NewPipe isn't in background apps it is opening YouTube app. 

![Newpipe not in background](https://user-images.githubusercontent.com/46630255/100381807-ccae9b00-303f-11eb-8dac-b855a06fccc8.gif)

When Newpipe is in background apps **back** button is opening Newpipe homepage.

![Newpipe in background](https://user-images.githubusercontent.com/46630255/100381883-04b5de00-3040-11eb-8622-b8acbe383366.gif)

Why not open NewPipe homepage when **back** button is pressed when Newpipe isn't in background apps?
I don't know whether my issue comes under this issue or not, but I'm commenting my issue on this issue because my issue also happens when I open a video using **share** button on YouTube web page or YouTube app. 

- Android version: 6.0.1

- Device model: Redmi note 3

**Comment by vlad-mk** [comment] 2020-12-14 21:27
still same bug for 0.20.6.
Enqueueing  a new item resets the existing queue.
The last version where it works correct is  0.20.2

**Comment by feelinskii** [comment] 2020-12-28 17:55
Version 0.20.8 not working too
Android versions: 5.0.2; 6.0.1; 7.1.2
Device modelsf: Teclast Air x98; Sony Xperia z3c; Meizu M6 Note

**Comment by Stypox** [comment] 2021-01-15 15:23
This is expected. Just open video info and then long press on background/popup.

**Comment by pymen** [comment] 2021-01-15 15:29
@Stypox the issue appears in the following case

when open the link from Youtube  > open with NewPipe -> it can NOT be enqueued, -> instead it just replaces the current video playing in NewPipe

Can the ticket be re-opened?

**Comment by Stypox** [comment] 2021-01-15 17:45
Just press on "Show info" and then you can enqueue (by looking at this video: https://github.com/TeamNewPipe/NewPipe/issues/4946#issuecomment-734431716)

**Comment by Stypox** [comment] 2021-01-15 17:45
If the chooser menu does not show up you need to set it to "Always ask" in the settings

**Comment by Bruceforce** [comment] 2021-01-15 18:03
@Stypox 

I always share from youtube to newpipe and choose pop-up player to play videos. In older versions of newpipe this enqueued the item automatically. Now it don't see a way to achieve the same behavior as in the old version. Is also don't see a "show info" in the newpipe sharing dialogue.

**Comment by Stypox** [comment] 2021-01-15 18:48
>  I also don't see a "show info" in the newpipe sharing dialogue.

This only happens when there is nothing playing: in such case the "play" item is shown and "play in the background" just plays the single item in the background (without replacing any queue since there is nothing playing). On the other hand, if something's already playing, the "show info" item is shown, allowing to do what I explained above.
If you never see "show info", even when something's playing, then please post a screenshot with some way to reproduce consistently.

**Comment by TobiGr** [comment] 2021-01-15 18:50
We should add an "enqueue" option when there is something running in the background / popup

**Comment by Stypox** [comment] 2021-01-15 18:54
@TobiGr then this is duplicate of #4779

**Closed by Stypox** 2021-01-15 18:54 UTC
Labels: enhancement, good first issue

**Comment by Bruceforce** [comment] 2021-01-16 08:42
@Stypox Just to make sure that I understand this correctly. In the attached screen I'm playing a video in pop-up mode (the one below the newpipe dialogue with the guy in front of the mirror). Then is share another video with newpipe and get the dialogue you see on the screenshot. If I got you right there should be an "Info" option instead?

![Screenshot_2021-01-16-09-37-28-398_org schabi newpipe](https://user-images.githubusercontent.com/20187589/104807383-fb92f300-57de-11eb-9e85-1b97d82afdf2.jpg)

**Comment by Stypox** [comment] 2021-01-16 08:49
@Bruceforce as I said, if there is not already something playing, "Video-Player" appears instead of "Show info". But if you press on that button you will be brought to the video details fragment. And in any case, if there is not something already playing, you wouldn't need enqueue buttons.

**Comment by rancidfrog** [comment] 2021-08-20 08:27
@Stypox 
**_BUG_  ** :
Show info button only appears when 2 videos are enqueued.
If there is only ONE video playing, show info does not appear.

**Comment by rancidfrog** [comment] 2021-08-20 08:27
BUG:
Show info button only appears when 2 videos are enqueued.
If there is only ONE video playing, show info does not appear.
