### ISSUE TITLE
Notifications feature 

### ISSUE THREAD

**Issue by deep0808** [TeamNewPipe/NewPipe#6002] opened 2021-04-04 15:45 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by deep0808** [comment] 2021-04-04 15:50
Just an humble request if you can ad Notification features like I get notifications every time subscribed channel post new videos just like YouTube. I appreciate your work. Keep going.

**Comment by TiA4f8R** [comment] 2021-04-04 15:54
Duplicate of #1086. See the corresponding PR: #2335.

**Closed by TiA4f8R** 2021-04-04 15:54 UTC
Labels: enhancement

**Comment by deep0808** [comment] 2021-04-04 16:09
This is dead the debug apk don't work plus its two year old and there is no further information about new version. If you guys cannot add notifications feature just refuse my request I don't mind at all because it might be hard to implement. And I'm not a programmer otherwise I would have figured out it by myself.
