### ISSUE TITLE
Don't save status video visualized

### ISSUE THREAD

**Issue by frandarko** [TeamNewPipe/NewPipe#7246] opened 2021-10-14 14:47 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any video
2. Press on middle progress bar video
3. Close app
4. Go historical videos and find the last video played
5. Play on
6. Video plays from beginning instead in the middle
7.

### Actual behavior

Historical videos not work

### Expected behavior

The video plays from the last status played

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment] 2021-10-15 04:37
Duplicate of #7236.

**Closed by mhmdanas** 2021-10-15 04:37 UTC
Labels: bug
