### ISSUE TITLE
If newpipe crashes the position of playing video is not saved.

### ISSUE THREAD

**Issue by Master2050** [TeamNewPipe/NewPipe#9102] opened 2022-10-10 22:38 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0 stable

### Steps to reproduce the bug

1. Start playing a video in background until half the total duration
2. Either force close newpipe or cause the app to crash
3. Upon entering the app again the position will not be saved and you will see the video marked at 00:00

### Expected behavior

The player should retain the position and start playing where you left after restarting the app.

### Actual behavior

The position of played video resets

### Affected Android/Custom ROM version

Color OS v6.0(android 9)

### Affected device model

Oppo Realme 1

**Comment by tsiflimagas** [comment] 2022-10-10 23:22
Duplicate of #8358.

**Closed** 2022-10-11 00:07 UTC
Labels: bug, needs triage
