### ISSUE TITLE
add reply column on comment

### ISSUE THREAD

**Issue by atuolol** [TeamNewPipe/NewPipe#4793] opened 2020-11-04 06:22 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
feature to show "reply" from each comment.

#### Is your feature request related to a problem? Please describe it
i can view the comment but not with the reply

#### Additional context
help view the reply column

#### How will you/everyone benefit from this feature?
with this feature people don't need to open the video in the browser to view the reply.

**Comment by opusforlife2** [comment] 2020-11-04 06:33
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

Duplicate of #2277. O_O

**Closed by opusforlife2** 2020-11-04 06:33 UTC
Labels: enhancement

**Comment by atuolol** [comment] 2020-11-04 11:50
> > I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
> 
> Duplicate of #2277. O_O

I hope you consider it. it's a pain to have to go back and forth to the browser just to see the reply field 😭

hey, how do i know if the title is like that, it is not the same as my title 🙄

**Comment by opusforlife2** [comment] 2020-11-04 13:11
I literally searched for "comment replies" and got the linked issue in one go. Anyway, if you make a little more effort when checking for duplicates, it saves everyone time.
