### ISSUE TITLE
Add option to sort comments by "top comments" & "newest first" along with total comment count.

### ISSUE THREAD

**Issue by newuser-tec** [TeamNewPipe/NewPipe#8497] opened 2022-06-10 04:04 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

An option to sort comments by "top comments" & "newest first" as seen on the website or the youtube app will make the user experience even more richer.

### Why do you want this feature?

This feature is already available on desktop website and youtube app and helps in finding latest feedback on a video.

**Comment by SameenAhnaf** [comment] 2022-06-10 08:06
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3115 & https://github.com/TeamNewPipe/NewPipe/issues/7191 respectively

**Closed** 2022-06-11 19:02 UTC
Labels: enhancement
