### ISSUE TITLE
Wanted to say... 

### ISSUE THREAD

**Issue by c0derb0i** [TeamNewPipe/NewPipe#8578] opened 2022-07-05 21:27 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Latest

### Steps to reproduce the bug

I feel you may not get this enough but thank you for creating such a great free app! You're awesome!

Thanks NewPipe Team!

**Comment by AudricV** [comment] 2022-07-05 22:19
Thank you for the kind words, we really appreciate them! Glad you like the app!

Closing this issue, as of course, it's not a bug :)

You may also join our IRC channel to talk directly to us in the future.

By the way, that's a special first GitHub issue :D

**Closed by AudricV** 2022-07-05 22:19 UTC
Labels: bug
