### ISSUE TITLE
Download video and burn in the captions

### ISSUE THREAD

**Issue by Donkey-Doug** [TeamNewPipe/NewPipe#8622] opened 2022-07-13 13:05 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When downloading a video, have an option to burn in the captions.

### Why do you want this feature?

I downloaded the captions seperately using newpipe, but playing that on android is quite tricky.

**Comment by SameenAhnaf** [comment] 2022-07-13 13:34
Duplicate of #5534

**Closed** 2022-07-13 15:23 UTC
Labels: enhancement
