### ISSUE TITLE
External Video Player : Can you guys add a standalone button for external video player by default 

### ISSUE THREAD

**Issue by sonuydv** [TeamNewPipe/NewPipe#8588] opened 2022-07-07 04:55 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Currently there is no button available for external video player , and once you enable it from settings you can no longer play videos in newpipe.
Can you guys add a a standalone button for external video player on video play screen alongwith like/dislike button.

### Why do you want this feature?

It's not quite handy to use external video player . I like to use video player like Kofi, MX player .  though there is an option to use external video player but that has some restriction. First you have to enable it from settings , and once you enable it you can no longer play video in newpipe itself rather you get only option to play externally. second there is no standalone button available for playing video on external video player.

**Comment by mhmdanas** [comment] 2022-07-10 16:33
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3642.

**Closed by mhmdanas** 2022-07-10 16:33 UTC
Labels: enhancement
