### ISSUE TITLE
F-Droid Release Schedule 

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#3991] opened 2020-07-28 15:11 UTC
#### Describe the feature you want

The recent issue was solved in 0.19.7 (F-Droid is 0.19.5) and really thankful for the team for such super fast solution! What I would like to know is when does the newer version gets released on F-Droid?

#### Is your feature request related to a problem? Please describe it

Not related to a problem.

#### Additional context

No need for it.

#### How will you/everyone benefit from this feature?

Pushing the update here always seem faster than F-Droid for obvious reasons, which is as we know is a go-to place for an average user with no idea about GitHub. I do understand that we can simply come over here and get the update. But as you know the signatures won't match and one has to reinstall the app from scratch. I can be completely wrong and do correct me but my guess would be most users who use F-Droid won't bother with GitHub. Of course, it's also true that many or most know about GitHub as an alternate source of download as handful of people consider such open source alternative.

**Comment by wb9688** [comment] 2020-07-28 16:05
>What I would like to know is when does the newer version gets released on F-Droid?

Whenever F-Droid builds it successfully. For v0.19.6, we initially had some trouble with reproducible builds, which we fixed, but then F-Droid coincidentally failed to build it every time (due to a long standing bug there).

**Comment by opusforlife2** [comment] 2020-07-28 17:59
Ohohohoho. Reproducible builds. *rubs hands together*

The day when we can install the Github version over the F-Droid version will be a glorious day, indeed. No more waiting a week or more for hot fixes. “ψ(｀∇´)ψ

**Comment by Stypox** [comment] 2020-07-28 18:02
@opusforlife2 you can already use the selfhosted NewPipe repository (see here: https://newpipe.schabi.org/blog/announcement/f-droid/pinned/f-droid-repo/)

**Comment by opusforlife2** [comment] 2020-07-28 18:04
O_O

**Comment by cbiere** [comment] 2020-07-28 20:41
> @opusforlife2 you can already use the selfhosted NewPipe repository (see here: https://newpipe.schabi.org/blog/announcement/f-droid/pinned/f-droid-repo/)

Thanks. I had to change the repo link to https manually. Otherwise, F-Droid ignored it and marked it as unverified.

**Comment by blshkv** [comment] 2020-07-29 09:14
can somebody help me out here? I have added newPipe repo and upgraded the app, however it is still shows v 0.19.6. What's wrong?

**Comment by baturayp** [comment] 2020-07-29 09:21
> Thanks. I had to change the repo link to https manually. Otherwise, F-Droid ignored it and marked it as unverified.

It's a little bit tricky to add new f-droid repos in general :/ 
What worked for me is: Manually adding the link below as a new repo; but make sure there is no space or newline left after the fingerprint and address
`https://archive.newpipe.net/fdroid/repo/?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501`

**Comment by db4rne** [comment] 2020-07-29 09:24
> can somebody help me out here? I have added newPipe repo and upgraded the app, however it is still shows v 0.19.6. What's wrong?

just remove and then reinstall the app

**Closed** 2020-08-25 19:36 UTC
Labels: question
