### ISSUE TITLE
Startpage tabs don't update correctly after settings import

### ISSUE THREAD

**Issue by vkay94** [TeamNewPipe/NewPipe#4381] opened 2020-10-04 13:50 UTC
### Version
- v0.20.0-RC7

### Steps to reproduce the bug

- Create a backup in which you change the order of tabs (Settings -> Content -> Content of main page)
- Export your settings
- Delete app data (clean)
- Import your previously created backup

### Expected behavior
The content of the fragments should update accordingly to the tabs after the automated restart

### Actual behaviour
The fragments content aren't updated. You see the "old" fragment (content =/= tab icon/toolbar title) (watch the video for better explanation).

### Screenshots/Screen recordings
Screen recording: https://streamable.com/e/2mqxe0

**Comment by opusforlife2** [comment] 2020-10-04 13:52
Duplicate of #3312. O_O

**Closed by opusforlife2** 2020-10-04 13:52 UTC
Labels: bug
