### ISSUE TITLE
"What's new" content not in chronological order

### ISSUE THREAD

**Issue by gloschtla** [TeamNewPipe/NewPipe#1629] opened 2018-08-27 10:29 UTC
I have subscribed to several youtube channels, and I have chosen "What's new" as my start page. 
But the latest uploaded videos are not shown on top of its list. Also the list of downloaded content is not sorted chronologically.

**Comment by TobiGr** [comment] 2018-08-27 12:43
Duplicate of #739

**Closed by TobiGr** 2018-08-27 12:43 UTC
Labels: duplicate
