### ISSUE TITLE
Mp3 Audio Download (Feature request)

### ISSUE THREAD

**Issue by Doctor-blob** [TeamNewPipe/NewPipe#6199] opened 2021-04-29 10:41 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

(I've seen multiple issues opened on this subject but none of them have filled out the form so that's why I opened this one.)

#### Describe the feature you want

I would like an option to download audio from a video in the .mp3 format.
So when you click download on the video an option to download it as an .mp3 file is there.

#### Is your feature request related to a problem? Please describe it

I use newpipe to download my music and put it on an mp3 player but that player doesn't support m4a or oppus and it's really irritating to convert everything before putting it on the player.

#### How will you/everyone benefit from this feature?

For me(and hopefully for other people it will make downloading and using the download feature way more easy.

**Comment by SameenAhnaf** [comment] 2021-04-29 10:54
Duplicate of #507.

**Comment by Doctor-blob** [comment] 2021-04-29 10:56
sorry I'll close the issue @SameenAhnaf

**Closed** 2021-04-29 10:56 UTC
Labels: enhancement
