### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by wutongskype** [TeamNewPipe/NewPipe#6862] opened 2021-08-07 03:55 UTC
玛暖馨, [07.08.21 11:52]
## Exception
* User Action: requested kiosk
* Request: Start loading: https://www.youtube.com/feed/trending
* Content Country: CN
* Content Language: zh-CN
* App Language: zh_CN
* Service: YouTube
* Version: 0.21.8
* OS: Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get Trending name
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.getName(YoutubeTrendingExtractor.java:87)
 at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:70)
 at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:58)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:184)
 at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$NbG7JFGg0N9HK-3exJNRB9r_hYY.call(Unknown Source:4)
 at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
 at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
 at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)

</details>
<hr>

**Comment by mhmdanas** [comment] 2021-08-07 12:47
Duplicate of #6839. See https://github.com/TeamNewPipe/NewPipe/issues/6839#issuecomment-892564080 for a workaround.

**Closed by mhmdanas** 2021-08-07 12:47 UTC
Labels: bug
