### ISSUE TITLE
Add option "Mark *ALL* as Watched" for entries in What's New tab

### ISSUE THREAD

**Issue by jaredbarez** [TeamNewPipe/NewPipe#8433] opened 2022-05-24 07:17 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Please add the requested option either in popup menu for a single entry or in a tab header, in order to make all feed entries marked as watched.

### Why do you want this feature?

To get rid of bloated (i.e. big) What's new tab list that accumulates over time or when importing my subscriptions. This feature would keep the feed tidy (or not, if user chooses that).

### Additional information

Thanks.

**Comment by SameenAhnaf** [comment] 2022-05-25 22:03
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7231

**Closed** 2022-05-28 18:26 UTC
Labels: enhancement, duplicate
