### ISSUE TITLE
Add support for using custom Invidio.us instance

### ISSUE THREAD

**Issue by jahway603** [TeamNewPipe/NewPipe#8280] opened 2022-04-22 20:41 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The app's look/behaviour would change to incorporate a user entering a custom Invidio.us instance

### Why do you want this feature?

This feature would add privacy if a user decided to enter & use a custom Invidio.us instance

### Additional information

N/A

**Comment by SameenAhnaf** [comment] 2022-04-22 23:57
Duplicate of https://github.com/TeamNewPipe/NewPipeExtractor/issues/427

Also, already under progress. Check the APK in https://github.com/TeamNewPipe/NewPipe/pull/8220

**Comment by jahway603** [comment] 2022-04-23 04:37
Thanks @SameenAhnaf for sharing that info with me. I still can't find issue 427 when I search the already filed issues for "Invidious". The testing APK in #8220 looks exciting too.

**Comment by TiA4f8R** [comment] 2022-04-23 10:16
> I still can't find issue 427 when I search the already filed issues for "Invidious".

Because that in the extractor repository and not in the app repository, because of this template instruction:

> - [x] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).

which is pretty clear: any new service (in which Invidious is included) request goes to the extractor repository. Follow properly template instructions the next time you open an issue, please! Thank you.

Closing as a duplicate of TeamNewPipe/NewPipeExtractor#427.

P.S.: remember that the service is Invidious and not invidio.us, which was the main instance when Omar Roth was developing Invidious.

**Closed by TiA4f8R** 2022-04-23 10:16 UTC
Labels: enhancement
