### ISSUE TITLE
Video are not loading 

### ISSUE THREAD

**Issue by Gul7333** [TeamNewPipe/NewPipe#8882] opened 2022-08-25 11:14 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

23.2

### Steps to reproduce the bug

Open New pipe..
Thumbnail are showing...
But when you click... video doesn't load or remain in loading.. but doesn't play

### Expected behavior

Videos should play buy they are loading 
<img alt="Screenshot_20220825-091435" src="https://user-images.githubusercontent.com/106809902/186649972-28772818-edf0-45ef-ab96-332a3054069e.png" height=600 />
<img alt="Screenshot_20220825-091429" src="https://user-images.githubusercontent.com/106809902/186650183-14b4fb11-5b45-4608-a8d7-db176b090344.png" height=600 />
![Uploading Screenshot_20220825-091435.png…]()

### Affected Android/Custom ROM version

Android 10

### Affected device model

Tecno pova LD7

**Comment by Midi-In** [comment] 2022-08-25 11:22
Nothing is loading for me either
Newpipe 0.23.2, Android 11, Xiaomi Redmi Note 11

**Comment by figo2001** [comment] 2022-08-25 11:23
Same as Redmi note 9

**Comment by msanguineti** [comment] 2022-08-25 11:24
> Same issue here

Also, I've tried to downgrade to 0.23.1 because i was certain it was working, but it behaves exactly the same. Maybe Google has changed few things and your page parsing is broken.

**Comment by TobiGr** [comment] 2022-08-25 11:25
Duplicate of #8876
A new version will be released soon.

**Closed by TobiGr** 2022-08-25 11:25 UTC
Labels: bug, needs triage
