### ISSUE TITLE
Youtube Live Streams

### ISSUE THREAD

**Issue by GurharinderSingh** [TeamNewPipe/NewPipe#8031] opened 2022-03-14 07:48 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Open any livestream

### Expected behavior

live streams to have review option (while it is live), and to be able to change its quality

### Actual behavior

# issue is not unique and i falsely marked it unique, i know there are already 30 ish issues on similar topics
As i understand from reading the answers to some older issues, youtube changed the way how it dealt live streams, and so now review action is basically useless, and i ideally would get 30 seconds of review from the current time (in most ideal case, i would like to review it as i would in youtube app), but on many videos i am not even getting 30 seconds, and just get a room of 2-3 seconds, which due to natural lag from youtube's end, makes the viewing impossible, also, as expected, the live stream should have played at the resolution of the last video, but on my end it always jumps up to maximum quality (1080p) which my network realistically can not stably support, and hence there is buffer, but i would rather watch it at lower qualities (like 144p). And please dont mark it is Duplicate, as i searched, almost all livestream related issues were marked to earlier posts for duplicates, but those posts have not been checked upon for quiet some time (like 1 year in case of #1239, even the version they are discussing is 0.20.x) and maybe a recent issue post would help

### Affected Android/Custom ROM version

Android 11 (non rooted)

### Affected device model

Vivo Y12(1904)

**Comment by opusforlife2** [comment] 2022-03-14 13:42
> and maybe a recent issue post would help

Since the issue you linked is still open, a comment helps more than a duplicate issue. Did you not see the PR linked in #1239 in the right-hand pane? You can test it and provide feedback.

> And please dont mark it is Duplicate

I've explained it above, so...
.
.
.
Duplicate of #1239

**Closed** 2022-03-14 13:42 UTC
Labels: bug
