### ISSUE TITLE
Implement Pinch to zoom to enlarge videos

### ISSUE THREAD

**Issue by topcaser** [TeamNewPipe/NewPipe#7028] opened 2021-08-31 03:05 UTC
Videos have typically a format of 16:9. A pinch to zoom gesture could enlarge videos a bit to fit into 20:9 format ändern allows to use the entire screen like YouTube does.

**Comment by SameenAhnaf** [comment] 2021-08-31 05:20
Duplicate of #3181.

**Closed** 2021-08-31 13:15 UTC
