### ISSUE TITLE
Youtuber's public Playlists

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#3770] opened 2020-06-09 23:59 UTC
There are youtubers who create their own public playlists to better organize their upload history. Of course on newpipe there is no tab when you view a channel. I don't know if it was a bug or missing feature.

**Comment by B0pol** [comment] 2020-06-10 07:17
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2414

**Closed by B0pol** 2020-06-10 07:17 UTC
Labels: bug
