### ISSUE TITLE
[Feature request] "Account" system

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#6069] opened 2021-04-13 12:03 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

A nice thing that could be added is a sort of profile system that allows you to create a completely seperate profile with different subscriptions, playlists and history, similarly to FreeTube.

#### Is your feature request related to a problem? Please describe it

Let's say I need to subscribe to some maths channels on YouTube. They'd come up in my otherwise personal "What's new?" feed. If I had a profile named "School" (which would be completely local)and when I switch to it, I'd only see the school videos I used that profile to sub to.

#### Additional context
Lot's of *Mock-ups* for this issue
![IMG_20210413_111323](https://user-images.githubusercontent.com/71007160/114549020-6b870d00-9c58-11eb-81b8-a09bc78ee139.jpg)
![IMG_20210413_111609](https://user-images.githubusercontent.com/71007160/114549038-70e45780-9c58-11eb-803d-996e9416547d.jpg)
![IMG_20210413_111700](https://user-images.githubusercontent.com/71007160/114549057-7641a200-9c58-11eb-825f-4e88f4b1fb24.jpg)
![IMG_20210413_111912](https://user-images.githubusercontent.com/71007160/114549077-7c378300-9c58-11eb-8d0e-7fa3a0de1792.jpg)

#### How will you/everyone benefit from this feature?
People can have seperate profiles to seperate subscriptions, play/search history and playlists.

**Comment by HTSamurai** [comment] 2021-04-13 12:06
This can tie in with these three issues - #5159 #5434 #5147

**Comment by SameenAhnaf** [comment] 2021-04-13 12:38
Related: https://github.com/TeamNewPipe/NewPipe/issues/5654#issuecomment-782784218

**Comment by eadmaster** [comment] 2021-05-21 03:43
the ideal solution for me would be via a browser extension that integrated into the YT GUI, so i can easily sync subscriptions between my desktop PC and my mobiles.

**Comment by HTSamurai** [comment] 2021-06-03 10:08
> the ideal solution for me would be via a browser extension that integrates into the YT GUI, so i can easily sync subscriptions between my desktop PC and my mobiles.

Not quite what I meant.

**Comment by mhmdanas** [comment] 2021-06-28 14:15
Duplicate of #5654.

@HTSamurai note that the use case you described can be fulfilled by channel groups I believe.

**Closed by mhmdanas** 2021-06-28 14:15 UTC
Labels: enhancement
