### ISSUE TITLE
Background play crashes

### ISSUE THREAD

**Issue by celikten** [TeamNewPipe/NewPipe#7888] opened 2022-02-17 07:32 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

After v0. 21.15

### Steps to reproduce the bug

Play any video in the NewPipe
Press home button.
App crashes

### Expected behavior

NewPipe can play in background, while dealing with another application or when you press home button. 

### Actual behavior

Application crashes and the  log given below appears. 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.0
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:658)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:255)
	at android.view.View.dispatchWindowVisibilityChanged(View.java:10282)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1289)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1534)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6325)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
	at android.view.Choreographer.doFrame(Choreographer.java:619)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6111)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```
</details>
<hr>

**Comment by litetex** [comment] 2022-02-17 18:31
Let me guess... you are using a Lenovo device.

Duplicate of #7549

**Closed by litetex** 2022-02-17 18:31 UTC
Labels: bug
