### ISSUE TITLE
Add Odysee-KBRY Support

### ISSUE THREAD

**Issue by ianblas** [TeamNewPipe/NewPipe#8704] opened 2022-07-28 04:52 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add Odysee/LBRY support.
LBRY, is a blockchain-based file-sharing and payment network that powers decentralized platforms, primarily social networks and video platforms.

### Why do you want this feature?

Odysee/LBRY is a decentralized YouTube alternative. 

### Additional information

https://odysee.com/
https://lbry.com/

**Comment by SameenAhnaf** [comment] 2022-07-28 05:30
> - [ ]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.

Well, no as mentioned below.

> - [ ] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).

Odyssey is a new service. So, this issue should have been opened in Extractor repo.

>- [ ]  I made sure that there are no existing issues - open or closed - which I could contribute my information to.

Duplicate of https://github.com/TeamNewPipe/NewPipeExtractor/issues/434

**Closed** 2022-07-28 14:05 UTC
Labels: enhancement, needs triage
