### ISSUE TITLE
crash trying to download on oxygenOS Oreo

### ISSUE THREAD

**Issue by water1309** [TeamNewPipe/NewPipe#886] opened 2017-12-01 10:30 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by water1309** [comment] 2017-12-01 10:32
{
"user_action": "ui error",
"request": "App crash, UI failure",
"content_language": "en",
"service": "none",
"package": "org.schabi.newpipe",
"version": "0.11.0",
"os": "Linux Android 8.0.0 - 26",
"time": "2017-12-01 10:29",
"ip_range": "143.179.0.0",
"exceptions": [
"java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:3579)\n\tat android.app.ActivityThread.-wrap4(Unknown Source:0)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1778)\n\tat android.os.Handler.dispatchMessage(Handler.java:105)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6809)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)\nCaused by: java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable\n\tat us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:103)\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:3569)\n\t... 8 more\njava.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable\n\tat us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:103)\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:3569)\n\tat android.app.ActivityThread.-wrap4(Unknown Source:0)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1778)\n\tat android.os.Handler.dispatchMessage(Handler.java:105)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6809)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)\n"
],
"user_comment": ""
}

**Comment by delit** [comment] 2017-12-01 10:40
I have the same problem. Tried to reinstall the app but no luck.

**Comment by coffeemakr** [comment] 2017-12-01 12:01
Hi 
have you reported this issue by email? I can't find any similar issues in the logs which would help investigate this error. 
Readable stacktrace:
```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3579)
	at android.app.ActivityThread.-wrap4(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1778)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6809)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:103)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3569)
	... 8 more
java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:103)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3569)
	at android.app.ActivityThread.-wrap4(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1778)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6809)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by coffeemakr** [comment] 2017-12-01 12:11
Okay this issue is duplicate of #813 and will be fixed by the next release.
But keep in mind:
> **Please use our bug tracking system instead of pasting things here directly.**

**Closed** 2017-12-01 14:59 UTC

**Comment by water1309** [comment] 2017-12-03 17:23
Could you tell me where I can find the bug tracking system?

**Comment by theScrabi** [comment] 2017-12-03 18:00
When an error occurs you will be asked if you want to send the error report over to us.
