### ISSUE TITLE
Support to go through video in a specified time

### ISSUE THREAD

**Issue by airon90** [TeamNewPipe/NewPipe#2193] opened 2019-03-07 11:00 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I'd like that you support the possibility to go to a time in the videos just by clicking on a link.
For example, see the description of [this video](https://www.youtube.com/watch?v=Chhlus7JWyE). If you click on the links in the description the video will go through the video to the specified time. On NewPipe this is not possible to do, see screenshot below

![screenshot_20190307-115620](https://user-images.githubusercontent.com/139841/53952314-b4128a80-40d0-11e9-93df-36bef3ecfbb0.png)

**Comment by Stypox** [comment] 2019-07-16 07:40
Duplicate of #1025

**Closed** 2019-07-16 07:41 UTC
