### ISSUE TITLE
I used Imgur when it ur app crashed. 

### ISSUE THREAD

**Issue by Qreed213** [TeamNewPipe/NewPipe#7426] opened 2021-11-20 10:09 UTC
Ops the gif was to great. 
I was using Imgur so this was really bisar. 
I LOVE YOUR APP TANK You for a really good video /Music client. 
 Sry if I did something incorrect. 
GL hf. 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.schabi.newpipe/.CheckForNewAppVersion }: app is in background uid UidRecord{ccbd07d u0a313 CAC bg:+1h0m1s240ms idle change:cached procs:1 seq(0,0,0)}
 at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1736)
 at android.app.ContextImpl.startService(ContextImpl.java:1691)
 at android.content.ContextWrapper.startService(ContextWrapper.java:720)
 at org.schabi.newpipe.CheckForNewAppVersion.startNewVersionCheckService(CheckForNewAppVersion.java:258)
 at org.schabi.newpipe.MainActivity.onPostCreate(MainActivity.java:175)
 at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1434)
 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3675)
 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:58)
 at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5625)
 at android.app.ActivityThread.access$3800(ActivityThread.java:274)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:233)
 at android.app.ActivityThread.main(ActivityThread.java:8030)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-11-20 16:11
Duplicate of #7397.

**Closed by mhmdanas** 2021-11-20 16:11 UTC
