### ISSUE TITLE
crash when getting out of fullscreen

### ISSUE THREAD

**Issue by bkqtnte10** [TeamNewPipe/NewPipe#1863] opened 2018-11-03 14:49 UTC
Happens with all videos when i press the "out of fullscreen" icon.

Report:

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.14.2
* __OS:__ Linux Android 7.1.2 - 25

<details><summary><b>Crash log</b></summary><p>

```
java.lang.RuntimeException: Unable to stop activity {org.schabi.newpipe/org.schabi.newpipe.player.MainVideoPlayer}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4202)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference
	at org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)
	at org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)
	at org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1290)
	at android.app.Activity.performStop(Activity.java:6859)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4197)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference
	at org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)
	at org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)
	at org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1290)
	at android.app.Activity.performStop(Activity.java:6859)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4197)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```
</p></details>
<hr>

**Comment by Gymcap** [comment] 2018-11-03 15:56
I get the same crash by following the same steps as well as, pressing home when "Minimize on app switch" is set to popup.

**Comment by gkeegan** [comment] 2018-11-03 20:41
Duplicate of #1855 I think

**Closed** 2018-11-03 21:03 UTC
