### ISSUE TITLE
Unexpected pauses when switching player type

### ISSUE THREAD

**Issue by alexlyzhov** [TeamNewPipe/NewPipe#5016] opened 2020-11-27 13:24 UTC
### Checklist

- [x] I am using the latest version - 0.20.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start some video in NewPipe
2. Minimize NewPipe by pressing home or opening Android recent applications drawer
3. Enter NewPipe again

### Actual behaviour

When I minimize the app, the audio stops playing for like 100-600ms and then resumes. It's pretty annoying.
When I reenter the app, the same thing happens.

### Expected behavior

No pauses in the audio are expected.

### Screenshots/Screen recordings

[Recording on youtube](https://youtu.be/Y0ihnKFnIRk)

### Device info

 - Android version/Custom ROM version: latest Android 10
 - Device model: Asus ZenFone 5Z

**Comment by alexlyzhov** [comment] 2020-11-27 13:27
It's certainly not connected to my internet speeds, all the other youtube apps never have this issue

**Comment by alexlyzhov** [comment] 2020-11-27 13:29
All the battery-saving power management options are disabled on my phone

**Comment by vkay94** [comment] 2020-11-27 14:05
This is expected because the player type is changed. because the player is destroyed and recreated again. You should have noticed it too when you minimized it. It's just longer during entering because the details screen takes more time to create than the background player for example.

So it's basically no bug but designed like that.

**Comment by alexlyzhov** [comment] 2020-11-27 14:27
Is it a good design element? Would it be difficult to make the playback persistent like on other youtube apps?

**Comment by vkay94** [comment] 2020-11-27 16:26
Hmm, I checked it. I though if you leave the app while the details are visible the player changes to the background player but it isn't. So you're right, there is basically no necessary to reload it.

@Stypox Is it always needed to re-assign the PlaybackManager and set the  in this specific case when the play queue entries are equal?
([Resume case](https://github.com/TeamNewPipe/NewPipe/blob/06b7072240c93879ed63272b57145eec779c9851/app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java#L1262-L1265) -> [useVideoSource](https://github.com/TeamNewPipe/NewPipe/blob/06b7072240c93879ed63272b57145eec779c9851/app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java#L1546-L1559) -> [reload](https://github.com/TeamNewPipe/NewPipe/blob/f0ca9164322a434eb7b48f9bb3ce5525bc8754d2/app/src/main/java/org/schabi/newpipe/player/BasePlayer.java#L1302-L1310))

**Comment by avently** [comment] 2020-11-29 19:45
@vkay94 the pause is just a process that reload the stream with video enabled or disabled based on current situation (the app in background - video disabled, in foreground - video enabled). So `reload` triggers track selection.

**Comment by Oizaro** [comment] 2020-12-25 11:11
> @vkay94 the pause is just a process that reload the stream with video enabled or disabled based on current situation (the app in background - video disabled, in foreground - video enabled). So `reload` triggers track selection.

This behaviour doesn't hapoen on Vanced.

**Comment by Coderdude112** [comment] 2021-03-19 02:49
Is there any update to this? I am still having this issue a lot.

**Comment by Stypox** [comment] 2021-03-19 09:25
> This behaviour doesn't happen on Vanced.

@Oizaro probably vanced just keeps playing the video in the background, instead of switching to audio

> I am still having this issue a lot.

**Comment by Stypox** [comment] 2021-03-19 09:25
> This behaviour doesn't happen on Vanced.

@Oizaro probably vanced just keeps playing the video in the background, instead of switching to audio. I don't know if there is any way to improve this.

**Comment by Coderdude112** [comment] 2021-03-19 12:55
What are the draw backs of this? If the video keeps playing without pauses isn't that good?

Idk how switching to a different player works but, would there be a way to implement something like using the same video player for the rest of the playing video and then switching to another video player when the video is done? That way the pause for the switch is hidden a little better and less obnoxious.

**Comment by Coderdude112** [comment] 2021-03-19 14:47
Honestly how much would it use tho. I used vanced for a long time without significant battery loss...
Even adding it as an option would be nice

**Comment by Stypox** [comment] 2021-03-19 15:14
Then maybe Vanced is able to change the playing stream seamlessly, but NewPipe is not and none of us has any idea how that could be achieved

**Comment by Coderdude112** [comment] 2021-03-19 15:22
Wouldn't my previous suggestion work tho? Also how did vanced edit the original YT app

**Comment by avently** [comment] 2021-03-19 15:42
YouTube app uses another type of video streams unsupported by newpipe as far as i know. it allows to disable video without stopping audio

**Comment by Logarithmus** [comment] 2021-07-26 08:42
> YouTube app uses another type of video streams unsupported by newpipe as far as i know. it allows to disable video without stopping audio

What another type? Do you mean HLS or separated video & audio?

**Comment by Logarithmus** [comment] 2021-07-26 08:49
This issue is super annoying BTW. I think that we can just use 2 separate players for video and audio and when going to backround mode just stop the video player. When going to picture-in-picture mode, we should continue playing the old video stream downscaled. And then asynchronously fetch the stream with smaller resolution and smoothly transition to it. YouTube Vanced and official app does that, and if NewPipe would support that too, then it would be the best YouTube app ever.

**Comment by Coderdude112** [comment] 2021-07-26 15:28
This sounds great! I would really love to see this implemented.

**Comment by IHateTheProgrammingClass** [comment] 2021-08-11 22:03
+1 please it's been months I'm going insane.

**Comment by Darkmaster006** [comment] 2021-08-11 23:44
This also happens when I click in 'Settings' and when I go back to the video from 'Settings' (this all inside the app).
EDIT1: This also happens if you press 'Downloads' or 'About'.
EDIT2: Very weird, if I choose 'open in pop-up mode' and I don't give it any permission to open it in pop-up mode, it will open it in background mode and there'll be no freezing. Any ideas?
EDIT3: This also occurs when I turn on and off the screen, even with the 'trick' of EDIT2. This also happens if the screen turns off by itself.

Hope this can be fixed.

**Comment by Logarithmus** [comment] 2021-08-11 23:48
@Darkmaster006 I want to fix it so much, I know a bit of Kotlin & Java Android development, but unfortunately won't have free time for that any time soon ☹️

**Comment by opusforlife2** [comment] 2021-08-14 04:17
See #2863 for earlier discussion around this. As stated there, this will have to wait until DASH is implemented in Newpipe. You are welcome to help test the DASH PR (#6537) for bugs so that it can be merged faster. :)

There are 2 scenarios here: 1st is navigating within the app, and the 2nd is going outside the app (even phone locking counts as this). Possible solutions:

1. Video stream keeps playing in the background when user opens menus inside Newpipe, because in most cases, they will shortly exit the menu. Toast: "Video still playing in background. Switch to audio to save data." -> user can choose to switch to audio manually before browsing menus in the app.
2. Going outside the app:
  - When the user switches away from the app, the video stream should keep playing in the background until the popup/audio stream(s) is/are loaded in another player instance, then seamlessly hand off playback and pause the first player instance. (Taking the 2 player instances idea from what avently said in the last paragraph of https://github.com/TeamNewPipe/NewPipe/issues/2863#issuecomment-658771865.)
  - When the user switches back to the app, the paused video stream can jump to the timestamp the audio/popup stream is at and resume. I don't know if there is a way to do this step seamlessly.
  - If user quickly switches back to Newpipe before 2nd player has fully loaded, just keep playing the video stream and close the 2nd player instance.

Seamless switching may require the video resolution of the main/popup players to be the same.

**Comment by IHateTheProgrammingClass** [comment] 2021-09-17 09:57
I would just like to add that this happens both ways. Leaving a stream with video and entering it.

Ok so if we fetch audio and video at the same time then suddenly we only need audio then we can drop the video stream but the audio should continue streaming seamlessly. There should not be a stutter in that case.

If we enter the video stream then it would be understandable because suddenly we need to fetch the video stream.

I think there should be a toggle in settings that would allow fetching a video stream in the background thus "wasting" more data. But the switch would be seamless. People - who actually know how to do this - should check what exactly happens when switching. Btw this could also be tied into the mobile internet toggle so it does not waste data.

**Comment by Coderdude112** [comment] 2021-10-21 07:15
So, according to @Stypox we don't currently have an idea of how to implement this functionality. 

After a little searchin online i found this doc page from Google, and while avoiding their products is kinda the reason behind NewPipe, they do give full examples for how to implement seamless transition between the full-screen video player and a PiP video player and back. Found here: https://developer.android.com/guide/topics/ui/picture-in-picture

Would it be possible to implement this in addition to the concept of dropping the video stream, but keeping the audio stream alive when the user wants to go from video to audio. This would reduce the need for the pause to only when the user is going from audio only to audio and video.

**Comment by opusforlife2** [comment] 2021-10-23 01:40
> I do but it skips. It shows a little time glass icon when switching for a fourth of a second before unpausing again.
Using calyxos.

@peepopoggers That only happens when you switch player type. Are you absolutely sure you're not tapping the thumbnail and opening the main player? Even if it has the headphone icon, it's not actually playing in the background. The icon is misleading and needs to be changed.

Does it happen to you on Youtube as well? Playing in background, switching to another app, and noticing a pause?

**Comment by peepopoggers** [comment] 2021-10-23 01:54
@opusforlife2 Alright that seems to work, I thought the headphone icon meant background. That sure is confusing and I think it needs to be changed.

**Comment by IHateTheProgrammingClass** [comment] 2021-11-12 13:03
@opusforlife2 mpv does this as well. Maybe NP uses the same player as mpv and the problem is with that instead?

**Comment by opusforlife2** [comment] 2021-11-12 16:03
@IHateTheProgrammingClass Why speculate on all that when you have a perfectly good PR right above you waiting to be tested? Check it out, it's awesome!

**Comment by IHateTheProgrammingClass** [comment] 2021-12-17 21:35
@opusforlife2 Sorry I'm kinda retarded.

**Closed** 2022-02-26 15:16 UTC
Labels: bug, player
