### ISSUE TITLE
Flip screen in full screen

### ISSUE THREAD

**Issue by JBABN** [TeamNewPipe/NewPipe#8402] opened 2022-05-15 18:29 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When you are in fullscreen,have a button that flips it horizontally or vertically. It's very comfortable.
I get the idea from samsung internet''s video player for android, at least the older versions

### Why do you want this feature?

It's very comfortable, other ways of flipping it are more cumbersome

**Comment by SameenAhnaf** [comment] 2022-05-15 19:22
Duplicate of #4500

**Comment by JBABN** [comment] 2022-05-15 19:24
Sorry, I searched but missed it

**Closed** 2022-05-16 19:44 UTC
Labels: enhancement
