### ISSUE TITLE
background problem

### ISSUE THREAD

**Issue by muhmd10** [TeamNewPipe/NewPipe#7539] opened 2021-12-14 07:16 UTC
He shared 1 video while sharing a video (sharing sound in the background) from Youtube application to Newpipe.  
Please add 10 - 20 video sharing features ?? 
Can you fix it when the new version is out ??   

it is in this version.  no problem adding 5 - 10 videos..    NewPipe v0.20.2 👍

**Comment by litetex** [comment] 2021-12-14 18:37
Closing this issue:
1. I don't understand what you want; The title "says" problem but the issue is annotated with "enhancement"
2. The template is missing
3. Multiple features in one issue
4. Completely outdated version

**Closed** 2021-12-14 18:37 UTC
Labels: enhancement, template-missing
