### ISSUE TITLE
can't seek back live videos

### ISSUE THREAD

**Issue by floss-birdy** [TeamNewPipe/NewPipe#3454] opened 2020-04-18 18:33 UTC
### Version : 

- 0.19.2

### Steps to reproduce the bug
now live streams in youtube can only be watched live. 
i've tested this on two different stock android devices.

### Expected behavior
earlier i was able to watch content upto 4hours from live.

### Actual behaviour
i can only watch a video as live only cant seek back upto 4 hours , which was possible on earlier 

### Screenshots/Screen recordings

![Screenshot_20200418-234432](https://user-images.githubusercontent.com/53141172/79658690-21985200-81d1-11ea-8005-223f312b1259.jpg)
![Screenshot_20200418-234522](https://user-images.githubusercontent.com/53141172/79658701-22c97f00-81d1-11ea-859f-c9157a1169c9.jpg)

**Comment by B0pol** [comment] 2020-04-18 19:03
I can confirm.

For clarification:
[This stream](https://www.youtube.com/watch?v=aH2TvmjxIFM) is blocking back seeking on YouTube.
[This one isn't](https://www.youtube.com/watch?v=9Auq9mYxFEE) isn't (I picked two live up for a while).

I seems that both now have the behaviour of streams blocking back seeking in NewPipe, and we should have the same thing as on YouTube: if the live stream blocks seeking back, we shouldn't be able to go 30s back (that's issue #1634), and if the live stream allows seeking back, let people seeking back (that's the point of this issue).

**Comment by floss-birdy** [comment] 2020-04-18 19:25
yeah i agree @B0pol  we should be able to seek back on live streams if it is available. It was possible to seek back on live streams till a few a few days ago( I was heavily using that) . now  its not possible on any live streams at all :(

**Comment by Stypox** [comment] 2020-04-27 08:25
Duplicate of #1634, let's keep the discussion there

**Closed by Stypox** 2020-04-27 08:25 UTC
Labels: bug
