### ISSUE TITLE
Repeat videos doesn't load on a playlist

### ISSUE THREAD

**Issue by randomusername45** [TeamNewPipe/NewPipe#6336] opened 2021-05-20 18:17 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

When I make the playlist regardless of the organization once the repeat video shows up the video loads indefinitely
(I'm not sure what I said made sense so here is an example)
If the organization of the playlist is 'Video A, Video A' and then play the playlist the 1st Video A will play, and after it finishes the 2nd Video A will load indefinitely 
If the organization of the playlist is 'Video A, Video B, Video A' then Video A and B will play but the 2nd Video A will load indefinitely 

### Expected behavior

The playlist should load the repeat video

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: moto g7 supra

**Comment by randacco** [comment] 2021-06-04 05:20
I can confirm this behavior happening on another device as well.

### Checklist
- [x] I am using the latest version - 0.21.3

### Steps to reproduce the bug
1. Tap to search any video (for example, "[Original Playstation 2 Intro](https://www.youtube.com/watch?v=B9WAa1GyK60)")
2. Access the desired video, tap in the "Add To" button -> "New Playlist", name it as you want (for example, "Test_Playlist"), and press "Create"
3. Search another video (for example, "[Gamecube Startup Logo (HQ)](https://www.youtube.com/watch?v=ksZh-FHuKpk)")
4. Access the desired video, tap in the "Add To" button, and select the playlist created previously (i.e. "Test_Playlist")
5. In the same video, tap once again in the "Add To" button, and re-select the same playlist created previously
6. Access the playlist (i.e. "Test_Playlist") and you will see that the playlist has the ordered format "Video A -> Video B -> Video B"
7. Reproduce the playlist using any of the available options (i.e. "Background", "Play All", and "Popup")

### Actual behaviour
In the ordered format described above (i.e. "Video A -> Video B -> Video B"), "Video A" will reproduce fine, "Video B" in the first time will reproduce fine too, but the second time that "Video B" has to reproduce, "Video B" will not reproduce and, if the playlist has another video after the last "Video B" (e.g. "Video A -> Video B -> Video B -> Video C"), the reproduction will stay stopped indefinitely

### Expected behavior
Even if a playlist has a video inserted more than one time (i.e. "Video A -> Video B -> Video B"), the reproduction should happen normally, without any interruption

### Screenshots/Screen recordings
(Sorry, the screen recording has no audio, but the issue is noticeable even without that)
https://user-images.githubusercontent.com/82992579/120749249-9cf2bb00-c4da-11eb-8b30-44cb3282d51a.mp4

### Device info
 - Android version: 6.0.1 (unmodified, official Samsung's Android)
 - Device model: Samsung Galaxy J5 Duos

**Comment by ShinyLuxray** [comment] 2021-06-15 00:34
I commented on a similar issue, #6122 I think is the same bug.

**Comment by Stypox** [comment] 2021-07-31 09:08
This was a duplicate and is fixed by #6712

**Closed by Stypox** 2021-07-31 09:08 UTC
Labels: bug
