### ISSUE TITLE
GUI crash when rotating phone whilst loading vidoes

### ISSUE THREAD

**Issue by Thomasmandrel** [TeamNewPipe/NewPipe#6133] opened 2021-04-21 11:08 UTC
In the video demonstrate it with one video but I was able to replicate it with lots of them. Some videos loaded much quicker, so the chances of getting a bad timing were low.

https://user-images.githubusercontent.com/82944343/115544089-51e16780-a2e1-11eb-86e0-da225372bb49.mp4

**Comment by sauravrao637** [comment] 2021-04-21 17:47
Hi!
Thanks for reporting the issue :)
It will be helpful if you can also share the error logs on crashing, it will really  help us to analyze and fix the issue .
Also, if you can follow the template that will be great too ;)

**Comment by Thomasmandrel** [comment] 2021-04-21 21:19
{"user_action":"ui error","request":"ACRA report","content_language":"en-AU","content_country":"AU","app_language":"en_AU","service":"none","package":"org.schabi.newpipe","version":"0.21.1","os":"Linux Android 11 - 30","time":"2021-04-19 20:01","exceptions":["java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)\n\tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3956)\n\tat android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5926)\n\tat android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5832)\n\tat android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)\n\tat android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)\n\tat android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:246)\n\tat android.app.ActivityThread.main(ActivityThread.java:8443)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)\nCaused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor\n\tat androidx.fragment.app.Fragment.instantiate(Fragment.java:563)\n\tat androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)\n\tat androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)\n\tat androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)\n\tat androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)\n\tat androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)\n\tat androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)\n\tat org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:55)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:279)\n\tat androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)\n\tat androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)\n\tat androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)\n\tat androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)\n\tat androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)\n\tat androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)\n\tat androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)\n\tat androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)\n\tat androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)\n\tat androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)\n\tat androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)\n\tat org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:139)\n\tat android.app.Activity.performCreate(Activity.java:8183)\n\tat android.app.Activity.performCreate(Activity.java:8167)\n\tat android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3753)\n\t... 13 more\nCaused by: java.lang.NoSuchMethodException: org.schabi.newpipe.fragments.EmptyFragment.<init> []\n\tat java.lang.Class.getConstructor0(Class.java:2332)\n\tat java.lang.Class.getConstructor(Class.java:1728)\n\tat androidx.fragment.app.Fragment.instantiate(Fragment.java:548)\n\t... 37 more\n"],"user_comment":""} 


Sorry I couldn't find the template. Where is it?

**Comment by Nothing4You** [comment] 2021-04-21 21:34
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ en-DE
* __App Language:__ en_DE
* __Service:__ none
* __Version:__ 0.21.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
	at org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:55)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:279)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:139)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	... 13 more
Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.fragments.EmptyFragment.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
	... 37 more

```
</details>
<hr>

**Comment by Thomasmandrel** [comment] 2021-04-21 21:36
Ok thanks. Will do that in future. Sorry for the inconvenience.

**Comment by Nothing4You** [comment] 2021-04-21 21:38
mine is not the actual issue template, just the "copy formatted report" button from the crash message.

**Comment by Nothing4You** [comment] 2021-04-21 21:38
I'm not sure if this may be fixed by #5976 already? the trace there was a bit different though

**Comment by TiA4f8R** [comment] 2021-04-21 21:41
Thanks for your report! Steps to reproduce are pretty the same as in #5941 and the crash origin produced by its stacktrace is the same (`Could not find fragment constructor`). Closing as a duplicate of this issue.

@Thomasmandrel If you want the issue templates and if you are using a GitHub client which doesn't support issue templates, here is the link of they: [bug report](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md), [feature request](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/feature_request.md). If you are using the GitHub website, it should be shown when you open [a new issue](https://github.com/TeamNewPipe/NewPipe/issues/new/choose).

(Sorry for my English.)

**Closed by TiA4f8R** 2021-04-21 21:41 UTC

**Comment by Thomasmandrel** [comment] 2021-04-21 21:42
All good. Thanks for the templates!
