### ISSUE TITLE
Randomly play playlist

### ISSUE THREAD

**Issue by p-hofer** [TeamNewPipe/NewPipe#7938] opened 2022-02-23 21:27 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

There should be a button to play a playlist in random order.

### Why do you want this feature?

In order to not start the playlist with the same song everytime.

**Comment by SameenAhnaf** [comment] 2022-02-23 22:36
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6625

**Comment by litetex** [comment] 2022-02-25 16:33
> There should be a button to play a playlist in random order.

Already exists.

**Closed by litetex** 2022-02-25 16:33 UTC
Labels: enhancement
