### ISSUE TITLE
Add a button to change the voice of the video

### ISSUE THREAD

**Issue by Thevoid30** [TeamNewPipe/NewPipe#10143] opened 2023-06-06 09:21 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

A subtitle-style menu, with the ability to switch between audio tracks of different languages

### Why do you want this feature?

Recently youtube implemented in some videos to change the audio to different languages by means of autogenerated voice, and sometimes automatically puts in a voice different from the original making it impossible to change it

**Comment by AudricV** [comment] 2023-06-06 09:44
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

You didn't, duplicate of #5854. Please search (better, with different keywords?) for duplicates, **especially the pinned ones**, the next time you want to open an issue. Thank you.

**Closed by AudricV** 2023-06-06 09:44 UTC
Labels: feature request, needs triage
