### ISSUE TITLE
Video+Subtitle Download Feature

### ISSUE THREAD

**Issue by mehedihasanziku** [TeamNewPipe/NewPipe#3685] opened 2020-05-30 10:10 UTC
I would like to do download at once.

Now we have to download video & subtitle separately, so what i want is trigger both at once, means a "both" option too.

It will be time saver feature. I hope it will be implement soon & still i am waiting for search day/weeks filter.

Thanks.

**Comment by Stypox** [comment] 2020-05-30 11:40
Duplicate of #2885

**Closed by Stypox** 2020-05-30 11:40 UTC
Labels: enhancement
