### ISSUE TITLE
what's new doesnt sort by new

### ISSUE THREAD

**Issue by fikrillah** [TeamNewPipe/NewPipe#2481] opened 2019-07-29 08:39 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

In the what's new tab, the videos are not shorted by time. Its seems like it doesn't shorted at all

![Capture+_2019-07-29-15-34-56](https://user-images.githubusercontent.com/48489341/62033758-e0ad7700-b216-11e9-9551-998868fe7df0.png)

**Comment by Stypox** [comment] 2019-07-29 08:52
Duplicate of #822, fixed in #2309

**Closed** 2019-07-29 08:53 UTC
