### ISSUE TITLE
Android TV - No video/black screen

### ISSUE THREAD

**Issue by bagnaram** [TeamNewPipe/NewPipe#8829] opened 2022-08-18 02:27 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.23.2

### Steps to reproduce the bug

1. Select a video and play it

### Expected behavior

The video should display in the mini-screen and in fullscreen

### Actual behavior

The video is completely black but the audio can be heard.

### Screenshots/Screen recordings

See https://github.com/TeamNewPipe/NewPipe/issues/4842
Exactly the same symptom, but it occurs every video instead of just "next video" 

### Logs

[logcat.txt](https://github.com/TeamNewPipe/NewPipe/files/9367149/logcat.txt)

### Affected Android/Custom ROM version

Android TV 11

### Affected device model

Tmobile TVision HUB v2

### Additional information

* The issue does not occur when video is set to `3gp` format and displays correctly.
* The issue occurred in previous versions of NewPipe occasionally, but now it happens for every video.

**Comment by AudricV** [comment] 2022-08-18 10:18
It seems like to be related to media tunneling, as we got several issues with media tunneling on Android TVs. Could you try to install a debug build, such as [this one](https://github.com/TeamNewPipe/NewPipe/suites/7807412689/artifacts/329503877), and see if you disable media tunneling, in the debug settings, that the issue is fixed? Thank you in advance!

**Comment by bagnaram** [comment] 2022-08-18 21:25
Thank you. Disabling media tunneling in the `debug` build solved the video playback issue for me.

**Comment by sydpy000** [comment] 2023-01-26 19:03
I also had this problem and it was also fixed by disabling media tunneling in the debug build !

What is the reason for this setting not being in the release build ? Is the issue coming from the media tunneling support on Android TV or rather the code path taken when this option is enabled ?

**Comment by hovercats** [comment] 2023-02-27 09:01
I also have this issue, but only on 1080p videos (doesnt seem to always happen though), and it doesnt appear to happen on 1080p60.
switching to 720p solves the issue for me.

I dont have an android tv per say, but the chromecast with android.

**Comment by TobiGr** [comment] 2023-05-25 13:45
Please install this [APK](https://github.com/TeamNewPipe/NewPipe/files/11565524/app-debug.zip). Go to settings > video & audio > exoplayer settings and use "disable media tunneling". Try to play a video. If the problem is solved, go to settings > debug  and use "Show device id" and post the id here so we can ensure that media tunneling is disabled by default for the device model.

**Comment by peat80** [comment] 2023-06-12 13:18
You can add my Sony A90J to that list.
Works fine with media tunneling disabled.
The device id is:

BRAVIA_VH2

**Comment by artubieski** [comment] 2023-07-08 08:21
Hey, thank you for working on this issue! disabling media tunneling worked on my android tv 8 device aswell. here is the device id:
PH7M_EU_5596

**Comment by TobiGr** [comment] 2023-07-08 11:20
@artubieski Please uninstall the test APK you installed to get the device id, install the latest APK from https://github.com/TeamNewPipe/NewPipe/pull/10122 and check if playing videos works out of the box.

**Comment by artubieski** [comment] 2023-07-08 12:19
@TobiGr all done, media tunelling was disabled per default and playing in full screen works well! thank you!

**Comment by JPluess** [comment] 2023-07-08 20:21
Hey, I compared version 25.1 and version 25.1 debug 10122. I had a hard time finding the download link for apk 10122. After testing it on my Panasonic 4KTV-JUP, I didn't find any issues that were present in the old version. I only tried the default settings without tunneling. Fullscreen and Fullscreen Autoplay are working as expected! Thank you.

**Comment by TobiGr** [comment] 2023-07-08 20:34
@JPluess Did you disable tunelling manually? If yes, please install the APk from [this comment](https://github.com/TeamNewPipe/NewPipe/issues/8829#issuecomment-1562939302) and tell me your device / model id so I can disable tunneling by default on that model.

**Comment by JPluess** [comment] 2023-07-08 21:00
Yes, I used that debug version. By default, the tunneling setting was off (grey). But maybe it was somehow not off since it worked fine. Now, I turned it on (red) and restarted the app. No issues were found. Then, I disabled it again and closed the app again. After reopening, the app crashed when I tried to go fullscreen. So, I enabled the tunneling setting again, and now it works fine. My TV model is TX-50JXW834.

**Comment by TobiGr** [comment] 2023-07-08 21:10
Is `TX-50JXW834` really the value shown when pressing the button "Show device id"? I've never seen a hyphen in a device id. They are usually replaced by underscores by Android.

**Comment by JPluess** [comment] 2023-07-08 21:12
I see, sorry for the confusion, Jupiter

**Comment by TobiGr** [comment] 2023-07-08 22:24
OK, test the latest APK from #10122 and check if everything works with default settings.

**Comment by ROBYER1** [comment] 2023-07-29 11:36
Device ID BRAVIA_ATV3_4K - fullscreen works with media tunneling disabled. Thanks for the fix!

**Closed** 2023-07-31 21:30 UTC
Labels: bug, player, device/software specific, Android TV

**Comment by j-seeley** [comment] 2023-08-07 03:51
Enabling all of the settings in the settings in the tunneling area worked in avoiding full screen crashes. However, now, when switching from small screen to full screen or from full screen to small screen, there is a black screen for 8-9 seconds and an additional 4-5 seconds where the video comes back but is frozen. During this time, the audio plays well. Tried various settings and combos of settings.. Nothing works to fix. This is with 25.2 and the latest debug apks. Using an android 6 .0 T95Z pro  tv box.
