### ISSUE TITLE
Add channel group as main page tab

### ISSUE THREAD

**Issue by peat80** [TeamNewPipe/NewPipe#8500] opened 2022-06-11 13:35 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Please add the ability to add a channel group as a main page to newpipe.
The tab(s) then should show the feed of the configured channel group.

There was once a pr that would do exactly that but it was never completed and got closed. 😔
(Feed group main-page tab #3556)

### Why do you want this feature?

The users could then fast and easily browse the feed of their configured channel groups in separate tabs.
At the moment you have to do a lot of clicks to reach them.

This is one of my most wanted newpipe features.
I offer hereby to donate 25€ to the newpipe project for a pr that brings this feature and gets merged. 💶😎

### Additional information

For good example pics of the wanted feature look at the closed pr #3556

**Comment by SameenAhnaf** [comment] 2022-06-11 18:00
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3319. You might set a [Bounty] (https://app.bountysource.com/teams/newpipe/issues) for that issue.

**Closed** 2022-06-11 18:38 UTC
Labels: enhancement

**Comment by peat80** [comment] 2022-06-11 20:09
Sorry, did not find this issue while searching.

Have set a bounty for #3319 instead.
(https://app.bountysource.com/issues/90835120-allow-adding-custom-feeds-as-tabs)

**Comment by bonniemunene** [comment] 2022-06-16 13:51
Ability to add channel group as a Tab, I would get personalized videos because I hand picked them myself. 
Tech channel group, Wellness channel group. 
Open newpipe, the content is just there. It would replace. 
It would make subscription tab more useful and personalized.

**Comment by peat80** [comment] 2022-06-16 23:04
@bonniemunene please refer, upvote or comment on

#3319

instead. This issue is closed as it is a duplicate. 😀
