### ISSUE TITLE
Background video title not showing on lockscreen and a request 

### ISSUE THREAD

**Issue by chris47368** [TeamNewPipe/NewPipe#1467] opened 2018-06-10 01:29 UTC
Hey Newpipe team,well done implementing the media controls on the lock screen that i and others suggested not too long back.

There is an issue however on the lock screen media control where the title of the background video being played is not shown.You may or may not already be aware of this issue but fixing this issue for the next version release would be great :) but im still very happy and grateful about the huge amount of progress your team are making on this app.

I also have another request.Is it possible that while saving a video as a sound file that you can give the user a way to modify the song tags such as title and artist/album .Also allowing to save a sound file at a higher bit rate would be good too.

The app can also randomly crash in the background after a while,its a minor but annoying issue but i have sent the crash logs via email anyway and hopefully its fixed soon in the later versions.

Thanks again Newpipe development team!!!

Edit:
Sorry i forgot to mention this but could you also add support for time-stamped YouTube links so when you open the link into newpipe the video automatically starts on the time within the link? I forgot to mention this while writing this post and did not want to create a second post

Thanks again Newpipe Dev team!!!

**Comment by theScrabi** [comment] 2018-06-14 19:46
Hello thank you :D. The props for the medio controllger go to @karyogamy.

> I also have another request.Is it possible that while saving a video as a sound file that you can give the user a way to modify the song tags such as title and artist/album .Also allowing to save a sound file at a higher bit rate would be good too.

There where discussions about this already, but so far no code. However please open up a new issue for this.

**Comment by karyogamy** [comment] 2018-06-15 04:28
> There is an issue however on the lock screen media control where the title of the background video being played is not shown.

Are you referring to the popup _video_ player or the background _audio_ player? 

>  the title of the background video being played is not shown

Does it show any notification or is it just the title not showing? Can you please provide a screenshot if its just the title?

> The app can also randomly crash in the background after a while,its a minor but annoying issue but i have sent the crash logs via email anyway and hopefully its fixed soon in the later versions.

Can you please provide a log or screenshot of the error here? Can't seem to find any recent crash log coming from the background player. Are you on the latest version?

**Comment by karyogamy** [comment] 2018-06-19 00:48
Thanks for the clarification.

> This issue is with the Newpipe background player as shown below:

I'll have to look into this a little more, but this might have something to do with `MediaBrowser` not implemented at the moment. It's quite strange that the metadata is passed to android wear and auto but not to notification access like in your case.

> I just posted the error report below:

This should be fixed in #1392, though it might take some more time before it is tested and merged.

**Comment by chris47368** [comment] 2018-06-19 00:59
Thanks :)

**Comment by karyogamy** [comment] 2018-06-28 19:47
An update on the missing title issue: 
Apparently this is caused by exoplayer itself, where it is not exposing the title through all the title metadata tags. Since third party widgets have multiple different choices for getting the title metadata, if it chose the wrong one out of the ones available, it will get a blank metadata. 

After updating to exoplayer 2.8.2 in #1392, this issue is fixed for the titles. But because of the above issue, the artist and album info is still going to be missing.

**Comment by Stypox** [comment] 2019-07-10 06:50
Related: #228

**Comment by Stypox** [comment] 2019-08-27 12:52
The first one is fixed (as the author says in #1568) and the second one is duplicate of #183

**Closed by Stypox** 2019-08-27 12:52 UTC
Labels: GUI, bug
