### ISSUE TITLE
Cannot play video from any channel since yeaterday

### ISSUE THREAD

**Issue by ddkk9880** [TeamNewPipe/NewPipe#3977] opened 2020-07-28 08:41 UTC
Since yesterday when I play video with the newpipe app within any channel I got this error message. No video can be played.

Could not decrypt video URL signature.

I have tried to uninstall the previous version the installed the 0.19.7 latest version but still the same problem. Cannot play video. Please help.

**Comment by wb9688** [comment] 2020-07-28 08:42
Duplicate of #3951

**Closed by wb9688** 2020-07-28 08:42 UTC
Labels: bug
