### ISSUE TITLE
Related streams are selectable although they are hidden

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#6000] opened 2021-04-04 14:15 UTC
### Checklist

- [x] I am using the latest version - 0.21.0 - dev
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ x I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a video which is not available or age-restricted. (e.g. https://m.youtube.com/watch?v=r4JWI4UDOrc)
2. Wait until the unavailable message is shown.
3. try to scroll the message by dragging it to the top: the page scrolls, although there is no visible content
4. tap below the message and report buttons on the white background. the underlying list is opened

### Expected behaviour
- The page is not scrollable
- one cannot select tap on a hidden stream info

### Additional info
most likely caused by #5148 

### Screenshots/Screen recordings
https://user-images.githubusercontent.com/17365767/113511548-8ecb0180-9560-11eb-8e37-def989e80f08.mp4

### Device info

 - Android version/Custom ROM version: API level 30
 - Device model:Pixel 3a XL emulator

**Comment by TiA4f8R** [comment] 2021-04-04 15:56
Duplicate of #5600.

**Closed by TiA4f8R** 2021-04-04 15:56 UTC
Labels: GUI, bug
