### ISSUE TITLE
Had Enough of UI Error

### ISSUE THREAD

**Issue by quinb96** [TeamNewPipe/NewPipe#10648] opened 2023-12-12 12:44 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

Can't reproduce it. Happens randomly. However this happens A LOT.

### Expected behavior

To simply just operate correctly and not spawn this error every 2 mins.

### Actual behavior

Error comes up ALL THE TIME.
I've looked up this error and their doesn't seem to be a clear answer on why this comes up for many people so much. I'm not seeing that the Newpipe team had ever answered why this happens. I apologize but I've had enough of this error now. Is there a known permanent fix for this?

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c7666df u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1988)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1933)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline1.m(R8$$SyntheticClass:0)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1091)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:749)
	at androidx.media.session.MediaButtonReceiver.onReceive(MediaButtonReceiver.java:115)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4894)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)
	... 7 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung Galaxy A13 5G

### Additional information

I've had this issue with multiple devices. I think that at least rules out it's not related to the phone model or OS.

**Comment by quinb96** [comment] 2023-12-12 12:46
This version is from Github but the F-droid version is always spawning some different error.

**Comment by AudricV** [comment] 2023-12-12 14:08
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

You didn't, your issue is a duplicate of multiple closed ones. Please search (better, with different keywords?) for duplicates and use a better title than `Had Enough of UI Error` the next time you want to open an issue. Thank you.

**Closed by AudricV** 2023-12-12 14:08 UTC
Labels: bug, needs triage

**Comment by quinb96** [comment] 2023-12-12 14:12
This answers absolutely nothing. Since you know I'm not able to find whatever issues you're referring to, why don't you link me to them instead of just responding with something that doesn't help at all. I came to you cause like I already I've been doing research on it.

**Comment by quinb96** [comment] 2023-12-12 14:12
> > - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
> 
> You didn't, your issue is a duplicate of multiple closed ones. Please search (better, with different keywords?) for duplicates and use a better title than `Had Enough of UI Error` the next time you want to open an issue. Thank you.

This answers absolutely nothing. Since you know I'm not able to find whatever issues you're referring to, why don't you link me to them instead of just responding with something that doesn't help at all. I came to you cause like I already I've been doing research on it.

**Comment by quinb96** [comment] 2023-12-12 14:14
> > - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
> 
> You didn't, your issue is a duplicate of multiple closed ones. Please search (better, with different keywords?) for duplicates and use a better title than `Had Enough of UI Error` the next time you want to open an issue. Thank you.

Like can you suggest keywords or something or just continue to provide me information that doesn't answer anything I said?? Any kind of help you can provide me at all?

**Comment by quinb96** [comment] 2023-12-12 22:36
> > Any kind of help YOU can provide me at all?
> 
> For any Github (or similar) project, always have a look at pinned issues before doing anything else. Depending on the platform, there may be pinned/stickied discussions/topics etc.

I already stated that I've done all maybe 3 times. Just read what I said. You guys keep telling me to search the closed issues foe a fix and one doesn't seem to even exist. And you guys refuse to link me to an issue that may solve my problem. There doesn't seem to be fix based on all the issues I read. I'm done with this though. There's no incentive to fix this issue. I'm just going to use LibreTube.

**Comment by quinb96** [comment] 2023-12-12 22:57
> > I already stated that I've done all maybe 3 times.
> 
> Did you read the pinned issues? You haven't stated that anywhere.

Yes and none of them are related to my problem. There's maybe 25+ people complaining about the same problem. Even Audric said this. And you guys are telling people do this and do that to fix the issue but we shouldn't have to do anything. It should just be working. I'm sorry but there's clearly a bug in that. I'm confused cause it sounds like Audric is aware that this an issue and still decided to tell me to just look at closed issues.

**Comment by quinb96** [comment] 2023-12-12 23:12
> Ok cool, you've searched the pinned issues and haven't found your problem or its solution.
> 
> Next step is to search issues using the first line of the crash log. So in this case, you'd use something like `android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException`, which you can see in your posted crash log.

I'm done. I'll leave you guys alone.
