### ISSUE TITLE
[enhancement] Add comments section

### ISSUE THREAD

**Issue by Tvax** [TeamNewPipe/NewPipe#952] opened 2018-01-03 17:48 UTC
A cool feature to add would be the comments section of a video.
It could be displayed by swiping to the right on the "Recommended videos" section beside the video player !

- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.

**Comment by TobiGr** [comment] 2018-01-03 19:06
Duplicate of #579 
@Tvax I added your idea to the comments ticket.
@theScrabi I don't have permission to close this issue.

**Comment by theScrabi** [comment] 2018-01-03 19:49
I think you need write permission to the repo if you want to close them.

**Closed** 2018-01-03 19:49 UTC
