### ISSUE TITLE
Comment time is wrong on some channels

### ISSUE THREAD

**Issue by bokeTanuki** [TeamNewPipe/NewPipe#9640] opened 2023-01-08 06:55 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Go to the [bigclivedotcom](https://www.youtube.com/@bigclivedotcom) YT channel. 
2. Click on the Aldi Ferrex 20/40 V video.
3. Look at the comment time stamp. One of them shows last week for a video just uploaded hours back. (On YT page it shows hours ago).

### Expected behavior

Comment time should not be before the video was uploaded.

### Actual behavior

<img alt="Screenshot_2023-01-08-11-55-28-970_org schabi newpipe" src="https://user-images.githubusercontent.com/122195435/211184146-988fd985-4e6b-40f5-8dbb-1d469e947cb7.jpg" width=300 />
<img alt="Screenshot_2023-01-08-11-55-46-254_org schabi newpipe" src="https://user-images.githubusercontent.com/122195435/211184149-ef618792-6825-45da-929b-0a8618b73b65.jpg" width=300 />

### Affected Android/Custom ROM version

Android 8.1 stock os

### Affected device model

Redmi 5 Plus

**Comment by AudricV** [comment] 2023-01-08 11:06
It isn't wrong, that's the same behavior on YouTube:

<img src="https://user-images.githubusercontent.com/74829229/211192568-54c8ff65-49ef-46ad-ab7c-6cb39bf8cf67.png" width="300px" alt="yt_comment_UgyK5VfEHnahcwa9E1F4AaABAg_on_video_jBfbqZHedto">

(Where `il y a 8 jours` means `8 days ago` (on UTC+1 timezone))

Likely the video was unlisted/private and shared to some people before its public release.

Closing as the extraction works as intended.

**Closed by AudricV** 2023-01-08 11:06 UTC
Labels: bug, needs triage
