### ISSUE TITLE
Option to read comments while watching a video using video player

### ISSUE THREAD

**Issue by luimu64** [TeamNewPipe/NewPipe#5384] opened 2021-01-10 16:19 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Ability to read comments while watching the video using the video player. You can currently achieve the same thing using popup player but it's inconvenient to change between them if you read comments often. Also there is a slight pause (and sometimes audio crack) when switching between the players.

#### Is your feature request related to a problem? Please describe it

There is no way to watch video using video player while reading comments.

#### Additional context

Video how it currently works and how it works in browser youtube:

https://imgur.com/a/2g8YN1j

#### How will you/everyone benefit from this feature?

Depends on how you use youtube/NewPipe, but if you read a lot of comments and are familiar how it's done in youtube this is a great, and probably simple to add, feature.

**Comment by mhmdanas** [comment] 2021-01-10 17:40
Thanks for opening an issue! I believe this is a duplicate of #4484. If you disagree, feel free to write a comment.

**Closed by mhmdanas** 2021-01-10 17:40 UTC
