### ISSUE TITLE
Please update the release soon

### ISSUE THREAD

**Issue by pc00per** [TeamNewPipe/NewPipe#8126] opened 2022-03-29 20:39 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

The last release was on 3rd march, which is almost a month ago. Why aren't we getting the next update? Newpipe use to get updates each 15 days frequently, which ain't the case now.

**Comment by peat80** [comment] 2022-03-30 08:16
Free software takes its time and is ready when is ready. You can always volunteer to speed up things. Or wait patiently...
This is not a commercial product that you paid for so you cannot demand anything.

**Comment by alaska99** [comment] 2022-03-30 15:45
WTF where this kid come from? Who thinks he is demanding that from developers who work on a voluntary basis. Child king generation! 🙄🤦‍♂️

**Comment by TiA4f8R** [comment] 2022-03-30 16:52
Please refrain of having this attitude in the future: like stated before, we are doing this on our free time, and we are quite busy with our real lifes. You cannot just ask us to make a release; it will come where it will.

The next release contains a lot of changes, which will require a lot of testing (which can be already done by testing APKs generated by the CI on pushes to the `dev` branch).

And no, we don't release an update every two weeks under normal circumstances, this happened because of critical regressions and bugs that make us releasing hotfixes between the normal releases.

Closing.

**Closed by TiA4f8R** 2022-03-30 16:52 UTC
Labels: question

**Comment by pc00per** [comment] 2022-04-02 11:25
> Free software takes its time. Wait patiently... 

I can understand the amount of hardwork it goes into here. Whether it has bugs or not, it'll atleast help users mitigate some older fixes that merged at the beginning of the month.
> This is not a commercial product that you paid for so you cannot demand anything.

I know that asking ETAs & demanding quick updates is against FOSS nature & version control principles.
I'm suggesting at least a regular CI/CD update will accompany some important features alongside bug fixes.
        There's this [buffering issue](https://github.com/TeamNewPipe/NewPipe/issues/7630)  which was reported by me that already got the fix merged by our beloved dev @karyogamy   on 21st feb. We could've been enjoyed this bug fix, if the recent update had it.😏

**Comment by opusforlife2** [comment] 2022-04-02 17:54
> Whether it has bugs or not

If you ever join a developer team, you will quickly learn to drop this opinion. What _you_ think is a minor bug may be a debilitating problem for another user. We can't be blase about letting bugs through just to release faster. Release regressions are worse than known bugs, because they break functionality for even _more_ users than before.

> Why aren't we getting the next update? Newpipe use to get updates each 15 days frequently, which ain't the case now.

Your question comes off as rude and demanding, which is why everyone responded the way they did. There is a reason for this.

Since we all communicate through text only, there is a severe lack of body language and facial expressions in this medium, which hampers conversations and causes misconceptions. To compensate for that, you need to be overly polite (even if that is not how you normally communicate) when discussing anything in FOSS projects. We don't know each other personally. Any sentence could be read in any tone, depending on the current mood of the one who is reading it: happy, sad, angry, annoyed, eager, and so on. It is on _you_ to ensure that politeness comes through in your writing. There may always be the rare person who takes offence to anything and everything, but you must still make a serious effort.

This should always be the case, even when dealing with people whose products you pay for, but it's especially true for FOSS communities, where there is no money (or a similarly compelling incentive) holding a volunteer back from leaving at any time. One bad exchange of words could sour things enough for a contributor to decide that it will be better for their well-being to leave. And then everyone suffers, _including you_.

> I know that asking ETAs & demanding quick updates is against FOSS nature & version control principles.

Then why did you open this issue, when you already know better? Even if you're absolutely polite and respectful with your words (which you weren't), asking for ETAs is _still bad manners_ and might piss off contributors. It doesn't _matter_ what your justification is. There is a reason that this is the topmost anger/irritation trigger for FOSS developers across projects, and why thousands and thousands of FAQs and ReadMes keep harping on about not asking for ETAs.

The ONLY acceptable way to ensure that an app is released faster is to OFFER YOUR HELP. And that help must be in the form of something _valuable_, not something simple that would take 2 minutes (or we would have done it ourselves):

"Hey guys, I noticed that the gap between releases is increasing. Any crucial bugs I could fix or PRs I could help improve or review? Please let me know."

That's it. You either grab an oar and start paddling, or you sit still and stay quiet, and let the others work.
