### ISSUE TITLE
Search In Subscription

### ISSUE THREAD

**Issue by caltrop2075** [TeamNewPipe/NewPipe#7187] opened 2021-10-01 17:25 UTC
just found this and it is GREAT!

be nice if there was a search in a subscription

I'd donate but I'm really poor, why I have to download videos at the Library to watch later at home since I have no Internet

**Comment by SameenAhnaf** [comment] 2021-10-01 20:41
Duplicate of #4795. Also, please fill in the template properly.

**Closed** 2021-10-02 09:27 UTC
Labels: enhancement
