### ISSUE TITLE
Allow usage of external player for playlists

### ISSUE THREAD

**Issue by Farbdose** [TeamNewPipe/NewPipe#2528] opened 2019-08-17 14:36 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) a to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I'm trying to play music from YouTube in the background ignoring audiofocus changes and having a separate volume control for it...

The best I managed so far is by using New Pipe with an external player that can ignore audio focus changes and has its own volume control (MxPlayer) 

The only problem is that this requires me to start each video by hand.

Could you add support for usage of external players for playlists / autoplay?
OR
Enable New Pipe to ignore permanent audiofocus changes on its own (including an option to change its volume independent of the device)?

**Comment by gkeegan** [comment] 2019-08-17 15:05
Adding playlists would be doable afaik by saving a playlist file, but I don't think autoplay would work.

I'm really against adding separate volume for NewPipe, as it can cause some times in public when you think it is muted but volume is full blast.

**Comment by Farbdose** [comment] 2019-08-18 07:32
I wasn't aware that one could prepare video URLs without them being invalidated after some time, so playlists files would sound great.
I thought more along the lines of somehow tracing when the external player finishes and then starting it with the next URL, bot no idea if that would even be possible are would have side-effects like bringing the other player app to the front :-(

**Comment by Stypox** [comment] 2019-08-29 06:58
Duplicate of #1686

**Closed by Stypox** 2019-08-29 06:58 UTC
