### ISSUE TITLE
New download dialog interface

### ISSUE THREAD

**Issue by jefferson018200306** [TeamNewPipe/NewPipe#6154] opened 2021-04-24 10:12 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
 i think it would be nice to have a new Interface where we can freely choose our preferred video, audio, and subtitle files. Instead of going back and forth on settings to choose format, why not list all of them? but with additional details such as Bitrates and codec (retrieve using ffprobe).

#### Is your feature request related to a problem? Please describe it
 I want to mix different quality of a downloaded video/audio, but there is no way to do it because the video already has a embedded audio in it. Why not separate them and let us pick our preferred video and audio... Then click mix to put them together in the container

#### Additional context
 I have no additional context

#### How will you/everyone benefit from this feature?
 this will make everyone freely choose their own needs of saving a video or audio in their storage. Making this app more user friendly and helpful for other uses.

**Comment by jefferson018200306** [comment] 2021-04-26 02:59
1. Basically, I just want a _new Interface that has a list of all audio video and subtitle files_
2. Also having a **MIX** button to put them all together in **MKV** format is such a nice feature to have.
3. And lastly, remove the feature to choose audio and video formats on Settings because it's annoying for me and many of us

**Comment by 1kaiser** [comment] 2021-04-29 13:31
Enque option to currently playing list of items directly from initial dialog Box
![enque](https://user-images.githubusercontent.com/26379748/116558605-3c8dbe00-a91d-11eb-85be-7a560039acf3.png)

**Comment by SameenAhnaf** [comment] 2021-11-03 07:11
@litetex Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2885, https://github.com/TeamNewPipe/NewPipe/issues/1059 and https://github.com/TeamNewPipe/NewPipe/issues/2613 respectively.

**Comment by litetex** [comment] 2021-11-03 15:55
Closing as described in https://github.com/TeamNewPipe/NewPipe/issues/6154#issuecomment-958699615.
Thanks @SameenAhnaf

**Closed by litetex** 2021-11-03 15:55 UTC
Labels: enhancement
