### ISSUE TITLE
[Request] Blacklist for blocking annoying channels

### ISSUE THREAD

**Issue by xGimmick022** [TeamNewPipe/NewPipe#2468] opened 2019-07-21 06:54 UTC
Hi. I ask for add a manual way like browser extensions to block annoying, hateful channels and them videos for not appearing in the search results, trendings and recomended videos.
excuse my english, thanks.

**Comment by Stypox** [comment] 2019-07-21 08:15
Duplicate of #1815

**Closed** 2019-07-21 08:15 UTC

**Comment by xGimmick022** [comment] 2019-07-21 12:22
Thanks :)
