### ISSUE TITLE
Start playing from here/ Enqueue from here

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#4805] opened 2020-11-04 23:46 UTC
.

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Although after merging #4425 (Replace specific enqueue options with one done by @vkay94 ) made enqueueing videos alot easier, one key change that was needed was overlooked, that is the ability to start  play/enqueue videos from the middle of playlist.

Edit (Dec 10):
- play from here         : starts a new queue
- enqueue from here : adds to existing queue if any

#### Is your feature request related to a problem? Please describe it

The problem is if you want to start  playing/enqueue videos from the middle of a playlist, you can't. you can use a work around which is start playing in background/pup-up mode then change to full screen mode however that not right. or you can enqueue videos, one by one, which is not practical especially in big playlists to say the least.

#### Additional context

I wish if we could add to context menu:
- Start playing from here and
- Enqueue from here when a video is playing
![Screenshot_20201105-020545](https://user-images.githubusercontent.com/63132171/98179194-4bb42600-1f0f-11eb-98f3-3fa9b711caec.png)

#### How will you/everyone benefit from this feature?

This would not only solve playing playlist from the middle but also able is to enqueue playlist while a video is playing

**Comment by ShareASmile** [comment] 2020-11-05 10:45
..yeah it is was there in v0.16.2 but was removed in 0.17.0. It was really helpful. I miss it just like yesterday. Probably needs a couple of lines of code.

**Comment by BartFarley** [comment] 2020-11-05 19:23
This feature existed in all versions up to 16.2. It was then deleted by @stypox. He said it was "useless". It wasn't.
The following people complained, and were ignored and lied to.

@jojoxl01
@xak2000
@jojoxl01
@xak2000
@astamminger
@LukasThyWalls
@geekyjazzy
@kurobon-jp 
@alittlebitofit
@caogia
@bartfarley

**Comment by MD77MD** [comment] 2020-11-05 23:52
> ..yeah it is was there in v0.16.2 but was removed in 0.17.0. It was really helpful. I miss it just like yesterday. Probably needs a couple of lines of code.

really, i guess i was late to the party 😁, anyway like you said this makes things alot easier.

**Comment by astamminger** [comment] 2020-11-06 07:05
> 
> 
> This feature existed in all versions up to 16.2. It was then deleted by @Stypox. He said it was "useless". It wasn't.
> The following people complained, and were ignored and lied to.
> 
> @jojoxl01
> @xak2000
> @jojoxl01
> @xak2000
> @astamminger
> @LukasThyWalls
> @geekyjazzy
> @kurobon-jp
> @alittlebitofit
> @caogia
> @BartFarley

Why was @BartFarley's comment marked as "disruptive comment" when it is nothing but the truth? Please stop silencing / ignoring opinions that do not align with what you think. You did that to me as well when I was explaining why that feature was essential to me and was told by more than one person that this function cannot be essential to me because **they** don't use it at all. (That was a little WTF-Moment for me to be honest)

Anyway, let's be constructive: I see that my suggestion to put the button toggling the auto-play function in a more prominent position has been implemented in the meantime. If someone could finally fix the list of upcoming videos to only contain the playlist items in an ordered fashion if a video was started from a playlist that would solve all the problems and make the play from here obsolete.

Cheers
Andreas

**Comment by opusforlife2** [comment] 2020-11-06 07:18
If the tone of a comment is aggressive or even passive-aggressive, it will be minimized. You are free to ping all the people for whom this issue is relevant, sure, but directly or indirectly attacking a developer who volunteers their free time will not be tolerated.

Since your comment quotes the entire previous comment, I'm editing it a little bit.

**Comment by astamminger** [comment] 2020-11-06 07:55
@opusforlife2 that's understandable, of course, but I'm under the constant impression that criticism gets confused with aggression here far too easily.

**Comment by opusforlife2** [comment] 2020-11-06 12:49
I'm not aware of this happening since I've started maintaining issues. Can you give other examples? I would like to analyse them.

**Comment by astamminger** [comment] 2020-11-06 13:01
@opusforlife2  Sorry if I was a bit unclear here maybe but I was talking about this specific thread because imho there‘s no aggression in @BartFarley‘s comment but facts

**Comment by opusforlife2** [comment] 2020-11-06 13:04
When you said "constant impression", I thought you had more than one instance in mind...

**Comment by astamminger** [comment] 2020-11-06 13:09
Yeah, that‘s what I meant with being unclear. Sorry about that.

**Comment by BartFarley** [comment] 2020-11-07 04:29
Firstly, thank you @astamminger. You get it. Every sentence in my last comment was the truth. No agression. No attack. Just the facts.
I love NewPipe. I use it every day.  Been using it since, I believe, version 13.0 or so. When you use an app that much, and see it improve and grow it's a great thing. The developers add new features once in a while, improving the software for the users.
People get used to, and depend on these features. Like say, for instance, playing a playlist, full screen, starting from any video in that playlist.
One or more of you developer types took the time to write the code implementing that feature. Volunteers. It's quite a bit of code too. I can tell because if you look at what was deleted from 16.2 to remove this feature, it was many lines of code.
Now, I for one would be a mighty angry volunteer coder if someone just went in, and deleted all my hard work without a reasonable explanation. 
The result is the disappearance of a feature that people like and use. Poof!! Gone.
There's more I could say about this, and other related items, but I see no joy in typing on my phone.

Version 20+ is a disaster.

Please put "play from here" back in

Don't become the latest FireFox (Disaster)

Gnome 3 flashbacks!

Implementing an audio volume normalizer in NewPipe would be useful.

**Comment by opusforlife2** [comment] 2020-11-15 10:00
@BartFarley @astamminger Are you and the users you linked aware of #2518?

**Comment by BartFarley** [comment] 2020-11-16 03:11
I can only speak for myself. Yes, I'm aware of #2518.
Are you aware of https://github.com/TeamNewPipe/NewPipe/pull/2368#issue-283397509 , the paragraph that starts with:
"I decided to remove..." ?

**Comment by Stypox** [comment] 2020-11-17 13:26
We developers can't unfortunately implement everyone's needs without breaking sombody else's. That's why I decided to make menus consistent and remove an action that only saved really little time (and now thanks to unified ui is not needed anymore). I get that some of you may have needed it, but all of the other people would just get confused by a long list of possible action and say "I can't understand NewPipe and it is really inconsistent, better to stick with YouTube". Therefore for now this will stay as it is, until a proper solution is implemented. I proposed #2583, trying to suit everyone's needs, but then I realised that would also be bad for people not much into technology. Another solution is needed.

**Comment by astamminger** [comment] 2020-11-17 17:18
> That's why I decided to [...] remove an action that only saved really little time

@Stypox can you please elaborate on this? What do you mean by *"saved really little time"*? Compared to what? I certainly might be missing something here but back then *"Start playing from here"* was my only option to start from a specific (video!) playlist track and auto-queue the upcoming videos from the playlist and only from the playlist. That was because enabling the auto-play option from the menu would play the selected video and continue to enqueue videos from the random list of *related* videos.

However! I suggested to use an auto-queue option for playlists (https://github.com/TeamNewPipe/NewPipe/issues/2510#issuecomment-537584700 :D) and I am happy to see that this has been finally implemented and works.

Thank you guys :thumbsup:

**Comment by MD77MD** [comment] 2020-11-19 11:44
> We developers can't unfortunately implement everyone's needs without breaking sombody else's. 

what are you breaking here, nothing

>That's why I decided to make menus consistent and remove an action that only saved really little time (and now thanks to unified ui is not needed anymore).

Unified UI has nothing to with this, we need this because simply thier is no alternative.

>I get that some of you may have needed it, but all of the other people would just get confused by a long list of possible action and say "I can't understand NewPipe and it is really inconsistent, better to stick with YouTube". 

I don't understand how would anyone get confused by this. many top video apps have this option including VLC. could point out the comments saying they are confused by this.

>Therefore for now this will stay as it is, until a proper solution is implemented. 

this is exactly whats getting people upset. everything depends on what you like... eg. like they notification color (which I consider an nich), only one person asked for it and it was merged immediately into the next release. while there are so many more important request that effect NewPipe usability are left out or denied simple because you don't need it.  this is not right. its a discussion bro

>I proposed #2583, trying to suit everyone's needs, but then I realised that would also be bad for people not much into technology. Another solution is needed.

I wouldn't count on it.

anyway just to be clear, Im grateful for everything you are doing here @Stypox i just which if you would open a little more for us and understand we are in your side and support you.

I would also like to extend my gratitude to @opusforlife2 @B0pol @TobiGr  and everyone helped in the 0.20.3 release

**Comment by B0pol** [comment] 2020-11-19 12:19
I did not read this issue entirely but I want to answer about notification:

It was a **must** to change to Android MediaStyle, because it did not work on Android 11.
Then about the color: as we are using Android MediaStyle notification, Android have already thought about color / no color and provided a simple way to do that. As you can see in #4643, it was really easy.

**Comment by MD77MD** [comment] 2020-11-19 12:25
> I did not read this issue entirely but I want to answer about notification:
> 
> It was a **must** to change to Android MediaStyle notifications, because ours it did not work on Android 11.
> Then about the color: as we are using Android MediaStyle notifications, Android have already thought about color / no color and provided a simple way to do that. As you can see in #4643, it was really easy.

im not against it, im just saying we should leave some room for people feedback in our decisions. especially in the small stuff that's all.

**Comment by vkay94** [comment] 2020-11-19 12:42
>I don't understand how would anyone get confused by this. many top video apps have this option including VLC. believe me, people are more familiar to this option than you think.

The point is the resulting overfilled dialog. It just doesn't look good to have repeated actions which differ in single words and containing the same word - in English it's "Queue", in German for example it's "Wiedergabe" which is pretty long to be honest o.0

>on the other hand there are so many more important request that effect NewPipe usability are left out or denied simply because you don't need them or dont interest you

Nah, that's totally fine. The devs aren't paid and work in their freetime, so they pick the issues/enhancement they like if it isn't a required one (everything except those which fix the service). But there're so many out there, sooner or later these will be worked on - or not xD

**Comment by MD77MD** [comment] 2020-11-20 21:20
>Nah, that's totally fine. The devs aren't paid and work in their freetime, so they pick the issues/enhancement they like if it isn't a required one (everything except those which fix the service). But there're so many out there, sooner or later these will be worked on - or not xD

bro doing it for free doesn't mean ignoring others because it's never been about money now is it... there are many people around the world who do charity and volunteer work, imagine a volunreer doctor refusing a patient saying his already working for free. 
GitHub wouldn't exist without such **patient people**. just look how you and @B0pol are recognizing our frustration and having a discussion explaining your point of view. why wouldn't @Stypox  do the same. he just came and throw his statement and left (sorry stypox). and as i said, we are all here at the same team working for the same goal. having different opinions is normal and that's what discussions are made for, to try to get closer to that solution.

Now regarding this feature, apparently it was done before but was removed. and gassing from the hot timbers showing in the early comments, others have been requesting to readd it but where rejected in a cold way.

**what i propose** is to exercise the same flexibility we used in the forward/rewind behavior feature #4264 (just a great experience all over). we could readd this in a beta mode, and see people's reaction toward it. if people like it or needs a bit of tweaking and it's not too confusing then great. but if people's feedback is negative or a better solution is found then we can just delete it. at least this way we can be sure we are making the right decision.

 what do you think guys? i hope I'm not being too pushy😁.

**Comment by vkay94** [comment] 2020-12-03 15:14
I'm throwing this workaround idea into the room due to maaaaany complaints (well, it's not perfect, but just for the idea): https://streamable.com/e/dpyxep

This would only appear in the playlist fragments (local, remote) and history (is it really needed there in the first place due to the changing order after every video?). The actions in the initial dialog refer to single streams, so for example "Start playing in background" enqueues/starts a list of 1 even in lists.

**Comment by xak2000** [comment] 2020-12-03 16:11
> "Start playing in background" starts a list of 1 even in lists.

Do you mean that this action will play just 1 song from a playlist even if there are other songs down the list?

Currently this action starts playing a playlist from the selected song and plays it up to the last song of the playlist. And this is totally desired behavior for me. Honestly, I can't imagine why someone may want to play just one song of the playlist. This is the main purpose of playlists - play songs of the list. :)

If this behavior (play just one item in the list) is really desired for someone, then maybe it's worth to add some switcher on the screen, that will control this behavior (ON - all actions that starts playing any item will continue to play the list, OFF - all these actions will stop playing after song is over).

**Comment by vkay94** [comment] 2020-12-03 16:34
>Do you mean that this action will play just 1 song from a playlist even if there are other songs down the list?

Yes.

>Honestly, I can't imagine why someone may want to play just one song of the playlist. This is the main purpose of playlists - play songs of the list. :)

Yesterday for example: #5070
By "separating" it into categories there is also a little bit more consistency to the behavior of this action in other screens (channel screen, search, ...). So this action would be same for all.

But there may be some other cases. NewPipe doesn't provide a "Watch later" functionality, so you have to create a playlist for this purpose. Then you don't want enqueue all streams at once, maybe just picking some of them :)

**Comment by xak2000** [comment] 2020-12-03 16:47
@vkay94 Ok, you convinced me that this behavior is desired by some people. :)

But other behavior is desired too (I mean "Start playing from here and play until playlist ends"). How could I do this if what you described will be implemented? Are new "enqueue" actions from submenu in the video do this?

I very confused because "enqueue" means that I want to **enqueue** some items **after** some other items which are already in the queue. But this is not the same as "Start playing from here" action (this clears the queue before enqueuing part of current playlist) that is most useful action for me.

**Comment by vkay94** [comment] 2020-12-03 17:29
>But other behavior is desired too (I mean "Start playing from here and play until playlist ends"). How could I do this if what you described will be implemented?

@xak2000 This is inside the sub-menu after clicking on "Queue options" (there is the small arrow as indicator). Also the "Enqueue from here" requested from the OP. 

>I'm very confused because "enqueue" means that I want to enqueue some items after some other items which are already in the queue. But this is not the same as "Start playing from here (in background)" action (that clears the queue before enqueuing part of current playlist) that is most useful action for me.

I've picked all string values fastly, so there is definitely place for improvement ;) . I just wanted to show the idea to implement the request of this issue in the first place (provide the feature while keeping the menu as light as possible).

**Comment by xak2000** [comment] 2020-12-03 17:44
So, "Enqueue from here in background" in your video actually means "Start playing from here in background"? Is this corrent?

And, if yes, then where is real "enqueue in background" action? :) I'm speculating here ofc. Personally, I don't need such option. But I'm sure there are users who need it, so they can quickly enqueue some videos from multiple playlists/etc into queue (without emptying this queue or stopping playing currently playing track) and then play this queue.

Another drawback of this solution is that some actions are more accessible than others. E.g. currently I need to do just 2 taps to start playing playlist starting from selected track in the background. But if what you shown in the video will be implemented, I'll need to do 3 taps. While some other user who prefers playing just one track will need only 2. Of course, you could argue that submenu will contain actions that are used most infrequently. But how can we know what actions are really used frequently and what are not? Is there are Google Analytics or something present in the app, that tracks user taps?

**Comment by vkay94** [comment] 2020-12-03 18:51
>So, "Enqueue from here in background" in your video actually means "Start playing from here in background"? Is this correct?

Correct.

>And, if yes, then where is real "enqueue in background" action? :)

Depends. If you mean enqueueing a single stream then it's "Start playing on background" if there's nothing playing in the moment otherwise "Enqueue" which enqueues the stream into the current player (current behavior) without interrupting playback.

>Another drawback of this solution is that some actions are more accessible than others.

Yeah, that might be true. From another aspect you have to weight: either all functionalities in one place as long (scrollable) list or remove/drop some of them or re-structure. That's the problem by differentiate between background and popup in the dialog - you have every play action twice (except for the "Enqueue" action).

> Is there are Google Analytics or something present in the app, that tracks user taps?

Probably? ^^ Just kidding ;)

I'm full aware that it's impossible to make everyone happy. As said it's an idea of what's possible :) Thanks for the feedback by the way :)

**Comment by xak2000** [comment] 2020-12-03 19:43
> Depends. If you mean enqueueing a single stream then it's "Start playing on background" if there's nothing playing in the moment otherwise "Enqueue" which enqueues the stream into the current player (current behavior) without interrupting playback.

But new "Enqueue.." actions will actually start playing from scratch, as you just confirmed. Not really _enqueue_. So it will be required to add several other actions into submenu, like:

* Start playing from here in background _(currently in your video, but incorrectly named "Enqueue...")_
* Enqueue from here in background _(not present in your video)_
* Start playing from here in pupup _(currently in your video, but incorrectly named "Enqueue...")_
* Enqueue from here in popup _(not present in your video)_

etc.

>  it's impossible to make everyone happy

Maybe if user will be allowed to enable/disable each menu item and reorder them from configuration screen, it's possible. ;)

Or at least allow to reorder menu items. In this case all "excessive" items (like 6th item and more) can be automatically hidden under "arrow submenu" as in your video.

This way each user can put 5 most useful **for him**  actions at the top of the list and will be able to access them with 2 taps, while 6th and more actions will be still accessible with 3 taps.

Just an idea!

---

To be honest, I'm not very adherent to this idea, because popup menu with many items is not a good UX anyway (if you ever used IntelliJ IDEA, you could know how hard is to find required item from context menu sometimes, even if you used it before million times). So it's better to  come up with something better idea. But the idea of removing some useful actions is much worse in my opinion. :)

**Comment by JeffRockatansky** [comment] 2020-12-04 10:36
> popup menu with many items is not a good UX anyway

Double on this. Maybe something else? A grid of actions with icons and labels? Or a circle menu? Or maybe an accordion list.

Might be grouped/hierarchical.

May even make "tap on video in a plylist" default to "Play from here" instead of "Open just one video". Or any other default video action, but it should consider the whole playlist, not the individual video in it, as it does now.

**Comment by vkay94** [comment] 2020-12-04 13:08
>This way each user can put 5 most useful for him actions at the top of the list and will be able to access them with 2 taps, while 6th and more actions will be still accessible with 3 taps.

I think that can't be handled well and would be more problematic than benefiting because you've got many such dialogs for normal streams, in history, in local and remote playlist. Also it's not common to edit such item based menus.

>A grid of actions with icons and labels? Or a circle menu?

From my perspective I had such in mind to try (grid) but the differentiating of background and popup would make it a total mess - you'll need much text to explain the function, 1-2 words and an icon aren't enough.

**Comment by xak2000** [comment] 2020-12-05 01:17
Another idea.

Make menus structured this way:

* Play one >
  * Play in the background
  * Play in a popup
  * etc
* Play all from here >
  * Play in the background
  * Play in a popup
  * etc
* Enqueue one >
  * Enqueue in the background
  * Enqueue in a popup
  * etc
* Enqueue all from here >
  * Enqueue in the background
  * Enqueue in a popup
  * etc

Where "etc" is other ways to play a stream. I just is not familiar with all the ways of playing that NewPipe supports. I use only "in background" options always because I use youtube on phone only for music listening.

This way 1st level menu will always have just 4 menu items.

Or it could be done this way instead:

* Play >
  * Play one in the background
  * Play one in a popup
  * Play all from here in the background
  * Play all from here in a popup
  * etc
* Enqueue>
  * Enqueue one in the background
  * Enqueue one in a popup
  * Enqueue all from here in the background
  * Enqueue all from here in a popup
  * etc

Just way there will be only 2 menu items in main menu. But text of submenu items will be longer, unfortunately. Otherwise they will be not descriptive enough.

Which way is better depends on how many other menu items (this "etc" item in my examples) need to be placed in submenu.

---

By the way, do we really need all these options for enqueue? I mean "In backgorund", "In popup" etc. Can't the mode of enqueuing be inherited from the type of currently playing queue?

I mean, we can have just 2 menu items for enqueuing:

* Enqueue one
* Enqueue all from here

And videos will be enqueued to the current queue, whatever it is.

E.g., if current queue is playing in the background, then new tracks will be enqueued to the end of this queue also in the background. If current queue is playing in a popup, then new tracks will be enqueued to the end of this queue also in a popup.

Maybe I don't understand how the queue work.. In my mind the queue is single and you just add items to it and then can play this queue in the foreground, in the background or in a popup or whatever mode NewPipe supports and switch between these modes at any moment (without losing the queue). Or it didn't work like this?

Sorry for maybe stupid question, but I really use NewPipe only to play music playlists in the background, so my pattern of use is closer to native YouTube application. I'm not familiar with the queue in NewPipe and never use it explicitly. Only implicitly through playing playlists, I think. In my mindset, I'm playing a playlist directly: track after track.

**Comment by SameenAhnaf** [comment] 2021-03-30 15:47
.It's quite late, I know. But https://github.com/TeamNewPipe/NewPipe/issues/5741#issuecomment-807936802 includes all types of enqeue options.

**Closed** 2021-11-13 10:49 UTC
Labels: enhancement, GUI
