### ISSUE TITLE
show more info about channel

### ISSUE THREAD

**Issue by Relected** [TeamNewPipe/NewPipe#7642] opened 2022-01-10 12:25 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

show more information and content about a YouTube channel (about, channels, community, playlists, etc) 

#### Why do you want this feature?

to have more info about the YouTube channel  (ie. socials, date of creation, Alt channels)

**Comment by TiA4f8R** [comment] 2022-01-10 12:59
> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

Duplicate of #2414. Please search (better?) for duplicates the next time. Thank you.

**Closed by TiA4f8R** 2022-01-10 12:59 UTC

**Comment by Relected** [comment] 2022-01-10 13:35
@TiA4f8R oh sorry I looked up "channel info"
