### ISSUE TITLE
Newpipe crashes and reboots android on clicking another video from suggestion

### ISSUE THREAD

**Issue by musq** [TeamNewPipe/NewPipe#6379] opened 2021-05-27 15:40 UTC
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

This crash happens ***nearly*** all the time when switching from one video to another. But here is one specific workflow:
1. Search "do re mi"
2. Play any Do Re Mi - Sound of Music video
3. Click on any other video in the suggestion
4. The app crashes and android reboots

### Actual behaviour

The app crashes and android reboots.

### Expected behavior

Newpipe should play the second clicked video normally and without crashes.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/12999426/119855760-d1410700-bf2f-11eb-9d2c-53fdc0415506.mp4

### Device info

 - Android version/Custom ROM version: `11`
 - Device model: `Xiaomi Mi A3 - Android One`

**Comment by TobiGr** [comment] 2021-05-27 15:43
Can you provide a full  log of the incident?

**Comment by musq** [comment] 2021-05-27 15:55
Since the app just straight up crashes the OS I don't have any logs. Could you suggest me a way to record logs for this?

**Comment by TiA4f8R** [comment] 2021-05-27 17:36
> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

Unfortunately, you didn't find the duplicate because this is a duplicate of #5961. Closing this issue.

**Closed by TiA4f8R** 2021-05-27 17:36 UTC
Labels: bug

**Comment by bloatware99** [comment] 2021-05-27 17:50
> Since the app just straight up crashes the OS I don't have any logs. Could you suggest me a way to record logs for this?

Same as facimg that issue,  we can't able to catch log when device is foreced to reboot.
