### ISSUE TITLE
Comments of YouTube videos don't show even if comments are enabled.

### ISSUE THREAD

**Issue by deep0808** [TeamNewPipe/NewPipe#5930] opened 2021-03-28 00:38 UTC
## Exception
* __User Action:__ requested comments
* __Request:__ Start loading: https://www.youtube.com/watch?v=ty0kTizMF-o
* __Content Country:__ IT
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.21.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json data for comments
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:100)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:55)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:154)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.grack.nanojson.JsonParserException: Unexpected character: < on line 1, char 1
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source:118)
	at com.grack.nanojson.JsonParser.advanceToken(Unknown Source:12)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:1)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:98)
	... 30 more

```
</details>
<hr>

**Comment by TiA4f8R** [comment] 2021-03-28 11:32
@deep0808 Please fill the template properly.
Comments are not disabled on this video, this is strange.
Can you install a debug APK like the following, follow https://github.com/TeamNewPipe/NewPipe/wiki/Additional-Debugging-Info and send the HAR to tnp@newpipe.schabi.org if you cannot see comments with this APK?
If you can see comments, can you try to export your data in the normal app, clear app data in Android Settings, import you database without settings and try to reproduce the bug?
Thank you in advance.

**Comment by dillir07** [comment] 2021-03-28 14:06
I was facing this issue on v0.21.0, after clearing storage & cache from android settings, now comments are loading properly.

**Comment by TiA4f8R** [comment] 2021-03-28 14:08
Only clear cache doesn't fix this issue?

**Comment by dillir07** [comment] 2021-03-28 18:23
I directly cleared the whole storage, so I can't confirm. sorry.

**Comment by sm4rk0** [comment] 2021-03-28 22:53
I've just tested clearing the cache only. It didn't solve the issue. The stack trace is identical as in this bug report.

**Comment by sm4rk0** [comment] 2021-03-28 22:57
What's specific about the video I was watching is that comments are turned off:

https://www.youtube.com/watch?v=A9YpgQHVm3E

But I can easily load the comments in original poster's video.

**Comment by deep0808** [comment] 2021-03-29 13:13
Sorry for late reply but clearing cache-data, uninstall-reinstall doesn't work at all. I don't why I tried using NewPipe on other phones but occurs same error🤷🏻‍♂️

**Comment by TiA4f8R** [comment] 2021-03-29 14:04
@deep0808 Thanks for your comment and feedback.

Can you follow what I said in my first-top comment?

Also, it seems that you are living in the EU. Google started rolling out new privacy consents, which redirects you to a page blocking website access (an URL with consent.youtube.com) until you click on `I agree` button.
Maybe it can be the origin of this issue, I started experienced this too.

**Comment by deep0808** [comment] 2021-03-29 14:14
I did it but I don't know way to confirm that action is successfully processed or not.

**Comment by TiA4f8R** [comment] 2021-03-29 14:20
So do you sent the report?

**Comment by deep0808** [comment] 2021-03-29 14:57
Yep I guess I did. If you can confirm if you  received it?

**Comment by NewNewPipe** [comment] 2021-03-29 16:53
In my app, the comments under this particular video load without a problem. Android 10. App ver 0.21.0

**Comment by deep0808** [comment] 2021-03-30 11:21
> In my app, the comments under this particular video load without a problem. Android 10. App ver 0.21.0

Well bro I don't know not just that particular video but the comment error occurs in every video I play. Okay One more question do newpipe send notifications if my subscribed channel post new video?

**Comment by TiA4f8R** [comment] 2021-03-30 11:28
No, this will be implemented with a PR.

**Comment by deep0808** [comment] 2021-03-30 11:36
PR what? Bro can you please share a tutorial or something coz I don't know how to🤷🏻‍♂️

**Comment by TiA4f8R** [comment] 2021-04-01 15:54
Can you try this APK please and see if it works? Thanks!
https://github.com/TeamNewPipe/NewPipe/files/6243573/app-debug.zip

**Comment by deep0808** [comment] 2021-04-01 18:41
This working thank you so much. But what about update where do I get it next time?

**Comment by TiA4f8R** [comment] 2021-04-01 18:47
Ok, closing as a duplicate of #5977 in this case. We will release a hotfix version including the fix soon.

**Closed** 2021-04-01 18:48 UTC
Labels: doesn't-follow-template, youtube

**Comment by deep0808** [comment] 2021-04-02 16:40
I don't want to bother you bro but in newpipe debug version today the comments section is disappeared I don't know why until yesterday is was working so well I'm sharing the picture take a look ![730e8e84-b586-41fe-af19-9114d2a4f041.jpg](https://user-images.githubusercontent.com/81495925/113435344-de83be80-93e2-11eb-92ea-a55eb72461a9.jpg)
