### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by woutiscoding** [TeamNewPipe/NewPipe#6875] opened 2021-08-08 09:28 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4198)
	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
	... 8 more

```
</details>
<hr>

**Comment by reno-a** [comment] 2021-08-08 09:46
On f-droid, NewPipe upstream repository error.

**Comment by woutiscoding** [comment] 2021-08-08 09:47
So should I compile it myself to fix the issue?

**Comment by SameenAhnaf** [comment] 2021-08-08 09:57
> So should I compile it myself to fix the issue?

No, try the apk file in #6841 and check if the bug still persists.

**Comment by woutiscoding** [comment] 2021-08-08 10:01
That fixes the bug. But it is a debug version, and doesn't use the data from my currently installed NP app

**Comment by litetex** [comment] 2021-08-08 12:47
> That fixes the bug. But it is a debug version, and doesn't use the data from my currently installed NP app

You can export the data in the "normal" version and import it back into the debug version.

Closing as
Duplicate of #6687

**Closed by litetex** 2021-08-08 12:47 UTC
