### ISSUE TITLE
allow search in history page

### ISSUE THREAD

**Issue by test2a** [TeamNewPipe/NewPipe#6258] opened 2021-05-09 11:08 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it

no way to search between already watched videos 

#### How will you/everyone benefit from this feature?

this feature will help find videos you saw last week but don't remember the exact title to be able to search in the normal youtube search because the additional constraint of having already watched that

**Comment by mhmdanas** [comment] 2021-05-09 11:42
Duplicate of #2977.

**Closed by mhmdanas** 2021-05-09 11:42 UTC
Labels: enhancement
