### ISSUE TITLE
AUDIO/VIDEO TRIM

### ISSUE THREAD

**Issue by umunais** [TeamNewPipe/NewPipe#5375] opened 2021-01-09 10:34 UTC
Please introduce an option to Trim and download audio/video from YouTube links giving parameters like start time and end time

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by mhmdanas** [comment] 2021-01-09 12:29
Thanks for opening an issue! This is a duplicate of #2800. If you disagree, feel free to make a comment.

**Closed by mhmdanas** 2021-01-09 12:29 UTC
Labels: enhancement
