### ISSUE TITLE
Video doesn't load if paused and restarted after a long time

### ISSUE THREAD

**Issue by cyphar** [TeamNewPipe/NewPipe#8455] opened 2022-05-29 01:39 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Play a video and pause it part of the way through.
2. Leave the app in the background for several hours.
3. Try to play the video afterwards.

### Expected behavior

The video would be able to play (maybe after a brief pause to refresh the stream).

### Actual behavior

The video plays for a bit (presumably playing the saved buffer) and then it loads indefinitely. Sometimes switching resolutions can get it to load the video again, but fairly often the video simply won't load. If you close the video and try to play it again, the video doesn't play at all and you just get the crash posted below.

The only way to solve the issue appears to be to clear the cache (or to just wait for the cache to be cleared by NewPipe automatically by watching other videos).

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/2888411/170848537-1af755a8-946c-4e73-a856-bd55465ab8dc.mp4

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=iB9QAzNNeyw
* __Content Country:__ JP
* __Content Language:__ ja-JP
* __App Language:__ ja_JP
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:396)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:641)
	at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)
	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:291)
	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:107)
	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:115)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomPayload(FragmentedMp4Extractor.java:457)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:336)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: com.google.android.exoplayer2.upstream.DataSourceException
	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:394)
	... 16 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 (but this issue has existed for a long time)

### Affected device model

Google Pixel 4a

**Comment by SameenAhnaf** [comment] 2022-05-29 03:18
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5730

**Closed** 2022-06-11 18:22 UTC
Labels: bug
