### ISSUE TITLE
[Feature Request] Add playlist as main page

### ISSUE THREAD

**Issue by eomobile** [TeamNewPipe/NewPipe#2749] opened 2019-10-21 18:51 UTC
How can we add a playlist instead of trend videos

example https://www.youtube.com/playlist?list=PLMC9KNkIncKtPzgY-5rmhvj7fax8fdxoj

**Comment by TobiGr** [comment] 2019-10-22 06:21
I moved this to the correct repository. @eomobile Can you please check whether a related issue already exists?

**Comment by Stypox** [comment] 2019-10-22 11:37
@TobiGr this is a duplicate of #1781

**Closed by Stypox** 2019-10-22 11:37 UTC
