### ISSUE TITLE
Could not parse website

### ISSUE THREAD

**Issue by stemy2** [TeamNewPipe/NewPipe#6461] opened 2021-06-09 03:32 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

"Sorry, something went wrong" instead of the expected comments.

### Expected behavior

Actual comments

### Logs

Error report - {"user_action":"requested comments","request":"Start loading: https://www.youtube.com/watch?v=M5lMRDBseac","content_language":"fr-BE","content_country":"BE","app_language":"en","service":"YouTube","package":"org.schabi.newpipe","version":"0.21.4","os":"Linux Android 8.1.0 - 27","time":"2021-06-09 05:28","exceptions":["org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern \"INNERTUBE_CONTEXT_CLIENT_NAME\\\":(.*?)[,}]\"\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:58)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.onFetchPage(YoutubeCommentsExtractor.java:137)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)\n\tat org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:34)\n\tat org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:154)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)\n\tat java.lang.Thread.run(Thread.java:764)\n"],"user_comment":""}

### Device info

 - Android version/Custom ROM version: /e/ 0.16
 - Device model: samsung galaxy s7

**Comment by mhmdanas** [comment] 2021-06-20 12:06
Duplicate of #6016.

**Closed by mhmdanas** 2021-06-20 12:06 UTC
