### ISSUE TITLE
Timestamps opening in pop-up player

### ISSUE THREAD

**Issue by Anon1444** [TeamNewPipe/NewPipe#7094] opened 2021-09-11 21:22 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any video and click on any timestamp (from description or comments).

### Actual behavior

Clicking on any timestamp opens the video in popup player even though it was in the simple mode initially.

### Expected behavior

It should have opened in the same mode as it was in before.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/75598465/132961871-12c71082-1e74-4dda-932b-c77281760b56.mp4

### Device info

 - Android version/Custom ROM version: Android 10, RealmeUI 1.0
 - Device model: Realme 3 (RMX1825)

**Comment by SameenAhnaf** [comment] 2021-09-11 22:20
Duplicate of #2851.

**Comment by litetex** [comment] 2021-09-12 13:08
Closing as duplicate

**Closed by litetex** 2021-09-12 13:08 UTC
Labels: bug
