### ISSUE TITLE
Crash with ClassCastException due to android.text.SpannedString cannot be cast to android.text.Spannable

### ISSUE THREAD

**Issue by sajanki** [TeamNewPipe/NewPipe#9240] opened 2022-10-29 14:01 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. I play a video either from a search or from a channel
2. The application crashes and shows me the error reporting dialog

### Expected behavior

I expect the application not to crash

### Actual behavior

The application repeatedly crashes

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: android.text.SpannedString cannot be cast to android.text.Spannable
	at org.schabi.newpipe.util.CommentTextOnTouchListener.onTouch([CommentTextOnTouchListener.java:29](http://commenttextontouchlistener.java:29/))
	at android.view.View.dispatchTouchEvent([View.java:13456](http://view.java:13456/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at android.view.ViewGroup.dispatchTransformedTouchEvent([ViewGroup.java:3113](http://viewgroup.java:3113/))
	at android.view.ViewGroup.dispatchTouchEvent([ViewGroup.java:2720](http://viewgroup.java:2720/))
	at [com.android](http://com.android/).internal.policy.DecorView.superDispatchTouchEvent([DecorView.java:467](http://decorview.java:467/))
	at [com.android](http://com.android/).internal.policy.PhoneWindow.superDispatchTouchEvent([PhoneWindow.java:1851](http://phonewindow.java:1851/))
	at [android.app](http://android.app/).Activity.dispatchTouchEvent([Activity.java:4064](http://activity.java:4064/))
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent([WindowCallbackWrapper.java:69](http://windowcallbackwrapper.java:69/))
	at [com.android](http://com.android/).internal.policy.DecorView.dispatchTouchEvent([DecorView.java:425](http://decorview.java:425/))
	at android.view.View.dispatchPointerEvent([View.java:13728](http://view.java:13728/))
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent([ViewRootImpl.java:5663](http://viewrootimpl.java:5663/))
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess([ViewRootImpl.java:5457](http://viewrootimpl.java:5457/))
	at android.view.ViewRootImpl$InputStage.deliver([ViewRootImpl.java:4956](http://viewrootimpl.java:4956/))
	at android.view.ViewRootImpl$InputStage.onDeliverToNext([ViewRootImpl.java:5009](http://viewrootimpl.java:5009/))
	at android.view.ViewRootImpl$InputStage.forward([ViewRootImpl.java:4975](http://viewrootimpl.java:4975/))
	at android.view.ViewRootImpl$AsyncInputStage.forward([ViewRootImpl.java:5115](http://viewrootimpl.java:5115/))
	at android.view.ViewRootImpl$InputStage.apply([ViewRootImpl.java:4983](http://viewrootimpl.java:4983/))
	at android.view.ViewRootImpl$AsyncInputStage.apply([ViewRootImpl.java:5172](http://viewrootimpl.java:5172/))
	at android.view.ViewRootImpl$InputStage.deliver([ViewRootImpl.java:4956](http://viewrootimpl.java:4956/))
	at android.view.ViewRootImpl$InputStage.onDeliverToNext([ViewRootImpl.java:5009](http://viewrootimpl.java:5009/))
	at android.view.ViewRootImpl$InputStage.forward([ViewRootImpl.java:4975](http://viewrootimpl.java:4975/))
	at android.view.ViewRootImpl$InputStage.apply([ViewRootImpl.java:4983](http://viewrootimpl.java:4983/))
	at android.view.ViewRootImpl$InputStage.deliver([ViewRootImpl.java:4956](http://viewrootimpl.java:4956/))
	at android.view.ViewRootImpl.deliverInputEvent([ViewRootImpl.java:7763](http://viewrootimpl.java:7763/))
	at android.view.ViewRootImpl.doProcessInputEvents([ViewRootImpl.java:7732](http://viewrootimpl.java:7732/))
	at android.view.ViewRootImpl.enqueueInputEvent([ViewRootImpl.java:7683](http://viewrootimpl.java:7683/))
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent([ViewRootImpl.java:7902](http://viewrootimpl.java:7902/))
	at android.view.InputEventReceiver.dispatchInputEvent([InputEventReceiver.java:188](http://inputeventreceiver.java:188/))
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at [android.os.MessageQueue.next](http://android.os.messagequeue.next/)([MessageQueue.java:336](http://messagequeue.java:336/))
	at android.os.Looper.loop([Looper.java:174](http://looper.java:174/))
	at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:7405](http://activitythread.java:7405/))
	at java.lang.reflect.Method.invoke(Native Method)
	at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([RuntimeInit.java:502](http://runtimeinit.java:502/))
	at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:980](http://zygoteinit.java:980/))

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 - 29

### Affected device model

Lenovo Tab M8

**Comment by tsiflimagas** [comment] 2022-10-29 14:12
Duplicate of #9052.

**Closed** 2022-10-29 14:26 UTC
Labels: bug, needs triage
