### ISSUE TITLE
[Feature request] Back up subscriptions

### ISSUE THREAD

**Issue by djanoris** [TeamNewPipe/NewPipe#906] opened 2017-12-07 08:22 UTC
__Back up subscribtions__  will be useful feature in couses when reinstalling the app, resetting (wipe/reset) the system or restoring list subscription on 2rd device.

**Comment by coffeemakr** [comment] 2017-12-07 08:37
Duplicate of #705

**Comment by theScrabi** [comment] 2017-12-07 10:42
We should backup the whole database.

**Closed** 2017-12-07 10:42 UTC
Labels: duplicate
