### ISSUE TITLE
Download queue could do with a remodel

### ISSUE THREAD

**Issue by ballo** [TeamNewPipe/NewPipe#6569] opened 2021-06-25 04:31 UTC
The download queue is a pain to use when there are many videos downloaded. Here are a few issues:
1) Deleting an item makes it impossible to select the last item until the popup notification goes away. An easy solution would be to replace the item in the list with the delete notification so it doesn't obscure anything.
2) For some reason NewPipe cannot play videos and thus cannot keep track of when the video was paused. A problem for long videos.
3) When going back from the 3rd party player (using VLC but I doubt this matters) NewPipe usually doesn't maintain the same location in the queue requiring the user to scroll the list which is a major PITA if the list is long.

**Comment by mhmdanas** [comment] 2021-06-25 18:51
Thanks for opening an issue! Please don't remove the template when opening an issue. Just open three separate issues for each of your requests that actually do follow the template properly (checking if each is a duplicate of an already existing issue of course, either open or closed).

**Closed by mhmdanas** 2021-06-25 18:51 UTC
Labels: enhancement
