### ISSUE TITLE
Attempting to open press-and-hold menu while a video is playing force-crashes the app.

### ISSUE THREAD

**Issue by Shockwave508** [TeamNewPipe/NewPipe#7533] opened 2021-12-12 15:52 UTC
### Checklist

- [x] I am using the latest version - 0.21.14 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a video in any mode (in-player, popup, or background).
2. Press and hold on a different video, as if attempting to enqueue it.

### Actual behavior
1. The app instantly crashes back to your device's launcher.

### Expected behavior
1. A menu would appear, to enqueue, add to a playlist, etc.

### Screenshots/Screen recordings
(Unable to provide screenshots, due to instant crashing.)

### Logs
(No error message/log appeared.)

### Device info

 - Android version/Custom ROM version: Android 10 (JOYUI 11 21.11.05)
 - Device model: Xiaomi Black Shark 2 Pro (128GB Storage/8GB RAM)

**Comment by ktprograms** [comment] 2021-12-13 08:48
@Shockwave508 Am I right that this only happens if the first video you opened is not fully loaded yet, or does it happen even if the first video is playing already?

**Comment by Shockwave508** [comment] 2021-12-13 08:55
It happens when the current video is already playing.

**Comment by ktprograms** [comment] 2021-12-13 08:57
I see. Unfortunately I don't think much can be done without logs.

**Comment by Stypox** [comment] 2022-01-27 09:20
Duplicate of #7305, will be fixed by #7704

**Closed by Stypox** 2022-01-27 09:20 UTC
Labels: bug
