### ISSUE TITLE
Problems with import subscriptions

### ISSUE THREAD

**Issue by 53845714nF** [TeamNewPipe/NewPipe#5077] opened 2020-12-03 01:28 UTC
### Checklist

- [x] I am using the latest version - 0.20.5
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Insert subscriptions list as described.

### Actual behaviour
Import List but not all. 
   - All Accounts with special characters at the beginning are ignored.
   - All Accounts with numbers at the beginning are ignored.
   - Accounts that are "user"  (no channel) will not be imported.

### Expected behavior
Insert all subscriptions.

**Comment by mhmdanas** [comment] 2020-12-03 05:23
The checklist is not optional. Please check the two unchecked boxes after you make sure you satisfy them. Ping me after you do that and I'll re-open the issue. Thanks!

**Comment by 53845714nF** [comment] 2020-12-03 15:31
I dont't find any related Issue. 

With kind regards 
Sebastian

**Comment by wisor12** [comment] 2020-12-05 17:12
I've an even bigger issue - no matter how I try to save the subscribtion.json. (via google drive, mail, direct download, selecting everything instead of just subscriptions, different browsers etc.) 

The subscription list stays empty. Changing name from abos.json to subscriptions.json doesn't fix it. It says imported but the list is empty... Also, the .json file is super tiny (3B - not kilobytes but bytes) and I've about 700+ subscriptions. Is that normal?

Perhaps it's the same issue as 0.15 had.

https://github.com/TeamNewPipe/NewPipe/issues/2029

**Comment by mhmdanas** [comment] 2020-12-05 17:16
@wisor12 are you exporting the subscriptions from NewPipe or Google Takeout? If it's the latter, this wouldn't be a NewPipe issue (see #5026).

**Comment by wisor12** [comment] 2020-12-05 17:54
Google Takeout. But I just figured it out. I'm an bloody idiot. On Google Takeout my default account was selected and since it's VERY old and during the Google+ days it got separated from my original main account (kinda a sub-account but linked with the original). So I choose an basically empty youtube account and not the one linked to it. Only an issue for people who have a very, very old google/youtube account.

Ignore it - worked now. I'm just a bit daft and blind.

Thanks anyway!

**Comment by survivor303** [comment] 2020-12-10 19:46
importing from google takeout json file arent supported by newpipe.

**Comment by mhmdanas** [comment] 2020-12-11 06:05
@survivor303 no, it is. See #4720.

**Comment by yesod-github** [comment] 2020-12-30 07:13
Possible regression:

NewPipe [v0.20.8](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.20.8) toasts `"could not import subscriptions"` when attempting to import a non-empty `subscriptions.json` which was downloaded via Google Takeout on PC and transferred via USB to the mobile running Android 7.0.

**Comment by Lolcommie1917** [comment] 2021-08-31 23:33
My file from youtube not working what is going wrong?

**Comment by ShareASmile** [comment] 2021-09-08 02:06
@mhmdanas solved
by #6882 isn't it?

**Comment by opusforlife2** [comment] 2021-09-08 05:06
Indeed. Please wait for version 0.21.10 for the fix.

**Closed by opusforlife2** 2021-09-08 05:06 UTC
Labels: bug
