### ISSUE TITLE
Drawer not under status bar

### ISSUE THREAD

**Issue by danielzgtg** [TeamNewPipe/NewPipe#5630] opened 2021-02-18 10:21 UTC
### Checklist

- [x] I am using the latest version - 0.20.10
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open the app
2. Swipe open the drawer
3. Look at the status bar

### Actual behaviour

The drawer does not go under the status bar. The status bar area to the right of the drawer isn't dimmed either.

### Expected behavior

NewPipe should follow the [Material Design guidelines for drawers](https://material.io/components/navigation-drawer).

This bug is a regression that happened sometime after #3259.

### Screenshots/Screen recordings

Drawer improperly not going under status bar:

![](https://user-images.githubusercontent.com/25646384/108341548-bf6cfc80-71a7-11eb-9b5d-204a007d4573.jpg)

Previous behaviour where it properly goes under the status bar:

![](https://user-images.githubusercontent.com/13389907/77258753-822c8180-6c5b-11ea-9118-1fd57d995d35.png)

### Analysis

This seems to be introduced by 011cc7d3376f14d4f92e3bac9ef5bf2c8483b789. Reverting it and going further to set the `statusBarColor` to `@android:color/transparent` fixes this particular problem. However, it ruins the experience in the fullscreen player because it keeps the status bar area red.

### Device info

 - Android version/Custom ROM version: Android 11, OP7Pro_O2_BETA_O1
 - Device model: OnePlus 7 Pro

**Comment by Stypox** [comment] 2021-03-24 08:42
This is the expected behaviour. We don't want to have a status bar of a different color than the toolbar, so it is the same one, and this stays so even after opening the drawer. We needed to do this also because otherwise users with notches or other stange form factors would see text overflowing under the status bar. I'm closing this, as it won't be changed, but if you have a solution that solves everything feel free to open a PR.

**Closed by Stypox** 2021-03-24 08:42 UTC
Labels: GUI, bug
