### ISSUE TITLE
[Enhancement/Feature request?]App does not handle Youtube videos marked as "Premieres".

### ISSUE THREAD

**Issue by Zazie-Lavender** [TeamNewPipe/NewPipe#1865] opened 2018-11-04 07:14 UTC
View a watch page that is known to be a "Premiere", with a known start availability date and time set.

Observe that the video when info is viewed in the subscription screen or in the Video Information shows a "Starts in" but no colon, or time to start; The Info view is not populated with any information on when the video should be available although it does show the content as unavailable. See http://imgur.com/a/sWptncW and http://imgur.com/a/pB69weY

- [ ✓ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ✓ ] I checked if the issue/feature exists in the latest version.
- [ ✓ ] NOT APPLICABLE, not a crash - I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by TobiGr** [comment] 2018-11-04 07:38
Duplicate of #1809

**Closed by TobiGr** 2018-11-04 07:38 UTC

**Comment by TobiGr** [comment] 2018-11-04 07:40
Thanks for your detailed request. If you want, you can add more information to this ticket: https://github.com/TeamNewPipe/NewPipe/issues/1809
