### ISSUE TITLE
no songs/videos on youtube  work

### ISSUE THREAD

**Issue by Yvethyst** [TeamNewPipe/NewPipe#2616] opened 2019-09-11 18:57 UTC
no video on youtube works, in my playlist or searched, it says "impossible to play this stream"

french version of the app, , 
App version 0.17.1
Os ;Android 7.0
Device : Wiko U pulse Lite

i tried re-installing by using F-droid or clearing the cache, neither worked,i also tried turning the phone off for a while then turning it back on, doesnt work either , neither data nor wifi work

![image](https://user-images.githubusercontent.com/55207599/64726292-94707a80-d4d6-11e9-8048-5a366aecb8b4.png) this is what any video goes to

**Comment by TobiGr** [comment] 2019-09-11 19:06
Duplicate of #2615

**Closed** 2019-09-11 19:05 UTC
Labels: duplicate
