### ISSUE TITLE
App crash when opening the list of downloads

### ISSUE THREAD

**Issue by franzalex** [TeamNewPipe/NewPipe#6767] opened 2021-07-26 08:24 UTC
### Checklist

- [x] I am using the latest version - 0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open the hamburger menu. 
2. Press the download menu item.
3. App crashes and restarts with the exception details. 

### Actual behavior

The app crashes and restarts with the exception log pasted below 

### Expected behavior

The list of downloads should be shown. 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GH
* __Content Language:__ en
* __App Language:__ en_GH
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4209)
	at android.app.ActivityThread.access$1500(ActivityThread.java:242)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1937)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4197)
	... 8 more

```
</details>
<hr>

### Device info

 - Android version: Android 11 Build 59.1.A.2.96 with May 2021 security updates
 - Device model: Sony Xperia 10 II (XQ-AU52)

**Comment by CamJ30** [comment] 2021-07-26 10:37
Same issue for me as well. Don't know what to do at this point. :/

**Comment by mhmdanas** [comment] 2021-07-26 13:25
Duplicate of #6687.

**Closed by mhmdanas** 2021-07-26 13:25 UTC
Labels: bug
