### ISSUE TITLE
video player error

### ISSUE THREAD

**Issue by siuslaw** [TeamNewPipe/NewPipe#7137] opened 2021-09-21 11:37 UTC
### Checklist

- [x] I am using the latest version - 0.21.9 - The latest available version on F-Droid
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to a video in your subscription tab.
2. Watch the video.
3. Exit out of the app and pause the video via the notification hub.
4. Go back on NewPipe and the video won't play.

(It doesn't always show up, happens to me once around every week.)

### Actual behavior

Video will be paused and you will see the thumbnail, if you click the video play button it will crash and show you the error logs.

### Expected behavior

Video will be paused and you will see the thumbnail, if you click the video play button it will crash and show you the error logs.

### Screenshots/Screen recordings
Wasn't able to get any screenshots.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@88fce63 with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'long org.schabi.newpipe.player.playqueue.PlayQueueItem.getRecoveryPosition()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4759)
	at android.app.ActivityThread.access$2000(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2186)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long org.schabi.newpipe.player.playqueue.PlayQueueItem.getRecoveryPosition()' on a null object reference
	at org.schabi.newpipe.player.Player.handleIntent(Player.java:674)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:129)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4741)
	... 8 more

```
</details>
<hr>

**Comment by litetex** [comment] 2021-09-21 18:53
Thank you for the issue!

This is a duplicate of #6652 / #7029

You can upvote the issues :)

**Closed by litetex** 2021-09-21 18:53 UTC
Labels: bug
