### ISSUE TITLE
Changing to different video quality takes much time

### ISSUE THREAD

**Issue by champion174** [TeamNewPipe/NewPipe#3596] opened 2020-05-16 04:38 UTC
The video plays smoothly when it is set to 360p and whenever i need to change it to 480p or sometimes to 720p, it takes very long time to change or sometimes I need to restart the app.
Hope you'll resolve it soon.

**Comment by Stypox** [comment] 2020-05-16 19:40
Caused by / duplicate of #2415

**Closed by Stypox** 2020-05-16 19:40 UTC
