### ISSUE TITLE
background player resume issue

### ISSUE THREAD

**Issue by snowzhangy** [TeamNewPipe/NewPipe#4355] opened 2020-09-29 21:28 UTC
### Version

-0.19.8

### Steps to reproduce the bug

1. use a bluetooth speaker or headphone and open a video and use background player to play it wirelessly.
2. turn of the speaker/headphone
3. turn on the speaker / headphone and click the resume button
result: no matte how many times you clicked, the audio won't resume , looks the play button is freezed.
all you can do is close everything and restart newpipe and find that video and redo from step1
i have this issue everything when i want to listen some music when i 'm driving. After i park my car and come back start again. 
I use my car speaker in bluetooth mode.

**Comment by opusforlife2** [comment] 2020-09-29 21:34
Please try this with the APK in the pinned RC thread.

**Comment by snowzhangy** [comment] 2020-09-29 21:45
> Please try this with the APK in the pinned RC thread.

Looks new 0.20.0RC4 doesn't have the background player button anymore. it's a headphone icon in 0.19.8

**Comment by opusforlife2** [comment] 2020-09-29 21:48
Nothing was changed regarding the background player button. It's still there below the thumbnail, along with the pop-up button.

**Comment by snowzhangy** [comment] 2020-09-29 22:02
> Nothing was changed regarding the background player button. It's still there below the thumbnail, along with the pop-up button.
thank you I found it! Originally i use the headphone icon after click the down down arrow icon on the right top of the video.
I just tested in my car, the resume issue is still happen.
after turn off the car and back on. the audio won't play anymore and click the playback button won't do anything.

**Comment by opusforlife2** [comment] 2020-09-30 05:07
Alright, thanks for confirming!

**Comment by Stypox** [comment] 2020-09-30 13:48
Duplicate of #2397 (sorry, that issue was closed by accident)

**Closed by Stypox** 2020-09-30 13:48 UTC
Labels: bug, player
