### ISSUE TITLE
Export/Import Playlists.

### ISSUE THREAD

**Issue by MavisCelus19201** [TeamNewPipe/NewPipe#7866] opened 2022-02-12 20:07 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The ability to import/export playlists in a similar way to subscriptions.

### Why do you want this feature?

Easier backup and modification of playlists, on top of potential support from Freetube to backup playlists from Newpipe.

### Additional information

Either in the content tab in settings or near the top of the playlist tab

-------------
Import from:

Previous Export
Freetube

Export to File
------------

Similar to the subscriptions tab.

**Comment by SameenAhnaf** [comment] 2022-02-13 00:51
Duplicate of #1348 & #4076.

**Closed** 2022-02-13 14:09 UTC
Labels: enhancement, duplicate

**Comment by qwirl** [comment] 2025-04-05 00:17
Please notice, that this issue/feature request isn't complete, as proposed per #4076
