### ISSUE TITLE
[Suggestion] Raise the lowest brightness gesture value by one 

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2660] opened 2019-09-23 18:19 UTC
A long standing 'bug' in NewPipe has been that, when turning the brightness down all the way via gesture, the brightness will reset to the system value (instead of the lowest value). 

Could this issue be remedied by simply raising the lowest value a digit or two? I.e. instead of lowering to 0 and being unregistered for lack of a better term, it lowers to 1 or 2. 

 **Problem**: Lowest brightness gesture value causes system to ignore NewPipe dictated brightness

**Suggestion**: Raise the lowest value to prevent the NewPipe dictated brightness from reaching the point where it gets ignored by the system

Ps. my app wont allow me to search issues. If this already exists, please go ahead and close.

**Comment by Gymcap** [comment] 2019-09-26 20:47
It seems this is the same approach that VLC has taken. I cannot point to a specific line of code, but VLC happens to show you the percentage of the brightness value when changing it via gesture. 

When using this gesture to set the lowest value, VLC displays it as 1% brightness.

**Comment by gkeegan** [comment] 2019-09-26 21:28
This could be applied to audio as well. For me, when at very low audio levels with the gesture (but not all the way down), no sound is output.

**Comment by Stypox** [comment] 2019-09-29 13:20
Duplicate of #1778

**Closed by Stypox** 2019-09-29 13:20 UTC
Labels: enhancement, good first issue, player
