### ISSUE TITLE
Provide ability to search within a channel

### ISSUE THREAD

**Issue by wqsrz** [TeamNewPipe/NewPipe#5909] opened 2021-03-25 06:29 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
YouTube's desktop version has a great feature to search videos within the channel. It would be much better if this feature could be brought to the NewPipe.

#### How will you/everyone benefit from this feature?
Sometimes it is very difficult to find a particular video from a particular channel which has thousands of videos. Most of the time default search algorithm shows results of similar titles from other popular channels or trending videos. The desired target becomes a challenge. In that case, this option will be very useful.

**Comment by SameenAhnaf** [comment] 2021-03-25 07:00
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5669

Your wish: Provide ability to search within a channel
My wish: Sort, order and set limit of videos

If you use "Include/Exclude" function from "Set limit" button, you will be able to search for videos with or without your mentioned words.

**Comment by wqsrz** [comment] 2021-03-25 08:13
I think there is a difference. Your method is quite complicated and could not be understandable for every Tom, Dick and Harry. It doesn't specify a simple specific search.

**Comment by mhmdanas** [comment] 2021-03-25 09:31
I think this is a duplicate of #5441.

**Closed by mhmdanas** 2021-03-25 09:31 UTC
Labels: enhancement

**Comment by SameenAhnaf** [comment] 2021-03-25 09:41
@mhmdanas I think, #5902 should stay open and #5441 should get closed. Search within any feed is a necessary feature.

**Comment by mhmdanas** [comment] 2021-03-25 09:43
@SameenAhnaf I think they're different things. #5902 requests (as I understand) the search bar used to search globally for videos to be always present, which #5441 talks about one specifically for the channel page.

**Comment by SameenAhnaf** [comment] 2021-03-25 10:07
@mhmdanas Thanks for the clarification!
