### ISSUE TITLE
Merge DB

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#4551] opened 2020-10-17 14:41 UTC
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be nice if you add feature of merging the databases. 

#### Is your feature request related to a problem? Please describe it

I was using my old phone with NewPipe. It got damaged. So, i started using NewPipe a different phone. But now that old phone is repaired, i'd like to merge both the history/subscription.

#### How will you/everyone benefit from this feature?

I cant think of smth not already obvious at the moment.

**Comment by opusforlife2** [comment] 2020-10-17 19:30
Duplicate of #4076.

**Closed by opusforlife2** 2020-10-17 19:30 UTC
Labels: enhancement

**Comment by yashpalgoyal1304** [comment] 2020-10-17 19:42
can that issues' description be updated to reflect the long discussion's summary?? 

i am coming from gitlab and there it can be. dont know how things work here on gh.
