### ISSUE TITLE
Localized titles for videos and channels don't work

### ISSUE THREAD

**Issue by Psycho-A** [TeamNewPipe/NewPipe#5401] opened 2021-01-13 13:38 UTC
Many videos and user channels on YouTube have now regional-languaged names for their channels and uploaded viedos, f.e. English titles and native language titles. Depending on the country and regional settings, we see the adapted names instead of the originals. In NewPipe this feature is broken. I see English titles even for my Russian channels which displays Russian texts in browsers and Google's YT client. For example, this channel: https://www.youtube.com/channel/UChlMWuw9JFZ5LNBe_fMoJEg . Please pay attention on this.

**Comment by realmain** [comment] 2021-01-14 04:18
Duplicate of #3185

**Closed** 2021-01-14 15:34 UTC
Labels: bug
