### ISSUE TITLE
default tabs

### ISSUE THREAD

**Issue by 1emirozdemir** [TeamNewPipe/NewPipe#2375] opened 2019-05-31 22:40 UTC
hello normally there are 3 tabs in the app's default, these feed, subscribers and playlist, how we can add new tabs

**Comment by gkeegan** [comment] 2019-05-31 23:29
Do you wish to add new tabs to the default in the code or manually add some to your installation?

---

To add to your installation, go to Settings>Appearance>Contents of Main Page and tap the plus.

---

To add to the default, you will need to edit [this file](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/MainActivity.java) at some point after line 121. You may also have to edit the strings.xml file depending on what you are doing. 

---

I hope I have answered your question sufficiently well.

**Comment by 1emirozdemir** [comment] 2019-06-01 09:00
yes I want to change the default in the code but I don't understand what to do in mainactivity

**Comment by TobiGr** [comment] 2019-06-02 09:29
So you basically want to make changes to the code, don't you?

**Comment by 1emirozdemir** [comment] 2019-06-02 10:40
yes

**Comment by 1emirozdemir** [comment] 2019-06-02 21:51
please help me

**Comment by Stypox** [comment] 2019-09-29 13:56
Duplicate of #2221

**Closed by Stypox** 2019-09-29 13:56 UTC
