### ISSUE TITLE
Videos refuse to play unless I fiddle with the quality settings

### ISSUE THREAD

**Issue by TippyLion28** [TeamNewPipe/NewPipe#3010] opened 2020-01-25 19:52 UTC
- [yes] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [yes] I checked if the issue/feature exists in the latest version.
- [n/a] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Every time I load a video it stays on a black loading screen until I change the resolution which is really annoying. Doesn't matter what default resolution I set, it needs to be changed before the video plays.

**Comment by gkeegan** [comment] 2020-01-25 20:00
I have the same issue, although setting default to 720 works fine.

**Comment by TheFrenchGhosty** [comment] 2020-01-25 22:19
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2509

**Closed** 2020-01-26 01:51 UTC
