### ISSUE TITLE
[Feature request] Add channel group picker

### ISSUE THREAD

**Issue by nhfo** [TeamNewPipe/NewPipe#3636] opened 2020-05-22 20:39 UTC
#### Describe the feature you want
There should be an option, in long press menu for channels, to display a channel group picker (similar to subscription picker proposed in #3589).

This picker will behave  same as the picker described in #3589, but instead of selecting/deselecting channels, it will select/deselect channel groups.

#### Is your feature request related to a problem? Please describe it
When subscribing to a new channel, one would also want to add it to some channel groups, as of now it has to be done one group at a time (channel group > long press > select subscription), which is tedious, more so if there are large number of subscriptions. Adding and removing channel from several groups should be easier.

**Comment by Stypox** [comment] 2020-05-23 07:13
Duplicate of #3588 and others

**Closed by Stypox** 2020-05-23 07:13 UTC
Labels: enhancement
