### ISSUE TITLE
Unrecoverable Player Error

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3036] opened 2020-01-29 19:58 UTC
720p/480p won't play. 
there is a message w/o actual error page, just a small message that disappears after a second. 

360p works fine.

v18.2

**Comment by Stypox** [comment] 2020-01-30 06:04
Duplicate of #2673

**Closed by Stypox** 2020-01-30 06:04 UTC

**Comment by eladkarako** [comment] 2020-01-30 21:46
doesn't seems to be related, it isn't webm, but mp4 stream.

**Comment by Stypox** [comment] 2020-01-31 06:04
Both issues are about missing resolutions and would be fixed by the same thing, most probably
