### ISSUE TITLE
Add loop feature

### ISSUE THREAD

**Issue by FrankFacundo** [TeamNewPipe/NewPipe#8436] opened 2022-05-24 21:54 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

In player interface, there will be available a button that allow to loop the current video.

### Why do you want this feature?

- People who want to repeat a song.
- People who want to repeat a video playlist.

**Comment by SameenAhnaf** [comment] 2022-05-25 03:10
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6914

**Comment by mhmdanas** [comment] 2022-05-25 15:54
Note that you can loop by using the loop button on the media notification.

**Closed by mhmdanas** 2022-05-25 15:54 UTC
Labels: enhancement
