### ISSUE TITLE
Add twitch support for downloads

### ISSUE THREAD

**Issue by Pass1Vlax** [TeamNewPipe/NewPipe#7818] opened 2022-02-05 13:59 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

I'd appreciate it if you could add twitch (like YouTube, SoundCloud etc)

#### Why do you want this feature?

NewPipe's UI is very user friendly so it would be very nice if you could add support for downloading (and if it's possible also viewing) lives from twitch. Is a pain in the *** to find third party sites for download and then waiting ages for it to be transferred to my phone

**Comment by SameenAhnaf** [comment] 2022-02-05 16:05
Duplicate of https://github.com/TeamNewPipe/NewPipeExtractor/issues/76

**Closed** 2022-02-07 20:39 UTC
Labels: enhancement
