### ISSUE TITLE
twice sceen rotation on back button

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#1993] opened 2019-01-10 06:07 UTC
When I start to play video NewPipe rotates screen horizontally and shows video fullscreen --- all is correct.

But when I press back button the following happens:
It shows the un-rotated screen as before I press play --- it's also correct.
It rotates previous screen horizontally and back vertically --- it's incorrect superfluous action.

**Comment by opusforlife2** [comment] 2019-09-17 05:35
Hey! This happens to me too! I thought this was a ROM specific issue because I get the exact same behavior in VLC. I'll see if the VLC Android Gitlab has this issue opened there.

**Comment by opusforlife2** [comment] 2019-09-17 21:23
@532910 What is your phone model and OS?

**Comment by opusforlife2** [comment] 2019-09-17 21:59
Okay, so I've opened an issue on the VLC Android Gitlab. https://code.videolan.org/videolan/vlc-android/issues/1040

Writing the bug report led me to investigate properly. When the video being played is in the opposite orientation from the phone, then the extra double rotation happens. If both are in the same orientation, it doesn't.

Steps to reproduce:
1. Lock phone in a certain orientation.
2. Make video have the opposite orientation.
3. Back out of video.

Where Newpipe differs from VLC is that Newpipe instantly backs out in all cases, whereas VLC freezes for a second or two before backing out.

**Comment by 532910** [comment] 2019-09-18 07:03
OP3T @ lineageos 16
But I haven't seen this issue for a month or more.

**Comment by opusforlife2** [comment] 2019-09-18 08:26
If you've ever used LOS 15.1, did it happen on that version?

**Comment by 532910** [comment] 2019-09-18 08:28
before 16 I used 15.1, possible it's 15.1 issue, not newpipe, could you try to upgrade to 16?

**Comment by opusforlife2** [comment] 2019-09-18 20:32
Well, a VLC maintainer replied that apps don't handle rotation, the OS does. This, combined with the fact that we both faced this on LOS 15.1 and that it happens on multiple apps (I was finally able to reproduce this on mpv-android as well) is enough evidence to conclude that this is an LOS 15 bug, which was probably fixed in LOS 16. Unless any contradictory evidence comes to light, I think we can close this issue, @Stypox. :)

**Closed** 2019-09-18 21:00 UTC
Labels: GUI, bug
