### ISSUE TITLE
Please remember unlink setting in speed control dialog between videos

### ISSUE THREAD

**Issue by fluffynuts** [TeamNewPipe/NewPipe#2412] opened 2019-06-20 17:11 UTC
I rarely watch YouTube videos at 1x. I never want sped up videos sounding like chipmunks. Every time I adjust tempo, I have to unlink first so as not to get adjusted pitch. The final result is like the speed control on YouTube web: the video plays faster and sounds sounds normal, just shortened.

Please just let the speed control dialog remember my preference to unlink. Everything else about NewPipe is awesome: I often recommend to others.

**Comment by Stypox** [comment] 2019-06-20 20:12
Probably duplicate of #1994

**Comment by fluffynuts** [comment] 2019-06-21 17:55
sorry, I did have a quick look at open issues, but didn't spot #1994 ):

**Closed** 2019-06-22 08:54 UTC
