### ISSUE TITLE
Automatically generated yt channels are not supported

### ISSUE THREAD

**Issue by Sam4000der3** [TeamNewPipe/NewPipe#8086] opened 2022-03-20 19:20 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1) search a artist you like

2)  Open the artist overview that Youtube offers you.

f. e. https://youtube.com/channel/UCakjxTy9HS0-fuKkAY2VrVA 

3) Open the Channel with NewPipe (Show Information)

If the channel was automatically generated by YouTube, the channel name will end with "- Topic" and will not display any videos.

### Expected behavior

All YouTube Videos and Playlists should be displayed

### Actual behavior

Newpipe does not show videos and so you have to share each album/playlist individually with newpipe (via yt Website or app) .

### Screenshots/Screen recordings

Youtube App Version of the channel 

<img alt="Screenshot_2022-03-20-20-17-33-402_com google android youtube" src="https://user-images.githubusercontent.com/101992430/159179002-837b98ce-dae0-4179-92b6-e25c4f239d55.jpg" height=600 />

NewPipe Version of the Channel 

<img alt="Screenshot_2022-03-20-20-18-00-292_org schabi newpipe" src="https://user-images.githubusercontent.com/101992430/159179020-5dbede76-44fa-403c-90d1-593888e2b68f.jpg" height=600 />

**Comment by litetex** [comment] 2022-03-20 20:00
Duplicate of #5336

**Closed by litetex** 2022-03-20 20:00 UTC
Labels: bug

**Comment by TiA4f8R** [comment] 2022-03-20 20:01
> - [X] I made sure that there are _no existing issues_ - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

No you didn't, because it's a duplicate of #5536. Please avoid opening new issues before checking properly the exisiting ones first. Thank you.

**Comment by Sam4000der3** [comment] 2022-03-20 20:08
> > - [X] I made sure that there are _no existing issues_ - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
> 
> No you didn't, because it's a duplicate of #5536. Please avoid opening new issues before checking properly the exisiting ones first. Thank you.

It's my first time use github. 😅 Sorry. Rookie /newbie mistake.

ps: my issue has more details / information.
