### ISSUE TITLE
Constant video buffering

### ISSUE THREAD

**Issue by heineraa** [TeamNewPipe/NewPipe#7639] opened 2022-01-09 23:29 UTC
### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.(I found some similar issues but not 100% duplicates 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

It doesnt matter which video i choose after 20-30 seconds it will buffer for 5 up to 10 seconds or.lomger and after watching for about 30 seconds, buffering will repeat. When i watch the same video with firefox on youtube is totally fluent.

### Expected behavior

I would like to watch videos as smooth as before.

### Logs

Observing the behaviour with logcat, there are a ton of errors like this one for example:

[SurfaceView[org.schabi.newpipe/org.schabi.newpipe.MainActivity]#30(BLAST Consumer)30](id:5d2600000022,api:3,p:23846,c:23846) detachBuffer: slot 17 is not owned by the producer (state = ACQUIRED)

Or this one(thats not shown hundreds of time, but often and it appear after the buffer error)

onPlaybackStateChanged(): org.schabi.newpipe tried to update with no new data

It looks like newpipe is ordering new data but in connection with the videobuffer, nothing will be received.
### Device info

 - Android version/Custom ROM version: Grapheneos Android 12
 - Device model: Google Pixel 3

**Comment by TiA4f8R** [comment] 2022-01-10 07:43
I think this is a duplicate of #6949. You can find a potential fix on my last comment.

Closing as a duplicate of this issue. If you don't think that's a duplicate of #6949, please explain why and I will reopen this issue. Thank you.

**Closed by TiA4f8R** 2022-01-10 07:43 UTC
Labels: bug
