### ISSUE TITLE
[feature request] Publish NewPipe on XDALabs for easy updating and distribution

### ISSUE THREAD

**Issue by zilexa** [TeamNewPipe/NewPipe#1760] opened 2018-09-24 20:09 UTC
- [X ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X ] I checked if the issue/feature exists in the latest version.
- [X ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Would it be possible to publish this app on XDALabs? The more I move away from Google Services the more need I have for an alternative. Fdroid never did it for me (lots of notifications of updates while it's already updated etc). 
YouTube Vanced is also on XDA Labs so I can imagine NewPipe would be allowed as well.

**Comment by Serkan-devel** [comment] 2018-12-02 10:32
Doesn't it work on F-Droid already?

**Comment by zilexa** [comment] 2018-12-06 08:43
Sure, but F-droid doesn't contain all apps. This request is to publish it in the XDA Labs app store.

**Comment by TobiGr** [comment] 2018-12-07 12:54
Duplicate of #925

**Closed by TobiGr** 2018-12-07 12:54 UTC
