### ISSUE TITLE
[REQUEST] Why you add PIP mode to play the video in the Overlay

### ISSUE THREAD

**Issue by Mikesew1320** [TeamNewPipe/NewPipe#2455] opened 2019-07-10 20:18 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by mikesew1320** [comment] 2019-07-10 20:20
It becomes more better and valuable when you add this feature to the app, also try to make it work at least for Android 5 and greater. This helpless to be used by more devices.

**Comment by EmberHeartshine** [comment] 2019-07-14 23:12
Picture-in-Picture is weaksauce compared to the pop-up window.

**Comment by mikesew1320** [comment] 2019-07-15 11:29
Ok, what about the pop up window. I think it's more usable for llwer android versions

**Comment by mikesew1320** [comment] 2019-07-15 11:33
Ok, what about the pop up window. I think it's more important for users
havingr lower android versions.

Can you add it or not?

**Comment by EmberHeartshine** [comment] 2019-07-18 19:58
I think there's a bit of a miscommunication. Picture-in-Picture is [an Android feature](https://developer.android.com/guide/topics/ui/picture-in-picture) allowing video-centric apps to continue playing in a "minimized" view, similar to NewPipe's pop-up player but with fewer options. NewPipe already implements its own version of this via the pop-up player, and it works on every Android version that NewPipe supports.

**Comment by Gymcap** [comment] 2019-07-28 00:17
I have to agree. Adding PIP seems like a downgrade compared to the existing overlay.

**Comment by Scrumplex** [comment] 2020-03-24 14:00
What about making this configurable? Meaning: One can choose between them in the settings (if on Oreo or newer)

**Comment by B0pol** [comment] 2020-05-10 17:20
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2223 https://github.com/TeamNewPipe/NewPipe/issues/712

**Closed by B0pol** 2020-05-10 17:20 UTC
Labels: device/software specific, enhancement, player
