### ISSUE TITLE
Background Player inaccessible, Notification area no controls

### ISSUE THREAD

**Issue by PrimeGinseng** [TeamNewPipe/NewPipe#4434] opened 2020-10-07 09:27 UTC
**Phone:  ** Google Pixel 3a XL
**Android ver: ** 11 (Sept 5 update)

After the latest update, enqueuing or playing videos in the background makes the playlist inaccessible without overwriting the queue.

Videos are indeed sent to the background, however pressing on the notification area player does nothing, where it used to bring you the queue list.

The only way I have been able to access the list is by playing another video normally, which brings up the in-app player, where the list icon is available, which overwrites the queue. 

There are no controls in the Notification area either. 
Regarding the seek issue: in the notification area, the seekbar accepts input, but upon seeking, will remove the control from being visible.

**Comment by opusforlife2** [comment] 2020-10-07 09:34
Duplicate of #4433.

**Closed by opusforlife2** 2020-10-07 09:34 UTC
