### ISSUE TITLE
Background player crashes

### ISSUE THREAD

**Issue by kuba-orlik** [TeamNewPipe/NewPipe#2853] opened 2019-12-09 17:44 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I know I'm not supposed to post crash reports because they're usually detected automatically, but this crash does not get detected and does not prompt me to send the crash report via email.

Whenever I play a video in the background and lock the screen, after 20 seconds or so the audio becomes choppy for a moment and then completely stops - the app appears to crash. The issue does seem to appear only when I lock the screen. I don't have background playback issues with any other app on my phone (e.g. AntennaPod)

**Comment by Stypox** [comment] 2019-12-09 20:26
Which phone do you have? This is probably an issue with the battery optimizer closing apps.

**Comment by kuba-orlik** [comment] 2019-12-10 11:34
LG Nexus 5X, running Android 8.1.0 with LineageOS 15.1 (microG). 

Disabling battery optimizations for Newpipe in fact did resolve the issue and now the playback works fine when the screen is off. Thank you for the suggestion!

**Comment by kuba-orlik** [comment] 2019-12-19 15:41
The crashes started happening again, now with battery optimizations disabled

**Comment by justanidea** [comment] 2019-12-19 17:29
It usually happens to me because i dont have a lot of ram, so when i open high ram consuming apps while im using the background player its just kicked out

**Comment by kuba-orlik** [comment] 2019-12-19 17:34
In my case I don't need to open any new apps during background playback. I just turn the screen off and that's it - after around 30 seconds playback stops, the app crashes and no crash report is sent

19 Dec 2019 18:29:26 justanidea <notifications@github.com>:

**Comment by Stypox** [comment] 2019-12-19 22:05
Are you sure the app crashes, and it is not closed by the system?

**Comment by kuba-orlik** [comment] 2019-12-20 09:25
How can I check that?

**Comment by Stypox** [comment] 2019-12-20 15:41
I have no idea, unfortunately...

**Comment by gkeegan** [comment] 2019-12-20 16:02
Would a logcat show that? @Stypox

**Comment by Stypox** [comment] 2019-12-20 16:08
Maybe

**Comment by TiA4f8R** [comment] 2021-06-12 12:21
@kuba-orlik Are you able to reproduce the bug with the latest version, 0.21.4?

**Comment by TiA4f8R** [comment] 2022-04-08 15:32
@kuba-orlik Again, are you able to reproduce this with the latest version (0.22.1)?

**Comment by kuba-orlik** [comment] 2022-04-09 15:09
I haven't had any issues with NewPipe crashing, but I am using new hardware now and can't use the old one. As far as *I'm* concerned, it's not an issue anymore!

**Comment by opusforlife2** [comment] 2022-04-09 15:16
Alright, thanks for confirming!

**Closed by opusforlife2** 2022-04-09 15:16 UTC
Labels: player, device/software specific
