### ISSUE TITLE
notification must be clearable in the paused state

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#4862] opened 2020-11-11 20:21 UTC
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Pause playback
2. Try to clear the notification

### Actual behaviour

Notification is permanent when playback is paused.

### Expected behavior

Clearable notification when playback is paused.

### Device info

 - Android version/Custom ROM version: LineageOS 17.1
 - Device model: OP3T

**Comment by opusforlife2** [comment] 2020-11-11 20:32
Duplicate of #4335.

**Closed by opusforlife2** 2020-11-11 20:32 UTC
Labels: bug
