### ISSUE TITLE
Age-Gated Videos not Playing

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#890] opened 2017-12-02 18:16 UTC
Videos such as https://www.youtube.com/watch?v=uiuiMDYWP2o, and https://www.youtube.com/watch?v=0OnnWMBS9z0; are age-gated, and while I have all the settings to allow it, they do not play, instead displaying "video not available"/"content not available".

**Comment by theScrabi** [comment] 2017-12-02 19:21
Yes this issue is known to us. We are working on it.

**Comment by johnth3doe** [comment] 2017-12-02 19:32
okay, thank you for the quick response.

**Comment by Serkan-devel** [comment] 2017-12-26 19:06
Maybe you need to change the url to something like https://youtube.com/embed/xj1lB4VpUvI

**Comment by theScrabi** [comment] 2017-12-26 20:41
It should be fixed by now.

**Comment by Serkan-devel** [comment] 2017-12-26 20:45
When will it be rolled out on f-droid?

**Comment by theScrabi** [comment] 2017-12-26 22:51
Should be on its way

**Comment by Cormak** [comment] 2018-01-27 10:05
I'm getting guru meditation errors on every age-restricted video in 0.11.5

**Comment by theScrabi** [comment] 2018-01-27 17:19
Can you please give an example url

**Comment by Cormak** [comment] 2018-01-27 21:44
@theScrabi The links in the OP and every other age-gated video gives me a guru-meditation error in 0.11.5 on 2 of my devices, both running Android 7.1.2.

No matter what link I use I see the error. It should be very reproducible.

**Comment by wb9688** [comment] 2018-01-27 21:47
I'm able to watch the video from the OP, but I'm getting an error for
getting the next videos. @theScrabi: Could we fix this before v1.0.0?

**Comment by TobiGr** [comment] 2018-01-27 21:50
> I'm able to watch the video from the OP, but I'm getting an error for getting the next videos.

Same here on Android 6.0 
@Cormak What error massage do you get exactly?

**Comment by theScrabi** [comment] 2018-01-28 10:10
We should probably.

**Comment by Cormak** [comment] 2018-01-29 00:22
@wb9688 @TobiGr Upon further investigation, there seems to be some variation when trying to view age-gated videos. 

1) Some of them are viewable but show an error at the bottom of the page that says "Sorry, some errors occured.  REPORT". This happens in both the videos in the OP. These videos tend to be of a sexual nature. 

2) Some of them are not viewable at all and just show a fullscreen error log message prompting me to email the error log. I notice that these videos tend to be of a socio-political nature. It's almost as if these videos have even more protection than the ones of a sexual nature, given how these videos are completely unviewable in Newpipe while the sexual ones are still viewable. 

I think it's worth digging into why Newpipe has 2 kinds of reactions to these age-gated videos.

All of the age-gated videos, by the way, are perfectly viewable using Youtube-dl.

**Comment by theScrabi** [comment] 2018-01-29 00:37
I see

**Comment by Serkan-devel** [comment] 2018-01-29 14:48
I guess it has something to do with the sandboxing (shadow banning) feature on youtube

**Comment by Jiikuy** [comment] 2018-02-03 10:55
@wb9688 Same here on Android 7. The video itself is playing but the next videos don't show.

**Comment by karyogamy** [comment] 2018-02-27 07:11
@Cormak 

> Some of them are viewable but show an error at the bottom of the page that says "Sorry, some errors occured. REPORT". This happens in both the videos in the OP. These videos tend to be of a sexual nature.

This is because, for age-gated urls, we are retrieving data from the embedded player rather than the actual webpage. The `REPORT` snackbar is shown since some info available to the regular webpage isn't on the embedded player. However, as this doesn't cripple any other functionality and only provides some error info, it's probably a low priority issue.

> Some of them are not viewable at all and just show a fullscreen error log message prompting me to email the error log. I notice that these videos tend to be of a socio-political nature. It's almost as if these videos have even more protection than the ones of a sexual nature, given how these videos are completely unviewable in Newpipe while the sexual ones are still viewable.

Can you please check if this problem still persists in latest (12.0 beta)? If so, can you provide some urls?

**Comment by karyogamy** [comment] 2018-03-02 00:59
> Some of them are not viewable at all and just show a fullscreen error log message prompting me to email the error log. I notice that these videos tend to be of a socio-political nature. It's almost as if these videos have even more protection than the ones of a sexual nature, given how these videos are completely unviewable in Newpipe while the sexual ones are still viewable.

Found the source of the problem, fixed [here](https://github.com/TeamNewPipe/NewPipeExtractor/pull/73/files#diff-eabbe0ba204823c144fd4551d4ba4f43R541). These are flagged contents that require the user to click to confirm before showing the player. I'm just glad youtube-dl has an example tame enough (compared to the other example I've found) for me to write a test :\

**Comment by speednroll** [comment] 2018-03-02 02:47
great! I'm forward to using the improved Newpipe 👍

**Closed** 2018-09-11 11:58 UTC
Labels: bug

**Comment by eladkarako** [comment] 2019-08-04 19:27
@theScrabi
you should reopen it,
0.16.0.2 still has this issue.

**Comment by TobiGr** [comment] 2019-08-04 19:30
This will be fixed in 0.17.0 which is about to be released soon. You can try out the current RC (see #2482 and #2483)

**Comment by johnth3doe** [comment] 2020-08-19 04:06
Reopened because issue has resurrected itself once again.

**Comment by opusforlife2** [comment] 2020-08-19 09:47
Let's keep the new one open instead.
