### ISSUE TITLE
[Feature Request]: Add "Download" to longpress menu

### ISSUE THREAD

**Issue by msoose** [TeamNewPipe/NewPipe#3305] opened 2020-03-30 17:47 UTC
#### Is your feature request related to a problem? Please describe it
I'd like to send a video to the Download menu/queue without leaving the main video screen.
#### Describe the solution you'd like
Add a "Download" option to the video longpress menu, that will start the video downloading, or add it to the download queue if there is a video already being downloaded.
#### How will you/everyone benefit from this feature?
Reduces the amount of interactions to begin downloading a video
Reduces network usage since details and information about the video don't need to be gathered and rendered

**Comment by Stypox** [comment] 2020-03-30 18:11
Duplicate of #2171

**Closed by Stypox** 2020-03-30 18:11 UTC
Labels: enhancement
