### ISSUE TITLE
Download video directly from background player, history list, or playlist, or channel.

### ISSUE THREAD

**Issue by androidSwDev099** [TeamNewPipe/NewPipe#3491] opened 2020-04-26 00:56 UTC
#### Describe the feature you want

Currently if there's a video I want to download from the background player, history list, or one of my playlists, or a channel, I first have to click on the video before I can access the Download dialogue box for that video.

I propose to add a "Video Download" option to the list of options that come up when the video item in these lists is long-pressed.  I realize the current list is long, but one of the top benefits of NewPipe that I use a lot is the download capability.

Pressing on the "Video Download" option would then bring up the Download dialogue box.  The user would confirm the selections shown and press OK.  This would start the download.  The Download dialogue box would close in the case of OK, up button, or device back button being pressed and NewPipe would continue to display the background player, history list, or one of my playlists, or a channel contents just a before the video download was initiated though this new enhancement Video Download option.

#### How will you/everyone benefit from this feature?

This new enhancement Video Download option would reduce the number of steps required to download a video from the the background player, history list, or one of my playlists, or a channel and allow the user to stay on the screen the download was initiated from with fewer clicks.

To download  video:
Currently from background player:
1. Long-press video in background player
2. Select Details
3. Click Download
4. Click OK on Download dialogue
5. Click phone back button to get back to background player.

With enhancement from background player:
1. Long-press video in background player
2. Select Download Video.  Download dialogue box will appear on top of background player screen.
3. Click OK on Download dialogue.  Download dialogue closes and background player screen still shows.

Two less clicks with enhancement.  Better UX IMHO :) .

**Comment by Stypox** [comment] 2020-04-27 06:19
Duplicate of #2171, would be fixed by #2583

**Closed by Stypox** 2020-04-27 06:19 UTC
Labels: enhancement
