### ISSUE TITLE
[SUGGESTION] Auto read every video of a channel group?

### ISSUE THREAD

**Issue by LittleMat** [TeamNewPipe/NewPipe#3534] opened 2020-05-05 14:21 UTC
#### Describe the feature you want

It would be nice to be able to read every video of a channel group automatically, so when one is finished it goes automatically to the next one (like a playlist). Right now, at the end of a video, it goes to another video (not the next one in the channel group).

#### How will you/everyone benefit from this feature?

It can be very useful for a music channel group for example (so you can subscribe to a bunch of music channels, and easily listen to all the new music).

**Comment by Stypox** [comment] 2020-05-06 06:13
This would probably be fixed by #2583

**Comment by wb9688** [comment] 2020-05-06 06:47
@Stypox: He's requesting the `player_controls` ("Play all", etc. buttons) to be added. I'm pretty sure this is a duplicate though.

**Comment by Stypox** [comment] 2020-05-06 07:08
Oh yes, duplicate of #3362

**Closed by Stypox** 2020-05-06 07:08 UTC
Labels: enhancement, feed
