### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by mohsinanayat** [TeamNewPipe/NewPipe#4139] opened 2020-08-16 07:24 UTC
### Version

-0.19.8

### Actual behaviour

Download percentage goes above 100%
![Screenshot_2020-08-16-12-46-49-09_ee8807d2de22f1831269d80920e33a3b](https://user-images.githubusercontent.com/63046281/90329126-8d43cd80-dfbf-11ea-9a4a-5fc010c5f3f6.jpg)

**Comment by wb9688** [comment] 2020-08-16 08:27
Duplicate of e.g. #4078. Please search for existing issues first.

**Closed by wb9688** 2020-08-16 08:27 UTC
Labels: bug

**Comment by mohsinanayat** [comment] 2020-08-17 02:40
This issue should be fixed as soon as possible.It annoys lot of people....
