### ISSUE TITLE
Watch downloaded videos from newpipe offline within the app

### ISSUE THREAD

**Issue by Newpipeuser** [TeamNewPipe/NewPipe#5214] opened 2020-12-18 12:49 UTC
Hello yes i still want the downloaded videos in the non phone gallery app Can you add a option to watch downloaded videos with newpipes video player and not the phone gallery in verison 0.20.7

### Checklist

- [-->] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ -->] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [--> ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I think it would be nice if you added watching videos on the newpipe player because its like youtube premium and also i think storage space will increase instead of downloading to the phones gallery
Example: also example B would be a good alternative if you cant do example A (add video download button to newpipe on the homescreen menu to make it easier to find your downloaded videos. also use youtube thumbnails when downloading and non file pictures. Lastly add a option to watch downloaded youtube videos on Newpipes video player instead of your phone defult player.

#### How will you/everyone benefit from this feature?
<!-- if you reworked the video downloader to look like youtubes video downloader with the thumbnails and add a option to watch youtube videos offline using newpipes deafult video player would be life chaging becuase you would be able to download more videos from newpipe without your phones storage getting full so quick and i think the newpipe community would love that change.

**Comment by Newpipeuser** [comment] 2020-12-18 12:54
i dont know how to change the labels or do checkmarks on the checklist

**Comment by mhmdanas** [comment] 2020-12-18 13:13
Not anybody can changes labels; it requires permission. To check checkmarks, put `x` between the brackets like this:
```md
- [x] Foo
- [x] Bar
- [ ] Baz
```
Anyway, this is a duplicate of #478.

**Closed by mhmdanas** 2020-12-18 13:13 UTC
Labels: enhancement

**Comment by Newpipeuser** [comment] 2020-12-18 13:54
This is not a duplicate of #478 becuase the #478 form has not been active and has been marked as staled by the bot

**Comment by mhmdanas** [comment] 2020-12-18 13:56
First, activity has nothing to do with this. Second, you are right that it was marked stale, but we have since phased out the stale bot and removed the `stale` label.
