### ISSUE TITLE
Video loading time is too much for YouTube 

### ISSUE THREAD

**Issue by soymadip** [TeamNewPipe/NewPipe#8275] opened 2022-04-21 16:15 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0

### Steps to reproduce the bug

1. Open app
2. Click on any video
3. Play
4. Video will take long time to load even at fast network. 
5. Orignal yt is loading in no time but newpipe is taking. 

### Expected behavior

Video will load Faster. 

### Actual behavior

Taking too much time 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/84225810/164504979-aef7d1e4-19c0-490e-91ec-570f182d23cf.mp4

### Affected Android/Custom ROM version

Android 11 / realme ui 2

### Affected device model

Realme narzo 30

**Comment by TiA4f8R** [comment] 2022-04-21 16:33
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Can't you follow template instructions? Duplicate of #7630.

Please stop reporting this issue, improvements of this YouTube throttling are coming in the next updates.

**Closed by TiA4f8R** 2022-04-21 16:33 UTC
Labels: bug
