### ISSUE TITLE
Unknown error, popping up even on non-feed related actions

### ISSUE THREAD

**Issue by 0Karakurt0** [TeamNewPipe/NewPipe#5545] opened 2021-02-09 01:56 UTC
## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ UA
* __Content Language:__ ru-UA
* __App Language:__ ru_UA
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UCk1hswrx09RKDsa1h_bu77w
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:225)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:67)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:114)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeFeedExtractor.getId(YoutubeFeedExtractor.java:55)
	at org.schabi.newpipe.extractor.feed.FeedInfo.getInfo(FeedInfo.java:39)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getFeedInfoFallbackToChannelInfo$6(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$ep3f-iOI31R0rCiVMC3iRDaEOxw.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeSwitchIfEmptySingle.subscribeActual(MaybeSwitchIfEmptySingle.java:45)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:215)
	... 11 more

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-02-10 08:47
This is a duplicate of #3313. Basically, one of the channels you're subscribed to has been terminated "because [YouTube] received multiple third-party claims of copyright infringement regarding material the user posted." I searched a bit and believe the channel's name is Gloomy Voice. Unsubscribing from that channel should fix that error.

**Closed by mhmdanas** 2021-02-10 08:47 UTC
Labels: bug
