### ISSUE TITLE
Suggestion to add the feature of choosing a specific scene from the video in YouTube to download

### ISSUE THREAD

**Issue by beshoyy** [TeamNewPipe/NewPipe#6812] opened 2021-07-31 06:30 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I want this feature in the application in the upcoming updates, which is to choose a scene or a specific piece of the video to download because I often listen to relaxing music, the duration of which is large, up to 8 hours, and I want, for example, only an hour of them, and I do not want all the video to download

#### How will you/everyone benefit from this feature?
This feature will greatly benefit those who listen to these videos, which helps them to deal with anxiety resulting from the current circumstances, as well as students who want to keep a specific part of the video for the lesson instead of keeping it completely, and it will also help a lot for people who have little memory space on their phones

**Comment by SameenAhnaf** [comment] 2021-07-31 06:59
Duplicate of #5674.

**Closed** 2021-07-31 11:48 UTC
Labels: enhancement
