### ISSUE TITLE
Play List Download

### ISSUE THREAD

**Issue by mablue** [TeamNewPipe/NewPipe#7390] opened 2021-11-10 11:48 UTC
Please add a button or menu button to download playlist videos one by one...:)

**Comment by SameenAhnaf** [comment] 2021-11-10 12:23
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5482. Also, please fill in the template properly. You are not supposed to remove it.

**Comment by litetex** [comment] 2021-11-10 20:40
Duplicate of #5482

**Closed by litetex** 2021-11-10 20:40 UTC
Labels: enhancement, template-ignored

**Comment by mablue** [comment] 2021-11-15 07:45
Thanks for responses 😌
Sorry for small t.i.
But I searched and find out this:
https://github.com/TeamNewPipe/NewPipe/issues/746#issuecomment-443459870

If no one want to work on it just say me where can I find the list variable that contains list of playlist links to write the code my own and than i will send pr
