### ISSUE TITLE
Block channels

### ISSUE THREAD

**Issue by antiPi** [TeamNewPipe/NewPipe#6330] opened 2021-05-18 21:45 UTC
Please add possibly to block Youtube channels so we don't need to suffer under idiotic content in the search or even in the preview... 

### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment] 2021-05-18 23:39
Duplicate of #1815.

**Comment by mhmdanas** [comment] 2021-05-19 14:22
This is a duplicate of #1815 as @SameenAhnaf says. Also, please don't remove the template when opening an issue.

**Closed by mhmdanas** 2021-05-19 14:22 UTC
Labels: enhancement
