### ISSUE TITLE
Third party app

### ISSUE THREAD

**Issue by bphd** [TeamNewPipe/NewPipe#2953] opened 2020-01-13 14:05 UTC
Hi,

YouTube asks now for a reCAPTCHA challenge

It's not a concern considering that we're not robots (i guess). But after that NewPipe stays in browser mode and we can't play the video in the NewPipe environement with his features

(it doesn't happen on cellular network)

- [X ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X ] I checked if the issue/feature exists in the latest version.
- [X ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment] 2020-01-13 17:07
Duplicate of #2896 #2788

**Closed** 2020-01-13 17:08 UTC
