### ISSUE TITLE
Downloaded audio defaulting to external player

### ISSUE THREAD

**Issue by HonourMatopoeia** [TeamNewPipe/NewPipe#2962] opened 2020-01-15 11:35 UTC
I can't play downloaded audio in NewPipe. When I select "play" a Google Play Music pop-up appears, then closes as soon as my screen goes to sleep. I've tried disabling GPM, but then I get another pop-up telling me that there's nothing I can play my downloads on.
Edit: "Use external audio player" is toggled "off".

**Comment by justanidea** [comment] 2020-01-15 12:26
If i remember well google play music doesnt support m4a files. I would advise you to try Vanilla Music that you can find on fdroid, its working well for me.

**Comment by HonourMatopoeia** [comment] 2020-01-15 18:49
> If i remember well google play music doesnt support m4a files. I would advise you to try Vanilla Music that you can find on fdroid, its working well for me.

Thanks very much. I'll give that a try. I'm just a bit puzzled as to why I need an external music player. I've edited my OP to indicate that "Use external audio player" is toggled "off".

**Comment by Stypox** [comment] 2020-01-16 06:21
Duplicate of #478

**Closed by Stypox** 2020-01-16 06:21 UTC
