### ISSUE TITLE
Use the built-in player for downloaded videos

### ISSUE THREAD

**Issue by loub** [TeamNewPipe/NewPipe#6580] opened 2021-06-27 10:20 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be nice if the downloaded could be played with the built-in player.
That would allow to have the same user experience as when watching online content:
- ability to skip or rewind 10s with a double tap
- speed control
- resuming the video where it was stopped
- have a "watched bar"
- etc.

#### Is your feature request related to a problem? Please describe it

Not related to a specific problem.

**Comment by mhmdanas** [comment] 2021-06-27 11:11
Duplicate of #478.

**Closed by mhmdanas** 2021-06-27 11:11 UTC
Labels: enhancement
