### ISSUE TITLE
Video flickers on Redmi 6

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#6755] opened 2021-07-24 14:59 UTC
### Checklist

- [x] I am using the latest version - 0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open vertical or lower resolution video
2. Screen flickers

### Actual behavior

Screen flickers on Redmi 6. This is not ROM dependent. Happened on other ROM on the same device before. Does not happen on other device with the same video. I've only encountered it in this app.

Video link: https://youtube.com/watch?v=0cKusfzhsOc

### Expected behavior

Screen does not flicker

### Screenshots/Screen recordings

I've managed to somehow show how its flickers. It's barely noticeable on screen recordings so I had to use another camera. It's much more intense irl. It's especially noticeable in low resolutions and vertical videos. Compare the flickering to UI elements.

https://imgur.com/a/0uBurr1

### Device info

 - Android version/Custom ROM version: Android 10, LineageOS 17.1
 - Device model: Redmi 6

**Comment by litetex** [comment] 2021-07-25 16:52
> I am using the latest version - x.xx.x 
What version are you using exactly?

Cannot reproduce the problem with the latest version neither on my smartphone nor the android emulator.
Has to be a device specific problem...

Does the issue persist after a reboot and in other apps?

**Comment by IHateTheProgrammingClass** [comment] 2021-07-25 21:54
@litetex Yes, as I said it's only been happening on this type of phone. As I said it has even persisted after a new ROM and as I said, no other app has ever done it. Detailed device specifications like screen size could help narrowing down the problem.

**Comment by ShareASmile** [comment] 2024-02-17 19:29
Closing it, as it cannot be rechecked with its author how app behaves on latest version as its author is a ghost now.

**Closed** 2024-02-17 19:30 UTC
Labels: bug, device/software specific
