### ISSUE TITLE
Show a warning before adding a duplicate video to a playlist

### ISSUE THREAD

**Issue by AnonymousSeal** [TeamNewPipe/NewPipe#4186] opened 2020-08-25 11:02 UTC
#### Describe the feature you want

It would be nice to be alerted when trying to add a video to a playlist that the playlist already contains.

#### How will you/everyone benefit from this feature?

It prevents you from accidentally adding a video to a playlist twice. Especially helpful for long playlists.

Edit: adding keywords for searching: duplicate/entry/entries/playlist/playlists/videos

**Comment by opusforlife2** [comment] 2020-08-25 14:24
Closing #1473 in favour of this. Alerting the user seems more useful than removing after the fact.

**Comment by ahmad-abdelbaset** [comment] 2020-11-04 15:22
Hi, I would like to work on this issue as a part of my project to Master Degree course (Software Construction), I discussed it with my instructor @atamrawi

**Comment by Stypox** [comment] 2020-11-04 16:01
@ahmad-abdelbaset great! Go for it, nobody else has taken it up so far. Thank you :-)

**Comment by ShareASmile** [comment] 2020-11-04 21:55
@Stypox  I think there should { or would be great } to have an option to Both
1. {disallow adding twice the same video to a list} 
2. and {to batch remove all previous duplicates} from video playlists.

As Batch remove duplicates from playlist would greatly help in eliminating duplicates from prevously made playlists by users (especially longer ones) from which manual removal is most difficult.
.. discussion from #1473

**Comment by Stypox** [comment] 2020-11-05 06:32
@ShareASmile @ahmad-abdelbaset yeah, I agree, there should be:
- a new "Remove duplicates" button in the local playlist page's three-dot menu (i.e. in the same place as "Remove watched")
- a small indicator next to each local playlist in the "Add to playlist" dialog meaning that the stream being added is already in there
- a confim dialog that opens when a user tries to add a stream to a local playlist that already contains it

**Comment by ahmad-abdelbaset** [comment] 2020-11-05 15:30
Thank you @Stypox and @ShareASmile, it is really good idea, I will own this one.
@atamrawi

**Comment by ahmad-abdelbaset** [comment] 2021-01-02 07:52
Hey, 
I made a pull request (#5334 ) which is showing a message tells the user if it was any duplicated video/s before and asking him if he like to add it once again. If the user accept, the video will be added. if he reject the video will not be added. @atamrawi

I didn't have time to add the feature of "Remove Duplicated", sorry.

**Comment by infinitewaveparticle** [comment] 2021-07-20 05:47
Any updates on implementing this?

**Comment by SameenAhnaf** [comment] 2021-07-20 06:07
@infinitewaveparticle PR #5334 is in progress.

**Comment by infinitewaveparticle** [comment] 2021-07-25 11:34
@SameenAhnaf I can see that, but it's been 6 months since anything has been posted about it. The contributor @ahmad-abdelbaset was doing this for a course in school which would have in all likelihood ended in May or June at the latest. If he doesn't reply to this it may be safe to assume that it's abandoned.

**Comment by Jared234** [comment] 2022-12-03 21:51
I would like to start working on this. I don't intend to reuse the implementation of @ahmad-abdelbaset, but I will take all of the feedback into account that he received in his PR. I hope this is ok.

**Comment by atamrawi** [comment] 2022-12-05 18:24
Yes Please, go ahead. Ahmad was working on it as part of his course work project and no longer working on it. I guess there is a lot of improvements can be made - What we proposed was something with a limited scope.

**Comment by Jared234** [comment] 2022-12-10 14:51
I am almost done with the implementation, but still have some questions regarding this issue.
The confirm dialog is already done, so I am focusing on the "small indicator next to each local playlist" that shows you whether an item is already in a playlist or not.  

Here is an image of my current solution. The design is obviously just a placeholder:
![Screenshot_20221210-154414](https://user-images.githubusercontent.com/26669009/206860953-354d5f82-787e-4c9c-b787-2acf9a69e21a.png)

I would like to get some input regarding the design of this feature. Is a checkmark the symbol we want to use to indicate that the stream is already in the playlist, or would you choose something different? And what would be the ideal position for such a checkmark?

**Comment by opusforlife2** [comment] 2022-12-10 16:32
I would say that if an item is already in a playlist, that playlist should be greyed out/not selectable, with a simple "(contains video)" added after the playlist name.

But then it's possible that users who want to put a video multiple times in a playlist for some reason will complain. So maybe just the text in brackets and greying out, but not preventing selection of such a playlist.

**Comment by Jared234** [comment] 2022-12-11 14:47
I agree with you that graying out is a good option for indicating that a video has already been added to a playlist. However, I'm not sure about the necessity of using brackets in this case. I feel like just graying it out would be a good enough indicator already. What do you think?

**Comment by opusforlife2** [comment] 2022-12-11 15:07
It won't be intuitive enough by itself for a lot of users, I'm afraid.

Also, "(already added)"? Seems better than the first option. It's inclusive of audios from SC, BC, etc.

Or... an explainer text in its own section under the New Playlist button that literally states: "The greyed out playlists already contain this item." That way playlists with long names won't cause issues.

**Comment by Jared234** [comment] 2022-12-11 16:50
I really like the idea of an extra section that explains this feature to the user.
I'll create a PR within the next few days.

**Comment by atamrawi** [comment] 2022-12-12 15:02
Note that we you may need to perform a check on already created playlist as they may have already contain duplicate videos.

**Comment by Jared234** [comment] 2022-12-12 22:06
I have now created a pull request.
As for the solution proposed by @Stypox, I have added an indicator to the "Add to playlist" dialog to alert users if they are attempting to add a duplicate stream. I have also created a dialog that opens if a user tries to add the same stream item multiple times, allowing them to confirm or cancel their action.
I didn't add the option to remove the duplicated items because it was already done in the closed PR #7703.

**Comment by maverick74** [comment] 2022-12-13 10:21
> I didn't add the option to remove the duplicated items because it was already done in the closed PR #7703.

I'm not sure if that landed...

**Comment by Jared234** [comment] 2022-12-13 14:15
[This comment](https://github.com/TeamNewPipe/NewPipe/pull/7703#issuecomment-1336499774) explains why the PR got closed. However, we may come back to this implementation in the future if we need it.

**Comment by maverick74** [comment] 2022-12-14 12:24
> This round icon should always follow these gestures. Short Press: Add a new duplicate at the bottom of the playlist. Long Press: Remove only the duplicates and keep the one placed in uppermost position.

I have just one question: When does this land???? (i know it's just an idea, but it's a great one. I vote for it!)

**Comment by ShareASmile** [comment] 2022-12-14 15:24
> However, if you think I should give it a try, I will gladly implement this as well.

Yes, that would be awesome if you also implement that. please go ahead.

> However, I believe this would be out of scope for this issue, because it would entail a redesign of the entire dialog

@Jared234 agree with you, let us keep it Simple here.

**Comment by maverick74** [comment] 2022-12-14 15:45
> @maverick74 On the right of each playlist name, a screenshot was added in [#4186 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/4186#issuecomment-1349599561)

I surely expressed myself in a bad way. What i really mean is to ask _**when does your idea get implemented and delivered to us, users?**_ (i understand it's just an idea for now. My expression is just with the intention to say that i loved it and that i would like to get my hands on something similar right away)

**Comment by ShareASmile** [comment] 2022-12-14 16:45
@SameenAhnaf Jared has already said that in 7973 last comment 

> I will take a look at it and write another comment if I am interested.

That explains mostly everything he has intended to say.

**Comment by Jared234** [comment] 2022-12-14 21:04
@ShareASmile Sure, I can do that. I'll create an additional PR on issue #5558 instead of adding it to this PR. I think this is the best solution. Do you agree?

@SameenAhnaf Ok, good to know.
Regarding 7973, @ShareASmile is right. If I'm interested in working on it, I'll just leave another comment. However, I haven't had time to really look into it yet. Before I possibly start working on it, I will let you know.

**Comment by Jared234** [comment] 2022-12-22 21:18
After discussing this feature with @opusforlife2 in the PR, we decided to omit the "Duplicate Video Found" dialog and just use the grayed out playlists to indicate duplicates. However, we want to display a short toast after a user adds a duplicate to one of the playlists. It should say either "Duplicate added" or "Duplicate added x times". Do you think it is important for the user to know how many times this video is already in the playlist? Or do you think this information is unnecessary?

Here is a short poll:
👍 - `Duplicated added`
👎 - `Duplicate added x time(s)`

**Comment by Jared234** [comment] 2022-12-30 15:50
I agree that we should allow the user to deduplicate their playlist. However, I don't think this is the right place to do it. For example, if you implement the deduplicate feature as a button only in the toast, you would have to add the video another time to be able to press this button.
As discussed with @ShareASmile, I will implement this in another issue.
@opusforlife2 Maybe we should open the issue #1473 again?

**Closed** 2023-01-29 09:36 UTC
Labels: feature request, playlist
