### ISSUE TITLE
Option on the popup to return to the video page

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#1386] opened 2018-05-08 21:09 UTC
~~1) Slide the popup to close it~~
2) Option on the popup to return to the video page
~~3) Play the video on the video page~~

**Comment by Somethingweirdhere** [comment] 2018-05-11 17:12
1. This already exists, but you have to slide really quickly off the screen to the left or right.
2. You can currently go to the fullscreen video, but not to the "information page", this should be added.
3. I believe this was worked on #834

**Comment by justanidea** [comment] 2018-05-11 17:17
Its pretty hard to close the popup like that, someone should make it easier..

**Comment by Stypox** [comment] 2019-08-18 19:48
1. Fixed by now
2. This is new, so I'm editing the issue to only include it
3. Duplicate of #528

**Comment by Stypox** [comment] 2019-08-28 18:11
Closing in favour of #1832

**Closed by Stypox** 2019-08-28 18:11 UTC
Labels: GUI, enhancement
