### ISSUE TITLE
Show more useful message in error page

### ISSUE THREAD

**Issue by MkQtS** [TeamNewPipe/NewPipe#8211] opened 2022-04-15 06:31 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Showing *video url* and probable *realtime announcement notice* in the error page which appears when NewPipe cannot play video. Below is a sketch map:

<img alt="Sketch Map" src="https://user-images.githubusercontent.com/81752398/163528990-1b4e72a5-f7af-46de-bf1f-b0a134ea6f4e.png" height=600 />

### Why do you want this feature?

Sometimes a certain technical problem happens and NewPipe cannot work normally. Now the error page shows video name but no video link. A replicable and clickable link is useful for users who want to use other app or browser to watch the video. The error page does not show any interpretative statements for the error state, which may make users feel helpless.

We can improve user experience and reduce probable duplicate and useless reports by adding a realtime announcement in the error page.

### Additional information

You may create a text file that recording some urgent announcements on GitHub. When some systemmatic error happens, just let the client try to access the file and show it to users.

**Comment by markusgerber76** [comment] 2022-04-15 08:03
I would suggest to add a short message "seems NewPipe cannot load the video". Please try with a browser:  "Button Browser Intent"

**Comment by SameenAhnaf** [comment] 2022-04-15 09:48
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6624

**Closed** 2022-04-15 16:29 UTC
Labels: enhancement
