### ISSUE TITLE
Critical bug: Infinite loading for youtube

### ISSUE THREAD

**Issue by AlexNetman** [TeamNewPipe/NewPipe#2647] opened 2019-09-18 20:14 UTC
- [x] I checked if the issue/feature exists in the v0.17.3

 1) Getting infinite loading on youtube Trending page
2) Getting "No results" when trying to search by keyword

Note: Soundcloud and MediaCCC are still working fine in NewPipe.
Note2: SkyTube app has also stop working - videos are searchable but not loading.

**Comment by lu4p** [comment] 2019-09-18 22:09
Which Version are you using?

**Comment by AlexNetman** [comment] 2019-09-19 07:58
I was using v0.17.0  when error happened 3 days ago. Then I updated to v0.17.2 and very soon v.0.17.3 was released. 
So far - I am still having that error in v0.17.3

**Comment by AlexNetman** [comment] 2019-09-20 18:35
Guys, Any recommendations? Reinstall of latest version have not helped. How to get logs?
It looks like not many other guys have faced the issue yet.

**Comment by AlexNetman** [comment] 2019-10-07 22:47
Somehow issue has gone by itself! Both SkyTube and NewPipe players are working fine now.

**Comment by Stypox** [comment] 2019-10-08 05:12
Mmmh strange, YouTube keeps changing things

**Comment by KonoromiHimaries** [comment] 2020-03-14 17:20
![Screenshot_2020-03-14 schabi newpipe](https://user-images.githubusercontent.com/5884000/76686800-779c3780-661e-11ea-9353-428c3bd68835.jpg)

Test https://www.youtube.com/channel/UCZNJmdsIDwtnS-oEZBuymAw

To reproduce

    example video that does not start https://www.youtube.com/watch?v=xlNp86uMBwk
    open video in pip mode

**Comment by KonoromiHimaries** [comment] 2020-03-14 17:21
But if i use menu, then worrk perfect
![Screenshot_2020-03-14 schabi newpipe](https://user-images.githubusercontent.com/5884000/76687029-9b607d00-6620-11ea-9b6c-4b2a52316a55.jpg)

**Comment by gkeegan** [comment] 2020-03-14 17:42
@KonoromiHimaries this is probably because launching the video from the info page causes it to load in 1080p, while going to popup from list causes it to load in 720p, which has no issues with the infinite loading.

**Comment by Stypox** [comment] 2020-04-20 07:06
Duplicate of #2415

**Closed by Stypox** 2020-04-20 07:06 UTC
Labels: bug, requires extractor change, youtube
