### ISSUE TITLE
Make the video stick to the top just like on YouTube, rather than being hidden when scrolling down

### ISSUE THREAD

**Issue by Linerly** [TeamNewPipe/NewPipe#8223] opened 2022-04-15 23:27 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Most of the time when I am watching a video, I often scroll down to view the comments/related videos/description, but scrolling down makes the video hidden which doesn't happen on YouTube's Android app

### Why do you want this feature?

So that the video is watchable while being able to scroll down to view the comments/related videos/description

### Additional information

Perhaps like this below

https://user-images.githubusercontent.com/47475676/163651880-9a6e5c6c-70c2-46bf-ba09-985ffa7a9cca.mp4

…or like this below, which I prefer because the visible thing is near the video and not being separated by the title/buttons

https://user-images.githubusercontent.com/47475676/163652004-5787c740-fc6c-4206-8c68-724b2c61bb85.mp4

**Comment by SameenAhnaf** [comment] 2022-04-16 12:05
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/448

**Closed** 2022-04-16 13:04 UTC
Labels: enhancement
