### ISSUE TITLE
Background subscription scan service to generate notifications

### ISSUE THREAD

**Issue by foxMclion** [TeamNewPipe/NewPipe#3372] opened 2020-04-05 18:01 UTC
#### Describe the feature you want
I think it would be nice if you guys added a new feature in the form of a background service for checking updates for the channels added to Newpipe in the form of feed subscriptions. Currently the feed update is done manually; with this proposed new feature a background service would check for feed updates on a specified interval, and compare with previous updates, and display notifications for newly found videos. 

#### Is your feature request related to a problem? Please describe it
I have no problem with manually checking feed updates on Newpipe itself, it works fine, but I wouldn't find a reason to have youtube installed if Newpipe provided notifications. With Newpipe I only have youtube installed because of the notifications really, as I, along with many other people that I know, don't use youtube as a social network.

#### How will you/everyone benefit from this feature?
It would be a very nice convenience to have notifications without youtube. One of the value propositions of Newpipe as I see it is the ability to help follow youtube content without having to create a google account and be subject to their terms. By having its own notifications system Newpipe will maximize its value proposition and further privacy choice on the net.

I know there has been many issues opened before like this one but they are from some time ago, and I wanted to articulate the concept better if possible.

**Comment by Stypox** [comment] 2020-04-10 07:20
Duplicate of #719 and #1086, closed by #2335

**Closed by Stypox** 2020-04-10 07:20 UTC
Labels: enhancement, feed
