### ISSUE TITLE
Open in Browser

### ISSUE THREAD

**Issue by cyber199** [TeamNewPipe/NewPipe#4529] opened 2020-10-16 11:00 UTC
### Checklist

- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I would very much like to see an Open in Browser button, as was under the right hand overflow menu in previous versions, make a return.  This makes opening the video in an external browser possible with a minimum of clicks.  Using the "Play Video>Tap to Show Controls>Expand Action Bar>Share>Copy to Clipboard" flow is unnecessarily long winded - especially if the user has already watched the video and has to play it again to access these functions - and is not optimal when a simple "Overflow Menu>Show in Browser" could replace this.

Usage scenario: a user watches videos with NewPipe to avoid tracking from the YouTube algorithm, but wishes to quickly open the video in a browser where they are logged in, in order to make a comment on the video.

#### Is your feature request related to a problem? Please describe it

This is related to the new "unified player" which others have considered a feature regression.  While I don't disagree with the new unified player, the problem here is that the new player UI removes the top action bar where functions such as Open in Browser (among other missing or moved functions such as Share and Send to Kodi) used to be housed.  Some of these functions are replicated while the video is playing, but Open in Browser is missing.

#### How will you/everyone benefit from this feature?

I believe the reintroduction of the Open in Browser function will be a quality of life addition for casual users of NewPipe and YouTube who wish to participate in the YouTube community, but are concerned about being tracked by "the algorithm".

**Comment by opusforlife2** [comment] 2020-10-16 11:08
Duplicate of #4039.

**Closed by opusforlife2** 2020-10-16 11:08 UTC
Labels: enhancement

**Comment by cyber199** [comment] 2020-10-16 11:20
Having explored further, I found #4039 which I hadn't seen before.  As this is a possible duplicate of that issue (Open in Browser is only mentioned in passing there, whereas I see it as a missing feature upon which I relied somewhat) I'm thinking of closing this issue myself.

**Comment by cyber199** [comment] 2020-10-16 11:21
> Duplicate of #4039.

Never mind, its been done
