### ISSUE TITLE
Add New Menu To Add to Playlist for suggested videos

### ISSUE THREAD

**Issue by IamJithendra** [TeamNewPipe/NewPipe#1251] opened 2018-04-03 11:15 UTC
Along with the Option to Enque on Background and Enqueue on Popup option on Next Videos Add Option to add to Playlist

**Comment by theScrabi** [comment] 2018-04-03 11:47
I'm sorry, I don't quite understand the sentence 😕

**Comment by IamJithendra** [comment] 2018-04-04 10:39
![screenshot_2018-04-03-16-37-24](https://user-images.githubusercontent.com/33452200/38303023-6879ec10-3822-11e8-9757-ca79a45a7255.png)

Along With These Option Add "Add to Play List" Feature

**Comment by theScrabi** [comment] 2018-04-04 18:12
yes this should be done right :+1:

**Comment by Stypox** [comment] 2019-07-19 13:28
Duplicate of #1142 
Will be fixed in #2368

**Closed by Stypox** 2019-07-19 13:28 UTC
Labels: enhancement
