### ISSUE TITLE
available on pc

### ISSUE THREAD

**Issue by tarbear123** [TeamNewPipe/NewPipe#6629] opened 2021-07-08 17:30 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### How will you/everyone benefit from this feature?
it will affect everyone that likes newpipe and wants it on pc's

**Comment by ShareASmile** [comment] 2021-07-08 18:06
Duplicate of #1051

**Comment by Gottarocket** [comment] 2021-07-08 18:27
Install freetube

**Comment by tarbear123** [comment] 2021-07-08 18:33
> Install freetube

does it have the features of newtube and is there a windows app?

**Closed** 2021-07-08 18:39 UTC
Labels: enhancement

**Comment by Gottarocket** [comment] 2021-07-08 18:50
Yes you can download it to all os https://freetubeapp.io/#download
