### ISSUE TITLE
[Just another feature], Implement Live Chat!

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#2334] opened 2019-05-09 13:08 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Just want to add the live chat to the live streams. Thanks

**Comment by Serkan-devel** [comment] 2019-05-19 12:03
Is there a branch for it already?

**Comment by SameenAhnaf** [comment] 2021-08-08 17:45
@mhmdanas Isn't this a duplicate of #5171?

**Comment by mhmdanas** [comment] 2021-08-08 17:46
It's the other way around, but that issue has more discussion anyway. Closing this.

**Closed by mhmdanas** 2021-08-08 17:46 UTC
Labels: enhancement
