### ISSUE TITLE
Recommended videos clickable through captcha error

### ISSUE THREAD

**Issue by Douile** [TeamNewPipe/NewPipe#6734] opened 2021-07-22 01:58 UTC
Similar to #6081 UI elements hidden underneath the captcha error can still be pressed without the user being able to see them.

### Checklist

- [x] I am using the latest version - fd4e1b8d2c09a7df34996e93376d49e5100403c2 (development build) >= v0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open video (portrait or tablet mode)
2. View captcha error
3. Tap where recommended videos normally are (only works if you had recommended selected last)

### Actual behavior

Pressing randomly causes invisible recommended videos to open

### Expected behavior

The click handlers on UI elements that are not visible should be inactive: clicking on a hidden UI element should not result in the normal click action.

### Device info

 - Android version/Custom ROM version: 11
 - Device model: N/A

**Comment by AudricV** [comment] 2024-02-10 22:53
> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

Duplicate of #5600. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-02-10 22:53 UTC
Labels: bug
