### ISSUE TITLE
Don't hide fullscreen button with auto-rotate enabled

### ISSUE THREAD

**Issue by tguen** [TeamNewPipe/NewPipe#7107] opened 2021-09-14 08:12 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### Describe the feature you want
Currently the fullscreen button is hidden if auto-rotate is enabled. The problem is I have enabled the "sensors off" quick tile from developer settings, which disables the gyro sensor. This effectively disables auto-rotate without the app detecting that it's disabled. 

#### How will you/everyone benefit from this feature?

Hiding the fullscreen button is of questionable value and the app doesn't explain why it's hidden. I was frustrated for about 2 weeks because it disappeared and I couldn't figure out why. I downgraded the app and it was still missing. I only figured out why when I came here to report it as a bug and found a comment on another report that explains why it disappeared.

**Comment by mhmdanas** [comment] 2021-09-14 10:54
Duplicate of #4478. Please +1 that issue.

**Closed by mhmdanas** 2021-09-14 10:54 UTC
Labels: enhancement
