### ISSUE TITLE
Batch unsubscribing

### ISSUE THREAD

**Issue by ggtylerr** [TeamNewPipe/NewPipe#8781] opened 2022-08-13 21:32 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

A way to select multiple channels in the subscription list and to remove them all at once.

### Why do you want this feature?

Right now, unsubscribing from multiple channels requires long tapping each one and pressing 'Unsubscribe'. Obviously this is rather tedious - I have a huge list of subscriptions that I imported (~700) and I want to remove them all. If I go through this process, assuming it'll take 3 seconds for each one (not including distractions, tiredness, etc.), it'll take me ***35 minutes.***

### Additional information

Relevant to this - I actually have no way of removing them besides the process earlier and straight up clearing my data. I tried manually editing the database but it won't import.

**Comment by SameenAhnaf** [comment] 2022-08-13 22:17
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3301

**Comment by mhmdanas** [comment] 2022-08-14 10:11
This is a duplicate of #3301 as @SameenAhnaf mentioned.

**Closed** 2022-08-14 10:11 UTC
Labels: enhancement, needs triage
