### ISSUE TITLE
During download large file progress show 100% but file downloading running in background. 

### ISSUE THREAD

**Issue by abhayjaiswal** [TeamNewPipe/NewPipe#731] opened 2017-09-23 06:13 UTC
I have faced issue during download large file like 1Gb file or more then 800mb and internet speed is slow (800MB internet speed  ) then arrive these issue :-

**Issue :-**
During download large file progress show 100% but file downloading running in background. so how solve this problem ?

**Comment by coffeemakr** [comment] 2017-09-23 10:28
Seems to be a duplicate of this: #602

**Closed** 2017-09-23 15:56 UTC
