### ISSUE TITLE
Longer loading time

### ISSUE THREAD

**Issue by Kash629** [TeamNewPipe/NewPipe#8085] opened 2022-03-20 19:02 UTC
Has anybody else experienced longer loading time? Videos take now about 10 seconds to load.

**Comment by Sam4000der3** [comment] 2022-03-20 19:26
Yes I have. This could also be due to the video in question. Not every video is affected. I also like to play entire albums (playlists) one after the other, so I have also encountered the phenomenon.

**Comment by litetex** [comment] 2022-03-20 20:18
Might already be fixed with #7919

**Comment by t297161** [comment] 2022-03-22 12:14
Yes I hva android 6.0.1 ruuning on my mobile and some time it takes 2 to 3 minutes to start a video using 0.22.1 github version. Never had such a bad experience

**Closed** 2022-03-25 19:51 UTC
Labels: template-ignored

**Comment by Dangelman** [comment] 2022-03-29 14:22
I believe this to be a duplicate of #7404
