### ISSUE TITLE
Subtitle embed in video features

### ISSUE THREAD

**Issue by ravig252525** [TeamNewPipe/NewPipe#2365] opened 2019-05-28 09:45 UTC
Subtitle embed in video features

**Comment by gkeegan** [comment] 2019-05-28 15:00
Could you please elaborate on what the issue is?

**Comment by ravig252525** [comment] 2019-05-31 12:14
I want to video download if video subtitle available mixing subtitle then download

**Comment by gkeegan** [comment] 2019-05-31 17:15
So hardcoding the subtitle into the video?

**Comment by opusforlife2** [comment] 2020-08-12 17:59
@kapodamy Possible?

**Comment by kapodamy** [comment] 2020-08-12 20:16
@opusforlife2 no, ambitious feature.

**Comment by opusforlife2** [comment] 2020-08-12 20:18
Alright. Thanks!

**Comment by opusforlife2** [comment] 2020-08-12 20:18
For clarity: closing because subtitles can be downloaded separately, which is the next best thing.

**Closed by opusforlife2** 2020-08-12 20:18 UTC
Labels: downloader, enhancement
