### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by bananachips29** [TeamNewPipe/NewPipe#6518] opened 2021-06-19 01:43 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
User Profiles that are stored in a server for sync between devices, mainly that of subscription, watch history and playback positions

#### Is your feature request related to a problem? Please describe it

I would like to use Newpipe as an alternative to Youtube on multiple devices

#### How will you/everyone benefit from this feature?

I can finally ditch Youtube completely if this feature were to be includes

**Comment by SameenAhnaf** [comment] 2021-06-19 03:27
Duplicate of #5325.

**Closed** 2021-06-19 10:18 UTC
Labels: enhancement
