### ISSUE TITLE
Pop up not working properly

### ISSUE THREAD

**Issue by blochhamiltonian** [TeamNewPipe/NewPipe#7439] opened 2021-11-24 18:13 UTC
### Checklist

- [x] I am using the latest version - 0.21.13
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any video
2. Press on "Popup"
3. Click the Home button OR the Overview button
4. Try to tap on any of the apps on home screen OR try to access any apps that are already open

### Actual behavior

If I try the home button: tapping any of the apps, or attempting to use any of the rest of the phone while Newpipe is in popup mode simply does not work. I tap and nothing happens, I can't use the other apps on my phone while Newpipe is in popup mode.

If I try the overview button: I cannot swipe between apps at all, trying to swipe does nothing while Newpipe is in popup mode.

### Expected behavior

That I would be able to use the apps/home screen/the rest of the phone while Newpipe is in popup mode: I would expect tapping on other apps to open them while Newpipe is in popup mode. I would expect swiping from the Overview menu to get me to other apps.

### Logs

No crash logs generated; not a crash. Just a feature that is not working as expected.

### Device info

 - Android version/Custom ROM version: Graphene OS SP1A.211105.004.2021112123
 - Device model: Pixel 4a (sunfish)

**Comment by SylvainBigonneau** [comment] 2021-11-25 14:57
Yup, this issue started after updating my phone to the latest firmware update on my Galaxy S21 (Android 12, On UI 4.0). I'm guessing it's a new permissions issue?

Note that it also happens on audio-only mode, the only way to access the phone back is to go back to the app through the top status bar menu and pause/close the video.

**Comment by tsiflimagas** [comment] 2021-11-25 15:02
Duplicate of #6770. See the workaround mentioned there.

**Closed** 2021-11-25 17:02 UTC
Labels: bug
