### ISSUE TITLE
UI Crash on App Launch

### ISSUE THREAD

**Issue by Gironorati** [TeamNewPipe/NewPipe#7828] opened 2022-02-06 11:41 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Launch the app.
2. Before the information and pictures load, try to search or open a video
3. Crash!

Whenever I try to use the app really fast just after the launch, it crashes.

### Actual behavior

The app crashes on usage of app on launch but works when wait for some time

### Expected behavior

The app works normally

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ NL
* __Content Language:__ de
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.16
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.RelativeLayout org.schabi.newpipe.databinding.PlaylistHeaderBinding.getRoot()' on a null object reference
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:301)
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:67)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0(BaseListInfoFragment.java:146)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.$r8$lambda$Gn1fP3-8OJnktT5gkmUmbW-egTg(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment$$ExternalSyntheticLambda4.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

Android version: Stock android 9
Phone model: Redmi mi A1

**Comment by litetex** [comment] 2022-02-07 20:57
Duplicate of #6231

**Closed by litetex** 2022-02-07 20:57 UTC
Labels: bug
