### ISSUE TITLE
on popup player cant return to played video

### ISSUE THREAD

**Issue by denemier** [TeamNewPipe/NewPipe#3422] opened 2020-04-13 00:15 UTC
we have only full screen option but cant return on popup player to video for downloading or looking comments.

and even if it is a video from suggestions.
1-I must search last search term again
2-i need to follow suggested videos and dive deep until i find the current video

**Comment by wb9688** [comment] 2020-04-13 06:02
Tap the notification, hold the video, press Details

**Comment by kptawesome** [comment] 2020-04-13 13:57
Tap the popup, tap the full-screen button, tap the list button, long press the video

**Comment by denemier** [comment] 2020-04-13 17:25
wow nice but its hidden for new users, as **wb** said if i click from notification and long press video, then i see dropdown menu and click details it works.
but what **kpt** sad from full screen > list button and if i long press the video it only sends me to last open place where the app was.

i am not sure if its a bug that the full screen list doesnt have dropdown menu for the videos detail page. but thanks for help

**Comment by PeterHindes** [comment] 2020-04-14 06:26
this isn't a bug it's an enhancement but it's a reasonable feature to request as it is quite difficult to get back to the details page when viewing a video in the pop-up or even the full screen player. Also you don't have to search the last thing you searched to find it again you can look at your view history in the left panel.

**Comment by B0pol** [comment] 2020-04-14 09:45
The thing is, you can put too much buttons on popup player, it's designed to be small.

**Comment by denemier** [comment] 2020-04-14 11:52
@B0pol  Yes but I think its responsive,
the current app has a difference between full stretch popup and much smaller version(multi touch resize), buttons changin on different popup sizes.

@PeterHindes wow, i didnt see that option its nice

**Comment by Stypox** [comment] 2020-04-15 18:59
Duplicate of #1873 and others. Wait for 0.20.0, it will bring a completely new player experience

**Closed by Stypox** 2020-04-15 18:59 UTC
Labels: bug
