### ISSUE TITLE
download playlist feature?

### ISSUE THREAD

**Issue by denemier** [TeamNewPipe/NewPipe#3424] opened 2020-04-13 00:27 UTC
Can we download multiple playlist it would be good.

Because its hard to choose quality for each video, to select max resolution is going to do the job.

İf available download the content with max = 720p or 1080p

**Comment by PeterHindes** [comment] 2020-04-14 06:16
There was at one point a fairly buggy pull request implimenting this. You could go check it out.

**Comment by B0pol** [comment] 2020-04-14 09:43
Duplicate of #1236. The pull request you are talking about is #2018.

**Closed by B0pol** 2020-04-14 09:43 UTC
Labels: enhancement
