### ISSUE TITLE
Rotating the screen in History tab causes an UI glitch that can crash the app

### ISSUE THREAD

**Issue by Fs00** [TeamNewPipe/NewPipe#7573] opened 2021-12-23 22:17 UTC
### Checklist

- [x] I am using the latest version - 0.21.14
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to History tab in Home screen
2. Scroll down through the list (header must not be visible)
3. Enter on a video
4. Rotate the screen
5. Minimize the video

OR

1. Go to History tab in Home screen
2. Scroll down through the list (header must not be visible)
3. Enter on a video
4. Minimize the video
5. Rotate the screen
6. Rotate the screen again

### Actual behavior

The UI will be slightly messed up (list header will be shown on top of the videos list). If you scroll to the top, the app will crash.

### Expected behavior

There should be no bugs in the UI and the app should not crash.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/30041551/147295738-821678c0-b9e8-4675-a0e8-ac0d636b5097.mp4

### Logs

* User Action: ui error
* Request: ACRA report
* Content Country: IT
* Content Language: it
* App Language: it_IT
* Service: none
* Version: 0.21.14
* OS: Linux Android 10 - 29

<details>
<summary><b>Crash log </b></summary>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
 at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7297)
 at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
 at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
 at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
 at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
 at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
 at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```
</details>

### Device info

 - Android version/Custom ROM version: Android 10, LineageOS 17.1
 - Device model: Samsung Galaxy A3 2017

**Comment by TiA4f8R** [comment] 2021-12-24 11:32
Duplicate of #4475. Please search (better?) for duplicates next time. Thank you.

**Closed by TiA4f8R** 2021-12-24 11:32 UTC
Labels: bug

**Comment by Fs00** [comment] 2021-12-24 11:37
Sorry! I've only searched for duplicates that matched the word "History" since I thought that the bug could only happen in History tab.
