### ISSUE TITLE
Could not parse website

### ISSUE THREAD

**Issue by pgenderson** [TeamNewPipe/NewPipe#3659] opened 2020-05-28 13:20 UTC
### Version

-19.3
### Steps to reproduce the bug

1. Go to youtube.com/watch?v=dcLaYwl48v0 (one of the results after searching 'full flex')

### Expected behavior
Plays video

### Actual behaviour
Guru meditation error report: could not parse website 

### Logs

The markdown converter site gives me an error 404.

**Comment by B0pol** [comment] 2020-05-28 14:45
Can you paste the error report like this:
```
``the crash report``
```

**Comment by eladkarako** [comment] 2020-05-28 16:28
I can replicate..

## Exception
* __User Action:__ requested stream
* __Request:__ http://youtube.com/watch?v=dcLaYwl48v0
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.19.3
* __OS:__ Linux samsung/j4ltejx/j4lte:9/PPR1.180610.011/J400FXXU4BSJ1:user/release-keys 9 - 28


<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:192)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:70)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:62)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

**Comment by B0pol** [comment] 2020-05-28 17:16
This is duplicate of #3576

**Closed by B0pol** 2020-05-28 17:16 UTC
Labels: bug

**Comment by luimu64** [comment] 2020-06-24 10:27
Having the same issue but with: https://youtu.be/oNg3M9IJJlY

``{"user_action":"requested stream","request":"https://www.youtube.com/watch?v=oNg3M9IJJlY","content_language":"en_FI","service":"YouTube","package":"org.schabi.newpipe","version":"0.19.3","os":"Linux Android 10 - 29","time":"2020-06-24 10:20","exceptions":["org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:192)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:70)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:62)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\n"],"user_comment":""}``

**Comment by wb9688** [comment] 2020-06-24 10:29
@luimu64: Upgrade to the latest version (currently v0.19.5)

**Comment by luimu64** [comment] 2020-06-24 11:36
That fixed it. I thougth fdroid would auto update it but it just auto downloads the apps my bad.

**Comment by Denofalltrades** [comment] 2020-10-27 01:18
20.1 is having this issue now, and you've removed the 19.5 install from fdroid, and I disabled YouTube, so where does that leave us. Oxygen OS9.0.11, OnePlus 5T

**Comment by opusforlife2** [comment] 2020-10-27 06:17
> and you've removed the 19.5 install from fdroid

@Denofalltrades We don't control F-Droid. It shows only the latest 3 versions. Enable the Archive repo from settings to get older versions.

**Comment by guzelonur** [comment] 2020-10-27 18:27
I have the same problem even with the latest version. It fails to parse any Youtube video on my old device (Android 5.0.1).

**Comment by matthewbrunswick** [comment] 2020-11-06 12:14
> I have the same problem even with the latest version which appears to be 0.20.1. It fails to parse any Youtube video on my old device (Android 5.0.1).

I'm having the same issue with 20.1 on my Oppo running Android 7.1.1 watching anything but the 
 Trending videos (I can't search then watch). Downgrading doesn't work either. It used to work fine.

**Comment by pgenderson** [comment] 2020-11-06 12:58
@matthewbrunswick have you tried with 20.2 (the latest)?
