### ISSUE TITLE
SoundCloud profile import

### ISSUE THREAD

**Issue by unknowndelicateboy** [TeamNewPipe/NewPipe#2739] opened 2019-10-19 16:04 UTC
Error: importing a soundcloud profile by typing the URL is not working.

**Comment by Stypox** [comment] 2019-11-01 10:45
I can't reproduce. Can you explain a little bit further?

**Comment by Stypox** [comment] 2020-02-19 16:49
Closing in favour of #3103

**Closed by Stypox** 2020-02-19 16:49 UTC
Labels: more info needed, soundcloud
