### ISSUE TITLE
Add Invidious support

### ISSUE THREAD

**Issue by e-edgren** [TeamNewPipe/NewPipe#2621] opened 2019-09-11 23:09 UTC
I would love to see an option in NewPipe's settings, where you can choose to connect to the Invidious network instead of YouTube, and also be able to change instance. What I know of, Invidious does not have any app for their service. Why not change that? 🙂

**Comment by Gymcap** [comment] 2019-09-12 01:05
I agree with this. It would also be nice to be able to use our own instance.

**Comment by airon90** [comment] 2019-09-14 08:28
See #2488

**Comment by dimqua** [comment] 2019-09-14 12:31
It's good move, but it'd even better to completely "disconnect" from YouTube (and other google services) by using Invidious API instead.

**Comment by Z3ROGRAV1TYx** [comment] 2019-11-25 03:08
Would love to see this!

**Comment by danialbehzadi** [comment] 2020-01-27 19:09
This would be awesome 😍

**Comment by KonoromiHimaries** [comment] 2020-02-26 11:53
https://github.com/TeamNewPipe/NewPipe/issues/3136

**Comment by KonoromiHimaries** [comment] 2020-02-26 12:39
https://github.com/TeamNewPipe/NewPipe/issues/1819

**Comment by trymeouteh** [comment] 2020-03-31 04:50
I think users should be able to add invidious instances just like you can add peertube instances. And have invidio.us as the default instance.

**Comment by danialbehzadi** [comment] 2020-04-01 02:43
> I think users should be able to add invidious instances just like you can add peertube instances. And have invidio.us as the default instance.

Invidious is not a network like Peertube, but an interface/proxy for YouTube. It should be able to redirect incoming YouTube URLs to selected Invidious instance.

**Comment by grravity** [comment] 2020-04-01 03:07
@danialbehzadi But there's different Invidious instances. For example the load on the main one is pretty bad, so if someone wanted to selfhost their own personal instance or use a friends they'd have that option to specify which one. Not exactly the same as PeerTube, but kinda the same idea just as a wrapper frontend

**Comment by danialbehzadi** [comment] 2020-04-01 07:11
@grravity That could be easily done with an entry in settings, just like NitterizeMe is doing.

**Comment by grravity** [comment] 2020-04-01 13:47
@danialbehzadi Yes ofc, but I was just clarifying I believe that is what he was asking for

**Comment by pluja** [comment] 2020-05-08 08:41
This would be amazing! Being able to use Invidious and never connect to Youtube

**Comment by B0pol** [comment] 2020-05-12 15:47
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1867

**Closed by B0pol** 2020-05-12 15:47 UTC
Labels: enhancement, new service
