### ISSUE TITLE
Background Dashboard broken in lock screen

### ISSUE THREAD

**Issue by PortalVector** [TeamNewPipe/NewPipe#2639] opened 2019-09-16 20:29 UTC
The dashboard (play, pause, next and previous) doesn't appear on my Xiaomi Redmi 5 Plus, i double checked my parameters and it's not about notifications settings, is there a issue with my phone or Newpipe (I can't provide screenshots i'm on FastHub.

**Comment by Stypox** [comment] 2019-09-17 04:47
Duplicate of #1998 
Could you please send a screenshot with your PC to that issue?

**Closed by Stypox** 2019-09-17 04:47 UTC

**Comment by gkeegan** [comment] 2019-09-17 05:14
Fasthub can add screenshots actually. Compose a comment, then tap the up arrow in the left of the compose box. Scroll to the right, then select the image icon.
