### ISSUE TITLE
2 Suggestions 

### ISSUE THREAD

**Issue by SerjS2** [TeamNewPipe/NewPipe#3239] opened 2020-03-17 08:21 UTC
I want to suggest these 2 things:

![Screenshot_20200317_100150](https://user-images.githubusercontent.com/57362708/76835372-a2ada380-6837-11ea-95ce-bc304d53bcb5.jpg)
First, as you see in the picture I put a flash, i want this to be as if i play click the video plays like that without like just putting the video in landscape mode automatically or in portrait mode but without showing the comments section and etc, this way we would see the description of the video while watching without going back and getting interrupted.

![Screenshot_20200317_100214](https://user-images.githubusercontent.com/57362708/76835487-dc7eaa00-6837-11ea-91f5-50dba633548a.jpg)
Now, the second picture, i want to suggest a section for showing latest uploads from our subscription list that we imported, because the 'What's New' isn't showing latest subscriptions, this can be in 2 ways:

1. Adding a fourth tab, in the middle of the 'Trending' and 'Subscriptions' or in the middle of 'Subscriptions' and 'Bookmarks', a tab named 'Latest Videos' that shows all of the latest videos from our subscriptions.
2. Adding a new part under the 'What's New' in the subscription tab, a tab named 'Latest Videos' which shows all of the latest videos from out subsciption list.

If, the 'What's New' is supposed to show the latest video:
![Screenshot_20200317_101822_org schabi newpipe](https://user-images.githubusercontent.com/57362708/76836004-be657980-6838-11ea-9b31-151d3bf6ff20.jpg)
It doesn't. As you can see, many of the videos are '11 months ago', '2 months ago' and etc, if this is supposed to show the latest videos, you could keep this and change it to showing only the videos of my subscribers that are popular and most watched. And, the new tab that you will add, 'Latest Videos', can only show the videos that were post recently, like only the new videos that were posted from my subscribers.

**Comment by Stypox** [comment] 2020-03-17 08:24
1) Duplicate of #2882
2) Fixed by #2309. Will be part of 0.19.0

**Closed by Stypox** 2020-03-17 08:24 UTC

**Comment by Stypox** [comment] 2020-03-17 08:25
Also, next time open two issues if you want to suggest two different things
