### ISSUE TITLE
Almost every action causes "Sorry, something went wrong. REPORT" to pop up.

### ISSUE THREAD

**Issue by BigClarky** [TeamNewPipe/NewPipe#5177] opened 2020-12-15 06:00 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Click on literally any youtube video
2. Press the play, pause, or full-screen button

### Actual behavior
The "Sorry, something went wrong. REPORT" error pops up every time, even though the action completes successfully. 

### Expected behavior
Nothing pops up and the action completes successfully.

### What I would recommend
If this cannot be fixed at least add an option to disable these popups entirely.

## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.6
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UCRacuoCHhh2HFs4jOmrfe_Q
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:224)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:66)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:114)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This channel does not exist."
	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:218)
	... 11 more
Caused by: org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This channel does not exist."
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.defaultAlertsCheck(YoutubeParsingHelper.java:548)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.onFetchPage(YoutubeChannelExtractor.java:108)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:47)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:125)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BOLWstv98dC8pFAG_uir5gPXYwY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
	... 12 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment] 2020-12-15 06:11
Thanks for the report! Reading the error a bit more closely, it seems it has something to do with a deleted channel (specifically, [this one](https://www.youtube.com/channel/UCRacuoCHhh2HFs4jOmrfe_Q)). Are you subscribed to this channel?

> add an option to disable these popups entirely.

This probably isn't going to happen. However, we know that this system isn't perfect, so we're trying to improve it. Could you check #5148 and see if you think it's better?

**Comment by XiangRongLin** [comment] 2020-12-15 06:52
This should probably be resolved by removing subscriptions automatically if the extractor throws an `ContentUnavailableException` (or however it is called).
As an extra you can add a toast notifying the user about that.

Alternately open a dialog for each exception notifying the user that the channel was deleted and asking him if he also wants to delete it.

Should be very approachable for newcomers if the extractor already recognizes deleted channels

**Comment by Stypox** [comment] 2020-12-15 08:01
Duplicate of #3313

**Closed by Stypox** 2020-12-15 08:01 UTC
Labels: bug, feed

**Comment by BigClarky** [comment] 2020-12-15 18:32
Sorry I was sleeping. I guess looking at the error more closely, it is in fact a duplicate of #3313
