### ISSUE TITLE
[feature request]Automatic switching to the video resolution with sound

### ISSUE THREAD

**Issue by galaxygh** [TeamNewPipe/NewPipe#3650] opened 2020-05-25 03:40 UTC
#### Describe the feature you want

Thanks  for developing this app. I think it would be nice if you add feature that automatic switching to the video resolution with sound when use external player.
#### Is your feature request related to a problem? Please describe it

I choose the option playing videos with external player and the set the defalt resolution as 1080p, but I often find a video doesn't has any sound. I have to quit the player and switch to a resolution with sound(mostly 360p). It would be nice if newpipe can switch the resolution to 360p automatically and temporarily the first time I open this type of video.
#### How will you/everyone benefit from this feature?

This feature will help people that use external player.

**Comment by Stypox** [comment] 2020-05-25 08:54
Duplicate of #1474

**Closed by Stypox** 2020-05-25 08:54 UTC
Labels: enhancement
