### ISSUE TITLE
An error occurs when I try to download a video and I can't download any videos.

### ISSUE THREAD

**Issue by sargoon** [TeamNewPipe/NewPipe#2445] opened 2019-07-04 13:00 UTC
**Actual behavior**
An error occurs when I try to download a video and I can't download any videos.

**Expected behavior**
Users need to download videos properly without any error.

**To Reproduce**
1. Open the NewPipe.
2. Click on any video.
3. Click on the "Download" button.
4. You will see that the video hasn't been downloaded and an error has occurred.

Note: Download fails in all thread options.

**Extra phone info**

• ROM: MIUI Global 10.3.6
• Android Version: Android 9.0

**Record of the Bug**
![NegativeAdorableInsect-size_restricted](https://user-images.githubusercontent.com/34961616/60668377-781be600-9e74-11e9-85fd-b9bda01e8e14.gif)

**Logcat Report**
Code: 1007
Post-processing failed
`java.io.EOFException: parser go beyond limits of the Element. type=0xf43b675 offset=10576755 size=453884 position=38358841
java.lang.ArithmeticException: divide by zero`

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by gkeegan** [comment] 2019-07-04 20:24
What version of NewPipe are you on?

**Comment by sargoon** [comment] 2019-07-04 20:48
> 
> 
> What version of NewPipe are you on?

Latest, 0.16.2

**Comment by gkeegan** [comment] 2019-07-04 21:12
Interesting. I'm not in a place where I can verify the bug right now (slow mobile data), so can somebody else verify this issue?

**Comment by Stypox** [comment] 2019-07-05 07:43
I think this is a duplicate of #2291. Can you confirm?

**Closed** 2019-07-05 10:58 UTC
