### ISSUE TITLE
Unified Player seekbar not appearing on Android 11

### ISSUE THREAD

**Issue by ZeroPucks** [TeamNewPipe/NewPipe#4277] opened 2020-09-13 16:39 UTC
### Version

- 0.19.8 pr3178 from #3178 
https://github.com/TeamNewPipe/NewPipe/files/5204058/app-debug.zip

- 0.19.8 530f745 from #4154 
https://github.com/TeamNewPipe/NewPipe/files/5190324/app-debug.zip

- 0.19.8 from #4255 
https://github.com/TeamNewPipe/NewPipe/files/5196395/app-debug.zip

### Steps to reproduce the bug

1. Open and play any video on Android 11.
2. Open the video in landscape fullscreen by rotating the device or tapping on fullscreen toggle.
3. Tap on the screen to expose video title, pause/play controls, and additional UI elements.

### Expected behavior

The seekbar should appear with timestamps, and status bar should disappear.
### Actual behaviour

Seekbar does not appear, and status bar is a persistent red bar across top of video, even when the other UI elements are gone.
### Screenshots/Screen recordings

Unified Player APKs:

![Screenshot_20200913-100018_1](https://user-images.githubusercontent.com/46003124/93023418-d7b76a80-f5bc-11ea-9ece-4fea23c3bdce.png)
![Screenshot_20200913-100035_1](https://user-images.githubusercontent.com/46003124/93023419-d8500100-f5bc-11ea-84e0-c51a826427b5.png)

Stable release APK 0.19.8 from 2020-07-28:
https://github.com/TeamNewPipe/NewPipe/releases/download/v0.19.8/NewPipe_v0.19.8.apk

![Screenshot_20200913-114858_1](https://user-images.githubusercontent.com/46003124/93023439-03d2eb80-f5bd-11ea-85b8-f294114aea08.png)

### Logs

N/A

### Notes
Screenshots taken on Pixel 3a (2220x1080 resolution, no cutouts or notches) running Android 11, sideloaded OTA and factory reset.

**Comment by opusforlife2** [comment] 2020-09-13 16:49
Can you confirm that this or a similar problem doesn't appear on any other media players like VLC and mpv-android?

**Comment by ZeroPucks** [comment] 2020-09-13 17:03
Can confirm VLC does not have a similar issue on latest stable 3.2.12 https://get.videolan.org/vlc-android/3.2.12/, and the latest nightly VLC-Android-3.3.0-armv8-20200913-0135.apk from https://artifacts.videolan.org/vlc-android/nightly-arm64/.

![Screenshot_20200913-125738_1](https://user-images.githubusercontent.com/46003124/93024068-76de6100-f5c1-11ea-9470-2faecc6032d3.png)
![Screenshot_20200913-125909_1](https://user-images.githubusercontent.com/46003124/93024070-7776f780-f5c1-11ea-888b-a7f8ab71c5cd.png)

**Comment by blackbox87** [comment] 2020-09-13 17:28
Try my latest [test version](https://github.com/TeamNewPipe/NewPipe/pull/4255#issuecomment-691698494). It should handle gesture navigation correctly, although I've only been able to test it on Android 10.

**Comment by ZeroPucks** [comment] 2020-09-13 18:01
Thank you for the test APK. It's almost there, the seekbar is just a little off-screen now.

Unrelated to your change, but the persistent red status bar is also still there.

![Screenshot_20200913-135536](https://user-images.githubusercontent.com/46003124/93025090-23701100-f5c9-11ea-9afd-2e59330f2c77.png)

**Comment by blackbox87** [comment] 2020-09-13 19:16
It scan see that it's correctly applying insets, but it looks like your status bar and navigation heights are being reported incorrectly.

Could you please try this test version and let me know the values that it displays?

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5214963/app-debug.zip)

**Comment by avently** [comment] 2020-09-13 19:25
@blackbox87 see the deprecation notice, maybe it's what we need. Some flags we use also deprecated so some of new methods may be used instead
https://developer.android.com/reference/android/view/View#SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN

**Comment by ZeroPucks** [comment] 2020-09-13 19:26
@blackbox87 Values are as follows:
Status bar: 66
Status bar landscape: 66
Navbar: 44
Navbar landscape: 44

**Comment by avently** [comment] 2020-09-13 19:27
So hideSystemUi and showSystemUi should be aware about android 11 methods

**Comment by blackbox87** [comment] 2020-09-13 19:45
@avently Maybe it's caused by that, but I'm not sure. The status bar height shouldn't be greater than the navbar on a device without a cutout though.

Honestly, the way I'm fixing most of these issues is more of a hack than a true fix. To do it correctly you'd need to recreate the video player so that it's aware of insets and applies them correctly without all of the calculations that I'm currently having to do.

**Comment by avently** [comment] 2020-09-13 19:51
@blackbox87 
> The status bar height shouldn't be greater than the navbar on a device without a cutout though.

In this case navbar is a thin line which has less height than status bar by visual comparison.

>To do it correctly you'd need to recreate the video player so that it's aware of insets

Do you know how to do it? It's easy to do in separate activity (just for a player) but not for activity with other fragments. Also the video should be below navbar while other controls should be side-by-side with it. I don't know how to do it without custom calculations

**Comment by avently** [comment] 2020-09-13 19:58
Actually I know that in theory we can use insets even here but it's hard to do. MainActivity should always be in contact with videodetalfragment. So whenever insets changes new values should be sent to the fragment which should apply side padding to some views. It's possible, maybe even easier than our calculations but I don't have time on testing this idea. Maybe some day

**Comment by blackbox87** [comment] 2020-09-13 20:03
> In this case navbar is a thin line which has less height than status bar by visual comparison.

Actually it's not. The value is for the traditional navbar and [the gesture controls are handled by insets](https://developer.android.com/reference/androidx/core/view/WindowInsetsCompat.html#getSystemGestureInsets()). I couldn't get a value to return from this though, so I'm using the navbar height + 4dp of extra padding. It works perfectly on Android 10.

> Do you know how to do it?

No, otherwise I would of done it already. But I'm going to see if it's possible to add padding to the root view instead of specific controls.

**Comment by ZeroPucks** [comment] 2020-09-13 20:25
May be related to this issue, but I just noticed the bottom of the video is cut off in landscape fullscreen.

![Screenshot_20200913-162425](https://user-images.githubusercontent.com/46003124/93027834-b155f700-f5dd-11ea-8b7a-7f362929fd7e.png)
![Screenshot_20200913-162435](https://user-images.githubusercontent.com/46003124/93027836-b1ee8d80-f5dd-11ea-969a-f599cb49da53.png)

Let me know if I should open another bug report for this.

**Comment by blackbox87** [comment] 2020-09-13 20:30
@ZeroPucks Does everything work correctly if you disable gesture navigation?

**Comment by ZeroPucks** [comment] 2020-09-13 20:41
Unfortunately no, seekbar is still off-screen with 3-button and 2-button navigation. The fullscreen minimize button is now partially visible. There is more of the video visible, but a portion of the bottom is still cut off.

Again this is on a 18.5:9 screen ratio (2220x1080) on Android 11.

**Comment by blackbox87** [comment] 2020-09-13 21:24
@avently Here's another test version. It contains my changes, but I've also compiled it against API 30 so that I could try out setDecorFitsSystemWindows().

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5215104/app-debug.zip)

**Comment by ZeroPucks** [comment] 2020-09-13 21:49
No difference from the last APK, seekbar is still partially off-screen. Appreciate you trying, though. Hopefully someone else on Android 11 can test to make sure it isn't just my device.

**Comment by blackbox87** [comment] 2020-09-13 22:01
I'll see if I can setup an emulator with Android 11 to try some stuff. I'm currently low on disk space which is why I haven't done that already.

**Comment by avently** [comment] 2020-09-13 22:49
Please, check this one. Works ok on emulator

[android-11.zip](https://github.com/TeamNewPipe/NewPipe/files/5215276/android-11.zip)

**Comment by ZeroPucks** [comment] 2020-09-13 23:42
@avently Thank you, the status bar is no longer persistent, video is completely visible, and the seekbar is now mostly visible. There is an opaque gesture navigation bar when the UI elements appear, but as you said it works okay.

![Screenshot_20200913-192144_1](https://user-images.githubusercontent.com/46003124/93031235-34377b80-f5f7-11ea-8be7-d149e28183d2.png)
![Screenshot_20200913-192201_1](https://user-images.githubusercontent.com/46003124/93031236-34d01200-f5f7-11ea-8084-27d3de613057.png)



The seekbar is completely visible when using 3-button and 2-button navigation:

![Screenshot_20200913-193805_1](https://user-images.githubusercontent.com/46003124/93031475-25ea5f00-f5f9-11ea-906c-bcaf053dc269.png)
![Screenshot_20200913-193822_1](https://user-images.githubusercontent.com/46003124/93031477-284cb900-f5f9-11ea-8d93-cf722ca5b1a0.png)

**Comment by blackbox87** [comment] 2020-09-13 23:45
Combined with my changes it'd likely fully fix the problem. I'm not sure what @avently changed though, so can't copy his changes into my build.

**Comment by avently** [comment] 2020-09-13 23:49
> I'm not sure what @avently changed though

second commit in:
https://github.com/TeamNewPipe/NewPipe/pull/4272

**Comment by avently** [comment] 2020-09-13 23:53
@ZeroPucks
> and the seekbar is now mostly visible

This will be probably fixed by @blackbox87's work so you'll get fully working app. Thank you for detailed issue and testing!

**Comment by ZeroPucks** [comment] 2020-09-13 23:57
@avently and @blackbox87 Thank you both for looking into this issue and working to resolve! Hopefully the changes can be merged with the notification changes in #3178  for a fully-compatible Android 11 build.

**Comment by blackbox87** [comment] 2020-09-14 00:04
Here's my changes with the Android 11 changes from @avently 

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5215382/app-debug.zip)

**Comment by ZeroPucks** [comment] 2020-09-14 00:31
Thank you @blackbox87, the seekbar is now completely visible and actionable. As you mention, status bar and navigation bar are still opaque. Unfortunately, previous test builds did not change that behavior.

![Screenshot_20200913-201226_1](https://user-images.githubusercontent.com/46003124/93032280-baa38b80-f5fe-11ea-87ec-562e44eaee67.png)

**Comment by avently** [comment] 2020-09-14 08:39
Try this one. Status bar and navigation bar will be transparent. This apk doesn't include @blackbox87 changes. If everything is fine, I'll upload changes to #4272 
[android-11-2.zip](https://github.com/TeamNewPipe/NewPipe/files/5217116/android-11-2.zip)

**Comment by avently** [comment] 2020-09-14 08:42
@blackbox87 since you have Android 10, do you see red status bar in fullscreen? Or it's only Android 11 problem?

**Comment by wb9688** [comment] 2020-09-14 08:49
@avently: That red status bar looks like energy saving mode. On my Android 10 phone, I don't see the status bar, but I don't think I can test with energy saving mode, because of Samsung's weird One UI.

**Comment by blackbox87** [comment] 2020-09-14 10:58
> @blackbox87 since you have Android 10, do you see red status bar in fullscreen? Or it's only Android 11 problem? I can apply my status bar fix for Android 10 too if it's needed.

I installed an Android 10 ROM to test things, but went back to my Android 9 backup. Luckily I still have screenshots though, so I can confirm that the issues unique to Android 11. On Android 10 the status bar, navigation bar and gesture bar are all transparent.

**Comment by ZeroPucks** [comment] 2020-09-14 21:33
> 
> 
> Try this one. Status bar and navigation bar will be transparent. This apk doesn't include @blackbox87 changes. If everything is fine, I'll upload changes to #4272
> [android-11-2.zip](https://github.com/TeamNewPipe/NewPipe/files/5217116/android-11-2.zip)

Confirmed, status bar and navigation bar are transparent on Android 11 with gesture navigation. As you said, it does not include @blackbox87 changes so the seekbar padding isn't quite there. But everything is on-screen and transparent as advertised.

**Closed** 2020-09-27 13:31 UTC
Labels: bug, player
