### ISSUE TITLE
Chat replay

### ISSUE THREAD

**Issue by icantcode4shit** [TeamNewPipe/NewPipe#7082] opened 2021-09-09 01:51 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Chat replay, where the original chat of the live is visible alongside the video (where made available by the content creator). It could just be top chat replay to account for popular lives and extends the comments feature of the app. 

#### How will you/everyone benefit from this feature?

Chat replay functions as the comment section for most live videos. Given that it's a past log and not possible to comment, this could be a better alternative than trying to implement live chat.

**Comment by SameenAhnaf** [comment] 2021-09-09 02:57
Duplicate of #5171.

**Closed** 2021-09-09 05:20 UTC
