### ISSUE TITLE
Crash on rewind

### ISSUE THREAD

**Issue by tfga** [TeamNewPipe/NewPipe#4738] opened 2020-10-31 11:24 UTC
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start playing a video (full screen). What I usually do is "Start playing in a pop-up" + maximise (don't know if this is relevant). 

2. Double tap to rewind

It doesn't happen every time. It's intermittent. But it happens often enough that I get it every day, multiple times a day. 

### Actual behaviour

Crash. 

### Expected behavior

Rewind. 

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.20.2
* __OS:__ Linux motorola/ali_n/ali_n:9/PPS29.55-37-7/445ae:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList androidx.core.app.NotificationCompat$Builder.mActions' on a null object reference
    at org.schabi.newpipe.player.NotificationUtil.shouldUpdateBufferingSlot(NotificationUtil.java:151)
    at org.schabi.newpipe.player.VideoPlayerImpl.onBuffering(VideoPlayerImpl.java:1121)
    at org.schabi.newpipe.player.BasePlayer.changeState(BasePlayer.java:583)
    at org.schabi.newpipe.player.VideoPlayerImpl.changeState(VideoPlayerImpl.java:1102)
    at org.schabi.newpipe.player.BasePlayer.onPlayerStateChanged(BasePlayer.java:798)
    at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:828)
    at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$AYkTJomZb3BnUDA59u8cvRVoKcM.invokeListener(Unknown Source:2)
    at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
    at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
    at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
    at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:826)
    at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
    at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
    at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
    at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
    at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6923)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

```
</details>
<hr>

**Comment by opusforlife2** [comment] 2020-10-31 12:40
Do you get it when you're playing or only if you're paused?

**Comment by tfga** [comment] 2020-10-31 15:40
While playing.

Never noticed if it also happens when paused. I'll try to pay attention
from now on.

**Comment by opusforlife2** [comment] 2020-10-31 15:47
Check again. Find out if it happens when paused or when playing, or both.

**Comment by tfga** [comment] 2020-10-31 16:22
Ok. Just checked. It happens when paused. And, surprisingly for me, when paused it happens *every time*. 😲

This thing is reproducible, after all. How come I didn't notice this before?! 🤔

**Comment by opusforlife2** [comment] 2020-10-31 16:26
Duplicate of #4390. Already fixed.

**Closed by opusforlife2** 2020-10-31 16:26 UTC
Labels: bug

**Comment by tfga** [comment] 2020-10-31 16:32
Ok. Sorry about that.
