### ISSUE TITLE
Videos are not loading [BUG]

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#8224] opened 2022-04-16 09:57 UTC
Hei guys, great work yesterday. For the release 0.22.2.

However I still have trouble using the all. Opening a Video does not yield an error, however the streams don't load at all. This however only happens on certain Videos. How could that be and how can it be fixed?

Video in the Example: https://www.youtube.com/watch?v=pfF1Qk6Sfnw

https://user-images.githubusercontent.com/1891273/163670789-b9148dea-ae42-4ed1-9d3e-e6d730432a04.mp4

**Comment by chrisbeardy** [comment] 2022-04-16 11:53
Ive also started getting issues with videos just erroring now. ![Screenshot_20220416-125236.png](https://user-images.githubusercontent.com/20585410/163673889-4a9567a6-2736-46dc-bbde-ce0c788e10e8.png)

**Comment by SameenAhnaf** [comment] 2022-04-16 12:19
@theScrabi The problem seems to be exclusive for 720p resolution on my device.

@chrisbeardy That's a different bug. Please update to the latest version 0.22.2

**Comment by TiA4f8R** [comment] 2022-04-16 13:02
Duplicate of #7630! As a workaround, seek in the video or switch the quality played, or try any debug APK which contains the PR linked in the issue (which will be included in the next release) or my delivery methods PR.

Thank you!

<h6>Could you please, as a project owner and former, follow our issue templates when you open an issue, and search for duplicates next time? Give the example to app users!</h6>

**Closed by TiA4f8R** 2022-04-16 13:02 UTC

**Comment by theScrabi** [comment] 2022-04-17 10:12
Yes. Sorry that was stupid. I will take care in the future :)
