### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by snowzhangy** [TeamNewPipe/NewPipe#4093] opened 2020-08-07 16:20 UTC
### Version

0.19.8

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=1PwrKkuzn7Y
* __Content Country:__ CA
* __Content Language:__ en-CA
* __App Language:__ en_CA
* __Service:__ YouTube
* __Version:__ 0.19.8
* __OS:__ Linux samsung/d2qcs/d2q:10/QP1A.190711.020/N975WVLU3CTE7:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr> -->

**Comment by opusforlife2** [comment] 2020-08-07 16:35
@Stypox This seems like a duplicate of 3992, but is just looking at the crash log enough to determine that?

Moreover is there some kind of pattern we can adhere to when suggesting people read previous issues to see if theirs is already filed? For example, a user could search "Could not get any stream" in existing issues for this particular crash log.

Maybe we could have keyword-search-friendly crash log summaries at the top of every crash log.

**Comment by wb9688** [comment] 2020-08-07 16:41
@opusforlife2: Click on the video URL and you'll see that it's a live stream. Above error message happens in NewPipe for recently ended live streams, which we can't fix (or maybe it's fixed already there?) until my DASH/HLS PR gets merged. If this wasn't a live stream, this bug would be worth investigating.

**Comment by snowzhangy** [comment] 2020-08-07 16:46
> @opusforlife2: Click on the video URL and you'll see that it's a live stream. Above error message happens in NewPipe for recently ended live streams, which we can't fix (or maybe it's fixed already there?) until my DASH/HLS PR gets merged. If this wasn't a live stream, this bug would be worth investigating.

The live stream is finished 30 mins ago but I still can't watch it. If it's a live stream new pipe seems works fine. Just not for recent finished live videos. Hope it could be fixed.

**Comment by opusforlife2** [comment] 2020-08-07 17:09
Ah. Then duplicate of #3336.

**Closed by opusforlife2** 2020-08-07 17:09 UTC
Labels: bug, youtube
