### ISSUE TITLE
Sleep Timer Feature

### ISSUE THREAD

**Issue by tawaypr** [TeamNewPipe/NewPipe#3339] opened 2020-04-03 08:10 UTC
Is that feature going to be implemented to that great app? It will make the app very friendly to use before sleeping.

**Comment by gkeegan** [comment] 2020-04-03 08:24
Duplicate of #2830

PR working on it is #2892

Please search the issues before opening one. Also follow the template.

**Closed** 2020-04-03 09:19 UTC
Labels: enhancement
