### ISSUE TITLE
App crashed - log attached - UI buttons went to the top of the screen

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#5962] opened 2021-03-30 21:53 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

I can't reproduce.

### Actual behaviour

This happened out of nowhere.

### Expected behavior

Should not happen.

### Screenshots/Screen recordings

![IMG_00231](https://user-images.githubusercontent.com/55331939/113061616-dab52980-91a1-11eb-9a58-ca9d991bfb3a.jpg)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7080)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: 10
 - Device model: OnePlus

**Comment by mhmdanas** [comment] 2021-03-31 05:11
Looks like a duplicate of #4475 to me, but the buttons moving to the top is a bit curious. Can you post that screenshot and error on that issue?

**Closed by mhmdanas** 2021-03-31 05:11 UTC
Labels: bug

**Comment by desmonk** [comment] 2021-03-31 12:52
Unfortunately, I am not able to reproduce this. Happens sometimes though. The buttons went up suddenly and I have no clue how that happened.
