### ISSUE TITLE
Add Support for Channel Tabs 

### ISSUE THREAD

**Issue by mikeloeven** [TeamNewPipe/NewPipe#10383] opened 2023-08-27 16:08 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

A while back youtube broke channels up into various tabs by categorys Videos, Shorts, Live Etc the current new pipe UI does not display these tabs or allow a user to select the category of content they want to view. The UI needs a update to allow changing category 

### Why do you want this feature?

I would say that adding support for channel tabs in the UI is rather important due to how its preventing access to a good amount of content due to content of these tabs not being visible on the main videos list.

**Comment by AudricV** [comment] 2023-08-27 16:37
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

You didn't, duplicate of #2414. Please search (better?) for duplicates before opening an issue. Thank you.

**Closed by AudricV** 2023-08-27 16:37 UTC
Labels: feature request, needs triage
