### ISSUE TITLE
Can't resume playback after pausing video

### ISSUE THREAD

**Issue by damoochie** [TeamNewPipe/NewPipe#6029] opened 2021-04-09 11:35 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
The video pauses but then won't start playing again when play is pushed.

### Expected behavior

Resume playback after pausing.

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Pixel 3

**Comment by ShareASmile** [comment] 2021-04-09 12:16
Always check duplicates by searching relevant  keyword {for example 'resume' in your case} before opening a new issue. As you ticked in the box before 2nd line in issue template.
[I checked, but didn't find any duplicates (open OR closed) of this issue in the repo]

@mhmdanas you can close this as Duplicate of #5730

**Closed** 2021-04-09 16:04 UTC
Labels: bug

**Comment by damoochie** [comment] 2021-04-09 20:51
@mhmdanas But that issue says paused "some hours ago". My issue happens immediately every single time I pause a video.
