### ISSUE TITLE
The app crashes every time I try to open a video, and it doesn't work with background or popup playback too

### ISSUE THREAD

**Issue by asereze** [TeamNewPipe/NewPipe#4451] opened 2020-10-08 17:17 UTC
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to any section of the app
2. Try to open any video
3. The app crashes

If I try to open a video in NewPipe, any video, the app crashes. If I try to open it in background or in popup playback the app doesn't crash, but the app doesn't manage to open the stream, and it tells me "Could not play this stream".

## Exception
* User Action: requested stream
* Request: https://www.youtube.com/watch?v=FSwRoNtXdsE
* Content Country: GB
* Content Language: en
* App Language: sc
* Service: YouTube
* Version: 0.20.0
* OS: Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

org.schabi.newpipe.extractor.exceptions.ParsingException: Could not load decryption code for the Youtube service.
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerUrl(YoutubeStreamExtractor.java:705)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:655)
 at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
 at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
 at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
 at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
 at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
 at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
 at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
 at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerUrl(YoutubeStreamExtractor.java:700)
 ... 30 more

</details>
<hr>

### Device info

 - Android version/Custom ROM version: LineageOS 16.0 (Android 9.0)
 - Device model: Xiamo Redmi Note 4X

**Comment by xibr** [comment] 2020-10-08 17:23
duplicate of [#3753](https://github.com/TeamNewPipe/NewPipe/issues/3753)

**Comment by opusforlife2** [comment] 2020-10-08 19:10
Since this user seems to be encountering the error on every try and not just occasionally, it might be a different issue.

Could you try the apk from https://github.com/TeamNewPipe/NewPipeExtractor/pull/406#issuecomment-703729182, @asereze?

**Comment by safkhet** [comment] 2020-10-09 00:41
I have the exact same issue.

 Android version/Custom ROM version: LineageOS 17.1 (Android 10.0)
 Device model: One Plus 6T

**Comment by safkhet** [comment] 2020-10-09 00:58
> Since this user seems to be encountering the error on every try and not just occasionally, it might be a different issue.
> 
> Could you try the apk from [TeamNewPipe/NewPipeExtractor#406 (comment)](https://github.com/TeamNewPipe/NewPipeExtractor/pull/406#issuecomment-703729182), @asereze?

Just tested with the debug apk and it works :-)

**Comment by safkhet** [comment] 2020-10-09 01:28
> > Since this user seems to be encountering the error on every try and not just occasionally, it might be a different issue.
> > Could you try the apk from [TeamNewPipe/NewPipeExtractor#406 (comment)](https://github.com/TeamNewPipe/NewPipeExtractor/pull/406#issuecomment-703729182), @asereze?
> 
> Just tested with the debug apk and it works :-)

Tested some more and something intriguing happened. As soon as I imported my subscriptions and settings the debug apk started crashing as well. So I tried uninstalling and reinstalling from F-Droid (at this point I did not import subscriptions and settings), and it worked. Then I tried importing only subscriptions, but not the settings and it continued working. I guess there must be something incompatible in my old settings.

**Comment by opusforlife2** [comment] 2020-10-09 04:34
Oh no. This is another one of the bad migration bugs, then.

**Comment by wb9688** [comment] 2020-10-09 06:44
@opusforlife2: Nope, it's most likely the reCAPTCHA cookies that have expired. #4453 adds a button to clear them. The proper solution would be to also store the expiry date and let it expire then.

**Comment by asereze** [comment] 2020-10-09 13:12
> Could you try the apk from [TeamNewPipe/NewPipeExtractor#406 (comment)](https://github.com/TeamNewPipe/NewPipeExtractor/pull/406#issuecomment-703729182), @asereze?

I tried it and it seems to work without any issue!

**Comment by opusforlife2** [comment] 2020-10-09 13:44
@wb9688 This still looks like a migration issue. ^

**Comment by Stypox** [comment] 2020-10-09 20:03
@safkhet @asereze could you test the apk provided in #4453, and see if after importing settings and clearing the recaptcha cookie everything works fine?

**Comment by asereze** [comment] 2020-10-10 14:21
> @safkhet @asereze could you test the apk provided in #4453, and see if after importing settings and clearing the recaptcha cookie everything works fine?

I didn't find any apk there, where can I download it?

**Comment by opusforlife2** [comment] 2020-10-10 14:22
Yes, @Stypox, where is the apk? 🤭

**Comment by Stypox** [comment] 2020-10-11 09:02
Mmmh, I just assume every PR has an uploaded apk... then let's wait for @wb9688 to upload one

**Comment by wb9688** [comment] 2020-10-14 12:08
@Stypox: Done now, next time please don't assume…

**Comment by Stypox** [comment] 2020-10-14 12:26
Ok, sorry @wb9688 ;-)

**Comment by Stypox** [comment] 2020-10-17 12:41
Fixed by the reCAPTCHA PR and the `Could not load decryption code` PR, hopefully

**Closed by Stypox** 2020-10-17 12:41 UTC
Labels: bug

**Comment by opusforlife2** [comment] 2020-10-17 14:55
Let's ask?

@asereze, please test 0.20.1 and confirm whether your issue is fixed.

**Comment by asereze** [comment] 2020-10-18 21:27
> Let's ask?
> 
> @asereze, please test 0.20.1 and confirm whether your issue is fixed.

Yes, it seems to be working fine, now. Thank you!

**Comment by opusforlife2** [comment] 2020-10-19 04:24
Awesome! Thanks for confirming.
