### ISSUE TITLE
Background player: Painful volume spikes when playback resumes after a pause due to buffering

### ISSUE THREAD

**Issue by jmbreuer** [TeamNewPipe/NewPipe#3086] opened 2020-02-12 15:30 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I sometimes have a network connection that even for just audio playback using the background player cannot keep up.

When the buffer empties, there's a gap of silence (obviously). When there's data coming in again, playback resumes with a spike of much louder volume, quickly (50-200ms at a guess) returning to the previous playback volume. Especially with headphones, those spikes can be quite painful.

(Conjecture: are 'empty' frames being fed to the decoder so it loses its playback gain tracking?)

Also, I had the impression that bits of audio (less then a second long) would repeat and stutter multiple times in that situation.

**Comment by Stypox** [comment] 2020-02-12 15:53
Duplicate of #2833

**Closed by Stypox** 2020-02-12 15:53 UTC
Labels: bug, player
