### ISSUE TITLE
Videos need to be loaded twice to load

### ISSUE THREAD

**Issue by TheFrenchGhosty** [TeamNewPipe/NewPipe#2509] opened 2019-08-13 03:32 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Since a lot of time every time I try to load a video it doesn't load (or load after 10+ seconds) and I need to close the player, open it again and it will load instantly.
Happens on my 2 android devices.
This really destroy the user experience.

Here is a screenshot showing the first load
![newpipe](https://user-images.githubusercontent.com/47571719/62913170-a39ac600-bd7a-11e9-9b6c-b0e91018cfe2.png)

**Comment by Silent-Marco** [comment] 2019-08-13 03:43
Can confirm that I have the same issue.

**Comment by gkeegan** [comment] 2019-08-13 03:59
Does it work better when videos are set to 720p to load by default? If so this might be an old bug popping up again.

**Comment by TheFrenchGhosty** [comment] 2019-08-13 16:51
> Does it work better when videos are set to 720p to load by default? If so this might be an old bug popping up again.

It's complicated, sometimes it work without problem (even for 1080p 60 fps) but most of the time it doesn't, this is really inconsistent

**Comment by Stypox** [comment] 2020-04-27 07:15
Duplicate of #2415

**Closed by Stypox** 2020-04-27 07:15 UTC
Labels: bug, player, youtube
