### ISSUE TITLE
Crash upon reordering channel groups

### ISSUE THREAD

**Issue by SPAHulst** [TeamNewPipe/NewPipe#5748] opened 2021-03-04 10:20 UTC
### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to 'Subscriptions'
2. Press on the three stripes in the top left to reorder the channel group order
3. Press on the three bars to swift order

### Actual behaviour

Upon trying to shift a channel group, an UI crash occurs immediately and it sends me to the error report page

### Expected behavior

It should upon holding the bars of a particular channel group be able to shift up and down the order

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.20.10
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.xwray.groupie.Item.getDragDirs()' on a null object reference
	at com.xwray.groupie.GroupieViewHolder.getDragDirs(GroupieViewHolder.java:87)
	at com.xwray.groupie.TouchCallback.getDragDirs(TouchCallback.java:18)
	at androidx.recyclerview.widget.ItemTouchHelper$SimpleCallback.getMovementFlags(ItemTouchHelper.java:2293)
	at androidx.recyclerview.widget.ItemTouchHelper$Callback.getAbsoluteMovementFlags(ItemTouchHelper.java:1593)
	at androidx.recyclerview.widget.ItemTouchHelper$Callback.hasDragFlag(ItemTouchHelper.java:1598)
	at androidx.recyclerview.widget.ItemTouchHelper.startDrag(ItemTouchHelper.java:1092)
	at org.schabi.newpipe.local.subscription.item.FeedGroupReorderItem$bind$1.onTouch(FeedGroupReorderItem.kt:38)
	at android.view.View.dispatchTouchEvent(View.java:14305)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:859)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
	at android.view.View.dispatchPointerEvent(View.java:14568)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6022)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5825)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8086)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8037)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7998)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8209)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 11/CalyxOS 2.2.0
 - Device model: Pixel 4a

**Comment by SPAHulst** [comment] 2021-03-04 10:20
> ### Checklist
> * [x]  I am using the latest version - 0.20.10
> * [x]  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
> * [x]  I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
> * [x]  This issue contains only one bug. I will open one issue for every bug report I want to file.
> 
> ### Steps to reproduce the bug
> ### Actual behaviour
> Upon trying to shift a channel group, an UI crash occurs immediately and it sends me to the error report page
> 
> ### Expected behavior
> It should upon holding the bars of a particular channel group be able to shift up and down the order
> 
> ### Screenshots/Screen recordings
> ### Logs
> ## Exception
> * **User Action:** ui error
> * **Request:** App crash, UI failure
> * **Content Country:** GB
> * **Content Language:** en-GB
> * **App Language:** en_GB
> * **Service:** none
> * **Version:** 0.20.10
> * **OS:** Linux Android 11 - 30
> 
> Crash log
> ### Device info
> * Android version/Custom ROM version: Android 11/CalyxOS 2.2.0
> * Device model: Pixel 4a

**Comment by SPAHulst** [comment] 2021-03-04 10:24
Closed it on accident, sorry

**Comment by mhmdanas** [comment] 2021-03-04 14:08
I believe this is a duplicate of #5596. If you disagree, feel free to make a comment.

**Closed by mhmdanas** 2021-03-04 14:08 UTC
Labels: bug
