### ISSUE TITLE
Subscription import crash (no json file) ~ proposed bug

### ISSUE THREAD

**Issue by pcoopergit** [TeamNewPipe/NewPipe#7212] opened 2021-10-08 00:57 UTC
Google's takeaway data now doesn't come with subscriptions.json. Instead it ships the CSV file, which crashes Newpipe, as it won't support CSV import as of now.

**Comment by mhmdanas** [comment] 2021-10-08 18:22
Duplicate of #6757.

**Closed by mhmdanas** 2021-10-08 18:22 UTC
