### ISSUE TITLE
Background Player Queue management

### ISSUE THREAD

**Issue by f4m4z** [TeamNewPipe/NewPipe#6170] opened 2021-04-25 15:46 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be a nice feature to have the background player queue have a separate page in the main page section. (Youtube)

The only way it can be accessed as of now is by tapping the background player notification from notifications 

also when i remove newpipe from my recents while a youtube video is playing in the background, the video/song still keeps playing and tapping the notification takes you to the background player queue, but tapping the "back" button in the top-left corner just quits newpipe instead of taking you to the main screen, which is annoying.

these should probably be some quick and easy things to implement which would greatly improve the quality-of-life of this app for me and proabably anyone else who uses this app to listen to music from Youtube

![Screenshot_2021-04-25-21-38-20-666_org schabi newpipe](https://user-images.githubusercontent.com/65540671/115999891-95084700-a60f-11eb-9b9a-204a7e903996.jpg)

**Comment by mhmdanas** [comment] 2021-04-25 16:27
Duplicate of #2477.

**Closed by mhmdanas** 2021-04-25 16:27 UTC
Labels: enhancement
