### ISSUE TITLE
App crashes when in background

### ISSUE THREAD

**Issue by WorkHard4470** [TeamNewPipe/NewPipe#9070] opened 2022-10-05 05:51 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Use multitasking to go back to NewPipe app and can cause crash. Foreground running occured. There was a problem with search suggestions which caused by their multitasking action.

### Expected behavior

The app worked fine without errors.

### Actual behavior

Crashes with running in foreground service exception unable to start with correct time  `android.app.ForegroundServiceDidNotStartInTimeException` as it appears it can't look up search suggestions.

### Screenshots/Screen recordings

See logs below.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ PH
* __Content Language:__ en-PH
* __App Language:__ en_PH
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a13ad15 u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2078)
	at android.app.ActivityThread.access$2800(ActivityThread.java:259)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 [Global India ROM, realme UI 3.0]

### Affected device model

realme 8 4G

**Comment by WorkHard4470** [comment] 2022-10-05 05:54
Must require by open a Pull Request. The developer of their repo has not yet fix their error.

**Comment by tsiflimagas** [comment] 2022-10-05 06:41
I don't understand what you're writing in your comment, but this appears to be a duplicate of #9053, which in return appears to be a duplicate of #9030, and eventually this crash was described in https://github.com/TeamNewPipe/NewPipe/issues/8646#issuecomment-1236162209.

**Comment by opusforlife2** [comment] 2022-10-05 09:23
@tsiflimagas Sure? I'm no dev, but the STRs don't seem similar, despite the exception possibly being the same.

**Comment by WorkHard4470** [comment] 2022-10-05 10:07
There could be a problem by clicking the search history. Follows app crash.

**Comment by tsiflimagas** [comment] 2022-10-05 11:54
> @tsiflimagas Sure? I'm no dev, but the STRs don't seem similar, despite the exception possibly being the same.

Tbh I had by doubts thinking it again, as I'm not a developer either. Let's wait for one I guess.

**Comment by Rominet13** [comment] 2022-10-06 16:18
I noticed the same since the last version


## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Nokia/Phoenix_00WW/PNX_sprout:11/RKQ1.200906.002/00WW_6_210:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d0aaf0a u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2006)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```
</details>
<hr>

**Comment by EthanZeigler** [comment] 2022-10-07 16:23
I can confirm what @Rominet13 said. The app doesn't even have to be focused for this to occur. Just having the app in the background (not manually swiping closed from switcher) is enough to trigger the error. Newpipe will take focus back from whatever the current app is to display a near identical error to everyone else. I'm not sure what I would have done to cause it given the app wasn't open.

**Comment by opusforlife2** [comment] 2022-10-07 18:02
I've gotten a report about this from a user, too. The app can randomly crash while the user is busy using some other app.

**Comment by Rominet13** [comment] 2022-10-07 19:22
Ok, it always appears when disconnecting (and sometimes when connecting) bluetooth devices like my car or loud speaker (My watch is connected too but I don't think it changes anything.)
Way to reproduce : use normally (watch some video, or listen music in background), quit the app. And after some time, connect and disconnect to a Bluetooth device like a car.

**Comment by opusforlife2** [comment] 2022-10-07 19:39
Right. That's a known problem and has more to do with Android. Before version 0.24.0, you just got a blank player notification, since Newpipe was the last "media player" app used. Now it causes a crash.

@Stypox This seems actionable now. Is there a way to prevent Newpipe being seen as a media app by the OS? It obviously has something to do with the changed player code, but we might be able to bypass the problem entirely.

**Comment by opusforlife2** [comment] 2022-10-08 16:33
Can you all confirm that you haven't disabled the Newpipe player notification in your OS settings? I'm interested in knowing if your player notification is showing just fine and you still get this error.

I'm trying to narrow this bug down and the lack of the player notification may be a cause, since that's what Android uses to determine if the app should be kept in memory or not.

**Comment by Rominet13** [comment] 2022-10-08 17:48
If by "Newpipe player notification", you mean the "Hide player when the media session has ended (the player allows you to resume a session from the expanded quick setting panel)", it is disabled. I have never changed... I didn't know it exists^^. I m going to set it on ( I don't why with VLC I can resume but not with NewPipe. Maybe it is the solution.)

**Comment by opusforlife2** [comment] 2022-10-08 18:47
I'm... not sure, actually, if that Android 11+ setting matters. What I'm asking specifically is that when you play a video in the main player, popup player, or the background player, does the player notification show in the notification shade?

**Comment by Rominet13** [comment] 2022-10-08 20:35
Yes the player is in the notification shade, and I use it.

**Comment by opusforlife2** [comment] 2022-10-09 12:50
Alright, that's a dead end, then. Thanks for confirming!

**Comment by kirkawolff** [comment] 2022-10-10 15:18
This is with an older version, adding in case this helps

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_UNSPECIFIED] occurred while playing https://www.youtube.com/watch?v=qKDbVWa_obA
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.3
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:617)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker$PlaylistStuckException
	at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.processLoadedPlaylist(DefaultHlsPlaylistTracker.java:739)
	at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:584)
	at com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:512)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:478)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	... 2 more

```
</details>
<hr>

**Comment by esibun** [comment] 2022-10-14 16:40
This looks like the same issue that I have started seeing over the past week or two with my NewPipe client.

Reproduction steps for me were similar to already mentioned: Play a video in background, stop playback, then connect the phone to the car (or presumably any other Bluetooth device that causes autoplay).

I was able to create a Tasker task to take over media events and saw the crashes go away which confirms it was definitely Bluetooth autoplay which triggered the bug.

I've had this happen both with the player in the notification shade and after dismissing the player by hitting the "X" in the lower right.

Pressing "Play" on a pair of headphones also seems to trigger the bug.

**Comment by opusforlife2** [comment] 2022-11-09 12:50
@esibun Could you confirm the bug for 0.24.1, please?

**Comment by esibun** [comment] 2022-11-09 17:39
Tried this earlier against 0.24.1 and was unable to reproduce.  Might be fixed but should be able to say for sure this afternoon.

**Comment by EthanZeigler** [comment] 2022-11-09 19:06
I reproduced the issue last night in my car (Bluetooth connection) using
0.24.1 so it's not resolved. As someone earlier said, it has something to
do with Google play services so changes can happen at any time without us
knowing.

**Comment by cohesive-flight** [comment] 2022-11-22 14:29
I've also been experiencing this issue about several times a day for the past two weeks. I am using the SponsorBlock fork, but the logs are nearly identical.

For the log below, I only had NewPipe paused in the background while scrolling through another app. I was using Bluetooth ear buds, but I wasn't doing anything with them at that time. Furthermore, pressing play from them does not cause NewPipe to crash in my case, unlike what others have mentioned.
 
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 13 - 33 (Graphene OS)
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d49c7ac u0 org.polymorphicshade.newpipe/org.schabi.newpipe.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2007)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1978)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2243)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1936)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1891)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at org.schabi.newpipe.player.helper.PlayerHolder.startService(PlayerHolder.java:126)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$4.onReceive(VideoDetailFragment.java:1496)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	... 8 more

```
</details>
<hr>

**Closed** 2023-11-16 07:59 UTC
Labels: bug, player
