### ISSUE TITLE
View count In video list bug

### ISSUE THREAD

**Issue by dryx01** [TeamNewPipe/NewPipe#555] opened 2017-05-14 11:22 UTC
Hi,
I look that the see counter, in video search list, is wrong ( show 1 view whereas the real count is 1 million )
I hope you correct that, your software is awesome

**Comment by mauriciocolli** [comment] 2017-05-14 13:28
It should be shorting the numbers, in your case, 1M, are you sure that there's no 'M' next to it?

Also, this could be happening if one 'locale' translate the short M to just some spaces, can you tell me the language used in your phone?

**Comment by mauriciocolli** [comment] 2017-05-26 20:10
I'll close this as information has not been given and is working fine in various devices.

**Comment by dryx01** [comment] 2017-05-27 08:37
This is surely too late, but no, it has no "M" after the number of view.
And my system language is the French

**Comment by TobiGr** [comment] 2017-05-27 17:19
I can't reproduce this.
The `short_million` string has been added to the French translation 16 days ago, so it didn't exist as you opened the issue. But the English string (also a "M") should have been used instead.
Do you use the latest version from F-Droid (0.9.7) now?

**Comment by dryx01** [comment] 2017-05-27 18:17
![screenshot_20170527-201434](https://cloud.githubusercontent.com/assets/6872170/26523499/2748c6a2-4319-11e7-9061-94994caf274d.png)
For exemple the gagnam style with 2 bilions of view... And it's show only 2 view.
i hope that screenshot help you

**Comment by mauriciocolli** [comment] 2017-05-27 19:51
The extractor is f'd up, the regex is not selecting numbers with space (which french uses).

[YoutubeStreamInfoItemExtractor.java#L120](https://github.com/TeamNewPipe/NewPipeExtractor/blob/master/services/youtube/YoutubeStreamInfoItemExtractor.java#L120)  specifically:

```java
input = "2 851 804 788 visionnements"
output = Parser.matchGroup1("([0-9,\\. ]*)", input)
    .replace(" ", "")
    .replace(".", "")
    .replace(",", "");
```

which could be replaced by:
```java 
output = input.replaceAll("[^0-9]+", "");
```

I'll do some more tests and open a pull request fixing this.

**PS**: Someone  [translated](https://hosted.weblate.org/translate/newpipe/strings/fr/?type=all&offset=148) the billion abbreviation to "M", that is equal to the [abbreviation of million](https://hosted.weblate.org/translate/newpipe/strings/fr/?type=all&offset=147) (also "M"), I don't think it's right, @dryx01 could you tell me if it's (or what is) the correct abbreviation?

**Comment by dryx01** [comment] 2017-06-01 19:26
If I understand right your question, you want to know the good abbreviations un french. The billion must be "B" and million "M", if your question is that

**Comment by devnoname120** [comment] 2017-06-04 21:31
@mauriciocolli
- million = M 
- milliard = Mrd

**Comment by mauriciocolli** [comment] 2017-06-04 23:23
Just to compare, here's what Youtube translate it for (very likely a professional translation):

French| French (Canada)
---|---
![fr][1] | ![fr_ca][2]

[1]: https://cloud.githubusercontent.com/assets/13389907/26766192/d7e8afbe-4962-11e7-971b-fd9ca042f926.png
[2]: https://cloud.githubusercontent.com/assets/13389907/26766193/d7f03c66-4962-11e7-942d-5bb4d2658a46.png

**Comment by devnoname120** [comment] 2017-06-05 12:47
I guess it's better then to stick to the official translation. `G` is never used in French (France).

**Comment by dryx01** [comment] 2017-06-10 21:36
Yes, it's best to have Mrd.
You have fix it and update the app ?

**Comment by mauriciocolli** [comment] 2017-06-11 01:44
I already changed to `Md` (like YouTube does) here in [WebLate](https://hosted.weblate.org/translate/newpipe/strings/fr/?type=all&offset=128), the new translation should be in place in the next release.

But my pull request it's not merged yet in the extractor repository, and I don't have write access to it, so I don't know when it'll be fixed (I think it'll be till the next release).

**Comment by theScrabi** [comment] 2017-06-11 01:48
Right I wan't to take care of everything this weekend.

**Closed** 2017-06-11 11:59 UTC
Labels: bug
