### ISSUE TITLE
Add pinch to zoom Gesture for Videos

### ISSUE THREAD

**Issue by lu4p** [TeamNewPipe/NewPipe#3494] opened 2020-04-26 16:49 UTC
#### Describe the feature you want

I want a pinch gesture added on the fullscreen player to switch between the fit and the zoom viewmode.

#### Is your feature request related to a problem? Please describe it

No.

#### Additional context

Many other apps which play Video like Neflix, the offical Youtube app, VLC etc. already have this feature. So many Users expect this to work the same on Newpipe.

#### How will you/everyone benefit from this feature?

It makes it easier to switch between the fit and zoom mode which helps if you want to quickly switch between them e.g. something essential is cropped off in zoom mode.

**Comment by Stypox** [comment] 2020-04-27 06:42
Duplicate of #3181

**Closed by Stypox** 2020-04-27 06:42 UTC
Labels: enhancement
