### ISSUE TITLE
Could not play this stream

### ISSUE THREAD

**Issue by evildog1** [TeamNewPipe/NewPipe#3484] opened 2020-04-25 18:31 UTC
### Version

- v0.19.2

### Steps to reproduce the bug

1. Play any videos
(might be hard to reproduce)

### Expected behavior
To play video without random errors

### Actual behaviour
"Could not play this stream" appear randomly even it is cached and connection is fine and fast

### Screenshots/Screen recordings

No screenshot

### Logs

[2020-04-25-20-16-15.txt](https://github.com/TeamNewPipe/NewPipe/files/4533765/2020-04-25-20-16-15.txt)

**Comment by Stypox** [comment] 2020-04-27 06:15
Duplicate of #2415

**Closed by Stypox** 2020-04-27 06:15 UTC
Labels: bug

**Comment by evildog1** [comment] 2020-05-03 09:00
How is that related to that issue?

The video can play but the stream error just happen out of nowhere

**Comment by Stypox** [comment] 2020-05-03 12:15
Hls stream types cause 404 errors, that result in infinite loading on the main player and "could not play this stream" on the background one. But the cause is always the same

**Comment by evildog1** [comment] 2020-05-03 12:21
Oh ok
