### ISSUE TITLE
Video stream suddenly stops to buffer after short play

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#7404] opened 2021-11-14 09:55 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start video
2. Video start playing immediately for 1 second
3. Stops to "prebuffer" [?] for 5-10 seconds
4. Starts playing with huge buffer visible on the playbar

### Actual behavior

There seems to be enough data to start playing the video immediately but it does not happen, rather it starts loading after one seconds of play. It's really annoying. I use MPEG 1080p. The connection is stable and fast.

### Expected behavior

The video just plays immediately does not wait for buffer. And progressively loads a buffer as it plays ahead.

OR

Does not start playing, builds a small buffer, then plays.

Currently it just seems it COULD play the stream as it is an instant but doesn't. If there weren't buffer it would not play immediately.

### Device info

 - Android version/Custom ROM version: 11, UneUI 3.1.
 - Device model: SM-A528B/DS

**Comment by MD77MD** [comment] 2021-11-14 22:38
this is happening to me as well

**Comment by ChiefMikeK** [comment] 2021-11-15 03:37
> this is happening to me as well

I would suggest that you press the pause button and allow the buffer to continue to fill.  
my Internet is @ times _spotty/congested_

**Comment by IHateTheProgrammingClass** [comment] 2021-11-15 07:23
> this is happening to me as well
> 
> I would suggest that you press the pause button and allow the buffer to continue to fill.
> my Internet is @ times spotty/congested

In my experience that should not be related.

So anyways I would like to add that 1 second play then 10 second buffer is usually the worst case scenario. It varies a bit, there are 4 second plays than 2 second loads as well sometimes. It's weird. Probably buffer management? I don't know anything about things like this though.

**Comment by opusforlife2** [comment] 2021-11-15 16:38
Please try the APK linked in #7406.

**Comment by IHateTheProgrammingClass** [comment] 2021-11-15 17:40
@opusforlife2 I cannot download the apk no matter how much I try. Clicking on the apk under Artifacts does nothing to me.

**Comment by opusforlife2** [comment] 2021-11-15 17:42
@IHateTheProgrammingClass Something with your browser config. I could download it perfectly fine.

**Comment by IHateTheProgrammingClass** [comment] 2021-11-15 18:07
@opusforlife2 Could you conform I'm on the right page? And if not could you send the correct link?

https://github.com/TeamNewPipe/NewPipe/actions/runs/1459576199

I'm trying to tap on the app at the bottom Under Artifacts. I tried with both a vanilla Chromium and Firefox browser. It does not work for me.

**Comment by opusforlife2** [comment] 2021-11-15 18:10
@IHateTheProgrammingClass Yes, you have to be signed in. Github Actions does not allow guest downloads, unfortunately.

**Comment by IHateTheProgrammingClass** [comment] 2021-11-15 18:53
@opusforlife2 Currently testing the app and it still has stops. But now instead of starting to load 1-5 seconds in the video it additionally loads at the very beginning sometimes. So it basically plays 1 single frame, so the thumbnail of the video is not visible only the very first frame perhaps. So it loads then it sometimes even loads at like 5 secs too. I'll record it now. Do you know a place where I could upload videos to?

**Comment by IHateTheProgrammingClass** [comment] 2021-11-15 19:19
I noticed that in both apps if I did not had my settings and data imported there were basically no stops at all. Only notable difference being that I usually disable auto play. But then I noticed that the default resolution is 720p and I set it to 1080p and after that it stutters. So at 72p after short one second loads at the very beginning usually there were buffer already in the video or the stream was able to be maintained without stutters. So I believe there are not enough stream of data at 1080p. Both apps have this problem still. But then again idk why it can be played immediately and only start to have problems with the higher bandwidth after like 5 seconds into the video. Anyways it's still progress I believe. @opusforlife2

**Comment by Dangelman** [comment] 2021-11-20 15:18
Can confirm it happens to me too. When you start Newpipe and click on a video, it plays 2s and then it starts to buffer for 2s. Happens every time, and I have a great connection. Def not existence-shaking, but still annoying.

I noticed that it only happens to the first video you play.

**Comment by IHateTheProgrammingClass** [comment] 2021-11-20 17:53
It happens to me on most videos.

**Comment by Stypox** [comment] 2021-11-21 19:33
Did #7406 fix this (check out the APK there)? Please close if that's the case

**Comment by opusforlife2** [comment] 2021-11-21 19:36
@Stypox https://github.com/TeamNewPipe/NewPipe/issues/7404#issuecomment-969093268 ;)

**Comment by IHateTheProgrammingClass** [comment] 2021-11-30 21:29
The problem would probably be fine if the player would not wait until an unnecessary amount of buffer is preloaded. I have noticed that after loading a bunch the buffer bar is unnecessarily long compared to the required to even play. Perhaps it's the problem. @opusforlife2

**Comment by opusforlife2** [comment] 2021-12-01 09:38
@IHateTheProgrammingClass Try the RC. Not that there is a specific fix in it, but just to cover all bases.

**Comment by IHateTheProgrammingClass** [comment] 2021-12-01 11:56
Sorry for my lack of knowledge in this field but what is RC?

**Comment by opusforlife2** [comment] 2021-12-01 16:24
@IHateTheProgrammingClass Release candidate. See the pinned issue.

**Comment by IHateTheProgrammingClass** [comment] 2021-12-02 16:08
@opusforlife2 I have been testing the app and the issue seems to be solved. Thank you. If anything changes I will definitely notify this thread.

**Comment by IHateTheProgrammingClass** [comment] 2021-12-04 17:05
@opusforlife2 Uh... So I need to do some further testing. It seems that the issue is still present although seemed to disappear. I was on an unstable 5G connection (?, the one where the 5G icon is not filled in at the notification bar), and the stream acted the same. Starts, loads for like 10 seconds then plays when an unnecessary amount of buffer is loaded. I will try to find out if it was the more stable WiFi connection that I think I was using that were making the issue disappear or if not that, what did.

For the record I would like to state that I did the testing of the app by exporting the old one's database, importing it into the RC and I particularily made sure I was using the correct one from then on.

**Comment by IHateTheProgrammingClass** [comment] 2021-12-07 09:53
Another thing: It seems to be that sometimes, usually at the last quarter of a video the stream just stops. It loads and loads and that's it. If I shuffle back and fourth or just simply shuffle somewhere the stream continues. It's also really weird.

**Comment by opusforlife2** [comment] 2021-12-11 16:14
@IHateTheProgrammingClass This ^ looks like a separate issue. Please check for duplicates and open a new issue.

**Comment by Flam3z** [comment] 2021-12-16 20:26
This issue happens to me at random, i'll watch the stream for a few seconds then it stops and tells me "could not view stream" despite the streamer not going offline this has been happening for a while now.

**Comment by Dangelman** [comment] 2022-03-19 23:43
Don't know others but with the recently it got worse.
It was fixed for me for a period (I think it was with 0.21.16 or 0.22) but now I have to buffer 20s after launching NewPipe (doesn't happen when watching multiple videos in a session), even with a great connection.

**Comment by ShareASmile** [comment] 2024-02-17 17:34
Closing this Intermittent buffering issue since [Introduction of Support delivery methods other than progressive HTTP on 22June 2022](https://github.com/TeamNewPipe/NewPipe/pull/8153) it has been mitigated 

Also as it cannot be rechecked with its author as its author is a ghost now.

If anyone experiences this issue please open a new one.

**Closed** 2024-02-17 17:38 UTC
Labels: bug
