### ISSUE TITLE
Main page tabs aren't what they should be after import before restart

### ISSUE THREAD

**Issue by PeterHindes** [TeamNewPipe/NewPipe#3312] opened 2020-03-30 21:16 UTC
Imported data is only updated  after restart of NewPipe.
After importing data from an older version with a different tab arrangement, the taps will not contain the screen they should. Haven't tested with data from the current version. Fix is simple. Close the app and relaunch after importing. The app can do this its self to prevent user jank.

Different tab arrangement:
![image](https://user-images.githubusercontent.com/19994487/77962663-3ef49300-7299-11ea-8206-37b1ff8be467.png)

**Comment by mauriciocolli** [comment] 2020-03-30 22:26
I'm not able to replicate this, can you post more detailed steps to reproduce it [like the bug report template indicates](https://raw.githubusercontent.com/TeamNewPipe/NewPipe/5f549a8fc688157dfea8329408311e52e7e8c88f/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by PeterHindes** [comment] 2020-03-30 23:46
Sorry about that.
Steps
  1. Install older version of newpipe
  2. Use settings to change which tabs show on top
  3. Export settings from old version of newpipe
  4. Install newest newpipe.
  5. import settings
  6. return to the home screen and see that they are not what the icon says they are. Unitll
  7. Restart the app
  8. They behave normaly now.

**Comment by gkeegan** [comment] 2020-03-30 23:49
I have noticed odd behavior with the import as well when changing the tabs. Can confirm this is (or at least was, but I don't see commits that say it was fixed) a bug.

**Comment by PeterHindes** [comment] 2020-03-30 23:51
I tested it on a build of the code from the dev branch

**Comment by PeterHindes** [comment] 2020-03-30 23:52
Should be a simple fix to restart the app on import of settings.

**Comment by mauriciocolli** [comment] 2020-03-31 00:35
@PeterHindes

You can see in this [absolute bad practice of a class](https://github.com/TeamNewPipe/NewPipe/blob/5f549a8fc688157dfea8329408311e52e7e8c88f/app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java#L47) that the app is, indeed, [restarted](https://github.com/TeamNewPipe/NewPipe/blob/5f549a8fc688157dfea8329408311e52e7e8c88f/app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java#L254-L269). In my case, the app is restarted and all the tabs are what they should be, in various Android versions as well.

About that screenshot that you posted, [the name and the icon](https://github.com/TeamNewPipe/NewPipe/blob/5f549a8fc688157dfea8329408311e52e7e8c88f/app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java#L219-L228) match what it should be. Please, post screenshots before and after importing so we can see the difference.

But by what you just said above:

>Should be a simple fix to restart the app on import of settings.

And,

> 5. import settings
> 6. return to the home screen and see that they are not what the icon says they are. Unitll

Most probably the app is not restarting due to something specific to your device, you shouldn't be able to just return to the home screen.

Is that it? The app doesn't restart at all after confirming the two dialogs?

---

@gkeegan 

> Can confirm this is (or at least was, but I don't see commits that say it was fixed) a bug.

Please, post the before/after screenshots too. And does the app restart at all for you?

**Comment by gkeegan** [comment] 2020-03-31 00:37
I can't do screenshots since I'm on 0.19.0 and afraid to import data since it is apparently broken or something. What I remember is that it shows trending when it is supposed to be the channel list with the "whats new" bar at the top. What was supposed to be bookmarks because that page instead.

**Comment by gkeegan** [comment] 2020-03-31 00:39
It did restart when I did it yes.

**Comment by PeterHindes** [comment] 2020-03-31 00:41
I am running it in the android emulator on andorid r and on a oneplus 6t on android 10

**Comment by PeterHindes** [comment] 2020-03-31 00:41
Ill try to collect screen shots in a little while

**Comment by mauriciocolli** [comment] 2020-03-31 00:51
Oh, now I managed to replicate the bug. Will fix it shortly.

**Comment by opusforlife2** [comment] 2020-08-15 09:39
Still true as of 0.19.8.

**Comment by opusforlife2** [comment] 2021-06-20 19:38
Some (accidental?) progress on this: If you uninstall an APK, reinstall it, then import database, Newpipe immediately shows the correct main page tabs, and also shows a toast saying the language will be changed on app restart (if that setting has been changed from the default).

But for some reason, this does not happen for completely new APKs.

@PeterHindes Could you confirm if this is the case for you?

**Comment by PeterHindes** [comment] 2021-06-20 23:53
> Some (accidental?) progress on this: If you uninstall an APK, reinstall it, then import database, Newpipe immediately shows the correct main page tabs, and also shows a toast saying the language will be changed on app restart (if that setting has been changed from the default).
> 
> But for some reason, this does not happen for completely new APKs.
> 
> @PeterHindes Could you confirm if this is the case for you?

I don't have the original testing environment I was using. Sorry.

**Comment by opusforlife2** [comment] 2021-06-24 15:05
@PeterHindes Sorry, I didn't get it. What testing environment? To be clear, I'm talking about the current release of Newpipe.

**Comment by PeterHindes** [comment] 2021-06-24 16:07
> @PeterHindes Sorry, I didn't get it. What testing environment? To be clear, I'm talking about the current release of Newpipe.

I installed a different rom on my phone and haven't been using NewPipe. I don't have my old save data.

**Comment by opusforlife2** [comment] 2021-07-16 18:55
I just installed a brand new debug APK (from https://github.com/TeamNewPipe/NewPipe/pull/6673), and it was able to successfully import the database and run on the first try. Seems like this problem is fixed. I want to test one or two more new debug APKs before closing this, though.

**Comment by XiangRongLin** [comment] 2021-07-17 08:20
It's probably because of #6639.

Now the db is closed before the import and gets reopened on the new db.

**Comment by opusforlife2** [comment] 2021-08-11 05:34
This was actually fixed by #6639, but that's already merged, so I linked it to the Release PR instead.

**Comment by opusforlife2** [comment] 2021-08-14 02:31
Actually, fixed by #6495 in a previous release. Closing.

**Closed by opusforlife2** 2021-08-14 02:31 UTC
Labels: bug, GUI
