### ISSUE TITLE
Shuffle only shuffles the loaded videos, not the entire playlist

### ISSUE THREAD

**Issue by crkellen** [TeamNewPipe/NewPipe#1511] opened 2018-06-26 22:52 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

I have a large playlist of just under 300 videos I use to listen to music.
In order to get a better shuffle, I must go into the playlist, then scroll down, load the videos, scroll down some more, and continue this process until I reach the first video.

If I don't do that, it wont actually shuffle all the videos, making the actual randomization very low.

**Comment by agarwalakash06** [comment] 2018-10-31 02:04
This bug is a duplicate of #875

**Closed** 2019-08-27 12:18 UTC
