### ISSUE TITLE
Turn off display after xx (user-defined) minutes when the video has ended

### ISSUE THREAD

**Issue by RAPXT** [TeamNewPipe/NewPipe#7706] opened 2022-01-26 18:39 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

It would be nice, to have an option to turn off the display after a user-defined time when the video has already finished playing.

#### Why do you want this feature?

I've had a case in which I was listening to a (2h long) talk while it was very late at night and I was already tired. So eventually I fell asleep and the next day i just recognized with mild annoyance that my phone was completely drained, because the YouTube app  didn't turn off the display even hours after it was finished 🙄. Since I don't think YouTube will ever bother about what their users want (I just say, dislike-button), I put all my hope and trust in you, even if it may take a while.

**Comment by SameenAhnaf** [comment] 2022-01-26 21:43
See: https://github.com/TeamNewPipe/NewPipe/issues/2830#issuecomment-932482364

**Comment by litetex** [comment] 2022-01-27 20:11
As @SameenAhnaf already mentioned above, I also think this is a duplicate of #2830.

> It would be nice, to have an option to turn off the display after a user-defined time when the video has already finished playing.
> I've had a case in which I was listening to a (2h long) talk while it was very late at night and I was already tired...

... use NewPipe's background player? It doesn't require an active display.

> because the YouTube app didn't turn off the display even hours after it was finished 

1. NewPipe is not the YT app
2. I was unable to reproduce this behavior with NewPipe

**Closed by litetex** 2022-01-27 20:11 UTC
Labels: enhancement
