### ISSUE TITLE
Can't fully play any stream

### ISSUE THREAD

**Issue by emacrack** [TeamNewPipe/NewPipe#8307] opened 2022-04-29 14:07 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Every version till date, including 0.23.0 Debug version.

### Steps to reproduce the bug

1. Open app.
2. Play any video.

### Expected behavior

Play video correctly from beginning to end.

### Actual behavior

Video playing starts correctly, then after a couple of seconds/minutes it stops and app crashes.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_UNSPECIFIED] occurred while playing https://www.youtube.com/watch?v=qqAxQ9yVa5A
* __Content Country:__ US
* __Content Language:__ es-US
* __App Language:__ es_US
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 4.4.2 - 19
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:617)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: null
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:441)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.OutOfMemoryError
	at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
	at com.google.android.exoplayer2.source.SampleDataQueue.preAppend(SampleDataQueue.java:233)
	at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:176)
	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:590)
	at com.google.android.exoplayer2.extractor.TrackOutput$-CC.$default$sampleData(TrackOutput.java:157)
	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1436)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:342)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	... 3 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 4.4.2 Custom ROM

### Affected device model

UG802 Android Stick (With 1GB of RAM)

### Additional information

I'm experiencing this bug since the first time I found the app a year ago, so, this is the first time I'm reporting it but it happened with every single release till date.

EDIT: In case it's helpful, with 1080p video the error eccurs faster than with 720p.

**Comment by Stypox** [comment] 2022-04-30 12:43
I don't think we can do anything about this... your device just runs out of memory, try to close some apps in the background or use smaller resolutions

**Comment by emacrack** [comment] 2022-04-30 13:33
Well, I guess you guys know a lot more than me, it's just that SmartTubeNext works good on the same device and, as far as I know, both apps use ExoPlayer to play the videos. So, you're saying that NewPipe can't run on any device with 1Gb of RAM?? Couldn't it be caused by a memory leak?? Thanks anyway for taking the time to answer!!

**Comment by Stypox** [comment] 2022-04-30 13:54
Yes, it could well be that there is a memory leak. Could you check if #8170 improves anything by chance?

**Comment by emacrack** [comment] 2022-04-30 15:07
Sorry for the dumb question, I'm pretty new at Github. In order to test that I have to compile your fork with Android Studio, right?? Thanks again for your time and effort!!

**Comment by TiA4f8R** [comment] 2022-04-30 15:24
No, you don't have to, the CI compiles an APK for you :)

See the `Checks` tab of the pull request to get an APK (the instruction was removed by Stypox), then click on `Artifacts`.

If no `Artifacts` section is shown, click on the `CI on pull request` job, then scroll down to get the APK. Make sure you are logged in, GitHub doesn't allow guests to download CI artifacts.

**Comment by emacrack** [comment] 2022-04-30 16:03
Thank you so much!! I'll try it now to see how it goes. ;)

**Comment by emacrack** [comment] 2022-05-03 16:08
I've

> Yes, it could well be that there is a memory leak. Could you check if #8170 improves anything by chance?

Hi! I've tried it and the problem persists... I'm running the app with 496Mb of free RAM memory and all background processes disabled in Android's developer settings, so pretty much nothing else is being executed when I run NewPipe. Shouldn't it be enough for the app to work correctly?? I can't even get 720p videos to finish playing and I even tried disabling Thumbnails, Comments, etc, to save as much memory as possible. Maybe there's something else that's failing and it's not a memory related thing??

**Comment by emacrack** [comment] 2022-05-03 19:45
Thanks for opening it up again, hope we can find the solution! Whatever I can do from my side, just let me know! ;)

**Comment by litetex** [comment] 2022-05-03 20:07
Looks like a duplicate of #8282 to me.

> Android 4.4.2 Custom ROM

What OS are you using?

Btw, this will be "fixed" with #7613

**Comment by emacrack** [comment] 2022-05-03 21:16
> Looks like a duplicate of #8282 to me.
> 
> > Android 4.4.2 Custom ROM
> 
> What OS are you using?
> 
> Btw, this will be "fixed" with #7613

My device can't be upgraded to Lollipop, so, not a "fix" for me, just one less bug to fix for you guys if you drop 4.4 support... :'( 
I don't know what do you mean by "what OS I'm using", It's a custom KitKat ROM for a Rockchip RK3066 device.

**Comment by litetex** [comment] 2022-05-04 17:50
> custom KitKat ROM

And what is this OS called exactly? (You can usally check it in the about-tab inside the settings)

**Comment by SC1040-TS2** [comment] 2022-05-22 15:55
> And what is this OS called exactly? (You can usally check it in the about-tab inside the settings)

Having done some skimming on what the UG802 Android Stick is, it is apparently a mini PC used specifically with TVs to make them behave closer to a Smart TV, similar to a Chromecast or other device.
https://www.notebookcheck.net/Rockchip-RK3066-ARM-SoC.86864.0.html

This SoC usually only comes with Android 4.0.x Ice Cream Sandwich versions by default. However, a small community exists that revolves around rooting it and installing custom ROMs as part of customizing it for Android Media Center purposes.
https://www.dramasian.com/threads/ug802-the-ultimate-android-media-center-on-a-stick.76640/

One popular use for it is for running instances of XMBC, now known as the Kodi media player. However, it will never use the latest version of Kodi, as it now requires Android 5.0 Lollipop minimum.

**Closed** 2022-06-26 00:15 UTC
Labels: bug, device/software specific, waiting-for-author
