### ISSUE TITLE
Androidtv no statusbar/lockscreen controls

### ISSUE THREAD

**Issue by frotna** [TeamNewPipe/NewPipe#3593] opened 2020-05-15 10:20 UTC
Hi.
Thanks devs for this excellent app.
I tried Newpipe on ShieldTV (android Pie based) and noticed few things (not bugs but issues) that can be improved for better user experience on androidTV platforms.
AndroidTV is lack of status bar and lockscreen and thus there is no way to control background playback (like on phone it can be controlled by controls in status bar or on lockscreen).
Also popup window doesn't respond to size change in options (it's always default size).
Thanks once more for excellent app...

**Comment by wb9688** [comment] 2020-05-15 10:34
Are you using v0.19.3? And could you test whether the APK in https://github.com/TeamNewPipe/NewPipe/pull/3178#issuecomment-628684161 fixes it?

**Comment by frotna** [comment] 2020-05-15 10:37
Yes 0.1.93...
Just downloaded app, will test asap and report...

**Comment by frotna** [comment] 2020-05-15 11:15
Installed it and these are observations:
Still no way to control background playback (I'm doing it with this workaround. Installed ProjectM visualizer and when set background music i can control next/prew with controls of ProjectM visualizer...)
Also can't access list of background music...
I think good way to control background playback on androidTV would be through widget on Launcher...
Also, popup window still doesn't respond to changes in settings...

**Comment by B0pol** [comment] 2020-05-15 11:20
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3515.

For the popup, as it's gesture based there is ro way to control it too.

**Closed by B0pol** 2020-05-15 11:20 UTC
Labels: enhancement
