### ISSUE TITLE
Popup player doesn't start at the right frame

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [TeamNewPipe/NewPipe#6136] opened 2021-04-21 21:54 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Watch a video
2. Press on the popup player
3. U will notice that the popup player doesnt start at the same frame.

So i encountered this bug multiple times but it looks like its random.

### Actual behavior
When u enable popup player while u are watching a video the video will skip back frames up to a few minutes.

### Expected behavior

Start at the same frame when u clicked on popup.

### Device info

 - Android version/Custom ROM version: Andrioid 11 Graphene OS
 - Device model: Google pixel 3a Xl

**Comment by sauravrao637** [comment] 2021-04-22 10:12
https://user-images.githubusercontent.com/56369484/115697424-2f069000-a381-11eb-97bd-e4f4f4ed9a34.mp4

Here is the screen recording for the same

**Comment by mhmdanas** [comment] 2021-04-22 13:41
Duplicate of #4497.

**Closed by mhmdanas** 2021-04-22 13:41 UTC
Labels: bug
