### ISSUE TITLE
Video plays while the feed is loading when touched on the screen

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#6289] opened 2021-05-14 10:17 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Whats new' 
2. Swipe down to refresh
3. While feed is loading, CLICK anywhere on the screen (in the marked region of screenshot)

### Actual behaviour

The video, which was there in the list (before refreshing), starts playing.

### Expected behavior

No touch input should be registered in that portion of loading screen. 

### Screenshots/Screen recordings

![feed_click_error](https://user-images.githubusercontent.com/50160188/118255807-696cd400-b4cc-11eb-9761-d28cdee3b253.jpg)

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment] 2021-05-28 17:41
Duplicate of #6081.

**Closed by mhmdanas** 2021-05-28 17:41 UTC
Labels: bug
