### ISSUE TITLE
UI Crash When See Queue in Split Mode

### ISSUE THREAD

**Issue by BillyAppetie** [TeamNewPipe/NewPipe#8540] opened 2022-06-24 11:41 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Play a video as background
<img alt="bugreport1" src="https://user-images.githubusercontent.com/108044794/175525931-9cae1369-3544-41d0-8fa7-4657ce072a4a.png" height=600 />

2. Go to queue via notification
<img alt="bugreport2" src="https://user-images.githubusercontent.com/108044794/175526005-4c62cc50-9de9-4786-91f4-92b5e43abee5.png" height=600 />

3. Split your screen and an error occured

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ ID
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.PlaybackParameters org.schabi.newpipe.player.Player.getPlaybackParameters()' on a null object reference
	at org.schabi.newpipe.player.PlayQueueActivity.onCreateOptionsMenu(PlayQueueActivity.java:100)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3482)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3084)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 9

### Affected device model

Asus Zenfone Max Pro M1

**Comment by litetex** [comment] 2022-06-24 19:09
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/8058

**Closed by litetex** 2022-06-24 19:09 UTC
Labels: bug
