### ISSUE TITLE
permanent white screen on android 4.2

### ISSUE THREAD

**Issue by turboteckel** [TeamNewPipe/NewPipe#425] opened 2017-01-24 17:59 UTC
After starting the application (0.8.8) it shows a permanent white screen that's only removable by restarting the device. The Home button doesn't seem to do anything. It feels like an infinite loop.

**Comment by theScrabi** [comment] 2017-01-24 21:43
That is strange.

**Comment by aikobel** [comment] 2017-01-25 09:35
Same for me on Android 4.1.2 (S3 Mini): infinite loop and forced to reboot.

**Comment by auroszx** [comment] 2017-01-25 14:28
Something similar happening on my LG P500 (Android 4.0.4). App launches and exits over and over only showing a white screen. However, I'm able to use my home button (pressing several times), go to app settings and force close it. Still, doesn't work. No issues on my Nexus 7 2012 (Android 4.4.4).

**Comment by selvodka** [comment] 2017-01-25 23:06
Me to it flashes white but I can press the home button couple times  to close it

**Comment by ksyko** [comment] 2017-01-26 07:07
Can anyone test this?
https://github.com/TeamNewPipe/NewPipe/pull/427 

[https://drive.google.com/file/d/0B-FjP9BFWN3ibWY5RDNlZnhLSTA/view?usp=sharing](Download)

**Comment by turboteckel** [comment] 2017-01-26 13:01
Will test later today.

**Comment by auroszx** [comment] 2017-01-26 18:51
Can confirm. Fixed over here as well.

**Comment by k3b** [comment] 2017-02-02 01:14
Confirm problem fixed in NewPipe-0.8.9. 

I had the sampe problem with my android-4.2 (api-17) with NewPipe-0.8.8. 

With NewPipe-0.8.9 the problem is gone

**Closed** 2017-02-02 07:51 UTC
