### ISSUE TITLE
Video stream crashes when playback speed is changed.

### ISSUE THREAD

**Issue by usearchbtw** [TeamNewPipe/NewPipe#8250] opened 2022-04-17 18:42 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0

### Steps to reproduce the bug

1. Play any video.
2. Change the playback speed of video (Increase or decrease )
3. Video playback crashes.

### Expected behavior

Video should continue to play at the new speed.

### Actual behavior

Video stops playing when speed is changed.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/95747869/163728006-12b5479a-ad06-4267-b916-de57a6b256a9.mp4

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=1] occurred while playing https://www.youtube.com/watch?v=BL4DCEp7blY
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.22.2
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 640, 29.97003], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:864)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:100)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1842)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
	... 5 more

```
</details>
<hr>

### Affected Android/Custom ROM version

LineageOS 18.1

### Affected device model

Oneplus 6T

**Comment by litetex** [comment] 2022-04-17 20:58
Duplicate of #8250

**Closed by litetex** 2022-04-17 20:58 UTC
Labels: bug

**Comment by opusforlife2** [comment] 2022-04-19 08:45
@litetex This 'marking issues as their own duplicates' seems to be a regular thing now. 😆
