### ISSUE TITLE
maximizing Pop Out forces Orientation Lock

### ISSUE THREAD

**Issue by IronAnimation** [TeamNewPipe/NewPipe#8124] opened 2022-03-29 02:53 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

current

### Steps to reproduce the bug

Set phone to Portrait Mode, locked

open a video in pop up player

click to Expand pop up player video

### Expected behavior

Switch to full screen, but if I click back button, exit full screen with the app navigation still in portrait mode.

### Actual behavior

App Navigation will be locked in Landscape mode unless you turn off Portrait Lock.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=1] occurred while playing https://www.youtube.com/watch?v=_3JfV7AdHdw
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640020, -1, null, [1280, 720, -1.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.640020, -1, null, [1280, 720, -1.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1051)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:606)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1465)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:713)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:998)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:830)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The surface has been released
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1960)
	at android.media.MediaCodec.configure(MediaCodec.java:1889)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:50)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1137)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1044)
	... 10 more

```
</details>
<hr>

### Additional information

in video, phone is vertical during entire duration.

**Comment by IronAnimation** [comment] 2022-03-29 02:58
![Screenshot_20220328-215601_One UI Home](https://user-images.githubusercontent.com/46913977/160524064-571bbcf6-8ef4-4aed-8aba-5474e2f45b86.jpg)
![Screenshot_20220328-215701_NewPipe](https://user-images.githubusercontent.com/46913977/160524078-f19b2e46-3e57-49bd-894b-851ba9ed8f6c.jpg)
![Screenshot_20220328-215708_One UI Home](https://user-images.githubusercontent.com/46913977/160524094-0d224ea3-93d1-42ee-9c5b-aa0437b41901.jpg)
![Screenshot_20220328-215719_One UI Home](https://user-images.githubusercontent.com/46913977/160524116-c3198d4b-0f5e-4e98-ba82-80334f8bec96.jpg)
![Screenshot_20220328-215722_NewPipe](https://user-images.githubusercontent.com/46913977/160524151-01f8d46e-b5f4-4d49-a1ce-93a8745cd1ac.jpg)

**Comment by mhmdanas** [comment] 2022-05-22 11:30
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/8016.

**Closed** 2022-05-22 11:31 UTC
Labels: duplicate
