### ISSUE TITLE
'Invalid URL' on Playlist Download

### ISSUE THREAD

**Issue by Samdvich** [TeamNewPipe/NewPipe#2216] opened 2019-03-14 21:15 UTC
When you share a playlist, you get an option to choose 'NewPipe' from there, you're able to select download.

However, this download outputs an 'Invalid URL' message. _Looking forward to seeing the ability to download playlists though._

**Comment by Stypox** [comment] 2019-09-27 05:26
Duplicate of #928

**Closed by Stypox** 2019-09-27 05:26 UTC
