### ISSUE TITLE
UI crash after tapping related video

### ISSUE THREAD

**Issue by sha-257** [TeamNewPipe/NewPipe#7822] opened 2022-02-05 18:49 UTC
Video is played.  At any time when tapping a related video, a full reload of the UI occurs (not full reload of OS).
Full logcat attached.

Crash occurs on line 24595 (abbreviated): 
```
02-05 13:23:17.235  1295  2439 I MediaFocusControl: requestAudioFocus() from uid/pid 10260/10673 clientId=android.media.AudioManager@f86894org.schabi.newpipe.player.helper.AudioReactor@2313d5 callingPack=org.schabi.newpipe req=1 flags=0x2 sdk=29
:eyes: 
**02-05 13:23:17.235   951   951 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc60 in tid 951 (surfaceflinger), pid 951 (surfaceflinger)**
02-05 13:23:17.257  1295  2439 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
02-05 13:23:17.257   866 10804 D msm8974_platform: platform_split_snd_device: snd_device(3) num devices(1) new_snd_devices(0)
02-05 13:23:17.257   866 10804 D ACDB-LOADER: ACDB -> send_audvoltable
02-05 13:23:17.257   866 10804 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_INSTANCE_GAIN_DEP_STEP_TABLE_SIZE
02-05 13:23:17.257   866 10804 D android.hardware.audio.service: Failed to fetch the lookup information of the device 0000000E 
02-05 13:23:17.257   866 10804 D ACDB-LOADER: Error: ACDB_CMD_GET_AUDPROC_INSTANCE_GAIN_DEP_STEP_TABLE_SIZE Returned = -19
02-05 13:23:17.257   866 10804 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_INSTANCE_GAIN_DEP_STEP_TABLE, vol index 0
02-05 13:23:17.257   866 10804 D android.hardware.audio.service: Failed to fetch the lookup information of the device 0000000E 
02-05 13:23:17.257   866 10804 D ACDB-LOADER: Error: ACDB AudProc vol returned = -19
02-05 13:23:17.257   866 10804 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 40
02-05 13:23:17.257   866 10804 W msm8974_platform: platform_send_gain_dep_cal: Usecase list is empty
02-05 13:23:17.258   866  1722 D msm8974_platform: platform_split_snd_device: snd_device(3) num devices(1) new_snd_devices(0)
02-05 13:23:17.258   866  1722 W msm8974_platform: platform_send_gain_dep_cal: Usecase list is empty
02-05 13:23:17.260   942  1283 W APM::AudioPolicyEngine: getDevicesForStrategy() unknown strategy: -1
02-05 13:23:17.260   942  1283 W APM::AudioPolicyEngine: getDevicesForStrategy() unknown strategy: -1
02-05 13:23:17.263   866  1044 I offload_effect_bb: bassboost_set_device: ctxt 0xe8180d68, disabled based on device
02-05 13:23:17.276 10819 10819 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
02-05 13:23:17.277   725   725 I tombstoned: received crash request for pid 951
02-05 13:23:17.277 10819 10819 I crash_dump64: performing dump of process 951 (target tid = 951)
02-05 13:23:17.286 10819 10819 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-05 13:23:17.286 10819 10819 F DEBUG   : Build fingerprint: 'Nokia/BabyGroot_00WW/BGT_sprout:11/RKQ1.200928.002/00WW_2_27D:user/release-keys'
02-05 13:23:17.286 10819 10819 F DEBUG   : Revision: '0'
02-05 13:23:17.286 10819 10819 F DEBUG   : ABI: 'arm64'
02-05 13:23:17.287 10819 10819 F DEBUG   : Timestamp: 2022-02-05 13:23:17-0500
02-05 13:23:17.287 10819 10819 F DEBUG   : pid: 951, tid: 951, name: surfaceflinger  >>> /system/bin/surfaceflinger <<<
02-05 13:23:17.287 10819 10819 F DEBUG   : uid: 1000
02-05 13:23:17.287 10819 10819 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc60
02-05 13:23:17.287 10819 10819 F DEBUG   : Cause: null pointer dereference
02-05 13:23:17.287 10819 10819 F DEBUG   :     x0  0000000000000000  x1  0000000000000000  x2  0000007fc1759d38  x3  0000000000000000
02-05 13:23:17.287 10819 10819 F DEBUG   :     x4  0000000000000010  x5  0000000000000000  x6  0000000000000000  x7  0000007fc1759699
02-05 13:23:17.287 10819 10819 F DEBUG   :     x8  0000000000000001  x9  00000000000fffff  x10 0000000000000001  x11 0000000000000000
02-05 13:23:17.287 10819 10819 F DEBUG   :     x12 0000000000000000  x13 0000000000000000  x14 b4000076ff5e8c30  x15 0000000000000000
02-05 13:23:17.287 10819 10819 F DEBUG   :     x16 000000798fe6e260  x17 00000079906d5b80  x18 0000007991ca0000  x19 b40000782f5ec930
02-05 13:23:17.287 10819 10819 F DEBUG   :     x20 b40000782f5ec8c0  x21 b4000076ff5efa10  x22 0000000000000000  x23 0000000000000000
02-05 13:23:17.287 10819 10819 F DEBUG   :     x24 0000007991793000  x25 0000007991793000  x26 0000000000000000  x27 0000000000000001
02-05 13:23:17.287 10819 10819 F DEBUG   :     x28 0000000000000007  x29 0000007fc1759cf0
02-05 13:23:17.287 10819 10819 F DEBUG   :     lr  000000798fda3168  sp  0000007fc1759cf0  pc  000000798fd46f24  pst 0000000040000000
[logcat-for-debugging.txt](https://github.com/TeamNewPipe/NewPipe/files/8008648/logcat-for-debugging.txt)

02-05 13:23:17.292  2399  2399 D SarTest : sar state 10101 10101
02-05 13:23:17.320 10819 10819 F DEBUG   : backtrace:
02-05 13:23:17.320 10819 10819 F DEBUG   :       #00 pc 00000000000def24  /system/lib64/libsurfaceflinger.so (android::Layer::setFrameRate(android::Layer::FrameRate)+32) (BuildId: 4bdd79de7997f77bf9a732a4996db879)
02-05 13:23:17.320 10819 10819 F DEBUG   :       #01 pc 000000000013b164  /system/lib64/libsurfaceflinger.so (_ZNSt3__120__packaged_task_funcIZN7android14SurfaceFlinger12setFrameRateERKNS1_2spINS1_22IGraphicBufferProducerEEEfaE4$_68NS_9allocatorIS8_EEFNS1_4$_69EvEEclEv$4167f4dd1ce157dd16d3d26fc671a663+116) (BuildId: 4bdd79de7997f77bf9a732a4996db879)
02-05 13:23:17.320 10819 10819 F DEBUG   :       #02 pc 000000000013aef8  /system/lib64/libsurfaceflinger.so (_ZN7android4TaskIZNS_14SurfaceFlinger12setFrameRateERKNS_2spINS_22IGraphicBufferProducerEEEfaE4$_68E13handleMessageERKNS_7MessageE$4167f4dd1ce157dd16d3d26fc671a663+80) (BuildId: 4bdd79de7997f77bf9a732a4996db879)
02-05 13:23:17.320 10819 10819 F DEBUG   :       #03 pc 0000000000019b88  /system/lib64/libutils.so (android::Looper::pollInner(int)+372) (BuildId: 4e69b93bf70ed592f0029dbd1097529e)
02-05 13:23:17.320 10819 10819 F DEBUG   :       #04 pc 00000000000199ac  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: 4e69b93bf70ed592f0029dbd1097529e)
02-05 13:23:17.320 10819 10819 F DEBUG   :       #05 pc 00000000000fb64c  /system/lib64/libsurfaceflinger.so (android::impl::MessageQueue::waitMessage()+84) (BuildId: 4bdd79de7997f77bf9a732a4996db879)
02-05 13:23:17.320 10819 10819 F DEBUG   :       #06 pc 000000000010cf18  /system/lib64/libsurfaceflinger.so (android::SurfaceFlinger::run()+20) (BuildId: 4bdd79de7997f77bf9a732a4996db879)
02-05 13:23:17.320 10819 10819 F DEBUG   :       #07 pc 0000000000002394  /system/bin/surfaceflinger (main+844) (BuildId: 3af5c63a4962244c1b80cdbf315f3d33)
02-05 13:23:17.320 10819 10819 F DEBUG   :       #08 pc 00000000000499e4  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: 8d77279a411c99f8bc6edb79c76340fb)
```

**Comment by opusforlife2** [comment] 2022-02-05 21:10
If this crash is reproducible, could you try it once again while running [Scoop](https://f-droid.org/en/packages/taco.scoop/) and paste the crash log here?

**Comment by sha-257** [comment] 2022-02-07 14:22
Installed scoop, made it crash, scoop says nothing has crashed.

**Comment by litetex** [comment] 2022-02-07 20:38
Duplicate of #5961:

Same exception stack. Same manufacturer.

**Closed by litetex** 2022-02-07 20:38 UTC
