### ISSUE TITLE
[Feature Request] Support for vr movement in vr videos

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6521] opened 2021-06-19 13:45 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be nice if you could add youtube vr to vr videos. And it would be kinda cool

#### Is your feature request related to a problem? Please describe it

I can't watch vr like the way it should be watched.

**Comment by mhmdanas** [comment] 2021-06-19 15:24
Duplicate of #2835.

**Closed by mhmdanas** 2021-06-19 15:24 UTC
Labels: enhancement
