### ISSUE TITLE
Import not possible

### ISSUE THREAD

**Issue by naddel81** [TeamNewPipe/NewPipe#4810] opened 2020-11-05 21:23 UTC
YouTube subscriptions manager does not create XML file, but instead opens

https://www.youtube.com/feed/channels

please help me. cannot create the needed xml file. not even on PC.

**Comment by Stypox** [comment] 2020-11-05 21:34
*Please **follow the issue template** when creating an issue, don't just delete everything!* Duplicate of #4720

**Closed** 2020-11-05 21:34 UTC
Labels: bug
