### ISSUE TITLE
Add support for av1 video download

### ISSUE THREAD

**Issue by hvjufg** [TeamNewPipe/NewPipe#6013] opened 2021-04-06 05:54 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Right now not many devices have support for hardware level av1 decoding and hence it might be hard to support av1 videos in newpipe itself, but can you please add an option to download atleast.av1 videos Play fine in mpv

**Comment by Redirion** [comment] 2021-04-08 03:39
Hi, sorry but this is a duplicate of #2849

**Closed by Redirion** 2021-04-08 03:39 UTC
Labels: enhancement
