### ISSUE TITLE
ArrayIndexOutOfBoundsException while postprocessing download of 1080p60fps video

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#3296] opened 2020-03-29 16:07 UTC
### Version

- 0.19.0 RC5

### Steps to reproduce the bug

1. Open https://www.youtube.com/watch?v=I5Zb4w03atU in NewPipe
2. Start a download with 1080p 60fps
3. Wait until download finished
4. Postprocessing fails at ~18%

For more info, see https://github.com/TeamNewPipe/NewPipe/issues/3266#issuecomment-605659721

## Exception
* __User Action:__ download post-processing
* __Request:__ https://www.youtube.com/watch?v=I5Zb4w03atU [ {type=video format=MPEG-4 quality=1080p60 videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.19.0
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: src.length=7730 srcPos=-15217326 dst.length=8192 dstPos=0 length=8192
	at java.lang.System.arraycopy(System.java:527)
	at us.shandian.giga.io.CircularFileWriter$BufferedFile.write(CircularFileWriter.java:405)
	at us.shandian.giga.io.CircularFileWriter.write(CircularFileWriter.java:231)
	at org.schabi.newpipe.streams.Mp4FromDashWriter.outWrite(Mp4FromDashWriter.java:502)
	at org.schabi.newpipe.streams.Mp4FromDashWriter.build(Mp4FromDashWriter.java:363)
	at us.shandian.giga.postprocessing.Mp4FromDashMuxer.process(Mp4FromDashMuxer.java:22)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:174)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:702)
	at us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(Unknown Source:0)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

```
</p></details>

**Comment by TobiGr** [comment] 2020-03-29 16:09
CC @kapodamy

**Comment by givemestella** [comment] 2020-03-29 18:17
Thanks, however the non 60fps 1080 version (3.61GB file) also produced the same error at postprocessing stage. So not just 60fps.  Also the file that I tried d/l earlier today,  the 1080 60fps 3.64GB file, is now showing as 5.01GB...for some reason, trying again now...

**Comment by givemestella** [comment] 2020-03-29 18:46
Ok that still failed.  Not sure why the download was showing as 5.01GB and not 3.64GB like it was earlier today. Thought it was going to work this time.

{
   "user_action": "download post-processing",
   "request": format=MPEG-4 quality=1080p60 videoOnly=true}  {type=audio format=m4a bitrate=128} ]",
   "content_language": "en_GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe.debug.release",
   "version": "0.19.0",
   "os": "Linux Android 10 - 29",
   "time": "2020-03-29 18:43",
   "exceptions": [
      "java.lang.ArrayIndexOutOfBoundsException: src.length=4614 srcPos=-15337530 dst.length=8192 dstPos=0 length=8192\n\tat java.lang.System.arraycopy(System.java:527)\n\tat us.shandian.giga.io.CircularFileWriter$BufferedFile.write(CircularFileWriter.java:405)\n\tat us.shandian.giga.io.CircularFileWriter.write(CircularFileWriter.java:231)\n\tat org.schabi.newpipe.streams.Mp4FromDashWriter.outWrite(Mp4FromDashWriter.java:502)\n\tat org.schabi.newpipe.streams.Mp4FromDashWriter.build(Mp4FromDashWriter.java:363)\n\tat us.shandian.giga.postprocessing.Mp4FromDashMuxer.process(Mp4FromDashMuxer.java:22)\n\tat us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:174)\n\tat us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:702)\n\tat us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(Unknown Source:0)\n\tat us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(Unknown Source:2)\n\tat java.lang.Thread.run(Thread.java:919)\n"
   ],
   "user_comment": ""
}

**Comment by kapodamy** [comment] 2020-03-29 19:26
@givemestella youtube-dl does the same thing first shows ~3GB and later 5GB

**Comment by givemestella** [comment] 2020-03-29 20:45
Ok interesting... So using youtube-dl it completes the DL with a warning in its logs.  "Requested formats are incompatible for merge and will be merged into mkv." The resultant 60fps .mkv is playable. Maybe this is why this fails in newpipe?

**Comment by givemestella** [comment] 2020-03-30 11:17
Also happens with 0.19.0 release not just rc5.

**Comment by kapodamy** [comment] 2020-03-30 16:21
@givemestella i known, the file is to big. i still searching the cause

**Closed** 2020-04-01 20:29 UTC
Labels: bug, downloader
