### ISSUE TITLE
NewPipe not Downloading 

### ISSUE THREAD

**Issue by hackin9-panda** [TeamNewPipe/NewPipe#2961] opened 2020-01-14 23:27 UTC
NewPipe will not download video or audio to any location when i try i get  the error 
"The file can not be created"

**Comment by gkeegan** [comment] 2020-01-15 00:06
Does NewPipe have storage permissions granted?

**Comment by hackin9-panda** [comment] 2020-01-15 14:59
I do not know 
Can you tell me have to give it the permissions

**Comment by gkeegan** [comment] 2020-01-15 19:25
Device settings>apps>newpipe>permissions

**Comment by hackin9-panda** [comment] 2020-01-16 05:54
Yes it does but sadly it still dies not work

**Comment by hackin9-panda** [comment] 2020-01-16 05:55
Is their any other app I can use to change the folder permissions. I have root permisionds if needed

**Comment by gkeegan** [comment] 2020-01-16 05:58
Strange. What version of NewPipe are you using and what device are you using? (Maker, model, android version)

**Comment by hackin9-panda** [comment] 2020-01-16 06:08
I don't know what version of newpipe I am useing

**Comment by hackin9-panda** [comment] 2020-01-16 06:09
My android is as follows 
Android 4.4.2
Model sm-g386w
Maker Samsung

**Comment by hackin9-panda** [comment] 2020-01-16 06:10
I just looked the newpipe version is 0.18.0

**Comment by hackin9-panda** [comment] 2020-01-16 17:50
is their any thing i can do to help this problem get solved

**Comment by hackin9-panda** [comment] 2020-01-17 06:35
I am getting another error on another app that say the downloads folder is read only
Is their any way t fix this

**Comment by gkeegan** [comment] 2020-01-17 06:36
Are you using the default downloads folder on the local storage?

**Comment by hackin9-panda** [comment] 2020-01-17 07:06
Yes

**Comment by hackin9-panda** [comment] 2020-01-17 07:07
Its at /storage/emulated/0/Dwonload

**Comment by hackin9-panda** [comment] 2020-01-17 07:08
Sorry Download

**Comment by hackin9-panda** [comment] 2020-01-17 07:18
The only app that had been able to edit the downloads dir is the stock file manager

**Comment by gkeegan** [comment] 2020-01-17 07:24
Maybe create a new folder outside of downloads and set NewPipe to download there.

**Comment by hackin9-panda** [comment] 2020-01-17 07:45
Just tried that and it did not work

**Comment by gkeegan** [comment] 2020-01-17 08:16
Well I don't know what else to try then, sorry. It doesn't seem like a NewPipe issue since it effects other apps besides NewPipe.

**Comment by Kukulkan2019** [comment] 2020-01-19 00:50
Right,, here's another problem with this broken app and I thought it was just me... Last night I spent hours trying to figure out why it was not downloading audio into the device, well somehow it was downloading into the files but not picked up by the device music system which previously it was... Today I woke up and tried to do the video thing, not working, even after unistalling/installing the new pipe app again... 💀

**Comment by Kukulkan2019** [comment] 2020-01-19 01:16
> Does NewPipe have storage permissions granted?

Of course it has storage permissions granted, that's automatically applied when you download the app, but just to be sure I checked anyway, it's there, the problem again is not with the users but with new pipe as happened a couple of months ago or whenever it was... It was downloading audio & video fine then all of a sudden it was not.

**Comment by gkeegan** [comment] 2020-01-19 01:48
>Of course it has storage permissions granted, that's automatically applied

No. You get a prompt asking for permission, and it was possible he had pressed no.

**Comment by Kukulkan2019** [comment] 2020-01-19 02:29
It is a New Pipe issue, what other apps? New Pipe is not downloading audio & video as it was previously 
![Screenshot_20200119_102633_com google android packageinstaller](https://user-images.githubusercontent.com/51299121/72673511-7f1fe400-3aa6-11ea-941d-909f7f622aa1.jpg)

**Comment by Kukulkan2019** [comment] 2020-01-19 02:30
![Screenshot_20200119_100754_org schabi newpipe](https://user-images.githubusercontent.com/51299121/72673526-b7bfbd80-3aa6-11ea-9a2f-543bde82c215.jpg)
![Uploading Screenshot_20200119_100718_org.schabi.newpipe.jpg…]()
![Uploading Screenshot_20200119_100700_org.schabi.newpipe.jpg…]()

**Comment by gkeegan** [comment] 2020-01-19 02:35
The issue you are describing here is not the same as what OP is describing.

**Comment by Kukulkan2019** [comment] 2020-01-19 02:40
I accidentally closed the other issue and there is no apparent way to
reopen, the issue is the same, audio & video are not downloading whereas
previously they were, all settings are the same, all other device systems
functioning normally...



Google gaming Archmage, legendary hero, great hero, EK League...

**Comment by gkeegan** [comment] 2020-01-19 02:43
You should be able to reopen, at least on the GitHub website.

The issue is not the same. This user isn't having access to download any videos at any resolution. 

The video you are trying to download just can't be accessed by NewPipe in 480p. You should be able to download at 720p. If you can, that shows there is separate issue.

**Comment by Kukulkan2019** [comment] 2020-01-19 02:47
The 720p worked... Gmail me a screenshot of what you're supposed to press
to reopen, I can't see it... Going through the Github is like a bewildering
maze, I'm just a user, not a computer programmer...




Google gaming Archmage, legendary hero, great hero, EK League...

**Comment by gkeegan** [comment] 2020-01-19 02:55
You should just see a button to reopen the issue. Someone will probably reopen it for you, since this is something that should probably get fixed.

**Comment by Kukulkan2019** [comment] 2020-01-19 03:02
Okay I'll check on it and keep reevaluating the situation on the
audio/video downloads later tonight, another thing that's been happening
for some time is a 'select download file' or some such term keeps promting
at the bottom of the screen in a small box even when I'm in other apps and
even though the file download folder has already been selected...




Google gaming Archmage, legendary hero, great hero, EK League...

**Comment by jhorner6511** [comment] 2020-01-25 19:42
Hello Everyone. I am neither a spokesperson nor a representative of SkyTube or NewPipe, however, I am here to inform you all that the reason why both apps are not working has nothing to do with the apps themselves. Unfortunately, YouTube/Google has updated their policies recently, along with their algorithms, and is now preventing such apps from scraping their videos. YouTube now requires that any app that scrapes its website for content, like SkyTube or NewPipe, they must now enter a reCAPTCHA to verify it's a human being that is scraping the content.

All respective developers of both apps are aware of the issue and are in the process of figuring out a workaround to Google's new algorithm. Please pay attention for any new updates and/or comments from the developers in the near future. On their behalf, we apologize for any inconvenience this has caused you.

**Comment by gkeegan** [comment] 2020-01-25 19:49
Yes we know that YouTube is changing their stuff. NewPipe works fine after updating.

**Comment by Kukulkan2019** [comment] 2020-01-25 20:51
That's what I thought to begin with, it is the Google death star entity, I
got the new update, but haven't tried it yet... I bid you the best of
luck...


Brennan




Google gaming Archmage, legendary hero, great hero, EK League...

**Comment by Kukulkan2019** [comment] 2020-01-26 14:13
Error reports across the board on everything even after last update... ♞
![Screenshot_20200126_221033_org schabi newpipe](https://user-images.githubusercontent.com/51299121/73136467-f6e2a580-4088-11ea-96a4-1843858bebbe.jpg)
![Screenshot_20200126_221104_org fdroid fdroid](https://user-images.githubusercontent.com/51299121/73136469-f77b3c00-4088-11ea-937a-d88ebf811f34.jpg)

**Comment by justanidea** [comment] 2020-01-26 14:26
Please make sure to write in the right thread next time.
Anyways, i would advise you to export your data, uninstall this version of newpipe that you got on fdroid, and then download this version from the official website: https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.18.2
Its because fdroid hasnt released the new version yet,  it takes quite longer :) Then you will can load your data again and enjoy the app without the crash anymore

**Comment by Kukulkan2019** [comment] 2020-01-26 14:30
I thought I did write in the thread, must've missed it, I'm old now...
Thanks for the info, but why is this happening? Why is Google preventing
open source access, this is like the third time in the past several
months...


Brennan




Google gaming Archmage, legendary hero, great hero, EK League...

**Comment by justanidea** [comment] 2020-01-26 14:42
I dont know if their main goal was to disturb a minor community watching youtube from an open source app, anyways, please, make sure to delete your messages when your problem will be fixed, not to overcrowd this thread :)

**Comment by Kukulkan2019** [comment] 2020-01-26 14:46
Hi,

I'll delete them right now, I'd rather not have to make threads to begin
with, I'd rather be able to have direct contact with a customer service,
I'd rather not have to have any technical problems with these things at
all...



Brennan





Google gaming Archmage, legendary hero, great hero, EK League...

**Comment by Younes-L** [comment] 2020-01-26 19:06
> Unfortunately, YouTube/Google has updated their policies recently, along with their algorithms, and is now preventing such apps from scraping their videos. YouTube now requires that any app that scrapes its website for content, like SkyTube or NewPipe, they must now enter a reCAPTCHA to verify it's a human being that is scraping the content.

Is this the reason why sharing/opening a yt video link newpipe and selecting "download" no longer works, while "show info" then downloading from the newpipe UI still works ?

**Comment by jhorner6511** [comment] 2020-01-26 19:11
1. Uninstall NewPipe
2. Go to: https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.18.2

3. Click on "Assets"
4. Download "NewPipe 18.2 apk
Install on your phone and enjoy.

**Comment by Kukulkan2019** [comment] 2020-02-11 06:41
Chrome browser is not opening the new update that came out today, can you
send me the link?


Brennan Mulrennan on LinkedIn, Gravatar & WordPress.com...♞

**Comment by jhorner6511** [comment] 2020-02-11 06:50
1. Uninstall NewPipe
> 2. Go to: https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.18.2
>
> 3. Click on "Assets"
> 4. Download "NewPipe 18.2 apk
> Install on your phone and enjoy.

**Comment by Kukulkan2019** [comment] 2020-02-28 11:55
Removing the three dot quick menu like to go back to history is not an
improvement...

Brennan Mulrennan on LinkedIn, Gravatar & WordPress.com...♞

**Comment by opusforlife2** [comment] 2020-08-12 22:03
Drop a comment if this is still an issue.

**Closed by opusforlife2** 2020-08-12 22:03 UTC
Labels: device/software specific, downloader, more info needed
