### ISSUE TITLE
Continue downloading an incomplete NewPipe video if app stopped for some reason

### ISSUE THREAD

**Issue by Pass1Vlax** [TeamNewPipe/NewPipe#7365] opened 2021-11-06 12:54 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
I'd appreciate it if you could make it possible to continue a download after (for example) an app crash. I was downloading a 4gb video from YouTube, the download randomly disappeared (turned phone to landscape-never happened again)

#### Why do you want this feature?
It was in 98% and now I'll have to download it again. This is an example but I needed this few times. It would save me a lot of time

**Comment by mhmdanas** [comment] 2021-11-06 14:33
Duplicate of #7059.

**Closed by mhmdanas** 2021-11-06 14:33 UTC
Labels: enhancement, downloader
