### ISSUE TITLE
[REQUEST] When searching, be able to sort by "Last Hour, Today, This week..."

### ISSUE THREAD

**Issue by espinosaluis** [TeamNewPipe/NewPipe#862] opened 2017-11-19 18:44 UTC
This is very useful for some videos that gets uploaded daily from TV shows and you want to get the latest.

**Comment by TobiGr** [comment] 2017-11-19 18:46
Duplicate of #110.

**Comment by espinosaluis** [comment] 2017-11-19 18:52
Sorry about that.

**Comment by johnjacobkenny** [comment] 2017-11-21 13:13
@espinosaluis Please close this issue if it is a duplicate 😄

**Closed** 2017-11-21 13:15 UTC
