### ISSUE TITLE
Peertube videos stop playing when exiting out of app.

### ISSUE THREAD

**Issue by SanjayVS1** [TeamNewPipe/NewPipe#6129] opened 2021-04-21 07:26 UTC
### Checklist

- [x] I am using the latest version - 0.21.1
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a video on any Peertube instance
2. Exit out of the app
3. Reopen app to find video unplayable

### Actual behaviour
Video stops playing when you exit the app and after reopening the app, it displays message "Unable to load stream".

### Expected behavior
Video to play in background and to continue playing in video player upon reopening the app.

### Screenshots/Screen recordings
![Screenshot_20210421-125121_NewPipe](https://user-images.githubusercontent.com/55355520/115513253-79fca680-a2a0-11eb-83c9-abffc2820d68.jpg)

### Device info

 - Android version/Custom ROM version: 10
 - Device model: Samsung A30s

**Comment by mhmdanas** [comment] 2021-04-21 10:02
Duplicate of #5097.

**Closed by mhmdanas** 2021-04-21 10:02 UTC
Labels: bug
