### ISSUE TITLE
Media control bugs

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#3149] opened 2020-02-27 16:10 UTC
Background player:
- Doesn't show track/channel name

Popup player:
- Doesn't provide album art

Newpipe's own media control in notification drawer is not affected by this.

**Comment by helght** [comment] 2020-02-27 16:23
![Screenshot_20200228-000258_Media and devices](https://user-images.githubusercontent.com/57073591/75463170-7a4c2b00-5996-11ea-9eab-9bfcd7df59bd.jpg)
![Screenshot_20200228-000340_Media and devices](https://user-images.githubusercontent.com/57073591/75463196-833cfc80-5996-11ea-91fe-b12e991b0055.jpg)

Some screenshots make it more clear

**Comment by helght** [comment] 2020-02-27 16:28
I see duplicates for this issue, but they don't mention different behavior of bg and popup players

**Comment by gkeegan** [comment] 2020-02-28 01:05
Phone name and Android version?

**Comment by cool-student** [comment] 2020-02-28 09:35
the issue is that our current notifications don't have a mediaSession / playback state attached to them and also we don't correctly set the metadata for the album art.

@helght I'm aware of this issue and this will be fixed as part of my notification improvements, I do need a few more days though so I hope you can be a bit patient.

**Closed** 2020-09-27 08:43 UTC
Labels: GUI, bug
