### ISSUE TITLE
Full screen video watching interface locking feature like kids lock

### ISSUE THREAD

**Issue by rijaslive** [TeamNewPipe/NewPipe#5768] opened 2021-03-06 06:30 UTC
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
*I think it would be nice if you add feature to lock the video watching interface (in Full screen) like in MX player. which help us protect against accedental clicking buttons, switching videos or activating gestures (volume control, brightness control)

#### Is your feature request related to a problem? 
I want to play some videos for my kid and handover my phone to him. He always holding the phone by touching the video watching interface. So it will activate the brightness, volume control or other gestures. So by providing a way to locking the interface will solve this problem.

#### Additional context
*Here is the screenshot of this feature from mxplayer*
![IMG_20210306_115800](https://user-images.githubusercontent.com/5830543/110197704-65d92300-7e73-11eb-8c60-281f468c4088.jpg)

#### How will you/everyone benefit from this feature?
* This feature will help us watching videos without any disturbance, we can handover the phones to kids for watching videos without any fear of touching new pipe buttons or enabling any gestures like volume control or brightness.*

**Comment by develop1st** [comment] 2021-03-09 07:28
This is being resolved in issue #5740

**Comment by SameenAhnaf** [comment] 2021-03-14 09:26
I think always-on button in #5821 will solve the issue. The video interface is already way too overcrowded. So, the extra options should be kept under this button. I requested for the "Lock" feature under this button.

**Comment by opusforlife2** [comment] 2021-03-19 18:57
Duplicate of #5740.

**Closed** 2021-03-19 18:57 UTC
Labels: enhancement, player
