### ISSUE TITLE
Some simplified Chinese translations in app are not consistent with source code

### ISSUE THREAD

**Issue by Geeyun-JY3** [TeamNewPipe/NewPipe#6469] opened 2021-06-10 15:28 UTC
### Checklist

- [x] I am using the latest version - 0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

e.g. Setting > Video and audio > Behavior
[`Fast-forward/-rewind seek duration`](https://hosted.weblate.org/translate/newpipe/strings/zh_Hans/?checksum=b9fddfc234226b06) is still translated into `快进 / 快退的单位时间`, not the lastest `快进 / 快退的寻址定位时间间隔`

### Actual behaviour

Some simplified Chinese translations in app are not consistent with https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-b%2Bzh%2BHANS%2BCN/strings.xml
Although the https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-b%2Bzh%2BHANS%2BCN/strings.xml is consistent with the translations on Weblate, some translations in app are still not updated. 

### Expected behavior

Translations are consistent with https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-b%2Bzh%2BHANS%2BCN/strings.xml

### Screenshots/Screen recordings

Nope

### Device info

 - Android version/Custom ROM version: Android 9 MIUI 10 9.9.3
 - Device model: Mi 8

**Comment by mhmdanas** [comment] 2021-06-15 10:42
Please try the APK from [the latest run](https://github.com/TeamNewPipe/NewPipe/actions/runs/931128456) (it's at the bottom); can you reproduce the issue there?

This is odd, as I checked and found that particular translation to be in `master`. Was the release APK built from an older commit perhaps?

**Comment by Geeyun-JY3** [comment] 2021-06-15 11:33
> Please try the APK from [the latest run](https://github.com/TeamNewPipe/NewPipe/actions/runs/931128456) (it's at the bottom); can you reproduce the issue there?

Tested. Still can reproduce.

**Comment by Geeyun-JY3** [comment] 2021-10-19 03:25
Oh I find the reason. The Simplified Chinese translation of NewPipe is consisten with https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-zh-rCN/strings.xml. But the latest translation would only push to https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-b%2Bzh%2BHANS%2BCN/strings.xml. Weblate also has a `Duplicated translation.` alert in Strings component for this.
![image](https://user-images.githubusercontent.com/49396421/137838410-62acc231-40f2-4a2d-8682-330edbe2105d.png)

Maybe the values-zh-rCN file should be deleted.

**Comment by Geeyun-JY3** [comment] 2022-03-29 02:51
Related: https://github.com/WeblateOrg/weblate/issues/7312

**Comment by Geeyun-JY3** [comment] 2022-06-24 17:35
Defacto duplicate of #2819. But #2819 is defacto not fixed yet.

**Comment by mhmdanas** [comment] 2022-07-24 18:49
_Should_ have been fixed by https://github.com/TeamNewPipe/NewPipe/pull/8549. Please leave a comment if the issue is still present (note that the fix hasn't landed in any release yet).

**Closed by mhmdanas** 2022-07-24 18:49 UTC
Labels: bug, localisation / translation
