### ISSUE TITLE
[Feature] Option to trim part of video for downloading

### ISSUE THREAD

**Issue by manikantag** [TeamNewPipe/NewPipe#3022] opened 2020-01-28 06:33 UTC
Thanks for the excellent work :)

Can you please consider adding support for video trimming (1080P/4K) (ex: https://ytcutter.com/) with start time (incl milli seconds) and end time. Because, most of the times I want a video for part of the content. Thanks.

**Comment by Stypox** [comment] 2020-01-28 06:44
Duplicate of #2800

**Closed** 2020-01-28 06:44 UTC
