### ISSUE TITLE
Required feature for music download program.

### ISSUE THREAD

**Issue by MACtr** [TeamNewPipe/NewPipe#1842] opened 2018-10-24 16:00 UTC
When downloading audio files with Newpipe, you should download the album cover photo and sound at 144p and 240p resolution.

**Comment by lionirdeadman** [comment] 2018-10-24 16:55
You should rename the title to "Thumbnail with audio downloads" or something along those lines, your title at the moment really doesn't say anything.

**Comment by Stypox** [comment] 2019-08-27 09:21
Duplicate of #1470

**Closed by Stypox** 2019-08-27 09:21 UTC
