### ISSUE TITLE
When an error occurs during downloads, try to resume automatically

### ISSUE THREAD

**Issue by Pass1Vlax** [TeamNewPipe/NewPipe#6754] opened 2021-07-24 13:51 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Please add automatic restarts on errors while downloading over a network with low bandwidth
![IMG_20210724_164437.jpg](https://user-images.githubusercontent.com/69008910/126870352-2ca90b37-0e30-4712-868b-762f7d7d3f77.jpg)

Optionally, also describe alternatives you've considered.
Example: *Z is also a good alternative. Not as good as Y, but at least...* or *I considered Z, but that didn't turn out to be a good idea because...* -->

#### Is your feature request related to a problem? Please describe it
I'm not sure if it's because of YouTube's servers (I haven't tried it on other platforms since YouTube is the only platform that I use in the app that downloads large files), but if I'm downloading a file over a slow network (less than half a megabyte per second), I regularly receive an error message, that pauses the download and I have to resume it manually

#### Additional context
 This is a screenshot of the error and a speedster of the network that is slow and shows the errors
![IMG_20210724_164437.jpg](https://user-images.githubusercontent.com/69008910/126870466-f2d0ef27-aa5e-4e49-86b0-f57740cba463.jpg)
![IMG_20210724_165015.jpg](https://user-images.githubusercontent.com/69008910/126870496-0e349025-3225-4ccf-8112-72770cfe2345.jpg)

#### How will you/everyone benefit from this feature?
This feature will help users to complete their downloads without the stress that they will be interrupted by an error

**Comment by mhmdanas** [comment] 2021-07-25 16:59
I think this is a duplicate of #4514. If you disagree, feel free to make a comment.

**Closed by mhmdanas** 2021-07-25 16:59 UTC
Labels: enhancement

**Comment by Pass1Vlax** [comment] 2021-07-25 17:41
> I think this is a duplicate of #4514. If you disagree, feel free to make a comment.

The reports are similar, I think that my report is focused on the fact that it also happens in slow bandwidth, not only when a long period passes

**Comment by mhmdanas** [comment] 2021-07-25 18:23
I understand that it is a different case, but the feature request itself is the same. Feel free to post your situation in that issue.
