### ISSUE TITLE
Access timestamps not included in chapters with the chapter button on interface

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#5694] opened 2021-02-24 06:23 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Sometimes, timestamps are not included in chapters as they don't start from 0:00. Still, accessing timestamps might be important for many users.

I know, it may cause a conflict. To avoid such situation, only a sentence could be shown. Anything after full stop, comma, enter, question and exclamation mark should be avoided. Only, first sentence should clear most of the confusion.

An option in the settings could be added to keep this feature optional.

#### Additional context

This process will be able to access timestamps regardless of being included into chapters or not.

#### How will you/everyone benefit from this feature?

Accessing any type of timestamp of the description will be much easier.

**Comment by TiA4f8R** [comment] 2021-03-16 18:35
Closing as a duplicate of #5695.

**Comment by SameenAhnaf** [comment] 2021-03-16 18:49
@TiA4f8R Bro, they are actually not the same issue. Read both of them carefully. #5695 asks to solve a bug. Any timestamp from the description should be able to get accessed. Users may want to access timestamps while scrolling the description. Any timestamp should be enable us to access them whether they are from description or comments.

This issue asks to include those timestamps in the chapter icon which is a completely new feature. It didn't ask to disable the ability to access timestamps from description and replace it here. Rather, include the same ability here as well. Please look before you leap.

**Closed** 2021-04-08 23:53 UTC
Labels: enhancement
