### ISSUE TITLE
I have a distorted mp4 video with the "new player"

### ISSUE THREAD

**Issue by quelbs** [TeamNewPipe/NewPipe#2075] opened 2019-01-29 21:26 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

In 0.15 the old player was removed, but on my Android TV the new player produces a distorted image for mp4 Streams.

Picture taken from the TV:
![screen picture tv](https://user-images.githubusercontent.com/570222/51941255-69885900-2414-11e9-9a69-d9a6bb66897c.jpg)
Screenshot on the phone
![screenshot phone](https://user-images.githubusercontent.com/570222/51941256-69885900-2414-11e9-9bff-7792cfa4c915.jpg)

example video: https://youtu.be/zBr9YiSwdzM

**Comment by theScrabi** [comment] 2019-01-31 15:21
This is mostlikely an issue of the android internal player, i fear we cant do much.

**Comment by quelbs** [comment] 2019-01-31 20:51
Thank you for your reply, although sad to hear. Is there another (minimal) app using the internal player I could test the problem with?

**Comment by quelbs** [comment] 2019-02-01 06:10
SkyTube works fine. If it also uses the internal player, there must be a difference between SkyTube and NewPipe. But I did not find an option to select the video type, thus it maybe uses webm by default and not the problematic mp4 
![screenpicturetv-skytube](https://user-images.githubusercontent.com/570222/52105272-6052e400-25ee-11e9-8345-19fe191b2f17.jpg)

At least I figured out I can use NewPipe without problems when setting WebM as prefered video codec.

**Comment by theScrabi** [comment] 2019-02-01 07:42
We use exoplayer, but it is build based on the iternal player. However maybe there is something wrong on how exoplayer parametrize playback.

**Comment by quelbs** [comment] 2019-02-01 07:57
First of all I did not yet thank you for the app! It is great and I love using it.

When testing around I figured out the TV setting is a bit weird. It has a native 4k resolution, but Android apps are rendered in a 1k resolution. Videos can be played in 4k (tested with VLC). When I use a 4k webm stream in NewPipe only some frames are displayed (they are displayed correct, but there are a lot of frames dropped). Videos with mp4 codec show the above problem regardless of the resolution selected.

**Comment by mozbugbox** [comment] 2019-02-08 07:48
It could be a problem with the hardware video decoder. It'd be better to have an option which let a user to select the software decoder over the hardware decoder.

VLC has this setting. 

Ref: https://github.com/google/ExoPlayer/issues/4757

**Comment by quelbs** [comment] 2019-02-08 07:51
I did a download of the mp4 video and checked with VLC and hardware decoder only set and the video displays fine.

**Comment by mozbugbox** [comment] 2019-02-08 07:53
For exoplayer:
https://github.com/google/ExoPlayer/issues/3039

**Comment by Stypox** [comment] 2020-09-30 13:53
Closing as outdated. If the issue is still present feel free to reopen.

**Comment by quelbs** [comment] 2020-09-30 15:00
The issue is still present on Android TV with Android 5 on it. As Workaround I use VLC as external player to show the videos. VLC displays the mp4 video without problems.

**Comment by Stypox** [comment] 2020-09-30 15:22
Does the apk provided in Release 0.20.0 #4332 fix anything by chance?

**Comment by quelbs** [comment] 2020-09-30 17:43
I just tested with 0.20.0 rc4 and it has a distorted video in the overview as well as in full screen. Opening in external player still works fine and the preview image is also displayed fine. Only displaying video in NewPipe did not work as expected.

**Comment by quelbs** [comment] 2020-09-30 19:43
How could I assist with more info? Is there anything I could test or any log that might help?

**Comment by opusforlife2** [comment] 2020-10-10 16:57
@quelbs This is only MP4 and not WebM? Also, could you update your OP to say 0.20.0 now?

**Comment by qoheniac** [comment] 2020-11-03 21:51
I have the same issue with NewPipe 0.20.2 on Android TV. WebM works without problems.

**Closed** 2022-04-23 00:11 UTC
Labels: bug, player, device/software specific, waiting-for-author
