### ISSUE TITLE
reCaptcha on loading

### ISSUE THREAD

**Issue by droidaholic** [TeamNewPipe/NewPipe#8187] opened 2022-04-12 19:29 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Open Newpipe
2. ReCAPTCHA challenge failed appears 
<img alt="Screenshot_20220412-152413_NewPipe" src="https://user-images.githubusercontent.com/103533051/163038595-c5578484-c627-4da6-b061-aff473e1be90.jpg" height=600 />
3. Clicking Retry presents the following:
<img alt="Screenshot_20220412-152425_NewPipe" src="https://user-images.githubusercontent.com/103533051/163038604-3f018f85-465e-4385-b312-281494a423bf.jpg" height=600 />
4. Behavior occurs in playlists/subbed channels as well.

### Expected behavior

Should load the Trending page on startup.

### Affected Android/Custom ROM version

Android 10

### Affected device model

Samsung Galaxy S9

**Comment by kmodexc** [comment] 2022-04-12 19:31
Duplicate of #8183

**Closed** 2022-04-12 19:35 UTC
Labels: bug
