### ISSUE TITLE
[unified player] stop current video from preloading when trying to play another one

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4232] opened 2020-09-04 14:13 UTC
#### Describe the feature you want

i think it would be nice to stop playing the actual video when choosing to play another not after it's fully loaded this way we won't be looking at the comments section of a video and another is being played on the background.

#### Is your feature request related to a problem? Please describe it

i don't know maybe?

#### Additional context

nothing..

#### How will you/everyone benefit from this feature?

every other app does this so newpipe should as well? 
well i guess it's helpful because it's what everyone expects to happen !

**Comment by opusforlife2** [comment] 2020-09-04 14:27
Why does it matter? The current way, you get less of a gap where you're left staring at the screen waiting for things to load. You get to enjoy the video until the new one is ready.

**Comment by panacist** [comment] 2020-09-04 14:55
@opusforlife2 it does matter because sometimes you don't enjoy the current playing video that's why you start playing another ?

**Comment by panacist** [comment] 2020-09-04 15:07
@opusforlife2 yeah that's an option but it doesn't solve the issue permenantly (the youtube app does solve it tho)

**Comment by opusforlife2** [comment] 2020-09-04 15:30
The Youtube app uses proprietary code to _directly_ access the Google servers and fetch videos. So they can do this super fast. Newpipe has to first obtain data from the website and _then_ fetch the video details, which means we can never be as fast as Youtube at fetching videos. So there's no point in comparing the two.

**Comment by panacist** [comment] 2020-09-04 15:37
@opusforlife2 i know that and i think you missing the point! what am saying is not to fetch videos as fast as youtube. am saying have some mechanism to stop the ongoing video whenever another video's tumbnail is pressed

**Comment by opusforlife2** [comment] 2020-09-04 15:40
My opinion is:
> Pause it before playing another. 🤭

So let's wait until more people weigh in on this.

**Comment by vkay94** [comment] 2020-09-04 19:34
What about an option (SwitchPreference) in preferences under "video and audio" regarding this behavior?

**Comment by avently** [comment] 2020-09-05 13:34
@opusforlife2 I agree with all your comments here. Actually I didn't pause a video just because of the silent gap between streams. Without pause it feels like a kind of instant playback

**Comment by opusforlife2** [comment] 2020-09-05 13:39
@avently Yep. I consider it a feature, not a bug.

**Comment by panacist** [comment] 2020-09-05 15:52
@avently @opusforlife2 i can't agree enough but i'm raising this issue because sometimes i have terrible internet (or for those using tor or vpn) considering the amount of time the app takes to fetsh the video, Retrieve the comments and recommended videos there's a huge amount of delay here ranging from a few seconds to minutes !
there's no need for me to keep playing the other video (which takes a considarable amount of memory and cache). that's all what i'm trying to say and what i am familiar with on other apps but if you feel like a production oriented philosophy is good for you go for it guys.

**Comment by avently** [comment] 2020-09-05 16:13
I don't think you'll get better results in terms of delay before next video if you just stop playback instead of loading in parallel. You can try it yourself and to compare with current behavior. Just stop playback via notification and than choose another video, compare the delay. Or pause and select another video

**Comment by opusforlife2** [comment] 2020-09-05 16:24
I think the question here, @avently, is that does the current video stop _loading_ when you open a new one? @panacist is concerned about the data usage. If the app keeps playing the already buffered video, but stops downloading more of it when you open another one, he should be fine.

Am I correct, @panacist?

**Comment by panacist** [comment] 2020-09-05 16:33
@opusforlife2 yess!! thtat's exactly what am trying to say keep loading the actuall video when not needed takes a nontrivial amount of data memory and cache for those who have bad internet connection and old phones.

**Comment by avently** [comment] 2020-09-05 16:34
@opusforlife2 the player always preloads some parts of a video and at some point of timeline IR doesn't load anything but at some point it loads next part.
The answer is no, the player don't stop prealoading.

**Comment by opusforlife2** [comment] 2020-09-05 17:15
Hmmm. Is it possible to programmatically stop preloading when another video is opened?

**Comment by vkay94** [comment] 2020-09-05 18:45
@opusforlife2 in fact it is (I tried it myself some hours ago) but I doubt it is good practice.
If you add `playerService.stop(false)` to the beginning of `VideoDetailFragment#selectAndLoadVideo` ([link](https://github.com/TeamNewPipe/NewPipe/blob/0fd1e2fcd9a944ac35eabe4c904fdc95acaecd17/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L951)), the video/service stops but the latest frame remains until the new video has been enqueued/starts to buffer.

**Comment by opusforlife2** [comment] 2020-09-05 19:04
From [this](https://github.com/TeamNewPipe/NewPipe/blob/0fd1e2fcd9a944ac35eabe4c904fdc95acaecd17/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L1194) line it looks like `playerService.stop` stops the actual player, not just the preloading/buffering part.

**Comment by avently** [comment] 2020-09-06 03:16
@vkay94 there is `hideMainPlayer()` for stopping without issues. But it still not allowing to continue playing with just disabled preloading, i'm not sure how to do it in exoplayer

**Comment by avently** [comment] 2020-09-06 04:07
Try this apk. Should work fine. The toast will tell you when preload is enabled or disabled. You can also check with any network monitor.

[preload.zip](https://github.com/TeamNewPipe/NewPipe/files/5179062/preload.zip)

**Comment by avently** [comment] 2020-09-07 16:46
PR #4246

**Comment by opusforlife2** [comment] 2020-09-07 17:06
Didn't you test the apk, @panacist?

**Comment by panacist** [comment] 2020-09-08 17:08
@avently thank you for working on that really appriciate it !
@opusforlife2 yeah it does work as expected (although i still think stopping the actual player is the best thing to do but we will see other users impressions once the new version is released :) )

**Comment by opusforlife2** [comment] 2020-09-08 17:10
The issue will be closed automatically when the PR is merged.

**Closed** 2020-09-25 19:22 UTC
Labels: enhancement
