### ISSUE TITLE
app-debug intermittent buffering stuttering issue

### ISSUE THREAD

**Issue by krtfwd** [TeamNewPipe/NewPipe#8217] opened 2022-04-15 09:52 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

app-debug.zip from the "fix"

### Steps to reproduce the bug

Play a video
Video starts playing 
Video freezes after 15-20 seconds and hangs for 5-8 seconds while buffering

### Expected behavior

Video playing and buffering as normal

### Actual behavior

Videos freezing every 15 seconds for 5-8 seconds waiting to buffer ( or just hangs for some other reason I can't think of)
also it seems like it takes a lot longer for videos to start playing as well

### Affected Android/Custom ROM version

Android 11RKQ1.20086.002 / Miui eu 12.5.5

### Affected device model

poco x3

### Additional information

Tried official youtube app and  nightly mobile on both lte and wifi (multiple resolutions) and also my laptop it is not my connection all combinations work fine except newpipe
Am I just incredibly unlucky with videos I play or is this an issue ? looks like a newpipe (or a youtube ?) issue from my end I can't seem to get a single video to buffer correctly and no other program/platform does it

**Comment by litetex** [comment] 2022-04-15 15:35
1. Is this still a problem in the latest release? (debug-apk are usually a lot slower than optimized production ones)
2. Might be a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7630

**Comment by Stypox** [comment] 2022-04-15 16:28
See https://github.com/TeamNewPipe/NewPipeExtractor/pull/832

**Closed by Stypox** 2022-04-15 16:28 UTC
Labels: bug, waiting-for-author
