### ISSUE TITLE
(Bug) Could not parse JSON response

### ISSUE THREAD

**Issue by allendema** [TeamNewPipe/NewPipe#3755] opened 2020-06-06 19:23 UTC
### Version
 v.0.19.5 

### Steps to reproduce the bug
 
1. From any other service, simply change to Soundcloud.

### Expected behavior

Charts should normally load.

### Actual behaviour

Blank, no charts are opened.
This happens even if i try to search anything.

## Exception
* __User Action:__ requested kiosk
* __Request:__ https://soundcloud.com/charts/new
* __Content Language:__ DE
* __Service:__ SoundCloud
* __Version:__ 0.19.5
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.getStreamsFromApi(SoundcloudParsingHelper.java:239)
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudChartsExtractor.computeNextPageAndStreams(SoundcloudChartsExtractor.java:68)
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudChartsExtractor.getInitialPage(SoundcloudChartsExtractor.java:83)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:72)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:58)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:184)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$3nu_IUHVaX-6ert-LLLuUGJnfDU.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonParser.currentValue(Unknown Source:31)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:4)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.getStreamsFromApi(SoundcloudParsingHelper.java:237)
	... 31 more

```
</p></details>
<hr>

See log here, too [https://haste.tchncs.de/arojiqixeq.avrasm](https://haste.tchncs.de/arojiqixeq.avrasm)

**Comment by B0pol** [comment] 2020-06-06 19:42
Duplicate of #2915

**Closed by B0pol** 2020-06-06 19:42 UTC
Labels: bug

**Comment by allendema** [comment] 2020-06-06 19:50
Didn't see that, waiting for a fix :)
