### ISSUE TITLE
Request | Real randomizer

### ISSUE THREAD

**Issue by AlexQuiniou** [TeamNewPipe/NewPipe#2828] opened 2019-11-27 09:47 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi
It's a request. I have a big playlist on YouTube (+1800 videos)
https://www.youtube.com/playlist?list=PLgfrzIaFR9HfrMfEHHA75y6ieaeyBxuTu

The random option always play the same first tracks. I always need to scroll down to hear news songs.
Can you make it to randomize stronger ?

**Comment by Stypox** [comment] 2019-12-03 15:07
Duplicate of #875

**Closed by Stypox** 2019-12-03 15:07 UTC
