### ISSUE TITLE
Crash on download

### ISSUE THREAD

**Issue by Beep6581** [TeamNewPipe/NewPipe#6738] opened 2021-07-23 13:07 UTC
1. Open https://www.youtube.com/watch?v=YXiLep5miK8
2. Click Download > crash.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ SE
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4412)
	at android.app.ActivityThread.access$1800(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4400)
	... 8 more

```
</details>
<hr>

**Comment by bew** [comment] 2021-07-23 14:09
This is a duplicate of #6687

**Closed** 2021-07-23 14:54 UTC
