### ISSUE TITLE
Feature Request — Invidious Privacy Redirect

### ISSUE THREAD

**Issue by fufik** [TeamNewPipe/NewPipe#7431] opened 2021-11-22 06:56 UTC
In short, I'd like to share videos from YT to my friends without any trackers or weighty JavaScript. I'd be happy to have a small feature implemented: to automatically replace domain name in URL from "Share" button with that of user's choice or from list of trusted Invidious instances. The end result would be that I could share my videos and keep my friends safe. So far NewPipe is the best app for YT and I admire your work. I doubt it would be any problem for you to implement this small feature, but for me it would be a major enhancement. 

Invidious: https://github.com/iv-org/invidious

**Comment by SameenAhnaf** [comment] 2021-11-22 07:26
Duplicate of #2351.

**Comment by litetex** [comment] 2021-11-22 19:13
Duplicate of #2351

**Closed by litetex** 2021-11-22 19:13 UTC
Labels: enhancement
