### ISSUE TITLE
Downloading Subtitles

### ISSUE THREAD

**Issue by Raif1** [TeamNewPipe/NewPipe#8024] opened 2022-03-13 16:17 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

My feature suggests an option to download with synced video subtitles from vids which have captions by the creator and an option to download auto generated subtitles or captions **_at the same time_**. And which will create a folder with the video and the captions.

### Why do you want this feature?

This will let us play vids with captions offline

**Comment by SameenAhnaf** [comment] 2022-03-13 16:25
Are you willing to download captions within the video? Then, this is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2885

**Comment by litetex** [comment] 2022-03-13 21:25
Duplicate of #4216

**Closed by litetex** 2022-03-13 21:25 UTC
Labels: enhancement
