### ISSUE TITLE
Filtering by Content dates

### ISSUE THREAD

**Issue by Daviwalle** [TeamNewPipe/NewPipe#8524] opened 2022-06-19 13:39 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add from the configuration an option to filter all content by date to be displayed in the application.

For example: I go to the settings and set it to only show me content from 2005 to 2019. Then, all the content that I get, either in the subscriptions, search bar, and all the application, will be from 2005 to 2019.

### Why do you want this feature?

In my opinion, the current YouTube content is horrible. I miss videos from 2012 and 2017, in fact whenever I search for a video, I always make sure it's from those dates. I think a lot of people would appreciate it if you would add in Newpipe a way to go back in time.

**Comment by litetex** [comment] 2022-06-19 14:19
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2251

**Closed by litetex** 2022-06-19 14:19 UTC
Labels: enhancement
