### ISSUE TITLE
Exception could not parse app update json data

### ISSUE THREAD

**Issue by phatloot123** [TeamNewPipe/NewPipe#2417] opened 2019-06-24 04:37 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I got this exception recently:

## Exception
* __User Action:__ something
* __Request:__ could not parse app update JSON data
* __Content Language:__ PH
* __Service:__ none
* __Version:__ 0.16.2
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
org.json.JSONException: Value <html><title>500 of type java.lang.String cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:112)
	at org.json.JSONObject.<init>(JSONObject.java:163)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:108)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:48)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7097)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```
</p></details>
<hr>

**Comment by Stypox** [comment] 2019-06-24 06:08
Duplicate of #2197

**Closed** 2019-06-24 06:09 UTC
Labels: duplicate
