### ISSUE TITLE
download

### ISSUE THREAD

**Issue by 404Help** [TeamNewPipe/NewPipe#5980] opened 2021-04-01 11:19 UTC
is there anyway you could put a download button on playlists to download every video in that playlist. would make this a whole lot easier. Thanks for reading hope to hear back soon

**Comment by SameenAhnaf** [comment] 2021-04-01 12:20
Duplicate of #5482. Please avoid already existing issues.

Also, please fill in the template properly. You are not supposed to remove it.

**Closed** 2021-04-01 13:39 UTC
Labels: enhancement
