### ISSUE TITLE
Jump to specific time via keypad 

### ISSUE THREAD

**Issue by OldGuyInTheClub** [TeamNewPipe/NewPipe#8002] opened 2022-03-08 02:52 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I listen to audiobooks and other long files with NewPipe.  It would be helpful to have a keypad option to enter a time in hours/mins/seconds and have the player jump to that point.  Rationale below.

### Why do you want this feature?

When listening to audiobooks, I often pause NewPipe and come back after many hours.  Sometimes the video will still be up in the player, other times I will resume from history.  Often the video will play for a while and then the spinning circle will come up with no way to resume at the point where it stopped playing.  I note the time of stopping and restart the video.  Getting back to that point with the slider is a little difficult - when I release it, I can be minutes off in either direction.  If there were a popup keypad option to key in the "go to time," it would be easier to resume.

### Additional information

Configuration:
NewPipe 0.22.1 on a Samsung Galaxy S10+, T-Mobile network (USA)
Android 11, Samsung One UI version 3.1

Steps I've taken:
- Searched the Issues page/Feature requests with multiple keyphrases with no similar requests
- Searched the documentation for equivalent functionality

**Comment by happys2333** [comment] 2022-03-11 14:42
I'd like to work on this issue. Can I assign it?

**Comment by opusforlife2** [comment] 2022-03-12 09:28
@happys2333 Please show mockups of how you would go about implementing this. Once we decide on how it should work, only then go ahead with a PR.

**Comment by happys2333** [comment] 2022-03-13 14:00
@opusforlife2 Thanks. I need a week to read the origin code and think about how to design it. I will reply to you about how I will design this feature soon.

**Comment by opusforlife2** [comment] 2022-03-25 19:07
@happys2333 Thanks! Now we should let the team and community discuss these options.

**Comment by opusforlife2** [comment] 2022-03-25 19:12
Another alternative to mention here is what iOS does: change the crudeness/fineness of seeking based on sliding the finger up or down while seeking.

**Comment by happys2333** [comment] 2022-03-30 01:00
Are there any results? I personally prefer the third option, which makes better use of the elements on the screen and is more intuitive.

**Comment by opusforlife2** [comment] 2022-04-01 19:37
Well, seeing as no one has commented with their opinions at all, I'm thinking this is a very niche feature. Based on that, though I really like the third option, I would go with the _first_ option, where the button is out of the way and only accessible to those few who need it. What do you think?

**Comment by OldGuyInTheClub** [comment] 2022-04-02 01:19
OP here: I like all the options but agree that this may be a lot of work for the benefit of a few people.

A friend pointed out that for my case, I could just download the long audiobooks and listen to them on a separate player.  A blindingly obvious solution that never occurred to me!

I also found this thread https://github.com/TeamNewPipe/NewPipe/issues/7606
"Simple UI for Old People" of which I am one.  I find the red dot slider hard to "grab" with my finger.  This has been true on multiple phones.  If there were a way to make the red dot larger, perhaps user configurable, it might be easier to move and drop the slider close to the correct time.  Since the slider only appears when required, it wouldn't otherwise detract from watching the video.

**Comment by happys2333** [comment] 2022-04-02 08:23
Here, I got a better idea. A Chinese app called Bilibili, with a feature that allows users to move forward and backward by dragging the screen left and right, may be a viable solution to our problem.
Here is an example. If I let go, I can reach the progress area, which will allow the user to make further fine-tuning.
![IMG_1280](https://user-images.githubusercontent.com/56923707/161374244-c3bc2229-4549-4a9a-ab51-b1e37eebe258.PNG)

**Comment by opusforlife2** [comment] 2022-04-02 18:32
> I find the red dot slider hard to "grab" with my finger. 

@OldGuyInTheClub If that is your real problem, then this is a duplicate of #6363, and can be closed.

If you still want this feature separately, then we can keep this open.

> move forward and backward by dragging the screen left and right

@happys2333 Please read https://github.com/TeamNewPipe/NewPipe/issues/6363#issuecomment-847923356.

**Comment by OldGuyInTheClub** [comment] 2022-04-02 21:57
We can close it since downloading and watching on a separate app will address the problem without any coding.

If Issue 6363 is implemented at some point, that'll also help general usability.

**Closed** 2022-04-03 06:56 UTC
Labels: enhancement, player

**Comment by opusforlife2** [comment] 2022-04-03 17:19
@happys2333 Would you like to work on #6363 instead? If not, that's also fine.
