### ISSUE TITLE
Feature: Download playlist

### ISSUE THREAD

**Issue by Flashwalker** [TeamNewPipe/NewPipe#3761] opened 2020-06-08 03:41 UTC
It would be nice to see the menu option for download saved playlist. As audio too.  
[]()  
And it would be nice to add Download option to context (long tap) menu for saved playlists and single video.  
[]()  
And it would be nice to add feature for select several videos for downloading.

**Comment by B0pol** [comment] 2020-06-08 18:14
Duplicate of #1058

**Closed by B0pol** 2020-06-08 18:14 UTC
