### ISSUE TITLE
Downloading a playlist in a single press, similar to download individual videos

### ISSUE THREAD

**Issue by alik604** [TeamNewPipe/NewPipe#6487] opened 2021-06-15 00:39 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be nice if you add *downloading a whole playlist in one go*. This is a convenient feature for those of us who transferred music playlists from Spotify/Tidal to Youtube, and want to avoid having a PC as the middle man. 

Optionally, the downloaded playlist could potentially be used as a cache for offline listening in-app.  

#### Is your feature request related to a problem? Please describe it

I'm too lazy to download ~200 songs by hand... and also too lazy to download it as a playlist with `youtube-dl` & plug my phone into my PC.  
> This feature seems like a quick win: 
1.. Add a menu item on the playlist view (under 'settings' and 'open in browser'). 
2.. Download the playlist and place it into a local folder of that name.   *I assume you guys use youtube-dl in the backend*

#### How will you/everyone benefit from this feature?

This feature will help us replace paid streaming services

----------
For donating, which is preferable for you guys, _liberapay_ or _bountysource_?
> I'm thankful for the download feature already available :)

**Comment by mhmdanas** [comment] 2021-06-15 10:24
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5782.

> For donating, which is preferable for you guys, liberapay or bountysource?

Bountysource is great if you want to put a bounty on a specific issue, while Liberapay is for recurring donations.

Thanks!

**Closed by mhmdanas** 2021-06-15 10:24 UTC
Labels: enhancement

**Comment by alik604** [comment] 2021-06-15 14:51
@TiA4f8R hey, in what way did i ignore template instructions?

**Comment by mhmdanas** [comment] 2021-06-15 14:53
They probably meant that it's a duplicate.

@TiA4f8R we should probably be more specific with this usage of the label. I'm creating a "duplicate" label, which I think should be used in cases like this.
