### ISSUE TITLE
Buffer issue on videos with Chapters

### ISSUE THREAD

**Issue by GokulSoman** [TeamNewPipe/NewPipe#6555] opened 2021-06-23 03:06 UTC
The videos with Chapters have frequent buffering problem, unless at very low resolutions (less than 360p). This problem does not seem to exist on the legacy Newpipe app.

**Comment by Thewisem** [comment] 2021-06-25 22:15
Show a link to a video

**Comment by RobertKillick** [comment] 2021-06-25 23:38
I have been having a similar issue with buffering, some of the time it will play normally but often it will buffer every second or so for a moment.

**Comment by TiA4f8R** [comment] 2021-07-04 16:15
It doesn't affect only videos with chapters but all videos (not everytime): see #6510. Closing as a duplicate of this issue.
Also, please follow the template the next time you open an issue.

**Closed by TiA4f8R** 2021-07-04 16:15 UTC
