### ISSUE TITLE
[Youtube] 403 reemerge

### ISSUE THREAD

**Issue by http403** [TeamNewPipe/NewPipe#10352] opened 2023-08-17 03:24 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

~~1. Watch video~~
~~2. App crash approx 1 minute into the video~~
~~1. Open a video~~
~~2. (optional) Full screen~~
~~3. Pause the video at start or middle~~
~~4. Exit to home (but not quit the app)~~
~~5. Do something else (2+ hours)~~
~~6. Go back and resume the video~~

### Expected behavior

Play the video continuously

### Actual behavior

~~About 1 minute into the video after resuming, it will crash with 403.~~

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=WxLzoq-NMpY
* __Content Country:__ GB
* __Content Language:__ en-
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux samsung/r9qzh/r9q:13/TP1A.220624.014/G9900ZHU5EWE3:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung Galaxy S21 5G FE

### Additional information

I know the problem was declared fixed in TeamNewPipe/NewPipeExtractor#1084, but it is still happening. 

This issue might look like #10329 but it is different. That issue is a result of 404, mine is a result of 403, thus I decided to open a new one. 

~~Noted, this bahavior is not consistant, and for the span of 3 days of light use, I only encounter twice. It is hard to reproduce, and not as frequent as in 0.25.1.~~

~~Upon further usage, I sort of find the way to reproduce the crash. However, I have no idea if it's reliable.~~

I didn't apply the workaround in the release note.

**Comment by attilafekete73** [comment] 2023-08-18 19:31
This happens to me too, but it does that every time I try to open a video. It plays for 1 minute, then it crashes.

**Comment by Haitham-7** [comment] 2023-08-18 23:34
Heppens to me too, not only pipe,  but also with Yutube Vanced,  Youtube Revanced, SkyTube, LibreTube.

I think google dod something to block these apps but I am not sure

**Comment by openmoth** [comment] 2023-08-19 17:07
My app is also doing this. It 'crashes', gives me the notif and then sometimes restarts from the point it left off and sometimes doesn't. I will keep getting sporadic error notifs until I quit out of the app, whether it restarts or not.

**Comment by http403** [comment] 2023-08-19 20:22
To all users, please use the thumbs up reaction on the main post to signify you experience the problem unless you have additional information such as, reliably triggering the error, with detailed steps on reproducing it. Thank you.

**Comment by http403** [comment] 2023-08-20 03:26
I updated the steps to reproduce the crash. Though I have no idea how reliable that is.

**Comment by AudricV** [comment] 2023-08-20 10:47
> Do something else (2+ hours)

Then the streaming URLs may have expired (URLs should be only valid for 21540 seconds), and in this case this issue would be a duplicate of #5730. You can still play the video for around 1 minute before getting the error as the player library, ExoPlayer, is configured to have the goal to buffer streams 50 seconds (the default value).

If you can still get sometimes this invalid response code when you start playing a video and after around 1 minute of playback, then it means that YouTube is disabling our last known workaround to use the Android client.

We wouldn't be the only app affected again by this issue, reVanced would be too for instance, but contrary to it, we have the freedom to use almost every YouTube client we want.

**Comment by http403** [comment] 2023-08-20 14:46
@AudricV Thanks for letting me know, and sorry for I didn't search thorough enough.

This proves I didn't find the correct way to reproduce the issue.

@Haitham-7 @openmoth @attilafekete73 and others, as you stated you experienced the issue, could you please share the crash log and possbility step to reproduce? This will help to judge if Google did something new or just a duplicate. Thank you.

**Comment by http403** [comment] 2023-08-24 19:18
@Haitham-7 You are using an old version of NewPipe. Please update to 0.25.2 then report back if you still experiencing the issue. Thank you.

**Comment by bonswouar** [comment] 2023-08-29 14:46
Not sure this is the same problem, forgive me if not, but I'm having an HTTP 429 error (too many requests - with google "exceptional traffic IP" message in the response), and only on some specific videos apparently (`/watch?v=BABiZOeoKw4` for example).
I'm using the latest docker version (just updated, previous one was few days old)

**Comment by Regenhardt** [comment] 2023-09-22 08:19
Here's my error log, although I'm on 0.25.1 and can't update because F-Droid doesn't seem to offer be 0.25.2

```
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=N1bggTnUZHc
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ YouTube
* __Version:__ 0.25.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:359)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

```

**Comment by shaohme** [comment] 2023-10-23 10:22
This occurred for me recently:

* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=redacted
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux Android 14 - 34

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Closed** 2023-10-25 00:11 UTC
Labels: bug, waiting for author, needs triage

**Comment by shaohme** [comment] 2023-10-25 06:48
> I don't see the need to reopen this because the error clearly isn't occurring for everyone like last time, but only intermittently, which is to be expected.

Would it be trivial to make NewPipe catch this error instead, show a generic error, (perhaps retry), instead of "crashing" in the background?

**Comment by squishyu** [comment] 2023-10-30 16:24
> > I don't see the need to reopen this because the error clearly isn't occurring for everyone like last time, but only intermittently, which is to be expected.
> 
> Would it be trivial to make NewPipe catch this error instead, show a generic error, (perhaps retry), instead of "crashing" in the background?

I support a solution like this. I've been getting this error every day for months, whenever my phone switches between WiFi and data (leaving the house)

When listening to a playlist, it just skips to the next song instead of retrying.

**Comment by http403** [comment] 2023-10-31 17:53
> > I don't see the need to reopen this because the error clearly isn't occurring for everyone like last time, but only intermittently, which is to be expected.
> 
> Would it be trivial to make NewPipe catch this error instead, show a generic error, (perhaps retry), instead of "crashing" in the background?

I think this issue will be appropriate to address by opening a new issue.
