### ISSUE TITLE
Make Play Queue an optional tab on the Main Page

### ISSUE THREAD

**Issue by andrasfelfoldi** [TeamNewPipe/NewPipe#5922] opened 2021-03-27 11:42 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I'd like to make the Play Queue screen an optional tab on the Main Page.
Right now, we can only add stuff like Subscriptions, Bookmarked Playlists, etc. to the Main Page in Settings > Content > Content of main page.
The Play Queue screen is not an option.

#### Is your feature request related to a problem? Please describe it

Right now, what I have to do to get to the Play Queue screen is:
1. start playing the music in the background (eg. from the History tab)
2. pull down the Notifications shade
3. tap on the notification to navigate to the Play Queue.

As far as I know, the Play Queue can only be accessed from the notification and even if there is an alternative way to get to that screen, there is no way to add it as a default tab on the Main Page.

#### How will you/everyone benefit from this feature?

Personally, I don't use playlists, so I just play whatever is in the History tab. I think, I'm not alone with that. The History tab however is not suitable to be used as a music player. For playing music, the Play Queue screen is the best, but I can only access it (AFAIK) through the app notification, which is cumbersome. Having it on the Main Page would be convenient.

#### Implementation
When on the Main Page, the Play Queue would display the content of the last Play Queue by default.

I would gladly implement this feature myself if I get a greenlight on it.
I'm not an Android developer myself so I will first go through the Android documentation, then get familiar with the code of this project. Because of this it might take some time for me to implement this feature in my freetime, but since I didn't find a similar feature request (see the first checkbox) I don't think that it's urgent.

**Comment by avently** [comment] 2021-03-27 13:19
I think it's a good idea. How about another one? Since we have mini player it can show a list button which shows (after click) a dialog with the play queue. It can be a dialog or a bottomSheet. More importantly by making this way you'll have easy access to the play queue. If you have a tab on main screen you would need to go back to the main screen which is not always useful, for example, when you see some channels and don't want to lose the link to it

**Comment by TiA4f8R** [comment] 2021-03-27 13:57
Duplicate of #2477 (original issue title edited because feature request was before 0.20.0).

**Closed by TiA4f8R** 2021-03-27 13:57 UTC
Labels: enhancement
