### ISSUE TITLE
release v0.17.1

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#2531] opened 2019-08-17 23:29 UTC
### New
- Thai localization

### Improved
- Add `start playing here` action in long-press menus for playlists again #2518 
- Add switch for SAF / legacy file picker #2521

### Fixed
- Fix disappearing buttons in downloads view when switching apps #2487 
- Fix playback position is stored although watch history is disabled
- Fix reduced performance caused by playback position in list views #2517
- [Extractor] Fix ReCaptchaActivity #2527, TeamNewPipe/NewPipeExtractor#186 
- [Extractor] [YouTube] Fix casual search error when playlists are in results TeamNewPipe/NewPipeExtractor#185

-----

### Build version 0.17.1 RC1:
- [release](https://github.com/TeamNewPipe/NewPipe/files/3512543/NewPipe-v0.17.1_RC1_release.apk.zip)

**Comment by tusch001** [comment] 2019-08-18 01:57
Minor thing - just a suggestion:
First time video download on Android 6.0.1 when no download directory is set and SAF is not activated in settings yet:
The internal file explorer starts with the top folder (/) which could be a problem for new users who don't know about where android stores files.  
I would suggest to open the file explorer with /sdcard or the downloads folder initially. Maybe activate SAF as default?

Just FYI: The internal file explorer only shows /sdcard but /storage/emulated doesn't show the subfolder to pick the internal sd (/storage/emulated/0). Don't know where the difference is to other apps on my phone - they don't have this problem. For users it doesn't matter - I can pick /sdcard.


My first impression is very positive: The video lists are shown very fast compared to 17.0-RC2.

**Comment by shadypt** [comment] 2019-08-18 08:47
Starting from the v0.16.0 (I think) I started getting this error. To reproduce it go to settings -> video and audio, just scroll down and the app crashes. This is still present on the latest version.
Already reported several times via user report.
Thanks for the awesome app.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ PT
* __Service:__ none
* __Version:__ 0.17.0
* __OS:__ Linux Android 8.1.0 - 27
going on settings, audio and video, and scrolling all the way down, the app crashes

<details><summary><b>Crash log</b></summary><p>

```
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4398)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3091)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3049)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2816)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2770)
	at android.support.v7.preference.ListPreference.getSummary(ListPreference.java:178)
	at android.support.v7.preference.Preference.onBindViewHolder(Preference.java:584)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:381)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:45)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
	at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
	at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
	at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:366)
	at android.support.v7.widget.GapWorker.run(GapWorker.java:397)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

```
</p></details>
<hr>

**Comment by theScrabi** [comment] 2019-08-18 09:17
I cant reproduce that error.

**Comment by undeadfox** [comment] 2019-08-18 13:44
> I cant reproduce that error.

"% s" instead of "%s" https://github.com/TeamNewPipe/NewPipe/blob/60f534d7a1ed1fe8323e0c5c86171bc7de0441f2/app/src/main/res/values-pt/strings.xml#L401

**Comment by shadypt** [comment] 2019-08-18 13:53
@theScrabi I can reproduce on another phone, a moto one vision. Here is the log

{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.16.2",
   "os": "Linux motorola\/kane_reteu\/kane_sprout:9\/PSA29.137-17\/6875e:user\/release-keys 9 - 28",
   "time": "2019-08-18 13:49",
   "exceptions": [
      "java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  \n\tat java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4398)\n\tat java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3091)\n\tat java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3049)\n\tat java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2816)\n\tat java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)\n\tat java.util.Formatter.parse(Formatter.java:2557)\n\tat java.util.Formatter.format(Formatter.java:2504)\n\tat java.util.Formatter.format(Formatter.java:2458)\n\tat java.lang.String.format(String.java:2842)\n\tat android.support.v7.preference.ListPreference.getSummary(ListPreference.java:178)\n\tat android.support.v7.preference.Preference.onBindViewHolder(Preference.java:584)\n\tat android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:381)\n\tat android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:45)\n\tat android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)\n\tat android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)\n\tat android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)\n\tat android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)\n\tat android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)\n\tat android.support.v7.widget.GapWorker.prefetch(GapWorker.java:366)\n\tat android.support.v7.widget.GapWorker.run(GapWorker.java:397)\n\tat android.os.Handler.handleCallback(Handler.java:873)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:215)\n\tat android.app.ActivityThread.main(ActivityThread.java:6929)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)\n"
   ],
   "user_comment": ""
}

**Comment by TobiGr** [comment] 2019-08-18 13:57
@shadypt should be fixed with 96e11227f09c1e1b67b84d35bc4ed2ec13e5a38e

**Comment by shadypt** [comment] 2019-08-18 13:59
@TobiGr Thanks, I will close the issue when fixed

**Comment by undeadfox** [comment] 2019-08-18 14:07
> 
> 
> @shadypt should be fixed with [96e1122](https://github.com/TeamNewPipe/NewPipe/commit/96e11227f09c1e1b67b84d35bc4ed2ec13e5a38e)

Similar typo: https://github.com/TeamNewPipe/NewPipe/blob/60f534d7a1ed1fe8323e0c5c86171bc7de0441f2/app/src/main/res/values-cs/strings.xml#L452

**Comment by unknowndelicateboy** [comment] 2019-08-19 04:29
[FR] 1. option to clear playback position  
2. search filter (https://i.imgur.com/iBMEMWI.png)

**Comment by theScrabi** [comment] 2019-08-19 10:36
@TobiGr what do you think? Stable enough to be released?

**Comment by Stypox** [comment] 2019-08-19 10:42
1. Open a standalone issue, this is **not a bug** introduced by 0.17.1
2. #110
@unknowndelicateboy

**Comment by TobiGr** [comment] 2019-08-19 10:49
@theScrabi yes

**Closed** 2019-08-22 09:47 UTC
