### ISSUE TITLE
Can't share link to newpipe

### ISSUE THREAD

**Issue by daufinsyd** [TeamNewPipe/NewPipe#8376] opened 2022-05-09 16:59 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

Try to share a supported link to newpipe (example https://www.youtube.com/clip/UgynGz5ityIwD3jv5xp4AaABCQ)

### Expected behavior

Link can be shared and opened in newpipe.

### Actual behavior

Newpipe won't be listed in the app list, or if it is (sharing from Firefox for examen) it won't work with the following error:
<img alt="Screenshot_2022-05-09-18-51-51-834_org schabi newpipe jpg" src="https://user-images.githubusercontent.com/1218113/167459466-5b611bad-6dd3-4edd-87ae-8cdb2f2700c1.png" height=600 />

### Screenshots/Screen recordings

<img alt="Screenshot_2022-05-09-18-58-21-066_android jpg" src="https://user-images.githubusercontent.com/1218113/167460060-768ad40e-127a-4c32-84be-30a2fd62a4c5.png" height=600 />
<img alt="Screenshot_2022-05-09-18-51-51-834_org schabi newpipe jpg" src="https://user-images.githubusercontent.com/1218113/167460063-3b99e1a0-952f-4475-bf0c-f76f2e79f617.png" height=600 />

### Affected Android/Custom ROM version

MIUI 13.0.4

### Affected device model

Poco F3

**Comment by litetex** [comment] 2022-05-11 19:14
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6828

Also please note for the future:
* Please also add the Android version
* English screenshots would be great - I can't read french

**Closed by litetex** 2022-05-11 19:14 UTC
Labels: bug
