### ISSUE TITLE
Age restriction

### ISSUE THREAD

**Issue by Avocadoman6** [TeamNewPipe/NewPipe#8107] opened 2022-03-25 16:57 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1 in any of the restricted videos

### Steps to reproduce the bug

Just watch any video that is age restricted on youtube

### Expected behavior

I expected the video to play out like normal

### Actual behavior

It didn't play and instead crashed when I tried, even when I had the settings on age restriction off

**Comment by SameenAhnaf** [comment] 2022-03-25 17:01
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/8102

**Closed** 2022-03-25 19:52 UTC
Labels: bug
