### ISSUE TITLE
Enqueued Video will fail to load upon opening the app the next day

### ISSUE THREAD

**Issue by Verathor** [TeamNewPipe/NewPipe#6885] opened 2021-08-09 22:05 UTC
If you queue up a list of videos but don't finish watching them the day of, when you open that list to continue watching the next day the video that you paused on will completely fail to load. Even removing it from the queue and restarting the app does not fix it and I end up having to watch that video on a different youtube app.

### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Leave a queue of videos overnight.
2. Try to play the current video the next day

### Device info

Android version 10
Galaxy Note 9

**Comment by SameenAhnaf** [comment] 2021-08-09 23:33
This is the expected behavior.

<details><summary> 1. You may save the whole queue within a new or existing playlist. </summary>

<img src="https://user-images.githubusercontent.com/79245641/128786566-d539cd6b-3ea5-48d9-9439-b26658d5d749.jpg"
height="300px"/>

</details>

<details><summary> 2. Or, you may save a single video to any playlist from a long press menu. </summary>

<img src="https://user-images.githubusercontent.com/79245641/128787085-b8ba8cd9-0606-43b0-8c9b-dca425baf1ef.jpg"
height="300px"/>

</details>

**Comment by ShareASmile** [comment] 2021-08-10 19:43
> This is the expected behavior.

@SameenAhnaf No, you probabely misread the issue, otherwise there is no way you could have stated this to be a kind of "Expected Behavior" 

Hastened responses like these neither help issue creator nor make maintainer's job easy & may create unnecessary confusions.

Actual problem is  {Playback fails on [Expired Stream Link] & doesn't recover} & is already reported in #5730

duplicate of #5730

**Closed** 2021-08-10 22:37 UTC
