### ISSUE TITLE
Video not available

### ISSUE THREAD

**Issue by Suncatcher** [TeamNewPipe/NewPipe#3064] opened 2020-02-06 11:09 UTC
Video not available error is thrown on some videos, presumably Live ones or recently released.
Version is latest.

![photo_2020-02-06_05-57-07](https://user-images.githubusercontent.com/6388034/73931945-3ee2a300-48a7-11ea-8ace-770048d2e7f1.jpg)

![photo_2020-02-06_05-57-11](https://user-images.githubusercontent.com/6388034/73931948-41dd9380-48a7-11ea-9ad9-be3f2f09468d.jpg)

**Comment by gkeegan** [comment] 2020-02-06 14:40
Confirmed. I've seen this on recent videos as well. Going back then clicking the video again makes it load though.

**Comment by Suncatcher** [comment] 2020-02-06 16:16
> Going back then clicking the video again

Immediate back-and-return doesn't help. Waiting 10 min helps sometimes, but I didn't find any strict rule or time interval though.

**Comment by B0pol** [comment] 2020-02-06 19:28
Should be related to this comment:
https://github.com/TeamNewPipe/NewPipe/issues/2969#issuecomment-580718374

There is currently no live preview support on NewPipe. 
Your issui is a video but planned to be streamed in live (so there will be a chat, but no stream, just recorded video), so it's not exactly the same but really close.

**Comment by Suncatcher** [comment] 2020-02-07 12:08
> If as you say it's a "live video"

It is NOT always a Live video. Sometimes I experienced that on videos that are years old. I will post here all videos where I meet this issue

**Comment by Stypox** [comment] 2020-02-07 13:38
Duplicate of #2900

**Closed by Stypox** 2020-02-07 13:38 UTC
