### ISSUE TITLE
Content is not available

### ISSUE THREAD

**Issue by 11fen** [TeamNewPipe/NewPipe#3116] opened 2020-02-20 08:45 UTC
![ppp](https://user-images.githubusercontent.com/44218055/74916065-296d8d00-5400-11ea-83d4-72a47df6b3ba.PNG)
Content is not available  （v0.18.3）
https://www.youtube.com/watch?v=qgDvlqgB5Jg

**Comment by Stypox** [comment] 2020-02-20 12:38
Duplicate of #2900

**Closed by Stypox** 2020-02-20 12:38 UTC
