### ISSUE TITLE
YouTube Music Mode must be added

### ISSUE THREAD

**Issue by Ledenav** [TeamNewPipe/NewPipe#5807] opened 2021-03-11 07:51 UTC
There are options in the menu for platforms such as SoundCloud, YouTube. The option for YouTube Music should also be added. This will display YouTube Music suggestions on the Homepage. And searches will only show YouTube Music results.
Please add the YouTube Music page.

**Comment by mhmdanas** [comment] 2021-03-11 08:48
Duplicate of #4844. Also, please don't remove the template when opening an issue.

**Closed by mhmdanas** 2021-03-11 08:48 UTC
Labels: enhancement

**Comment by AthenaZiff** [comment] 2021-06-20 13:53
Yes, NewPipe is missing a YouTube Music tab
