### ISSUE TITLE
[FEATURE REQUEST] Implement horizontal video seeking (like VLC has)

### ISSUE THREAD

**Issue by campbellkerr** [TeamNewPipe/NewPipe#5119] opened 2020-12-07 03:45 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Vertical swiping currently allows us to adjust brightness and volume.

VLC also has horizontal swiping to seek back and forward in the video. It also shows how far you're seeking, eg `+10 (1:10)` or `-15 (0:45)`

This would be a handy feature!

Pic of VLC video controls:
![image](https://user-images.githubusercontent.com/38451588/101306827-07af9a80-389a-11eb-8fbd-f133a59fe8c1.png)

#### How will you/everyone benefit from this feature?
This will make seeking easier, more accessible (currently to seek you have to tap the screen, then fiddle with the small seek bar) and more accurate. I realise it may not be easy to show live previews when seeking on YouTube videos, but at least we could easily see how many seconds/minutes we're jumping to). Thanks!

**Comment by mhmdanas** [comment] 2020-12-07 05:20
Duplicate of #889.

**Closed by mhmdanas** 2020-12-07 05:20 UTC
Labels: enhancement
