### ISSUE TITLE
Search history not working well

### ISSUE THREAD

**Issue by illustribe** [TeamNewPipe/NewPipe#7707] opened 2022-01-27 10:40 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

Usually when clicking on the search icon one would get the keyboard to type a search query AND at the same time the history of searches would show up starting from the last search made. Of course this is super useful when one doesn't need to type it all in again.
But now (since some 3-4 versions back) the search history doesn't refresh with the new searches, and continues to list rather old search queries first.
It's clear it's a problem of the list sorting, since if I types in again the latest search query I did (for example), it does show up as a past query already been searched  before (by the icon of clock+arrow instead of the magnifying glass when it's a new search).

### Expected behavior

The list of searches already done listed as history sorted by the latest first

### Device info

 - Android version/Custom ROM version:
 - Device model:
Pocofone f1 xiaomi Android 9

**Comment by mhmdanas** [comment] 2022-01-27 12:59
Duplicate of #6763.

**Closed by mhmdanas** 2022-01-27 12:59 UTC
Labels: bug
