### ISSUE TITLE
Download videos without opening 

### ISSUE THREAD

**Issue by Hanankhan1983** [TeamNewPipe/NewPipe#7959] opened 2022-02-27 14:32 UTC
### Checklist

- [ ] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hi ,newpipe team so I want a feature that could download videos without opening the video you want to download. just by long pressing the video there would be a pop up in the pop up there will be a option to  download and you can download it without opening like SnapTube

                                                                                         Thank you 😊

### Why do you want this feature?

Because it's hard to Download a lot of videos from a channel. Open one by one and click download

**Comment by SameenAhnaf** [comment] 2022-02-27 14:53
Duplicate of #2171. Check the APK in https://github.com/TeamNewPipe/NewPipe/pull/6563

**Comment by Hanankhan1983** [comment] 2022-02-27 15:21
> Duplicate of #2171. Check the APK in #6563

Ooh I didn't knew it's a duplicate but where the APK? I didn't found it

**Closed** 2022-02-27 16:07 UTC
Labels: enhancement, duplicate
