### ISSUE TITLE
Random video notification popup

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6141] opened 2021-04-22 12:18 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Just randomly mess around and wait

### Actual behaviour

Some popup randomly appears saying Video is loading even though I didn't open newpipe

### Expected behavior

Nothing

### Screenshots/Screen recordings

![Imagepipe_0](https://user-images.githubusercontent.com/74511929/115712787-e13c5880-a37d-11eb-81e7-a26975483574.jpg)

### Device info

 - Android version/Custom ROM version: Version 7.1.1 Nougat
 - Device model: SM P555

**Comment by TiA4f8R** [comment] 2021-04-22 16:48
I think it's a duplicate of #5778. If you don't think so, please comment why and I will reopen this issue.

**Closed by TiA4f8R** 2021-04-22 16:48 UTC
Labels: bug
