### ISSUE TITLE
Video playing in Same screen

### ISSUE THREAD

**Issue by manimaran96** [TeamNewPipe/NewPipe#2249] opened 2019-03-25 12:29 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

When the user tap to play a video, New pipe takes to another screen.
But user expects to play at the video player view as in youtube. 
Because the user can explore other videos list while playing.

![photo6109621842651228293](https://user-images.githubusercontent.com/13943321/54919768-aa3db380-4f27-11e9-9353-4fe31f50f89b.jpg)

**Comment by gkeegan** [comment] 2019-03-25 16:02
So like this? ![Image](https://user-images.githubusercontent.com/32858528/54934782-fcc2a400-4f16-11e9-9aed-6174a0e135a8.png)
The image is from here: https://github.com/TeamNewPipe/NewPipe/pull/834, but that code can't be used.

Anyways, this is a duplicate of #528 and possibly #1831.

**Closed** 2019-03-26 22:47 UTC
Labels: duplicate
