### ISSUE TITLE
Gestures Request

### ISSUE THREAD

**Issue by dude-shah** [TeamNewPipe/NewPipe#7660] opened 2022-01-15 17:06 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Can you make a swipe down gesture on video to exit full screen.

![IMG_20220115_220029.jpg](https://user-images.githubusercontent.com/63038690/149710652-e4a08d36-2b0d-4e5b-aa9a-dfd50dd81216.jpg)

#### Why do you want this feature?
cool features are fun for the app experience.

**Comment by SameenAhnaf** [comment] 2022-01-15 18:08
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7624

**Comment by dude-shah** [comment] 2022-01-16 04:08
> Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7624

Sorry it's not duplicate ... i suggested other ui changes too

**Comment by mhmdanas** [comment] 2022-01-16 04:21
@dude-shah one of the items that you have checked is this:

> This issue contains only one feature request. I will open one issue for every feature I want to request.

Since your gesture request is a duplicate, please edit your issue to mention only your other suggestion (the customizable button placement one).

**Comment by dude-shah** [comment] 2022-01-16 10:02
Changed it to buttons ...

**Comment by SameenAhnaf** [comment] 2022-01-16 10:25
@dude-shah Please avoid including multiple feature requests into the same issue. Such actions lead to confusion. You've already filled the template. Plus, you can always close an issue and open a new one. 

>This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by dude-shah** [comment] 2022-01-16 10:28
No prob here ... just add the gesture this time 
I'll make the button request some other time

**Comment by litetex** [comment] 2022-01-16 19:41
> #### What feature do you want?
> 
> Can you make a swipe down gesture on video to exit full screen.
> 
>  ``<Image>``

1. Why does the text say swipe down but the picture has an arrow pointing upwards?
2. What are the circles on the bottom for?

> #### Why do you want this feature?
> cool features are fun for the app experience.

That's not a valid reason.

**Comment by dude-shah** [comment] 2022-01-17 05:01
Check now

**Comment by litetex** [comment] 2022-01-17 18:59
> Check now

Better but there are still 2/4 points missing.

> The title is it's a bit unspecific.

> That's not a valid reason.

**Closed** 2022-02-01 00:08 UTC
Labels: enhancement, waiting-for-author
