### ISSUE TITLE
Comments not showing up

### ISSUE THREAD

**Issue by MrFeelgoood** [TeamNewPipe/NewPipe#5110] opened 2020-12-06 15:08 UTC
### Checklist

- [x] I am using the latest version - 0.20.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a video.
2. Go in the comment section.
3. You will notice that comments are not showing up. 

### Actual behaviour
Comments are not showing up anymore even with the "show comments" option enabled.

### Expected behavior
Comments should be visible with the "show comments" option enabled.

### Device info

 - Android version/Custom ROM version: OxygenOs 10.3.7
 - Device model: Oneplus 6T

**Comment by mhmdanas** [comment] 2020-12-06 15:21
Duplicate of https://github.com/TeamNewPipe/NewPipeExtractor/issues/455.

**Closed by mhmdanas** 2020-12-06 15:21 UTC
Labels: bug
