### ISSUE TITLE
cant play videos

### ISSUE THREAD

**Issue by coolst3r** [TeamNewPipe/NewPipe#8041] opened 2022-03-15 18:28 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

I choose a video 
Then try and play it

### Expected behavior

To play the video

### Actual behavior

Crashes  at play

### Screenshots/Screen recordings

https://www.directupload.net/file/d/6488/oirp77gi_png.htm

### Logs

{"user_action":"play stream","request":"Player error[type=1] occurred while playing https://www.youtube.com/watch?v=GMOoXz20VZU","content_language":"en-GB","content_country":"UG","app_language":"en_AU","service":"YouTube","package":"org.schabi.newpipe","version":"0.22.1","os":"Linux Android 10 - 29","time":"2022-03-15 20:10","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 29.97003], [-1, -1]), format_supported=YES\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)\n\tat android.os.Handler.dispatchMessage(Handler.java:103)\n\tat android.os.Looper.loop(Looper.java:214)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:864)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)\n\t... 3 more\nCaused by: java.lang.IllegalStateException\n\tat android.media.MediaCodec.native_dequeueInputBuffer(Native Method)\n\tat android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2729)\n\tat com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:93)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1209)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:845)\n\t... 5 more\n"],"user_comment":""}

### Affected Android/Custom ROM version

Android 10 linage os

### Affected device model

redmi 9c

### Additional information

It a fresh install

**Comment by litetex** [comment] 2022-03-15 20:32
Duplicate of #8041

**Closed by litetex** 2022-03-15 20:32 UTC
Labels: bug

**Comment by KiYugadgeter** [comment] 2022-03-20 08:59
> Duplicate of #8041 (← This issue even contains a correctly formatted exception)

This is recursive reference
