### ISSUE TITLE
Implement option for hiding Future Videos/Lives from channel subscription

### ISSUE THREAD

**Issue by pleiozc** [TeamNewPipe/NewPipe#6553] opened 2021-06-22 22:25 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

If possible implement option that allows to hide future videos (week, days from now). It's taking alot of space with many subscriptions and you have to scroll down to get to newly posted videos in feed.

#### How will you/everyone benefit from this feature?

Not wasting time to scroll through all the videos that are pinned at the top of all subscription feeds.

**Comment by mhmdanas** [comment] 2021-06-22 23:33
Duplicate of #5875.

**Closed by mhmdanas** 2021-06-22 23:33 UTC
Labels: enhancement
