### ISSUE TITLE
[0.19.3] App Crash returning from download screen to playlist view that ended

### ISSUE THREAD

**Issue by rancidfrog** [TeamNewPipe/NewPipe#3561] opened 2020-05-09 21:45 UTC
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.19.3
* __OS:__ Linux Android 7.1.1 - 25

<details><summary><b>Crash log</b></summary><p>

```
java.lang.RuntimeException: Unable to resume activity {org.schabi.newpipe/org.schabi.newpipe.player.MainVideoPlayer}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.playqueue.PlayQueue.init()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3572)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3612)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2854)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6334)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.playqueue.PlayQueue.init()' on a null object reference
	at org.schabi.newpipe.player.BasePlayer.initPlayback(BasePlayer.java:355)
	at org.schabi.newpipe.player.MainVideoPlayer.onResume(MainVideoPlayer.java:294)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1364)
	at android.app.Activity.performResume(Activity.java:6847)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3542)
	... 10 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.playqueue.PlayQueue.init()' on a null object reference
	at org.schabi.newpipe.player.BasePlayer.initPlayback(BasePlayer.java:355)
	at org.schabi.newpipe.player.MainVideoPlayer.onResume(MainVideoPlayer.java:294)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1364)
	at android.app.Activity.performResume(Activity.java:6847)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3542)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3612)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2854)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6334)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```
</p></details>
<hr>
 
App crashed on return from download list.
- Queued multiple files on pop-up player
- Clicked notification to show playlist queue for pop-up player
- Shared one item in list to newpipe to download
- Clicked notification to show download list
- Pop-up queue ends so drag pop-up player to 'x' to exit
- Download finished so click back button to exit
- Back tries to go back to Newpipe playlist view for pop-up player, which does not exist anymore since I dragged pop-up to 'x' so it is now null hence the crash

**Comment by Stypox** [comment] 2020-09-08 21:43
Does [this apk](https://github.com/TeamNewPipe/NewPipe/files/5190780/app-debug.zip), containing the features that will be in 0.20.0, fix the issue?

**Comment by Stypox** [comment] 2020-09-08 21:50
#3200

**Closed by Stypox** 2020-09-08 21:50 UTC
Labels: GUI, bug, more info needed

**Comment by opusforlife2** [comment] 2020-09-08 22:08
> Shared one item in list to newpipe to download

What is this feature I don't have this. O_O

**Comment by opusforlife2** [comment] 2020-09-08 22:16
@Stypox Were you able to follow the STR? I don't understand the step above so I can't say either way if it's solved or not.

**Comment by Stypox** [comment] 2020-09-09 08:03
@opusforlife2 this is duplicate of #3200, and is not solved
