### ISSUE TITLE
Reading comments while keeping the video on the 

### ISSUE THREAD

**Issue by MattRGX** [TeamNewPipe/NewPipe#6195] opened 2021-04-28 15:49 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Today if i scroll through the comments, i can't see the video anymore.
Be able to make the player video static. That way, i can scroll through comments but still can watch the video.

#### How will you/everyone benefit from this feature?

I think that lot of people are waiting for that and it will be very handful

**Comment by skyGtm** [comment] 2021-04-28 17:47
Duplicate of #4484
Until the feature is implemented, you can use a little hack as follows
1. Open popup player
2. Resize and place it at the top of the screen
3. Scroll through comments

Video here: https://github.com/TeamNewPipe/NewPipe/issues/5450#issuecomment-762596954

**Closed** 2021-04-28 19:32 UTC
Labels: enhancement
