### ISSUE TITLE
Exception ui error 0.21.9

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [TeamNewPipe/NewPipe#7010] opened 2021-08-29 05:34 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@68ecb0a with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'long org.schabi.newpipe.player.playqueue.PlayQueueItem.getRecoveryPosition()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long org.schabi.newpipe.player.playqueue.PlayQueueItem.getRecoveryPosition()' on a null object reference
	at org.schabi.newpipe.player.Player.handleIntent(Player.java:674)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:129)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
	... 8 more

```
</details>
<hr>

**Comment by litetex** [comment] 2021-08-29 16:06
Looks like a duplicate of #6652.

Would be good if you could file a complete bug report: https://github.com/TeamNewPipe/NewPipe/issues/new?assignees=&labels=bug&template=bug_report.md else we don't know how the error happened...

**Comment by mhmdanas** [comment] 2021-08-31 14:39
@litetex why do you think it's a duplicate of #6652? The errors look different to me.

**Closed** 2021-08-31 14:39 UTC
Labels: bug, template-missing

**Comment by litetex** [comment] 2021-08-31 16:17
@mhmdanas 
The reason/message is exactly the same:
``Attempt to invoke virtual method 'long org.schabi.newpipe.player.playqueue.PlayQueueItem.getRecoveryPosition()' on a null object reference`` 

Only the locations are different 🤔

**Comment by mhmdanas** [comment] 2021-08-31 16:57
Ah, makes sense; I only looked at the first exception.
