### ISSUE TITLE
Black/Whitelist for channels and videos

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#4911] opened 2020-11-18 11:06 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I was scrolling F-Droid and found a youtube client which had this black/whitelisting feature, and it nearly got me to install it.
Maybe with the blacklisting NewPiep could have an "Automatically whitelist subscribed channels" with whitelist mode on, a block button next to the subscribe button on blacklist mode, and an option for none.
I realized before I installed said app, it could be bad, and nothing can match the quality of NewPipe.

**Comment by Stypox** [comment] 2020-11-18 11:44
Duplicate of #1815

**Closed by Stypox** 2020-11-18 11:44 UTC
Labels: enhancement, template-ignored

**Comment by HTSamurai** [comment] 2022-04-05 16:46
This includes a whitelist feature though

**Comment by opusforlife2** [comment] 2022-04-08 19:49
So it's a half-duplicate, you're saying? xD

The functionality needed is the same. Don't bump zombie issues.
