### ISSUE TITLE
Ability to "lock screen"

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#3330] opened 2020-04-02 06:10 UTC
#### Is your feature request related to a problem? Please describe it
I'd like to have a feature to lock the screen so in case a user presses a button on accident, the screen lock could prevent that.

#### How will you/everyone benefit from this feature?
So button pressing mistakes could not happen as frequently.

**Comment by Stypox** [comment] 2020-04-02 07:19
Duplicate of #1734

**Closed by Stypox** 2020-04-02 07:19 UTC
Labels: enhancement
