### ISSUE TITLE
Implement action buttons (pause/resume & cancel) on download notification

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#151] opened 2016-01-09 20:04 UTC
![unnamedrttuyduo](https://cloud.githubusercontent.com/assets/6850125/12218460/048b8d42-b720-11e5-9f68-35f107abfb15.png)

**Comment by theScrabi** [comment] 2016-01-09 21:04
Will come. In february I whant to refactor downloading anway.

**Comment by M2ck** [comment] 2016-01-09 21:30
Great! It will close #13 too by the way.
I've updated title and added screenshot above.

**Comment by opusforlife2** [comment] 2020-08-04 02:03
Duplicate of #3332.

**Closed** 2020-08-04 06:11 UTC
Labels: GUI, downloader, enhancement
