### ISSUE TITLE
Enqueue in background & minimise on app switch

### ISSUE THREAD

**Issue by offshade** [TeamNewPipe/NewPipe#7542] opened 2021-12-15 08:41 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?

In previous versions you could enqueue tracks in the background when adding them, now everything just starts playing replacing the current playing song. Is there any way this can be done? 

Also, "minimise on app switch" to background, does not continue playing the current playing song of a playlist, but starts the playlist from the beginning.

**Comment by BoldyPlays** [comment] 2021-12-15 17:53
Able to replicate, bug specific to the latest version.

0.21.14
Samsung SM-N975F/DS (Note10+)

**Comment by offshade** [comment] 2021-12-15 20:39
I don't understand.

**Comment by AlertSubject** [comment] 2021-12-15 23:46
Seems to be a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7531

**Comment by ThisIsPaulDaily** [comment] 2021-12-19 14:42
I think this PR solves it. It's a PR for a fix that broke in version 19. They only just opened it after closing a different PR. Pretty sure this is the one, but search open PRs for related fixes too.  https://github.com/TeamNewPipe/NewPipe/pull/7266

**Comment by offshade** [comment] 2021-12-19 19:49
> I think this PR solves it. It's a PR for a fix that broke in version 19. They only just opened it after closing a different PR. Pretty sure this is the one, but search open PRs for related fixes too. #7266

That's exactly what I was looking for, thank you very much!

**Comment by SameenAhnaf** [comment] 2021-12-21 08:26
@litetex Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7531 and https://github.com/TeamNewPipe/NewPipe/issues/4779

**Comment by litetex** [comment] 2021-12-21 16:55
> In previous versions you could enqueue tracks in the background when adding them, now everything just starts playing replacing the current playing song.

That is definitely wrong and was never intended to happen.
Update: Just checked v0.21.8 and was unable to reproduce enqueing with the default settings.

See also #4779

For the other thing mentioned in this issue see #7531

Closing this issue as duplicate.

**Closed by litetex** 2021-12-21 16:55 UTC
Labels: question
