### ISSUE TITLE
Recommended videos.

### ISSUE THREAD

**Issue by jniniinoinoino** [TeamNewPipe/NewPipe#3311] opened 2020-03-30 20:46 UTC
#### Is your feature request related to a problem? Please describe it
*The problem is that there isn't any recommended videos*

#### Describe the solution you'd like
*The solution is, we create a new recommended videos tab(kiosk) that takes multiple watched videos from "Next" and post them inside recommended videos kiosk. This way we get similar videos from what we have watched. I don't know how heavy this will be on the app. But maybe copy "Next" videos from max 20 watched videos? After you watched a total amount of videos it asks you to refresh the recommended videos tab and takes new videos or same videos.. Cuz YouTube isn't that great at it either. I get the same videos constantly back to back.*

#### Additional context
*I can't post pictures but I would if I could rn.*

#### How will you/everyone benefit from this feature?
This is a huge step into the right direction. People wanna discover new videos, more content. The only thing that separates us from YouTube is recommended videos. This won't be as accurate but sure will do wonders.

**Comment by Stypox** [comment] 2020-03-30 20:55
Duplicate of #2256

**Closed by Stypox** 2020-03-30 20:55 UTC
Labels: enhancement
