### ISSUE TITLE
Click on the video to play on the small screen first

### ISSUE THREAD

**Issue by a936919** [TeamNewPipe/NewPipe#3492] opened 2020-04-26 04:11 UTC
Describe the feature you want
Click on the video to play on the small screen first

Is your feature request related to a problem? Please describe it
When you click the video to play in the list, first play the small screen at the top of the screen to see if there is a demand and then play it in full screen.

Screenshots/Screen recordings
![S00426-12090516](https://user-images.githubusercontent.com/41937411/80297574-e4c2f100-87b6-11ea-89e8-da523217e330.png)
Hope it's the same

**Comment by wb9688** [comment] 2020-04-26 05:58
You mean like in #2907?

**Comment by Stypox** [comment] 2020-04-27 06:25
Duplicate of #2882 and others

**Closed by Stypox** 2020-04-27 06:25 UTC
Labels: enhancement
