### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by JohnConstantine88** [TeamNewPipe/NewPipe#8214] opened 2022-04-15 08:27 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

NewPipe 0.22.1

### Steps to reproduce the bug

<img alt="Screenshot_20220415-112233724" src="https://user-images.githubusercontent.com/103735357/163546222-43632b96-0140-4cf4-a810-088e6f714e97.jpg" height=600 />

### Expected behavior

düzeltilmesini rica ediyorum

### Actual behavior

ERROR 
<img alt="Screenshot_20220415-112233724" src="https://user-images.githubusercontent.com/103735357/163545874-4dbfb4ff-e245-46e8-9750-bde91bdc6c39.jpg" height=600 />

### Screenshots/Screen recordings

<img alt="Screenshot_20220415-112015667" src="https://user-images.githubusercontent.com/103735357/163545468-52eedd1d-e611-4432-9718-1c0ecdc2bc8c.jpg" height=600 />
<img alt="Screenshot_20220415-112233724" src="https://user-images.githubusercontent.com/103735357/163545754-b59689aa-98ce-41e5-b959-f428ba6d671e.jpg" height=600 />

### Logs

ERROR
<img alt="Screenshot_20220415-112233724" src="https://user-images.githubusercontent.com/103735357/163546055-3a1a6356-84f7-4297-9708-869820423755.jpg" height=600 />

hata hata

### Affected Android/Custom ROM version

12 android

### Affected device model

Asus rog phone 3

### Additional information

ERROR
<img alt="Screenshot_20220415-112233724" src="https://user-images.githubusercontent.com/103735357/163545940-3fb51a70-174b-47d7-9928-ae0a5773451f.jpg" height=600 />

**Comment by ZaneHannanAU** [comment] 2022-04-15 08:30
Duplicate

**Comment by Me0wzz** [comment] 2022-04-15 08:31
Duplicate of #8202

**Closed** 2022-04-15 08:37 UTC
Labels: bug
