### ISSUE TITLE
Rotation to landscape results in the video only in the top left corner.

### ISSUE THREAD

**Issue by DB501** [TeamNewPipe/NewPipe#8399] opened 2022-05-14 12:56 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Play any youtube video
2. Rotate the screen to landscape

### Expected behavior

The video should be played in fullscreen with the image over the whole screen.

### Actual behavior

Most of the times the video is in top left of the screen and the rest of the screen is black. As if the size of the video didn't change from portrait mode

### Screenshots/Screen recordings

![Screenshot_20220514-143745_NewPipe](https://user-images.githubusercontent.com/105549189/168426500-cce9669d-1d88-41e8-a6be-ce8205180c67.jpg)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S21 5G

### Additional information

It works correct if the video is paused when rotating the screen and unpaused after the rotation.

**Comment by TiA4f8R** [comment] 2022-05-14 13:35
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #7262. Please search (better, with different keywords?) for duplicates the next time you want to open an issue.

Thank you.

**Closed by TiA4f8R** 2022-05-14 13:35 UTC
Labels: bug
