### ISSUE TITLE
The pop up window resizes to small size everytime I try to resize it

### ISSUE THREAD

**Issue by ridwan47** [TeamNewPipe/NewPipe#1642] opened 2018-08-30 05:43 UTC
The pop up window resizes to small size everytime I try to resize it. It should remain the same size as before when I pinch it, to resize to a new size.

**Comment by Duppadaadadii** [comment] 2018-08-30 11:05
I think that pop-up rezising works kind of janky. it's like you have to move your both fingers just right to get it to move. Not like in most zooming where you just move fingers apart enough and it will zoom.

**Comment by Duppadaadadii** [comment] 2018-08-30 19:54
X-axis zooms. Y-axis does not. Just noticed.

**Comment by Stypox** [comment] 2019-08-27 13:40
Duplicate of #515

**Closed by Stypox** 2019-08-27 13:40 UTC

**Comment by haistakaavittukaikkisaatana** [comment] 2019-10-11 14:26
Im not sure if this a bug or how its supposed to work, but I can resize popup window with only one finger, by holding my finger on top of the popup window a half a second will resize the popup window. I dont mind at all if this is a bug, I kinda like it for simplicity lol.

Check this video:

https://streamable.com/s/b7jw8
