### ISSUE TITLE
does not recognize the function activated in the settings for the videos to open in full screen

### ISSUE THREAD

**Issue by razbone** [TeamNewPipe/NewPipe#9093] opened 2022-10-09 18:22 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

in the settings I let the youtube video open in full screen
but when watching any video it does not do the feature

### Expected behavior

the video opens in full screen

### Actual behavior

it does not recognize the function activated in the settings

### Affected Android/Custom ROM version

android 8 

### Affected device model

box tv

**Comment by opusforlife2** [comment] 2022-10-09 19:11
Probably related to #9023.

**Comment by Stypox** [comment] 2023-02-16 22:13
Duplicate of #9027

**Closed by Stypox** 2023-02-16 22:13 UTC
Labels: bug, player, Android TV
