### ISSUE TITLE
SoundCloud: Can't analyse this website

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#3542] opened 2020-05-06 12:38 UTC
### Version

- 0.19.3
### Steps to reproduce the bug

1. Bring up the side panel.
2. Switch the search to SC.
3. Try searching anything.
______________
1. Open any SC link, to profile or to track.
2. Let it open NewPipe.

### Expected behavior

The track, profile or search results show up.

### Actual behaviour

I get an error message.

### Screenshots/Screen recordings

![Screenshot_20200506-143726_NewPipe](https://user-images.githubusercontent.com/26146502/81177558-24ec5580-8fa7-11ea-9aa7-a86da27d938c.jpg)

### Logs

https://hastebin.com/goxequfuba.md

**Comment by Stypox** [comment] 2020-05-06 13:54
The text that is generated using the [Incredible Error Report to Markdown Converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) is supposed to be pasted right after the `Logs` title: the output format is markdown.
Anyway this is a duplicate of #2915

**Closed by Stypox** 2020-05-06 13:54 UTC
Labels: bug
