### ISSUE TITLE
Disable (touch) input / lock controls and interface

### ISSUE THREAD

**Issue by kecksk0enig** [TeamNewPipe/NewPipe#1575] opened 2018-08-03 08:17 UTC
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi, I would like to recomend a feature well known from MXPlayer which is capable of locking the complete screen so it does not react on an accidently made userinput. 

This would allow my 2yr old son to watch a video throug newPipe without constantly  returning to the home menu.

Thanks in advance

**Comment by SameenAhnaf** [comment] 2021-08-24 06:18
@mhmdanas Shouldn't this be closed in favor of #5740?

**Comment by litetex** [comment] 2021-12-11 11:49
Duplicate of #1575

**Closed by litetex** 2021-12-11 11:49 UTC
Labels: enhancement, GUI

**Comment by opusforlife2** [comment] 2021-12-11 16:35
@litetex Same here. Self-referencing duplicate. It's like a recursive function. :P
