### ISSUE TITLE
Fullscreen video sometimes stuck at small size

### ISSUE THREAD

**Issue by qol3m** [TeamNewPipe/NewPipe#8309] opened 2022-04-30 00:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. rotate phone for fullscreen

### Expected behavior

video displays in fullscreen

### Actual behavior

video often does not display in fullscreen, but is stuck at the small size it had before going fullscreen. I have to keep on leaving fullscreen and rotate back until it works. see screenshot

### Screenshots/Screen recordings

![Screenshot_20220430-021006_NewPipe](https://user-images.githubusercontent.com/43688266/166082604-97ad6c72-fcb4-41b0-b233-1e511db8c23b.jpg)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy A52s 5G

**Comment by SameenAhnaf** [comment] 2022-04-30 00:23
Duplicate of Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7262

**Closed** 2022-04-30 04:35 UTC
Labels: bug
