### ISSUE TITLE
Show if video is (already) added to playlist

### ISSUE THREAD

**Issue by dennis90a** [TeamNewPipe/NewPipe#7526] opened 2021-12-12 02:37 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

An indication that shows if a video has already been added to a playlist. Like YouTube does. 
What NewPipe could do is show a little check onstead of the plus in the playlist button. If it is clicked(and it has already been added), there could be an option to remove it from a playlist or add it to a playlist.

#### Why do you want this feature?

Sometimes I end up adding the same video multiple times, because I would not remember if I had already added it.
Also, sometimes I while watching my Watch Later playlist, I would lik3 to remove the video I am watching from the playlist,  for which I would have to go to the playlista viewer and remove it from there.

**Comment by SameenAhnaf** [comment] 2021-12-12 06:24
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4186

**Closed** 2021-12-17 08:17 UTC
Labels: enhancement
