### ISSUE TITLE
Doesn't work smooth on 4G (even for 480p)

### ISSUE THREAD

**Issue by elSolus** [TeamNewPipe/NewPipe#6478] opened 2021-06-11 17:35 UTC
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

Not playing even the 480p videos smoothly, even on 4G.

### Expected behavior

I sometimes get 4G+. Anyway 4G is enough to play even 1080p videos smoothly.

### Device info

 - Android version/Custom ROM version: MIUI 12.0.4 Global Stable
 - Device model: Redmi Note 10 (4GB, 64GB)

**Comment by skyGtm** [comment] 2021-06-12 09:16
This issue might already be fixed. Get the apk from here https://github.com/TeamNewPipe/NewPipe/pull/6444#issuecomment-856623424

**Comment by Atemu** [comment] 2021-06-17 07:19
I'm not sure this is a buffering issue. I also sometimes experience a similar issue on WiFi where videos would load *very* slowly for no apparent reason. The download speed (as reported by LOS' status bar meter) while "watching" the video is in the lower hundred kbit/s while I easily get speeds in the megabytes when doing a speedtest in the browser.

Restarting and/or clearing all kinds of caches usually fixes this but yesterday I couldn't get a certain video to load properly at all.

I'm not sure it's the same one as experienced here but it seems similar.

What should I look for when I come across this issue again?

**Comment by botistreamer** [comment] 2021-06-18 12:21
I think this is related to #6510. 

Try this apk. https://github.com/TeamNewPipe/NewPipe/issues/6510#issuecomment-863908502

**Comment by masiv1001** [comment] 2021-07-26 14:44
> 
> 
> I think this is related to #6510.
> 
> Try this apk. [#6510 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/6510#issuecomment-863908502)

It also happened to me, installed Newpipe Extractor and now it works fine.

**Comment by elSolus** [comment] 2021-07-26 15:01
Where can I find that?

**Comment by masiv1001** [comment] 2021-07-26 16:15
Just download debug apk from here [https://github.com/TiA4f8R/NewPipe/pull/1/checks](url), click on "Artifacts" and then "app"

**Comment by elSolus** [comment] 2021-07-26 16:17
> Just download debug apk from here [https://github.com/TiA4f8R/NewPipe/pull/1/checks](url), click on "Artifacts" and then "app"

Hey, the link says "no result found"

**Comment by masiv1001** [comment] 2021-07-26 16:21
Just download debug apk from here [NewPipe Extractor debug apk](https://github.com/TiA4f8R/NewPipe/pull/1/checks) ,click on "Artifacts" and then "app"

**Comment by botistreamer** [comment] 2021-08-02 04:11
Isn't this a duplicate of #6510?

**Comment by litetex** [comment] 2021-11-28 15:46
I also think this is a duplicate of #6510. Issue will be automatically closed in 14days if no further comments from the author pop up.

**Closed** 2021-12-13 00:07 UTC
Labels: bug, waiting-for-author
