### ISSUE TITLE
Suggestion on playlists and general usability

### ISSUE THREAD

**Issue by DanDanG1224** [TeamNewPipe/NewPipe#2805] opened 2019-11-15 18:10 UTC
I think it would be great if you could download all the songs from a playlist and not have to download them all individually. That would make the app much more streamlined. Another thing you could add would be if you press and hold on a video you can download it. I think these would make NewPipe way better, but thanks for all you've done so far!
- [y ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [y ] I checked if the issue/feature exists in the latest version.
- [y ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment] 2019-12-03 14:23
Duplicate of #1236 (fixed by #2018). Take a look at #2583

**Closed by Stypox** 2019-12-03 14:23 UTC
