### ISSUE TITLE
Create a reposotiry to host and maintain the version 0.19.8

### ISSUE THREAD

**Issue by juanpaulconte** [TeamNewPipe/NewPipe#4786] opened 2020-11-03 05:37 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I'm wondering if it is possible to TeamNewPipe create a new repository to maintain a working version 0.19.8 of the NewPipe, like was made a time ago when created a new repository for hosting NewPipe-legacy?

#### Is your feature request related to a problem? Please describe it
I'm asking this because there are some people who like so much the way that NewPipe worked until the version 0.19.8.

The Unified Player merged on the version 0.20 have a negative impact to some NewPipe users that are dissatisfied with the new paradigm introduced by Unified Player. Others users have reported, too, a drop in performance.

#### Additional context
While the problem of performance can be addressed in some moment in the future on ongoing versions., these people are impossibility to use the actual version NewPipe in a adequate way today, or it is unusable at all.

About the main question, there are significant changes imposed from the Unified Play and his paradigm, that may not be solved in any moment in the future, because there are users that prefer much much more the former way that NewPipe always worked and feels that this is the way that it should be.

#### How will you/everyone benefit from this feature?
The creation of a repository will make possible maintain a version that embrace the way NewPipe worked until the version 0.19.8 and with focuses on low resources usage, targeting old devices like NewPipe-legacy already do, but maintaining the old paradigm, only doing changes required to make it work again and, may be, implementing future changes that have low impact on the actual performance or the paradigm, as long as it can be possible.

As this new-old version will have less bells and whistles then the main version of NewPipe that is constantly merged on NewPipe-legacy, maybe it make more simply to maintain the compatibility with the older devices, so the better option is that be a fork of NewPipe-legacy-0.19.8.

I'm not a software developer, but I am willing to help maintain it, together with other developers who eventually have an interest in this new-old version of NewPipe.

**Comment by opusforlife2** [comment] 2020-11-03 06:22
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

Duplicate of #4686. O_O

**Closed by opusforlife2** 2020-11-03 06:22 UTC
Labels: enhancement
