### ISSUE TITLE
Cannot edit Content order on FireTV (no swipe)

### ISSUE THREAD

**Issue by bluezed** [TeamNewPipe/NewPipe#7554] opened 2021-12-19 15:02 UTC
### Checklist

- [x] I am using the latest version - 0.21.14 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open New Pipe on FireTV
2. Go to Settings -> Content -> Content of Main page
3. Try to change the order or remove entries in the list.

### Actual behavior

There is no way on FireTV to swpie a list entry to remove it or hold it to move up or down.

### Expected behavior

For the use with the FireTV remote control there should be buttons or other ways to edit the list.

 

### Device info

 - Android version/Custom ROM version: Fire OS 7.2.5.5
 - Device model: Fire TV Stick 4K Max

**Comment by SameenAhnaf** [comment] 2021-12-19 15:18
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7022.

**Comment by litetex** [comment] 2021-12-20 15:26
Duplicate of #7022

**Closed by litetex** 2021-12-20 15:26 UTC
Labels: bug, Android TV, duplicate
