### ISSUE TITLE
Background Playback unpauses when minimized

### ISSUE THREAD

**Issue by DanGLES3** [TeamNewPipe/NewPipe#1538] opened 2018-07-22 02:56 UTC
I have the minimize feature enabled to switch to background player when minimized,the problem is that if the video is either paused or finished once minimized they resume playing,please make so if the video is stopped/finished the background player pauses (if the video is paused) or don't start it (if the video is over)

**Comment by justanidea** [comment] 2018-08-12 10:36
Another unexpected behavior : when answering a call, the video you watch switches in background and continues playing during the call

**Comment by theScrabi** [comment] 2018-08-31 00:48
Whut ... Thats anoying.

**Comment by jooooop** [comment] 2019-01-28 10:43
Just adding my 2¢ by saying it does it for me if I pause the video, and once my phone automatically locks after no activity the video resumes in a pop-up

**Comment by shtrom** [comment] 2019-09-16 10:42
Is this a dupe of #2395?

**Comment by Stypox** [comment] 2019-09-29 14:04
Closing in favour of #2391

**Closed by Stypox** 2019-09-29 14:04 UTC
Labels: bug, player
