### ISSUE TITLE
[Request] Use interest based cookies to personalize Trending Page

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2846] opened 2019-12-07 00:36 UTC
What if NewPipe could store user chosen, interest based cookies in the app in order to provide a more personalized experience

I'm imagining using cookies in the same way that YouTube uses them when you're logged out, except with more user control, and less automated tracking

This could allow the 'Trending' page to be much more relevant and useful to the individual using the app, without completely compromising privacy.

**Comment by Stypox** [comment] 2019-12-09 19:52
Unless there is a way to build a cute interface where the user chooses which content he wants, I don't know if this would be a good idea, since most people have no idea how to manipulate cookies.

**Comment by Gymcap** [comment] 2019-12-12 05:52
I unfortunately can't build any interface as I'm without a computer. 

I think a good place to start would be to add an option to implement your subscribed channels into your cookie. 

If the idea is taken well, there could eventually be a searchable "topic list" where users can choose from a list of known interest cookies.

**Comment by B0pol** [comment] 2020-05-10 17:52
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2256

**Closed by B0pol** 2020-05-10 17:52 UTC
Labels: enhancement, youtube
