### ISSUE TITLE
Newpipe video playing issue

### ISSUE THREAD

**Issue by Sachin9600** [TeamNewPipe/NewPipe#3474] opened 2020-04-23 09:31 UTC
Sir so many times when we click on any video play botton it will not start playing video while it consuming too much mobile data but video can't play,and after we go back and click to play again it start playing... this type of issues is here in newpipe app 19.2version...kindly fix it as soon as possible.
And one more request is that please make this app for laptop compatible also.thanks in advance

**Comment by Stypox** [comment] 2020-04-23 12:35
*Please **follow the issue template** when creating an issue, don't just delete everything!*
Duplicate of #1051 and #2415

**Closed by Stypox** 2020-04-23 12:35 UTC
