### ISSUE TITLE
"Default Content Country" doesn't really change the search

### ISSUE THREAD

**Issue by DNDEBUG** [TeamNewPipe/NewPipe#8479] opened 2022-06-04 01:40 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1: Open App
2: Search Stuff
3: Day ruined

### Expected behavior

search stuff and only see results from the "Defaulty content country"

### Actual behavior

Searching stuff gives me results from my own country

### Affected Android/Custom ROM version

/e/ 0.23 and 1.0

### Additional information

idk

**Comment by litetex** [comment] 2022-06-19 14:49
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2251

**Closed by litetex** 2022-06-19 14:49 UTC
Labels: bug, youtube

**Comment by opusforlife2** [comment] 2022-06-19 22:52
@DNDEBUG Changing that setting only affects the Trending kiosk. So it's not a bug.

@litetex Does the search filter on Youtube include a country filter?

**Comment by litetex** [comment] 2022-06-21 20:35
@opusforlife2 

No I guess but if the platform doesn't provides one we can't do anything...

See also https://github.com/TeamNewPipe/NewPipe/issues/8523

**Comment by opusforlife2** [comment] 2022-06-25 21:11
I asked because I didn't understand why you marked this as a duplicate of the search filter request. And from your answer, it seems like the wrong issue.

**Comment by alittlebitofit** [comment] 2022-06-26 18:32
If the search results are from the same country (regardless of the Settings), does that mean YouTube still knows it's me despite using NewPipe?
