### ISSUE TITLE
[Feature Request] Implement Cache Mode

### ISSUE THREAD

**Issue by keksimusmaximus** [TeamNewPipe/NewPipe#2775] opened 2019-11-03 11:00 UTC
Hi @all,

it would be very convenient if Newpipe had a cache mode. I.E. if the video starts, it is cached (depending on settings) and after it's completely cached it's possible to play it without any network access.

Background is, that in rural areas the mobile connection is often bad/not available so caching within the app would be very useful. The current way of downloading and playing it with an external program is just a big overhead to the users (IMHO).

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [No Need?] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by Stypox** [comment] 2019-11-03 13:58
Duplicate of #1179 #155

**Closed by Stypox** 2019-11-03 13:58 UTC
