### ISSUE TITLE
Automaticly update the content when NewPipe starts

### ISSUE THREAD

**Issue by Grkrz** [TeamNewPipe/NewPipe#8758] opened 2022-08-11 20:57 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Is it possible to make the app update the content automatically when open, and so it scrolls to the top like yt does?

### Why do you want this feature?

Ease of use and time saving since I do it every time I open the app.

**Comment by opusforlife2** [comment] 2022-08-12 18:47
> make the app feed the content automatically when opening it

You mean update it?

**Comment by Grkrz** [comment] 2022-08-18 18:08
Yes ,exactly

**Comment by opusforlife2** [comment] 2022-08-19 19:46
Then please state that clearly in your title and description.

**Comment by Grkrz** [comment] 2022-08-19 20:18
Done, Hopefully this time is done correctly.
Thank you for doing great job.

**Comment by SameenAhnaf** [comment] 2022-08-24 06:16
Aren't you asking for https://github.com/TeamNewPipe/NewPipe/issues/4967?

**Comment by opusforlife2** [comment] 2022-08-25 17:26
Ah, indeed. Thanks. Duplicate of #4967.

**Closed by opusforlife2** 2022-08-25 17:26 UTC
Labels: enhancement, feed
