### ISSUE TITLE
Accessibility: Unsigned buttons

### ISSUE THREAD

**Issue by bmivzkrp** [TeamNewPipe/NewPipe#7572] opened 2021-12-23 18:04 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

When I focus on each of these buttons, I hear the word Button. The situation gets a little better, when in the screen reader settings I enable the ability to declare the IDs of unsigned objects, I hear the following names:

control repeat
control backward
control fast rewind
control play pause
control fast forward
control forward
control shuffle

I suspect that the reason is the following: there is no Content Description for these elements.

### Expected behavior

I hear the real names of these buttons, without any screen reader settings.

### Device info

 - Android version/Custom ROM version:

6.0 

 - Device model:

Impression ImSmart-C551

**Comment by bmivzkrp** [comment] 2021-12-23 19:56
I found two more unsigned buttons. After the start of playback, in the lower right corner of the screen, there are two buttons. Jieshuo tells me the following:

overlay play pause button

overlay close button

Also, in the tab settings, I noticed an unsigned button:

addTabsButton

And yet: this does not apply to this topic, just no longer have the strength to create another issue: the player has an element that the screen reader calls:

1x

Maybe it should be called something else, because not every user will immediately understand what it is. Or provide some contextual hint.

**Comment by SameenAhnaf** [comment] 2021-12-24 05:44
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4303

**Comment by bmivzkrp** [comment] 2021-12-24 09:54
@SameenAhnaf Sorry, I didn t want to create duplicates. Yesterday I searched for the keyword accessibility, and did not find any issue. I sincerely apologize for that.

In the notification settings, Jieshuo sees a button:

notificationActionClickableArea

**Comment by litetex** [comment] 2021-12-24 20:40
Duplicate of #4303

**Closed by litetex** 2021-12-24 20:40 UTC
Labels: bug

**Comment by bmivzkrp** [comment] 2021-12-31 15:40
Regarding "overlay play pause button": if possible, it would be great if the behavior was as follows:
1. During playback, this button is called "Pause".
2. During the pause, the button is called "Play".
The same goes for the player.
In general, in such cases, it would be ideal if the controls change the name, depending on the state.
