### ISSUE TITLE
ERROR_CODE_DECODER_INIT_FAILED

### ISSUE THREAD

**Issue by kkmehta03** [TeamNewPipe/NewPipe#8485] opened 2022-06-06 05:11 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. search for video [Link here](https://www.youtube.com/watch?v=5mpq_4rzB1U)
2. click on open with NewPipe
3. error displays

### Expected behavior

video to be played 

### Actual behavior

error

### Logs

```
{
  "user_action": "play stream",
  "request": "Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=5mpq_4rzB1U",
  "content_language": "en-US",
  "content_country": "US",
  "app_language": "en_US",
  "service": "YouTube",
  "package": "org.schabi.newpipe",
  "version": "0.23.0",
  "os": "Linux Android 8.1.0 - 27",
  "time": "2022-06-06 10:17",
  "exceptions": [
    "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D401F, -1, null, [1280, 720, -1.0], [-1, -1]), format_supported=YES\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:192)\n\tat android.os.HandlerThread.run(HandlerThread.java:65)\nCaused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.4D401F, -1, null, [1280, 720, -1.0], [-1, -1])\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1017)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1437)\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:799)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:950)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)\n\t... 3 more\nCaused by: android.media.MediaCodec$CodecException: Error 0xffffffed\n\tat android.media.MediaCodec.native_configure(Native Method)\n\tat android.media.MediaCodec.configure(MediaCodec.java:1943)\n\tat android.media.MediaCodec.configure(MediaCodec.java:1872)\n\tat com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)\n\tat com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:130)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1095)\n\tat com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1006)\n\t... 10 more\n"
  ],
  "user_comment": ""
}
```

### Affected Android/Custom ROM version

Linux Android 8.1.0 - 27

**Comment by litetex** [comment] 2022-06-19 14:39
Duplicate of #8485

**Closed by litetex** 2022-06-19 14:39 UTC
Labels: bug
