### ISSUE TITLE
Back button does not lead to the previous view

### ISSUE THREAD

**Issue by Fassi96** [TeamNewPipe/NewPipe#7364] opened 2021-11-04 19:03 UTC
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Select a video and play it
2. Select another video and play it (it doesn't matter which way)
3. Select another video and play it (it doesn't matter which way)
4. If you now use the back button (from the mobile phone) you do not come back to the previous view (e.g. subscriptions) but to the previous video.

### Actual behavior

When you use the back button (from the mobile phone) you do not come back to the previous view (e.g. subscriptions) but to the previous video. You have to press the back button as often as you have seen videos to get back to the previous view. This is a disaster, especially on a FireTV stick

### Expected behavior

You should come back to the previous view (e.g. subscriptions).

### Screenshots/Screen recordings

Link to Video: https://netherghast-my.sharepoint.com/:v:/g/personal/matthias_hanisch_netherghast_de/EVzOm5GglxdHocxA4mvN_ssBnK6rYS32zrIKRS0rTtbMyQ?e=5idSYA

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Samsung Galaxy Note20 Ultra 5G (SM-N986B/DS)

**Comment by skyGtm** [comment] 2021-11-05 05:43
Check the APK in #6895
You can change the behavior of back button via settings

**Comment by mhmdanas** [comment] 2021-11-05 12:08
Duplicate of #4479.

**Closed by mhmdanas** 2021-11-05 12:08 UTC
Labels: bug
