### ISSUE TITLE
NewPipe WebM stuttering where as MPEG-4 doesn't at 30FPS.

### ISSUE THREAD

**Issue by vgturtle127** [TeamNewPipe/NewPipe#1298] opened 2018-04-10 03:10 UTC
Hey, I'm using NewPipe 0.13.1.

So on this video:

https://www.youtube.com/watch?v=vwx83kfch1Y

The WebM at 720p60 always stutters and drops frames, whereas the 720p30 MPEG-4 runs fine at half the framerate. On other videos, MPEG-4 720p60 runs fine as well.

Is this a codec issue, or is there some discrepancy between files stored on the YouTube servers, or what's happening here?

If I can do anything to help, such as include logs or anything I will do what I can. I only have one rooted device.

**Comment by karyogamy** [comment] 2018-04-10 03:46
Can you please provide us with the device specs? The video seems to play without any stutter on my phone.

**Comment by Duppadaadadii** [comment] 2018-04-10 10:27
I have Oneplus One, LineageOs, Boefflakernel.
It stutters here too. WebM has stuttered on my device with every video.

**Comment by theScrabi** [comment] 2018-04-10 21:41
I remember that some older devices are not able to hardware decode webm, however even the older ones should do mpeg4 just fine. So oneplus one has a lot of power tho but still I would take this as an explenation. @karyogamy what do you thing?

If it turns out its the LOS software decoder for webm there is not much we can do. You might have to go with mpeg4 then :/

**Comment by mauriciocolli** [comment] 2018-04-10 22:28
Duplicate of #597

**Closed by mauriciocolli** 2018-04-10 22:28 UTC

**Comment by vgturtle127** [comment] 2018-04-10 22:44
@mauriciocolli Does this mean the issue won't be fixed due to issues with WebM as a codec?

**Comment by theScrabi** [comment] 2018-04-11 16:15
Well first of all this seems to be a problem at exoplayer. Seh here https://github.com/google/ExoPlayer/issues/2777
So they had to address that issue. Maybe the next updates of exoplayer will fix it.

**Comment by vgturtle127** [comment] 2018-04-11 20:59
@theScrabi Oh, so it's more of an internal YouTube issue?

**Comment by mauriciocolli** [comment] 2018-04-11 21:48
@vgturtle127 I don't think there's much else we can do besides warning about the player not able to decode the video in real time, which is the idea already mentioned in the the referenced issue.

> so it's more of an internal YouTube issue?

I highly doubt it, most probably client side issue.

The A6 [doesn't have](https://www.qualcomm.com/products/snapdragon/processors/410) VP* hardware decoding so it is expected, but it's a little strange that it does that in your S7, the [Exynos 8 8890](http://www.samsung.com/semiconductor/minisite/exynos/products/mobileprocessor/exynos-8-octa-8890/#specs) does have VP9 hardware decoding support... Or your phone has another processor?

> @theScrabi  Well first of all this seems to be a problem at exoplayer. Seh here google.ExoPlayer#2777

That's not the issue here. At least he didn't tell us about altering the playback speed.

**Comment by vgturtle127** [comment] 2018-04-11 23:53
@theScrabi I didn't change the playback speed, though? 🤷‍♂️ 

@mauriciocolli My processor is a Qualcomm Snapdragon 820 CPU with an Adreno 530 GPU. My phone model is the Samsung Galaxy S7 SM-G930V. I have the latest Android version and all my apps are up to date, so I don't think it's any sort of bug.

**Comment by mauriciocolli** [comment] 2018-04-12 01:29
@vgturtle127 So yeah, this is sort of expected, the [Snapdragon 820](https://www.qualcomm.com/products/snapdragon/processors/820) doesn't list VP* support, but it's still strange that it can't handle even 720@60F (and can easily handle 4K in another codec, but who knows, hardware support can improve decoding by _a lot_).

As a test, can you download a WebM 720@60 stream in NewPipe and then try to play it with MX Player and VLC? That might give some better insight.

**Comment by karyogamy** [comment] 2018-04-12 01:44
Got my hands on an Exynos version of S7 to test this and the video ran just fine, maybe a stutter after seeking but that's about it. So, it's most likely that vp9 exceeds snapdragon 820's capability, even though I saw [this](https://twitter.com/qualcomm/status/665321749010063360?lang=en).

**Comment by vgturtle127** [comment] 2018-04-12 02:33
@mauriciocolli I looked through about 15 pages of 720p60 videos and none of them had WebM 720p60. 😞 

Do you know where I could download some so I don't have to download the entire 2 and a half hour video on my phone?

@karyogamy Huh, I don't know.

**Comment by mauriciocolli** [comment] 2018-04-12 02:49
@vgturtle127 change the "Default Video Format" to WebM, then just search "60fps" on YouTube, any video will do, but test to see if it stutters in NewPipe first.

**Comment by vgturtle127** [comment] 2018-04-12 04:09
@mauriciocolli Alright, so downloaded and streamed videos play fine when it is a WebM at 720p60, VLC works fine, mpv works fine, and MX Player work fine. It must just be that specific video...
