### ISSUE TITLE
''Limit download queue'' option doesn't work as intended

### ISSUE THREAD

**Issue by nadiration** [TeamNewPipe/NewPipe#5408] opened 2021-01-14 10:57 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Settings > Download > Limit download queue

### Actual behaviour

When you toggle the option  Limit download queue on Settings, it was supposed to limit the parallel downloads to 'one download at a time' but all the downloads start simultaneously. Sometimes it works and queues other downloads but 90% of the time it doesn't work.

### Expected behavior

The option as it's name implies was supposed to limit the download queue to one at a time.

### Device info

 - Device independent. Tried on multiple devices.

**Comment by tsiflimagas** [comment] 2022-11-08 13:04
Seems like a duplicate of #4215.

**Comment by opusforlife2** [comment] 2022-11-09 13:07
Check if your issue is occurring due to the same steps mentioned in 4215 or something else.

**Closed** 2022-11-24 00:14 UTC
Labels: bug, downloader, waiting for author
