### ISSUE TITLE
Please add subtitle support. 

### ISSUE THREAD

**Issue by aFoxWhoIsNice** [TeamNewPipe/NewPipe#1121] opened 2018-02-18 07:05 UTC
Hi, I really like using your app. But could you please add subtitle support? Many videos do have subtitles, and they're rather handy at times. Thanks.

**Comment by mauriciocolli** [comment] 2018-02-18 07:28
Duplicate of #55
See #1067

**Closed by mauriciocolli** 2018-02-18 07:28 UTC
Labels: duplicate
