### ISSUE TITLE
Not able to load videos 

### ISSUE THREAD

**Issue by Ryderpenner** [TeamNewPipe/NewPipe#8203] opened 2022-04-15 00:28 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Any video
Click it
Error can't load 

### Expected behavior

Video won't load

### Actual behavior

Video failed to load

### Screenshots/Screen recordings

> 

> `
<img alt="Screenshot_20220414-192304_NewPipe" src="https://user-images.githubusercontent.com/103704204/163496989-8e90308f-fe8a-4e4a-8363-6b5ee0f62239.jpg" height=600 />
`

### Logs

everything is not working ## Exception * __User Action:__ requested stream * __Request:__ https://www.youtube.com/watch?v=6nxrllqnP2Q * __Content Country:__ CA * __Content Language:__ en-CA * __App Language:__ en_CA * __Service:__ YouTube * __Version:__ 0.22.1 * __OS:__ Linux samsung/starqltecs/starqltecs:10/QP1A.190711.020/G960WVLU9FUH1:user/release-keys 10 - 29 Crash log 

``` org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details. 	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194) 	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72) 	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64) 	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116) 	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0) 	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4) 	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43) 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813) 	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35) 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813) 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41) 	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330) 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153) 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78) 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66) 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42) 	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868) 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36) 	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330) 	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46) 	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813) 	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644) 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:919) ``` 

### Affected device model

S9

**Comment by CaidenBlock** [comment] 2022-04-15 00:30
Duplicate of #8202

**Comment by itsme24082004** [comment] 2022-04-15 01:01
I too having this problem from this morning

**Comment by unnavailable** [comment] 2022-04-15 01:14
I have the same problem.

**Comment by Abdel-ilah** [comment] 2022-04-15 01:15
I can confirm, no videos loading

**Comment by ByYapmaz** [comment] 2022-04-15 01:16
> 

Aynı sorun bende'de mevcut sorunun çözümünü bilen varsa yazsın lütfen

**Comment by xgngrizzlyy1** [comment] 2022-04-15 01:39
I have the same issue also.

**Comment by PandoraHayami** [comment] 2022-04-15 02:38
This happened the last time, and the devs said it before, give actual useful info, don't open new issues and, if possible, give logs, not for OP, for everyone else reading.

**Comment by TacoTheDank** [comment] 2022-04-15 02:45
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/8202

**Closed by TacoTheDank** 2022-04-15 02:45 UTC
Labels: bug

**Comment by TacoTheDank** [comment] 2022-04-15 03:55
I'll give the creator of this issue the benefit of the doubt, as it was made only two minutes after the first issue.
