### ISSUE TITLE
Interchange playlist button with chapters button

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#6772] opened 2021-07-26 22:11 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it

the playlist button should be interchanged with the chapters button because if I am watching a video in a playlist which doesn't have chapters, it will have playlist button on the right, next to arrow and if it has chapters, playlist button gets pushed to the left, causing me to click on the chapter button

what I'm asking for is to keep playlist button on the right, consistently as this is causing issues in videos with chapters

#### Additional context

a ss of video without chapters
![Screenshot_20210727-032751_NewPipe](https://user-images.githubusercontent.com/84063610/127065632-e7b37ec5-a803-4d93-9a2d-264e0cf0613b.jpg)

a ss of video with chapters causing playlist button to be pushed away, causing misclicks
![Screenshot_20210727-032408_NewPipe](https://user-images.githubusercontent.com/84063610/127065687-8e567d4f-2bf6-4602-8704-ded95780aa2f.jpg)

**Comment by SameenAhnaf** [comment] 2021-07-27 02:05
Duplicate of #6197.

**Closed** 2021-07-27 17:21 UTC
Labels: enhancement
