### ISSUE TITLE
Put a reminder when the video will release or when it is supposed to arrive instead of content not availabe.

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#5774] opened 2021-03-06 15:51 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think it would be okay if you could make changes to this video which is like a previewed video which has a timer. Like a time ticking until it is previewed or anything. Just not content not available
![2beb6939-b20b-4230-a604-62fdc2ff7f7a](https://user-images.githubusercontent.com/74511929/110212364-1236fb80-7eac-11eb-9adc-db0fa680702c.jpg)

Maybe just say video will be availabe. I mean it's not as informative but it will do

#### Additional context

![10cbec15-37c6-45de-af4c-3180b72c9fed](https://user-images.githubusercontent.com/74511929/110212521-bf117880-7eac-11eb-9e9b-46366d67123e.jpg)
https://www.youtube.com/watch?v=eDKUamxUhwM

#### How will you/everyone benefit from this feature?

It will help people who clicked on the video know it hasn't been aired yet or hasn't been uploaded yet. And also let them kknow how long it will take for the video to release.

**Comment by AudricV** [comment] 2024-02-16 13:10
> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

Duplicate of #5192. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-02-16 13:10 UTC
Labels: feature request
