### ISSUE TITLE
ability to filter subscription list by source/account

### ISSUE THREAD

**Issue by khimaros** [TeamNewPipe/NewPipe#5809] opened 2021-03-11 17:30 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

when viewing the subscription list, i would like to be able to limit the list of subscriptions to eg. YouTube or SoundCloud.

#### Is your feature request related to a problem? Please describe it

because i have imported a large list of subscriptions from both YouTube and SoundCloud, it is difficult to differentiate between video and non-video content.

#### Additional context

initially, i expected the "source" selection from the hamburger menu to switch between these worlds. i see a benefit to a combined feed, but at times it is also helpful to be able to view just one source.

#### How will you/everyone benefit from this feature?

it would be easier to manage subscriptions when using NewPipe with multiple input sources.

**Comment by khimaros** [comment] 2021-03-11 17:56
quick code dive indicates this might require a bit of plumbing. the good news is that the `serviceId` seems to be stored in the database on import. `SubscriptionDAO` has a `listByService` method, but it doesn't seem to be used. 

https://github.com/TeamNewPipe/NewPipe/blob/29376066e8f4d71a851dadd7e7b99ca2357e350f/app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionDAO.kt#L18

**Comment by litetex** [comment] 2021-11-10 19:48
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5960#issuecomment-912994831

**Closed by litetex** 2021-11-10 19:48 UTC
Labels: enhancement, feed
