### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Barmarel** [TeamNewPipe/NewPipe#5536] opened 2021-02-06 22:19 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
It will be very good if it will be possible to set a playback timer, after which the video playback will be stopped.

#### Is your feature request related to a problem? Please describe it
--

#### Additional context
--

#### How will you/everyone benefit from this feature?
I often include videos to help me sleep.  Or listening to audiobooks before bed.  But these recordings last for a long time.  That is why there was a need to be able to set a timer.

**Comment by mhmdanas** [comment] 2021-02-07 13:06
I believe this is a duplicate of #2830. If I misunderstood, feel free to write a comment.

**Closed by mhmdanas** 2021-02-07 13:06 UTC
Labels: enhancement
