### ISSUE TITLE
translation is work when change app into different language.

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#2887] opened 2019-12-22 08:32 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
translation is work when change app into different language. Like Hindi, chines etc.

**Comment by Stypox** [comment] 2019-12-22 18:51
Could you please rephrase? I don't understand, sorry

**Comment by rahuldeshwal21** [comment] 2019-12-25 12:37
> Could you please explain further? I don't understand, sorry
Let's  explain  I English is my  second language I try  App work language change in 
Hindi (Indian language)  
Home >Setting > content >Default content Language > Select Hindi {Or more language} > done 
#So app Language not change what'S The problem???

**Comment by Stypox** [comment] 2019-12-26 10:26
That switch changes the content language, not the app language. To change the app language you have to change the system language.

**Comment by arielshulman** [comment] 2020-01-01 08:20
That was not the usage earlier.
I'd preffer the language of the app would be English (as it was till last upgrade) even though my system language is Hebrew.

**Comment by Stypox** [comment] 2020-01-13 18:52
Duplicate of #2794

**Closed by Stypox** 2020-01-13 18:52 UTC
Labels: localisation / translation, question
