### ISSUE TITLE
Offline search subscribers channels names

### ISSUE THREAD

**Issue by Github-com-foss** [TeamNewPipe/NewPipe#6485] opened 2021-06-14 14:43 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Pls provide an option for offline search subcriptions channel names. It helps to show subcription channel without internet, if i click the channel then connect to internet.

#### Is your feature request related to a problem? Please describe it
No

#### Additional context
No

#### How will you/everyone benefit from this feature?
Yes

**Comment by mhmdanas** [comment] 2021-06-14 20:11
Duplicate of #4795. Also, please follow the template properly when you open an issue. Thanks!

**Closed by mhmdanas** 2021-06-14 20:11 UTC
Labels: enhancement, user-ignored-template-instructions
