### ISSUE TITLE
Feeds are always outdated

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [TeamNewPipe/NewPipe#3696] opened 2020-05-31 06:57 UTC
### Version

-
19.05
### Steps to reproduce the bug

1. Go to settings,content and set feed threshold to always update
2. Do not enable fetch from dedicated fieldd
3. Restart the app

### Expected behavior

Feed should be updated after restart
### Actual behaviour

Feeds do not get updated

**Comment by B0pol** [comment] 2020-05-31 10:31
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3329

Always update means you can always press the refresh button, not it will do it automatically.

**Closed by B0pol** 2020-05-31 10:31 UTC
Labels: bug

**Comment by Ashutosh-Kukreti** [comment] 2020-05-31 11:54
This issue was not present in old version with old layout , feeds used to get updated automatically on startup,Why did you guys removed that feature? :(
