### ISSUE TITLE
Stream bitrate option for live streaming

### ISSUE THREAD

**Issue by pedro1977uk** [TeamNewPipe/NewPipe#8833] opened 2022-08-18 14:02 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When live streaming, it doesn't let you select the resolution and the global settings aren't enforced. It seems to go to highest resolution and consume large amounts of data. i.e. sky news live.

### Why do you want this feature?

Saves data and provides flexibility.

**Comment by AudricV** [comment] 2022-08-18 14:11
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #1239. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2022-08-18 14:11 UTC
Labels: enhancement, needs triage

**Comment by pedro1977uk** [comment] 2022-08-18 14:14
Sorry, thanks for the reference. I see this has been a problem for some years.
