### ISSUE TITLE
Onlongclick, got a nullpointer crash

### ISSUE THREAD

**Issue by zxfish** [TeamNewPipe/NewPipe#7424] opened 2021-11-19 17:00 UTC
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Swipe to my subscription. 
2. click into lasted updated video, open one, when it load slowly, close wifi.
3.  long touched upper position of screen.
4.  back to last fragment, long click any video, crash.

### Actual behavior

Crash 

### Expected behavior

  crash

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CN
* __Content Language:__ zh-CN
* __App Language:__ zh_CN
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.size()' on a null object reference
	at org.schabi.newpipe.player.helper.PlayerHolder.getQueueSize(PlayerHolder.java:74)
	at org.schabi.newpipe.local.feed.FeedFragment.showStreamDialog(FeedFragment.kt:331)
	at org.schabi.newpipe.local.feed.FeedFragment.access$showStreamDialog(FeedFragment.kt:80)
	at org.schabi.newpipe.local.feed.FeedFragment$listenerStreamItem$1.onItemLongClick(FeedFragment.kt:390)
	at com.xwray.groupie.GroupieViewHolder$2.onLongClick(GroupieViewHolder.java:32)
	at android.view.View.performLongClickInternal(View.java:6340)
	at android.view.View.performLongClick(View.java:6298)
	at android.view.View.performLongClick(View.java:6316)
	at android.view.View$CheckForLongPress.run(View.java:24694)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:android 8.0.0
 - Device model: sharp ,fs8010

**Comment by litetex** [comment] 2021-11-30 18:24
Duplicate of #7305.
You may give that issue an upvote 😉

**Closed by litetex** 2021-11-30 18:24 UTC
Labels: bug

**Comment by Stypox** [comment] 2022-01-25 16:44
Could you test if #7704 solves the issue?
