### ISSUE TITLE
NewPipe 

### ISSUE THREAD

**Issue by NewPipeUser2** [TeamNewPipe/NewPipe#7101] opened 2021-09-13 03:20 UTC
I would recommend adding a mp3 and mp4 option because most apps only support mp3 and mp4. 

-PLEASE ADD

**Comment by SameenAhnaf** [comment] 2021-09-13 03:27
Duplicate of #507. Please fill in the template properly and avoid reopening issues.

**Closed** 2021-09-13 04:45 UTC
Labels: enhancement
