### ISSUE TITLE
Brightness gesture default setting: please disable

### ISSUE THREAD

**Issue by dilbech** [TeamNewPipe/NewPipe#5489] opened 2021-01-25 19:11 UTC
### Checklist

- [x] I am using the latest version -v0.20.8
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Too many phones due the other bugs listed in the issue tracker do not restore to proper original brightness
2. Or users slide gesture and increase it by mistake - causing battery drain.

### Actual behaviour

Ideally everyone using phone knows to increase brightness by slider (from notification). 

### Expected behavior

Please change the default brightness gesture setting to OFF

### Device info

 - Android version/Custom ROM version: Lineage 17.1
 - Device model: Pixel 2L

**Comment by vkay94** [comment] 2021-01-25 20:23
Regarding 1: I searched, but couldn't find such issues in the tracker. You're referring to other users, but do you face this issue on your device, too? (For me, I couldn't reproduce it (auto brightness disabled or enabled - the brightness changes to its normal value after leaving full screen))

If it's a personal preference, you can just disable it in the settings.

**Comment by mhmdanas** [comment] 2021-01-26 05:34
I agree with disabling it by default, but I want to point this out:

> Ideally everyone using phone knows to increase brightness by slider (from notification).

The gesture is there so that we _won't_ have to open that thing when we're in the middle of a video.

Also, you're using the bug report template, but you should be using the feature request template in this case, as this is not a bug. I won't close this issue, but please choose the correct template next time.

**Comment by nadiration** [comment] 2021-01-26 07:14
The brightness gesture is godsend why would anyone want to disable it 🤔

**Comment by urlordjames** [comment] 2021-01-26 20:13
1: This should be resolved when 20.9 releases. (duplicate of #4481 resolved in #5283)
2: duplicate of #3713

**Comment by mhmdanas** [comment] 2021-01-27 17:19
@urlordjames indeed you are right. @dilbech you can comment on #3713 to voice your opinion about this.

**Closed by mhmdanas** 2021-01-27 17:19 UTC
Labels: bug
