### ISSUE TITLE
Playlist are not shown on youtube's user profiel

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#5037] opened 2020-11-30 04:41 UTC
### Checklist

- [x] I am using the latest version - 0.20.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open https://www.youtube.com/user/beardyman/playlists

### Actual behaviour

Not playlists are shown

### Expected behavior

Playlists are shown

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/14617699/100569523-60ea5d80-32df-11eb-8e19-dc4cf1079e7c.png)

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment] 2020-11-30 05:02
Duplicate of #2414.

**Closed by mhmdanas** 2020-11-30 05:02 UTC
Labels: bug
