### ISSUE TITLE
Video plays in a completely different language

### ISSUE THREAD

**Issue by Palocay** [TeamNewPipe/NewPipe#8936] opened 2022-09-06 06:46 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Open the following Video in Newpipe: [MrBeast - World’s Most Dangerous Escape Room!](https://www.youtube.com/watch?v=3jS_yEK8qVI)

### Expected behavior

I expected the video to play in English. 

### Actual behavior

The video somehow plays in a completely different language. I also explicitly set my system language to:

- German (since I am from Germany)
- English (US)
- English (UK)

but this has no effect either. Playing the exact same video on Youtube will result in the video playing in English.

### Affected Android/Custom ROM version

Android 12

### Affected device model

OnePlus 9 Pro

**Comment by opusforlife2** [comment] 2022-09-07 20:38
> The video somehow plays in a completely different language

Arabic. xD

**Comment by opusforlife2** [comment] 2022-09-07 20:46
Duplicate of #5854

**Closed** 2022-09-07 20:47 UTC
Labels: bug, player
