### ISSUE TITLE
Video format by switching to landscape

### ISSUE THREAD

**Issue by gotmails** [TeamNewPipe/NewPipe#7806] opened 2022-02-04 13:44 UTC
Hello,

First of all, thank you for your great work.
Small bug on my Pixel P5.

Sometimes (about 50% of the time), when I turn my phone to switch to full screen, the video size is much smaller. 
I'd like to point out that if I switch back to portrait mode and then back to landscape, the format can be correct.

See image below.
Pixel 5
ROM: GraphenOS (Android 12).
NewPipe: Latest version (0.21.16)

![Screenshot_20220201-135612](https://user-images.githubusercontent.com/56850764/152539111-db6f2926-07a5-494c-baf2-29c267ff8044.png)

![Screenshot_20220201-135641](https://user-images.githubusercontent.com/56850764/152539143-8be81adf-f939-4e09-bf35-3c9bc3dd6294.png)

**Comment by jbwpt** [comment] 2022-02-04 22:13
Is your NewPipe working normally? I keep getting a "Could not parse website" error.

**Comment by mhmdanas** [comment] 2022-02-04 22:49
@jbwpt update to 0.21.16.

**Comment by mhmdanas** [comment] 2022-02-04 22:54
Duplicate of #7262.

**Closed by mhmdanas** 2022-02-04 22:54 UTC

**Comment by jbwpt** [comment] 2022-02-04 23:09
> @jbwpt update to 0.21.16.

I am up to date and still getting the "Could not parse website" error.

**Comment by mhmdanas** [comment] 2022-02-04 23:14
You're probably using the official F-Droid repo, which still doesn't have 0.21.16. You can wait a little more for it to get the update, or you can [switch to our custom repo](https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/), keeping in mind to export your database before uninstalling NewPipe, or you will lose your NewPipe data.
