### ISSUE TITLE
Video scale

### ISSUE THREAD

**Issue by IErnest134** [TeamNewPipe/NewPipe#7902] opened 2022-02-19 14:38 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Add video zoom feature

Not enlarged ▼
![изображение_viber_2022-02-19_16-25-32-567](https://user-images.githubusercontent.com/99507421/154805254-2c4a26c6-5dfe-4938-b3f0-4d3c6212050e.jpg)

With increasing ▼
![изображение_viber_2022-02-19_16-25-32-649](https://user-images.githubusercontent.com/99507421/154805259-0510e257-989c-4a69-a1e8-29ce2e0ee9e6.jpg)

### Why do you want this feature?

I need this function so that black edges are not visible and it is more convenient to watch videos.

**Comment by SameenAhnaf** [comment] 2022-02-19 14:45
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7179

**Comment by mujibultanim** [comment] 2022-02-19 18:45
It will be great if the app include sleep timer feature. That would help people to listen audio.

**Closed** 2022-02-21 19:26 UTC
Labels: enhancement
