### ISSUE TITLE
Search favorites

### ISSUE THREAD

**Issue by gcoimbra** [TeamNewPipe/NewPipe#7099] opened 2021-09-12 23:23 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I want to search my playlists/favorite playlists. 

Optionally, also describe alternatives you've considered.
I don't think there's an viable alternative to this.

#### Is your feature request related to a problem? Please describe it

No.

#### Additional context

I want to find a video by title or maybe description that I've added to my playlists. Maybe we can search through all playlists or one-by-one. 

#### How will you/everyone benefit from this feature?

I think many of us have many videos in the playlists and we need to go through them one-by-one.

**Comment by SameenAhnaf** [comment] 2021-09-13 02:55
Duplicate of #3037.

**Closed** 2021-09-13 11:11 UTC
Labels: enhancement
