### ISSUE TITLE
the app is crashing when typing in the search area

### ISSUE THREAD

**Issue by harun53aydin** [TeamNewPipe/NewPipe#6779] opened 2021-07-27 12:31 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ TR
* __Content Language:__ tr
* __App Language:__ tr
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux samsung/r7naxx/r7:11/RP1A.200720.012/N770FXXU7EUE2:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.RelativeLayout org.schabi.newpipe.databinding.PlaylistHeaderBinding.getRoot()' on a null object reference
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:285)
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:66)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0(BaseListInfoFragment.java:146)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0$BaseListInfoFragment(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.-$$Lambda$BaseListInfoFragment$Gn1fP3-8OJnktT5gkmUmbW-egTg.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

**Comment by botistreamer** [comment] 2021-07-27 14:21
I think this a duplicate of #6231.

**Comment by litetex** [comment] 2021-07-27 17:12
> I think this a duplicate of #6231 
Thank you for the hint.

Stacktrace is (nearly) identical so I think this is very likely one.

@harun53aydin 
If you have additional useful information please post it as a comment under #6231. You can also up-vote #6231 

For now I am closing this issue as
Duplicate of #6231

**Closed by litetex** 2021-07-27 17:12 UTC
Labels: bug
