### ISSUE TITLE
Play queue within app

### ISSUE THREAD

**Issue by osshelper** [TeamNewPipe/NewPipe#8430] opened 2022-05-22 18:04 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The play queue should be available directly within app.

### Why do you want this feature?

Currently, play queue is accessible from the notification, it is a big UX problem according to me.

**Comment by SameenAhnaf** [comment] 2022-05-22 19:41
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3515

**Closed** 2022-05-23 17:16 UTC
Labels: enhancement
