### ISSUE TITLE
Missing videos in YT  channel

### ISSUE THREAD

**Issue by jediafr** [TeamNewPipe/NewPipe#2650] opened 2019-09-19 05:42 UTC
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi,

Newspipe 17.3 is a great Great app that freed me from google and i've detected an issue with a french channel that has more than 30 videos but in Newspipe i can only see 4 of them in the subscribed channel.(could be a accent issue as it is french so a lot of  : ' éàè).
here is the URL : https://www.youtube.com/channel/UCcF_lt5AbYnvfHOlibVb_-A

**Comment by jediafr** [comment] 2019-09-19 05:44
Never mind, i've found the answer... the videos are blocked and unavailable.
good to know NP is filtering those pesky unvailable videos !

**Comment by Stypox** [comment] 2019-09-19 05:47
This is a duplicate of #1066 I think

**Closed** 2019-10-03 05:23 UTC
