### ISSUE TITLE
Add support for Invidious, an alternative privacy-respecting YouTube front-end.

### ISSUE THREAD

**Issue by perrsona1234** [TeamNewPipe/NewPipe#3748] opened 2020-06-05 16:38 UTC
#### Describe the feature you want

It would be nice for NewPipe to support Invidious front-end for YouTube and sharing YouTube links converted to Invidious by default. Right now I'm using UntrackMe (https://f-droid.org/app/app.fedilab.nitterizemelite) to do so.

More about Invidious: https://github.com/omarroth/invidious

#### Is your feature request related to a problem? Please describe it

I would like to be able to use the Invidious front-end for YouTube and share links converted to Invidious by default, but there is no way to do it. I have to use an external app to do so.

#### Additional context

Dunno what to put here.
#### How will you/everyone benefit from this feature?

It will allow users to minimize the amount of tracking that they already have to fight against. It will also help them a bit in securing their online activity and protecting their privacy.

**Comment by B0pol** [comment] 2020-06-05 17:47
Duplicate of #1867

**Closed by B0pol** 2020-06-05 17:47 UTC
Labels: enhancement
