### ISSUE TITLE
Faster speed

### ISSUE THREAD

**Issue by fajis1** [TeamNewPipe/NewPipe#7640] opened 2022-01-10 00:32 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Wondering if we can get new pipe to allow speeds up to 5x. That's what my podcast player does. 

#### Why do you want this feature?

I found new pipe because I was looking for ways to speed up YouTube on Android. 

On the PC I use a speed controller to set speeds faster than 3x. 

My wife also listens to stuff faster than 3x and look forward to the day that new pipe has faster speeds. 

Thanks

**Comment by TiA4f8R** [comment] 2022-01-10 07:28
> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

Duplicate of #3876. Please search better for duplicates the next time you open an issue. Thank you.

**Closed by TiA4f8R** 2022-01-10 07:28 UTC
Labels: enhancement
