### ISSUE TITLE
"Trending" not always in preferred language

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#2085] opened 2019-02-01 12:50 UTC
The "Trending" videos (the tab name, the word "Trending" itself) sometimes appears in my local IP language instead of NewPipe's preferred settings language (English). It appears like that sometimes but after refreshing it says Trending again.

**Comment by Stypox** [comment] 2019-09-17 05:10
Duplicate of #578

**Closed by Stypox** 2019-09-17 05:10 UTC
