### ISSUE TITLE
Delete history after a while or after entry limit

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [TeamNewPipe/NewPipe#6627] opened 2021-07-08 10:27 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

An option to forget history after a while or only remember a certain amount of it would be useful. Presumably history doesn't get used that much and even if it gets, probably only the recent videos are looked for, so preventing stockpiling data would be great.

#### How will you/everyone benefit from this feature?

Better privacy and less stored data.

**Comment by SameenAhnaf** [comment] 2021-07-08 10:31
I'd recommend you to keep the discussion in #3487.

**Comment by IHateTheProgrammingClass** [comment] 2021-07-08 16:33
What do you mean? Who's Hogerys?

**Comment by SameenAhnaf** [comment] 2021-07-08 17:34
#6627 is a duplicate of #6431.
#6628 is a duplicate of #5936.
#6625 is a duplicate of #6264.
#6626 is a duplicate of #5496.

Check the title, edit history and comments. How is it possible that all of the issues were 'deleted' (according to you) and opened around the same time?

I have no desire to ask why or how you did this. But if you really want to get rid of your account, just delete your account and subscribe again to the issues with your new account. That way, nobody will be able to catch you.

The reason why I am suggesting you to avoid such activities as users require to subscribe again to new issues unnecessarily.

**Comment by IHateTheProgrammingClass** [comment] 2021-07-09 06:10
@SameenAhnaf I literally don't understand what made you assume it was me but ok. All of these posts are deleted.

**Comment by SameenAhnaf** [comment] 2021-07-09 08:37
Hahaha, cautcha! But that's ok, too😂

**Comment by SameenAhnaf** [comment] 2021-07-10 11:04
Please keep the discussion in #3487.

**Closed** 2021-08-17 19:44 UTC
Labels: enhancement
