### ISSUE TITLE
Transcript

### ISSUE THREAD

**Issue by WhtUsrWrks** [TeamNewPipe/NewPipe#8528] opened 2022-06-21 09:39 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

It would be good if video transcripts were available, like they are in YT

### Why do you want this feature?

I find they are useful

**Comment by SameenAhnaf** [comment] 2022-06-21 09:45
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7375

**Comment by AudricV** [comment] 2022-06-21 10:03
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #7375. Please search (better, with different keywords?) for duplicates the next time you want to open an issue.
Thank you!

(By the way welcome to GitHub!)

**Closed by AudricV** 2022-06-21 10:03 UTC
Labels: enhancement

**Comment by koendv** [comment] 2022-12-10 08:50
A transcript is text-to-speech of the audio channel. This is useful: it is faster to read the text than to watch the video. Or when you want the lyrics of a song. Unfortunately, sometimes the owner of a video turns transcript off. It would be useful to have video transcripts that do not depend upon youtube.

[vosk](https://alphacephei.com/vosk/) is open source text-to-speech software; available as [android library](https://github.com/alphacep/vosk-api). Using vosk, create a transcript of youtube videos and songs.

**Comment by opusforlife2** [comment] 2022-12-10 16:40
@koendv Why comment on a closed duplicate? The original issue is available.
