### ISSUE TITLE
Repeat part of the video

### ISSUE THREAD

**Issue by Angelk90** [TeamNewPipe/NewPipe#6849] opened 2021-08-04 18:58 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

In addition to repeating the video, it would be very useful to have the possibility to be able to specify a beginning and an end where the repetition should take place, instead of repeating everything from start to finish.

**Comment by mhmdanas** [comment] 2021-08-04 19:01
Sounds like a duplicate of #5653. If you disagree, feel free to make a comment.

**Closed by mhmdanas** 2021-08-04 19:01 UTC
Labels: enhancement
