### ISSUE TITLE
Subscription videos not showing in order

### ISSUE THREAD

**Issue by kelna** [TeamNewPipe/NewPipe#1384] opened 2018-05-08 17:13 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

The videos in my subscription list are not listed in publication time order. They are in seemingly random order. This, sadly, makes the feature fairly useless.

**Comment by kelna** [comment] 2018-05-08 17:17
The order is the same after app kill/restart. I cannot see any logic in it. First a 9 months old video, then 2 months, 1 year, 21 hours, 23 hours, 3 days, 5 days, 1 day...

**Comment by CyniqueDuBonSensEtDeLaRaison** [comment] 2018-05-08 18:08
Hi kelna,
I have the same issue. Just can agree with you. For me, the order of videos is : 2 days, 1 month, 2 days, 1 week, 10 hours, 1 week, 2 months etc...
I didn't find how to fix it :(
Glad to see I'm not alone.

**Comment by Phoenix616** [comment] 2018-05-08 23:40
Duplicate of #739 which contains more info.

**Closed** 2018-05-12 16:58 UTC
Labels: duplicate
