### ISSUE TITLE
[Feature request] When on WiFi stream at 1080p

### ISSUE THREAD

**Issue by Androidphonetoucher** [TeamNewPipe/NewPipe#1310] opened 2018-04-13 17:08 UTC
I'd love to see the ability to custom set playback quality according to the avaliable Internet connection. 

E.g. On WiFi use 1080p, and on 4G use 360p etc. Thanks :)

**Comment by stnby** [comment] 2018-04-14 08:56
Yes exactly that would be cool feauture.

**Comment by Stypox** [comment] 2019-07-19 14:53
Duplicate of #518

**Closed by Stypox** 2019-07-19 14:53 UTC
