### ISSUE TITLE
Feature request: add MP3 to download options

### ISSUE THREAD

**Issue by ofiala-a51** [TeamNewPipe/NewPipe#3123] opened 2020-02-22 00:45 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

The title says it all. MP3 is the most widely supported audio format, so imo it should be included as one of the options...

**Comment by wb9688** [comment] 2020-02-22 05:50
We only provide the formats that YouTube (or other services, like SoundCloud) offer. YouTube doesn't offer MP3, so we don't either. If your request is to convert a file you've downloaded to MP3, I think there's already an issue for that, but that's unlikely to be implemented.

**Comment by Stypox** [comment] 2020-02-22 08:57
Duplicate of #507

**Closed by Stypox** 2020-02-22 08:57 UTC
