### ISSUE TITLE
Video doesn't play

### ISSUE THREAD

**Issue by Kobura11** [TeamNewPipe/NewPipe#8534] opened 2022-06-22 16:46 UTC
### Checklist

- [ ] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [ ] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Opened the app and started playing a video in the background.
2. Received a notification about an avaliable update for the app.
3. Agreed to proceed with the update.
4. The update was completed and the app stopped working.
5. Closed the app and restarted it, but when I try to play the video, the error shows up. 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_MALFORMED] occurred while playing https://www.youtube.com/watch?v=ZWS2nFo7eEo
* __Content Country:__ IT
* __Content Language:__ en-IT
* __App Language:__ en_IT
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:213)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Invalid NAL length
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:621)
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:258)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>
<hr>

### Affected device model

Honor 10

**Comment by AudricV** [comment] 2022-06-23 11:02
Closing as a duplicate of #8310 (same stacktrace and related steps to reproduce).

Please search (better, with different keywords?) for duplicates the next time you want to open an issue.

You can try to clear the application cache in system settings after closing the app in order to avoid this issue. Thank you.

**Closed by AudricV** 2022-06-23 11:02 UTC
Labels: bug, template-ignored
