### ISSUE TITLE
Add ability to filter by time videos are uploaded 

### ISSUE THREAD

**Issue by ruineka** [TeamNewPipe/NewPipe#8347] opened 2022-05-03 18:01 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When under the whats new it would be extremely handy to filter the content by nearest to oldest or vice versa.

### Why do you want this feature?

Currently the "Whats new!" tab seems to bring up content in a random order varying from minutes to hours the video was added. Keeping it organized to see the latest Steam Deck videos as they come would be nice! :)

**Comment by SameenAhnaf** [comment] 2022-05-04 03:26
Duplicate of #6878

**Closed** 2022-05-04 18:01 UTC
Labels: enhancement

**Comment by ruineka** [comment] 2022-05-04 18:59
> Duplicate of #6878

Related but not necessarily the same. From my little use of this app I seem to see videos within the current day, but the minutes or hours the video is listed is not in the order of soonest to latest.

For example. I'll see videos all posted today, but the first video to pop up would have been posted 2 hours ago, and the video underneath it will be 40 minutes ago and another video under it would be 1 hour ago.

When looking for specific videos not using the Whats New tab it is completely random.

![Screenshot_20220504-135613.png](https://user-images.githubusercontent.com/16360335/166806475-7f55d160-f521-4d08-9214-daa4a4c42ea2.png)

I tried to get a screenshot showing the timestamps out of order on Whats New, but it appears to be showing as I'd expect it to now.

**Comment by opusforlife2** [comment] 2022-05-05 20:48
> seems to bring up content in a random order varying from minutes to hours the video was added

Never seen this behaviour. Any feed is always ordered by time of upload. How often does this happen to you? Or was it a one-off event?

**Comment by ruineka** [comment] 2022-05-06 05:03
> > seems to bring up content in a random order varying from minutes to hours the video was added
> 
> Never seen this behaviour. Any feed is always ordered by time of upload. How often does this happen to you? Or was it a one-off event?
> 
> Edit: regarding your image above: this is not a bug. Search results are expected to be sorted by relevance. That's the default behaviour on the official website as well.

I haven't seen it recently and haven't had time to really watch any YT. It's possible that the time frame of when started using NewPipe was when everything in my feed was Steam Deck related that the whats new and whatnot were showing pretty much the same stuff just in a different order. If I notice it again I'll screenshot it and leave a comment.
