### ISSUE TITLE
Blank Comments Bug

### ISSUE THREAD

**Issue by 1YuvrajS** [TeamNewPipe/NewPipe#10953] opened 2024-04-06 15:12 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.26.1

### Steps to reproduce the bug

1. When you want to watch any video in Newpipe.
2. You will find glitch or big in Comments Section and I see but everything is fine.

### Expected behavior

There is a bug or glitch in Comments Section 

### Actual behavior

It happens in some video that I play.

### Screenshots/Screen recordings

<img alt="Screenshot_2024-04-06-20-41-25-695_org schabi newpipe" src="https://github.com/TeamNewPipe/NewPipe/assets/93419850/91f28297-e86f-47f7-8e1f-e193a2a84baa" width=270 />

### Logs

I can't find where log is?

### Affected Android/Custom ROM version

Android 14

### Affected device model

Redmi Note 12 Pro+

### Additional information

Nil

**Comment by AudricV** [comment] 2024-04-06 17:54
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #10808. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-04-06 17:54 UTC
Labels: bug, needs triage
