### ISSUE TITLE
Support for Android Auto

### ISSUE THREAD

**Issue by Tomblarom** [TeamNewPipe/NewPipe#2163] opened 2019-02-28 16:42 UTC
Hey! I'm using NewPipe in my freetime, but can't use it while driving.. It's distracting a little bit too much. Google Auto is a great App that simplyfies basic controls like play, pause, next or previous.

It's quite easy to implement: https://developer.android.com/training/auto/audio
I'd be happy to see it listed in Google Auto.

**Comment by ReekyMarko** [comment] 2019-02-28 22:14
Android Auto relies heavily on Google Play Services, so my guess is it's not going to be implemented, or at least not very soon as there is a whole list of more pressing issues.

Although I must say I'm not very familiar with Android Auto so I can't say for certain how would one implement this.

**Comment by N3RG4L** [comment] 2019-03-04 23:02
Hey ! that was on my todolist, I'll do a pull request soon :)

**Comment by Redirion** [comment] 2019-07-31 08:57
@N3RG4L did you start working on this yet? if not, I would like to give it a try next week

**Comment by Stypox** [comment] 2019-07-31 09:28
I don't have the permission to rename issues 😅

**Comment by Stypox** [comment] 2019-09-26 05:36
Duplicate of #1758, also, this is not possible anymore

**Closed by Stypox** 2019-09-26 05:36 UTC
