### ISSUE TITLE
Android w/ Zoom bug

### ISSUE THREAD

**Issue by gabrielDane** [TeamNewPipe/NewPipe#5803] opened 2021-03-10 04:03 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

Use app with font zoom on android causes unreadable text overlap

### Expected behavior

Text should display properly on android at all font zoom levels

### Screenshots/Screen recordings

![Screenshot_20210309-185748_NewPipe](https://user-images.githubusercontent.com/7246249/110574627-b02ffd80-811a-11eb-84b7-880b8e6dbba0.jpg)

![Screenshot_20210309-205424_Settings](https://user-images.githubusercontent.com/7246249/110574643-baea9280-811a-11eb-87b5-c09b655f7f70.jpg)

### Device info

 - Android version/Custom ROM version: 9/stock
 - Device model: Samsung Galaxy S8+

**Comment by iamthesenate1** [comment] 2021-03-10 19:02
Can reproduce on Redmi Note 5A on XL font size

**Comment by wangear** [comment] 2021-03-12 09:43
Hello! I'd like to work on this enhancement. Can i assigned to this issue? :)

**Comment by TiA4f8R** [comment] 2021-03-12 10:20
Duplicate of #5096.
@wangear I assigned you in this issue.

**Closed by TiA4f8R** 2021-03-12 10:20 UTC
Labels: bug
