### ISSUE TITLE
UI stays on screen after resuming playback with a Bluetooth device

### ISSUE THREAD

**Issue by itzLukeYo** [TeamNewPipe/NewPipe#7560] opened 2021-12-20 15:32 UTC
When I resume video playback by pressing the play/pause button on my speaker, the UI stays on the screen.

**Comment by SameenAhnaf** [comment] 2021-12-20 17:50
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7086

**Comment by itzLukeYo** [comment] 2021-12-20 17:59
> Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7086

I do not think it is? That report describes not being able to resume playback in background. I am describing the UI staying visible while resuming playback in fullscreen mode (in my case video does start playing).

Sorry if I'm wrong, I'm pretty new to GitHub.

**Comment by litetex** [comment] 2021-12-20 21:09
Duplicate of #3403 ;)

**Closed by litetex** 2021-12-20 21:09 UTC
Labels: template-missing
