### ISSUE TITLE
Download file info

### ISSUE THREAD

**Issue by Arthurdw** [TeamNewPipe/NewPipe#2571] opened 2019-08-28 22:00 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.  
  
When you download a video or sound file the YouTube/SoundCloud/... 's author name stands as author ect.  
This would be useful if users want to search a song in a default phone app.

**Comment by snappyapple632** [comment] 2019-08-28 23:18
Having a metadata tool would indeed be useful and feasible, I often find myself archiving music and videos where I have to use a dedicated program to edit the metadata.

**Comment by Stypox** [comment] 2019-08-29 06:37
Duplicate of #183

**Closed by Stypox** 2019-08-29 06:37 UTC
