### ISSUE TITLE
Use newpipe player to play downloaded videos 

### ISSUE THREAD

**Issue by AlertSubject** [TeamNewPipe/NewPipe#7369] opened 2021-11-07 21:48 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
Clicking on a video in the downloads section of the app causes the phones default video player to open. The gallery app in my case. I'd rather have it use the default newpipe player 

#### Why do you want this feature?
The advantage would be being able to use all the features of new pipes player 
Seeking, double tap to fast forward / backwards and the app being able to save your progress in the video + add it to your watch history 
Most of these things are not supported in default players that come with Android devices

**Comment by SameenAhnaf** [comment] 2021-11-08 03:22
Duplicate of #478 and see https://github.com/TeamNewPipe/NewPipe/issues/478#issuecomment-960959193

**Closed** 2021-11-08 19:54 UTC
Labels: enhancement
