### ISSUE TITLE
After Refreshing the Page it is asking for Captcha to fill out

### ISSUE THREAD

**Issue by Jonathan39045** [TeamNewPipe/NewPipe#11703] opened 2024-11-14 00:54 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1) Just refresh  the feed.

2) After refreshing Click on any video which you have Subscribed.

3) It is displaying the Error message like "recaptcha Challenge requested".

4) And I cant able to see any Videos.

5) Even I cant able to playback the Videos which I have already seen in my history.

6) But after some time ( Cant able to tell exact timing) 2 to 3 hrs it is Automaticcaly get resolved and I can able to View the Videos Which shown in my feed.
![Screenshot_2024-11-14-06-14-05-208_org schabi newpipe](https://github.com/user-attachments/assets/6aa1a4ae-e4fe-49df-ab20-fc1ff26c6d4f)

### Expected behavior

It needs to open and videos should get Viewed by the User

### Actual behavior

It is of telling the User to "reCAPTCHA challenge requested" 

### Affected Android/Custom ROM version

Android 13

### Affected device model

Redmi 12C

**Comment by AudricV** [comment] 2024-11-14 11:38
> - [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #11661. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-11-14 11:38 UTC
Labels: bug, needs triage
