### ISSUE TITLE
When I press download button, Newpipe crashes

### ISSUE THREAD

**Issue by anomlycreator** [TeamNewPipe/NewPipe#6761] opened 2021-07-25 07:49 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ UA
* __Content Language:__ uk-UA
* __App Language:__ uk_UA
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4295)
	at android.app.ActivityThread.access$1700(ActivityThread.java:250)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2008)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4283)
	... 8 more

```
</details>
<hr>

**Comment by bew** [comment] 2021-07-25 08:39
Duplicate of #6687

**Closed** 2021-07-25 16:56 UTC
Labels: bug
