### ISSUE TITLE
Ability to use audio with subtitles.

### ISSUE THREAD

**Issue by nalinalini** [TeamNewPipe/NewPipe#6163] opened 2021-04-25 03:52 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The aboility to hear the audio with the subtitles. I think it should be recognized by a new name.Because background plays it in background but this will use audio and subtitles except the video.

#### Is your feature request related to a problem? Please describe it

This will save data by disabling video and make availability of subtitles (when available).
I want to hear a podcast with watching their subtitle but there is no way to do it.

**Comment by mhmdanas** [comment] 2021-04-25 16:31
Duplicate of #6102.

**Closed by mhmdanas** 2021-04-25 16:31 UTC
Labels: enhancement
