### ISSUE TITLE
Card View

### ISSUE THREAD

**Issue by rahaaatul** [TeamNewPipe/NewPipe#8096] opened 2022-03-23 10:41 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

In List View mode, add a new mode: **Card**.
Like a full grid, instead of 2.

### Why do you want this feature?

1. With list mode on, the thumbnail is small and hard to see.
2. With grid mode on, the title isn't completely shown, so you have to tap to read it.

<img alt="IMG_20220323_162632.jpg" src="https://user-images.githubusercontent.com/86149861/159682138-3f33d95f-f7b0-4f4a-92e4-c0c0553872f5.jpg" height=600 />

### Additional information

Like Youtube app's card feed:
<img alt="Screenshot_20220323163228_1.jpg" src="https://user-images.githubusercontent.com/86149861/159681865-6fb5db98-54c2-4786-8fbf-fae9f87ad8eb.jpg" height=600 />

**Comment by SameenAhnaf** [comment] 2022-03-23 10:44
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6906

**Closed** 2022-03-23 19:28 UTC
Labels: enhancement
