### ISSUE TITLE
loading videos in 144p as default quality takes a long time

### ISSUE THREAD

**Issue by nicoursi** [TeamNewPipe/NewPipe#2829] opened 2019-11-27 11:46 UTC
Playing videos in 360p works just fine. Playing them with a lower resolution, expecially 144p, takes a long time to load. This happens when the quality (different than 360p) is set as default.

**Comment by Serkan-devel** [comment] 2019-11-27 12:56
720p loads much faster than 480p here

**Comment by ignas-sa** [comment] 2019-12-01 19:02
Have you tried changing audio/video format to WebM? It's worked wonders for me.

**Comment by nicoursi** [comment] 2019-12-02 10:30
It works! Thank you!

**Comment by nicoursi** [comment] 2019-12-02 10:37
It works well with 144 but it get slower with 360. This is annoying because i have to switch every time I'm on WiFi. Normally I have 360 with WiFi and 144 with mobile data.

**Comment by Stypox** [comment] 2020-01-08 18:05
Duplicate of #2754 and many others

**Closed by Stypox** 2020-01-08 18:05 UTC
