### ISSUE TITLE
Ability to view all YouTube CHANNELS under a particular Channel Group (NOT Videos) - Sorted by Newest publication date

### ISSUE THREAD

**Issue by ascworl** [TeamNewPipe/NewPipe#7993] opened 2022-03-05 18:15 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Currently, when we open a Channel Group, it displays a video feed, sorted by most recently uploaded.
I would like it so we can click a Channel Group, then have it display all YouTube Channels under that particular group. Sorted by the channels that uploaded most recently.
As an example, check out the app "Podcast Addict." We can select a category, then see all podcast subscriptions under that particular category. We can then open the podcast and see the videos.

Again, the improved navigation would be:
Select Channel Group (Category)
See a list of all YouTube Channels under that category (sorted by publication date - newest first)
Select YouTube Channel
See a list of all videos by that channel (newest at the top)
Select video and watch

### Why do you want this feature?

This is much less overwhelming and easy to use than seeing a giant list of all videos being uploaded.
We should have both options available (The current method and the one I am proposing).

### Additional information

If this is not possible, at the very least, we could at least be able to see a list of all Channel names under a particular Channel Group.

Thank you

**Comment by ascworl** [comment] 2022-03-05 18:17
Since this is not possible currently, I am having to use import YouTube channel RSS feeds into a separate app (such as Podcast addict), which allows this better view, navigation, and sorting.

**Comment by SameenAhnaf** [comment] 2022-03-06 01:46
Duplicate of #3812

**Closed** 2022-03-23 19:29 UTC
Labels: enhancement
