### ISSUE TITLE
Crash while playing video!

### ISSUE THREAD

**Issue by Spok1** [TeamNewPipe/NewPipe#10306] opened 2023-08-05 15:10 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Open video using WiFi hotspot over 4g internet;
2. Start video playback at x1.5 speed;
3. Can issue a crash.

### Expected behavior

So that this doesn't happen again.

### Actual behavior

Video crash on playback.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Play Queue has not been initialized.
	at org.schabi.newpipe.player.playback.MediaSourceManager.<init>(MediaSourceManager.java:141)
	at org.schabi.newpipe.player.playback.MediaSourceManager.<init>(MediaSourceManager.java:130)
	at org.schabi.newpipe.player.Player.reloadPlayQueueManager(Player.java:618)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onMenuItemClick(VideoPlayerUi.java:1207)
	at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1200)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3165)
	at android.widget.AbsListView$3.run(AbsListView.java:4080)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6097)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7, ZenUi

### Affected device model

Z500M

**Comment by Zyban117** [comment] 2023-08-07 03:11
Translation: 

Title: Crash while playing video!

Steps to reproduce the bug:
1. Open video using WiFi hotspot;
2. Start video playback at x1.5 speed; 
3. May crash.

Expected behavior: To not be like that.
Actual behavior: Video crash on playback.

**Comment by Spok1** [comment] 2023-08-07 11:20
@Zyban117 ,Okay, you can delete the comment, corrected the description.

**Comment by Spok1** [comment] 2023-08-07 22:11
>When does the crash occur?

 after the video has played for some time

>And does the crash occur consistently with your given steps? Or only sometimes?

The video may play, or it may crash all the time. I can not say what it is connected with.😔

**Comment by Spok1** [comment] 2023-08-08 10:51
@opusforlife2 , Installed yesterday, will check.

**Comment by yuvarajpm1853** [comment] 2023-08-08 13:30
I love using newpipe .  After YouTube changed UI I to three tabs . I started to use Newpipe channel tabs . But , in recent days the apk starts to  crash after some seconds of playing with message of Network error . While the same content plays well in YouTube. I don't know why is it happening. Is it for me only ? 

The same content runs well in newpipe apk .  But , due to no video , shorts , love tabs I moved to newpipe channel tab . Is there any way to get these UI in newpipe . Or any possible way to solve the problem in Newpipe channel tab else need to use other version of newpipe ...

The error message : 

-------------------------------------
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:257)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
-------------------------------------

Can anyone reply me simply what to do next ?

**Comment by githubw0** [comment] 2023-08-09 00:35
i'm encountering random/unpredictable YT video play errors > 3mins after start with unacceptable frequency >25% of play attempts. 25.1, itself, never crashes.

once video errors mid-play, can't be resumed or restarted without a lengthy timeout, ~1hr. only then is vid restart possible, not by closing/clearing cash/reopening timeout. play @ >1x speed increases risk of play fail, but not required. i can move to a different vid & play it just fine.

toast error message advises viewing notification for details, but no details to be found there.

did 25.1 muck up play caching?

on SM-908U TM, Damsung official, Andro13, OneUI 5.1. 

older newpipes never failed like this.

help. thanks.

**Comment by imsi32** [comment] 2023-08-09 06:29
I have similar issue when I get the video resolutian to 720p or 720p60. And after few seconds video crashes and I cannot restart that video.

I use my mobile internet instead of wifi.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=1grU6YbVZ1Q
* __Content Country:__ TR
* __Content Language:__ tr-
* __App Language:__ tr
* __Service:__ YouTube
* __Version:__ 0.25.1
* __OS:__ Linux HUAWEI/SNE-LX1/HWSNE:10/HUAWEISNE-L01/10.0.0.212C432:user/release-keys 10 - 29
`<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>
`

**Comment by federicodilo** [comment] 2023-08-10 21:34
I have the same problem, at some point the video crashes and a notification saying connection error would happear. Both with 1.5× and normal speed.

I watch videos in Wi-Fi and I've been using the same Wi-Fi for a long time, I can say it is not a router related problem. Also other devices paired do not show the same problem.

**Comment by imsi32** [comment] 2023-08-13 02:46
I updated to v0.25.2 and it seems like my issue is fixed. Thanks.

**Closed** 2023-08-15 01:10 UTC
Labels: bug, waiting for author, needs triage

**Comment by Spok1** [comment] 2023-08-15 15:02
@opusforlife2, the problem is no longer observed since I installed the latest version of the application. I recommend everyone to install the latest version!
