### ISSUE TITLE
YouTube errors

### ISSUE THREAD

**Issue by BaphometTechnology** [TeamNewPipe/NewPipe#3990] opened 2020-07-28 14:54 UTC
No matter what video or whether I choose play, pop-up, or background the videos do not play. This is with the most recent version of the app.

**Comment by strongwinderic** [comment] 2020-07-28 14:55
"Could not play this stream" is the error message.

**Comment by soladev** [comment] 2020-07-28 14:56
Duplicate of #3951. The isse has been fixed and the release is coming **SOON**

**Comment by wb9688** [comment] 2020-07-28 15:56
Use v0.19.8

**Closed by wb9688** 2020-07-28 15:56 UTC
Labels: bug
