### ISSUE TITLE
[Request] Drag down to refresh.

### ISSUE THREAD

**Issue by Duppadaadadii** [TeamNewPipe/NewPipe#858] opened 2017-11-18 21:48 UTC
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
I would like to have a drag down to refresh page action, as now i always have to shut down the app and return in it to refresh the page for latest videos. Quick F5 would be better. ;)

I think it would be a good thing to implement. Im no coder myself though.

**Comment by theScrabi** [comment] 2017-11-19 00:47
Yea I thought about this my self. Maybe considerable.

**Comment by 2SI3NX** [comment] 2017-11-21 17:53
Nice, yes! This would be great to implement also while the video is trying to load and gets stuck loading, maybe during connection issues.  Swiping down to refresh the connection and reload the video

**Comment by jpatelvnera** [comment] 2018-10-24 05:49
Hey, I Plan to work on this feature. Can you guide me where to start? I am looking through the codebase and plan to use google's activity

**Comment by theScrabi** [comment] 2018-10-24 09:35
Googles activity? You may take a look at BaseActivity.

**Comment by skylarmt** [comment] 2019-06-07 07:57
Any progress on this?  I was about to open an issue for it, but then I saw this one, as well as #740 and #1003.

**Comment by skylarmt** [comment] 2019-06-07 08:04
Currently the only way to refresh the "What's New" list is to close the app all the way and open it again.  This is problematic, as some channels release updates daily on a regular schedule, making this flaw quite obvious.

Heck, make a refresh button that restarts the whole app, that's still a better refresh experience than the current nonexistent one.

**Comment by Stypox** [comment] 2019-06-23 12:35
This will be implemented in #2309

**Comment by Stypox** [comment] 2019-06-23 12:36
Closing, since this is a duplicate of #740

**Closed by Stypox** 2019-06-23 12:36 UTC
Labels: enhancement
