### ISSUE TITLE
Popup Window Resolution Problem

### ISSUE THREAD

**Issue by GKid94** [TeamNewPipe/NewPipe#1337] opened 2018-04-21 13:38 UTC
When I select 720p as the default resolution and 360p for the popup window resolution the popup window always plays in 720p, can you please fix that?

**Comment by karyogamy** [comment] 2018-04-21 17:58
If you open the popup in from the video details page, then it is going to use the resolution selected at the top. This popup setting is only for starting from popup enqueue.

**Comment by karyogamy** [comment] 2018-04-22 06:07
No, unfortunately, as this is the intended behavior. We'd rather have the action be consistent with the quality shown on the details page, which is apparent to the user, than using a setting that's hidden somewhere else.

**Comment by B0pol** [comment] 2020-05-10 09:42
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/843

**Closed by B0pol** 2020-05-10 09:42 UTC
Labels: enhancement
