### ISSUE TITLE
media play button raises NP with empty PL

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#1787] opened 2018-10-03 12:17 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

while https://github.com/TeamNewPipe/NewPipe/issues/1542 fixed in 0.14.1 it's still not perfect: using BT headset I push "Play" and end up with NP appearing among Notifications but playlist is empty. Not good.

**Comment by theScrabi** [comment] 2018-10-04 09:18
please post the npe.

**Comment by Stypox** [comment] 2019-08-28 16:55
Duplicate of #1619

**Closed by Stypox** 2019-08-28 16:55 UTC
