### ISSUE TITLE
[Enhancement] Remember repeat option

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1302] opened 2018-04-10 11:56 UTC
When I play video on background I can click repeat icon in notification to repeat video but I have to do this every time I launch app. Some option for this in settings would be nice.

**Comment by speednroll** [comment] 2018-04-11 23:51
remember to label this as an improvement, or respond with the feature request if it was requested before, please 😉

**Comment by Stypox** [comment] 2019-08-27 12:07
Duplicate of #981

**Closed** 2019-08-27 12:08 UTC
Labels: GUI, enhancement
