### ISSUE TITLE
Suggested video

### ISSUE THREAD

**Issue by Gottarocket** [TeamNewPipe/NewPipe#6630] opened 2021-07-08 18:45 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Youtube has option to popup suggestion youtuber makes to check there old videos. Would appreciate that in new newpipe release so we can access it instead of searching for that video when its not on description 

If onscreen option like on youtube to touch and play that suggested  video would be appreciated or  buttons like timestamp or next video would also be helpful .

#### Is your feature request related to a problem? Please describe it

No

#### How will you/everyone benefit from this feature?

It would be easier to watch videos without searching for it and would be helpful to recommend others to switch to newpipe when its similar like youtube app

**Comment by mhmdanas** [comment] 2021-07-08 21:37
Thanks for opening an issue! I believe this is a duplicate of #2854.

**Closed by mhmdanas** 2021-07-08 21:37 UTC
