### ISSUE TITLE
Clicking Another Video While Video is Playing Causes Phone to Reboot

### ISSUE THREAD

**Issue by enchainingrealm** [TeamNewPipe/NewPipe#8149] opened 2022-04-04 16:45 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. In Settings > History and cache, disable "Resume playback" or disable "Watch history".
2. On the Trending page, tap any video to begin playing it.
3. Swipe down to minimize the currently playing video.
4. On the Trending page, tap another video.
5. The phone instantly reboots.

### Expected behavior

The second video (tapped in Step 4) should begin playing.

### Actual behavior

The phone instantly reboots.

### Affected Android/Custom ROM version

Android 11

### Affected device model

Pixel 2

**Comment by TiA4f8R** [comment] 2022-04-04 17:01
> - [x] I made sure that there are _no existing issues_ - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

No. Next time, please check better for duplicates, because this issue is a duplicate of #5961. Thank you.

**Closed by TiA4f8R** 2022-04-04 17:01 UTC
Labels: bug
