### ISSUE TITLE
[Request] Pull down to refresh channels

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2512] opened 2019-08-13 17:44 UTC
Currently if you want to manually refresh a channel to grab freshly uploaded content, you'll have to clear the cache and reload the channel. There should be a way for the user to initiate a scrape manually within the app.

I feel that 'pull down to refresh' is universal enough to work here. It gives the user an intuitive way to check for updates without any changes to how regular checks are made.

**Comment by Stypox** [comment] 2019-10-02 12:17
Duplicate of #740

**Closed by Stypox** 2019-10-02 12:17 UTC
