### ISSUE TITLE
App crash, UI failure when searching and playing

### ISSUE THREAD

**Issue by Suncatcher** [TeamNewPipe/NewPipe#5087] opened 2020-12-03 07:53 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

Nothing unusual, trying to play the video from search

### Expected behavior

Normal playing

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ en-US
* __Service:__ none
* __Version:__ 0.20.5
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
	at j$.util.DesugarGregorianCalendar.from(:1)
	at org.schabi.newpipe.util.Localization.relativeTime(Localization.java:317)
	at org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.getFormattedRelativeUploadDate(StreamInfoItemHolder.java:98)
	at org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.getStreamInfoDetailLine(StreamInfoItemHolder.java:83)
	at org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.updateFromItem(StreamInfoItemHolder.java:65)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:337)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:360)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:871)
	at android.view.View.layout(View.java:20694)
	at android.view.ViewGroup.layout(ViewGroup.java:6208)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2821)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2348)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1488)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7260)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
	at android.view.Choreographer.doCallbacks(Choreographer.java:816)
	at android.view.Choreographer.doFrame(Choreographer.java:751)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6831)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</p></details>
<hr>

There are similar bugs I found ([4546](https://github.com/TeamNewPipe/NewPipe/issues/4546)), however I didn't use background playing, so I created a new bug.

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: Kyocera E6910

**Comment by B0pol** [comment] 2020-12-03 09:37
Duplicate of #5075

**Closed by B0pol** 2020-12-03 09:38 UTC
Labels: bug
