### ISSUE TITLE
Add to the Accrescent.app store 

### ISSUE THREAD

**Issue by JaByteOS** [TeamNewPipe/NewPipe#11332] opened 2024-07-21 17:07 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Have you considered or are you planning on putting your app on Accrescent (app store focused on security, privacy, and usability) 

### Why do you want this feature?

Accrescent is a private and secure Android app store built with modern features in mind.

It was just endorsed by GrapheneOS (considered by many to be the most private and secure mobile operating). GrapheneOS also now has accrescent in their app store. 

Right now there is only 9 apps on it. So any new apps added get great installation opportunities from the privacy and security minded community. 

### Additional information

Anyway, I really like your app, and would love to see it on Accrescent because it's so easy to install and update apps compared with f-droid, plus much more secure! 

Thank you for taking the time to read this. I'm a security and privacy conscious individual, not associated with Accrescent or GrapheneOS (though I use them both).

Xoxo Olivia

**Comment by fynngodau** [comment] 2024-07-21 17:37
Per the current documentation,

> Sign-up is not yet available to the general public and is only permitted for allowlisted GitHub accounts. This choice was made to ensure that all developers on Accrescent are willing to tolerate the lackluster user experience, console bugs, and frequent policy changes resultant of Accrescent being in its early stages.

NewPipe also at this time does not issue split apks, which is listed as an inclusion criterium.

At this time, I personally don't see much reason to go through efforts to support an additional distribution mechanism, considering it can additionally make recurring maintenance necessary.

**Comment by JaByteOS** [comment] 2024-07-21 17:42
That makes sense, thank you for the quick response and taking this time. Much appreciated.

**Comment by AudricV** [comment] 2024-07-21 17:58
> - [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #9559. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-07-21 17:58 UTC
Labels: discussion
