### ISSUE TITLE
Bug Issue.

### ISSUE THREAD

**Issue by dude-shah** [TeamNewPipe/NewPipe#7663] opened 2022-01-16 10:13 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

Sometimes video publishers give time stamps of video in description when you click on time stamp , video move to certain time .
In newpipe when i click on time stamps it opens a popup player which i didn't wanted ...

### Expected behavior
When clicking time stamp .. video should move to certain time not open a popup player

### Device info

 - Android version/Custom ROM version: android 11
 - Device model: realme 6

**Comment by SameenAhnaf** [comment] 2022-01-16 10:26
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4241

**Closed** 2022-01-16 10:27 UTC
Labels: bug

**Comment by dude-shah** [comment] 2022-01-16 10:30
The same request as mine was posted 1 year ago ...
Please make this feature available in app for next update
