### ISSUE TITLE
Video playback doesn't start or stops at some point

### ISSUE THREAD

**Issue by antzi** [TeamNewPipe/NewPipe#8386] opened 2022-05-11 08:00 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

2.23.0

### Steps to reproduce the bug

Go to https://www.youtube.com/watch?v=VfyrQVhfGZc

### Expected behavior

Play the video

### Actual behavior

Video playback does not start

### Logs

com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Invalid NAL length
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:621)
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:258)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

### Affected Android/Custom ROM version

EMUI 12.0.0 build 12.0.0.236

### Affected device model

Huawei P40 pro (ELS-NX9)

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_MALFORMED] occurred while playing https://www.youtube.com/watch?v=VfyrQVhfGZc
* __Content Country:__ BG
* __Content Language:__ en-BG
* __App Language:__ en_BG
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Invalid NAL length
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:621)
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:258)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>
<hr>

**Comment by raniesantos** [comment] 2022-05-15 11:36
Exact same issue, my device is a Nokia G10.

**Comment by raniesantos** [comment] 2022-05-15 13:50
No idea how or why, but restarting my phone fixed it.

Some other video related apps were also failing to play video, like the Twitch app.

Now both apps are functioning again.

**Comment by AudricV** [comment] 2022-06-23 10:59
Closing as a duplicate of #8310 (same stacktrace and related steps to reproduce).

Please search (better, with different keywords?) for duplicates the next time you want to open an issue.

You can try to clear the application cache in system settings after closing the app in order to avoid this issue. Thank you.

**Closed by AudricV** 2022-06-23 10:59 UTC
Labels: bug
