### ISSUE TITLE
NewPipe Videos not loading properly

### ISSUE THREAD

**Issue by ZioZvevo** [TeamNewPipe/NewPipe#8122] opened 2022-03-29 01:09 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Just press on any video and it will do this 50 percent of the time. First, however, you need to go under settings, click on video and audio, and click on Video Player and set Video player as the default opener when clicking on a video.

### Expected behavior

The video is expected to play without a huge loading wait time.

### Actual behavior

The videos sometimes, at least fifty percent of the time, take 15 or even 30 seconds to load. I have a very fast internet and wifi, so that is not the issue that may seem obvious to everyone.

### Screenshots/Screen recordings

<img alt="Screenshot_20220328-180216" src="https://user-images.githubusercontent.com/99705790/160511961-0e59f983-c0d9-4e52-88a6-ea8220a641db.png" height=600 />

### Affected Android/Custom ROM version

Android 9

### Affected device model

LG G8 Thinq

### Additional information

I really like NewPipe and am new to it, but fixing this problem would make it my favorite app by far. I am a YouTube Vance's user, but want to transition to this, which i believe has the potential (if this is fixed) to beat vanced in many ways. But if the videos take 30 seconds or sometimes a minute to load, it's unusable to listen to music or watch videos while doing activities such as exceeding or simply relaxing. Thank you for developing and creating a wonderful app, NewPipe ,and please let me know what you can do.

**Comment by Me0wzz** [comment] 2022-03-29 05:48
Duplicate of #8085

**Closed** 2022-03-29 13:28 UTC
Labels: bug

**Comment by ZioZvevo** [comment] 2022-03-30 01:16
Wow, thank you for your very deep comment by the way.
