### ISSUE TITLE
Minimized player interferes with gestures

### ISSUE THREAD

**Issue by andrespalumbo311** [TeamNewPipe/NewPipe#4405] opened 2020-10-05 10:06 UTC
### Checklist

- [v] I checked, but didn't find any duplicates of this issue in the repo. 
- [v] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [v] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
The new minimized in-app player in the bottom of the page should be bigger or pushed up a little bit in my opinion

#### Is your feature request related to a problem? Please describe it
The minimized player as it is now sometimes conflicts with android's swipe-based gestures to go home

#### Additional context
here is how it looks now 
![now](https://user-images.githubusercontent.com/68204348/95066509-c9afc200-0702-11eb-824c-2abfd7fd2e3f.jpg)
and here is an idea of how it might look
![new look](https://user-images.githubusercontent.com/68204348/95066569-dc29fb80-0702-11eb-8660-0e266bbeb5a4.jpg)
under the player you could have a blank space or the extension of the list we now have above the player

#### How will you/everyone benefit from this feature?
this feature would help everyone who uses a gestures system to navigate its device's UI

**Comment by opusforlife2** [comment] 2020-10-05 10:08
If it interferes with gestures, then that seems like a bug, not a feature request.

**Comment by andrespalumbo311** [comment] 2020-10-05 10:10
> If it interferes with gestures, then that seems like a bug, not a feature request.

ok, i hadn't flagged it as a bug because it's a behaviour that can be avoided by paying some attention to where you put your finger when you start the swipe

**Comment by leacha69** [comment] 2020-10-05 13:42
An option to turn off this feature would be highly appreciated.

**Comment by Stypox** [comment] 2020-10-05 16:04
@andrespalumbo311 you can just tap on it to make it bigger, there is no need to swipe. Unfortunately I don't think making it larger or higher would be an option, since people with no gestures already have no problems with the smaller one, and making it bigger would just use up more space on their screen. Do you have any other solution that would suit everyone? Otherwise I'd close this, since as I said you can already tap on the minimized player to bring it up, without needing to swipe or drag.

**Comment by leacha69** [comment] 2020-10-05 16:19
I'm just looking to keep it off. That feature was/is an annoying part of
YT. If I want something to continue playing I'll use the pop up or
background. When I close I want it off.

**Comment by Stypox** [comment] 2020-10-05 16:23
@leacha69 you can already press the X in the upper left of the screen, and you will achieve the result you are looking for, that is stop playing.

**Comment by leacha69** [comment] 2020-10-05 16:27
Ok I'll reload the new app and double check.

Thank you!

**Comment by opusforlife2** [comment] 2020-10-05 17:09
> you can just tap on it to make it bigger, there is no need to swipe.

@Stypox Still, that's a workaround, not a fix. Either we disable swipe on the minimised player and only allow tapping, or we remove the conflict with OS gestures.

**Comment by andrespalumbo311** [comment] 2020-10-05 17:56
> @andrespalumbo311 you can just tap on it to make it bigger, there is no need to swipe. Unfortunately I don't think making it larger or higher would be an option, since people with no gestures already have no problems with the smaller one, and making it bigger would just use up more space on their screen. Do you have any other solution that would suit everyone? Otherwise I'd close this, since as I said you can already tap on the minimized player to bring it up, without needing to swipe or drag.

i think that obtaining something kinda like this would be good. the "wasted" space for the player would remain exactly the same
![old](https://user-images.githubusercontent.com/68204348/95114840-d81ecd80-0744-11eb-9e6f-8e076f48b6f1.jpg)

**Comment by andrespalumbo311** [comment] 2020-10-05 17:58
> > @andrespalumbo311 you can just tap on it to make it bigger, there is no need to swipe. Unfortunately I don't think making it larger or higher would be an option, since people with no gestures already have no problems with the smaller one, and making it bigger would just use up more space on their screen. Do you have any other solution that would suit everyone? Otherwise I'd close this, since as I said you can already tap on the minimized player to bring it up, without needing to swipe or drag.
> 
> i think that obtaining something kinda like this would be good. the "wasted" space for the player would remain exactly the same
> ![old](https://user-images.githubusercontent.com/68204348/95114840-d81ecd80-0744-11eb-9e6f-8e076f48b6f1.jpg)

obviously something more polished, this is a bad microsoft paint 2 minutes work. it's just to give you an idea

**Comment by Stypox** [comment] 2020-10-05 19:22
> i think that obtaining something kinda like this would be good. the "wasted" space for the player would remain exactly the same

In my opinion that's a bad UI: lists should not be hovered with something in between.

> Still, that's a workaround, not a fix.

Well, it would not be a workaround, since it is one of the intended ways to expand the minimized player. If one of the intended ways has limitations under specific circumstances, but usually feels a little bit more comfortable, to me it does not seem like a workaround to use the other way. Similarly to the SAF-nonSAF filesystems: SAF is the best way, but on phones where SAF is not supported it is not a workaround to use nonSAF, but the expected behaviour. Though maybe this comparison is not well built, I'll have to find another one ;-)

**Comment by opusforlife2** [comment] 2020-10-05 19:29
@Stypox I mean it doesn't address the issue that swiping on the player conflicts with OS gestures. Tapping is fine, but we need to find a fix for the gesture conflict somehow. I'm perfectly fine with removing the swipe gesture completely.

**Comment by Stypox** [comment] 2020-10-05 19:40
But removing the gesture would remove a comfortable action for people who do not have navigation gestures

**Comment by opusforlife2** [comment] 2020-10-05 19:42
Can Newpipe detect if the user has OS gestures enabled and disable swipe only for that case?

**Comment by Oizaro** [comment] 2020-10-06 11:45
> Can Newpipe detect if the user has OS gestures enabled and disable swipe only for that case?

Why don't move timebar a bit up? This could fix the problem.

**Comment by opusforlife2** [comment] 2020-10-06 12:00
Timebar?

**Comment by Oizaro** [comment] 2020-10-06 12:04
> Timebar?

Timbar/Seekbar/The way to select the exacting minute and second of a video

**Comment by opusforlife2** [comment] 2020-10-06 12:05
We're talking about the minimised player here, though? Where is the seekbar?

**Comment by Oizaro** [comment] 2020-10-06 12:07
> We're talking about the minimised player here, though? Where is the seekbar?

Oh sorry... I got the wrong issue report.

**Comment by opusforlife2** [comment] 2020-10-06 12:14
You were thinking of #4419, probably. :P

**Comment by streaps** [comment] 2020-10-10 12:43
The changes in 0.20 are super annoying and confusing. Were can I disable the minimized player?

**Comment by avently** [comment] 2020-10-14 20:37
@opusforlife2 
>I'm perfectly fine with removing the swipe gesture completely.

You often tries to find a solution for new issues without thinking of people who like current behavior and whom this behavior is made for. It's kind of wrong solution, isn't it?

**Comment by opusforlife2** [comment] 2020-10-15 04:51
Hey, no issues with discussion though, right? It's not like the moment I post my comment the behaviour will be changed. These are just possibilities. Since you say you want this behaviour, I might think of a different solution at some point. Or someone else will.

**Comment by Stypox** [comment] 2020-10-16 18:59
@andrespalumbo311 may I ask you how YouTube handles this situation? If they do it the same way NewPipe currently does it, I think we should not change this behaviour as probably a team of ui experts decided it was good and standardized it

**Comment by andrespalumbo311** [comment] 2020-10-17 09:38
> @andrespalumbo311 may I ask you how YouTube handles this situation? If they do it the same way NewPipe currently does it, I think we should not change this behaviour as probably a team of ui experts decided it was good and standardized it

![photo_2020-10-17_11-38-17](https://user-images.githubusercontent.com/68204348/96333944-4af54600-106d-11eb-9b13-ace50806b574.jpg)

**Comment by MD77MD** [comment] 2020-10-17 10:43
![Screenshot_20201017-133139](https://user-images.githubusercontent.com/63132171/96334944-2dc87380-107d-11eb-92a1-93bb58553e56.png)
@Stypox 
>@andrespalumbo311 may I ask you how YouTube handles this situation? If they do it the same way NewPipe currently does it, I think we should not change this behaviour as probably a team of ui experts decided it was good and standardized it

i think this is the best middle solution, using minimize video... its big enough that we can make it only 2/3 swipable from the top...

 but isn't so wasteful as you benefit from seeing complete video

**Comment by MD77MD** [comment] 2020-10-17 11:06
we could also do this

![Uploading 20201017_140524.png…]()

**Comment by LunarLanding** [comment] 2021-03-31 09:57
I have a related issue that is very annoying ui-wise. Whenever I open newpipe while using the background player, the position of the seek bar is so close to the bottom of the screen that whenever I use the system swipe gestures for home/back/recents the seek position is changed. 
![Screenshot_20210331-105108_NewPipe](https://user-images.githubusercontent.com/4441338/113126319-6f09a580-920f-11eb-93f6-14fb89e13d14.jpg)
Pushing it up by 1cm or putting the seek bar on top, the play/skip buttons on the bottom would solve it.

**Comment by opusforlife2** [comment] 2022-04-08 20:50
Is this still a problem?

**Comment by avently** [comment] 2022-04-09 02:44
@opusforlife2 I would say yes. In my case I have disabled bottom handle of Android (thin navigation bar), so I don't have a pill underneath of any app. Just clean app window. In this case it's hard to swipe mini player up without triggering Android gestures. So instead of swipe I use a click on mini player.

But I still don't think we should do anything with it unless someone create something beautiful and unique look for mini player that both fixes it problem and more useful than current mini player

**Comment by LunarLanding** [comment] 2022-04-09 09:32
It is still a problem. I think it should be fixed, and it doesn't need to be part of some other change. All that needs to be done is shift the interface up an inch if the app is in full screen mode (ie home/back/recents buttons are hidden).

**Comment by opusforlife2** [comment] 2022-04-09 15:14
That's a bigger task than a simple bug fix, then. It would need discussion on the appropriate UI changes.

**Comment by MD77MD** [comment] 2022-04-11 10:29
@avently like this
![96334944-2dc87380-107d-11eb-92a1-93bb58553e56](https://user-images.githubusercontent.com/63132171/162721972-9e7113af-1118-4a33-b46a-1bd830362ad7.png)

**Closed** 2022-04-23 00:11 UTC
Labels: bug, GUI, player, waiting-for-author
