### ISSUE TITLE
Please accept paypal for donations

### ISSUE THREAD

**Issue by ElenaXX** [TeamNewPipe/NewPipe#7886] opened 2022-02-16 19:12 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Please accept paypal for donations. I would have already donated otherwise since (despite the very poor support) Newpipe deserves it. But not every people has bitcoins or such things while almost everybody has paypal. Thanks

### Why do you want this feature?

I think I have already said it above

**Comment by mhmdanas** [comment] 2022-02-17 13:21
Duplicate of #2698.

**Closed by mhmdanas** 2022-02-17 13:21 UTC
Labels: enhancement
