### ISSUE TITLE
Unrecoverable player error occurred

### ISSUE THREAD

**Issue by SubharthiChatterjee** [TeamNewPipe/NewPipe#6700] opened 2021-07-19 02:37 UTC
On clicking play icon on video content, shows error 'Unrecoverable player error occurred'

### Checklist

- [x] I am using the latest version - 0.21.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to a video link
2. Click play button on Video Content

### Actual behavior

1. Video loader stops loading 
2. Error pops up at the bottom, says "Unrecoverable player error occurred"

### Expected behavior
On click video should play

### Device info

 - Android version/Custom ROM version: 8.1.0
 - Device model: Oneplus A5010

**Comment by mhmdanas** [comment] 2021-07-19 12:00
Duplicate of #5426.

**Closed by mhmdanas** 2021-07-19 12:00 UTC
Labels: bug

**Comment by mhmdanas** [comment] 2021-07-19 12:01
Try rebooting your device; it might fix the issue.
