### ISSUE TITLE
Videos playing in the background randomly stop

### ISSUE THREAD

**Issue by TheMCNerd2017** [TeamNewPipe/NewPipe#7535] opened 2021-12-13 01:26 UTC
### Checklist

- [x] I am using the latest version - 0.21.14 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to any video
2. Click on the Background button to start playing the video in the background
3. Wait a few minutes. You can do anything during this time or let the device idle. The video should stop playing on it's own and the Android media notification may still show the pause button as if the video is playing normally. Sometimes it shows the hourglass instead as if the video is loading despite the video already being loaded. If the issue doesn't happen try another video, as the issue seems to happen randomly and at random times.

### Actual behavior

Whatever video is playing in the background stops and the Android media notification sometimes still shows the pause icon as if the video is still playing. Trying to make the video play by clicking pause/play does not work and actually causes the Android media notification to become out of sync with NewPipe (possibly another bug). Scrubbing in the Android media notification to any time makes the video resume playing at the time you've scrubbed to, though the audio may become distorted.

### Expected behavior

Whatever video is playing in the background should continue to play until the video ends.

### Device info

 - Android version/Custom ROM version: GrapheneOS 12 (SQ1A.211205.008.2021121012)
 - Device model: Pixel 4 XL

**Comment by TheMCNerd2017** [comment] 2021-12-13 03:11
OK turns out this issue happens regardless of whether the device is locked or not, and resuming playback by scrubbing sometimes results in the audio becoming distorted.

**Comment by genesisaix** [comment] 2021-12-13 09:53
I can confirm the exact same behavior on 0.21.14;
- running sound in background and it somewhat randomly (10min+) freeze, I am guessing it has something to do with end of buffer
- sound gets distorted afterwards if I manage to resume; low volume (on same volume bar) or noisy
- Closing the application allow for another 10-13ish minutes of error-free listening

Samsung S10 (8gb ram)
Android 11 / 1.june 2021
Kernel 4.14.113-22340597

/love to all of Newpipes contributors

**Comment by adueppen** [comment] 2021-12-13 23:46
I'm experiencing this behavior as well, only on 0.21.14. Tracks are stopping randomly after 5-10 minutes and when I try to bring them back by either scrubbing back in the track or skipping to the next one, it comes back with extremely low-quality distorted audio only in my left ear.

Device: Pixel 5a, Android 12 2021-11-05 with kernel 4.19.191-g7a0aca88361d-ab7709095

**Comment by timsu92** [comment] 2021-12-14 14:06
Me too on 0.21.14. However, I'm not facing this as same time as other people's. I listen to lots of music containing short singles and long albums, and all those randomly stop somewhere in the last minute.
Furthermore, I paused and played a song the other day, and the music played on right ear only but not distorted.

Device: Samsung S21, Android 11, stock rom, kernel 5.4.61-qgki-22265714

**Comment by x1n1t** [comment] 2021-12-14 21:22
i can confirm the same behavior on this exact version
a playlist plays in background for few minutes  and then randomly stops. if i manage to resume it plays with noticeable distortions until i reopen the app

**Comment by drewsat** [comment] 2021-12-16 00:25
Yep I have this issue as well

**Comment by ssaagamemer** [comment] 2021-12-16 05:08
same and notification not show

**Comment by LicoriceTea** [comment] 2021-12-16 08:49
Same thing, would stop right before the end of a song. Had distorted sound once that made me think I blew a speaker. 
I turned off 'remember popup properties' and it hasn't happened again

**Comment by NoahJelen** [comment] 2021-12-19 03:39
I have this same problem except newpipe buffers to hell too. I'm using a Pixel 3a XL with CalyxOS (Android 11).

**Comment by Danielmb87** [comment] 2021-12-22 09:33
I have the same issue which makes listening to music a rather frustrating task.

This issue sounds very similar, could it be the same issue? I wasn't able to download the apk and try it (definitely operator error, haha) but maybe someone else could try it to see if it resolves the issue:
https://github.com/TeamNewPipe/NewPipe/issues/7529

**Comment by TiA4f8R** [comment] 2021-12-22 17:52
Please test if the APK of #7555 solved the issue and let us know here.

**Comment by andrewferguson** [comment] 2021-12-23 11:16
@TiA4f8R I tried out #7555's APK this morning and it has resolved the issue for me.
Great job on such a quick fix!

**Comment by timsu92** [comment] 2021-12-23 15:24
@TiA4f8R Mostly running well in totally 4 hours today, expect it paused several times tonight, but resumed in few seconds after I lit up the screen. However, the network is still connected before I lit it up as I can see it in my laptop which was sharing its internet access through WIFI.
After some minutes of encountering the situation above, it popped-up a notification saying that it encountered socket timeout, and this is the formatted report: [error_log.txt](https://github.com/TeamNewPipe/NewPipe/files/7770123/error_log.txt)

**Comment by TheMCNerd2017** [comment] 2021-12-23 22:28
@TiA4f8R Do I need to uninstall the current version of NewPipe on my mobile device before I try out the test APK of #7555? Also do I need to be signed-in to download it? The "app" text in the Artifacts section on my mobile device isn't clickable for some reason.

**Comment by TiA4f8R** [comment] 2021-12-23 23:10
@TheMCNerd2017

> Do I need to uninstall the current version of NewPipe on my mobile device before I try out the test APK of #7555?

No, this APK will be installed as a separate app.

> Also do I need to be signed-in to download it?

Yes, unfortunately, you need to be logged on GitHub (that's not a restriction within our control).

> The "app" text in the Artifacts section on my mobile device isn't clickable for some reason.

Then use this direct link to the APK instead: https://github.com/TeamNewPipe/NewPipe/suites/4706181150/artifacts/128965460

**Comment by TheMCNerd2017** [comment] 2021-12-24 02:09
@TiA4f8R OK, I'll install the test APK and use it for a while and see if the issue is fixed. Also the reason the text in the Artifacts section was not clickable on my mobile device was because I was not signed in (and the direct link gives a 404 error as well, also because I was not  signed in). I was able to download it on my desktop.

**Comment by TheMCNerd2017** [comment] 2021-12-24 05:51
@TiA4f8R Alright I've used the test APK for a while now and the issue doesn't come up.

**Comment by genesisaix** [comment] 2021-12-24 09:39
@TiA4f8R I downloaded the APK from your link and can confirm that the issues described earlier no longer prevail here. Thanks for the information on how to go about to download this.

I will add a tip for others; if you install this particular versions it will be an addition to the main app. I first thought my subscription-list was gone, but it is still there in the main app.

**Comment by TiA4f8R** [comment] 2021-12-24 09:52
This fix is included on the new version we released, 0.21.15. Download it to get ride of this issue!

Closing this issue as a duplicate of #7529, which has been fixed with #7555.

**Closed by TiA4f8R** 2021-12-24 09:52 UTC
Labels: bug
