### ISSUE TITLE
Videos always stay inqueue

### ISSUE THREAD

**Issue by mouarfff** [TeamNewPipe/NewPipe#2433] opened 2019-06-29 12:58 UTC
Hello,

each time i download a video, this video stay in queue and i need to force start to begin it.

homtom HT7 android android 7 and last version of newpipe 0.16.2

thx !

**Comment by Neodymium5312** [comment] 2019-06-29 14:36
duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2072
known issue caused by vpn

**Closed** 2019-06-29 16:36 UTC
