### ISSUE TITLE
Select all videos to add to enqueue option

### ISSUE THREAD

**Issue by komals1** [TeamNewPipe/NewPipe#8272] opened 2022-04-21 05:14 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

To play all daily feed is it possible to have an option which help to select all feed videos and then can be added to enqueue

### Why do you want this feature?

Can help more easily create a enqueue list from feed

### Additional information

with this one can multi select or select all video from feed and and it to the enqueue list . kind of actions we have in file explorer.
![Screenshot_2022_0421_104314](https://user-images.githubusercontent.com/73154889/164376873-81f84760-5f00-4596-942d-a23e7550de25.png)

**Comment by SameenAhnaf** [comment] 2022-04-21 06:17
Are you asking this feature especifically for feeds? If so, it's a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3362

**Comment by komals1** [comment] 2022-04-22 06:38
yes,

**Comment by SameenAhnaf** [comment] 2022-04-22 06:43
You may close this issue as it is already asked by other users.

**Closed** 2022-04-23 15:22 UTC
Labels: enhancement
