### ISSUE TITLE
Crash when opening video from lqdn.fr

### ISSUE THREAD

**Issue by Discostu36** [TeamNewPipe/NewPipe#7847] opened 2022-02-09 13:42 UTC
### Checklist

- [x] I am using the latest version - 0.21.16 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Click on the link https://video.lqdn.fr/w/eWVHM1L96VBZ84A4xmty9n
2. Choose that Newpipe as the app that should open the link

### Actual behavior

The app crashes

### Expected behavior

The video is played

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.21.16
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:488)
	at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:503)
	at org.schabi.newpipe.util.ListHelper.$r8$lambda$UGNhfSv5KuYwsqrcThyeG189sI0(Unknown Source:0)
	at org.schabi.newpipe.util.ListHelper$$ExternalSyntheticLambda0.compare(Unknown Source:4)
	at java.util.Collections$ReverseComparator2.compare(Collections.java:5235)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at org.schabi.newpipe.util.ListHelper.sortStreamList(ListHelper.java:269)
	at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:243)
	at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:130)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1602)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6(VideoDetailFragment.java:913)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$X-UcNln23jPsop2TvHe2VPTu0NQ(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda11.accept(Unknown Source:8)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7715)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2022-02-09 13:48
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6860.

**Closed by mhmdanas** 2022-02-09 13:48 UTC
Labels: bug
