### ISSUE TITLE
Fails to load some results in what's new screen

### ISSUE THREAD

**Issue by Younes-L** [TeamNewPipe/NewPipe#3439] opened 2020-04-15 11:15 UTC
### Version

- 0.19.2 

### Steps to reproduce the bug

1. Go to 'what's new'
2. Press on 'refresh (refresh button)'

 says couldn't load 1 result (with snackbar to report the problem)

### Screenshots/Screen recordings

![Screenshot_20200415-120636_cropped](https://user-images.githubusercontent.com/23421600/79331067-7fe3dd00-7f12-11ea-9ace-6acee2b3ecd3.png)

### Logs ("converted" through NPE to Markdown converter)

 {
   "user_action": "requested feed",
   "request": "Loading feed",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.19.2",
   "os": "Linux Android 9 - 28",
   "time": "2020-04-15 11:03",
   "exceptions": [
      "org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 1:https:\/\/soundcloud.com\/epicmountain\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:220)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:63)\n\tat io.reactivex.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:113)\n\tat io.reactivex.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)\n\tat io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: java.lang.RuntimeException: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response\n\tat io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)\n\tat io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:91)\n\tat io.reactivex.Single.blockingGet(Single.java:2700)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:214)\n\t... 11 more\nCaused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudChannelExtractor.onFetchPage(SoundcloudChannelExtractor.java:42)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:46)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:128)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.Single.blockingGet(Single.java:2699)\n\t... 12 more\nCaused by: com.grack.nanojson.JsonParserException: Expected JSON value, got EOF on line 1, char 0\n\tat com.grack.nanojson.JsonParser.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonParser.currentValue(Unknown Source:30)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:3)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:15)\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudChannelExtractor.onFetchPage(SoundcloudChannelExtractor.java:40)\n\t... 21 more\n"
   ],
   "user_comment": ""
}

**Comment by Stypox** [comment] 2020-04-15 19:15
This is an issue with soundcloud. Does it happen every time? Reloading should solve the issue if that's not the case

**Comment by Stypox** [comment] 2020-04-15 19:16
Duplicate of #2915

**Closed by Stypox** 2020-04-15 19:16 UTC
Labels: bug

**Comment by Younes-L** [comment] 2020-04-15 20:17
> This is an issue with soundcloud. Does it happen every time? Reloading should solve the issue if that's not the case

Although at the time of a submitting the issue, reloading multiple times did not help, it seems to work fine now after a cold start. New uploads have been posted since then, but none this week of SoundCloud origin (just to clarify, I had no new activity from soundcloud that might have caused this, but I'm no pro either ^^ )

I did search in issues and thought the older parsing issue was fixed, sorry for duplicate 😬

**Comment by Younes-L** [comment] 2020-04-24 23:34
It's happening again, and like last time, no new SoundCloud upload

Here's the log from "report" button 
{
   "user_action": "requested feed",
   "request": "Loading feed",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.19.2",
   "os": "Linux Android 9 - 28",
   "time": "2020-04-24 23:33",
   "exceptions": [
      "org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https:\/\/www.youtube.com\/channel\/UCg6ubQnooDRFTQvKEy-ZK8g\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException$Companion.wrapList(FeedLoadService.kt:162)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1$1.run(FeedLoadService.kt:311)\n\tat androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:386)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:300)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:63)\n\tat io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)\n\tat io.reactivex.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onComplete(FlowableBuffer.java:152)\n\tat io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:215)\n\tat io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)\n\tat io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get duration\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.getDuration(YoutubeStreamInfoItemExtractor.java:127)\n\tat org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:54)\n\tat org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:94)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.collectStreamsFrom(YoutubeChannelExtractor.java:280)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getInitialPage(YoutubeChannelExtractor.java:233)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:82)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:47)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:128)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.Single.blockingGet(Single.java:2699)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:214)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:63)\n\tat io.reactivex.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:113)\n\tat io.reactivex.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)\n\tat io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)\n\t... 7 more\n"
   ],
   "user_comment": ""
}
