### ISSUE TITLE
Videos are not loading 

### ISSUE THREAD

**Issue by Gul7333** [TeamNewPipe/NewPipe#8878] opened 2022-08-25 04:18 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

23.2

### Steps to reproduce the bug

Open new pipe...
Video thumbnail are showing..
But when you click on any video ... video start loading...but it doesn't load

### Expected behavior

Video should load.... videos are not loading 

### Actual behavior

Videos are loading

**Comment by codetalker101** [comment] 2022-08-25 04:24
Duplicate of #8876

**Comment by WIMMPYIII** [comment] 2022-08-25 04:27
Same. Nothing will load.

**Comment by ktbloomq** [comment] 2022-08-25 04:32
I am also noticing this.

**Comment by xalienxx** [comment] 2022-08-25 04:58
Yes. Same here

**Comment by PrincessMiki** [comment] 2022-08-25 06:14
Same

**Comment by Master2050** [comment] 2022-08-25 06:15
Having same issue, [debug build by @Theta-Dev](https://github.com/TeamNewPipe/NewPipe/files/9387795/app-debug.zip) in https://github.com/TeamNewPipe/NewPipe/issues/8839 seems to have fixed the issue.

**Closed** 2022-08-25 06:41 UTC
Labels: bug, needs triage
