### ISSUE TITLE
Hold the video to get a download option

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#6748] opened 2021-07-24 00:26 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

as the title says, hold the video to get a download option

#### Is your feature request related to a problem? Please describe it

currently, we get options like add to playlist, share, etc. we should also get an option to download quickly because now, we have to click on the video to get an option for downloading

#### How will you/everyone benefit from this feature?

this would be helpful if we are currently watching a video and wanna download another video, like when scrolling through subscription feed, I am watching youtuber a video, and there is another video below this, I could just hold the video to get an option to download like we have to share and etc.

**Comment by mhmdanas** [comment] 2021-07-24 00:31
Duplicate of #2171.

**Closed by mhmdanas** 2021-07-24 00:31 UTC
Labels: enhancement
