### ISSUE TITLE
[feature request] support Android TV

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#2897] opened 2019-12-27 22:46 UTC
Hello, 
<sub>(might be related to https://github.com/TeamNewPipe/NewPipe/issues/2347) </sub>
I wish there would be an official support for the Android <strong>TV layout</strong>. 
Currently the application sometimes opens up vertical on the tv, 
and button-background is not very clear, and some items are unreachable.

Thanks.

**Comment by Stypox** [comment] 2019-12-28 16:51
Duplicate of #1363

**Closed by Stypox** 2019-12-28 16:51 UTC
