### ISSUE TITLE
Most YouTube videos is unavailable even though video is available in Youtube. 

### ISSUE THREAD

**Issue by teddong9281** [TeamNewPipe/NewPipe#2900] opened 2019-12-28 09:12 UTC
Various videos have sent the prompt ' Content Unavailable ' even though the video is playable in YouTube app. No other information such as description, next video etc is missing. However comment section is present. I didn't bother to give out a screenshot as it is a normal prompt and there is no crash. Hope the problem is fixed.

**Comment by Stypox** [comment] 2019-12-28 17:17
Which NewPipe version are you using? Do you have age restrictions enabled?

**Comment by randomshell** [comment] 2019-12-30 03:49
@Stypox I noticed it too on latest v0.18.0. Age restrictions settings doesn't matter.

Video example https://m.youtube.com/watch?v=g5FloMq9Lck

**Comment by tamirOK** [comment] 2019-12-30 04:19
@randomshell I am using the same version as yours. Your video example is working on my device.

**Comment by randomshell** [comment] 2019-12-30 05:14
What should I look for in the logcat? I tried with verbose filter and the debug apk of newpipe but I can't find info on why the content is unavailable.

There is a `E/WindowManager Activity org.schabi.newpipe.RouterActivity has leaked window DecorView@29e2202[] that was originally added here`, but I don't think it's related.

**Comment by cool-student** [comment] 2019-12-30 08:20
just a note "Content Unavailable" also happens when a video is a scheduled stream in the future even though that might not be related to these "Content Unavailable" errors.

**Comment by randomshell** [comment] 2019-12-30 18:33
The network I used had a family filter dns and the browser was configured with an uncensored DoH server, this is why it worked there and not on newpipe. Sorry about this.

**Comment by mendyz** [comment] 2020-01-18 01:53
Been having the same issue on every video for the same 20+day duration. No idea why. I didn't post initially because it was on music videos and figured yt changed sometime and broke music videos, as can happen. But now it's been long, and i fell into this thread. Makes the app completely unusable, and I'm not sure where to start resolving this. Please help.

**Comment by Stypox** [comment] 2020-01-18 06:39
Update to 0.18.0

**Comment by mendyz** [comment] 2020-01-19 04:14
Thank you! Fixed now. 
Seemed simple, just update. Of course I did that. For both fdroid and new pipe. But apparently what threw me off was fdroid was telling me I was up to date. I never checked to see if there were newer versions. Fdroid just wasn't updating it's packages properly and I didn't see that it wasn't getting it's repositories when I told it to. After deleting both and restarting my phone, i installed both again and fdroid showed version 18 for new pipe. Installed. Everything works now. 
Thank you!

**Comment by gillhash** [comment] 2020-02-01 12:33
Latest test apk given in #2309  PR shows empty "Show info" page with "both video content unavailable" "Some errors occurred, " message. This occurs on 1 out of 10 videos i try to watch, Which can be played in the browser.
After Search clicking on playlist in error report then this video:-
https://www.youtube.com/watch?v=ACOLT3z6Kag
Gives blank page with sad face.

Error Report
{
   "user_action": "requested playlist",
   "request": "https:\/\/www.youtube.com\/playlist?list=PL-e1nvB0oq_y-Fr0nnzMw3dInAkMJ0szX",
   "content_language": "GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe.pr2309",
   "version": "0.420.6969",
   "os": "Linux Android 6.0.1 - 23",
   "time": "2020-02-01 09:21",
   "exceptions": [
      "org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get durationhttps:\/\/www.youtube.com\/watch?v=ACOLT3z6Kag\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor$1.getDuration(YoutubePlaylistExtractor.java:238)\n\tat org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:54)\n\tat org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:94)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.collectStreamsFrom(YoutubePlaylistExtractor.java:198)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.getInitialPage(YoutubePlaylistExtractor.java:131)\n\tat org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:20)\n\tat org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:98)\n\tat org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:30)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getPlaylistInfo$9(ExtractorHelper.java:176)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$_QwiJvTe_SoIGFHJ5lSdqLNGnh8.call(lambda)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)\n\tat java.lang.Thread.run(Thread.java:818)\nCaused by: java.lang.NumberFormatException: Invalid long: \"7,257\"\n\tat java.lang.Long.invalidLong(Long.java:124)\n\tat java.lang.Long.parse(Long.java:363)\n\tat java.lang.Long.parseLong(Long.java:353)\n\tat java.lang.Long.parseLong(Long.java:321)\n\tat org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeParsingHelper.parseDurationString(YoutubeParsingHelper.java:119)\n\tat org.schabi.newpipe.extractor.services.yout

**Closed** 2020-05-06 16:43 UTC
Labels: bug, more info needed, youtube
