### ISSUE TITLE
Cause fatal failure in sudden random moments.

### ISSUE THREAD

**Issue by toto1444** [TeamNewPipe/NewPipe#5537] opened 2021-02-07 11:30 UTC
### Checklist

- [X] I am using the latest version - 0.20.8 
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
* There is one report that has similar log of mine, but the crash happens in different situation.

- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

I have no clue what so ever, I could not diagnose the problem by myself. 
For that reason, I have no idea whatsoever to reproduce this bug again artificially. 

### Actual behaviour

A. While playing random video. 
B. In sudden moment, app itself causing fatal crashes.

### Expected behavior

It should play video normally. 

### Logs

While playing video, it happens regularly. 
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7080)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7615)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: G710

**Comment by vkay94** [comment] 2021-02-07 13:25
>There is one report that has similar log of mine, but the crash happens in different situation.

Could you describe the different situation it little bit more? The issue you refer is probably list related, isn't it?

**Comment by mhmdanas** [comment] 2021-02-07 14:57
@toto1444 I believe this is a duplicate of #4475 (presumably the report you mentioned). The bug reported in that issue can happen in a bunch of places, which is why I think this is a duplicate. If you disagree, feel free to write a comment.

**Closed by mhmdanas** 2021-02-07 14:57 UTC
Labels: bug
