### ISSUE TITLE
Subscriber bugg

### ISSUE THREAD

**Issue by Arthurdw** [TeamNewPipe/NewPipe#2691] opened 2019-10-04 20:30 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

The subscriber count isnt right. (idk y)
![Screenshot_20191004_222708_org schabi newpipe](https://user-images.githubusercontent.com/38541241/66237890-7ae9d980-e6f6-11e9-9691-8db837709d0a.jpg)

**Comment by omarroth** [comment] 2019-10-04 21:46
Duplicate of #2632, should be fixed with TeamNewPipe/NewPipeExtractor#196 (likely as part of the next release).

**Closed** 2019-10-05 05:11 UTC
