### ISSUE TITLE
Add "Download" option to context menu

### ISSUE THREAD

**Issue by Beep6581** [TeamNewPipe/NewPipe#3270] opened 2020-03-25 13:35 UTC
Click-and-hold any video so that the context menu pops up. Please add "Download" to the context menu, so that we can easily download the audio without opening each video.

**Comment by Stypox** [comment] 2020-03-25 14:06
Duplicate of #2171
You can provide some feedback in #2583 if you want ;-)

**Closed by Stypox** 2020-03-25 14:06 UTC
Labels: enhancement
