### ISSUE TITLE
reCAPTCHA challenge requested but 405 error shows when pressing "solve"

### ISSUE THREAD

**Issue by madimura20** [TeamNewPipe/NewPipe#8190] opened 2022-04-12 19:39 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Launch NewPipe as normal (through app icon or YT link).
2.  "ReCAPTCHA challenge Requested" shows up. Press "Solve".
3. Instead of a CAPTCHA, a Google page with this text appears: "405. That’s an error. The request method GET is inappropriate for the URL /youtubei/v1/guide. That’s all we know.
4. Tried clearing cache, restarting device, and reinstalling the app, no luck, still ends up with a "solve reCaptcha" request leading to a 405 page.

### Expected behavior

1. Launch app through icon or YT link.
2. Home page should show up with trending videos, and video playback and other functions should show as well.
3. If asked to solve a CAPTCHA, pressing Solve should lead to a CAPTCHA page, and normal functionality should be restored upon completion.

### Actual behavior

"Recaptcha challenge requested" page shows up upon launching app, but proceeding with "Solve" leads to a Google Error 405 page instead of a CAPTCHA challenge, making it impossible to use the app as normal. "Retry" button still leads to the same situation.

### Logs

From Recaptcha page:
Google
405. That’s an error.

The request method GET is inappropriate for the URL /youtubei/v1/guide. That’s all we know.

### Affected Android/Custom ROM version

Android 12, latest updates March 2022

### Affected device model

Google Pixel 6 Pro

### Additional information

This happens when using cellular mobile data. Unable to test on WiFi at the moment.

**Comment by delthas** [comment] 2022-04-12 19:39
Duplicate of #8183

**Closed** 2022-04-12 19:40 UTC
Labels: bug

**Comment by Tiger12395** [comment] 2024-10-29 18:22
It happend to me too just today for the hole day!
![Screenshot_20241029_201740_Tubular](https://github.com/user-attachments/assets/bdec59ed-6cb4-40fa-a61b-988fe65bbc88)
![Screenshot_20241029_201731_Tubular](https://github.com/user-attachments/assets/ad7e4e64-6d38-45a8-acf0-1df21d5ad8c3) 
It might look like it happend in tubular but I tried also newpipe regularly twice and for hole day and reinstalling and still happening!
I tried on Samsung A13 with the latest update of October 2024.
