### ISSUE TITLE
Playback autoresumes after unlocking phone when in full screen 

### ISSUE THREAD

**Issue by Kromppo** [TeamNewPipe/NewPipe#6971] opened 2021-08-25 00:28 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Start playing any video in FULL SCREEN mode
2. Lock the phone screen while the video is playing or paused (doesn't matter)  but still in full screen
3. Unlock the phone

### Actual behavior
The video continues playback after the phone was locked and stopped the playback. Even if the video was paused but in full screen mode when the phone was locked, it starts to play again. 

### Expected behavior
The playback should stay paused until you hit play again, unless you have the "resume playback" feature enabled. 

### Device info

 - Android version/Custom ROM version: Andoird 11 OxygenOS 11.0.11
 - Device model: OnePlus 8T+5G KB2007 (TMobile Version)

**Comment by ShareASmile** [comment] 2024-02-17 18:39
Closing this issue as I cannot reproduce. 

If you still experience this issue in 0.26.1, pleade feel free to comment here I will reopen it. Thank you.

**Closed** 2024-02-17 18:39 UTC
Labels: bug
