### ISSUE TITLE
Switching to main from popup player shows wrong video

### ISSUE THREAD

**Issue by SameenAhnaf** [TeamNewPipe/NewPipe#6684] opened 2021-07-16 11:15 UTC
### Checklist

- [x] I am using the latest version - 0.21.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start playing a video or queue on popup player
2. Open any other video info
3. Switch the popup player to main player

### Actual behavior

As of the screen recording, video with brown thumbnail shows although the blue one is on popup player.

### Expected behavior

Video or queue on popup player should switch to main player.

### Screenshots/Screen recordings

https://drive.google.com/file/d/15ag_JQGHWPju0bnN5qZrPzu6DS-g-lAR/view?usp=drivesdk

### Device info

 - Android version/Custom ROM version: Android 11, MIUI 12.5.1
 - Device model: Xiaomi Redmi Note 8 Pro

**Comment by mhmdanas** [comment] 2021-07-16 12:00
Duplicate of #6400.

**Closed by mhmdanas** 2021-07-16 12:00 UTC
Labels: bug
