### ISSUE TITLE
Email address for reporting crashes does not work

### ISSUE THREAD

**Issue by ElenaXX** [TeamNewPipe/NewPipe#7821] opened 2022-02-05 18:36 UTC
I am using the latest version on my Samsung s7 edge phone.
Often I am plagued by the "Sorry something went wrong ->REPORT" popup, even when a video loads fine. This always happened.
However the issue is that the email address <crashreport@newpipe.schabi.org> which is used automatically if I select "REPORT" does not work ! Email are rejected suddently with the error message
"Reason: GNiGnd21siF0aGNiGns6Uz we are sorry your message hasn't been delivered. Destination server replied: 530 5.7.0. Must issue a STARTTLS command first"
Please fix this annoyance, thanks. This always happened, it is NOT something introduced recently.

**Comment by mhmdanas** [comment] 2022-02-05 20:25
Please do not remove the issue template, it's there for a reason.

What version of NewPipe are you using? I want the exact version please.

**Comment by ElenaXX** [comment] 2022-02-05 21:16
As I said it is the last version, 0.21.16.
As I also said, the non working email address never worked for me since I started using NP one year ago, so the version doesn't really matter I think...
-- Elena

**Comment by mhmdanas** [comment] 2022-02-05 21:23
> As I said it is the last version, 0.21.16.

I've actually had people before thinking that they used the latest version, but they weren't. This is a just-in-case check.

> As I also said, the non working email address never worked for me since I started using NP one year ago, so the version doesn't really matter I think...

We have been (and still are) receiving reports through the e-mail, so I'm pretty sure it's something on your side. According to https://stackoverflow.com/questions/10509699/must-issue-a-starttls-command-first, it's probably because you're trying to send an e-mail through an unauthenticated connection. I have no idea how you can switch to an authenticated connection there though, so I don't know how I can help you there.

**Comment by ElenaXX** [comment] 2022-02-05 21:43
Strange, such a thing never happened to me with emails before. However sorry for the hassle and thanks for your quick feedback. At least you now confirmed that the email address is working. I will carry further tests then.
-- Elena

**Comment by opusforlife2** [comment] 2022-02-05 21:48
Closing as resolved for now. Please leave a comment if the issue needs to be reopened.

**Closed by opusforlife2** 2022-02-05 21:48 UTC
Labels: bug, template-ignored

**Comment by mhmdanas** [comment] 2022-02-06 11:09
My comment was more of a guess, not a 100% confirmed reason.
