### ISSUE TITLE
[Feature Request] Cloud sync of settings, backup/restore via Dropbox | Google Drive

### ISSUE THREAD

**Issue by ondernuray** [TeamNewPipe/NewPipe#3754] opened 2020-06-06 19:07 UTC
#### Describe the feature you want

It might be useful if we sync backup/restore subscription and settings via Dropbox | Google Drive, cross sync on multiple devices simultaneously.

#### Is your feature request related to a problem? Please describe it

No

**Comment by B0pol** [comment] 2020-06-06 19:18
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1163

**Closed by B0pol** 2020-06-06 19:18 UTC
