### ISSUE TITLE
video unavailable :( but in browser all fine

### ISSUE THREAD

**Issue by f242** [TeamNewPipe/NewPipe#2988] opened 2020-01-24 06:55 UTC
https://youtu.be/YR9b9NyOi1g
in v.18.2  i see splash with text "video unavailable :(", in previous v.18.1 was something like crash in this case but in browser it playing fine without authorization

**Comment by WheresAlice** [comment] 2020-01-24 07:25
Possible duplicate of #2981 - please provide more information if that doesn't apply

**Comment by f242** [comment] 2020-01-24 07:32
i think is not duplicate because link from #2981 playing fine

**Comment by Stypox** [comment] 2020-01-27 18:52
Duplicate of #2900

**Closed by Stypox** 2020-01-27 18:52 UTC
