### ISSUE TITLE
Trending page not loading

### ISSUE THREAD

**Issue by AnXh3L0** [TeamNewPipe/NewPipe#6839] opened 2021-08-04 07:23 UTC
Trending page not loading any content
## Exception
* __User Action:__ requested kiosk
* __Request:__ Start loading: https://www.youtube.com/feed/trending
* __Content Country:__ AL
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.21.8
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get Trending name
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.getName(YoutubeTrendingExtractor.java:87)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:70)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:58)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:184)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$NbG7JFGg0N9HK-3exJNRB9r_hYY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

**Comment by TiA4f8R** [comment] 2021-08-04 10:58
YouTube gived me a 500 error with the content country AL. Looks like the Albania country is not supported by Trending pages: it doesn't appear in YouTube country selection:

![image](https://user-images.githubusercontent.com/74829229/128168272-dd4186de-f4b2-45d9-a23e-7484e2f1aef8.png)

As a workaround, try switching the default content country in Settings, Content to a valid country (check the list provided on YouTube website).

Also, please don't remove the template when opening an issue.

**Comment by AnXh3L0** [comment] 2021-08-04 11:41
Maybe YouTube changed things or there's an issue with NewPipe. Last version (namely 0.21.7) worked just fine with Albania chosen as the trending page.

**Comment by mhmdanas** [comment] 2021-08-04 11:46
There have been some massive changes in the extractor related to YouTube (TeamNewPipe/NewPipeExtractor#604), which is probably the cause for these errors.

**Comment by ShareASmile** [comment] 2022-09-03 09:06
@mhmdanas.. still open? it was fixed long time ago.
I think we forgot to close it. I think Automatic closing the issues was brought later in the repository.

**Closed** 2022-09-18 00:16 UTC
Labels: bug, youtube, requires extractor change, template ignored, waiting for author
