### ISSUE TITLE
YoutubeStreamExtractor$DecryptException

### ISSUE THREAD

**Issue by cion49235** [TeamNewPipe/NewPipe#2262] opened 2019-04-02 07:29 UTC
org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function 
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:739)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:614)
        at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
        at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
        at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
        at io.reactivex.Maybe.subscribe(Maybe.java:4154)
        at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
        at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
        at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
        at io.reactivex.Flowable.subscribe(Flowable.java:14479)
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
        at io.reactivex.Maybe.subscribe(Maybe.java:4154)
        at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern ";([A-Za-z0-9_\$]{2})\...\( inside of var u=function(a){for(var b=Xt(a,!0),c=eu(a),d=1;d<b;d++)c=256*c+eu(a);return c};"
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:73)
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:726)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:614) 
        at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52) 
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63) 
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59) 
        at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115) 
        at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda) 
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44) 
        at io.reactivex.Single.subscribe(Single.java:3438) 
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35) 
        at io.reactivex.Single.subscribe(Single.java:3438) 
        at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41) 
        at io.reactivex.Maybe.subscribe(Maybe.java:4154) 
        at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153) 
        at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78) 
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66) 
        at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) 
        at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36) 
        at io.reactivex.Maybe.subscribe(Maybe.java:4154) 
        at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46) 
        at io.reactivex.Single.subscribe(Single.java:3438) 
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by AbdulGh** [comment] 2019-04-02 07:51
Happens to me whenever I open any video, reported this in-app.

**Comment by cion49235** [comment] 2019-04-02 08:05
> Happens to me whenever I open any video, reported this in-app.

It happened suddenly today!

**Comment by cion49235** [comment] 2019-04-02 08:06
Sometimes I'm uncomfortable with this kind of encryption error.

**Comment by gitrdn** [comment] 2019-04-02 09:13
- Every video refuses to load, starting around 11 pm 4/1
- Simultaneously, SkyTube commenced video playback errors on every video as well

Reboot, clear cache, etc fixed nothing.
Did YT go live at midnight (their time) with code change? 

Having Newpipe 0.14.1, also tried upgrading: first, via Fdroid (v 0.14.2) which refused to download, then via direct APK download (v 0.16.1), which downloaded ok but refused to install. April Fool's crosses my mind.

I then downloaded SkyTube Extra, which is fully functional. I'm no dev, but the "non-OSS libraries" in SkyTube Extra appear immune to the problem at hand. However, Rogan at 1.0x speed is unbearable. 

Newpipe's variable speed and popout features are essential. If NewPipe's was more reliable, and if comments were viewable, I'd have no reason to use SkyTube. 

Thanks for your hard work and for a good product. Hope it's an easy fix for now.

**Comment by DHSYongJun** [comment] 2019-04-02 09:53
Originally had the same problem on 0.16.0 on my phone. Then updated to 0.16.1 via F-Droid and it now works (https://i.ibb.co/hK7YmJC/Screenshot-20190402-174538-Nova-Launcher.jpg). Though it surprisingly works on 0.16.0 on my tablet.

**Comment by AbdulGh** [comment] 2019-04-02 10:29
I also want to thank TeamNewPipe for their app, which I love dearly!

**Comment by hoschi-it** [comment] 2019-04-02 15:32
Having the same problem with NewPipeV0.15.1 since todays morning.

**Comment by maltfield** [comment] 2019-04-02 16:38
https://github.com/TeamNewPipe/NewPipeExtractor/issues/153

**Comment by ouzowtf** [comment] 2019-04-02 18:58
You should use an up-to-date version of NewPipe (0.16.1)

**Comment by Nihilarian9** [comment] 2019-04-02 21:17
I had this issue on 14.1. After updating to 16.1 I don't have this issue.

**Comment by TobiGr** [comment] 2019-04-03 14:10
I cannot reproduce this. Can someone please post the full error report. @cion49235 Next time please use the [crash report converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) which is linked in every new issue. The info you posted there only helps us particularly. And in this case, I cannot reproduce your problem because the important info is missing.

**Comment by cion49235** [comment] 2019-04-04 01:03
> I cannot reproduce this. Can someone please post the full error report. @cion49235 Next time please use the [crash report converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) which is linked in every new issue. The info you posted there only helps us particularly. And in this case, I cannot reproduce your problem because the important info is missing.

This error does not occur for a specific period of time 
It is not a precise reason, but error or pause occurs for a certain time when decrypting from NewPipe when the URL changes or updates on YouTube side

If this error occurs, the error will disappear after 24 hours or a day or two
I've already had 2 experiences
Despite not using version 0.16.1
It has been activated again
Have you updated the NewPipeExtractor Core File?
I am wondering if core files will be modified in real time
Ex)
implementation 'com.github.TeamNewPipe:NewPipeExtractor:f7c7b9df1a'

**Comment by hoschi-it** [comment] 2019-04-04 04:47
The problem stopped occuring for me.

**Comment by TobiGr** [comment] 2019-04-04 09:34
The extractor version can only differ when you install different NewPipe versions on your device. In other words, not the extractor changes abruptly, but the parsed YouTube site. For this reason, we try to have different regular expressions to parse the info. If all fail, a DecryptException is thrown - if we have not info on the video, we can't show it.

However, the people at YouTube do some AB testing, too. Sometimes, they deploy new website versions for some users and then roll back. This seems to be the case. For this reason, I'll close this. When we can't reproduce it, we are not able to fix it.

**Closed by TobiGr** 2019-04-04 09:34 UTC
