### ISSUE TITLE
Let playlist queue playback continue from selected video

### ISSUE THREAD

**Issue by Etim-Orb** [TeamNewPipe/NewPipe#8252] opened 2022-04-17 19:52 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When I enter a playlist I can "play all" the videos which creates a queue and plays those videos as the playlist lists them.

If I let's say want to play the 21th video in the playlist (without going through the previous ones), so if I want to maintain this queue I would have to tap on "Play all" again then skip to the desired video, since by simply selecting a random video from the playlist page does not create this queue (and the episode skip buttons next to the play icon does not appear). If I could create this queue without tapping "Play all" it would make things much easier.

I suggest whenever we tap on a video that is a part of a playlist automatically create and enter this playlist queue and continue with the selected video, then autoplay the next one, just as before.

### Why do you want this feature?

Less effort, less time consuming, more productive, more logical.

**Comment by SameenAhnaf** [comment] 2022-04-17 21:06
Duplicate of #5741

**Comment by Etim-Orb** [comment] 2022-04-17 22:03
@SameenAhnaf Should I close?

**Closed** 2022-04-18 09:57 UTC
Labels: enhancement
