### ISSUE TITLE
NewPipe Playlists

### ISSUE THREAD

**Issue by EvPix** [TeamNewPipe/NewPipe#6523] opened 2021-06-19 16:48 UTC
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
The ability to view a list of playlists directly on the channel.

#### Additional context
What it looks like now:
![NewPipe.jpg](https://user-images.githubusercontent.com/12032252/122649546-f7c11f00-d136-11eb-93bc-a379c65ebe45.jpg)

Playlists on the channel:
![NewPipe_Playlists.png](https://user-images.githubusercontent.com/12032252/122649616-41aa0500-d137-11eb-8e39-2bbaaf4f66f5.png)

**Comment by mhmdanas** [comment] 2021-06-19 17:22
Duplicate of #5203.

**Closed by mhmdanas** 2021-06-19 17:22 UTC
Labels: enhancement
