### ISSUE TITLE
Crashes upon sleep mode or backgrounding

### ISSUE THREAD

**Issue by ethanc8** [TeamNewPipe/NewPipe#11532] opened 2024-09-15 01:44 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2, from the NewPipe F-Droid repo

### Steps to reproduce the bug

Navigate to the Hsinchu City Chinese Youth Orchestra channel, find the all-time hits playlist, and choose the first video.

### Expected behavior

The video plays.

### Actual behavior

The video plays until a few seconds after the user puts their phone to sleep or starts playing the video in the background.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux samsung/dm1quew/dm1q:14/UP1A.231005.007/S911U1UEU2CXCG:user/release-keys 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2809)
	at android.os.Parcel.writeValue(Parcel.java:2575)
	at android.os.Parcel.writeValue(Parcel.java:2374)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1917)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1954)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:873)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2804)
	... 50 more

```
</details>
<hr>

### Additional information

I these crashes on many videos when I put the phone to sleep or put the video in background. This only manifests on some channels such as the HeartString guzheng music channel and the Hsinchu City Youth Chinese Orchestra channel, but not on AtinPiano, Patrik Pietschmann, or PianoDeuss.

**Comment by AudricV** [comment] 2024-09-15 14:38
> - [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #11356. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-09-15 14:38 UTC
Labels: bug, needs triage

**Comment by ethanc8** [comment] 2024-09-16 00:58
Sorry, I was unsure of which keywords this would be under. I will try to search better next time.
