### ISSUE TITLE
"Guru Meditation"

### ISSUE THREAD

**Issue by jennyfromtheblockwiththegoodhair** [TeamNewPipe/NewPipe#3658] opened 2020-05-28 11:47 UTC
![Screenshot_20200528-124156_NewPipe](https://user-images.githubusercontent.com/66068134/83137252-c2d3cb80-a0e0-11ea-9b87-2b3bbfa79cbf.jpg)

Hey, I'm sure you've put up with a lot of issues for this already but please could you find a way to fix this? I have done everything that people would recommend doing and yet it stil remains prominent. I cannot go onto any video without this popping up. I made an account just to say this since newpipe is one of my go-to apps and this error is vexxing to say the least. So I am once again asking for your co-operation. Please fix this bug if you aren't trying to already. Thank you

**Comment by Stypox** [comment] 2020-05-28 12:52
Please use the [Incredible Error Report to Markdown Converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) before sending bug reports, as you should have been told when creating the issue.
@wb9688 could you provide him with the apk to extract json?

**Comment by B0pol** [comment] 2020-05-28 17:17
Very likely to be duplicate of #3576

**Closed by B0pol** 2020-05-28 17:17 UTC
Labels: bug
