### ISSUE TITLE
Random Videos fail to Play

### ISSUE THREAD

**Issue by Pair-of-Pears** [TeamNewPipe/NewPipe#8720] opened 2022-07-31 17:17 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

This bug appears to occur at random, and I have had it happen to me whilst listening to long playlists of music in the background player.

### Expected behavior

Videos play normally.

### Actual behavior

Individual videos fail to play properly, spending no time buffering and instead being replaced with five minutes of complete silence. Clearing the queue and requeuing the video does not change this. Completely restarting the app, including background player, usually makes the affected video play properly again, though causes other videos to stop working in the same way.

### Affected Android/Custom ROM version

Android Nougat 32 bit

### Affected device model

OnePlus 3T (Emulated)

### Additional information

Note that this bug also occurs on my mobile device; Samsung Galaxy S8 running Android 9

**Comment by AudricV** [comment] 2022-07-31 17:30
The 5 minutes of audio silence is that YouTube is detecting more third-party clients and returning an error stream instead of the real stream (source: iv-org/invidious#3217).

Closing as a duplicate of #8713. Thank you for your report.

**Closed by AudricV** 2022-07-31 17:30 UTC
Labels: bug, needs triage
