### ISSUE TITLE
Get back "Open with" and  "Share" buttons

### ISSUE THREAD

**Issue by Flashwalker** [TeamNewPipe/NewPipe#4855] opened 2020-11-10 21:23 UTC
### Checklist
[+] I checked, but didn't find any duplicates of this issue in the repo. 
[+] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
[+] This issue contains only one feature request. I will open one issue for every feature I want to request.

### Describe the feature you want
Get back "Open with" and "Share" buttons to use them without playing video first. And it would be nice to add "Open with" button to context menu of queued videos.

### Is your feature request related to a problem? Please describe it
At my point of view hiding the "Share" and "Open with" buttons until start playing the video was a bad idea.

Now if i want to open the video in another application or browser i must first start playing the video and only then the buttons appears.
This is a clear disadvantage in functionality.

It is not uncommon for me to listen a video in the background player and later want to open it in another application. But for this, now I have to start playing it before I can press the "Open with" button.

Judging by some recent changes in the application, it may seem that the developers set out to worsen it, or complicate of use.

### How will you/everyone benefit from this feature?
We are all will be happy of using this good old app without lack of UX.

**Comment by juantxorena** [comment] 2020-11-10 22:38
This is a duplicate of #4039, which is being ignored for months.

**Closed** 2020-11-11 05:35 UTC

**Comment by opusforlife2** [comment] 2020-11-11 05:40
> which is being ignored for months.

That is extremely strange, because I could have sworn it has a linked PR we have been testing for weeks. 🤔

**Comment by opusforlife2** [comment] 2020-11-11 05:41
> I checked, but didn't find any duplicates of this issue in the repo.

Little more effort next time.
