### ISSUE TITLE
playback position indicators are still shown with disabled feature

### ISSUE THREAD

**Issue by barackenkumpel** [TeamNewPipe/NewPipe#7969] opened 2022-02-28 19:19 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Enable watch history
2. Disable "Positions in list" option
3. Watch a video to the half
4. Reload the list

### Expected behavior

Video will continue playing at the right position, but position indicator won't be shown in the list.

### Actual behavior

The red bar indicates the resume position in the list. No matter whether in list or grid mode. Also, for testing I even disabled the "Resume playback" option, but NewPipe continued saving playback positions and showing them in lists.

### Screenshots/Screen recordings

<img alt="Screenshot_20220228-201043_NewPipe" src="https://user-images.githubusercontent.com/93818968/156043995-f77d9312-bbdf-4981-b36c-52de368327da.png" height=600 />
<img alt="Screenshot_20220228-201101_NewPipe" src="https://user-images.githubusercontent.com/93818968/156044001-c6d79423-82a7-4b22-8ea2-9b6cafab6559.png" height=600 />
<img alt="Screenshot_20220228-201109_NewPipe" src="https://user-images.githubusercontent.com/93818968/156044014-d72bebee-8a19-4e42-8a68-a53a20d4ad1c.png" height=600 />

### Affected Android/Custom ROM version

Project Sakura 5.2 (Android 11)

### Affected device model

SM-G950F

### Additional information

Installed from F-Droid

**Comment by SameenAhnaf** [comment] 2022-03-01 03:37
Note that this bug persists only if some videos were watched while `Positions in Lists` was turned on. If those videos were removed from history or no video was watched while keeping the option on, this bug doesn't seem to occur.

**Comment by Trust04zh** [comment] 2022-04-08 01:26
I've found the problem, can I work on this issue?

**Comment by Trust04zh** [comment] 2022-04-08 12:13
It seems that the option `Position in lists` doesn't play a role as its description currently. 

In current code, `Position in lists` does nothing with the playback indicators in video lists. Current function for this option is to control whether these two views (see screenshot 1) should display together with option `Watch history`, `Resume playback` and some other conditions. If both `Watch history` and `Resume playback` are enabled and playback information is avaliable, these views always display. If they are not both enabled, while `Positions in lists` is enabled and the playback information is avaliable, these views display still. Other wise they do not display.

In my opinion, option `Position in lists` is helpful while not playing the expected role now, and I have some ideas for fixing this, I wonder if they are ok or if there are other ideas.

Here are my ideas:

- Display the two views in screenshot 1 iff both `Watch history` and `Resume playback` are enabled, as they are not for videos in lists but for detailed video information.

- Set `Resume playback` as the dependancy of  `Position in lists`, since if users need the playback information to be displayed, it makes no sense that they don't wanna resume playback.

- Display the playback progress in video lists (in screenshot 2) iff `Watch history`, `Resume playback` and `Position in lists` are all enabled, this fix the bug reported in this issue.

screenshot 1
![图片](https://user-images.githubusercontent.com/36195713/162431624-7fc1bfd3-9c75-4adc-892d-45e91673e1a0.png)

screenshot 2
![图片](https://user-images.githubusercontent.com/36195713/162432009-a6cb26b3-e9ad-48d8-ba0d-9a7712551d2a.png)

**Comment by opusforlife2** [comment] 2022-04-08 20:30
Also see: #4053.

**Comment by Trust04zh** [comment] 2022-04-09 16:30
@opusforlife2 Thank you for the information! Sorry that I didn't find it on my own. 

So this issue seems to be the duplication, as correct the function of `Positions in lists` and lose the same function from `Watch history` and `Resume playback` would just solve this issue. I would move to and work on it.

> Also see: #4053.

**Comment by opusforlife2** [comment] 2022-04-09 16:38
Closing this as duplicate of #4053.

**Closed by opusforlife2** 2022-04-09 16:38 UTC
Labels: bug
