### ISSUE TITLE
Using "start playing in background" causes it enqueue all tracks in the current playlist or history

### ISSUE THREAD

**Issue by luckcolors** [TeamNewPipe/NewPipe#6120] opened 2021-04-20 16:51 UTC
### Checklist

- [x] I am using the latest version - 0.21.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour
All of the playlist or history you where picking your videos from gets queued into the player's background playlist, just like if i pressed the enqueue all button.

### Expected behavior
The "play in background" should only add the one track its selected on (just like it does if done from the details view of a video), this should especially be the case given the app has dedicated buttons both in history and playlists for "enquequing all".
This i suppose could be another options in settings, as maybe other people do find this behaviour already acceptable, as it's been in the app for months.

Also since play in background is a destructive action on the background playlist this should either follow the "Ask for confirmation before clearing a queue" option or have it's own dedicated one for enabling wether the user should receive a warning prompt before clearing the current background player queue.

### Notes
I thank you all devs so much for making this app as it is really helpfull for me. 😄

**Comment by SameenAhnaf** [comment] 2021-04-25 17:24
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5586.

**Comment by luckcolors** [comment] 2021-04-25 23:13
Thank you for spotting the duplicate.
I did search myself but i didn't manage to find it.

If necessary feel free to close this in favour of the other one.
If you would like to transfer my points (wich aren't in the other one) to the other one let me know and i'll do it.

Thanks again for the help.

**Comment by SameenAhnaf** [comment] 2021-04-26 22:01
@mhmdanas Please close this.

>Duplicate of #5586.

**Closed** 2021-04-26 22:12 UTC
Labels: bug
