### ISSUE TITLE
Cannot interact with apps under the floating player

### ISSUE THREAD

**Issue by ehainry** [TeamNewPipe/NewPipe#8257] opened 2022-04-19 10:46 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Open a video in floating mode
2. Click the home button to hide newpipe but the pop-up continues playing
3. Taps do not register outside of the player or the back, home, menu buttons

### Expected behavior

Apps under the pop-up, or the home screen used to be interactable.

### Actual behavior

When I launch a floating video from Firefox, I can no longer use Firefox while the pop-up is there. Note that newpipe itself can be interacted with under the floating player.

Newpipe correctly has the "Vue en premier plan" permission. Vlc, in which the pop-up player has the expected behaviour, does not but has a "picture in picture" permission.

### Affected Android/Custom ROM version

Android 12 / Samsung One UI 4.1

### Affected device model

Samsung Galaxy Tab S6 Lite

### Additional information

It used to work but the OS was recently updated.

**Comment by SameenAhnaf** [comment] 2022-04-19 11:32
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6770

**Comment by TiA4f8R** [comment] 2022-04-19 11:59
> Cannot interact with apps under the floating player

Cannot search for duplicate issues before opening a new one (indeed that's a duplicate of #6770), can find a potential fix in the original issue, in the last comments.

More seriously, please read and follow the issue form next time, you must follow the checkboxes' instructions before opening a new issue. Thank you.

**Closed by TiA4f8R** 2022-04-19 11:59 UTC
Labels: bug
