### ISSUE TITLE
Resolutions Unavailable 

### ISSUE THREAD

**Issue by ToTheMoon1234** [TeamNewPipe/NewPipe#8415] opened 2022-05-18 20:41 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

Videos don't have some resolution options like 240p, 480p
I was looking through the videos of a channel and found that videos were missing these resolution while playing or on download option 
Some links:
https://youtu.be/yYNCbGxsAVc
https://youtu.be/SIiK0xzuq-I

### Expected behavior

I have default resolution as 240p and expected the video to play in it. 

### Actual behavior

But it turns out 240p, 480p and 144p Mpeg is not available. Note that these resolutions are available on yt app, vanced or website

### Screenshots/Screen recordings

<img alt="Screenshot_20220519-013211" src="https://user-images.githubusercontent.com/73231423/169151490-b55ab4af-74e1-45aa-b4b3-5675572f6672.png" height=600 />
240p, 480p available on yt vanced
<img alt="Screenshot_20220519-011330" src="https://user-images.githubusercontent.com/73231423/169151518-137b4248-d7df-4d24-9f35-a69d7f07aa4b.png" height=600 />
<img alt="Screenshot_20220519-021255" src="https://user-images.githubusercontent.com/73231423/169152748-47ddcfb2-e3c7-4eed-aee3-4b40217c7654.png" height=600 />

### Affected Android/Custom ROM version

Android 10

### Affected device model

Nokia 7 plus 

### Additional information

Default resolution is 240p on newpipe
The missing resolutions are available on yt stock, vanced and website but not on newpipe
Although it is not my concern but 3gp was only available in 144p and no webm.

**Comment by TiA4f8R** [comment] 2022-05-19 08:26
Duplicate of #2415.

You don't really have to be worried about not searching propely existing issues because the title of the issue ls the original state of the issue and not the current one.

Except a fix which should come soon (see the PR linked in the issue).

**Closed by TiA4f8R** 2022-05-19 08:26 UTC
Labels: bug
