### ISSUE TITLE
Error on Resuming backgrouded Video

### ISSUE THREAD

**Issue by herkulessi** [TeamNewPipe/NewPipe#8304] opened 2022-04-29 05:28 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Start Video in Background (Explicitly with the button, not by backgrounding the App)
2. Put the Video to foreground and start the video-half by clicking play

### Expected behavior

Video starts

### Actual behavior

Crash Report get triggered, starting the Video after that works

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=1] occurred while playing https://www.youtube.com/watch?v=-Edv8Onsrgg
* __Content Country:__ 
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.22.2
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, -1.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, avc1.640028, -1, null, [1920, 1080, -1.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1051)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:606)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1465)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:713)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:998)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:830)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
	... 4 more
Caused by: java.lang.IllegalArgumentException: The surface has been released
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2176)
	at android.media.MediaCodec.configure(MediaCodec.java:2092)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:50)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1137)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1044)
	... 11 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S10+

### Additional information

I have had this exact bug happen multiple times now, I have actually intentionally reproduced it 10 minutes ago, but now I cant seem to reproduce it... Ill try some more and add to the reproduce section above.

**Comment by mhmdanas** [comment] 2022-05-20 11:08
I think this is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/8016.

**Closed by mhmdanas** 2022-05-20 11:08 UTC
Labels: bug
