### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ahsmha** [TeamNewPipe/NewPipe#7748] opened 2022-02-01 06:25 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Realme/RMX1945/RMX1945:9/PPR1.180610.011/1590067236:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.schabi.newpipe.extractor.stream.StreamInfo org.schabi.newpipe.player.resolver.MediaSourceTag.getMetadata()' on a null object reference
	at org.schabi.newpipe.player.Player.onPlayerError(Player.java:2526)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$10(ExoPlayerImpl.java:1269)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$-K5msfvAakBrxKAsG9AjoK30L1g(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda7.invoke(Unknown Source:4)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283)
	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
	at com.google.android.exoplayer2.util.ListenerSet.$r8$lambda$NbKDn9xtItiyMgYZmjIx_Sv1FFQ(Unknown Source:0)
	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1340)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1175)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1(ExoPlayerImpl.java:216)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$nOBJYkeEQ2uz3sBKLToLWmzrgZk(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda22.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7191)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```
</details>
<hr>

**Comment by flexagoon** [comment] 2022-02-01 07:06
Duplicate of #7732

**Comment by TiA4f8R** [comment] 2022-02-01 07:52
Closing as a duplicate of #7734.

Please follow issue template and its instructions the next time you open an issue. Thank you.

**Closed by TiA4f8R** 2022-02-01 07:52 UTC
Labels: bug

**Comment by ahsmha** [comment] 2022-02-01 08:18
> Closing as a duplicate of #7734.
> 
> Please follow issue template and its instructions the next time you open an issue. Thank you.

Alright! 

Btw when will there be a new release to current bugs?
