### ISSUE TITLE
UI crashing if i tap download tab

### ISSUE THREAD

**Issue by learnhack7** [TeamNewPipe/NewPipe#6943] opened 2021-08-19 07:29 UTC
{"user_action":"ui error","request":"ACRA report","content_language":"en-IN","content_country":"IN","app_language":"en_IN","service":"none","package":"org.schabi.newpipe","version":"0.21.8","os":"Linux Nokia/Phoenix_00WW/PNX_sprout:11/RKQ1.200906.002/00WW_6_210:user/release-keys 11 - 30","time":"2021-08-19 12:56","exceptions":["java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:4205)\n\tat android.app.ActivityThread.access$1500(ActivityThread.java:238)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1933)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:223)\n\tat android.app.ActivityThread.main(ActivityThread.java:7697)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference\n\tat us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)\n\tat us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)\n\tat us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)\n\tat android.app.ActivityThread.handleCreateService(ActivityThread.java:4193)\n\t... 8 more\n"],"user_comment":""}

**Comment by mhmdanas** [comment] 2021-08-19 14:31
Duplicate of #6687.

**Closed by mhmdanas** 2021-08-19 14:31 UTC
Labels: bug
