### ISSUE TITLE
Can't interact with app/screen below popup player on Android 12

### ISSUE THREAD

**Issue by Joristdh** [TeamNewPipe/NewPipe#6770] opened 2021-07-26 14:32 UTC
### Checklist

- [x] I am using the latest version - 0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

0. This is a bug on Android 12 beta 3
1. Open a video in the popup player (it doesn't matter which video or how you open it)
2. Make sure the popup uses the full width of the screen (when in portrait)
3. Open another app below the popup player, go to the home screen or open recent apps
4. Try to interact with the screen below the popup

### Actual behavior

All touches to the app/screen below the popup are ignored, because of the following behavior change in Android 12: https://developer.android.com/about/versions/12/behavior-changes-all#untrusted-touch-events 

### Expected behavior

The app below the popup responds to the touches.

### Workaround
For now this issues can be solved per device by running the following ADB command:
`adb shell settings put global block_untrusted_touches 0`

### Device info

 - Android version/Custom ROM version: Android 12 beta 3
 - Device model: Pixel 3

**Comment by chrstfer** [comment] 2021-08-03 04:24
Im seeing this sporadically on android 11 (samsung gs20 ultra with up to date stock firmware) with most recent release (0.21.7).  Often the app beneath will respond to drags and swipes but no controls will send their events even though they animate.

**Comment by chrstfer** [comment] 2021-08-09 17:27
What needs to be done to fix this? Its real annoying to need to clear my queue (because of an unrelated issue) just to send a tweet.

**Comment by Joristdh** [comment] 2021-08-10 13:06
@chrstfer I don't think it is the same bug. The behavior change is introduced in Android 12, as you can see in the link I provided in the description. If you encounter a similar bug in Android 11 it's probably caused by something else.
Maybe Samsung implemented a similar restriction in One UI or those apps implemented some restrictions themselves (for while another app overlays them). 

If your bug does have the same cause, the ADB shell command in the description should fix it. If it doesn't, or you can't execute the command at all (because you aren't on Android 12), you should probably file a new bug report detailing your specific issue.

**Comment by hackel** [comment] 2021-09-02 03:39
I also (still) have this issue on Android 12 beta 4.1 and the width of the pop-up makes no difference.  I believe I read that the actual PIP more will need to be used going forward for security.

**Comment by schnatzi** [comment] 2021-10-31 17:31
Same thing on Pixel 6 with Android 12.0. Oddly enough the problem wasn't an issue on the Pixel 3 with Android 12 on my end.

**Comment by dbenjaminmiller** [comment] 2021-11-03 10:22
Can confirm this is an issue for me on Android 12. What I think would be the proper solution is to offer a native popup as the default for A12 users with the old-style popup available as an option (which would require ADB access to be useful).

**Comment by Coderdude112** [comment] 2021-11-04 04:22
@schnatzi You arn't having problems with it on your Pixel 3? I'm having problems on my Pixel 3...

**Comment by schnatzi** [comment] 2021-11-04 08:27
> @schnatzi You aren't having problems with it on your Pixel 3? I'm having problems on my Pixel 3...

Maybe it just didn't occur at my end, because I didn't use it in combination with other apps since the update.

**Comment by xdIceBear** [comment] 2021-12-03 05:14
Can confirm this. When in pop up player mode, screen below the player becomes unresponsive. 

A12 latest build

**Comment by PacoBell** [comment] 2021-12-04 03:46
> > >adb shell am compat disable BLOCK_UNTRUSTED_TOUCHES org.schabi.newpipe
> > Cannot override a change on a non-debuggable app and user build.
> 
> Seems to not work for this. It is documented here though so good thinking: https://developer.android.com/about/versions/12/behavior-changes-all?hl=ro#untrusted-touch-events

Yes, the specifically targeted app workaround doesn't work, but the global one does:

`adb shell settings put global block_untrusted_touches 0`

Just FYI 😉

**Comment by Coderdude112** [comment] 2021-12-04 08:30
Thanks @PacoBell! Worked immediately

**Comment by rawlife56** [comment] 2021-12-06 11:00
The security measure exists for a reason. It is not smart enough to disable it globally.

**Comment by Coderdude112** [comment] 2021-12-06 19:49
@rawlife56 Yes, it does exist for a reason, I believe there is an application for it. It's new with Android 12 to my knowledge and not many apps have been updated to work with the new permissions. Pip is a useful feature and is something I use **all** the time, so this *temporary* fix is ok.

**Comment by book000** [comment] 2021-12-14 21:31
This issue also occurs on Pixel 3a, Android 12.
Moreover, it seems to occur even when playing in the background... (There is a notification in the notification column that "NewPipe is displayed above other apps")

**Comment by eRaz3r** [comment] 2021-12-24 07:04
Same Problem here with Samsung Galaxy S21 Ultra (Android12/OneUI 4).

**Comment by xelaseer** [comment] 2021-12-31 13:57
Can confirm this still occurs on 0.21.15 with the latest Graphene OS on a Pixel 4XL.

Makes the popup feature basically unusable, as not only does this not allow tapping on apps below during use, but also makes any app or interaction with the phone non-responsive after use, except for Newpipe, until phone restart.

**Comment by captainhook** [comment] 2021-12-31 14:31
> Can confirm this still occurs on 0.21.15 with the latest Graphene OS on a Pixel 4XL.
> 
> Makes the popup feature basically unusable, as not only does this not allow tapping on apps below during use, but also makes any app or interaction with the phone non-responsive after use, except for Newpipe, until phone restart.

Force stop Newpipe. No need to restart.

**Comment by ebanDev** [comment] 2022-01-07 16:28
Same problem on my Pixel 4XL with latest GrapheneOS 😭

**Comment by pyladus** [comment] 2022-01-14 15:32
Same for Samsung S10+

**Comment by R136A2** [comment] 2022-01-17 09:12
Any ideas,  how it can work  properly? 🤔

**Comment by captainhook** [comment] 2022-01-17 10:14
It will be fixed when PIP is implemented.

**Comment by Jinux-1** [comment] 2022-01-28 06:35
Just wanted to pop in and confirm that this is also an issue on CalyxOS' Beta of Android 12. Hoping it's updated ASAP because i heavily relied on the popup player

**Comment by Inrumpo** [comment] 2022-01-29 17:22
+1 for CalyxOS 3.1.0 (Android 12) on Pixel 4a

**Comment by mhmdanas** [comment] 2022-01-29 18:05
To those to see this issue: PLEASE don't comment unless you can add some useful info. Thus, no +1's, and no "this affects my Android 12 device too," unless you're adding something useful. If not, just react with a thumbs-up to this issue.

**Comment by zevoz** [comment] 2022-02-05 23:33
Similar issue here. Samsung s20fe , started after updating to A12.

App screen freezes after pop-up, even with Pip gone/switched off. Buttons & drag down menus work.

Closing Np doesn't fix this, only restart. Gets cumbersome 🤔

Thanks for the attention, and the awesome app. 🤟hope this gets fixed.

**Comment by Coderdude112** [comment] 2022-02-06 01:34
Dude, @zevoz, come on.

This thread already has tons of comments describing this issue and 20+ people are subscribed to pings to this thread. The comment directly above yours was literally asking people NOT to comment with +1s or comments saying "this affects my device too". Just react with the thumbs up on his comment.

**Comment by captainhook** [comment] 2022-02-06 01:39
@TobiGr @mhmdanas could you lock this issue, please? There's nothing else to add to this discussion, we know the issue is that PIP needs to be implemented. As and when someone has time to work on PIP implementation, I'm sure a PR will be raised.

**Comment by zevoz** [comment] 2022-02-06 02:13
🤷🏻‍♂️ @Coderdude112 I figure some specifics I've mentioned qualify as new information / symptoms not previously mentioned in this thread. It's being worked on, got it. No need to get testy 🧘🏻

**Comment by Coderdude112** [comment] 2022-02-06 02:26
@zevoz I understand. Sorry if I came off as rude. As someone above found, you can use adb and the command below to disable the new feature in Android 12 that causes this issue.

```bash
adb shell settings put global block_untrusted_touches 0
```

While not a great solution, as it allows any app to do what NewPipe is trying to do, it does work. Would prob turn this back on as soon as someone here fixes the issue tho.

**Comment by TiA4f8R** [comment] 2022-02-12 17:33
Like stated before, the issue will be fixed when Android Picture in Picture API is implemented in NewPipe.

But we don't really have the time to implement this (and I personally don't have the knowledge to do this) so we need help from someone else.

**Comment by PacoBell** [comment] 2022-02-12 18:58
Dunno if this helps, but https://github.com/twireapp/Twire implemented PiP, but they seem to be having some issues with it at the moment. 

Also, Google has some sample PiP code if anyone wants to study that.

https://github.com/android/media-samples/tree/main/PictureInPicture

**Comment by UnixPhonez** [comment] 2022-02-16 20:46
Having same issue on pixel 6 pro android 12 grapheneos

**Comment by SlidingHorn** [comment] 2022-02-23 05:12
I apologize ahead of time of this is unwelcome, but mpv-android seems to have a working implementation that has resizing, etc. Just figured that the suggestion could be helpful if any contributors are able to discern how they did it:

https://github.com/mpv-android/mpv-android

**Comment by TiA4f8R** [comment] 2022-02-25 17:51
If it's not done by the player and all its components rewrite, I suggest to work on this only after the player rewrite is done. This will probably decrease the work that needs to be done to add the PiP feature.

**Comment by cyphar** [comment] 2022-03-10 08:26
> > Can confirm this still occurs on 0.21.15 with the latest Graphene OS on a Pixel 4XL.
> > Makes the popup feature basically unusable, as not only does this not allow tapping on apps below during use, but also makes any app or interaction with the phone non-responsive after use, except for Newpipe, until phone restart.
> 
> Force stop Newpipe. No need to restart.

How do you force stop an app if touch events are not working on the screen outside of the newpipe app? You can't even use the task switcher to close the app normally, let alone open the settings app to force stop NewPipe. The only option is to restart your phone AFAICS (and I've now just removed permissions for overlaying in NewPipe given the feature is completely broken -- which sucks since this feature was one of the main features I liked about NewPipe). Hopefully the devs have time to fix it soon.

**Comment by TiA4f8R** [comment] 2022-03-16 17:37
Please test #8045. It's not the optimal solution at all, but should really help you until the player rewrite is done.

**Comment by werjany** [comment] 2022-04-07 15:36
> Please test #8045. It's not the optimal solution at all, but should really help you until the player rewrite is done.

After the newest update to MIUI 13 that solution doesn't work at all. Cannot use a popup window - the phone doesn't respond to touching anywhere else.

**Comment by moneytoo** [comment] 2022-04-07 18:56
This must be just some fixable issue as other video players using overlay window API (not the PiP) work just fine on Android 12 (Samsung Galaxy S21 FE). For example Nova Video Player or (when configured to use overlay window instead of native PiP) MX Player and OPlayer. I will try debugging that when I have some time.

**Comment by TiA4f8R** [comment] 2022-04-07 21:41
I made some tests and the non interaction of the screen on Android 12 is definitively caused by the close popup view button! By preventing its construction on Android 12+, other apps can get touches made to the screen.

However, several things in the player are based on this button, and just prevent the creation of this button crashes the app when resizing or moving the view. So, if the solution to this issue is to disable this button, at least for Android 12+, code using the close popup button will need to be updated.

**Comment by TiA4f8R** [comment] 2022-04-14 12:33
> So, if the solution to this issue is to disable this button, at least for Android 12+, code using the close popup button will need to be updated.

I did it and the issue seems to be gone, at least on my emulator (Pixel 5 running Android 12).

However, I can't test the resize gesture.

Could you test this gesture and everything else with the popup player, using the following APK to see if I didn't break something with my changes (you can find them here: https://github.com/TiA4f8R/NewPipe/tree/disable-close-popup-button-creation-android-12-and-higher)? Thank you in advance!

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/8489141/app-debug.zip)

**Comment by werjany** [comment] 2022-04-14 20:50
> made some tests and the non interaction of the screen on Android 12 is definitively caused by the close popup view button! By preventing its construction on Android 12+, other apps can get touches made to the screen.
> 
> However, several things in the player are based on this button, and just prevent the creation of this button crashes the app when resizing or moving the view. So, if the solution to this issue is to disable this button, at least for Android 12+, code using the close popup button will need to be updated.

I tried your update. Didn't solve the problem (Xiaomi Mi Note 10 Lite, MIUI 13.0.1, Android 12). It is still impossible to use the overlay outside the app.

**Comment by moneytoo** [comment] 2022-04-15 06:32
> I did it and the issue seems to be gone, at least on my emulator (Pixel 5 running Android 12).
> 
> However, I can't test the resize gesture.

FYI: It is possible to use pinch to zoom (using standard mouse) in the emulator. There's some "secret" key combination to se the wanted initial zones for the gesture (last time I needed this I found the answer on StackOverflow).

> Could you test this gesture and everything else with the popup player, using the following APK to see if I didn't break something with my changes (you can find them here: https://github.com/TiA4f8R/NewPipe/tree/disable-close-popup-button-creation-android-12-and-higher)? Thank you in advance!

Works for me seemingly fine on Android 12 (Samsung Galaxy S21 FE) including the window resize.

**Comment by vnckppl** [comment] 2022-04-20 23:57
Running the fix on my Samsung a53 stock without any issues.  Watching a video in popup mode while typing this comment.

**Comment by TiA4f8R** [comment] 2022-04-21 18:02
@moneytoo @vnckppl Sorry to ping you, but could you also test this APK and see if the issue is gone too?

It seems when setting a lower opacity to the close button ([up to 0.8](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#maximum-obscuring-opacity)), we can also use the popup player on Android 12 and higher.

Could you test the following changes to see if they work (the source code is available [here](https://github.com/TiA4f8R/NewPipe/tree/set-maximum-allowed-opacity-for-close-overlay-android-12-and-higher))? Thank you!

[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/8533633/app-debug.zip)

**Comment by moneytoo** [comment] 2022-04-21 18:21
@TiA4f8R The attached build works perfectly for me when using the popup player.

**Comment by werjany** [comment] 2022-04-21 19:38
> @moneytoo @vnckppl Sorry to ping you, but could you also test this APK and see if the issue is gone too?
> 
> It seems when setting a lower opacity to the close button ([up to 0.8](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#maximum-obscuring-opacity)), we can also use the popup player on Android 12 and higher.
> 
> Could you test the following changes to see if they work (the source code is available [here](https://github.com/TiA4f8R/NewPipe/tree/set-maximum-allowed-opacity-for-close-overlay-android-12-and-higher))? Thank you!
> 
> [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/8533633/app-debug.zip)

That works for me too! Thanks!

**Comment by book000** [comment] 2022-04-21 20:28
The build posted by @TiA4f8R confirms that the popups work as expected! (Pixel 3a / Android 12)

**Comment by alexsohn1126** [comment] 2022-04-22 04:02
> @moneytoo @vnckppl Sorry to ping you, but could you also test this APK and see if the issue is gone too?
> 
> It seems when setting a lower opacity to the close button ([up to 0.8](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#maximum-obscuring-opacity)), we can also use the popup player on Android 12 and higher.
> 
> Could you test the following changes to see if they work (the source code is available [here](https://github.com/TiA4f8R/NewPipe/tree/set-maximum-allowed-opacity-for-close-overlay-android-12-and-higher))? Thank you!
> 
> [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/8533633/app-debug.zip)

Amazing. Worked for me. 
Using Galaxy S10+ with Android 12.

**Comment by vnckppl** [comment] 2022-04-22 16:18
> @moneytoo @vnckppl Sorry to ping you, but could you also test this APK and see if the issue is gone too?
> 
> It seems when setting a lower opacity to the close button ([up to 0.8](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#maximum-obscuring-opacity)), we can also use the popup player on Android 12 and higher.
> 
> Could you test the following changes to see if they work (the source code is available [here](https://github.com/TiA4f8R/NewPipe/tree/set-maximum-allowed-opacity-for-close-overlay-android-12-and-higher))? Thank you!
> 
> [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/8533633/app-debug.zip)

Works great! I can navigate normally in underlying apps and dragging the popup window to the closing button works too.

**Comment by TiA4f8R** [comment] 2022-04-23 17:53
This bug should have been fixed by #8279, included in the upcoming release, 0.23.0. Closing as resolved.

**Closed by TiA4f8R** 2022-04-23 17:53 UTC
Labels: bug, player, device/software specific
