### ISSUE TITLE
On the tab “Subscriptions” add sorting channels into folders.

### ISSUE THREAD

**Issue by IT-Tool** [TeamNewPipe/NewPipe#2687] opened 2019-10-04 18:32 UTC
- [x] I carefully read the contribution guidelines and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

  When there are too many channels, I would like to sort them by topic on my own. One folder for channels with music, a separate folder for podcasts and so on.
   It would be useful to see the number of channels in each folder in the General list.

**Comment by TemporaryAccount0x1** [comment] 2019-10-05 10:30
a few months ago @mauriciocolli was working on something similar as part of https://github.com/TeamNewPipe/NewPipe/pull/2309 . In his case he was working on subscriptions groups so that one could only look at the latest videos of the channels one has put in a group, it didn't really work as folders but more so as a group of subscription which you could than use to only see the latest subscription of that group. maybe what you're asking for could be done with the Groupie library that he was using ?

**Comment by Stypox** [comment] 2019-10-06 06:41
Duplicate of #565

**Closed by Stypox** 2019-10-06 06:41 UTC
