### ISSUE TITLE
video surface transition problem

### ISSUE THREAD

**Issue by error-reporting** [TeamNewPipe/NewPipe#11035] opened 2024-05-04 09:33 UTC
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

0. sroll up in video history tab
1. watch any video and enter full-screen
2. and then exit using the exit full-screen button
3. and then sroll to the top in video history
4. after around 1 to 3 sec
5. the app crash

### Expected behavior

the app continue playback normally

### Actual behavior

the app or ui crash

### Screenshots/Screen recording
_no response_
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ VN
* __Content Language:__ vi-VN
* __App Language:__ vi_VN
* __Service:__ none
* __Version:__ 0.27.0
* __OS:__ Linux OPPO/CPH2179T2/OP4F2F:10/QP1A.190711.020/1672196830:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7790)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6873)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1425)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1158)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2050)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5835)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1068)
	at android.view.Choreographer.doCallbacks(Choreographer.java:892)
	at android.view.Choreographer.doFrame(Choreographer.java:815)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1053)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:240)
	at android.app.ActivityThread.main(ActivityThread.java:7829)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)

```
</details>
<hr>

### Affected Android/Custom ROM version

android 10/coloros 7.2

### Affected device model

Oppo a15s

### Additional information

**Comment by error-reporting** [comment] 2024-05-04 09:39
i meant pop-up player

**Comment by error-reporting** [comment] 2024-05-05 03:30
please remove the template ignored i have followed the template instructions

**Comment by AudricV** [comment] 2024-05-05 09:07
No, your issue is a duplicate of #4475. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-05-05 09:07 UTC
Labels: template ignored, duplicate
