### ISSUE TITLE
Add the ability to select multiple videos for download

### ISSUE THREAD

**Issue by theremotest** [TeamNewPipe/NewPipe#8741] opened 2022-08-06 07:20 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

The ability to select multiple videos from history, what's new, search results, and playlists for quick actions such as download. And/or in the case of playlists, add a button to download all videos. After the selected videos would be selected for download and the download button would be pressed, the user would set the type of download and quality for all the selected videos at once.

### Why do you want this feature?

Downloading music of of youtube is currently a painstaing process as each music video has to be opened, selected for download, and the type and quality of download has to be set individualy. This feature would allow an entire album to be downloaded in just one go.

**Comment by SameenAhnaf** [comment] 2022-08-06 09:40
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5482

**Comment by theremotest** [comment] 2022-08-06 15:00
I just want to apologise for not searching enough for duplicates. Will try more next time.

**Closed** 2022-08-06 19:09 UTC
Labels: enhancement, needs triage
