### ISSUE TITLE
The app closes itself within seconds, every time I open it .

### ISSUE THREAD

**Issue by thefosser** [TeamNewPipe/NewPipe#7687] opened 2022-01-23 03:05 UTC
Oh no, a bug! It happens. Thanks for reporting an issue with NewPipe. To make it easier for us to help you please enter detailed information in the template we have provided below. If a section isn't relevant, just delete it, though it would be helpful to still provide as much detail as possible.
-->

### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

The app closes itself after opening within a matter of seconds

### Expected behavior
To function as usual and play the video that I choose flawlessly 

### Logs
This happens every time I open this app.
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4167)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4185)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4459)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:658)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:255)
	at android.view.View.dispatchDetachedFromWindow(View.java:15437)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4758)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4732)
	at android.view.ViewGroup.removeView(ViewGroup.java:4663)
	at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.java:350)
	at androidx.fragment.app.SpecialEffectsController$Operation$State.applyState(SpecialEffectsController.java:452)
	at androidx.fragment.app.SpecialEffectsController$1.run(SpecialEffectsController.java:211)
	at androidx.fragment.app.SpecialEffectsController$Operation.complete(SpecialEffectsController.java:695)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:744)
	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:597)
	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:332)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3132)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:334)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:330)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:278)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:446)
	at android.app.Activity.performDestroy(Activity.java:6907)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4154)
	... 10 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by litetex** [comment] 2022-01-23 13:45
Duplicate of #7549

Also please fill out the template correctly next time 😄

**Closed** 2022-01-23 13:45 UTC
Labels: bug, template-ignored, duplicate

**Comment by litetex** [comment] 2022-01-23 14:14
@thefosser 
Is your device a Lenovo device?

**Comment by thefosser** [comment] 2022-01-24 14:28
Yes lenovo k6 power
