### ISSUE TITLE
Question / Enhancement: Independently upgradable extractor / parser

### ISSUE THREAD

**Issue by SebiderSushi** [TeamNewPipe/NewPipe#2045] opened 2019-01-20 19:27 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

In light of the current discussions about deprecation & legacy and breaking parser & quicker updates:
Could it be possible to implement the parser as a standalone part of the application that could be updated on-the-fly without needing to touch the rest of the app? Possibly by the app itself over-the-air without installing an update?

This would make it possible to update right away if a YouTube change breaks the parser and possibly give the developers or the community the chance to maintain a legacy version while moving on to drop legacy parts in the main release.

**Comment by theScrabi** [comment] 2019-01-20 21:20
That is an excellent question. Well some pleople suggested that if the decypher function failes (which is mostly the case) it should be downloading the regex to find the function again from our servers. This would, (at least) in the case of the decyper issue fix our problem.

**Comment by SebiderSushi** [comment] 2019-01-20 22:37
First of all I think it's awesome that you support this.

I was thinking that it must be technically possible one way or the other so I was mostly asking whether you as the developer would be willing to adopt this and whether any other hurdles can be tackled too. For example:
 - Is it possible to implement this and stay trusted? After all, this _could_ be leveraged to push malware to the users. -> Implications on F-Droid? I'm thinking of an AntiFeature at least. Maybe if this has to be activated manually it will be okay?
 - How do you secure this feature so that only trusted code gets loaded?

**Comment by theScrabi** [comment] 2019-01-23 13:38
Comming to think about this, a couple of while ago I was trying to merge an app that utilises DexClassLoader into fdroid. Fdroid does not like this, because the can not ensure that the code that is loaded by the DexClassLoader was generated by their servers therfore they block apps that use this completely. With the [App update notification](https://github.com/TeamNewPipe/NewPipe/pull/1608) written by @krtkush and the [reproducable Build feature of fdroid](https://f-droid.org/de/docs/Reproducible_Builds/) we can pretty much punch down that problem. With the advantage that everything can be build by fdroid, but we could still release fast, and that we don't need to change something about our actual code.

Also hot swapping the backend is not completely solving our problems. It is more important to change the way we develop frontend and backend. For example during the development of 0.15.0 we had the problem that one feature that got merged into the backend broke the API to it, so the frontend could not communicate with it any more. This may not happen, so we need a `stable/master` and a `developer` branch for the extractor. If an error occurs on the youtube side we will fix that error on the `stable/master` branch. This way the currently released version gets a postfix, but we don't need to release a new unfinished dev version (like v0.15.0 at the moment).

**Closed by theScrabi** 2019-01-23 13:38 UTC
Labels: enhancement

**Comment by TobiGr** [comment] 2019-01-23 13:40
> For example during the development of 0.15.0 we had the problem that one feature that got merged into the backend broke the API to it, so the frontend could not communicate with it any more. This may not happen, so we need a stable/master and a developer branch for the extractor. If an error occurs on the youtube side we will fix that error on the stable/master branch. This way the currently released version gets a postfix, but we don't need to release a new unfinished dev version (like v0.15.0 at the moment).

Completely agree with that :+1:

**Comment by SebiderSushi** [comment] 2019-01-23 20:08
Thank you very much for your verbose response.
That settles that.

But it raises another question for me: How is [Termux](https://termux.com) allowed in F-Droid since it allows installing packages from the developers' repository? I'll do some research, but I guess it's probably because the apps classes themselves remain untouched as it just loads additional code.
