### ISSUE TITLE
[FR] Use NewPipe for internal video playback

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#3083] opened 2020-02-12 13:41 UTC
Pretty much the title. At this point in my case at least, NewPipe's functionality is superior to even VLC's.

Smooth software VP9 decoding on my 2016(ish) MTK processor, fast-forward functionalities being the most important ones to me.

I miss it especially when I download a video from within NP but have to use another player to watch it.

**Comment by Stypox** [comment] 2020-02-12 14:04
Duplicate of #478 and #1179

**Closed by Stypox** 2020-02-12 14:04 UTC
