### ISSUE TITLE
Not all videos of a channel get loaded

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#4103] opened 2020-08-09 12:01 UTC
### Version
0.19.8
-

### Steps to reproduce the bug
1. Open a chanel
2. Scroll to the bottom
3. repeat until error happens

### Expected behavior
Older videos of the channel get loaded

### Actual behaviour
Sometimes NewPipe behaves as if there where not more videos. Although a channel definitely has more. This happens not always but offten after some tries.

### Screenshots/Screen recordings
![clip mp4](https://user-images.githubusercontent.com/1891273/89731630-cd97ce80-da48-11ea-9ae5-41af6d8bd3ae.gif)

**Comment by Stypox** [comment] 2020-08-09 12:19
Duplicate of #4094, I think

**Closed** 2020-08-09 12:19 UTC
Labels: bug

**Comment by opusforlife2** [comment] 2020-08-09 12:44
This just goes to show, even if you're the former project lead, you should _still_ make it a habit to search for your issue among existing ones. :P
