### ISSUE TITLE
Background Play Broadcast isn't detected.

### ISSUE THREAD

**Issue by RuthlessRuler** [TeamNewPipe/NewPipe#2942] opened 2020-01-09 18:56 UTC
When using the background function to listen to music, the Android Lock Screen doesn't pickup the Album Art not does app like lawn chair shows what's playing in the At A Glance widget that most of Music Players are able to get so.

(Music Played using Musicolet)
![Screenshot_20200110-002220](https://user-images.githubusercontent.com/20885012/72096078-82490080-333f-11ea-8102-eddc0bbe6a7a.jpg)
![Screenshot_20200110-002344](https://user-images.githubusercontent.com/20885012/72096083-837a2d80-333f-11ea-85cd-19cff095e7cc.jpg)

(Music played Using NewPipe)
![Screenshot_20200110-002304](https://user-images.githubusercontent.com/20885012/72096081-82e19700-333f-11ea-894c-90dc8a6e5f19.jpg)
![Screenshot_20200110-002328](https://user-images.githubusercontent.com/20885012/72096079-82e19700-333f-11ea-8b41-b6ff041c18b3.jpg)

**Comment by Stypox** [comment] 2020-01-10 13:06
Duplicate of #228

**Closed by Stypox** 2020-01-10 13:06 UTC
