### ISSUE TITLE
Show channel playlist with channel info..(like youtube)

### ISSUE THREAD

**Issue by heartlog** [TeamNewPipe/NewPipe#8749] opened 2022-08-08 07:05 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I am not able to browse channel playlist of yt channel..
# I have solution to this
__*Remember I don't know Java /kotlin but rather know python a bit__

I don't know issues that restrict yt channel from showing playlist from api or website...

But, I have an idea.....
Please see this @Stypox !
# Idea to add this feature
- you can use [invidious](https://github.com/iv-org/invidious)
- it have search feature
- Also channel URL from youtube channel is ditto to original !
Eg. Mr.beast channel
YouTube:
https://www.youtube.com/channel/UCX6OQ3DkcsbYNE6H8uQQuVA
Invidious: https://vid.puffyan.us/channel/UCX6OQ3DkcsbYNE6H8uQQuVA

## Playlist listing is also easy in invidious !
https://vid.puffyan.us/channel/UCX6OQ3DkcsbYNE6H8uQQuVA/playlists
(See additional info for pic)

You can use Invidious as playlist reference of channel and can extract to newpipe channel section....

### Why do you want this feature?

I want to see newpipe's libre idea seeing came true...
And I expect a lot from newpipe to implement !

### Additional information

# [🙋 PLAYLIST LISTING ](https://vid.puffyan.us/channel/UCX6OQ3DkcsbYNE6H8uQQuVA/playlists)

<img alt="https://vid.puffyan.us/channel/UCX6OQ3DkcsbYNE6H8uQQuVA/playlists" src="https://user-images.githubusercontent.com/76758776/183357434-ec9e966e-7c94-4793-abc3-664781b1a1cd.jpg" height=600 />

* Please look at this and add playlist listing in channel.. Please....

**Comment by heartlog** [comment] 2022-08-08 07:39
# Adding:
 invidious also provides api we dev can use...
Read [invidious api docs](https://docs.invidious.io/api/#get-apiv1channelsplaylistsucid-apiv1channelsucidplaylists)

## Here is [api response example](https://docs.invidious.io/api/#get-apiv1channelsplaylistsucid-apiv1channelsucidplaylists) from them..

![Screenshot_20220808-130059_Chrome](https://user-images.githubusercontent.com/76758776/183364941-ce442b0c-9ef5-4704-ae4d-7b273b59b547.jpg)

**Comment by Stypox** [comment] 2022-08-08 10:25
Thank you for the investigation, but there is no need to rely on invidious. YouTube can already provide all information we want, that's not the issue. The issue is just that no developer showed interest in implementing channel tabs so far.

Duplicate of #2414

**Closed by Stypox** 2022-08-08 10:25 UTC
Labels: enhancement, needs triage
