### ISSUE TITLE
Randomize save Playlist option

### ISSUE THREAD

**Issue by Likenewbie** [TeamNewPipe/NewPipe#8454] opened 2022-05-28 22:57 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

An option to randomize or mix a saved Playlist. 

### Why do you want this feature?

When I workout or go running, I tend to listen to music that I have saved on a Playlist. Along with the play all button, being able to randomly mix the songs on my Playlist would be great instead of just playing the list with the same order of songs.

**Comment by SameenAhnaf** [comment] 2022-05-29 02:56
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6625

**Closed** 2022-06-11 18:19 UTC
Labels: enhancement
