### ISSUE TITLE
Phone crashing when trying to play any video

### ISSUE THREAD

**Issue by Sstarless** [TeamNewPipe/NewPipe#5211] opened 2020-12-18 05:24 UTC
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

The phone goes to lock screen and keeps turning the screen on and off, until eventually the UI crashes and i have to reboot the phone

### Expected behavior

I expect the video to play normally

### Screenshots/Screen recordings
Unable to provide it as i don't have another phone or camera to record

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Xiaomi MI A2

**Comment by Sstarless** [comment] 2020-12-18 05:39
Disabling "show thumbnail" and changing "preferred 'open' action" to video player seemed to fix it

**Comment by mhmdanas** [comment] 2020-12-18 10:18
You didn't specify your NewPipe version. Could you please add it? If it is 0.20.6, this is likely a duplicate of #5162.

**Comment by nonremittal** [comment] 2020-12-18 12:32
Also on a Xioami Mi A2, same bug. Turning off thumbnails fixes it.

**Comment by Sstarless** [comment] 2020-12-18 15:36
> You didn't specify your NewPipe version. Could you please add it? If it is 0.20.6, this is likely a duplicate of #5162.
It's indeed 0.20.6, added it to the main post

**Comment by mhmdanas** [comment] 2020-12-19 07:51
Then I'll be closing this as a duplicate of #5162.

**Closed by mhmdanas** 2020-12-19 07:51 UTC
Labels: bug
