### ISSUE TITLE
Opening a timeline link always switches to the popup window

### ISSUE THREAD

**Issue by firefoxlover** [TeamNewPipe/NewPipe#6944] opened 2021-08-19 13:05 UTC
### Steps to reproduce the bug
1. Open a video
2. If it has a timeline (like 14:21) in the comments or description click on it

### Actual behavior
It opens the video at that place, but in a popup window, producing much lag. When closing the popup the video starts from the beginning.

### Expected behavior
When clicking on the timestamp, it should just skip the playing video to that time.

### Device info

 - 18.1-20210714-UNOFFICIAL-Onyx
 - 4.4.192-black_caps+
 - Nokia 7 plus, Hardware Version 5.0, B2NGAA987261xxxx

**Comment by SameenAhnaf** [comment] 2021-08-19 14:15
Duplicate of #4241. Also, please fill in the template properly.

**Closed** 2021-08-19 14:31 UTC
Labels: bug
