### ISSUE TITLE
Click on playing background video in pulldown menu (Oxygen OS)

### ISSUE THREAD

**Issue by dandjo** [TeamNewPipe/NewPipe#6568] opened 2021-06-25 03:22 UTC
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.5
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.PlaybackParameters org.schabi.newpipe.player.Player.getPlaybackParameters()' on a null object reference
	at org.schabi.newpipe.player.PlayQueueActivity.onCreateOptionsMenu(PlayQueueActivity.java:107)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4212)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
</details>
<hr>

**Comment by TiA4f8R** [comment] 2021-07-01 13:30
Please edit your issue by using the bug report template (that you can get [here](https://github.com/TeamNewPipe/NewPipe/issues/new?assignees=&labels=bug&template=bug_report.md)) and include steps to reproduce this crash. Also, by looking at the stacktrace you provide, this issue seems to be a duplicate of #5800. Closing for now.

**Closed by TiA4f8R** 2021-07-01 13:30 UTC
