### ISSUE TITLE
Schedule auto backup data newpipe

### ISSUE THREAD

**Issue by NSTAdventure** [TeamNewPipe/NewPipe#9046] opened 2022-09-30 15:04 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Please consider to add auto backup with it schedule system in newpipe

### Why do you want this feature?

1. Im forgetful those automation and schedule will obviously help me

2. Of course I don't want to lose my precious data on newpipe finding those video and put that on playlist is not easy task

3. Reminder message is nice combo with those features request so please consider add This too.

### Additional information

No i don't have any cats 🥴🤦

**Comment by ShareASmile** [comment] 2022-09-30 16:46
Duplicate of #3558

**Comment by NSTAdventure** [comment] 2022-10-01 00:02
> Duplicate of #3558

Wait i never see those test apk or those feature where was it? 🙏🤔

**Closed** 2022-10-01 01:00 UTC
Labels: enhancement, needs triage
