### ISSUE TITLE
Ability to download playlists like youtube-dl

### ISSUE THREAD

**Issue by tifDev** [TeamNewPipe/NewPipe#4812] opened 2020-11-05 21:57 UTC
I use now NewPipe more than Youtube app and I find it easier to have my Bookmarked playlists on NewPipe. But I find it difficult to download the playlists songs. 
**Is there a way to download the playlists like youtube-dl?** 

F.e. Keep track of the downloaded videos on a `Downloaded.txt` from *playlistX* and when I click *"Download"* it only downloads the musics that weren't downloaded (whose video id is not in the file `Downloaded.txt`)

I tested exporting the data and check the `newpipe.db` wich has the videos url but the formatting makes it very hard to make it viable to download the videos this way. **Maybe change this formatting or add an option to export only URL's from the selected Bookmarked playlist?**

**Comment by test2a** [comment] 2020-11-06 03:44
duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2380

**Comment by opusforlife2** [comment] 2020-11-06 05:31
Don't ignore the template.

**Closed by opusforlife2** 2020-11-06 05:31 UTC
Labels: enhancement
