### ISSUE TITLE
Adding Twitch Api 

### ISSUE THREAD

**Issue by vapasleepee** [TeamNewPipe/NewPipe#6068] opened 2021-04-13 11:29 UTC
So here's an Idea that came to my mind. Adding Twitch topics. Why ? more useful than peertube more people will be concerned and as you know Newpipe is very easy to use, so that could be better for everyone to watch on new pipe the topics from Twitch.![Screenshot_2021-04-13-14-10-12-78.jpg](https://user-images.githubusercontent.com/66576908/114550024-06d0b000-9c62-11eb-9967-281bc4b5d769.jpg)

**Comment by SameenAhnaf** [comment] 2021-04-13 11:38
Please fill in the template properly. Don't ignore it. Put an 'x' (letter:exe) between third brackets to check a checkbox.

Also, your title is not supposed to include all irrelevant topics. Include key sentence there only and properly describe your feature in "Describe what you want". Please mention exactly what you want. We don't understand what you are talking about.

**Comment by vapasleepee** [comment] 2021-04-13 12:13
> Please fill in the template properly. Don't ignore it. Put an 'x' (letter:exe) between third brackets to check a checkbox.
> 
> Also, your title is not supposed to include all irrelevant topics. Include key sentence there only and properly describe your feature in "Describe what you want". Please mention exactly what you want. We don't understand what you are talking about.

i did it

**Comment by TiA4f8R** [comment] 2021-04-13 12:29
Duplicate of TeamNewPipe/NewPipeExtractor#76. Services requests go to [the extractor repository](https://github.com/TeamNewPipe/NewPipeExtractor/). Please follow the template next time.

**Closed by TiA4f8R** 2021-04-13 12:29 UTC
Labels: enhancement
