### ISSUE TITLE
Add duplicate warning when adding video to playlist which has already been added

### ISSUE THREAD

**Issue by Mati20187** [TeamNewPipe/NewPipe#8370] opened 2022-05-08 12:54 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

It would be nice to have a pop-up saying something like: 
**This video has already been added to the playlist. Do you want to add it anyway?**
And have options:
**Add** and **Cancel**

### Why do you want this feature?

I often end up with duplicates in my playlists: I add a song to "Music" playlist, stumble upon the same song in watch suggestions a month later and add it again.

**Comment by SameenAhnaf** [comment] 2022-05-08 13:02
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4186

**Closed** 2022-05-08 13:04 UTC
Labels: enhancement
