### ISSUE TITLE
Specific Videos of Vevo cannot be played

### ISSUE THREAD

**Issue by Afx987** [TeamNewPipe/NewPipe#6396] opened 2021-05-29 18:30 UTC
This is a bug in YouTube api here is my description it happens only in videos of Vevo while searching Stacie Orrico 

### Steps to reproduce the bug

1. Go to 'search bar'
2. Find  on 'Stacie Orrico' with any vevo media
3. Open the video 

### Actual behaviour
 It shows an error that the video cannot be played 

### Expected behavior
 I think this is a problem expected on request directly asynchronous API from YouTube 

### Logs
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=wUOcQnWbk_U
* __Content Country:__ US
* __Content Language:__ es-US
* __App Language:__ es_US
* __Service:__ YouTube
* __Version:__ 0.21.3
* __OS:__ Linux motorola/ocean/ocean:10/QPO30.52-29/c0490:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not find videoSecondaryInfoRenderer
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getVideoSecondaryInfoRenderer(YoutubeStreamExtractor.java:970)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getAgeLimit(YoutubeStreamExtractor.java:239)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractImportantData(StreamInfo.java:106)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:71)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: 10
 - Device model: Moto G7 Power XT1955-2

**Comment by TiA4f8R** [comment] 2021-05-29 19:03
Yes, it's a problem of YouTube's side and this issue is a duplicate of #5326.

**Closed by TiA4f8R** 2021-05-29 19:03 UTC
Labels: bug
