### ISSUE TITLE
F-Droid Reproducible Builds now support v2/v3 signatures

### ISSUE THREAD

**Issue by obfusk** [TeamNewPipe/NewPipe#6168] opened 2021-04-25 14:46 UTC
The signing issue -- mentioned in #5069 and #5421 -- should be fixed now, so it should be possible for NewPipe to switch back to using Reproducible Builds for official F-Droid releases.

The `fdroiddata` CI has also been updated to test whether Reproducible Builds work.

**Comment by TobiGr** [comment] 2021-04-25 15:34
Thank for notifying us. I already saw [F-Droid's toot](https://mastodon.technology/@fdroidorg/106096743622198951) and was planning to update NewPipe's metadata before publishing the next release. I recently deleted my local buildserver VM which I used for testing, because I was running out of space. I am unsure whether I have enough time to set it up again to generate the APK and test the reproducibility again.

Btw. thank you for fixing the problems!

**Comment by obfusk** [comment] 2021-04-26 01:47
You should be able to use the `fdroiddata` CI to test the reproducibility (without needing a local build server VM). I tested my own apps by making a draft MR that just points to the latest commit (instead of a version tag) and adding the signatures using `fdroid signatures` from `fdroidserver` `master`. This way I could fix any outstanding reproducibility issues before the next release.

(I did run into some differences between the CI and the actual build server, but those were all NDK-related.)

**Comment by obfusk** [comment] 2021-06-14 23:26
See #6486 :(

**Comment by AudricV** [comment] 2024-02-10 22:10
NewPipe is currently signed with v1, v2 and v3 signatures, so this issue can be closed as fixed.

**Closed by AudricV** 2024-02-10 22:10 UTC
Labels: meta
