### ISSUE TITLE
Crash with fullscreen playback on T95Z android 7.1.1

### ISSUE THREAD

**Issue by Barkfin** [TeamNewPipe/NewPipe#9955] opened 2023-03-22 02:26 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

Click on any video whatsoever, the playback becomes fullscreen, and video freezes while audio plays. If you back out of the player, "guru meditation fault." 

	

### Expected behavior

Not crash. Player crashes 100% of the time, it is totally unusable.

### Actual behavior

I have replicated this with 0.24.0, 0.24.1, and 0.25.0.
For awhile 0.24.1worked in "mini player" in top-left corner of the screen with list of related videos on right side.
Click on "maximize video" causes exact same crash.
There is one way to reliably get full screen playback and that is to be playing one video in the top left corner, and before it is done select another from the list on the right, and change before the first video ends. The second video starts up and fills the screen, and does not crash. This only worked in 0.24.1 but since I updated to 0.25.0 there is no workaround. I even uninstalled and re-installed 0.24.1, nothing works anymore. App is 100% unusable.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4203)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4495)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:654)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:247)
	at android.view.View.dispatchDetachedFromWindow(View.java:15551)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3181)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3181)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3181)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3181)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3181)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3181)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3181)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3181)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4717)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4691)
	at android.view.ViewGroup.removeView(ViewGroup.java:4622)
	at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.kt:288)
	at androidx.fragment.app.SpecialEffectsController$Operation$State.applyState(SpecialEffectsController.java:470)
	at androidx.fragment.app.SpecialEffectsController$1.run(SpecialEffectsController.java:211)
	at androidx.fragment.app.SpecialEffectsController$Operation.complete(SpecialEffectsController.java:713)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:770)
	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:615)
	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:350)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2844)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2820)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:345)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:306)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:280)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:440)
	at android.app.Activity.performDestroy(Activity.java:6881)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190)
	... 10 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7.1.1, kernel 3.14.29

### Affected device model

T95Z+ 3GB

### Additional information

T95Z+ is a 3GB android playback media box connected to the TV and operated with a handheld remote control.
I believe this is the ideal use case for NewPipe.

**Comment by Motodavide** [comment] 2023-03-22 12:54
Similar situation with a Lenovo tablet with Android 7.1.1 - 25. App version 0.25.0.
<details><summary>Crash log</summary>
<p>

java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.finishDrawing(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:666)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:162)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

</p>
</details>

**Comment by AudricV** [comment] 2023-03-22 13:37
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

You did not, that's duplicate of an existing issue and is almost unfixable as this is a bug in Android 7 fixed in Android 8.

**Closed by AudricV** 2023-03-22 13:37 UTC
Labels: bug, needs triage
