### ISSUE TITLE
Request For Forking The App UI From LibreTube v0.3.1  Repository.

### ISSUE THREAD

**Issue by parasgargexx20** [TeamNewPipe/NewPipe#8480] opened 2022-06-04 09:37 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I Have Request For You (Dev's) To Fork The UI And Accent Colour Option From LibreTube That Way NewPipe Will Look Way More Mordern.

### Why do you want this feature?

The NewPipe App Design Looks As If I'm In Like 2015 Versus LibreTube Design Is Looking Like Very 2022 Like. Basically Looks A Lot More Mordern.
<img alt="Screenshot_20220604-140554_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993699-bc66a828-9eb2-4d8d-82cb-0daad889a5f7.png" height=600 /> <img alt="Screenshot_20220604-144440_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993706-e76055ae-77ec-40c6-8b4a-75369959d612.png" height=600 /> <img alt="Screenshot_20220604-144452_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993710-1f7e4f85-713f-4ad5-8ca9-c991a7607f6b.png" height=600 /> <img alt="Screenshot_20220604-144518_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993711-b47ed43e-891b-4aec-bb16-197cc8d57b9b.png" height=600 /> <img alt="Screenshot_20220604-144525_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993712-e1a7c89d-c78b-419e-91ba-5c020d9abaa1.png" height=600 /> <img alt="Screenshot_20220604-144531_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993714-7a5c5638-8c68-4f42-942e-f561531802da.png" height=600 /> <img alt="Screenshot_20220604-144535_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993716-0444cda3-236e-4129-bdf7-c51ac94a5b18.png" height=600 /> <img alt="Screenshot_20220604-144546_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993717-13994ad2-e297-4bf4-a1ed-3406a6bad43e.png" height=600 /> <img alt="Screenshot_20220604-144551_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993718-823e0b67-b85a-4dfa-b688-46a105c9e687.png" height=600 /> <img alt="Screenshot_20220604-144852_LibreTube" src="https://user-images.githubusercontent.com/102552831/171993719-d69ff13d-ce8e-49e3-b34f-1df19d22c891.png" height=600 />

### Additional information

I Also Want To Mention The LibreTube App Has Player Issues And Currently I'm Using Mobile Data So Thumbnail Didn't Load Up.Again, Hope You Can Fork Only The Design From LibreTube And Implement It In NewPipe And Keep The YouTube Thing Shown In The Below ScreenShot.
And Also The Current NewPipe Player To Load Up 1080p Videos Much Faster Than LibreTube ;).

![Screenshot_20220531-194352_NewPipe](https://user-images.githubusercontent.com/102552831/171194699-f6975ea5-c770-44f6-a230-9f961f66e2c5.png)

LibreTube GitHub Repository Link
https://github.com/libre-tube/LibreTube

**Comment by SameenAhnaf** [comment] 2022-06-04 10:02
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7595

**Comment by parasgargexx20** [comment] 2022-06-04 10:06
> Duplicate of #7595

Not A Duplicate

**Comment by parasgargexx20** [comment] 2022-06-04 10:10
> Duplicate of #7595

I Never Asked For Material You I Only Asked To Fork LibreTube Design

**Comment by hazysu** [comment] 2022-06-05 00:08
I definitely think NewPipe needs some sort of redesign, but personally I think LibreTube doesn't actually look that much better. LibreTube looks weird in a different way. It uses both purple and blue for backgrounds of some items, the margins are a bit unnecessarily big, the rounding on items is also a bit extreme.
Of course, just my opinion, but I'd prefer to see a material-you redesign than just pulling the LibreTube design into NewPipe.

**Comment by tsiflimagas** [comment] 2022-06-05 00:14
No offense, but saying "go and copy that app's look" is, apart of too generic, unreasonable.

**Comment by parasgargexx20** [comment] 2022-06-05 02:46
> I definitely think NewPipe needs some sort of redesign, but personally I think LibreTube doesn't actually look that much better. LibreTube looks weird in a different way. It uses both purple and blue for backgrounds of some items, the margins are a bit unnecessarily big, the rounding on items is also a bit extreme. Of course, just my opinion, but I'd prefer to see a material-you redesign than just pulling the LibreTube design into NewPipe.

Fine.I Thought You Would Have Liked LibreTube Design But Ok

**Comment by lilcheti** [comment] 2022-06-05 04:04
Hey, LibreTube dev here Is there anyone from here willing to help us on this, to not use piped instances and make the player better?
It would be awesome thanks!

**Comment by hazysu** [comment] 2022-06-05 04:31
> Hey, LibreTube dev here Is there anyone from here willing to help us on these, to not use piped instances and make the player better?
> It would be awesome thanks!

Seeing as your goal for LibreTube was [to make a client that functions even when YouTube is blocked](https://github.com/libre-tube/LibreTube/issues/53#issuecomment-1066507391), I don't see any way you can switch away from using Piped instances. If you fetched content directly, it'd load much faster, but in regions where YouTube is banned it would simply not work, same as using NewPipe or Vanced or anything else. If you want to provide both solutions however, I'd suggest looking into using NewPipeExtractor, the same library used by NewPipe and also which is used by Piped instances.

**Comment by pc00per** [comment] 2022-06-06 15:23
Newpipe ingeneral never had a team that had gui development in mind. So I don't think any redesign is even possible for now. This is already an issue that's been asked like a zillion times.

**Comment by Stypox** [comment] 2022-07-04 20:59
> Newpipe ingeneral never had a team that had gui development in mind

Thank you? Anyway, that's right, we never had a clear team direction about the UI. Most parts of the app have not changed since, like, ever (for example, the non-good-looking thumbnail code from #8573 had been there since forever). If you are an Android app designer, or you know somebody, you could start opening small pull requests improving some details here and there over time (doing one big PR would be problematic). 

This issue is not useful, though, as copying a whole UI design from another app is not a good idea and also not completely doable (due to different needs). The issue that addresses migrating to more recent design standard is, as already mentioned, #7595. So I'm closing this as a duplicate of #7595.

**Closed by Stypox** 2022-07-04 20:59 UTC
Labels: enhancement, discussion, GUI
