### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Karelinsony** [TeamNewPipe/NewPipe#4670] opened 2020-10-27 06:07 UTC
Error while watching video from history

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=mqB7g4mK60c
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ YouTube
* __Version:__ 0.20.1
* __OS:__ Linux Xiaomi/dipper/dipper:10/QKQ1.190828.002/V11.0.4.0.QEAMIXM:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: YouTube did not provide player config even after three attempts
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(Unknown Source:259)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Unknown Source:7)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(Unknown Source:0)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(Unknown Source:4)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(Unknown Source:4)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(Unknown Source:16)
	at io.reactivex.Single.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(Unknown Source:7)
	at io.reactivex.Single.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(Unknown Source:7)
	at io.reactivex.Maybe.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(Unknown Source:90)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(Unknown Source:11)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(Unknown Source:20)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(Unknown Source:7)
	at io.reactivex.Flowable.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(Unknown Source:9)
	at io.reactivex.Maybe.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(Unknown Source:9)
	at io.reactivex.Single.subscribe(Unknown Source:14)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source:2)
	at io.reactivex.Scheduler$DisposeTask.run(Unknown Source:9)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by xibr** [comment] 2020-10-27 06:20
Duplicate of #4572.

**Closed** 2020-10-27 06:21 UTC
Labels: bug
