### ISSUE TITLE
newpipe loop loading video

### ISSUE THREAD

**Issue by Domiuns** [TeamNewPipe/NewPipe#3949] opened 2020-07-27 16:38 UTC
### Version

-

### Logs

Newpipe can't load video from this channel https://www.youtube.com/channel/UCn6Wa9PYgVtnRSJPug9XO4A
I have try to change resolution but nothing change, video don't want start :( i think is problem with extractor.

**Comment by wb9688** [comment] 2020-07-27 17:21
If the resolution doesn't show x MB in the download dialog, it indeed won't load. Duplicate of #2415.

**Comment by opusforlife2** [comment] 2020-07-27 17:21
@Domiuns They're DASH videos. Same issue as #2415. You can see that they play fine on 360p MPEG-4.

**Closed by wb9688** 2020-07-27 17:21 UTC
Labels: bug
