### ISSUE TITLE
Missing comment replies

### ISSUE THREAD

**Issue by pizzaHar** [TeamNewPipe/NewPipe#2590] opened 2019-09-01 10:35 UTC
NewPip seems that only single comments are showed. where no one has responded.

but comments that are discussed (reply) are not displayed.

**Comment by soshial** [comment] 2020-02-21 09:53
Probably, a relevant bug that I found for comments:
## BUG: "no comments" seen in NewPipe
(while THERE ARE COMMENTS on YouTube)

#### 1. On Youtube:

![Screenshot_20200221-074508](https://user-images.githubusercontent.com/100644/75023348-56717c80-54a0-11ea-8c79-7be7569e576e.png)

#### 2. On NewPipe:

![Screenshot_20200221-074531](https://user-images.githubusercontent.com/100644/75023359-5bcec700-54a0-11ea-8be8-9f05fca18a18.png)

#### 3. In browser (it is hidden, which is probably the reason of the bug):
<img width="1249" alt="Screenshot 2020-02-21 at 11 41 28" src="https://user-images.githubusercontent.com/100644/75023547-a94b3400-54a0-11ea-8ab2-2953af0d9b78.png">


The bug reproduces perfectly on this video : https://www.youtube.com/watch?v=t_gl0Dvmxlc

**Comment by Stypox** [comment] 2020-02-21 13:52
@soshial please open a different issue ;-)

**Comment by soshial** [comment] 2020-02-22 06:58
Opened https://github.com/TeamNewPipe/NewPipe/issues/3126 and deleted the comment here.

**Comment by B0pol** [comment] 2020-05-10 10:18
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2277

**Closed by B0pol** 2020-05-10 10:18 UTC
Labels: enhancement, requires extractor change
