### ISSUE TITLE
View the entire comment thread on youtube

### ISSUE THREAD

**Issue by kyanhluong** [TeamNewPipe/NewPipe#3533] opened 2020-05-05 13:04 UTC
#### Describe the feature you want

I want to see sub comment of comment, something NewPipe don't do
There invidio.us which do show the entire comment thread but only play up 720p

#### Is your feature request related to a problem? Please describe it

Normally if i want to see the entire comment thread, i have to :
-switch to miniplayer
-open browser go to invidio.us , search the same video then look at the comment
The other alternative i know is switch to stock youtube app

#### How will you/everyone benefit from this feature?

So the user wont have to go back to stock youtube app or visit invidio.us to see the full thread which either breaking privacy or tedious

**Comment by wb9688** [comment] 2020-05-05 13:43
Duplicate of #2590

**Closed by wb9688** 2020-05-05 13:43 UTC
Labels: enhancement
