### ISSUE TITLE
Can you add full screen button so that I don't have to turn on auto rotation to view videos in full screen?

### ISSUE THREAD

**Issue by ixxakthomas** [TeamNewPipe/NewPipe#7690] opened 2022-01-23 17:46 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment] 2022-01-23 17:50
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4478. Also, please fill in the template properly.

**Closed** 2022-01-23 18:03 UTC
Labels: enhancement
