### ISSUE TITLE
Whenever I connect to my car's bluetooth radio, the newpipe audio only player pops up

### ISSUE THREAD

**Issue by Haxaaaa** [TeamNewPipe/NewPipe#6541] opened 2021-06-21 05:48 UTC
Whenever I connect to my car's bluetooth radio, the newpipe audio only player pops up

### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version: Android 9
 - Device model: Samsung Note10+

**Comment by Haxaaaa** [comment] 2021-06-21 05:49
Whenever I connect to my car's bluetooth radio, the newpipe audio only player pops up

**Comment by mhmdanas** [comment] 2021-06-21 14:36
Duplicate of #6233 (see https://github.com/TeamNewPipe/NewPipe/issues/5989#issuecomment-855012122).

**Closed by mhmdanas** 2021-06-21 14:36 UTC
Labels: bug
