### ISSUE TITLE
Share video URL without playing the video

### ISSUE THREAD

**Issue by kjgeyumubdutmjtuyj** [TeamNewPipe/NewPipe#5484] opened 2021-01-23 10:53 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Add Share button for sharing video link in video details screen near the description or beside download button so that users won't need to play the video just to get to the share video button in the video player

#### Is your feature request related to a problem? Please describe it

Nope

#### Additional context

Feature was removed after UI overhaul
![image](https://user-images.githubusercontent.com/77880578/105576118-9f663b00-5dab-11eb-9e67-8d0cd63f6fc1.png)

#### How will you/everyone benefit from this feature?

Easier way of getting the video URL of currently opened video without playing the video.
Reduce internet usage when on mobile data.

**Comment by vkay94** [comment] 2021-01-23 13:27
This feature is already merged and will be available in the upcoming release (0.20.9). You can already try it yourself by installing the RC in the pinned area - look here how it looks #4534

**Closed by vkay94** 2021-01-23 13:27 UTC
Labels: enhancement

**Comment by opusforlife2** [comment] 2021-01-23 13:34
More importantly,
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

Duplicate of #4039. Check more carefully next time?
