### ISSUE TITLE
Shuffling on big playlists

### ISSUE THREAD

**Issue by bphd** [TeamNewPipe/NewPipe#5547] opened 2021-02-09 21:36 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

(Any way to get a big playlist is valid, here I will use the "play all" function on a channel to generate a big playlist)

Go to a channel
Choose "Play all" or "Background" or equivalent
Go the the played playlist (I cannot find function to do that other than clicking on the associated notification. No way to do that into the app...)
Toggle the shuffle button on the bottom

### Actual behaviour

Only the element on the playlist showed is shuffled (so in my example the last 20-30ish videoes of the youtuber). So it's impossible to really shuffle all his channel, hence it's impossible to fall into the first created videoes (as the playlist generates, it takes the last videoes, so even re-shuffling with that does not get older videoes)

### Expected behavior

The player should take all the elements of the playlist (here all the videoes of the channel) and shuffle that, so I will get other things than a mix of the last videoes

Notice that YouTube have this behaviour with his playlists, it already generated a complete playlist, so it shuffle it and it's perfect. If it's a generated playlist like "next video" it takes from the algorthm anyway so it stays random

### Device info

 - Android version/Custom ROM version: Reproduce on all
 - Device model: Reproduce on all

**Comment by mhmdanas** [comment] 2021-02-10 08:59
Duplicate of #5125.

**Closed by mhmdanas** 2021-02-10 08:59 UTC
Labels: bug

**Comment by bphd** [comment] 2021-02-10 09:04
Maybe the guy reported a similar problem, but the thing is that the reply is only about how to customize buttons on the notification panel, and not how to repair that shuffle problem

So please, either reopen one of those 2 issues or both, but don't close issues not resolved, thanks

**Comment by mhmdanas** [comment] 2021-02-10 09:07
That issue is still open; it hasn't been closed. The person who replied was just saying that the reporter can customize the buttons in the notification, which the reporter thought was not possible:
> And I would like to have a shuffle button in the notification panel, not only the repeat button option.

**Comment by bphd** [comment] 2021-02-10 09:26
Oh okay, I read rapidly and my closed issue was reported on this issue
