### ISSUE TITLE
Folder for Playlists

### ISSUE THREAD

**Issue by Sam4000der3** [TeamNewPipe/NewPipe#8084] opened 2022-03-20 18:56 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

A folder structure for playlists should promote clarity. This is especially necessary for people with a lot of playlists.

### Why do you want this feature?

I I use NewPipe a lot for listening to music and need a folder structure for playlists for a better overview. For example, folders for filtering by genre or by language.

**Comment by SameenAhnaf** [comment] 2022-03-20 19:41
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1313

**Comment by Sam4000der3** [comment] 2022-03-20 20:01
> Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1313

Sorry. In my preliminary search I did not find or overlooked the entry.

**Closed** 2022-03-20 20:02 UTC
Labels: enhancement
