### ISSUE TITLE
Video player should be fixed when scrolling through comments/description/similar.

### ISSUE THREAD

**Issue by tactical-snail** [TeamNewPipe/NewPipe#7605] opened 2022-01-01 09:48 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

When scrolling through the comments/description/similar videos while watching a video, the video player should be fixed, like the original youtube app/website. It should not scroll up.

#### Why do you want this feature?

It would help in reading them without needing to pause the video.

**Comment by SameenAhnaf** [comment] 2022-01-01 11:37
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4484

**Closed** 2022-01-01 14:48 UTC
Labels: enhancement
