### ISSUE TITLE
Opera Classic & newpipe

### ISSUE THREAD

**Issue by Baltazar500** [TeamNewPipe/NewPipe#2266] opened 2019-04-03 07:28 UTC
Auto send link from Opera Classic causes newpipe to crash :

"user_action": "something"
"request": "null"
"content_language": "RU"
"service": "none"
"package": "org.schabi.newpipe"
"version": "0.16.0"
"os": "Linux Android 5.1 - 22"
"time": "2019-04-03 07:12"

"exceptions":

"java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.acceptUrl(java.lang.String)' on a null object reference
org.schabi.newpipe.extractor.StreamingService.getLinkTypeByUrl(StreamingService.java:315)
org.schabi.newpipe.extractor.NewPipe.getServiceByUrl(NewPipe.java:75)
org.schabi.newpipe.RouterActivity.lambda$handleUrl$0(RouterActivity.java:130)
org.schabi.newpipe.-$$Lambda$RouterActivity$jGbV3sDp3V_oonJa1z1jLD1TKkg.call(lambda)
io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
io.reactivex.Observable.subscribe(Observable.java:12090)
io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
java.util.concurrent.FutureTask.run(FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)"

###

In newpipe 0.14.1 auto send works without problems

**Comment by ouzowtf** [comment] 2019-04-03 08:11
Try again with the current version 0.16.1

**Comment by Baltazar500** [comment] 2019-04-03 09:54
"URL no supported"

**Comment by Baltazar500** [comment] 2019-04-03 09:55
"URL not supported"

**Comment by TobiGr** [comment] 2019-04-03 14:14
Can someone please post a link which causes the crash? I cannot reproduce it.

**Comment by gkeegan** [comment] 2019-04-03 14:53
@Baltazar500 you got "URL not supported" after upgrading to version 0.16.1? Also please give your link like was asked.

**Comment by Baltazar500** [comment] 2019-04-06 07:17
>you got "URL not supported" after upgrading to version 0.16.1?
yes
> Also please give your link like was asked.
any youtube url

Perhaps the problem is somewhere in the "vnd.youtube" url, which Opera Classic's is transmitted to newpipe?

**Comment by TobiGr** [comment] 2019-04-13 17:48
Can you please post a link which is shared by opera classic? We need the shared link to see what is going wrong as the opera classic is no longer available.

**Comment by Baltazar500** [comment] 2019-04-14 03:43
>Can you please post a link which is shared by opera classic?

Original url: https://www.youtube.com/watch?v=rCKL7Y_Iv2E

From logcat: 

I/ActivityManager(  869): START u0 {act=android.intent.action.VIEW dat=vnd.youtube:rCKL7Y_Iv2E?vndapp=youtube_mobile&vndclient=mv-google&vndel=home flg=0x3000000 cmp=org.schabi.newpipe/.RouterActivity} from uid 10085 on display 0

>We need the shared link to see what is going wrong as the opera classic is no longer available.

https://get.geo.opera.com/pub/opera/android/classic/Mobile_Classic_12_1_9_Generic_Opera_ARMv5v7.apk

**Comment by TobiGr** [comment] 2019-04-14 09:27
`vnd.youtube:rCKL7Y_Iv2E?vndapp=youtube_mobile&vndclient=mv-google&vndel=home` us definitely not  a valid URL. We could add support for this, but atm there are other things to do. In other words, this is has a very low priority. Changes by Opera which are very unlikely, since the latest Opera Classic APK was released in 2015.
However, #1963 will be included in the next release. This should fix the problem for you. Please let us know if 0.16.2 if it does. If not, we can try to find a solution.

**Comment by B0pol** [comment] 2020-05-09 22:16
closed in https://github.com/TeamNewPipe/NewPipeExtractor/pull/324/

**Closed by B0pol** 2020-05-09 22:16 UTC
Labels: device/software specific, enhancement

**Comment by Baltazar500** [comment] 2020-11-21 04:13
And again :(

"user_action": "something"
"request": "vnd.youtube:d3dNyavyMOo?vndapp=youtube_mobile&vndclient=mv-google&vndel=home"
"content_language": "ru"
"content_country": "RU"
"app_language": "ru_RU"
"service": "none"
"package": "org.schabi.newpipe"
"version": "0.20.2"
"os": "Linux Android 5.1 - 22"
"time": "2020-11-21 03:55"

java.lang.IllegalArgumentException: The given URL is not valid
at org.schabi.newpipe.extractor.services.media_ccc.linkHandler.MediaCCCStreamLinkHandlerFactory.getId(MediaCCCStreamLinkHandlerFactory.java:27)
at org.schabi.newpipe.extractor.services.media_ccc.linkHandler.MediaCCCStreamLinkHandlerFactory.onAcceptUrl(MediaCCCStreamLinkHandlerFactory.java:51)
at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.acceptUrl(LinkHandlerFactory.java:80)
at org.schabi.newpipe.extractor.StreamingService.getLinkTypeByUrl(StreamingService.java:287)
at org.schabi.newpipe.extractor.NewPipe.getServiceByUrl(NewPipe.java:93)
at org.schabi.newpipe.RouterActivity.lambda$handleUrl$0$RouterActivity(RouterActivity.java:148)
at org.schabi.newpipe.-$$Lambda$RouterActivity$jGbV3sDp3V_oonJa1z1jLD1TKkg.call(lambda)
at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

NewPipe 0.20.02 crashes when opening youtube links from google in Opera Classic on Android 5.1. On Android 4.2.2 + NewPipe Legacy 0.20.02, everything works without crashes.
