### ISSUE TITLE
Voice commands

### ISSUE THREAD

**Issue by bphd** [TeamNewPipe/NewPipe#7339] opened 2021-10-31 15:08 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?

Is there anything to control vocally NewPipe? Because I use it often when i'm on my car, and it's really difficult (and dangerous/illegal) to type what I want to see/listen on the app

Ideally NewPipe would be controlled with voice commands like

"NewPipe, play in background video named NewPipe presentation"

"NewPipe, search for video named NewPipe presentation..... NewPipe, play the second result in fullscreen"

"NewPipe, switch the video in a frame"

"NewPipe, reduce the app (NewPipe) in split screen" (or in pin for newer Android)

And a voice command for any other relevant commands

And maybe a Google Assistant shortcut to make a search from it, because now it only uses YouTube to search

For now, in NewPipe, you need to manually manage how the app displays (fullscreen, split screen, pinned), which is dangerous to make while driving (I like it at side of Waze). And the only thing that can be vocalized is the search terms via the Google Assistant of the keyboard. So you still need a lot of manual manipulation

**Comment by SameenAhnaf** [comment] 2021-10-31 15:21
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2159

**Closed** 2021-10-31 15:23 UTC
Labels: question
