### ISSUE TITLE
Add maximize button even if screen rotation is enabled

### ISSUE THREAD

**Issue by iamthesenate1** [TeamNewPipe/NewPipe#5798] opened 2021-03-09 00:16 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

It would be nice if we had the maximize button even if screen rotation is enabled in the phone settings, just like the YouTube app.

#### How will you/everyone benefit from this feature?

I beleve this feature will make it easier to maximize, giving us more options and making new users feel more confortable.

**Comment by mhmdanas** [comment] 2021-03-09 05:05
Thanks for opening an issue! I believe this is a duplicate of #4478. If you disagree, feel free to make a comment.

**Closed by mhmdanas** 2021-03-09 05:05 UTC
Labels: enhancement
