### ISSUE TITLE
Play queue shows a wrong playback speed

### ISSUE THREAD

**Issue by 532910** [TeamNewPipe/NewPipe#4847] opened 2020-11-09 13:47 UTC
Steps to reproduce:
1. Set some playback speed so it become remembered
2. Open youtube video and start playback in the background
3. Tap notification
4. The result is on the screenshot:
![Screenshot_20201109-134027_NewPipe](https://user-images.githubusercontent.com/14617699/98548457-997fb400-22aa-11eb-9316-b9363fcff542.png)

version 0.20.2 from newpipe's fdroid channel

**Comment by Stypox** [comment] 2020-11-09 21:19
This is a known issue and is probably a duplicate of some closed issue, but it should stay open ;-)
Thank you for the report, but **please follow the template next time**

**Comment by Stypox** [comment] 2022-11-07 20:45
This was solved in the meantime

**Closed by Stypox** 2022-11-07 20:45 UTC
Labels: bug, player
