### ISSUE TITLE
Release 0.20.7

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#5245] opened 2020-12-21 20:17 UTC
# Changelogs
### New
- YouTube Mix support (radio icon as creator avatar used to differentiate between normal playlists) #3243 
- [YouTube] Display additional info about search query (Covid-19), video creators (public broadcaster) or video content (Covid-19) #4754 

### Improved
- Update Invidious URL list in the manifest #4859
- Use user agent of DownloaderImpl also in ReCaptchaActivity #5215 

### Fixed
- Fixed crash deleting video refreshing #5116 
- Fixed blank ReCaptcha webview #5208
- Removed timestamp from share URL for all services except YouTube #5228 
- Updated NewPipe's website domain name #5184 #5236

### Development
- Use GitHub actions as a CI instead of Travis. #5132 
- Fix some typos #5112
- Use ContextCompat.getDataDir() #5176
- Use a notification instead of a ProgressDialog in MissionAdapter #5142 
- Use ActivityCompat.recreate() #5178
- Extract export database logic into own class #5059, #5186, #5204
- Use view binding in activities #4762 
- Use WebViewClientCompat #5217 
- Use ServiceCompat.stopForeground() #5218

### New
- [YouTube] Mix support (auto-generated playlists) TeamNewPipe/NewPipeExtractor#280, TeamNewPipe/NewPipeExtractor#483
- [YouTube] stream segments support TeamNewPipe/NewPipeExtractor#479 

### Fixed
-  [PeerTube] Fixed related streams API URL when no tags TeamNewPipe/NewPipeExtractor#490 

### Development
- Use Objects methods TeamNewPipe/NewPipeExtractor#419

# To do
- [x] #4754 
- [ ] ~~#4814~~
- [x] TeamNewPipe/NewPipeExtractor#484
- [x] Weblate translation sync 
- [x] fastlane changelog

# APK for testing

[NewPipe_v0.20.7_RC5.zip](https://github.com/TeamNewPipe/NewPipe/files/5742262/NewPipe_v0.20.7_RC5.zip)

**See the corresponding PR #5246**

**Comment by Poolitzer** [comment] 2020-12-22 11:31
Accessing the player queue via notification when the player is in the background opens the correct view, but nothing is enqueued/the player is not accessible.

**Comment by HTSamurai** [comment] 2020-12-22 13:59
Ooh nice! Finally i can use mixes! When is the full release of this version?

**Comment by HTSamurai** [comment] 2020-12-22 14:01
And my youtube chapters/segnests! Thanks for adding my idea!

**Comment by XiangRongLin** [comment] 2020-12-22 16:23
@TobiGr You need to replace the extractor links. They are currently pointing to this repo

**Comment by TobiGr** [comment] 2020-12-22 16:54
[The problem](https://github.com/TeamNewPipe/NewPipe/issues/5245#issuecomment-749495460) described by @Poolitzer was caused by e6021465f677d91afe68ef17bacaf5251f4e200a. @Isira-Seneviratne Do you have time for fixing this?

**Comment by agravier** [comment] 2020-12-23 02:06
Opened the RC1, tried to play https://www.youtube.com/watch?v=-cf5CGYjGt4 from the search, raised an exception as follows:

(The music still plays)

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.VideoDetailFragment.ACTION_PLAYER_STARTED flg=0x10 } in org.schabi.newpipe.fragments.detail.VideoDetailFragment$4@6fa63fa
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1590)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.schabi.newpipe/.player.MainPlayer }: app is in background uid UidRecord{4a715eb u0a394 CAC  bg:+2m19s320ms idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1715)
	at android.app.ContextImpl.startService(ContextImpl.java:1670)
	at android.content.ContextWrapper.startService(ContextWrapper.java:720)
	at org.schabi.newpipe.player.helper.PlayerHolder.startService(PlayerHolder.java:59)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$4.onReceive(VideoDetailFragment.java:1343)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
	... 8 more

```
</details>
<hr>

**Comment by Isira-Seneviratne** [comment] 2020-12-23 04:01
> [The problem](https://github.com/TeamNewPipe/NewPipe/issues/5245#issuecomment-749495460) described by @Poolitzer was caused by [e602146](https://github.com/TeamNewPipe/NewPipe/commit/e6021465f677d91afe68ef17bacaf5251f4e200a). @Isira-Seneviratne Do you have time for fixing this?
> 
> @XiangRongLin Fixed.

I'll do it in a few hours.

@Stypox did you come across this issue?

**Comment by Stypox** [comment] 2020-12-23 07:32
@Isira-Seneviratne I could reproduce, but didn't come across this issue while testing

@agravier that's caused by the interactions of multiple NewPipes and is not related to this release

**Comment by vkay94** [comment] 2020-12-23 10:14
>I'm not sure what's causing the issue, since I made sure to keep the logic the same.

Yeah, that's pretty strange, especially the fact that the layout is showing correctly for a moment and disappears again ...

**Comment by TobiGr** [comment] 2020-12-23 13:29
[NewPipe_v0.20.7_RC2.zip](https://github.com/TeamNewPipe/NewPipe/files/5735423/NewPipe_v0.20.7_RC2.zip) contains:
- translation updates
- stream and search meta info (public broadcasters and Covid-19)
- ktlint update

**Comment by Isira-Seneviratne** [comment] 2020-12-23 15:04
@Stypox I fixed the issue.

**Comment by TobiGr** [comment] 2020-12-23 15:20
[NewPipe_v0.20.7_RC3.zip](https://github.com/TeamNewPipe/NewPipe/files/5735862/NewPipe_v0.20.7_RC3.zip) contains @Isira-Seneviratne's fix for the empty play queue

**Comment by B0pol** [comment] 2020-12-23 19:05
> @Isira-Seneviratne I could reproduce, but didn't come across this issue while testing
> 
> @agravier that's caused by the interactions of multiple NewPipes and is not related to this release

and is fixed by #5221, hopefully in the next update

**Comment by TobiGr** [comment] 2020-12-23 19:12
[NewPipe_v0.20.3_RC4.zip](https://github.com/TeamNewPipe/NewPipe/files/5736751/NewPipe_v0.20.3_RC4.zip) fixes `media.ccc.de`'s service color and adds Somali to the app language chooser.

The changelog for this release is ready to be translated on weblate: https://hosted.weblate.org/projects/newpipe/metadata/

**Comment by B0pol** [comment] 2020-12-23 19:49
Regression: 

## Exception
* __User Action:__ requested playlist
* __Request:__ https://music.youtube.com/playlist?list=RDCLAK5uy_l5CaXPtlHAWKUBF5rj9w5xII1Bugs-iwc
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ YouTube
* __Version:__ 0.20.6
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Got HTML document, expected JSON response (latest url was: "https://www.youtube.com/watch?v=CLAK5uy_l5C")
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getValidJsonResponseBody(YoutubeParsingHelper.java:575)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getResponse(YoutubeParsingHelper.java:588)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeMixPlaylistExtractor.onFetchPage(YoutubeMixPlaylistExtractor.java:59)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getPlaylistInfo$9(ExtractorHelper.java:172)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$RLOrwix0kCDfcc_WpFBc8DTJw0Q.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by TobiGr** [comment] 2020-12-23 20:10
Regression will be fixed by https://github.com/TeamNewPipe/NewPipeExtractor/pull/484

**Comment by Poolitzer** [comment] 2020-12-24 16:37
blogpost can be found at TeamNewPipe/Website#211

**Comment by TobiGr** [comment] 2020-12-25 18:04
Last RC containing the fix for YouTube Music search and a fixed regression for YouTube Music Playlists
[NewPipe_v0.20.7_RC5.zip](https://github.com/TeamNewPipe/NewPipe/files/5742262/NewPipe_v0.20.7_RC5.zip)

**Closed** 2020-12-26 16:14 UTC
