### ISSUE TITLE
Download a whole playlist

### ISSUE THREAD

**Issue by Frouk3** [TeamNewPipe/NewPipe#6250] opened 2021-05-06 14:43 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Make a feature to download whole playlist

#### How will you/everyone benefit from this feature?

This feature make downloading a bit easier, like someone wanna to download his favourite music, but it will take too long to download whole music by pressing every video and download an audio. This feature may be useful for people who wanna download memes.

**Comment by mhmdanas** [comment] 2021-05-06 16:01
Duplicate of #2380.

**Closed by mhmdanas** 2021-05-06 16:01 UTC
Labels: enhancement
