### ISSUE TITLE
Watched video mark

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#5497] opened 2021-01-27 16:19 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

There already are a red line under videos which indicates how much you watched of a certain video. But after i watched this video it disappears. If i watched a video i would like a mark of some sort that indicates that i watched that video.

**Comment by mizzunet** [comment] 2021-02-25 12:37
Is this feature has been added? It doesn't seem to. I can't see any indiaction on video that I have watched, maybe I'm wrong :D

**Comment by PavelCibulka** [comment] 2021-03-29 08:47
This would be great. Some mark that video has been finished. Something like Podcast Addict has.

**Comment by mhmdanas** [comment] 2021-04-06 07:01
Closing as a duplicate of #5497.

**Closed by mhmdanas** 2021-04-06 07:01 UTC
Labels: GUI, enhancement
