### ISSUE TITLE
Searching videoswithin a channel

### ISSUE THREAD

**Issue by ewokie** [TeamNewPipe/NewPipe#7650] opened 2022-01-13 15:01 UTC
Just installed this app and great so far
1 question
 is there ability to search for the  subscribed channels videos?
 Or is it possible and I can't find that option?

Thanks

**Comment by SameenAhnaf** [comment] 2022-01-13 15:14
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5441. Also please fill in the template properly. You're not supposed to remove it.

**Closed** 2022-01-13 16:12 UTC
Labels: question
