### ISSUE TITLE
add sorting options to "whats new" tab

### ISSUE THREAD

**Issue by dasapa4746** [TeamNewPipe/NewPipe#8448] opened 2022-05-27 21:39 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

some sorting options would be nice, like by length (ascending, descending), by channel (videos of the same channel together), by channel group (videos of the same channel group together) and by release to get back to the current view

### Why do you want this feature?

to be honest this isn't something I can't live without, but would be nice to have, and who knows, maybe is a thing other people that don't know how to open issues want, but if not I understand the work it takes to get a new feature up

**Comment by SameenAhnaf** [comment] 2022-05-27 22:12
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/8069

**Closed** 2022-05-28 18:39 UTC
Labels: enhancement, template-ignored, duplicate
