### ISSUE TITLE
21% battery usage with no use and background activity restricted

### ISSUE THREAD

**Issue by karan** [TeamNewPipe/NewPipe#5616] opened 2021-02-17 14:48 UTC
### Checklist

- [x] I am using the latest version - 0.20.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Install the client on Pixel.

### Actual behaviour

21% battery usage with no app use and background activity restricted.

### Expected behavior

No battery should be used because there's no background activity, and the app is not used.

### Screenshots/Screen recordings

![Screenshot_20210217-064330](https://user-images.githubusercontent.com/3261985/108220677-db12cd00-70eb-11eb-9ba3-33a50a04f36f.png)
![Screenshot_20210217-064351](https://user-images.githubusercontent.com/3261985/108220697-dea65400-70eb-11eb-9b2a-d950a1629532.png)

### Device info

 - Android version/Custom ROM version: QP1A.191005.007.A3 (Pixel ROM Android 10)
 - Device model: Pixel

**Comment by hugohelder** [comment] 2021-09-02 19:33
I can confirm I have the same issue, with android 11 and background description applied. Tried switching resolutions and codecs, didn't work. Will look further

**Comment by mibzman** [comment] 2021-09-09 13:06
I'm having the same issue.  I tried out the cpufix-1 build for a bit, and I'm seeing about the same power draw.  Watching videos in the foreground for 40 minute used 7%, and listening in the background for about an hour used another 6%.  I'm surprised that the background usage is so high, I expected it to be much lower.

I closed the media notification card, I'll keep an eye on it and see if NewPipe draws any more power with the card closed, then listen to something else later today, but leave the card open and paused and see what happens.

**Comment by mibzman** [comment] 2021-09-29 23:56
After running the new build for awhile I haven't noticed a change in power consumption, it's still pretty high.

**Comment by stukkat** [comment] 2021-11-08 09:31
Just had this issue with NewPipe 0.21.13 on Android 10.
12 minutes of foreground use, 6 background free with a 35% battery drain.

Downgraded to NewPipe 0.21.12 and this behavior stopped.

**Comment by litetex** [comment] 2021-11-28 16:02
I don't think this problem exists anymore, as a pretty similar issue was fixed recently: #7166

Also my power consumption stats for the last few days since I charged my phone to 100% are pretty normal:
* Battery usage: 12%
* Used CPU time: 3h 20m
* Used CPU in background: 3m 25s
* Downloaded data: 3600MB (720p 30/60FPS)
* Used energy: 500mAh (from a 3000mAh battery + some minor charges in the meantime)

I think this is more a hardware problem. Maybe a bad battery?

**Comment by mibzman** [comment] 2021-12-01 21:06
I ran 0.21.13 for an hour this morning and I got an appropriate amount of power usage and no mysterious background power draw afterwards.  Seems fixed to me!

**Comment by litetex** [comment] 2021-12-02 18:44
If no further objections occur (from the author= the issue will be closed in 14 days.

**Closed** 2021-12-17 00:07 UTC
Labels: bug, waiting-for-author
