### ISSUE TITLE
Dates of the videos are indicated in the language of the country I'm in

### ISSUE THREAD

**Issue by unalignedcoder** [TeamNewPipe/NewPipe#1718] opened 2018-09-15 02:50 UTC
Sorry if I may not report this properly, I'm on my phone and without much time. It seems that the dates of the videos are indicated in the language of the locale of the google/YouTube servers, rather than the locale the user has chosen for their phone.

**Comment by sNrVJx** [comment] 2018-09-15 06:04
Yea, I'd like to see them in english too instead of my location language.

**Comment by trymeouteh** [comment] 2018-09-23 04:10
From what I understand this is caused by VPNs. When I connect to a server in another country that is no the same language as my country it will appear in that countrys language. I hope NewPipe devs can find a way to ensure that the date appears in the language on your phone.

**Comment by unalignedcoder** [comment] 2018-09-23 09:39
Nothing to do with VPN. Although it shows that NewPipe retrieves the date strings from the servers but does not process them. I think I understand why. It can't be easy to convert those since they are in that friendly format.

**Comment by selay01** [comment] 2019-05-06 10:25
@unalignedcoder @sNrVJx  @trymeouteh 
Not caused by vpn, but vpn can also cause this problem.
The key point seems to be the location of the exit ip that initiated the request. 

I opened a related issue:
https://github.com/TeamNewPipe/NewPipe/issues/2330

**Comment by Stypox** [comment] 2019-08-28 07:10
Duplicate of #578

**Closed by Stypox** 2019-08-28 07:10 UTC
