### ISSUE TITLE
Full brightness is forced when playing video

### ISSUE THREAD

**Issue by ultimatevert** [TeamNewPipe/NewPipe#1456] opened 2018-06-06 03:27 UTC
I carefully read the contribution guidelines and agree to them.
I checked if the issue/feature exists in the latest version

This did not occur in 0.13.4 but does occur in 0.13.5

Whenever I play videos full brightness is forced on and even the 0% brightness setting using gestures does not go as low as Android allows. This did not used to happen in the previous versions and I can no longer watch videos in the dark as they become to bright. If I close the video, my brightness goes back to what I set it to in Android.

Can this be reversed or be an option to turn off this feature?

**Comment by wb9688** [comment] 2018-06-06 05:53
I think you can swipe down on the left side, but it should use your
system's brightness by default

**Comment by theScrabi** [comment] 2018-06-06 10:47
@acrosca changed the way brightnes is handled during the last release. Remember brightness for the session #1416 #1442

@acrosca could you please check this.

**Comment by acrosca** [comment] 2018-06-06 11:30
Is the phone special in any way?

I set the brights to the value specified by Android documentation to result in default value.
I will research the issue but nothing seems obviously wrong now.

**Comment by ultimatevert** [comment] 2018-06-08 07:10
I am running LineageOS...that's about as special as the phone gets. I have removed 0.13.5 and went back to 0.13.4 and the issue does not exist. Basically with 0.13.4 it keeps whatever brightness my phone is set to via android brightness settings whereas on 0.13.5 it overrides to complete brightness. Not sure how else to help out.

**Comment by acrosca** [comment] 2018-06-08 12:43
For sanity sake, before I install LineageOS just to check, please repeat this test:

NewPipe 0.13.4
NewPipe 0.13.5
Youtube 

In a dark room, play
https://www.youtube.com/watch?v=zj9LmS-99mY

There was no difference in the video on my device.
I did noticed a difference in the black UI (when using black theme of  NewPipe) and the black of the video. Somehow, on all apps, black video was brighter vs black UI

**Comment by ultimatevert** [comment] 2018-06-09 22:55
Good thing you did not waste your time. I played the video you linked on 0.13.4 and did not notice anything different, brightness settings were as they should as I set in Android. Uninstalled and tried 0.13.5 and played the video, no problems either. Loaded some other videos and NewPipe did not apply full brightness at all at one point.

So maybe it was a LineageOS bug or android bug that was causing full brightness on when the video loaded? Sorry to have wasted your time, next time I will remember to reboot before posting.

**Comment by theScrabi** [comment] 2018-06-14 19:48
> https://www.youtube.com/watch?v=zj9LmS-99mY

Somehow of scope but I would really love to have a ten hour version of this :+1:

**Comment by Xilis** [comment] 2018-07-18 18:32
I'm experiencing a brightness issue that is somewhat related.

Essentially, the brightness is stuck at whatever you set it using gesture controls, after disabling the gestures.
So the gesture brightness setting is getting loaded regardless of gestures being enabled or not.

Reproduction steps:
Gestures enabled, open a vid, turn brightness all the way up (or down). Disable gestures, open a vid, brightness is stuck to whatever you've set it with gestures. Changing device-wide brightness does nothing. So essentially, with gestures disabled, the brightness during playback is stuck to whatever it was set at using gestures.

Solution for stuck brightness:
Use gestures,
reinstall the app disabling gestures before setting brightness using them.

NewPipe 0.13.5
OnePlus 5T - Android 8.1.0 (OxygenOS 5.1.3)

**Comment by Xilis** [comment] 2018-07-18 18:48
(I am not 100% about this)

Looking at #1442, saw the session defined as 4 hours. I've tried setting the phone date one day forward, and the brightness was correctly defaulted back to system default brightness.

So my expectation was that the brightness would just always be whatever the current system brightness is at, but the gesture setting is instead remembered for 4 hours.

Just quickly went over the PR and tried it out so someone else should give it a go too.

**Comment by acrosca** [comment] 2018-07-20 12:53
I will add the check
if ( gestures off OR > 4 h)

**Comment by rmchd** [comment] 2020-03-23 07:02
What's the status on this issue? I'm experiencing it in the latest version (0.18.7) exactly as Xilis described it.

**Comment by Stypox** [comment] 2020-09-02 13:12
@ryanm0 @ultimatevert @Xillis
Could you check if this is fixed by # 2907? You can grab the latest apk here: https://github.com/TeamNewPipe/NewPipe/projects/17#card-42918515

**Comment by opusforlife2** [comment] 2020-10-10 15:38
Please comment if this is still not resolved by 0.20.0.

**Closed by opusforlife2** 2020-10-10 15:38 UTC
Labels: GUI, bug

**Comment by Xilis** [comment] 2020-10-10 21:01
Hm I think the issue is a bit different now, but still persists.

Scenario:
- System settings brightness is at lowest setting
- Enable gestures for brightness
- Open a video, fullscreen, set brightness to max using gestures
- Disable gestures for brightness
- Open a video, fullscreen, cannot set brightness using gestures (expected), cannot set brightness using system settings (possibly unexpected?) - "settings controller by an application" equivalent message.

Brightness is still stuck at max (as it was set using gestures) when viewing a video fullscreen, does not reflect system settings.

**Comment by opusforlife2** [comment] 2020-10-10 21:06
@Xilis That is a different issue from the OP. Could you open a new bug report? Enabling gestures, using them, then disabling them isn't something a normal user would do, but the bug should still be handled by the app gracefully.

**Comment by Xilis** [comment] 2020-10-10 21:08
@opusforlife2 yeah just went over the full thread, definitelly not the same issue as OP.

I will create a new ticket (copying the above comment).
