### ISSUE TITLE
Doesn'tload all videos from a given playlist.

### ISSUE THREAD

**Issue by mnd7171** [TeamNewPipe/NewPipe#4857] opened 2020-11-11 11:18 UTC
### Checklist

- [x] I am using the latest version - 0.20.2 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

No matter how i scroll in the app, restart it, clear its cache it refuses to load more than 99 of the videos in a give n playlist.

### Expected behavior

I expect it to load all the videos in the playlist.

### Device info

 - Android version/Custom ROM version: Android 8.0.0 Samsung experience 9.0
 - Device model: SM-A520F

**Comment by c-shubh** [comment] 2020-11-11 12:49
duplicate of #4819

**Comment by opusforlife2** [comment] 2020-11-11 13:14
>  I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

This isn't optional, @mnd7171.

**Closed** 2020-11-11 13:13 UTC
Labels: bug
