### ISSUE TITLE
Minor interface bug

### ISSUE THREAD

**Issue by tyler-reclen** [TeamNewPipe/NewPipe#3060] opened 2020-02-05 03:57 UTC
when switching between players with a paused video newpipe "forgets" that the video was paused

Eg if you pause a video then close the app then the video will resume as a pop-up on in the background.(assuming you have "minimise on app switch enabled")

**Comment by Stypox** [comment] 2020-02-05 07:10
Duplicate of #2239 and #2391

**Closed by Stypox** 2020-02-05 07:10 UTC
