### ISSUE TITLE
Queue tab 

### ISSUE THREAD

**Issue by Juppy6** [TeamNewPipe/NewPipe#7327] opened 2021-10-29 16:06 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

In settings under 'content of main page', an option to add a Queue tab

#### Why do you want this feature?

Firstly, thank you! only been using for a few days, already got rid of YouTube and Spotify apps thanks to this great app.

The only thing I have trouble with is some queue confusion. I've seen other posts since v0.20 regarding the separate pop-up/background/main queues switching to combined and others wondering how you access the queue entirely. 

I'd like to suggest having the queue being in a tab that does not clear unless manually cleared which would eliminate the finding the queue questions/confusion and stop people accidently clearing their queue, and adding an add to queue button to the right of any play button.

So if you have a queue open and playing and someone sends you a video you can choose whether to add the video to the end of the queue or press play and have the video interrupt the queue but keep the queue stored in the tab ready to resume once you've finished with the 'interrupter'.

**Comment by SameenAhnaf** [comment] 2021-10-29 21:58
Duplicate of #5235.

**Comment by mhmdanas** [comment] 2021-10-30 13:26
@SameenAhnaf that issue asks for a swipe-up queue; this one asks for a queue tab. Anyway, this is a duplicate of #2477.

**Closed by mhmdanas** 2021-10-30 13:26 UTC
Labels: enhancement
