### ISSUE TITLE
Extra Services: Bilibili & Niconico

### ISSUE THREAD

**Issue by AngelofMe** [TeamNewPipe/NewPipe#8558] opened 2022-06-28 06:00 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

May 11, 2022 I noticed this GitHub repository appeared
sorry, my English not good
I and lots of korean, japanese, chinese often watch these asian danmaku video website
chinese especially, because their network got government block, over 50% chinese can't access youtube/niconico and good websites successfully
https://github.com/InfinityLoop1309/NewPipeEnhanced

### Why do you want this feature?

they're video sharing websites

**Comment by SameenAhnaf** [comment] 2022-06-28 06:10
See https://github.com/TeamNewPipe/NewPipeExtractor/issues/674#issuecomment-1166570297 to know why Bilibili got rejected by TeamNewPipe.

Duplicate of https://github.com/TeamNewPipe/NewPipeExtractor/issues/771. Also, open service requests on [Newpipe Extractor](https://github.com/TeamNewPipe/NewPipeExtractor/), not here.

**Closed** 2022-06-28 10:22 UTC
Labels: enhancement

**Comment by opusforlife2** [comment] 2022-07-01 19:18
https://github.com/TeamNewPipe/NewPipeExtractor/pull/770#issuecomment-1021490876 would be more appropriate to point to for Niconico.
