### ISSUE TITLE
v0.21.2 video playback performance regression

### ISSUE THREAD

**Issue by FrostKiwi** [TeamNewPipe/NewPipe#6207] opened 2021-04-30 11:05 UTC
With the update to v0.21.2 my OnePlus One is unable to playback 1080p60 videos smoothly any more. Instead it drops it's framerate to below 10fps and becomes a slide show. Going down to 720p60 solves the issue.
This was not the case before v0.21.2.
Anyone else having this experience or is it just my device?
### Checklist

- [x] I am using the latest version - v0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version: Android 10, LineageOS 17.1
 - Device model:  OnePlus One (A0001)

**Comment by TiA4f8R** [comment] 2021-04-30 16:19
Maybe this was caused with the last ExoPlayer update (#5856)? @Redirion What do you think?
Also @FrostKiwi what format are you using to stream videos? MP4 or WEBM?

From a personnal note, on my device, an Honor 9X running EMUI 10, I can't play smoothly videos in 1080p60 with WEBM but I can with MP4. This happens before this release and is related to my device and its performances.

**Comment by FrostKiwi** [comment] 2021-04-30 20:11
> Maybe this was caused with the last ExoPlayer update (#5856)? @Redirion What do you think?
I'll go ahead and mess with downgrades then, thx for the reference

> I can't play smoothly videos in 1080p60 with WEBM but I can with MP4.

Unfortunately, it concerns MPEG-4 as well :S

**Comment by FrostKiwi** [comment] 2021-05-01 19:27
@TiA4f8R 
Arright, here are the downgrading results:
Downgraded to v0.21.0 - MPEG-4 1080p60 videoplayback is smooth
Upraded to v0.21.1 - MPEG-4 1080p60 videoplayback is smooth
Upraded to v0.21.2 - MPEG-4 1080p60 videoplayback is a 10fps slideshow mess. Besides that, turning the phone from vertical to horizontal with this version takes forever, like up to 3 seconds.
The one major feature introduced with 0.21.2 was the playback control while buffering...

**Comment by TiA4f8R** [comment] 2021-05-01 21:25
I always think it's a problem with ExoPlayer.

**Comment by FrostKiwi** [comment] 2021-05-02 13:03
@TiA4f8R 
Here is the ADB logcat output, from the moment I started that NewPipe Debug apk.

Actions performed in log in chronological order: I opened NewPipe Debug, opened a video, changed to 1080p60, NewPipe Debug crashed, opened for a splitsecond the releasebuild of Newpipe, opened NewPipe Debug again, started the video again, changed to 1080p60, watched the video in the 10fps slideshow lag awfulness and finally closed the app.
[catlog.txt](https://github.com/TeamNewPipe/NewPipe/files/6411391/catlog.txt)

If by "capture logs from a debug APK with ADB" you were not referring to logcat, pls elaborate.

**Comment by TiA4f8R** [comment] 2021-05-02 14:30
I was indeed refering to Android's logcat, thank you! Now you will need to a wait that a developer checks what's wrong (I am not one). This can take some time.

**Comment by TobiGr** [comment] 2021-05-02 16:33
I can onyl make guesses, but that's what I've found:
## Framedrops
We are getting a bunch of lines which are similar to this one:
```
05-02 14:54:01.494 22575 22575 I Choreographer: Skipped 52 frames!  The application may be doing too much work on its main thread.
```
These are always preceeded by some kind of `animate()` method being called. Looks like some animations require too much CPU time. I cannot think of any changes in animation handling from 0.21.1 to 0.21.2. That's why I guess the unterlying issue might be something else which triggers the animation.

<details><summary>Log 1</summary>

```
05-02 14:54:01.350 22575 22575 D VideoDetailFragment@e21e61e: handleResult() called with: result = [StreamInfo[url="https://www.youtube.com/watch?v=3Nj96AS_QJ8", name="Valve needs to be communicating right."]]
05-02 14:54:01.350 22575 22575 D ViewUtils: animate():    false ΓåÆ  [ProgressBar:loading_progress_bar] [ALPHA 0:0] execOnEnd=null
05-02 14:54:01.351 22575 22575 D ViewUtils: animate():    false ΓåÆ  [LinearLayout:error_panel] [ALPHA 150:0] execOnEnd=null
05-02 14:54:01.351 22575 22575 D ViewUtils: animate(): view was already gone > view = [android.widget.LinearLayout{2b8a38c G.E...... ......I. 0,0-0,0 #7f0a011c app:id/error_panel}]
05-02 14:54:01.363 22575 22575 D LeakCanary: Watching instance of android.widget.RelativeLayout (org.schabi.newpipe.fragments.list.comments.CommentsFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key b610cb7f-2897-4d36-80e3-401d3e43f40f
05-02 14:54:01.364 22575 22575 D LeakCanary: Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key 0ec5eb39-c1f8-46af-a101-95f154d94a88
05-02 14:54:01.364 22575 22575 D LeakCanary: Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key 354faa72-cb95-4d1b-816e-84bf1f26e100
05-02 14:54:01.365 22575 22575 D LeakCanary: Watching instance of org.schabi.newpipe.fragments.list.comments.CommentsFragment with key 9b2ad367-0f97-4061-bd12-604eff849407
05-02 14:54:01.365 22575 22575 D StateSaver: onDestroy() called with: savedState = [131946954587161 > ]
05-02 14:54:01.365 22575 22575 D LeakCanary: Watching instance of org.schabi.newpipe.fragments.list.comments.CommentsFragment (org.schabi.newpipe.fragments.list.comments.CommentsFragment received Fragment#onDestroy() callback) with key e08a8cdd-17ff-411b-a2e9-05c8a5024fed
05-02 14:54:01.369 22575 22575 D LeakCanary: Watching instance of android.widget.RelativeLayout (org.schabi.newpipe.fragments.list.videos.RelatedItemsFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 0e4819ef-c4b3-4547-9dc6-912554a70c29
05-02 14:54:01.370 22575 22575 D LeakCanary: Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key 456a5c3c-50c5-4382-99b2-832432f80e5c
05-02 14:54:01.370 22575 22575 D LeakCanary: Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key db21eeef-c02b-469e-a52a-a8f52f2fff45
05-02 14:54:01.371 22575 22575 D LeakCanary: Watching instance of org.schabi.newpipe.fragments.list.videos.RelatedItemsFragment with key e801cc4f-0075-432e-9781-b36394f53f9d
05-02 14:54:01.371 22575 22575 D StateSaver: onDestroy() called with: savedState = [131946862158186 > ]
05-02 14:54:01.371 22575 22575 D LeakCanary: Watching instance of org.schabi.newpipe.fragments.list.videos.RelatedItemsFragment (org.schabi.newpipe.fragments.list.videos.RelatedItemsFragment received Fragment#onDestroy() callback) with key 4e449ea5-d63c-485c-a722-01b1dd6e3d99
05-02 14:54:01.373 22575 22575 D CommentsFragment@f082f8d: onCreate() called with: savedInstanceState = [null]
05-02 14:54:01.375 22575 22575 D RelatedItemsFragment@43f4ec1: onCreate() called with: savedInstanceState = [null]
05-02 14:54:01.395 22575 22575 D CommentsFragment@f082f8d: onViewCreated() called with: rootView = [android.widget.RelativeLayout{2c55138 V.E...... ......I. 0,0-0,0}], savedInstanceState = [null]
05-02 14:54:01.399 22575 22575 D CommentsFragment@f082f8d: doInitialLoadLogic() called
05-02 14:54:01.399 22575 22575 D CommentsFragment@f082f8d: startLoading() called with: forceLoad = [false]
05-02 14:54:01.400 22575 22575 D ViewUtils: animate():    false ΓåÆ  [LinearLayout:empty_state_view] [ALPHA 150:0] execOnEnd=null
05-02 14:54:01.400 22575 22575 D ViewUtils: animate(): view was already gone > view = [android.widget.LinearLayout{f161676 G.E...... ......I. 0,0-0,0 #7f0a0104 app:id/empty_state_view}]
05-02 14:54:01.400 22575 22575 D ViewUtils: animate():     true ΓåÆ  [ProgressBar:loading_progress_bar] [ALPHA 400:0] execOnEnd=null
05-02 14:54:01.401 22575 22575 D ViewUtils: animate():    false ΓåÆ  [LinearLayout:error_panel] [ALPHA 150:0] execOnEnd=null
05-02 14:54:01.401 22575 22575 D ViewUtils: animate(): view was already gone > view = [android.widget.LinearLayout{1a48e4 G.E...... ......I. 0,0-0,0 #7f0a011c app:id/error_panel}]
05-02 14:54:01.403 22575 27082 D InfoCache: getFromKey() called with: serviceId = [0], url = [https://www.youtube.com/watch?v=3Nj96AS_QJ8]
05-02 14:54:01.403 22575 27082 D ExtractorHelper: loadFromCache() called, info > CommentsInfo[url="https://m.youtube.com/watch?v=3Nj96AS_QJ8" (originalUrl="https://www.youtube.com/watch?v=3Nj96AS_QJ8"), name="Comments"]
05-02 14:54:01.422 22575 22575 D RelatedItemsFragment@43f4ec1: onViewCreated() called with: rootView = [android.widget.RelativeLayout{d60f175 V.E...... ......I. 0,0-0,0}], savedInstanceState = [null]
05-02 14:54:01.431 22575 22575 D RelatedItemsFragment@43f4ec1: doInitialLoadLogic() called
05-02 14:54:01.431 22575 22575 D RelatedItemsFragment@43f4ec1: startLoading() called with: forceLoad = [false]
05-02 14:54:01.431 22575 22575 D ViewUtils: animate():    false ΓåÆ  [LinearLayout:empty_state_view] [ALPHA 150:0] execOnEnd=null
05-02 14:54:01.431 22575 22575 D ViewUtils: animate(): view was already gone > view = [android.widget.LinearLayout{7e9817b G.E...... ......I. 0,0-0,0 #7f0a0104 app:id/empty_state_view}]
05-02 14:54:01.432 22575 22575 D ViewUtils: animate():     true ΓåÆ  [ProgressBar:loading_progress_bar] [ALPHA 400:0] execOnEnd=null
05-02 14:54:01.432 22575 22575 D ViewUtils: animate():    false ΓåÆ  [LinearLayout:error_panel] [ALPHA 150:0] execOnEnd=null
05-02 14:54:01.432 22575 22575 D ViewUtils: animate(): view was already gone > view = [android.widget.LinearLayout{5c2ff1 G.E...... ......I. 0,0-0,0 #7f0a011c app:id/error_panel}]
05-02 14:54:01.448 22575 22575 D ViewUtils: animate():     true ΓåÆ  [AppCompatImageView:detail_thumbnail_play_button] [ALPHA 200:0] execOnEnd=null
05-02 14:54:01.463 22575 22575 D ViewUtils: animate():     true ΓåÆ  [AppCompatTextView:detail_duration_view] [ALPHA 100:0] execOnEnd=null
05-02 14:54:01.493 22575 22575 D Player  : onBroadcastReceived() called with: intent = [Intent { act=org.schabi.newpipe.debug.VideoDetailFragment.ACTION_VIDEO_FRAGMENT_RESUMED flg=0x10 }]
05-02 14:54:01.494 22575 22575 I Choreographer: Skipped 52 frames!  The application may be doing too much work on its main thread.
```
</details>
<details><summary>Log 2</summary>

```
05-02 14:54:52.002 27693 27693 D RelatedItemsFragment@4896a3f: doInitialLoadLogic() called
05-02 14:54:52.002 27693 27693 D RelatedItemsFragment@4896a3f: handleResult() called with: result = [RelatedItemInfo[url="https://www.youtube.com/watch?v=3Nj96AS_QJ8", name="Valve needs to be communicating right."]]
05-02 14:54:52.002 27693 27693 D ViewUtils: animate():    false ΓåÆ  [LinearLayout:empty_state_view] [ALPHA 150:0] execOnEnd=null
05-02 14:54:52.002 27693 27693 D ViewUtils: animate(): view was already gone > view = [android.widget.LinearLayout{74893da G.E...... ......I. 0,0-0,0 #7f0a0104 app:id/empty_state_view}]
05-02 14:54:52.003 27693 27693 D ViewUtils: animate():    false ΓåÆ  [ProgressBar:loading_progress_bar] [ALPHA 0:0] execOnEnd=null
05-02 14:54:52.003 27693 27693 D ViewUtils: animate(): view was already gone > view = [android.widget.ProgressBar{b8f900b G.ED..... ......I. 0,0-0,0 #7f0a01f3 app:id/loading_progress_bar}]
05-02 14:54:52.003 27693 27693 D ViewUtils: animate():    false ΓåÆ  [LinearLayout:error_panel] [ALPHA 150:0] execOnEnd=null
05-02 14:54:52.003 27693 27693 D ViewUtils: animate(): view was already gone > view = [android.widget.LinearLayout{d85dee8 G.E...... ......I. 0,0-0,0 #7f0a011c app:id/error_panel}]
05-02 14:54:52.003 27693 27693 D ViewUtils: animate():     true ΓåÆ  [RecyclerView:items_list] [ALPHA 300:0] execOnEnd=null
05-02 14:54:52.004 27693 27693 D ViewUtils: animate(): view was already visible > view = [androidx.recyclerview.widget.RecyclerView{b5ac901 VFED.V... ......I. 0,0-0,0 #7f0a01b7 app:id/items_list}]
05-02 14:54:52.064 27693 27693 D SearchFragment@a615680: onResume() called
05-02 14:54:52.065 27693 27693 D SearchFragment@a615680: hideKeyboardSearch() called
05-02 14:54:52.065 27693 27693 D SearchFragment@a615680: hideSuggestionsPanel() called
05-02 14:54:52.066 27693 27693 D ViewUtils: animate():    false ΓåÆ  [LinearLayout:suggestions_panel] [LIGHT_SLIDE_AND_ALPHA 200:0] execOnEnd=null
05-02 14:54:52.066 27693 27693 D ViewUtils: animate(): view was already gone > view = [android.widget.LinearLayout{24fef2c GFE...... ......ID 0,0-0,0 #7f0a0333 app:id/suggestions_panel}]
05-02 14:54:52.086 27693 27693 D Player  : onBroadcastReceived() called with: intent = [Intent { act=android.intent.action.CONFIGURATION_CHANGED flg=0x70200010 }]
05-02 14:54:52.089 27693 27693 D Player  : onConfigurationChanged() called
05-02 14:54:52.094 27693 27693 D Player  : updateScreenSize() called: screenWidth = [1920.0], screenHeight = [1080.0]
05-02 14:54:52.097 27693 27693 D Player  : Thumbnail - updateEndScreenThumbnail() called with: currentThumbnail = [android.graphics.Bitmap@ab381c2], 600x337, scaled end screen height = 337.0, scaled end screen width = 600
05-02 14:54:52.098 27693 27693 I Choreographer: Skipped 67 frames!  The application may be doing too much work on its main thread.
```
</details>

## Buffering
I did not yet compare the log with a "normal" log, but your log contains the word "buffer" _very_ often: In the ~7000 lines, we got ~1800 lines with info about buffer stuff.
```
05-02 14:53:48.982   236  1629 W         : buffer descriptor with invalid usage bits 0x2002000
```
```
05-02 14:54:22.504  9831 21063 D CCodecBuffers: [c2.android.aac.decoder#182:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 4
```
```
05-02 14:54:52.517 27693 27818 E BufferQueueProducer: [SurfaceTexture-1-27693-0] detachBuffer: slot 2 is not owned by the producer (state = FREE)
```
```
05-02 14:54:56.130 27693 27818 I CCodecConfig: query failed after returning 12 values (BAD_INDEX)
```
```
05-02 14:55:01.366 27693 27789 D PipelineWatcher: onInputBufferReleased: frameIndex not found (729); ignored
```
----
I do not have time to look into this, but my next steps would be:
1. Get a 0.21.1 debug version
    1.  and  check how often the animations are performed
    1. check if we have that many debug info related to buffering
2. Try the exoplayer update #5457
3. Try to understand what these lines say:
```
05-02 14:54:45.318   299 13446 E qcreverb: 	[vendor/qcom/proprietary/mm-audio-noship/audio-effects/safx/android-adapter/qcreverb/qcreverb.c:531] Assertion fail: pConfig->inputCfg.format == AUDIO_FORMAT_PCM_16_BIT
05-02 14:54:48.820   299   379 E qcbassboost: 	[vendor/qcom/proprietary/mm-audio-noship/audio-effects/safx/android-adapter/qcbassboost/qcbassboost.c:395] Assertion fail: pConfig->inputCfg.format == AUDIO_FORMAT_PCM_16_BIT
05-02 14:54:48.831   299  5350 E qcvirt  : 	[vendor/qcom/proprietary/mm-audio-noship/audio-effects/safx/android-adapter/qcvirt/qcvirt.c:568] Assertion fail: pConfig->inputCfg.format == AUDIO_FORMAT_PCM_16_BIT
05-02 14:54:48.844   299   384 E qcreverb: 	[vendor/qcom/proprietary/mm-audio-noship/audio-effects/safx/android-adapter/qcreverb/qcreverb.c:531] Assertion fail: pConfig->inputCfg.format == AUDIO_FORMAT_PCM_16_BIT
```
4. Ask @Redirion for help

**Comment by Redirion** [comment] 2021-05-02 16:58
it looks like the development of your Lineageos version for your device has advanced to a new version. 18.1.
Are you using the latest nightly of 17.1? If not you could try to upgrade to that. And if you already do, you could try 18.1
https://download.lineageos.org/bacon

But yes please also try the updated ExoPlayer to see if that makes a difference

**Comment by Redirion** [comment] 2021-05-03 11:14
ah @TobiGr you have linked the wrong update.
The correct PR is https://github.com/TeamNewPipe/NewPipe/pull/6206

@FrostKiwi please try that ExoPlayer version and please comment on my Lineageos question

**Comment by FrostKiwi** [comment] 2021-05-03 16:28
> 
> 
> ah @TobiGr you have linked the wrong update.
> The correct PR is #6206
> 
> @FrostKiwi please try that ExoPlayer version and please comment on my Lineageos question

Tried the debug build provided by PR https://github.com/TeamNewPipe/NewPipe/pull/6206
Same deal. 10fps during 1080p60 playback. The Animations of the NewPipe app btw still play at full framerate and are smooth. (The slide animations, rotate animations... it's just the video that's choppy)

I am on the 11th April build of LineageOS 17.1 as provided by [this ROM](https://forum.xda-developers.com/t/rom-q-r-unofficial-optimized-lineageos-18-1-april-29th-lineageos-17-1-april-11th.3693223/)
Although LineageOS 18.1 has been out for a year for my device, it was still young and stability was wonky, so I stuck around with 17.1 till now. If it helps tracking down the issue, I can wipe and cleanflash my device to 18.1.

**Comment by Redirion** [comment] 2021-05-04 07:51
MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64002A, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [bacon, A0001, OnePlus, 29]

VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
VideoCapabilities: Unrecognized profile 2130706433 for video/avc



Can you please try if it works better with webm?

**Comment by Redirion** [comment] 2021-05-04 07:57
this is curious:
CacheDataSink: fragmentSize is below the minimum recommended value of 2097152. This may cause poor cache performance.

**Comment by TobiGr** [comment] 2021-05-04 09:57
@Redirion Good catch!
@FrostKiwi Can you please test the APK from #6238. It is a debug APK, so its is genereally slower than the normal release build. However, if @Redirion tackeled the casue for your frame drops, you should notice that.

**Comment by FrostKiwi** [comment] 2021-05-04 15:19
I have tested the APK as [provided in the PR](https://github.com/TeamNewPipe/NewPipe/suites/2645965328/artifacts/58122062).
Unfortunately there were absolutely no performance changes between v0.21.2 and v0.21.2 "fixfragmentsize". Launching into MPEG-4 1080p60 results in a laggy single digit fps mess. @Redirion Though I'm glad to have indirectly contributed to an improvement already :D
> Can you please try if it works better with webm?

On all version, v0.21.1, v0.21.2 and v0.21.2 "fixfragmentsize" the playback of WebM 720p60 and WebM 1080p60 is equally a single-digit fps slideshow. This kinda leads me to believe that my Device has stopped providing Hardware decoding for MPEG-4 with v0.21.2 maybe? Is there a way to check that?

For reference, here is a video showing off all symptoms in all versions, captured externally, as not to fudge the results: 

https://user-images.githubusercontent.com/60887273/117027202-c4e4d800-acfc-11eb-91a5-8ea545320920.mp4

In chronological order:

- Starting v0.21.1 and confirming the version, showing smooth playback of MPEG-4 1080p60
- Switching to v0.21.2 "fixfragmentsize" and confirming the version, showing Choppy playback of MPEG-4 1080p60 and Smooth playback MPEG-4 720p60  and lastly, showing horizontal orientation 1080p60 still being choppy.
- Switching to v0.21.1 and confirming the version, showing switching playback default to WebM and showing Choppy playback of both WebM 1080p60 and 720p60

**Comment by Redirion** [comment] 2021-05-05 04:00
Thank you for the video!
I tried to dig through your logs again but there is so much going on. Is it possible to disable the audio_effects module / bass boost stuff? Maybe you have some sort of Equalizer app that can be disabled.
Video playback requires uninterrupted audio stream for syncing timestamps.
Later I will make another "media tunneling disabled" test APK based on current dev and one with downgraded ExoPlayer version. It might be an issue with offloading syncing timestamps to the device. But in any case I would like to find the root cause.

**Comment by FrostKiwi** [comment] 2021-05-11 08:28
I wanted to clean flash my Phone before posting again, but since we are here:

> I tried to dig through your logs again but there is so much going on. Is it possible to disable the audio_effects module / bass boost stuff? Maybe you have some sort of Equalizer app that can be disabled.

As @matterharz reported, I disabled that audio effects and there was no change either.
The audio effects came in my case from the preinstalled "AudioFX" solution. Though I also used Viper4Android in the past. Never an issue and Audio never lags. With all of that disabled, no changes.
All the "qcXXXX: [vendor/qcom/proprietary" stuff refers to the in-built hardware audio proccessing by QualComm, is commanded by the kernel and always running, as far as I'm aware. It can be used by to tune the spaekers, redirect audio to different speakers for Stereo and so on. It is only accessible to the OEM or if you have root.

**Comment by Ammako** [comment] 2021-05-14 02:15
I switched to webm to avoid unrecoverable player errors when rotating phone and entering split screen mode, it works but after some time (30m-1h+) videos start to stutter more and more. If I close the app and reopen the same video to continue it, the stuttering is gone and it plays back relatively well.

Video resolution at 720p (30fps), I never had stuttering with mp4 but mp4 causes player errors all the time when I enter split screen so that's not an option. Not sure about 0.21.1 or earlier, as I wasn't using webm until now. Maybe at some point I could try downgrading, just to see if this is related.

**Comment by TobiGr** [comment] 2021-05-14 08:02
I found thesesn lines in @FrostKiwi's and @Mr-Mime's log:
```
05-02 14:54:45.557 27693 27783 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64002A, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [bacon, A0001, OnePlus, 29]
05-02 14:54:45.558 27693 27783 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64002A, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [bacon, A0001, OnePlus, 29]

05-02 14:54:42.637 27693 27783 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
05-02 14:54:42.642 27693 27783 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
```

```
2021-05-10 19:12:15.490 31583-31666/org.schabi.newpipe W/VideoCapabilities: Unrecognized profile 4 for video/hevc
2021-05-10 19:12:15.492 31583-31666/org.schabi.newpipe W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2021-05-10 19:12:15.495 31583-31666/org.schabi.newpipe W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
2021-05-10 19:12:15.511 31583-31666/org.schabi.newpipe W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2021-05-10 19:12:15.526 31583-31666/org.schabi.newpipe I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
```

@Mr-Mime I think you did not use a debug version to create the crash log, did you? Can you please create a more detailed log with the [latest dev version](https://github.com/TeamNewPipe/NewPipe/suites/2740615444/artifacts/60551238)?

**Comment by Mr-Mime** [comment] 2021-05-14 09:12
@TobiGr, this time I used the lastest dev version you linked. I also set the logcat output level to "Debug", last time it was set to "Info".

[Here](https://github.com/TeamNewPipe/NewPipe/files/6477684/newPipe_debug.log) are the new logs.
I opened he app and started a Video in 720p, worked fine.
Then switched to 1080p60 and it started stuttering.
I added 3 lines to separate the 720p part from the 1080p part in the logs.

I also see these lines, which were also in @FrostKiwi's log...
```
2021-05-14 10:48:22.492 12090-12354/org.schabi.newpipe.debug D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64002A, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [OnePlus2, ONE A2003, OnePlus, 28]
2021-05-14 10:48:22.494 12090-12354/org.schabi.newpipe.debug D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64002A, video/avc] [OMX.qcom.video.decoder.avc, video/avc] [OnePlus2, ONE A2003, OnePlus, 28]
```

BTW my lineage is degoogled, not that I think it is related to this issue, but who knows :)

**Comment by Redirion** [comment] 2021-05-14 10:11
Please check with the apk from this PR #6288 if it works for you. It could be that there is an issue with media tunneling where syncing audio and video timestamps is being offloaded to the device if the device claims support for that. In the event that media tunneling is broken on the device sync timestamps might be missing / incorrect and could lead to stutter or low fps.

**Comment by Mr-Mime** [comment] 2021-05-14 11:37
@Redirion the apk from the PR did nothing for me. Turned tunneling off and still had stuttering video. (MP4 and WEBM)

However I can say that 4a9d210 introduced the stuttering on my device.

I built the app locally.   
First at ad8f3aa, and the video playback @1080p60 was smooth.
Then I switched to 4a9d210, built the apk and the stuttering occurred.

**Comment by TobiGr** [comment] 2021-05-14 12:30
@Mr-Mime That looks like a wrong conclusion. The history is not linear. https://github.com/TeamNewPipe/NewPipe/commit/ad8f3aa6c9f0cbaf4fea499779fcbde326c979f5 is directly based on the 0.21.0 release (464d0e50b01317ffe41f8455e40efa770f067087). So when you do not experience the problem with ad8f3aa6c9f0cbaf4fea499779fcbde326c979f5, that only tells us, that the problem did not exist in the 0.21.0 release. However, https://github.com/TeamNewPipe/NewPipe/commit/4a9d21062a1f9097de788fb82a14dcca3184ce42 has a bunch more commits which made changes to the player. I really do not believe that the performance regression was introduced by preventing a single device from using media tunneling. Can you test 5739caaa5a4039a602b74b6771524097d2053d5b?

**Comment by Redirion** [comment] 2021-05-14 12:44
the first commit was based on an outdated dev branch at that time it appears.
For example it was still at ExoPlayer 2.12, while the other commit was on recent dev branch at that time with ExoPlayer 2.13

**Comment by Mr-Mime** [comment] 2021-05-14 12:45
Yes, sorry I completely overlooked that.

@TobiGr with 5739caa I experience the stuttering.

**Comment by Redirion** [comment] 2021-05-14 13:38
please try ExoPlayer 2.12 from PR #6294 
and ExoPlayer 2.14 from PR #6295 
both were created on current dev branch

**Comment by Mr-Mime** [comment] 2021-05-14 15:51
For me with the downgrade the stuttering is gone.
But the version with ExoPlayer 2.14 also has the stuttering.

**Comment by FrostKiwi** [comment] 2021-05-14 16:08
Damn you guys are fast 0.0
> please try ExoPlayer 2.12 from PR #6294
> and ExoPlayer 2.14 from PR #6295
> both were created on current dev branch

Can confirm aswell with my OnePlus One. #6294 runs smoothly, #6295 is a slideshow.
I think I now hold the world record for most NewPipe Apps installed at the same time.

**Comment by opusforlife2** [comment] 2021-05-14 16:11
Huhuhu. One of our devs had something like 30+ Newpipes installed at one point. But keep trying. ;P

**Comment by tegutistgut** [comment] 2021-05-14 17:07
I kinda have the same problem(?)
For me it is like this: when a video is playing, the playback stutters randomly in the video, as if my internet was bad. But with the yt app oder via firefox mobile i dont have this problem.

**Comment by Redirion** [comment] 2021-05-14 19:45
my guess is that it all boils down to this issue and its fix in ExoPlayer that is present since 2.13:
https://github.com/equeim/ExoPlayer/commit/78a975c268809b847ddd0aa938ddcf19e4c6837b

ExoPlayer checks decoder capabilities and dismisses probable decoders as they do not correctly announce profileLevel support for what is needed for Youtube 1080p60
MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64002A

so the normally well performing decoder gets dismissed and another, inferior, software renderer like Googles own gets used instead resulting in sluggish performance.

In my opinion this should be an issue of LineageOS and can be fixed by correctly reporting supported h265 codec profile levels.

**Comment by Mr-Mime** [comment] 2021-05-14 23:16
Just as a note:

I updated my OnePlus One to the latest LineageOs 18.1 build.
Unfortunately the stuttering is still there.

Thus I think the issue described by @Redirion should be reported to LineageOs.

**Comment by Redirion** [comment] 2021-05-14 23:24
We will downgrade ExoPlayer for the next version

**Comment by Mr-Mime** [comment] 2021-05-15 00:25
FYI: Created a issue at LineageOs's issue tracker [here](https://gitlab.com/LineageOS/issues/android/-/issues/3475).   
Feel free to add information there if I forgot something or you have new one.

**Comment by opusforlife2** [comment] 2021-05-15 01:47
@Mr-Mime Might be a good idea to also submit a post to their subreddit. Quite a few devs are active there, so it might increase the chances of someone having a look at this.

**Comment by FrostKiwi** [comment] 2021-05-15 06:16
> We will downgrade ExoPlayer for the next version

This clears the issue for now then.
Thank you for the indepth analysis.

**Comment by opusforlife2** [comment] 2021-05-15 06:52
Let's keep it open to keep track of LineageOS developments.

**Comment by FrostKiwi** [comment] 2021-05-15 11:13
@opusforlife2 @TobiGr 
![tenor_1](https://user-images.githubusercontent.com/60887273/118358487-464f2c80-b57f-11eb-9738-b74d08043edf.gif)

**Comment by opusforlife2** [comment] 2021-05-15 13:03
ᕕ( ᐛ )ᕗ

**Comment by Redirion** [comment] 2021-06-24 21:42
@Mr-Mime any news regarding avc profile level support for your chipset? I don't see any recent patch in https://review.lineageos.org/q/project:LineageOS%252Fandroid_hardware_qcom_media

**Comment by Mr-Mime** [comment] 2022-01-17 08:32
Lost focus on this in summer...
But today the issue was closed for lineage. ([issue in lineage git](https://gitlab.com/LineageOS/issues/android/-/issues/3475#note_811728307))
Actually it was closed in November, but the devs forgot to close the issue.

**Comment by Redirion** [comment] 2022-01-17 14:21
sounds good! Can you confirm that the issue is not present in the current NewPipe release?

**Comment by Mr-Mime** [comment] 2022-01-18 09:20
I am on the latest LineageOS and have NewPipe 21.15 installed. I see no stuttering.
Also this line from the log, seems to indicate, that the media codec is set correctly
```
org.schabi.newpipe I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 4811790
```

**Comment by Redirion** [comment] 2022-01-18 11:13
perfect! I will close this issue then :)

**Closed by Redirion** 2022-01-18 11:13 UTC
Labels: bug, player, device/software specific
