### ISSUE TITLE
Combine Fast Mode and normal mode fetching

### ISSUE THREAD

**Issue by bigfinfrank** [TeamNewPipe/NewPipe#7465] opened 2021-11-29 18:36 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

It would be great to see a middleground option between fast and non-fast mode where both are used. For example an initial fetch could be done with the fast mode technique for speed and afterwards a slow mode fetch is used to fill in missing information.

#### Why do you want this feature?

I watch podcast style live streams after they're live as I prefer starting from the beginning which means fast mode itself isn't really an option for me but I'd still like the speed benefits of it. I thought about the problem and went "why not both?".

**Comment by litetex** [comment] 2021-11-29 20:52
I think that's not possible / useful.
The fast-mode uses different methods/APIs than the "normal" fetching.

It's like you have a truck or a sports car inside your garage: Either use the fast one that can't pull so much or the slow one which can pull more.

> For example an initial fetch could be done with the fast mode technique for speed and afterwards a slow mode fetch is used to fill in missing information.

That would perform the same as the "normal" fetching mode or even slower.

**Comment by SameenAhnaf** [comment] 2021-11-30 16:09
If I'm not wrong, this is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4934

**Comment by litetex** [comment] 2021-11-30 18:18
@SameenAhnaf 
Thx for the hint 😄 

Duplicate of #4934

**Closed by litetex** 2021-11-30 18:18 UTC
Labels: enhancement
