### ISSUE TITLE
one feature request and one error (bir özellik isteği ve bir hata)

### ISSUE THREAD

**Issue by aTetii** [TeamNewPipe/NewPipe#2952] opened 2020-01-12 01:20 UTC
My suggestion is what, might be more useful if when "moving video playback speed control" is added instead of 'moving brightness control' and 'moving volume control'. 

When we click on the video there is comments + video on the first screen. the first screen does not play video and when we click the video again on the new screen plays video. but comments are hidden. Is it possible for this error to be solved, ie (that is) to play video on the first screen? that is, the video should be played on the first screen as soon as you click the video on the homepage or trends. in this way, comments appear.

TeamNewPipe, thank you for everything you do for free-open source 

Loves and Respects from Turkey :-)

**Comment by B0pol** [comment] 2020-01-12 07:04
There is a way to do what you want : popup mode.
If you long press on the popup, it will expand to the maximum size possible.

**Comment by Stypox** [comment] 2020-01-12 10:47
Thanks for the issue :-)
The first part is duplicate of #1823
The second part is duplicate of #1200
Also, next time open two different issues when there are two different things to be discussed ;-)

**Closed by Stypox** 2020-01-12 10:47 UTC
