### ISSUE TITLE
Video,background and pop up player not working on some videos.

### ISSUE THREAD

**Issue by bumbleeb** [TeamNewPipe/NewPipe#2337] opened 2019-05-11 09:07 UTC
For some reason,it won't open some videos,and some of those videos are youtube music "topics" or just audios.
It just keeps loading. I tried to play it on an external audio and video play (for example:Google Music) it says "Couldn't play the track that you requested." 
The app version is 0.16.1

**Comment by CorneliusHuber** [comment] 2019-05-11 18:40
I have that bug as well. When you kill the app and delete the cache it works again for a few videos. Pretty soon after that the problems starts appearing again.

**Comment by Stypox** [comment] 2019-05-12 09:59
I think the problem is strictly connected with cache, since by deleting it after every video I watch the loading works just fine. I'll try to investigate into this.

**Comment by ritiek** [comment] 2019-05-12 10:38
Seems like this is a problem similar to https://github.com/mps-youtube/mps-youtube/issues/977#issuecomment-491578414. I'll copy-paste the relevant part here:

To me, this seems like a bug with the YouTube API itself. Pick up any YouTube video and get its video or audio URL with youtube-dl and like 1/5 times it would result in a forbidden URL. Such as:
```
$ curl --head $(youtube-dl -x https://youtube.com/watch?v=p_vSh1DUsD4 -g)
```
And as with mps-youtube, it seems NewPipe also caches these generated URLs so if the error occurs on a track once, you will always get this same error whenever you try to play that same track through NewPipe (until you clear the cache).

**Comment by ritiek** [comment] 2019-05-12 10:46
(Also looks like this and issue #2336 have the same problem)

**Comment by Stypox** [comment] 2019-05-12 11:54
Youtube urls expire after some time, so I don't think it is a good idea to cache them. But if I remember right the url also contains an argument telling when it is going to expire. So we could check if the url has expired, and if it has, we just ask the extractor to get another one. Abviously the extractor would require some changes in order to be able to provide an expiration date alongside the extracted urls.

But what if the youtube API goes beyond checking the expiration date, and also keeps track of how many times an url has been used? How much time passed between the you first run the command

**Comment by Stypox** [comment] 2019-05-12 12:11
Youtube urls expire after some time, so I don't think it is a good idea to cache them. But if I remember right the url also contains an argument telling when it is going to expire. So we could check if the url has expired, and if it has, we just ask the extractor to get another one. Abviously the extractor would require some changes in order to be able to provide an expiration date alongside the extracted urls.

For example, in the url
```
https://r4---sn-hpa7znsd.googlevideo.com/videoplayback?id=o-AOo7es3DK0F2PYCteQ_SRBTdFQ_IkE1M6XlGF5Dkk9Aq&itag=140&source=youtube&requiressl=yes&pl=24&ei=kgvYXN68E9iL7gOuzrrQBg&mime=audio%2Fmp4&gir=yes&clen=7741&dur=0.441&lmt=1509072763676229&fvip=4&keepalive=yes&beids=9466588&c=WEB&ip=87.4.21.218&ipbits=0&expire=1557684210&sparams=clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,source&signature=64D1EBA9309BAF1038BC0B4D0DBA7ECA4C2C54FA.447772629FAD9FD908C673FB92B12FB2A94F81D7&key=cms1&ratebypass=yes&redirect_counter=1&cm2rm=sn-nx5cvox-hpae77z&fexp=9466588&req_id=289bf7475eeea3ee&cms_redirect=yes&ipbypass=yes&mm=30&mn=sn-hpa7znsd&ms=nxu&mt=1557662080&mv=u
```
that I got from youtube-dl there is the `expire=1557684210` argument, and that epoch time maps to 6 hours after I fetched the url (fetched at roughly 12:03:30, expires at 18:03:30).

But what if the youtube API goes beyond checking the expiration date, and also keeps track of how many times an url has been used? I don't think this matters though, as I ran a script that downloaded the same file 500 times without any problem.

**Comment by ritiek** [comment] 2019-05-12 13:19
@Stypox I'm not very familiar with NewPipe's source, so it might be possible that we're already taking care of expired URLs or something (since I don't remember having any problem related to this in the past).

We could probably leave that alone for now since the problem seems to occur because YouTube generates a random 403 forbidden content URL (https://github.com/TeamNewPipe/NewPipe/issues/2337#issuecomment-491584025). If we could workaround this, we shouldn't need to mess with content URLs getting expired. One way would be to check if the content URL is 403 forbidden, if so we could keep retrying until the fetched URL works properly.

**Comment by Stypox** [comment] 2019-05-13 15:56
After some testing I found this: 
- I opened a video I had NEVER seen before
- it didn't work
- I wiped the cache
- it then worked

If the problem had to do with expired urls, it wouldn't create any problem with never watched videos... I'll try to test the app more (by adding more logs) and see what happens.

**Comment by Stypox** [comment] 2019-05-13 18:39
Ok, after some testing I found out that the extractor provides an invalid link:
```
https://r3---sn-fpoq-ugol.googlevideo.com/videoplayback?expire=1557794230&ei=VrnZXLnRFaXA8gOVqqbICg&ip=151.68.148.156&id=o-AGA_w9hCFILqd_b9ZGJBOFKPbvhY78BYLMrhRTKWgLcM&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-fpoq-ugol%2Csn-hpa7znsd&ms=au%2Crdu&mv=m&pl=17&gcr=it&initcwndbps=362500&mime=video%2Fmp4&gir=yes&clen=4354025&ratebypass=yes&dur=191.378&lmt=1557441496957830&mt=1557772546&fvip=5&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAJYdNfm49eWB_4vtinpii0htA_8NkVZ6jkSou52hOgZpAiEA8Lt-L-EwwgUEN7066GxQPMgw1XPLDmOIBJPS8dBi4-4%3D&signature=ALgxI2wwRQIgFIaTAnA0s1vWKzJDXZu3jaL41PcIrArXcuPa7aP8VqUCIQCTpWHkljM7-B55WMb37e9lZGCXkjvPxqP4w4yeYZJGYQ==
```
Even Firefox on my pc couldn't load it, so I think this is an extractor problem. The strange thing is it only happens sometimes...

**Comment by Stypox** [comment] 2019-05-13 18:41
Ok, after some testing I found out that the extractor provides an invalid link:
```
https://r3---sn-fpoq-ugol.googlevideo.com/videoplayback?expire=1557794230&ei=VrnZXLnRFaXA8gOVqqbICg&ip=XXX.XX.XXX.XXX&id=o-AGA_w9hCFILqd_b9ZGJBOFKPbvhY78BYLMrhRTKWgLcM&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-fpoq-ugol%2Csn-hpa7znsd&ms=au%2Crdu&mv=m&pl=17&gcr=it&initcwndbps=362500&mime=video%2Fmp4&gir=yes&clen=4354025&ratebypass=yes&dur=191.378&lmt=1557441496957830&mt=1557772546&fvip=5&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAJYdNfm49eWB_4vtinpii0htA_8NkVZ6jkSou52hOgZpAiEA8Lt-L-EwwgUEN7066GxQPMgw1XPLDmOIBJPS8dBi4-4%3D&signature=ALgxI2wwRQIgFIaTAnA0s1vWKzJDXZu3jaL41PcIrArXcuPa7aP8VqUCIQCTpWHkljM7-B55WMb37e9lZGCXkjvPxqP4w4yeYZJGYQ==
```
Even Firefox on my pc couldn't load it, so I think this is an extractor problem. The strange thing is it only happens sometimes...

P.S. I replaced the IP in the url with XXX.XX.XXX.XXX for privacy reasons.

**Comment by omarroth** [comment] 2019-05-13 18:45
Replace `&signature=` with `&sig=` to see if it works with the link you provided. Appears to be related to TeamNewPipe/NewPipeExtractor#162.

**Comment by Stypox** [comment] 2019-05-13 18:46
It works :-3

**Comment by Stypox** [comment] 2019-05-13 18:56
Is it ok if I make a pull request to the extractor with the fix about the signature you explained in [TeamNewPipe/NewPipeExtractor#155 (comment)](https://github.com/TeamNewPipe/NewPipeExtractor/issues/155#issuecomment-483033261)?

**Comment by Stypox** [comment] 2019-05-13 18:57
Is it ok if I make a pull request to the extractor with the fix about the signature you explained in [TeamNewPipe/NewPipeExtractor#155 (comment)](https://github.com/TeamNewPipe/NewPipeExtractor/issues/155#issuecomment-483033261)?
@omarroth

**Comment by omarroth** [comment] 2019-05-13 19:04
Absolutely!

**Comment by bumbleeb** [comment] 2019-05-13 19:33
I'm kind of the "not so good with codes and programming" guy,so I have some small questions. Is the problem caused by Youtube? If not,then is NewPipe going to update,or do we just have to change the code in the app like @omarroth said?

**Comment by hurinmon** [comment] 2019-05-14 04:41
https://www.youtube.com/watch?v=xRbPAVnqtcs

this video not played

The app version is 0.16.1

**Comment by Stypox** [comment] 2019-05-14 05:10
@hurinmon I tested that video and it doesn't work with the old app, but it works with the fixed one

**Closed** 2019-05-14 19:29 UTC
