### ISSUE TITLE
Better error handling for terminated or unsupported YouTube channels

### ISSUE THREAD

**Issue by snappyapple632** [TeamNewPipe/NewPipe#5393] opened 2021-01-11 22:45 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Instead of a vague prompt showing that there was a problem loading terminated YouTube channels and a Guru Meditation error, show a proper error with an option to remove the terminated channel(s) from the subscription list.

#### Is your feature request related to a problem? Please describe it

NewPipe currently does not handle terminated channels very well, only showing a small prompt with a link to a Guru Meditation error.

#### Additional context

The error message that appears when you attempt to refresh a feed with a terminated or unsupported channel.
![Screenshot_20210111-143841](https://user-images.githubusercontent.com/40573129/104246410-ca9b7280-541a-11eb-91bb-be1e2c57d649.jpg)

#### How will you/everyone benefit from this feature?

No more dreadful, menacing Guru Meditation errors for simply explained occurrences.

**Comment by mhmdanas** [comment] 2021-01-12 16:39
Thanks for opening an issue! I think this is a duplicate of #3313. If you disagree, feel free to write a comment.

**Closed by mhmdanas** 2021-01-12 16:39 UTC
Labels: enhancement
