### ISSUE TITLE
Option to disable timestamps on share button

### ISSUE THREAD

**Issue by TippyLion28** [TeamNewPipe/NewPipe#4391] opened 2020-10-04 20:40 UTC
### Checklist

- [/] I checked, but didn't find any duplicates of this issue in the repo. 
- [/] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [/] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Add an option to disable timestamps on share button

#### How will you/everyone benefit from this feature?

I don't always want to timestamp video links that I'm sharing with people

**Comment by opusforlife2** [comment] 2020-10-05 02:20
If you just want a plain Share button back, then duplicate of #4039. Can you confirm?

**Comment by TippyLion28** [comment] 2020-10-05 04:55
No, there is already a share button. However I would like the option to disable the &t=XXX

In effect this would be sharing the video without a timestamp.

**Comment by opusforlife2** [comment] 2020-10-05 04:57
The share button in the top bar shares the link without the timestamp in 0.19.8. So in that version, there are two kinds of share buttons. We're discussing how to put that and other buttons into the action bar in the issue I linked.

**Comment by TippyLion28** [comment] 2020-10-05 05:04
Ohh this makes sense! I was second-guessing myself about whether this was always the behaviour of the share button. I suppose this issue is pretty redundant then :-)

**Comment by opusforlife2** [comment] 2020-10-05 05:05
Thanks for confirming!

**Closed by opusforlife2** 2020-10-05 05:05 UTC
Labels: enhancement
