### ISSUE TITLE
Stream hangs when playing after a long break

### ISSUE THREAD

**Issue by micw** [TeamNewPipe/NewPipe#7712] opened 2022-01-28 11:37 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x]  I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
I'm viewing some longer videos during lunch. When I', finished (with lunch), I pause the video and put my tablet aside. The next day (or some days after), I resume playing where I stopped.

### Actual behavior
It plays a few more minutes (probably until a buffer is empty), then stops. I need to re-open the video to continue watching.

### Expected behavior
Video should continue seamlessly. At least it should be able to recover when the end of buffer is reached.

Alternatively, there should be some way to reload, so that I do not need to navigate away and back to reload the video.

### Device info

 - Android version/Custom ROM version: 11 (original rom, latest update)
 - Device model: Galaxy Tab S5e

**Comment by mhmdanas** [comment] 2022-01-28 14:08
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5730.

**Closed by mhmdanas** 2022-01-28 14:08 UTC
Labels: bug
