### ISSUE TITLE
Background audio playback resumes by itself

### ISSUE THREAD

**Issue by chrisvella** [TeamNewPipe/NewPipe#570] opened 2017-05-19 01:24 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

First of all thank you for the great program. I use it every day.

I have an issue with NewPipe resuming background audio playback on various events i.e. getting a message. This can be pretty embarrassing haha

I am using version 0.9.6 from fdroid.

**Comment by mauriciocolli** [comment] 2017-05-19 01:31
Yeah I already fixed it, just wait for the next version.

Also this a duplicate of #519.

**Closed by mauriciocolli** 2017-05-19 01:31 UTC
Labels: duplicate
