### ISSUE TITLE
Show subtitle

### ISSUE THREAD

**Issue by mhd4mr** [TeamNewPipe/NewPipe#1001] opened 2018-01-16 23:54 UTC
Hi, please add subtitle feature like (YouTube.com)

Now I must to download subtitle from https://downsub.com/ and download video from YouTube.com and play with MX Player.

**Comment by wb9688** [comment] 2018-01-17 05:35
We're already working on that and this is a duplicate of #55.

**Closed** 2018-01-17 05:35 UTC
