### ISSUE TITLE
Not enough space to display playing position

### ISSUE THREAD

**Issue by minsk21** [TeamNewPipe/NewPipe#3018] opened 2020-01-27 17:47 UTC
NewPipe v0.18.2

Display 5.5', 1440 x 2560 pix, 411 dp

<details>

![screenshot](https://i.imgur.com/cEuemQS.png)

</details>

**Comment by Stypox** [comment] 2020-01-27 18:42
This is a duplicate, though I can't find the related issue

**Comment by Stypox** [comment] 2020-02-19 15:05
Duplicate of #2606

**Closed by Stypox** 2020-02-19 15:05 UTC
Labels: GUI, bug, duplicate, player
