### ISSUE TITLE
Some videos load forever with WebM for some reason

### ISSUE THREAD

**Issue by Atemu** [TeamNewPipe/NewPipe#3298] opened 2020-03-30 02:45 UTC
### Version

- 0.19.0

### Steps to reproduce the bug

1. Set the default video format to WebM
2. Open an affected video like [this one](https://www.youtube.com/watch?v=kh9NUF6X21U)
3. Open the player

### Expected behavior
Tell us what you expected to happen.

I would expect it to load the video and, if it fails that, try to fall back to the highest quality MPEG-4 stream or, if that doesn't work either, even less desirable ones like the 360p vp8 streams or 3GP streams.

### Actual behaviour
Tell us what happens instead.

It just sits there and "loads" forever with no visible network activity.

The 360p MPEG-4 stream in the dropdown works and even the 1080p60 MPEG-4 stream works when the default video format is set to MPEG-4.

The YouTube app loads the highest quality MPEG-4 stream (299) by default.

### Screenshots/Screen records
If applicable, add screenshots or a screen recording to help explain your problem. GitHub should support uploading them directly in the issue field. If your file is too big, feel free to paste a link from an image/video hoster here instead.

### Logs
If your bug includes a crash, please head over to the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/). Copy the result. Paste it here:

**Comment by Stypox** [comment] 2020-03-30 07:11
Duplicate of #2415

**Closed by Stypox** 2020-03-30 07:11 UTC
Labels: bug
