### ISSUE TITLE
Comments are not displayed in version 0.20.10, 0.20.6

### ISSUE THREAD

**Issue by ProblemCase** [TeamNewPipe/NewPipe#5717] opened 2021-02-27 23:30 UTC
Hi! I just wanted to inform you that after the update to version 0.20.10 the comments are no longer displayed. In the settings it is set to "Show comments", and in the previous version you could see them. Is there something for me, as a user, can do to make the comments visible again? Thank you!
The app is installed on Sony TV in the Android TV and the Samsung Tablet S6.

**Comment by AchmadFathoni** [comment] 2021-02-28 04:27
Can confirm, still 'no comment' even after the restricted mode is disabled.

**Comment by mhmdanas** [comment] 2021-02-28 05:32
Duplicate of #5585.

**Closed by mhmdanas** 2021-02-28 05:32 UTC
Labels: bug
