### ISSUE TITLE
Maximize into and after popup bug

### ISSUE THREAD

**Issue by duofficier** [TeamNewPipe/NewPipe#7092] opened 2021-09-11 13:10 UTC
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior
  Video opens in portrait fullscreen. This can be 'fixed' by turning phone to landscape. Can only close video which results in the newpipe app being expanded over my statusbar and navigation button bar. In this state I can open other videos but the maximize button doesnt work anymore. 

### Expected behavior
Id expect it to not have these issues and switch between modes without issues. Tried to record this but screen recording strangely enough doesnt capture landscape fullscreen and portrait fullscreen correctly

### Device info

 - Android version/Custom ROM version: android 11 onui core 3.1
 - Device model: samsung m51

**Comment by mhmdanas** [comment] 2022-01-22 08:59
Closing as duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5339.

**Closed by mhmdanas** 2022-01-22 08:59 UTC
Labels: bug, GUI, player
