### ISSUE TITLE
Volume spikes

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#7460] opened 2021-11-28 17:39 UTC
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

Volume level fluctuate from the current value to a newer (lower) one, more and more times in a second.

### Expected behavior

Volume should keep a preset value (chosen by the user).

### Device info

 - Android version/Custom ROM version:
Android 12/One Ui 4.0
 - Device model:
 S21

**Comment by 9Orlaf2** [comment] 2021-11-28 17:39
@Stypox

**Comment by mhmdanas** [comment] 2021-11-28 17:43
@9Orlaf2 any particular reason you're pinging a team member?

**Comment by 9Orlaf2** [comment] 2021-11-28 17:45
> @9Orlaf2 any particular reason you're pinging a team member?

I once read a bug report where stypox talked about a Volume FX implementation. Maybe he already knows what the problem is.

**Comment by mhmdanas** [comment] 2021-11-28 17:46
@9Orlaf2 makes sense, but it's quite rude to ping somebody like this out of the blue; I recommend you avoid it in the future.

**Comment by 9Orlaf2** [comment] 2021-11-28 17:49
> @9Orlaf2 makes sense, but it's quite rude to ping somebody like this out of the blue; I recommend you avoid it in the future.

Next time I'll try to explain myself instead put a general tag.

**Comment by mhmdanas** [comment] 2021-11-28 17:50
@9Orlaf2 that's not exactly the issue; it's that you're pinging them at all.

**Comment by 9Orlaf2** [comment] 2021-11-28 17:52
> @9Orlaf2 that's not exactly the issue; it's that you're pinging them at all.

Ok, they should not be tagged regardless. No problem.

**Comment by opusforlife2** [comment] 2021-11-28 17:54
Do you have a system/user equalizer app active?

**Comment by 9Orlaf2** [comment] 2021-11-28 17:57
> Do you have a system/user equalizer app active?

The one of One Ui, set to normal with Dolby Atmos enabled and set on Music preset.

Have no problem with other apps, except with NewPipe.

**Comment by opusforlife2** [comment] 2021-11-28 17:58
Try disabling the Equalizer and use Newpipe, so we can narrow down the problem to it.

**Comment by 9Orlaf2** [comment] 2021-11-28 18:02
> Try disabling the Equalizer and use Newpipe, so we can narrow down the problem to it.

Ok. I've disabled Dolby Atmos (the only disabled option...equalizer can't be disabled) and the problem still exists.

**Comment by opusforlife2** [comment] 2021-11-28 18:05
Is your Equalizer set to the default values for everything? If not, could you temporarily do that and try Newpipe?

**Comment by 9Orlaf2** [comment] 2021-11-28 18:08
> Is your Equalizer set to the default values for everything? If not, could you temporarily do that and try Newpipe?

I leave the equalizer set on default preset. But again: One Ui don't allow me to disable it...unfortunately.

**Comment by opusforlife2** [comment] 2021-11-28 18:10
No, if it's set to the default, then the problem isn't with the interaction between Newpipe and the Equalizer. It's something else.

Do you have any other app or setting that modifies the sound coming out of media apps?

**Comment by 9Orlaf2** [comment] 2021-11-28 18:16
> No, if it's set to the default, then the problem isn't with the interaction between Newpipe and the Equalizer. It's something else.
> 
> Do you have any other app or setting that modifies the sound coming out of media apps?

Nope...except these two values there's nothing that could interact with audio.

All these options are condensed in a menu called: "Audio quality and effects".

**Comment by opusforlife2** [comment] 2021-11-28 18:24
Just to be sure, you're not using anything like Viper4Android?

**Comment by 9Orlaf2** [comment] 2021-11-28 18:32
> Just to be sure, you're not using anything like Viper4Android?

Nope. Everything on my phone is stock (and if I'm not wrong Viper4Android works just with root).

**Comment by opusforlife2** [comment] 2021-11-28 18:34
Ah, well, then I'm out of ideas for now. Thanks for testing.

**Comment by 9Orlaf2** [comment] 2021-11-28 18:37
> Ah, well, then I'm out of ideas for now. Thanks for testing.

There is a section in code where volume is managed? Maybe the problem can be solved in an easy way.

**Comment by ShareASmile** [comment] 2024-02-17 17:04
Closing this issue, as it cannot be rechecked with its author how app behaves on latest version as its author is a ghost now.

If anyone experiences this issue please open a new one.

**Closed by ShareASmile** 2024-02-17 17:04 UTC
Labels: bug
