### ISSUE TITLE
Downloading and viewing of videos/playlists within the app

### ISSUE THREAD

**Issue by pdmnhn** [TeamNewPipe/NewPipe#8398] opened 2022-05-14 11:42 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Enable downloading and viewing of videos/playlists offline within the app like in the official YouTube app downloads with the already available option of downloading of the video to the device storage.

### Why do you want this feature?

I watch videos from playlists of order of 200 videos during commute during which internet speed with mobile data is very bad, so downloading each video separately and organizing the videos to watch them in a separate app is a nightmare, so adding the feature of downloading entire playlist will be very useful

**Comment by SameenAhnaf** [comment] 2022-05-14 12:48
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5482 and https://github.com/TeamNewPipe/NewPipe/issues/2414

**Comment by TiA4f8R** [comment] 2022-05-14 13:32
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #5482 and #478. Please search (better, with different keywords?) for duplicates the next time you want to open an issue.

> - [x] This issue contains only one feature request.

No, it contains two feature requests. Please follow properly our issue template the next time you want to open an issue.

Thank you!

**Closed by TiA4f8R** 2022-05-14 13:32 UTC
Labels: enhancement
