### ISSUE TITLE
Big playlists only loading first 100 videos

### ISSUE THREAD

**Issue by mjsir911** [TeamNewPipe/NewPipe#4903] opened 2020-11-17 04:26 UTC
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to https://www.youtube.com/playlist?list=PLABS9rhwbrHkrsit9lgHhx7MyqjJvj34C&list=UL
2. Scroll down

### Actual behaviour

Last selectable video is 'How About a Song? "An Unwavering Heart" - Pokemon X & Y"

Same behavior if enqueued on background

### Expected behavior

Expected to load 100 more videos, which is a bit inconvenient on a 3000 video playlist to get to the bottom but is sane behaviour

**Comment by mhmdanas** [comment] 2020-11-17 05:42
Duplicate of #4819.

**Closed** 2020-11-17 06:11 UTC
Labels: bug
