### ISSUE TITLE
(Idea) Installation of an Youtube Music selection (like Soundcloud)

### ISSUE THREAD

**Issue by jnewz** [TeamNewPipe/NewPipe#1927] opened 2018-12-04 12:06 UTC
It would be nice to have Youtube Music own button similar to Soundcloud.

**Comment by copoer** [comment] 2018-12-12 14:39
Similar issues
#1484  #1931

**Comment by Stypox** [comment] 2019-08-28 21:16
Duplicate of #1484

**Closed by Stypox** 2019-08-28 21:16 UTC
