### ISSUE TITLE
[Feature request] Sort videos in channels

### ISSUE THREAD

**Issue by HTSamurai** [TeamNewPipe/NewPipe#5324] opened 2020-12-31 16:48 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
DICLAIMER: A lot of times, no results come up on my devices and people still say it is a duplicate. I don't know why it doesn't come up.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I want to be able to sort the order of videos in a channel (for example by newest or oldest first.)

#### Is your feature request related to a problem? Please describe it
The channel page doesn't have many things so I thought this would be good.

#### Additional context

Here's my *mock-up!*
![IMG_20201231_164102](https://user-images.githubusercontent.com/71007160/103418710-c43e0880-4b87-11eb-964c-a8c9539f7954.jpg)
I couldn't make this *mock-up* look good in dark mode so I did it in light mode *by the way*

#### How will you/everyone benefit from this feature?

People can find videos easily with this feature!

**Comment by HTSamurai** [comment] 2020-12-31 16:49
Sorry if this isn't very clear, it's hard to say why or what, it would just be nice to have as an optional button.

**Comment by mhmdanas** [comment] 2020-12-31 16:58
This _might_ be a duplicate of #5202, but it's unclear whether they're talking about the videos of one channel or the "what's new" page. I would actually be inclined to keep this one if it is indeed a duplicate of #5202 as this one is far clearer.

> DICLAIMER: A lot of times, no results come up on my devices and people still say it is a duplicate. I don't know why it doesn't come up.

A possible reason is that I usually search using multiple possible terms. But this time, I just searched for "sort" and got #5202 in third place. So yeah, something might be wrong on your side.

**Comment by HTSamurai** [comment] 2020-12-31 17:03
> This _might_ be a duplicate of #5202, but it's unclear whether they're talking about the videos of one channel or the "what's new" page. I would actually be inclined to keep this one if it is indeed a duplicate of #5202 as this one is far clearer.
> 
> > DICLAIMER: A lot of times, no results come up on my devices and people still say it is a duplicate. I don't know why it doesn't come up.
> 
> A possible reason is that I usually search using multiple possible terms. But this time, I just searched for "sort" and got #5202 in third place. So yeah, something might be wrong on your side.

Yeah that one is a bit "*w*h*a*t *i*s *t*h*e *m*e*a*n*i*n*g *o*f *t*h*i*s"

**Comment by litetex** [comment] 2022-03-07 19:21
Consolidated into #7729

**Closed by litetex** 2022-03-07 19:21 UTC
Labels: enhancement
