### ISSUE TITLE
[Feature request] download entire playlists

### ISSUE THREAD

**Issue by gcandrade10** [TeamNewPipe/NewPipe#1512] opened 2018-06-27 04:33 UTC
- [ √] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ √] I checked if the issue/feature exists in the latest version.
I'm fan of newpipe, I used it to listen music in background, it would be great if a playlist could be downloaded a played offline.
English is not my main language, sorry for typos.

**Comment by MaskedPierrot** [comment] 2018-07-06 16:24
Was just about to come make this suggestion. It really would be great

**Comment by TobiGr** [comment] 2018-07-09 21:19
Duplicate of #1058

**Closed by TobiGr** 2018-07-09 21:19 UTC
Labels: duplicate
