### ISSUE TITLE
[Feature Request] Extensive Search Options

### ISSUE THREAD

**Issue by tekbry** [TeamNewPipe/NewPipe#2696] opened 2019-10-06 05:59 UTC
NewPipe search options are very limited. Is there any way to sort searches by duration, upload date, or even quality of stream both in ascending and descending form? How about filters as well, by limiting searches for the above criteria. Most other YouTube apps dont limit the search functionality.

**Comment by Stypox** [comment] 2019-10-06 06:47
Duplicate of #110

**Closed by Stypox** 2019-10-06 06:47 UTC
