### ISSUE TITLE
Option to display channels' playlists when in channel screen

### ISSUE THREAD

**Issue by illustribe** [TeamNewPipe/NewPipe#8453] opened 2022-05-28 17:41 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

When looking at a channel's content, there's no way to see the channel's playlists. I think it'd be so good to be able to view them without going to YT

### Why do you want this feature?

Been explained just before 👆

**Comment by litetex** [comment] 2022-05-28 18:41
Duplicate of #2414

**Closed by litetex** 2022-05-28 18:41 UTC
Labels: enhancement
