### ISSUE TITLE
Background button is sometimes missing

### ISSUE THREAD

**Issue by expobar** [TeamNewPipe/NewPipe#2465] opened 2019-07-16 06:20 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

### _This issue seems like a duplicate of other issues but I couldn't find the exact filed issue that represents it._

**Comment by expobar** [comment] 2019-07-16 06:24
![2019-07-16-142235](https://user-images.githubusercontent.com/52035600/61270832-67089880-a7d5-11e9-9e0b-7ffd411f03d7.jpg)

**Comment by expobar** [comment] 2019-07-16 06:26
A quick fix I found is simply clearing the cache of the app, it will go back to normal until this issue comes up again.

**Comment by Stypox** [comment] 2019-07-26 19:19
Duplicate of #1671

**Closed by Stypox** 2019-07-26 19:19 UTC
