### ISSUE TITLE
absolutely positioned video player with relatively positioned comments

### ISSUE THREAD

**Issue by skojr** [TeamNewPipe/NewPipe#8465] opened 2022-06-01 20:07 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

It would be great to have an absolutely positioned player with scrolling comments so the player stays fixed while browsing comments. This would be a major improvement to user experience.

### Why do you want this feature?

The benefits of this are standalone, but browsing videos isn't the same without reading comments and vice versa. It's almost imperative to be able to do both at the same time!

### Additional information

Just a thanks to the team for an already awesome project.

**Comment by SameenAhnaf** [comment] 2022-06-01 21:50
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4484

You might use hack mentioned in https://github.com/TeamNewPipe/NewPipe/issues/5450#issuecomment-762596954 temporarily.

**Closed** 2022-06-11 18:37 UTC
Labels: enhancement
