### ISSUE TITLE
Next/Previous Buttons Missing - With Auto-Queue Off

### ISSUE THREAD

**Issue by desmonk** [TeamNewPipe/NewPipe#6351] opened 2021-05-22 16:16 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Turning off auto-queue will make next and previous buttons go missing.

### Actual behaviour

Next and previous play back buttons go missing.

### Expected behavior

Should stay as normally they do.

### Screenshots/Screen recordings

NA

### Logs

NA

### Device info

 - Android version/Custom ROM version: 11
 - Device model: OnePlus

**Comment by mhmdanas** [comment] 2021-05-22 17:20
I think that's intended behavior. If you don't have auto-queue, nothing is in the queue before/after the current video unless you add something manually, so having next/previous buttons wouldn't make sense.

**Comment by desmonk** [comment] 2021-05-22 19:20
First, slow down and read again from a user standpoint.

Buttons should not rely on queue. They must remain static.

A user should have independence to choose from. This is like saying I won't want to play next or previous video if automatic queue is off! That is never the case. Never. We play songs and videos as we wish and that don't need to rely on whether we have some playlist or auto queue on.

This is really simple to understand and I am surprised you failed to see this clearly and closed the case without giving some deep thoughts. Always, think twice before arriving to a decision. There are always two sides to the coin.

And we all say, with great power comes great responsibility. So I hope you use your powers well.

Also, auto queue feature consumes unnecessary data if left on all the time. This give a user manual control. Hope this info has helped you!

**Comment by mhmdanas** [comment] 2021-05-22 19:25
> A user should have independence to choose from. This is like saying I won't want to play next or previous video if automatic queue is off! That is never the case. Never. We play songs and videos as we wish and that don't need to rely on whether we have some playlist or auto queue on.

Well, the buttons are suppose to move forward/backward in the queue. If the queue is empty, there's nothing to move to, so then what are the buttons supposed to do?

> Also, auto queue feature consumes unnecessary data if left on all the time.

What is your source on that statement?

**Comment by desmonk** [comment] 2021-05-22 19:34
Buttons should play forward an backward as needed not relying on queue. See, a queue is merely an option to continue playing while buttons hit a break on it when needed. In short, they must remain independent of queue or playlist. Buttons needs to be simple buttons, that's all!

Auto-queue gonna keep going and going and that gonna consume data? Are you referring to something else? If I misunderstood, do let me know.

**Comment by mhmdanas** [comment] 2021-05-22 19:41
> Auto-queue gonna keep going and going and that gonna consume data by definition.

It does not keep going. It will just put the next video in the queue, and when the current video finishes and the next video starts playing, the third video is then automatically queued. Thus, no extra data is used up at all. This means that there are absolutely no cons to enabling auto-queue, so you should be able to use it just fine.

> In short, they must remain independent of queue or playlist.

The buttons are dependent on the queue (not the playlist, as its items are added to the queue itself); that's how they're designed to work. I'm not sure I see the benefit of decoupling them from the queue. Could you explain?

**Comment by mhmdanas** [comment] 2021-05-22 19:42
I'll be opening this issue to continue the discussion, but I personally find this unnecessary to implement.

**Comment by desmonk** [comment] 2021-05-22 19:49
Buttons need to be independent. It's like taking away manual gear option just because there is auto transmission! Users here can choose if they want to hit next or go back or pause. Also, about data. Think of this like this. Auto-queue will continue playing videos whether user wants or not as that is how this works unless there is some end to the list. That gonna consume data.

Meaning, auto queue actually does not stop unless it is turned off. And right now, if we turn it off, the buttons go down with it. Best analogy would a Walkman player from old days. We need to in control of selection, not the algorithm!

Thank you and I hope to learn from you too!

**Comment by mhmdanas** [comment] 2021-05-22 20:10
Ok, I think I understand what you mean now. Thanks for the explanation.

I understand why you want this now, but I thought up a solution that I found simpler and hopefully easier to implement: add an option to not go to the next video in the queue automatically, which would have the same effect that you want but you would also have to have auto-queue enabled. This option would also be more useful generally, for example when playing playlists. What is your opinion about this?

**Comment by desmonk** [comment] 2021-05-22 22:25
That's a good one but thing is that will confuse users more. Then we have to implement say, Auto-Play option in addition to Auto-Queue. That will allow users to disable/enable auto playing of videos with queue enabled.

But again, there is no manual control here, is it? This still won't allow user to hit Forward/Backward buttons. Meaning with your options, next video won't play. But now how to play then? As there are no buttons for navigation except the ouch controls.

But touch controls won't work in full screen mode and only work with side menu of videos are visible. So once again, buttons are needed.

Think of this like this. Without buttons, we can't move. With auto-play and auto-queue, we can only halt or continue, we can't still hit next or go back.

**Comment by mhmdanas** [comment] 2021-05-22 22:34
> his still won't allow user to hit Forward/Backward buttons.

Why not? As long as the queue contains more items (which auto-queue add) they can press the forward/backward buttons as they please. Am I misunderstanding?

**Comment by desmonk** [comment] 2021-05-22 22:51
We are on two different tracks:

You:
Auto-queue stays enabled but won't automatically plays next video. So buttons also stay present.

Me:
Buttons needs to be present all the time irrespective of any queue.

Now how your suggestion will lead to confusion is like this:
Auto-queue means to automatically queue. Right now all videos are getting played like this. It is more simple. Still no buttons. But if we halt the automatic playback, then the auto-queue which most users including myself think will play next video, won't simply play. So now we need something like auto-play and therefore we added more steps.

Whereby in my case, all we need are buttons.

**Comment by SameenAhnaf** [comment] 2021-05-23 05:24
I don't know about your use case. But these are probably the possible reasons.

1. Prevent more data usage.

It's not true. As @mhmdanas stated, new videos are loaded only if streaming a video is complete.

> It does not keep going. It will just put the next video in the queue, and when the current video finishes and the next video starts playing, the third video is then automatically queued. Thus, no extra data is used up at all. This means that there are absolutely no cons to enabling auto-queue, so you should be able to use it just fine.

If you really want to save data, enable 'Auto-queue next stream' from Settings>Video and Audio and disable "Show 'Next' and 'Similar' videos". Please note that you can't remove next video directly. You need to replace it somewhere. Then, you will be able to remove it. This has a couple of perks.
A. Show videos one by one.
B. Buttons are still there.
C. You can choose whether the the next video to play or not.
D. You can go back or ahead.
The same option should also solve this problem.
>Buttons should play forward and backward as needed not relying on queue.

https://user-images.githubusercontent.com/79245641/119248195-5be0d980-bbb1-11eb-8e89-b0cff9f41c4e.mp4

2. Stream next videos only manually through buttons. 

It won't be possible to recognise if playing an enqueued list is complete or not. Plus, as I mentioned earlier, it's not necessary to enable "Show 'Next' and 'Similar' videos" for related videos. This will even let users into confusion who don't need related videos and enqueue videos only by themselves.

![IMG_20210523_093335](https://user-images.githubusercontent.com/79245641/119248473-2b9a3a80-bbb3-11eb-96c0-dd8ccf977ca3.jpg)

3. >Buttons need to be independent. It's like taking away manual gear option just because there is auto transmission!
>Buttons needs to be present all the time irrespective of any queue.

When you are enabling 'Auto-queue next stream', you are actually affirming that you need buttons. Why do you need buttons? You want to play videos one by one. Plus, a single or more related videos can be optionally loaded as I mentioned in the first point.

4. >With auto-play and auto-queue, we can only halt or continue, we can't still hit next or go back.

I'm not sure what exactly you are talking about. You opened this issue so that you can get buttons regardless of enabling 'Auto-queue next stream' setting. If "Auto-queue" option is enabled, you should be able to get back and skip videos with 'Previous' and 'Next' button respectively.

5. >First, slow down and read again from a user standpoint. Buttons should not rely on queue. They must remain static.
>Whereby in my case, all we need are buttons.
>Buttons needs to be present all the time irrespective of any queue

Nope, everyone doesn't always need buttons. Many users like me only need them while playing an enqueued list. If I don't want to enqueue any video, why do I need them?

6. >Buttons should play forward and backward as needed not relying on queue. See, a queue is merely an option to continue playing while buttons hit a break on it when needed. In short, they must remain independent of queue or playlist.

Could you please explain what difficulties else are you facing while enabling 'Auto-queue next stream'? If you don't want showing a queue or playlist on the front while main player, my uploaded video has that solution. 

Also, what will be the function of forward and backward buttons for the first and last of an enqueued list?? Maybe, they could be greyed out. But the current behaviour of hiding it seems to be much more specific and also helpful for senior users.

I agree to @mhmdanas if something like this really has to be implemented. As far as I know, Newpipe is the only player allowing the users to disable thumbnails. But disabling it doesn't actually save a good amount of data. Then, why is this feature? Because that's the core power of Newpipe, "Everything you need, nothing you don't".

>add an option to not go to the next video in the queue automatically, which would have the same effect that you want but you would also have to have auto-queue enabled. This option would also be more useful generally, for example when playing playlists.

**Comment by desmonk** [comment] 2021-05-23 08:38
Thank you for that detailed response.

1. Data consumption increases as the auto queue by definition gonna start the next video after the current one ends. Simple as that. I'm not referring to thumbnails here. I am referring to player keeps on going to play next queue whether warranted.

2. Disabling video suggestions as grouped under similar and next will worsen the experience completely. This is a core YouTube feature.

3. Need buttons! They go missing in normal and also in full screen without auto queue on.

4. Same as above.

5. Need to work regardless of auto queue.

6. You're focused on queued list. Thereby you think that buttons are needed in such case. I'm focused on only buttons. Meaning say there is a next video in queue but I'd like to choose to play it or not. Not relying on auto queue at all. Present situation allows the play back to continue consuming more data. Also, full screen mode must have buttons just as stated here. We can touch the next video in normal UI but in full screen we can't as there is nothing there.

Hope I've answered well.

**Comment by SameenAhnaf** [comment] 2021-05-23 09:02
As far as I understand, you want to enter next related video directly from full screen but manually, right? Then, we might implement this feature.

Swipe up the bottom interface for entering any related videos. Unlike YouTube app, swiping up for related videos should occur from only bottom interface as swiping up is already involved in volume and brightness gestures.

https://user-images.githubusercontent.com/79245641/119254309-6c0baf80-bbd7-11eb-815c-f2aa364f21d1.mp4

Would you agree to have it instead of always-on buttons? Avoiding always-on buttons would help us know if a queue truly exists or not and also remove this bug.
https://user-images.githubusercontent.com/79245641/119248473-2b9a3a80-bbb3-11eb-96c0-dd8ccf977ca3.jpg

**Comment by desmonk** [comment] 2021-05-23 15:14
That's a well thought out idea to be honest. But why not have buttons too? What if a user is not geared toward using gestures? Many use old UI and even Android has kept it for a reason. Besides that you pretty much nailed it!

**Comment by SameenAhnaf** [comment] 2021-05-23 16:22
>But why not have buttons too?

I completely understand the reason why you want YouTube app behaviour. But I also used to misunderstand a lot of things just like you (and I still do😅). Newpipe app is nearly six years old. So, yes, many old users would like to have current behaviour as usual.

>Many use old UI and even Android has kept it for a reason.

That's completely okay. You have the independence to choose how to deal with things. But if you try to lock yourself into a never-changing UI, you will eventually miss a lot of new things that might be useful for you. Newpipe has a lot of customisations and the app requires a proper co-ordination.

>But why not have buttons too? What if a user is not geared toward using gestures? 

Normally, buttons only appear if a queue actually exists. As I stated earlier, there will remain no opportunity to know if a queue is actually in existence or not. See the screenshots for better understanding. Sorry for my poor editing capabilities.

![IMG_20210523_213747](https://user-images.githubusercontent.com/79245641/119268216-c9bded00-bc13-11eb-8858-a2acd9e52f12.jpg)
![IMG_20210523_214632](https://user-images.githubusercontent.com/79245641/119268217-cd517400-bc13-11eb-82b8-d8c11f4ffd71.jpg)
![IMG_20210523_222038](https://user-images.githubusercontent.com/79245641/119268501-1f46c980-bc15-11eb-9eec-271add1f0a3c.jpg)


>That's a well thought out idea to be honest.
>Besides that you pretty much nailed it!

Thank you so much for the appreciation. I am glad to know that I could help you at least a little 😀.

**Comment by desmonk** [comment] 2021-05-23 19:03
I have question now. Aren't the queued videos actually suggested ones by YouTube as they resonate with it? Buttons are still needed though as with auto queue will continue after each video and also have no option on full screen UI.


I'm not at all against implementation of gestures but if we have to develop a really good app that can cover older phones too, then we better have some options as Android have.

**Comment by SameenAhnaf** [comment] 2021-05-24 03:15
No, having related videos enabled is not a condition for enqueueing videos. Watch the video. I disabled both "Auto-queue next stream" and "Show 'Next' and 'Similar' videos". Yet, I was able to enqueue videos from seperate feeds like search results, channel feed and subscription feed.
Extremely sorry for poor video. I had to cover the file size limit 

https://user-images.githubusercontent.com/79245641/119291343-1cc58d80-bc70-11eb-8aed-5f9deb318d32.mp4

**Comment by desmonk** [comment] 2021-05-24 03:47
I see that you manually created a queue. Differences here is turning of YouTube suggested videos breaks down the experience as most users would want some similar videos as this trend of so called recommended things are crucial and carefully designed and calibrated. Not just YouTube but all major apps. Example, Amazon.

My focus right now is having independence from queue completely. The swipe gesture from the bottom is a good one in full screen. But buttons too important as they represent a bold behavior. Meaning they state the obvious. So you have to think beyond queue here. Especially not manual queue as turning off recommended videos is a big let down.

Also, I observe one tiny thing. The video progress bar is so thin to manually drag the slider!

**Comment by SameenAhnaf** [comment] 2021-05-24 06:53
>YouTube suggested videos breaks down the experience as most users would want some similar videos as this trend of so called recommended things are crucial and carefully designed and calibrated. 

As a student, I watch videos on a single topic from selected teachers only. I know whom I need for better understanding. Plus, I won't like to switch topics every now and then unless my note is complete. I need very specific videos and would also have to finish them one by one. But YouTube never suggests videos according to every single person's preference.

The same goes for news readers, binge-watchers (a single series) and many other users. If you solely watch videos for entertainment purposes, you won't notice the importance. But that's not always the case.

>My focus right now is having independence from queue completely.

You're gonna miss a lot of things in that case.

1. Total queue duration
2. Repeat a single or all videos
3. Shuffle videos
4. Replace the videos' positions
5. Add selected videos to a playlist altogether
6. An enqueued list for playback at once
![IMG_20210524_115529](https://user-images.githubusercontent.com/79245641/119303372-708fa100-bc87-11eb-8fa6-baad831b8509.jpg)

>Differences here is turning of YouTube suggested videos breaks down the experience as most users would want some similar videos as this trend of so called recommended things are crucial and carefully designed and calibrated. Not just YouTube but all major apps. Example, Amazon.

If you want to question, you can question a lot of things. YouTube blocks almost all major functionalities if you go anonymous. But Newpipe offers an opportunity to unlock them like a charm without harming your privacy. Why don't you question that fact?

Every shoe doesn't fit every foot and Newpipe is no exception. Many people don't like Facebook. But that doesn't change the fact that Facebook is no. 1 social app. In reality, no streaming app is perfect. SnapTube enforces users to turn on gesture, Ymusic loads a single page of related videos, Tubemate only supports web version of YouTube with no extra functionality and the list goes beyond.

I know, you are having a hard time understanding the app. But all of the users have passed that phase. Please be patient to get accustomed.

Newpipe also offers support for SoundCloud, Peertube, BBC Sounds (upcoming) and Framatube. Should Newpipe follow their design language separately too?? That would make the app unnecessarily heavy and no streaming app works that way.

Every app has a core value and new changes should not be affect that. If you want to break the usual behaviour of an app, you may eventually kill the core functionalities like:
1. Losing anonymity: It becomes a lot easier to invade your privacy if you have an account
2. Playback on background and popup: Most streaming platforms don't offer them for free.
3. Blocking ads.
4. All functions mentioned in second point.

>Also, I observe one tiny thing. The video progress bar is so thin to manually drag the slider!

Please open a separate issue regarding this matter. You have already checked this checkbox.👇

>This issue contains only one bug. I will open one issue for every bug report I want to file.

**Comment by desmonk** [comment] 2021-05-24 14:54
Aren't similar videos function here take advantage of YouTube recommendations? If not then I have to admit how does this work? As NewPipe can't possibly have that secret sauce that need data scientists level programming to achieve this. And I'm stating a fact not comparison.

Secondly, you're a student. You are using it in a different manner. Most users are not students. And this is not some hypothesis. Entertainment is driving force here not education.

Your suggestion only solved full screen UI with swipe gestures. Again no buttons.

I'm surprised you're actually going in the wrong direction here. You are still not able to see that buttons are core functionality and having them made reliant on queue is never a good idea.

Third, I'm a long time user of this and I'm very well accustomed to the nature of the app. As a user my job is to think in ways that might help others too.

You can see my old issues opened here and understand how far I've gone to make this experience better for all and not just me or you.

**Comment by SameenAhnaf** [comment] 2021-05-24 15:21
I have no desire to argue with you. I have already suggested an alternative. Tell me how these functions will be available again.


>>You're gonna miss a lot of things in that case.

Total queue duration
Repeat a single or all videos
Shuffle videos
Replace the videos' positions
Add selected videos to a playlist altogether
An enqueued list for playback at once>>

>>

>You can see my old issues opened here and understand how far I've gone to make this experience better for all and not just me or you.

I appreciate your hard work. But it should not be unknown to you that a single fork was created for ditching multiple features in 0.20. See this issue: https://github.com/TeamNewPipe/NewPipe/issues/4918

Do you know the top reason listed? Losing the ability to have multiple queues on multiple players. See: #5864

**Comment by desmonk** [comment] 2021-05-24 16:49
Calm down!

I asked you how are you doing similar and grouped suggestions? You didn't answer. Also, what on earth are you talking about? Data? Privacy? Duh! Why do you think am I here?

Also, you are being arrogant here.

What kind of arguments are these? I asked a question and you're coming back with zero reply. Buttons are a must. Buttons! Don't you get it? Carbon copy of YouTube? What?

Do you even understand what are you talking about? I'm done with your idiotic attitude. You're not in the real world but some dreams.

This must open your eyes. You lack a clear vision.
I'm disappointed to write this as you are entrapped in your own web of mismanagement.

**Comment by mhmdanas** [comment] 2021-05-24 17:23
@desmonk why did you close this issue?

**Comment by desmonk** [comment] 2021-05-24 17:43
I don't want to keep pushing a button when the system is off the grid.

**Comment by SameenAhnaf** [comment] 2021-05-25 03:48
>I asked you how are you doing similar and grouped suggestions? You didn't answer.
>I asked a question and you're coming back with zero reply. Buttons are a must. Buttons! Don't you get it?

I did answer your question by suggesting an alternative. So, buttons are not a must.

>Swipe up the bottom interface for entering any related videos. Unlike YouTube app, swiping up for related videos should occur from only bottom interface as swiping up is already involved in volume and brightness gestures.

I wanted to keep buttons reliant on queue as "Swiping up for related videos" could be used as an alternative for your needs. But you wanted to ditch queue completely and make buttons reliant on related videos only. What is the alternative of queue? 

>My focus right now is having independence from queue completely.

>>You're gonna miss a lot of things in that case.
>1. Total queue duration
>2. Repeat a single or all videos
>3. Shuffle videos
>4. Replace the videos' positions
>5. Add selected videos to a playlist altogether
>6. An enqueued list for playback at once

Talking about carbon copy, I meant that we can't make every single thing like YouTube app. Data backup was just an example.

**Comment by desmonk** [comment] 2021-05-25 09:18
All you came up with was swiping up gestures in full screen. This doesn't work on standard UI. Also, when I asked about how you do the grouped/similar videos, as you're opposed to YouTube's recommendation service, you didn't answer oonce and instead started talking about all those aforementioned points as you are too focused only on custom made queues, which is a very specific approach to usage.

YouTube will always primary be about entertainment.
Not gonna get entangled here again as you can read each point again.

**Comment by SameenAhnaf** [comment] 2021-05-25 09:37
@desmonk What's the alternative of queue? Please suggest any.

Also, I have already mentioned that an entire fork had to be built just for ditching a queue-related feature. Even, many entertainment users need queues too as I mentioned about my sister.

>I appreciate your hard work. But it should not be unknown to you that a single fork was created for ditching multiple features in 0.20. See this issue: #4918
>
>Do you know the top reason listed? Losing the ability to have multiple queues on multiple players. See: #5864

**Comment by desmonk** [comment] 2022-12-11 19:21
Buttons are static and required to navigate easily. They should remain independent irrespective of anything else. They are simple buttons at the end of the day! This should not be that hard to see. Imagine the buttons only become visible on any device or app if we only allow it play next or previous selection!

**Comment by opusforlife2** [comment] 2022-12-11 19:46
Since you're available, open a new issue with the new issue forms.

**Closed by opusforlife2** 2022-12-11 19:46 UTC
Labels: bug

**Comment by desmonk** [comment] 2022-12-20 22:39
No problem I will open this as a feature request now as this is not a bug the default behavior.

**Comment by Sajid1500** [comment] 2023-02-15 08:42
This is something that I agree with and I also failed to understand how these guys just can't understand the point. It's like they've never used the YouTube app. I'm not saying copy the privacy interfering features but it sure would be useful if they could implement the others.
