### ISSUE TITLE
Main to popup

### ISSUE THREAD

**Issue by vkhomenk** [TeamNewPipe/NewPipe#3051] opened 2020-02-04 10:09 UTC
Changing from main view to popup opens both popup and background playback and randomly choses one to play.

**Steps to reproduce:**
1. Click on youtube video to open main view.
2. Go to popup view.
3. Opens both popup and background and plays one of them.

**Expected behaviour:**
...
3. Opens popup and plays it

**Configuration:**
Oneplus 7
Android 10
OxygenOS 10.3.0GM57AA

**Comment by Stypox** [comment] 2020-02-04 12:37
After 1. and 2. are there two notificantions in the app bar, one for the background player and one for the popup player?

**Comment by Stypox** [comment] 2020-02-07 13:57
Duplicate of #2070

**Closed by Stypox** 2020-02-07 13:57 UTC
Labels: more info needed

**Comment by vkhomenk** [comment] 2020-02-11 12:46
Yes there are two of them
