### ISSUE TITLE
Feature Request: "Download" in long press menu

### ISSUE THREAD

**Issue by radiationcowboy** [TeamNewPipe/NewPipe#7519] opened 2021-12-08 16:49 UTC
First off, this project is amazing. Thanks to all the devs and contributors.

Have you considered adding "Download" to the long press menu on the "Whats New" Tab?

I tried setting "download" under Behavior / Default 'open' action. But that doesnt seem to work, or I am missunderstanding it.

**Comment by SameenAhnaf** [comment] 2021-12-08 17:08
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2171

**Comment by TiA4f8R** [comment] 2021-12-08 18:22
@radiationcowboy It seems you are using a client which doesn't support issue templates, please next time use [our issue templates available in GitHub's new issue chooser for our repo](https://github.com/TeamNewPipe/NewPipe/issues/new/choose).

Like @SameenAhnaf said, this issue is a duplicate of #2171. Closing.

**Closed by TiA4f8R** 2021-12-08 18:22 UTC
