### ISSUE TITLE
[playlist] move to another, batching select

### ISSUE THREAD

**Issue by mo-han** [TeamNewPipe/NewPipe#7487] opened 2021-12-03 10:46 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

- add option to move selected item from current playlist to another list, which combines "add" and "delete" into one shot.
- select multiple items in the playlist, so the next operation will be done on them all in one shot.

#### Why do you want this feature?

reduce a lot of redundant work.

**Comment by SameenAhnaf** [comment] 2021-12-03 17:26
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3444. Also, please fill in the template properly.

**Closed** 2021-12-04 00:16 UTC
Labels: enhancement, template-ignored, waiting-for-author
