### ISSUE TITLE
Don't want to open anything when upgrade to newest available version

### ISSUE THREAD

**Issue by kovameshtar** [TeamNewPipe/NewPipe#7763] opened 2022-02-01 14:17 UTC
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### Additional context

![Screenshot_20220201-151614_NewPipe](https://user-images.githubusercontent.com/98824491/151984728-7c9cf792-4425-416e-93da-742b5292ba40.jpg)

**Comment by mbnoimi** [comment] 2022-02-01 14:30
Same problem occurs

**Comment by mhmdanas** [comment] 2022-02-01 14:36
Duplicate of #7734. Also, follow the template next time you open an issue.

**Closed by mhmdanas** 2022-02-01 14:36 UTC
Labels: question
