### ISSUE TITLE
Live streams: very low resolution

### ISSUE THREAD

**Issue by wiz0u** [TeamNewPipe/NewPipe#2667] opened 2019-09-27 22:31 UTC
Hello! I'm using NewPipe 0.17.3 on a PicoPix PPX4935 (1280x720)

When viewing normal videos, they show up in 720p without much problem.

When viewing a live stream, it shows up in 180p or something like that, very low resolution (and no selector to change the format)

Example: 
- https://www.youtube.com/watch?v=-aDOpyUmfL4
- https://www.youtube.com/watch?v=EEIk7gwjgIM

**Comment by Stypox** [comment] 2020-04-20 07:53
Duplicate of #1239

**Closed by Stypox** 2020-04-20 07:53 UTC
Labels: enhancement, requires extractor change, youtube
