### ISSUE TITLE
broken channels causing refresh error

### ISSUE THREAD

**Issue by test2a** [TeamNewPipe/NewPipe#3435] opened 2020-04-14 11:14 UTC
i am on 0.19.2 running on android 7. i have about 100 subscriptions but one of them has some error. maybe the channel was deleted or something else but everytime i refresh the app, with the new sortable view which is great, i am left with one error.  " this channel does not exist". the app does not say which channel is it so that i can remove the error.

there is a send bug report, i checked that but among other things, it only has the url of that channel and the error "this channel does not exist".

i am proposing that any channel which has been found to be problematic or like above, does not exist, the app should intimate the user with the name of that channel.

**Comment by B0pol** [comment] 2020-04-14 12:13
How to make your feed great again: find this channel that has been deleted, and unsubscribe by.
To do so, go in subscriptions page, click on each channel, and the one that display that is the good one.
<img src="https://user-images.githubusercontent.com/58657617/79223303-96256680-7e48-11ea-9ddc-a2b2db3a64e2.png" width="200">
Then go back to the subscriptions page, and unsubscribe by long pressing on channel then pressing "unsubscribe".

Ping @mauriciocolli, linked issue: https://github.com/teamnewpipe/newpipeextractor/issues/228 (with a channel to test) [here is where it's crashing in NPE](https://github.com/TeamNewPipe/NewPipeExtractor/blob/1b522304c12f966b8adde5664bfb14a6e27545be/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeChannelExtractor.java#L109).

**Comment by test2a** [comment] 2020-04-14 15:08
I have 104 subscriptions. Unable to check one by one.

**Comment by B0pol** [comment] 2020-04-20 07:58
Duplicate of #3313

**Closed by B0pol** 2020-04-20 07:58 UTC
Labels: bug, feed
