### ISSUE TITLE
Change behavior of back button in action bar

### ISSUE THREAD

**Issue by mission712** [TeamNewPipe/NewPipe#526] opened 2017-05-01 19:02 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hello. I have noticed that clicking the <- button on the action bar on NewPipe on a video view takes you back to the start page even if you have opened 3 videos, and this causes you to lose your video history. Can we do one of the following:
1. Make the back button on the action bar do the same thing as pressing the back button on the phone
2. Make the back button's icon a home icon so it makes more sense.

This isn't really a big deal but more of a QoL thing. Thanks in advance.

**Comment by mauriciocolli** [comment] 2017-05-01 19:32
Duplicate of #520

If the two button do the exact same thing, what is the purpose of having them both (and not just one)?
But I think this would improve the behavior https://github.com/TeamNewPipe/NewPipe/issues/520#issuecomment-298186207, what do you think?

**Closed** 2017-05-01 21:43 UTC

**Comment by mission712** [comment] 2017-05-02 09:38
That seems like a good solution. What about my second idea? Can we make it so it shows a home button?

**Comment by theScrabi** [comment] 2017-05-02 14:44
That would violate the material design criteria.

**Comment by mission712** [comment] 2017-05-03 03:17
I see. @mauriciocolli 's idea is what I support now.
