### ISSUE TITLE
Swipe gesture to switch to Ultrawide mode 

### ISSUE THREAD

**Issue by firefoxlover** [TeamNewPipe/NewPipe#6859] opened 2021-08-06 16:46 UTC
Hi, really great app!

Newpipe already has this feature, its just a bit hidden away and I think permanent or not. Would be great for people with a taller display to switch to this "zoom" mode (something on the top and bottom is cut out) by pulling two fingers out or by a shortcut in the dropdown menu.

**Comment by SameenAhnaf** [comment] 2021-08-06 16:59
Please keep the discussion in #3181.

**Comment by litetex** [comment] 2021-08-06 20:24
Duplicate of #3181 

You may upvote #3181

**Closed by litetex** 2021-08-06 20:24 UTC
