### ISSUE TITLE
Cannot play viedo which is age restricted.

### ISSUE THREAD

**Issue by agn-gpl** [TeamNewPipe/NewPipe#5006] opened 2020-11-26 03:18 UTC
### Checklist

- [o] I am using the latest version - 0.20.4 
- [o] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [o] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [o] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Find some age restricted video on youtube, like https://www.youtube.com/watch?v=r4JWI4UDOrc
2. Open with Newpipe.
3. It showed that the content is unaviable, but I can see some recommentsof the video there.

P.S. option "Show age restricted content" is on.

### Actual behaviour

Video not unaviable. Cannot play it.

### Expected behavior

I can play this video with Newpipe.

### Screenshots/Screen recordings

[link](https://i.imgur.com/Tro4i7o.png) 

### Device info

 - Android version/Custom ROM version: 9
 - Device model: ASUS_X00TDB

**Comment by TotalCaesar659** [comment] 2020-11-26 18:33
I guess Google starts to forbid playing embedded age-restricted videos: https://9to5google.com/2020/09/22/youtube-age-restricted-videos/
It seems to be a part of the [issue](https://github.com/TeamNewPipe/NewPipe/issues/4979) I've created, I can add additional info there if you or admins want.

**Comment by agn-gpl** [comment] 2020-11-27 07:51
> I guess Google starts to forbid playing embedded age-restricted videos: https://9to5google.com/2020/09/22/youtube-age-restricted-videos/
> It seems to be a part of the [issue](https://github.com/TeamNewPipe/NewPipe/issues/4979) I've created, I can add additional info there if you or admins want.

It sounds bad. Many good videos on youtube become age-restricted for no reason, specailly for ASMR videos. 
Maybe an optional "youtuwbe log in" option is needed in order to watch those age-restricted videos on newpipe?

**Comment by Toshiba1127** [comment] 2020-12-16 11:13
This is why I still have an alternative app which still works and lets me download age-restricted videos

**Comment by rocketinventor** [comment] 2021-02-24 11:02
In build 0.20.10, this does not appear to be the case anymore.

@agn-gpl Are you still having issues with this?

**Comment by czarkoff** [comment] 2021-07-11 11:52
Sorry for reviving the ticket, but it started again. Here is an example: https://www.youtube.com/watch?v=F2skk6RFFos

**Comment by SmoothJaz** [comment] 2021-09-03 14:01
I can confirm the issue appears to be present on 21.9

**Comment by litetex** [comment] 2021-10-03 13:28
Statusupdate: v0.21.10

> Sorry for reviving the ticket, but it started again. Here is an example: https://www.youtube.com/watch?v=F2skk6RFFos

Video works as expected/is playable.

> https://www.youtube.com/watch?v=r4JWI4UDOrc

Video is not playable

**Comment by moriel5** [comment] 2022-04-11 21:04
I also seem to have this issue, and toggling the "age-restriction" time seems not to do anything (nor am I using any filtered DNS, since CloudFlare doesn't offer that over HTTPS).

I tried opening HISHE's "How Lord of The Rings Should Have Ended" (which for some odd reason is now marked as a "Age Restricted Video", something that it certainly wasn't a few years ago when I had last watched it) when I had run into this.

Link: https://www.youtube.com/watch?v=1yqVD0swvWU

**Comment by moriel5** [comment] 2022-04-11 23:37
It appears that a method may have been going to bypass this in the browser, could this be useful for NewPipe?

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass

**Comment by TiA4f8R** [comment] 2022-04-12 09:04
Duplicate of #8102. Note that only embeddable age-restricted videos will be viewable.

**Closed by TiA4f8R** 2022-04-12 09:04 UTC
Labels: bug
