### ISSUE TITLE
UI: Video List Empty Upon Clicking on Channel

### ISSUE THREAD

**Issue by memz13155n** [TeamNewPipe/NewPipe#9260] opened 2022-10-31 23:35 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Search for a channel
2. Click on channel
3. Videos not listed even though videos are supposed to be listed (I'm sure Mental Outlaw have at least one (1) video)

### Expected behavior

List videos under channel

### Actual behavior

Youtube Channel seen as Empty channel

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/98498676/199128916-1d5310c3-becb-480f-b291-8c159e297d7c.mp4

### Affected Android/Custom ROM version

Android 7.1.1

### Affected device model

T Mobile Revvl Plus C370A1

**Comment by ardumpl** [comment] 2022-10-31 23:37
If any one see this report, please mark this as duplicate of https://github.com/TeamNewPipe/NewPipe/issues/9223

**Closed** 2022-10-31 23:39 UTC
Labels: bug, needs triage
