### ISSUE TITLE
Feature request:. Export play list contents to plain text file

### ISSUE THREAD

**Issue by Gg31265** [TeamNewPipe/NewPipe#2258] opened 2019-03-31 23:48 UTC
First of all, thanks for newpipe, one of my most used apps for vids and especially music. Would it be possible to have an export to text (.txt) file for all playlists?

**Comment by justanidea** [comment] 2019-04-01 05:15
Yeah i would love having this feature too :)

**Comment by Echolon** [comment] 2019-04-26 23:11
Is there already something like a backup? I have to switch my phone :confused:

**Comment by gkeegan** [comment] 2019-04-27 01:58
You can backup your history, subscriptions, and playlists by going to Settings>Content>Export Database and save the file. Transfer it to somewhere it will be accessible on the new device. 

Then download Newpipe and your file you saved onto the new device and go to settings>content>import database and select the file.

Your stuff will be there now.

@Echolon

**Comment by github-userx** [comment] 2019-09-22 14:09
No update on this? I would love to see this being implemented so we can give youtube-dl a txt file as input to download an entire (local) playlist from newpipe.

**Comment by Isayso** [comment] 2019-09-23 17:59
I found that the exported file is a SQL lite database format. You can use sqlite tools windows to extract the playlists
sqlite3 -header -csv newpipe.db "select * from streams;" > test.csv

**Comment by Stypox** [comment] 2019-09-27 05:57
Duplicate of #1788

**Closed by Stypox** 2019-09-27 05:57 UTC
