### ISSUE TITLE
GPL license violation for this software

### ISSUE THREAD

**Issue by ikonyavuz** [TeamNewPipe/NewPipe#7953] opened 2022-02-26 22:47 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### What is/are your question(s)?

There are apps on the Google Play Store that use your software exactly or with minor modifications. and they do not even state that they were inspired by this software. They also get ad revenue from it. What can we do against them? I have notified Google separately for each of them. So what can we do?

### Additional information

<img alt="2022-02-27 01_45_38-MiniTube - Minimizer for Video Tube   Free Music - Google Play'de Uygulamalar" src="https://user-images.githubusercontent.com/44204999/155861410-900eae6c-2741-4a29-892c-0b0859c994f0.png" height=600 />
![2022-02-27 01_38_37-Greenshot](https://user-images.githubusercontent.com/44204999/155861411-4152c390-db1a-4f90-8225-b50cbf01a6d2.png)
<img alt="2022-02-27 01_40_34-NewPipe Video   Mp3 Downloader - Google Play'de Uygulamalar" src="https://user-images.githubusercontent.com/44204999/155861412-4b529563-3906-4fb6-ad75-21d797070c45.png" height=600 />
<img alt="2022-02-27 01_41_07-HBTube - Video Player - Free Background Music - Google Play'de Uygulamalar" src="https://user-images.githubusercontent.com/44204999/155861413-34876086-67b7-484b-ae10-c50cc6e3eb52.png" height=600 />
<img alt="2022-02-27 01_41_22-iTube Video Floating - Google Play'de Uygulamalar" src="https://user-images.githubusercontent.com/44204999/155861414-ee03607b-13a8-459f-857a-a8de21d242e0.png" height=600 />
<img alt="2022-02-27 01_41_53-Play Tube   Video Tube - Google Play'de Uygulamalar" src="https://user-images.githubusercontent.com/44204999/155861415-38e3a70a-8d89-4d75-aed1-622ad16cb84b.png" height=600 />
<img alt="2022-02-27 01_43_31-HD Video Player All Formats - Google Play'de Uygulamalar" src="https://user-images.githubusercontent.com/44204999/155861416-3d62576a-0949-4e48-a7b3-c74e508a2f47.png" height=600 />
<img alt="2022-02-27 01_45_25-MiniTube - Minimizer for Video Tube   Free Music - Google Play'de Uygulamalar" src="https://user-images.githubusercontent.com/44204999/155861417-6ea922e3-f21c-478a-ac76-7da32f07bfc2.png" height=600 />

**Comment by TiA4f8R** [comment] 2022-02-26 23:03
Duplicate of #539. Please search better next time for exisiting duplicates of issues.

You may see in it some answers to your questions.

If the copycats are not already mentioned in the issue, please add a comment with them (package ids (that's the `id` part of Google Play Store app URLs) and app names) in it.

Thank you!

**Closed by TiA4f8R** 2022-02-26 23:03 UTC
Labels: question
