### ISSUE TITLE
Play Button does not hide if playback is resumed externally (keyboard or bluetooth earpiece)

### ISSUE THREAD

**Issue by ktprograms** [TeamNewPipe/NewPipe#7340] opened 2021-11-01 03:05 UTC
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start playing a video
2. Pause the video (doesn't matter how it's done, can be with the pause button or externally)
3. Use either a keyboard's space button or a bluetooth earpiece to resume the playback.

### Actual behavior

The play button stays visible.

### Expected behavior

The play button should hide, like when you tap the button manually.

### Device info
Not applicable, happens on all the devices I've tested.

**Comment by mhmdanas** [comment] 2021-11-03 13:43
Duplicate of #3403.

**Closed by mhmdanas** 2021-11-03 13:43 UTC
Labels: bug, player
