### ISSUE TITLE
100+ Playlists Youtube

### ISSUE THREAD

**Issue by BaphometTechnology** [TeamNewPipe/NewPipe#4856] opened 2020-11-11 08:28 UTC
If you have playlists with over 100 count videos (YouTube) they stop loading at the 100th item limiting you to only 100 pieces of content from that list

**Comment by opusforlife2** [comment] 2020-11-11 08:45
Always fill the template here: https://github.com/TeamNewPipe/NewPipe/issues/new/choose

Duplicate of #4819.

**Closed by opusforlife2** 2020-11-11 08:45 UTC
