### ISSUE TITLE
Stopped NewPipe bugs out while another app is using full screen in foreground

### ISSUE THREAD

**Issue by JustAnotherSupporter** [TeamNewPipe/NewPipe#5989] opened 2021-04-02 12:14 UTC
The bug occurs repeatedly when using the app "magic earth" while gps is active just before/after voice input is given while having connected the phone to the car via bluetooth.
NewPipe is not used, is closed in the background, and is not running in the quick action bar. I have tried stopping the application via the app manager, but to no avail. Netguard is also running, but don't think it's operation is inteteffering.

the bug doesn't occur every time the voice service of the satnav is triggered. The bug doesn't seem to occur when the phone is not connected to Bluetooth.

The actionbar will sometimes show a NewPipe message with [unknown][unknown] when the bug is triggered.

The error log is the following:
`
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DK
* __Content Language:__ da-DK
* __App Language:__ da_DK
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.getIndex()' on a null object reference
	at org.schabi.newpipe.player.Player.onCompleted(Player.java:2144)
	at org.schabi.newpipe.player.Player.changeState(Player.java:1984)
	at org.schabi.newpipe.player.Player.onPlayerStateChanged(Player.java:1905)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$6(ExoPlayerImpl.java:1443)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$6$ExoPlayerImpl$PlaybackInfoUpdate(Unknown Source:0)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$b8AtGdawGxQCz-_rX1H1__vkxF4.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1498)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$100(ExoPlayerImpl.java:56)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:1440)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1328)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:956)
	at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:320)
	at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1402)
	at com.google.android.exoplayer2.DefaultControlDispatcher.dispatchPrepare(DefaultControlDispatcher.java:57)
	at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onPlay(MediaSessionConnector.java:1151)
	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onPlay(MediaSessionCompat.java:1614)
	at android.media.session.MediaSession$Callback.onMediaButtonEvent(MediaSession.java:928)
	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onMediaButtonEvent(MediaSessionCompat.java:1604)
	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1566)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>
`

**Comment by sauravrao637** [comment] 2021-04-02 19:19
I would love to try fixing this :)

**Comment by davidgro** [comment] 2021-04-30 20:09
This certainly seems to be associated with my car's Bluetooth, but I haven't determined if it's connection, disconnection, or Other. Note that I don't play music or anything in the car, just voice calls and/or Maps directions - and neither of those is needed to trigger this crash.
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.getIndex()' on a null object reference
	at org.schabi.newpipe.player.Player.onCompleted(Player.java:2144)
	at org.schabi.newpipe.player.Player.changeState(Player.java:1984)
	at org.schabi.newpipe.player.Player.onPlayerStateChanged(Player.java:1905)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$6(ExoPlayerImpl.java:1443)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$6$ExoPlayerImpl$PlaybackInfoUpdate(Unknown Source:0)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$b8AtGdawGxQCz-_rX1H1__vkxF4.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1498)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$100(ExoPlayerImpl.java:56)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:1440)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1328)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:956)
	at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:320)
	at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1402)
	at com.google.android.exoplayer2.DefaultControlDispatcher.dispatchPrepare(DefaultControlDispatcher.java:57)
	at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onPlay(MediaSessionConnector.java:1151)
	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onPlay(MediaSessionCompat.java:1614)
	at android.media.session.MediaSession$Callback.onMediaButtonEvent(MediaSession.java:779)
	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onMediaButtonEvent(MediaSessionCompat.java:1604)
	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1355)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

```
</details>
<hr>

**Comment by mhmdanas** [comment] 2021-06-04 21:35
Duplicate of #6233.

**Closed by mhmdanas** 2021-06-04 21:35 UTC
