### ISSUE TITLE
Add download to menu on long-press

### ISSUE THREAD

**Issue by rancidfrog** [TeamNewPipe/NewPipe#4595] opened 2020-10-22 09:53 UTC
Current menu:
![](https://i.imgur.com/d7qLjKJ.jpg)

To download user must 1. Share 2. Select Newpipe 3. Select download

Adding one more line to menu to download should not be an issue

**Comment by opusforlife2** [comment] 2020-10-22 10:02
You didn't use the issue template here https://github.com/TeamNewPipe/NewPipe/issues/new/choose. You didn't check for duplicates.

Duplicate of #2171.

**Closed by opusforlife2** 2020-10-22 10:02 UTC

**Comment by rancidfrog** [comment] 2020-10-22 10:09
Sorry for that.
I did search but didn't notice this issue

**Comment by rancidfrog** [comment] 2020-10-22 10:10
In regards to templates,
Does not appear in app.
It should appear automatically

**Comment by opusforlife2** [comment] 2020-10-22 10:12
You should open a bug for your app also.

**Comment by rancidfrog** [comment] 2020-10-22 10:18
Also for a simple adding new option, it should have been looked at sooner,
#2171  opened this issue on 2 Mar 2019
🙉🙊🙈, which may be why I did not come across it
see here - https://github.com/TeamNewPipe/NewPipe/issues/2171#issuecomment-703243142
> as you can see many duplicates of this issue were closed, so yes, this is a highly requested feature ;-)
I would be ok merging this before the bigger work is ready, mostly because I am not sure if the bigger work will ever be suitable for everyone, and it will surely take some long time. So in my opinion you can go for it, thank you :-D
The implementation should be rather simple, you can take a look at the code for the "Download" action in the open/share menu. 

Not to criticize, just mentioning it because it is a simple addition that has been requested many times, and there is no obections to adding it.

**Comment by opusforlife2** [comment] 2020-10-22 10:20
As you can see, a user was interested in working on the feature and was given the go ahead. We can only wait now.
