### ISSUE TITLE
Google Takeout 'subscriptions.json' file is not fully parsed.

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#6290] opened 2021-05-14 10:36 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Import subscriptions.json file from takeout.
2. Backup subscriptions from NewPipe.
3. Compare both json files.

### Actual behaviour

Only 157 of 237 subscriptions is loaded.

### Expected behavior

All 237 subscriptions need to be loaded.

### Screenshots/Screen recordings

1. Feed loading screenshot
![parsing_error](https://user-images.githubusercontent.com/50160188/118258101-2f510180-b4cf-11eb-8b3e-af7eaa3b5b6c.PNG)

2. Comparision of subscriptions.json and newPipe's subscription backup. (I used this https://jsonbeautifier.org/ website)
![new](https://user-images.githubusercontent.com/50160188/118258348-750dca00-b4cf-11eb-8c18-8b1860f29f88.png)

3. Json files.
[subscriptions.zip](https://github.com/TeamNewPipe/NewPipe/files/6478200/subscriptions.zip)

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by TiA4f8R** [comment] 2021-05-14 10:46
> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

Duplicate of #5806... Please search better next time!

**Closed by TiA4f8R** 2021-05-14 10:46 UTC
Labels: bug
