### ISSUE TITLE
Bug: NewPipe is using 2 different languages in some areas

### ISSUE THREAD

**Issue by haistakaavittukaikkisaatana** [TeamNewPipe/NewPipe#2718] opened 2019-10-11 15:07 UTC
To repro:

1. Try to search something
2. Now scroll down
3. Pay attention to time codes when videos are uploaded
4. In my case it shows "2 years ago - in english" and "4 kuukautta sitten - in finnish"
5. And yes, my content language and country are both set to US

![Screenshot_20191011-180010](https://user-images.githubusercontent.com/54250399/66662655-e7625c80-ec51-11e9-8935-9e96e7702ec3.jpg)

**Comment by haistakaavittukaikkisaatana** [comment] 2019-10-11 18:13
Also Trending tab has all time codes in Finnish, what is weird is that it shows number of views in English but time of upload in Finnish.

**Comment by haistakaavittukaikkisaatana** [comment] 2019-10-12 19:00
Am I really the only one with this issue? My phone has only one language set (en-US), and default Youtube app doesnt have this issue.

**Comment by gkeegan** [comment] 2019-10-12 19:04
There's been language issues with Newpipe for a long time afaik.

**Comment by haistakaavittukaikkisaatana** [comment] 2019-10-12 19:05
@gkeegan

Gotcha, thank you for your reply.

**Comment by Stypox** [comment] 2019-10-15 20:33
Duplicate of #578

**Comment by Stypox** [comment] 2019-10-15 20:33
Other issues related to language are: #578 #1013 #1130 #1132 #1215 #1588

**Closed by Stypox** 2019-10-15 20:33 UTC
