### ISSUE TITLE
Directly go to "Play Queue" screen

### ISSUE THREAD

**Issue by nikhilCad** [TeamNewPipe/NewPipe#8130] opened 2022-04-02 12:58 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

<img alt="Screenshot_20220402-182746" src="https://user-images.githubusercontent.com/47214394/161384386-291126ec-25e6-46eb-83b6-2c51fa51a649.png" height=600 />

Look at this Play Queue screen. Currently, to reach here, I have to click Background Play in my playlist, then click the notification to reach here. It will be nice if there is a direct button to reach here

### Why do you want this feature?

Because this screen acts as an exceptional music streamer. No video is loaded, and I can easily switch between songs without opening any video

### Additional information

None

**Comment by SameenAhnaf** [comment] 2022-04-02 13:00
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3515

**Comment by nikhilCad** [comment] 2022-04-02 13:07
Indeed a duplicate, I did run a search of the word "Play Queue" and didn't find anything

**Closed** 2022-04-02 13:07 UTC
Labels: enhancement
