### ISSUE TITLE
[Feature Request]Show Playlists inside a YouTube channel

### ISSUE THREAD

**Issue by sebma** [TeamNewPipe/NewPipe#3209] opened 2020-03-10 16:18 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi,

Can you please add the ability to show the playlists inside a YouTube channel ?

At the time being, when one opens a YouTube channel url ([example URL](https://www.youtube.com/channel/UCNb2H0PwlajFSmfjgfDdKvA/?disable_polymer=1)) on the smartphone and shares it to NewPipe, there is actually no way to show the playlists ([example playlists](https://www.youtube.com/channel/UCNb2H0PwlajFSmfjgfDdKvA/playlists?disable_polymer=1)) of that selected channel.

**Comment by wb9688** [comment] 2020-03-10 16:24
Duplicate of #2414. I'm already working on it in #3201.

**Closed by wb9688** 2020-03-10 16:24 UTC
Labels: duplicate, enhancement, pr open, requires extractor change
