### ISSUE TITLE
The items and symbols of settings list in Arabic version should be aligned to the right.

### ISSUE THREAD

**Issue by ahmad-abdelbaset** [TeamNewPipe/NewPipe#4711] opened 2020-10-29 19:11 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Change the system language to Arabic, run the application and then:
1. Go to 'القائمة'
2. Press on 'الإعدادات'

### Actual behaviour

The items and symbols are aligned to left, but we are reading Arabic from right to left.

### Expected behavior

The items and symbols in Arabic should be aligned to the right!

### Screenshots/Screen recordings

![image](https://user-images.githubusercontent.com/27960593/97617821-ed76d700-1a26-11eb-9fe5-224aa03f24c8.png)

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: All android devices

**Comment by opusforlife2** [comment] 2020-10-30 14:32
Duplicate of #3882.

**Closed by opusforlife2** 2020-10-30 14:32 UTC
Labels: bug
