### ISSUE TITLE
Not able to watch the videos

### ISSUE THREAD

**Issue by Mishalabdullah** [TeamNewPipe/NewPipe#8804] opened 2022-08-15 15:59 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Go to "All Channel Group"
2. Press on any video 

### Expected behavior

Normally it should start playing the video, but its not. The error is also happening on my mother's phone too.

### Actual behavior

 The video after clicking it will load for a while then it stops and shows "Sorry something went wrong".
All the thumbnails are being loaded, but only the videos are unplayable. If I search for a video/topic then also, the videos are unplayable.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/85678545/184670648-4a0c97ff-b068-4c34-bd7b-80e868919805.mp4

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=c0ArprJZ-0E
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.23.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 9

### Affected device model

Lenovo K10 note pro

**Comment by TDavLinguist** [comment] 2022-08-15 16:54
You're not using the latest version. The bug you describe has already been fixed in 0..23.1, released 2 days ago. Please download and install the newest release and you should be fine. Please close the topic once you succeed.

**Comment by joe733** [comment] 2022-08-15 18:26
> You're not using the latest version. The bug you describe has already been fixed in 0..23.2, released 2 days ago. Please download and install the newest release and you should be fine. Please close the topic once you succeed.

Looks like update has not been pushed to F-Droid yet.

**Comment by AudricV** [comment] 2022-08-15 19:02
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #8760. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2022-08-15 19:02 UTC
Labels: bug, needs triage

**Comment by TDavLinguist** [comment] 2022-08-16 01:59
> > You're not using the latest version. The bug you describe has already been fixed in 0..23.2, released 2 days ago. Please download and install the newest release and you should be fine. Please close the topic once you succeed.
> 
> Looks like update has not been pushed to F-Droid yet.

If you want to use F-Droid, please add their custom repository. If even that isn't fast enough for the update, I suggest you keep an eye on the release section whenever you encounter a big bug like this. I personally don't even update NewPipe with F-Droid anymore, as I find the GitHub updates to be faster and more reliable. Hope this helps!

**Comment by Mishalabdullah** [comment] 2022-08-16 10:16
Thank you
