### ISSUE TITLE
Requesting changes to exporting database

### ISSUE THREAD

**Issue by IamJithendra** [TeamNewPipe/NewPipe#1493] opened 2018-06-17 17:23 UTC
* On back the database the default content country is not saved 

* Automatically backup the database within a limited period, say every week

* Backup the data to NewPipe downloads folder 

* And on importing automatically open the NewPipe downloads folder

And the overriding of existing database will be helpful because the too many files will be confused which one is the latest 
And if you can change the format of database file from zip to JSON

**Comment by theScrabi** [comment] 2018-06-18 08:52
At @IamJithendra please split your request into smaller ones, and check if they already exist.

> - On Back The Database the Default Content Country Not Saved

This is an issue that we have on multiple places, but i think it's been taken care of.

> - Automatically Back up The Database Within A Limited Period Say Every Week

is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1163

> - Backup The Data To NewPipe Downloads Folder

I think that the database does not belong there :D, however I thought maybe the export can be done via share menu.

> - And On Importing Automatically Open The New pipe Downloads Folder

Maybe we should talk about setting a common folder for inport/export :)

> And If You Can Change The Format Of Database File From Zip To JSON

Our database is a SQLite, converting it to JSON was kind of pain.

> And The Overriding Of Existing Database Will Be Helpful Because The Too Many Files Will Be Confused which One Is The Latest

I'm not sure if I understand this correctly, but the internal database file already gets override when you import one.

**Closed as completed** 2021-08-26 19:39 UTC
Labels: feature request
