### ISSUE TITLE
Fast-forward/rewind 10 seconds in background player

### ISSUE THREAD

**Issue by TheLastGimbus** [TeamNewPipe/NewPipe#3409] opened 2020-04-10 08:25 UTC
It would be nice if we had "fast-forward/rewind 10 seconds" buttons in background player. Buttons in notification do that, but they are kinda confusing, and I don't "know" what they will do when I see them. It would be nice to add them to "Background player activity" - with some "10" in icon, so that user knows "okay, this will rewind 10 seconds".

If someone could give me some directions on how to commit to this repo - I could totally do that.

**Comment by Stypox** [comment] 2020-04-10 10:16
Duplicate of #2722

**Closed by Stypox** 2020-04-10 10:16 UTC
