### ISSUE TITLE
Newpipe download subtitle (.srt) without line breaks

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#2891] opened 2019-12-25 18:03 UTC
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [Not applicable] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Newpipe download subtitle (.srt) without line breaks which makes it hard to read. It's not normal. Youtube supports line breaks and youtube-dl can download subtitle with line breaks

I use a video by 8 bit guy as an example https://www.youtube.com/watch?v=kxx2F4ffmeE

Newpipe:
```
0
00:00:00,070 --> 00:00:17,109
OK, here it is. I’ve received about a thousandemails from people asking if I was aware of

1
00:00:17,109 --> 00:00:21,609
this product and if was going to review it.And, I think that’s like asking if the sun

2
00:00:21,609 --> 00:00:24,929
is going to rise tomorrow, of course I’mgoing to review it. So, let’s go ahead and
```
I tested other softwares which support downloading subtitles and they downloaded sub with line breaks as expected
Youtube-dl:
```
00:00:00.070 --> 00:00:17.109
OK, here it is. I’ve received about a thousand
emails from people asking if I was aware of

00:00:17.109 --> 00:00:21.609
this product and if was going to review it.
And, I think that’s like asking if the sun

00:00:21.609 --> 00:00:24.929
is going to rise tomorrow, of course I’m
going to review it. So, let’s go ahead and
```

Tubemate:
```
<SYNC Start=70><P class='en-US'>OK, here it is. I’ve received about a thousand
emails from people asking if I was aware of
<SYNC Start=17109><P class='en-US'>&nbsp;
<SYNC Start=17109><P class='en-US'>this product and if was going to review it.
And, I think that’s like asking if the sun
<SYNC Start=21609><P class='en-US'>&nbsp;
<SYNC Start=21609><P class='en-US'>is going to rise tomorrow, of course I’m
going to review it. So, let’s go ahead and
<SYNC Start=24929><P class='en-US'>&nbsp;
<SYNC Start=24929><P class='en-US'>get started.
```

Attachment of sub files
[TheC64 Maxi - Full sized C64 review and disassembly.zip](https://github.com/TeamNewPipe/NewPipe/files/4000717/Newpipe.TheC64.Maxi.-.Full.sized.C64.review.and.disassembly.zip)

**Comment by kapodamy** [comment] 2020-01-08 16:56
use notepad++ or similar, the default windows notepad doesnt support that kind of line break

**Comment by lyndmi** [comment] 2020-01-12 20:01
@kapodamy What are you talking about??? This has nothing to do with Notepad or Notepad++ at all
NewPipe downloads subtitles without line breaks but the Player and Youtube app shows subtitles just fine

Try download subtitle by yourself and open the .srt file in Xplore app or Notepad++ and you will see the problem

**Comment by lyndmi** [comment] 2020-01-12 20:11
Edited issue

**Comment by kapodamy** [comment] 2020-01-14 01:06
i never looked you files and now see youtube made changes. The CRLF was replaced with `</br>` html tag.

**Comment by lyndmi** [comment] 2020-01-14 21:19
Was debugging it myself to find out why this happen in TtmlConverter (even though i don't have much knowledge in Android development) but nice you already found out. Now i'll wait until PR merged, finally.

**Comment by winteum** [comment] 2020-04-05 13:37
Still not fixed!
Can't read the youtube subtitles with that line break.

**Comment by Stypox** [comment] 2020-04-06 18:24
@kapodamy

**Comment by winteum** [comment] 2020-04-06 18:26
Every Google generated subtitle appears as two lines instead of one. But
the first line is the previous sentence.

**Comment by kapodamy** [comment] 2020-04-07 15:23
@winteum WebVTT != SubRip
![image](https://user-images.githubusercontent.com/16857233/78686919-f86eec00-78c9-11ea-8802-b5f94d63ac5e.PNG)
@Stypox  nothing to fix

**Comment by winteum** [comment] 2020-04-07 16:04
Please watch a YouTube video with English auto generated subtitles and
you'll understand what we mean. Thanks

**Comment by TobiGr** [comment] 2020-04-09 20:02
@winteum Can you please test this apk below and tell us if the problem is solved? Thank you :)

[NewPipe_srtseqdrop-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4458383/NewPipe_srtseqdrop-debug.apk.zip)

**Comment by winteum** [comment] 2020-04-12 10:00
Nope. It's the same behavior.

**Comment by opusforlife2** [comment] 2020-09-13 10:58
@kapodamy The account is deleted. Do you want to close your PR now since there's basically no tester available?

**Comment by kapodamy** [comment] 2020-09-13 14:47
sure

**Comment by opusforlife2** [comment] 2020-09-13 15:08
Alright. 👍

**Closed by opusforlife2** 2020-09-13 15:08 UTC
Labels: question, youtube
