### ISSUE TITLE
offline update history for subscriptions

### ISSUE THREAD

**Issue by anpic** [TeamNewPipe/NewPipe#3585] opened 2020-05-14 09:52 UTC
#### Describe the feature you want

please add options  to store update history for subscriptions
options such as
checkbox Automatic updates
checkbox Update on startup
textbox Automatic update interval (in seconds or minutes)
textbox Update from date (in seconds or minutes, 0 - no limit)
textbox Update store limit (0 - no limit)
textbox Clear store interval (in seconds or minutes, 0 - never)
textbox Auto cleanup watched (in seconds or minutes, 0 - never)
textbox Auto cleanup unwatched (in seconds or minutes, 0 - never)
checkbox Keep starred items

#### Is your feature request related to a problem? Please describe it

no

#### How will you/everyone benefit from this feature?

use Youtube as RSS

**Comment by Stypox** [comment] 2020-05-14 10:17
Duplicate of #3329

**Closed by Stypox** 2020-05-14 10:17 UTC
Labels: enhancement

**Comment by anpic** [comment] 2020-05-14 10:21
> Duplicate of #3329

I have wider suggestions :)

**Comment by B0pol** [comment] 2020-05-14 16:53
Then make multiple tickets. If you have read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md) (you should've), it says

> Please only add one issue at a time. Do not put multiple issues into one thread.
