### ISSUE TITLE
Youtube vids - does not show replys to comments (VERY important)

### ISSUE THREAD

**Issue by succeedmr123** [TeamNewPipe/NewPipe#6649] opened 2021-07-12 09:28 UTC
I vouch am not lazy. Will tell exactly what it is and why it is important to fix.

### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

It just do not go deeper than basic comments, and you can not look for useful replies to the comments. Therefore, unusable for following some useful comments+replies expressed under the video

### Expected behavior

To show all comments+replies

### Device info

 - Android version/Custom ROM version: 12, and 5.0.1 (tested on two separate devices as true)
 - Device model: irrelevant - same effect

**Comment by TiA4f8R** [comment] 2021-07-12 10:56
> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.

Duplicate of #2277. Please search (better) for existing issues the next time you want to open an issue. Thank you.

**Closed** 2021-07-12 10:56 UTC
Labels: bug
