### ISSUE TITLE
SEARCH ENGINE on subscription list

### ISSUE THREAD

**Issue by NewNewPipe** [TeamNewPipe/NewPipe#7787] opened 2022-02-03 16:45 UTC
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
I would like to propose that a search engine be used on the subscription list for the channel names in the list, so that each letter entered in the search engine takes you closer and closer to the name of the channel you are looking for in the list. This would make it much easier to find a channel in a list containing several hundred channel subscriptions in the app

#### Why do you want this feature?
Great convenience / streamlining the use of the app with a large subscription list.

**Comment by SameenAhnaf** [comment] 2022-02-03 18:21
Duplicate of #4795. Also, make sure to check all the instructions on checklist.

**Comment by litetex** [comment] 2022-02-03 20:15
``This checklist is COMPULSORY. The first box has been checked for you to show you how it is done.``

**Closed by litetex** 2022-02-03 20:15 UTC
Labels: enhancement, template-ignored, duplicate
