### ISSUE TITLE
Per subscription permanent content filter 

### ISSUE THREAD

**Issue by PeuDenPau** [TeamNewPipe/NewPipe#6877] opened 2021-08-08 14:57 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The idea is to allow on a chanel page, choose which type of videos get from that chanel and made that decission persistent on the news tab. So, you can choose from a chanel which videos to get, for example with regex or string comparation and only get or hide those, or by lenght, only show or hide videos with minimum/maximum X lenght.  

#### Is your feature request related to a problem? Please describe it

This would help with channels that upload different content and you are only interested in one type, or like podcast channels that upload a chapter a week but each uploads clips of  previous podcast. That feature would clean the feed and get rid of all the flood you don't want to see. And that would be another feature no client of YT (nor youtube itself) had.

#### How will you/everyone benefit from this feature?

We will have a cleaner feed and a more pleasant browsing.

**Comment by SameenAhnaf** [comment] 2022-02-25 18:38
@mhmdanas Duplicate of #3827

**Closed** 2022-03-23 19:31 UTC
Labels: enhancement, feed
