### ISSUE TITLE
[Feature Request] Black list feature for channels

### ISSUE THREAD

**Issue by ndr48291** [TeamNewPipe/NewPipe#4187] opened 2020-08-25 15:52 UTC
#### Describe the feature you want

Black list feature for channels. So that we can hide their videos and dont see them on trending page also.

**Comment by opusforlife2** [comment] 2020-08-25 17:03
_Always_ search for your issue before opening. Duplicate of #1815.

**Closed by opusforlife2** 2020-08-25 17:03 UTC
