### ISSUE TITLE
Watched videos will only be removed after the What's New page has been reloaded

### ISSUE THREAD

**Issue by Fassi96** [TeamNewPipe/NewPipe#8611] opened 2022-07-11 16:58 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

Go to Subscriptions. 
Go to All. 
Mark videos as seen.

### Expected behavior

The videos that have been watched will be removed directly from the list.

### Actual behavior

The videos that have already been viewed will only be removed after the page has been reloaded.

### Screenshots/Screen recordings

https://netherghast-my.sharepoint.com/:f:/g/personal/matthias_hanisch_netherghast_de/EpUSz9fLTHxBhFhPeTFej8cBO_q9YXc62pNeez0tAIQTdg?e=dMa9O3

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy Note 20 5G Ultra SM-N986B/DS

**Comment by litetex** [comment] 2022-07-16 13:07
Duplicate of #7545

**Closed by litetex** 2022-07-16 13:07 UTC
Labels: bug, feed
