### ISSUE TITLE
Enqueue UI app crash

### ISSUE THREAD

**Issue by erikeah** [TeamNewPipe/NewPipe#5470] opened 2021-01-21 12:36 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

(You should have auto play next video enabled)

1. Play in the background anything.
2. In the video recomendation section of the content that you are already playing long press any content to show the menu.
3. Wait that the content that you have already played has ended while the menu is still displayed.
4. When the next content is being played, press enqueue.
5. Crash

### Actual behaviour

The app crash and close, after a guru meditation windows shows up.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.widget.Toast.makeText(Toast.java:315)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnBackgroundPlayer(NavigationHelper.java:198)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnBackgroundPlayer(NavigationHelper.java:191)
	at org.schabi.newpipe.util.StreamDialogEntry.lambda$static$0(StreamDialogEntry.java:35)
	at org.schabi.newpipe.util.-$$Lambda$StreamDialogEntry$62aigyTTdqr26LrXhhJwc-oYHBk.onClick(Unknown Source:0)
	at org.schabi.newpipe.util.StreamDialogEntry.clickOn(StreamDialogEntry.java:132)
	at org.schabi.newpipe.fragments.list.BaseListFragment.lambda$showStreamDialog$1(BaseListFragment.java:365)
	at org.schabi.newpipe.fragments.list.BaseListFragment.lambda$showStreamDialog$1$BaseListFragment(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.-$$Lambda$BaseListFragment$PrX9_25MbpqEQd6DTy65QLAhdlQ.onClick(Unknown Source:4)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1222)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1196)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3207)
	at android.widget.AbsListView$3.run(AbsListView.java:4125)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7561)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: MIUI 12/Android 10
 - Device model: Xiaomi Note 9 (merlin)

**Comment by vkay94** [comment] 2021-01-21 18:42
Thank you for reporting this bug ;) I checked and could reproduce it. In fact, this crash is not limited to the enqueue action but also happens on choosing "Share" for example. 

The easiest way to fix it is by closing the menu dialog whenever the stream changed (= related streams change).

**Comment by SumatraPeter** [comment] 2021-07-25 01:55
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux Android 5.0.1 - 21
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.widget.Toast.makeText(Toast.java:294)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnVideoPlayer(NavigationHelper.java:168)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnVideoPlayer(NavigationHelper.java:161)
	at org.schabi.newpipe.util.StreamDialogEntry.lambda$static$1(StreamDialogEntry.java:51)
	at org.schabi.newpipe.util.-$$Lambda$StreamDialogEntry$P8nCsNt_qHShgSaccFUg1FFUTIE.onClick(lambda)
	at org.schabi.newpipe.util.StreamDialogEntry.clickOn(StreamDialogEntry.java:153)
	at org.schabi.newpipe.fragments.list.BaseListFragment.lambda$showStreamDialog$1(BaseListFragment.java:384)
	at org.schabi.newpipe.fragments.list.BaseListFragment.lambda$showStreamDialog$1$BaseListFragment(BaseListFragment.java)
	at org.schabi.newpipe.fragments.list.-$$Lambda$BaseListFragment$PrX9_25MbpqEQd6DTy65QLAhdlQ.onClick(lambda)
	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
	at android.widget.AdapterView.performItemClick(AdapterView.java:300)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
	at android.widget.AbsListView$3.run(AbsListView.java:3833)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5306)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```
</details>
<hr>
I just got the above crash report. Not quite sure exactly but IIRC was indeed trying to enqueue something. It's the same issue and I don't need to open a new report, right?

**Comment by TacoTheDank** [comment] 2022-03-29 14:32
Hello, does this issue still occur on the latest version?

**Comment by erikeah** [comment] 2022-03-29 20:17
Yes, It's still occurring.

**Comment by TacoTheDank** [comment] 2022-03-30 14:35
@erikeah Could you post a new crashlog please (of the issue occurring on the latest version)? The current crashlog is no longer useful considering there have been many changes since then.

**Closed** 2022-04-16 00:12 UTC
Labels: bug, template-ignored, waiting-for-author
