### ISSUE TITLE
Play All Starting From the middle of a Play List

### ISSUE THREAD

**Issue by Ryu945** [TeamNewPipe/NewPipe#6947] opened 2021-08-20 16:14 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The ability to start play list from the middle of a play list.  

#### Is your feature request related to a problem? Please describe it

Right now, it is only possible to start a play list from the very beginning.  The auto-play to the next song only works when started from the beginning.   This means that currently, you must manually start every single song in the play list if you wish to start a play list anywhere except the beginning of the playlist.

#### How will you/everyone benefit from this feature?

Some music play list can be many hours long and take several days to listen through.   You don't want to listen to the same songs over an over again because you can only start the play list from the beginning.   You want to be able to listen to part of the play list over the course of many days or more.

**Comment by SameenAhnaf** [comment] 2021-08-20 16:32
Duplicate of#4805.

**Closed** 2021-08-20 18:22 UTC
Labels: enhancement
