### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by weole** [TeamNewPipe/NewPipe#11358] opened 2024-07-28 14:07 UTC
{"user_action":"requested feed","request":"","content_language":"en-US","content_country":"US","app_language":"en_US","service":"none","package":"org.schabi.newpipe","version":"0.27.2","os":"Linux motorola/guamna_retail/guamna:11/RZA31.Q2-146-14R2/e8dbb:user/release-keys 11 - 30","time":"2024-07-28 10:07","exceptions":["org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UC52TIYLWZJmFka4GRobmOrw\n\tat org.schabi.newpipe.local.feed.service.FeedLoadManager$DatabaseConsumer.accept$lambda$1(FeedLoadManager.kt:285)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadManager$DatabaseConsumer.$r8$lambda$nP61ZaEPy7GNixUaWP6wyXDQaWo(FeedLoadManager.kt:0)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadManager$DatabaseConsumer$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)\n\tat androidx.room.RoomDatabase.runInTransaction(RoomDatabase.kt:585)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadManager$DatabaseConsumer.accept(FeedLoadManager.kt:271)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadManager$DatabaseConsumer.accept(FeedLoadManager.kt:268)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onNext(FlowableBuffer.java:124)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:403)\n\tat io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:178)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)\n\tat io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:923)\nCaused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: Failed to find pattern \"([\\d]+([\\.,][\\d]+)?)\" inside of \"@sniss\"\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:75)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:60)\n\tat org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:49)\n\tat org.schabi.newpipe.extractor.utils.Utils.mixedNumberWordToLong(Utils.java:93)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getSubscriberCountFromPageChannelHeader(YoutubeChannelExtractor.java:303)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getSubscriberCount(YoutubeChannelExtractor.java:248)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:86)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:53)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:126)\n\tat org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$BOLWstv98dC8pFAG_uir5gPXYwY(ExtractorHelper.java:0)\n\tat org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda13.call(R8$$SyntheticClass:0)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleOnErrorReturn.subscribeActual(SingleOnErrorReturn.java:38)\n\tat io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)\n\tat io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadManager.loadStreams(FeedLoadManager.kt:179)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadManager.access$loadStreams(FeedLoadManager.kt:33)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadManager$startLoading$7.apply(FeedLoadManager.kt:113)\n\tat org.schabi.newpipe.local.feed.service.FeedLoadManager$startLoading$7.apply(FeedLoadManager.kt:112)\n\tat io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:116)\n\tat io.reactivex.rxjava3.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:132)\n\tat io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:399)\n\t... 7 more\n"],"user_comment":""}

**Comment by AudricV** [comment] 2024-07-28 15:53
Duplicate of #11353. Please follow the issue templates in your future issues. Thank you.

**Closed by AudricV** 2024-07-28 15:53 UTC
