### ISSUE TITLE
Sorry is already solved

### ISSUE THREAD

**Issue by weirdmagicguy** [TeamNewPipe/NewPipe#7681] opened 2022-01-22 16:40 UTC
It would be great to hve the option to change the first site from trends to Whats New because that is the Site the most people use the most right?

**Comment by SameenAhnaf** [comment] 2022-01-22 17:21
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5701

**Closed** 2022-01-22 18:23 UTC
