### ISSUE TITLE
Newpipe v0.18.5 not load youtube channel :(

### ISSUE THREAD

**Issue by Domiuns** [TeamNewPipe/NewPipe#3148] opened 2020-02-27 13:17 UTC
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi, the new version of newpipe not load channel videos (i have all video channel on screening but when i click to open it newpipe is loading for unlimited time) only comment section load, I think is a problem with new extractor. I have android 4.4
![IMG_20200227_141004](https://user-images.githubusercontent.com/53193434/75448314-414a9100-596b-11ea-8919-11874e06b689.JPG)
![IMG_20200227_140728](https://user-images.githubusercontent.com/53193434/75448429-7b1b9780-596b-11ea-9f53-17da954c8b13.JPG)

**Comment by Stypox** [comment] 2020-02-27 14:32
Are you sure this only happens when opening videos from a channel, and it happens every time? I followed all the steps you provided but I couldn't reproduce this issue unfortunately.
@wb9688

**Comment by wb9688** [comment] 2020-02-27 14:57
@Stypox: There is, in NewPipeExtractor at least (not sure about NewPipe), no difference between opening a video from a channel or otherwise. I can't reproduce it either

@Domiuns: What countries/languages have you set in Settings->Content? Are you using a proxy or VPN? If not, in what country are you located?

**Comment by Domiuns** [comment] 2020-02-27 15:06
I have tried and it happens with any video, even if a video in the trend I managed to upload it. I am Italian and I have the feed Italy

**Comment by Domiuns** [comment] 2020-02-27 15:23
I have finnaly load an video for test all. Buth other video not load.
This is worked
![IMG_20200227_161614](https://user-images.githubusercontent.com/53193434/75457385-b377a180-597c-11ea-9c45-5d79b9bd4e2b.JPG)
![IMG_20200227_161625](https://user-images.githubusercontent.com/53193434/75457399-b7a3bf00-597c-11ea-932b-77707cfde971.JPG)
![IMG_20200227_161647](https://user-images.githubusercontent.com/53193434/75457415-bbcfdc80-597c-11ea-900b-27d910d61c98.JPG)
With 0.18.4 i not have problem. (I not sue vpn)

**Comment by Domiuns** [comment] 2020-02-29 18:00
I have Sniff traffic and i not receive nothing from some youtube channel.

work video:
GET /watch?v=Jx5JW2bouBY HTTP/1.1
Accept-Language: en-GB, en;q=0.9
User-Agent: Mozilla/5.0 (Android 8.1.0; Mobile; rv:62.0) Gecko/62.0 Firefox/62.0
Host: m.youtube.com
Connection: Keep-Alive
Accept-Encoding: gzip

and i receive this:
GET /yts/jsbin/player_ias-vflsFV4r3/en_GB/base.js HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept-Language: en-GB, en;q=0.9
Host: youtube.com
Connection: Keep-Alive
Accept-Encoding: gzip

another work:
GET /watch?v=_6n2ZydohKk HTTP/1.1
Accept-Language: en-GB, en;q=0.9
User-Agent: Mozilla/5.0 (Android 8.1.0; Mobile; rv:62.0) Gecko/62.0 Firefox/62.0
Host: m.youtube.com
Connection: Keep-Alive
Accept-Encoding: gzip

receive this:
GET /yts/jsbin/player_ias-vflsFV4r3/en_GB/base.js HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept-Language: en-GB, en;q=0.9
Host: youtube.com
Connection: Keep-Alive
Accept-Encoding: gzip

Another work link YouTube:
https://www.youtube.com/watch?v=EkvRidaJ_DE

Example link for not work video:
https://m.youtube.com/watch?v=Ddev2WzSYJE

https://m.youtube.com/watch?v=mPVDGOVjRQ0

https://m.youtube.com/watch?v=G_e6lVLNyWo

**Comment by wb9688** [comment] 2020-02-29 18:12
@Domiuns: Could you try if you also have the issue in the following apk? If so, the bug is already fixed in the next release. [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4270686/app-debug.apk.zip)

**Comment by Domiuns** [comment] 2020-02-29 21:25
@wb9688 i have strange error when install apk. 
![IMG_20200229_222030](https://user-images.githubusercontent.com/53193434/75615278-09497680-5b42-11ea-9efb-7168f80e2bb5.JPG)
I have try to decompile and try to fix minim SDK for make a test if I set android 4.0 fix error. But i have find this error when recompile it

`resvaluespublic.xml:45: error: Public symbol array/app_language_code declared here is not defined.
resvaluespublic.xml:46: error: Public symbol array/app_language_name declared here is not defined.
resvaluespublic.xml:47: error: Public symbol array/audio_format_description_list declared here is not defined.
resvaluespublic.xml:48: error: Public symbol array/audio_format_values_list declared here is not defined.
resvaluespublic.xml:49: error: Public symbol array/country_codes declared here is not defined.
resvaluespublic.xml:50: error: Public symbol array/country_names declared here is not defined.
resvaluespublic.xml:51: error: Public symbol array/downloads_maximum_retry_list declared here is not defined.
resvaluespublic.xml:52: error: Public symbol array/language_codes declared here is not defined.
resvaluespublic.xml:53: error: Public symbol array/language_names declared here is not defined.
resvaluespublic.xml:54: error: Public symbol array/limit_data_usage_description_list declared here is not defined.
resvaluespublic.xml:55: error: Public symbol array/limit_data_usage_values_list declared here is not defined.
resvaluespublic.xml:56: error: Public symbol array/list_view_mode_description declared here is not defined.
resvaluespublic.xml:57: error: Public symbol array/list_view_mode_values declared here is not defined.
resvaluespublic.xml:58: error: Public symbol array/minimize_on_exit_action_description declared here is not defined.
resvaluespublic.xml:59: error: Public symbol array/minimize_on_exit_action_key declared here is not defined.
resvaluespublic.xml:60: error: Public symbol array/preferred_open_action_description_list declared here is not defined.
resvaluespublic.xml:61: error: Public symbol array/preferred_open_action_values_list declared here is not defined.
resvaluespublic.xml:62: error: Public symbol array/resolution_list_description declared here is not defined.
resvaluespublic.xml:63: error: Public symbol array/resolution_list_values declared here is not defined.
resvaluespublic.xml:64: error: Public symbol array/seek_duration_description declared here is not defined.
resvaluespublic.xml:65: error: Public symbol array/seek_duration_value declared here is not defined.
resvaluespublic.xml:66: error: Public symbol array/service_list declared here is not defined.
resvaluespublic.xml:67: error: Public symbol array/settings_filename_charset declared here is not defined.
resvaluespublic.xml:68: error: Public symbol array/settings_filename_charset_name declared here is not defined.
resvaluespublic.xml:69: error: Public symbol array/theme_description_list declared here is not defined.
resvaluespublic.xml:70: error: Public symbol array/theme_values_list declared here is not defined.
resvaluespublic.xml:71: error: Public symbol array/video_format_description_list declared here is not defined.
resvaluespublic.xml:72: error: Public symbol array/video_format_values_list declared here is not defined.`
You can send an version with minim SDK 14 ? I have custom ROM with android 4.4.4 but i think this fix errore for this apk

**Comment by Domiuns** [comment] 2020-03-01 08:19
I have finnaly install apk, the zip file was damaged while I was downloading it, my mistake.

Exception:
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ it_IT
* __Service:__ none
* __Version:__ 0.18.5
* __OS:__ Linux Android 4.4.4 - 19


<details><summary><b>Crash log</b></summary><p>

```
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
	at org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeParsingHelper.getUrlFromNavigationEndpoint(YoutubeParsingHelper.java:282)
	at org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeParsingHelper.getTextFromObject(YoutubeParsingHelper.java:313)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getDescription(YoutubeStreamExtractor.java:210)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:224)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:70)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:61)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)

```
</p></details>
<hr>

**Comment by wb9688** [comment] 2020-03-01 08:50
@Domiuns: Those errors are impossible in theory, unless your Android version is older than 19 (i.e. 4.4). When do those errors happen? Also, could you try [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4271540/app-debug.apk.zip), in which the first error is impossible (no matter what your Android version is)?

**Comment by Domiuns** [comment] 2020-03-01 09:33
I have android 4.4.4 custom ROM but originaly my phone have android 4.2.1

Now i have this exception only
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ it_IT
* __Service:__ none
* __Version:__ 0.18.5
* __OS:__ Linux Android 4.4.4 - 19


<details><summary><b>Crash log</b></summary><p>

```
java.lang.NoClassDefFoundError: java.util.Objects
	at org.schabi.newpipe.local.history.HistoryRecordManager.loadStreamState(HistoryRecordManager.java:213)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.updateProgressInfo(VideoDetailFragment.java:1255)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1148)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$startLoading$2$VideoDetailFragment(VideoDetailFragment.java:784)
	at org.schabi.newpipe.fragments.detail.-$$Lambda$VideoDetailFragment$tEiqo0hQK1CYkgx6kHDmCgjawWs.accept(lambda)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

```
</p></details>
<hr>
![IMG_20200301_102856](https://user-images.githubusercontent.com/53193434/75623176-d9cd5500-5ba7-11ea-8020-1fbae62f4650.JPG)

But with normal version i have this video working
![IMG_20200301_103240](https://user-images.githubusercontent.com/53193434/75623202-05503f80-5ba8-11ea-99d5-d0d1c915f565.JPG)
I think is debug version problem for this exception.

**Comment by wb9688** [comment] 2020-03-01 09:46
@Domiuns: Then complain at your custom ROM's developer and/or use NewPipe Legacy (which doesn't have v0.18.5 yet).

**Closed by wb9688** 2020-03-01 09:46 UTC
Labels: bug, youtube

**Comment by Domiuns** [comment] 2020-03-01 09:49
Thanks for help and sorry for disturb

**Comment by Domiuns** [comment] 2020-03-01 20:59
@wb9688 thanks for all help new version 0.18.6 have fix all my problem. And i not have exception UI Failure. Sorry for all disturb.
