### ISSUE TITLE
Clicking fullscreen on a paused video causes it to play

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#6437] opened 2021-06-06 08:23 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a youtube video
2. Press pause
3. Click the "full screen" icon in the lower right corner of the video

### Actual behaviour

The video is switched to full screen mode and continues playing - sometimes from a few seconds after the pause point.

### Expected behavior

It should switch to full screen and remain paused at the same exact point in the video at which it was paused.

### Device info

 - Android version/Custom ROM version: 7.0
 - Device model: Samsung Galaxy J3
 - NewPipe version: 0.21.3

**Comment by SameenAhnaf** [comment] 2021-06-06 09:33
I might be wrong. But aren't you supposed to resume the playback too while switching the player?

If you want to resume playback on another player a few moments later, you can just leave the player paused and click on the desired switch button later.

**Comment by opusforlife2** [comment] 2021-06-06 09:35
I consider this a feature, not a bug. You generally go full screen when you want to watch the video. Otherwise, let it stay paused in portrait mode? It's still paused that way.

**Comment by infinitewaveparticle** [comment] 2021-06-08 02:02
@opusforlife2 I usually watch videos in portrait mode. When I pause it and switch to fullscreen it's because I want to "zoom in" on that video at that exact moment. I have an older device. Watching in fullscreen kills my battery pretty fast... So I consider this a bug. I normally switch to fullscreen to get a closer look (like when searching for graphical errors or Easter eggs in videos) and then switch back to continue watching. I'd like this to at least be a configurable setting, like "Keep playback state when switching to and from fullscreen mode" that is by default disabled... That way we can both have our needs met.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2021-06-08 02:14
@SameenAhnaf Not following

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by SameenAhnaf** [comment] 2021-06-08 02:40
Then we should consider 'Zoom and pan' gesture mentioned in https://github.com/TeamNewPipe/NewPipe/issues/1406#issuecomment-820748116. This will let you freely zoom whenever and wherever you want with or without pausing the playback.

I prefer full screen button to work in current way. Because, the key purpose of this button is to focus on the video, not to zoom in the video.

**Comment by infinitewaveparticle** [comment] 2021-06-26 06:09
I worry that simply zooming in on a video while in portrait mode will not give me the same image crispness the full screen would. I don't actually care to "zoom" (my own poor choice of words), but rather just see a larger still of the video and then go back to portrait mode to hit play again. If it gets blurry it defeats the purpose. Adding zoom would likely help in some instances, but it would be more helpful in landscape mode for me. Again, adding a setting would be best so everyone is happy. I personally love extreme customization (Expert Mode settings) for apps. Unrelated, but we should also be able to customize the app colors (text, titles, background, etc)... Even if those options are limited. I prefer to be able to click a button in settings to customize everything - even to assign which buttons are shown on which screens and what they do and what long-pressing them does.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by SameenAhnaf** [comment] 2021-06-26 09:32
>I worry that simply zooming in on a video while in portrait mode will not give me the same image crispness the full screen would.

I understand your use case. Anyway, this feature should be optional.

**Comment by infinitewaveparticle** [comment] 2021-07-25 11:44
I desire both to be optional. We should be able to enable zoom/pan or disable it. We should also be able to control when playback is started and when it isn't.

**Comment by Stypox** [comment] 2021-07-27 09:07
This is the expected behaviour, I'm sorry it doesn't suit you. Adding a custom option just for this is not a good idea, because as always, niche options get in the way of 99% of users and still need to be maintained. NewPipe's aim is not to be extremely customizable, because that would turn away most users. Therefore I am closing this.

**Closed by Stypox** 2021-07-27 09:07 UTC
Labels: bug, player

**Comment by KKKaisar** [comment] 2023-07-07 15:55
@Stypox what if I pull request and try make what I want and show you? Or this not planned at all?
