### ISSUE TITLE
Team NewPipe, 

                    There is streaming platforms that YouTube, PeerTube, SoundCloud, Bandcamp and media.cc.   i would like to add the Spotify and when downloading audio it doesn't has audio codec MP3 320 kbps. Please team can you please make these add-on. >.<

### ISSUE THREAD

**Issue by ytgalaxygaming** [TeamNewPipe/NewPipe#7633] opened 2022-01-09 04:52 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

**Comment by SameenAhnaf** [comment] 2022-01-09 04:59
Duplicate of https://github.com/TeamNewPipe/NewPipeExtractor/issues/614.

**Comment by yashpalgoyal1304** [comment] 2022-01-09 06:57
Title != Body @ytgalaxygaming

**Closed** 2022-01-09 11:12 UTC
Labels: enhancement
