### ISSUE TITLE
[feature request] an option in the menu to continue the reproduction where you left it

### ISSUE THREAD

**Issue by speednroll** [TeamNewPipe/NewPipe#978] opened 2018-01-09 23:13 UTC
- [x]  I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

- [x] I checked if the issue/feature exists in the latest version.

I sometimes hear audiobooks that last for many hours on the newpipe background player instead of downloading them. and I was thinking that an way that would facilitate my life would be an option that will allow you to continue playing where you left it, both in the background player, pop-up and video player. It would even be beneficial for much later versions like newpipe 1.x with soundcloud support and others.

**Comment by speednroll** [comment] 2018-01-12 12:30
can someone answer about this? :eyes:

**Comment by coffeemakr** [comment] 2018-01-12 14:01
Good idea and sound like a duplicate of #537

**Comment by speednroll** [comment] 2018-01-12 14:19
I had no idea that it had already been requested :neutral_face:, maybe the only thing that remains to be added then is that instead of the newpipe automatically remembering the position it only offers it as a warning. like the VLC video player for pc that when you come back to watch the video the player gives you a warning offering you to go back to the same position

**Closed** 2018-01-12 15:37 UTC
