### ISSUE TITLE
Can't click anything underneath a pop-up window since Android 12

### ISSUE THREAD

**Issue by eiluudio** [TeamNewPipe/NewPipe#7321] opened 2021-10-28 19:51 UTC
### Checklist

- [x] I am using the latest version - 0.21.13 
- [X ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Go to any video, choose to open as a floating window, then attempt to click on or scroll objects/windows underneath it outside of NewPipe (as was always possible in the past)--it no longer works (on Pixel 5, Graphene OS).

### Actual behavior

I recently upgraded my Pixel 5, running Graphene OS, to the most recent update, which naturally installed Android 12. It seems this transition has broken many apps, including any app which 'layers' over others. I noticed this with NewPipe and another app I used, Red Moon, which made me think my phone was broken. When you launch a window as a pop-up, you can interact with that window itself, but nothing in the background (outside of NewPipe--I've noted I can still scroll menus and lists in NP as long as I don't tab out). The consistent workaround I've found is to go into the settings via the drawer and manually force stop the app from the Apps list. 

As I mentioned, I believe it is an issue of 'layering on top' because this last happened when Red Moon had started my evening blue light filter, and I also thought my phone was broken then. I have checked all permissions and settings related to apps running over other apps and they are as normal. I have been told by the Graphene devs then that the problem is most likely with NewPipe & Red Moon respectively, rather than A12 or Graphene. I have looked in the issue tracker and didn't find an issue similar to this one.

### Expected behavior

Normally, I can have a pop-up window anywhere on screen and continue to interact with windows & objects behind it. I am no longer able to.

### Screenshots/Screen recordings

n/a

### Logs

n/a

### Device info

 - Android version/Custom ROM version: Graphene OS SP1A.210812.015.2021102613 (most recent) 
 - Device model: Pixel 5

**Comment by asdf512** [comment] 2021-10-29 18:49
Possible duplicate of #6770. There is an app specific work around mentioned in this issue. Unsure if it works on production builds of GrapheneOS.

**Comment by mhmdanas** [comment] 2021-10-30 13:22
Pretty much sounds like a duplicate of #6770 to me.

**Closed by mhmdanas** 2021-10-30 13:22 UTC
Labels: bug
