### ISSUE TITLE
App Crash on Opening Banned [YouTube] Channel (v0.18.2)

### ISSUE THREAD

**Issue by gillhash** [TeamNewPipe/NewPipe#3055] opened 2020-02-04 20:10 UTC
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter] to paste bug reports.

Tapping on youtube channel (which i didn't know was banned recently) triggers App Crash.
https://www.youtube.com/channel/UCg6IB3Yz6Y2Gf83cNZC0Dmg
I Paste youtube channel link somewhere in phone to quickly see all its content just by tapping. Opening link of banned channel with NewPipe Crashes the app.

Banned channel in Subscriptions also shows "sorry some Errors occurred" eachtime i tap on "what's new" alongwith loading other channel's videos. 2309 PR latest apk also shows "Errors occurred" "one channel update failed" in "what's new" section while checking for newly uploaded videos.

Expected Behaviour:
App should display youtube like message that "channel has been Blocked" or "account has been banned"

Present Behaviour:
App Giving Following Exception 
{
   "user_action": "requested channel",
   "request": "https:\/\/www.youtube.com\/channel\/UCg6IB3Yz6Y2Gf83cNZC0Dmg",
   "content_language": "GB",
   "service": "YouTube",
   "package": "org.schabi.newpipe",
   "version": "0.18.2",
   "os": "Linux Android 6.0.1 - 23",
   "time": "2020-02-04 19:45",
   "exceptions": [
      "org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get channel name\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getName(YoutubeChannelExtractor.java:104)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:62)\n\tat org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:49)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:123)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(lambda)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)\n\tat java.lang.Thread.run(Thread.java:818)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Node.attr(java.lang.String)' on a null object reference\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getName(YoutubeChannelExtractor.java:102)\n\t... 28 more\n"
   ],
   "user_comment": ""
}

**Comment by B0pol** [comment] 2020-02-04 20:20
Duplicate of TeamNewpipe/NewpipeExtractor#228

**Comment by Stypox** [comment] 2020-02-04 20:49
Also, next time use the incredible markdown converter, as you have checked in the corresponding checkbox

**Closed** 2020-02-04 20:48 UTC

**Comment by gillhash** [comment] 2020-02-04 21:19
Sorry for that i am new on github. I tried to use the incredible markdown converter https://teamnewpipe.github.io/CrashReportToMarkdown/
But couldn't use it successfully. btw I am using git on a browser.
Can you suggest a better choice like some git client which is safe & speedy ?
