### ISSUE TITLE
Add "Premier Time" Support

### ISSUE THREAD

**Issue by nekobit1** [TeamNewPipe/NewPipe#1809] opened 2018-10-13 22:08 UTC
- [ yes ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ yes ] I checked if the issue/feature exists in the latest version.
- [ cannot ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I have noticed some videos i watch have a premier time, meaning, that they will show when they will be uploaded, kind of like livestreaming time, but its not live, its the actual video full length.

The preview description for the video shows Begin: (iirc?) or Starts:, and when you click the video it gives you that video could not be played (not crash reporter dialog).

**Comment by Stypox** [comment] 2019-08-28 17:44
Duplicate of #1517

**Closed by Stypox** 2019-08-28 17:44 UTC
Labels: enhancement
