### ISSUE TITLE
Are/will CC be available?

### ISSUE THREAD

**Issue by MissBastet** [TeamNewPipe/NewPipe#1833] opened 2018-10-21 04:50 UTC
I know there was a thread regarding the downloading of subtitles that has been closed and one of the listed features of the app is subtitles however the app doesn't give option to download cc as prev thread shows. I deleted and reinstalled app from f droid to make sure I had latest version and I do. is there something I am supposed to be doing or is this not a available feature or will not be feature?

- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by theScrabi** [comment] 2018-10-21 09:28
No its not yet there. If the feature list shows that it needs to be removed

**Comment by TobiGr** [comment] 2018-11-22 20:59
I'll close this as duplicate of #1347 and #1460.

Btw. subtitle download is implemented in #1759 which is waiting for a code review and testing.

**Closed by TobiGr** 2018-11-22 20:59 UTC
Labels: duplicate
