### ISSUE TITLE
Keyboaard not showing up when clicking on search icon

### ISSUE THREAD

**Issue by AndRo-Marian** [TeamNewPipe/NewPipe#8057] opened 2022-03-16 21:23 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Open the app.
Click on search icon

The search box appear with blocking line.

### Affected Android/Custom ROM version

Android 8, Emui 8

### Affected device model

Huawei P10 Lite

**Comment by litetex** [comment] 2022-03-17 12:47
Duplicate of #7647

**Closed by litetex** 2022-03-17 12:47 UTC
Labels: bug
