### ISSUE TITLE
Request to add 4x speed

### ISSUE THREAD

**Issue by privacymentor** [TeamNewPipe/NewPipe#5086] opened 2020-12-03 07:27 UTC
First I highly appreciate your hard work and your time for this project.

As in modern age, everyone tries to save time wherever possible, and most of us has conditioned ourselves to consume media at 2x, 3x speeds. So is the case here, I would highly request to add speed bar for 4x speed.

Our brain conditions to whatever circumstances we throw at it, so please add this feature, till now I'm consuming content at 4x speed on my laptop with an extension on firefox, but it's not always convenient to use laptop.

**Comment by mhmdanas** [comment] 2020-12-03 07:32
Duplicate of #3876. Also, please don't remove the template next time you open an issue and don't forget to follow its instructions properly. Thanks!

**Closed by mhmdanas** 2020-12-03 07:32 UTC
Labels: enhancement
