### ISSUE TITLE
Crash in downloads after update if download in progress/recovering before.

### ISSUE THREAD

**Issue by S10MC2015** [TeamNewPipe/NewPipe#6894] opened 2021-08-10 18:00 UTC
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps that lead to bug (don't know if it could repro)

I will also say that before update I had a download that wasn't starting and was stuck on recovering that prompted me to update as I though YouTube changed something thus this needed a update.

### Actual behavior

Crash

### Expected behavior

Not crash

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.8
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4387)
	at android.app.ActivityThread.access$1900(ActivityThread.java:270)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:245)
	at android.app.ActivityThread.main(ActivityThread.java:8004)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4375)
	... 8 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: 11 Oxygen OS
 - Device model: OP Nord

**Comment by mhmdanas** [comment] 2021-08-10 19:21
Duplicate of #6687.

**Closed by mhmdanas** 2021-08-10 19:21 UTC
Labels: bug
