### ISSUE TITLE
[Feature Request] Apply video thumbnail on audio only download

### ISSUE THREAD

**Issue by scoopscoop** [TeamNewPipe/NewPipe#1470] opened 2018-06-10 18:18 UTC
- [ x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x ] I checked if the issue/feature exists in the latest version.

What if NewPipe could swipe the thumbnail off a youtube video from it's URL and then apply it to the downloaded audio file via ID3 tag? At least from my experience, the types of videos that end up saved as an audio file have a useful thumbnail set by the uploader. I thought of this idea while I was trying to use automatag to edit in thumbnails, but a lot of things don't show up on it and you have to fumble around saving pictures while the image you want to use is already in the video's preview.

This feature was requested some time ago, but it wasn't in an atomized issue, and I remember it requested something more complex.

**Comment by theScrabi** [comment] 2018-06-14 19:34
> What if NewPipe could swipe the thumbnail off a youtube video from it's URL and then apply it to the downloaded audio file via ID3 tag

For this we need a way to handle mp3 files. There have been discussions about this before, but so far no coding effort.

**Comment by B0pol** [comment] 2020-05-10 09:28
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/3389

**Closed by B0pol** 2020-05-10 09:28 UTC
Labels: downloader, enhancement
