### ISSUE TITLE
Allow YewTube URLs to be shared to NewPipe

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#4069] opened 2020-08-03 22:57 UTC
invidio.us is shutting down on September 1st and it would be nice to see NewPipe accept yewtu.be URLs to be shared to NewPipe and be able to open videos from YewTube Invidious instance

**Comment by B0pol** [comment] 2020-08-04 13:32
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2351. It's about invidious project, i.e. https://github.com/iv-org/invidious , not invidio.us specifically

**Closed by B0pol** 2020-08-04 13:32 UTC
Labels: enhancement, youtube
