### ISSUE TITLE
Windows version of NewPipe

### ISSUE THREAD

**Issue by IErnest134** [TeamNewPipe/NewPipe#7874] opened 2022-02-14 12:24 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

How about making a Windows version of NewPipe?

### Why do you want this feature?

I really like NewPipe and just wish there was a version for Windows as well.

**Comment by TiA4f8R** [comment] 2022-02-14 13:53
- [X] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

No you didn't: duplicate of #1051. Please avoid opening issues without searching correctly (even if it can be hard sometimes).

Note that with Windows 11, using Windows Subsystem for Android, you might be able to use the app by install it using developer options and adb.

Thank you.

**Closed by TiA4f8R** 2022-02-14 13:53 UTC
Labels: enhancement
