### ISSUE TITLE
Link not supported: Youtube Mix

### ISSUE THREAD

**Issue by PhoenixIV** [TeamNewPipe/NewPipe#3703] opened 2020-05-31 11:13 UTC
I like sharing links to NewPipe to start listening in the background. It failed with this link: https://www.youtube.com/playlist?list=RDeDRLTI5uKgU&feature=share&playnext=1

I try to continue listening to this "playlist" in NewPipe, but it said "Link not supported". This might be connected to https://github.com/TeamNewPipe/NewPipe/issues/3250

NewPipe for Android 0.19.3

Can you support this link?

**Comment by Stypox** [comment] 2020-05-31 15:04
Duplicate of #2895, which I accidentally closed a while ago, sorry ;-)

**Closed by Stypox** 2020-05-31 15:04 UTC
Labels: enhancement
