### ISSUE TITLE
Add NewPipe video suggestions based on watch history

### ISSUE THREAD

**Issue by KfirCohen95** [TeamNewPipe/NewPipe#4281] opened 2020-09-15 15:31 UTC
#### Describe the feature you want

I think it would be great to have a feature where users could get video recommendations on NewPipe's main page, based on their watch history.

#### Is your feature request related to a problem? Please describe it

This feature is related to two problems:

1. The NewPipe app currently does not offer any video suggestions to users, making it a lot less useful when searching for new content to watch.

2. YouTube recommendation algorithm has changed drastically during recent years, offering either unrelated content, repeated suggestions and other recommendations based more on what is popular rather than what is more likely to interest their users. This often favors YouTube's own interests than their consumer needs.

#### Additional context

Add a completely new "Recommendations" tab to the content of the main page. 

#### How will you/everyone benefit from this feature?

By NewPipe implementing their own video suggestions engine, they have the opportunity to become much better, much more useful than anything YouTube has to offer when searching for new content to watch.

**Comment by opusforlife2** [comment] 2020-09-15 15:34
Duplicate of #2256. Add your view as a comment there instead.

**Closed by opusforlife2** 2020-09-15 15:34 UTC
Labels: enhancement
