### ISSUE TITLE
480p Resolution  not loading

### ISSUE THREAD

**Issue by IamJithendra** [TeamNewPipe/NewPipe#2525] opened 2019-08-16 12:14 UTC
When try to watch video on 480p resolution  it takes very more time and sometimes  it doesnot playing  and when changing the resolution  from 480p to 720p works very well without any  issues 

One of the video  in which the  error is occurred  : https://www.youtube.com/watch?v=cImw5BcXjaI

**Comment by gkeegan** [comment] 2019-08-16 12:35
What version of NewPipe is this on?

**Comment by Stypox** [comment] 2019-08-16 15:46
Can confirm, 0.17.0 and previous

**Comment by Stypox** [comment] 2019-08-16 15:48
Is this the same as #2509 ?

**Comment by AnotherLife** [comment] 2019-08-16 21:19
I think I have always noticed 480p video sometimes failing to start, whereas 360p and 720p are more reliable.

**Comment by gkeegan** [comment] 2019-08-16 23:12
I have noticed that as well.

**Comment by IamJithendra** [comment] 2019-08-17 01:48
Yes.  The issue  i am currently  experiencing in on v0.17.0 and almost all versions fails in dealing  properly  with 480p

**Comment by floss-birdy** [comment] 2019-08-17 02:53
True I've also experienced similar experience where 360p and  720p are more reliable than 480p in the past and still now.

**Comment by Stypox** [comment] 2020-04-27 07:14
Duplicate of #2415

**Closed by Stypox** 2020-04-27 07:14 UTC
Labels: bug, requires extractor change, youtube
