### ISSUE TITLE
Import and export database does not work with Android tv Xiaomi mi box version 9

### ISSUE THREAD

**Issue by casimoes03** [TeamNewPipe/NewPipe#6682] opened 2021-07-16 09:55 UTC
### Checklist

- [x] I am using the latest version - 0.21.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to settings - contents - import or export database
2. Try the intended action

### Actual behavior
It is shown a toast saying that there are no installed app to the desired action. Old versions worked fine 

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by mhmdanas** [comment] 2021-07-16 10:46
I'm not sure, but it sounds like that you've got no file manager installed. Could you try installing one and see if it works?

**Comment by skyGtm** [comment] 2021-07-16 11:50
I think the SAF is enabled by default in v0.21.6. which is causing this issue.
Though the problem is not download related. On doing SAF--> ON/OFF showed different results for me.

You can:
1. Install a file manager as `mhmdanas` told,
2. or just disable SAF from Settings > Download > Use system folder Picker(SAF) --> OFF , and see if it works.

**Comment by casimoes03** [comment] 2021-07-16 11:53
Older versions worked in the device as it is now. I have solid explorer installed too.

**Comment by mhmdanas** [comment] 2021-07-16 11:58
Can you try some other file manager (e.g. https://f-droid.org/packages/me.zhanghai.android.files) and see if it has the same issue? If the file manager supports SAF but it still doesn't work, maybe there's a bug in your device's Android variant.

**Comment by skyGtm** [comment] 2021-07-16 12:10
@casimoes03 
Yeah Solid File Explorer is NOT showing for me too.
But I also have Mixplorer installed and its showing for me.

**Comment by casimoes03** [comment] 2021-07-16 12:33
I installed com.android.documentsui and Material Files. The first is shown in the window that allows one choose the file manager but the second is not shown. When choosing com.android.documentsui nothing happens. Maybe SAF is not compatible with Android tv.

**Comment by casimoes03** [comment] 2021-07-16 13:18
It seems to work with mixplorer

**Comment by mhmdanas** [comment] 2021-07-17 20:14
Since this does not sound like an issue with NewPipe, I'll be closing this issue. If you disagree, feel free to make a comment.

**Closed by mhmdanas** 2021-07-17 20:14 UTC
Labels: bug
