### ISSUE TITLE
some weird behavior after importing database

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4133] opened 2020-08-15 17:41 UTC
### Version

-0.19.8

### Steps to reproduce the bug

1. get rid of the default kiosk from the main page 
2. export database from the settings
3. exit the app and reimport the database you just exported

### Expected behavior

you should see subscriptions rather than trending 
### Actual behaviour
seeing trending!
### Screenshots/Screen recordings

![Screenshot_20200813-154637](https://user-images.githubusercontent.com/66388840/90318194-5ff31300-df1e-11ea-9e75-4a25227721e8.png)

### Logs
none

**Comment by opusforlife2** [comment] 2020-08-15 17:45
Duplicate of #3312.

**Closed by opusforlife2** 2020-08-15 17:45 UTC
Labels: bug
