### ISSUE TITLE
(Feature  request) Add #Explore Function 

### ISSUE THREAD

**Issue by rahuldeshwal21** [TeamNewPipe/NewPipe#2950] opened 2020-01-11 15:38 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Default  search  best normal Search like #songs #india #news #vivek bindra and +++.. 
😀😀
Add  # Keyword  Search on Video  like  search  tag  Like  Facebook , Google+ , Twitter,  and  many  More. Get  tagged  Video  results.

**Comment by Stypox** [comment] 2020-01-12 21:30
Duplicate of #2251

**Closed by Stypox** 2020-01-12 21:30 UTC
