### ISSUE TITLE
Audio sessions are not closed properly

### ISSUE THREAD

**Issue by Ch3ri0ur** [TeamNewPipe/NewPipe#3644] opened 2020-05-24 19:07 UTC
I recently got the app Wavelet (https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet). 

I noticed in Wavelet, that the audio sessions of NewPipe don't get closed properly.

The author of Wavelet already noticed such a behavior in Spotify and wrote a bug report there:

https://community.spotify.com/t5/Ongoing-Issues/Android-Audio-sessions-are-not-opened-and-closed-properly/idi-p/4861998

Quote:
""https://developer.android.com/reference/android/media/audiofx/AudioEffect.html#ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION
If this intent is not broadcasted, audio effects that were applied to this session stay applied. This causes some effects not to be available to any other audio session and unnecessary consumption of system resources.""

I think this is a similar issue.

### Version
- 0.19.3

### Steps to reproduce the bug
1. Install Wavelet
2. Start Wavelet and activate AutoEQ
3. Start NewPipe and open a Video
-> Notice that a instance of NewPipe is registered in the Wavelet notification
4. Start another Video 
-> Another instance is registered.
![Screenshot_20200523-115043](https://user-images.githubusercontent.com/22932267/82762387-01c40180-9e01-11ea-8d46-4c04362a92a0.png)
5. After the 3rd instance Wavelet starts throwing errors ( the reason I noticed this )
![Screenshot_20200523-1157362](https://user-images.githubusercontent.com/22932267/82762458-6aab7980-9e01-11ea-850e-98becb24fe18.png)

### Expected behavior
Only ever one instance in Wavelet, which closes as soon as I stop using NewPipe.

### Actual behavior
The instances in Wavelet stack indefinitely and never close.

**Comment by Stypox** [comment] 2020-05-24 19:25
Duplicate of #2373

**Closed** 2020-05-24 19:26 UTC
Labels: bug
