### ISSUE TITLE
Add "Playlist" Tab to Youtube channel pages

### ISSUE THREAD

**Issue by Sosasees** [TeamNewPipe/NewPipe#7006] opened 2021-08-28 18:56 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Is your feature request related to a problem? Please describe it

I want to see all the Playlists that any channel has made, but there's no way to do it in NewPipe.

#### Additional context

I have made a sketch of what this feature could look like:
![](https://user-images.githubusercontent.com/66305550/131228011-e0a7f71d-12ee-4dfe-b8d4-56937cd4b30b.png)

#### How will you/everyone benefit from this feature?

Everyone can much more easily and quickly get an overview of entire YouTube channels because many of them made playlists for that purpose.

**Comment by TiA4f8R** [comment] 2021-08-28 19:02
Duplicate of #5203

**Closed by TiA4f8R** 2021-08-28 19:02 UTC
Labels: enhancement
