### ISSUE TITLE
Slow buffering

### ISSUE THREAD

**Issue by azat11** [TeamNewPipe/NewPipe#1294] opened 2018-04-09 17:27 UTC
I have a 50mbps Wi-Fi and videos do still buffer very slowly, especially when it comes to 60fps. So much so that I can not even watch the video for a minute or two without the loading circle appearing.
And with the 0.13.1 version it's now the loading circle for a couple of seconds every couple of seconds of the video.
Is it just me, or is this just how NewPipe is?

**Comment by azat11** [comment] 2018-04-09 20:30
> However for me it helped to just close the video and restart it.
Seems to help for now. Although it buffers so slowly I can't even see it on the progress bar.

> lucky mann, my connection barely has 10mbps.
Well, it's Russia man. $9 for a month at 50mbps. Double at double the speed.

**Comment by theScrabi** [comment] 2018-04-09 21:05
xD you've never been to germany. Everyone says we have a shitty net... its because we have a shitty net. You are lucky if you get 50mbps there but you pay up to 40$ for it.

**Comment by karyogamy** [comment] 2018-04-10 03:57
[This](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java) is our current buffering strategy. In short, once we enter buffering state (at the start or not enough data while playing), and the player have loaded `initialPlaybackBufferMs`, the playback will start immediately. When playing, the buffer will zigzag between the `minimumPlaybackbufferMs` and `optimalPlaybackBufferMs` watermarks. 

> And with the 0.13.1 version it's now the loading circle for a couple of seconds every couple of seconds of the video.

I imagine the constant buffering on 13.1 is because the `initialPlaybackBufferMs` might be too low for unstable network, though it really makes starting up a video faster under stable situations. So, it might be a good idea to create a setting in the player that allows the user to change the `initialPlaybackBufferMs` parameter, to let the player buffer for a little more before start playing.

**Comment by azat11** [comment] 2018-04-11 16:01
> However for me it helped to just close the video and restart it.

Update. This only helps for a minute or so. After that it's back to couple seconds of loading and playing for 720p60, and a second/half a second of loading and playing for 720p.
With the new version I now can not watch videos at all, though with these speeds it shouldn't be a problem.
BTW, tried SkyTube, and it works fine for the 720p (no 60fps option there). So it's likely not not the connection that is the culprit.

**Comment by theScrabi** [comment] 2018-04-11 20:47
> BTW, tried SkyTube, and it works fine for the 720p (no 60fps option there). So it's likely not not the connection that is the culprit.

yea I see. Well @karyogamy also put an option into the app to clear the cache, ... maybe that helps. However if it das it was also just a partial solution. We need to be able to reproduce this issue.

> create a setting in the player that allows the user to change the initialPlaybackBufferMs parameter, to let the player buffer for a little more before start playing.

I think this sounds like a good idea.

**Comment by azat11** [comment] 2018-04-12 10:27
**Christian Schabesberger** wrote here about clearing the cache. Seems the comment was deleted. I assume he meant metadata cache, and that helped me today. Were able to watch in 720p60 without any buffering lags at all.

**Comment by azat11** [comment] 2018-04-15 11:14
Update: Clearing the cache helps for a minute or two now, and then back to buffering glitches.

**Comment by theScrabi** [comment] 2018-04-16 15:13
Hm :/ I could think so. What could be the reason. To lesd storage space? Should we consider to clear the cache periodical.

**Comment by azat11** [comment] 2018-04-21 20:14
Nothing changed on 0.13.2. I guess I'm deleting NewPipe. Hope this will gets solved in the future (if anyone cares about this at all, maybe it's too rare of an issue).
Cheers.

**Comment by bmccoy11** [comment] 2018-04-30 04:28
I've been having this issue as well. Sometimes the issues goes away shortly if I switch to a higher or lower quality stream or clear my cache, but it makes NewPipe unusable for me.

**Comment by azat11** [comment] 2018-04-30 05:09
> I've been having this issue as well. Sometimes the issues goes away shortly if I switch to a higher or lower quality stream or clear my cache, but it makes NewPipe unusable for me.

I switched to OGYouTube, like it less, but it works.

**Comment by theScrabi** [comment] 2018-04-30 07:30
@azat11 instead of creating pressure you could help us solve this issue. We are all people that have our daily job and our daily tasks. It's not like we don't care that the app has a problem, but finding time for that is kind of hart, and so far we seem to dick in the dark.

@bmccoy11 @azat11 maybe the log says anything useful. Could you provide use one.

**Comment by wb9688** [comment] 2018-04-30 07:40
I think this happens because John changed the amounts of buffer iirc. I
think we can fix it by just changing it back. Btw I don't have this issue
(even at 1080p60 at 2×).

**Comment by karyogamy** [comment] 2018-04-30 19:06
@bmccoy11 @azat11 

Does this type of buffering problem still occur when you bring down the quality (e.g. to 360p)? 

If you have external video players such as VLC, does this problem also happen if you open the video in them (with your usual quality: 720p60, 720p, etc.)?

Since you mentioned clearing caches make things faster, can you check the memory usage during playback? Just want to make sure you are not running out of memory while playing video, which _can_ cause stutters and buffering. Would appreciate if you can provide your device info.

If possible, can you please also include a video capture of this happening? Any further details will help us to debug this problem.

> OGYouTube

OGYouTube lost support for quite some time now, I recommend giving [iYTBP](https://forum.xda-developers.com/android/apps-games/app-iytbp-injected-youtube-background-t3560900) or [YMusic](https://forum.xda-developers.com/android/apps-games/app-youtube-music-sound-stream-youtubes-t3399722) a shot, if you are willing to overlook the FOSS and multiservice aspects.

@theScrabi @wb9688

We can try reverting the buffering strategy, though I'm not sure this will solve the root cause, since @azat11 mentioned the problem happened every minute instead of the couple seconds now. As the playback start time was 2500ms compared to the 500ms now, it's strange as to why there would be such a difference, since the buffer being consumed shouldn't affect the stream downloading. 

It's even stranger that clearing the metadata cache would alleviate this problem, since the cache has a hardlimit on how many entries we can have in there, being LRU and all, which can't really be a memory issue on a recent device.

**Comment by azat11** [comment] 2018-05-01 12:55
@karyogamy 
I'll provide the info as soon as I get to installing NewPipe again and checking it all.

> since @azat11 mentioned the problem happened every minute instead of the couple seconds now

It really did this: a minute or two of playback without issues, and then buffering stutter started (video stops to buffer every two-three seconds). Sometimes clearing the cache would help, sometimes not, so I can not pinpoint that that solution works 100%.

I have a question though: should it not show buffered video in the progress bar? It never really buffered more than a few seconds with me, so I couldn't even see that on the progress bar (different shade of red). Or is that normal and as is intended?

**Comment by karyogamy** [comment] 2018-05-01 22:37
> should it not show buffered video in the progress bar?

With 720p on 50mbps, it absolutely should. If there is no buffering at all, then _maybe_ the player failed to create a cache file. How much storage space do you have left?

**Comment by azat11** [comment] 2018-05-01 22:50
> How much storage space do you have left?

Uhmm.. It's mostly unused, around 60 GB..

**Comment by theScrabi** [comment] 2018-05-12 11:56
@azat11 I've created a test build with the changes made in https://github.com/TeamNewPipe/NewPipe/pull/1389. Please tell me if it works:
https://cloud.damken.com/index.php/s/wSyRd2yC15x2ZwT
passwort is: buffertest

**Comment by Stypox** [comment] 2019-07-21 09:31
Is this still an issue? I can't reproduce it... I can only play 1080p60 videos on my phone, since that's the screen resolution, but they buffer as expected. On slow networks (e.g. 5mbps) the bandwidth is almost completely used by NewPipe, and the buffer progress bar is always some seconds ahead of the playing progress bar.

**Comment by gkeegan** [comment] 2019-07-22 00:53
@stypox I believe this was fixed in 0.16.2. It was a separate issue from the one with music videos not loading.

**Comment by Stypox** [comment] 2019-07-22 06:33
Mmh I see... it was probably fixed by #1392

**Closed** 2020-04-27 07:19 UTC
Labels: bug, more info needed, player

**Comment by Tojaw** [comment] 2020-10-02 20:31
I still have that problem though.

**Comment by Tojaw** [comment] 2020-10-02 20:33
I still have that problem though.

**Comment by opusforlife2** [comment] 2020-10-03 04:55
@Tojaw Wait for 0.20.0 to release and try it. If it is still a problem, then open a new issue.

**Comment by Tojaw** [comment] 2020-10-04 10:06
Thank you. I'll do that.

**Comment by Tojaw** [comment] 2020-10-04 10:07
Thank you. I will do that.

**Comment by 18iteration** [comment] 2021-09-09 14:52
Update for future readers, the buffering issue is back.

**Comment by infinitewaveparticle** [comment] 2021-09-10 09:00
I second this... Every few minutes videos buffer. Only this time you can usually change it to any other resolution and it works again... For a few minutes. The only way to get it to not buffer at all is to put it at 240p or 144p.

**Comment by 18iteration** [comment] 2021-09-10 15:16
> I second this... Every few minutes videos buffer. Only this time you can usually change it to any other resolution and it works again... For a few minutes. The only way to get it to not buffer at all is to put it at 240p or 144p.

For me it buffers a ton at the beginning, even vanced and youtube original play almost immediately.

Is there even a way we can even submit diagnostics/help dev? 
It's a buffering issue, not crashes, java exceptions etc...

Still want to thank the newpipe devs, the app is free, quite impressive and they put their free-time into this.

**Comment by infinitewaveparticle** [comment] 2021-09-10 16:16
There's a more recent buffering issue that was opened - and closed with version 0.21.8, I think...?... That's the one that is happening again for me. You may want to create a new issue for what you're experiencing, or search for one that matches exactly what you're seeing and add your message there. These issues definitely need revisited. I appreciate NewPipe too, but when it buffers so much and issues like this keep reappearing it's basically unusable.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Tanishq-Banyal** [comment] 2022-03-15 11:29
Can we just have option to set buffer manually ? (Just like YT Vanced gives you the option)
