### ISSUE TITLE
[0.15.1]playback speed controls

### ISSUE THREAD

**Issue by fullon9** [TeamNewPipe/NewPipe#2108] opened 2019-02-09 01:00 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
..............................................................................................................................
I hope I can set DEFAULT settings for playback speed controls.
My favorite setttings are
  tempo : 2x ([v]unlink(may cause distortion))
Thanks in advance

**Comment by Tikotik** [comment] 2019-03-21 03:57
Duplicate of #1924

**Comment by Stypox** [comment] 2019-08-28 21:15
Duplicate of #735

**Closed by Stypox** 2019-08-28 21:15 UTC
