### ISSUE TITLE
Unrecoverable player error occurred

### ISSUE THREAD

**Issue by xxkfqz** [TeamNewPipe/NewPipe#6225] opened 2021-05-03 06:59 UTC
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open a video
2. Tap on "Play" button

### Actual behaviour

Video does not load. The message "Unrecoverable player error occurred" is displayed.
I have already seen [this](https://github.com/TeamNewPipe/NewPipe/issues/5556#issuecomment-777548500) comment, but reboot did not help

### Screenshots/Screen recordings

![Screenshot_20210503-115324_NewPipe](https://user-images.githubusercontent.com/52203435/116848543-43128300-ac06-11eb-98ca-1255112beef3.png)

### Device info

 - Android version/Custom ROM version: Android 10 / AICP 15.0
 - Device model: Xiaomi Redmi 6A

**Comment by mhmdanas** [comment] 2021-05-09 11:45
Does this happen on _all_ videos?

**Comment by xxkfqz** [comment] 2021-05-09 14:35
@mhmdanas On every video that are in subscriptions as well as on some other videos

**Comment by mhmdanas** [comment] 2021-07-19 11:59
Closing as duplicate of #6225. If you disagree, feel free to make a comment.

**Closed by mhmdanas** 2021-07-19 11:59 UTC
Labels: bug, more info needed, player

**Comment by mhmdanas** [comment] 2021-07-19 12:01
Rebooting your device may fix the issue.

**Comment by HanoJing** [comment] 2022-01-03 21:19
Hi all, 
I have the same Device (Xiaomi Redmi 6A) as mhmdanas.
LineageOS 17.1 is running on mine.
I get the exact same issue since version 0.21.14 

Playing the video in the background works (Sound works).

So I selected WebM instead of MPEG4 and one video that would not work if MPEG4 works with WebM.
