### ISSUE TITLE
Popping new activity when playing a video in main player...eigther playing like youtube in a window..at the video detail activity...

### ISSUE THREAD

**Issue by MkSikander** [TeamNewPipe/NewPipe#3445] opened 2020-04-16 12:19 UTC

**Comment by Stypox** [comment] 2020-04-16 12:23
*Please **follow the issue template** when creating an issue, don't just delete everything!* If i understood correctly this is a duplicate of many other issues and fixed by #2907

**Closed by Stypox** 2020-04-16 12:23 UTC
