### ISSUE TITLE
Yt videos are very slow to load

### ISSUE THREAD

**Issue by legacychimera247** [TeamNewPipe/NewPipe#8265] opened 2022-04-20 09:31 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2 but was already there in 0.21

### Steps to reproduce the bug

Well simply enough more than 50% of youtube videos are very slow to load (or better, open) while the web browser is almost instant

Is there anything that could be done about it?i don't recall the app was so slow to load videos in last year versions

### Affected Android/Custom ROM version

Android 9

### Affected device model

Sony xperia xa2

**Comment by TiA4f8R** [comment] 2022-04-20 10:13
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

<img src="https://user-images.githubusercontent.com/74829229/164204140-aa7d98de-9bdb-4b2d-8da2-01009d5793ec.png" height="100px" alt="image">

Duplicate of #6949 for buffering during playback and of #7630 for initial buffering.

Please avoid opening duplicate issues and follow template instructions in the future. Thanks!

> Is there anything that could be done about it?

You can test the (latest) solutions in the issues I linked.

**Closed by TiA4f8R** 2022-04-20 10:13 UTC
Labels: bug
