### ISSUE TITLE
Peertube comments error

### ISSUE THREAD

**Issue by test2a** [TeamNewPipe/NewPipe#3855] opened 2020-07-07 02:19 UTC
## Exception
* __User Action:__ requested comments
* __Request:__ https://peertube3.cpy.re/api/v1/videos/9c9de5e8-0a1e-484a-b099-e80766180a6d/comment-threads
* __Content Language:__ PK
* __Service:__ PeerTube
* __Version:__ 0.19.5
* __OS:__ Linux Android 7.0 - 24

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get account.displayName
	at org.schabi.newpipe.extractor.utils.JsonUtils.getValue(JsonUtils.java:28)
	at org.schabi.newpipe.extractor.utils.JsonUtils.getString(JsonUtils.java:34)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeCommentsInfoItemExtractor.getName(PeertubeCommentsInfoItemExtractor.java:44)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:22)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:79)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeCommentsExtractor.collectStreamsFrom(PeertubeCommentsExtractor.java:53)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeCommentsExtractor.getPage(PeertubeCommentsExtractor.java:81)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeCommentsExtractor.onFetchPage(PeertubeCommentsExtractor.java:90)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:33)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:24)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$Xyj84g1UeNZqX9LVYNvWZsdT-kI.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

-------------------

org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get account.displayName
	at org.schabi.newpipe.extractor.utils.JsonUtils.getValue(JsonUtils.java:28)
	at org.schabi.newpipe.extractor.utils.JsonUtils.getString(JsonUtils.java:34)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeCommentsInfoItemExtractor.getName(PeertubeCommentsInfoItemExtractor.java:44)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:22)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:79)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeCommentsExtractor.collectStreamsFrom(PeertubeCommentsExtractor.java:53)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeCommentsExtractor.getPage(PeertubeCommentsExtractor.java:81)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeCommentsExtractor.onFetchPage(PeertubeCommentsExtractor.java:90)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:33)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:24)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$Xyj84g1UeNZqX9LVYNvWZsdT-kI.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```
</p></details>
<hr>

**Comment by B0pol** [comment] 2020-07-07 07:38
Duplicate of https://github.com/TeamNewPipe/NewPipeExtractor/issues/339. It's already fixed, wait for the next version

**Closed** 2020-07-07 07:38 UTC
