### ISSUE TITLE
Video scrolls with the screen as you are browsing comments/suggested videos

### ISSUE THREAD

**Issue by Burburon** [TeamNewPipe/NewPipe#5917] opened 2021-03-27 00:58 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I would like it so that the video follows the screen as you are browsing the comments and suggested videos.

#### How will you/everyone benefit from this feature?
It would make it so that I don't have to scroll all the way up when I'm finished reading the comments.

**Comment by mhmdanas** [comment] 2021-03-27 09:56
Duplicate of #4484.

**Closed by mhmdanas** 2021-03-27 09:56 UTC
Labels: enhancement
