### ISSUE TITLE
Error recovering download 

### ISSUE THREAD

**Issue by mayank1470** [TeamNewPipe/NewPipe#4110] opened 2020-08-10 11:24 UTC
## Exception
* __User Action:__ download failed
* __Request:__ https://www.youtube.com/watch?v=n8vlEklS3gA [ {type=video format=MPEG-4 quality=1080p videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.19.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Page is not fetched. Make sure you call fetchPage()
	at org.schabi.newpipe.extractor.Extractor.assertPageFetched(Extractor.java:61)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getVideoOnlyStreams(YoutubeStreamExtractor.java:502)
	at us.shandian.giga.get.DownloadMissionRecover.resolveStream(DownloadMissionRecover.java:144)
	at us.shandian.giga.get.DownloadMissionRecover.tryRecover(DownloadMissionRecover.java:90)
	at us.shandian.giga.get.DownloadMissionRecover.run(DownloadMissionRecover.java:54)

```
</details>
<hr>

**Comment by wb9688** [comment] 2020-08-10 11:42
This could be fixed by simply adding `IOException` to [this `catch` clause](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/us/shandian/giga/get/DownloadMissionRecover.java#L74). Note how there being an `IOException` is not a bug, just that it isn't caught and thus fails later (with an unclear error message) is the bug here.

**Comment by mayank1470** [comment] 2020-08-10 17:15
is it an issue with my filesystem or the network, because it seems like the application is not able to access the YT stream, while my internet connection was working fine

**Closed** 2021-11-06 00:06 UTC
Labels: bug, youtube, requires extractor change, waiting-for-author
