### ISSUE TITLE
[Feature Request] Playlist Tab For Channels

### ISSUE THREAD

**Issue by PeterHindes** [TeamNewPipe/NewPipe#3173] opened 2020-03-02 16:05 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

On the channel page in NewPipe, you can only see uploaded videos in chronological order. I would appreciate being able to see all the playlists created by the channel. This would be especially useful for people who use NewPipe for music.
[example playlists page](https://www.youtube.com/channel/UCfLdIEPs1tYj4ieEdJnyNyw/playlists)
Further Music pages have playlists specifically listed as Albums, this could be very useful aswell.
[example albums page](https://www.youtube.com/channel/UCfLdIEPs1tYj4ieEdJnyNyw/playlists?view=50&sort=dd&shelf_id=1369)

**Comment by XiangRongLin** [comment] 2020-03-02 19:53
The first part is a duplicate of #2414.
The second part could be included in that issue as well.

**Comment by Stypox** [comment] 2020-03-02 20:26
Yeah, let's keep everything in #2414

**Closed by Stypox** 2020-03-02 20:26 UTC

**Comment by PeterHindes** [comment] 2020-03-02 20:52
Oh sorry, missed that one when searching arround.

**Comment by Stypox** [comment] 2020-03-02 20:54
No problem ;-)
