### ISSUE TITLE
Cannon open video in 1080p

### ISSUE THREAD

**Issue by rissilver** [TeamNewPipe/NewPipe#2584] opened 2019-08-31 12:12 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I cannon open video in 1080p, sometime video open after 1-2 minute waiting. I have 40mbps internet speed that shouldn't create a problem. In 720p video start instantly. 
Phone: Xiaomi redmi note 4X
Android: 8.1.0 lineageos without gapps
Version : 0.17.1

**Comment by Stypox** [comment] 2019-10-02 13:46
Related: #2525

**Comment by Stypox** [comment] 2020-04-27 07:15
Duplicate of #2415

**Closed by Stypox** 2020-04-27 07:15 UTC
Labels: bug, requires extractor change, youtube
