### ISSUE TITLE
Add More Supported Formats available to download

### ISSUE THREAD

**Issue by TausifAlam007** [TeamNewPipe/NewPipe#6177] opened 2021-04-26 14:12 UTC
Please add more formats like mp3 etc to be available to download...

**Comment by SameenAhnaf** [comment] 2021-04-29 10:55
Duplicate of #507. Please avoid opening issues on already existing topics. Doing so will kill devs' precious time which they could utilize for solving the problems.

**Closed** 2021-04-29 12:26 UTC
Labels: enhancement
