### ISSUE TITLE
Error 405 while trying to solve a captcha

### ISSUE THREAD

**Issue by Teskann** [TeamNewPipe/NewPipe#8188] opened 2022-04-12 19:33 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

- Try to open a video
- If a captcha challenge is required, click solve
- The captcha fails to load and Google responds with an HTTP error 405

### Expected behavior

The captcha is displayed and can be solved

### Actual behavior

The captcha does not load because of the HTTP error 405

### Screenshots/Screen recordings

<img alt="Screenshot_20220412-211921" src="https://user-images.githubusercontent.com/47865674/163037804-12a67114-efed-4483-a470-aedef0cd4474.png" height=600 />

### Affected Android/Custom ROM version

GrapheneOS Android 12

### Affected device model

Google pixel 6

### Additional information

As you may see on the navigation bar of the screenshot, I use a VPN which is Blokada. Tried to disable it, but the issue is still there.

New Pipe was working as expected a few hours ago and I never had to solve a captcha before.

**Comment by kmodexc** [comment] 2022-04-12 19:34
Duplicate of #8183.

**Comment by ozmustafalevent** [comment] 2022-04-12 19:34
I don't use a vpn but it happens to me too.

**Closed by ozmustafalevent** 2022-04-12 19:34 UTC
Labels: bug
