### ISSUE TITLE
Download playlist

### ISSUE THREAD

**Issue by EliasKomar** [TeamNewPipe/NewPipe#4197] opened 2020-08-27 19:07 UTC
#### Describe the feature you want

It would be nice to be able to download an entire playlist by clicking only one button. Of course the programm should warn you if the videos exceed a certain threshold (e.g. 100 Mb).

#### How will you/everyone benefit from this feature?

At the moment it is rather tedious to download an entire playlist. This would make it a lot easier to download many videos with the same settings (e.g. a tutorial series in hq mp4, or your favourite songs as small mp3 files)

**Comment by opusforlife2** [comment] 2020-08-27 19:28
Always search existing issues before opening. Duplicate of #2380.

**Closed by opusforlife2** 2020-08-27 19:28 UTC

**Comment by Pokemetti** [comment] 2020-09-09 17:55
It isn't a duplicate of #2380. Please mention the actual issue of downloading a playlist, not a channel or feed.

**Comment by opusforlife2** [comment] 2020-09-09 17:57
The title of that issue states 3 things. You mentioned 2 of them but skipped the relevant one.

**Comment by Pokemetti** [comment] 2020-09-09 17:58
#1058 would be more fitting though

**Comment by opusforlife2** [comment] 2020-09-09 18:00
True. There are a bunch of duplicates floating around. It doesn't help that people often state multiple things in one issue which then overlap with other issues.

**Comment by Pokemetti** [comment] 2020-09-09 18:01
Plus there is an open PR (#2018), even if it is old

**Comment by Pokemetti** [comment] 2020-09-09 18:03
Yes, #1058 probably has the most duplicates, I think it should just be added to make managing the issues easier and cleaner.

**Comment by opusforlife2** [comment] 2020-09-09 18:06
There are a lot of issues in the repo. We're cleaning them up, but it is a slow process that requires input from others, so it'll take time. You're welcome to help like you did here. 👍
