### ISSUE TITLE
Share with "youtu.be" links

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#2387] opened 2019-06-07 17:11 UTC
Kinda surprized this didn't exist already.

Especially when sharing, one would want to share the shortest URL possible, yet NP still puts out the whole thing, like

https://www.youtube.com/watch?v=cUvjDOWYNY8, where as it should be a very easy task to automatically convert it to

[youtu.be/cUvjDOWYNY8](https://www.youtube.com/watch?v=cUvjDOWYNY8), which even is a valid NP link.

_Sent from my Moto E (4) Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by Stypox** [comment] 2019-06-07 20:57
If moderators approve I will add this feature

**Comment by OffifialMITX** [comment] 2019-06-07 21:15
As I'm not exactly sure how this works, I'd like to remind that there is the feature of sharing with position now.

**Comment by Stypox** [comment] 2019-06-08 05:20
I added that, so I know it :-)

**Comment by TobiGr** [comment] 2019-06-08 07:29
I think the best way is to add a new method to the extractor which returns the shortened url. And then just change the called method in the app.

**Comment by Stypox** [comment] 2019-06-10 19:38
I'll implement this as soon as #2368 is merged, to prevent merging issues.

**Comment by Stypox** [comment] 2019-08-27 12:45
Duplicate of #1556

**Closed by Stypox** 2019-08-27 12:45 UTC
