### ISSUE TITLE
Screen rotation does not revert to Portrait on completion of fullscreen widescreen video

### ISSUE THREAD

**Issue by astatine** [TeamNewPipe/NewPipe#8581] opened 2022-07-06 09:17 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Lock phone screen orientation to Portrait using the Android Quick Settings tile
2. Open NewPipe and play any video, e.g., https://www.youtube.com/watch?v=di09GdLJBEw
3. Click on the bottom right button to make the video fullscreen and watch it till the end (rotate your phone when watching the video) 

### Expected behavior

NewPipe UI should rotate back to the Portrait layout when the video finishes and I rotate the phone (and I am not in fullscreen mode)

### Actual behavior

NewPipe UI stays in Landscape layout until I tap `Back' multiple times to go back to NewPipe's 'landing' screen, at which time the NewPipe UI reverts to Portrait.

### Affected Android/Custom ROM version

Android 11 (MIUI 12.5.1)

### Affected device model

Xiaomi Redmi 7A

### Additional information

The same behavior is observed on my Xiaomi Mi A2 device running Android 11 (LineageOS18.1).

**Comment by SameenAhnaf** [comment] 2022-07-06 09:44
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5967

**Comment by lawson85** [comment] 2022-07-06 10:41
I get this behaviour on 0.23.0

**Closed** 2022-07-10 16:34 UTC
Labels: bug
