### ISSUE TITLE
405 Error on reCaptcha page

### ISSUE THREAD

**Issue by wesleymg** [TeamNewPipe/NewPipe#11661] opened 2024-10-30 03:51 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1. Get to a point where a reCaptcha is required
2. Tap Solve

### Expected behavior

Video should work normally, or reCaptcha should appear and be solved.

### Actual behavior

Google reports a 405 error, no reCaptcha appears, and ergo cannot be solved, videos are unwatchable.

### Screenshots/Screen recordings

![Screenshot_2024-10-29-23-49-08-99_2d25272d9bb7c9f889502d429df8c72b](https://github.com/user-attachments/assets/98f9242a-0823-42d0-a68d-d0f31fa75089)

### Affected Android/Custom ROM version

OxygenOS 14.0

### Affected device model

OnePlus 12R

### Additional information

I can intermittently watch a video, especially if I disconnect from my wifi, but after one or two, I can no longer use the app successfully.

**Comment by BaconCondensate** [comment] 2024-10-30 04:30
Can also confirm the issue, also happens with trending tabs and not just videos. Switching networks (eg. VPN) temporarily solves the issue

My uneducated assumption is that google is doing some A/B testing in specific regions/connection

**Comment by LucaWight** [comment] 2024-10-30 05:54
It also carries over to the regular YouTube app which also refuses to work now.

**Comment by AsyrafFile** [comment] 2024-10-30 07:48
It also occurs bug #11139 after I restarted the the router.

**Comment by vorsn** [comment] 2024-10-30 08:37
This is maybe not an actual recaptcha error. When you try to use YT on a browser in the same network you get 429 errors

`We're sorry... ... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.`

You can play sporadic videos. Updating feeds only adds 2-3 videos every x minutes. So this seems to be some kind of burst limiting. I hope you can find a workaround, looks bad.

As an user you should not update your feed anymore to avoid blocking youtube page in general.

**Comment by junelac** [comment] 2024-10-30 09:54
It seems that YouTube started to ban IP of Newpipe users. The ban is not complete, I'm still able to watch videos on YouTube with a browser, but there are are errors message and I can't connect to my account. When using a VPN it works for a while, then I'm banned again

**Comment by aufuss** [comment] 2024-10-30 11:37
I encountered the same Problem, first time yesterday 29.10. Switching to Browser works (Vanadium). Rebooting the phone helps (for a while).
Pixel 7a with GrapheneOS and no Google apps.

**Comment by rjdg14** [comment] 2024-10-30 14:59
> It seems that YouTube started to ban IP of Newpipe users. The ban is not complete, I'm still able to watch videos on YouTube with a browser, but there are are errors message and I can't connect to my account. When using a VPN it works for a while, then I'm banned again

It sounds to me a little like a rate limiting related error, especially since other clients are getting a 429 (too many requests) error.

Are the IP blocks others are experiencing temporary and going away after a few minutes to hours of requests from the app stopping? Also, how many requests has it taken others here within a certain period for the issue to occur?

I think YouTube has used a form of rate limiting for a while so what has likely changed?

**Comment by rjdg14** [comment] 2024-10-30 16:22
Could this have anything to do with the problem perhaps (YouTube releasing a new layout)?

https://old.reddit.com/r/youtube/comments/1gev7jz/anyone_getting_429_cant_do_anything_in_android_app/lujkzxn/

**Comment by Nachoswithpepper** [comment] 2024-10-30 20:00
I fear that this might be another Ban-wave as previously mentioned- aimed at specific IPs. Seems both Newpipe and GrayJay are suffering, though GrayJay is able to play videos through a different stream (fails to retrieve iOS stream data, fallsback to UMP) but still returns a 429 Error when prompting refresh/retry on the Home tab, just as Newpipe fails on both Trending/Subscriptions.

**Comment by Cf0cus** [comment] 2024-10-30 20:35
same exact issue, to add on it I checked youtube itself in the web of mobile it says "invalid response" and also if you use the youtube app it says smth error 429

**Comment by AudricV** [comment] 2024-10-30 20:47
**Please only comment if you have something useful to provide, thank you!**

This is likely triggered by making too many requests to YouTube's internal API within a certain period of time. Refreshing YouTube subscriptions without fast mode is what probably triggers the limit, so it is probably a good idea to disable auto-refresh of subscriptions and avoid refreshing your feed if you have an important number of subscriptions from YouTube for now.

If you stop connecting to YouTube in any way for an unknown amount of time, you should be able to get your access back.

The response the app gets is described in this comment: https://github.com/TeamNewPipe/NewPipe/issues/11661#issuecomment-2446190153 (the HTML response also can be raised if you set an non Google or YouTube `Origin` or `Referrer` HTTP header on these requests (and this time you get an 403 HTTP error and not a 429 one)).

The app interprets any HTTP 429 error as a captcha request, which is very bad. This must be changed, as it also affects other services (PeerTube for instance if you reach the limit of requests within a certain amount time for your IP the instance has set).

Help is wanted to determine what amount of requests within a certain period of time triggers the error and how much time you need to wait to get back valid responses.

> fails to retrieve iOS stream data, fallsback to UMP

UMP is a streaming media protocol used by YouTube and not a way to get URLs of streams.

**Comment by rjdg14** [comment] 2024-10-30 22:34
> **Please only comment if you have something useful to provide, thank you!**
> 
> This is likely triggered by making too many requests to YouTube's internal API within a certain period of time. Refreshing YouTube subscriptions without fast mode is what probably triggers the limit, so it is probably a good idea to disable auto-refresh of subscriptions and avoid refreshing your feed if you have an important number of subscriptions from YouTube for now.
> 
> If you stop connecting to YouTube in any way for an unknown amount of time, you should be able to get your access back.
> 
> The response the app gets is described in this comment: [#11661 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/11661#issuecomment-2446190153) (the HTML response also can be raised if you set an non Google or YouTube `Origin` or `Referrer` HTTP header on these requests (and this time you get an 403 HTTP error and not a 429 one)).
> 
> The app interprets any HTTP 429 error as a captcha request, which is very bad. This must be changed, as it also affects other services (PeerTube for instance if you reach the limit of requests within a certain amount time for your IP the instance has set).
> 
> Help is wanted to determine what amount of requests within a certain period of time triggers the error and how much time you need to wait to get back valid responses.
> 
> > fails to retrieve iOS stream data, fallsback to UMP
> 
> UMP is a streaming media protocol used by YouTube and not a way to get URLs of streams.

Is it likely that subscription refreshes were also what was causing the "sign in to confirm you are not a bot" error that some users were reporting earlier this year? In my case I have never used NewPipe or any similar software for keeping track of subscriptions and never had that problem. I'm currently away from home and don't want to load any videos on my data limited mobile connection, but can confirm that the trending page and search pages within NewPipe load normally.

Is the issue known to be affecting those who do not use NewPipe for channel subscription purposes?

**Comment by terranora** [comment] 2024-10-30 23:25
1. Activate fast mode (feed loading)
2. Turn off your Wi-Fi (or mobile network) for 15+ minutes to change your IP

**Comment by rjdg14** [comment] 2024-10-30 23:31
There is a setting called Feed Update Threshold. It's possible this issue is occuring for those who have it set to "always update".

**Comment by rj4387rmx87t98d7** [comment] 2024-10-31 00:30
I'm experiencing this issue too, as of about 24 hours before this comment. My home and work networks are both affected, but mobile data is not. Maybe fingerprinting is involved? Maybe because I spend much less time on mobile networks? 

Some of my relevant settings:
fetch from dedicated feed (fast mode?) - off
feed update interval - 1 hour
auto refresh - 351 channels, frequency 4 hours

It's also important to note that I'm a heavy user. I'm seeing this issue on every device connected to these networks, even after signing in. Sometimes I can load a video in the browser, sometimes not.

**Comment by CBSkarmory** [comment] 2024-10-31 03:29
> Help is wanted to determine what amount of requests within a certain period of time triggers the error and how much time you need to wait to get back valid responses.

Refreshing ~500 subscriptions (taking ~2min) (fetch from dedicated feed OFF) appears sufficient to trigger the error, though not immediately (after a few min).

Waiting 24hrs initially was sufficient to get back valid responses.

**Comment by rjdg14** [comment] 2024-10-31 09:25
It may be that for those with, say, 500 subscriptions, YouTube is interpreting the auto refresh as though you are loading 500 channel pages in a very short period of time, which I think would trigger its probably temporary rate limit block. It's common for Google to display an "unusual traffic" captcha page if you make too many searches in a short period, and I think YouTube is very similar in this regard.

Is it possible that YouTube has simply tightened the threshold of their rate limit as a way of making scraping more difficult, and this is interfering with those who have a large number of auto-updating subscriptions in NewPipe?

**Comment by burritoOverflow** [comment] 2024-10-31 16:23
I've encountered this on a few occasions this week now.
It seems YouTube then blocks your IP for some time (this will apply to all clients (even "native" clients) on that network.

I've not been able to restore use of the service in any fashion outside of calling my ISP and getting a new DHCP lease.

Hard to replicate the cause given the consequences of the failure---but it seems the number of requests sent by refreshing subscriptions could be a cause.

I'm able to occasionally view videos on a web client. Many requests fail with `403` or `429`.

I hadn't considered the `429` "appropriate" until I read this thread. No idea how long the "rate-limiting" lasts. I've not had it restored after waiting any duration, only via a new IP address.

**Comment by rjdg14** [comment] 2024-10-31 17:04
I've tested both NewPipe and FreeTube at home today and haven't had any problems, though I don't use either for subscriptions, and I think this is probably what's causing some users to get this error. My advice would be to delete your subscriptions from the app (or at minimum disable auto refresh) and simply make a note of your favourite channels so you can remember their names and search for them manually if you want to check if they've added a new video.

In the case of FreeTube, it looks like many users are currently able to use it as normal ('d imagine the same is true of NewPipe), so I suspect the 429 error is probably affecting the minority of users of both apps who have a lot of subscriptions and who have auto refresh turned on.

**Comment by Cooked14** [comment] 2024-10-31 17:28
> I've not been able to restore use of the service in any fashion outside of calling my ISP and getting a new DHCP lease.

What's DHCP lease? I live in a sh*thole country so I'm not sure they'll even understand me if I say that. Is it the same as asking for an IP change?

**Comment by burritoOverflow** [comment] 2024-10-31 18:53
> > I've not been able to restore use of the service in any fashion outside of calling my ISP and getting a new DHCP lease.
> 
> What's DHCP lease? I live in a sh*thole country so I'm not sure they'll even understand me if I say that. Is it the same as asking for an IP change?

Yes, exactly.

My network hardware has functionality to relinquish the lease, but doesn't grant a new IP without intervention from my ISP.

@rjdg14 cheers, I'll be more cautious.

Ironically enough, YT seems to 4XX sign-in attempts from "legitimate" first party clients, so I've not found a work around for this outside of new IP addr.

**Comment by kingthrillgore** [comment] 2024-10-31 19:40
I also ran into this issue after trying to update subscriptions in NewPipe and i'm 429ed on YouTube in the app and on the web until...well I dunno. I hope its not indefinite because I don't know if my ISP will let me DHCP release/renew.

**Comment by burritoOverflow** [comment] 2024-10-31 19:50
> I also ran into this issue after trying to update subscriptions in NewPipe and i'm 429ed on YouTube in the app and on the web until...well I dunno. I hope its not indefinite because I don't know if my ISP will let me DHCP release/renew.

Keep us updated as to the duration as am at a point where I'm concerned about calling again and getting my account flagged or something. Obviously YT's rate limiting "timeout" is unfortunately opaque to us.

You might be able to disconnect router from your network for some time and seeing if you get a new IP on re-connection--I have no suggestions as to the time to do that nor the success. It's **not** worked for me, but this may differ by ISP. I have to travel for a day this weekend so I'll leave my hardware off the network and see if I get a new IP on return.

FWIW, I can access videos on browsers (unauthenticated) most of the time on my home network, but often requires multiple attempts/disabling DNS filters or content blockers (uBlock/Brave Shields), dumping cookies/cache and other efforts.

**Comment by ls-alh** [comment] 2024-10-31 20:35
> I'm experiencing this issue too, as of about 24 hours before this comment. My home and work networks are both affected, but mobile data is not. Maybe fingerprinting is involved? Maybe because I spend much less time on mobile networks?
> 
> Some of my relevant settings: fetch from dedicated feed (fast mode?) - off feed update interval - 1 hour auto refresh - 351 channels, frequency 4 hours
> 
> It's also important to note that I'm a heavy user. I'm seeing this issue on every device connected to these networks, even after signing in. Sometimes I can load a video in the browser, sometimes not.

20 hours after this, on my work network (an affected network), I can use duckduckgo browser after a fresh wipe, but every request first returns an error, and a refresh will load the requested content. A fresh Newpipe install after doing this still trips up with "recaptcha challenge requested" for every request. Possible Youtube is targeting newpipe and other unofficial apps by sending a broken page on every request which stops newpipe usage in it's tracks. Handling 429 requests better may mitigate symptoms?

> The app interprets any HTTP 429 error as a captcha request, which is very bad. This must be changed, as it also affects other services (PeerTube for instance if you reach the limit of requests within a certain amount time for your IP the instance has set).

**Comment by rjdg14** [comment] 2024-10-31 20:38
> > I also ran into this issue after trying to update subscriptions in NewPipe and i'm 429ed on YouTube in the app and on the web until...well I dunno. I hope its not indefinite because I don't know if my ISP will let me DHCP release/renew.
> 
> Keep us updated as to the duration as am at a point where I'm concerned about calling again and getting my account flagged or something. Obviously YT's rate limiting "timeout" is unfortunately opaque to us.
> 
> You might be able to disconnect router from your network for some time and seeing if you get a new IP on re-connection--I have no suggestions as to the time to do that nor the success. It's **not** worked for me, but this may differ by ISP. I have to travel for a day this weekend so I'll leave my hardware off the network and see if I get a new IP on return.
> 
> FWIW, I can access videos on browsers (unauthenticated) most of the time on my home network, but often requires multiple attempts/disabling DNS filters or content blockers (uBlock/Brave Shields), dumping cookies/cache and other efforts.

In my case my home has a static IP4 address which has been the same since about 2004. Thankfully I've never used NewPipe for subscriptions, which I think is what is causing this for others here.

**Comment by kingthrillgore** [comment] 2024-10-31 20:47
> You might be able to disconnect router from your network for some time and seeing if you get a new IP on re-connection--I have no suggestions as to the time to do that nor the success. It's **not** worked for me, but this may differ by ISP. I have to travel for a day this weekend so I'll leave my hardware off the network and see if I get a new IP on return.

Unfortunately I tried that through hardware power cycling and Xfinity is no longer giving me any IP I please, its giving me the same one I had on move-in, and the next DHCP release besides me calling and playing 20 questions is in 3 days. I have to think with the dearth of IPv4 addresses they've just started assigning addresses. I am left wondering if Google has me in the doghouse and for how long (indefinite would not be fun).

**Comment by burritoOverflow** [comment] 2024-11-01 00:08
> > You might be able to disconnect router from your network for some time and seeing if you get a new IP on re-connection--I have no suggestions as to the time to do that nor the success. It's **not** worked for me, but this may differ by ISP. I have to travel for a day this weekend so I'll leave my hardware off the network and see if I get a new IP on return.
> 
> Unfortunately I tried that through hardware power cycling and Xfinity is no longer giving me any IP I please, its giving me the same one I had on move-in, and the next DHCP release besides me calling and playing 20 questions is in 3 days. I have to think with the dearth of IPv4 addresses they've just started assigning addresses. I am left wondering if Google has me in the doghouse and for how long (indefinite would not be fun).
> 
> I don't know of any customer service contacts at YouTube either to plead my case. I'm probably not going to use NewPipe again for the forseeable future, no disrespect to the maintainers. This is a bad hand we've been dealt.

Also worth mentioning that even if a new IP solves the issue (it did for me twice), it seems that as soon as your IP is flagged, you're in the dog house for some indeterminate time.

Seems to be zero tolerance. In each instance with me, once one request failed, all clients started failing immediately. 

Indefinite seems extreme, especially considering these are residential addresses that are typically not static assignments (excluding @rjdg14 above)

Would be a bad deal if random people other than NewPipe/AdBlock/DNS Filtering users start getting these flagged addresses after they're released and lose YT access.

**Comment by dev-a** [comment] 2024-11-01 13:29
few ideas
I too have encountered the same problem (currently it seems to be working, I don't want to break everything again right away)
I too have a lot of channels followed (around 300)
When newpipe wasn't working, I was able to watch youtube via the browser (on a same device) (so no ip blocking, maybe something about the headers).

Now, while waiting for the problem to be solved, I've switched to a light update of my feeds:
"fetch from dedicated feed when available"
it seems to be working for the moment

**Comment by kingthrillgore** [comment] 2024-11-01 13:43
I can confirm that after 24 hours the blocks stop, so at least its a day's wait.

**Comment by jonfre** [comment] 2024-11-02 10:01
Updating a number of subscriptions at once is a clear trigger to rise the bot flag. What about **adding an update strategy to mimic a regular user**, i.e. spreading out subscription updates randomly over the day.

The frequency of full updates could be configurable to x times a day or week.

This way you would have a feed automatically updated with some hours of delay for each subscription, without acting like a bot.

This could also be combined with some **subscription priority**, e.g. to have multiple update strategies configured and use one of them for each subscription. This would be more flexible than a blacklist as suggested in #11669.

**Comment by GlytchMeister** [comment] 2024-11-03 06:52
I only have 124 subscriptions and I'm being blocked.
I'm using a VPN tho.  I just switched endpoints and updated my list and the next video I tried to watch returned "content unavailable".  Switched endpoints again, didn't update my list, same video isn't blocked, nor any others.

I agree, a different way of updating the subscription list needs to be implemented.  Maybe shuffling with a basic pseudo-RNG, then taking that list and spacing each channel update out evenly throughout the day.  And maybe check the list against trending to make sure if one of your channels pops up on trending, it shows up immediately in the subscriptions feed.

**Comment by aufuss** [comment] 2024-11-03 23:20
I can reliably reproduce the 405 error when I refresh my 500+ subscriptions.

YouTube still works always with my browser, it seems totally unaffected.

After restarting my degoogled android newpipe works normally reliably.

I just checked my ip adress with
https://whatismyipaddress.com/
and after restart my ISP gives my a new IP address.
I use mobile data.

But if my IP is  somehow flagged, the browser shouldn't work too, right?


I have organized my subscriptions in channel groups. Biggest one with 92 channels. Since they can be refreshed individually and it didn't trigger the 405 error, that's my solution for now.

**Comment by sidgdev** [comment] 2024-11-04 17:40
Using ByeDPI android app in VPN mode which circumvents DPI by creating a local VPN but doesn't change IP resolved this error on New Pipe for me and even resolved other errors in GrayJay & FreeTube as well. Turning off the app quickly brought back the same errors & again turning on errors are gone. 

Believe YouTube is able differentiate requests from NewPipe & other invidious clients from browser/android client based on packet inspection but not outright rejecting requests based on IP ban. 

This is a useful workaround which is working for me right now, kindly let me know if its working for others.

Link to app-

https://github.com/dovecoteescapee/ByeDPIAndroid/releases

**Comment by vehosah** [comment] 2024-11-04 17:49
> Using ByeDPI android app in VPN mode which circumvents DPI by creating a local VPN but doesn't change IP resolved this error on New Pipe for me and even resolved other errors in GrayJay & FreeTube as well. Turning off the app quickly brought back the same errors & again turning on errors are gone.
> 
> Believe YouTube is able differentiate requests from NewPipe & other invidious clients from browser/android client based on packet inspection but not outright rejecting requests based on IP ban.
> 
> This is a useful workaround which is working for me right now, kindly let me know if its working for others.
> 
> Link to app-
> 
> https://github.com/dovecoteescapee/ByeDPIAndroid/releases

For two videos it went nice, but here we are again 429 that's all we know

**Comment by sidgdev** [comment] 2024-11-04 17:54
> > Using ByeDPI android app in VPN mode which circumvents DPI by creating a local VPN but doesn't change IP resolved this error on New Pipe for me and even resolved other errors in GrayJay & FreeTube as well. Turning off the app quickly brought back the same errors & again turning on errors are gone.
> > Believe YouTube is able differentiate requests from NewPipe & other invidious clients from browser/android client based on packet inspection but not outright rejecting requests based on IP ban.
> > This is a useful workaround which is working for me right now, kindly let me know if its working for others.
> > Link to app-
> > https://github.com/dovecoteescapee/ByeDPIAndroid/releases
> 
> For two videos it went nice, but here we are again 429 that's all we know

Not experienced any 429 errors yet, hope you are using app in VPN instead of proxy mode.

**Comment by BaconCondensate** [comment] 2024-11-04 18:22
> > > Using ByeDPI android app in VPN mode which circumvents DPI by creating a local VPN but doesn't change IP resolved this error on New Pipe for me and even resolved other errors in GrayJay & FreeTube as well. Turning off the app quickly brought back the same errors & again turning on errors are gone.
> > > Believe YouTube is able differentiate requests from NewPipe & other invidious clients from browser/android client based on packet inspection but not outright rejecting requests based on IP ban.
> > > This is a useful workaround which is working for me right now, kindly let me know if its working for others.
> > > Link to app-
> > > https://github.com/dovecoteescapee/ByeDPIAndroid/releases
> > 
> > 
> > For two videos it went nice, but here we are again 429 that's all we know
> 
> Not experienced any 429 errors yet, hope you are using app in VPN instead of proxy mode.

Tested that method, doesn't seem to work. I don't think DPI protection will even do anything when Google isn't doing MITM because they **are** the endpoint

Newpipe will probably need to fake being a browser (?)

**Comment by vehosah** [comment] 2024-11-04 19:17
Uhhh and now what, we won't be able to use newpipe ever again?

**Comment by vehosah** [comment] 2024-11-04 21:17
Yes and now comments are considered spam now 🙄

**Comment by vehosah** [comment] 2024-11-04 21:20
And now we can't use the app at all now

**Comment by ThatAsshe** [comment] 2024-11-08 07:07
> > Help is wanted to determine what amount of requests within a certain period of time triggers the error and how much time you need to wait to get back valid responses.
> 
> Refreshing ~500 subscriptions (taking ~2min) (fetch from dedicated feed OFF) appears sufficient to trigger the error, though not immediately (after a few min).
> 
> Waiting 24hrs initially was sufficient to get back valid responses.

Thank you for this contribution! I was looking for an answer for a few hours on why regular Youtube was giving me the error 429 and 405 on the Tubular app, and I happen to have more than 600 subscriptions *oopsie* 😅

**Comment by realquink** [comment] 2024-11-10 00:15
Adding to the discussion. I use NewPipe daily about 130 subs on a phone and I use a VPN via the router. In total 3 devices use NewPipe throughout a given day on the same IP. Today I received this error for the first time.

**Comment by rabidrivas** [comment] 2024-11-10 12:19
[Freetube](https://freetubeapp.io/) seems to work, It uses RSS to avoid rate limiting. Could it be fixed impementing something like that?

**Comment by ThatAsshe** [comment] 2024-11-10 13:49
> Adding to the discussion. I use NewPipe daily about 130 subs on a phone and I use a VPN via the router. In total 3 devices use NewPipe throughout a given day on the same IP. Today I received this error for the first time.

Wait exactly 24 hours and the temp. ban will be lifted, after that what I've done is to create channel groups in the 'Subscriptions' section to reduce the amount of subbed channels that'd update at once, delete the 'What's New' tab from the Main page (settings > content > content of main page) to avoid updating the list by accident or just delete your subscriptions at all until a new fix comes out!

**Comment by rabidrivas** [comment] 2024-11-10 14:09
> > Adding to the discussion. I use NewPipe daily about 130 subs on a phone and I use a VPN via the router. In total 3 devices use NewPipe throughout a given day on the same IP. Today I received this error for the first time.
> 
> Wait exactly 24 hours and the temp. ban will be lifted, after that what I've done is to create channel groups in the 'Subscriptions' section to reduce the amount of subbed channels that'd update at once, delete the 'What's New' tab from the Main page (settings > content > content of main page) to avoid updating the list by accident or just delete your subscriptions at all until a new fix comes out!

Yeah, or if you are lazy, update subs with a vpn

**Comment by tauch** [comment] 2024-11-11 07:24
**I can confirm:** 
Refreshing the subscribed feeds (~500) instantly triggers an **IP ban** (that persists for approx. a day). 
While the ban is active, NewPipe will prompt to solve a captcha, but that function does fail when attempted in NewPipe.
Note: The ban also affects playback via youtube-nocookie, where I get redirected to youtube while a ban is active.

Solution-Ideas:
I'd really love to see a triggerable background updater for the feeds, where the requests/min can be adjusted or even better, where NewPipe remembers which channels did not have new content for a long time, and then check those much more seldomly (reducing the necessary requests to Youtube).
A first work-around for the ban-problem could even be a simple setting to introduce a fixed **minimum-delay between feeds during update** (this way the update will take ages, but that could avoid getting the IP banned).

**Comment by realquink** [comment] 2024-11-11 17:18
> > Wait exactly 24 hours and the temp. ban will be lifted, after that what I've done is to create channel groups in the 'Subscriptions' section to reduce the amount of subbed channels that'd update at once, delete the 'What's New' tab from the Main page (settings > content > content of main page) to avoid updating the list by accident or just delete your subscriptions at all until a new fix comes out!

Confirming this is right. Ban is lifted and I can load and play videos.

**Comment by Jordan112004** [comment] 2024-11-22 20:39
![Screenshot_20241122_153704_NewPipe.jpg](https://github.com/user-attachments/assets/234c1713-e3de-4401-a23d-83efa630cbc7)

Hi newpipe, can y'all please fix this issue, I keep on having content unavailable error messages when I have on my mobile data. when I have the Wi-Fi on it works good. Please fix this issue as soon as possible thanks...

**Comment by Stypox** [comment] 2024-11-24 16:03
The rate limiting when reloading the feed is hopefully fixed by #11743, let us know if the next release (0.27.3) solves the issue for you

**Closed by Stypox** 2024-11-24 16:03 UTC
Labels: bug, help wanted, youtube

**Comment by Jordan112004** [comment] 2024-11-24 21:46
There's a content unavailable issue, it happens every time I use my mobile data on my phone, I need this issue to be fixed ASAP...

**Comment by Lorthiz** [comment] 2024-12-18 15:33
I think that this should not be closed. Implemented 'fix' also slows down RSS feed updates that did not have any rate limiting problem afaik. The only way I was informed about this issue was because this 'fix' changed my feed refresh time from few seconds to few minutes. And right now having bigger amount of subscriptions makes this APP almost unusable.
For comparison FreeTube still woks great with RSS feeds.

**Comment by MavisCelus19201** [comment] 2025-05-01 02:44
Seeing this issue on my end now. Newpipe doesn't give me an option to open in browser on account of not "seeing" my browser even on two different Android devices, it just doesn't let me open anything, and trying to solve the recaptcha in Newpipe just gives me a 405 error, which keeps popping up intermittently after some searches. I can open a browser page manually and solve the recaptcha but that doesn't fix it in Newpipe.
