### ISSUE TITLE
Starting with v0.23.1, nothing works properly or works at all. I had to resort to an old APK and some old settings imported to it to listen to music. I am afraid to even try the current v0.23.2. What is going on with NewPipe! For the first time, NewPipe is going down-hill!

### ISSUE THREAD

**Issue by flawpc** [TeamNewPipe/NewPipe#8836] opened 2022-08-19 05:14 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Starting with v0.23.1.

### Steps to reproduce the bug

NOTHING WORKS! Starting with v0.23.1, nothing works properly or works at all. I had to resort to an old APK and some old settings imported to it to listen to music. I am afraid to even try the current v0.23.2. What is going on with NewPipe! For the first time, NewPipe is going down-hill!

**Comment by mhmdanas** [comment] 2022-08-19 09:06
0.23.2 fixes the problem, please update.

Duplicate of #8760.

**Closed by mhmdanas** 2022-08-19 09:06 UTC
Labels: bug, needs triage

**Comment by flawpc** [comment] 2022-08-19 22:25
Thank you, and incidentally, I should have previously added, with high regard, that it is unexpected from NewPipe.

**Comment by opusforlife2** [comment] 2022-08-19 22:31
Then you'll keep being disappointed, sorry. Newpipe is a 3rd party app that has no control over the changes YT (or any other service) makes. All that can be done is adapting to such changes after the fact, which means that there will _always_ be some period of time when Newpipe breaks for everyone.

A more healthy outlook would be to keep yourself updated on such changes through our pinned issues, and update to a new version whenever it becomes available.

**Comment by flawpc** [comment] 2022-08-20 13:36
Thank you for the valuable information. I must keep it in mind, making use of it.
