### ISSUE TITLE
Question about languages on NewPipe

### ISSUE THREAD

**Issue by davidre345** [TeamNewPipe/NewPipe#4085] opened 2020-08-05 23:21 UTC
Hello there,

I just want to ask you a question: I had translated New Pipe to my language at 100% and I just want to know if I have to wait until a new update will be released to Newpipe for seeing this application at 100% in my mobile phone, or there are other alternatives?

**Comment by Gymcap** [comment] 2020-08-06 00:15
The latest translations are added just before each new release version. To answer your question, you'll either need to wait until the next update, or build NewPipe yourself with translations included.


To the Devs:  
I guess this may be a decent time to suggest that all translations are kept online, outside of the app. If we allow users to download language packs on demand through the app, this would lower the compiled app size while also allowing people to update their languages without waiting for the next release.

**Comment by davidre345** [comment] 2020-08-06 00:53
Hello,

Thank you for answering me! So, how often do you make an update?

O xov, 6 ago, 2020 02:15, Gymcap <notifications@github.com> escribiu:

**Comment by opusforlife2** [comment] 2020-08-06 17:25
You can see the releases tagged on the Releases page. It's roughly once a month, give or take a few days, and exceptions like hot fixes.

**Comment by davidre345** [comment] 2020-08-06 20:37
Thank you so much for the information. I will be waiting until the next
month.

O xov., 6 de ago. de 2020 ás 19:26, opusforlife2 (<notifications@github.com>)
escribiu:

**Comment by B0pol** [comment] 2020-08-07 19:54
> To the Devs:
I guess this may be a decent time to suggest that all translations are kept online, outside of the app. If we allow users to download language packs on demand through the app, this would lower the compiled app size while also allowing people to update their languages without waiting for the next release.

This is a bad idea, translation must be reviewed otherwise it will likely cause crashes, e.g. in the past https://github.com/TeamNewPipe/NewPipe/issues/3524 https://github.com/TeamNewPipe/NewPipe/issues/3350 caused by bad formatting (e.g. `% s` instead of `%s`). 
Moreover, we have to add the new language in the language selector (settings -> content -> app language).

As said before, you can build newpipe, or you can also ask us to build, otherwise wait the next version. I'm closing this issue as it's answered.

**Closed by B0pol** 2020-08-07 19:54 UTC
Labels: localisation / translation, question
