### ISSUE TITLE
UI crashed. 

### ISSUE THREAD

**Issue by bensonkb** [TeamNewPipe/NewPipe#1452] opened 2018-06-05 03:03 UTC
```
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.13.5",
   "os": "Linux Android 8.1.0 - 27",
   "time": "2018-06-05 03:00",
   "exceptions": [
      "java.lang.RuntimeException: Unable to resume activity {org.schabi.newpipe\/org.schabi.newpipe.player.MainVideoPlayer}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.playqueue.PlayQueue.init()' on a null object reference\n\tat android.app.ActivityThread.performResumeActivity(ActivityThread.java:3597)\n\tat android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3637)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1652)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6600)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)\nCaused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.playqueue.PlayQueue.init()' on a null object reference\n\tat org.schabi.newpipe.player.BasePlayer.initPlayback(BasePlayer.java:254)\n\tat org.schabi.newpipe.player.MainVideoPlayer.onResume(MainVideoPlayer.java:178)\n\tat android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)\n\tat android.app.Activity.performResume(Activity.java:7189)\n\tat android.app.ActivityThread.performResumeActivity(ActivityThread.java:3572)\n\t... 8 more\njava.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.playqueue.PlayQueue.init()' on a null object reference\n\tat org.schabi.newpipe.player.BasePlayer.initPlayback(BasePlayer.java:254)\n\tat org.schabi.newpipe.player.MainVideoPlayer.onResume(MainVideoPlayer.java:178)\n\tat android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)\n\tat android.app.Activity.performResume(Activity.java:7189)\n\tat android.app.ActivityThread.performResumeActivity(ActivityThread.java:3572)\n\tat android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3637)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1652)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6600)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)\n"
   ],
   "user_comment": "This happen when opening from chrome browser."
}
```

```
java.lang.RuntimeException: Unable to resume activity {org.schabi.newpipe/org.schabi.newpipe.player.MainVideoPlayer}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.playqueue.PlayQueue.init()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3597)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3637)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1652)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6600)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.playqueue.PlayQueue.init()' on a null object reference
	at org.schabi.newpipe.player.BasePlayer.initPlayback(BasePlayer.java:254)
	at org.schabi.newpipe.player.MainVideoPlayer.onResume(MainVideoPlayer.java:178)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
	at android.app.Activity.performResume(Activity.java:7189)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3572)
	... 8 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.playqueue.PlayQueue.init()' on a null object reference
	at org.schabi.newpipe.player.BasePlayer.initPlayback(BasePlayer.java:254)
	at org.schabi.newpipe.player.MainVideoPlayer.onResume(MainVideoPlayer.java:178)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
	at android.app.Activity.performResume(Activity.java:7189)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3572)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3637)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1652)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6600)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```

**This happen when opening from chrome browser.**

**Comment by theScrabi** [comment] 2018-06-05 09:04
https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#issue-reportingfeature-requests

**Comment by theScrabi** [comment] 2018-06-05 09:04
Please give us a further description on when this error occured, and with which video.

**Comment by bensonkb** [comment] 2018-06-07 03:00
This error occurred when opening an YouTube vedio from chrome browser

**Comment by theScrabi** [comment] 2018-06-07 06:59
I can not reproduce it.

**Comment by PacoBell** [comment] 2018-06-07 22:01
I can. I get that every time I try to share a video from the YouTube app after playing some other video in NewPipe at least once. Force closing NewPipe will allow the next video to play, but subsequent videos will always crash with the same NullPointerException error. I'm also running on Android 8.1.0.

**Comment by theScrabi** [comment] 2018-06-26 15:56
I could not reproduce it directly, but i found something else.

@karyogamy could you please take a look at this.

![gurken](https://user-images.githubusercontent.com/1891273/41924381-27d3b0f4-796a-11e8-8c1c-94838552631b.gif)


```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getRepeatMode()' on a null object reference
	at org.schabi.newpipe.player.BasePlayer.getRepeatMode(BasePlayer.java:1150)
	at org.schabi.newpipe.player.BasePlayer.handleIntent(BasePlayer.java:235)
	at org.schabi.newpipe.player.VideoPlayer.handleIntent(VideoPlayer.java:256)
	at org.schabi.newpipe.player.MainVideoPlayer.onNewIntent(MainVideoPlayer.java:156)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1224)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1236)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2827)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2842)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2858)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1575)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by karyogamy** [comment] 2018-06-26 17:37
@theScrabi This was reported in #1412. See #1509.

**Closed** 2018-06-27 09:49 UTC
Labels: duplicate
