### ISSUE TITLE
Playback for 720p Mpeg4 and 480p WebM hangs

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#2673] opened 2019-09-29 20:28 UTC
~~[Ex-Microsoft employee remembers the last sound he heard at Microsoft: Bing!](https://www.youtube.com/watch?v=7GM4Lt5k24s)~~

~~Happens at any resolution, the video doesn't even need to be loaded.~~

**Comment by OffifialMITX** [comment] 2019-09-29 21:06
Ok, apparently every video does this as soon as I enter landscape mode, which is something that has never happened before. Also I can't view any 720p videos.

**Comment by gkeegan** [comment] 2019-09-29 21:07
What version of NewPipe and what is your location?

**Comment by OffifialMITX** [comment] 2019-09-29 21:09
@gkeegan I'm on F-Droid's latest 0.17.1 build and am located in Germany.

**Comment by gkeegan** [comment] 2019-09-29 21:14
For me 1080p works fine for all videos, but 720p doesn't work. Looks like another change happened.

**Comment by OffifialMITX** [comment] 2019-09-29 21:48
The other thing is that NewPipe kicks me out when I try to view anything in landscape…

**Comment by licaon-kter** [comment] 2019-09-30 19:40
Webm 480/720/1080 work... But not 360.

**Comment by Stypox** [comment] 2019-10-02 12:27
Maybe #2525 is related

**Comment by OffifialMITX** [comment] 2019-10-03 09:29
@Stypox Actually I think it's related. It's been an issue for while for me as well, and wasn't consisten, even with the same videos.

**Comment by OffifialMITX** [comment] 2019-10-03 09:32
So the problem with "kicking out" wasn't actually related to NewPipe, it's been a problem with LawnChair's hidden optuons that freaked out at device rotation.

**Comment by OffifialMITX** [comment] 2019-10-03 09:34
Also, interestingly enough, 720p at 60 fps works just fine.

**Comment by Pentaphon** [comment] 2019-10-06 23:55
I was having problems playing videos until I switched to webm video and webm audio as defaults. Now 17.3 is fine.

**Comment by OffifialMITX** [comment] 2019-10-08 08:40
Still on F-Droid's 0.17.1, now some videos work in 720p, usually when there's no 60fps counterpart.

**Comment by licaon-kter** [comment] 2019-10-08 09:23
@OffifialMITX Why don't you update?

**Comment by OffifialMITX** [comment] 2019-10-08 09:55
I did now, F-Droid just didn't tell me there's an update, even though the repo was updated. Either way I couldn't notice any changes in regards to this issue.

**Comment by eladkarako** [comment] 2020-01-30 21:50
v18.2
480p,720p,+...MP4 streams failed to load in the player, 
no error page just a small banner the disappears after 1 second saying Unrecoverable player errer. 
all videos in the 'recently updated' 'feed'.

**Comment by OffifialMITX** [comment] 2020-01-31 07:08
I'm not quite sure what happens, but it looks like by now that the process hangs on whichever resolution/fps the player was first opened but works just fine if I choose *any* other resolution/fps. Even if I change it back to the resolution I first opened the video before the newly selected video is properly buffered.

**Comment by gkeegan** [comment] 2020-01-31 07:17
I can confirm the behavior @OffifialMITX is experiencing.

**Comment by eladkarako** [comment] 2020-02-02 21:55
all resolutions seems to work now (nothing changed within NewPipe). Possibly 'servers fault'...

**Comment by OffifialMITX** [comment] 2020-02-02 22:30
@eladkarako For me the behavior seems highly inconsistent, but definitely there.

**Comment by opusforlife2** [comment] 2020-02-06 19:26
In my case there are certain videos that don't play on _any_ DASH resolution. The only three streams that play are the non DASH video streams that contain the audio streams within them. This means WebM 360p (VP8), MPEG-4 720p and 360p (AVC) streams, the bottom 3 formats in any youtube-dl format list. 

I noticed this because if I tap on Download, and look at the list of resolutions, _only_ the sizes of the mentioned streams are loaded. The rest aren't.

One such video I encountered most recently is this: https://www.youtube.com/watch?v=PUg574WphuQ

**Comment by aaazv** [comment] 2020-02-25 16:15
The videos dont play in other resolutions than 360p and also dont work with other formats

**Comment by Pentaphon** [comment] 2020-02-26 09:43
I think this bug has to do with this bug https://github.com/TeamNewPipe/NewPipe/issues/2934

**Comment by soshial** [comment] 2020-02-28 20:16
Same BUG for me: videos play ONLY in 360p Mpeg4.

**Comment by opusforlife2** [comment] 2020-02-28 20:38
By the way, after some testing, Google seems to have removed all VP8 encodes from YouTube. Now the videos containing audio are limited to mp4.

**Comment by mittorn** [comment] 2020-04-13 00:37
Everything higher than 360 hangs here (including 1080 mpeg4):
https://youtube.com/watch?v=mytds2HrAr8
https://youtube.com/watch?v=c2j79HRxe8w
And with many other videos. In 0.17.x it did not work too

**Comment by Stypox** [comment] 2020-04-27 06:15
Duplicate of #2415

**Closed by Stypox** 2020-04-27 06:15 UTC
Labels: ASAP, bug, youtube
