### ISSUE TITLE
Clicking on a timestamp to a YouTube video in NewPipe causes recents app launching to not work while video is playing

### ISSUE THREAD

**Issue by SegiH** [TeamNewPipe/NewPipe#8165] opened 2022-04-08 03:31 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Search YT for a concert video that has a list of hyperlinks with the timestamp of each song in the video either in the description of the video (or the comments). For example, I can reproduce this issue out with this video: https://www.youtube.com/watch?v=reK0S5O_gSI which has a link to each song in the video.
2. Play the video
3. Tap the recents button and if you try to swipe an app up, you will see that it moves up. Don't close NewPipe!
4. Go back to the NewPipe app and click on any of the timestamp hyperlinks to jump to a specific time stamp. The currently video pauses and then opens a small pop up overlay on top of the same video at the timestamp that was clicked on.
5. Tap the recents button again
6. Try to swipe up or down or left or right and you'll see that nothing happens. If you press the home button, you are taken back to the home screen but you cannot launch any other apps. You have to press the back button to go back to NewPipe. If you press the square maximize button in the overlay and then click on X to stop playing the video, everything goes back to normal.

### Expected behavior

For the overlay not to prevent the device from registering touches on the screen while a video is playing

### Actual behavior

You cannot launch any other app. You can't do anything.

In Settings under Video and audio, there is a toggle called "Start main player in full screen".  This preference was off. I turned it on and see the same behavior. I also changed the preference "Preferred Open action" to "Video player" but no matter what I do, clicking on the timestamp hyperlink opens in a popup overlay.

### Screenshots/Screen recordings

N/A

### Logs

N/A

### Affected Android/Custom ROM version

Android 12/Stock Samsung ROM w/One UI 4.1 & March 2022 Security Update

### Affected device model

Samsung Note 20

**Comment by TiA4f8R** [comment] 2022-04-08 15:10
This behavior is the same as #6770 (popup player, Android 12). Closing as a duplicate of this issue.

Please take a look at pinned issues next time! Thanks!

**Closed by TiA4f8R** 2022-04-08 15:10 UTC
Labels: bug
