### ISSUE TITLE
Video does not fill screen when watching the video in full screen mode

### ISSUE THREAD

**Issue by MrBKA95** [TeamNewPipe/NewPipe#8460] opened 2022-05-30 19:17 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

Can happen when you click on any video. Either when auto rotate is enabled on phone or when you click full screen in the bottom right of the video.

### Expected behavior

Video should fill the whole of screen in full screen mode.

### Actual behavior

Video only fills roughly 25% of the screen when in full screen mode - top left hand of the screen. If you go out of full screen mode it's a 50/50 chance between the video staying in the same position or correcting itself and filling the whole screen. Sometimes it won't correct unless you force stop the app.

### Screenshots/Screen recordings

![Screenshot_20220530-175606_NewPipe](https://user-images.githubusercontent.com/105092892/171049586-edbd4547-92bc-4b70-9ff9-047d6715e006.jpg)
![Screenshot_20220530-180529_NewPipe](https://user-images.githubusercontent.com/105092892/171049590-9d96191a-bab2-4b69-8722-e0b7ab36195c.jpg)
![Screenshot_20220530-200202_NewPipe](https://user-images.githubusercontent.com/105092892/171049596-47e6d7a4-9710-4b51-b5a7-488aa6722f3f.jpg)
![Screenshot_20220530-200251_NewPipe](https://user-images.githubusercontent.com/105092892/171049598-096f9533-b8e9-4474-94fe-79b2b9b21b07.jpg)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S21

**Comment by SameenAhnaf** [comment] 2022-05-30 19:34
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7262

**Closed** 2022-06-11 18:32 UTC
Labels: bug
