### ISSUE TITLE
Unable to view comment replies 

### ISSUE THREAD

**Issue by badri001** [TeamNewPipe/NewPipe#9866] opened 2023-02-28 15:33 UTC
### Checklist

- [ ] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Need an option to view comment replies 

### Why do you want this feature?

I seen someone asked an question in the video comments and i went to answer that question in YouTube then only i noticed that comment already has many replies to it.

### Additional information

In Vanced 
<img alt="Screenshot_20230228_210110" src="https://user-images.githubusercontent.com/34916335/221901003-13c58717-e57a-4021-abcb-ef6a73484e9a.jpg" width=284 />

In YouTube
<img alt="Screenshot_20230228_210218" src="https://user-images.githubusercontent.com/34916335/221901078-a82e4fee-32af-4a23-b6fb-a6fdfd812dfd.jpg" width=284 />

**Comment by lrusso96** [comment] 2023-02-28 15:39
Duplicate of #2277

**Closed as completed** 2023-02-28 15:41 UTC
Labels: template ignored, duplicate
