### ISSUE TITLE
Can't download Videos anymore

### ISSUE THREAD

**Issue by oiiiiiiii** [TeamNewPipe/NewPipe#3983] opened 2020-07-28 09:33 UTC
If I use the share option within the YouTube-App I get the error, that the URL isn't supported and when I try to open a video within the App it's crashing..

**Comment by soladev** [comment] 2020-07-28 09:33
(Most likely) duplicate of #3951, a release will soon correct this issue

**Closed** 2020-07-28 09:35 UTC

**Comment by tuxayo** [comment] 2020-07-28 09:57
Hijacking this issue to message @TobiGr and @TeamNewPipe :
To get less duplicates, maybe #3951 could be kept open and pinned in the issue tracker.

Thanks to all the people involved for your valuable work :green_heart:

**Comment by wb9688** [comment] 2020-07-28 10:32
@tuxayo: It's already pinned, and it shouldn't be re-opened, as the issue is already fixed in the code.

**Comment by tuxayo** [comment] 2020-07-28 18:22
Indeed already pinned.

I missed https://github.com/cyw026/NewPipeExtractor/pull/3 and though the fix was https://github.com/TeamNewPipe/NewPipeExtractor/pull/352
Sorry for the confusion. Thanks for you time.

**Comment by wb9688** [comment] 2020-07-28 18:34
@tuxayo: No, https://github.com/TeamNewPipe/NewPipeExtractor/commit/5ac80624a40f4c600ae493e66881b5bf008f0ddb is the fix.
