### ISSUE TITLE
[Request] Download Tab on the Main Page

### ISSUE THREAD

**Issue by notBradPitt** [TeamNewPipe/NewPipe#8385] opened 2022-05-11 00:42 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I think it'd be great to have a download tab on the main page, similar to the kiosk, subscription, and history tabs already available.

### Why do you want this feature?

It makes switching to the downloaded tab faster and easier. For people who use NewPipe to download videos, it's more convenient when you can open and see the downloaded videos right away

**Comment by mhmdanas** [comment] 2022-05-22 11:40
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2565.

**Closed by mhmdanas** 2022-05-22 11:40 UTC
Labels: enhancement
