### ISSUE TITLE
Sort trending videos based on time

### ISSUE THREAD

**Issue by Tikotik** [TeamNewPipe/NewPipe#1881] opened 2018-11-12 11:38 UTC
It is not easy to find, which video is uploaded recently and trending.
It would be great if trending page is sorted locally based on the video upload date - recent at first.

Is it sorted on some other metrics at present?

**Comment by TobiGr** [comment] 2018-11-12 11:56
Duplicate of #822.

**Closed by TobiGr** 2018-11-12 11:56 UTC
