### ISSUE TITLE
UI Crash when searching peertube (sepiasearch)

### ISSUE THREAD

**Issue by UnixPhonez** [TeamNewPipe/NewPipe#7726] opened 2022-01-30 18:45 UTC
Issues when watching videos on peertube using sepiasearch

### Checklist
- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. select peertube search 
2. search any videos on the sepiasearch
3. then try to watch them 

### Actual behavior
app crashes 

### Expected behavior
to watch videos

### Logs
```
{"user_action":"ui error","request":"ACRA report","content_language":"en-US","content_country":"US","app_language":"en_US","service":"none","package":"org.schabi.newpipe","version":"0.21.15","os":"Linux Android 12 - 31","time":"2022-01-30 13:39","exceptions":["java.lang.NumberFormatException: For input string: \"\"\n\tat java.lang.Integer.parseInt(Integer.java:627)\n\tat java.lang.Integer.parseInt(Integer.java:650)\n\tat org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:488)\n\tat org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:503)\n\tat org.schabi.newpipe.util.ListHelper.$r8$lambda$UGNhfSv5KuYwsqrcThyeG189sI0(Unknown Source:0)\n\tat org.schabi.newpipe.util.ListHelper$$ExternalSyntheticLambda0.compare(Unknown Source:4)\n\tat java.util.Collections$ReverseComparator2.compare(Collections.java:5235)\n\tat java.util.TimSort.binarySort(TimSort.java:296)\n\tat java.util.TimSort.sort(TimSort.java:221)\n\tat java.util.Arrays.sort(Arrays.java:1492)\n\tat java.util.ArrayList.sort(ArrayList.java:1470)\n\tat java.util.Collections.sort(Collections.java:206)\n\tat org.schabi.newpipe.util.ListHelper.sortStreamList(ListHelper.java:269)\n\tat org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:243)\n\tat org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:130)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1602)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6(VideoDetailFragment.java:913)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$X-UcNln23jPsop2TvHe2VPTu0NQ(Unknown Source:0)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda11.accept(Unknown Source:8)\n\tat io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)\n\tat io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)\n\tat io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.app.ActivityThread.main(ActivityThread.java:7841)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)\n\tat com.android.internal.os.ExecInit.main(ExecInit.java:48)\n\tat com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)\n\tat com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)\n"],"user_comment":""}
```
### Device info

 - Android version/Custom ROM version: GrapheneOS
 - Device model: Pixel 6 Pro

**Comment by TiA4f8R** [comment] 2022-01-30 19:58
Please follow properly our issue template the next time you open an issue. You didn't fill the version of the app you are using and you wrote outside template parts.

> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

Duplicate of #6860. Will be fixed in one of the coming releases.

Please search better for duplicates next time. Thank you!

**Closed by TiA4f8R** 2022-01-30 19:58 UTC
Labels: bug
