### ISSUE TITLE
bug tap show controll on player (unified UI)

### ISSUE THREAD

**Issue by Domiuns** [TeamNewPipe/NewPipe#4179] opened 2020-08-23 21:44 UTC
when I press once the status bar appears on the screen and not the player controls, if I press a second time the player controls appear. I would like that when I press once the player controls appear as they do for the normal version of newpipe.

### Version

-I use an preview version of future newpipe release apk
### Steps to reproduce the bug

Open an video make one tap for show status bar, make second tap for show all player controll

### Screenshots/Screen recordings

![Screenshot_2020-08-23-22-35-57](https://user-images.githubusercontent.com/53193434/90989398-d5ec1f80-e599-11ea-9880-2421736ba5ee.png)
![Screenshot_2020-09-04-02-40-35](https://user-images.githubusercontent.com/53193434/92186835-488db280-ee58-11ea-9dba-1f45c612d997.png)

**Comment by opusforlife2** [comment] 2020-08-24 10:55
Both the player controls and status bar appear in one tap for me. This could be something Kitkat specific.

**Comment by avently** [comment] 2020-09-03 15:28
@opusforlife2 
> Both the player controls and status bar appear in one tap for me. This could be something Kitkat specific.

He probably uses unreleased version from #3777 (based on timeline on screenshot).

It's not a problem of current dev branch (because it's not reproducible in an emulator). The issue can be closed until there will be proofs that the current code in dev branch has this problem.

@Domiuns next time don't open issues if you test unreleased code but write about that problems right into the PR you test

**Comment by opusforlife2** [comment] 2020-09-03 15:44
@avently I think you mean #3205? Yeah, @Domiuns, if that apk is the one you're testing, then you should raise the issue there. If it's in the debug builds Bopol provides (https://github.com/TeamNewPipe/NewPipe/projects/17#card-42918515), only then should you post it here.

**Comment by avently** [comment] 2020-09-03 16:01
> I think you mean #3205? 

Yes, I am.

**Comment by Domiuns** [comment] 2020-09-04 00:35
@avently I have test the apk version a84b54f 2020-09-03 at https://github.com/TeamNewPipe/NewPipe/projects/17#card-42918515
and i continue to have the same issues
I think is a problem with unified UI or Player

**Comment by opusforlife2** [comment] 2020-09-04 05:47
Alright. Thanks for confirming.

**Comment by Domiuns** [comment] 2020-09-04 12:01
Video demostration problem https://streamable.com/e/hqj8l9

**Comment by avently** [comment] 2020-09-11 18:16
@opusforlife2 looks like it device specific thing based on conversation in #4267, so I think this issue should be removed from unified player project

**Comment by ShareASmile** [comment] 2022-09-03 01:19
It's open for a long time if @Domiuns still uses his oldie phone he can test 0.23.3 because 0.24.0 will be released with android Lollipop as the minimum version instead of KitKat 4.4
@opusforlife2 should put this issue on waiting for author? or close if resolved.

**Closed** 2022-09-18 00:16 UTC
Labels: bug, player, device/software specific, waiting for author
