### ISSUE TITLE
Automatic database backups

### ISSUE THREAD

**Issue by dennis90a** [TeamNewPipe/NewPipe#7410] opened 2021-11-15 13:38 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Automatic backups whenever a change is made to the database, like when a video/subscription added/removed.

#### Why do you want this feature?

It is a hassle to (remember to) manually export the database every week to make sure you are backed up.

**Comment by SameenAhnaf** [comment] 2021-11-15 13:44
Duplicate of #3558.

**Comment by litetex** [comment] 2021-11-15 18:52
Duplicate of #3558

**Closed by litetex** 2021-11-15 18:52 UTC
Labels: enhancement
