### ISSUE TITLE
Can't import previous data when update to new App version.

### ISSUE THREAD

**Issue by tifDev** [TeamNewPipe/NewPipe#5033] opened 2020-11-29 11:09 UTC
### Checklist

- [x] I am using the latest version - 0.20.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Download new version of NewPipe
2. Export data from previous version and uninstall it
3. Install last NewPipe version and import old data

**I can't import the old data, it says that it couldn't import the data.** Any other easier way to switch between version? Every time a install a new version I always need to add my subscriptions and playlists manually :(

### Device info

 - Android version/Custom ROM version: MIUI GLOBAL 12.0.3
 - Device model: Xiaomi 9T pro

**Comment by mhmdanas** [comment] 2020-11-29 12:17
You don't need to uninstall NewPipe to update to a new version, unless you are moving from GitHub APKs to F-Droid or something similar. I'll be keeping this open for now, since there were several other reports of this. Also, could you specify the NewPipe version from which you exported the data?

**Comment by Stypox** [comment] 2020-12-01 13:49
@tifDev unfortunately we can't do anything without something to test on ;-)

**Comment by tifDev** [comment] 2020-12-04 20:12
@mhmdanas I was using the previous version of 0.20.4. 
I usually download the latest version from github and then do this manually because F-droid APK is not updated (for example, the current version on F-droid is 0.20.1). 
Is it possible to have the F-droid repo updated more quickly? This would solve this issue because when I update from F-droid it prompts a message asking if I want to keep the data.

THank you

**Comment by tifDev** [comment] 2020-12-13 09:40
Any news?

**Comment by mhmdanas** [comment] 2020-12-13 09:48
None so far, primarily because of our inability to reproduce this and the lack of logs.

**Comment by Stypox** [comment] 2020-12-14 18:37
Closing as there is not enough information to do anything

**Closed by Stypox** 2020-12-14 18:37 UTC
Labels: bug, more info needed
