### ISSUE TITLE
[Feature Request] Video Page Player & Side Player

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#1831] opened 2018-10-20 18:59 UTC
The official YouTube app has a video player on the video page itself and when you go back to browse Youtube the video player is in the bottom right corner. I think by having some settings to enable/disable this setup will be handy especially for those who are new to NewPipe.

And I believe this is possible since all you need to do for the video page player is use the popup player but have it fixed on the thumbnail spot on the video page and not be able to resize the image.

For the side video player use the popup player itself and not be able to resize it or move it around. And to close the side player just swipe it to the left. Then all NewPipe needs to do is detect if your on the video page and if so no side player. If not the side player is shown.

**Comment by gkeegan** [comment] 2018-10-20 22:29
Both of these have been brought up already I believe. And the "video page player" has been a work in progress with a pull request for a while.

**Comment by epitron** [comment] 2018-10-28 20:32
I'd like to offer a personal observation of how I behave while using the official YouTube app vs NewPipe...

When I have to focus on one video at a time, it increases my attention span. In the official YouTube app, I get distracted by related videos and quickly succumb to a feedback loop of "what else is on". I end up getting a lot less value from each video, and become addicted to searching for something better than what I'm currently watching.

Now, being able to play videos while navigating is great when you're creating music playlists. However, the background player covers that use case for me. (It is a bit awkward to switch from the background player to the full screen player -- that could definitely be improved.)

Does anyone else have an opinion on this?

**Comment by Stypox** [comment] 2019-08-28 18:06
Duplicate of #528

**Closed by Stypox** 2019-08-28 18:06 UTC
