### ISSUE TITLE
[Feature Request] Save time of played videos.

### ISSUE THREAD

**Issue by jmliz** [TeamNewPipe/NewPipe#2466] opened 2019-07-17 07:04 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I'd like to see in newpipe the feature of saving last position in a played video. This will be very useful for long videos, like documentaries and lectures, in which I have to be remembering for each one at what time did I left the video, which is cumbersome to begin with, and my brain has a limited amount of memory as well.

This is a feature that not even youtube itself has and I believe will bring more adoption to your software.

**Comment by gkeegan** [comment] 2019-07-17 07:32
Implemented in #2288, so it will be included in the next release.

**Comment by Stypox** [comment] 2019-07-17 07:32
Already fixed in #2288

**Closed** 2019-07-17 07:33 UTC

**Comment by jmliz** [comment] 2019-07-17 07:49
@Stypox is #2288 the same thing? By saving I meant the video automatically starts playing from where you left it. Not just a visual aid.

**Comment by Stypox** [comment] 2019-07-17 10:55
Yes, I think it does what you want. Anyway this is a duplicate of #1970

**Comment by jmliz** [comment] 2019-07-17 10:57
Ok thanks
