### ISSUE TITLE
Feature: most popular, date added (oddest) date added (newest) 

### ISSUE THREAD

**Issue by Hanankhan1983** [TeamNewPipe/NewPipe#7968] opened 2022-02-28 12:45 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Hi, there Newpipe team I want the feature like YouTube have . When you go to a channel there you will find a option (most popular,date added (oddest) and date added (newest) that's it

I don't know if it's duplicate.                                                    Thank you 😊

### Why do you want this feature?

Because I need it to download it's hard to scroll for the oldest and find the most popular 

### Additional information

..

**Comment by SameenAhnaf** [comment] 2022-02-28 13:17
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/5815

**Closed** 2022-02-28 13:27 UTC
Labels: enhancement

**Comment by TiA4f8R** [comment] 2022-02-28 15:21
> I don't know if it's duplicate.

If you don't know, search for duplicates first (use different keywords related to your issue if you cannot find it), please. Duplicate/part of #2414.

Thank you.
