### ISSUE TITLE
Add channel blocking feature

### ISSUE THREAD

**Issue by ramzymbk** [TeamNewPipe/NewPipe#8856] opened 2022-08-22 09:05 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

An option to block a channel and all its videos from timeline, search results, etc....
It is already done for web browsers ([Firefox](https://addons.mozilla.org/en-US/firefox/addon/blocktube/)/[Chrome ](https://chrome.google.com/webstore/detail/blocktube/bbeaicapbccfllodepmimpkgecanonai)) via an add-on called [BlockTube](https://github.com/amitbl/blocktube), but it's never been included in an app.

### Why do you want this feature?

A family member who is new to YouTube (and technology in general) is being bombarded by harmful/misleading content from certain channels. I tried blocking/reporting them but they keep popping back up no matter what, it's so frustrating.

**Comment by Git79806** [comment] 2022-08-22 09:23
Duplicate

**Comment by SameenAhnaf** [comment] 2022-08-22 12:04
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1815

**Closed** 2022-08-23 18:05 UTC
Labels: enhancement, needs triage
