### ISSUE TITLE
Disable "gesture" volume and brightness control by default

### ISSUE THREAD

**Issue by ilia3101** [TeamNewPipe/NewPipe#3713] opened 2020-06-01 01:54 UTC
It's really annoying and an acquired taste. Most people for sure hate it. Much less useful than it is annoying (bad ux).

BTW newpipe is amazing and I love it, probably my favourite app. This is just the only thing that bothers me, I always have to disable it.

**Comment by Stypox** [comment] 2020-06-01 06:16
I also never use gestures, but from my experience assumptions like "most people hate them" often turn out to be wrong. Vlc has them enabled by default, too, so I think keeping the current behavour is ok

**Comment by B0pol** [comment] 2020-06-01 09:47
I disagree. Personally i really enjoy these gestrfures, for examéle luminosity: you first have to open the notification menu, but also set the luminosity in it. That means you maybe need to set the luminosity twice, because you didn't see it how it renders in live.
With gestures, just swipe. Wow the video is too bright, let's just swipe down. Easy and fast.

**Comment by ingingin** [comment] 2020-06-01 11:54
I hate the gestures. My mom also has problems with these controls, I told her about the gestures but it always messes up her viewing experience when just touching the screen and I have to run down the stairs to show her how it works and reset everything. Finally I just turned it off for her. Which means the default should be OFF here.

**Comment by ilia3101** [comment] 2020-06-01 12:47
Sorry if I came off rude at all. @Stypox You are right, assumptions are hard to make correctly. Maybe a poll of newpipe users could be done?

And another issue with gestures that I forgot to mention: quickly swiping down from the top of the screen just to see the notification icons or the clock triggers the gestures too, and volume goes way down sometimes.

**Comment by Stypox** [comment] 2020-06-01 12:56
> Maybe a poll of newpipe users could be done?

I was thinking about this, too. Maybe something on the website? Would we be allowed to collect feedback there given the GDPR regulation? @TobiGr @TheAssassin 

> And another issue with gestures that I forgot to mention: quickly swiping down from the top of the screen just to see the notification icons and clock triggers the gestures too, and volume goes way down sometimes.

This is fixed in 0.19.4

**Comment by TheAssassin** [comment] 2020-06-01 12:57
> Maybe a poll of newpipe users could be done?

There's no reason not to do so. Just make sure to use a privacy-friendly tool, which also has a proper privacy policy.

**Comment by wb9688** [comment] 2020-06-01 13:09
What about just using GitHub reactions? I.e. react with :+1: or :-1: on this message.

**Comment by Stypox** [comment] 2020-06-01 13:14
@wb9688 how many people who use NewPipe, also take a look at its repository to check issues and give feedback? Some surely do, but most people don't even know how GitHub works. I meant that there could be a more mainstream way to vote on active issues, with a proper ui and accessible by anyone, so that the vote can be more representative of the user base.

**Comment by wb9688** [comment] 2020-06-01 13:15
@Stypox: How many people look at our website? I know I basically never do.

**Comment by Stypox** [comment] 2020-06-01 13:16
Maybe we could put a button in NewPipe's drawer advertising that users can cast their vote on the website

**Comment by Stypox** [comment] 2020-06-01 13:54
@ingingin there are no checks for duplicate votes, if I wanted I could just vote 100 times. Using Reddit for polls seems good idea, does it support built-in polls (maybe through bots)?

**Comment by ingingin** [comment] 2020-06-01 13:58
Reddit doesn't use polls, which is sad. I did find [Redditpoll](http://redditpoll.com/) But it's HTTP, and isn't a privacy minded services either. That poll I gave you is the only one privacy focused

**Comment by TheAssassin** [comment] 2020-06-01 14:03
@ingingin random tools make no sense, and please don't create polls on behalf of the NewPipe project, this gives a wrong impression and we take no responsibility for third party poll stuff. Your enthusiasm is admirable, but maybe take a step back, we'll set up a proper poll if we need one.

Reddit makes no sense either. Just gives people access who want to sign up with such a service.

**Comment by ingingin** [comment] 2020-06-01 14:07
@TheAssassin What the fuck, don't talk to me like that. I am trying to help but would rather give you the finger, I am trying to help here, creating a poll is what I did to show how it looks. Take all the credit if you care so much. I was never invited anyways

**Comment by ingingin** [comment] 2020-06-01 14:09
You even said it yourself; 

> There's no reason not to do so. Just make sure to use a privacy-friendly tool, which also has a proper privacy policy.

And I found one, be glad now

**Comment by ilia3101** [comment] 2020-06-02 09:16
@ingingin You are not as important as you think you are. Newpipe team have zero obligation to instantly accept things done on their behalf. They don't even get to see the results of that poll you, some 15 day old user, created.

**Comment by androidSwDev099** [comment] 2020-06-02 13:42
The gesture settings are retained through updates for me, so I don't understand the issue.  I have the volume gesture on and the brightness gesture off. Default on makes sense so new people know they exist.

**Comment by puppykickr** [comment] 2020-06-03 17:26
Personally, myself a long time user, I despise the gestures.

There is not much more annoying than having the volume and brightness
controls screwed up each time the screen is touched.

Phone slips in the hand? Volume all the way up. Or vise-versa. Change hands
holding device? Brightness all the way down. Or vice-versa. Each is
annoying.

Perhaps an anouncement toast upon initial app start to notify new users of
the presence of this 'feature'.

I, for one, thank God that there is a way to turn this off, in addition for
NewPipe as a whole.

Grant Ryan Swan                        (puppykicker)

**Comment by androidSwDev099** [comment] 2020-06-03 17:38
New users should go through the settings to learn what they can do with the app. ☺️

**Comment by ilia3101** [comment] 2020-06-03 17:46
If something puts off new users, it should be disabled by defualt. ☺️

**Comment by androidSwDev099** [comment] 2020-06-03 18:12
Won't ever be able to please all users no matter what the default settings are.

**Comment by ilia3101** [comment] 2020-06-03 20:55
It's confusing because it is a very unusual software control, that's just the truth. A feature that is very likely to confuse or infuriate some new users is better turned off by default.

At the very least, an explanation/some kind of tip should show up when the app is first opened.

@puppykickr describes the situation perfectly.

> Phone slips in the hand? Volume all the way up. Or vise-versa. Change hands
holding device? Brightness all the way down. Or vice-versa. Each is
annoying.

**Comment by B0pol** [comment] 2020-06-03 20:58
Unusual? Definitely not unusual for video players, see VLC, MX Player, MPV…

**Comment by ChiefMikeK** [comment] 2020-06-04 02:18
> Personally, myself a long time user, I despise the gestures. There is not much more annoying than having the volume and brightness controls screwed up each time the screen is touched. Phone slips in the hand? Volume all the way up. Or vise-versa. Change hands holding device? Brightness all the way down. Or vice-versa. Each is annoying. Perhaps an anouncement toast upon initial app start to notify new users of the presence of this 'feature'. I, for one, thank God that there is a way to turn this off, in addition for NewPipe as a whole. Grant Ryan Swan (puppykicker)

## My thoughts🏝 A delay of a few hundred milliseconds upon accidentally touching the screen but, only for an _increase_ in volume / luminous   
I prefer to have an instant lowering of volume and dislike an accidental full volume!

**Comment by theFireProjet** [comment] 2020-06-04 18:14
I'm using the gestures. I'm used to it from VLC and I think it's useful if your phone is standing somewhere and the volume keys are on the wrong side, at the bottom so you can't reach them.
Also my phone has a video enhancer mode which makes the screen massively brighter on the same brightness value, so it is useful to be able to readjust this within the player. Also I don't like to pull down the bright, white notification bar to tune the brightness while watching videos cause it's blinding.

**Comment by puppykickr** [comment] 2020-06-08 00:02
@ChiefMikeK 
I kind of like your idea.
Especially if the delay was adjustable, similar to how it is done on a keyboard alternate.

The more I think of it, the more I like it.

But I would also want the delay for decreases, as well.

There could even be a different time allotment for the longpress required for each.

Obviously this would increase the complexity of the app, and in setting it up.

But, as stated above by others, many popular video apps have this feature- and almost every keyboard app has a similar feature that deals with the timing of a longpress.

**Comment by Sonickyle27** [comment] 2020-07-03 09:52
Other apps I've used come with a sort of introduction sequence to what the app does and shows to the user some basic settings. Something like Davx5 comes to mind. It's been a while since I've set up NewPipe so I don't know if NewPipe has this already?

A setting for Gestures can be provided in this introduction, with a slide dedicated to showing the gesture controls. The page could have a radio button with a description next to it says something like:

"Drag up and down on the left side of the current video to change the brightness, and drag up and down on the right side of the video to change the volume."

And then a second radio button that says:

"Disable gesture controls on the video player."

There could be a graphic showing this in action, I guess looking similar to the gestures video in ![Android 10's gesture settings](https://i.imgur.com/4YjSVbJ.png).

At least with this introduction, you get the choice of if you want gesture controls enabled or not when younfirst run the app, and it doubles as a tutorial for how the gestures work too!

**Comment by MD77MD** [comment] 2020-07-03 13:10
> > Unusual? Definitely not unusual for video players, see VLC, MX Player, MPV…
> 
> Sure, but Google/Netflix/Amazon/Apple would have added such a feature to their video-related apps by now if it benefitted the user experience. These companies do research on this stuff because user experience can affect their profits.

would wouldn't be using newPipe if they did things right... big companys with stupid minds... the only thing they are good at is collecting 💰

**Comment by ilia3101** [comment] 2020-07-12 23:44
> would wouldn't be using newPipe if they did things right... big companys with stupid minds... the only thing they are good at is collecting 💰

That's irrelevant. What's relevant is that they make apps most people can happily use in the default configuration.

And this feature, is really annoying. I am almost certain it has put some new users off. I know just how quickly I'll stop using an app if I dislike something. If not for the popup player, I probably would've given up on newpipe instantly.

> A setting for Gestures can be provided in this introduction, with a slide dedicated to showing the gesture controls.

This would be a really great solution.

**Comment by MD77MD** [comment] 2020-10-11 01:16
>That's irrelevant. What's relevant is that they make apps most people can happily use in the default configuration.

Yes it is, if we were happy by the way they make things, you and me would not be here... we wouldn't even need to have newPipe... 

anyway, i think a clear indication to what people like more, could be extracted from what every video app out there has by default, that is gestures on by default. on the other hand, if most people did not like gestures, developers of those apps would have so much complaints, that they would have them off by default, but they don't. so this should definitely be the default setting  .

**Comment by krushia** [comment] 2020-11-23 16:17
The easiest way to find out what people prefer is to change it and see who complains.

**Comment by MD77MD** [comment] 2020-11-24 20:27
> The easiest way to find out what people prefer is to change it and see who complains.

what are talking about...isn't this obvious already?

**Comment by krushia** [comment] 2020-12-01 15:18
@MD77MD Nobody has ever opened an issue to request these gestures be enabled by default. There are however several closed issues that were caused by gestures.

Commenting in opposition to an opened issue is less noteworthy than one being created (many of you are here only because you got a watched project notification). The only way to get comparable feedback from users is to disable gestures by default.

**Closed** 2020-12-01 16:02 UTC
Labels: enhancement, player

**Comment by crozone** [comment] 2021-01-18 03:23
Found this issue after slipping on newpipe and accidentally maxing the volume on my bluetooth headphones. Not only are the gestures incredibly annoying, they are dangerous to the users hearing.

VLC is also plagued by similar gestures, for both mobile *and* desktop. Personally I have never found them to be anything but an annoyance and something to immediately disable after a fresh install.

The issues with the UX of these features are threefold.

* They aren't discoverable by simply looking at the UI, only by accidentally changing the volume or brightness drastically can the user discover these features even exist. The features aren't consistent with the placement of other features in the menu, such as resolution and speed control.

* The actions the gestures perform are already baked into the Android UI. Users already know how to change their brightness and volume on their devices easily with physical buttons or the notification dropdown. The gestures are completely redundant.

* The gestures are easily triggered by accident and the result can range from annoying (brightness being set too high or low), to dangerous (headphones being set to maximum volume instantaneously).

I would urge the developers to reconsider this issue and potentially disable the gestures by default.

**Comment by thansk** [comment] 2021-02-04 17:48
I am happy with the gestures, they are extremely useful and convenient and wouldn't have found out about them if they weren't enabled by default.

**Comment by crozone** [comment] 2021-02-08 01:29
> wouldn't have found out about them if they weren't enabled by default.

This is indicative of poor UI design that doesn't prioritise discoverability. Annoying users with hidden behaviour is not a substitute for a visual indicator that flags the presence of a feature.

**Comment by shscs911** [comment] 2021-02-11 10:17
As a long-time user of MX Player, I personally found the brightness and volume gestures extremely intuitive. Just my opinion, but it would be awesome, if there was a setting to make the Brightness and Volume set by gestures to persist across sessions (Though I don't think many people would like that). Thanks for all your hardwork.
