### ISSUE TITLE
Error report: Recovering from Player Error

### ISSUE THREAD

**Issue by rahaaatul** [TeamNewPipe/NewPipe#8093] opened 2022-03-22 09:15 UTC
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=2] occurred while playing https://www.youtube.com/watch?v=2tUEHZaSF7s
* __Content Country:__ BD
* __Content Language:__ bn
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:587)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:257)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0
	at android.media.MediaCodec.native_flush(Native Method)
	at android.media.MediaCodec.flush(MediaCodec.java:2298)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:160)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:912)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:905)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReinitializeCodec(MediaCodecRenderer.java:881)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onPositionReset(MediaCodecRenderer.java:730)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onPositionReset(MediaCodecVideoRenderer.java:419)
	at com.google.android.exoplayer2.BaseRenderer.resetPosition(BaseRenderer.java:158)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.resetRendererPosition(ExoPlayerImplInternal.java:1277)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1255)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1188)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.seekToInternal(ExoPlayerImplInternal.java:1159)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:481)
	... 3 more

```
</details>
<hr>

**Comment by litetex** [comment] 2022-03-22 17:58
Duplicate of #8016

**Closed by litetex** 2022-03-22 17:58 UTC
