### ISSUE TITLE
Popup Player issues with Android 12 update

### ISSUE THREAD

**Issue by UkrainianSteamHacker** [TeamNewPipe/NewPipe#7692] opened 2022-01-24 01:53 UTC
- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x ] This issue contains only one bug. I will open one issue for every bug report I want to file.

Steps to reproduce the bug
<!--
1. Go to any video and open in Pop-up Player
2. Try to do anything else after leaving the NewPipe app

Actual behavior
Once the pop-up player is live, you can't tap on anything. The Android home buttons/menu buttons don't work, you can't close or open other apps, you can't get to menus. The only way to pull out of it is to turn off the phone. 

I have enabled "display over other apps" in the settings, but that doesn't help. 

Expected behavior
Be able to use any other feature Android when newpipe is up lol

Device info

 - Android version/Custom ROM version: 12
 - Device model: A52 5g

**Comment by TiA4f8R** [comment] 2022-01-24 09:26
> - [x] I am using the latest version - 0.20.8 

The latest version is 0.21.15.

> - [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

Duplicate of #2223. Closing this issue as a duplicate of it.

You didn't follow the issue template, please follow it the next time you open an issue (especially check if you're using the latest version and check for duplicates first by searching for exisiting issues (closed or opened), like stated in the template). Thank you.

**Closed by TiA4f8R** 2022-01-24 09:26 UTC
Labels: bug
