### ISSUE TITLE
App bar background same color as theme instead of Red and hide on scroll.

### ISSUE THREAD

**Issue by rakibdev** [TeamNewPipe/NewPipe#8298] opened 2022-04-27 07:54 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

App bar, status bar background color black or white based on current theme instead of Red and hide when scrolling videos just like YouTube app.

### Why do you want this feature?

I new installed this app as YouTube working slow. This very fast, useful. Few issue the Red background taking all focus, distracting all time, looking out of place when I'm using pure black theme.

App bar taking lot of free space. Could use more compact design moving some rarely used buttons (show watched items, fast mode) to settings. And user scrolls only to see video list, that time app bar can be hidden. Hide on scroll used everywhere Chrome, YouTube, Play Store. Overall this a request to redesign app bar.

**Comment by litetex** [comment] 2022-04-27 18:12
Duplicate of #8110

**Closed by litetex** 2022-04-27 18:12 UTC
Labels: enhancement
