### ISSUE TITLE
video not available

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#6277] opened 2021-05-13 01:27 UTC
hi

I get the message video not available on youtube on many videos while the videos are reallyon youtube.

**Comment by dreamsoftunitedkingdom** [comment] 2021-05-13 01:45
It seems it has something to do with youtube's new age verification for certain videos.
I get the error 'video not available' for each youtube video thar required the age verification.

This is normal in newpipe or is there a fix for this available?

**Comment by iamthesenate1** [comment] 2021-05-13 09:05
Can you give examples?

**Comment by dreamsoftunitedkingdom** [comment] 2021-05-13 13:31
just take any video on youtube that required age verification...
they all have this error

**Comment by TiA4f8R** [comment] 2021-05-13 18:48
Did you enabled `Show age restricted content` in Settings, Content? If no, can you try again please? Thank you!

**Comment by seanking2919** [comment] 2021-05-16 01:58
> 
> 
> Did you enabled `Show age restricted content` in Settings, Content? If no, can you try again please? Thank you!

I have "Show age restricted content" enabled. And I can't even access videos like [Toy Soldier](https://www.youtube.com/watch?v=uoB_MDSkHms) per se.

**Comment by dreamsoftunitedkingdom** [comment] 2021-05-29 23:45
stupid crap software!!!

**Comment by seanking2919** [comment] 2021-05-31 22:31
> 
> 
> > Did you enabled `Show age restricted content` in Settings, Content? If no, can you try again please? Thank you!
> 
> I have "Show age restricted content" enabled. And I can't even access videos like [Toy Soldier](https://www.youtube.com/watch?v=uoB_MDSkHms) per se.

As of v0.21.3, my issue with "age restricted content" is fixed.

**Comment by opusforlife2** [comment] 2021-06-04 17:46
Well, ghost is ghost, and @seanking2919 says the issue is fixed.

**Closed by opusforlife2** 2021-06-04 17:46 UTC
Labels: doesn't-follow-template
