### ISSUE TITLE
Could not get video duration for a video

### ISSUE THREAD

**Issue by el-banto** [TeamNewPipe/NewPipe#6405] opened 2021-05-31 18:11 UTC
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Visit the channel page

Interestingly, the YouTube website and app aren't able to get the duration for this video either

The video plays fine though

### Actual behaviour

Video duration isn't shown

### Expected behavior

Video duration should be shown

### Screenshots/Screen recordings

![Screenshot_20210531-185254](https://user-images.githubusercontent.com/29665788/120228293-bd084d00-c242-11eb-9300-f14f41b63e43.jpg)

## Exception
* __User Action:__ requested channel
* __Request:__ Start loading: https://www.youtube.com/channel/UCnGqG_jyyXmTzdamBpKfeHA
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.21.3
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get duration
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.getDuration(YoutubeStreamInfoItemExtractor.java:118)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:106)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.collectStreamsFrom(YoutubeChannelExtractor.java:320)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getInitialPage(YoutubeChannelExtractor.java:250)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:83)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:48)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:123)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BOLWstv98dC8pFAG_uir5gPXYwY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:220)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:68)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:114)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>

**Comment by skyGtm** [comment] 2021-06-01 03:40
Similar #5326

**Comment by TobiGr** [comment] 2021-06-01 21:31
That video does not have a duration :open_mouth: Looks like a YouTube bug.
 ![grafik](https://user-images.githubusercontent.com/17365767/120392815-5150dd80-c331-11eb-9677-e757e616850f.png)

**Comment by el-banto** [comment] 2021-06-01 21:52
Indeed, not a bug with NewPipe I guess. I'm not sure if this is something you'd want to add a work around for in that case (this is the only video I have noticed with such an issue).

Side note:
When playing the video from the NewPipe app directly, it plays fine and you can move to any time in the video via the progress bar (video length is shown here)

However, if the video was opened in PiP mode via a link (e.g. from the exception above), the video duration can't be found so while the video still plays, you can't move to any other point in time via the progress bar.

**Comment by mhmdanas** [comment] 2021-06-13 09:47
This sounds like an isolated case that's caused by a YouTube bug, so I'm closing this. If more cases start to pop out, then perhaps this should be given another look.

**Closed by mhmdanas** 2021-06-13 09:47 UTC
Labels: bug
