### ISSUE TITLE
[Feature] Add Peertube Livestream resolution selector

### ISSUE THREAD

**Issue by UnlimitedCookies** [TeamNewPipe/NewPipe#7110] opened 2021-09-14 23:59 UTC
### Checklist
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
It would be awesome if you could also select the resolution on a peertube livestream. 
Peertube videos seem to have a toggle for the resolution.

#### Is your feature request related to a problem? Please describe it
Not really. I don't know which resolution is chosen currently, but I think it is the native resolution.

#### How will you/everyone benefit from this feature?
_This feature will help us colonize the galaxy!_

**Comment by TiA4f8R** [comment] 2021-09-26 19:00
Closing as a duplicate of/merging with #1239, which should be applied for livestreams of all streaming services.

**Closed by TiA4f8R** 2021-09-26 19:00 UTC
Labels: enhancement, player, peertube

**Comment by UnlimitedCookies** [comment] 2021-09-26 19:05
I thought this was a peertube specific issue. Seems all services lack the selector. Thanks for merging.
