### ISSUE TITLE
Sharing a playlist with another NewPipe user

### ISSUE THREAD

**Issue by andrei-belkin** [TeamNewPipe/NewPipe#3719] opened 2020-06-02 04:15 UTC
#### Describe the feature you want
I believe it would be great if a NewPipe user could share a playlist they made with another NewPipe user.

Some options I'm seeing are:
1 - Assigning a random public URL (maybe temporary) to the playlist.
2 - Exporting the playlist (just that playlist, not the whole NewPipe database on the device) as a JSON file and importing it on another device.
3 - Sharing the playlist in some form (maybe the same JSON file) on the local network, without actually going into the internet.

#### Is your feature request related to a problem? Please describe it

Say, I made a playlist and want to watch it on another device. That's impossible to do at this point in time (as of June 2nd, 2020) without having to export and import the whole NewPipe database that's stored on the device, which is a privacy threat to me.

#### Additional context

N/A

#### How will you/everyone benefit from this feature?

There are multiple use cases for such a feature. Here are some of them:
- Sharing a playlist with a friend.
- Watching the playlist on another device (like an Android TV or a tablet).
- Sending the playlist to someone for a more serious matter (for example, it could be an aggregation of public videos regarding a particular topic: political speeches, TV shows, an artist album, videos serving as proof of some fact, etc).

In my case, all I want at this moment is to watch a large playlist I made (over a hundred videos) on another device (the playlist is stored on my phone and I often want to watch it on my Android TV).

**Comment by Stypox** [comment] 2020-06-02 19:25
Duplicate of #1788. I am adding your description there though, since it is well built. Thank you for the report!

**Closed by Stypox** 2020-06-02 19:25 UTC
Labels: enhancement
