### ISSUE TITLE
Add support for YT shorts links

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#7961] opened 2022-02-27 16:17 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

This issue is an improved version of #7955.

Sharing a YT-shorts link like https://youtube.com/shorts/twc57bBb4AY?feature=share to NewPipe is not working because NewPipe doesn't support the link-format.

### Why do you want this feature?

See #7995

### Additional information

Demo video by @SameenAhnaf:

https://user-images.githubusercontent.com/79245641/155879368-d347236e-4666-462c-bd15-2c678973f40d.mp4

**Comment by cmtrkr83** [comment] 2022-02-28 06:41
Not only shorts link... All youtube link open in my browser.

**Comment by ravilov** [comment] 2022-02-28 12:00
This was addressed back in #7130 and is certainly working without issues for me. Heck, now sometimes links get open in NP even when I don't want them to. 🙂 I would suggest you check your system settings, perhaps NP​ isn't set to be allowed to handle certain links.

**Comment by AudricV** [comment] 2024-02-11 14:53
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Like marked above, this issue is a duplicate of #7130. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2024-02-11 14:53 UTC
Labels: feature request
