### ISSUE TITLE
`Default resolution` selector should `Show higher resolutions`

### ISSUE THREAD

**Issue by Obscure2020** [TeamNewPipe/NewPipe#8036] opened 2022-03-14 20:31 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I propose that the behavior of the `Default resolution` option in the **Video and audio** settings should be changed.

If the option `Show higher resolutions` has been enabled, the `Default resolution` selector should add the options `1440p`, `1440p60`, `2160p`, and `2160p60`.

### Why do you want this feature?

I have a OnePlus 8 Pro. Its display resolution is 1440x3168.

If I have `Show higher resolutions` disabled, I get 1080p video. That's too low.
If I have `Show higher resolutions` _enabled_, I get 2160p video. That's too _high_.

I want to be able to enable `Show higher resolutions` and then set `Default resolution` to `1440p60` so I always get the best resolution for my phone, and never get higher than I need.

### Additional information

This is more of a pet peeve than a feature request, but I thought I'd mention it:

In the Settings menu, the `Video and audio` and `History and cache` options should be changed.
They should read `Video and Audio` and `History and Cache`.

It's a subtle difference.
Trust me, it'll look better.

**Comment by mhmdanas** [comment] 2022-03-14 20:39
This is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2941.

> This is more of a pet peeve than a feature request, but I thought I'd mention it:
>
> In the Settings menu, the Video and audio and History and cache options should be changed.
They should read Video and Audio and History and Cache.

Hmm, I prefer how it is now, but I don't mind much either way. Also, you should avoid mentioning unrelated things in the issue.

**Closed by mhmdanas** 2022-03-14 20:39 UTC
Labels: enhancement
