### ISSUE TITLE
Resizing the app when in split screen mode causes a crash

### ISSUE THREAD

**Issue by franzalex** [TeamNewPipe/NewPipe#7716] opened 2022-01-29 17:21 UTC
### Checklist

- [x] I am using the latest version - 0.21.15 (Was using the latest version at the time the issue was created)
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open NewPipe
2. Enable split-screen
3. Open another app; NewPipe should now be at the top pane
4. Adjust the slider upwards to reduce the size of the NewPipe pane

### Actual behavior

The application crashes at step 4 when the upper pane (with NewPipe) gets very small.

### Expected behavior

The application isn't supposed to crash.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GH
* __Content Language:__ en
* __App Language:__ en_GH
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.PlaybackParameters org.schabi.newpipe.player.Player.getPlaybackParameters()' on a null object reference
	at org.schabi.newpipe.player.PlayQueueActivity.onCreateOptionsMenu(PlayQueueActivity.java:106)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4206)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3084)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:807)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7730)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```
</details>

### Device info

 - Android version/Custom ROM version: Android 11
 - Device model: Sony Xperia 10II

**Comment by litetex** [comment] 2022-01-30 16:03
Thank you for the issue.

Could you please fill out the issue according to the template (see https://github.com/TeamNewPipe/NewPipe/issues/new?assignees=&labels=bug&template=bug_report.md)

**Comment by slasherfun** [comment] 2022-04-18 14:17
Duplicate of #6078? The crash log is almost identical.

**Comment by litetex** [comment] 2022-04-27 18:32
Fixed by https://github.com/TeamNewPipe/NewPipe/pull/8244

**Closed by litetex** 2022-04-27 18:32 UTC
Labels: bug
