### ISSUE TITLE
Viewing YouTube comments with replies

### ISSUE THREAD

**Issue by vrgovinda** [TeamNewPipe/NewPipe#7965] opened 2022-02-28 06:17 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

While viewing the comments to a video, we don't get to the conversation that sometimes ensues after the comment. Sometimes, there are interesting replies with reference to external links, etc... That would be a great feature that hasn't seen the light of the day yet.

### Why do you want this feature?

It would be a wonderful feature to have in Newpipe.

### Additional information

Nothing.

**Comment by SameenAhnaf** [comment] 2022-02-28 12:02
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/2277

**Comment by litetex** [comment] 2022-02-28 18:50
> I made sure that there are no existing issues

No, duplicate

**Closed by litetex** 2022-02-28 18:50 UTC
Labels: enhancement
