### ISSUE TITLE
[Feature request] Sort by duration 

### ISSUE THREAD

**Issue by Wacek** [TeamNewPipe/NewPipe#2694] opened 2019-10-05 17:04 UTC
I know sorting by date is currently being discussed but could duration be added as well? Sometimes it is really useful and handy to have that possibility. For example I use yt all the time to listen to university talks, lectures etc and it is really working great  however it is  often frustrating as hell when you want to find a talk from a legitimate institution because first you have to sift through hundreds of short uploads by some nonames, and having the ability to sort by duration really helps with that, since any serious lecture or talk usually lasts close to an hour or longer. Adding "lecture" or " talk" into the search box really doesn't help much since most institutions almost never include such words in the title.  What would be even better is to have the feature of searching videos above certain duration combined with sorting by date so that I could stay on top with any new uploads
Maybe NewPipe could even periodically show me a popup informing me about any new upload with speciffic parameters ;)?

**Comment by opusforlife2** [comment] 2020-08-12 19:53
Duplicate of #2251.

**Closed by opusforlife2** 2020-08-12 19:53 UTC
Labels: enhancement
