### ISSUE TITLE
Brief pause in audio when switching apps

### ISSUE THREAD

**Issue by joelcieslar** [TeamNewPipe/NewPipe#6011] opened 2021-04-06 00:50 UTC
### Checklist

- [x] I am using the latest version - v0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to `Settings` -> `Video and Audio` -> `"Minimize on app switch"` and set this to _"minimise to background player"_
2. Choose a video with audio
2. Press play
3. Minimise app/return to home screen

### Actual behaviour

- There is a brief pause in audio playback for a couple of seconds

### Expected behavior

-  Audio should continue playing without interruption when switching apps

### Device info

 - Android version/Custom ROM version: MIUI 12.2.5
 - Device model: Xiaomi Mi 10

**I am not sure if this is an issue with the app, or perhaps my configuration of the app, although I couldn't find anything obvious in the settings.**

**Comment by mhmdanas** [comment] 2021-04-06 06:27
Duplicate of #5016.

**Closed by mhmdanas** 2021-04-06 06:27 UTC
Labels: bug
