### ISSUE TITLE
YouTube subscribtions CSV format

### ISSUE THREAD

**Issue by ltokdilli** [TeamNewPipe/NewPipe#6932] opened 2021-08-16 08:35 UTC
Hello,
YouTube subscribtions info were coming from Google, JSON format in the past. 
YouTube subscribtions info are coming CSV format now. 
Could you please make NewPipe is set to read CSV format.

**Comment by mhmdanas** [comment] 2021-08-16 12:04
Duplicate of #6757. Also, please don't remove the template next time you open an issue.

**Closed by mhmdanas** 2021-08-16 12:04 UTC
Labels: bug
