### ISSUE TITLE
Make queue editor use the entire screen in portrait mode

### ISSUE THREAD

**Issue by AlertSubject** [TeamNewPipe/NewPipe#7324] opened 2021-10-28 23:42 UTC
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
Make use of the portrait modes screen size when editing a queue

#### Why do you want this feature?
Currently the queue editor / overview only covers the size of the video playing when in portrait mode (which is not a lot of space) 
This really means that a lot is screen space is not used and makes rearranging items very difficult. 
I'm obviously not gonna read comments while editing my queue so there isn't really a reason to not make use of the rest of the screen

Usability would be improved massively for people who just queue their videos right from their feed before playing them all

**Comment by litetex** [comment] 2021-11-01 21:59
Duplicate of #5235

**Closed by litetex** 2021-11-01 21:59 UTC
Labels: enhancement
