### ISSUE TITLE
Broken sub counters in search results

### ISSUE THREAD

**Issue by alxthecomrade** [TeamNewPipe/NewPipe#1899] opened 2018-11-22 19:38 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.

**Comment by TobiGr** [comment] 2018-11-22 20:51
Please give more information / post a screenshot and tell us which content country and language you have set in the options. Ideally, tell us the expected sub count  :)

**Comment by gkeegan** [comment] 2018-11-23 01:51
Duplicate of #1672. Update Newpipe to version 14.2. If you are currently on 14.2, then please elaborate on the issue as @TobiGr said.

**Comment by alxthecomrade** [comment] 2018-11-23 04:46
Some channels have way over 100m subs! Country of browsing: Russia
Language: English

**Comment by alxthecomrade** [comment] 2019-01-04 17:38
Sorry for not replying so long.

I just reinstalled it a couple of days ago, and now the counters seem to be
okay. Thank you!

**Closed** 2019-08-28 21:00 UTC
