### ISSUE TITLE
App/UI Crashed

### ISSUE THREAD

**Issue by aoGFX** [TeamNewPipe/NewPipe#2458] opened 2019-07-12 03:39 UTC
- [yes] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [yes] I checked if the issue/feature exists in the latest version.
- [yes] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.16.2
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.ReCaptchaActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #9: Error inflating class EditText
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3108)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #9: Error inflating class EditText
Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class EditText
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 50: TypedValue{t=0x2/d=0x7f040201 a=-1}
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:946)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.widget.TextView.<init>(TextView.java:1313)
	at android.widget.EditText.<init>(EditText.java:106)
	at android.widget.EditText.<init>(EditText.java:102)
	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
	at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114)
	at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
	at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1034)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:898)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1034)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:898)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at org.schabi.newpipe.ReCaptchaActivity.onCreate(ReCaptchaActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
android.view.InflateException: Binary XML file line #14: Binary XML file line #9: Error inflating class EditText
Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class EditText
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 50: TypedValue{t=0x2/d=0x7f040201 a=-1}
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:946)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.widget.TextView.<init>(TextView.java:1313)
	at android.widget.EditText.<init>(EditText.java:106)
	at android.widget.EditText.<init>(EditText.java:102)
	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
	at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114)
	at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
	at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1034)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:898)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1034)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:898)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at org.schabi.newpipe.ReCaptchaActivity.onCreate(ReCaptchaActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
android.view.InflateException: Binary XML file line #9: Error inflating class EditText
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 50: TypedValue{t=0x2/d=0x7f040201 a=-1}
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:946)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.widget.TextView.<init>(TextView.java:1313)
	at android.widget.EditText.<init>(EditText.java:106)
	at android.widget.EditText.<init>(EditText.java:102)
	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
	at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114)
	at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
	at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1034)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:898)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1034)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:898)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at org.schabi.newpipe.ReCaptchaActivity.onCreate(ReCaptchaActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
java.lang.UnsupportedOperationException: Failed to resolve attribute at index 50: TypedValue{t=0x2/d=0x7f040201 a=-1}
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:946)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.widget.TextView.<init>(TextView.java:1313)
	at android.widget.EditText.<init>(EditText.java:106)
	at android.widget.EditText.<init>(EditText.java:102)
	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
	at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114)
	at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
	at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:811)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1034)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:898)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1034)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:898)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at org.schabi.newpipe.ReCaptchaActivity.onCreate(ReCaptchaActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```
</p></details>
<hr>

**Comment by gkeegan** [comment] 2019-07-12 04:06
Please use the bugreport to markdown converter from [this site](https://teamnewpipe.github.io/CrashReportToMarkdown/) and edit your issue accordingly. This makes it easier to read. 

Also, could you explain what you were doing or steps that can be done to recreate the crash?

**Comment by aoGFX** [comment] 2019-07-12 16:11
@gkeegan Done 👌🏻

**Comment by gkeegan** [comment] 2019-07-12 19:12
Thanks for the edit. Could you explain what you were doing when it gave the error?

**Comment by aoGFX** [comment] 2019-07-13 00:33
@gkeegan
When open any video.
From homepage or from search.
I cleared data and still.
But now its working well. I didnt do anything.

**Comment by SnwMds** [comment] 2019-07-25 11:21
I was having this same problem.

_I tried to clear the cache and forcing the application to stop, but it didn't help me. The problem persisted.
_ 
_I tried to clear all the data and forcing the application to stop, but it did not help me. The problem persisted._ 

The problem was only resolved after I uninstalled and re-installed the New Pipe.

I'm basically in the same operating environment specified by @aoGFX. The only difference is that I'm using Android 8.1 - 27.

**Comment by Stypox** [comment] 2019-10-01 19:44
Duplicate of #2484, it was a problem with the ReCaptcha page that has now been fixed

**Closed by Stypox** 2019-10-01 19:44 UTC
