### ISSUE TITLE
Popup mode 

### ISSUE THREAD

**Issue by qol3m** [TeamNewPipe/NewPipe#8308] opened 2022-04-30 00:03 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Play video in popup mode

### Expected behavior

Phone can be used in the background of the popup

### Actual behavior

Phone cannot be used in the background of the popup. Nothing can be tapped/selected while the video is playing. (inside the popup I can still tap stuff)

 Even when going back into regular mode it sometimes gets stuck and the screen is unresponsive, displaying the home screen (the bottom keys still work and so does pulling down from the notification bar, which lets me quit newpipe and end the "screen freeze").

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy A52s 5G

### Additional information

I debloated my phone by disabling a lot of apps, but I always do that and Newpipe works on my other phones.

**Comment by SameenAhnaf** [comment] 2022-04-30 00:26
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6770

**Closed** 2022-04-30 04:35 UTC
Labels: bug
