### ISSUE TITLE
v0.19.0 crashes as soon I open the app

### ISSUE THREAD

**Issue by Jona-D** [TeamNewPipe/NewPipe#3303] opened 2020-03-30 15:17 UTC
I was previously using v0.18.5 which was working fine for me, now after updating the app crashes as soon as I open it. I'm unable to even get into the app to backup my data. Please help.

### Version

- v0.19.0

### Steps to reproduce the bug

1. Open app

### Expected behavior
Open the app without it crashing.

### Actual behaviour
The app crashes as soon as I open it.

### Screenshots/Screen records
None.

### Logs
If your bug includes a crash, please head over to the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/). Copy the result. Paste it here:
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ US
* __Service:__ none
* __Version:__ 0.19.0
* __OS:__ Linux samsung/d2qsq/d2q:10/QP1A.190711.020/N975USQU2BTA9:user/release-keys 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | NOT NULL constraint failed: streams_new.uploader (code 1299 SQLITE_CONSTRAINT_NOTNULL[1299])
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:209)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7770)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: streams_new.uploader (code 1299 SQLITE_CONSTRAINT_NOTNULL[1299])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1066)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2322)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2249)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
	at org.schabi.newpipe.database.Migrations$2.migrate(Migrations.java:84)
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:87)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:124)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:493)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:391)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:452)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:275)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:304)
	at androidx.room.util.DBUtil.query(DBUtil.java:54)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$10.call(FeedDAO_Impl.java:499)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$10.call(FeedDAO_Impl.java:496)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: streams_new.uploader (code 1299 SQLITE_CONSTRAINT_NOTNULL[1299])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:1066)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2322)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2249)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
	at org.schabi.newpipe.database.Migrations$2.migrate(Migrations.java:84)
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:87)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:124)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:493)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:391)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:452)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:275)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:304)
	at androidx.room.util.DBUtil.query(DBUtil.java:54)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$10.call(FeedDAO_Impl.java:499)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl$10.call(FeedDAO_Impl.java:496)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</p></details>
<hr>

**Comment by XiangRongLin** [comment] 2020-03-30 18:01
@mauriciocolli @Stypox @TobiGr 
[This](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/database/Migrations.java#L78) should be the cause of that crash.
What wonders me more is how your database has a null value for the upload field of one of your streams and if you will be the only one with this problem.

Concerning restoring your data, if you have root access it would be very easy to get the data.
If not you'll have to follow some steps involving adb (https://stackoverflow.com/a/15559278). If you have no clue what that means, i can give a more detailed guide.

**Comment by mauriciocolli** [comment] 2020-03-30 18:10
@XiangRongLin yes, I was about to push a fix for this.

@TobiGr @Stypox we'll have to release a hotfix ASAP.

I was also writing some debug steps for @Jona-D, including that backup command, for him to at least be able to downgrade the app. Then he could just export the database and test the fix in a debug version. If he's not able to, we could also provide a signed release version with a fix for him to test it.

I'll open a pull request in a bit.

**Comment by TakuyaSama** [comment] 2020-03-30 18:24
> @mauriciocolli @Stypox @TobiGr
> [This](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/database/Migrations.java#L78) should be the cause of that crash.
> What wonders me more is how your database has a null value for the upload field of one of your streams and if you will be the only one with this problem.
> 
> Concerning restoring your data, if you have root access it would be very easy to get the data.
> If not you'll have to follow some steps involving adb (https://stackoverflow.com/a/15559278). If you have no clue what that means, i can give a more detailed guide.

I have the same issue here. I updated from NewPipe 0.18.7.

LineageOS 17.1 (based on AOSP 10).

**Comment by TobiGr** [comment] 2020-03-30 18:42
@mauriciocolli Please notify me as soon as you have a fix. I'll release a new version asap. For now, I have opened https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6557 to mark the F-Droid update as unstable.

**Comment by mauriciocolli** [comment] 2020-03-30 18:45
Hey, @TakuyaSama, can you do some tests then? Since you use a custom ROM, can you transfer the database from your current version into this debug version?

If so:
1. Install this version: [v0.19.0-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4404802/v0.19.0-debug.apk.zip)
2. Copy the database from your current version into the debug one.
     Should be as easy as copying from `/data/data/org.schabi.newpipe/databases` to `/data/data/org.schabi.newpipe.debug/databases`.
3. Open the app and see if the migration went well.

It should be pretty much fixed, but it's good to have some confirmation.

**Comment by TobiGr** [comment] 2020-03-30 20:02
@Jona-D @TakuyaSama Did you try @mauriciocolli' apk? I am waiting for a response. I'd like to get the new version out with some testing.

**Comment by Jona-D** [comment] 2020-03-30 20:23
> @Jona-D @TakuyaSama Did you try @mauriciocolli' apk? I am waiting for a response. I'd like to get the new version out with some testing.

I just installed the apk that @mauriciocolli posted & imported a old backup file that I had saved. Everything seems to be working fine using the debug apk, no crashes so far. @TobiGr

**Comment by AndhikaWB** [comment] 2020-03-30 20:29
I just tested @mauriciocolli debug APK and after importing databases from NewPipe 0.18.7 everything seems to be there (watch history, search history, bookmarks, and playlists).

**Comment by TobiGr** [comment] 2020-03-30 21:02
@AndhikaWB Did you see the crash, too?

**Comment by AndhikaWB** [comment] 2020-03-31 04:12
> @AndhikaWB Did you see the crash, too?

Using @mauriciocolli debug build? No.

Using 'official' pre-release build? No (by updating from 0.18.7).

Fun fact: I'm also using LineageOS 17.1

**Comment by 0xACE** [comment] 2020-03-31 12:32
* 0.18.7 - was fine for me
* 0.19.0 - I had the exact error message/problem as OP
* 0.19.1 - has fixed this problem for me.

I'd wager you can close this issue now.

**Closed** 2020-03-31 12:39 UTC
Labels: ASAP, bug

**Comment by TakuyaSama** [comment] 2020-03-31 13:22
> Hey, @TakuyaSama, can you do some tests then? Since you use a custom ROM, can you transfer the database from your current version into this debug version?
> 
> If so:
> 
>     1. Install this version: [v0.19.0-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/4404802/v0.19.0-debug.apk.zip)
> 
>     2. Copy the database from your current version into the debug one.
>        Should be as easy as copying from `/data/data/org.schabi.newpipe/databases` to `/data/data/org.schabi.newpipe.debug/databases`.
> 
>     3. Open the app and see if the migration went well.
> 
> 
> It should be pretty much fixed, but it's good to have some confirmation.

Sorry for the late reply. I tested it yesterday just before go to bed, and i couldn't reply here just after that.

I still got the issue, following your instructions with the debug app, but the 0.19.1 hotfix version solved my crash.

> @Jona-D @TakuyaSama Did you try @mauriciocolli' apk? I am waiting for a response. I'd like to get the new version out with some testing.

Sorry for my delayed response. I tried and i still got the crash with the debug APK, but everything's working fine with the 0.19.1 hotfix release, thank you very much :).
