### ISSUE TITLE
Suggest new videos to watch

### ISSUE THREAD

**Issue by AlertSubject** [TeamNewPipe/NewPipe#7145] opened 2021-09-22 13:22 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
I'd like to see a new screen being added that suggests you videos to watch 
I'd like to be able to select a few of my favorite channels and then want to be presented with some older videos, or videos I haven't watched in some time 
Basically a random way of re-watching old videos. 
This way there can be suggestions without the need for data collection 

Either random Videos suggestions 
Or 
Old videos from channels you've watched the most (based on watch history) 
Or 
Select your favorite channels and get presented old videos you haven't seen in a while 

Optionally, also describe alternatives you've considered.
Example: *Z is also a good alternative. Not as good as Y, but at least...* or *I considered Z, but that didn't turn out to be a good idea because...* -->

#### How will you/everyone benefit from this feature?
This feature will make newpipe more interesting to use when you have finished watching your chronological feed
Sometimes you just want to continue watching some more videos. In other apps this would be achieved by taking in your watch history and suggestions new content based on that
Newpipe obviously doesn't do that. My suggested way of doing it would enable us to get some suggestions to keep watching.

**Comment by SameenAhnaf** [comment] 2021-09-22 16:15
>Old videos from channels you've watched the most (based on watch history)

'History' already has that functionality. The ability to access drawer from any page is already suggested in https://github.com/TeamNewPipe/NewPipe/issues/6194#issuecomment-828585330 and "History" should be easily accessible from there.

>Select your favorite channels and get presented old videos you haven't seen in a while

I'd rather have #6440 instead as the playback progress can be easily checked from each video's thumbnail. So, watched and unwatched videos should not be hard to differenciate. Also, video suggestions will be free from unnecessary dependence on history.

**Comment by AlertSubject** [comment] 2021-09-22 17:59
The history tab doesn't allow me to search for videos of channels that I haven't watched in some time. It only allows to sort by recently watches or oldest entries first

I just want to be suggested watched / unwatched videos based on which channels I have watched the most in recent history

Such a behavior doesn't exist in the current history tab

**Comment by litetex** [comment] 2021-09-22 19:51
Duplicate of #2256

**Closed by litetex** 2021-09-22 19:51 UTC
Labels: enhancement
