### ISSUE TITLE
You can add this options in a big update?

### ISSUE THREAD

**Issue by esp2019** [TeamNewPipe/NewPipe#6475] opened 2021-06-11 12:58 UTC
-Option to download videos with original and full resolution thumbnail embedded.

-the same option but with audio.

-mp3 option audio fomat.

I think this will be convenient for the app beacuse other similar app have errors with this.

**Comment by SameenAhnaf** [comment] 2021-06-11 13:14
>-Option to download videos with original and full resolution thumbnail embedded.
>
>-the same option but with audio.

Duplicate of #5445 

>-mp3 option audio fomat.

Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1059.

Also, please don't remove the template and fill in it properly. Also, check duplicates before opening an issue.

**Comment by esp2019** [comment] 2021-06-11 13:17
Ok, sorry, i don know if the issue of the titles of spanish viadeo titles translated to english is opened, 8s other problem

**Comment by mhmdanas** [comment] 2021-06-13 09:38
@esp2019 It is as @SameenAhnaf says, except that the third point is a duplicate of #507, not #1059. Thanks!

**Closed by mhmdanas** 2021-06-13 09:38 UTC
