### ISSUE TITLE
Youtube pushing harder against "non-authorized" apps?- only VPN works

### ISSUE THREAD

**Issue by cammeltech** [TeamNewPipe/NewPipe#2808] opened 2019-11-17 08:35 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Newpipe stopped working a few days ago. I use it since one Year (mostly) without any problem.
Now I can search for videos in NewPipe, but I'am unable to play any of them (example bug report below - of course - also transmitted with newpipes bugreport System).

If I connect via VPN, all works fine. This occours on all my devices (2 x Stock Android, 1 x Lineage with Android 9), and on all apps (NewPipe, Skytube, Skytube Extra). If I use a Browser I have to solve captchas and Youtube show me the messsage as shown in the screenshot below (refering to "non-authorized apps". I think some of the closed issus (Example: #2662) refer to the same cause. But the problems there lasted only a few days. In my case, it is now 3 days. I fear Youtube is pushing harder against alternative apps.

Is there a workaround without VPN? Anyone with similar problems?

{
  "user_action": "requested stream",
  "request": "https:\/\/www.youtube.com\/watch?v=tAGnKpE4NCI",
  "content_language": "GB",
  "service": "YouTube",
  "package": "org.schabi.newpipe",
  "version": "0.17.4",
  "os": "Linux Android 8.1.0 - 27",
  "time": "2019-11-17 07:53",
  "exceptions": [
     "java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerConfig(YoutubeStreamExtractor.java:660)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:638)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)\n\tat java.lang.Thread.run(Thread.java:764)\n"
  ],
  "user_comment": ""
}

![Screenshot_20191117-082618](https://user-images.githubusercontent.com/47948096/69004860-f5269400-0919-11ea-83a6-fd43340489c3.png)
![Screenshot_20191116-210408](https://user-images.githubusercontent.com/47948096/69004863-f952b180-0919-11ea-88bc-5ddeeefad214.png)

**Comment by Stypox** [comment] 2019-12-03 14:31
Duplicate of #2787

**Closed by Stypox** 2019-12-03 14:31 UTC
