### ISSUE TITLE
Long playlists yet again not loading

### ISSUE THREAD

**Issue by giniyo** [TeamNewPipe/NewPipe#5754] opened 2021-03-04 17:22 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Try load any playlist with 100+ songs, play in background
2. Open background playlist, scroll down

### Actual behaviour

It will stop prematurely after not even half the songs are loaded

### Expected behavior

It will usually stop, load more songs, stop, until you reach the end of the playlist

### Logs

I've also tried de-installing and re-installing previous version and current version, no change.

### Device info

 - Android version/Custom ROM version: Android 11 updated last 20th feb 2021
 - Device model: Samsung Galaxy S10

**Comment by mhmdanas** [comment] 2021-03-04 17:29
Thanks for opening an issue! I believe this is a duplicate of #5739. If you believe I'm wrong, feel free to write a comment.

**Closed by mhmdanas** 2021-03-04 17:29 UTC
Labels: bug
