### ISSUE TITLE
proposal: temporary ban for duplicate posted of issue on 1st page of issues (most recent)

### ISSUE THREAD

**Issue by infinitewaveparticle** [TeamNewPipe/NewPipe#7764] opened 2022-02-01 14:33 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
could you implement a policy of temprary ban for any duplicate posted for an open issue located on the first page of issues (most recent ones so no excuse)? follow this with a permanent ban for the 3rd such offense or for bitching about it like a crybaby

**Comment by litetex** [comment] 2022-02-03 20:48
I think the implementation of #6941 would also help a lot because nearly every duplicate of #7734 has a ``template-ignored`` or ``template-missing`` flag.

**Comment by SpiritAxolotl** [comment] 2022-02-08 04:12
Good idea. Can't believe some people don't put any effort into just looking/searching for duplicates of their issue, _**even on the first page.**_ Fully support this.

**Comment by opusforlife2** [comment] 2022-02-12 14:06
We're working on issue forms right now. Let's see how far that solves the problem. If the problem still persists, then we can re-open this and think some more.

Closing for now.

**Closed by opusforlife2** 2022-02-12 14:06 UTC
Labels: discussion, meta
