### ISSUE TITLE
Add advanced search

### ISSUE THREAD

**Issue by Add-1** [TeamNewPipe/NewPipe#5034] opened 2020-11-29 11:29 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
By adding advanced search, I believe it will improve the user experience!
Things like: Sort by; Search by date; Duration; Location (country).

These things are very useful when looking for something specific

I hope you implement this

Thanks

**Comment by mhmdanas** [comment] 2020-11-30 13:26
Duplicate of #110.

**Closed by mhmdanas** 2020-11-30 13:26 UTC
Labels: enhancement
