### ISSUE TITLE
MPEG 720 resolution videos are not loading.

### ISSUE THREAD

**Issue by Taratect** [TeamNewPipe/NewPipe#6424] opened 2021-06-04 11:05 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

These are the links I found videos where 720p to keep loading despite loading desc n comments:

https://youtu.be/GDKVtWikC50
https://youtu.be/YlXbDoysa1I

### Actual behaviour

The video keeps on loading even tho there is a good connection and I can watch it seamlessly on other browser.

### Expected behavior

The video should load fine.

### Logs

No log

### Device info

 - Android version/Custom ROM version: Android 10 (MIUI 11)
 - Device model: Redmi 8

**Comment by EthanZeigler** [comment] 2021-06-07 12:44
Another example: https://www.youtube.com/watch?v=Ea9xIxbB1lA. Happy to provide any other information. Im on a google pixel 3 running the latest version as of this comment through fdeikd. Just checked.

**Comment by opusforlife2** [comment] 2021-06-07 16:40
@Taratect Both videos load at 720p for me. But the first video took some time before it started. And the second video took even longer (like 10+ and 15+ seconds).

@EthanZeigler Your video loaded instantly for me.

Sometimes Newpipe gets stuck loading a particular resolution, which a restart of the app (after swiping away from Recents) can fix. Sure it's not that?

**Comment by EthanZeigler** [comment] 2021-06-07 21:54
It certainly could be, but that wasnt fixing it for me last night. If I can find a good way to reproduce this I will follow up with the procedure. 

Its also possible this was an issue on YT's side given it was a specific resolution, wasn't directly after the release of an app update, multiple people experienced it, and I'm unable to find anything out of the ordinary right now.

**Comment by Taratect** [comment] 2021-06-09 08:57
@opusforlife2 , ya I'm aware that restarting the app fixes some videos. I use this method because newpipe starts buffering after watching 3 or 4 vids. But the links I gave here didn't work for me at the time. Now I can play the vids though it lags a little.

The loading problem changes randomly and so it's hard to reproduce. Like one link I found is this https://www.youtube.com/watch?v=tqViKzepqkY&t=509.  

I think the problems lies in something else rather than individual videos. Also it's kinda annoying to restart the app after watching a few vids

**Comment by markochk** [comment] 2021-06-09 10:31
> The loading problem changes randomly and so it's hard to reproduce. Like one link I found is this which is still not loading.
> https://www.youtube.com/watch?v=tqViKzepqkY&t=509.

I'm also unable to open this video in 720p (1080p, 480p and other resolutions work fine).

Another video I've found that isn't loading in 720p is this: https://www.youtube.com/watch?v=WaRcH8K7yY8

Newpipe version: 0.21.4
Android 9 (Custom ROM)
Device: Huawei Honor 6X

**Comment by opusforlife2** [comment] 2021-06-11 09:02
> I think the problems lies in something else rather than individual videos.

Probably.

**Comment by dev-a** [comment] 2021-06-11 10:47
I confirm that I also have this problem
and it also happens when we change the quality 
 I did not try to switch to other formats like webm

**Comment by opusforlife2** [comment] 2021-06-11 11:40
Whoops! So sorry guys. I actually absent-mindedly tested all the links with WebM, not MP4. I just opened all the links again after switching the format, and some videos are indeed giving me issues:
- Some open fine.
- Some need to first be loaded in a different resolution before going back to 720p.
- One that doesn't work for me no matter what I do: `https://www.youtube.com/watch?v=WaRcH8K7yY8` discovered by @markochk

**Comment by TiA4f8R** [comment] 2021-06-12 11:03
So, I looked into the issue for videos `tqViKzepqkY` and  `WaRcH8K7yY8` (I can't do it for `Ea9xIxbB1lA` because it's now private) and it seems to be related to codecs. Before my explanation, let me explain that the extractor currently doesn't add the MPEG-4 720p stream which is video-only (itag 136) and uses the MPEG-4 720p with audio and video embedded in the same file (itag 22) (not present for musical videos). (This behavior will be reverted in `TeamNewPipe/NewPipeExtractor#604`.)

- the itag 22 of this video has the following MIME type: `"video/mp4; codecs=\"avc1.64001F, mp4a.40.2\""`. It is not playable, even if on my Windows computer in VLC or in my browsers.
- the itag 18 (MPEG-4 360p, with audio and video embedded in the same file) has the following MIME type: `"video/mp4; codecs=\"avc1.42001E, mp4a.40.2\""`. It plays fine on my browsers and in VLC.
- the itag 136 is also playable and has the following MIME type: `"video/mp4; codecs=\"avc1.4d401f\""`

I don't know if we can do something.

**Comment by opusforlife2** [comment] 2021-06-12 13:04
> This behavior will be reverted in TeamNewPipe/NewPipeExtractor#604

@TiA4f8R Will that not solve the issue?

**Comment by TiA4f8R** [comment] 2021-06-12 15:49
@opusforlife2 No, because we are still using video streams with audio and video embedded in the same file first, then video only streams mixed with audio only streams. So 360p and 720p video only streams are hidden and a change in the app will be needed to show these streams first.

**Comment by opusforlife2** [comment] 2021-06-13 07:16
@TiA4f8R So that just means one more PR on the Newpipe side, right?

**Comment by Donkey-Doug** [comment] 2021-09-17 11:18
Same for me, but the problem has now spread to all MP4 files. Only webp plays now.

**Comment by vehosah** [comment] 2021-12-10 16:09
> Same for me, but the problem has now spread to all MP4 files. Only webp plays now.
> 
> Initially the problem was only for 720p for me as well.

For me neither the webp works

**Comment by vehosah** [comment] 2021-12-10 16:12
Actually nothing is working for me, neither cleaning cache works or restart the app works nor change the resolution works

**Comment by EthanZeigler** [comment] 2021-12-10 21:04
I'm not able to replicate this anymore, but it's absolutely a real problem. The question is why. I feel like it must be a youtube-sided issue and not the app itself, or rather a weird response type that isn't consistent from YT itself.

**Comment by opusforlife2** [comment] 2021-12-11 16:28
Could you all try #6537 to see if it solves this?

**Comment by opusforlife2** [comment] 2022-07-16 07:46
Linking #8153 for posterity.

**Comment by Taratect** [comment] 2023-06-23 09:03
Has anyone having buffering issues on 720p videos again lately? Idk why but some videos buffer at 720 but if I increase or lower the resolution, it plays without any problems. 
The problem is seen in both mpeg and webm.

I found this url as an example
https://www.youtube.com/watch?v=B1MU8DAT4ak&t=0

**Comment by EthanZeigler** [comment] 2023-06-23 14:18
Yep, issue is back. Extremely long buffering times for mpeg 720p specifically. Not unplayable this time oddly but same vein of problem.

**Comment by Taratect** [comment] 2023-06-24 14:43
I think I found a connection. Only videos that has 60fps option available are having this issue where 720p buffers and 720p60fps works fine in WebM and 3gp. Video is playable in MPEG 720p if there is no 60fps option is available. However speed is slower in mpeg (which results in buffering sometimes) than webm/3gp. But when there is 60fps is available you cannot watch the video in 720p  as it buffers in every video format unless u change the resolution to 720p60, 1080p60, 480p.

PS: regular 1080p without 60fps is absent in videos that offers 60fps format.

**Comment by EthanZeigler** [comment] 2023-06-24 17:10
> I think I found a connection. Only videos that has 60fps option available are having this issue where 720p buffers and 720p60fps works fine in WebM and 3gp. Video is playable in MPEG 720p if there is no 60fps option is available. However speed is slower in mpeg (which results in buffering sometimes) than webm/3gp. But when there is 60fps is available you cannot watch the video in 720p as it buffers in every video format unless u change the resolution to 720p60, 1080p60, 480p.
> 
> PS: regular 1080p without 60fps is absent in videos that offers 60fps format.

Yep, this matches my experience. Nice find.

**Comment by AudricV** [comment] 2023-06-26 16:37
The new issue described is different than the original one and is a duplicate of #10183. Closing again this issue as it was fixed.

**Closed by AudricV** 2023-06-26 16:37 UTC
Labels: bug
