### ISSUE TITLE
Enqueue in background in context menu when share

### ISSUE THREAD

**Issue by s1awek** [TeamNewPipe/NewPipe#5163] opened 2020-12-12 21:11 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

I noticed that from two versions back the "add to background queue" option disappeared from share the context menu. I often browse the YouTube application and when I find interesting material that I would like to listen to later in Newpipe, I add it to the queue.  

Until recently, I could add any number of video to the queue, but since the two previous updates, I can only listen one video at a time. Sharing new one will remove previously added material from qieue. 

I would like to kindly ask you to restore the add to background queue function to share context menu. I think that this functionality should not be too difficult to implement, at the same time it seems quite important not only for me, but also for all users of the application.

![IMG_20201212_213940](https://user-images.githubusercontent.com/3338469/101994834-e3065900-3cc5-11eb-94cd-785f86ef0651.jpg)
![IMG_20201212_214111](https://user-images.githubusercontent.com/3338469/101994835-e4378600-3cc5-11eb-9183-10f6bd805bc1.jpg)

**Comment by shivasagarrao** [comment] 2020-12-15 21:16
Resetting of background player queue issue #4946

**Comment by Stypox** [comment] 2021-01-15 18:54
duplicate of #4779

**Closed by Stypox** 2021-01-15 18:54 UTC
Labels: enhancement
