### ISSUE TITLE
[For later] Making an optional tutorial on the features of Newpipe

### ISSUE THREAD

**Issue by iamthesenate1** [TeamNewPipe/NewPipe#6251] opened 2021-05-06 20:28 UTC
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

As Newpipe gets more features/changes, not all are enabled by default. As there will be more and more such cases I think it would be a good think if (optional) start tutorials would be a thing. 

#### Is your feature request related to a problem? Please describe it

New features that are not enabled by default could be missed by new users.

#### Additional context

I marked this as "for later" as now there aren't so many such features

#### How will you/everyone benefit from this feature?

The features will be more known to pople so that in the future there wouldn't be feature requests of a feature that has alredy been introduced in the app.

**Comment by mhmdanas** [comment] 2021-05-07 09:48
@iamthesenate1 I think this _is_ a duplicate of #859.

**Closed by mhmdanas** 2021-05-07 09:48 UTC
Labels: enhancement

**Comment by iamthesenate1** [comment] 2021-05-07 10:41
Ok
