### ISSUE TITLE
Please can you fix this error

### ISSUE THREAD

**Issue by kstmm** [TeamNewPipe/NewPipe#7143] opened 2021-09-21 22:31 UTC
https://user-images.githubusercontent.com/49512135/134256177-68b7ca7c-337d-4bba-a307-2993d9e27eab.mp4

**Comment by mhmdanas** [comment] 2021-09-22 19:16
Duplicate of #7059. Also, please don't remove the template when opening an issue.

**Closed by mhmdanas** 2021-09-22 19:16 UTC
Labels: bug
