### ISSUE TITLE
a few issues that are related to the same thing

### ISSUE THREAD

**Issue by panacist** [TeamNewPipe/NewPipe#4464] opened 2020-10-09 15:30 UTC
first i would love to thank you guys for the hard work on this new version !

and look i really appreciate the convincing arguments of @opusforlife2 and the deadly comments of @avently ,but despite that i am still opposing the idea of having two seperate players while watching a video (the main player and the one in the notifications).
nonetheless here are a few issues that i've encountered probably due to that (i might be wrong) :
(initial conditions: no trending page, autoplay is off, and a smile?)

issue number 1:
1. play (in the background) any video 
2. minimize the video
3. press the home button 
4. go back to the app (from recent apps) and maximize the video again

issue number 2:
1. go to youtube music 
2. play (in the background) any piece written by bach or preferably chopin
3. keep pressing the phone's back arrow untill you're out of the app
4. go back to the app (the minimized thing disappears)

issue number 3:
1. play bach again from youtube music
2. go to soundcloud top 50
3. try playing the second song (which is not supported by newpipe)
4. how can i go back to bach's comments ?

(another issue related to this one is that when you press the back arrow you close the stream instead of minimizing it)

issue number 4:
1. play bach again (i'm sorrry about it )
2. go to soundcloud top 50 again
3. press the first song (which is supported by newpipe)
4. why does bach stop playing while autoplay is off?

issue number 5 (not sure how to reproduce):
1. play (in the background) well chopin this time
2. enjoy the music a bit
3. go to soundcloud hot and new
4. press really quickly the first song there
5. and before the tumbnail loads click the big headset icon to play it (not in the background)
6. it will play chopin instead.

**Comment by avently** [comment] 2020-10-09 15:35
Opusforlife2 will be here soon and will close the issue...
But thanks for a great start! I'm not sure how to translate the "deadly comments" but the post is something I wanted to read

**Comment by panacist** [comment] 2020-10-09 15:44
@avently i was just kidding about the deadly comments let's say not "user friendly" ones haha
@opusforlife2 sorry for putting a bunch of issues in the same place again !

**Comment by panacist** [comment] 2020-10-09 15:54
@opusforlife2 an out of subject question : is it fine to post issues that i have no idea how to reproduce?

**Comment by avently** [comment] 2020-10-09 16:14
1. What happens in this case? What's the issue and what mean `(in the background)`?  I'm just tried to open a video in background player with steps provided but didn't find anything unusual
2. Initially I shut down the background player and popup player in this case but later I was asked to leave background player and popup player playing. So I did it. You see the cost. For me it's ok since you can choose any video and not lose the playback state anyway. 
3. Have no idea. The unsupported things are not covered. Better to create a new issue for this one
4. If you have disabled autoplay it will not start playing a new video but will stop previous. Expected behavior
5. Before info is loaded you know only about previous track. After info loads it will be used for playing

**Comment by opusforlife2** [comment] 2020-10-09 16:26
> is it fine to post issues that i have no idea how to reproduce?

@panacist You should, because someone else may find out how to reproduce it. But make sure you give as many details as possible.

**Comment by panacist** [comment] 2020-10-09 16:29
@avently 
1. here is what happens for me :
![Screenshot_20201009-040505](https://user-images.githubusercontent.com/66388840/95607384-3270a480-0a4b-11eb-8a3b-382c0a650252.png)
and in the background is the headset icon 
2. so it isn't to be considered a bug is that what you mean ?
3. sure maybe opus can open an issue (as you may have noticed i am the worst man to describe issues).
4. not an expected behavior !! if you remember i once was having a descussion with you and opus about whether to stop the playing video when chosing to play the next one and opus was like hey you will have time to enjoy the playing video while the other is being loaded. so i just wonder is it not the case here ? giving the assumption that autoplay is off stoping the previous video without my consent is unusual
5. okay then fair enough

**Comment by opusforlife2** [comment] 2020-10-09 16:36
@panacist After you find out which are real issues and which aren't, I expect you'll open separate bug reports for each because, as avently rightly said, I will close this.

**Comment by avently** [comment] 2020-10-09 16:41
2. You can open an issue if you want but I don't think this rare situation should cost hours of finding a solution which don't look ugly
4. If I don't stop the previous video you'll get video working in the background without displaying it. It will load a video (not an audio) which is a bad situation. We didn't talk about this implementation because it has no alternatives
We talked about when to stop the video: right after choosing another or when another one has downloaded info to show. We chose the first way.

**Comment by avently** [comment] 2020-10-09 16:51
1. Show a screenrecord please

**Comment by panacist** [comment] 2020-10-09 16:59
@avently 
2. no need to open an issue you guys have enough already
4. sure thing, i think you and opus flipped roles you are the convincing guy now haha and opus is angry about the template
1. i will provide it as soon as possible.

**Comment by opusforlife2** [comment] 2020-10-09 17:00
Not angry. Just firm in my stance. :3

**Comment by avently** [comment] 2020-10-09 17:03
@opusforlife2 why are you sooooo angry? We just listening people's problems...

**Comment by opusforlife2** [comment] 2020-10-10 12:29
> no need to open an issue

@panacist Open an issue, please. Whether or not someone fixes it is not your problem.

**Comment by opusforlife2** [comment] 2020-10-10 12:31
@avently What is the cause of (2)? Why doesn't the minimised player stay?

**Comment by avently** [comment] 2020-10-10 13:21
@opusforlife2 because when you press back and your backstack is empty, activity with all fragments gets destroyed (mini player located inside a fragment). After returning back you have a blank activity without loaded videodetailsfragment

**Comment by opusforlife2** [comment] 2020-10-10 13:26
@avently Okay. Can there be a condition added that if the foreground service is active/playing a stream, not to close the minimised player on back press? The entire point of the minimised player was that it would let streams play uninterrupted until the user manually closed it.

**Comment by avently** [comment] 2020-10-10 13:50
@opusforlife2 not like you said, but in a different way. Once new activity gets created the service needs to be found in running processes and in case it's found activity should send a broadcast related to the need to open and connect mini player. The broadcast i'm talking about I added in the last my PR. These are all instructions I can give you. If you know Android it's enough

**Comment by opusforlife2** [comment] 2020-10-10 13:57
@avently Could you open a new issue with these instructions? I'll see if someone can work on it.

**Comment by avently** [comment] 2020-10-10 14:07
@opusforlife2 no, I'm not. You may open if you want.

**Comment by opusforlife2** [comment] 2020-10-10 14:08
>:(

**Comment by opusforlife2** [comment] 2020-10-11 09:01
@panacist I'm closing this. Please open separate issues now.

**Closed by opusforlife2** 2020-10-11 09:01 UTC
Labels: bug, more info needed
