### ISSUE TITLE
Interrupt playing music

### ISSUE THREAD

**Issue by mailsantam** [TeamNewPipe/NewPipe#5578] opened 2021-02-13 18:43 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
The music Interrupt playing for a Short time , 0,5sec if I : 
Play music and :
1- change to another app , for ex. From Newspipe to Gmail or any other
2-lock my phone with ON/OFF button
3-Unlock my phone with ON/OFF Button
4-Change back to Newspipe Ap from any other App

### Device info

 - Android version/Custom ROM version: Android 10/ QSAS30-62-33-8
 - Device model: Motorola One Vision XT1970-3

**Comment by igorcmelo** [comment] 2021-02-15 07:44
Newpipe automatically changes from normal to background if you are watching a video then you minimize the app.
I am not a dev but I believe it is the regular behavior because audio and video are separate streams. 

If you don't want that to happen, press the background button and let the music play on background.

**Comment by mhmdanas** [comment] 2021-02-16 05:14
This is a duplicate of #5016. If I misunderstood feel free to make a comment.

**Closed by mhmdanas** 2021-02-16 05:14 UTC
Labels: bug
