### ISSUE TITLE
Audio sync

### ISSUE THREAD

**Issue by PULFORDASH** [TeamNewPipe/NewPipe#5068] opened 2020-12-02 06:23 UTC
Version 0.20.5

I'm getting the same audio syncing issue as occurred in v 19.5. 
Any video the audio and video fall out of sync. Scrubbing temporarily realigns it. 

The long the video plays the worse the sync issue becomes. 

Thanks guys, really appreciate your work.

**Comment by mhmdanas** [comment] 2020-12-02 06:30
Probably a duplicate of #4472. If it is indeed the same issue, you can fix it by opening the playback speed controls (using the button beside the quality button in the player) and press "reset" at the bottom left. If this did not fix it, please open an issue with the bug template properly filled from [here](https://github.com/TeamNewPipe/NewPipe/issues/new/choose). Thanks!

**Closed by mhmdanas** 2020-12-02 06:30 UTC
