### ISSUE TITLE
Not possible to watch videos on NewPipe

### ISSUE THREAD

**Issue by LukiQu** [TeamNewPipe/NewPipe#7781] opened 2022-02-03 11:51 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Since February 1st I can't watch any more videos on Newpipe because every time I click on one it says "Sorry, something went wrong". I've tried several times to "repair" the app by uninstalling and reinstalling it, but it doesn't work.

**Comment by mhmdanas** [comment] 2022-02-03 12:00
Duplicate of #7734. Update to 0.21.16 to fix the issue.

**Closed by mhmdanas** 2022-02-03 12:00 UTC
Labels: question

**Comment by LukiQu** [comment] 2022-02-03 12:02
I cant find this version on f-droid

**Comment by mhmdanas** [comment] 2022-02-03 12:05
The official F-Droid repo may take some time to release updates. Follow the steps at https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/ to switch to our custom F-Droid repo, which provides updates in a more timely manner.

**IMPORTANT**: when following the steps in the link above, DO NOT FORGET TO EXPORT YOUR DATABASE BEFORE INSTALLING, OR YOU WILL LOSE EVERYTHING.

**Comment by LukiQu** [comment] 2022-02-03 12:07
Thank you! Now it works
