### ISSUE TITLE
Popup Player: Ability to switch to background or fullscreen

### ISSUE THREAD

**Issue by trymeouteh** [TeamNewPipe/NewPipe#3206] opened 2020-03-09 04:49 UTC
Please add a button on the popup player or add a floating button on the left and right of the red closing X button. This way it is easily to switch to the background player or fullscreen player from the popup player.

**Comment by Stypox** [comment] 2020-03-09 07:30
Duplicate of #1832

**Closed by Stypox** 2020-03-09 07:30 UTC
