### ISSUE TITLE
Content localization is still broken

### ISSUE THREAD

**Issue by JCU0** [TeamNewPipe/NewPipe#5572] opened 2021-02-13 12:56 UTC
### Checklist

- [x] I am using the latest version - 0.20.9 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

#3089 looks like possible duplicate, not sure.

### Steps to reproduce the bug

1. Set Russian/Russia in the Content settings field. Also, you may switch all three localization settings to Russia/Russian Federation.
2. Add example channel to your favorites (subscribe) in Newpipe.
3. Check channel name and video titles.
4. Enter the channel via your browser or YouTube app with your language set to Russian.

This animal-related channel is a good example for the bug. It is originally in Russian, but is being translated to English.
https://www.youtube.com/channel/UCwB1KTdX2PNgA4Q79PfOydw

Additional channels with the same problem:
https://www.youtube.com/c/AndreyanovD/videos
https://www.youtube.com/channel/UCJCPyZ49hBMlMPh51vfDkag/videos
In both of these channels most videos are Russian-only, but channel names and some videos are translated to English and the NewPipe app shows an English version.

### Actual behaviour
Channel name looks like "Yoll the Eagle-Owl"
Most of videos are with English titles.

### Expected behavior
Channel name looks like "Yoll"
All videos are titled in Russian (maybe with some English words)

### Device info

1. Galaxy Tab A, Android v9.0
2. Galaxy A6, Android v8.0

**Comment by mhmdanas** [comment] 2021-02-16 05:40
> #3089 looks like possible duplicate, not sure.

I also think this is a duplicate of #3089, so I'll be closing this issue.

**Closed by mhmdanas** 2021-02-16 05:40 UTC
Labels: bug
