### ISSUE TITLE
Clone bookmarked playlists

### ISSUE THREAD

**Issue by yephny** [TeamNewPipe/NewPipe#7347] opened 2021-11-02 07:45 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?

Currently, you can bookmark a playlist but cannot edit it as it belongs to a Youtube account who can update it. This feature would allow the user to clone a bookmarked playlist so that they can work on it. A better way to implement this functionality would be to have an "Add to playlist" option for all videos in a playlist.

For now, there is a workaround: you can open a bookmarked playlist, play it in the background and add the play queue to a new playlist.

#### Why do you want this feature?

When you bookmark a playlist, you can't edit it. It just remains the way it is or might get deleted/modified by whoever has created it. If the user could instead save this playlist to a local one, it would help preserving the playlist while allowing the user to make changes to it.

This feature request is related to #7294.

**Comment by SameenAhnaf** [comment] 2021-11-02 09:17
Duplicate of #3695.

**Comment by litetex** [comment] 2021-11-02 20:13
Duplicate of #3695

**Closed by litetex** 2021-11-02 20:13 UTC
