### ISSUE TITLE
App crashes whenever I try to download content or when I go see my downloads

### ISSUE THREAD

**Issue by ParamonPlay2205** [TeamNewPipe/NewPipe#6920] opened 2021-08-14 02:53 UTC
When ever I try to download a video as an audio or video file. Or whenever I go to the "Downloads" menu the app crashes. This has been occuring for the past 3 recent updates of Newpipe. And after installing the recent updates, I decided to report it.

Log:
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.8
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4209)
	at android.app.ActivityThread.access$1500(ActivityThread.java:242)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1937)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4197)
	... 8 more

```
</details>
<hr>

Version of Newpipe Installed:
NewPipe Version 0.21.8

Device Information:
OS: Android 11
Device: Sony Xperia 5 II

**Comment by mhmdanas** [comment] 2021-08-14 15:23
Duplicate of #6687.

**Closed by mhmdanas** 2021-08-14 15:23 UTC
Labels: bug
