### ISSUE TITLE
Resume playback turn off makes my xiaomi mi a3 force restart

### ISSUE THREAD

**Issue by Haeryzer** [TeamNewPipe/NewPipe#8260] opened 2022-04-19 16:40 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1.go to settings
2.select "history and cache"
3.turn off " resume playback"
4.now, play a any video
5.select another video from section "similar video" 
6. Then crash and force restart

### Affected Android/Custom ROM version

Android 11

### Affected device model

Xiaomi Mi A3

**Comment by TiA4f8R** [comment] 2022-04-19 17:20
> - [x] I made sure that there are _no existing issues_ - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

No, duplicate of #5961. Check (better?) for exisiting duplicates before opening a new issue the next time, please. Thank you.

**Closed by TiA4f8R** 2022-04-19 17:20 UTC
Labels: bug
