### ISSUE TITLE
displays "any button" in the player while the video selected to watch is over the thumbnail

### ISSUE THREAD

**Issue by atuolol** [TeamNewPipe/NewPipe#4804] opened 2020-11-04 22:30 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
show any button on the player above the thumbnail when selecting a video to watch. not only show thumbnails and hide control buttons

#### Is your feature request related to a problem? Please describe it
with the player button not showing, i can't change the resolution, share the video to the browser or close the video immediately

#### Additional context
helps users access multiple button actions, no need to swipe down to find the selected watch video close button

#### How will you/everyone benefit from this feature?
some people can get a quick access button before the video plays. if they make a mistake choose the wrong video they watch. they can close the video without swiping down to tap the close button in minimal player mode.
can change the video resolution before the video plays, and can use the share button to the browser if necessary.

**Comment by opusforlife2** [comment] 2020-11-05 11:00
Duplicate of #4039.

**Closed by opusforlife2** 2020-11-05 11:00 UTC
Labels: enhancement
