### ISSUE TITLE
Video lags on 1080p60

### ISSUE THREAD

**Issue by passwin** [TeamNewPipe/NewPipe#7627] opened 2022-01-07 13:56 UTC
### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1.Go to any video(I used https://www.youtube.com/watch?v=mkggXE5e2yk"
2.Select 1080p60(MPEG4 or WebM Doesn't matter)
3.Play. It's lagging.

### Actual behavior

Video lags on 1080p60.
If device is in power saving mode, 720p lags.

### Expected behavior

Video plays properly without lags.

### Screenshots/Screen recordings

https://drive.google.com/file/d/1B8MO7gDuFsmWAhLR2nuNLjiT7t7omrIp/view?usp=sharing

### Logs

No Logs.

### Device info

 - Android version/Custom ROM version:Lineageos 17.1(QQ3A.200855.001)
 - Device model:a7xelte(SM-A710F)

**Comment by TiA4f8R** [comment] 2022-01-07 14:46
Closing as a duplicate of #7599 (by according to the custom ROM you are using). Please search better for duplicates the next time you open an issue. Thank you!

**Closed by TiA4f8R** 2022-01-07 14:46 UTC
Labels: bug
