### ISSUE TITLE
"Sorry, something went wrong. REPORT"

### ISSUE THREAD

**Issue by phind431** [TeamNewPipe/NewPipe#5100] opened 2020-12-05 11:08 UTC
I get a really stupid message at the bottom of the newpipe window when trying to play pretty much any video at all. 
"Sorry, something went wrong. REPORT", is overlayed on top of the window at the bottom. PLEASE REMOVE THIS OBNOXIOUSLY IRRITATING MESSAGE FROM THE CODE! Everything works fine. Autoplay is disabled. Autoupdate is enabled. The "REPORT" button does nothing. Whatever the hell is triggering it, please STOP already. It interferes with being able to close a video. I don't need a useless error message and there are no problems to begin with! Please remove that error message and allow your user base to get on with their lives.

### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

Error message pops up at the bottom of window and I have to wait for it to go away which interferes with the actual working button commands.

### Expected behavior

I don't expect useless "something went wrong..." messages when in fact NOTHING'S WRONG.
The problem is almost random. Not sure if the feeds themselves are the issue, I suspect, but whatever it is, PLEASE GET RID OF THAT STUPID MESSAGE

### Screenshots/Screen recordings

https://imgpile.com/images/ue7rIh.png

### Device info

 - Android version/Custom ROM version:
Android9 / lineage-16.0-20201107-UNOFFICIAL-microG-signed-oneplus3
 - Device model: oneplus 3t global unlocked, rooted, no google bs (fakestore etc)

**Comment by phind431** [comment] 2020-12-05 11:20
It happens when I hit the play button on practically any video whatsoever. Newpipe's behaviour is different. It used to go into full screen when you hit play. Now it only likes landscape mode for some odd reason. It'd be nice if it went fullscreen in portrait like it used to.

**Comment by mhmdanas** [comment] 2020-12-05 12:37
> I am using the latest version - x.xx.x 

Please specify your NewPipe version. If it is 0.20.5, I suspect this would be a duplicate of #5075, which can be caused by many things, not only opening from a notification.

> PLEASE REMOVE THIS OBNOXIOUSLY IRRITATING MESSAGE FROM THE CODE! 

Please calm down your tone. We have to show this message so that users can send crash logs to us, which are immensely valuable in fixing bugs. Since this message is shown, that means that something, somewhere, is going wrong, even if you see nothing wrong. This bug will hopefully be fixed in the next version.

> The "REPORT" button does nothing.

That is very odd. I'll ask the devs.

**Comment by B0pol** [comment] 2020-12-05 12:45
Comments don't load therefore an error is produced. It's expected that the snackbar show up. Closing for https://github.com/TeamNewPipe/NewPipeExtractor/issues/455

**Closed by B0pol** 2020-12-05 12:45 UTC
Labels: bug, more info needed
