### ISSUE TITLE
[Issue] The "What's New" tab only shows the latest video per channel, instead of an entire feed. 

### ISSUE THREAD

**Issue by glyko54** [TeamNewPipe/NewPipe#3213] opened 2020-03-11 15:34 UTC
For some reason, the "What's New" tab only shows the latest video uploaded by each channel you are subscribed to. I'm not sure if this is intended but I feel like it would be much more convenient if "what's new" showed all recent videos, like the subscription feed on the official YouTube website. 
![image](https://user-images.githubusercontent.com/62068242/76434599-2c7feb80-63b6-11ea-82ee-72961400f0be.png)

I'm sorry for bothering you if such a feed already exists, but I can't find it for the life of me. 
What do y'all think? 
And thank you very much for your great work!

**Comment by Stypox** [comment] 2020-03-11 15:50
Duplicate of #822

**Closed by Stypox** 2020-03-11 15:50 UTC
