### ISSUE TITLE
SoundCloud playback results in error.

### ISSUE THREAD

**Issue by nahteyamashita** [TeamNewPipe/NewPipe#3516] opened 2020-05-02 23:42 UTC
Title explains the problem pretty well. Error text as seen below.

{
   "user_action": "requested stream",
   "request": "https:\/\/soundcloud.com\/jacksqrd\/homestuck-sunslammer-cover",
   "content_language": "US",
   "service": "SoundCloud",
   "package": "org.schabi.newpipe",
   "version": "0.19.2",
   "os": "Linux Android 10 - 29",
   "time": "2020-05-02 23:40",
   "exceptions": [
      "org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveFor(SoundcloudParsingHelper.java:119)\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudStreamExtractor.onFetchPage(SoundcloudStreamExtractor.java:45)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:65)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:61)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:120)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\nCaused by: com.grack.nanojson.JsonParserException: Expected JSON value, got EOF on line 1, char 0\n\tat com.grack.nanojson.JsonParser.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonParser.currentValue(Unknown Source:30)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:3)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:15)\n\tat org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveFor(SoundcloudParsingHelper.java:117)\n\t... 30 more\n"
   ],
   "user_comment": ""
}

**Comment by gkeegan** [comment] 2020-05-02 23:55
Please follow the issue template and use the bug report to markdown converter.

**Comment by Stypox** [comment] 2020-05-03 08:18
Duplicate of #2915

**Closed by Stypox** 2020-05-03 08:19 UTC
