### ISSUE TITLE
Not Playing any video 

### ISSUE THREAD

**Issue by dhananceo** [TeamNewPipe/NewPipe#3971] opened 2020-07-28 06:17 UTC
![Screenshot_2020-07-28-11-44-24-287_org schabi newpipe](https://user-images.githubusercontent.com/66171961/88626334-1b671b00-d0c8-11ea-94f0-f75bbe12785a.jpg)

Not Playing any video

**Comment by wb9688** [comment] 2020-07-28 06:22
Duplicate of #3951

**Closed by wb9688** 2020-07-28 06:22 UTC
Labels: bug
