### ISSUE TITLE
Add support for /c/ YouTube Channel links

### ISSUE THREAD

**Issue by Gymcap** [TeamNewPipe/NewPipe#2949] opened 2020-01-11 15:19 UTC
YouTube now allows channel links written with /c/ instead of /channel/. I'm not sure if this is new or not, but NewPipe can't currently open it.

Example: https://YouTube.com/c/AveragePixel

**Comment by B0pol** [comment] 2020-01-14 17:33
NewPipe handles it actually, share to NewPipe the link above and it works
But yeah, if you just click on it without sharing to NewPipe it doesn't work.
And this is duplicate of #2425

**Comment by B0pol** [comment] 2020-01-14 17:34
Duplicate of #2425

**Closed** 2020-01-14 18:30 UTC
Labels: bug, requires extractor change, youtube
