### ISSUE TITLE
Set thumbnail as default art cover l for music downloads 

### ISSUE THREAD

**Issue by cityji** [TeamNewPipe/NewPipe#8324] opened 2022-05-01 09:30 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

I am in love with this project 😺 it also has built in download btn to download in many resolutions,

However there's one issue ive faced so far (not a issue exactly)
When i downloaded in mp3 / ogg quality the audio seems lacking metadata it's okay but it will be nice if we can reuse that fetched thumbnail

As a. Cover image to that downloaded music  **no extra resources are needed**  the external youtube video downloaders had this feature to include metadata also

It is nothing but a humble request,  

### Why do you want this feature?

The external youtube video downloaders had this feature to include metadata also on downloading audio from YouTube

I want that feature to be there because it gets so hard to identify or find a particular audio file in audio player :(

Also the video thumbnail downloaded / fetched on app get's wasted, I know it doesn't take more than 100-300kib to download the thumbnail but we can reuse that downloaded thumbnail in audio cover image 

Also it is really hard and manual process to add metadata or cover images to be added later (eg. After downloading a song)

**Comment by SameenAhnaf** [comment] 2022-05-01 09:49
Duplicate of #4341

**Closed** 2022-05-01 11:18 UTC
Labels: enhancement
