### ISSUE TITLE
Video playback halts for no reason

### ISSUE THREAD

**Issue by eternal-sorrow** [TeamNewPipe/NewPipe#4297] opened 2020-09-20 11:48 UTC
### Version
- 0.19.8

### Steps to reproduce the bug
1. Open any video longer than 10 minutes
2. Watch it at least for 2/3

### Expected behavior
Video playing smoothly till the end.

### Actual behaviour
Video pauses periodically for a couple seconds and then resumes playback for a couple seconds. And repeats this untill the end.  It's almost like it's buffering due to not enough connection throughput, but I have no problem playing the same video with the same resolution  in the browser. Also, I tried decreasing resolution in NewPipe, it didn't help. Also, when I start playback or when I switch resolution, it's buffering with a rotating indicator in the middle of the screen but when it starts halting, there's no indicator.

**Comment by Stypox** [comment] 2020-09-20 11:58
Could you check if this is an issue in [this apk](https://github.com/TeamNewPipe/NewPipe/files/5250142/app-debug.zip) (which is basically a preview of 0.20.0)?

**Comment by eternal-sorrow** [comment] 2020-09-26 13:16
I won't install any `.apk`s not from the fdroid.

**Comment by opusforlife2** [comment] 2020-09-26 13:19
Well, then you'll need to wait for 0.20.0 to release first. After updating to that, make sure you get back to us, whether the issue is fixed or not. Don't leave us hanging. ;)

**Comment by drmalesh** [comment] 2020-10-03 02:39
With the stable release, I have the same issue playing Costa Rica 4K on Android TV with quad-core SoC (2019 model MTK chipset). At first, I thought it was due to hardware but the video is smooth beside those stops. Smart Youtube TV and Google Youtube app play the video in 4K with HDR without hiccups.

Tried 0.20.0 RC6 and it is fixed now. Plays smoothly. 

Wish there was a dedicated ATV version of NewPipe tho :)

**Comment by opusforlife2** [comment] 2020-10-10 14:52
@eternal-sorrow Tried the new release yet?

**Comment by opusforlife2** [comment] 2020-10-10 21:12
Closing until the user replies.

**Comment by eternal-sorrow** [comment] 2020-10-11 02:54
I tried it, and it doesn't seem to have this issue. But I can't be sure because of random nature of it.

**Comment by opusforlife2** [comment] 2020-10-11 05:17
@eternal-sorrow Please make sure you get back to us in case you encounter it again.

**Comment by eternal-sorrow** [comment] 2020-10-18 12:43
@opusforlife2, after some time I can say that the issue persists on version 0.20.0.

It's can be difficult to spot because it's random (and It happens quite rarely), and also it's hard to differentiate it from the legitimate buffering on bad connection.

**Comment by opusforlife2** [comment] 2020-10-18 12:57
Alright. Reopening. Could you read through some of the other issues we have about playback halting? There are a few and yours may overlap with one or more.

**Comment by eternal-sorrow** [comment] 2020-10-18 13:19
This on looks similar: https://github.com/TeamNewPipe/NewPipe/issues/4209

**Comment by opusforlife2** [comment] 2020-10-18 14:39
> Video pauses periodically for a couple seconds and then resumes playback for a couple seconds.

This sounds exactly the same as
> If the bug happens, the video will stutter every 1-2s like there would be a buffering issue

to me. So let's close this as a duplicate of #4209. Thanks for checking!

**Closed by opusforlife2** 2020-10-18 14:39 UTC
Labels: bug, more info needed, player
