### ISSUE TITLE
3 problems

### ISSUE THREAD

**Issue by kafkagrey** [TeamNewPipe/NewPipe#1940] opened 2018-12-12 10:35 UTC
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

In the app I found 3 problems
1: watching videos in playlists in the background sometimes the music stops and I have to start it again or even worse ending a song all the ones after it all skips and no audio part
2: occasionally, after a few minutes of use, the app no longer connects to the internet and does not charge anything
3: exiting the app with the active video player does not activate the musical background
Thanks for reading, I love this app

**Comment by copoer** [comment] 2018-12-12 14:37
[Guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md)
- Please only add one issue at a time. Do not put multiple issues into one thread.

Also #1737 is simar to your first issue.

**Comment by DMSalesman** [comment] 2018-12-22 14:31
I can reproduce your second issue.

**Comment by Stypox** [comment] 2019-08-28 21:29
1. duplicate of #1188
2. probably a problem with vpn, see #1119. If it is not, please open a new issue, as keeping three problems toghether makes it not convenient (see guidelines)
3. There is a switch in the settings: `Settings -> Video & audio -> Minimize on app switch`

**Closed by Stypox** 2019-08-28 21:29 UTC
