### ISSUE TITLE
Removing Downloads

### ISSUE THREAD

**Issue by awarakhaki** [TeamNewPipe/NewPipe#7646] opened 2022-01-11 14:31 UTC
When we attach a file to a download. If we pause the download and close the application, it automatically removes the download.
In simple words. When we exit from app So It's removing all incomplete, paused or error Downloads.

**Comment by SameenAhnaf** [comment] 2022-01-11 18:20
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7059. Also, please fill in the template properly.

**Closed** 2022-01-13 18:52 UTC
Labels: template-missing
