### ISSUE TITLE
"could not get any stream" could not parse website

### ISSUE THREAD

**Issue by SmoothJaz** [TeamNewPipe/NewPipe#4034] opened 2020-07-31 23:23 UTC
_As a pre-warning, Ive never submitted anything through github and know pretty much nothing about coding, bit I've looked for this issue and I don't think I can find it anywhere (so it could possibly be a personal issue then maybe) be gentle with me <3_

### Version
Newpipe 0.19.8
-

### Steps to reproduce the bug

1. Go to any video, for me it's most consistent when selecting a video from the "feed" part of the subscription tab. For myself the video I recognised it on was [this video](https://www.youtube.com/watch?v=sAf7SbvTlIY) 
But I've noticed it on many others also
2. Press on the video to go to it's page where comments and whatnot can be seen
3. Error appears here, preview thumbnail doesn't load, sometimes comments do but then it crashes shortly after

### Expected behavior
Video thumbnail would load and the video would become playable

### Actual behaviour
Crashes! Also worth noting that the video can't be played in the background or as a popup either.
### Screenshots/Screen recordings

Screen shot just before the crash report
![Screenshot_20200801-092102_NewPipe](https://user-images.githubusercontent.com/69060834/89087697-7191d200-d3d8-11ea-9c5c-a6def9e97051.jpg)

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=sAf7SbvTlIY
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_AU
* __Service:__ YouTube
* __Version:__ 0.19.8
* __OS:__ Linux samsung/d2sxx/d2s:10/QP1A.190711.020/N975FXXU4CTE9:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by SmoothJaz** [comment] 2020-07-31 23:24
Let me know if I didn't provide any information or did something wrong, thanks 😁

**Comment by Stypox** [comment] 2020-08-04 11:42
Thank you for the detailed bug report. This is a duplicate of #3992

**Closed by Stypox** 2020-08-04 11:42 UTC
Labels: bug
