### ISSUE TITLE
[BUG] video wont autoplay

### ISSUE THREAD

**Issue by TheSilencedOne** [TeamNewPipe/NewPipe#6325] opened 2021-05-18 05:24 UTC
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

This depends on your autoplay setting

If autoplay is on:
click on a video it wont autostart you have to click play again

If autoplay is off:
Click on video, click play, it wont start you have to click play again

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/78061111/118594570-b0322680-b777-11eb-9133-c3e8962cc5de.mp4

### Device info

 - Android version/Custom ROM version: FireOS 6.3.1.5 | Android 7.1.2
 - Device model: Amazon Fire 8 (2018)

**Comment by SameenAhnaf** [comment] 2021-05-18 05:39
Duplicate of #6179. Also, PR is made.

**Comment by mhmdanas** [comment] 2021-05-18 10:36
Duplicate of #6179.

**Closed by mhmdanas** 2021-05-18 10:36 UTC
Labels: bug
