### ISSUE TITLE
[FR][Multiservice] play local files

### ISSUE THREAD

**Issue by ildar** [TeamNewPipe/NewPipe#1052] opened 2018-01-31 01:25 UTC
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

NP grown mature and cool ))
I think it's time to play local (video) files.
Probably Multi Service initiative should fit just fine as an implementation base for it.

**Comment by speednroll** [comment] 2018-01-31 01:27
I'm not sure but I think that was also requested earlier

**Comment by ildar** [comment] 2018-01-31 01:40
I seeked and couldn't find. Sorry if dup

**Comment by ildar** [comment] 2018-12-02 05:38
Up.
Sorry for that but it's important

**Comment by ildar** [comment] 2019-03-01 06:39
Should this FR stay here or move to
https://github.com/TeamNewPipe/NewPipeExtractor ?

**Comment by Stypox** [comment] 2019-06-23 19:41
@ildar it has nothing to do with the extractor

**Comment by Stypox** [comment] 2019-06-23 19:42
Also see #478

**Comment by mhmdanas** [comment] 2021-06-13 22:15
Duplicate of #478.

**Closed by mhmdanas** 2021-06-13 22:15 UTC
Labels: enhancement
