### ISSUE TITLE
requested stream failure

### ISSUE THREAD

**Issue by toumbo** [TeamNewPipe/NewPipe#6243] opened 2021-05-06 01:50 UTC
## Exception
* __User Action:__ requested stream
* __Request:__ https://m.soundcloud.com/papercutgr/better-skies-ft-efi-theologou opened with background_player
* __Content Country:__ GR
* __Content Language:__ el-GR
* __App Language:__ el_GR
* __Service:__ SoundCloud
* __Version:__ 0.21.2
* __OS:__ Linux Blackview/BV5500Plus_EEA/BV5500Plus:10/QP1A.190711.020/1599031515:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not resolve id with embedded player. ClientId not extracted
	at org.schabi.newpipe.extractor.services.soundcloud.linkHandler.SoundcloudStreamLinkHandlerFactory.getId(SoundcloudStreamLinkHandlerFactory.java:37)
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:77)
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:58)
	at org.schabi.newpipe.extractor.StreamingService.getStreamExtractor(StreamingService.java:262)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4799)
	at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:692)
	at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:664)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not resolve id with embedded player. ClientId not extracted
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveIdWithWidgetApi(SoundcloudParsingHelper.java:173)
	at org.schabi.newpipe.extractor.services.soundcloud.linkHandler.SoundcloudStreamLinkHandlerFactory.getId(SoundcloudStreamLinkHandlerFactory.java:35)
	... 30 more
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get id
	at org.schabi.newpipe.extractor.utils.JsonUtils.getValue(JsonUtils.java:33)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveIdWithWidgetApi(SoundcloudParsingHelper.java:169)
	... 31 more

```
</details>
<hr>

**Comment by TiA4f8R** [comment] 2021-05-06 17:04
The extraction fails because the resolve endpoint of SoundCloud doesn't return the data if the URL has the mobile part (`m.`) (empty JSON response), even on the mobile internal API. If you remove the `m.` part, the extraction will work. This will be easy to fix.

Also, don't remove the template the next time you open an issue. There are good reasons to keep it. Please edit your issue and fill the template properly.

**Comment by TiA4f8R** [comment] 2021-05-14 10:19
Closing as a duplicate of #6284, which follows the template and is more understandable.

**Closed by TiA4f8R** 2021-05-14 10:19 UTC
Labels: bug, requires extractor change, soundcloud, user-ignored-template-instructions
