### ISSUE TITLE
Option to Export Playlists seperately

### ISSUE THREAD

**Issue by LostWanita21** [TeamNewPipe/NewPipe#5106] opened 2020-12-06 01:25 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) 
- [X ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ X] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I'm thinking it could go either in the main content page under settings, or a sub option could be on the bookmarked playlists page, like how subscriptions are handled where the export/import is on its page.

Import Playlist:
Overwrite your current saved Playlists

Export Playlist:
Export Saved Playlists to a file

I don't know how Newpipe saves playlists, but one suggestion u found mentioned saving those as a .CSV file, which could be good as a format but alternative formats are also welcome.

#### How will you/everyone benefit from this feature?
Convince us! How does it change your NewPipe experience and/or your life?
The better this paragraph is, the more likely a developer will think about working on it.

I feel this could be useful for two reasons, the first being backing up playlists to another Newpipe instance without interfering with existing settings with the seperate instance, eg: sending a playlist to a friend who also uses Newpipe.

The second reason could be helpful for similar, non mobile services like Freetube, where being able to import a Newpipe playlist into a Freetube or Yotter instance, though this depends on how they save playlists compared to how Newpipe saves it.

**Comment by mhmdanas** [comment] 2020-12-06 09:10
I believe this is a duplicate of #1788. If you have something else in mind, please tell me. Thanks!

**Closed by mhmdanas** 2020-12-06 09:10 UTC
Labels: enhancement
