### ISSUE TITLE
AV1 support

### ISSUE THREAD

**Issue by wqsrz** [TeamNewPipe/NewPipe#4361] opened 2020-10-01 05:30 UTC
#### How will you/everyone benefit from this feature?

Please add an option to download videos in AV1 if available. Thanks

**Comment by Stypox** [comment] 2020-10-01 05:36
*Please **follow the issue template** when creating an issue, don't just delete everything!* Anyway, duplicate of #2849

**Closed** 2020-10-01 05:36 UTC
Labels: downloader, enhancement, requires extractor change
