### ISSUE TITLE
App insta crashes when trying to import subs csv

### ISSUE THREAD

**Issue by Asrour494** [TeamNewPipe/NewPipe#8516] opened 2022-06-15 21:13 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Open app
2. Have subscriptions csv from YouTube
3. Follow steps on app to import subscriptions
4. app crashes as soon as I accept the "network intensive-ness"

### Expected behavior

App should import subs

### Actual behavior

App crashes

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@d0834d with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{a9ab4a6 22077:org.schabi.newpipe/u0a295} (pid=22077, uid=10295) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4661)
	at android.app.ActivityThread.access$2000(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2095)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{a9ab4a6 22077:org.schabi.newpipe/u0a295} (pid=22077, uid=10295) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5850)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6976)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3336)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1675)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1622)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4643)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:611)
	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:235)
	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:125)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6002)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2440)


```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 5a

**Comment by litetex** [comment] 2022-06-19 14:14
Duplicate of #7411 

Anyway thanks for filling in a detailed report :)

**Closed by litetex** 2022-06-19 14:14 UTC
Labels: bug

**Comment by Asrour494** [comment] 2022-06-19 17:26
Sorry! my first time using github, couldn't figure out the search function.
Thank you, I will try the workarounds here.
