### ISSUE TITLE
Android TV Option that triggers a different UI

### ISSUE THREAD

**Issue by christopher-wilson** [TeamNewPipe/NewPipe#5398] opened 2021-01-12 17:26 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The problem is that there are a lot of UI issues when used on a television, and just trying to force a touch-based phone UI to work on a television seems counterproductive. We all know how it should look and operate as there are several examples of similar apps without the same usability problems.

#### Additional context

If this were accomplished, then we could actually do a community-based redesign for the TV layout, which I think it really needs. Aside from time and labor, I don't see a reason why this shouldn't work as well as YouTube does.

#### How will you/everyone benefit from this feature?

NewPipe isn't unusable, but it is unpleasant to use on an Android TV compared to YouTube, Plex, et al. Since we know how it should look and operate intuitively, having the option to toggle on a better interface should allow developers to iterate on it more quickly without impacting the design of the mobile layout.

**Comment by AlexN1997** [comment] 2021-01-14 17:22
[Almost the same enchantment that I wanted](https://github.com/TeamNewPipe/NewPipe/issues/5322)

**Comment by Stypox** [comment] 2021-01-14 20:22
Duplicate of #5322

**Closed by Stypox** 2021-01-14 20:22 UTC
Labels: Android TV, enhancement
