### ISSUE TITLE
Option to always open the video maximized (without comments)

### ISSUE THREAD

**Issue by etofi** [TeamNewPipe/NewPipe#5565] opened 2021-02-12 18:37 UTC
I use NewPipe on my FireTV. When I open videos from my favorites they are always minimized and opened with the comments.
It would be great if you could turn on an option that the videos are always opened automatically maximized.

**Comment by mhmdanas** [comment] 2021-02-13 12:53
This is a duplicate of #4387. Also, please don't remove the template when opening an issue. Thanks!

**Closed by mhmdanas** 2021-02-13 12:53 UTC
Labels: enhancement
