### ISSUE TITLE
Skipping to timestamps switches playback mode

### ISSUE THREAD

**Issue by christopherlam888** [TeamNewPipe/NewPipe#8587] opened 2022-07-07 04:27 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Play a video with timestamps in the description either in the default mode or in background mode.
2. Press a timestamp set in the description.
3. The playback mode switches to popup mode in addition to going to the given time.

### Expected behavior

The expectation is that the video remains in the selected playback mode.

### Actual behavior

The actual behaviour is that the video switches to popup mode, which is very inconvenient when a specific playback mode is preferred and thus must be switched to again.

### Affected Android/Custom ROM version

Android 12

### Affected device model

Google Pixel 6

**Comment by SameenAhnaf** [comment] 2022-07-07 09:10
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/4241

**Comment by AudricV** [comment] 2022-07-07 10:01
> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

Duplicate of #4241 as stated above. Please search (better, with different keywords?) for duplicates the next time you want to open an issue. Thank you.

**Closed by AudricV** 2022-07-07 10:01 UTC
Labels: bug
