### ISSUE TITLE
Can't play restricted videos

### ISSUE THREAD

**Issue by AleRicco03** [TeamNewPipe/NewPipe#6612] opened 2021-07-05 14:26 UTC
I have the latest version of the app
I enabled the option to show the restricted contents
Despite that, still can't play videos with under 18 restrictions
https://www.youtube.com/watch?v=8SXEoVLUP44&ab_channel=TeduaTedua
This is one of the videos that i can't watch on NewPipe

**Comment by SameenAhnaf** [comment] 2021-07-05 15:11
Did you turn on "Show "Age-restricred" Content" from "Settings">"Content"? Keep both settings as shown in the screenshot. The video opens as expected on my device.
![IMG_20210705_210745](https://user-images.githubusercontent.com/79245641/124491766-71166e00-ddd5-11eb-8075-c851d6d119ac.jpg)

**Comment by AleRicco03** [comment] 2021-07-05 16:03
> Did you turn on "Show "Age-restricred" Content" from "Settings">"Content"? Keep both settings as shown in the screenshot. The video opens as expected on my device.
> ![IMG_20210705_210745](https://user-images.githubusercontent.com/79245641/124491766-71166e00-ddd5-11eb-8075-c851d6d119ac.jpg)

The settings I have it like the ones in the picture

**Comment by AleRicco03** [comment] 2021-07-05 16:05
"Show age restricted content" is on
Turn on YouTube "Restricted Mode" is off
And somehow i can't reproduce restricted videos

**Comment by TiA4f8R** [comment] 2021-07-05 16:22
Duplicate of #6403. It will be fixed with the next release. Also, don't remove the template when opening an issue. Thank you.

**Closed by TiA4f8R** 2021-07-05 16:22 UTC
Labels: bug
