### ISSUE TITLE
Suggestion for improvement: download already from the list (long click)

### ISSUE THREAD

**Issue by kreorei** [TeamNewPipe/NewPipe#6960] opened 2021-08-23 18:08 UTC
Hi,

I always like to download a lot of files. And then look at them offline.

When I do a search, the search results come up. There you should be able to either long click on each file you want to have to download it. Here see the menu that currently exists. Just extend that.

Alternatively, it would be even better if you could mark many of the search suggestions. And then could set everything to download.

**Comment by SameenAhnaf** [comment] 2021-08-24 06:04
Duplicate of #5482. Also, please fill in the template properly.

**Closed** 2021-08-24 14:12 UTC
Labels: enhancement, user-ignored-template-instructions
