### ISSUE TITLE
Update Subscription manager

### ISSUE THREAD

**Issue by Ksanbah** [TeamNewPipe/NewPipe#6845] opened 2021-08-04 14:51 UTC
#6843 
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to 'Subscription'
2. Press on 'YouTube'
3. Follow the instructions of 'Import YouTube Subscription'
4. Notice that the Subscription file format is now .csv not .json 
5. Converting the file from csv to json does not help. 
6. Please update New Pipe for this issue

### Actual behavior
What happens with the steps given above? 
The app can't process csv or "csv to json" converted file.

### Expected behavior
What do I expect to happen? 
To work normally ike it did with the previous json format.

### Screenshots/Screen recordings
Screen record sample

https://user-images.githubusercontent.com/51513596/128202473-fd1c4707-36ae-4c46-aac5-5b5df95a190d.mp4

### Device info

 - Android version/Custom ROM version: ColorOS 11 (Android 11 skin) 
 - Device model: Oppo Reno 3 Pro

**Comment by mhmdanas** [comment] 2021-08-04 16:46
Duplicate of #6757.

**Closed by mhmdanas** 2021-08-04 16:46 UTC
Labels: bug
