### ISSUE TITLE
Android TV Playback Speed Crash

### ISSUE THREAD

**Issue by zubayy** [TeamNewPipe/NewPipe#7034] opened 2021-08-31 14:40 UTC
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any video on Newpipe app on Android TV
2. Try to change playback speed
3. The app crashes with "unrecoverable playback error"

### Actual behavior

It always crashes with "unrecoverable playback error"

### Expected behavior

It should not crash when trying to change playback speed
*Changing playback speed on TVs has been broken for several months, the crash is not caused by any changes made recently.

### Screenshots/Screen recordings

NA sorry once again, getting logs is kinda a pain on Android TVs.

### Device info

 - Android version/Custom ROM version: Android Pie
 - Device model: Sony, Samsung (I think it affects Android TVs in general)

**Comment by mhmdanas** [comment] 2021-08-31 14:43
Probably a duplicate of #6392.

**Closed by mhmdanas** 2021-08-31 14:43 UTC
Labels: bug

**Comment by zubayy** [comment] 2021-08-31 14:58
Hey sorry @mhmdanas but when I searched the issues using the Android TV label the issue didn't appear, will search manually next time but I legit didn't know this issue existed.
