### ISSUE TITLE
Wearable notification frequency

### ISSUE THREAD

**Issue by Siress** [TeamNewPipe/NewPipe#1860] opened 2018-10-31 14:19 UTC
WhenNewPipe is in the notification bar, it pushes a notification alert to my smart watch at a high frequency (2-4 Hz) regardless of if anything is playing or not. This behavior has been present for at least the past 5 versions.

Running Android 7.1.2 with NP 0.14.2.

**Comment by theScrabi** [comment] 2018-11-04 18:34
Hm we added a notification system for bluetooth devices. We might need to check this again. What device do you own?

**Comment by Siress** [comment] 2018-11-05 00:09
Garmin Vivoactive HR.

(Thank you for the excellent app!)

**Comment by Stypox** [comment] 2019-08-28 20:43
Duplicate of #1574

**Closed by Stypox** 2019-08-28 20:43 UTC
