### ISSUE TITLE
Guru Mediation error after playing Videos

### ISSUE THREAD

**Issue by whywhywhyHah** [TeamNewPipe/NewPipe#2787] opened 2019-11-06 12:40 UTC
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [x ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hello, after some played videos im getting this error:
`## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=TqK9lG4MPqY
* __Content Language:__ DE
* __Service:__ YouTube
* __Version:__ 0.17.4
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerConfig(YoutubeStreamExtractor.java:660)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:638)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>
`

Already installed the latest and greatest. Before that error occurs, there was a recaptcha thing to solve. This app is routed over orbot.

**Comment by lulucca12** [comment] 2019-11-08 01:09
I am having the same issue, also routed over orbot

**Comment by lulucca12** [comment] 2019-11-09 19:20
I think this is due to sometimes redirecting to a page wich says Invalid response recieved.

**Comment by whywhywhyHah** [comment] 2019-11-12 15:42
> I think this is due to sometimes redirecting to a page wich says Invalid response recieved.

did you find a workaround

**Comment by lulucca12** [comment] 2019-11-13 10:31
Not really, i just reload the tor identity until i can open the video on a browser and pass the captcha.

**Comment by whywhywhyHah** [comment] 2019-11-13 12:02
> Not really, i just reload the tor identity until i can open the video on a browser and pass the captcha.

thank you i will test it

**Comment by Z3ROGRAV1TYx** [comment] 2019-11-15 14:33
Same issue,  not using tor

**Comment by Emonshr** [comment] 2019-11-26 13:29
Facing same. Can't figure out this problem 😷

**Comment by 7FM** [comment] 2019-12-21 13:59
I think it is related to: https://github.com/TeamNewPipe/NewPipeExtractor/issues/197

**Comment by Stypox** [comment] 2020-08-14 17:13
Closing since this error is caused by code about pages, that has since been changed a lot, so this either is not happening anymore, or is happening in another way, so the provided error is not useful anymore

**Closed by Stypox** 2020-08-14 17:13 UTC
Labels: bug, youtube
