### ISSUE TITLE
Phone starts to show lock screen and is catched in a loop on certain videos

### ISSUE THREAD

**Issue by eti1988** [TeamNewPipe/NewPipe#6279] opened 2021-05-13 10:30 UTC
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to 'https://www.youtube.com/watch?v=N5V-FVK2rAA&ab_channel=PlanetaDance' (example video; happens on other videos as well)

### Actual behaviour

Phone starts to show the lock screen, where I have to type my pin in and is catched in a loop (if I type in the pin, phone turns black and shows the lock screen again). The music from the video above is playing normally in the background. Only restarting the phone helps.

### Expected behavior
Playing the video normally without showing the lock screen and/or be catched in a loop.

### Device info

 - Android version/Custom ROM version: Android version 10
 - Device model: Sony Xperia XZ2 (Model: H8216)

**Comment by TiA4f8R** [comment] 2021-05-13 18:54
What you refer seems to be a crash of the System UI. I think it's a duplicate of #4638. Check the issue and the linked PR for more explanations.

As a workaround, you can disable the notification thumbnail by toogle off the `Show thumbnail notification` option located in Settings, Notification. Thank you.

**Closed by TiA4f8R** 2021-05-13 18:54 UTC
Labels: bug

**Comment by eti1988** [comment] 2021-05-13 19:34
Hey! Thanks! It works!
