### ISSUE TITLE
[Feature Request] Option to hide live/upcoming videos

### ISSUE THREAD

**Issue by lonix1** [TeamNewPipe/NewPipe#6445] opened 2021-06-07 08:47 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

The videos list shows "live" and "upcoming" items at the top. I'm sure some people like that, but I find them of no use, and frustrating when I open them only to discover an error.

It would be nice to have a feature to hide those items.

It could be disabled by default, for backwards compatibility.

#### Is your feature request related to a problem? Please describe it
No, an UX improvement

#### Additional context

no

#### How will you/everyone benefit from this feature?

Reduce clutter, prevent me from accidentally clicking on videos that cannot be played. On large feeds there can be dozens of these useless videos, it gets messy.

**Comment by opusforlife2** [comment] 2021-06-07 16:32
That's true. Live streams in a feed are only useful if the feed has been recently updated. Maybe there should be a section labelled "Live streams" in every feed where all the _currently live_ streams of all channels in that channel group show up, followed by a "Feed" section where all the normal videos are listed.

Swiping down or tapping on Refresh should refresh the "Feed" section like it does now, but the "Live streams" section should always be updated every time that Feed is opened. Or at least every time Newpipe is restarted.

**Comment by mhmdanas** [comment] 2021-06-22 23:32
Duplicate of #5875.

**Closed by mhmdanas** 2021-06-22 23:32 UTC
Labels: enhancement, feed
