### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by ilhanyurek** [TeamNewPipe/NewPipe#6119] opened 2021-04-19 23:56 UTC
It would be nice if there is a theme option that we can make the top red panel black.

**Comment by TobiGr** [comment] 2021-04-20 08:27
NewPipe has three themes: light, dark and black. You can choose you preferred one on the Appearance settings. Support for individual themes is out of scope for now.

**Comment by ilhanyurek** [comment] 2021-04-20 13:35
Complete black like mod apks

**Comment by mhmdanas** [comment] 2021-04-21 10:12
Duplicate of #4148.

**Closed by mhmdanas** 2021-04-21 10:12 UTC
Labels: GUI
