### ISSUE TITLE
Enqueue option is not available if the background playlist is empty

### ISSUE THREAD

**Issue by HenriDellal** [TeamNewPipe/NewPipe#4981] opened 2020-11-23 16:01 UTC
### Checklist

- [x] I am using the latest version - 0.20.4
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Long-press on History item, you'll get a context menu with "Enqueue" option missing
2. Press "Start playing in background"
3. Repeat step 1, you'll see "Enqueue" as the first option

### Actual behaviour

Read previous section, it's self-descriptive

### Expected behavior

Long-press on History item brings a context menu with Enqueue option

### Device info

 - Android version/Custom ROM version: 9.0
 - Device model: Samsung Galaxy A10

**Comment by vkay94** [comment] 2020-11-23 16:43
This behavior is expected as it is. If there is nothing in the queue (= background playlist is empty), the action "Start in background" and "Enqueue" would be equal and therefore unnecessary. 
Btw, there is no scenario where the background playlist is empty because the background player is closing as soon as  you remove all streams.

**Comment by HenriDellal** [comment] 2020-11-23 16:56
@vkay94 there is a difference. "Enqueue" adds a single video in the play queue, "start in background" puts entire history list in the play queue.

**Comment by vkay94** [comment] 2020-11-23 17:06
Ah okay, that's what you mean. The title is misleading and "Expected behavior" section isn't explaining that you want enqueue a single item instead of all ;)

**Comment by Stypox** [comment] 2021-01-15 19:01
Yeah, let's keep everything in #4805

**Closed by Stypox** 2021-01-15 19:01 UTC
Labels: bug
