### ISSUE TITLE
Videos can be downloaded at 720p

### ISSUE THREAD

**Issue by OffifialMITX** [TeamNewPipe/NewPipe#2674] opened 2019-09-29 20:38 UTC
[Linus Tech Tips](https://www.youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw)

Since two weeks or so I can't download any videos from that channel anymore. The error just says "Not found"

**Comment by gkeegan** [comment] 2019-09-29 21:07
I can download their videos just fine. What version of NP are you on, and what is your location?

**Comment by OffifialMITX** [comment] 2019-09-29 21:09
@gkeegan I'm on F-Droid's latest 0.17.1 build and am located in Germany.

**Comment by gkeegan** [comment] 2019-09-29 21:15
Ah there is a problem. 1080p downloads fine but 720p doesn't. Confirmed issue.

**Comment by omarroth** [comment] 2019-09-29 21:17
Testing a few videos I can also confirm. Likely related to omarroth/invidious#750.

**Comment by Aimmig** [comment] 2019-10-03 09:25
I'm having a similar issue: Using MPEG-4 720p quality doesn't play some videos (all other qualities work). Switching to WebM Video-Format everything works just fine

**Comment by sohmc** [comment] 2019-10-06 15:00
I can confirm the same problem.  WebM works fine.

**Comment by AnXh3L0** [comment] 2019-10-06 21:31
Chiming in to confirm I have the same issue.

**Comment by OffifialMITX** [comment] 2019-10-09 21:12
Ok, so since today I can download any resolution and framerate but it's in a format that VLC (on my phone) can barely handle it, I can pretty much only play videos with hardware accleration disabled and I can't do any skipping or else it starts to glitch out. Anyone experiencing something similar?

**Comment by OffifialMITX** [comment] 2019-10-09 23:08
Ok, disregard that, apparently it's just due to my phone not handling WebM properly.

**Comment by Stypox** [comment] 2020-04-27 07:14
Duplicate of #2415

**Closed by Stypox** 2020-04-27 07:14 UTC
Labels: bug, requires extractor change, youtube
