### ISSUE TITLE
[Request] add options to embed subtitles

### ISSUE THREAD

**Issue by jefferson018200306** [TeamNewPipe/NewPipe#5366] opened 2021-01-07 15:22 UTC
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
It would be great if we can have an option to embed subtitles rather than downloading it separately. So in that way, we can enjoy the downloaded videos with subtitles embedded inside of the video file.

#### Is your feature request related to a problem? Please describe it
I have a problem of making downloaded subtitle files to work on famous media player. Because media player can automatically add the subtitles if also the subtitle file has the same name of the video file. And I'm tired of doing those things repeatedly, and now I just want to embed the subtitle file in the video file itself.

#### How will you/everyone benefit from this feature?

This feature will help us not to get tired of doing repeating things on some media players rules. Thank you, and please guide me whenever you need more details about this feature

**Comment by shivasagarrao** [comment] 2021-01-09 21:14
Duplicate of [#4426](https://github.com/TeamNewPipe/NewPipe/issues/4426)

**Closed** 2021-01-09 21:28 UTC
Labels: enhancement
