### ISSUE TITLE
Sorting videos by duration in a playlist

### ISSUE THREAD

**Issue by Aj8787** [TeamNewPipe/NewPipe#8522] opened 2022-06-19 03:33 UTC
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

In a playlist, please add option to sort videos by duration (and name etc.).

### Why do you want this feature?

This will help user finish shorter once quickly based on their occupancy.

It's difficult to scroll back and forth to find the short duration videos when you have more videos in a playlist.

**Comment by litetex** [comment] 2022-06-19 14:21
Duplicate of #3263

**Closed by litetex** 2022-06-19 14:21 UTC
Labels: enhancement
